### ISSUE TITLE
[Bug]: Loki output don't include metric name as a label

### ISSUE THREAD

**Issue by garciarodrigor** [influxdata/telegraf#10000]
### Relevent telegraf.conf

```toml
# Global tags can be specified here in key="value" format.
[global_tags]
  dc = "local" # will tag all metrics with dc=local

# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "s"
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false


# -- OUTPUT PLUGINS -- #
[[outputs.loki]]
  ## The domain of Loki
  domain = "http://loki:3100"

# -- INPUT PLUGINS -- #
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states
  report_active = false
```

### System info

Telegraf 1.20.2, Writing to Loki 2.3

### Steps to reproduce

1. Check Loki stored metrics to see that the metric name is not included in the labels 

### Expected behavior

In order to improve queries performance in Loki, we need to include the metric name as a label, I added a fix here to add this info as a label with the name "__name" https://github.com/garciarodrigor/telegraf/commit/ca8602a46118aa9feec766d8bdf5d4095d9d9729

### Actual behavior

The metric name is missing in Loki, so we can't filter by it
