### ISSUE TITLE
RabbitMQ collection without queue data

### ISSUE THREAD

**Issue by nickjones** [influxdata/telegraf#1000]
I operate a RabbitMQ cluster with a very high number of anonymous queues created (clients connect with anonymous queues, do a task, publish something, and disconnect).  Others connect and subscribe to a topic on an anonymous queue for a few hours.  Telegraf currently always collects queue metrics but in this case it creates excessive numbers of series in InfluxDB; we have over 7M series with a retention period of 14d in this db.

I propose adding configuration options to selectively choose which portions of the available JSON to publish to the output plugins.  Preferably, the data wouldn't be requested to avoid the additional load on the RabbitMQ hosts either.

**Comment by sparrc** [comment]
that makes sense, so you would like something like this in the config?

```toml
[[inputs.rabbitmq]]
  url = "http://localhost:15672" # required
  # name = "rmq-server-1" # optional tag
  # username = "guest"
  # password = "guest"
  ## A list of nodes to pull metrics about. If not specified, metrics for
  ## all nodes are gathered.
  # nodes = ["rabbit@node1", "rabbit@node2"]
  ## Select which queues to collect metrics on
  queues = ["important_queue1", ... ]
  ## Turn off queue metric collection entirely
  dont_collect_queues = false
```
