### ISSUE TITLE
Intel RDT plugin metrics timestamp issue

### ISSUE THREAD

**Issue by KubaTrojan** [influxdata/telegraf#10025]
### Relevent telegraf.conf

```toml
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.intel_rdt]]
   sampling_interval = 5
   processes = ["top"]
```

### System info

Telegraf v1.20.3, Ubuntu 18.04

### Steps to reproduce

1. Change your local timezone to different than UTC (e.g. "export TZ=America/New_York")
2. Run Telegraf with Intel RDT plugin enabled (and another plugin to compare). Any valid configuration.
3. Gather some metrics. Note the measurements timestamps.
4. Compare timestamps from the RDT plugin to Telegraf agent time or another plugin timestamp.

### Expected behavior

The Telegraf Intel RDT plugin should set correct time values to gathered measurements. 

### Actual behavior

The RDT plugin provides incorrect timestamp values if the local timezone is not set to UTC.

Example:

Local Timezone (`TZ` variable) configured: **America/New_York**
Command `date` output: **Fri Oct 29 09:23:00 EDT 2021**

Telegraf agent time: **2021-10-29T13:23:00Z** 

Timestamps from InfluxDB:
CPU plugin metric time: **2021-10-29T13:23:00.000Z**
RDT plugin metric time: **2021-10-29T09:23:00.000Z**

It seems that the RDT plugin takes local time not paying attention to the timezone. (Assuming UTC).
