### ISSUE TITLE
Graylog output plugin: `full_message` is handled like a custom field

### ISSUE THREAD

**Issue by alespour** [influxdata/telegraf#10024]
### Relevent telegraf.conf

```toml
[[outputs.graylog]]
  ## Endpoints for your graylog instances.
  servers = ["udp://127.0.0.1:12201"]
```

### System info

Telegraf 1.20

### Steps to reproduce

Graylog output plugin does not handle default gelf field "full_message" as default field. It treates it as custom field and adds "_" at beginning. Thats not correct, like "short_message" field, also full_message field must not start with underscore (see https://docs.graylog.org/en/4.0/pages/gelf.html).

Mentioned by @1tft in #9862.

1. data with a tag or field named `full_message`
2. it is sent in GELF payload as `"_full_message": "whatever",`

### Expected behavior

`full_message` field name should not be prefixed with underscore.

### Actual behavior

`full_message` field name is prefixed with underscore.
