### ISSUE TITLE
docker statsd python client, telegraf and InfluxDB - bind: cannot assign requested address

### ISSUE THREAD

**Issue by strus38** [influxdata/telegraf#1003]
Hi

Not sure I am in the right place to ask some help but it has been a few days I am stuck.
I have 2 VMs:

1. 2 containers with:
    - 1 container for a python app incl. python-statsd : 80/tcp, 8125/udp
    - 1 container with telegraf configured with statsd input plugin, influxdb output
2. - 1 container with influxdb

The ouput plugin to influxdb seems to work, however I have troubles configuring correctly the python & telegraf containers together.

Here is the content of my docker-compose.tml file:
```
pythonapp:
  restart: always
 ... < some content>
  expose:
    - "80"
    - "8125/udp"

telegraf:
  restart: always
  build: ./docker-telegraf
  environment:
    NODE_NAME: <this VM name>
    DB: api_metrics
    HOST: <remote influxdb host>
    STATSD_NODE: pythonapp
    STATSD_PORT: 8125
    INTERVAL: 10s
  links:
    - pythonapp 
```

When the telegraf container is built I update in the telegraf conf file the env variable by their content.
The telegraf container restart every few seconds, the log is the following:

```
=> Starting Telegraf ...
2016/04/09 11:37:08 Starting Telegraf (version 0.11.1)
2016/04/09 11:37:08 Loaded outputs: influxdb
2016/04/09 11:37:08 Loaded inputs: statsd
2016/04/09 11:37:08 Tags enabled: host=5d5539247ada node=<VM ID>
2016/04/09 11:37:08 Agent Config: Interval:10s, Debug:false, Quiet:false, Hostname:"5d5539247ada", Flush Interval:12.988465751s 
2016/04/09 11:37:08 Started the statsd service on pythonapp:8125
2016/04/09 11:37:08 ERROR: ListenUDP - listen udp 172.17.0.5:8125: bind: cannot assign requested address
```

172.17.0.5 is the IP of pythonapp container.

Any idea why it is not working as expected?
Thanks!!

**Comment by sparrc** [comment]
@strus38 how did you end up fixing this?

**Comment by strus38** [comment]
By being less stupid :-)

```
    STATSD_NODE: localhost
    STATSD_PORT: 8125
    INTERVAL: 10s
expose:
    - "8125:8125/udp"
```

And configuring the python code to use telegraph as the statsd node:

```
statsd_node = os.getenv('TELEGRAF_PORT_8125_UDP_ADDR')
statsd_ip = re.findall( r'[0-9]+(?:\.[0-9]+){3}', statsd_node )
teou_stats = statsd.StatsClient(str(statsd_ip[0]), 8125, prefix='teou')
```
