### ISSUE TITLE
inputs.docker plugin unix:///var/run/docker.sock Permission Denied

### ISSUE THREAD

**Issue by phantomski77** [influxdata/telegraf#10031]
### Relevent telegraf.conf

```toml
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_names = []
  container_name_include = []
  container_name_exclude = []
  perdevice = false
  perdevice_include = ["cpu", "blkio", "network"]
  total = true
  total_include = ["cpu", "blkio", "network"]
```

### System info

Telegraf 1.20.3, Ubuntu 21.10 (Linux 5.13.0-1009-raspi aarch64) on Raspberry Pi 4, Docker-CE 20.10.10

### Docker

docker-compose.yml
```
version: “3.8”
services:

telegraf:
    image: telegraf:1.20.3
    container_name: telegraf
    restart: unless-stopped
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    security_opt:
      - apparmor=unconfined
    volumes:
      - /telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    networks:
      - InfluxDB
    depends_on:
      InfluxDB:
        condition: "service_healthy"     
```

### Steps to reproduce

1. Enable plugin in telegraf.conf
2. Start telegraf container
3. Observe errors in the log
4. No Docker timeseries data stored in InfluxDB

### Expected behavior

- Docker Engine API data collected through unix:///var/run/docker.sock and stored as timeseries to InfluxDB
- Worked correctly in previous telegraf 1.20.x versions

### Actual behavior

telegraf log error:

E! [inputs.docker] Error in plugin: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.21/containers/json?filters=%7B%22status%22%3A%5B%22running%22%5D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied

**Comment by powersj** [comment]
Hi,

The Telegraf docker image no longer runs as the root user per Docker best practices. The Docker socket is owned by the root user and the docker group. As a result, you will want to add the `--group-add docker` option when creating the image. Use the group name or number that owns the Docker socket. This will allow the Telegraf user in the container to access to the socket.

Thanks!

**Comment by phantomski77** [comment]
> The Telegraf docker image no longer runs as the root user per Docker best practices. 

Thanks for quick and detailed reply. I’ve completely missed the change, apologies.

While I welcome the security hardening (telegraf requires a lot of access), it is a bit unfortunate because:
- personally I’d prefer not to build images every time I deploy a stack - I prefer to use pre-build ones from Docker hub or my own repository
- `docker-compose` is somehow ignoring the `group_add` setting. It worked in V2, then it didn’t, after a little upheaval now it’s supposed to sort-of work according to latest GitHub docs (official website is very quiet about it) in both V2 and V3, but doesn’t…
- so the only `docker-compose` option right now is `user: telegraf:<numeric_host_docker_gid>`, which is a bit of a undocumented coincidence (matching numeric gid is picked up from host) and can get broken at any time.

**Comment by dontobi** [comment]
I have the same error since today. I run Telegraf in a Docker container and have monitored all Docker containers so far. Maybe someone can tell me exactly what I need to change to get [input.docker] working again.

**Comment by phantomski77** [comment]
On your host, run command:
```
id
```
It will display the list of users and groups. Find the group `docker` and its associated `gid`.

Then it depends on how you spin your containers.

If you’re using `docker run` command line, then you’ll need to use `--group-add <your_host_docker_gid>` to add the telegraf’s container `telegraf` user to the host’s `docker` group which has the privileges for `unix:///var/run/docker.sock` .
For example:
```
docker run -d --name=telegraf \
      --net=influxdb \
      -v /var/run/docker.sock:/var/run/docker.sock:ro \
      -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro \
      --group-add 130 \
      telegraf
```
Technically you can use `docker` as a group name instead of gid, but I don’t have good experience with that (some docker versions presume the group exists within container, rather than host)

If you’re using `docker-compose`, then it’s a bit complicated, depending on your `docker-compose` version and your `docker-compose.yml` `version:` option. The `group_add` used to be available in versions `2` before and worked the same way as `docker run` as described above. Then it disappeared for versions `3` (won’t bother with [sad story details](https://github.com/docker/cli/issues/1318)), only to magically reappear in the [github docs](https://github.com/compose-spec/compose-spec/blob/master/spec.md#group_add) again. Funny thing is - it just doesn’t work. `docker-compose` doesn’t throw an error, but it doesn’t add the group to the container. For that, you need to add `user: telegraf:<your_host_docker_gid>` option, for example:
```
version: “3.8”
services:
  telegraf:
      image: telegraf:1.20.3
      container_name: telegraf
      restart: unless-stopped
      user: telegraf:<your_host_docker_gid>
      environment:
        - HOST_ETC=/hostfs/etc
        - HOST_PROC=/hostfs/proc
        - HOST_SYS=/hostfs/sys
        - HOST_VAR=/hostfs/var
        - HOST_RUN=/hostfs/run
        - HOST_MOUNT_PREFIX=/hostfs
      volumes:
        - /telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
```
This is the only way it worked for me. Using `group_add` or using `docker` as group name in `user:` option didn’t add the group and Docker monitoring telegraf plugin wasn’t working as the docker.sock wasn’t accessible.

It is bit of a mess and sadly it’s not mentioned anywhere in the influx and/or telegraf docs and examples (or I just couldn’t find it).

This is the short easy version. There are [more complicated and proper ways how to do it](https://jtreminio.com/blog/running-docker-containers-as-current-host-user/), but I’ll leave that up to you.

**Comment by freender** [comment]
This is the way I use it:
```
--group-add $(getent group | grep docker | awk -F ":" '{ print $3 }')
```

**Comment by danielb7390** [comment]
The fix provided above didn't work for me on unRAID, but i managed to fix it with `--user root`. Might not be the best secure solution but it works for me!

**Comment by powersj** [comment]
Hi Folks,

The team met this week to discuss the feedback you all provided about this change to the Telegraf DockerHub image. First, thank you for the quick responses and feedback. It helps us know how our images are getting used.

Clearly, the image does not come with everything that is needed for all scenarios and therefore users need to be able to add additional software and configuration. We have made a second change to allow the user to still install software packages that they need to do the monitoring. This image is live.

The telegraf process itself will still run as the `telegraf` user and group, not as root. That means that anything that Telegraf needs, like a service, socket, etc. to monitor needs to be visible by the `telegraf` user or group. As a result, I would suggest using `--user telegraf:<group>` as mentioned by @phantomski77 above in most cases. I will edit my previous posts to reflect this as well.

We published a [post](https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/) detailing this and again appreciate the feedback you gave this week.

Again, we really do appreciate the quick feedback. We missed some use cases and are incorporating some of these into our future testing when making changes. Thanks again!

**Comment by phantomski77** [comment]
> Again, we really do appreciate the quick feedback. We missed some use cases and are incorporating some of these into our future testing when making changes. Thanks again!

Thank you very much for a quick update and resolution. A prime example of well managed opensource project with a keen eye on the community feedback. I really welcome and appreciate both the security hardening principles implemented and the subsequent detailed update about the changes. Well done!

**Comment by grasshide** [comment]
>`user: telegraf:<numeric_host_docker_gid>`

Thank you! I was looking for that solution for a while now.

**Comment by acouvreur** [comment]
Any solution on swarm cluster ?

```yaml
 telegraf:
    image: telegraf:1.21.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf-config
        target: /etc/telegraf/telegraf.conf
    deploy:
      restart_policy:
        condition: on-failure
      mode: global
```

How do you set the GUID, which may differ from machines... ?
