### ISSUE TITLE
[inputs.internal] buffer_limit and buffer_size are wrong when multiple outputs of the same type are configured

### ISSUE THREAD

**Issue by Zanthras** [influxdata/telegraf#10041]
### Relevent telegraf.conf

```toml
[agent]
  interval = "2s"

[[outputs.influxdb]]
  metric_buffer_limit = 10
  urls = ["http://localhost:9999"]
  [outputs.influxdb.tagpass]
    output = [ "file" ]

[[outputs.influxdb]]
  metric_buffer_limit = 100
  urls = ["http://localhost:9998"]

[[inputs.internal]]

[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
```

### System info

Telegraf 1.20.0

### Steps to reproduce

1.) Run the config as described (with no influx server at the listed ports)
2.) Wait for the buffers to fill up
3.) look at the buffer_limit/buffer_size metrics

### Expected behavior

The internal_write measurement buffer_limit and buffer_size fields should reflect the two distinct output configurations in a sane manner.

Presumable an additional tag could be added for internal_write which would be "plugin_order" to allow for differentiation of outputs with the same type. And then track the other various added/droped/filtered/written per output plugin, not just per plugin type.

Presumably the plugin order would remain the same between restarts assuming the configuration was unchanged.

### Actual behavior

buffer_limit is always the last output configured, buffer_size randomly flips between any of the output buffer sizes. The mix of consistent (but incomplete) buffer_limit and random buffer_size makes using that information basically impossible when multiple output plugins of the same type are in use.
