### ISSUE TITLE
Enable extracting tag values from MQTT topics

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#10049]
### Proposal:
Currently, a whole MQTT topic can be stored as a tag. Proposing an enhancement to `inputs.mqtt_consumer` that allows tag values (measurements, fields as well) to be extracted from the MQTT topic letting you store the information provided in the topic in a more meaningful way. This is especially useful when subscribing to topics with single level wildcards. 

### Current behavior:
Need to configure a regex processor to pull tag values from topics.

### Desired behavior:
A setting in the `mqtt_consumer` plugin configuration to determine which part of the topic you may want to assign as measurement, tag, fields. 

Users would be able to configure the Topic: `abc/123/567/foo/bar`

1. Set measurement:
`topic_measurement = "_/_/_/_/measurement"`

2. Extract tag value and designate tag name: 
`topic_tags = "_/_/_/tag-name/_"`

3. Extract field value and designate field name: 
`topic_fields = "_/field-1-name/field-2-name//_"`

Output:
```
bar,tag-name=foo field-1-name=123, field-2-name=567
```

### Use case: 
IoT / MQTT users aren't developers. Having to defer them to writing a Starlark script or other complex processors isn't the user experience we want. This is an important enough aspect of MQTT ingestion that it should be handled at the input plugin in a simple TOML UX since segments (parents/children) are always delimited with "/". 

### Examples:
**Example 1**
Payload: `{ "temp": 23.1, "status": "ok", "alert": false, "load": 432.6}`
Topic: `meter/9174573134579843517855/7/HQ/energy`

Configuration:
```toml
topic_measurement = "_/_/_/_/measurement"
topic_tags = "_/_/_/location/_"
topic_fields = "_/customer_id/reconnect_count/_/_"
```

Expected Output:
```
energy,location=HQ,status=ok,alert=false customer_id=9174573134579843517855,reconnect_count=7i,load=432.6
```

**Example 2**
Payload: `10`
Topic: `things/abc/xyz/0002/temp`

Configuration:
```toml
topics = ["things/+/temp"]
topic_measurement = "measurement/_/_/_/_"
topic_tag = "_/_/_/device_id/_"
topic_field = "_/_/_/_/_"
```

Expect Output:
```
things,device_id=0002 temp=10
```
