### ISSUE TITLE
docker.sock access error

### ISSUE THREAD

**Issue by grasshide** [influxdata/telegraf#10050]
### Relevent telegraf.conf

```toml
[[inputs.docker]]
   endpoint = "unix:///var/run/docker.sock"
   container_names = []
   timeout = "5s"
   perdevice = false
   perdevice_include = ["cpu"]
   total = true
   total_include = ["cpu"]
```

### System info

Telegraf 1.20.3, Debian 11

### Docker

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

### Steps to reproduce

1. start docker container
2. see error log
3.
...

### Expected behavior

no errors expected.

### Actual behavior

2021-11-03T12:40:00Z E! [inputs.docker] Error in plugin: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.21/info": dial unix /var/run/docker.sock: connect: permission denied,
2021-11-03T12:40:00Z E! [inputs.docker] Error in plugin: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.21/containers/json?filters=%7B%22status%22%3A%5B%22running%22%5D%7D&limit=0": dial unix /var/run/docker.sock: connect: permission denied

### Additional info

My setup worked perfectly till the update form 29. Oktober.
All other services (portainer, traefik, watchtower) have no issue with accessing docker.sock.
I don't have a root user. I use sudo. Telegraf is started by docker-compose up -d in "sudo su" mode.

**Comment by danielb7390** [comment]
Same as #10031 ?

**Comment by powersj** [comment]
Hi,

We recently made a change to our Telegraf container images to run the telegraf process as the `telegraf` user and group. This means that when running Telegraf in a container, you will need to make sure that the `telegraf` user is added to the `docker` group.

The docker user directive can accomplish this by adding:

```
--user telegraf:$(stat -c '%g' /var/run/docker.sock)
```

We have a full [post](https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/) on why we made this change and the impact to users.

Thanks!

**Comment by pbek** [comment]
> --user telegraf:$(stat -c '%g' /var/run/docker.sock)

Of course if telegraf is used with docker-compose you either need to set the group statically by executing `stat -c '%g' /var/run/docker.sock` on the command line on the host and using that group id with the `user` property in your `docker-compose.yaml`, like:

```yaml
  telegraf:
...
    # "1000" is the group id of the docker daemon, run: $(stat -c '%g' /var/run/docker.sock)
    # see: https://www.influxdata.com/blog/docker-run-telegraf-as-non-root/
    user: telegraf:1000
...
```

Or you can play around with https://github.com/docker/compose/issues/1532#issuecomment-619548112 to get an env variable with the group id into the `docker-compose.yaml`.
