### ISSUE TITLE
[inputs.prometheus] not working for kubernetes config file

### ISSUE THREAD

**Issue by YuanhuiQu** [influxdata/telegraf#10055]
### Relevent telegraf.conf

```toml
[[inputs.prometheus]]
  kube_config = "/path/tel_k8s_conf/config"
  monitor_kubernetes_pods = true
  monitor_kubernetes_pods_namespace = "qa"
  insecure_skip_verify = true
```

### System info

Since telegraf 18.3 agent change

### Steps to reproduce

1. Install telegraf on kube node
2. Make sure prometheus annotition is setup properly in k8s yaml file
2. Add this config, make sure it point to the right config file

### Expected behavior

It should ship kube metrics in prometheus format

### Actual behavior

Got error 
```
unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

### Additional info

We have this config working fine before and it got broken after telegraf 1.18.3 where we introduced client agent https://github.com/influxdata/telegraf/pull/9271
Potentially cause: https://stackoverflow.com/questions/63628920/accessing-aks-kubeconfig-file-from-go-program
