### ISSUE TITLE
[inputs.mongodb] Telegraf crash on init if conn to MongoDB fails

### ISSUE THREAD

**Issue by papey** [influxdata/telegraf#10078]
### Relevent telegraf.conf

`/etc/telegraf/telegraf.d/mongo.conf`

```toml
[[inputs.mongodb]]
  servers = ["mongodb://127.0.0.1:27017/?connect=direct"]
  gather_perdb_stats = false

  fieldpass = ["deletes_per_sec", "flushes_per_sec", "getmores_per_sec", "inserts_per_sec", "updates_per_sec", "queries_per_sec", "open_connections", "net_in_bytes", "net_out_bytes", "repl_lag", "state"]
```

### System info

Telegraf 1.20.2 (git: HEAD f721f53d), Debian 10.11

### Steps to reproduce

1. Add a dedicated conf for MongoDB like the one above (to simulate a failed conn, just change the port number, for example)
2. Restart Telegraf

### Expected behavior

At least a log message to STDERR, on init, about a failing conn to a MongoDB server (with no retry mechanism)

### Actual behavior

Telegraf crashes :

```
Nov 08 17:32:09 test-mongo-telegraf telegraf[3423]: 2021-11-08T16:32:09Z E! [telegraf] Error running agent: could not initialize input inputs.mongodb: unable to connect to MongoDB: server selection error: context deadline exceeded, current topology: { Type: Single,
Nov 08 17:32:09 test-mongo-telegraf systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
```

### Additional info

My hypothesis is that we need to rethink some logic in the Init function in the [mongodb input code](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/mongodb/mongodb.go#L138-L146)
