### ISSUE TITLE
telegraf log file (/var/log/telegraf/telegraf.log)

### ISSUE THREAD

**Issue by yoonghm** [influxdata/telegraf#10070]
### Relevent telegraf.conf

```toml
[agent]  
  ## ...
  debug = true
  quiet = false
  logtarget = "file"
  logfile = "/var/log/telegraf/telegraf.log"
  ## ...
```

### System info

telegraf 1.20.3, influxdb 2.0.9 Lubuntu 20.04

### Steps to reproduce

The log file entry in `telegraf.conf` shall be fixed to `/var/log/telegraf.log` as all the scripts have assumed this location and it is easier and more consistent for user to troubleshoot and report errors.

### Expected behavior

Uses just need to enable `debug` to enable logging.

[agent]  
  ## ...
  debug = true

### Actual behavior

Nothing to be done unless users want to log events and errors to a log file.
