### ISSUE TITLE
Processor skipping fails

### ISSUE THREAD

**Issue by desvdp** [influxdata/telegraf#10071]
### Relevent telegraf.conf

```toml
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "some/topic/integer",
    "another/topic/json",
  ]
  data_format = "value"
  data_type = "string"

[[processors.converter]]
  [processors.converter.fields]
     integer = ["value"]
  [[processors.override.tagpass]]
     topic = ["some/topic/integer"]

[[outputs.file]]
  files = ["stdout"]
```

### System info

Telegraf 1.20, Docker

### Steps to reproduce

1. Given the Config file above
2. Send MQTT messages to the relevant topic in either json or raw int format
2. Observe the output 

### Expected behavior

I had expected the converter processor would be skipped for topics other than the the one mentioned.  
Where the json topic would be printed to stdout without conversion. 

I had based this assumption on:
"If a metric is excluded from a Processor or Aggregator plugin, it is skips the plugin and is sent onwards to the next stage of processing." found on: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering

### Actual behavior

The output log indicated the processor tried to convert the json to an integer. Further processing is stopped, the json is not output to stdout 

2021-11-07T13:09:20Z E! [processors.converter] error converting to integer [string]: {"time": 1636290541124, "fruit":"Apples"}
