### ISSUE TITLE
Cisco_telemetry_mdt input plugin incorrect parsing of child policy data sent by sensor "Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics"

### ISSUE THREAD

**Issue by MichaelTharwat** [influxdata/telegraf#10087]
### Relevent telegraf.conf

```toml
# Telegraf Configuration

###############################################################################
#                              GLOBAL CONFIG                                  #
###############################################################################

[agent]

  interval = "60s"
#  round_interval = true
#  metric_batch_size = 5000
#  metric_buffer_limit = 100000
#  collection_jitter = "0s"
  flush_interval = "30s"
#  flush_jitter = "0s"
#  debug = false
#  quiet = false
  logfile = "/tmp/telegraf_tcp.log"
#  hostname = ""
#  omit_hostname = false

###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################

[[inputs.cisco_telemetry_mdt]]
transport = "tcp"
service_address = ":5432"

embedded_tags = [
"Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics/class-stats/class-name","Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics/class_stats/child_policy/content/policy_name","Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics/class_stats/child_policy/content/class_stats/class_name"]

[[outputs.influxdb]]
   database = "telegrafdb"
   urls = ["http://localhost:8086"]
   retention_policy = "autogen"
```

### System info

debian buster

### Steps to reproduce

1.
2.
3.
...
1.Cisco equipment details
Cisco IOS XR Software, Version 6.5.3
Version : 6.5.3

2.Relevant Cisco equipment configuration
telemetry model-driven
destination-group GROUP1
  address-family ipv4 10.110.254.3 port 5432
   encoding self-describing-gpb
   protocol tcp
  !
!
destination-group DGroup2
  address-family ipv4 10.110.254.3 port 5431
   encoding json
   protocol tcp
  !
!
sensor-group s11
  sensor-path Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics
!
subscription sub11
  sensor-group-id s11 sample-interval 30000
  destination-id GROUP1
!
!

3.send telegraf output to influxdb 

### Expected behavior

Expected to convert child class name and child policy name to tags , 
expected to get all class names related to child class name but we receive only "class default"

### Actual behavior

convert only class name for parent policy not child and hence get only all class names for parent not child policy .
