### ISSUE TITLE
Plugin processors.regex not create new field

### ISSUE THREAD

**Issue by ihard** [influxdata/telegraf#10092]
### Relevent telegraf.conf

```toml
[global_tags]
[agent]
  interval = "1s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "500ms"
  debug = true
  quiet = false
  omit_hostname = true
[[inputs.influxdb_v2_listener]]
  service_address = ":8086"
[[processors.regex]]
  [[processors.regex.fields]]
    key = "value"
    pattern = "^(.*)$"
    replacement = "${1}"
    result_key = "my_value"
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### System info

telegraf 1.20.3 ubuntu 20.04

### Steps to reproduce

1. send metric to input "test123,instance=test1,metric_type=counter value=1i 1636562575000000000"

### Expected behavior

Metric with field my_value 
"test123,instance=test1,metric_type=counter value=1i,my_value=1i 1636562575000000000"

### Actual behavior

The plugin does not create a new field, metric is unchanged:
"test123,instance=test1,metric_type=counter value=1i 1636562575000000000"

### Additional info

I conducted some experiment and for a field that is of type string - everything works fine, it does not work only for integer and floating values.  Looks like an error in type processing.
