### ISSUE TITLE
OPC-UA input plugin will report errors once an hour and completely cut off at a random time.

### ISSUE THREAD

**Issue by zwl-sun** [influxdata/telegraf#10095]
### Relevent telegraf.conf

```toml
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"


# Configuration for telegraf agent
[agent]
  interval = "0.5s"
  round_interval = true
  metric_batch_size = 500
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "2s"
  flush_jitter = "0s"
  precision = "ms"

  ## Log at debug level.
   debug = true
  ## Log only error level messages.
  quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
   logtarget = "file"
   logfile = "/var/log/telegraf/telegraf2_log"
   # hostname = "zwl"
    omit_hostname = false

  # logfile_rotation_interval = "0d"

   logfile_rotation_max_size = "5MB"

   logfile_rotation_max_archives = -1

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago

   log_with_timezone = "Local"


  [[outputs.http]]
   url = "http://localhost:6041/telegraf/AAA"
      timeout = "5s"
   ## HTTP method, one of: "POST" or "PUT"
      method = "POST"
      username = "root"
      password = "taosdata"
      data_format = "json"
      json_timestamp_units = "1ms"

   ## HTTP Content-Encoding for write request body, can be set to "gzip" to
   ## compress body or "identity" to apply no encoding.
   # content_encoding = "identity"



   [[inputs.opcua]]
      endpoint = "opc.tcp://192.168.70.1:49320"
      connect_timeout = "10s"
      request_timeout = "10s"
      security_policy = "None"
      security_mode = "None"
      auth_method = "Anonymous"
	    tagexclude = ["id"]
   [inputs.opcua.tags]    
         tool_no="value1"
         workplace_name="999"

  [[inputs.opcua.group]]	 
      name = "Force"
      nodes =[
Omitted..here..........................................................................................................................................................................................................................................................................................
]

[[processors.converter]]
   [processors.converter.fields]
               string = ["value"]
  [[processors.printer]]
```

### System info

Telegraf 1.19.3    Centos7.2

### Docker

Nothing!

### Steps to reproduce

1.There are 150 metrics in the configuration file.
2.Data acquisition interval is 0.5s.
3.During connection we see an error like in subject and below logs. And only restart telegraf will restore.
...

### **No error will be reported every hour or If an error is reported, it will restart automatically.**

2021-11-04T17:00:09+08:00 D! [outputs.http] Wrote batch of 150 metrics in 122.670209ms
2021-11-04T17:00:09+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-04T17:00:11+08:00 D! [outputs.http] Wrote batch of 150 metrics in 1.187410076s
2021-11-04T17:00:11+08:00 D! [outputs.http] Buffer fullness: 150 / 100000 metrics
2021-11-04T17:00:12+08:00 D! [outputs.http] Wrote batch of 150 metrics in 1.090435665s
2021-11-04T17:00:12+08:00 D! [outputs.http] Buffer fullness: 150 / 100000 metrics
2021-11-04T17:00:13+08:00 D! [outputs.http] Wrote batch of 150 metrics in 827.333763ms

### 1. Errors will be reported every hour.

2021-11-04T16:59:56+08:00 D! [outputs.http] Wrote batch of 150 metrics in 45.53379ms
2021-11-04T16:59:56+08:00 D! [outputs.http] Buffer fullness: 150 / 100000 metrics
2021-11-04T16:59:57+08:00 D! [outputs.http] Wrote batch of 150 metrics in 53.488778ms
2021-11-04T16:59:57+08:00 D! [outputs.http] Buffer fullness: 150 / 100000 metrics
2021-11-04T16:59:59+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-04T16:59:59+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-04T16:59:59+08:00 D! [outputs.http] Wrote batch of 150 metrics in 88.856268ms
2021-11-04T16:59:59+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-04T17:00:00+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-04T17:00:00+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-04T17:00:01+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-04T17:00:01+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-04T17:00:01+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-04T17:00:02+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-04T17:00:02+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-04T17:00:03+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-04T17:00:03+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-04T17:00:03+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-04T17:00:08+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-04T17:00:08+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-04T17:00:08+08:00 E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: The operation timed out. StatusBadTimeout (0x800A0000)
2021-11-04T17:00:09+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-04T17:00:09+08:00 D! [outputs.http] Wrote batch of 150 metrics in 122.670209ms
2021-11-04T17:00:09+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-04T17:00:11+08:00 D! [outputs.http] Wrote batch of 150 metrics in 1.187410076s
2021-11-04T17:00:11+08:00 D! [outputs.http] Buffer fullness: 150 / 100000 metrics

### 2.At a random moment, the Inputs-Opcua Plugin will always report an error and will not restart automatically.

2021-11-05T10:53:07+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:08+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:08+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:09+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:09+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:09+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:10+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:10+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:11+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:11+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:11+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:12+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:12+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:13+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:13+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:13+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:14+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:14+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:15+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:15+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:15+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:16+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:16+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:17+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:17+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:17+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:18+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:18+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:19+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:19+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:19+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:20+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:20+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:21+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:21+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:21+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:22+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:22+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:23+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:23+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:23+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:24+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:24+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:25+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:25+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:25+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:26+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:26+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:27+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:27+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:27+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:28+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:28+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:29+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:29+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:29+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:30+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:30+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:31+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:31+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:31+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:32+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:32+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:33+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:33+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:33+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:34+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:34+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:35+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:35+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:35+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:36+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:36+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:37+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:37+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:37+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:38+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:38+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:39+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:39+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:39+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:40+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:40+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:41+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:41+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:41+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:42+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:42+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:43+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:43+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:43+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:44+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:44+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:45+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:45+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:45+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:46+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:46+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:47+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:47+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:47+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:48+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:48+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:49+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:49+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:49+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:50+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:50+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:51+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:51+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:51+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:52+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:52+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:53+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:53+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:53+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:54+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:54+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:55+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:55+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:55+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:56+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:56+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:57+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:57+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:57+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:53:58+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:58+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:59+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:53:59+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:53:59+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2021-11-05T10:54:00+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:54:00+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:54:01+08:00 W! [inputs.opcua] Collection took longer than expected; not complete after interval of 1s
2021-11-05T10:54:01+08:00 D! [inputs.opcua] Previous collection has not completed; scheduled collection skipped
2021-11-05T10:54:01+08:00 D! [outputs.http] Buffer fullness: 0 / 100000 metrics
