### ISSUE TITLE
statsd plugin sanitizes '?'

### ISSUE THREAD

**Issue by mbanaszkiewicz-vonage** [influxdata/telegraf#10113]
### Relevent telegraf.conf

```toml
[[inputs.statsd]]
  service_address = ":8125"
  delete_gauges = true
  delete_counters = true
  delete_sets = true
  delete_timings = true
  percentiles = [90]
  metric_separator = "_"
  parse_data_dog_tags = false
  allowed_pending_messages = 10000
  percentile_limit = 1000
```

### System info

telegraf:alpine latest

### Docker

docker-compose available here: https://github.com/spring-projects/spring-boot/issues/28393

### Steps to reproduce

detailed steps to reproduce: https://github.com/spring-projects/spring-boot/issues/28393

### Expected behavior

Telegraf should receive metrics with '?'

### Actual behavior

Sanitization of '?' character makes it not possible to use metrics related to urls with query params, for example, in grafana. Looks like telegraf statsd input ignores tags with '?'

Context: 
https://github.com/spring-projects/spring-boot/issues/28393
https://github.com/micrometer-metrics/micrometer/issues/2840
