### ISSUE TITLE
telemetry GRPC connection cannot be established

### ISSUE THREAD

**Issue by xinmos** [influxdata/telegraf#10141]
### Relevent telegraf.conf

```toml
[[inputs.cisco_telemetry_mdt]]
 ## Telemetry transport can be "tcp" or "grpc".  TLS is only supported when
 ## using the grpc transport.
 transport = "grpc"
 max_msg_size = 20000000

 ## Address and port to host telemetry listener
 service_address = ":57500"
```

### System info

Telegraf 1.19

### Steps to reproduce

XR：7.3.1 telemetry 配置
```
destination-group 192.168.1.1
  address-family ipv4 192.168.1.1 port 57500
   encoding self-describing-gpb
   protocol grpc no-tls

 sensor-group sr_policy
  sensor-path Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies

subscription telegraf_policy
  sensor-group-id sr_policy strict-timer
  sensor-group-id sr_policy sample-interval 5000
  destination-id 13tcp
  destination-id 192.168.1.1
```

### Expected behavior

When I used GRPC Dial-out to collect data of XR9K device, I could not establish an effective link all the time. XR devices are 64-bit
According to the document, it should meet the telemetry configuration requirements, but I could not collect valid data through GRPC Dial-out. But TCP Dial-out does. So I can't confirm what's wrong, right

### Actual behavior

No connection and no data

### Additional info

Could it be an equipment problem? Maybe you could test it out for me
