### ISSUE TITLE
SMART plugin doesn't collect vendor-specific data with nvme-cli v1.14+

### ISSUE THREAD

**Issue by KubaTrojan** [influxdata/telegraf#10149]
### Relevent telegraf.conf

```toml
[[inputs.smart]]
  path_smartctl = "/usr/sbin/smartctl"
  path_nvme = "/usr/sbin/nvme"
  enable_extensions = [ "Intel" ]
  use_sudo = true
  nocheck = "never"
  attributes = true
  devices = ["/dev/nvme0n1"]
```

### System info

Telegraf 1.20.4, Ubuntu 18.04, nvme-cli 1.14

### Steps to reproduce

1. Run Telegraf with SMART plugin enabled.
2. Observe metrics.

### Expected behavior

Telegraf successfully collects SMART metrics from nvme devices.

### Actual behavior

When running Telegraf with a config with SMART plugin's Intel extension enabled, Intel specific metrics are not being reported for nvme drive.

### Additional info

The output format of nvme-cli (v1.14+) has been changed, and SMART plugin doesn't read properly from it.
