### ISSUE TITLE
Sudden close of Telegraf caused by OPC UA input plugin

### ISSUE THREAD

**Issue by hybuild-project** [influxdata/telegraf#10140]
### Relevent telegraf.conf

```toml
[[inputs.opcua]]
  name = "xyz"
  endpoint = "opc.tcp://xxx.yyy.wwww.zzz:4840"
  security_policy = "None"
  security_mode = "None"
  nodes = [
    { name="abc",  namespace="6",  identifier_type="s",  identifier="abc"},
    { name="def",  namespace="6",  identifier_type="s",  identifier="def"},
...
]
```

### System info

Telegraf 1.20.3, Windows 10

### Steps to reproduce

1. Simly running Telegraf with that plugin
2.
3.
...

### Expected behavior

No errors

### Actual behavior

After some random time (hours, one day at most) it crashes:

goroutine 68418 [running]:
github.com/gopcua/opcua/uasc.(*SecureChannel).dispatcher(0xc0007b8000)
        /go/pkg/mod/github.com/gopcua/opcua@v0.2.0-rc2.0.20210409063412-baabb9b14fd2/uasc/secure_channel.go:208 +0x185
created by github.com/gopcua/opcua/uasc.(*SecureChannel).open.func1
        /go/pkg/mod/github.com/gopcua/opcua@v0.2.0-rc2.0.20210409063412-baabb9b14fd2/uasc/secure_channel.go:496 +0x5f
