### ISSUE TITLE
json time key not match and _field is more than json_string_fields

### ISSUE THREAD

**Issue by ccb1900** [influxdata/telegraf#10146]
### Relevent telegraf.conf

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  # debug = true
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[inputs.mqtt_consumer]]
  ## Broker URLs for the MQTT server or cluster.  To connect to multiple
  ## clusters or standalone servers, use a seperate plugin instance.
  ##   example: servers = ["tcp://localhost:1883"]
  ##            servers = ["ssl://localhost:1883"]
  ##            servers = ["ws://localhost:1883"]
  servers = ["tcp://emqx:1883"]

  ## Topics that will be subscribed to.
  topics = [
    "device/#",
  ]

  ## The message topic will be stored in a tag specified by this value.  If set
  ## to the empty string no topic tag will be created.
  # topic_tag = "topic"

  ## QoS policy for messages
  ##   0 = at most once
  ##   1 = at least once
  ##   2 = exactly once
  ##
  ## When using a QoS of 1 or 2, you should enable persistent_session to allow
  ## resuming unacknowledged messages.
  # qos = 0

  ## Connection timeout for initial connection in seconds
  # connection_timeout = "30s"

  ## Maximum messages to read from the broker that have not been written by an
  ## output.  For best throughput set based on the number of metrics within
  ## each message and the size of the output's metric_batch_size.
  ##
  ## For example, if each message from the queue contains 10 metrics and the
  ## output metric_batch_size is 1000, setting this to 100 will ensure that a
  ## full batch is collected and the write is triggered immediately without
  ## waiting until the next flush_interval.
  # max_undelivered_messages = 1000

  ## Persistent session disables clearing of the client session on connection.
  ## In order for this option to work you must also set client_id to identify
  ## the client.  To receive messages that arrived while the client is offline,
  ## also set the qos option to 1 or 2 and don't forget to also set the QoS when
  ## publishing.
  # persistent_session = false

  ## If unset, a random client ID will be generated.
  # client_id = ""

  ## Username and password to connect MQTT server.
  # username = "telegraf"
  # password = "metricsmetricsmetricsmetrics"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
data_format = "json"
  json_time_key="origin"
  json_name_key="meta_deviceName"
  json_time_format="unix"
  tag_keys=[
      "meta_profileName",
      "meta_sourceName"
  ]
  json_string_fields=["Int16","Int32"]
## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
data_format = "json"
  json_time_key="origin"
  json_name_key="meta_deviceName"
  json_time_format="unix"
  tag_keys=[
      "meta_profileName",
      "meta_sourceName"
  ]
  json_string_fields=["Int16","Int32"]
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]

  ## API token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "hello"

  ## Destination bucket to write into.
  bucket = "iot
```

### System info

Telegraf 1.20.0, Ubuntu 20.04

### Steps to reproduce

```json
[
    {
        "Int16": -14948,
        "Int32": -1018565424,
        "meta": {
            "Int16": {
                "deviceName": "Random-Integer-Device",
                "id": "b95a0986-4391-4330-b418-443fd288dcff",
                "origin": 1637633149094696079,
                "profileName": "Random-Integer-Device",
                "valueType": "Int16"
            },
            "Int32": {
                "deviceName": "Random-Integer-Device",
                "id": "ac259ef9-52ff-4c0e-bfd3-68af262da81c",
                "origin": 1637633149094696079,
                "profileName": "Random-Integer-Device",
                "valueType": "Int32"
            },
            "correlationid": "",
            "deviceName": "Random-Integer-Device",
            "id": "3442fe68-b8ca-4cf3-ac98-b82c08e09e4b",
            "origin": 1637633149094696079,
            "profileName": "Random-Integer-Device",
            "sourceName": "rr",
            "tags": null
        },
        "origin": 1637633149
    }
]
```

### Expected behavior

```json
{
    "fields": {
        "Int16": -8259,
        "Int32": 127230490
 
    },
    "name": "Random-Integer-Device",
    "tags": {
        "host": "a5c64718a06f",
        "meta_profileName": "Random-Integer-Device",
        "meta_sourceName": "rr",
        "topic": "device/integer"
    },
    "timestamp": 1637633054
}
```

### Actual behavior

```json
{
    "fields": {
        "Int16": -8259,
        "Int32": 127230490,
        "meta_Int16_origin": 1637633054030601200,
        "meta_Int32_origin": 1637633054030601200,
        "meta_origin": 1637633054030601200
    },
    "name": "Random-Integer-Device",
    "tags": {
        "host": "a5c64718a06f",
        "meta_profileName": "Random-Integer-Device",
        "meta_sourceName": "rr",
        "topic": "device/integer"
    },
    "timestamp": 1637633054
}
```

### Additional info

I set json time key ,but it seems no effect.

in influxdb,I got _time every 10s.in fact ,i should every 5s
