### ISSUE TITLE
processors.unpivot: Reuse tags and field names

### ISSUE THREAD

**Issue by trennepohl** [influxdata/telegraf#10164]
## Feature Request
Hi :wave: 
If makes sense for the project I'd like to implement this improvement.
I've bumped into a scenario where I need to unpivot a metric but still keep its original field name and tags.

### Proposal:
When `tag_key` and `value_key ` are not set, the processor will keep tags as they are and create a new metric per field. i.e
```diff
-cpu, cpu=cpu0 time_idle=42i,time_user=43i
+cpu, cpu=cpu0 time_idle=42i
+cpu, cpu=cpu0 time_user=43i
```
### Current behavior:
for each field the processor creates a new metric, but the field name becomes a tag value
```diff
- cpu,cpu=cpu0 time_idle=42i,time_user=43i
+ cpu,cpu=cpu0,name=time_idle value=42i
+ cpu,cpu=cpu0,name=time_user value=43i
```

### Desired behavior:
as described in the proposal

**Comment by powersj** [comment]
Hi,

Can you provide an example configuration that you are using to generate these? It would help to think through this proposal a bit.

```diff
-cpu, cpu=cpu0 time_idle=42i,time_user=43i
+cpu, cpu=cpu0 time_idle=42i
+cpu, cpu=cpu0 time_user=43i
```

As this is written, in Line Protocol, one thing to keep in mind is that the first line is essentially identical to the 2nd and 3rd assuming the timestamps are identical.

**Comment by trennepohl** [comment]
Sure.

```toml
[global_tags]
  cluster_name = "test-cluster"
  example = "another-example"
  host = "some-host"

[[inputs.internal]]
  collect_memstats = false
  tagexclude = ["go_version", "version", "host"]
  namepass = ["internal_agent"]

[[processors.unpivot]]
  order = 1
  tag_key = "name"
  value_key = "value"

[[processors.printer]]
 order = 2

[[outputs.health]]
  service_address = "http://:8080/health"
```

The config above produces the following 
```diff
-internal_agent,cluster_name=test-cluster,example=another-example metrics_written=20i,metrics_dropped=0i,metrics_gathered=5i,gather_errors=0i 1638789830000000000
+internal_agent,cluster_name=test-cluster,example=another-example,name=metrics_written value=0i 1638789890000000000
+internal_agent,cluster_name=test-cluster,example=another-example,name=metrics_dropped value=0i 1638789890000000000
+internal_agent,cluster_name=test-cluster,example=another-example,name=metrics_gathered value=0i 1638789890000000000
+internal_agent,cluster_name=test-cluster,example=another-example,name=gather_errors value=0i 1638789890000000000
```

And what I'm proposing is when using unpivot without specifying a `tag_key` and `tag_value` would produce metrics without the tag `name` and use the field_name itself for the new metric field name
```diff
-internal_agent,cluster_name=test-cluster,example=another-example metrics_written=20i,metrics_dropped=0i,metrics_gathered=5i,gather_errors=0i 1638789830000000000
+internal_agent,cluster_name=test-cluster,example=another-example metrics_written=0i 1638789890000000000
+internal_agent,cluster_name=test-cluster,example=another-example metrics_dropped=0i 1638789890000000000
+internal_agent,cluster_name=test-cluster,example=another-example metrics_gathered=0i 1638789890000000000
+internal_agent,cluster_name=test-cluster,example=another-example gather_errors=0i 1638789890000000000
```
