### ISSUE TITLE
parser json_v2  multiple_timestamps bug 

### ISSUE THREAD

**Issue by covered** [influxdata/telegraf#10160]
### Relevent telegraf.conf

```toml
# Example taken from: https://github.com/influxdata/telegraf/issues/5940

[[inputs.file]]
    files = ["./testdata/multiple_timestamps/input.json"]
    data_format = "json_v2"
    [[inputs.file.json_v2]]
        [[inputs.file.json_v2.object]]
            path = "events"
            timestamp_key = "time"
            timestamp_format = "unix_ms"
```

### System info

telegraf 1.20.4  / telegraf 1.20.0

### Steps to reproduce

1.  input json：
```
{
    "events": [
        {
            "name1": "fire1",
            "name": "fire",
            "time": "0"
        },
        {
            "name": "flood",
            "time": "1"
        }
    ]
}
```

### Expected behavior

file name="fire" 0
file name="flood" 1

### Actual behavior

file name="fire", name1="fire1" 1577811661000000000
file name="flood" 1
