### ISSUE TITLE
bigquery unknown plugin

### ISSUE THREAD

**Issue by theiny** [influxdata/telegraf#10177]
### Relevent telegraf.conf

```toml
[[outputs.bigquery]]
  ## GCP Project
  project = "erudite-bloom-151019"
  ## The BigQuery dataset
  dataset = "telegraf"
  ## Timeout for BigQuery operations.
  # timeout = "5s"
  ## Character to replace hyphens on Metric name
  # replace_hyphen_to = "_"
```

### System info

Telegraf 1.20, Docker 20.10.10

### Steps to reproduce

1. Run telegraf with bigquery output plugin defined in telegraf.conf
2.
3.
...

### Expected behavior

Telegraf should recognise the BigQuery plugin

### Actual behavior

[telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: error parsing bigquery array, Undefined but requested output: bigquery
