### ISSUE TITLE
telegraf config parser mqtt json  "json_v2"

### ISSUE THREAD

**Issue by Qdynasty** [influxdata/telegraf#10194]
### Relevent telegraf.conf

```toml
data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
     measurement_name = "gateway_insert"
       [[inputs.mqtt_consumer.json_v2.object]]
          path = "@this"
          disable_prepend_keys = false
          excluded_keys = ["points"]
          [[inputs.mqtt_consumer.json_v2.object.field]]
              path = "@this.odometer"
              rename = "odo"
              type = "string"
```

### System info

telegraf  1.20.4

### Docker

``` 
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    links:
      - influxdb
    volumes:

    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 1024M

    restart: unless-stopped
```

### Steps to reproduce

1.  config rename invalid
2.  It is found that the data is not parsed according to the configuration
3.  A JSON data nested array field is fully arranged and combined, but only one data can be found

### Expected behavior

1. filter odometer 
2. ”speed“ Each element rename resolution is stored in influxdb
3. 其他字段原类型存储到influxdb

### Actual behavior

{
        "y": 1111111.354243171,
        "x": 1111111.9858582001,
        "speed": [0.0, 1.0, 2.0, 4.0],
        "angle": [
            0.35431448844127544,
            0.09063859006636221,
            0.35431448844127544,
            0.09063859006636221,
            -0.08514534218357994,
            0.35431448844127544,
            -0.2609292744335221,
            0.1785305561913333
        ],
        "name": "A001",
        "left_behind_at": 1634607917.8445928,
        "odometer": [9.9,
                     9.1,
                     9.5,
                     6.6000000000000005,
                     9.9,
                     10.100000000000001,
                     9.5,
                     7.9],
        "distance": 0.0,
        "gy": 957004.5313795683,
        "current_throttle": 0.0,
        "points": [{"type": 0, "x": -27.771453857421875, "y": 7.960874557495117},
                   {"type": 0, "x": -26.048484802246094, "y": 7.958527565002441},
                   {"type": 16, "x": 14.540033340454102, "y": -25.705089569091797}
                  ],
        "time": str(datetime.datetime.utcnow().strftime("%Y-%m-%dT %H:%M%SZ"))
    }

### Additional info

![image](https://user-images.githubusercontent.com/50348487/143766807-4de844d2-4ed9-41ac-9239-b2fb8d43eed3.png)
