### ISSUE TITLE
Metrics: Download Stats

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#10227]
## Overview

Track download statistics from Docker + dl.influxdata.com

## Use Case

Understand which are the more popular Telegraf builds

## Data sources

- InfluxData downloads page: https://dl.influxdata.com/logs/stats.html
- Docker downloads: https://hub.docker.com/v2/repositories/library/telegraf/
- Homebrew: https://formulae.brew.sh/formula/telegraf
```toml
[[inputs.http]]
interval = "24h"
  urls = [
    "https://formulae.brew.sh/api/formula/telegraf.json",
    "https://formulae.brew.sh/api/formula/influxdb.json"
  ]
  name_override = "brew"
  tagexclude = ["url"]
  method = "GET"
  data_format = "json"
  json_query = "analytics"
  tag_keys = ["install", "install_on_request", "build_error"]
```

## Expected Result

Single place to view the total downloads for Telegraf
