### ISSUE TITLE
Upgrading Telegraf 1.18.3 to 1.20.4

### ISSUE THREAD

**Issue by jcourt2006** [influxdata/telegraf#10233]
### Relevent telegraf.conf

```toml
root@cta0000xxxxx  ~]# more /etc/telegraf/snmp-trap.conf
[global_tags]
  squad = "xxxxxx"

[agent]
  interval = "180s"
  flush_interval = "60s"

# Publish all metrics to /metrics for Prometheus to scrape
[[outputs.prometheus_client]]
  ## Address to listen on.
  listen = ":9126"
  metric_version = 2
  path = "/metrics"
  string_as_label = true
  export_timestamp = true

[[inputs.snmp_trap]]
  service_address = "udp://:162"

  version = "3"
  sec_name = "xxxxxx"
  sec_level = "xxxxx"
  auth_protocol = "xxxx"
  auth_password = "xxxxxx"
  priv_protocol = "xxxx"
  priv_password = "xxxxxx"

#Add DNS Key/Value pair to metric
[[processors.reverse_dns]]
  order = 1
  [[processors.reverse_dns.lookup]]
    tag = "source"
    dest = "dns"

[[processors.regex]]
  order = 2
  [[processors.regex.tags]]
    ## Field to change
    key = "dns"

        ## strip domain
    pattern = "^([a-zA-Z\\d]+-[a-zA-Z\\d]+).*"
    replacement = "${1}"
    result_key = "sysname"



[[processors.starlark]]
  order = 3
  ## File containing a Starlark script.
  script = "/etc/telegraf/starlark.py"
```

### System info

Red Hat Enterprise Linux Server release 7.9 (Maipo)

### Docker

  telegraf-ddos-trap:
      image: rexxx.xxxx.xxx.xxx/telegraf:1.18.3
      container_name: telegraf-ddos-trap
      hostname: telegraf-ddos-trap
      restart: always
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - /etc/telegraf/snmp-trap.conf:/etc/telegraf/telegraf.conf
        - /etc/telegraf/mibs/:/usr/share/snmp/mibs/
        - /etc/telegraf/starlark.py:/etc/telegraf/starlark.py
      ports:
        - 10090:9126
        - 162:162/udp
      logging:
        driver: syslog
        options:
          syslog-address: "tcp://localhost:514"
          syslog-format: "rfc5424"
          tag: "{{.ImageName }}/{{.Name }}/{{.ID }}"
      command: telegraf --config /etc/telegraf/telegraf.conf

# Will not work if I change above version to:
  telegraf-ddos-trap:
      image: rexxx.xxxx.xxx.xxx/telegraf:1.20.4
      container_name: telegraf-ddos-trap
      hostname: telegraf-ddos-trap
      restart: always
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - /etc/telegraf/snmp-trap.conf:/etc/telegraf/telegraf.conf
        - /etc/telegraf/mibs/:/usr/share/snmp/mibs/
        - /etc/telegraf/starlark.py:/etc/telegraf/starlark.py
      ports:
        - 10090:9126
        - 162:162/udp
      logging:
        driver: syslog
        options:
          syslog-address: "tcp://localhost:514"
          syslog-format: "rfc5424"
          tag: "{{.ImageName }}/{{.Name }}/{{.ID }}"
      command: telegraf --config /etc/telegraf/telegraf.conf

### Steps to reproduce

1.Change the docker compose file
2.  docker-compose up -d
3.
...

### Expected behavior

That telegraf 1.20.4 will work fine, but we get the next errors

Dec  7 14:59:50 cta0000xxxxx rexxx.xxxx.xxx.xxx/telegraf:1.20.4/telegraf-ddos-trap/507050d4ad7c[1485] 2021-12-07T13:59:50Z E! [telegraf] Error running agent: starting input inputs.snmp_trap: listen udp :162: bind: permission denied
Dec  7 15:00:00 cta0000xxxxx audispd: node=cta0000xxxxx type=AVC msg=audit(1638885600.002:639438): avc:  denied  { module_request } for  pid=21139 comm="ping" kmod="net-pf-10" scontext=system_u:system_r:container_t:s0:c756,c979 tcontext=system_u:system_r:kernel_t:s0 tclass=system permissive=1

### Actual behavior

The telegraf version 1.18.3 don't have any problem and can bind to UDP 162

CONTAINER ID        IMAGE                                                          COMMAND                  CREATED             STATUS              PORTS                                                                         NAMES
6fe18f385a18        rexxx.xxxx.xxx.xxx/telegraf:1.18.3                    "/entrypoint.sh te..."   14 seconds ago      Up 13 seconds       8092/udp, 0.0.0.0:162->162/udp, 8125/udp, 8094/tcp, 0.0.0.0:10090->9126/tcp   telegraf-ddos-trap

### Additional info

I hope you can help us with this issue
