### ISSUE TITLE
Timestamp of data that collected from telegraf is disordered.

### ISSUE THREAD

**Issue by zzcpower** [influxdata/telegraf#10241]
### Relevent telegraf.conf

```toml
[global_tags]
vm_os_type = "linux"
vm_uuid = "5b616bfd-dbc4-4d9b-a015-610870b8bb14"

[agent]
interval = "60s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "5s"
flush_interval = "60s"
flush_jitter = "10s"
debug = false
quiet = false
hostname = "5b616bfd-dbc4-4d9b-a015-610870b8bb14"
omit_hostname = false

[[inputs.procstat]]
systemd_unit = "redis-server.service"
name_prefix = "vm_linux_"
[[outputs.file]]
files = ["/etc/telegraf/test.txt"]
```

### System info

Telegraf 1.14.1, CentOS Linux release 7.9.2009 (Core)

### Steps to reproduce

1.Set up the telegraf.conf 
2.check the timestamp of data in output file "/etc/telegraf/test.txt"

...

### Expected behavior

cat /etc/telegraf/test.txt

vm_linux_procstat_lookup,host=5b616bfd-dbc4-4d9b-a015-610870b8bb14,pid_finder=pgrep,result=success,systemd_unit=redis-server.service,vm_os_type=linux,vm_uuid=5b616bfd-dbc4-4d9b-a015-610870b8bb14 pid_count=1i,running=1i,result_code=0i **1638958861000000000**

vm_linux_procstat_lookup,host=5b616bfd-dbc4-4d9b-a015-610870b8bb14,pid_finder=pgrep,result=success,systemd_unit=redis-server.service,vm_os_type=linux,vm_uuid=5b616bfd-dbc4-4d9b-a015-610870b8bb14 result_code=0i,pid_count=1i,running=1i **1638958921000000000**

vm_linux_procstat_lookup,host=5b616bfd-dbc4-4d9b-a015-610870b8bb14,pid_finder=pgrep,result=success,systemd_unit=redis-server.service,vm_os_type=linux,vm_uuid=5b616bfd-dbc4-4d9b-a015-610870b8bb14 pid_count=1i,running=1i,result_code=0i **1638958982000000000**

### Actual behavior

If we check the output file we can see that the out put is disordered.

```
cat /etc/telegraf/test.txt
```

vm_linux_procstat_lookup,host=5b616bfd-dbc4-4d9b-a015-610870b8bb14,pid_finder=pgrep,result=success,systemd_unit=redis-server.service,vm_os_type=linux,vm_uuid=5b616bfd-dbc4-4d9b-a015-610870b8bb14 result_code=0i,pid_count=1i,running=1i **1638958921000000000**

vm_linux_procstat_lookup,host=5b616bfd-dbc4-4d9b-a015-610870b8bb14,pid_finder=pgrep,result=success,systemd_unit=redis-server.service,vm_os_type=linux,vm_uuid=5b616bfd-dbc4-4d9b-a015-610870b8bb14 pid_count=1i,running=1i,result_code=0i **1638958861000000000**

vm_linux_procstat_lookup,host=5b616bfd-dbc4-4d9b-a015-610870b8bb14,pid_finder=pgrep,result=success,systemd_unit=redis-server.service,vm_os_type=linux,vm_uuid=5b616bfd-dbc4-4d9b-a015-610870b8bb14 pid_count=1i,running=1i,result_code=0i **1638958982000000000**

### Additional info

As we can see, the timestamps that attached to **the first and second data is disordered.** This issue happens sometimes but not frequently .
, but it still impact my proceeding alarm service logic.

Moreover, this is not only about procstat plugin. This issue actually happens in all types of plugins, including cpu, mem, and others.( I tested before)

Can someone help please?
Feel free to ask more information of this issue if needed.
