### ISSUE TITLE
AMQP consumer should not consume more messages than fit in the input buffer

### ISSUE THREAD

**Issue by don-code** [influxdata/telegraf#10244]
### Proposal:

This proposal suggests that Telegraf does not consume an AMQP queue if its local metric buffer is full. Telegraf does not appear to negative-acknowledge messages if the input buffer is full, nor does it refuse to consume if the input buffer is full. Instead, messages are always  consumed and dropped on the floor once the local metric buffer is filled. Furthermore, it consumes as many messages as it can once the agent is brought back up.

### Current behavior:

If Telegraf agents using the `amqp_consumer` input are brought back online after an outage, during which messages have been queued on a RabbitMQ queue, they will consume the queue in one large step:

![Screen Shot 2021-12-08 at 09 20 42](https://user-images.githubusercontent.com/8206137/145224248-e5133d75-0500-4907-9abc-06d7ccf6e34b.png)

The agents will then drop the messages on the floor, losing them permanently:

```
2021-12-08T14:08:44Z I! Starting Telegraf 1.20.0
2021-12-08T14:08:44Z I! Using config file: /etc/telegraf/telegraf.conf
2021-12-08T14:08:44Z I! Loaded inputs: amqp_consumer
2021-12-08T14:08:44Z I! Loaded aggregators:
2021-12-08T14:08:44Z I! Loaded processors:
2021-12-08T14:08:44Z I! Loaded outputs: influxdb
2021-12-08T14:08:44Z I! Tags enabled:
2021-12-08T14:08:44Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2021-12-08T14:08:46Z W! [outputs.influxdb] Metric buffer overflow; 6926 metrics have been dropped
2021-12-08T14:08:47Z W! [outputs.influxdb] Metric buffer overflow; 20385 metrics have been dropped
2021-12-08T14:08:47Z W! [outputs.influxdb] Metric buffer overflow; 18889 metrics have been dropped
(this message repeats many times)
```

### Desired behavior:

The Telegraf agent should not consume messages off of an AMQP queue if its only recourse is to drop them.

### Use case:

One of the benefits of using the AMQP producer/consumer combination is that metrics can be buffered during a backend outage. For instance, metrics can be published to the queue and not consumed while an InfluxDB database is unavailable, then processed in a delayed fashion once InfluxDB becomes available again.

**Comment by reimda** [comment]
Hi @don-code it makes sense to me that Telegraf shouldn't consume messages and then just drop them.

The first thing that would help someone implementing this change would be to have a way to reproduce the conditions you described, with data in the amqp queue and telegraf that is in metric buffer overflow. Do you have an easy way to set this up so a dev could test a potential change? Thanks!

**Comment by don-code** [comment]
Hi @reimda - I put together a small test case with Docker Compose. This will launch a RabbitMQ and a Telegraf producer/consumer. The consumer is intentionally configured with a tiny metric buffer.

docker-compose.yml:
```
version: "3"
services:
  consumer:
    depends_on:
      - rabbitmq
    image: telegraf:1.22.3
    networks:
      - telegraf
    restart: on-failure
    volumes:
      - ./telegraf-consumer.conf:/etc/telegraf/telegraf.conf

  rabbitmq:
    image: rabbitmq:3.8.9-management
    networks:
      - telegraf
    ports:
      - "15672:15672"

  producer:
    depends_on:
      - rabbitmq
    image: telegraf:1.22.3
    networks:
      - telegraf
    volumes:
      - ./telegraf-producer.conf:/etc/telegraf/telegraf.conf
    ports:
      - "8126:8125/udp"

networks:
  telegraf:
```

telegraf-producer.conf:
```
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.amqp]]
   brokers = ["amqp://rabbitmq:5672/"]
   exchange = "telegraf"
    exchange_type = "fanout"
    exchange_durability = "transient"
    username = "guest"
    password = "guest"
    use_batch_format = true
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
```

telegraf-consumer.conf:
```
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 10
  metric_buffer_limit = 10
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = true
[[outputs.exec]]
  command = ["tee", "-a", "/dev/null"]
[[inputs.amqp_consumer]]
   brokers = ["amqp://rabbitmq:5672/"]
    username = "guest"
    password = "guest"
   exchange = "telegraf"
    exchange_type = "fanout"
    exchange_durability = "transient"
   queue = "telegraf-consumer-1"
   queue_durability = "transient"
   binding_key = "#"
    prefetch_count = 1000
```

After running `docker-compose up` and waiting a few minutes, this will be showing in the logs:
```
consumer_1  | 2022-05-10T16:30:35Z W! [outputs.exec] Metric buffer overflow; 4 metrics have been dropped
consumer_1  | 2022-05-10T16:30:45Z W! [outputs.exec] Metric buffer overflow; 21 metrics have been dropped
consumer_1  | 2022-05-10T16:30:55Z W! [outputs.exec] Metric buffer overflow; 21 metrics have been dropped
(...)
```
