### ISSUE TITLE
error parsing OID Value after upgrade from 1.14.4 to 1.18.3

### ISSUE THREAD

**Issue by RemcoAA** [influxdata/telegraf#10240]
### Relevent telegraf.conf

```toml
#Interfaces Information:
  [[inputs.snmp.table]]
    name = "_interface"
    oid = "IF-MIB::ifTable"
    inherit_tags = ["sysname"]
    index_as_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      name = "ifdescr"
      is_tag = true

  [[inputs.snmp.table]]
    name = "_interface"
    oid = "IF-MIB::ifXTable"
    inherit_tags = ["sysname" , "ifdescr"]

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      name = "ifdescr"
      is_tag = true
```

### System info

Telegraf1.18.3, Docker 1.13.1

### Steps to reproduce

After upgrading Telegraf from 1.14.4 to 1.18.3 for one device type the IF-MIB::ifTable metrics are no longer available.

Telegraf is logging the following error:
Error in plugin: agent <device-fqdn>: gathering table _interface: performing bulk walk for field ifSpecific: error in unmarshalResponse: error decoding value: error parsing OID Value: invalid OID length

A snmpwalk on IF-MIB::ifTable gives normal results but when I try the OID in the error I get this:

snmpwalk -v 3 -u xxx -l authPriv -a SHA -A xxx -x AES -X xxx  <device-fqdn> IF-MIB::ifSpecific
IF-MIB::ifSpecific = OID: ccitt

Is this bad implementation of the IF-MIB by this vendor or something in the Telegraf code?

### Expected behavior

Telegraf should process the IF-MIB oid with out any issues, as it has done in v1.14.4.

### Actual behavior

ifTable metrics are not processed for this device type.
