### ISSUE TITLE
MQTT regex patterns

### ISSUE THREAD

**Issue by AndersoLeyendo** [influxdata/telegraf#10250]
Hi everyone, I was wondering if it was possible to replace multiple elements with Regex.

This code work:
```toml
[[processors.regex]]
  namepass = ["mqtt_consumer"]
  order = 1

  [[processors.regex.tags]]
    key = "topic"
    pattern = "^[^/]+/(.*)"
    replacement = "${1}"
 
  [[processors.regex.tags]]
        key = "topic"
        pattern = "inpd4"
        replacement = "temperatura"
```

But that's not enough for me.
I was hoping that such a thing would work but it doesn't ...
```toml
[[processors.regex.tags]]
        key = "topic"
        pattern = ["inpd4", "co2"]
        replacement = ["temperatura", "anidride"]
```

So, the expected result should have been this:
inpd4->temperatura
co2->anidride

And this is my mqtt config:
```toml
data_format = "value"
data_type = "float"
```

**Comment by srebhan** [comment]
I don't get the issue here... In your example above, why not add
```toml
[[processors.regex.tags]]
        key = "topic"
        pattern = "co2"
        replacement = "anidride"
```

Anyway, if you only replace non-regex static values you might also take a look at the [enum processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/enum) or use, as a last resort, starlark...
