### ISSUE TITLE
Using plugins/beat to collect filebeat metrics to prometheus will cause prometheus memory to be full

### ISSUE THREAD

**Issue by yanming-zhang** [influxdata/telegraf#10253]
### Relevent telegraf.conf

```toml
[[inputs.beat]]
    url = "http://$HOSTIP:5066"
    include = ["beat", "libbeat", "system", "filebeat"]
    timeout = "10s"

[[outputs.prometheus_client]]
    listen = ":9273"
```

### System info

telegraf-1.20.4   centos-7.6    kubenetes-1.16.9

### Steps to reproduce

1. Use plugins/beat to collect filebeat metrics to prometheus
2. A large number of indicators similar to the following appear:
beat_filebeat_harvester_files_0066da78_a3af_4ca2_9360_d8372861e5a7_read_offset
beat_filebeat_harvester_files_0066da78_a3af_4ca2_9360_d8372861e5a7_size
3. As a result, the memory occupied by prometheus continues to grow, and the system memory has recently been full

### Expected behavior

I want to collect each type of metrics in beat, libbeat, system, and filebeat:
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/beat

### Actual behavior

![image](https://user-images.githubusercontent.com/11608532/145509882-8673df91-b926-4067-a1bb-c286d396fdc9.png)
