### ISSUE TITLE
inputs_mysql.conf gather perf events is false. Still generating mysql perf metrics.

### ISSUE THREAD

**Issue by rmharrisva** [influxdata/telegraf#10251]
### Relevent telegraf.conf

```toml
# # Read metrics from one or many mysql servers
[[inputs.mysql]]

#   ## specify servers via a url matching:
#   ##  [username[:password]@][protocol[(address)]]/[?tls=[true|false|skip-verify]]
#   ##  see https://github.com/go-sql-driver/mysql#dsn-data-source-name
#   ##  e.g.
#   ##    servers = ["user:passwd@tcp(127.0.0.1:3306)/?tls=false"]
#   ##    servers = ["user@tcp(127.0.0.1:3306)/?tls=false"]
#   #

#   #####
#   ##### THE USERID NEEDS TO HAVE THE "SELECT" AND "PROCESS"
#   ##### PRIVILEGES FOR THIS PLUGIN TO WORK.
#   #####     - RMH
#   #####
#   ## If no servers are specified, then localhost is used as the host.
   servers = ["xxxx:xxxx@tcp(127.0.0.1:3306)/"]
#   ## the limits for metrics form perf_events_statements
#   ##### TRUST ME. WE WANT TO DIAL THIS BACK A TAD.
#   ##### THESE PERF METRICS ARE VOLUMOUS. - RMH
#   perf_events_statements_digest_text_limit  = 30
#   perf_events_statements_limit              = 75
#   perf_events_statements_time_limit         = 7200
#   #
#   ## if the list is empty, then metrics are gathered from all databasee tables
   table_schema_databases                    = []
#   #
#   ## gather metrics from INFORMATION_SCHEMA.TABLES for databases provided above list
   gather_table_schema                       = false
#   #
#   ## gather thread state counts from INFORMATION_SCHEMA.PROCESSLIST
   gather_process_list                       = true
#   #
#   ## gather thread state counts from INFORMATION_SCHEMA.USER_STATISTICS
#   ##### NOT SETUP - RMH
   gather_user_statistics                    = false
#   #
#   ## gather auto_increment columns and max values from information schema
#   ##### TOO VERBOSE - RMH
   gather_info_schema_auto_inc               = false
#   #
#   ## gather metrics from INFORMATION_SCHEMA.INNODB_METRICS
   gather_innodb_metrics                     = true
#   #
#   ## gather metrics from SHOW SLAVE STATUS command output
#  ##### IF THE DB IS THE MASTER, THIS DOES NOTHING.  - RMH
   gather_slave_status                       = true
#   #
#   ## gather metrics from SHOW BINARY LOGS command output
#   ##### DO NOT NEED. - RMH
   gather_binary_logs                        = false
#   #
#   ## gather metrics from PERFORMANCE_SCHEMA.TABLE_IO_WAITS_SUMMARY_BY_TABLE
   gather_table_io_waits                     = true
#   #
#   ## gather metrics from PERFORMANCE_SCHEMA.TABLE_LOCK_WAITS
   gather_table_lock_waits                   = true
#   #
#   ## gather metrics from PERFORMANCE_SCHEMA.TABLE_IO_WAITS_SUMMARY_BY_INDEX_USAGE
   gather_index_io_waits                     = true
#   #
#   ## gather metrics from PERFORMANCE_SCHEMA.EVENT_WAITS
   gather_event_waits                        = true
#   #
#   ## gather metrics from PERFORMANCE_SCHEMA.FILE_SUMMARY_BY_EVENT_NAME
#   ##### DO NOT NEED. - RMH
   gather_file_events_stats                  = false
#   #
#   ## gather metrics from PERFORMANCE_SCHEMA.EVENTS_STATEMENTS_SUMMARY_BY_DIGEST
#   ##### VERY VERBOSE - RMH
   gather_perf_events_statements             = false
#   #
#   ## Some queries we may want to run less often (such as SHOW GLOBAL VARIABLES)
   interval_slow                   = "30m"
```

### System info

Telegraf 1.19.1, Centos 7.9

### Steps to reproduce

1. Make sure inputs_mysql.conf the following statements are set as follows:

```
#   perf_events_statements_digest_text_limit  = 30
#   perf_events_statements_limit              = 75
#   perf_events_statements_time_limit         = 7200
   gather_perf_events_statements             = false
```

2. Restart Telegraf
3.  curl -s http://127.0.0.1:9126/metrics | grep -i mysql | grep perf | grep -v '^\#' | wc -l
`The result I got was 9557.`

### Expected behavior

The result should have been 0

### Actual behavior

Depending which of our MySQL servers one runs the above `curl ... | wc -l`  commands the result is usually between 5000 and 10000.

### Additional info

We detected this after we upgraded to Telegraf 1.19.1 on all of our slave database servers. The `mysql_slave_Slave_SQL_Running` metric disappeared. To correct this we increased the `metric_buffer_limit` from 10000 to 50000 on all of our MySQL servers.
