### ISSUE TITLE
[outputs][sql] Error occurred when the metric with different data format output to rdb

### ISSUE THREAD

**Issue by ElapsedSoul** [influxdata/telegraf#10264]
### Relevent telegraf.conf

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 30
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "101.83"
  omit_hostname = false
[[outputs.sql]]
  ## Database driver
  ## Valid options: mssql (Microsoft SQL Server), mysql (MySQL), pgx (Postgres),
  ##  sqlite (SQLite3), snowflake (snowflake.com)
  driver = "pgx"

  ## Data source name
  ## The format of the data source name is different for each database driver.
  ## See the plugin readme for details.
  data_source_name = "postgres://user:password@10.20.xxx.xx:5432/newdb"

  ## Timestamp column name
  timestamp_column = "timestamp"

  ## Table creation template
  ## Available template variables:
  ##  {TABLE} - table name as a quoted identifier
  ##  {TABLELITERAL} - table name as a quoted string literal
  ##  {COLUMNS} - column definitions (list of quoted identifiers and types)
  table_template = "CREATE TABLE {TABLE}({COLUMNS})"

  ## Table existence check template
  ## Available template variables:
  ##  {TABLE} - tablename as a quoted identifier
  table_exists_template = "SELECT 1 FROM {TABLE} LIMIT 1"

  ## Initialization SQL
  # init_sql = ""

  ## Metric type to SQL type conversion
  [outputs.sql.convert]
    integer              = "BIGINT"
    real                 = "FLOAT"
    text                 = "TEXT"
    timestamp            = "TIMESTAMP"
    defaultvalue         = "TEXT"
    unsigned             = ""
    bool                 = "BOOL"
[[outputs.http]]
#   ## URL is the address to send metrics to
   url = "http://10.20.xxx.xx:6041/telegraf/udp"
#
#   ## Timeout for HTTP message
#   # timeout = "5s"
#
#   ## HTTP method, one of: "POST" or "PUT"
    method = "POST"
#
#   ## HTTP Basic Auth credentials
    username = "root"
    password = "xxxxxxx"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.http_listener_v2]]
  service_address = ":8080"
  path = "/telegraf"
  methods = ["POST", "PUT"]
  data_format = "influx"
```

### System info

Telegraf 1.21.0-5cb99391 (git: master 5cb99391),centos7

### Steps to reproduce

```./telegraf -config ./telegraf.conf```

### Expected behavior

data record insert into the postgres

### Actual behavior

```
Dec 14 13:21:38 bigdata-01 telegraf[30266]: 2021-12-14T05:21:38Z E! [agent] Error writing to outputs.sql: 错误: 关系 "system" 的 "uptime" 字段不存在 (SQLSTATE 42703)
```

### Additional info

I use outputs.http to print log to get the metics format like this followed:
```
system,host=101.83 load1=0.15,load5=0.06,load15=0.06,n_cpus=8i,n_users=2i 1639465920000000000
system,host=101.83 uptime=80956i 1639465920000000000
```
which means it's nosql data, when the data insert into a rdb, the same table must have a different table structure, so we get the error like this followed:
```
2021-12-14T07:30:31Z E! [outputs.sql] Error during insert: 错误: 关系 "system" 的 "uptime" 字段不存在 (SQLSTATE 42703), INSERT INTO "system"("timestamp","host","uptime") VALUES($1,$2,$3)
2021-12-14T07:30:31Z E! [agent] Error writing to outputs.sql: 错误: 关系 "system" 的 "uptime" 字段不存在 (SQLSTATE 42703)
```
