### ISSUE TITLE
aggregators.merge causes processing loop

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#10261]
### Relevent telegraf.conf

```toml
[agent]
interval = "1s"
flush_interval = "1s"
round_interval=false

[[outputs.file]]
  files = ["stdout"]

[[inputs.exec]]
commands=["echo test,i=0 a=0i"]
data_format="influx"

[[processors.execd]]
command=["perl","-pe","$|++; s/i=(\\d+)/\"i=\" . ($1 + 1)/e"]

[[aggregators.merge]]   
delay = "10ms"
period = "500ms"
grace = "1h"
drop_original = true
```

### System info

Telegraf 5cb9939

### Steps to reproduce

1. Run the above config

### Expected behavior

Should emit metrics with `i=1`.

### Actual behavior

Emits metrics with `i=2`.
