### ISSUE TITLE
shim trigger output to write single metric

### ISSUE THREAD

**Issue by dkuk** [influxdata/telegraf#10277]
### Relevent telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "10s"
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = ""
  omit_hostname = false

[[outputs.execd]]
  command = ["/home/esb/click-output", "-config", "/home/esb/click-metrics.conf"]
  namepass = ["esb_snd", "esb_rcv", "esb_queue"]
  tagexclude = ["ep","host","path"]
  metric_batch_size = 1000
```

### System info

telegraf 1.20.4

### Steps to reproduce

Make an output plugin.

Output triggers every 10 seconds, but batch size for every call is 1 metric.

Simple output plugin triggers write on each metric

```go
func (c *ClickhouseClient) Write(metrics []telegraf.Metric) (err error) {
        // Check for batch size
        log.Printf("Metrics batch %+v", len(metrics))
        return err
}
```

telegraf log
```log
2021-12-15T03:50:53Z D! [outputs.execd] Wrote batch of 133 metrics in 989.756µs
2021-12-15T03:50:53Z E! [outputs.execd] stderr: 2021/12/15 13:50:53 Metrics batch 1
```

Shim scans batch per line and triggers write output for each metric ? 
(https://github.com/influxdata/telegraf/blob/e97a15d7e716bb3d40e33af62974851c1f381c53/plugins/common/shim/output.go#L41)

### Expected behavior

https://github.com/influxdata/telegraf/blob/master/docs/OUTPUTS.md

Metrics should pass to write equal to metric_batch_size or all metrics collected before flush_interval + rand(flush_jitter)

### Actual behavior

Single write call for every metric in batch.
