### ISSUE TITLE
Groundwork doesn't handle string metrics and payload without NextCheckTime and StartTime

### ISSUE THREAD

**Issue by VladislavSenkevich** [influxdata/telegraf#10278]
### Relevent telegraf.conf

```toml
# Send telegraf metrics to GroundWork Monitor
[[outputs.groundwork]]
  ## URL of your groundwork instance.
  url = "http://groundwork:8080"
  ## Agent uuid for GroundWork API Server.
  agent_id = "a0eeddb0-ed82-4d62-8320-0882579b6260"
  ## Username and password to access GroundWork API.
  username = "SECRET"
  password = "SECRET"
  
  ## Default display name for the host with services(metrics).
  # default_host = "telegraf"
  ## Default service state.
  # default_service_state = "SERVICE_OK"
  ## The name of the tag that contains the hostname.
  resource_tag = "resource"
```

### System info

Telegraf 1.20.4, Ubuntu 20.04, Docker 20.10.7, Groundwork 8.2.1

### Steps to reproduce

1. Connect the 'groundwork' output plugin with any Groundwork instance
2. Open the Groundwork -> Status -> Dashboard page on your Groundwork instance UI

### Expected behavior

Resource and services from telegraf plugin must be displayed

### Actual behavior

Resources and services from telegraf plugin not displayed
