### ISSUE TITLE
can not index elasticsearch_cluster_health

### ISSUE THREAD

**Issue by marszhang-sha** [influxdata/telegraf#10280]
### Relevent telegraf.conf

```toml
[[inputs.elasticsearch]]
      servers = ["http://server:9200"]
      username = "**"
      password = "**"
      interval = "60s"
      local = false
      cluster_health = true
      cluster_health_level = "indices"
      cluster_stats = true
      node_stats = ["indices", "os", "jvm", "http", "fs", "process", "transport"]


    [[outputs.elasticsearch]]
      urls = [ "server:9200" ]
      timeout = "30s"
      enable_sniffer = false
      health_check_interval = "10s"
      username = "**"
      password = "**"
      index_name = "telegraf-elastic-%Y.%m" # required.

      ## Optional TLS Config
      # tls_ca = "/etc/telegraf/ca.pem"
      # tls_cert = "/etc/telegraf/cert.pem"
      # tls_key = "/etc/telegraf/key.pem"
      ## Use TLS but skip chain & host verification
      # insecure_skip_verify = false

      manage_template = true
      template_name = "telegraf-elastic"
      overwrite_template = true
      force_document_id = false
```

### System info

telegraf 1.20.4 aliyun k8s 1.18.8

### Steps to reproduce

1.start the telegraf pod 
2.pod log

> 2021-12-16T05:44:05Z E! Elasticsearch indexing failure, id: 0, error: unknown parameter [norms] on mapper [timed_out] of type [null], caused by: %!s(<nil>), %!s(<nil>)
>2021-12-16T05:44:05Z E! [agent] Error writing to outputs.elasticsearch: W! Elasticsearch failed to index 13 metrics

3. search the indice, can not find elasticsearch_cluster_health, while the other elasticsearch_fs, elasticsearch_os, elasticsearch_http exist.

### Expected behavior

elasticsearch_cluster_health has been indexed

### Actual behavior

elasticsearch_cluster_health is not indexed
