### ISSUE TITLE
Problem with inputs.tail as of 1.21.0

### ISSUE THREAD

**Issue by aarontroot** [influxdata/telegraf#10292]
### Relevent telegraf.conf

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://xxxx:8086"]
  database = "telegraf"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
[[inputs.sensors]]
[[inputs.tail]]
  files = ["/var/log/PhoenixMiner/log*.txt"]
  from_beginning = false
  data_format = "grok"
  name_override = "gpu_total_power"
  tagexclude = ["path"]
  grok_timezone = "America/Denver"
  grok_patterns = ["%{GPUTOTALPOWER}"]
  grok_unique_timestamp = "disable"
  grok_custom_patterns = '''
    GPUTOTALPOWER ^GPUs power: %{BASE10NUM:gpu_total_power:float} W$
  '''
```

### System info

Telegraf 1.21.0-1, Ubuntu 20.04.3 LTS

### Steps to reproduce

1. sudo -u telegraf /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --test

### Expected behavior

Normal startup

### Actual behavior

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7c8b5f]

goroutine 32 [running]:
github.com/influxdata/telegraf/plugins/parsers/grok.(*Parser).ParseLine(0xc000b2e960, {0xc0012000a0, 0x4a})
	/go/src/github.com/influxdata/telegraf/plugins/parsers/grok/parser.go:213 +0x2ff
github.com/influxdata/telegraf/plugins/parsers/grok.(*Parser).Parse(0x44ab40, {0xc001200050, 0x4a, 0x50})
	/go/src/github.com/influxdata/telegraf/plugins/parsers/grok/parser.go:386 +0x15c
github.com/influxdata/telegraf/plugins/inputs/tail.parseLine({0x577f6b0, 0xc000b2e960}, {0xc001200000, 0x0})
	/go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:303 +0x10f
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).receiver(0xc0005aa900, {0x577f6b0, 0xc000b2e960}, 0xc00081e2c0)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:371 +0x4f4
github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles.func2()
	/go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:275 +0x85
created by github.com/influxdata/telegraf/plugins/inputs/tail.(*Tail).tailNewFiles
	/go/src/github.com/influxdata/telegraf/plugins/inputs/tail/tail.go:273 +0x7af

### Additional info

This was working fine until the 1.21.0 update
