### ISSUE TITLE
DPDK input plugin socket connection failure causes Telegraf service failure

### ISSUE THREAD

**Issue by Pengozoid** [influxdata/telegraf#10291]
### Relevent telegraf.conf

```toml
[global_tags]

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://192.168.1.2:8186"]
  database = "telegraf"
  timeout = "5s"

[[inputs.dpdk]]
  socket_path = "/var/run/dpdk/rte/dpdk_telemetry.v2"
  socket_access_timeout = "200ms"
  device_types = ["ethdev"]
  [inputs.dpdk.ethdev]
    exclude_commands = ["/ethdev/link_status"]
```

### System info

telegraf-1.21.0-1.x86_64.rpm (run as root), CentOS 7.4, DPDK 20.11.0

### Steps to reproduce

1. Make stats socket unavailable (stop DPDK application; or specify many sections in telegraf.conf for DPDK apps with different paths to sockets)
2. Restart Telegraf:
`systemctl restart telegraf`
3. Telegraf service fails.

### Expected behavior

Plugin fails to connect to the DPDK stats socket producing error message in Telegraf log, but Telegraf service keeps running.

### Actual behavior

Telegraf service fails.

### Additional info

```
дек 16 09:03:49 vDPDK telegraf[24087]: 2021-12-16T14:03:49Z E! [telegraf] Error running agent: could not initialize input inputs.dpdk: failed to connect to the socket - dial unixpacket /var/run/dpdk/rte/dpdk_telemetry.v2: connect: connection refused
дек 16 09:03:49 vDPDK systemd[1]: telegraf.service: main process exited, code=exited, status=1/FAILURE
дек 16 09:03:49 vDPDK systemd[1]: Unit telegraf.service entered failed state.
дек 16 09:03:49 vDPDK systemd[1]: telegraf.service failed.
```
