### ISSUE TITLE
Telegraf 1.21.0 - issue with SNMP plugin

### ISSUE THREAD

**Issue by bondskin** [influxdata/telegraf#10290]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  # List of agents to poll
  agents = [ "tardis.ip", "flash.ip", "dreamer.ip", "batman.ip", "millenniumfalcon.ip" , "area51.ip"]
  # Polling interval
  interval = "60s"
  # Timeout for each SNMP query.
  timeout = "10s"
  # Number of retries to attempt within timeout.
  retries = 3
  # SNMP version
  version = 2
  # SNMP community string.
  community = "public"
  # Measurement name
  name = "snmp.UAP"
  ##
  ## System Details
  ##
  #  System name (hostname)
```

### System info

Raspbian, Telegraf 1.21.0

### Docker

no

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

should work as before with 1.20.4

MIB file unchanged:
pi@raspberrypidns:/etc/telegraf/telegraf.d $ ll /var/lib/mibs/ietf/DPI20-MIB
-rw-r--r-- 1 root root 1683 25. Dez 2020  /var/lib/mibs/ietf/DPI20-MIB

### Actual behavior

Dez 16 14:52:13 raspberrypidns telegraf[18888]: Parse module: /var/lib/mibs/ietf/DPI20-MIB:9:4: unexpected "ibm" (expected ";")
Dez 16 14:52:13 raspberrypidns telegraf[18888]: 2021-12-16T13:52:13Z W! [inputs.snmp] Could not load module at DPI20-MIB
Dez 16 14:52:16 raspberrypidns telegraf[18888]: Parse module: /var/lib/mibs/ietf/HPR-MIB:494:30: unexpected "HprRtpCounter" (expected "}")
Dez 16 14:52:16 raspberrypidns telegraf[18888]: 2021-12-16T13:52:16Z W! [inputs.snmp] Could not load module at HPR-MIB
