### ISSUE TITLE
SNMP Traps from Juniper not fully translated

### ISSUE THREAD

**Issue by hkml2000** [influxdata/telegraf#10309]
### Relevent telegraf.conf

```toml
[[inputs.snmp_trap]]
  service_address = "udp://:162"
  path = ["/usr/share/snmp/mibs"]
  timeout = "10s"
  version = "2c"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### System info

Telegraf 1.21.1

### Steps to reproduce

1. put Juniper MIB files into /usr/share/snmp/mibs

2. start telegraf using above config

3. send snmptrap  using "snmptrap -v 2c -c public **telegraf_server_ip** '' .1.3.6.1.4.1.2636.3.53.1.2.1.1"

4. observe the output from telegraf :  
snmp_trap,community=public,host=xxxxxx,mib=**JUNIPER-SMI**, name=**jnxL2cpMibRoot**,oid=.1.3.6.1.4.1.2636.3.53.1.2.1.1,source=x.x.x.x,version=2c sysUpTime=130777096i 1640015154364309647
translation don't go beyond JUNIPER-SMI MIB

5. using snmptranslate command  with the same OID :  
snmptranslate 1.3.6.1.4.1.2636.3.53.1.2.1.1 
==> we obtain: JUNIPER-L2CP-FEATURES-MIB::**jnxLacpTimeOut**

### Expected behavior

load all MIBs to fully translate snmp traps

### Actual behavior

partial snmp trap translation, seems like not all MIBs from path are loaded
