### ISSUE TITLE
Feature to add suffix and prefix to tag value

### ISSUE THREAD

**Issue by aratik711** [influxdata/telegraf#10308]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add a feature under strings processor to add suffix and prefix to the value of the specified tag key
### Current behavior:
This feature is not available currently
### Desired behavior:
The suffix/prefix mentioned in conf should be added to the value of the specified tag
```
[[processors.strings]]
  [[processors.strings.add_prefix]]
    tag = "host"
    prefix = "new-"
  [[processors.strings.add_suffix]]
    tag = "env"
    suffix = "-stg"
```
    
 ### Expected output

 Sample input
 `host=myhost.local env=US-east http_version=1.1 1519652321000000000`
 Sample output
 `host=new-myhost.local env=US-east-stg http_version=1.1 1519652321000000000`
 
### Use case: 
This request came up when we tried using grafana to retrive tag_values(), which kept on giving a React error.
The changes have already been tested by me locally.

**Comment by srebhan** [comment]
Hey @aratik711,

I think this should be possible using the [`regex` processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex) with e.g.
```toml
[[processors.regex]]
  [[processors.regex.tags]]
    key = "host"
    pattern = "^(.*)$"
    replacement = "new-${1}"

  [[processors.regex.tags]]
    key = "env"
    pattern = "^(.*)$"
    replacement = "${1}-stg"
```
