### ISSUE TITLE
Error in SNMP Plugin

### ISSUE THREAD

**Issue by toketsai** [influxdata/telegraf#10306]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
agents = [
"192.168.1.1"
]
version = 2
community = "public"

[[inputs.snmp.field]]
name = "InterfaceStatus"
oid = 'F5-BIGIP-SYSTEM-MIB::sysInterfaceStatus."1.0"'
```

### System info

1.20.0

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

get value

### Actual behavior

_snmpget -v2c -c public 192.168.1.1 'F5-BIGIP-SYSTEM-MIB::sysInterfaceStatus."1.0"'_  can get value.
Actually,it losts all metrics
