### ISSUE TITLE
Telegraf 1.21.1: Marshal error with SNMP PowerNet MIB

### ISSUE THREAD

**Issue by Doridian** [influxdata/telegraf#10304]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "SNIP" ]
  version = 2
  community = "SNIP"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"

  [[inputs.snmp.field]]
    name = "model"
    oid = "PowerNet-MIB::upsBasicIdentModel.0"

  [[inputs.snmp.field]]
      name = "name"
      oid = "PowerNet-MIB::upsBasicIdentName.0"

  [[inputs.snmp.field]]
      name = "upsBasicBatteryTimeOnBattery"
      oid = "PowerNet-MIB::upsBasicBatteryTimeOnBattery.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryRunTimeRemaining"
      oid = "PowerNet-MIB::upsAdvBatteryRunTimeRemaining.0"

  [[inputs.snmp.field]]
      name = "upsAdvBatteryReplaceIndicator"
      oid = "PowerNet-MIB::upsAdvBatteryReplaceIndicator.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecBatteryCapacity"
      oid = "PowerNet-MIB::upsHighPrecBatteryCapacity.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecBatteryTemperature"
      oid = "PowerNet-MIB::upsHighPrecBatteryTemperature.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsBasicOutputStatus"
      oid = "PowerNet-MIB::upsBasicOutputStatus.0"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputLoad"
      oid = "PowerNet-MIB::upsHighPrecOutputLoad.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputEfficiency"
      oid = "PowerNet-MIB::upsHighPrecOutputEfficiency.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputVoltage"
      oid = "PowerNet-MIB::upsHighPrecOutputVoltage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecInputLineVoltage"
      oid = "PowerNet-MIB::upsHighPrecInputLineVoltage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputCurrent"
      oid = "PowerNet-MIB::upsHighPrecOutputCurrent.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsHighPrecOutputEnergyUsage"
      oid = "PowerNet-MIB::upsHighPrecOutputEnergyUsage.0"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "upsAdvOutputActivePower"
      oid = "PowerNet-MIB::upsAdvOutputActivePower.0"
      conversion = "float(0)"

  [[inputs.snmp.field]]
      name = "upsAdvOutputApparentPower"
      oid = "PowerNet-MIB::upsAdvOutputApparentPower.0"
      conversion = "float(0)"
```

### System info

Telegraf 1.21.1

### Steps to reproduce

1. Put this config in
2. Wait for it to pull
3. Observe error `2021-12-18T08:06:00Z E! [inputs.snmp] Error in plugin: agent SNIP: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier`

### Expected behavior

It works

### Actual behavior

`2021-12-18T08:06:00Z E! [inputs.snmp] Error in plugin: agent SNIP: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier`

### Additional info

This uses the PowerNet MIB from APC's website: https://www.apc.com/shop/us/en/products/PowerNet-MIB-v4-3-2/P-SFPMIB432
There is no errors loading the MIB, and playing around with gosmi's commandline tools and small test programs with it, it seems to be able to translate the descriptions to OIDs correctly.

This used to work before the switch to gosmi. Other MIBs (such as UPS-MIB) work fine.

Also worthy of note if I replace the string representations (`PowerNet-MIB::...`) with their full numeric representation, these errors vanish
