### ISSUE TITLE
Marshal error with SNMP plugin 1.21.0

### ISSUE THREAD

**Issue by mabnz** [influxdata/telegraf#10305]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "udp://fgt01:161" ]
  version = 2
  timeout = "5s"
  retries = 3
  community = "public"
  name = "fortisnmp"

	[[inputs.snmp.field]]
		name = "hostname"
		oid = "SNMPv2-MIB::sysName.0"
		is_tag = true

	[[inputs.snmp.field]]
		name = "cpu"
		oid = "FORTINET-FORTIGATE-MIB::fgSysCpuUsage.0"

	[[inputs.snmp.field]]
		name = "memory"
		oid = "FORTINET-FORTIGATE-MIB::fgSysMemUsage.0"
```

### System info

Telegraf 1.20.0, Ubuntu 20.04.3.

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

No errors.

### Actual behavior

After upgrade to 1.21.0, the snmp agent is having trouble fetching certain OIDs.

```
telegraf[505949]: 2021-12-18T21:14:00Z E! [inputs.snmp] Error in plugin: agent 192.168.62.11:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:00Z E! [inputs.snmp] Error in plugin: agent 192.168.60.122:161: performing get on field model: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.60.1:161: performing get on field cpu: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.62.10:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
telegraf[505949]: 2021-12-18T21:14:10Z E! [inputs.snmp] Error in plugin: agent 192.168.62.11:161: performing get on field signal: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier

```
