### ISSUE TITLE
inputs.file not working as stated

### ISSUE THREAD

**Issue by Wnthr** [influxdata/telegraf#10330]
### Relevent telegraf.conf

```toml
[agent]
precision = "s"

[[inputs.file]]
files = ["/var/log/chrony/measurements.log"]
from_beginning = true
pipe = false
max_undelivered_lines = 1000
character_encoding = "utf-8" 
data_format = "grok"
grok_patterns = ["%{CHRONY_MEASUREMENTS_LOG_FORMAT}"]
grok_custom_pattern_files = ["/etc/telegraf/patterns/chrony"]
grok_timezone = "UTC"
path_tag = "path"

[[outputs.influxdb_v2]]
urls = ["http://..."]
...
```

### Logs from Telegraf

# telegraf --debug --config-directory=/etc/telegraf/telegraf.d/
2021-12-22T15:36:22Z I! Starting Telegraf 1.18.3
2021-12-22T15:36:22Z I! Using config file: /etc/telegraf/telegraf.conf
2021-12-22T15:36:22Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/chrony_measurements.conf: plugin inputs.file: line 4: configuration specified the fields ["from_beginning" "max_undelivered_lines" "pipe" "path_tag"], but they weren't used

### System info

Telegraf 1.18.3-1.21.1 Gentoo Linux

### Steps to reproduce

1. # telegraf --debug --config-directory=/etc/telegraf/telegraf.d/ 
2. Error message as above shows up
3. No profit
...

### Expected behavior

Telegraf would start and use the documented configuration (start from beginning, last 1000 lines, utf-8 and so forth.

### Actual behavior

Error message claiming the configuration items documented in the readme are not used, after which telegraf then quits without running.
