### ISSUE TITLE
ping_interval won't override agent

### ISSUE THREAD

**Issue by junior466** [influxdata/telegraf#10359]
### Relevent telegraf.conf

```toml
[[inputs.ping]]
  urls = ["google.com"]
  count = 1
  ping_interval = 300.0
  timeout = 5.0
```

### Logs from Telegraf

...

### System info

Ubuntu 20.04

### Steps to reproduce

1.Ping
2.
3.
...

### Expected behavior

Ping be send every 300s. 

### Actual behavior

Ping is being sent at 10s interval as per agent. 

### Additional info

My files are split into multiple files located at `/etc/telegraf/telegraf.d`.
