### ISSUE TITLE
[inputs.vsphere] Unable to find metric name for id 355. Skipping!

### ISSUE THREAD

**Issue by pradig** [influxdata/telegraf#10350]
### Relevent telegraf.conf

```toml
[[inputs.vsphere]]
  vcenters = [ "https://xxx.yyy.net/sdk" ]
  username = "collector@xxx.net"
  password = "collector"
  insecure_skip_verify = true
```

### Logs from Telegraf

Dec 27 12:48:50 orfeo telegraf[10823]: 2021-12-27T12:48:50Z I! [inputs.vsphere] Unable to find metric name for id 355. Skipping!

### System info

Telegraf 1.21.1 (git: HEAD 7c9a9c17), Linux 5.4.0-91-generic #102-Ubuntu SMP

### Steps to reproduce

Connect to vCenter 7.0.3-18778458
Start plugin

### Expected behavior

No error in syslog

### Actual behavior

Error in syslog
