### ISSUE TITLE
json_v2 fails if input data contains null values

### ISSUE THREAD

**Issue by igomura** [influxdata/telegraf#10358]
### Relevent telegraf.conf

```toml
[[inputs.file]]
  files = ["config.json"]
  data_format = "json_v2"

  [[inputs.file.json_v2]]
    measurement_name = "info.config"
    [[inputs.file.json_v2.object]]
      path = "config"
```

### Logs from Telegraf

2021-12-30T21:56:57Z E! [inputs.file] Error in plugin: unknown format '<nil>' for field  'storage_redis_caCertificates'

### System info

telegraf-1.19.0-0.1.x86_64, CentOS 7

### Steps to reproduce

Input data file:
`{
  "config": {
    "apikey": "*",
    "ipAddressEnabled": true,
    "initialization": {
      "timeoutMS": 10000,
      "forceFreshStartup": false
    },
    "storage": {
      "type": "redis",
      "redis": {
        "host": "localhost",
        "port": 6379,
        "tlsServerName": "",
        "caCertificates": null,
        "tlsSkipNameValidation": false,
        "tlsClientCertificate": "",
        "tlsClientKey": ""
      }
    }
  }
}
`

### Expected behavior

parsed data

### Actual behavior

the plugin fail to read data when one of json attributes has a value *null*
In my example this is `"caCertificates": null`
