### ISSUE TITLE
Jolokia2 weblogic.conf - Weblogic Specific Metrics not working

### ISSUE THREAD

**Issue by utsukprani** [influxdata/telegraf#10362]
### Relevent telegraf.conf

```toml
[[inputs.jolokia2_agent]]
 urls = ["http://x.x.x.x:8778/jolokia/"]
 name_prefix = "weblogic."
 name_override="custom_jolokia_weblogic_xxxx"

 [inputs.jolokia2_agent.tags]
    monitor = "JMX"
    level1 = "NONPROD"

### JVM Generic Metrics

 [[inputs.jolokia2_agent.metric]]
    name  = "OperatingSystem"
    mbean = "java.lang:type=OperatingSystem"
    paths = ["ProcessCpuLoad","SystemLoadAverage","SystemCpuLoad"]

 [[inputs.jolokia2_agent.metric]]
    name  = "jvm_runtime"
    mbean = "java.lang:type=Runtime"
    paths = ["Uptime"]

 [[inputs.jolokia2_agent.metric]]
    name  = "jvm_memory"
    mbean = "java.lang:type=Memory"
    paths = ["HeapMemoryUsage", "NonHeapMemoryUsage", "ObjectPendingFinalizationCount"]

### WLS Metrics

 [[inputs.jolokia2_agent.metric]]
    name = "JTARuntime"
    mbean = "com.bea:Name=JTARuntime,ServerRuntime=*,Type=JTARuntime"
    paths =["SecondsActiveTotalCount","TransactionRolledBackTotalCount","TransactionRolledBackSystemTotalCount","TransactionRolledBackAppTotalCount","TransactionRolledBackResourceTotalCount","TransactionHeuristicsTotalCount","TransactionAbandonedTotalCount","TransactionTotalCount","TransactionRolledBackTimeoutTotalCount","ActiveTransactionsTotalCount","TransactionCommittedTotalCount"]
    tag_keys   = ["ServerRuntime"]
    tag_prefix = "wls_"
```

### Logs from Telegraf

2022-01-01T18:13:51Z I! Starting Telegraf 1.20.0
2022-01-01T18:13:51Z D! [agent] Initializing plugins
2022-01-01T18:13:51Z D! [agent] Starting service inputs
2022-01-01T18:13:51Z D! [agent] Stopping service inputs
2022-01-01T18:13:51Z D! [agent] Input channel closed
2022-01-01T18:13:51Z D! [agent] Processor channel closed
2022-01-01T18:13:51Z D! [agent] Processor channel closed
2022-01-01T18:13:51Z D! [agent] Stopped Successfully
> weblogic.custom_jolokia_weblogic_xxxx,jolokia_agent_url=http://x.x.x.x:8778/jolokia/,level1=NONPROD,monitor=JMX ProcessCpuLoad=0.0013271863649063984,SystemCpuLoad=0.09316221948462643,SystemLoadAverage=0.78 1641060832000000000
> weblogic.custom_jolokia_weblogic_xxxx,jolokia_agent_url=http://x.x.x.x:8778/jolokia/,level1=NONPROD,monitor=JMX Uptime=242102807 1641060832000000000
> weblogic.custom_jolokia_weblogic_xxxx,jolokia_agent_url=http://x.x.x.x:8778/jolokia/,level1=NONPROD,monitor=JMX HeapMemoryUsage.committed=953155584,HeapMemoryUsage.init=536870912,HeapMemoryUsage.max=1908932608,HeapMemoryUsage.used=597336808,NonHeapMemoryUsage.committed=441737216,NonHeapMemoryUsage.init=2555904,NonHeapMemoryUsage.max=-1,NonHeapMemoryUsage.used=432062952,ObjectPendingFinalizationCount=0 1641060832000000000

### System info

Telegraf 1.20, Weblogic 12.2.1, Red Hat Linux Enterprise 7.9

### Steps to reproduce

1. Create conf file
2. Run /usr/bin/telegraf -config custom_jolokia_weblogic.conf --test --debug

### Expected behavior

I was expecting to see the Weblogic Specific metric in the response. However it seems that these metrics are not getting collected.

### Actual behavior

Only JRE specific metrics are coming.

### Additional info

I am using the Jolokia2 JVM agent and attaching it to the already running Weblogic Server process by:
java -jar jolokia-jvm-1.7.1.jar --host x.x.x.x 7876
