### ISSUE TITLE
blank spaces not parsed in statsd data

### ISSUE THREAD

**Issue by rudigerlove** [influxdata/telegraf#10372]
### Relevent telegraf.conf

```toml
[[inputs.statsd]]
  protocol = "tcp"
  service_address = ":8182"
  delete_gauges = true
  ## Reset counters every interval (default=true)
  delete_counters = true
  ## Reset sets every interval (default=true)
  delete_sets = true
  ## Reset timings & histograms every interval (default=true)
  delete_timings = true
  

  allowed_pending_messages = 1000000
  ## Percentiles to calculate for timing & histogram stats.
  percentiles = [50.0, 90.0, 99.0, 99.9, 99.95, 100.0]

  ## separator to use between elements of a statsd metric
  metric_separator = "/"
  separator = "/"
  datadog_extensions = true
  #added graphite to check if it changes something but still not parsed
  data_format = "graphite" 


  templates = [
    "*.*.*.*.*  measurement.server.measurement.interface.field*"
  ]
```

### Logs from Telegraf

ctrcoll01:/data/TEMP/SRI# ./telegraf --debug --config ./telegraf.conf 
2022-01-04T13:51:07Z I! Starting Telegraf 1.19.3
2022-01-04T13:51:07Z I! Loaded inputs: statsd
2022-01-04T13:51:07Z I! Loaded aggregators: 
2022-01-04T13:51:07Z I! Loaded processors: 
2022-01-04T13:51:07Z I! Loaded outputs: file
2022-01-04T13:51:07Z I! Tags enabled: host=ctrlcoll01 site=Collector0X
2022-01-04T13:51:07Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ctrlcoll01", Flush Interval:10s
2022-01-04T13:51:07Z D! [agent] Initializing plugins
2022-01-04T13:51:07Z D! [agent] Connecting outputs
2022-01-04T13:51:07Z D! [agent] Attempting connection to [outputs.file]
2022-01-04T13:51:07Z D! [agent] Successfully connected to outputs.file
2022-01-04T13:51:07Z D! [agent] Starting service inputs
2022-01-04T13:51:07Z I! [inputs.statsd] TCP listening on "[::]:8182"
2022-01-04T13:51:07Z I! [inputs.statsd] Started the statsd service on ":8182"
2022-01-04T13:51:17Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2022-01-04T13:51:27Z D! [outputs.file] **Wrote batch of 1 metrics in 202.862µs**
2022-01-04T13:51:27Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics

### System info

Telegraf 1.19.3 (git: HEAD a799489f)

### Steps to reproduce

1. injected the following data for telegraf to consume (one of the elements in the metric tree has spaces : _**ARP flood stats**_ )

```
echo "f5telemetry.server-CVv15d01-ve-service-63kgfh-ad-testbed-dcn.dos-DeviceStats.ARP flood stats.common-aggDetected:0|g|#common.status:Ready,deviceType:Static Vector - Inline,vectorName:XXXRAM1 flood" | nc -C -w 1 localhost 8182
```
2.  Checked the results in the dump file It was not correct:
```
ctrcoll01:/data/TEMP/SRI# cat dump.2022-01-04-1641304717.log 
f5telemetry/server-CVv15d01-ve-service-63kgfh-ad-testbed-dcn/dos-DeviceStats/ARP,common.status=Ready,deviceType=Static\ Vector\ -\ Inline,host=ctrlcoll01,metric_type=gauge,site=Collector0X,vectorName=XXXRAM1\ flood value=0 1641304710000000000
```

### Expected behavior

I expected the data to contain the line:" interface = ARP flood stats"

f5telemetry/dos-DeviceStats,common.status=Ready,deviceType=Static\ Vector\ -\ Inline,host=ctrlcoll01,interface=ARP flood stats,metric_type=gauge,server=server-CVv15d01-ve-service-63kgfh-ad-testbed-dcn,site=Collector0X,vectorName=XXXRAM1\ flood common-aggDetected=0 1641307700000000000

### Actual behavior

Instead, I got a truncated metric without any meaning:

f5telemetry/server-CVv15d01-ve-service-63kgfh-ad-testbed-dcn/dos-DeviceStats/ARP,common.status=Ready,deviceType=Static\ Vector\ -\ Inline,host=ctrlcoll01,metric_type=gauge,site=Collector0X,vectorName=XXXRAM1\ flood value=0 1641307830000000000
