### ISSUE TITLE
Bug: unable to pull metrics from multiple AWS CloudWatch namespaces

### ISSUE THREAD

**Issue by AvivShrem1** [influxdata/telegraf#10391]
### Relevent telegraf.conf

```toml
[agent]
      collection_jitter = "0s"
      debug = true
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
       [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2


    [[outputs.influxdb]]
      database = "telegraf"
      urls = [
        "DB_URL"
      ]

    [[inputs.cloudwatch]]
      delay = "5m"
      interval = "30s"
      namespaces = [
        "AWS/EC2",
        "AWS/ApplicationELB"
      ]
      period = "5m"
      region = "us-east-1"
    [[inputs.internal]]
      collect_memstats = false
```

### Logs from Telegraf

[inputs.cloudwatch] Error in plugin: failed to list metrics with params per namespace: operation error CloudWatch: ListMetrics, https response error StatusCode: 400, RequestID: f735bdc9-c9e4-4fc2-83e6-4378ebc2e352, InvalidParameterValue: Parameters do not match original request parameters

### System info

Telegraf helm chart 1.8.10 , Telegraf version 1.21.1

### Steps to reproduce

1. add the telegraf configuration above.
2. Start telegraf with telegraf --config telegraf.conf

### Expected behavior

collect metrics of both services.

### Actual behavior

Metrics are not collected at all. 
received error:
[inputs.cloudwatch] Error in plugin: failed to list metrics with params per namespace: operation error CloudWatch: ListMetrics, https response error StatusCode: 400, RequestID: f735bdc9-c9e4-4fc2-83e6-4378ebc2e352, InvalidParameterValue: Parameters do not match original request parameters
