### ISSUE TITLE
syslog output: not using correct ASCII trailers per RFC 6587

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#10392]
### Relevent telegraf.conf

```toml
[[inputs.file]]
  files = ["log.out"]
  data_format = "value"
  data_type = "string"

[[outputs.syslog]]
  address = "tcp://:518"
  framing = "non-transparent"
  trailer = "LF"
```

### Logs from Telegraf

Log.out:

```
hello 123
```

### System info

master

### Steps to reproduce

1. Run with the above config
2. View the output to syslog specifically the trailers

### Expected behavior

If the trailer is set to `LF` it should use `0x0a` the newline character, if set to `NUL` it should use `0x00`. Per section [3.4.2 of rfc6587](https://datatracker.ietf.org/doc/html/rfc6587#section-3.4.2)

### Actual behavior

If the trailer is set to `LF` it uses `0x00`, if set to `NUL` it uses `0x01`. This is because we are not calling the `Value()` function of the [trailer variable](https://github.com/influxdata/go-syslog/blob/ac565dc76ba6bb17b47140fb74355d1de7f19307/nontransparent/trailer_type.go#L9) and instead getting the iota value.
