### ISSUE TITLE
inputs.mysql : value too large in SHOW STATUS make strconv.ParseUint return a negative int

### ISSUE THREAD

**Issue by Daryes** [influxdata/telegraf#10407]
### Relevent telegraf.conf

```toml
# Read metrics from one or many mysql servers
[[inputs.mysql]]
  ## specify servers via a url matching:
  # servers = ["tcp(127.0.0.1:3306)/"]
  servers = ["<**user**>:<**pass**>@tcp(127.0.0.1:3306)/"]

  ## Selects the metric output format.
  metric_version = 2

  ## the limits for metrics form perf_events_statements
  perf_events_statements_digest_text_limit  = 120
  perf_events_statements_limit              = 250
  perf_events_statements_time_limit         = 86400
  #
  ## if the list is empty, then metrics are gathered from all databasee tables
  table_schema_databases                    = []
  #
  ## gather metrics from INFORMATION_SCHEMA.TABLES for databases provided above list
  gather_table_schema                       = false
  #
  ## gather thread state counts from INFORMATION_SCHEMA.PROCESSLIST
  gather_process_list                       = true
  #
  ## gather thread state counts from INFORMATION_SCHEMA.USER_STATISTICS
  gather_user_statistics                    = false
  #
  ## gather auto_increment columns and max values from information schema
  gather_info_schema_auto_inc               = true
  #
  ## gather metrics from INFORMATION_SCHEMA.INNODB_METRICS
  gather_innodb_metrics                     = true
  #
  ## gather metrics from SHOW SLAVE STATUS command output
  gather_slave_status                       = true
  #
  ## gather metrics from SHOW BINARY LOGS command output
  gather_binary_logs                        = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.TABLE_IO_WAITS_SUMMARY_BY_TABLE
  gather_table_io_waits                     = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.TABLE_LOCK_WAITS
  gather_table_lock_waits                   = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.TABLE_IO_WAITS_SUMMARY_BY_INDEX_USAGE
  gather_index_io_waits                     = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.EVENT_WAITS
  gather_event_waits                        = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.FILE_SUMMARY_BY_EVENT_NAME
  gather_file_events_stats                  = false
  #
  ## gather metrics from PERFORMANCE_SCHEMA.EVENTS_STATEMENTS_SUMMARY_BY_DIGEST
  gather_perf_events_statements             = false
  #
  ## Some queries we may want to run less often (such as SHOW GLOBAL VARIABLES)
  interval_slow                   = "30m"

  ## Optional TLS Config (will be used if tls=custom parameter specified in server uri)
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false


# fix some mysql metrics data type
[[processors.converter]]
  [processors.converter.fields]
    string = [ "old_alter_table" ]
```

### Logs from Telegraf
```
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-31": strconv.ParseUint: parsing "-31": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-31": strconv.ParseUint: parsing "-31": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-27": strconv.ParseUint: parsing "-27": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-102": strconv.ParseUint: parsing "-102": invalid syntax
E! [inputs.mysql] Error in plugin: error parsing mysql InnoDB metric "buffer_pool_pages_misc"="-26": strconv.ParseUint: parsing "-26": invalid syntax
```

### System info

Telegraf 1.21.2 - Ubuntu 18.04 - no Docker - MariaDB 10.4.22

### Steps to reproduce

1. Upgrade from telegraf 1.19.2 to 1.21.2
1. start telegraf 1.21.2 normally with the mysql input
2. check the logs

Btw, telegraf 1.19.2 doesn't raise this error.

### Expected behavior

no error

### Actual behavior

- Generate an error (in the log) due to a value too long in `SHOW STATUS`
- Generate also an error with `telegraf --test`  (rc=1) but the cause is only visible in the logs (could be as expected)

### Additional info

The cause is due to a too long value in MariaDB STATUS, and telegraf expecting an integer (or long) while it's much greater.

```
MariaDB [(none)]> SHOW STATUS like "%buffer_pool_pages_misc%";
+-------------------------------+----------------------+
| Variable_name                 | Value                |
+-------------------------------+----------------------+
| Innodb_buffer_pool_pages_misc | 18446744073709551418 |
+-------------------------------+----------------------+
```

Dunno why it is at this value as it is on an light instance sized for low memory usage , but it seems to be valid, given "innodb_buffer_pool_chunk_size" which has a similar limit.
https://mariadb.com/kb/en/innodb-system-variables/#innodb_buffer_pool_chunk_size
