### ISSUE TITLE
inputs.docker container_state_include variable doesn't work

### ISSUE THREAD

**Issue by SecorD0** [influxdata/telegraf#10419]
### Relevent telegraf.conf

```toml
[[inputs.docker]]
  container_state_include = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  timeout = "5s"
  perdevice = true
  total = false
```

### Logs from Telegraf

-

### System info

Ubuntu 20.04, Telegraf 1.21.2, InfluxDB 1.8, Docker 20.10.12

### Steps to reproduce

1. Create any continuously running container
2. Create another container
3. Stop one

### Expected behavior

The Telegraf have to parse to docker_container_status table info about containers with all statuses, not just "running".

### Actual behavior

The Telegraf parse to docker_container_status table info about containers with only "running" status.

### Additional info

I also tested other variables, which also don't work
- container_name_exclude
- container_state_include
- container_state_exclude
