### ISSUE TITLE
kube_inventory - context deadline exceeded

### ISSUE THREAD

**Issue by KannappanSomu** [influxdata/telegraf#10421]
### Relevent telegraf.conf

```toml
[[inputs.kube_inventory]]
  url = "$K8S_API_ADDRESS"
  namespace = ""
  insecure_skip_verify = true
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
```

### Logs from Telegraf

2022-01-11T09:36:05Z E! [inputs.kube_inventory] Error in plugin: Get "https://API_url:443/apis/apps/v1/statefulsets": context deadline exceeded

2022-01-11T09:37:05Z E! [inputs.kube_inventory] Error in plugin: Get "https://API_url:443/api/v1/pods": context deadline exceeded

### System info

telegraf 1.20.0 to 1.21.2

### Steps to reproduce

1. use above telegraf config for kube inventory
2. all version from 1.20 to 1.21.2 has the same probelm
3. when downgraded to 1.17.0 probelm is fixed no such errors 
...

### Expected behavior

connect to api server normally and scrape metrics

### Actual behavior

metrics are missed intermittently
