### ISSUE TITLE
 Error in plugin- dialout packet too long

### ISSUE THREAD

**Issue by Praveen2099** [influxdata/telegraf#10439]
### Relevent telegraf.conf

```toml


    [[inputs.cisco_telemetry_mdt]]
      transport = "tcp"
      service_address = ":57000" # instruct telegraf to listen on port 57000 for gRPC telemetry

    [[outputs.file]]
      files = ["stdout"] # files to write to, "stdout" is a specially handled file
      data_format = "json"

getting error while pulling data from cisco routers 
E! [inputs.cisco_telemetry_mdt] Error in plugin: dialout packet too long: 1768894326
```

### Logs from Telegraf

`E! [inputs.cisco_telemetry_mdt] Error in plugin: dialout packet too long: 1768894326`

### System info

Telegraf 1.21.1

### Steps to reproduce

1.Push data in bulk to Telegraf from cisco routers.

### Expected behavior

Logs should be consumed by Telegraf.

### Actual behavior

Getting  error: 
E! [inputs.cisco_telemetry_mdt] Error in plugin: dialout packet too long: 1768894326
