### ISSUE TITLE
MIBS not Loaded after Update to 1.21.2

### ISSUE THREAD

**Issue by langweiler2020** [influxdata/telegraf#10444]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "10.x.x.x","10.x.x.x" ]
  version = 2
  community = "public"
  interval = "60s"
#  path = ["/usr/share/snmp/mibs"]
#  path = ["/mibs"]
#  path = ["/root/.snmp/mibs"]

# System
name = "pan_system"
[[inputs.snmp.field]]
  name = "hostname"
  oid = ".1.3.6.1.2.1.1.5.0"
  is_tag = true
[[inputs.snmp.field]]
  name = "hrProcessorLoad.1"
  oid = ".1.3.6.1.2.1.25.3.3.1.2.1"
[[inputs.snmp.field]]
  name = "hrProcessorLoad.2"
  oid = ".1.3.6.1.2.1.25.3.3.1.2.2"
[[inputs.snmp.field]]
  name = "panSessionUtilization"
  oid = "PAN-COMMON-MIB::panSessionUtilization.0"
[[inputs.snmp.field]]
  name = "panSessionActiveTcp"
  oid = "PAN-COMMON-MIB::panSessionActiveTcp.0"
[[inputs.snmp.field]]
  name = "panSessionActiveUdp"
  oid = "PAN-COMMON-MIB::panSessionActiveUdp.0"
[[inputs.snmp.field]]
  name = "panSessionActiveICMP"
  oid = "PAN-COMMON-MIB::panSessionActiveICMP.0"
[[inputs.snmp.field]]
  name = "panGPGWUtilizationActiveTunnels"
  oid = "PAN-COMMON-MIB::panGPGWUtilizationActiveTunnels.0"
```

### Logs from Telegraf

docker-compose up telegraf
Starting telegraf ... done
Attaching to telegraf
telegraf       | 2022-01-14T09:19:59Z I! Starting Telegraf 1.21.2
telegraf       | 2022-01-14T09:19:59Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf       | 2022-01-14T09:19:59Z I! Loaded inputs: cpu snmp
telegraf       | 2022-01-14T09:19:59Z I! Loaded aggregators:
telegraf       | 2022-01-14T09:19:59Z I! Loaded processors:
telegraf       | 2022-01-14T09:19:59Z I! Loaded outputs: influxdb
telegraf       | 2022-01-14T09:19:59Z I! Tags enabled: host=telegraf
telegraf       | 2022-01-14T09:19:59Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
telegraf       | 2022-01-14T09:20:01Z E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field panSessionUtilization: translating: cannot make PAN-COMMON-MIB::panSessionUtilization.0 numeric, please ensure all imported mibs are in the path

### System info

telegraf 1.21.2 Docker 20.10.12

### Steps to reproduce

1. Pull latest telegraf image 
2. start service
3.
...

### Expected behavior

Should be running fine with the PALOALTO Network MIBS

### Actual behavior

Container is restarting permanently

### Additional info

Running perfect on telegraf version 1.20.4
