### ISSUE TITLE
snmp_trap does not translate PacketwareTeleProvisionMIB::genericAlert

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#10470]
### Relevent telegraf.conf

```toml
# Receive SNMP traps
[[inputs.snmp_trap]]
  ## Transport, local address, and port to listen on.  Transport must
  ## be "udp://".  Omit local address to listen on all interfaces.
  ##   example: "udp://127.0.0.1:1234"
  ##
  ## Special permissions may be required to listen on a port less than
  ## 1024.  See README.md for details
  ##
  # service_address = "udp://:162"
  ##
  ## Path to mib files
  # path = ["/usr/share/snmp/mibs"]
  ##
  ## Timeout running snmptranslate command
  # timeout = "5s"
  ## Snmp version, defaults to 2c
  # version = "2c"
  ## SNMPv3 authentication and encryption options.
  ##
  ## Security Name.
  # sec_name = "myuser"
  ## Authentication protocol; one of "MD5", "SHA" or "".
  # auth_protocol = "MD5"
  ## Authentication password.
  # auth_password = "pass"
  ## Security Level; one of "noAuthNoPriv", "authNoPriv", or "authPriv".
  # sec_level = "authNoPriv"
  ## Privacy protocol used for encrypted messages; one of "DES", "AES", "AES192", "AES192C", "AES256", "AES256C" or "".
  # priv_protocol = ""
  ## Privacy password used for encrypted messages.
  # priv_password = ""

  # already drop items we're not gonna use
  tagexclude = ["community", "version"]

  [inputs.snmp_trap.tags]
    groups = "snmp"
    service = "snmptraps_last"
    status = "SERVICE_UNKNOWN"
```

### Logs from Telegraf

No relevant errors in the logs..

### System info

Telegraf 1.21.1

### Steps to reproduce

1. run telegraf
2. send trap 
```bash
snmptrap -v2c -cpublic localhost `date +%s` .1.3.6.1.4.1.25967.3.2.1.1 \
			.1.3.6.1.4.1.25967.3.2.2.1 s "123" \
			.1.3.6.1.4.1.25967.3.2.2.2 s "ABC" \
			.1.3.6.1.4.1.25967.3.2.2.12 s "xxx"
```
3. inspect metric

### Expected behavior

```ini
snmp_trap,groups=snmp,mib=PacketwareTeleProvisionMIB,name=genericAlert,oid=.1.3.6.1.4.1.25967.3.2.1.1,service= snmptraps_last,source=172.21.0.1,status=SERVICE_UNKNOWN id="123",type="ABC",host="xxx",sysUpTimeInstance=5364741i 1642681689810209368
```

### Actual behavior

```ini
snmp_trap,groups=snmp,mib=SNMPv2-SMI,name=enterprises,oid=.1.3.6.1.4.1.25967.3.2.1.1,service= snmptraps_last,source=172.21.0.1,status=SERVICE_UNKNOWN enterprises="xxx",sysUpTimeInstance=5364741i 1642681689810209368
```

### Additional info

The relevant MIB is [packetware.my](https://github.com/influxdata/telegraf/files/7905162/packetware.my.txt) and is placed in `/usr/share/snmp/mibs/`.
