### ISSUE TITLE
Nagios parser writes no useful log on file permission error

### ISSUE THREAD

**Issue by Sakerdotes** [influxdata/telegraf#10472]
### Relevent telegraf.conf

```toml
[[inputs.exec]]
commands = ['/opt/checks/nagios_check.pl']
interval = '30s'
timeout = '15s'
name_suffix = '__nagios_check'
data_format = 'nagios'
```

### Logs from Telegraf

not needed

### System info

Telegraf 1.21.2, Oracle Linux Server 8.5

### Steps to reproduce

1. Remove all permissions from executable file
2. Let Telegraf execute the file

### Expected behavior

2022-01-20T14:29:43Z E! [inputs.exec] Failed to add nagios state: exec: get exit code: fork/exec /opt/checks/nagios_check.pl: permission denied

### Actual behavior

2022-01-20T14:29:43Z E! [inputs.exec] Failed to add nagios state: exec: get exit code: expected *exec.ExitError
