### ISSUE TITLE
input_file json tag field:

### ISSUE THREAD

**Issue by neeles83** [influxdata/telegraf#10492]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Make the tag field more flexible.

### Current behavior:
With below inputs.file and json structure we are enable to set the ASN (remoteAs) or the state as an Label/Tag of SWP49 or SWP50. 
This as the array and structure of the json. All float's and intergers are set as metrics but not the tags.

```toml
[[inputs.file]]
  #files = ["/etc/telegraf/checks/bgp_ipv4.json"]
  files = ["/etc/telegraf/checks/bgp.json"]
  name_override = "cumulus_bgp"
  data_format = "json_v2"
  json_query = "ipv4 unicast.peers"
  tag_keys = [
    "remoteAs"
  ]
```
```json
{
    "ipv4 unicast": {
        "as": 65206,
        "bestPath": {
            "multiPathRelax": "true"
        },
        "dynamicPeers": 0,
        "peerCount": 4,
        "peerGroupCount": 1,
        "peerGroupMemory": 64,
        "peerMemory": 78944,
        "peers": {
            "swp49": {
                "hostname": "nldcr11t-r01spn",
                "idType": "interface",
                "inq": 0,
                "msgRcvd": 106835,
                "msgSent": 106896,
                "outq": 0,
                "peerUptime": "1d03h12m",
                "peerUptimeEstablishedEpoch": 1642579375,
                "peerUptimeMsec": 97922000,
                "prefixReceivedCount": 78,
                "remoteAs": 65205,
                "state": "Established",
                "tableVersion": 0,
                "version": 4
            },
            "swp50": {
                "hostname": "nldcr11t-r01spn",
                "idType": "interface",
                "inq": 0,
                "msgRcvd": 106835,
                "msgSent": 106896,
                "outq": 0,
                "peerUptime": "1d03h12m",
                "peerUptimeEstablishedEpoch": 1642579375,
                "peerUptimeMsec": 97922000,
                "prefixReceivedCount": 78,
                "remoteAs": 65205,
                "state": "Established",
                "tableVersion": 0,
                "version": 4
            }
        }
        "ribCount": 163,
        "ribMemory": 24776,
        "routerId": "10.227.160.21",
        "tableVersion": 382,
        "totalPeers": 4,
        "vrfId": 0,
        "vrfName": "default"
    }
}
```

### Desired behavior:
Be able to set a option where you can select tags in the itterated item. In the example case that would be;

$item sets the root and there for the tag_keys can be selected out of that tree.
Another solution would be to introduce this for the tag_keys which makes more sense and makes it more flexible. That way you can also retrieve nested key's by peers.$item.remoteAs if the root would be "ipv4 unicast" instead of ipv4 unicast.peers.

$item.remoteAs

```toml
[[inputs.file]]
  #files = ["/etc/telegraf/checks/bgp_ipv4.json"]
  files = ["/etc/telegraf/checks/bgp.json"]
  name_override = "cumulus_bgp"
  data_format = "json_v2"
  json_query = "ipv4 unicast.peers.$item"
  tag_keys = [
    "remoteAs"
  ]
```

```s
file,first=Dale last="Murphy",age=44
```

### Use case: 

This is important so the setting of tags by input.files or input.exec consuming json format more flexible. This would I think help a great many of people consume metrics more easily instead of restructuring their json, which in our case isn't possible as it's from a vendor.
