### ISSUE TITLE
Elasticsearch Sniffing Broken

### ISSUE THREAD

**Issue by zpriddy** [influxdata/telegraf#10512]
### Relevent telegraf.conf

```toml
## The full HTTP endpoint URL for your Elasticsearch instance
  ## Multiple urls can be specified as part of the same cluster,
  ## this means that only ONE of the urls will be written to each interval.
  urls = [ "http://node1.es.example.com:9200" ] # required.
  ## Elasticsearch client timeout, defaults to "5s" if not set.
  timeout = "5s"
  ## Set to true to ask Elasticsearch a list of all cluster nodes,
  ## thus it is not necessary to list all nodes in the urls config option.
  enable_sniffer = true
  ## Set to true to enable gzip compression
  enable_gzip = false
  ## Set the interval to check if the Elasticsearch nodes are available
  ## Setting to "0s" will disable the health check (not recommended in production)
  health_check_interval = "10s"
  ## HTTP basic authentication details
  # username = "telegraf"
  # password = "mypassword"
  ## HTTP bearer token authentication details
  # auth_bearer_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

  ## Index Config
  ## The target index for metrics (Elasticsearch will create if it not exists).
  ## You can use the date specifiers below to create indexes per time frame.
  ## The metric timestamp will be used to decide the destination index name
  # %Y - year (2016)
  # %y - last two digits of year (00..99)
  # %m - month (01..12)
  # %d - day of month (e.g., 01)
  # %H - hour (00..23)
  # %V - week of the year (ISO week) (01..53)
  ## Additionally, you can specify a tag name using the notation {{tag_name}}
  ## which will be used as part of the index name. If the tag does not exist,
  ## the default tag value will be used.
  # index_name = "telegraf-{{host}}-%Y.%m.%d"
  # default_tag_value = "none"
  index_name = "telegraf-%Y.%m.%d" # required.

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Template Config
  ## Set to true if you want telegraf to manage its index template.
  ## If enabled it will create a recommended index template for telegraf indexes
  manage_template = true
  ## The template name used for telegraf indexes
  template_name = "telegraf"
  ## Set to true if you want telegraf to overwrite an existing template
  overwrite_template = false
  ## If set to true a unique ID hash will be sent as sha256(concat(timestamp,measurement,series-hash)) string
  ## it will enable data resend and update metric points avoiding duplicated metrics with diferent id's
  force_document_id = false

  ## Specifies the handling of NaN and Inf values.
  ## This option can have the following values:
  ##    none    -- do not modify field-values (default); will produce an error if NaNs or infs are encountered
  ##    drop    -- drop fields containing NaNs or infs
  ##    replace -- replace with the value in "float_replacement_value" (default: 0.0)
  ##               NaNs and inf will be replaced with the given number, -inf with the negative of that number
  # float_handling = "none"
  # float_replacement_value = 0.0
```

### Logs from Telegraf

Jan 13 00:04:10 b***** telegraf[58151]: 2022-01-13T00:04:10Z D! [agent] Successfully connected to outputs.file
Jan 13 00:04:10 b***** telegraf[58151]: 2022-01-13T00:04:10Z D! [agent] Attempting connection to [outputs.elasticsearch]
Jan 13 00:04:10 b***** telegraf[58151]: 2022-01-13T00:04:10Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'no active connection found: no Elasticsearch node available'
Jan 13 00:04:25 b***** telegraf[58151]: 2022-01-13T00:04:25Z E! [telegraf] Error running agent: connecting output outputs.elasticsearch: Error connecting to output "outputs.elasticsearch": no active connection found: no Elasticsearch node available

### System info

Telegraf 1.21.2, REHL8 Ubuntu18.04

### Steps to reproduce

1.  Enable sniffing for elastic search output
2. Start telegraf and try to ship logs.
...

### Expected behavior

Sniffing should find all elasticsearch nodes and configure the plugin.

### Actual behavior

It fails to find all elastic nodes due to issues with missing scheme for elastic sniffing

### Additional info

This is an issue of the elasticvsearch plugin not setting the scheme when enabling sniffing. 
https://github.com/olivere/elastic/issues/1569

As a result, the scheme must be set whenever sniffing is enabled. This is a simple fix and a PR will be sent with this bug.
