### ISSUE TITLE
Fix apache plugin timeout

### ISSUE THREAD

**Issue by Victor-D** [influxdata/telegraf#10516]
### Relevent telegraf.conf

```toml
# cat /etc/telegraf/telegraf.d/apache.conf
[[inputs.apache]]
timeout = "30s"
urls = ["http://localhost/server-status?auto"]

# cat /etc/telegraf/telegraf.conf
# Telegraf Configuration
#
# THIS FILE IS MANAGED BY PUPPET
#
[global_tags]
  ".retention" = "15778800000"
  host_type = "web"

[agent]
  hostname = "secret"
  omit_hostname = false
  interval = "30s"
  round_interval = true
  metric_batch_size = 250
  metric_buffer_limit = 30000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "10s"
  precision = ""
  logfile = "/var/log/telegraf.log"
  debug = false
  quiet = false

#
# OUTPUTS:
#
[outputs.warp10]
max_string_error_size = 1024
prefix = "secret"
print_error_body = true
timeout = "60s"
token = "secret"
warp_url = "secret"


#
# INPUTS:
#
[[inputs.conntrack]]
dirs = ["/proc/sys/net/netfilter"]
files = ["nf_conntrack_count", "nf_conntrack_max"]
[[inputs.cpu]]
percpu = false
totalcpu = true
[[inputs.disk]]
mount_points = ["/", "/var", "/var/log", "/tmp"]
[[inputs.diskio]]
[[inputs.exec]]
commands = ["/opt/telegraf/nfs.py"]
data_format = "influx"
interval = "30s"
timeout = "10s"
[[inputs.mem]]
[[inputs.net]]
interfaces = ["eth*"]
[[inputs.netstat]]
[[inputs.system]]
[[inputs.temp]]
```

### Logs from Telegraf

2022-01-25T13:56:26Z I! Starting Telegraf 1.21.2
2022-01-25T13:56:26Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/apache.conf: plugin inputs.apache: line 1: configuration specified the fields ["timeout"], but they weren't used

### System info

Telegraf 1.21.2 (git: HEAD 30d981d3) on Debian

### Steps to reproduce

1. Add a telegraf basic configuration in /etc/telegraf/telegraf.conf
2. Add the apache exec plugin configuration in /etc/telegraf/telegraf.d/apache.conf
3. Restart telegraf service, it works fine
4. Add the timeout option in /etc/telegraf/telegraf.d/apache.conf
5. Restart telegraf service, Telegraf log now show the timeout option is ignored and there is an error

### Expected behavior

Timeout for this exec plugin should be now 30 seconds.

### Actual behavior

I have a working Telegraf configuration. If I add the timeout option on the apache plugin then there is an error in the logs.

### Additional info

Maybe it's just a false positive we can ignore ?
