### ISSUE TITLE
Telegraf with SNMP config stopped working with 1.21.3

### ISSUE THREAD

**Issue by voiprodrigo** [influxdata/telegraf#10549]
### Relevent telegraf.conf

```toml
[[inputs.snmp]]
  agents = [ "x.x.x.x" ]
  version = 3
  auth_protocol = "SHA"
  auth_password = "xxx"
  sec_level = "authPriv"
  sec_name = "user"
  priv_protocol = "AES"
  priv_password = "xxx"
  name = "snmp_device"
  interval = "60s"
  timeout = "20s"
  tagexclude = ["role","region","country","location"]

  [inputs.snmp.tags]
    influxdb_database = "snmpmetrics"

  [[inputs.snmp.field]]
    name = "device"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
  [[inputs.snmp.field]]
    name = "desc"
    oid = "SNMPv2-MIB::sysDescr.0"

  [[inputs.snmp.table]]
    name = "snmp_eaton_xups"
    inherit_tags = [ "device" ]
    index_as_tag = true

    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsBatTimeRemaining"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsBatVoltage"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsBatCurrent"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsBatCapacity"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsBatteryAbmStatus"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsInputFrequency"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsInputLineBads"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsInputNumPhases"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsInputPhase"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsInputVoltage"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsInputCurrent"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsInputSource"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputSource"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputLoad"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputFrequency"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputNumPhases"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputPhase"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputVoltage"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputCurrent"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsOutputWatts"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsEnvAmbientTemp"
    [[inputs.snmp.table.field]]
      oid = "XUPS-MIB::xupsAlarms"


[[inputs.snmp]]
  agents = [ "1.1.1.1","2.2.2.2","3.3.3.3" ]
  version = 2
  community = "xxx"
  name = "snmp_device"
  interval = "60s"
  timeout = "20s"
  retries = 4
  tagexclude = ["role","region","country","location"]

  [inputs.snmp.tags]
    influxdb_database = "snmpmetrics"

  [[inputs.snmp.field]]
    name = "device"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
  [[inputs.snmp.field]]
    name = "desc"
    oid = "SNMPv2-MIB::sysDescr.0"

  # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
  [[inputs.snmp.table]]
    name = "snmp_int"
    inherit_tags = [ "device" ]
    oid = "IF-MIB::ifTable"
    index_as_tag = true

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "ifAlias"
      oid = "IF-MIB::ifAlias"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = "IF-MIB::ifName"
      is_tag = true

  # IF-MIB::ifXTable contains newer High Capacity (HC) counters that do not overflow as fast for a few of the ifTable counters
  [[inputs.snmp.table]]
    name = "snmp_int"
    inherit_tags = [ "device" ]
    oid = "IF-MIB::ifXTable"
    index_as_tag = true

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "ifAlias"
      oid = "IF-MIB::ifAlias"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = "IF-MIB::ifName"
      is_tag = true

  # EtherLike-MIB::dot3StatsTable contains detailed ethernet-level information about what kind of errors have been logged on an interface (such as FCS error, frame too long, etc)
  [[inputs.snmp.table]]
    name = "snmp_int"
    inherit_tags = [ "device" ]
    oid = "EtherLike-MIB::dot3StatsTable"
    index_as_tag = true

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "ifAlias"
      oid = "IF-MIB::ifAlias"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = "IF-MIB::ifName"
      is_tag = true
```

### Logs from Telegraf

2022-01-31T11:54:11Z I! Loaded inputs: burrow conntrack cpu disk diskio ethtool exec (4x) influxdb_listener (3x) internal interrupts iptables (2x) kernel kernel_vmstat linux_sysctl_fs mem net netstat nstat processes procstat (7x) snmp (2x) socket_listener (2x) swap system
2022-01-31T11:54:11Z I! Loaded aggregators:
2022-01-31T11:54:11Z I! Loaded processors: override (3x) regex
2022-01-31T11:54:11Z I! Loaded outputs: influxdb (12x)
2022-01-31T11:54:11Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"xxx", Flush Interval:1m0s
2022-01-31T11:54:11Z D! [agent] Initializing plugins
2022-01-31T11:54:14Z W! [inputs.snmp] module errors could not be loaded
2022-01-31T11:54:19Z W! [inputs.snmp] module rfc1212.my could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module README could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module list-ids-diagnostics.txt could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module notifications.txt could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module vc-alarms-65.csv could not be loaded

### System info

CentOS 7.9, Telegraf 1.21.3

### Steps to reproduce

Use the SNMP config above on a CentOS 7 system. Run and check logs

### Expected behavior

Normal execution of all plugins, as in up to 1.21.2

### Actual behavior

Telegraf remains in a loop with this messages block repeating over and over. No plugins run.

2022-01-31T11:54:14Z W! [inputs.snmp] module errors could not be loaded
2022-01-31T11:54:19Z W! [inputs.snmp] module rfc1212.my could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module README could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module list-ids-diagnostics.txt could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module notifications.txt could not be loaded
2022-01-31T11:54:21Z W! [inputs.snmp] module vc-alarms-65.csv could not be loaded
