### ISSUE TITLE
[outputs.http] Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by renatomotorline** [influxdata/telegraf#10566]
### Relevent telegraf.conf

```toml
[agent]
  interval = "500ms"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_jitter = "0s"
  debug = true
  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]

  database = "endpoints"
  namepass = ["*"]

# # A plugin that can transmit metrics over HTTP
 [[outputs.http]]
    url = "http://api:3000/values"
    method = "PUT"
    data_format = "json"
    [outputs.http.headers]
        Content-Type = "application/json"

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# # Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
  servers = ["tcp://emqx.backend:1883"]
  topics = ["topics/#"]
  qos = 2
  connection_timeout = "30s"
  username = "telegraf"
  password = "<password>"
  json_name_key = "endpoint"
  tag_keys = ["host"]
  json_string_fields = ["value"]
  data_format = "json"
```

### Logs from Telegraf

2022-02-02T10:08:22Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:24Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:24Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:25Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:25Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:27Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:27Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:28Z D! [outputs.influxdb] Wrote batch of 1 metrics in 48.414741ms
2022-02-02T10:08:28Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:30Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:30Z W! [agent] ["outputs.http"] did not complete within its flush interval
2022-02-02T10:08:30Z D! [outputs.http] Buffer fullness: 1 / 100000 metrics
2022-02-02T10:08:31Z W! [agent] ["outputs.http"] did not complete within its flush interval
2022-02-02T10:08:31Z D! [outputs.http] Buffer fullness: 1 / 100000 metrics
2022-02-02T10:08:31Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:33Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:33Z W! [agent] ["outputs.http"] did not complete within its flush interval
2022-02-02T10:08:33Z D! [outputs.http] Buffer fullness: 1 / 100000 metrics
2022-02-02T10:08:33Z D! [outputs.http] Buffer fullness: 1 / 100000 metrics
2022-02-02T10:08:33Z E! [agent] Error writing to outputs.http: Put http://api:3000/values: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2022-02-02T10:08:33Z D! [outputs.http] Wrote batch of 1 metrics in 18.145111ms
2022-02-02T10:08:33Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:34Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:34Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:36Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:36Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:37Z D! [outputs.http] Wrote batch of 1 metrics in 7.676851ms
2022-02-02T10:08:37Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:37Z D! [outputs.influxdb] Wrote batch of 1 metrics in 49.811761ms
2022-02-02T10:08:37Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:39Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:39Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:40Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:40Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:42Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:42Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:43Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:43Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:45Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:45Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:46Z D! [outputs.http] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:46Z D! [outputs.influxdb] Buffer fullness: 0 / 100000 metrics
2022-02-02T10:08:48Z D! [outputs.influxdb] Wrote batch of 1 metrics in 49.724835ms

### System info

AlmaLinux release 8.5 (Arctic Sphynx), Docker version 20.10.12

### Docker

Dockerfile
# Get telegraf image
FROM telegraf:1.12.2
# FROM telegraf:1.19

# Set working directory
WORKDIR /etc/telegraf

# Copy config to container
COPY telegraf.conf .

docker-compose.yml
telegraf:
    image: "registry/telegraf:latest"
    depends_on:
      - influxdb
    environment:
      - INTERVAL="500ms"
    networks:
      local-network:
        aliases:
          - telegraf
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: any
        delay: 30s

### Steps to reproduce

Cannot give the steps to reproduce. The problem seems to happen randomly.

### Expected behavior

To work normally like most of the requests

### Actual behavior

Random Error writing to outputs.http

### Additional info

I'm using docker swarm.
The HTTP receiver is a restify server. I have 4 replicas of that service and is not overloaded, any other request to that service works fine.
Any idea what I'm doing wrong?
