### ISSUE TITLE
Add dynamic tag set to json_v2

### ISSUE THREAD

**Issue by wz2b** [influxdata/telegraf#10576]
## Feature Request

Add support for dynamic tag names in json_v2 input format

### Proposal:

Currently you can specify a dynamic set of fields at a certain path

```toml
   [[inputs.file.json_v2.object]]
     path = "fields"
```
but this only applies to fields, not tags.  In my case, the fields are unknown.  What I am using is a JSON representation of what line protocol like this:

```json
{
  "measurement": "measurementName",

  "tags": {
    "tag1": "tagValue1",
    "tag2": "tagValue2"
  },

  "fields": {
    "field1": 1.0,
    "field2": 2.0
  }
}
```

I want to be able to specify "tags_path", with the desired result being:

`measurementName,tag1=tagValue1,tag2=tagvalue2 field1=1.0,field2=2.0 ...`

### Current behavior:

Currently tags must be specified explicitly in the telegraf configuration file as an array of strings.  In my case, 'path' does what I want for fields (pretend it is named "field_path") but "tag_path" is missing.

If we create "tag_path" then the input could be documented like this:

```toml
[[inputs.file.json_v2.object]]
            path = "" # A string with valid GJSON path syntax, can include array's and object's
            tag_path = "" # A string with valid JSON path syntax, can include arrays and objects
```

### Use case: 
I am trying to get data into telegraf using Node Red. There is a plugin for Node Red that manipulates line protocol.  It uses the object representation I described above.  See [node-red-contrib-influxdb-line-protocol](https://github.com/opatut/node-red-contrib-influxdb-line-protocol) for an example.

There are some other requests out in the ether looking for "line protocol in json" as well.  (example)[https://community.influxdata.com/t/json-file-line-protocol-influxdb/7818/6] is one.  So I think the generic capability would be worthwhile.
