### ISSUE TITLE
[inputs.modbus] Error in plugin: modbus: exception '244' (unknown), function '3'

### ISSUE THREAD

**Issue by ToM-MaS** [influxdata/telegraf#10597]
### Relevant telegraf.conf

```toml
[[inputs.modbus]]
  ## Connection Configuration
  ##
  ## The plugin supports connections to PLCs via MODBUS/TCP or
  ## via serial line communication in binary (RTU) or readable (ASCII) encoding
  ##
  ## Device name
  name = "Device_UMG604_MA21"

  ## Slave ID - addresses a MODBUS device on the bus
  ## Range: 0 - 255 [0 = broadcast; 248 - 255 = reserved]
  slave_id = 1

  ## Timeout for each request
  timeout = "1s"

  ## Maximum number of retries and the time to wait between retries
  ## when a slave-device is busy.
  # busy_retries = 0
  # busy_retries_wait = "100ms"

  # TCP - connect via Modbus/TCP
  controller = "tcp://192.168.192.52:502"

  ## Serial (RS485; RS232)
  # controller = "file:///dev/ttyUSB0"
  # baud_rate = 9600
  # data_bits = 8
  # parity = "N"
  # stop_bits = 1
  # transmission_mode = "RTU"


  ## Measurements
  ##

  ## Digital Variables, Discrete Inputs and Coils
  ## measurement - the (optional) measurement name, defaults to "modbus"
  ## name        - the variable name
  ## address     - variable address

  #discrete_inputs = [
  #  { name = "start",          address = [0]},
  #  { name = "stop",           address = [1]},
  #  { name = "reset",          address = [2]},
  #  { name = "emergency_stop", address = [3]},
  #]
  #coils = [
  #  { name = "motor1_run",     address = [0]},
  #  { name = "motor1_jog",     address = [1]},
  #  { name = "motor1_stop",    address = [2]},
  #]

  ## Analog Variables, Input Registers and Holding Registers
  ## measurement - the (optional) measurement name, defaults to "modbus"
  ## name        - the variable name
  ## byte_order  - the ordering of bytes
  ##  |---AB, ABCD   - Big Endian
  ##  |---BA, DCBA   - Little Endian
  ##  |---BADC       - Mid-Big Endian
  ##  |---CDAB       - Mid-Little Endian
  ## data_type  - INT16, UINT16, INT32, UINT32, INT64, UINT64, FLOAT32-IEEE, FLOAT64-IEEE (the IEEE 754 binary representation)
  ##              FLOAT32 (deprecated), FIXED, UFIXED (fixed-point representation on input)
  ## scale      - the final numeric variable representation
  ## address    - variable address

  #holding_registers = [
  #  { name = "power_factor", byte_order = "AB",   data_type = "FIXED", scale=0.01,  address = [8]},
  #  { name = "voltage",      byte_order = "AB",   data_type = "FIXED", scale=0.1,   address = [0]},
  #  { name = "energy",       byte_order = "ABCD", data_type = "FIXED", scale=0.001, address = [5,6]},
  #  { name = "current",      byte_order = "ABCD", data_type = "FIXED", scale=0.001, address = [1,2]},
  #  { name = "frequency",    byte_order = "AB",   data_type = "UFIXED", scale=0.1,  address = [7]},
  #  { name = "power",        byte_order = "ABCD", data_type = "UFIXED", scale=0.1,  address = [3,4]},
  #]
  #input_registers = [
  #  { name = "tank_level",   byte_order = "AB",   data_type = "INT16",   scale=1.0,     address = [0]},
  #  { name = "tank_ph",      byte_order = "AB",   data_type = "INT16",   scale=1.0,     address = [1]},
  #  { name = "pump1_speed",  byte_order = "ABCD", data_type = "INT32",   scale=1.0,     address = [3,4]},
  #]


  input_registers = [
    { name = "Voltage L1-N (V)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19000,19001]},
    { name = "Voltage L2-N (V)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19002,19003]},
    { name = "Voltage L3-N (V)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19004,19005]},
    { name = "Voltage L1-L2 (V)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19006,19007]},
    { name = "Voltage L2-L3 (V)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19008,19009]},
    { name = "Voltage L1-L3 (V)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19010,19011]},
    { name = "Current I L1 (A)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19012,19013]},
    { name = "Current I L2 (A)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19014,19015]},
    { name = "Current I L3 (A)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19016,19017]},
    { name = "Vector sum; IN=I1+I2+I3 (A)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19018,19019]},
    { name = "Real power P1 L1N (W)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19020,19021]},
    { name = "Real power P2 L2N (W)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19022,19023]},
    { name = "Real power P3 L3N (W)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19024,19025]},
    { name = "Sum; Psum3=P1+P2+P3 (W)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19026,19027]},
    { name = "Apparent power S1 L1N (VA)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19028,19029]},
    { name = "Apparent power S2 L2N (VA)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19030,19031]},
    { name = "Apparent power S3 L3N (VA)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19032,19033]},
    { name = "Sum; Ssum3=S1+S2+S3 (VA)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19034,19035]},
    { name = "Fund. reactive power Q1 L1N (var)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19036,19037]},
    { name = "Fund. reactive power Q2 L2N (var)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19038,19039]},
    { name = "Fund. reactive power Q3 L3N (var)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19040,19041]},
    { name = "Fund. Sum; Qsum3=Q1+Q2+Q3 (var)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19042,19043]},
    { name = "CosPhi; UL1 IL1 (fundamental comp.)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19044,19045]},
    { name = "CosPhi; UL2 IL2 (fundamental comp.)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19046,19047]},
    { name = "CosPhi; UL3 IL3 (fundamental comp.)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19048,19049]},
    { name = "Measured frequency (Hz)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19050,19051]},
    { name = "Rotation field; 1=right, 0=none, -1=left",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19052,19053]},
    { name = "Real energy L1 (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19054,19055]},
    { name = "Real energy L2 (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19056,19057]},
    { name = "Real energy L3 (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19058,19059]},
    { name = "Real energy L1..L3 (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19060,19061]},
    { name = "Real energy L1, consumed (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19062,19063]},
    { name = "Real energy L2, consumed (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19064,19065]},
    { name = "Real energy L3, consumed (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19066,19067]},
    { name = "Real energy L1..L3, consumed, rate 1 (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19068,19069]},
    { name = "Real energy L1, delivered (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19070,19071]},
    { name = "Real energy L2, delivered (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19072,19073]},
    { name = "Real energy L3, delivered (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19074,19075]},
    { name = "Real energy L1..L3, delivered (Wh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19076,19077]},
    { name = "Apparent energy L1 (VAh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19078,19079]},
    { name = "Apparent energy L2 (VAh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19080,19081]},
    { name = "Apparent energy L3 (VAh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19082,19083]},
    { name = "Apparent energy L1..L3 (VAh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19084,19085]},
    { name = "Reactive energy L1 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19086,19087]},
    { name = "Reactive energy L2 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19088,19089]},
    { name = "Reactive energy L3 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19090,19091]},
    { name = "Reactive energy L1..L3 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19092,19093]},
    { name = "Reactive energy ind. L1 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19094,19095]},
    { name = "Reactive energy ind. L2 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19096,19097]},
    { name = "Reactive energy ind. L3 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19098,19099]},
    { name = "Reactive energy ind. L1..L3 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19100,19101]},
    { name = "Reactive energy cap. L1 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19102,19103]},
    { name = "Reactive energy cap. L2 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19104,19105]},
    { name = "Reactive energy cap. L3 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19106,19107]},
    { name = "Reactive energy cap. L1..L3 (varh)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19108,19109]},
    { name = "Harmonic, THD U L1-N (%)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19110,19111]},
    { name = "Harmonic, THD U L2-N (%)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19112,19113]},
    { name = "Harmonic, THD U L3-N (%)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19114,19115]},
    { name = "Harmonic, THD I L1 (%)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19116,19117]},
    { name = "Harmonic, THD I L2 (%)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19118,19119]},
    { name = "Harmonic, THD I L3 (%)",   byte_order = "ABCD",   data_type = "FLOAT32-IEEE",   scale=1.0,     address = [19120,19121]},
  ]
```

### Logs from Telegraf

[inputs.modbus] Error in plugin: modbus: exception '244' (unknown), function '3'

### System info

telegraf-1.21.3_windows_amd64,  influxdb2-2.1.1-windows-amd64

### Steps to reproduce

start telegraf:  telegraf.exe --config ./telegraf.conf

### Expected behavior

no Error message

### Actual behavior

Error message

### Additional info

What does this error mean?
