### ISSUE TITLE
Prometheus input plugin not working when there is no \n at the end of the file

### ISSUE THREAD

**Issue by mb2993** [influxdata/telegraf#10608]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://host:port/api/monitor/metrics"]
```

### Logs from Telegraf

2022-02-09T11:18:20Z E! [inputs.prometheus] Error in plugin: error reading metrics for http://host:port/api/monitor/metrics: reading text format failed: text format parsing error in line 181: unexpected end of input stream

### System info

Telegraf 1.21.3, Ubuntu 20.04, Docker 20.10.12

### Steps to reproduce

1. Configure Telegraf with the Prometheus Input plugin
2. Try to scrape metrics that do not have a \n at the end of the file

### Expected behavior

The Prometheus plugin should accept the response whether there is an \n and the end of the file or not.

### Actual behavior

The plugin throws a parsing error and does not process the metrics.
