### ISSUE TITLE
incorrect display of mem_used_percent MacOs

### ISSUE THREAD

**Issue by tetesh** [influxdata/telegraf#10632]
### Relevant telegraf.conf

```toml
[global_tags]
  dc = "denver-1"

[agent]
  interval = "10s"

[[inputs.exec]]
  commands = [ "/etc/telegraf/hardware/temp.sh",
    "/etc/telegraf/hardware/periphery.sh",
    "/etc/telegraf/hardware/cpuusage.sh",
    "/etc/telegraf/hardware/serialnumber.sh",
    "/etc/telegraf/hardware/osversion.sh",
    "/etc/telegraf/service/ldap.sh",
    "/etc/telegraf/service/krb.sh",
    "/etc/telegraf/service/iscsi.sh",
    "/etc/telegraf/service/moulinette.sh",
    "/etc/telegraf/service/vogsphere.sh",
    "/etc/telegraf/alert/examusb.sh",
    "/etc/telegraf/login.sh",
    "/etc/telegraf/exam.sh" ]
  timeout = "10s"
  data_format = "influx"

[[inputs.disk]]
  tagexclude = ["fstype"]

[[inputs.mem]]

[[inputs.net]]
  interfaces = ["en*", "lo0"]

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
```

### Logs from Telegraf

```
[root] pr-h4 [~] # tail -f /var/log/telegraf.err.log
2022-02-11T07:19:53Z I! [agent] Stopping running outputs
2022-02-11T07:19:57Z I! Starting Telegraf 1.21.3
2022-02-11T07:19:57Z I! Using config file: /etc/telegraf/telegraf.conf
2022-02-11T07:19:57Z I! Loaded inputs: disk exec mem net
2022-02-11T07:19:57Z I! Loaded aggregators: 
2022-02-11T07:19:57Z I! Loaded processors: 
2022-02-11T07:19:57Z I! Loaded outputs: prometheus_client
2022-02-11T07:19:57Z I! Tags enabled: dc=denver-1 host=pr-h4.kzn.21-school.ru
2022-02-11T07:19:57Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"pr-h4.kzn.21-school.ru", Flush Interval:10s
2022-02-11T07:19:57Z I! [outputs.prometheus_client] Listening on http://[::]:9273/metrics
```

### System info

Telegraf 1.17.2 (git: HEAD 74011e22), MacOs Mojave 10.14.6

### Steps to reproduce

1. I look at the metrics at http://hostname:9273/metrics

### Expected behavior

I want to see real mem_used_percent indicators (90%)

```
# HELP mem_total Telegraf collected metric
# TYPE mem_total gauge
mem_total{dc="denver-1",host="pr-h4.kzn.21-school.ru"} 8.589934592e+09
# HELP mem_used Telegraf collected metric
# TYPE mem_used gauge
mem_used{dc="denver-1",host="pr-h4.kzn.21-school.ru"} 7.747760128e+09
# HELP mem_used_percent Telegraf collected metric
# TYPE mem_used_percent gauge
mem_used_percent{dc="denver-1",host="pr-h4.kzn.21-school.ru"} 90.19579887390137
````

### Actual behavior

I see not real indicators, because no one uses the iMac and the top utility also issues:

Load Avg: 1.50, 1.02, 0.70  CPU usage: 0.32% user, 0.32% sys, 99.34% idle
SharedLibs: 119M resident, 39M data, 28M linkedit.
MemRegions: 14416 total, 1087M resident, 77M private, 560M shared.
`PhysMem: 4150M used (1419M wired), 4042M unused.`
VM: 802G vsize, 1372M framework vsize, 0(0) swapins, 0(0) swapouts.
Networks: packets: 18793774/4189M in, 8271302/2404M out.
Disks: 1902868/27G read, 11020419/85G written.
