### ISSUE TITLE
telegraf don't work as service but work when executed from shell

### ISSUE THREAD

**Issue by meditant** [influxdata/telegraf#10666]
### Relevant telegraf.conf

```toml
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://webserver.franck-rondot.lan:8086"]

  ## API token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "frondot"

  ## Destination bucket to write into.
  bucket = "telegraf"
```

### Logs from Telegraf

telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/telegraf.service.d
           └─override.conf
   Active: active (running) since Wed 2022-02-16 21:24:09 GMT; 1s ago
     Docs: https://github.com/influxdata/telegraf
 Main PID: 719 (telegraf)
    Tasks: 9 (limit: 871)
   CGroup: /system.slice/telegraf.service
           └─719 /usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d

févr. 16 21:24:09 alchymage-laboserv systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
févr. 16 21:24:09 alchymage-laboserv telegraf[719]: 2022-02-16T21:24:09Z I! Starting Telegraf 1.21.3
févr. 16 21:24:09 alchymage-laboserv telegraf[719]: 2022-02-16T21:24:09Z I! Loaded inputs: cpu disk diskio kernel mem processes swap system
févr. 16 21:24:09 alchymage-laboserv telegraf[719]: 2022-02-16T21:24:09Z I! Loaded aggregators:
févr. 16 21:24:09 alchymage-laboserv telegraf[719]: 2022-02-16T21:24:09Z I! Loaded processors:
févr. 16 21:24:09 alchymage-laboserv telegraf[719]: 2022-02-16T21:24:09Z I! Loaded outputs: influxdb_v2
févr. 16 21:24:09 alchymage-laboserv telegraf[719]: 2022-02-16T21:24:09Z I! Tags enabled: host=alchymage-laboserv
févr. 16 21:24:09 alchymage-laboserv telegraf[719]: 2022-02-16T21:24:09Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"alchymage-laboserv", Flu

### System info

Ubuntu 20.04

### Steps to reproduce

Hello,

When i use telegraf on service i don received data in influxDB 2, but on the same machine if i execute telegraf from shell it's work !

Best regard

### Expected behavior

I dont have any errors message from service status

### Actual behavior

Error
