### ISSUE TITLE
Why telegraf will use 5GB virtual memory in linux

### ISSUE THREAD

**Issue by liming2008512** [influxdata/telegraf#10669]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "60s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "60s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  # quiet = false

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true





[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = true
  name_override = "system_cpu"
  tagexclude = ["cpu"]
  fieldpass = ["usage_active", "usage_nice", "usage_idle", "usage_user"]


[[outputs.file]]
  files = ["stdout"]
```

### Logs from Telegraf

log

### System info

Telegraf 1.21.4, redhat 7.4

### Steps to reproduce

1. run command: ./telegraf --config telegraf.conf
2.
3.
...

### Expected behavior

Telegraf should not use too much virtual memory.

### Actual behavior

telegraf uses 5GB virtual memory in linux.

root     107585  1.2  0.5 5240212 46044 pts/0   Sl+  10:56   0:00 ./telegraf --config /opt/app/go_path/src/telegraf/telegraf.conf
root     107623  0.0  0.0 112816   976 pts/2    S+   10:57   0:00 grep --color=auto telegraf
