### ISSUE TITLE
CSV parser does not handle csv_header_row_count correctly

### ISSUE THREAD

**Issue by NielsH** [influxdata/telegraf#10678]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  commands = ["sudo /usr/local/sbin/repquota4.06 -P -sk, -a -O csv"]

  data_format = "csv"
  csv_header_row_count = 1
  csv_column_types = ["string", "string", "string", "string", "string", "string", "string", "int", "int", "int", "string"]
  csv_tag_columns = ["Project"]
  name_override = "quota_project"

  # Means to skip empty strings
  csv_skip_values = [""]

  # Only expose these fields, drop others
  fieldpass = ["Project", "SpaceUsed", "FileUsed"]

[[processors.regex]]
  order = 1
  namepass = ["quota_project"]
  [[processors.regex.fields]]
  key = "SpaceUsed"
  pattern = "^(.*)K$"
  replacement = "${1}"

[[processors.converter]]
  order = 2
  namepass = ["quota_project"]
  [processors.converter.fields]
    integer = ["SpaceUsed"]
```

### Logs from Telegraf

2022-02-18T09:06:31Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 449.287µs
2022-02-18T09:06:31Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:31Z D! [outputs.influxdb] Wrote batch of 25 metrics in 45.592603ms
2022-02-18T09:06:31Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:40Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:06:41Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 221.635µs
2022-02-18T09:06:41Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:41Z D! [outputs.influxdb] Wrote batch of 25 metrics in 4.141917ms
2022-02-18T09:06:41Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:50Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:06:51Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 233.676µs
2022-02-18T09:06:51Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:06:51Z D! [outputs.influxdb] Wrote batch of 25 metrics in 4.00893ms
2022-02-18T09:06:51Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:00Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:07:01Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 235.754µs
2022-02-18T09:07:01Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:01Z D! [outputs.influxdb] Wrote batch of 25 metrics in 3.653304ms
2022-02-18T09:07:01Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:10Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:07:11Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 221.834µs
2022-02-18T09:07:11Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:11Z D! [outputs.influxdb] Wrote batch of 25 metrics in 40.921214ms
2022-02-18T09:07:11Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:20Z E! [inputs.exec] Error in plugin: column type: parse int error strconv.ParseInt: parsing "FileUsed": invalid syntax
2022-02-18T09:07:21Z D! [outputs.prometheus_client] Wrote batch of 25 metrics in 255.106µs
2022-02-18T09:07:21Z D! [outputs.prometheus_client] Buffer fullness: 0 / 10000 metrics
2022-02-18T09:07:21Z D! [outputs.influxdb] Wrote batch of 25 metrics in 3.244573ms
2022-02-18T09:07:21Z D! [outputs.influxdb] Buffer fullness: 0 / 10000 metrics

### System info

Telegraf 1.21.4-1 - Debian 11

### Docker

N/A

### Steps to reproduce

1. Run the supplied telegraf.conf with repquota4.06 (older versions dont have all the flags we use included)
2. The first metric works correctly
3. All other metrics (every 10 seconds) give the error shown in the logs
...

### Expected behavior

Metrics collected every interval (10 seconds) don't give an error

### Actual behavior

Every 10 seconds we get an error

### Additional info

So I *think* this is related to https://github.com/influxdata/telegraf/issues/10347

What I think is happening, the output of the command we run is:
```
Project,SpaceStatus,FileStatus,SpaceUsed,SpaceSoftLimit,SpaceHardLimit,SpaceGrace,FileUsed,FileSoftLimit,FileHardLimit,FileGrace
timtest_a68e,ok,ok,849892K,0K,0K,,196,0,0,
#0,ok,ok,8446956K,0K,0K,,95870,0,0,
```

So the first, initial run of collecting metrics, the `csv_header_row_count = 1` is applied correctly to see the first row as a header. However every secondary run (every 10 seconds) I think it is trying to parse the header row as metric data and as such it is failing. It's supposed to always see the first row as the header every time we run the command.

We can sort of work around it by adding
```
csv_column_names = ["Project", "SpaceStatus", "FileStatus", "SpaceUsed", "SpaceSoftLimit", "SpaceHardLimit", "SpaceGrace", "FileUsed", "FileSoftLimit", "FileHardLimit", "FileGrace"]

# And removing:
#csv_header_row_count = 1

```

And then changing the command to:

```
commands = ["/var/tmp/quota-test.sh"]
```

And in `/var/tmp/quota-test.sh` we do: 
```
#!/bin/bash

sudo /usr/local/sbin/repquota4.06 -P -sk, -a -O csv | tail +2
```

Note that under Debian 11, the `repquota` command included in the `quota` package under `/usr/sbin/repquota` can also be used to reproduce it. But if you're using Debian 10 which has an older repquota version you have to use 4.06 specifically.
