### ISSUE TITLE
[[inputs.jenkins]] Can't target jobs inside folders. 

### ISSUE THREAD

**Issue by Pauss** [influxdata/telegraf#10677]
### Relevant telegraf.conf

```toml
# # Read jobs and cluster metrics from Jenkins instances
[[inputs.jenkins]]
  ## The Jenkins URL in the format "schema://host:port"
  url = "http://jenkins:8080"
  username = "admin"
  password = "admin"
#
  ## Set response_timeout
  response_timeout = "5s"
#
#   ## Optional TLS Config
#   # tls_ca = "/etc/telegraf/ca.pem"
#   # tls_cert = "/etc/telegraf/cert.pem"
#   # tls_key = "/etc/telegraf/key.pem"
#   ## Use SSL but skip chain & host verification
  insecure_skip_verify = true
#
#   ## Optional Max Job Build Age filter
#   ## Default 1 hour, ignore builds older than max_build_age
  max_build_age = "1h"
#
#   ## Optional Sub Job Depth filter
#   ## Jenkins can have unlimited layer of sub jobs
#   ## This config will limit the layers of pulling, default value 0 means
#   ## unlimited pulling until no more sub jobs
#   # max_subjob_depth = 0
#
#   ## Optional Sub Job Per Layer
#   ## In workflow-multibranch-plugin, each branch will be created as a sub job.
#   ## This config will limit to call only the lasted branches in each layer,
#   ## empty will use default value 10
#   # max_subjob_per_layer = 10
#
#   ## Jobs to include or exclude from gathering
#   ## When using both lists, job_exclude has priority.
#   ## Wildcards are supported: [ "jobA/*", "jobB/subjob1/*"]
   job_include = [ "job*", "P1/job*", "P1/job/*", "job/P1/*", "/job/P1/*", "P1/.*", "P1/*", ".*/P1/*", "*job*" ]
#   # job_exclude = [ ]
#
#   ## Nodes to include or exclude from gathering
#   ## When using both lists, node_exclude has priority.
#   # node_include = [ "*" ]
#   # node_exclude = [ ]
#
#   ## Worker pool for jenkins plugin only
#   ## Empty this field will use default value 5
#   # max_connections = 5
```

### Logs from Telegraf

---

### System info

docker image telegraf:1.21

### Steps to reproduce

I have my job inside P1 folder, I've tried all kinds of expression but non of them work :
job_include = [ "job*", "P1/job*", "P1/job/*", "job/P1/*", "/job/P1/*", "P1/.*", "P1/*", ".*/P1/*", "*job*" ]

Please help. 

### Expected behavior

Collect data from builds with name like "job1", "job3" inside folder "P1'.

### Actual behavior

Collect data only for root level jobs with pattern name "job*".

This how my jenkins looks like. 
root/job1
![image](https://user-images.githubusercontent.com/18573691/154644248-e9b5e596-bf78-4f88-90a1-5b1d99912eb0.png)

P1/job3
![image](https://user-images.githubusercontent.com/18573691/154643945-1b46e670-05ce-4413-aa25-d2a7858246f5.png)

This is data collected by telegraf.
![image](https://user-images.githubusercontent.com/18573691/154644135-6a946032-6890-4fbc-ae5d-613fbe30d4be.png)
![image](https://user-images.githubusercontent.com/18573691/154644136-e7a81fcd-044e-44ac-8d28-b57b9c548a13.png)
