### ISSUE TITLE
Wrong behavior of outputs.sql.convert unsigned setting

### ISSUE THREAD

**Issue by crabvk** [influxdata/telegraf#10671]
### Relevant telegraf.conf

```toml
[[outputs.sql]]
  driver = "clickhouse"
  data_source_name = "tcp://example.com:9000?username=user&password=pass&database=db"
  table_template = "CREATE TABLE {TABLE}({COLUMNS}) ENGINE = MergeTree() ORDER by timestamp"
  [outputs.sql.convert]
    integer = "Int64"
    real = "Float64"
    text = "String"
    timestamp = "DateTime"
    defaultvalue = "String"
    unsigned = "UInt64"
    bool = "Uint8"
```

### Logs from Telegraf

2022-02-14T06:01:11Z E! [agent] Error writing to outputs.sql: code: 62, message: Syntax error: failed at position 72 ('UInt64'): UInt64,"inactive" Int64 UInt64,"vmalloc_chunk" Int64 UInt64,"sreclaimable" Int64 UInt64,"swap_cached" Int64 UInt64,"used" Int64 UInt64,"huge_pages_free" Int64 U. Expected one of: DEFAULT, MATERIALIZED, ALIAS, NOT, NULL, COMMENT, CODEC, TTL, token, Comma, ClosingRoundBracket

### System info

Telegraf built from master branch (with #9671 PR merged), ArchLinux 5.16.8

### Steps to reproduce

1. Use telegraf config above
2. Run telegraf to collect metrics to ClickHouse
3. Got the error

### Expected behavior

No errors

### Actual behavior

[This line](https://github.com/influxdata/telegraf/blob/3c600cde72fd4b6ef3898936815f2aec88b8a066/plugins/outputs/sql/sql.go#L103) causes the error, because when value type is `uint64` the `datatype` becomes `Int64 UInt64`.

### Additional info

Setting `unsigned` is exceptional, in fact it behaves more like `unsigned_suffix` now. To fix the issue the code should be
```go
datatype = p.Convert.Unsigned
```
as with other data type settings, and default config for setting `unsigned` should be changed to
```toml
[outputs.sql.convert]
    unsigned = "INT UNSIGNED"
```
instead of
```toml
[outputs.sql.convert]
    unsigned = "UNSIGNED"
```
`UNSIGNED` is not a type on its own, it is a suffix.
