### ISSUE TITLE
Cisco Model-Driven Telemetry - Negative value bug

### ISSUE THREAD

**Issue by feifeel** [influxdata/telegraf#10682]
### Relevant telegraf.conf

```toml
[[inputs.cisco_telemetry_mdt]]
 ## Telemetry transport can be "tcp" or "grpc".  TLS is only supported when
 ## using the grpc transport.
 transport = "grpc"

 ## Address and port to host telemetry listener
 service_address = ":8081"
```

### Logs from Telegraf

 --

### System info

Telegraf 1.21.2, Redhat 8.4, InfluxFB 2.1.0, Cisco NX 9000 OS 10.1,2

### Steps to reproduce 
We would like to collect Telemetry data from this source command "show ptp_colck" via Cisco NX-API.

For that we use the Cisco Model-Driven Telemetry Telegraf Plugin.
Cisco Telemetry --------------> Telegraf Cisco MDT plugin --------> InfluxDB

### Expected behavior

When we get a negative value for this particular key "**Offsets From Master**",  the value written in InfluxDB should be the same one.

Example: If "Offsets From Master" value is -16, the data written in InfluxDB should be -16

### Actual behavior

When we should get a negative value for this particular key "**Offsets From Master**", for some reason Telegraf doen't write a negative value in influxdb and instead writes a huge positive number.

For example if  "Offsets From Master" from the switch is -16 or whatever negative value, the data written in InfluxDB is always the same 9223372036854776000
