### ISSUE TITLE
Mysql input: Slave_IO_Running returns unexpected values in newer version (1.20+)

### ISSUE THREAD

**Issue by ekk1** [influxdata/telegraf#10697]
### Relevant telegraf.conf

```toml
[[inputs.mysql]]
  servers = ["xxxxx"]
  metric_version = 2
  gather_global_variables = true
  gather_slave_status = true

[[outputs.prometheus_client]]
  listen = "xxxxx"
  metric_version = 2
  basic_username = "xxx"
  basic_password = "xxx"
  string_as_label = false
```

### Logs from Telegraf

telegraf --test output

Current Version (tested on 1.21.4 ):
> mysql,host=xxxx,slave_slave_io_running="Yes",slave_slave_sql_running="Yes" 1645512305000000000

Previous Version ( tested on 1.18.2 ):
> mysql,host=xxxx,slave_slave_io_running=1i,slave_slave_sql_running=1i 1645512448000000000

### System info

Telegraf 1.21.4,  Debian Buster

### Steps to reproduce

1. Use telegraf 1.21.4 with pasted config to scrape a running mysql instance

### Expected behavior

In previous versions, the value of slave_slave_io_running and slave_slave_sql_running is Int, which is easy for prometheus to process.

### Actual behavior

In telegraf output, the value of slave_slave_io_running and slave_slave_sql_running is now String, which is hard for prometheus to process.
Also it may break previously defined prometheus rules, like:
mysql_slave_slave_sql_running == 0
Which is also hard to discover.. since the metrics would simply disappear, not triggering any alert.

### Additional info

I was wondering if it's possible to add a option to make metrics like slave_slave_io_running to be parsed as int, like previous versions.
