### ISSUE TITLE
telegraf reboot loop

### ISSUE THREAD

**Issue by henriknoerr** [influxdata/telegraf#10709]
### Relevant telegraf.conf

```toml
[[inputs.snmp.table]]
    name = "bsnAPTable"
#    oid = "AIRESPACE-WIRELESS-MIB::bsnAPTable"
    inherit_tags = [ "hostname" ]

    [[inputs.snmp.table.field]]
      name = "APName"
      oid = "AIRESPACE-WIRELESS-MIB::bsnAPName"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "APMAC"
      oid = "AIRESPACE-WIRELESS-MIB::bsnAPDot3MacAddress"

    [[inputs.snmp.table.field]]
      name = "APLocation"
      oid = "AIRESPACE-WIRELESS-MIB::bsnAPLocation"

    [[inputs.snmp.table.field]]
     oid = "AIRESPACE-WIRELESS-MIB:bsnApIfNoOfUsers"
     oid_index_suffix = ".0"
     name = "radio24Users"
```

### Logs from Telegraf

from /var/log/messages

Feb 22 21:48:45 host systemd[1]: telegraf.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 21:48:45 host systemd[1]: telegraf.service: Failed with result 'exit-code'.
Feb 22 21:48:45 host systemd[1]: telegraf.service: Service RestartSec=100ms expired, scheduling restart.
Feb 22 21:48:45 host systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 51.
Feb 22 21:48:45 host systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Feb 22 21:48:45 host systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Feb 22 21:48:45 host telegraf[1319766]: 2022-02-22T20:48:45Z I! Starting Telegraf 1.21.4
Feb 22 21:48:45 host telegraf[1319766]: 2022-02-22T20:48:45Z I! Loaded inputs: cpu disk internal mem net ping snmp (385x) swap
Feb 22 21:48:45 host telegraf[1319766]: 2022-02-22T20:48:45Z I! Loaded aggregators:
Feb 22 21:48:45 host telegraf[1319766]: 2022-02-22T20:48:45Z I! Loaded processors: converter (2x)
Feb 22 21:48:45 host telegraf[1319766]: 2022-02-22T20:48:45Z I! Loaded outputs: influxdb_v2 (2x)
Feb 22 21:48:45 host telegraf[1319766]: 2022-02-22T20:48:45Z I! Tags enabled: host=host
Feb 22 21:48:45 host telegraf[1319766]: 2022-02-22T20:48:45Z I! [agent] Config: Interval:2m0s, Quiet:false, Hostname:"host", Flush Interval:10s
Feb 22 21:48:48 host telegraf[1319766]: 2022-02-22T20:48:48Z E! [telegraf] Error running agent: could not initialize input inputs.snmp::/etc/telegraf/telegraf.d/wlc/wlc.conf: initializing table bsnAPTable: initializing field radio24Users: translating: Could not find module named AIRESPACE-WIRELESS-MIB:bsnApIfNoOfUsers

### System info

telegrad 1.21.4

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

no service reboot loop

### Actual behavior

when telegraf 1.21.4 after the upgrade from 1.20.4 was restarted it the upgrade it went into a rebootloop.

### Additional info

using MIB
/usr/share/snmp/mibs/AIRESPACE-WIRELESS-MIB.txt
