### ISSUE TITLE
Accept varying topic lengths in MQTT topic parsing configs

### ISSUE THREAD

**Issue by samhld** [influxdata/telegraf#10716]
Telegraf is soon to support multi-segment wildcards (`#`) in MQTT topics in the topic parsing feature. This is distinct from the `+` wildcard that maps to exactly one topic segment. The `#` could match to 0 or more (not just one).

Given this support, it would be nice to use it to our advantage and allow for parsing topics of varying lengths. Below is an example use case.

Imagine I have this topic: `sensors/CLE/device5/temp` following this schema: `sensors/<site>/<device_name>/<field>`
Then I update firmware of my devices to a version that changes the target topics for metrics (this is built in and unchangeable by me). The new topics follow this schema: `sensors/<site>/<sub-site>/<version>/<device_name>/<field>`. If the same device is updated, it now publishes temp data to topic: `sensors/CLE/west/v2/device5/temp`

If I have devices running multiple versions, I may have multiple topics of varying lengths that ultimately have the same data in them and _could be_ dealt with the same way. Say I don't care about the `sub-site` and `version` data. In other words, the newly introduced topic segments aren't meaningful to me.

It would be convenient to apply the same topic parsing configuration to both cases where possible, like this:
```
[[inputs.mqtt_consumer]]
    ....
    topics = "sensors/#"
    [[inputs.mqtt_consumer.topic_parsing]]
        measurement = "measurement/_/#/_/_"
        tags = "_/site/#/device_name/_"
        fields = "_/_/#/_/field"
```
The above configuration will accept a topic of any length that matches the pattern of the first two segments and last two segments. Any segments -- whether there are 0 or more -- in between those first two and last two would be ignored.

**Comment by srebhan** [comment]
Hey @samhld, topic parsing supports a `topic` property
```toml
  # [[inputs.mqtt_consumer.topic_parsing]]
  #   topic = ""
  #   measurement = ""
  #   tags = ""
  #   fields = ""
```
which can be used to filter the topics handled by this topic-parser. In your case, you want to define such a `topic_parsing` section (there can be multiple per plugin) for each version... So like
```toml
    [[inputs.mqtt_consumer.topic_parsing]]
      topic = "sensors/+/+/+"
      measurement = "measurement/_/_/_"
      tags = "_/site/device_name/_"
      fields = "_/_/_/field"

    [[inputs.mqtt_consumer.topic_parsing]]
      topic = "sensors/+/+/+/+"
      measurement = "measurement/_/_/_/_"
      tags = "_/site/sub_site/device_name/_"
      fields = "_/_/_/_/field"
```
Does that make sense?

**Comment by srebhan** [comment]
I see. So IMO having
```toml
    [[inputs.mqtt_consumer.topic_parsing]]
      topic = "sensors/#/+/+"
      measurement = "measurement/__"
      tags = "_/site/__/device_name/__"
      fields = "__/field"
```
with `__` (double low-dash) being "one or more elements", would be what you want is this correct? Of course we could also use other placeholders...
