### ISSUE TITLE
How to get HTTPCode_ELB_5XX sum of AWS ApplicationLoadBalancer ?

### ISSUE THREAD

**Issue by yongnam-kwon** [influxdata/telegraf#10738]
### Relevant telegraf.conf

```toml
[[inputs.cloudwatch]]
  region = "ap-northeast-2"
  period = "5m"
  delay = "5m"
  interval = "5m"

  namespace = "AWS/ApplicationELB"

  [[inputs.cloudwatch.metrics]]
    names = [ "HTTPCode_ELB_5XX_Count" ]
    statistic_include = [ "sum" ]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "LoadBalancer"
      value = "app/alb-pkr-rda-n*"
```

### Logs from Telegraf

I executed telegraf command, like below. But I couldn't get any results...

$ telegraf --input-filter cloudwatch --test
No result

### System info

telegraf 1.19.3, Amazon Linux 2

### Steps to reproduce

1. Set inputs.cloudwatch plugin like above.
2. [in server] execute "telegraf --config /etc/telegraf/telegraf.conf --input-filter cloudwatch --test"
3.  get no result from the command.
...

### Expected behavior

I expected the result like "<measurement-name>,<tags-key-value> http_code_elb_5xx_count_sum=1234 <timestamp>".
A result in the past is like below.

cloudwatch_aws_application_elb,availability-zone=$AZ,host=$HOST,instance-group=adm,instance-id=$INSTANCEID,instance-type=$INSTANCETYPE,load_balancer=app/alb-pkr-rda-nxxx/xxrandomyy,purpose=OPERATION,region=ap-northeast-2,role=$ROLE,service-name=RDA,target_group=targetgroup/RDA-NXXX/yyyrandomxxxx http_code_elb_5xx_count_sum=1234 1645770240000000000

### Actual behavior

No result.

### Additional info

In the past(about 6 months before?), this conf worked,
but now telegraf cannot collect the metrics from ALB.
(telegraf --input-filter cloudwatch --test → none)

How can I set the telegraf configuration for get "HTTPCode_ELB_5XX_Count"?
