### ISSUE TITLE
ping6 input plugin broken under FreeBSD 13

### ISSUE THREAD

**Issue by PacoTyson** [influxdata/telegraf#10743]
### Relevant telegraf.conf

```toml
[global_tags]


[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://<redacted>:8086"]
  database = "supervision"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  insecure_skip_verify = false







[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = true

[[inputs.disk]]

[[inputs.diskio]]

[[inputs.mem]]

[[inputs.processes]]


[[inputs.system]]

[[inputs.net]]

[[inputs.pf]]

[[inputs.ping]]
  method = "exec"
  binary = "ping6"
  urls = ['2001:db8::1']
```

### Logs from Telegraf

...
2022-02-26T23:03:30Z E! [inputs.ping] Error in plugin: host 2001:db8::1: ping6: illegal option -- x
usage:
        ping [-4AaDdfHnoQqRrv] [-C pcp] [-c count] [-G sweepmaxsize]
            [-g sweepminsize] [-h sweepincrsize] [-i wait] [-l preload]
            [-M mask | time] [-m ttl] [-P policy] [-p pattern] [-S src_addr]
            [-s packetsize] [-t timeout] [-W waittime] [-z tos] IPv4-host
        ping [-4AaDdfHLnoQqRrv] [-C pcp] [-c count] [-I iface] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-P policy] [-p pattern]
            [-S src_addr] [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] IPv4-mcast-group
        ping [-6AaDdfHnNoOquvyY] [-b bufsiz] [-c count] [-e gateway]
            [-I interface] [-i wait] [-k addrtype] [-l preload] [-m hoplimit]
            [-p pattern] [-P policy] [-S sourceaddr] [-s packetsize] [-t timeout]
            [-W waittime] [-z tclass] [IPv6-hops ...] IPv6-host, exit status 1
2022-02-26T23:03:40Z E! [inputs.ping] Error in plugin: host 2001:db8::1: ping6: illegal option -- x
usage:
        ping [-4AaDdfHnoQqRrv] [-C pcp] [-c count] [-G sweepmaxsize]
            [-g sweepminsize] [-h sweepincrsize] [-i wait] [-l preload]
            [-M mask | time] [-m ttl] [-P policy] [-p pattern] [-S src_addr]
            [-s packetsize] [-t timeout] [-W waittime] [-z tos] IPv4-host
        ping [-4AaDdfHLnoQqRrv] [-C pcp] [-c count] [-I iface] [-i wait]
            [-l preload] [-M mask | time] [-m ttl] [-P policy] [-p pattern]
            [-S src_addr] [-s packetsize] [-T ttl] [-t timeout] [-W waittime]
            [-z tos] IPv4-mcast-group
        ping [-6AaDdfHnNoOquvyY] [-b bufsiz] [-c count] [-e gateway]
            [-I interface] [-i wait] [-k addrtype] [-l preload] [-m hoplimit]
            [-p pattern] [-P policy] [-S sourceaddr] [-s packetsize] [-t timeout]
            [-W waittime] [-z tclass] [IPv6-hops ...] IPv6-host, exit status 1
...

### System info

OPNsense 22.1.1_3-amd64; FreeBSD 13.0-STABLE 

### Steps to reproduce

1. Setup a ping6 input plugin on Opnsense 22.1 (FreeBSD13 based firewall)

### Expected behavior

No error should appear in logs and ping6 metrics should be generated.

### Actual behavior

Ping6 utility returns an error : no metric is generated and an error log is produced.

### Additional info

[The ping utility changed in FreeBSD13](https://cgit.freebsd.org/src/commit/?id=3cde9171d2d5), -x doesn't exist anymore.

Issue opened first on Opnsense : https://github.com/opnsense/plugins/issues/2864
