### ISSUE TITLE
mqtt_consumer timestamp_path breaks configuration

### ISSUE THREAD

**Issue by JaegerStephan** [influxdata/telegraf#10753]
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
servers = ["tcp://localhost:1883"]
topics = ["#",]
data_format = "json_v2"
[[inputs.mqtt_consumer.topic_parsing]]
topic = "+/+"
tags = "Line/Measure"
[[inputs.mqtt_consumer.json_v2]]
timestamp_path = "time"
timestamp_format = "unix_ms"
[[inputs.mqtt_consumer.json_v2.field]]
path = "position"
rename = "p"
type = "int"
```

### Logs from Telegraf

nothing particular regarding [[input.mqtt_consumer]]

### System info

Telegraf 1.21.4 ,Ubuntu 20.04, docker 20.10.12

### Steps to reproduce

1. when having the MQTT input plugin with json_v2 data format [[inputs.mqtt_consumer.json_v2]]
2. whenever timestamp_path and timestamp_format is used all the configuration after the timestamp_path and timestamp_format is ignored and timestamp is also ignored

### Expected behavior

Using timestamp_path = "time" and timestamp_format = "unix_ms" should read the timestamp from the MQTT payload and the defined [[inputs.mqtt_consumer.json_v2.field]] should be renamed (from "position" to "p") and appropriately formated (type).

### Actual behavior

Whenever the timestamp_path and timestamp_format are used, whether the timestamp is applied correctly to the influx database (always the current time is applied) nor the field is transformed correctly (rename). If I define the timestamp_path and timestamp_format after the [[inputs.mqtt_consumer.json_v2.field]], at least the field is transformed correctly although the timestamp is never applied correctly.

### Additional info

MQTT Message

topic:
01/06

payload:
{
"time": "1646052034000",
"position": 55
}
