### ISSUE TITLE
Something in SNMP MIB reading behaviour changed from 1.20 to 1.21

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/telegraf#10755]
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
   agents = [ "10.0.0.1" ]
   interval = "60s"
   timeout = "10s"
   retries = 2
   version = 2
   community = "public"
   max_repetitions = 10
   name = "snmp.rtx830"
# can't find ifTable without this!!!!!! added for 1.21
   path = ["/usr/local/share/snmp/mibs", "/usr/share/snmp/mibs"]
#
#   ## measurement name
#   name = "system"
   [[inputs.snmp.field]]
     name = "sysName"
     is_tag = true
     oid = "RFC1213-MIB::sysName.0"
   [[inputs.snmp.field]]
     name = "sysObjectID"
     oid = "RFC1213-MIB::sysObjectID.0"
   [[inputs.snmp.field]]
     name = "sysDescr"
     oid = "RFC1213-MIB::sysDescr.0"
   [[inputs.snmp.field]]
     name = "sysContact"
     oid = "RFC1213-MIB::sysContact.0"
   [[inputs.snmp.field]]
     name = "sysLocation"
     oid = "RFC1213-MIB::sysLocation.0"
   [[inputs.snmp.field]]
     name = "sysUpTime"
     oid = "RFC1213-MIB::sysUpTime.0"

#
# YAMAHA specific
#
   [[inputs.snmp.field]]
     name = "yrhCpuType"
     oid = "YAMAHA-RT-HARDWARE::yrhCpuType.0"
   [[inputs.snmp.field]]
     name = "yrhMemorySize"
     oid = "YAMAHA-RT-HARDWARE::yrhMemorySize.0"
   [[inputs.snmp.field]]
     name = "yrfRevision"
     oid = "YAMAHA-RT-FIRMWARE::yrfRevision.0"
   [[inputs.snmp.field]]
     name = "yrhMemoryUtil"
     # oid = ".1182.2.1.4"
     oid = "YAMAHA-RT-HARDWARE::yrhMemoryUtil.0"
   [[inputs.snmp.field]]
     name = "yrhCpuUtil5sec"
     # oid = ".1182.2.1.5"
     oid = "YAMAHA-RT-HARDWARE::yrhCpuUtil5sec.0"
   [[inputs.snmp.field]]
     name = "yrhCpuUtil1min"
     # oid = ".1182.2.1.6"
     oid = "YAMAHA-RT-HARDWARE::yrhCpuUtil1min.0"
   [[inputs.snmp.field]]
     name = "yrhCpuUtil5min"
     # oid = ".1182.2.1.7"
     oid = "YAMAHA-RT-HARDWARE::yrhCpuUtil5min.0"

    # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
    # IF-MIB::ifXTable contains counters on input and output traffic as well as errors and discards.
   [[inputs.snmp.table]]
    name = "snmp.rtx830.interface"
    # inherit_tags = [ "sysName" ]
    # oid = "IF-MIB::ifXTable"
    oid = "IF-MIB::ifTable"
    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

   [[inputs.snmp.table]]
    name = "snmp.rtx830.interface"
    # inherit_tags = [ "sysName" ]
    oid = "IF-MIB::ifXTable"
    # oid = "IF-MIB::ifTable"
    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

# tagpass just does not work well. There are over 150 interfaces and we only want *FIVE*
# maybe there's a way to ask only for LAN1 LAN2 TUNNEL[1] TUNNEL[2] VLAN2 if so, no one knows how.
#
```

### Logs from Telegraf

2022-03-01T21:41:19+09:00 E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing table snmp.rtx830.interface: translating: Could not find node named ifTable
2022-03-01T21:42:20+09:00 E! [inputs.snmp] Error in plugin: agent 10.0.0.1: performing get on field yrhCpuType: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
2022-03-01T21:42:20+09:00 E! [telegraf] Error running agent: input plugins recorded 1 errors

### System info

Freebsd 13, telegraf 1.21.1

### Steps to reproduce

Put yamaha mibs in /usr/local/share/snmp/mibs/
Test with simple SNMPWALK.
snmpwalk -m +ALL -v 2c -c public 10.0.0.1 YAMAHA-RT-HARDWARE::yrhCpuType.0
YAMAHA-RT-HARDWARE::yrhCpuType.0 = INTEGER: a38x(16)

Test with telegraf:
/usr/local/bin/telegraf --config=/usr/local/etc/telegraf.conf --config-directory=/usr/local/etc/telegraf.conf.d --test --input-filter snmp > a1

no result in the file. 203 interfaces though!

### Expected behavior

works like it does on 1.20

### Actual behavior

does not work.

2022-03-01T21:42:20+09:00 E! [inputs.snmp] Error in plugin: agent 10.0.0.1: performing get on field yrhCpuType: marshal: marshalPDU: unable to marshal varbind list: unable to marshal OID: Invalid object identifier
2022-03-01T21:42:20+09:00 E! [telegraf] Error running agent: input plugins recorded 1 errors

### Additional info

This works on 1.20 so clearly this gosmi thing is the culprit but I have no idea how to investigate further.
