### ISSUE TITLE
change uri scheme for default RavenDB configuration 

### ISSUE THREAD

**Issue by ml054** [influxdata/telegraf#10765]
### Relevant telegraf.conf

```toml
[[inputs.ravendb]]
  ## Node URL and port that RavenDB is listening on
  url = "http://localhost:8080"

  ## RavenDB X509 client certificate setup
  tls_cert = "/etc/telegraf/raven.crt"
  tls_key = "/etc/telegraf/raven.key"
```

### Logs from Telegraf

none

### System info

Latest version

### Steps to reproduce

1. default scheme is https but should be http

### Expected behavior

http along with default port: 8080

### Actual behavior

https and 8080 port
