### ISSUE TITLE
Json_v2 optional only works on objects not on root 

### ISSUE THREAD

**Issue by hurricanepkt** [influxdata/telegraf#10776]
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer.json_v2]]
      measurement_name_path = "Alias"
      timestamp_path = "Time"
      timestamp_format = "2006-01-02T15:04:05"
      timestamp_timezone = "America/New_York"
      [[inputs.mqtt_consumer.json_v2.tag]]
          path = "MAC"
      [[inputs.mqtt_consumer.json_v2.field]]
          path = "RSSI"
          type = "float"
      [[inputs.mqtt_consumer.json_v2.field]]
          path = "Soil_Moisture"
          type = "float"
          optional = true
      [[inputs.mqtt_consumer.json_v2.field]]
          path = "Temperature"
          type = "float"
          optional = true
```

### Logs from Telegraf

2022-03-03T18:01:57Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2022-03-03T18:01:57Z E! [inputs.mqtt_consumer] Error in plugin: GJSON Path returned null, either couldn't find value or path has null value
2022-03-03T18:02:10Z E! [inputs.mqtt_consumer] Error in plugin: GJSON Path returned null, either couldn't find value or path has null value

### System info

Telegraf 1.21.4 on Docker (arm)

### Steps to reproduce

1. Try and injest Tasmota-Blerry Mqtt Content from devices with different information  (two samples below)

...

**ATCpvvx**
```
{
  "Model": "ATCpvvx",
  "Battery_Voltage": 3.038,
  "RSSI": -86,
  "Alias": "ble_cli_bathroom",
  "Humidity": 68,
  "Temperature": 24.2,
  "Battery": 93,
  "DewPoint": 17.91,
  "MAC": "A4C138F07A87",
  "Time": "2022-03-03T13:01:57"
}
```

**Xiaomi  - MiFlora**
```
{
  "Model": "Xiaomi",
  "RSSI": -95,
  "Alias": "ble_plant_olive",
  "Lux": 112630,
  "DevID": "HHCCJCY01",
  "Temperature": 30.5,
  "Time": "2022-03-03T13:36:06",
  "MAC": "C47C8D6C82FE",
  "Soil_Moisture": 0
}
```

### Expected behavior

Optional Fields would be null or blank

### Actual behavior

Get  "GJSON Path returned null, either couldn't find value or path has null value" errors

### Additional info

Similar to [pull request 10468](https://github.com/influxdata/telegraf/pull/10468)

But that only works when optional fields are not in the root.
