### ISSUE TITLE
Syslog "eror" level is tagged as "info"

### ISSUE THREAD

**Issue by PoloKltz** [influxdata/telegraf#10784]
### Description 
When collecting Grafana error (actual level sent by Grafana is `eror`) logs using syslog input and Telegraf, the message is tagged with an `info`  severity, thus preventing to be filter correctly afterwards. 

### Relevant telegraf.conf

```toml
# Telegraf - /etc/telegraf/telegraf.d/inputs.syslog.conf

[[inputs.syslog]]
  server = "udp://:6514"

# Syslog - /etc/rsyslog.d/50-telegraf.conf
*.* @localhost:6514;RSYSLOG_SyslogProtocol23Format
```

### Logs from Telegraf

![image](https://user-images.githubusercontent.com/27371716/156994343-e9ac900d-a5fa-4827-8573-a905cceaaf6f.png)

### System info

Telegraf 1.21.4, Ubuntu 20.04

### Steps to reproduce

1. Deploy a running instance of Grafana
2. Set rsyslog configuration
3. Enable syslog input on Telegraf
4. Trigger any error level on Grafana, which result in `eror` level log message sent to syslog

### Expected behavior

Severity of this log message should be tagged as `err`

### Actual behavior

Severity of this log message should be tagged as `info`
