### ISSUE TITLE
nginx_vts plugin in nginx1 20.1 operation error, unable to collect data normally

### ISSUE THREAD

**Issue by nondevops** [influxdata/telegraf#10809]
### Relevant telegraf.conf

```toml
###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################


# Read Nginx virtual host traffic status module information (nginx-module-vts)
[[inputs.nginx_vts]]
  ## An array of ngx_http_status_module or status URI to gather stats.
  #urls = ["http://localhost/status"]
  urls = ["http://xxx.devops.press/status/format/prometheus"]
  #urls = ["http://xxx.devops.press"]

  ## HTTP response timeout (default: 5s)
  response_timeout = "5s"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false
```

### Logs from Telegraf

![image](https://user-images.githubusercontent.com/12181410/158047780-1256e0e7-fc2a-4e7f-8ab0-42e55ed08ae7.png)

### System info

centos7 /Telegraf 1.20.4 (git: HEAD 34ad5aa1)/

### Steps to reproduce

1、Generate nginx_ For VTS configuration,
2、no corresponding return data is available using the test parameter of telegraf

### Expected behavior

this is fail

### Actual behavior

Can return to nginx normally_ VTS Information

### Additional info

By the way, my nginx version is 1.20.1. I suspect it is caused by the incompatibility of the nginx version. Please repair it if possible.

The following methods have been tried and cannot be solved:

1、nginx_ vts. The URL parameter configuration in conf adds the specified parameters (/ status / format / Prometheus and / status / format / JSON);

2、nginx-vts. devopss. press. In the configuration of conf, modify the value of format to JSON or Prometheus;

exts:
![Uploading image.png…]()

**Comment by powersj** [comment]
Hi,

> The URL parameter configuration in conf adds the specified parameters (/ status / format / Prometheus and / status / format / JSON);

Who adds those? Nginx?

>   urls = ["http://xxx.devops.press/status/format/prometheus"]

Can you provide an example of the content found at the above URL? As well as the content at `http://xxx.devops.press/status/`

>  2、no corresponding return data is available using the test parameter of telegraf

Do you mean running with `--test`?

**Comment by nondevops** [comment]
> Hi,
> 
> > The URL parameter configuration in conf adds the specified parameters (/ status / format / Prometheus and / status / format / JSON);
> 
> Who adds those? Nginx?
> 
> > urls = ["http://xxx.devops.press/status/format/prometheus"]
> I tried to solve the problem with this configuration, but in fact, it can't solve the problem. The correct URL given by the official is configured as http://xxx.xxx.xxx/status


> Can you provide an example of the content found at the above URL? As well as the content at `http://xxx.devops.press/status/`
> 
> > 2、no corresponding return data is available using the test parameter of telegraf
> 
> Do you mean running with `--test`?
The -- test parameter is used for debugging, but there is no correct response result

**Comment by powersj** [comment]
Can you provide an example of the content found at the above URL? As well as the content at http://xxx.devops.press/status/

**Comment by nondevops** [comment]
> Can you provide an example of the content found at the above URL? As well as the content at http://xxx.devops.press/status/
This is the official demo
![image](https://user-images.githubusercontent.com/12181410/158599506-6f40a900-c954-4cb6-bfb9-c64492893e7d.png)

This is the configuration URL formed according to my own needs. At the same time, the official document provides three configuration formats, including HTML JSON Prometheus.

![image](https://user-images.githubusercontent.com/12181410/158599902-6a4ac8dd-18ed-4a67-a0fc-74ab9ff8d539.png)
http://xxxs.devops.press/status/format/html
http://xxx.devops.press/status/format/json
http://xxx.devops.press/status/format/prometheus
I tried to configure these three formats, but I couldn't get the response data correctly

**Comment by powersj** [comment]
> http://xxxs.devops.press/status/format/html
> http://xxx.devops.press/status/format/json
> http://xxx.devops.press/status/format/prometheus

What was the error message for each of these?

**Comment by powersj** [comment]
The plugin is expecting the output to be JSON:

```go
	case "application/json":
		return gatherStatusURL(bufio.NewReader(resp.Body), getTags(addr), ACC)
```

Otherwise, you will get the error about the unexpected content type.

In my nginx config I set:

```c
        location /status {
            vhost_traffic_status_display;
            vhost_traffic_status_display_format json;
        }
```

with this Telegraf config:

```toml
[agent]
  omit_hostname = true

[[outputs.file]]

[[inputs.nginx_vts]]
  urls = ["http://192.168.100.236/status"]
```

I got the following output:

```s
nginx_vts_connections,port=80,source=192.168.100.236 accepted=2i,handled=2i,requests=9i,active=2i,reading=0i,writing=1i,waiting=1i 1647444840000000000
nginx_vts_server,port=80,source=192.168.100.236,zone=localhost requests=8i,in_bytes=2524i,response_2xx_count=8i,cache_miss=0i,cache_expired=0i,cache_revalidated=0i,request_time=0i,out_bytes=17005i,response_4xx_count=0i,cache_bypass=0i,cache_stale=0i,response_5xx_count=0i,cache_scarce=0i,response_1xx_count=0i,response_3xx_count=0i,cache_updating=0i,cache_hit=0i 1647444840000000000
nginx_vts_server,port=80,source=192.168.100.236,zone=* request_time=0i,response_1xx_count=0i,cache_scarce=0i,response_3xx_count=0i,cache_miss=0i,cache_expired=0i,cache_stale=0i,cache_updating=0i,cache_revalidated=0i,in_bytes=2524i,out_bytes=17005i,requests=8i,response_2xx_count=8i,response_4xx_count=0i,response_5xx_count=0i,cache_bypass=0i,cache_hit=0i 1647444840000000000
2022-03-16T15:34:07Z D! [outputs.file] Wrote batch of 3 metrics in 71.5µs
2022-03-16T15:34:07Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics

```

I don't think this is a bug in Telegraf, and I would suggest updating your nginx config to use json output for the status output.

Thanks!
