### ISSUE TITLE
please provide an snmp table filtering example in the documentation.

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/telegraf#10801]
(The community won't let me login or signup!)

Please provide an example of how to filter out unnecessary interfaces from the following:
```toml
# more yamaha stuff above, like cpu, free memory, uptime

    # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards. (
    # IF-MIB::ifXTable contains counters on input and output traffic as well as errors and discards. (in/out counters useful)
   [[inputs.snmp.table]]
    name = "snmp.rtx830.interface"
    # inherit_tags = [ "sysName" ]
    # oid = "IF-MIB::ifXTable"
    oid = "IF-MIB::ifTable"
    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

   [[inputs.snmp.table]]
    name = "snmp.rtx830.interface"
    # inherit_tags = [ "sysName" ]
    oid = "IF-MIB::ifXTable"
    # oid = "IF-MIB::ifTable"
    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true
```
As is, the above gives me 202 lines. Many of which are completely unnecessary. This router has a ridiculous number of interfaces and only 4 or 5 of them are in use:
AMAHA-RT-INTERFACES::yrIfNumber.0 = INTEGER: 162

I would like to know how to filter the above so that I only keep certain interfaces, e.g.

YAMAHA-RT-INTERFACES::yrIfDescr.1 = STRING: "LAN1"
YAMAHA-RT-INTERFACES::yrIfDescr.2 = STRING: "LAN2"
YAMAHA-RT-INTERFACES::yrIfDescr.133 = STRING: "TUNNEL[1]"
YAMAHA-RT-INTERFACES::yrIfDescr.134 = STRING: "TUNNEL[2]"

Alternatively, how to request stuff only for the above interfaces.  
```text
> snmp.rtx830.interface,agent_host=10.0.0.1,ifDescr=LAN1,ifIndex=1 ifAdminStatus=1i,ifInDiscards=20906i,ifInErrors=0i,ifInNUcastPkts=81777853i,ifInOctets=4270640405i,ifInUcastPkts=2422328177i,ifInUnknownProtos=33746905i,ifLastChange=0i,ifMtu=1500i,ifOperStatus=1i,ifOutDiscards=2i,ifOutErrors=0i,ifOutNUcastPkts=1165559i,ifOutOctets=3019370283i,ifOutQLen=0i,ifOutUcastPkts=853158092i,ifPhysAddress="00:a0:de:e8:23:a4",ifSpecific=".0.0",ifSpeed=1000000000i,ifType=6i 1646921624000000000
> snmp.rtx830.interface,agent_host=10.0.0.1,ifDescr=LAN1 ifHCInBroadcastPkts=31748017i,ifHCInMulticastPkts=50029836i,ifHCInOctets=1176796729994i,ifHCInUcastPkts=2422328380i,ifHCOutBroadcastPkts=304692i,ifHCOutMulticastPkts=860867i,ifHCOutOctets=5500577555093i,ifHCOutUcastPkts=5148125571i,ifInBroadcastPkts=31748017i,ifInMulticastPkts=50029836i,ifOutBroadcastPkts=304692i,ifOutMulticastPkts=860867i 1646921624000000000
```
This is LAN1, I do not know why one has "ifIndex" and the other does not.

**Comment by Hipska** [comment]
> I do not know why one has "ifIndex" and the other does not.

Simply because `ifTable` has this field, but `ifXTable` doesn't.

If you want to filter metrics, this is already [explained in the docs](https://github.com/influxdata/telegraf/tree/master/config#metric-filtering). In your case it would be something like:
```toml
  [inputs.snmp.tagpass]
    ifDescr = ["LAN1", "LAN2"]
```

What I would do was merge these 2 into 1 table and also make `ifAdminStatus` a tag, so then you can filter the ones that are enabled:
```toml
  # Don't collect data for down(2) or testing(3) interfaces
  [inputs.snmp.tagdrop]
    ifAdminStatus = ["2", "3"]
```
