### ISSUE TITLE
Using empty string for `precision` in AgentConfig causes startup error

### ISSUE THREAD

**Issue by pichlermarc** [influxdata/telegraf#10813]
### Relevant telegraf.conf

```toml
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})

[global_tags]

[agent]

interval = "10s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
precision = ""
hostname = ""
omit_hostname = false

[[outputs.influxdb]]

[[inputs.cpu]]

percpu = true
totalcpu = true
collect_cpu_time = false
report_active = false

[[inputs.disk]]
ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
```

### Logs from Telegraf

```
2022-03-14T09:52:26Z E! [telegraf] Error running agent: Error loading config file sample-config.conf: error parsing [agent]: line 27: (config.AgentConfig.Precision) time: invalid duration ""
```

### System info

Telegraf 1.22.0-4fcff21c (git: master 4fcff21c), Ubuntu 20.04

### Steps to reproduce

1. Build telegraf from master (1d7295f252b8afbe8dd1613b7ef13d0ebb05dced)
2. ./telegraf config > default-config.conf
3. ./telegraf --config default-config.conf

### Expected behavior

I was expecting the default config that contains `""` for `precision` in the AgentConfig to ignore the "empty" value and use a default value, as was the case with previous versions. Alternatively, I was expecting the default config obtainable via `telegraf config` to work out of the box.

### Actual behavior

telegraf exits with code 1 and mentions `time: invalid duration ""` as the reason.

### Additional info

Possibly related to #10803, #10734
