### ISSUE TITLE
http_response - HTTP Request Body seems doesn't works

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#10839]
### Relevant telegraf.conf

```toml
[[inputs.http_response]]
  urls = ["https://example.com/test.php"]
  method = "POST"
  body = '''
  {'fake':'data'}
  '''
  response_body_field = 'test'
```

### Logs from Telegraf

2022-03-17T15:46:48Z I! Starting Telegraf 1.21.4
> http_response,host=XXXX,method=POST,result=success,server=https://example.com/test.php,status_code=200 content_length=13i,http_response_code=200i,response_time=0.044556621,result_code=0i,result_type="success",test="array(0) {
}
" 1647532009000000000

### System info

Telegraf 1.15.2 / Telegraf 1.21.4

### Steps to reproduce

1. Add a webserver with php
2. Add this php file
```php
<?php
var_dump($_POST);
```
3. Try a curl
```bash
curl --request POST 'https://example.com/test.php' --form 'fake=data'
array(1) {
  ["fake"]=>
  string(4) "data"
}
```
4. Try with telegraf
5. The array output is empty

### Expected behavior

PHP is supposed to receive the data during the POST

### Actual behavior

PHP didn't receive any body data during the POST
