### ISSUE TITLE
inputs nginx_vts json error parser 

### ISSUE THREAD

**Issue by feiniao886** [influxdata/telegraf#10877]
### Relevant telegraf.conf

```toml
[[inputs.nginx_vts]]
  ## An array of ngx_http_status_module or status URI to gather stats.
  urls = ["http://localhost:18080/status/format/json"]
  ## HTTP response timeout (default: 5s)
  response_timeout = "5s"
```

### Logs from Telegraf

2022-03-23T15:03:50Z I! Starting Telegraf 1.21.4
2022-03-23T15:03:50Z I! Loaded inputs: nginx_vts
2022-03-23T15:03:50Z I! Loaded aggregators: 
2022-03-23T15:03:50Z I! Loaded processors: 
2022-03-23T15:03:50Z W! Outputs are not used in testing mode!
2022-03-23T15:03:50Z I! Tags enabled: dc=ksord-dc host=10-11-17-90
2022-03-23T15:03:50Z E! [inputs.nginx_vts] Error in plugin: http://localhost:18080/status/ returned unexpected content type 
2022-03-23T15:03:50Z E! [telegraf] Error running agent: input plugins recorded 1 errors

### System info

Telegraf 1.21.4 ubuntu20.4

### Steps to reproduce

telegraf -config ./telegraf.conf -input-filter nginx_vts -test

### Expected behavior

sucess

### Actual behavior

error

### Additional info

2022-03-23T15:03:50Z I! Starting Telegraf 1.21.4
2022-03-23T15:03:50Z I! Loaded inputs: nginx_vts
2022-03-23T15:03:50Z I! Loaded aggregators: 
2022-03-23T15:03:50Z I! Loaded processors: 
2022-03-23T15:03:50Z W! Outputs are not used in testing mode!
2022-03-23T15:03:50Z I! Tags enabled: dc=ksord-dc
2022-03-23T15:03:50Z E! [inputs.nginx_vts] Error in plugin: http://localhost:18080/status/ returned unexpected content type 
2022-03-23T15:03:50Z E! [telegraf] Error running agent: input plugins recorded 1 errors
