### ISSUE TITLE
directory_monitor + unpivot stalls with no error message

### ISSUE THREAD

**Issue by meowcat** [influxdata/telegraf#10894]
### Relevant telegraf.conf

```toml
# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "3s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  ## Log at debug level.
  debug = true
  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  logfile = ""
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

#Send telegraf metrics to file(s)
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["/opt/telegraf/metrics.out"]
  data_format = "influx"
  use_batch_format = false
  rotation_interval = "0"
  rotation_max_size = "0MB"
  rotation_max_archives = 5

[[inputs.directory_monitor]]

  name_override = "mymetric"
  directory = "/data/in"
  #
  ## The directory to move finished files to.
  finished_directory = "/data/out"
  error_directory = "/data/err"
  files_to_monitor = [".*\\.csv"]
  directory_duration_threshold = "10s"
  max_buffered_metrics = 5000
  file_queue_size = 100000
  

  data_format = "csv"
  csv_delimiter = "\t"
  csv_header_row_count = 0
  #csv_skip_rows = 1
  csv_column_names = [
    "ts",
    "date",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "AA",
    "AB",
    "AC",
    "AD",
    "AE",
    "AF",
    "AG",
    "AH",
    "AI",
    "AJ",
    "AK",
    "AL",
    "AM",
    "AN",
    "AO",
    "AP",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU"
  ]
  csv_timestamp_column = "date"
  csv_timestamp_format = "2006-01-02 15:04:05"
  file_tag = "machine"

[[processors.unpivot]]
  order = 1
  namepass = ["mymetric"]
  tag_key = "name"
  value_key = "value"
  #tagdrop = ["machine"]
```

### Logs from Telegraf

> docker-compose up
Starting telegraf ... done
Attaching to telegraf
telegraf    | 2022-03-25T13:59:22Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf    | 2022-03-25T13:59:22Z I! Starting Telegraf 1.22.0
telegraf    | 2022-03-25T13:59:22Z I! Loaded inputs: directory_monitor
telegraf    | 2022-03-25T13:59:22Z I! Loaded aggregators:
telegraf    | 2022-03-25T13:59:22Z I! Loaded processors: unpivot
telegraf    | 2022-03-25T13:59:22Z I! Loaded outputs: file
telegraf    | 2022-03-25T13:59:22Z I! Tags enabled: host=61a134236d67
telegraf    | 2022-03-25T13:59:22Z I! [agent] Config: Interval:3s, Quiet:false, Hostname:"61a134236d67", Flush Interval:10s
telegraf    | 2022-03-25T13:59:22Z D! [agent] Initializing plugins
telegraf    | 2022-03-25T13:59:22Z D! [agent] Connecting outputs
telegraf    | 2022-03-25T13:59:22Z D! [agent] Attempting connection to [outputs.file]
telegraf    | 2022-03-25T13:59:22Z D! [agent] Successfully connected to outputs.file
telegraf    | 2022-03-25T13:59:22Z D! [agent] Starting service inputs
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Wrote batch of 1000 metrics in 130.74331ms
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Buffer fullness: 85158 / 100000 metrics
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Wrote batch of 1000 metrics in 135.992551ms
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Buffer fullness: 100000 / 100000 metrics
telegraf    | 2022-03-25T13:59:24Z W! [outputs.file] Metric buffer overflow; 73271 metrics have been dropped
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Wrote batch of 1000 metrics in 108.057716ms
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Buffer fullness: 100000 / 100000 metrics
telegraf    | 2022-03-25T13:59:24Z W! [outputs.file] Metric buffer overflow; 53729 metrics have been dropped
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Wrote batch of 1000 metrics in 94.145368ms
telegraf    | 2022-03-25T13:59:24Z D! [outputs.file] Buffer fullness: 99000 / 100000 metrics
telegraf    | 2022-03-25T13:59:32Z D! [outputs.file] Wrote batch of 1000 metrics in 100.444691ms
telegraf    | 2022-03-25T13:59:32Z D! [outputs.file] Wrote batch of 1000 metrics in 92.004273ms
telegraf    | 2022-03-25T13:59:32Z D! [outputs.file] Wrote batch of 1000 metrics in 90.857812ms
telegraf    | 2022-03-25T13:59:32Z D! [outputs.file] Wrote batch of 1000 metrics in 90.163131ms
telegraf    | 2022-03-25T13:59:32Z D! [outputs.file] Wrote batch of 1000 metrics in 88.621189ms
telegraf    | 2022-03-25T13:59:32Z D! [outputs.file] Wrote batch of 1000 metrics in 90.008234ms
telegraf    | 2022-03-25T13:59:32Z D! [outputs.file] Wrote batch of 1000 metrics in 89.934326ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 106.54132ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 99.471323ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 96.228434ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 89.097881ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 92.837014ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 92.332164ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 90.554029ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 90.685714ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 90.896274ms
telegraf    | 2022-03-25T13:59:33Z D! [outputs.file] Wrote batch of 1000 metrics in 90.339688ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 89.751924ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 95.288561ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 91.075279ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 92.867588ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 94.296442ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 95.643658ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 90.940446ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 90.953624ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 90.253176ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 90.764847ms
telegraf    | 2022-03-25T13:59:34Z D! [outputs.file] Wrote batch of 1000 metrics in 90.825323ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 98.191707ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 98.44443ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 91.792156ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 92.139663ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 97.008161ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 91.652571ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 93.820425ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 89.481059ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 92.411415ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 90.682637ms
telegraf    | 2022-03-25T13:59:35Z D! [outputs.file] Wrote batch of 1000 metrics in 91.006148ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 98.686651ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 104.666173ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 90.323336ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 95.431408ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 92.028407ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 92.479711ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 93.743418ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 90.14061ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 90.475251ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 89.103945ms
telegraf    | 2022-03-25T13:59:36Z D! [outputs.file] Wrote batch of 1000 metrics in 94.284879ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 99.504767ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 92.68628ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 97.967189ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 90.719876ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 91.548769ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 93.821748ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 92.599069ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 95.495148ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 93.170502ms
telegraf    | 2022-03-25T13:59:37Z D! [outputs.file] Wrote batch of 1000 metrics in 90.158257ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 91.565076ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 89.902957ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 93.075782ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 90.948143ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 93.961806ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 90.226733ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 94.135023ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 90.930213ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 91.236827ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 91.843087ms
telegraf    | 2022-03-25T13:59:38Z D! [outputs.file] Wrote batch of 1000 metrics in 88.750102ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 98.032994ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 105.283709ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 93.072829ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 93.998129ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 95.085389ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 93.96725ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 95.94414ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 91.170316ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 95.634189ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 93.092077ms
telegraf    | 2022-03-25T13:59:39Z D! [outputs.file] Wrote batch of 1000 metrics in 92.511018ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 93.181399ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 90.559947ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 93.576686ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 92.486305ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 92.303799ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 92.645501ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 93.655857ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 98.235836ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 91.470974ms
telegraf    | 2022-03-25T13:59:40Z D! [outputs.file] Wrote batch of 1000 metrics in 92.420418ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Wrote batch of 1000 metrics in 90.485421ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Wrote batch of 1000 metrics in 92.662521ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Wrote batch of 1000 metrics in 92.379334ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Wrote batch of 1000 metrics in 91.873798ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Wrote batch of 1000 metrics in 93.482953ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Wrote batch of 1000 metrics in 92.49551ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Wrote batch of 1000 metrics in 91.801329ms
telegraf    | 2022-03-25T13:59:41Z D! [outputs.file] Buffer fullness: 0 / 100000 metrics
telegraf    | 2022-03-25T13:59:42Z D! [outputs.file] Buffer fullness: 0 / 100000 metrics
telegraf    | 2022-03-25T13:59:52Z D! [outputs.file] Buffer fullness: 0 / 100000 metrics
telegraf    | 2022-03-25T14:00:02Z D! [outputs.file] Buffer fullness: 0 / 100000 metrics
telegraf    | 2022-03-25T14:00:12Z D! [outputs.file] Buffer fullness: 0 / 100000 metrics
Gracefully stopping... (press Ctrl+C again to force)
Stopping telegraf ... done

### System info

Telegraf 1.21.4 or 1.22, Docker on Debian 10, native Docker on Debian 10 on WSL, Docker Desktop on Win 10 and others

### Docker

version: '3.4'

services:
      telegraf:
            container_name: telegraf
            image: telegraf:1.22
            volumes:
                  - "./telegraf.conf:/etc/telegraf/telegraf.conf"
                  - "./out:/opt/telegraf"
                  - "./data:/data"

### Steps to reproduce

(More details in https://github.com/meowcat/20220325-telegraf-unpivot-reprex)
* Unzip "in.zip" to `data/in/", it should then contain 334 CSV files
* Run `docker-compose -f up`
  * This starts Telegraf with `telegraf.conf` as config, where `directory_monitoring` input is rotated to long form with the `unpivot` processor and then written to `file` output
* This processes ~20 files (also dropping many metrics, but this is less relevant) and then completely stops. 
* Killing and restarting the docker will process another ~10-20 files and stop again; this can be repeated to process more files. So any specific input file is not the problem.
* Note that 
  * other inputs would continue to work in parallel with no problems
  * this happens with `file` and `influxdb` output plugins, as well as both in parallel.

### Expected behavior

Telegraf should process all input files in `data/in` and move them to `data/out`. If anything goes wrong (e.g. dropped metrics) it should provide some indication of the error and gracefully continue.

### Actual behavior

Telegraf processes ~10 files from `data/in` to `data/out` and then stops processing files with no error message or other indication of a problem. Putting new files into the input dir will also not trigger processing.

After restarting the Docker, Telegraf will process another ~10 files, and so on. 

### Additional info

https://github.com/meowcat/20220325-telegraf-unpivot-reprex 
Data: https://drive.switch.ch/index.php/s/OqWzQ4rVEEtEc0u

The error only happens when using the `unpivot` processor after `directory_monitor`, not with `directory_monitor` alone (see github for the alternative config.)

I have not checked `tail` or `file`; I would suspect the large number of metrics generated by unpivoting causes an overflow somewhere.

I have tried different combinations of buffer sizes, file queue length, batch sizes, intervals etc to no avail.

The provided log is from WSL; less metrics are dropped on native debian.
