### ISSUE TITLE
Telegraf sends inputs.system to influxdb although respective input is disabled

### ISSUE THREAD

**Issue by christofkac** [influxdata/telegraf#10938]
### Relevant telegraf.conf

```toml
[[outputs.influxdb]]
  urls = ["http://192.168.178.233:8086"]
#  database = "telegrafProxmox"  # this database works as only the Proxmox instance is writing into it
  database = "telegraf"  # here I get a conflict as multiple instances of Telegraf are writing into this database

....
#[[inputs.system]]
  ## Uncomment to remove deprecated metrics.
#  fielddrop = ["uptime*"]
#  name_suffix = "_proxmox"
```

### Logs from Telegraf

```text
Apr 04 21:00:21 proxmox telegraf[2726935]: 2022-04-04T19:00:21Z E! [outputs.influxdb] E! [outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "uptime" on measurement "system" is type float, already exists as type integer dropped=6
```

### System info

Telegraf 1.21.3 on Proxmox 7.1-6

### Steps to reproduce

I don't really know why the error happens therefore I can't tell, what shall be done to reproduce

### Expected behavior

No inputs.system data sent to influxdb as disabled

### Actual behavior

There seems to be a conflict regarding the value "uptime" (although as I don't understand it as Telegraf should not report the same value in different instances with different units)
The mentioned issue is found in the Proxmox logs which I don't understand.
As you see, I tried to add a prefix or filter out uptime but still the error is present.

### Additional info

Only when I switch to a new database, the error is gone as there only the Proxmox Telegraf instance is reporting into the specific database and therefore the conflict is gone.
Also telegraf -test shows, that no inputs.system is transmitted. So why do I get the influxdb error?

Any help appreciated!
