### ISSUE TITLE
Prefix pod labels and annotations scraped by prometheus input plugin

### ISSUE THREAD

**Issue by imranismail** [influxdata/telegraf#10945]
## Feature Request

Namespace kubernetes labels and annotations tags scraped by prometheus plugin so that it is easier to exclude it using `tagexclude`.

### Proposal:

Prefix annotation and label tags so that it is easier to process the tags by it's prefix

```diff
[[inputs.prometheus]]
  metric_version = 2
  monitor_kubernetes_pods = true
  pod_scrape_scope = "node"
+ pod_label_template = 'pod.label/{{ . }}'
+ pod_annotation_template = 'pod.annotation/{{ . }}'
+ tagexclude = ["pod.annotation/*"]
```

### Current behavior:

```
<label>=<value>
<annotation>=<value>
```

### Desired behavior:

```
pod.label/<label>=<value>
pod.annotation/<annotation>=<value>
```

### Use case

```toml
[[inputs.prometheus]]
  metric_version = 2
  monitor_kubernetes_pods = true
  pod_scrape_scope = "node"
  tagexclude = ["pod.annotation/*"]
```
