### ISSUE TITLE
why iops_in_progress metric value from diskio plugin doesn't match with iostat  and most of the times iops_in_progress  is 0 even though there is disk io activity?

### ISSUE THREAD

**Issue by ganga1980** [influxdata/telegraf#10942]
### Relevant telegraf.conf

```toml
[[inputs.diskio]] 
  ## By default, telegraf will gather stats for all devices including
  ## disk partitions.
  ## Setting devices will restrict the stats to the specified devices.
  devices = ["sd[a-z][0-9]"]
  ## Uncomment the following line if you need disk serial numbers.
  # skip_serial_number = false
  #
  ## On systems which support it, device metadata can be added in the form of
  ## tags.
  ## Currently only Linux is supported via udev properties. You can view
  ## available properties for a device by running:
  ## 'udevadm info -q property -n /dev/sda'
  ## Note: Most, but not all, udev properties can be accessed this way. Properties
  ## that are currently inaccessible include DEVTYPE, DEVNAME, and DEVPATH.
  # device_tags = ["ID_FS_TYPE", "ID_FS_USAGE"]
  #
  ## Using the same metadata source as device_tags, you can also customize the
  ## name of the device via templates.
  ## The 'name_templates' parameter is a list of templates to try and apply to
  ## the device. The template may contain variables in the form of '$PROPERTY' or
  ## '${PROPERTY}'. The first template which does not contain any variables not
  ## present for the device is used as the device name tag.
  ## The typical use case is for LVM volumes, to get the VG/LV name instead of
  ## the near-meaningless DM-0 name.
  # name_templates = ["$ID_FS_LABEL","$DM_VG_NAME/$DM_LV_NAME"]
  fieldpass = ["reads", "read_bytes", "read_time", "writes", "write_bytes", "write_time", "io_time", "iops_in_progress"]
  taginclude = ["name"]
```

### Logs from Telegraf

```text
# diskio plugin 
root@omsagent-q4wj5:~/diskio-test# /opt/telegraf --config telegraf.conf  -test
2022-04-06T06:03:27Z I! Starting Telegraf 1.20.3
> diskio,name=sdb1 io_time=844,iops_in_progress=0,read_bytes=4434944,read_time=27,reads=129,write_bytes=306614272,write_time=2092,writes=630 1649225008000000000
> diskio,name=sda1 io_time=1945340,iops_in_progress=0,read_bytes=11035541504,read_time=238886,reads=160153,write_bytes=45347107840,write_time=2425815,writes=4425529 1649225008000000000

# iostat 

root@omsagent-q4wj5:~/diskio-test# bash test.sh 
iostat,device=sdb read_queued_sec=0.00,write_queued_sec=0.00,read_completed_sec=0.00,write_completed_sec=0.00,read_kbytes_sec=0.00,write_kbytes_sec=0.00,avg_sector_size=0.00,avg_queue_len=0.00,await_ms=0.00,read_await_ms=0.00,write_await_ms=0.00,svctime_ms=0.00,util_pct=0.00   0.00   0.00
iostat,device=sda read_queued_sec=0.00,write_queued_sec=1.20,read_completed_sec=0.00,write_completed_sec=2.40,read_kbytes_sec=0.00,write_kbytes_sec=0.00,avg_sector_size=0.00,avg_queue_len=0.00,await_ms=0.00,read_await_ms=0.00,write_await_ms=0.00,svctime_ms=0.00,util_pct=2.00   2.00   0.24

root@omsagent-q4wj5:~/diskio-test# iostat -x
Linux 5.4.0-1072-azure (omsagent-q4wj5)         04/06/22        _x86_64_        (2 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           3.50    0.01    2.66    0.05    0.00   93.79

Device            r/s     w/s     rkB/s     wkB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
sdb              0.00    0.00      0.02      0.49     0.00     0.03   0.00  96.49    0.21    3.32   0.00    34.05   475.28   0.92   0.00
sda              0.27    7.50     17.85     73.16     0.05     2.69  15.45  26.36    1.53    0.56   0.00    66.34     9.75   0.45   0.35
```

### System info

1.20.3

### Steps to reproduce

1. Run telegraf diskio plugin  `/opt/telegraf --config telegraf.conf  -test`
2. Run "iostat -x" command  or  below sample script which generates influx format 

#!/bin/bash

while read -r device read_queued_sec write_queued_sec read_completed_sec write_completed_sec read_kbytes_sec write_kbytes_sec avg_sector_size avg_queue_len await_ms read_await_ms write_await_ms svctime_ms util_pct; do
    [ ! -z "$device" ] && echo "iostat,device=$device read_queued_sec=$read_queued_sec,write_queued_sec=$write_queued_sec,read_completed_sec=$read_completed_sec,write_completed_sec=$write_completed_sec,read_kbytes_sec=$read_kbytes_sec,write_kbytes_sec=$write_kbytes_sec,avg_sector_size=$avg_sector_size,avg_queue_len=$avg_queue_len,await_ms=$await_ms,read_await_ms=$read_await_ms,write_await_ms=$write_await_ms,svctime_ms=$svctime_ms,util_pct=$util_pct"
done < <(iostat -dxyk 5 1 |  tail -n +4)
exit 0
...

3. Compare the results and observe majority of the time "iops_in_progress"

### Expected behavior

From iostat man page - https://linux.die.net/man/1/iostat, disk metrics are fetched from /proc/diskstats

From  Telegraf diskio plugin  page -https://github.com/influxdata/telegraf/tree/master/plugins/inputs/diskio#metrics, disk metrics are fetched from /proc/diskstats

Expected behavior is, iops_in_progress  should match with iostat read_completed_sec + write_completed_sec value.

### Actual behavior

iops_in_progress  value majority of the 0 and doesnt correlate with actual diskio numbers with oputput standard tool like iostat 

### Additional info

If the metric value of iops_in_progress  doesnt match with disk iops, then how this metric will be useful?
