### ISSUE TITLE
Ability to set the measurement name when using the Prometheus input plugin with metric_version=2

### ISSUE THREAD

**Issue by afausti** [influxdata/telegraf#10943]
## Feature Request

We would like to have the option to set the measurement name when collecting metrics with the Prometheus input plugin.

This only applies when `metrics_version=2`.

### Proposal:

When collecting metrics from multiple Prometheus sources we are using the tag/tagpass mechanism to send them to a specific bucket, but we miss the option to set the measurement name.

Ideally, each input source below should go to a different measurement:
```
inputs:
  - prometheus:
        urls:
          - http://argocd-application-controller-metrics.argocd:8082/metrics
          - http://argocd-notifications-controller-metrics.argocd:9001/metrics
          - http://argocd-redis-metrics.argocd:9121/metrics
          - http://argocd-repo-server-metrics.argocd:8084/metrics
          - http://argocd-server-metrics.argocd:8083/metrics
        tags:
          app: "argocd"
        metric_version: 2
```
and
```
outputs:
    - influxdb_v2:
        urls:
          - "https://monitoring.lsst.codes/"
        bucket: "argocd"
        token: "$INFLUX_TOKEN"
        organization: "square"
        tagpass:
          app: ["argocd"]
```
 
### Current behavior:

Currently, the above will write all metrics to the `prometheus` measurement. That seems to be hardcoded in the current implementation of the Prometheus input plugin.

See:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/prometheus.go#L24
and
https://github.com/influxdata/telegraf/blob/master/plugins/parsers/prometheus/parser.go#L84  

wich results in field and tag name collision.

### Desired behavior:

The default measurement name should still be `prometheus` for backward compatibility with previous versions of the plugin, but it should be possible to set a different measurement name for each input source. 

### Use case: 

It is not super important because we can accomplish the same with the override processor plugin, as suggested by the Telegraf team on Slack, but it would be nice to have.
