### ISSUE TITLE
snmp gloriously broken in 1.22 again.

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/telegraf#10955]
### Relevant telegraf.conf

```toml
# This config was made after the grand gosnmp borkage and has worked from March 22nd~
# regressions like this are annoying and make one never want to update ever.
# 
# It might have to be changed, IF SO, some clueful error messages would help.
#
[[inputs.snmp]]
   agents = [ "10.0.0.1" ]
   interval = "60s" timeout = "10s" retries = 2 version = 2 community = "public" max_repetitions = 10
   name_override = "snmp.rtx830" # name = "snmp.rtx830"
   tagexclude=["agent_host"]
# can't find ifTable without this!
   path = ["/usr/local/share/snmp/mibs"]

   [[inputs.snmp.field]] is_tag = true oid = "sysName.0"
```

### Logs from Telegraf

```text
/usr/local/bin/telegraf --config=/usr/local/etc/telegraf.conf --config-directory=/usr/local/etc/telegraf.conf.TEST --test --debug --input-filter snmp


2022-04-10T21:55:50+09:00 E! [telegraf] Error running agent: could not initialize input inputs.snmp: initializing field : translating: sysName.0: Unknown Object Identifier (Sub-id not found: (top) -> sysName): exit status 2
```

### System info

Telegraf-1.22.0 freebsd 13

### Steps to reproduce

have working snmp on previous version (where MIB filenames need to match.)

upgrade

borked.

### Expected behavior

It to work.

### Actual behavior

competely uninformative crash.
There are zero clues in that error message as to what is going wrong.

### Additional info

Nightly;
 37236416 Apr 10 16:42 telegraf-nightly_freebsd_amd64.tar.gz  = NG (1.23)
Freebsd pkg:
telegraf-1.22.0_1~6ff3f32db5.pkg = NG
telegraf-1.21.4~19d92c9d00.pkg = OK
