### ISSUE TITLE
inputs.modbus.request.tags give error cannot unmarshal TOML array table into map

### ISSUE THREAD

**Issue by romainlaisne** [influxdata/telegraf#10965]
### Relevant telegraf.conf

```toml
[[inputs.modbus]]

  name = "powermeter"

  slave_id = 1

  timeout = "1s"

  controller = "tcp://x.x.x.x:502"

  #interval = "1s"

  configuration_type = "request"

  [[inputs.modbus.request]]
    slave_id = 8
    byte_order = "ABCD"
    register = "holding"
    fields = [
      { address=19841, measurement= "Total positive active energy (kwh)", name="energy phase 1", type="UINT32", scale=1.0 },
      { address=21889, measurement= "Total positive active energy (kwh)", name="energy phase 2", type="UINT32", scale=1.0 },
      { address=23937, measurement= "Total positive active energy (kwh)", name="energy phase 3", type="UINT32", scale=1.0 },

      { address=18476, measurement= "Total active power (W)", name="power phase 1", type="INT32", scale=1.0},
      { address=20524, measurement= "Total active power (W)", name="power phase 2", type="INT32", scale=1.0 },
      { address=22572, measurement= "Total active power (W)", name="power phase 3", type="INT32", scale=1.0 }
    ]
    [[inputs.modbus.request.tags]]
       location = "floor 1"
```

### Logs from Telegraf

```text
[telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/input/input-main-busbars.conf: error parsing modbus, line 30: (modbus.requestDefinition.Tags) cannot unmarshal TOML array table into map[string]string (need slice)
```

### System info

Telegraf 1.22.1, modbus plugin

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

I expect Telegraf to send the tags in the output (for influxdb)

### Actual behavior

Error message below:

[telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/input/input-main-busbars.conf: error parsing modbus, line 30: (modbus.requestDefinition.Tags) cannot unmarshal TOML array table into map[string]string (need slice)

### Additional info

I use the Telegraf modbus plugin with the "Per request definition" (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/modbus).

It seems that the modbus plugin has trouble parsing the "tags" section of the config as specify in the doc.

**Comment by romainlaisne** [comment]
Related? https://github.com/influxdata/telegraf/issues/3868

**Comment by powersj** [comment]
Looks like tags were added with https://github.com/influxdata/telegraf/commit/99ddb467e9de14d48b62ba2bff8b2f0f429ab06b @srebhan is the tag format incorrect? Copy and pasting the example config provides the same error:

```

```

**Comment by romainlaisne** [comment]
Do we perhaps miss a make() initialization?

Example in telegraf/config/config_test.go:
`inputConfig.Tags = make(map[string]string)`

It is also mentioned in the golang book, section "Map":
https://www.golang-book.com/books/intro/6

**Comment by romainlaisne** [comment]
The config works if I write the tag section with single square-bracket :

`[[inputs.modbus.request]]
    slave_id = 8
    byte_order = "ABCD"
    register = "holding"
    fields = [
      { address=19841, measurement= "Total positive active energy (kwh)", name="energy phase 1", type="UINT32", scale=1.0 },
      { address=21889, measurement= "Total positive active energy (kwh)", name="energy phase 2", type="UINT32", scale=1.0 },
      { address=23937, measurement= "Total positive active energy (kwh)", name="energy phase 3", type="UINT32", scale=1.0 },

      { address=18476, measurement= "Total active power (W)", name="power phase 1", type="INT32", scale=1.0},
      { address=20524, measurement= "Total active power (W)", name="power phase 2", type="INT32", scale=1.0 },
      { address=22572, measurement= "Total active power (W)", name="power phase 3", type="INT32", scale=1.0 }
    ]
    [inputs.modbus.request.tags]
       location = "floo 1"`
       
Is that then the correct way, or is it an error in the code?

**Comment by srebhan** [comment]
You are absolutely right, the documentation is wrong and needs an update. The correct way is to set
```toml
    [inputs.modbus.request.tags]
       location = "floor 1"
```
with single brackets.
