### ISSUE TITLE
<element> tag is getting added on repeated counter while decoding protobuf to XML

### ISSUE THREAD

**Issue by ravi7248** [influxdata/telegraf#11018]
### Relevant telegraf.conf

```toml
[agent]
  interval = "1s"
  debug = true
  quiet = false


[[inputs.mqtt_consumer]]
  servers = ["mqtt+ssl:aws-activemq:8883"]
  qos = 0
 topics = ["#"]
  connection_timeout = "30s"
  client_id = "telegraf12"

  ## Username and password to connect MQTT server.
  username = "username"
  password = "password"

  data_format = "xpath_protobuf"
  xpath_protobuf_type = "provided"
  xpath_protobuf_file = "message.proto"
  xpath_protobuf_import_paths = ["/etc/telegraf/protofiles/"]

  xpath_print_document = true
  name_override = "final_test3"

  [[inputs.mqtt_consumer.xpath]]
     timestamp = "//firstBinStartTime"
     timestamp_format = "unix"
     #field_selection = "descendant::*[not(*)]"
     field_selection = "//element/..[not(local-name()='element')][normalize-space(.)]|descendant::*[not(*)]"
	 
[[processors.converter]]
  order = 1
  [processors.converter.fields]
    tag = ["tag1","tag2","tag3","tag4"]
    string = ["*"]

[[processors.starlark]]
  order = 2
  source = '''
renames = {
    '': 'element',
}
def apply(metric):
  for k,v in metric.fields.items():
    if type(v) == "float":
      if v > 2147483647.0:
        metric.fields[k] = 0.0
    if type(v) == "int":
      if v > 2147483647:
        metric.fields[k] = 0
  return metric
'''
	 

[[outputs.file]]
#  files = ["/etc/telegraf/influx_output.out"]
   files = ["stdout","/etc/telegraf/influx_format_output.out"]
 data_format = "influx"
```

### Logs from Telegraf

```text
in logs no is there is no error and data is coming as telegraf is decoding
```

### System info

Docker container telegraf 1.22.1

### Steps to reproduce

1. create 1 proto file and import 2nd proto files
2. put some fields as repeated and some as non-repeated
3. Now try to read the data from broker and decode using the proto files
...

### Expected behavior

Now data should come in XML format without any extra external tags.

### Actual behavior

repeated fields are coming with the extra <element> </element> tags

### Additional info

**message.proto file**

```
syntax = "proto3";
package com.cloud.lte.sci;
option java_outer_classname = "MessageProtocol";



import "CumulativeReport.proto";


message Message {

        string  version                         = 1;
        string  SystemId             = 2;
        uint64  StartTime       = 3;
        string  Mac                           = 4;
        string  Serial                        = 5;
        string  Venue                         = 6;
                                                
        package.CumulativeReport    CumulativeReport     = 102;
}
```

**cumu_report.proto**
```

syntax = "proto3";
option java_package = "package_name";


message NetworkView {

    repeated uint32     field1		            = 1;
    repeated uint32     field2		            = 2;
    repeated uint32     field3		        = 3;
	uint64     field4		        = 4;
    repeated uint32     field5		        = 5;
    repeated uint32     field6		        = 6;
}


message CumuReport {

    repeated NetworkView NetworksViews = 1;
}

```

**output we are getting** 
```

<?xml version=\"1.0\"?>
<Cumu>
    <cumuBins>
        <NetworksViews>
            <field1>
            <element>32</element>
            </field1>
            <field2>
            <element>0</element>
            </field2>
            <field3>
            <element>-8</element>
            </field3>
            <field4>1650272385</field14>
            <field5>
            <element>0</element>
            </field5>
            <field6>
            <element>-8</element>
            </field6>
        </NetworksViews>
    </cumuBins>
</Cumu>
<version>1.0.0</version>
<SystemId>4465</SystemId>
<Serial>22192</Serial>
<Venue>office</Venue>
<Mac>94:bf</Mac>

```
