### ISSUE TITLE
Telegraf v1.22 x panic crash with concurrent map write

### ISSUE THREAD

**Issue by BlackMoon2020** [influxdata/telegraf#11025]
### Relevant telegraf.conf

```toml
[[Inputs.file]]
files = ["/apps_folder/*_plugin.status"]
file_tag = "instance"
data_format = "csv"
....
[[Inputs file]
["/apps_folder/*_module.status"]
file_tag = "instance"
```

### Logs from Telegraf

```text
fatal error: concurrent map writes

goroutine 1772 [running]:
runtime.throw......
```

### System info

Telegraf 1.22 x, linux red hat 8

### Steps to reproduce

1. Start with multiples [[inputs.file]]]
2. Telegraf 1.22.x crash
3.
...

### Expected behavior

To work until end of time

### Actual behavior

Crash

### Additional info

Work perfectly with same config, same server with Telegraf 1.21.4
