### ISSUE TITLE
[[inputs.jolokia2_agent]] returning 403

### ISSUE THREAD

**Issue by purushottambaghel** [influxdata/telegraf#11065]
### Relevant telegraf.conf

```toml
[[inputs.jolokia2_agent]]
  urls = ["http://localhost:7777/jolokia"]

  [[inputs.jolokia2_agent.metric]]
    name  = "java_runtime"
    mbean = "java.lang:type=Runtime"
    paths = ["Uptime"]

  [[inputs.jolokia2_agent.metric]]
    name  = "Cache"
    mbean = "org.apache.cassandra.metrics:name=*,scope=*,type=Cache"
    tag_keys = ["name", "scope"]
    field_prefix = "$1_"
```

### Logs from Telegraf

```text
2022-05-06T08:22:30Z E! [inputs.jolokia2_agent] Error in plugin: Unexpected status in response from target : 403
2022-05-06T08:22:30Z E! [inputs.jolokia2_agent] Error in plugin: Unexpected status in response from target : 403
```

### System info

Telegraf 1.13.4
Jolokia JVM Agent 1.5.0

### Steps to reproduce

1. add the above conf in telegraf.conf
2. run the telegraf
3.
...

### Expected behavior

200 status should return

### Actual behavior

403 status

### Additional info
I can make request to this curl
curl GET http://localhost:7777/jolokia/read/org.apache.cassandra.metrics:*

it returns 200 success status
