### ISSUE TITLE
Suddently cant log data anymore | OPC-UA

### ISSUE THREAD

**Issue by JustPrints** [influxdata/telegraf#11070]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "30s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
   #logtarget = "eventlog"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
   #logfile = "log"

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
   #logfile_rotation_interval = "12h"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
   #logfile_rotation_max_size = "25MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
   #logfile_rotation_max_archives = 10

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
   #log_with_timezone = "local"

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://127.0.0.1:8086"]

  ## Token for authentication.
  token = "***************************Z*E*N*S*O*R*E*D***************************"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "FREQCON"

  ## Destination bucket to write into.
  bucket = "FREQCON"

  ## The value of this tag will be used to determine the bucket.  If this
  ## tag is not set the 'bucket' option is used as the default.
  # bucket_tag = ""

  ## If true, the bucket tag will not be added to the metric.
  # exclude_bucket_tag = false

  ## Timeout for HTTP messages.
  # timeout = "5s"

  ## Additional HTTP headers
  # http_headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP Proxy override, if unset values the standard proxy environment
  ## variables are consulted to determine which proxy, if any, should be used.
  # http_proxy = "http://corporate.proxy:3128"

  ## HTTP User-Agent
  user_agent = "telegraf"

  ## Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
   content_encoding = "gzip"

  ## Enable or disable uint support for writing uints influxdb 2.0.
  # influx_uint_support = false

  ## Optional TLS Config for use on HTTP connections.
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false


[[inputs.opcua]]
  ## Metric name
  name = "opcua"
  #
  ## OPC UA Endpoint URL
  endpoint = "opc.tcp://192.168.38.155:4840"
  # endpoint = "opc.tcp://FANUC-OPC:59611"
  #
  ## Maximum time allowed to establish a connect to the endpoint.
  connect_timeout = "10s"
  #
  ## Maximum time allowed for a request over the estabilished connection.
  request_timeout = "5s"
  #
  ## Security policy, one of "None", "Basic128Rsa15", "Basic256",
  ## "Basic256Sha256", or "auto"
  security_policy = "None"
  #
  ## Security mode, one of "None", "Sign", "SignAndEncrypt", or "auto"
  security_mode = "None"
  #
  ## Path to cert.pem. Required when security mode or policy isn't "None".
  ## If cert path is not supplied, self-signed cert and key will be generated.
  certificate = "/etc/telegraf/cert.pem"
  #
  ## Path to private key.pem. Required when security mode or policy isn't "None".
  ## If key path is not supplied, self-signed cert and key will be generated.
  private_key = "/etc/telegraf/key.pem"
  #
  ## Authentication Method, one of "Certificate", "UserName", or "Anonymous".  To
  ## authenticate using a specific ID, select 'Certificate' or 'UserName'
  auth_method = "UserName"
  #
  ## Username. Required for auth_method = "UserName"
  username = "simotion"
  #
  ## Password. Required for auth_method = "UserName"
  password = "simotion"

   nodes = [
    {name="gs_eirgrid_saved.b0_eirgrid_active_power_control", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_active_power_control"},
    {name="gs_eirgrid_saved.b0_eirgrid_frequency_response", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_frequency_response"},
    {name="gs_eirgrid_saved.b0_eirgrid_frequency_response_curve_1_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_frequency_response_curve_1_selected"},
    {name="gs_eirgrid_saved.b0_eirgrid_frequency_response_curve_2_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_frequency_response_curve_2_selected"},
    {name="gs_eirgrid_saved.b0_eirgrid_response_mode_1_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_response_mode_1_selected"},
    {name="gs_eirgrid_saved.b0_eirgrid_response_mode_2_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_response_mode_2_selected"},
    {name="gs_eirgrid_saved.b0_eirgrid_response_mode_3_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_response_mode_3_selected"},
    {name="gs_eirgrid_saved.b0_eirgrid_response_mode_4_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_response_mode_4_selected"},
    {name="gs_eirgrid_saved.b0_eirgrid_response_mode_5_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0_eirgrid_response_mode_5_selected"},
    {name="gs_eirgrid_saved.b0i_eirgrid_system_services_dynamic_frequency_response_system_mode_status_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0i_eirgrid_system_services_dynamic_frequency_response_system_mode_status_selected"},
    {name="gs_eirgrid_saved.b0i_eirgrid_system_services_static_frequency_response_system_mode_status_selected", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.b0i_eirgrid_system_services_static_frequency_response_system_mode_status_selected"},
    {name="gs_eirgrid_saved.r32_eirgrid_active_power_control_setpoint", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.r32_eirgrid_active_power_control_setpoint"},
    {name="gs_eirgrid_saved.r32_eirgrid_frequency_droop_setting", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid_saved.r32_eirgrid_frequency_droop_setting"},
    {name="gs_rocof.r32_frequency", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_rocof.r32_frequency"},
    {name="gs_supercap.r32_soc_system_1", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_supercap.r32_soc_system_1"},
    {name="gs_supercap.r32_soc_system_2", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_supercap.r32_soc_system_2"},
    {name="gs_supercap.r32_soc_system_3", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_supercap.r32_soc_system_3"},
    {name="gs_supercap.r32_soc_total", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_supercap.r32_soc_total"},
    {name="gs_supercap.r32_power", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_supercap.r32_power"},
    {name="gs_diesel.b0_active_power_setpoint_WFCS_active", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel.b0_active_power_setpoint_WFCS_active"},
    {name="gs_diesel.i16q_number_of_genset_available", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel.i16q_number_of_genset_available"},
    {name="gs_diesel.r32_active_power_setpoint_WFCS", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel.r32_active_power_setpoint_WFCS"},
    {name="gs_diesel.r32_power", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel.r32_power"},
    {name="gs_eirgrid.s32i_eirgrid_active_power_control_setpoint.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32i_eirgrid_active_power_control_setpoint.r32_live"},
    {name="gs_eirgrid.s32q_eirgrid_FFR_availability.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32q_eirgrid_FFR_availability.r32_live"},
    {name="gs_eirgrid.s32q_eirgrid_POR_availability.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32q_eirgrid_POR_availability.r32_live"},
    {name="gs_eirgrid.s32q_eirgrid_SOR_availability.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32q_eirgrid_SOR_availability.r32_live"},
    {name="gs_eirgrid.s32q_eirgrid_TOR1_availability.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32q_eirgrid_TOR1_availability.r32_live"},
    {name="gs_eirgrid.s32q_eirgrid_TOR2_availability.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32q_eirgrid_TOR2_availability.r32_live"},
    {name="gs_eirgrid.s32q_eirgrid_active_power_output.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32q_eirgrid_active_power_output.r32_live"},
    {name="gs_eirgrid.s32q_eirgrid_available_active_power.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_eirgrid.s32q_eirgrid_available_active_power.r32_live"},
    {name="gs_control_cabinet_climate.s32i_control_cabinet_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_control_cabinet_climate.s32i_control_cabinet_temperature.r32_live"},
    {name="gs_diesel_cabinet_climate.s32i_cabinet_temperature_diodes.r32_filt", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel_cabinet_climate.s32i_cabinet_temperature_diodes.r32_filt"},
    {name="gs_diesel_cabinet_climate.s32i_cabinet_temperature_genset_connection.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel_cabinet_climate.s32i_cabinet_temperature_genset_connection.r32_live"},
    {name="gs_diesel_cabinet_climate.s32i_converter_gensets_cabinet_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel_cabinet_climate.s32i_converter_gensets_cabinet_temperature.r32_live"},
    {name="gs_diesel_cabinet_climate.s32i_diesel_transformer_temperature_1.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel_cabinet_climate.s32i_diesel_transformer_temperature_1.r32_live"},
    {name="gs_diesel_cabinet_climate.s32i_diesel_transformer_temperature_2.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel_cabinet_climate.s32i_diesel_transformer_temperature_2.r32_live"},
    {name="gs_diesel_cabinet_climate.s32i_gensets_connection_cabinet_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_diesel_cabinet_climate.s32i_gensets_connection_cabinet_temperature.r32_live"},
    {name="gs_grid_cabinet_climate.s32i_converter_grid_cabinet_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_grid_cabinet_climate.s32i_converter_grid_cabinet_temperature.r32_live"},
    {name="gs_grid_cabinet_climate.s32i_grid_connection_cabinet_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_grid_cabinet_climate.s32i_grid_connection_cabinet_temperature.r32_live"},
    {name="gs_ultracaps_cabinet_climate.s32i_converter_ultra_caps_cabinet_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_ultracaps_cabinet_climate.s32i_converter_ultra_caps_cabinet_temperature.r32_live"},
    {name="gs_ultracaps_cabinet_climate.s32i_ultra_caps_cabinet_room_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_ultracaps_cabinet_climate.s32i_ultra_caps_cabinet_room_temperature.r32_live"},
    {name="gs_ultracaps_cabinet_climate.s32i_ultra_caps_cabinet_temperature_1.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_ultracaps_cabinet_climate.s32i_ultra_caps_cabinet_temperature_1.r32_live"},
    {name="gs_converter_cooling.s32i_converter_cooling_water_system_1_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_converter_cooling.s32i_converter_cooling_water_system_1_temperature.r32_live"},
    {name="gs_converter_cooling.s32i_converter_cooling_water_system_2_temperature.r32_live", namespace="2", identifier_type="s", identifier="unit/dglobaloperationvar.gs_converter_cooling.s32i_converter_cooling_water_system_2_temperature.r32_live"},
    {name="gs_data_diesel.r64_genset_running_hour_1", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.r64_genset_running_hour_1"},
    {name="gs_data_diesel.r64_genset_running_hour_2", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.r64_genset_running_hour_2"},
    {name="gs_data_diesel.r64_genset_running_hour_3", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.r64_genset_running_hour_3"},
    {name="gs_data_diesel.r64_genset_running_hour_4", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.r64_genset_running_hour_4"},
    {name="gs_data_diesel.r64_genset_running_hour_5", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.r64_genset_running_hour_5"},
    {name="gs_data_diesel.u32_genset_number_of_starts_1", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.u32_genset_number_of_starts_1"},
    {name="gs_data_diesel.u32_genset_number_of_starts_2", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.u32_genset_number_of_starts_2"},
    {name="gs_data_diesel.u32_genset_number_of_starts_3", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.u32_genset_number_of_starts_3"},
    {name="gs_data_diesel.u32_genset_number_of_starts_4", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.u32_genset_number_of_starts_4"},
    {name="gs_data_diesel.u32_genset_number_of_starts_5", namespace="2", identifier_type="s", identifier="unit/dglobaldatavar.gs_data_diesel.u32_genset_number_of_starts_5"}
  ]
```

### Logs from Telegraf

```text
2022-05-09T13:14:46Z I! Starting Telegraf 1.21.4
2022-05-09T13:14:56Z I! Loaded inputs: opcua
2022-05-09T13:14:56Z I! Loaded aggregators:
2022-05-09T13:14:56Z I! Loaded processors:
2022-05-09T13:14:56Z I! Loaded outputs: influxdb_v2
2022-05-09T13:14:56Z I! Tags enabled: host=DESKTOP-LOGGER
2022-05-09T13:14:56Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"DESKTOP-LOGGER", Flush Interval:10s
2022-05-09T13:14:56Z D! [agent] Initializing plugins
2022-05-09T13:14:56Z E! [telegraf] Error running agent: could not initialize input inputs.opcua: EOF
```

### System info

Telegraf 1.21.4 | InfluxDB 2.1.1 | Windows 10 Pro

### Steps to reproduce

1. Run this config

### Expected behavior

Running without "EOF" Error

### Actual behavior

The Error "EOF" get printed 

### Additional info

Thanks for helping
