### ISSUE TITLE
Wavefront output plugin adding empty tag

### ISSUE THREAD

**Issue by farukhali** [influxdata/telegraf#11077]
### Relevant telegraf.conf

```toml
[[outputs.wavefront]]
  host = "somehost"
  port = 12878
  prefix = "\u2206telegraf."
  namepass = ["somenamepass*"]
  fielddrop = ["ln*" , "tdigest"]
  source_override = ["api"]
```

### System info

1.21.0

### Steps to reproduce

1. Use wavefront output.
2. add source override tag.
3. Do not provide host tag in metric.
4. Plugin will add empty telegraf.host tag to the metric sent to wavefront proxy.
5. Wavefront will return error for empty tag.
...

### Expected behavior

Wavefront output plugin should not expect host tag in source metric. There should not be any empty tag output from this plugin.

### Actual behavior

If host tag is not provided in metrics, wavefront output plugin add empty telegraf.host tag which cause failure on wavefront proxy end. 

### Additional info

The code here https://github.com/influxdata/telegraf/blob/4a15e0aba85b7ab423562fdc804d2cc5f55ee863/plugins/outputs/wavefront/wavefront.go#L193 assume there will always be host tag. I can share a PR to fix this issue.
