### ISSUE TITLE
SNMP Printer

### ISSUE THREAD

**Issue by gkloss** [influxdata/telegraf#11142]
Hello everyone,

I got following Config:

```toml
[agent]
  interval = "1h"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = "fancyHostname"
  omit_hostname = false
  snmp_translator = "gosmi"

[[outputs.influxdb_v2]]
  # some InfluxDBv2

[[inputs.snmp]]

  agents = [ "someAgent" ]

  timeout = "2s"
  version = 2
  community = "public"
  retries = 1

  [[inputs.snmp.field]]
    oid = ".1.3.6.1.4.1.1347.43.10.1.1.12.1.1"
    name = "all_pages"

  [[inputs.snmp.field]]
    oid = ".1.3.6.1.4.1.11.2.3.9.1.1.7.0"
    name = "hpInfo"

  [[inputs.snmp.field]]
    oid = ".1.3.6.1.2.1.43.5.1.1.17.1"
    name = "SN"

  [[inputs.snmp.field]]
    oid = ".1.3.6.1.2.1.25.3.2.1.3.1"
    name = "hrDeviceDescr"

  [[inputs.snmp.table]]
    name = "prtMarkerColorantEntry"
    index_as_tag = true
    [[inputs.snmp.table.field]]
      name = "prtMarkerColorantValue"
      oid = ".1.3.6.1.2.1.43.12.1.1.4"

  [[inputs.snmp.table]]
    name = "prtMarkerSuppliesEntry"
    index_as_tag = true
    [[inputs.snmp.table.field]]
      name = "prtMarkerSuppliesDescription"
      oid = ".1.3.6.1.2.1.43.11.1.1.6"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "prtMarkerSuppliesColorantIndex"
      oid = ".1.3.6.1.2.1.43.11.1.1.3"
    [[inputs.snmp.table.field]]
      name = "prtMarkerSuppliesMaxCapacity"
      oid = ".1.3.6.1.2.1.43.11.1.1.8"
    [[inputs.snmp.table.field]]
      name = "prtMarkerSuppliesLevel"
      oid = ".1.3.6.1.2.1.43.11.1.1.9"

  [[inputs.snmp.field]]
    oid = ".1.3.6.1.2.1.1.3.0"
    name = "sysUpTime"

  [[inputs.snmp.field]]
    oid = ".1.3.6.1.2.1.1.6.0"
    name = "sysLocation"
    is_tag = true

```

And following Flux query:

```javascript
import "influxdata/influxdb/schema"
from(bucket: "some_bucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "prtMarkerSuppliesEntry")
  |> filter(fn: (r) => r._field == "prtMarkerSuppliesLevel" or r._field == "prtMarkerSuppliesMaxCapacity")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> group(columns: ["prtMarkerColorantValue", "agent_host"])
  |> schema.fieldsAsCols()
  |> map(fn: (r) => ({ r with _value: (r.prtMarkerSuppliesLevel/ r.prtMarkerSuppliesMaxCapacity) * 100.0 }))
  |> mean()
  |> yield(name: "stuff")
```

not sure how to join the Colors to the MarkerSupplies correctly.
Is there a way to strip the index in telegraf or join it in Grafana?

**Comment by gkloss** [comment]
I got the join working but want to include more fields in the Line Protocol.

```toml
 [[inputs.snmp.table]]                             
   name = "prtMarkerSuppliesEntry"                 
   index_as_tag = false                            
   [[inputs.snmp.table.field]]                     
     name = "prtMarkerSuppliesDescription"         
     oid = ".1.3.6.1.2.1.43.11.1.1.6"              
     is_tag = true                                 
                                                   
   [[inputs.snmp.table.field]]                     
     name = "prtMarkerSuppliesColorantIndex"       
     oid = ".1.3.6.1.2.1.43.11.1.1.3"              
     secondary_index_table = true                  
     is_tag = true                                 
                                                   
   [[inputs.snmp.table.field]]                     
     name = "prtMarkerColorantValue"               
     oid = ".1.3.6.1.2.1.43.12.1.1.4.1"            
     secondary_index_use = true                    
     is_tag = true                                 
                                                   
   [[inputs.snmp.table.field]]                     
     oid = ".1.3.6.1.4.1.11.2.3.9.1.1.7.0"         
     name = "hpInfo"                               
     is_tag = true                                 
                                                   
   [[inputs.snmp.table.field]]                     
     oid = ".1.3.6.1.2.1.43.5.1.1.17.1"            
     name = "SN"                                   
     is_tag = true                                 
                                                   
   [[inputs.snmp.table.field]]                     
     oid = ".1.3.6.1.2.1.25.3.2.1.3.1"             
     name = "hrDeviceDescr"                        
     is_tag = true                                 
                                                   
   [[inputs.snmp.table.field]]                     
     oid = ".1.3.6.1.2.1.1.6.0"                    
     name = "sysLocation"                          
     is_tag = true                                 
                                                   
   [[inputs.snmp.table.field]]                     
     name = "prtMarkerSuppliesMaxCapacity"         
     oid = ".1.3.6.1.2.1.43.11.1.1.8"              
                                                   
   [[inputs.snmp.table.field]]                     
     name = "prtMarkerSuppliesLevel"               
     oid = ".1.3.6.1.2.1.43.11.1.1.9"              
                                                   
                                                   
   [[inputs.snmp.table.field]]                     
     oid = ".1.3.6.1.2.1.1.3.0"                    
     name = "sysUpTime"                            

```
