### ISSUE TITLE
OpenBSD package broken: "mmap: cannot allocate memory"

### ISSUE THREAD

**Issue by ichilton** [influxdata/telegraf#11160]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://x.x.x.x:8086"]
  database = "telegraf"
  retention_policy = ""
  timeout = "5s"
```

### Logs from Telegraf

```text
None
```

### System info

telegraf-1.22.1, OpenBSD 7.1

### Steps to reproduce

1. pkg_add telegraf
2. Attempt to run telegraf

### Expected behavior

It should run.

### Actual behavior

```
# telegraf
2022/05/21 22:19:01 mmap: cannot allocate memory
```

### Additional info

Got 4x OpenBSD hosts. Was working fine prior to 1.22.1 release. Since then it's giving the error and failing to start.
