### ISSUE TITLE
inputs.vsphere, reports duplicate points

### ISSUE THREAD

**Issue by yogeshprasad** [influxdata/telegraf#11168]
### Relevant telegraf.conf

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "60s"

# Read metrics from one or many vCenters
[[inputs.vsphere]]
    ## List of vCenter URLs to be monitored. These three lines must be uncommented
  ## and edited for the plugin to work.
  vcenters = [ "https://vcenter.local/sdk" ]
  username = "user@corp.local"
  password = "secret"

  ## VMs
  ## Typical VM metrics (if omitted or empty, all metrics are collected)
  # vm_include = [ "/*/vm/**"] # Inventory path to VMs to collect (by default all are collected)
  # vm_exclude = [] # Inventory paths to exclude
  vm_metric_include = [
    "cpu.demand.average",
    "cpu.idle.summation",
    "cpu.latency.average",
    "cpu.readiness.average",
    "cpu.ready.summation",
    "cpu.run.summation",
    "cpu.usagemhz.average",
    "cpu.used.summation",
    "cpu.wait.summation",
    "mem.active.average",
    "mem.granted.average",
    "mem.latency.average",
    "mem.swapin.average",
    "mem.swapinRate.average",
    "mem.swapout.average",
    "mem.swapoutRate.average",
    "mem.usage.average",
    "mem.vmmemctl.average",
    "net.bytesRx.average",
    "net.bytesTx.average",
    "net.droppedRx.summation",
    "net.droppedTx.summation",
    "net.usage.average",
    "power.power.average",
    "virtualDisk.numberReadAveraged.average",
    "virtualDisk.numberWriteAveraged.average",
    "virtualDisk.read.average",
    "virtualDisk.readOIO.latest",
    "virtualDisk.throughput.usage.average",
    "virtualDisk.totalReadLatency.average",
    "virtualDisk.totalWriteLatency.average",
    "virtualDisk.write.average",
    "virtualDisk.writeOIO.latest",
    "sys.uptime.latest",
  ]
  # vm_metric_exclude = [] ## Nothing is excluded by default
  # vm_instances = true ## true by default

  ## Hosts
  ## Typical host metrics (if omitted or empty, all metrics are collected)
  # host_include = [ "/*/host/**"] # Inventory path to hosts to collect (by default all are collected)
  # host_exclude [] # Inventory paths to exclude
  host_metric_include = [
    "cpu.coreUtilization.average",
    "cpu.costop.summation",
    "cpu.demand.average",
    "cpu.idle.summation",
    "cpu.latency.average",
    "cpu.readiness.average",
    "cpu.ready.summation",
    "cpu.swapwait.summation",
    "cpu.usage.average",
    "cpu.usagemhz.average",
    "cpu.used.summation",
    "cpu.utilization.average",
    "cpu.wait.summation",
    "disk.deviceReadLatency.average",
    "disk.deviceWriteLatency.average",
    "disk.kernelReadLatency.average",
    "disk.kernelWriteLatency.average",
    "disk.numberReadAveraged.average",
    "disk.numberWriteAveraged.average",
    "disk.read.average",
    "disk.totalReadLatency.average",
    "disk.totalWriteLatency.average",
    "disk.write.average",
    "mem.active.average",
    "mem.latency.average",
    "mem.state.latest",
    "mem.swapin.average",
    "mem.swapinRate.average",
    "mem.swapout.average",
    "mem.swapoutRate.average",
    "mem.totalCapacity.average",
    "mem.usage.average",
    "mem.vmmemctl.average",
    "net.bytesRx.average",
    "net.bytesTx.average",
    "net.droppedRx.summation",
    "net.droppedTx.summation",
    "net.errorsRx.summation",
    "net.errorsTx.summation",
    "net.usage.average",
    "power.power.average",
    "storageAdapter.numberReadAveraged.average",
    "storageAdapter.numberWriteAveraged.average",
    "storageAdapter.read.average",
    "storageAdapter.write.average",
    "sys.uptime.latest",
  ]
    ## Collect IP addresses? Valid values are "ipv4" and "ipv6"
  # ip_addresses = ["ipv6", "ipv4" ]

  # host_metric_exclude = [] ## Nothing excluded by default
  # host_instances = true ## true by default


  ## Clusters
  # cluster_include = [ "/*/host/**"] # Inventory path to clusters to collect (by default all are collected)
  # cluster_exclude = [] # Inventory paths to exclude
  # cluster_metric_include = [] ## if omitted or empty, all metrics are collected
  # cluster_metric_exclude = [] ## Nothing excluded by default
  # cluster_instances = false ## false by default

  ## Resource Pools
  # datastore_include = [ "/*/host/**"] # Inventory path to datastores to collect (by default all are collected)
  # datastore_exclude = [] # Inventory paths to exclude
  # datastore_metric_include = [] ## if omitted or empty, all metrics are collected
  # datastore_metric_exclude = [] ## Nothing excluded by default
  # datastore_instances = false ## false by default

    ## Datastores
  # datastore_include = [ "/*/datastore/**"] # Inventory path to datastores to collect (by default all are collected)
  # datastore_exclude = [] # Inventory paths to exclude
  # datastore_metric_include = [] ## if omitted or empty, all metrics are collected
  # datastore_metric_exclude = [] ## Nothing excluded by default
  # datastore_instances = false ## false by default

  ## Datacenters
  # datacenter_include = [ "/*/host/**"] # Inventory path to clusters to collect (by default all are collected)
  # datacenter_exclude = [] # Inventory paths to exclude
  datacenter_metric_include = [] ## if omitted or empty, all metrics are collected
  datacenter_metric_exclude = [ "*" ] ## Datacenters are not collected by default.
  # datacenter_instances = false ## false by default

  ## Plugin Settings
  ## separator character to use for measurement and field names (default: "_")
  # separator = "_"

  ## number of objects to retrieve per query for realtime resources (vms and hosts)
  ## set to 64 for vCenter 5.5 and 6.0 (default: 256)
  # max_query_objects = 256

  ## number of metrics to retrieve per query for non-realtime resources (clusters and datastores)
  ## set to 64 for vCenter 5.5 and 6.0 (default: 256)
  # max_query_metrics = 256

  ## number of go routines to use for collection and discovery of objects and metrics
  # collect_concurrency = 1
  # discover_concurrency = 1

  ## the interval before (re)discovering objects subject to metrics collection (default: 300s)
  # object_discovery_interval = "300s"

  ## timeout applies to any of the api request made to vcenter
  # timeout = "60s"

  ## When set to true, all samples are sent as integers. This makes the output
  ## data types backwards compatible with Telegraf 1.9 or lower. Normally all
  ## samples from vCenter, with the exception of percentages, are integer
  ## values, but under some conditions, some averaging takes place internally in
  ## the plugin. Setting this flag to "false" will send values as floats to
  ## preserve the full precision when averaging takes place.
  # use_int_samples = true

  ## The number of vSphere 5 minute metric collection cycles to look back for non-realtime metrics. In 
  ## some versions (6.7, 7.0 and possible more), certain metrics, such as cluster metrics, may be reported
  ## with a significant delay (>30min). If this happens, try increasing this number. Please note that increasing
  ## it too much may cause performance issues.
  # metric_lookback = 3

  ## Custom attributes from vCenter can be very useful for queries in order to slice the
  ## metrics along different dimension and for forming ad-hoc relationships. They are disabled
  ## by default, since they can add a considerable amount of tags to the resulting metrics. To
  ## enable, simply set custom_attribute_exclude to [] (empty set) and use custom_attribute_include
  ## to select the attributes you want to include.
  ## By default, since they can add a considerable amount of tags to the resulting metrics. To
  ## enable, simply set custom_attribute_exclude to [] (empty set) and use custom_attribute_include
  ## to select the attributes you want to include.
  # custom_attribute_include = []
  # custom_attribute_exclude = ["*"]

  ## Optional SSL Config
  # ssl_ca = "/path/to/cafile"
  # ssl_cert = "/path/to/certfile"
  # ssl_key = "/path/to/keyfile"
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false
```

### Logs from Telegraf

```text
No relevant logs
```

### System info

Telegraf v1.22.4

### Steps to reproduce

1. Set interval = "60s" in agent 
2. Enable the Vsphere input plugin with default settings
3. Run the telegraf for 5 min

### Expected behavior

There should not be any duplicate points 

### Actual behavior

Nearly 10 % of points are being duplicate 

### Additional info

This is the function which creates duplicate points as we are adjusting the time here.
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/endpoint.go#L1104

**Comment by powersj** [comment]
Hi,

Would you be willing to share some of the example duplicate points from a telegraf log? It would be helpful to use the `[[outputs.file]]` output to see what metrics you are getting and if they do show up multiple times.

Thanks!

**Comment by yogeshprasad** [comment]
Hi @powersj 
Here is the file [metrics.out.zip](https://github.com/influxdata/telegraf/files/8777607/metrics.out.zip), it has data for more than 10 min and nearly 25% of data is duplicated.
Some of the metrics:

`"vsphere.vm.mem.usage.average" source="skajagar-win2008" 1653477360000 6.99 "esxhostname"="gty-a003.test.com" "dcname"="WF_BGLR_INT_DC" "clustername"="WF_BGLR_INT_Cluster01" "_wavefront_source"="proxy::abcd-efgh-241-239.test.com" "vcenter"="int-vc.test.com" "guest"="winLonghorn64" "uuid"="420b5c3c-6f1b-d231-314b-23b88901cd98" "vmname"="skajagar-win2008" "moid"="vm-129" "guesthostname"="WIN-PR69FI29KLE"`
--->`"vsphere.vm.mem.usage.average" source="skajagar-win2008" 1653477360000 6.99 "esxhostname"="gty-a003.test.com" "dcname"="WF_BGLR_INT_DC" "clustername"="WF_BGLR_INT_Cluster01" "_wavefront_source"="proxy::abcd-efgh-241-239.test.com" "vcenter"="int-vc.test.com" "guest"="winLonghorn64" "vmname"="skajagar-win2008" "uuid"="420b5c3c-6f1b-d231-314b-23b88901cd98" "moid"="vm-129" "guesthostname"="WIN-PR69FI29KLE"`


`"vsphere.host.cpu.used.summation" source="gty-a003.test.com" 1653477360000 43.0 "esxhostname"="gty-a003.test.com" "dcname"="WF_BGLR_INT_DC" "clustername"="WF_BGLR_INT_Cluster01" "_wavefront_source"="proxy::abcd-efgh-241-239.test.com" "vcenter"="int-vc.test.com" "cpu"="81" "moid"="host-17"`
--->`"vsphere.host.cpu.used.summation" source="gty-a003.test.com" 1653477360000 48.0 "esxhostname"="gty-a003.test.com" "dcname"="WF_BGLR_INT_DC" "clustername"="WF_BGLR_INT_Cluster01" "_wavefront_source"="proxy::abcd-efgh-241-239.test.com" "vcenter"="int-vc.test.com" "cpu"="81" "moid"="host-17"`

`"vsphere.host.cpu.coreUtilization.average" source="gty-a003.test.com" 1653477360000 1.04 "esxhostname"="gty-a003.test.com" "dcname"="WF_BGLR_INT_DC" "clustername"="WF_BGLR_INT_Cluster01" "_wavefront_source"="proxy::abcd-efgh-241-239.test.com" "vcenter"="int-vc.test.com" "cpu"="31" "moid"="host-17"`
--->`"vsphere.host.cpu.coreUtilization.average" source="gty-a003.test.com" 1653477360000 0.98 "esxhostname"="gty-a003.test.com" "dcname"="WF_BGLR_INT_DC" "clustername"="WF_BGLR_INT_Cluster01" "_wavefront_source"="proxy::abcd-efgh-241-239.test.com" "vcenter"="int-vc.test.com" "cpu"="31" "moid"="host-17"`

**Comment by powersj** [comment]
What is your output you are pushing this to? And what is the output in your comment above from?

When looking at the metrics.out file I first looked at the metrics at the timestamp you first referenced, `1653477360000` and looked for "winLonghorn64". There are some very similar lines, but they are different.

For example:

```diff
- vsphere_vm_power,clustername=WF_BGLR_INT_Cluster01,dcname=WF_BGLR_INT_DC,esxhostname=gty-a003.test.com,guest=winLonghorn64,guesthostname=WIN-PR69FI29KLE,host=telegraf_rhel_nossl,moid=vm-129,source=skajagar-win2008,uuid=420b5c3c-6f1b-d231-314b-23b88901cd98,vcenter=int-vc.test.com,vmname=skajagar-win2008 power_average=244i 1653477360000000000
+ vsphere_vm_power,clustername=WF_BGLR_INT_Cluster01,dcname=WF_BGLR_INT_DC,esxhostname=gty-a003.test.com,guest=winLonghorn64,guesthostname=WIN-PR69FI29KLE,host=telegraf_rhel_nossl,moid=vm-129,source=skajagar-win2008,uuid=420b5c3c-6f1b-d231-314b-23b88901cd98,vcenter=int-vc.test.com,vmname=skajagar-win2008 power_average=247i 1653477360000000000
```

In the above, the tags are all the same, but the field value reported for power_average is different between the two.

A similar example looking at the memory output:

```diff
- vsphere_vm_mem,clustername=WF_BGLR_INT_Cluster01,dcname=WF_BGLR_INT_DC,esxhostname=gty-a003.test.com,guest=winLonghorn64,guesthostname=WIN-FCCHP2L47JJ,host=telegraf_rhel_nossl,moid=vm-131,source=skajagar-win2016-Activated,uuid=420bc4e3-d966-403e-f6f7-7bb6223b6fae,vcenter=int-vc.test.com,vmname=skajagar-win2016-Activated swapinRate_average=0i,active_average=419429i,swapout_average=0i,swapin_average=0i,swapoutRate_average=0i,latency_average=0,vmmemctl_average=0i,usage_average=9.99,granted_average=4194304i 1653477360000000000
+ vsphere_vm_mem,clustername=WF_BGLR_INT_Cluster01,dcname=WF_BGLR_INT_DC,esxhostname=gty-a003.test.com,guest=winLonghorn64,guesthostname=WIN-FCCHP2L47JJ,host=telegraf_rhel_nossl,moid=vm-131,source=skajagar-win2016-Activated,uuid=420bc4e3-d966-403e-f6f7-7bb6223b6fae,vcenter=int-vc.test.com,vmname=skajagar-win2016-Activated active_average=398458i,granted_average=4194304i,swapout_average=0i,swapin_average=0i,swapoutRate_average=0i,swapinRate_average=0i,latency_average=0,vmmemctl_average=0i,usage_average=9.49 1653477360000000000
```

Here the `active_average` is different as well.

So I would not say that these are duplicates. What I do wonder about is why the metric is showing up twice with the same timestamp.

Can you please provide the rest of your configuration?

**Comment by yogeshprasad** [comment]
@powersj Thanks for the analysis.
 as you mentioned for the below example everything is same except the value and that's the problem exactly. How it is possible for a resource to have different values at the same time, and because of this we are not able to conclude which value is the correct one.
 
```diff
- vsphere_vm_power,clustername=WF_BGLR_INT_Cluster01,dcname=WF_BGLR_INT_DC,esxhostname=gty-a003.test.com,guest=winLonghorn64,guesthostname=WIN-PR69FI29KLE,host=telegraf_rhel_nossl,moid=vm-129,source=skajagar-win2008,uuid=420b5c3c-6f1b-d231-314b-23b88901cd98,vcenter=int-vc.test.com,vmname=skajagar-win2008 power_average=244i 1653477360000000000
+ vsphere_vm_power,clustername=WF_BGLR_INT_Cluster01,dcname=WF_BGLR_INT_DC,esxhostname=gty-a003.test.com,guest=winLonghorn64,guesthostname=WIN-PR69FI29KLE,host=telegraf_rhel_nossl,moid=vm-129,source=skajagar-win2008,uuid=420b5c3c-6f1b-d231-314b-23b88901cd98,vcenter=int-vc.test.com,vmname=skajagar-win2008 power_average=247i 1653477360000000000
```

**Comment by powersj** [comment]
As I don't think the plugin would suddenly start generating duplicate metrics, it looks like you have two plugins running at the same time.

Some follow up questions:

- How are you running Telegraf?
- How many configuration files do you have?
- Can you provide your entire configuration file(s) with secrets removed?
- Do you have multiple vsphere input plugins configured? Can you provide the start of the logs which shows what plugins are loaded?

If you add the following to your config, does the output change?

```toml
[[inputs.vsphere]]
  name_override = "vsphere_local"
  vcenters = [ "https://vcenter.local/sdk" ]
```

I would expect to see a single metric called "vsphere_local".
