### ISSUE TITLE
Telegraf logging stopped in telegraf:1.22.1

### ISSUE THREAD

**Issue by Dhyanesh97** [influxdata/telegraf#11180]
### Relevant telegraf.conf

Working in telegraf:1.20.0

agent-telegraf.conf

```toml
[agent]
metric_batch_size = 10000
metric_buffer_limit = 100000
debug = false
omit_hostname = true
logtarget = "file"
logfile = "/etc/telegraf/log/telegraf.log"
logfile_rotation_max_size = "50MB"
logfile_rotation_max_archives = 3
```

### Logs from Telegraf

logs are not generated using above configuration in file.
docker logs -f telegraf => shows telegraf logs but doesn't have any logs related to agent configuration file.

### System info

Telegraf 1.22.1, Ubuntu 20.04, Docker 19.03.9

### Docker
```yaml
version: "3"
services:
  telegraf:
    image: telegraf:1.22.1
    container_name: telegraf
    restart: always
    depends_on:
        - influxdb
    networks:
      - analytics
    volumes:
      - /mnt/telegraf/:/var/lib/telegraf
      - ./etc/telegraf/:/etc/telegraf/
    env_file:
      - secrets.env
    environment:
        INFLUXDB_URL: http://influxdb:8086
    command:
        --config-directory /etc/telegraf/telegraf.d
        --config /etc/telegraf/telegraf.conf
    links:
      - influxdb
    logging:
      options:
        max-size: "10m"
        max-file: "3"
networks:
  analytics:
```

### Steps to reproduce

1. Configure telegraf agent file for logging.
2. start telegraf container.
3. no log file will be generated with the configuration mentioned in agent-telegraf.config file above.

### Expected behavior

Normally log file should be created as per the mentioned configuration. 50mb each file and max 3 file should be present in the folder.

### Actual behavior

It is not creating log files in the folder with telegraf 1.22.1 but log files are getting created with 1.20.0 telegraf version
