### ISSUE TITLE
Support KeyDB metrics as part of "redis" input plugin

### ISSUE THREAD

**Issue by erkexzcx** [influxdata/telegraf#11219]
## Feature Request

KeyDB is designed to be faster fork of Redis, keeping 1:1 compatibility with Redis. Everything is very similar to Redis, including metrics. Even the same command `INFO` works in the same manner, however, there are few mismatching data types for certain fields which causes failure of a whole plugin when used with KeyDB.

### Proposal:

Implement fixes so `redis` input plugin works with KeyDB as well.

### Current behavior:

Input plugin `redis` works with KeyDB already, however, some fields from the measurement `redis` are marked as invalid type (e.g. expects float, but got string) which causes this whole measurement to be empty.

### Desired behavior:

Input plugin `redis` works just as it works with Reddis server.

### Use case: 

KeyDB is a popular Redis alternative, keeping 1:1 compatibility with Redis. It is a drop in replacement for Redis, however, telegraf plugin needs to be updated.

### Bonus:

This doesn't work:
```toml
# KeyDB is drop in replacement for Redis. It is advertised as 100% compatible with Redis.
[[inputs.redis]]
  servers = ["tcp://localhost:6379"]
```

But this one does, however, some fields are dropped:
```toml
# KeyDB is drop in replacement for Redis. It is advertised as 100% compatible with Redis.
[[inputs.redis]]
  servers = ["tcp://localhost:6379"]
  # Below needs to be dropped to suppress errors regarding mismatching data types. After all it's Redis plugin, not KeyDB...
  # By fixing these errors, metrics in measurement "redis" started to appear.
  fielddrop = [
    "used_memory_dataset_perc",
    "allocator_frag_bytes",
    "used_memory_peak_perc"]
```

Expected error messages in Telegraf logs:
```
[outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "used_memory_peak_perc" on measurement "redis" is type float, already exists as type string dropped=1
[outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "used_memory_peak_perc" on measurement "redis" is type float, already exists as type string dropped=1
[outputs.influxdb] Failed to write metric (will be dropped: 400 Bad Request): partial write: field type conflict: input field "used_memory_peak_perc" on measurement "redis" is type float, already exists as type string dropped=1
```
