### ISSUE TITLE
Prometheus output, export_timestamp only works with v2

### ISSUE THREAD

**Issue by hackery** [influxdata/telegraf#11230]
### Relevant telegraf.conf

```toml
[[outputs.prometheus_client]]
  # metric_version = 1
  ...
  export_timestamp = true
```

### Logs from Telegraf

```text
n/a
```

### System info

Telegraf 1.21.2

### Steps to reproduce

Configure `export_timestamp` in a Prometheus output with the default v1 metrics formatting.

### Expected behavior

Timestamps are included in output

### Actual behavior

Timestamps are not included in output

### Additional info

Should either be implemented for v1 output, or docs updated.
