### ISSUE TITLE
Error when testing telegraf config on Windows: driver "sqlite" not supported

### ISSUE THREAD

**Issue by kuzyn** [influxdata/telegraf#11259]
### Relevant telegraf.conf

```toml
[[inputs.sql]]
  interval = "5m"
  driver = "sqlite"
  dsn = "C:/PATH/TO/DB"

  [[inputs.sql.query]]
    query="SELECT * FROM tableName ORDER BY day DESC LIMIT 1"
```

### Logs from Telegraf

```text
[telegraf] Error running agent: could not initialize input inputs.sql: driver "sqlite" not supported use one of [clickhouse cockroach maria mssql mysql pgx postgres snowflake sqlserver tidb]
```

### System info

Telegraf 1.22.4; Windows 10 Pro

### Steps to reproduce

1. Configure `conf` to point to sqlite database
2. Run telegraf with the `--test` and `--debug` switches 
3. It gives the error above
...

### Expected behavior

Works and show a test example of the sql metrics

### Actual behavior

Gives the error aboves

### Additional info

This config works on Linux (with updated dsn path). The database can be loaded via the `sqlite3.exe` util, so I know it's not corrupt... Is there a limitation with telegraf, sqlite and Windows 10?
