### ISSUE TITLE
Automatic refresh a Bearer ACCESS TOKEN in inputs.http

### ISSUE THREAD

**Issue by JornDL** [influxdata/telegraf#11279]
## Feature Request

Make it possible to refresh a **Bearer ACCESS TOKEN** in inputs.http

Opening a feature request kicks off a discussion.

### Proposal:

To make this possible in inputs.http:

### Current behavior:

[[inputs.http]]
	urls = ["https://api.netatmo.com/api/gethomecoachsdata?device_id=MAC-ADDRESS"]
	headers = {"accept" = "application/json"}
	headers = {"Authorization" = "**Bearer ACCESS TOKEN**"}

This works fine as long as the **Bearer ACCESS TOKEN** has not expired

### Desired behavior:

Automatic refresh of the **Bearer ACCESS TOKEN** so it does not expire

### Use case: 

All cases where the **Bearer ACCESS TOKEN** expires.

Example from Netatmo:

![image](https://user-images.githubusercontent.com/83627515/173018068-4edae697-60af-4cd9-be40-58b77f4f417f.png)

**Comment by Hipska** [comment]
Hi @JornDL the bearer token is read from file at every gather interval. So if you make sure that file is updated on time, telegraf will continue to work.

**Comment by JornDL** [comment]
Hi @Hipska 

Can you help me on how to do that, please.

**Comment by Hipska** [comment]
Updating a file?

It seems like it isn't even needed when I look at your initial description. It appears that You want to use an Oauth2 service:
```toml
  ## OAuth2 Client Credentials. The options 'client_id', 'client_secret', and 'token_url' are required to use OAuth2.
  client_id = "clientid"
  client_secret = "secret"
  token_url = "https://api.netatmo.com/oauth2/token"
  # scopes = ["urn:opc:idm:__myscopes__"]
```
