### ISSUE TITLE
Prometheus / OpenMetrics timestamp parsing incorrect

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#11283]
### Relevant telegraf.conf

```toml
/etc/telegraf/telegraf.d/mymetrics.conf.deactivated 

[[inputs.file]]
  files = [ "/etc/telegraf/telegraf.d/mymetrics.dat"  ]
  interval = "5s"
  precision = "1s"
  data_format = "prometheus"
```

### Logs from Telegraf

```text
Nothing regarding this issue.
```

### System info

Telegraf 1.22.3 on RHEL8

### Steps to reproduce

Create file /etc/telegraf/telegraf.d/mymetrics.dat with following content:

```
media_count01 1.0 1654964761
media_count02 1.0 1654976701
```

Run Telegraf test config
`telegraf -config /etc/telegraf/telegraf.d/mymetrics.conf.deactivated -test`

### Expected behavior

I expect the test output to be something like:
_media_count01=1 1654964761000000
media_count02=1 1654976701000000_

### Actual behavior

The output timestamp is up to 999seconds unprecise:
_media_count01=1 1654965000000000
media_count02=1 1654977000000000_

### Additional info

Issue also occurs with `inputs.tail` , `inputs.prometheus`, `inputs.exec` etc..
Working with no timestamp specification at mymetrics.dat or using  `inputs.prometheus` and `ignore_timestamp = false` telegraf ouptut timestamp is like expected.
There does not exist any test case/prometheus protocol line with a timestamp (https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/parser_test.go) to identify such issues (parse a correctly given timestamp). So it should be included there.

**Comment by reimda** [comment]
Hi @1tft, in your test data (mymetrics.dat) the timestamps are in seconds. The prometheus exposition format and telegraf's parser expect timestamps in milliseconds. (see https://github.com/influxdata/telegraf/blob/master/plugins/parsers/prometheus/README.md and the spec it links to https://prometheus.io/docs/instrumenting/exposition_formats/#comments-help-text-and-type-information)

When I use your file input config and input data, along with an output config,

```toml
[global_tags]

[agent]
  interval = "2s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "2s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = true

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[inputs.file]]
  files = [ "metric.prom.11283" ]
  precision = "1s"
  data_format = "prometheus"
```
this is telegraf's output:

```
$ ../telegraf --config telegraf.conf.11283 
2022-06-14T21:17:16Z I! Starting Telegraf 1.24.0-72e91bae
2022-06-14T21:17:16Z I! Loaded inputs: file
2022-06-14T21:17:16Z I! Loaded aggregators: 
2022-06-14T21:17:16Z I! Loaded processors: 
2022-06-14T21:17:16Z I! Loaded outputs: file
2022-06-14T21:17:16Z I! Tags enabled: 
2022-06-14T21:17:16Z I! [agent] Config: Interval:2s, Quiet:false, Hostname:"", Flush Interval:2s
prometheus media_count01=1 1654965000000000
prometheus media_count02=1 1654977000000000
```

InfluxDB line protocol timestamps are in nanoseconds, so 1654965000000000 is 1654965 in unix epoch seconds. Thats a date in 1970:

```
$ date -u -d @1654965
Tue 20 Jan 1970 03:42:45 AM UTC
```

The last three significant figures in the input data (what telegraf read as milliseconds) are lost because your config has `precision = "1s"`.

If I change your input data to have millisecond timestamps by adding 000 to the end of each timestamp, 

```
media_count01 1.0 1654964761000
media_count02 1.0 1654976701000
```

then run telegraf with the same configuration, this is the output:

```
$ ../telegraf --config telegraf.conf.11283 
2022-06-14T21:15:58Z I! Starting Telegraf 1.24.0-72e91bae
2022-06-14T21:15:58Z I! Loaded inputs: file
2022-06-14T21:15:58Z I! Loaded aggregators: 
2022-06-14T21:15:58Z I! Loaded processors: 
2022-06-14T21:15:58Z I! Loaded outputs: file
2022-06-14T21:15:58Z I! Tags enabled: 
2022-06-14T21:15:58Z I! [agent] Config: Interval:2s, Quiet:false, Hostname:"", Flush Interval:2s
prometheus media_count01=1 1654964761000000000
prometheus media_count02=1 1654976701000000000
```

1654964761000000000ns is 1654964761s, and a timestamp from around the time you opened this issue:

```
$ date -u -d @1654964761
Sat 11 Jun 2022 04:26:01 PM UTC
```

In this case the `precision = "1s"` doesn't have any effect because the timestamps are already rounded to the second.
