### ISSUE TITLE
inputs.youtube is missing in Telegraf

### ISSUE THREAD

**Issue by anand-autointelli** [influxdata/telegraf#11327]
### Relevant telegraf.conf

```toml
[[inputs.youtube]]
  ## List of channels to monitor.
  channels = [
    "UCBR8-60-B28hp2BmDPdntcQ",
    "UCnrgOD6G0y0_rcubQuICpTQ"
  ]

  ## YouTube API key.
  # api_key = ""
```

### Logs from Telegraf

```text
2022-06-19T12:16:44Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/yoututbe.conf: error parsing youtube, Undefined but requested input: youtube
```

### System info

Telegraf 1.22.1 on Oracle Linux 8

### Steps to reproduce

1. Create a configure file 
2. put inputs.youtube configuration
3. Restart TElegraf
...

### Expected behavior

Telegraf should start automatically and collect metrics

### Actual behavior

2022-06-19T12:16:44Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/yoututbe.conf: error parsing youtube, Undefined but requested input: youtube
