### ISSUE TITLE
Power state should be a field not a tag in nvidia-smi input plugin

### ISSUE THREAD

**Issue by JamesGibo** [influxdata/telegraf#11387]
## Feature Request

In the [nvidia-smi](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/nvidia_smi) input plugin the `pstate` shoudl be a field rather than a tag.

By having the `pstate` as a tag it makes simple operations to display metrics like the utilisation display incorrectly as each `pstate` means a separate table is created. 

### Proposal:

Change `pstate` tag to a field.

### Current behavior:
![image](https://user-images.githubusercontent.com/22477854/175513801-f8e9d958-f682-4208-97e5-c31d4884e667.png)

### Desired behavior:

![image](https://user-images.githubusercontent.com/22477854/175513761-0f234633-6a0d-41a8-8874-6c4689a0ff3c.png)

### Use case: 

if the `pstate` is changed to a field it will make simple operations to display metrics like the utilisation much easier.

**Comment by MyaLongmire** [comment]
Hi, thank you for filing this feature request. We are hesitate to change tags to fields or visa versa as it will break other users. We do have the [Converter Processor](https://github.com/influxdata/telegraf/blob/master/plugins/processors/converter/README.md) that can change them for you.

**Comment by jeffrey4l** [comment]
Solved this by regexp and convert processors

```toml
[[inputs.nvidia_smi]]

[[processors.regex]]
  order = 10
  alias = 'nvidia_drop_pstate'
  namepass = ['nvidia_smi']

  [[processors.regex.tags]]
  key = 'pstate'
  pattern = 'P(\d)'
  replacement = '${1}'

[[processors.converter]]
  order = 20
  alias = 'nvidia_drop_pstate'
  namepass = ['nvidia_smi']

  [processors.converter.tags]
  integer = ['pstate']
````
