### ISSUE TITLE
Prometheus monitor_kubernetes_pods overwrites the namespace tag for a metric with the namespace of the pod being scraped

### ISSUE THREAD

**Issue by gracewehner** [influxdata/telegraf#11383]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  interval = "1m"
  monitor_kubernetes_pods = true
  pod_scrape_scope = "node"
  kubernetes_label_selector = ""
  kubernetes_field_selector = ""
  fieldpass = ["kube_pod_info", "kube_pod_container_info"]
  fielddrop = []
  metric_version = 2
  url_tag = "scrapeUrl"
  # kube_config = "/path/to/kubernetes.config"
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  response_timeout = "15s"
  tls_ca = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  insecure_skip_verify = true
```

### Logs from Telegraf

```text
N/A
```

### System info

Telegraf 1.22.2, Ubuntu 18.04, Kubernetes v1.21.7

### Steps to reproduce

1. Set `monitor_kubernetes_pods=true` and use pod annotations to scrape a Prometheus endpoint from a pod that has metrics with `namespace` as a dimension name.
2. Deploying `kube-state-metrics` is an easy way to test by adding the annotations to the pod:
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
Note: For `kube-state-metrics`, to get around this, the `kubernetes_services` setting can be used. However, this is used as an easy example and this will not always work. For example Kubevirt (https://github.com/kubevirt/kubevirt) does not have an associated service and all pods in the daemonset need to be scraped

### Expected behavior

The dimension value for `namespace` shouldn't be overwritten by the namespace of the pod that the metrics are being scraped from. For example, if a `kube-state-metrics` pod in the `kube-system` namespace is being scraped, the metric for the pod named `example-pod` in `example-namespace` should be: `kube_pod_info{pod="example-pod", namespace="example-namespace"}`

### Actual behavior

The dimension value for `namespace` is the namespace of the pod that the metrics are being scraped from instead of the actual value of the metric for the namespace dimension. For example, if a `kube-state-metrics` pod in the `kube-system` namespace is being scraped, the metric for the pod named `example-pod` in `example-namespace` is: `kube_pod_info{pod="example-pod", namespace="kube-system"}`
