### ISSUE TITLE
[[inputs.sql]] Looping telegraf if one instance is down

### ISSUE THREAD

**Issue by N3v3R3nD** [influxdata/telegraf#11457]
### Relevant telegraf.conf

```toml
[[inputs.sql]]
  driver = "mysql"
  dsn = "xxxx:xxxx@tcp(10.0.0.100:3306)/master"
[[inputs.sql.query]]
  query="SELECT SELECT usrGrp AS usr_grp,FROM current_users WHERE endTime = 0"
[[inputs.sql]]
  driver = "mysql"
  dsn = "xxxx:xxxx@tcp(10.0.0.101:3306)/master"
[[inputs.sql.query]]
  query="SELECT SELECT usrGrp AS usr_grp,FROM current_users WHERE endTime = 0"
```

### Logs from Telegraf

```text
! [inputs.sql] Testing connectivity...
! [inputs.sql] Preparing statement "SELECT usrGrp AS usr_grp,FROM current_users WHERE endTime = 0"...
! [inputs.sql] Connecting to "test:test@tcp(10.0.0.100:3306)/master"...
! [inputs.sql] Testing connectivity...
! [telegraf] Error running agent: starting input inputs.sql: connecting to database failed: dial tcp 10.0.101:3306: i/o timeout
! Starting Telegraf 1.23
```

### System info

Telegraf 1.23.0  - Debian 

### Steps to reproduce

1. Create 2 [inputs.sql] where one instance is down

### Expected behavior

Expected telegraf to start 

### Actual behavior

It just restarts and loops when it can not connect to the instance that is down and telegraf never starts.

If instance goes down while telegraf is running it breaks collecting and it starts to loop again.
