### ISSUE TITLE
Serial number from physical host using telegraf

### ISSUE THREAD

**Issue by George-Lutch** [influxdata/telegraf#11470]
I am looking for a way to use the telegraf agent to pull the serial number of the host physical server. So far I see where you can do this for the systems disks but have not seen where you can do it for the host system.  Anyone know of a plugin that would do this?

**Comment by srebhan** [comment]
On Linux you can do the following
```toml
[[inputs.file]]
  files = ["/sys/class/dmi/id/product_serial"]
  data_format = "value"
  data_type = "string"
  name_override = "serial_number"
```
if your telegraf user has read access to `/sys/class/dmi/id/product_serial`. This will result in 
```text
> serial_number,host=Hugin value="To be filled by O.E.M." 1657213246000000000
```
