### ISSUE TITLE
[inputs.intel_powerstat] error while trying to read MSR (probably msr module was not loaded)

### ISSUE THREAD

**Issue by hammoumi94** [influxdata/telegraf#11535]
### Relevant telegraf.conf

```toml
# Telegraf Configuration
#
# THIS FILE IS MANAGED BY PUPPET
#
[global_tags]
  controller_id = "${KEBA_HW_SERIAL_NUMBER}"

[agent]
  hostname = "cp505-a"
  omit_hostname = false
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  logfile = ""
  debug = false
  quiet = false

#
# OUTPUTS:
#
[outputs]


#
# INPUTS:
#
[inputs.disk]
ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[inputs.intel_powerstat]
cpu_metrics = ["cpu_frequency", "cpu_busy_frequency", "cpu_temperature", "cpu_c1_state_residency", "cpu_c6_state_residency", "cpu_busy_cycles"]
[inputs.kernel]
[inputs.mem]
[inputs.net]
interfaces = ["eth0", "br0"]
[inputs.system]
[inputs.temp]
[[inputs.cpu]]
collect_cpu_time = false
percpu = true
report_active = false
totalcpu = true
[[inputs.influxdb_v2_listener]]
service_address = ":8086"
[[inputs.procstat]]
exe = "civetweb"
[[inputs.procstat]]
exe = "Ctrl"
[[inputs.socket_listener]]
service_address = "udp://:8095"
```

### Logs from Telegraf

```text
ERR : [inputs.intel_powerstat] error while trying to read MSR (probably msr module was not loaded)
```

### System info

telegraf 1.23.2, debian 10

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

pass

### Actual behavior

[inputs.intel_powerstat] error while trying to read MSR (probably msr module was not loaded)
