### ISSUE TITLE
CUSTOM time layouts should support custom milliseconds separator- Grok input data format 

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#11544]
### Proposal:
CUSTOM time layouts should support custom milliseconds separator.

### Current behavior:
CUSTOM time layouts only support `.` or `,` as milliseconds separator. (yes we know, its a Golang thing and its written here: https://docs.influxdata.com/telegraf/v1.22/data_formats/input/grok/ - _To match a comma decimal point you can use a period in the pattern string. See https://golang.org/pkg/time/#Parse for more details._).
So currently Telegraf cant completely parse timestamps like _15.07.2022 13:20:30:777_

### Desired behavior:
Support timestamp parsing of dates with milliseconds separated by individual separator like ":" or ";" or "-" etc..

### Use case: 
Parse loglines like _15.07.2022 13:20:30:777 my cool log message_

We reported issue also here: https://support.influxdata.com/s/case/5001S00001TuBWvQAN/ but got only a workaround for parsing our logline: Ignore milliseconds.

**Comment by powersj** [comment]
Hi @1tft,

As you have pointed out, the Go upstream will not enable support for additional separators. We certainly do not want to fork and maintain the time parsing library for this seemingly rare use case.

One possible option is for us to add an option to the Grok parser, where you can specify a millisecond separator character. Then as timestamps are read, we can replace the last instance of that character with a period `.` to get the timestamp to parse correctly.

Is adding this option something that would help your use case?

Thanks!

**Comment by 1tft** [comment]
Hello @powersj , adding a grok parser option which replaces original millisecond separator sounds for a good solution.
Currently there is no way how to tell Telegraf to parse a timestamp like "15.07.2022 13:20:30:777". Everything which make it possible to parse such a timestamp would be an improvement.

**Comment by powersj** [comment]
Are there other plugins or parsers you are trying to use that type of timestamp with other than Grok parser?

**Comment by 1tft** [comment]
We are currently using it with input plugin "tail" and "file" (and maybe "http") and 90% with with grok parser.
There are also use cases where we use `input.tail` with json_v2 parser. But its not so important for us also to find a solution for  json_v2.

**Comment by srebhan** [comment]
@1tft a suitable solution would be to replace the "fraction" separator with a dot or comma and then parse the timestamp like

```toml
[[inputs.file]]
  files = ['./test_configs/grok_issue_11544.txt']
  name_override = "custom_grok"
  data_format = "grok"
  grok_patterns = ['%{CUSTOM_TIMESTAMP:ts} %{GREEDYDATA:text}']
  grok_custom_patterns = '''
    CUSTOM_TIMESTAMP (?:%{MONTHDAY}.%{MONTHNUM}.%{YEAR} %{HOUR}:%{MINUTE}:%{SECOND}:%{NUMBER})
  '''

[[processors.regex]]
  namepass = ["custom_grok"]
  [[processors.regex.fields]]
    key = "ts"
    pattern = '^(.*):(.*)$'
    replacement = "${1}.${2}"

[[processors.converter]]
  namepass = ["custom_grok"]
  [processors.converter.fields]
    timestamp = ["ts"]
    timestamp_format = "02.01.2006 15:04:05.999999999"
```

For your example

```text
15.07.2022 13:20:30:777 my cool log message
```

this will produce

```text
> custom_grok,host=Hugin text="my cool log message" 1657891230777000000
```

Does that work for you?
