### ISSUE TITLE
inputs.exec influx data example doesn't work

### ISSUE THREAD

**Issue by georgettica** [influxdata/telegraf#11579]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  ## Commands array
  commands = [
    'echo myMeasurement,tag1=value1,tag2=value2 fieldKey="fieldValue" 1556813561098000000'
  ]
  data_format = "influx"
```

### Logs from Telegraf

```text
Aug 01 18:06:10 XXX telegraf[2881629]: 2022-08-01T18:06:10Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 1:49: "myMeasurement,tag1=value1,tag2=value2 fieldKey=fieldValue 1556813561098000000"
```

### System info

Telegraf 1.23.3-1 , Ubuntu 20.04.4, Docker 20.10.8

### Steps to reproduce

run on machine the config given, see the error

### Expected behavior

no error

### Actual behavior

the input was not parsed

### Additional info

the line was taken from https://docs.influxdata.com/influxdb/v2.3/reference/syntax/line-protocol/
