### ISSUE TITLE
ip_addresses = ["ipv4" ] Failed in Windows

### ISSUE THREAD

**Issue by robbyq92** [influxdata/telegraf#11589]
### Relevant telegraf.conf

```toml
###############################################################################
#                                  INPUTS                                     #
###############################################################################
[[inputs.internal]]
  collect_memstats = true
[[inputs.mem]]
 name_override = "win_mem"
[[inputs.win_services]]
  ## Names of the services to monitor. Leave empty to monitor all the available services on the host
  service_names = []
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time"
    ]
    Measurement = "win_cpu"
    # Set to true to include _Total instance when querying for all (*).
    IncludeTotal=true

  [[inputs.win_perf_counters.object]]
    # Disk times and queues
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
      "% User Time",
      "% Free Space",
      "Current Disk Queue Length",
      "Free Megabytes",
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Avg. Disk Queue Length",
      "Split IO/Sec"
    ]
    Measurement = "win_disk"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [
      "Context Switches/sec",
      "System Calls/sec",
      "Processor Queue Length",
      "Threads",
      "System Up Time",
      "Processes"
    ]
    Instances = ["------"]
    Measurement = "win_system"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false
    ip_addresses = ["ipv4" ]
```

### Logs from Telegraf

```text
PS C:\telegraf> .\telegraf.exe --test --debug --config .\telegraf.conf
2022-08-02T08:33:04Z W! DeprecationWarning: Option "precision" of plugin "outputs.influxdb" deprecated since version 1.0
.0 and will be removed in 2.0.0: option is ignored
2022-08-02T08:33:04Z E! [telegraf] Error running agent: Error loading config file .\telegraf.conf: plugin inputs.win_per
f_counters: line 93: configuration specified the fields ["ip_addresses"], but they weren't used
PS C:\telegraf>


Last version. 1.23.3
```

### System info

Telegraf 1.23.3, Windows Server 2016

### Steps to reproduce

1. i put the config (read telegraf) for choose the config of ip_addresses.
2. add in the telegraf.conf
3. i do the debug telegraf.exe --test --debug --config file.conf
...

### Expected behavior

i have error said the werent used the ip_addresses filds in wib_perf_counters...

### Actual behavior

-
