### ISSUE TITLE
[inputs.x509_cert] Using wrong server name for verification

### ISSUE THREAD

**Issue by srebhan** [influxdata/telegraf#11623]
### Relevant telegraf.conf

```toml
# Reads metrics from a SSL certificate
  [[inputs.x509_cert]]
    ## List certificate sources
    sources = ["smtp://server-A.org:587", "smtp://server-B.org:25"]
```

### Logs from Telegraf

```text
No specific logs, only wrong output.
```

### System info

Telegraf 1.23.2

### Steps to reproduce

Run Telegraf with the above config against two servers with non-overlapping DNS entries.

### Expected behavior

Certificates are reported to be valid in the metrics (`verification=valid`) as they are valid.

### Actual behavior

Instead of reporting the certificates valid, all certificates of the second `source` will be reported invalid similar to

```text
> x509_cert,common_name=server-B.com,host=telegraf-7fdffb564-97r6k,issuer_common_name=Some\ Certificate\ Authority\ -\ G2,public_key_algorithm=RSA,san=server-B.org, www.server-B.org, sub.server-B.org,serial_number=e077f23dd76b209f,signature_algorithm=SHA256-RSA,source=smtp://server-B.org:25,verification=invalid age=14708051i,enddate=1679151227i,expiry=19592748i,startdate=1644850427i,verification_code=1i,verification_error="x509: certificate is valid for server-B.org, www.server-B.org, sub.server-B.org, not server-A.org" 1659558478000000000
```

It is important to note that the error message indicates that the certificate chain of `server-B.org` is checked against `server-A.org` or more generally speaking against the first of the `sources` enumerated.
