### ISSUE TITLE
Rename Processor Plugin replace problem

### ISSUE THREAD

**Issue by ladvocat** [influxdata/telegraf#11628]
### Relevant telegraf.conf

```toml
[[processors.rename]]
  [[processors.rename.replace]]
    tag = "/interfaces/interface/@name"
    dest = "intname"
  [[processors.rename.replace]]
    tag = "/interfaces/interface/subinterfaces/subinterface/@index"
    dest = "subint"
```

### Logs from Telegraf

```text
n/a
```

### System info

docker telegraf version = 1.22.4

### Steps to reproduce

1. The processor.rename.replace is used to replace a received tag value from [[inputs.jti_openconfig_telemetry]]
2. Collect data
3. Check the tags from the measurement

### Expected behavior

Replace the original tag by the "dest" value.

### Actual behavior

Both tags exist in parallel.

With the config of this case, "/interfaces/interface/@name" and "intname", are stored.

**Comment by powersj** [comment]
Hi,

If I use the following as input:

```s
metric,/interfaces/interface/subinterfaces/subinterface/@index="foo",/interfaces/interface/@name="bar" value=1
```

and this config:

```toml
[agent]
  omit_hostname = true

[[inputs.file]]
  files = ["metrics"]
  data_format = "influx"

[[processors.rename]]
  [[processors.rename.replace]]
    tag = "/interfaces/interface/@name"
    dest = "intname"
  [[processors.rename.replace]]
    tag = "/interfaces/interface/subinterfaces/subinterface/@index"
    dest = "subint"

[[outputs.file]]
```

I get the following, which I think is what you are after.

```
metric,intname="bar",subint="foo" value=1 1659717159000000000
```

Can you provide your full config? And with actual metrics + expected metric examples?

Thanks
