### ISSUE TITLE
E! [inputs.snmp] Error in plugin: agent ###Your Network Device Ip Address###: gathering table interface: performing bulk walk for field ifDescr: error reading from socket: read udp 127.0.0.1:41716->127.0.0.1:161: recvfrom: connection refused

### ISSUE THREAD

**Issue by harvey945** [influxdata/telegraf#11632]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "30s"
  flush_jitter = "0s"
  precision = ""
  hostname = "xxxx"
  omit_hostname = false


[[outputs.opentsdb]]
  host = "http://172.xx.xx.xx"
  port = 19000
  http_batch_size = 50
  http_path = "/opentsdb/put"
  debug = false
  separator = "_"

[[inputs.snmp]]
  agents = ["10.xx.xx.xx"]
  timeout = "5s"
  version = 2 
  community = "public"
  agent_host_tag = "ident"
  retries = 1

[[inputs.snmp.field]]
 oid = "1.3.6.1.2.1.1.3.0"
 name = "Uptime"

[[inputs.snmp.field]]
 oid = "1.3.6.1.2.1.1.5.0"
 name = "sysName"
 is_tag = true

[[inputs.snmp]]
  agents = ["###Your Network Device Ip Address###"]
  community = "###your community###"

[[inputs.snmp.field]]
  oid = "RFC1213-MIB::sysUpTime.0"
  name = "uptime"

[[inputs.snmp.field]]
  oid = "RFC1213-MIB::sysName.0"
  name = "source"
  is_tag = true

[[inputs.snmp.field]]
  oid = "1.3.6.1.4.1.2011.5.25.31.1.1.1.1.5.67108873"
  name = "CpuUsage"

[[inputs.snmp.field]]
  oid = "1.3.6.1.4.1.2011.5.25.31.1.1.1.1.7.67108873"
  name = "MemUsage"

[[inputs.snmp.field]]
  oid = "1.3.6.1.4.1.2011.5.25.31.1.1.1.1.5.16842753"
  name = "CpuUsage"

[[inputs.snmp.field]]
  oid = "1.3.6.1.4.1.2011.5.25.31.1.1.1.1.7.16842753"
  name = "MemUsage"

[[inputs.snmp.table]]
  oid = "IF-MIB::ifTable"
  name = "interface"
  inherit_tags = ["source"]

[[inputs.snmp.table.field]]
  oid = "IF-MIB::ifDescr"
  name = "ifDescr"
  is_tag = true
```

### Logs from Telegraf

```text
as the title.

E! [inputs.snmp] Error in plugin: agent ###Your Network Device Ip Address###: gathering table interface: performing bulk walk for field ifDescr: error reading from socket: read udp 127.0.0.1:41716->127.0.0.1:161: recvfrom: connection refused
```

### System info

CentOS Linux release 7.7.1908 (Core)

### Steps to reproduce

1.Configured as above, continue to execute for 3 days
2.
3.
...

### Expected behavior

noting.

### Actual behavior

noting.
