### ISSUE TITLE
mqtt parsing: Error in plugin: strconv.ParseFloat: parsing "\"tF\":146.2}}": invalid syntax

### ISSUE THREAD

**Issue by peters77** [influxdata/telegraf#11659]
### Relevant telegraf.conf

```toml
# # Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
   ## MQTT broker URLs to be used. The format should be scheme://host:port,
   ## schema can be tcp, ssl, or ws.
   servers = ["tcp://127.0.0.1:1883"]

   ## Topics that will be subscribed to.
    topics = ["pv1/status/switch:0/#"]  

    data_format = "value"
    data_type = "float"

#   ## Username and password to connect MQTT server.
    username = "test"
    password = "test"
```

### Logs from Telegraf

```text
2022-08-11T07:16:46Z I! [inputs.mqtt_consumer] Connected [tcp://127.0.0.1:1883]
2022-08-11T07:17:01Z E! [inputs.mqtt_consumer] Error in plugin: strconv.ParseFloat: parsing "\"tF\":146.2}}": invalid syntax
```

### System info

Telegraf 1.23.3. Debian 11

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

System should parse all into database. Sorry, I'm new to that but cant fin a solution to parse mey content nto the influxdb. 
Im; interested in "apower":375.0, "voltage":226.0, "current":1.659, "aenergy":{"total":134753.219} at the end but even setting 

topics = ["pv1/status/switch:0/apower"] 

doesn't write anyting into the database?

### Actual behavior

Last entry could not been parsed. Readout is the MQTT stream form a Shelly Plus 1PM sent to a mosquitto broker running local.

### Additional info

Here is thee line to parse which fails:

pv1/status/switch:0 {"id":0, "source":"init", "output":true, "apower":375.0, "voltage":226.0, "current":1.659, "aenergy":{"total":134753.219,"by_minute":[8076.639,8042.825,7995.476],"minute_ts":1660202939},"temperature":{"tC":63.9, "tF":147.0}}
