### ISSUE TITLE
diskio - specify disk not by dev but by id

### ISSUE THREAD

**Issue by ser** [influxdata/telegraf#11685]
### Use Case

`/dev/sda`-like devices are not persistent in linux, so after disk swapping in a bay gathered statistics can relate to completely another device.

It would be much smarter to use `/dev/disk/by-id` links, which persist, for example:

`/dev/disk/by-id/ata-ST3000VX010-2E4166_Z6A0D9N1`

### Expected behavior

```
[[inputs.diskio]]
  devices = ["/dev/disk/by-id/nvme-WDS100T1X0E-00AFY0_21086Q902252"]
```

### Actual behavior

```
[[inputs.diskio]]
  devices = ["nvme0n1"]
```

**Comment by srebhan** [comment]
Works for me. I specified
```toml
[[inputs.disk]]
  devices = ["disk/by-id/nvme-eui.xyz"]
```

and got exactly the same output compared to

```toml
[[inputs.disk]]
  devices = ["nvme0n1"]
```

Which error do you get or what is the behavior you are seeing?
