### ISSUE TITLE
id is blank?

### ISSUE THREAD

**Issue by inselbuch** [influxdata/telegraf#11719]
### Relevant telegraf.conf

```toml
[[inputs.opcua.group]]
  name = "opc141"
  namespace="3"
  nodes = [
        {name="value",identifier_type="i",identifier="1001",data_type="integer",tags=[["point","Counter"],["server","${HOSTID}"]] },
        {name="value",identifier_type="i",identifier="1003",data_type="float",tags=[["point","Sawtooth"],["server","${HOSTID}"]] }
   ]
```

### Logs from Telegraf

```text
{"fields":{"Quality":"OK (0x0)","value":-0.08000004},"name":"opc141","tags":{"id":"","point":"Sawtooth","server":"ubuntu5"},"timestamp":1661355320}
```

### System info

Telegraf 1.23.4,  Docker 20.10.17, Ubuntu 22.04 LTS

### Docker

docker run -i -d --name opcua \
    --user telegraf:$(stat -c '%g' /var/run/docker.sock) \
    --network transpara \
    --hostname=`hostname` \
    --restart=always \
    -e HOSTID=ubuntu5 \
    opcua:latest

dockerfile:
FROM telegraf:1.23.4
ADD opc-ua.conf /etc/telegraf/telegraf.conf

### Steps to reproduce

1. edit the .conf file for valid simulation server and tags
2. fire it up
3. watch it go
...

### Expected behavior

{"fields":{"Quality":"OK (0x0)", "value":-0.08000004}, "name":"opc141", "tags":{"id":"<something in here>", "point":"Sawtooth", "server":"ubuntu5"}, "timestamp":1661355320}

### Actual behavior

{"fields":{"Quality":"OK (0x0)", "value":-0.08000004}, "name":"opc141", "tags":{"id":"<nothing in here>", "point":"Sawtooth", "server":"ubuntu5"}, "timestamp":1661355320}
