### ISSUE TITLE
Azure Monitor Output fails with bad request (Unable to load managed identity)

### ISSUE THREAD

**Issue by pengxo** [influxdata/telegraf#11730]
### Relevant telegraf.conf

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.azure_monitor]]
  region = "westeurope"
  # resource id corresponds to the resource id of Azure Container App.
  resource_id = "/subscriptions/<subscriptionId>/resourceGroups/<resourcegroup>/providers/Microsoft.App/containerApps/<containerappName>"
[[inputs.prometheus]]
   urls = ["http://localhost:3500/v1.0/invoke/<containerappname>/method/actuator/prometheus"]
```

### Logs from Telegraf

```text
2022-08-26T20:16:27.168684941Z 2022-08-26T20:16:27Z E! [agent] Error writing to outputs.azure_monitor: unable to fetch authentication credentials: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://westeurope.monitoring.azure.com/subscriptions/<subscriptionid>/resourceGroups/acrrg/providers/Microsoft.App/containerApps/<containerappname>/metrics: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {"statusCode":400,"message":"Unable to load the proper Managed Identity.","correlationId":"141bc3c1-8fef-4b1f-bf58-838e62c5410a"} Endpoint http://localhost:42356/msi/token?api-version=2017-09-01&resource=https%3A%2F%2Fmonitoring.azure.com%2F
```

### System info

Telegraf 1.23.4 

### Steps to reproduce

1. Deploy the telegraf agent image and the app image to Azure Container App (two containers in Azure Container App) with dapr enabled;
2. The managed identity is linked to Azure Container App with role `Monitoring Metrics Publisher`
3. Telegraf publish the custom metrics from the app (endpoint `actuator/prometheus`) to Azure Monitor.

### Expected behavior

The output plugin `azure_monitor` should publish the custom metrics to Azure Monitor

### Actual behavior

Bad request returns as shown above.
