### ISSUE TITLE
Potential memory leak due to docker_log input plugin?

### ISSUE THREAD

**Issue by feld** [influxdata/telegraf#11749]
### Relevant telegraf.conf

```toml
# Read metrics about docker containers
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  container_state_include = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  # container_state_exclude = []
  total = false

  ## Timeout for docker list, info, and stats commands
  timeout = "5s"

  ## Whether to report for each container per-device blkio (8:0, 8:1...),
  ## network (eth0, eth1, ...) and cpu (cpu0, cpu1, ...) stats or not.
  ## Usage of this setting is discouraged since it will be deprecated in favor of 'perdevice_include'.
  ## Default value is 'true' for backwards compatibility, please set it to 'false' so that 'perdevice_include' setting
  ## is honored.
  perdevice = true

  # perdevice_include = ["cpu"]
  # total_include = ["cpu", "blkio", "network"]

  docker_label_include = []
  docker_label_exclude = []

  tag_env = ["JAVA_HOME", "HEAP_SIZE"]


[[inputs.docker_log]]
  endpoint = "unix:///var/run/docker.sock"
```

### Logs from Telegraf

```text
n/a
```

### System info

Telegraf 1.23.0, Debian 11 Bullseye

### Docker

Docker version 20.10.17, build 100c701

### Steps to reproduce

![image](https://user-images.githubusercontent.com/40271278/187717053-32c0e4f8-4526-4412-96c2-3a4db81af961.png)

1.3G usage by telegraf alone, but dockerd is also quite high

After restarting telegraf dockerd memory usage drops as well:

![image](https://user-images.githubusercontent.com/40271278/187717162-c6db109e-e717-40cc-afe7-64df8248ca94.png)

### Expected behavior

Not leaking memory

### Actual behavior

Leaking memory

### Additional info

The docker containers on this server can spew a LOT of logs, so I suspect it's related to docker_log not docker
