### ISSUE TITLE
Specifying an interval - the agent runs, but sometimes records get lost

### ISSUE THREAD

**Issue by mickym2** [influxdata/telegraf#11761]
### Relevant telegraf.conf

```toml
# # Monitors internet speed using speedtest.net service
 [[inputs.internet_speed]]
#   ## This plugin downloads many MB of data each time it is run. As such
#   ## consider setting a higher interval for this plugin to reduce the
#   ## demand on your internet connection.
    interval = "10m"

#   ## Sets if runs file download test
    enable_file_download = false
#
#   ## Caches the closest server location
#   # cache = false
```

### Logs from Telegraf

```text
no log available - runs as a service
```

### System info

Telegraf 1.21.4., Windows 11

### Steps to reproduce

1. Query data with data explorer, but records are incomplete
2.
3.
...

### Expected behavior

I would expect that the input-plugin will be executed every 10 minutes and deliver data. 

### Actual behavior

The plugin is executed every 10 minutes but the data records are incomplete.

`<html>
<body>

tableMEAN | _measurementGROUPSTRING | _fieldGROUPSTRING | _valueNO GROUPDOUBLE | _startGROUPDATETIME:RFC3339 | _stopGROUPDATETIME:RFC3339 | _timeNO GROUPDATETIME:RFC3339 | hostGROUPSTRING
-- | -- | -- | -- | -- | -- | -- | --
0 | internet_speed | download | 81.01752953500367 | 2022-09-04T23:41:38.144Z | 2022-09-05T00:41:38.144Z | 2022-09-04T23:51:10.000Z | MSI
0 | internet_speed | download | 82.2300724995407 | 2022-09-04T23:41:38.144Z | 2022-09-05T00:41:38.144Z | 2022-09-05T00:11:10.000Z | MSI
0 | internet_speed | download | 81.08852710870629 | 2022-09-04T23:41:38.144Z | 2022-09-05T00:41:38.144Z | 2022-09-05T00:21:10.000Z | MSI
0 | internet_speed | download | 81.10720544479429 | 2022-09-04T23:41:38.144Z | 2022-09-05T00:41:38.144Z | 2022-09-05T00:41:10.000Z | MSI

</body>
</html>`

![image](https://user-images.githubusercontent.com/58858526/188340561-641e3416-217d-43c0-acb4-4b03dea0e1f2.png)
