### ISSUE TITLE
influx_parser_type field unused

### ISSUE THREAD

**Issue by elyscape** [influxdata/telegraf#11801]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  commands = ["/bin/echo measurement field1=1"]
  data_format = "influx"
  influx_parser_type = "upstream"

[[outputs.file]]
  files = ["stdout"]
```

### Logs from Telegraf

```text
2022-09-13T22:21:42Z E! [telegraf] Error running agent: Error loading config file demo.conf: plugin inputs.exec: line 1: configuration specified the fields ["influx_parser_type"], but they weren't used
```

### System info

Telegraf 1.24.0

### Steps to reproduce

1. Specify `data_format = "influx"` and `influx_parser_type = "upstream"` on an input.

### Expected behavior

Telegraf is able to load the config file.

### Actual behavior

Telegraf says that the `influx_parser_type` field is unused.

### Additional info

This appears to be related to the following two changes:

1. #11432 migrated the `influx` parser to the new style
2. #11532 removed awareness of the `influx_parser_type` field from the config parser

Neither of these updated the README for the `influx` parser to indicate that the field was no longer supported, or that use of the upstream parser should now be done by using the `influx_upstream` parser (assuming that this is, in fact, how that is supposed to be done). This is a breaking change that should have been called out in the release notes.
