### ISSUE TITLE
No measurments with knx plugin listener

### ISSUE THREAD

**Issue by Gilles7472** [influxdata/telegraf#11812]
### Please direct all support questsions to slack or the forums. Thank you.

Hello everybody,

I need a hand please because I can't have measurments in Influxdb2 with the knx listener plugin.
I have just did the request of a temperature group address in the correct data point type and no measurments.
I am connected in the good multicast adress : 224.0.23.12:3671 and in docker all is all right I think telegraf is connected.
So I must use node-red to flow de group address directly in Influxdb2, all is allright.

Is someone have an idea ?

Thank you very much and sorry for my poor English

Have a nice day

```toml
# Listener capable of handling KNX bus messages provided through a KNX-IP Interface.
[[inputs.knx_listener]]
  ## Type of KNX-IP interface.
  ## Can be either "tunnel" or "router".
  service_type = "router"

  ## Address of the KNX-IP interface.
  service_address = "224.0.23.12:3671"

## Measurement definition(s)
[[inputs.knx_listener.measurement]]
  #   ## Name of the measurement
  name = "TemP9KNX"
  #   ## Datapoint-Type (DPT) of the KNX messages
  dpt = "9.001"
  #   ## List of Group-Addresses (GAs) assigned to the measurement
  addresses = ["0/7/0"]
```
