### ISSUE TITLE
Environmental Variable read still broken

### ISSUE THREAD

**Issue by afikac** [influxdata/telegraf#11868]
### Relevant telegraf.conf

```toml
# # Configuration for sending metrics to InfluxDB 2.0
[[outputs.influxdb_v2]]
#   ## The URLs of the InfluxDB cluster nodes.
#   ##
#   ## Multiple URLs can be specified for a single cluster, only ONE of the
#   ## urls will be written to each interval.
#   ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["https://127.0.0.1:8086"]
#
#   ## Token for authentication.
  token = "$INFLUX_TOKEN"
#
#   ## Organization is the name of the organization you wish to write to.
  organization = "xxxxxxxxxxxxxxxx"
#
#   ## Destination bucket to write into.
  bucket = "xxxxxxxxxxxxxx"
#
#   ## The value of this tag will be used to determine the bucket.  If this
#   ## tag is not set the 'bucket' option is used as the default.
#   # bucket_tag = ""
#
#   ## If true, the bucket tag will not be added to the metric.
#   # exclude_bucket_tag = false
#
#   ## Timeout for HTTP messages.
#   # timeout = "5s"
#
#   ## Additional HTTP headers
#   # http_headers = {"X-Special-Header" = "Special-Value"}
#
#   ## HTTP Proxy override, if unset values the standard proxy environment
#   ## variables are consulted to determine which proxy, if any, should be used.
#   # http_proxy = "http://corporate.proxy:3128"
#
#   ## HTTP User-Agent
  user_agent = "telegraf"
#
#   ## Content-Encoding for write request body, can be set to "gzip" to
#   ## compress body or "identity" to apply no encoding.
#   # content_encoding = "gzip"
#
#   ## Enable or disable uint support for writing uints influxdb 2.0.
#   # influx_uint_support = false
#
#   ## Optional TLS Config for use on HTTP connections.
#   # tls_ca = "/etc/telegraf/ca.pem"
  tls_cert = "/etc/telegraf/self-cert.crt"
  tls_key = "/etc/telegraf/self-key.key"
#   ## Use TLS but skip chain & host verification
  insecure_skip_verify = true
```

### Logs from Telegraf

```text
2022-09-22T21:30:29Z E! [agent] Error writing to outputs.influxdb_v2: failed to send metrics to any configured server(s)
2022-09-22T21:30:39Z E! [outputs.influxdb_v2] When writing to [https://127.0.0.1:8086]: failed to write metric to xxxxxxxxxxxxxxxxx (401 Unauthorized): unauthorized: unauthorized access
```

### System info

Telegraf 1.24, Ubuntu 22.04, InfluxDB OSS 2.4

### Steps to reproduce

1. Scratch install
    - Ubuntu 22.04
    - Install InfluxDB
     - Install telegraf
2. Set some environmental variables in /etc/default/telegraf (for example INFLUX_TOKEN), like in normal TIG stack build.
3. Configure telegraf to use $INFLUX_TOKEN in /etc/telegraf/telegraf.conf
4.  Restart system.

5. Attempt to start telegraf ... you should receive 401 errors due to missing environmental variables.
THIS IS THE PROBLEM...   since /etc/default/telegraf has environment variables configured it "should" be working.

7. Run service telegraf status...  Get the "Main PID" for the telegraf process.
8. Use that PID in this command.

/proc/<Main PID>/environ

THIS IS WHERE YOU CAN SEE THE PROBLEM... the environment variables from /etc/default/telegraf are missing, and never loaded.

Source of this problem is the hyphen in the 

### Expected behavior

/etc/default/telegraf environmental variables should load by default.

The hyphen in the 

### Actual behavior

401 Unauthorized failure, even though all Influx and telegraf config files correct.

### Additional info

Brand new build...  Telegraf 1.24, Ubuntu 22.04, InfluxDB OSS 2.4

Same problem listed here (bug #8395).  This bug was closed without addressing the issue.  This is still a problem, 2 years later.
====================
Telegraf service typo error in script file causes not loading it properly #8395
====================
The fix...

service telegraf stop
cd /lib/systemd/system
vim telegraf.service
.................
<<< EDIT and remove the bad hyphen>>>
PROBLEM LINE

EnvironmentFile=-/etc/default/telegraf

SHOULD BE

EnvironmentFile=/etc/default/telegraf

REMOVE THE HYPHEN
... save edits...

systemctl daemon-reload
service telegraf start

service telegraf status 
>>> Get Main PID and use in next command>>>
/proc/<Main PID>/environ

Environmental variables should be visible now.  If not, reboot system, then check again.

**Comment by powersj** [comment]
Hi,

Can you show me what you have in your `/etc/default/telegraf` file? Of course with removing any secrets. Then what does your corresponding entry look like in your config file?

Per the systemd docs that were referenced in https://github.com/influxdata/telegraf/issues/8395, the `-` makes the file optional. so I'm not sure why removing it would make a difference. I would not call the addition of the `-` character a typo either as the file is literally optional. I will add that the original reporter in that issue came back and said they resolved this after realizing their config was not correct.

While I have put up https://github.com/influxdata/telegraf/pull/11869 which removes the `-` as you suggest I will take a look at the behavior of the build artifacts tomorrow. Most importantly checking to verify that if the file does not exist, does telegraf start.

**Comment by powersj** [comment]
To show an example usage here is my `/etc/default/telegraf`:

```s
MY_USER=johndoe
MY_SECRET=password
```

and a config using this configuration `/etc/telegraf/telegraf.conf`:

```toml
[[inputs.exec]]
  commands = ["/bin/echo metric,user=$MY_USER,secret=$MY_SECRET value=1"]
  data_format = "influx"

[[outputs.file]]
```

which produces:

```
Sep 23 13:38:55 j1 systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
Sep 23 13:39:05 j1 telegraf[1812]: metric,host=j1,secret=password,user=johndoe value=1 1663940340000000000
Sep 23 13:39:15 j1 telegraf[1812]: metric,host=j1,secret=password,user=johndoe value=1 1663940350000000000
Sep 23 13:39:25 j1 telegraf[1812]: metric,host=j1,secret=password,user=johndoe value=1 1663940360000000000
```

Now if I use an artifact from my previous PR, and I do not have that environment file, Telegraf will not start and produce the following messages. This would be a breaking change, should someone not have that file. While the odds are slim someone deleted it, it truly is option:

```s
Sep 23 13:44:16 j1 systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Sep 23 13:44:17 j1 systemd[1]: telegraf.service: Failed to load environment files: No such file or directory
Sep 23 13:44:17 j1 systemd[1]: telegraf.service: Failed to run 'start' task: No such file or directory
Sep 23 13:44:17 j1 systemd[1]: telegraf.service: Failed with result 'resources'.
Sep 23 13:44:17 j1 systemd[1]: Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.
```

Finally, to show an example very similar to your InfluxDB v2 output:

```s
INFLUX_URL=http://192.168.1.160:8086
INFLUX_TOKEN=my-token
INFLUX_ORG=my-org
INFLUX_BUCKET=my-bucket
```

```toml
[agent]
   debug = true
[[inputs.exec]]
  commands = ["/bin/echo metric value=1"]
  data_format = "influx"

[[outputs.influxdb_v2]]
   urls=["$INFLUX_URL"]
   token = "$INFLUX_TOKEN"
   organization = "$INFLUX_ORG"
   bucket = "$INFLUX_BUCKET"
```

```
Sep 23 13:53:47 j1 telegraf[2186]: 2022-09-23T13:53:47Z D! [outputs.influxdb_v2] Wrote batch of 1 metrics in 5.669288ms
Sep 23 13:53:47 j1 telegraf[2186]: 2022-09-23T13:53:47Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
Sep 23 13:53:57 j1 telegraf[2186]: 2022-09-23T13:53:57Z D! [outputs.influxdb_v2] Wrote batch of 1 metrics in 5.94555ms
Sep 23 13:53:57 j1 telegraf[2186]: 2022-09-23T13:53:57Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```

> (401 Unauthorized): unauthorized: unauthorized access

I'm willing to bet you have a typo when you copied your token over, or you are not using the same environment variable name in your config file or something similar.
