### ISSUE TITLE
Invalid character '}' after decimal point numeric literal

### ISSUE THREAD

**Issue by jli113** [influxdata/telegraf#11880]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 9000
  metric_buffer_limit = 90000
  collection_jitter = "0s"
  flush_interval = "30s"
  flush_jitter = "5s"
  precision = ""

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  debug = true

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# [[outputs.influxdb]]
#   urls = ["http://influxdb:8086"]
#   database = "telegraf"
#   username = "telegraf"
#   password = "telegraf"
#   retention_policy = ""

[[outputs.influxdb_v2]]
  urls = ["http://influxdb_winone:8086"]
  token = "SVjwjnslnEg9_kh6EZp7dez5WNsXMl0qGmScSzspOEccj1_7nsNxkoCPatW6RqYFdhFWZ8PF9vJXvBjkxsu9rQ=="
  organization = "midea"
  bucket = "winone"


###############################################################################
#                             INPUT PLUGINS                                   #
###############################################################################


[[inputs.mqtt_consumer]]
  ## MQTT broker URLs to be used. The format should be scheme://host:port,
  ## schema can be tcp, ssl, or ws.
  servers = ["tcp://127.0.0.1:1883"]

  ## Topics that will be subscribed to.
  topics = [
    "/edge/#",
  ]

  ## The message topic will be stored in a tag specified by this value.  If set
  ## to the empty string no topic tag will be created.
  # topic_tag = "topic"

  ## QoS policy for messages
  ##   0 = at most once
  ##   1 = at least once
  ##   2 = exactly once
  ##
  ## When using a QoS of 1 or 2, you should enable persistent_session to allow
  ## resuming unacknowledged messages.
  qos = 1

  ## Connection timeout for initial connection in seconds
  # connection_timeout = "30s"

  ## Maximum messages to read from the broker that have not been written by an
  ## output.  For best throughput set based on the number of metrics within
  ## each message and the size of the output's metric_batch_size.
  ##
  ## For example, if each message from the queue contains 10 metrics and the
  ## output metric_batch_size is 1000, setting this to 100 will ensure that a
  ## full batch is collected and the write is triggered immediately without
  ## waiting until the next flush_interval.
  # max_undelivered_messages = 1000

  ## Persistent session disables clearing of the client session on connection.
  ## In order for this option to work you must also set client_id to identify
  ## the client.  To receive messages that arrived while the client is offline,
  ## also set the qos option to 1 or 2 and don't forget to also set the QoS when
  ## publishing.
  persistent_session = true

  ## If unset, a random client ID will be generated.
  client_id = "test"

  ## Username and password to connect MQTT server.
  username = "test"
  password = "test"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "json"

###############################################################################
#                        PROCESSING PLUGINS                                   #
###############################################################################

[[processors.strings]]
  # [[processors.strings.base64decode]]
  #   field = "message"
  [[processors.strings.valid_utf8]]
    field = "message"
    replacement = ""
```

### Logs from Telegraf

```text
Starting winone_influxdb_winone_1 ... done
Starting winone_telegraf_winone_1 ... done
Attaching to winone_influxdb_winone_1, winone_telegraf_winone_1
influxdb_winone_1  | 2022-09-26T10:36:19.770166872Z     info    found existing boltdb file, skipping setup wrapper      {"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
influxdb_winone_1  | 2022-09-26T10:36:20.010754276Z     info    found existing boltdb file, skipping setup wrapper      {"system": "docker", "bolt_path": "/var/lib/influxdb2/influxd.bolt"}
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Starting Telegraf 1.24.0
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Loaded inputs: mqtt_consumer
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Loaded aggregators: 
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Loaded processors: strings
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Loaded outputs: influxdb_v2
telegraf_winone_1  | 2022-09-26T10:36:20Z I! Tags enabled: host=winone
telegraf_winone_1  | 2022-09-26T10:36:20Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"winone", Flush Interval:30s
telegraf_winone_1  | 2022-09-26T10:36:20Z D! [agent] Initializing plugins
telegraf_winone_1  | 2022-09-26T10:36:20Z D! [agent] Connecting outputs
telegraf_winone_1  | 2022-09-26T10:36:20Z D! [agent] Attempting connection to [outputs.influxdb_v2]
telegraf_winone_1  | 2022-09-26T10:36:20Z D! [agent] Successfully connected to outputs.influxdb_v2
telegraf_winone_1  | 2022-09-26T10:36:20Z D! [agent] Starting service inputs
telegraf_winone_1  | 2022-09-26T10:36:20Z I! [inputs.mqtt_consumer] Connected [tcp://10.116.128.12:1883]
telegraf_winone_1  | 2022-09-26T10:36:20Z D! [inputs.mqtt_consumer] Session found [tcp://10.116.128.12:1883]
influxdb_winone_1  | ts=2022-09-26T10:36:20.163868Z lvl=info msg="Welcome to InfluxDB" log_id=0dALkaGl000 version=2.1.1 commit=657e1839de build_date=2021-11-09T03:03:48Z
influxdb_winone_1  | ts=2022-09-26T10:36:20.165162Z lvl=info msg="Resources opened" log_id=0dALkaGl000 service=bolt path=/var/lib/influxdb2/influxd.bolt
influxdb_winone_1  | ts=2022-09-26T10:36:20.165225Z lvl=info msg="Resources opened" log_id=0dALkaGl000 service=sqlite path=/var/lib/influxdb2/influxd.sqlite
influxdb_winone_1  | ts=2022-09-26T10:36:20.168408Z lvl=info msg="Checking InfluxDB metadata for prior version." log_id=0dALkaGl000 bolt_path=/var/lib/influxdb2/influxd.bolt
influxdb_winone_1  | ts=2022-09-26T10:36:20.168499Z lvl=info msg="Using data dir" log_id=0dALkaGl000 service=storage-engine service=store path=/var/lib/influxdb2/engine/data
influxdb_winone_1  | ts=2022-09-26T10:36:20.168528Z lvl=info msg="Compaction settings" log_id=0dALkaGl000 service=storage-engine service=store max_concurrent_compactions=2 throughput_bytes_per_second=50331648 throughput_bytes_per_second_burst=50331648
influxdb_winone_1  | ts=2022-09-26T10:36:20.168535Z lvl=info msg="Open store (start)" log_id=0dALkaGl000 service=storage-engine service=store op_name=tsdb_open op_event=start
influxdb_winone_1  | ts=2022-09-26T10:36:20.179588Z lvl=info msg="index opened with 8 partitions" log_id=0dALkaGl000 service=storage-engine index=tsi
influxdb_winone_1  | ts=2022-09-26T10:36:20.180446Z lvl=info msg="Reading file" log_id=0dALkaGl000 service=storage-engine engine=tsm1 service=cacheloader path=/var/lib/influxdb2/engine/wal/9e5919725e50819f/autogen/1/_00001.wal size=178842
influxdb_winone_1  | ts=2022-09-26T10:36:20.192943Z lvl=info msg="Opened shard" log_id=0dALkaGl000 service=storage-engine service=store op_name=tsdb_open index_version=tsi1 path=/var/lib/influxdb2/engine/data/9e5919725e50819f/autogen/1 duration=22.276ms
influxdb_winone_1  | ts=2022-09-26T10:36:20.192986Z lvl=info msg="Open store (end)" log_id=0dALkaGl000 service=storage-engine service=store op_name=tsdb_open op_event=end op_elapsed=24.452ms
influxdb_winone_1  | ts=2022-09-26T10:36:20.193001Z lvl=info msg="Starting retention policy enforcement service" log_id=0dALkaGl000 service=retention check_interval=30m
influxdb_winone_1  | ts=2022-09-26T10:36:20.193014Z lvl=info msg="Starting precreation service" log_id=0dALkaGl000 service=shard-precreation check_interval=10m advance_period=30m
influxdb_winone_1  | ts=2022-09-26T10:36:20.193058Z lvl=info msg="Starting query controller" log_id=0dALkaGl000 service=storage-reads concurrency_quota=1024 initial_memory_bytes_quota_per_query=9223372036854775807 memory_bytes_quota_per_query=9223372036854775807 max_memory_bytes=0 queue_size=1024
influxdb_winone_1  | ts=2022-09-26T10:36:20.197028Z lvl=info msg="Configuring InfluxQL statement executor (zeros indicate unlimited)." log_id=0dALkaGl000 max_select_point=0 max_select_series=0 max_select_buckets=0
influxdb_winone_1  | ts=2022-09-26T10:36:20.482146Z lvl=info msg=Starting log_id=0dALkaGl000 service=telemetry interval=8h
influxdb_winone_1  | ts=2022-09-26T10:36:20.482150Z lvl=info msg=Listening log_id=0dALkaGl000 service=tcp-listener transport=http addr=:8086 port=8086
telegraf_winone_1  | 2022-09-26T10:36:52Z D! [outputs.influxdb_v2] Wrote batch of 19 metrics in 4.869655ms
telegraf_winone_1  | 2022-09-26T10:36:52Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 90000 metrics
influxdb_winone_1  | ts=2022-09-26T10:36:56.202315Z lvl=info msg=Unauthorized log_id=0dALkaGl000 error="session not found"
telegraf_winone_1  | 2022-09-26T10:37:22Z E! [inputs.mqtt_consumer] Error in plugin: invalid character '}' after decimal point in numeric literal
telegraf_winone_1  | 2022-09-26T10:37:25Z D! [outputs.influxdb_v2] Wrote batch of 9 metrics in 3.451429ms
telegraf_winone_1  | 2022-09-26T10:37:25Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 90000 metrics
telegraf_winone_1  | 2022-09-26T10:37:34Z E! [inputs.mqtt_consumer] Error in plugin: invalid character '}' after decimal point in numeric literal
telegraf_winone_1  | 2022-09-26T10:37:57Z D! [outputs.influxdb_v2] Wrote batch of 11 metrics in 2.576138ms
telegraf_winone_1  | 2022-09-26T10:37:57Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 90000 metrics
telegraf_winone_1  | 2022-09-26T10:38:29Z D! [outputs.influxdb_v2] Wrote batch of 13 metrics in 2.77671ms
telegraf_winone_1  | 2022-09-26T10:38:29Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 90000 metrics
```

### System info

Docker 20.10.8

### Docker

version: '3'
services:
  telegraf:
    image: telegraf:latest
    restart: always
    depends_on:
      - influxdb
    links:
      - influxdb
    networks:
      - test_net
    volumes: 
      - /root/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - '8125:8125/udp'

  influxdb:
    image: influxdb:latest
    restart: always
    ports:
      - '8086:8086'
    networks:
      - test_net
    volumes:
      - influx_storage:/var/lib/influxdb
  
networks:
  test_net:
    driver: bridge

volumes:
  influx_storage: {}

### Steps to reproduce

1. data to send: {"devs":[{"d":[{"m":"digital_HT_jiandarenke_dht_7801_c","ts":1664190472,"v":328.000},{"m":"digital_HT_jiandarenke_dht_7801_h","ts":1664190472,"v":418.000},{"m":"digital_HT_jiandarenke_dht_7802_c","ts":1664190472,"v":334.000},{"m":"digital_HT_jiandarenke_dht_7802_h","ts":1664190472,"v":398.000},{"m":"digital_HT_jiandarenke_dht_7803_c","ts":1664190472,"v":323.000},{"m":"digital_HT_jiandarenke_dht_7803_h","ts":1664190472,"v":425.000},{"m":"digital_HT_jiandarenke_dht_7804_c","ts":1664190472,"v":334.000},{"m":"digital_HT_jiandarenke_dht_7804_h","ts":1664190472,"v":405.000},{"m":"digital_HT_jiandarenke_dht_7805_c","ts":1664190472,"v":334.000},{"m":"digital_HT_jiandarenke_dht_7805_h","ts":1664190472,"v":407.000},{"m":"digital_HT_jiandarenke_dht_7806_c","ts":1664190472,"v":330.000},{"m":"digital_HT_jiandarenke_dht_7806_h","ts":1664190472,"v":417.000},{"m":"digital_HT_jiandarenke_dht_7807_c","ts":1664190472,"v":334.000},{"m":"digital_HT_jiandarenke_dht_7807_h","ts":1664190472,"v":412.000},{"m":"digital_HT_jiandarenke_dht_7808_c","ts":1664190472,"v":338.000},{"m":"digital_HT_jiandarenke_dht_7808_h","ts":1664190472,"v":392.000},{"m":"digital_HT_jiandarenke_dht_7809_c","ts":1664190472,"v":332.000},{"m":"digital_HT_jiandarenke_dht_7809_h","ts":1664190472,"v":413.000},{"m":"digital_HT_jiandarenke_dht_7810_c","ts":1664190472,"v":334.000},{"m":"digital_HT_jiandarenke_dht_7810_h","ts":1664190472,"v":410.000},{"m":"digital_HT_jiandarenke_dht_7811_c","ts":1664190472,"v":335.000},{"m":"digital_HT_jiandarenke_dht_7811_h","ts":1664190472,"v":406.000},{"m":"digital_HT_jiandarenke_dht_7812_c","ts":1664190472,"v":328.000},{"m":"digital_HT_jiandarenke_dht_7812_h","ts":1664190472,"v":421.000},{"m":"digital_HT_jiandarenke_dht_7813_c","ts":1664190472,"v":332.000},{"m":"digital_HT_jiandarenke_dht_7813_h","ts":1664190472,"v":415.000},{"m":"digital_HT_jiandarenke_dht_7814_c","ts":1664190472,"v":333.000},{"m":"digital_HT_jiandarenke_dht_7814_h","ts":1664190472,"v":433.000},{"m":"digital_HT_jiandarenke_dht_7815_c","ts":1664190472,"v":331.000},{"m":"digital_HT_jiandarenke_dht_7815_h","ts":1664190472,"v":425.000},{"m":"digital_HT_jiandarenke_dht_7816_c","ts":1664190472,"v":331.000},{"m":"digital_HT_jiandarenke_dht_7816_h","ts":1664190472,"v":460.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Acc_EER","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_TC_WS","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak11","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak12","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak13","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak14","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak15","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak16","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak17","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak18","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak19","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak20","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak21","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak22","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak23","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak24","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak25","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak26","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak27","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak28","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_TC_T_SP","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_BTU_AccCool","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_BTU_AccFL","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_BTU_FL","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_BTU_FLV","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_BTU_InsCool","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_BTU_R_T","ts":1664190472,"v":-107612256.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_BTU_S_T","ts":1664190472,"v":-107612576.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_TC_T","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CHWRT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CHWST","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Con_DT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CondP","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CondT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Current","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_TC_Mode","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CWRT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CWST","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_ET","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Eva_DT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_EvaP","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_EvaT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_OA_WBT","ts":1664190472,"v":-0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Load","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_LR","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_ResetT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Restart_DT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_RT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_OA_T","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Run_Mode","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_SOT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_SPST","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_ST","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Startup_Num","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Status","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_TargetT","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHW_DP","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_OA_RH","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_OA_HR","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CWP_VFD_Frq_FB","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHWP_VFD_Frq_FB","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHWR_T","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHWS_T","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHWT_FSP","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CT_VFD_Frq_FB[1]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CT_VFD_Frq_FB[2]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CT_VFD_Frq_FB[3]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CT_VFD_Frq_FB[4]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CT_VFD_Frq_FB[5]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CT_VFD_Frq_FB[6]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_OA_ENT","ts":1664190472,"v":-0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_OA_Dew","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_Uca","ts":1664190472,"v":-0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_Ubc","ts":1664190472,"v":-0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_Uab","ts":1664190472,"v":-0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_P","ts":1664190472,"v":-37545291834504249344.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_Ic","ts":1664190472,"v":6638756650511499264.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_Ib","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_Ia","ts":1664190472,"v":-11471251539266107017235791872.},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Elec_E","ts":1664190472,"v":-0.058},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_EER","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CWT_FSP","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CWS_T","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CWR_T","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CW_DP","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Total_Alarm","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_Run[5]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_Run[6]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_Run[4]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CWP_F","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CWP_LR","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CWP_Run","ts":1664190472,"v":1.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_Run[3]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_Run[2]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_Run[1]","ts":1664190472,"v":1.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_LR[6]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_LR[5]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_LR[4]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_LR[3]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_LR[2]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_LR[1]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_F[6]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_F[5]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_F[4]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_F[3]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_Final_Startup","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_F[2]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CTF_F[1]","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHWP_LR","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHWP_F","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_Run","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_F","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_TC_LR","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CW_FS","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_TC_Startup","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CH_CHW_FS","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak9","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_bak10","ts":1664190472,"v":0.000},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1_CHWP_Run","ts":1664190472,"v":1.000},{"m":"digital_HT_jiandarenke_dht","ts":1664190472,"v":1},{"m":"s7_1200_MODBUSTCP_S7_1200_Device_1","ts":1664190472,"v":1}],"dev":"shishanlift"}],"pKey":"WinoneFactoryNanHai","sn":"2206210316","ts":1664190472,"ver":"2.0.0"}
2. docker-compose up
3.
...

### Expected behavior

expects telegraf to write all data to database

### Actual behavior

got error Invalid character '}' after decimal point numeric literal
