### ISSUE TITLE
OPCUA - Tags not present in the metrics

### ISSUE THREAD

**Issue by Giu-seppe** [influxdata/telegraf#11899]
### Relevant telegraf.conf

```toml
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})


# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Collection offset is used to shift the collection by the given amount.
  ## This can be be used to avoid many plugins querying constraint devices
  ## at the same time by manually scheduling them in time.
  # collection_offset = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## Collected metrics are rounded to the precision specified. Precision is
  ## specified as an interval with an integer + unit (e.g. 0s, 10ms, 2us, 4s).
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  ##
  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s:
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ##
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  precision = "0s"

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0h"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true

  ## Method of translating SNMP objects. Can be "netsnmp" which
  ## translates by calling external programs snmptranslate and snmptable,
  ## or "gosmi" which translates using the built-in gosmi library.
  # snmp_translator = "netsnmp"


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################
# Configuration for sending metrics to InfluxDB 2.0
[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "myToken"
  organization = "xxx"
  ## Destination bucket to write into.
  bucket = "ALL"





[[outputs.file]]
  ## Files to parse each interval.  Accept standard unix glob matching rules,
  ## as well as ** to match recursive files and directories.
   files = ["./tmp/metrics.out"]
   data_format = "influx"
   rotation_interval = "24h"
   rotation_max_archives = 10

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# Retrieve data from OPCUA devices
[[inputs.opcua]]
  ## Metric name
   alias = "OPCUA"
   name = "OPCUA"
  #
  ## OPC UA Endpoint URL
   endpoint = "opc.tcp://192.168.1.200:4840"
  #
  ## Maximum time allowed to establish a connect to the endpoint.
   connect_timeout = "10s"
  #
  ## Maximum time allowed for a request over the estabilished connection.
   request_timeout = "1s"
  #
  ## Security policy, one of "None", "Basic128Rsa15", "Basic256",
  ## "Basic256Sha256", or "auto"
   security_policy = "None"
  #
  ## Security mode, one of "None", "Sign", "SignAndEncrypt", or "auto"
   security_mode = "None"
  #
  ## Path to cert.pem. Required when security mode or policy isn't "None".
  ## If cert path is not supplied, self-signed cert and key will be generated.
  # certificate = "/etc/telegraf/cert.pem"
  #
  ## Path to private key.pem. Required when security mode or policy isn't "None".
  ## If key path is not supplied, self-signed cert and key will be generated.
  # private_key = "/etc/telegraf/key.pem"
  #
  ## Authentication Method, one of "Certificate", "UserName", or "Anonymous".  To
  ## authenticate using a specific ID, select 'Certificate' or 'UserName'
  # auth_method = "Anonymous"
  #
  ## Username. Required for auth_method = "UserName"
  # username = ""
  #
  ## Password. Required for auth_method = "UserName"
  # password = ""
  #
  ## Option to select the metric timestamp to use. Valid options are:
  ##     "gather" -- uses the time of receiving the data in telegraf
  ##     "server" -- uses the timestamp provided by the server
  ##     "source" -- uses the timestamp provided by the source
   timestamp = "gather"
  #
  ## Node ID configuration
  ## name              - field name to use in the output
  ## namespace         - OPC UA namespace of the node (integer value 0 thru 3)
  ## identifier_type   - OPC UA ID type (s=string, i=numeric, g=guid, b=opaque)
  ## identifier        - OPC UA ID (tag as shown in opcua browser)
  ## tags              - extra tags to be added to the output metric (optional)
  ## Example:
  ## {name="ProductUri", namespace="0", identifier_type="i", identifier="2262", tags=[["tag1","value1"],["tag2","value2]]}
   nodes = [
    {name="aGlobalArray", namespace="6", identifier_type="s", identifier="::AsGlobalPV:aGlobalArray", tags=[["tag1","value1"],["tag2","value2"]]},
    {name="bBlink50ms", namespace="6", identifier_type="s", identifier="::AsGlobalPV:bBlink50ms", tags=[["component", "Genset"]]},
    {name="nGlobal", namespace="6", identifier_type="s", identifier="::AsGlobalPV:nGlobal", tags=[["component", "Engine"]]},
    {name="V10.RPMx100", namespace="6", identifier_type="s", identifier="::Program:V10.RPMx100", tags=[["component", "Engine"]]},
    {name="V10.temp", namespace="6", identifier_type="s", identifier="::Program:V10.temp", tags=[["component", "Engine"]]},
    {name="V10.torque", namespace="6", identifier_type="s", identifier="::Program:V10.torque", tags=[["component", "Engine"]]},
    {name="V10.torquePercentage", namespace="6", identifier_type="s", identifier="::Program:V10.torquePercentage", tags=[["component", "Engine"]]},
  ]
```

### Logs from Telegraf

```text
C:\Users\TEST_LAB\InfluxData\telegraf>telegraf.exe --debug --config telegraf.conf --config-directory telegraf.d
2022-09-28T13:18:45Z I! Starting Telegraf 1.24.0-28e7cf05
2022-09-28T13:18:45Z I! Available plugins: 205 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-09-28T13:18:45Z I! Loaded inputs: opcua
2022-09-28T13:18:45Z I! Loaded aggregators:
2022-09-28T13:18:45Z I! Loaded processors:
2022-09-28T13:18:45Z I! Loaded outputs: file influxdb_v2 (2x)
2022-09-28T13:18:45Z I! Tags enabled:
2022-09-28T13:18:45Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
2022-09-28T13:18:45Z D! [agent] Initializing plugins
2022-09-28T13:18:45Z W! [inputs.opcua::OPCUA] Failed to load certificate: open /etc/telegraf/cert.pem: The system cannot find the path specified.
2022-09-28T13:18:45Z D! [agent] Connecting outputs
2022-09-28T13:18:45Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2022-09-28T13:18:45Z D! [agent] Successfully connected to outputs.influxdb_v2
2022-09-28T13:18:45Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2022-09-28T13:18:45Z D! [agent] Successfully connected to outputs.influxdb_v2
2022-09-28T13:18:45Z D! [agent] Attempting connection to [outputs.file]
2022-09-28T13:18:45Z D! [agent] Successfully connected to outputs.file
2022-09-28T13:18:45Z D! [agent] Starting service inputs
```

### System info

Telegraf 1.24.0-28e7cf05 ; Windows 10 

### Steps to reproduce

1. Start the configuration
2. Open the metrics.out file
3. Added tags are not present

### Expected behavior

Tags have been added to the metrics
Example:
```
    {name="aGlobalArray", namespace="6", identifier_type="s", identifier="::AsGlobalPV:aGlobalArray", tags=[["tag1","value1"],["tag2","value2"]]},
```
the tags added in the configuration are present in the metrics
```
OPCUA,tag1=value1,tag2=value2,id=ns\=6;s\=::Program:V10.torquePercentage V10.torquePercentage=0i,Quality="OK (0x0)" 1664355420000000000
```

### Actual behavior

Tags have been added to the metrics
Example:
```
    {name="aGlobalArray", namespace="6", identifier_type="s", identifier="::AsGlobalPV:aGlobalArray", tags=[["tag1","value1"],["tag2","value2"]]},
```
The tags added in the configuration are not present in the metrics
```
OPCUA,id=ns\=6;s\=::Program:V10.torquePercentage V10.torquePercentage=0i,Quality="OK (0x0)" 1664355420000000000
```

### Additional info

With this configuration, the tags entered in the configuration do not appear in the metrics.
This is the first time I use the "tags" feature of this plugin, I think this is how it works, if not, please correct me
