### ISSUE TITLE
Procstat cpu_usage reports higher percent value than system total_cpu from CPU plugin

### ISSUE THREAD

**Issue by neet01** [influxdata/telegraf#11908]
### Relevant telegraf.conf

```toml
# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## Comment this line if you want the raw CPU time metrics
  fielddrop = ["time_*"]

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default, telegraf gather stats for all mountpoints.
  ## Setting mountpoints will restrict the stats to the specified mountpoints.
  # mount_points = ["/"]

  ## Ignore some mountpoints by filesystem type. For example (dev)tmpfs (usually
  ## present on /run, /var/run, /dev/shm or /dev).
  ignore_fs = ["tmpfs", "devtmpfs"]

# Read metrics about disk IO by device
[[inputs.diskio]]
  ## By default, telegraf will gather stats for all devices including
  ## disk partitions.
  ## Setting devices will restrict the stats to the specified devices.
  # devices = ["sda", "sdb"]
  ## Uncomment the following line if you need disk serial numbers.
  # skip_serial_number = false

# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  # no configuration

# Read metrics about memory usage
[[inputs.mem]]
  # no configuration

# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration

# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration

# Read metrics about system load & uptime
[[inputs.system]]
  # no configuration

# Read metrics about network interface usage
[[inputs.net]]
  # collect data only about specific interfaces
  # interfaces = ["eth0"]

[[inputs.netstat]]
  # no configuration

[[inputs.interrupts]]
  # no configuration

[[inputs.linux_sysctl_fs]]
  # no configuration

[[inputs.procstat]]
  
[[inputs.procstat]]
  user = "{{ app_user }}"
  prefix = "{{ procstat_var }}"

[[inputs.procstat]]
  exe = "telegraf"
  prefix = "telegraf"
```

### Logs from Telegraf

```text
No error (see title)
```

### System info

Telegraf 1.24.1 / Ubuntu 18.03

### Steps to reproduce

1.  Run telegraf with procstat and cpu input plugins (and influxDB v2 output plugin) on Ubuntu 18.04 AWS EC2
2. Query data to view in Grafana, compare cpu plugin and procstat plugin in same panel.
3. Notice usage inconsistencies.
...

### Expected behavior

CPU Usage needs to display values within system parameters. Currently procstat CPU usage is greater than overall system total, but in reality, procstat values should be lower than total system cpu usage.

### Actual behavior

Procstat metric values show metrics greater than actual system total, implying that procstat is using more cpu than available even when load is within bounds. 
![image](https://user-images.githubusercontent.com/77303397/193159117-de912d61-75f9-4878-a7c8-0cf9e7f7d241.png)
