### ISSUE TITLE
JSON_v2 parses OK from file, but not from HTTP

### ISSUE THREAD

**Issue by dfousek** [influxdata/telegraf#11916]
### Relevant telegraf.conf

```toml
[[inputs.http]]
    urls = ["http://100m.ddns.net:44482/status.json"]
#   files = ["/home/pi/test.json"]
    name_override = "mydata"
    data_format = "json_v2"
    [[inputs.http.json_v2]]
        [[inputs.http.json_v2.field]]
            path = "Monitor.AI.AI1.value"
            rename = "AI1"
            type = "float"
```

### Logs from Telegraf

```text
[inputs.http] Error in plugin: [url=http://100m.ddns.net:44482/status.json]: parsing metrics failed: invalid JSON provided, unable to parse
```

### System info

Telegraf 1.24.1 - InfluxDB v2.4.0 - Debian GNU/Linux 11 (bullseye) aarch64  (RasPi4)

### Steps to reproduce

1. I have a JSON string (http://100m.ddns.net:44482/status.json) with valid GJSON path syntax.
2. When Copied/Pasted from a browser to a text file (and replace inputs.http with inputs.file in the above conf) the parsing succeeds.
3. When running directly the above conf with http, parsing fails

### Expected behavior

(see above the Steps to reproduce)

### Actual behavior

(see above the Steps to reproduce)

**Comment by powersj** [comment]
> invalid JSON provided, unable to parse

This error, generally means that the JSON you downloaded is invalid. I would suggest trying to `curl` or `wget` that URL on the system you are running telegraf on to see what data you are getting. It could be that it is behind a login or you are getting some error or HTML injected into the file, which would cause the parsing to fail.

If I have a JSON file like this:

```
{
    "value": 1.23456
}
```

Using this config as a file and served locally on an HTTP server works:

```toml
[[inputs.file]]
  files = ["data.json"]
  name_override = "mydata"
  data_format = "json_v2"
  [[inputs.file.json_v2]]
    [[inputs.file.json_v2.field]]
      path = "value"
      type = "float"

[[inputs.http]]
  urls = ["http://127.0.0.1:8000/data.json"]
  name_override = "mydata"
  data_format = "json_v2"
  [[inputs.http.json_v2]]
    [[inputs.http.json_v2.field]]
      path = "value"
      type = "float"

```

```s
mydata value=1.23456 1664804838000000000
mydata,url=http://127.0.0.1:8000/data.json value=1.23456 1664804838000000000
```
