### ISSUE TITLE
Telegraf Graylog Doesn't Pull Metrics

### ISSUE THREAD

**Issue by hackdefendr** [influxdata/telegraf#11918]
### Relevant telegraf.conf

```toml
# Read flattened metrics from one or more GrayLog HTTP endpoints
[[inputs.graylog]]
  ## API endpoint, currently supported API:
  ##
  ##   - multiple  (Ex http://<host>:12900/system/metrics/multiple)
  ##   - namespace (Ex http://<host>:12900/system/metrics/namespace/{namespace})
  ##
  ## For namespace endpoint, the metrics array will be ignored for that call.
  ## Endpoint can contain namespace and multiple type calls.
  ##
  ## Please check http://[graylog-server-ip]:12900/api-browser for full list
  ## of endpoints
  servers = [
    "http://192.168.187.15:9000/api/system/metrics",
  ]

  timeout = "5s"

  ## Metrics list
  ## List of metrics can be found on Graylog webservice documentation.
  ## Or by hitting the web service api at:
  ##   http://[graylog-host]:12900/system/metrics
  metrics = [
    "org.graylog2.inputs",
    "org.graylog2.plugins",
    "org.graylog2.buffers",
    "org.graylog2.throughput"
  ]

  ## Username and password
  username = "admin"
  password = "********"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = true
```

### Logs from Telegraf

```text
root@influx:~# telegraf --config /etc/telegraf/telegraf.conf --input-filter graylog --test --debug
2022-10-02T00:52:07Z I! Starting Telegraf 1.25.0-ed0b59f1
2022-10-02T00:52:07Z I! Available plugins: 223 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-10-02T00:52:07Z I! Loaded inputs: graylog
2022-10-02T00:52:07Z I! Loaded aggregators: 
2022-10-02T00:52:07Z I! Loaded processors: 
2022-10-02T00:52:07Z W! Outputs are not used in testing mode!
2022-10-02T00:52:07Z I! Tags enabled: 
2022-10-02T00:52:07Z D! [agent] Initializing plugins
2022-10-02T00:52:07Z D! [agent] Starting service inputs
2022-10-02T00:52:07Z D! [agent] Stopping service inputs
2022-10-02T00:52:07Z D! [agent] Input channel closed
2022-10-02T00:52:07Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.25.0-ed0b59f1, Debian 11, LXC

### Docker

* Running as an LXC container under Proxmox.

### Steps to reproduce

1. Configure a graylog input to pull from the metrics api
2. Test configuration with telegraf cli using --debug
3. Validate that no data is received as shown in the telegraf log.
...

### Expected behavior

When I visit the API for Graylog directly to pull a list of fields, then endpoint is:

`http://localhost:9000/api/system/metrics`

### Actual behavior

The API is accessible directly, but Telegraf just isn't trying. See the screenshot in Additional Info.

### Additional info

Screenshot of the current Graylog API Browser.

<img width="752" alt="Screenshot 2022-10-01 at 8 00 09 PM" src="https://user-images.githubusercontent.com/2224217/193433579-36f6bb28-1a28-4c74-bd5c-5a82fa35ac07.png">

It looks like the endpoint changed, the url of the API browser changed, and this may have caused things to break in the Telegraf plugin.
