### ISSUE TITLE
parser not respecting data_type

### ISSUE THREAD

**Issue by wicol** [influxdata/telegraf#11921]
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
  name_override = "mqtt"
  ...
  data_format = "value"
  data_type = "string"

[[processors.parser]]
  namepass = ["mqtt"]
  parse_fields = ["value"]
  drop_original = false
  merge = "override"
  data_format = "value"
  data_type = "float"
```

### Logs from Telegraf

```text
2022-10-02T10:43:25Z E! [processors.parser] could not parse field value: strconv.Atoi: parsing "243.671": invalid syntax
```

### System info

Telegraf 1.24.1

### Steps to reproduce

1. Input with simple data_format = "value", data_type = "string"
2. parser processor with data_format = "value", data_type = "float"

### Expected behavior

I'm upgrading from 1.23 where this works as expected. Values get converted to floats.

### Actual behavior

Looks like it's trying to convert values to ints in 1.24?
