### ISSUE TITLE
inputs.docker docker_label_exclude[] filter not working

### ISSUE THREAD

**Issue by chrish987** [influxdata/telegraf#11930]
### Relevant telegraf.conf

```toml
[[inputs.docker]]

  interval = "30s"
  alias = "docker_rhel"
  name_override = "docker"

  ## Docker Endpoint
  ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
  ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"

  ## Set to true to collect Swarm metrics(desired_replicas, running_replicas)
  ## Note: configure this in one of the manager nodes in a Swarm cluster.
  ## configuring in multiple Swarm managers results in duplication of metrics.
  gather_services = false

  ## Only collect metrics for these containers. Values will be appended to
  ## container_name_include.
  ## Deprecated (1.4.0), use container_name_include
  # container_names = []

  ## Set the source tag for the metrics to the container ID hostname, eg first 12 chars
  source_tag = false

  ## Containers to include and exclude. Collect all if empty. Globs accepted.
  container_name_include = []
  container_name_exclude = []

  ## Container states to include and exclude. Globs accepted.
  ## When empty only containers in the "running" state will be captured.
  ## example: container_state_include = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  ## example: container_state_exclude = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  # container_state_include = []
  # container_state_exclude = []

  ## Timeout for docker list, info, and stats commands
  timeout = "5s"

  ## Whether to report for each container per-device blkio (8:0, 8:1...),
  ## network (eth0, eth1, ...) and cpu (cpu0, cpu1, ...) stats or not.
  ## Usage of this setting is discouraged since it will be deprecated in favor of 'perdevice_include'.
  ## Default value is 'true' for backwards compatibility, please set it to 'false' so that 'perdevice_include' setting
  ## is honored.
  perdevice = false

  ## Specifies for which classes a per-device metric should be issued
  ## Possible values are 'cpu' (cpu0, cpu1, ...), 'blkio' (8:0, 8:1, ...) and 'network' (eth0, eth1, ...)
  ## Please note that this setting has no effect if 'perdevice' is set to 'true'
  perdevice_include = ["cpu"]

  ## Whether to report for each container total blkio and network stats or not.
  ## Usage of this setting is discouraged since it will be deprecated in favor of 'total_include'.
  ## Default value is 'false' for backwards compatibility, please set it to 'true' so that 'total_include' setting
  ## is honored.
  total = true

  ## Specifies for which classes a total metric should be issued. Total is an aggregated of the 'perdevice' values.
  ## Possible values are 'cpu', 'blkio' and 'network'
  ## Total 'cpu' is reported directly by Docker daemon, and 'network' and 'blkio' totals are aggregated by this plugin.
  ## Please note that this setting has no effect if 'total' is set to 'false'
  total_include = ["cpu", "blkio", "network"]

  ## docker labels to include and exclude as tags.  Globs accepted.
  ## Note that an empty array for both will include all labels as tags
  # docker_label_include = ["container_name", "container_status", "engine_host", "job", "cpu"]
  docker_label_include = []
  docker_label_exclude = [
    "com_docker_compose_config_hash",
    "com_docker_compose_container_number",
    "com_docker_compose_oneoff",
    "com_docker_compose_project",
    "com_docker_compose_project_config_files",
    "com_docker_compose_project_working_dir",
    "container_id",
    "container_image",
    "container_version",
    "server_version",
    "org_opencontainers_image_created",
    "org_opencontainers_image_revision",
    "org_opencontainers_image_source",
    "org_label_schema_arch",
    "org_label_schema_build_date",
    "org_label_schema_description",
    "org_label_schema_docker_dockerfile",
    "org_label_schema_license",
    "org_label_schema_name",
    "org_label_schema_url",
    "org_label_schema_vcs_ref",
    "org_label_schema_vcs_type",
    "org_label_schema_vcs_url",
    "org_label_schema_version",
    "authors",
    "maintainer",
    "org_label_schema_url"
    ]
  
  ## Which environment variables should we use as a tag
  # tag_env = ["JAVA_HOME", "HEAP_SIZE"]

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

[[outputs.prometheus_client]]

  namepass = ["httpd","redfish","mysql","vsphere","docker"]

  ## Address to listen on.
  listen = ":9273"

  ## Metric version controls the mapping from Prometheus metrics into Telegraf metrics.
  ## See "Metric Format Configuration" in plugins/inputs/prometheus/README.md for details.
  ## Valid options: 1, 2
  metric_version = 2

  ## Use HTTP Basic Authentication.
  # basic_username = "Foo"
  # basic_password = "Bar"

  ## If set, the IP Ranges which are allowed to access metrics.
  ##   ex: ip_range = ["192.168.0.0/24", "192.168.1.0/30"]
  # ip_range = []

  ## Path to publish the metrics on.
  # path = "/metrics"

  ## Expiration interval for each metric. 0 == no expiration
  expiration_interval = "120s"

  ## Collectors to enable, valid entries are "gocollector" and "process".
  ## If unset, both are enabled.
  collectors_exclude = ["gocollector", "process"]

  ## Send string metrics as Prometheus labels.
  ## Unless set to false all string metrics will be sent as labels.
  # string_as_label = true

  ## If set, enable TLS with the given certificate.
  # tls_cert = "/etc/ssl/telegraf.crt"
  # tls_key = "/etc/ssl/telegraf.key"

  ## Set one or more allowed client CA certificate file names to
  ## enable mutually authenticated TLS connections
  # tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]

  ## Export metric collection time.
  # export_timestamp = false
```

### Logs from Telegraf

```text
nothing useful in the logs - output is (truncated):

# HELP docker_active_anon Telegraf collected metric
# TYPE docker_active_anon untyped
docker_active_anon{com_docker_compose_config_hash="04fd20539b144c2cfbcbdac99145b1368d178c454b11386ecf7f647c01bfb4dc",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="guacamole",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/guacamole",com_docker_compose_service="guacd",com_docker_compose_version="1.28.4",container_id="3442fb45553b5f169e931c2ea0ed2dd9d1b2a01e0b8fc0da874671559d1742ca",container_image="guacamole/guacd",container_name="guacd",container_status="running",container_version="1.4.0",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 8192
docker_active_anon{com_docker_compose_config_hash="11b62f8035a5919901355072b86f97535107d20f4661ad7b5fad6398e72a5b69",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="monitor_stack",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/monitor_stack",com_docker_compose_service="snmp-exporter",com_docker_compose_version="1.28.4",container_id="a98f23fd94b3ca761090191a6b47c8b4bfcbf0ebd3244c12883b0e5deaa565d5",container_image="prom/snmp-exporter",container_name="snmp-exporter",container_status="running",container_version="latest",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="1596a1545ed323462d145705e8bd84fdd9e90e65ff25cbd08a21a9933fa44147",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="httpd",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/httpd",com_docker_compose_service="php",com_docker_compose_version="1.28.4",container_id="e7c1a3104327cebd3b6f80f2f887502ce028382c3b89994d19caeb4ee7cc13b1",container_image="httpd_php",container_name="php",container_status="running",container_version="unknown",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 12288
docker_active_anon{com_docker_compose_config_hash="1664635a68396cd8ce5293d9d0e0ab888e2eadf6d029115df4be9de58801a7d9",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="guacamole",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/guacamole",com_docker_compose_service="guacamole",com_docker_compose_version="1.28.4",container_id="63acb4ddfa24e97eadc605a5ed83f12c163f8866f1e5213df36533547c12ef93",container_image="guacamole/guacamole",container_name="guacamole",container_status="running",container_version="1.4.0",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="3c00f41a9af978c08d537ef44960141551863a5e3eeedfc7ecfc40b530500020",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="monitor_stack",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/monitor_stack",com_docker_compose_service="grafana",com_docker_compose_version="1.28.4",container_id="5b2b45c7dd8c16af974cc781ce17ef6e03308c27184bf2a8c8a90b471c1c7eb3",container_image="grafana/grafana",container_name="grafana",container_status="running",container_version="9.1.6",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="735b29ba09cb15d61cd9990d08238be52918697f933aae7436945502d584d999",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="httpd",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/httpd",com_docker_compose_service="httpd",com_docker_compose_version="1.28.4",container_id="0c874b7b84e9f5a4031cbea0a8932baccaf51a69730673dd01fac74d695aec6d",container_image="httpd_httpd",container_name="httpd",container_status="running",container_version="unknown",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 12288
docker_active_anon{com_docker_compose_config_hash="9966b4cabc2728bab86fa27d8411050ffdda9aa67e80067b0ee897039ab6a4f4",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="monitor_stack",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/monitor_stack",com_docker_compose_service="telegraf",com_docker_compose_version="1.28.4",container_id="2cff7800865609b672b975c44af81063fe99daac22a1345cc7e19d18279d7a86",container_image="telegraf",container_name="telegraf",container_status="running",container_version="1.24.2-alpine",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="af04598688c56c350bfb5b2b138d7dfd771ecf46146cd079e82fddf85dfec561",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="monitor_stack",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/monitor_stack",com_docker_compose_service="cadvisor",com_docker_compose_version="1.28.4",container_id="127a95fe3f862f926f32721b514a7355e9838aad725c7d3358bff3a942e07482",container_image="gcr.io/cadvisor/cadvisor",container_name="cadvisor",container_status="running",container_version="v0.45.0",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="bd38840bf5a331a522aa45fafe636950464cdc1d5c0900fe79be6d228c67acda",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="portainer",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/portainer",com_docker_compose_service="portainer",com_docker_compose_version="1.28.4",container_id="9faefcb94c45f9a04ed631490e0582cef803a14310942b114384ce50df63ee9f",container_image="portainer/portainer-ee",container_name="portianer",container_status="running",container_version="2.15.1-alpine",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="f16ed3059ba8cc0a6d3265e9ea98977f087e0636fd57b81bcdabf75d404585e2",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="monitor_stack",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/monitor_stack",com_docker_compose_service="prometheus",com_docker_compose_version="1.28.4",container_id="550751f58490274ab04822e5f45b4149e683e67ea430e33241fc4cf70dad434a",container_image="prom/prometheus",container_name="prometheus",container_status="running",container_version="v2.38.0",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="51b4863cbf03aec7045fee8f2b82a6e63cfb31f3184d0fcad8d2839026006edf",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="mosquitto",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/mosquitto",com_docker_compose_service="mosquitto",com_docker_compose_version="1.28.4",container_id="304314ef3d7b2551fdbf024c448663dddc5c8b3bac51ad5d1d54ada927cc584c",container_image="eclipse-mosquitto",container_name="mosquitto",container_status="running",container_version="2.0.14",description="Eclipse Mosquitto MQTT Broker",engine_host="rhel.nzsnet.com",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="9cf96b79c0012c180cb9a45c473eda01a3a59ebf761c40c485ca4bf5f9640a13",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="monitor_stack",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/monitor_stack",com_docker_compose_service="mimir",com_docker_compose_version="1.28.4",container_id="305c82f7ccc391f1b7c50dc3b1e83f826e57f41c5337fad8a003df33b8472b5a",container_image="grafana/mimir",container_name="mimir",container_status="running",container_version="2.3.0",engine_host="rhel.nzsnet.com",org_opencontainers_image_revision="b3f22b4",org_opencontainers_image_source="https://github.com/grafana/mimir/tree/main/cmd/mimir",org_opencontainers_image_title="mimir",server_version="20.10.18"} 4096
docker_active_anon{com_docker_compose_config_hash="bc8a41de159980309707d1dad0728bbbf3074bd06286c54f1102e6de7199fcb0",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="monitor_stack",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/opt/monitor_stack",com_docker_compose_se
```

### System info

telegraf 1.24.2 (1.24.1 also not working)

### Steps to reproduce

1.set input as above
output as above
2.
3.
...

### Expected behavior

tags in the docker_label_exclude[] section are not output in prometheus /metrics. glob patterns also does not work.

authors tag is filtered any tag with an _ seems not to be filtered.

### Actual behavior

no filtering of tags as per above
