### ISSUE TITLE
Ping Input fails when integers are provided in floating point options

### ISSUE THREAD

**Issue by jrha** [influxdata/telegraf#11945]
### Relevant telegraf.conf

```toml
[[inputs.ping]]
    count = 1
    timeout = 1
    urls = [ 
        "host01.example.org",
    ]
```

### Logs from Telegraf

```text
2022-10-05T09:58:40Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/lb.conf: error parsing ping, line 33: (ping.Ping.Timeout) cannot unmarshal TOML integer into float64
```

### System info

Telegraf 1.23.4 (git: HEAD 5b48f5da)

### Steps to reproduce

1. Put an integer in a field that expects a float (e.g. `timeout = 1` vs `timeout = 1.0`)

### Expected behavior

The plugin to cast the integer to a float and carry on.

### Actual behavior

Telegraf fails to start with the above error.

### Additional info

This seems like another instance of #9441, which was fixed in #9447.
