### ISSUE TITLE
Tail input plugin not found in Telegraf >= 1.24.0

### ISSUE THREAD

**Issue by couloum** [influxdata/telegraf#11978]
### Relevant telegraf.conf

```toml
[[inputs.tail]]
  ## files to tail.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   "/var/log/**.log"  -> recursively find all .log files in /var/log
  ##   "/var/log/*/*.log" -> find all .log files with a parent dir in /var/log
  ##   "/var/log/apache.log" -> just tail the apache log file
  ##
  ## See https://github.com/gobwas/glob for more examples
  ##
  files = ["/path/to/my/file.log"]
  ## Read file from beginning.
  from_beginning = true
  ## Whether file is a named pipe
  # pipe = false

  ## Method used to watch for file updates.  Can be either "inotify" or "poll".
  # watch_method = "inotify"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  # data_format = "influx"
```

### Logs from Telegraf

```text
E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/input-tail.conf: error parsing tail, parser not found
```

### System info

Telegraf 1.24.2-1, Ubuntu 20.04.5

### Steps to reproduce

1. Install Telegraf >= 1.24.0
2. Create a configuration using `tail` input plugin. Only specify `files` parameter with path to file to watch
3. Start Telegraf

### Expected behavior

Telegraf starts correctly

### Actual behavior

Telegraf doesn't start and display an error saying that `parser is not found`.

### Additional info

I reproduced the error with version 1.24.0 and 1.24.2.
I confirmed that the exact same configuration works correctly with version 1.23.4 of Telegraf.
