### ISSUE TITLE
Using prometheus data_format with exec results in bogus prefix

### ISSUE THREAD

**Issue by ctheune** [influxdata/telegraf#11975]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
commands = ["/root/ceph-usage.py --ceph-binary=/nix/store/7jmbg8jzv0a2pg3s0kpakw6i6l8h7xyl-ceph-sudo"]
data_format = "prometheus"
timeout = "10s"
```

### Logs from Telegraf

```text
no relevant logs IMHO
```

### System info

Telegraf 1.18.1, NixOS 21.05

### Steps to reproduce

1. Use input as above
2. curl metrics 
3.
...

### Expected behavior

Output from the executable is:

fc_ceph_df_usage_percent{crush_type="osd", crush_name="osd.16", crush_host="cartman09", crush_rack="MDF_W.0.1", crush_datacenter="dev", crush_root="default"} 35.84032

### Actual behavior

Output from telegraf on prometheus output contains a bogus prefix:

prometheus_fc_ceph_df_usage_percent{crush_datacenter="dev",crush_host="cartman09",crush_name="osd.16",crush_rack="MDF_W.0.1",crush_root="default",crush_type="osd",host="cartman02",location="dev",platform="nixos",profile="storage",resource_group="services"} 35.840562

This does not happen with other exec inputs that are using data_format json.

### Additional info

Setting name_override = "" or name_prefix = "" doesn't  help either. I think its due to: https://github.com/influxdata/telegraf/blob/master/plugins/parsers/prometheus/parser.go#L90

**Comment by powersj** [comment]
Hi,

> Output from telegraf on prometheus output contains a bogus prefix:

Would be helpful next time if you include that in your config to ensure we aren't missing any configuration settings ;)

It does appear that the prometheus_client, when using the v1 parser, will set the name based on a combination of the metric name "prometheus" + the field name; This is done [here in v1/collector.go](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/prometheus_client/v1/collector.go#L360). This is inline with the [prometheus documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus#metric-format-configuration) that says in v1 the "prometheus metric name becomes the telegraf metric name", which in this case is "prometheus".

The v2 output does not do this same manipulation because the "The prometheus metric name becomes a telegraf field key"

To reproduce I used the following config:

```toml
[[inputs.exec]]
commands = ["/usr/bin/echo fc_ceph_df_usage_percent{crush_type=\\\"osd\\\"} 35.85032"]
data_format = "prometheus"
[[outputs.prometheus_client]]
listen = ":9273"
metric_version = 1
collectors_exclude = ["gocollector", "process"]
```

I think this is effectively working as expected, thoughts?
