### ISSUE TITLE
unable to use inputs.statsd  through tcp protocol

### ISSUE THREAD

**Issue by pgeler** [influxdata/telegraf#11985]
### Relevant telegraf.conf

```toml
[[inputs.statsd]]
  ## Protocol, must be "tcp", "udp4", "udp6" or "udp" (default=udp)
  protocol = "tcp"

  ## MaxTCPConnection - applicable when protocol is set to tcp (default=250)
  max_tcp_connections = 250

  ## Enable TCP keep alive probes (default=false)
  tcp_keep_alive = false

  ## Specifies the keep-alive period for an active network connection.
  ## Only applies to TCP sockets and will be ignored if tcp_keep_alive is false.
  ## Defaults to the OS configuration.
  # tcp_keep_alive_period = "2h"

  ## Address and port to host UDP listener on
  service_address = ":8125"
```

### Logs from Telegraf

```text
Error in plugin: accept tcp [::]:8125: use of closed network connection
```

### System info

telegraf 1.24.2

### Steps to reproduce

1. enable statd input plugin
2. change proto udp -> tcp
3. start telegraf

### Expected behavior

telegraf should start and work with tcp 

### Actual behavior

telegraf is exiting with an error
