### ISSUE TITLE
agggregator stats not working

### ISSUE THREAD

**Issue by vipinvkmenon** [influxdata/telegraf#11988]
### Relevant telegraf.conf

```toml
[[aggregators.basicstats]]
  ## The period on which to flush & clear the aggregator.
  period = "1s"

  ## If true, the original metric will be dropped by the
  ## aggregator and will not get sent to the output plugins.
  drop_original = false

  ## Configures which basic stats to push as fields
  # stats = ["mean"]


[[inputs.influxdb_v2_listener]]
service_address = ":8086"



[[outputs.file]]
files = ['stdout']

```
```


### Logs from Telegraf

```text
2022-10-12T09:24:57Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"khj", Flush Interval:10s
2022-10-12T09:24:57Z I! [inputs.influxdb_v2_listener] Started HTTP listener service on :8086
cpu_load_short,host=server01,region=us-west value=1 1434055562000000000
```

### System info

telegraf 1.24, mac

### Steps to reproduce

Use the above configuration  and run telegraf

### Expected behavior

The output also has logs for the stats (mean) along with metrics emitted.

### Actual behavior

The aggregated mean is missing

### Additional info

Not sure if its a config issue, but it seems like a very simple config so I'm not sure if there would be errors in it.
