### ISSUE TITLE
Splunk serializer data_format=splunkmetric does not work in 1.23+

### ISSUE THREAD

**Issue by pgeler** [influxdata/telegraf#12010]
### Relevant telegraf.conf

```toml
[[outputs.http]]
   url = "${SPLUNK_HEC_STATSD_URL}"
   timeout = "5s"
   data_format = "splunkmetric"
   splunkmetric_hec_routing = true
   splunkmetric_multimetric = true
...
```

### Logs from Telegraf

```text
Additional info
```

### System info

Telegraf 1.23

### Steps to reproduce

1. splunk cloud + mstats index
2. send data through HTTP hec forwarder
3. failed
...

### Expected behavior

just work

### Actual behavior

does not work

### Additional info

Our current version was 1.20, after an attempt to upgrade to 1.24, Splunk `mstats`  stopped working, and `index` does not have any recent data. The research found that a new "event" field is added and causing the problem. Also found two controversial PR's #8039 and #8761, and closed issue #11500 without an explanation of how to move forward with the most recent versions. Looks like this functionality needs to have a flag to enable/disable the `event` field. @powersj thoughts?
