### ISSUE TITLE
Eventhub_Consumer Input Plugin - Unable to receive more than 15k messages on an average 

### ISSUE THREAD

**Issue by MSIT-BPSC-IOT** [influxdata/telegraf#12028]
### Relevant telegraf.conf

```toml
[agent]

  interval = "2s"
  debug = true
  quiet = false
  round_interval = true
  metric_batch_size = 500
  metric_buffer_limit = 1000
  collection_jitter = "0s"
  flush_interval = "2s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

[[inputs.internal]]
  collect_memstats = true
  [inputs.internal.tags]
    source="metrics"

[[inputs.eventhub_consumer]]
  persistence_dir = "/var/lib/eventhub_persistence"
  partition_ids = ["0"]
  data_format = "value"
  data_type = "string"
  [inputs.eventhub_consumer.tags]
    source="events"

[[inputs.eventhub_consumer]]
  persistence_dir = "/var/lib/eventhub_persistence"
  partition_ids = ["1"]
  data_format = "value"
  data_type = "string"
  [inputs.eventhub_consumer.tags]
    source="events"

[[inputs.eventhub_consumer]]
  persistence_dir = "/var/lib/eventhub_persistence"
  partition_ids = ["2"]
  data_format = "value"
  data_type = "string"
  [inputs.eventhub_consumer.tags]
    source="events"

[[inputs.eventhub_consumer]]
  persistence_dir = "/var/lib/eventhub_persistence"
  partition_ids = ["3"]
  data_format = "value"
  data_type = "string"
  [inputs.eventhub_consumer.tags]
    source="events"
```

### Logs from Telegraf

```text
Log shows it can read ~20 to 40 messages every 2 secs
```

### System info

Telegraf 1.24

### Steps to reproduce

1. Post 25k messages per minute
2. Telegraf pods throttles.

### Expected behavior

I need to process 120k messages per minute

### Actual behavior

I could process only 15k per minute

### Additional info

I have scaling issue with Eventhub_Consumer plugin. I have AKS and 8 namespaces having 1 POD each (4 Partitions per POD). Even with high end nodepool in my AKS, I can still process only 20; (Max) no matter how I alert these configurations. I could achieve 20k with the below config. Also, the **Prefetch** is not working. I tried adding “**Prefetch**” as 1000 and I did not see any difference. So, I removed it. My requirement is to process 120k events per minute. 

![image](https://user-images.githubusercontent.com/63116334/196054760-7f0033e6-8214-413e-9f47-0cfa4107016b.png)

How to scale Telegraf to process 120k per minute?
