### ISSUE TITLE
MongoDB input fails most of the time

### ISSUE THREAD

**Issue by blockloop** [influxdata/telegraf#12047]
### Relevant telegraf.conf

```toml
[[inputs.mongodb]]
  servers = ["mongodb://localhost:27017/?directConnection=true"]
  gather_cluster_status = false
  gather_perdb_stats = false
  gather_col_stats = false
  gather_top_stat = false
  disconnected_servers_behavior = "skip"
```

### Logs from Telegraf

```text
2022-10-18T17:41:25Z E! [inputs.mongodb] failed to gather data: %!w(*bsoncodec.DecodeError=&{[journaledMB dur] 0xc0005e34f0})
2022-10-18T17:41:26Z E! [inputs.mongodb] failed to gather data: %!w(*bsoncodec.DecodeError=&{[journaledMB dur] 0xc0005e34f0})
```

### System info

Telegraf 1.24.2, MongoDB v2.6.11

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

Input plugin should gather metrics

### Actual behavior

Most of the time the plugin only outputs the error

```
2022-10-18T17:41:37Z E! [inputs.mongodb] failed to gather data: %!w(*bsoncodec.DecodeError=&{[journaledMB dur] 0xc000302530})
```

and does not gather any metrics. However, sporadically it works and prints metrics. I have no idea why.
