### ISSUE TITLE
[inputs.mqtt_consumer] Error in plugin: connection lost: EOF

### ISSUE THREAD

**Issue by psxde** [influxdata/telegraf#12046]
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt.domain.com:1883"]
  topics = [
    "ecu/r35/out"
  ]
  topic_tag = "topic"
  connection_timeout = "30s"
  max_undelivered_messages = 1500
  persistent_session = true
  client_id = "telegraf_mqtt"
  username = "user"
  password = "pass"
  name_override = "mqtt"
  data_format = "json"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt.domain.com:1883"]
  username = "user"
  password = "pass"
  client_id = "telegraf_tasmota"
  topics = ["tele/+/SENSOR"]
  data_format = "json"
  name_override = "tasmota"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt.domain.com:1883"]
  username = "user"
  password = "pass"
  client_id = "telegraf_test"
  topics = ["test/sensor/#"]
  data_format = "value"
  data_type = "float"
  topic_tag = ""

[[inputs.mqtt_consumer.topic_parsing]]
  topic = "test/+/+/+"
  measurement = "measurement/_/_/_"
  tags = "_/_/sensor/_"
```

### Logs from Telegraf

```text
2022-10-18T17:15:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:15:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:15:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:16:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:16:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:16:07Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:17:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:17:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
2022-10-18T17:17:00Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
```

### System info

Telegraf 1.23.0, FreeBSD 13.1-RELEASE-p1

### Steps to reproduce

1. start mosquitto
2. start telegraf
3. send metadata to mosquitto
4. look into influx db

### Expected behavior

Metadata from mqtt is written in influxdb

### Actual behavior

Metadata of client_id telegraf_test is written in database, but either telegraf_mqtt or telegraf_tasmota is written into database. Its always the same mosquitto server. Currently telegraf_mqtt is not working since yesterday

### Additional info

mosquitto log:

1666113690: New connection from x.x.x.x:3566 on port 1883.
1666113690: New connection from x.x.x.x:18125 on port 1883.
1666113690: New client connected from x.x.x.x:3566 as telegraf_tasmota (p2, c1, k60, u'mqtt').
1666113690: New client connected from x.x.x.x:18125 as telegraf_test (p2, c1, k60, u'mqtt').
1666113691: New connection from x.x.x.x:14938 on port 1883.
1666113720: Client telegraf_mqtt closed its connection.
1666113720: Client telegraf_tasmota closed its connection.
1666113722: Client telegraf_test closed its connection.
1666113750: New connection from x.x.x.x:46840 on port 1883.
1666113750: New connection from x.x.x.x:49499 on port 1883.
1666113750: New client connected from x.x.x.x:46840 as telegraf_tasmota (p2, c1, k60, u'mqtt').
1666113750: New client connected from x.x.x.x:49499 as telegraf_test (p2, c1, k60, u'mqtt').
1666113750: New connection from x.x.x.x:55590 on port 1883.
1666113750: New client connected from x.x.x.x:55590 as telegraf_mqtt (p2, c1, k60, u'mqtt').
1666113780: Client telegraf_tasmota closed its connection.
1666113780: Client telegraf_mqtt closed its connection.
