### ISSUE TITLE
Support JSON nested in fields for JSON serializer

### ISSUE THREAD

**Issue by nicho2** [influxdata/telegraf#12070]
### Relevant telegraf.conf

```toml
# # Configuration for MQTT server to send metrics to
 [[outputs.mqtt]]
#   ## MQTT Brokers
#   ## The list of brokers should only include the hostname or IP address and the
#   ## port to the broker. This should follow the format '{host}:{port}'. For
#   ## example, "localhost:1883" or "127.0.0.1:8883".
   servers = ["localhost:1883"]
#
#   ## MQTT Topic for Producer Messages
#   ## MQTT outputs send metrics to this topic format:
#   ## <topic_prefix>/<hostname>/<pluginname>/ (e.g. prefix/web01.example.com/mem)
   topic_prefix = "system/v1/gp_telegraf/tm"
#
#   ## QoS policy for messages
#   ## The mqtt QoS policy for sending messages.
#   ## See https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.dev.doc/q029090_.htm
#   ##   0 = at most once
#   ##   1 = at least once
#   ##   2 = exactly once
#   # qos = 2
#
#   ## Keep Alive
#   ## Defines the maximum length of time that the broker and client may not
#   ## communicate. Defaults to 0 which turns the feature off.
#   ##
#   ## For version v2.0.12 and later mosquitto there is a bug
#   ## (see https://github.com/eclipse/mosquitto/issues/2117), which requires
#   ## this to be non-zero. As a reference eclipse/paho.mqtt.golang defaults to 30.
    keep_alive = 60
#
#   ## username and password to connect MQTT server.
#   # username = "telegraf"
#   # password = "metricsmetricsmetricsmetrics"
#
#   ## client ID
#   ## The unique client id to connect MQTT server. If this parameter is not set
#   ## then a random ID is generated.
#   # client_id = ""
#
#   ## Timeout for write operations. default: 5s
#   # timeout = "5s"
#
#   ## Optional TLS Config
#   # tls_ca = "/etc/telegraf/ca.pem"
#   # tls_cert = "/etc/telegraf/cert.pem"
#   # tls_key = "/etc/telegraf/key.pem"
#
#   ## Use TLS but skip chain & host verification
#   # insecure_skip_verify = false
#
#   ## When true, metrics will be sent in one MQTT message per flush. Otherwise,
#   ## metrics are written one metric per MQTT message.
#   # batch = false
#
#   ## When true, metric will have RETAIN flag set, making broker cache entries until someone
#   ## actually reads it
#   # retain = false
#
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
   data_format = "json"

 
## A [JSONata](https://jsonata.org/) transformation of the JSON in [standard-form](#examples).
  ## This allows to generate an arbitrary output form based on the metric(s). Please use
  ## multiline strings (starting and ending with three single-quotes) if needed.
  #[[outputs.mqtt.JSONata]]
	json_transformation = '''($ ~> | fields |  $each(function($v, $n){{$n: $eval($v) }} ) ~> $merge() |).$merge([fields, {"tags": tags, "timestamp": $fromMillis(timestamp*1000)}])'''
```

### Logs from Telegraf

```text
2022-10-20T13:24:29Z I! Starting Telegraf 1.24.2
2022-10-20T13:24:29Z I! Available plugins: 205 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-10-20T13:24:29Z I! Loaded inputs: mqtt_consumer
2022-10-20T13:24:29Z I! Loaded aggregators: merge
2022-10-20T13:24:29Z I! Loaded processors: pivot
2022-10-20T13:24:29Z I! Loaded outputs: mqtt
2022-10-20T13:24:29Z I! Tags enabled: host=FRL17123456
2022-10-20T13:24:29Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"FRL123456", Flush Interval:10s
2022-10-20T13:24:29Z I! [inputs.mqtt_consumer] Connected [tcp://127.0.0.1:1883]
```

### System info

Telegraf 1.24.2; windows 10

### Steps to reproduce

1.  i send topics on mqtt as define here:
```
[
    {
        "topic": "gateway/00:80:E1:0B:14:31/diagnostic/devices/F4CE36DBF3AA2794",
        "payload": {
              "shortAddress": "0000",
              "status": "online"
            }
    },
    {
        "topic": "gateway/00:80:E1:0B:14:31/diagnostic/devices/00047400001212AC",
        "payload": {
              "shortAddress": "AB1A",
              "status": "online"
            }
    },
    {
        "topic": "gateway/00:80:E1:0B:14:31/diagnostic/devices/0004740000AEFC89",
        "payload": {
              "status": "offline"
            }
    },
```
2. all topics are merge and i obtain this:
```
{
  "fields": {
    "00047400001212AC": "{\"shortAddress\": \"AB1A\", \"status\": \"online\"}",
    "0004740000AEFC89": "{\"status\": \"offline\"}",
    "F4CE36DBF3AA2794": "{\"shortAddress\": \"0000\", \"status\": \"online\"}"
  },
  "name": "3ddlmlite_diag_devices",
  "tags": {
    "device_id": "00:80:E1:0B:14:31",
    "host": "FRL17123456",
    "type": "diagnostic"
  },
  "timestamp": 1666006350
}
```

3. i want publish an unique topic as define in Expected behavior
4.  i use the json_transformation = `'''($ ~> | fields |  $each(function($v, $n){{$n: $eval($v) }} ) ~> $merge() |).$merge([fields, {"tags": tags, "timestamp": $fromMillis(timestamp*1000)}])'''`
but nothing is published.

5. if i use only : 
```
json_transformation = '''$merge([fields, {"tags": tags, "timestamp": $fromMillis(timestamp*1000)}])'''
```

i obtain the result:
```
{
  "00047400001212AC": "{\"shortAddress\": \"AB1A\", \"status\": \"online\"}",
  "0004740000AEFC89": "{\"status\": \"offline\"}",
  "F4CE36DBF3AA2794": "{\"shortAddress\": \"0000\", \"status\": \"online\"}",
  "tags": {
    "device_id": "00:80:E1:0B:14:31",
    "host": "FRL17123456",
    "type": "diagnostic"
  },
  "timestamp": "2022-10-17T11:32:30.000Z"
}
```

### Expected behavior

topic system/v1/gp_telegraf/tm/FRL17123456/3ddlmlite_diag_devices 
with payload:
```
{
  "name": "3ddlmlite_diag_devices",
  "timestamp": 1666006350,
  "tags": {
    "device_id": "00:80:E1:0B:14:31",
    "host": "FRL17123456",
    "type": "diagnostic"
  },
  "00047400001212AC": {
    "shortAddress": "AB1A",
    "status": "online"
  },
  "0004740000AEFC89": {
    "status": "offline"
  },
  "F4CE36DBF3AA2794": {
    "shortAddress": "0000",
    "status": "online"
  }
}
```

### Actual behavior

nothing send on mqtt

**Comment by powersj** [comment]
Looks like you are using `mqtt_consumer` as an input. how are you parsing the data when it first comes in?

**Comment by nicho2** [comment]
below, the input part:



[[inputs.mqtt_consumer]]
name_override = "3ddlmlite_diag_devices"
servers = ["tcp://127.0.0.1:1883"]
   ## Topics that will be subscribed to.
topics = [
		"gateway/+/diagnostic/devices/+",
   ]
	topic_tag = ""  # permet d'enlever le tag "topic" si "" car empêche le merge
	data_format = "value"
	data_type = "string" # required
	precision = "10s"		# précision du timestamp pour le merge

	[[inputs.mqtt_consumer.topic_parsing]]
        topic = "+/+/+/+/+"  # all topics with 5 segments
        tags = "_/device_id/type/_/field"
        measurement = "_/_/_/_/measurement"

	
		
[[processors.pivot]]
	tag_key = "field"
	value_key = "value"
	order = "1"


# # # # Process metrics using a Starlark script
# [[processors.starlark]]
	
	
[[aggregators.merge]]
#   ## If true, the original metric will be dropped by the
#   ## aggregator and will not get sent to the output plugins.
	drop_original = true
	period = "10s"
	#order = "2"

**Comment by powersj** [comment]
Can you turn on debugging, I am thinking there is an error that shows up during the call to Serialize the metric that only gets printed with debug turned on.

Also I am wondering if our jsonata library is too old. If I try this in the [JSONata playground](https://try.jsonata.org/) it works, but if I choose an older version, like 1.5.4 it fails on the call to `$each`. We use the [blues/jsonata-go](https://github.com/blues/jsonata-go) library, which has a single tag for v1.5.4, which I wonder if that aligns with the v1.5.4 in the jsonata version in the playground.

**Comment by nicho2** [comment]
yes, in debug mode, i have:


2022-10-24T08:56:30Z D! [aggregators.merge] Updated aggregation range [2022-10-24 10:56:30 +0200 CEST, 2022-10-24 10:56:40 +0200 CEST]
2022-10-24T08:56:33Z D! [outputs.mqtt] Could not serialize metric: function "each" takes 2 argument(s), got 1
2022-10-24T08:56:33Z D! [outputs.mqtt] Wrote batch of 1 metrics in 558.4µs
2022-10-24T08:56:33Z D! [outputs.mqtt] Buffer fullness: 0 / 10000 metrics
2022-10-24T08:56:40Z D! [aggregators.merge] Updated aggregation range [2022-10-24 10:56:40 +0200 CEST, 2022-10-24 10:56:50 +0200 CEST]
2022-10-24T08:56:43Z D! [outputs.mqtt] Buffer fullness: 0 / 10000 metrics

**Comment by nicho2** [comment]
I have tried the go file below with GoLand 2022.2.4 intelliJ and that seems OK

my result is:

map[fields:map[00047400001212AC:{"shortAddress": "AB1A", "status": "online"} 0004740000AEFC89:{"status": "offline"} F4CE36DBF3AA2794:{"shortAddress": "0000", "status": "online"}] name:3ddlmlite_diag_devices tags:map[device_id:00:80:E1:0B:14:31 host:FRL17172 type:diagnostic] timestamp:1.66600635e+09]



[test.txt](https://github.com/influxdata/telegraf/files/9851324/test.txt)

**Comment by powersj** [comment]
> I have modify to have two arguments

Ah good, I'm glad the error message helped a bit

> this function was add in the version: 1.6.1

aaah ok. I did try to look for a new library and did not find anything. I even saw you filed an upstream issue as well, thank you for that!

At this point I'm not sure what more we can do outside documenting the version in use by Telegraf. Thoughts?

**Comment by nicho2** [comment]
hello,
I try an another script jsonata tested in https://try.jsonata.org/ with version 1.5.4

(
$to_json := function($x){(
 $list := $replace($x,"\"","");
 $list := $replace($list,"{","");
 $list := $replace($list,"}","");
 $list := $split($list, ",");
$res := $map($list, function($x){ (
    $val := $replace($x," ","");
    $val := $split($val, ":");
    {$val[0]:$val[1]}
        )}  );
$merge($res)        
)};

($ ~> | fields |  $each($,function($v, $n){{$n: $to_json($v) }} ) ~> $merge() |)
)


i put that in my conf, i restart the service and send topics but now the service stop with no error


2022-10-26T05:34:20Z I! Starting Telegraf 1.24.2
2022-10-26T05:34:20Z I! Available plugins: 205 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-10-26T05:34:20Z I! Loaded inputs: mqtt_consumer
2022-10-26T05:34:20Z I! Loaded aggregators: merge
2022-10-26T05:34:20Z I! Loaded processors: pivot
2022-10-26T05:34:20Z I! Loaded outputs: mqtt
2022-10-26T05:34:20Z I! Tags enabled: host=FRL17172
2022-10-26T05:34:20Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"FRL17172", Flush Interval:10s
2022-10-26T05:34:20Z D! [agent] Initializing plugins
2022-10-26T05:34:20Z D! [agent] Connecting outputs
2022-10-26T05:34:20Z D! [agent] Attempting connection to [outputs.mqtt]
2022-10-26T05:34:20Z D! [outputs.mqtt] registered mqtt broker: tcp://localhost:1883
2022-10-26T05:34:20Z D! [agent] Successfully connected to outputs.mqtt
2022-10-26T05:34:20Z D! [agent] Starting service inputs
2022-10-26T05:34:20Z I! [inputs.mqtt_consumer] Connected [tcp://127.0.0.1:1883]
2022-10-26T05:34:20Z D! [aggregators.merge] Updated aggregation range [2022-10-26 07:34:20 +0200 CEST, 2022-10-26 07:34:30 +0200 CEST]
2022-10-26T05:34:30Z D! [aggregators.merge] Updated aggregation range [2022-10-26 07:34:30 +0200 CEST, 2022-10-26 07:34:40 +0200 CEST]

and no more things and the service is stopped

**Comment by nicho2** [comment]
is it possible to propose an another alternative as starlark to transform the output?

My first problem is to keep a value (payload) as an json object.

Salutations.

**Comment by powersj** [comment]
> and no more things and the service is stopped

When you say stopped, you mean telegraf flushes the buffer and completely stops running or no further output shows up?

> is it possible to propose an another alternative as starlark to transform the output?

That is probably an option, I think the [json starlark example](https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/testdata/json.star) does something very similar to what you are after.

**Comment by nicho2** [comment]
> When you say stopped, you mean telegraf flushes the buffer and completely stops running or no further output shows up?
   telegraf flushes the buffer and completely stops running
 
> That is probably an option, I think the [json starlark example](https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/testdata/json.star) does something very similar to what you are after.

No in fact , i want transform the json in the output


{
  "00047400001212AC": "{\"shortAddress\": \"AB1A\", \"status\": \"online\"}",
  ...
  "timestamp": "2022-10-17T11:32:30.000Z"
}

to:
{
   "timestamp": 1666006350,
   "00047400001212AC": {
                             "shortAddress": "AB1A",
                             "status": "online" },
 ....
}

so I must use starlark in the output plugin as :



# # Configuration for MQTT server to send metrics to
 [[outputs.mqtt]]
   servers = ["localhost:1883"]
   topic_prefix = "system/v1/gp_telegraf/tm"

   data_format = "json_with_starlark"

load("json.star", "json")
# loads json.encode(), json.decode(), json.indent()

def apply(metric):
   for k,v in metric.fields.items():
        metric.fields[k] = json.decode(v)
   return metric


In your example the json in "value" is split in two value, i want keep the whole object:

json value="{\"label\": \"hero\", \"count\": 14}" 1465839830100400201
to
value={"label": "hero", "count": 14}
==>
{
 "fields" : {
           value={"label": "hero", "count": 14}
               }
   "timestamp": 1465839830100400201
}

**Comment by srebhan** [comment]
We cannot handle JSON nested in fields, so reopening this as feature request.

**Comment by srebhan** [comment]
@nicho2 can you please test the binary built in #12260 (once it's finished)!? With your input data I get
```json
{
  "00047400001212AC": {
    "shortAddress": "AB1A",
    "status": "online"
  },
  "0004740000AEFC89": {
    "status": "offline"
  },
  "F4CE36DBF3AA2794": {
    "shortAddress": "0000",
    "status": "online"
  },
  "tags": {
    "device_id": "00:80:E1:0B:14:31",
    "host": "FRL17123456",
    "type": "diagnostic"
  },
  "timestamp": "2022-10-17T11:32:30.000Z"
}
```
with the following config
```toml
[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
  json_nested_fields_include = ["*"]
  json_transformation = '''$merge([fields, {"tags": tags, "timestamp": $fromMillis(timestamp*1000)}])'''
```
