### ISSUE TITLE
processors.parser changes measurement name to 'parser'

### ISSUE THREAD

**Issue by thomas725** [influxdata/telegraf#12115]
### Relevant telegraf.conf

```toml
[[inputs.file]]
  files = ["/test/test.txt"]
  data_format = "value"
  data_type = "string"

[[processors.parser]]
  namepass = ["file"]
  parse_fields = ["value"]
  drop_original = false
  merge = "override"
  data_format = "value"
  data_type = "float"

[[outputs.file]]
  files = ["stdout"]
```

### Logs from Telegraf

```text
Telegraf 1.23.4:
file value=7.2 1664873970000000000

Telegraf 1.24.2:
parser value=7.2 1664892267000000000
```

### Steps to reproduce

Use the [[processors.parser]] as shown in the example above or as reported in one of links given in the "Additional info" block.

### Expected behavior

like Telegraf 1.23.4 does: keep the measurement name of the input.

### Actual behavior

Measurement name is changed to 'parser'.
The field is dropped from the original measurement, even with setting `drop_original = false`.

### Additional info

The same issue get's talked about behind these 3 links:
* https://community.influxdata.com/t/parser-processor-change-measurement-name-to-parser/26984
* https://community.influxdata.com/t/single-mqtt-consumer-for-int-float-string/27137
* https://influxcommunity.slack.com/archives/CH99HUH8V/p1666794045416509

I'm a new user of InfluxDB & Telegraf, and have no idea how to actually switch to an older Telegraf version. I've copied the sample and it's output from this issue:
https://github.com/influxdata/telegraf/issues/11921
