### ISSUE TITLE
env variables get only loaded when starting telegraf with systemd

### ISSUE THREAD

**Issue by cschra** [influxdata/telegraf#12123]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]
  alias = "KAFKA_IN"
  brokers = ["${KAFKA_BROKER}"]
  topics = ["${KAFKA_TOPIC}"]
  consumer_group = "telegraf_nmsprime"
  insecure_skip_verify = ${KAFKA_SSL_SKIP_VERIFY}
  data_format = "json_v2"
```

### Logs from Telegraf

```text
2022-10-28T10:22:05Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.d/kafka.conf: Error parsing data: line 6: invalid TOML syntax
```

### System info

Telegraf 1.24.2, CentOS 7, installed via rpm

### Steps to reproduce

1. systemctl start telegraf -> no errors
2. telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --debug -> above error appears

### Expected behavior

env variables should be loaded no matter if telegraf is started directly oder as a service

### Actual behavior

it seems to me that the environment variables from `/etc/default/telegraf` get not loaded when running telegraf directly on cli but when starting the service it does so correctly...
