### ISSUE TITLE
directory_monitor plugin complaining about invalid cross-device link

### ISSUE THREAD

**Issue by dirk-ecker** [influxdata/telegraf#12121]
### Relevant telegraf.conf

```toml
# reads data from directory
[[inputs.directory_monitor]]
  directory = "/data"
  files_to_monitor = ["A70084_*"]
  finished_directory = "/data-finished"
  error_directory = "/data-error"
  parse_method = "at-once"
  data_format = "csv"
  csv_header_row_count = 3
  csv_column_names = ["No","Time","1:Proben","2:cm","3:�C:0","4:uS/cm:(do.)","5:pH:(do.)","6:pH mV:(do.)","7:NOmg/l:(do.)","8:Clmg/l:(do.)","9:NTU %:(do.)","10:cm","HK-Bat:V","HK-Temp:oC"]
  csv_column_types = ["int","float","float","float","float","float","float","float","float","float","float","float","float","float"]
  csv_skip_rows = 0
  csv_metadata_rows = 0
  csv_metadata_separators = [":", "="]
  csv_metadata_trim_set = ""
  csv_skip_columns = 0
  csv_delimiter = ","
  csv_comment = "("
  csv_trim_space = true
  csv_tag_columns = []
  csv_measurement_column = ""
  csv_timestamp_column = "Time"
  csv_timestamp_format = "02.01.2006 15:04:05"
  csv_timezone = ""
  csv_skip_values = []
  csv_skip_errors = false

# additional receiver of processed data (node-receiver-example)
# [[outputs.http]]
#   url = "http://134.94.56.177:9086/api"
#   method = "POST"
#   data_format = "json"
#   headers = { "Content-Type" = "application/json" }

# output to console
# [[outputs.file]]
#   files = ["stdout"]
#   data_format = "json"
#   json_timestamp_units = "1s"

# standard output influxdb for the raw data
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "8_bpyugbaAwB_nXdBOiwnMpyawkV2hQ6IAm8MFqKXoHh8NWGGjH6pR5IdTIY5wq1WKup1I5BMHmIF889hjruIQ=="
  organization = "ibg3"
  bucket = "rawdata"
```

### Logs from Telegraf

```text
telegraf_1  | 2022-10-28T06:52:20Z E! [inputs.directory_monitor] Error while moving file '/data/A70084_20220101050342.asc' to another directory. Error: rename /data/A70084_20220101050342.asc /data-finished/A70084_20220101050342.asc: invalid cross-device link
telegraf_1  | 2022-10-28T06:52:30Z E! [inputs.directory_monitor] Error while moving file '/data/A70084_20220101050342.asc' to another directory. Error: rename /data/A70084_20220101050342.asc /data-finished/A70084_20220101050342.asc: invalid cross-device link
telegraf_1  | 2022-10-28T06:52:40Z E! [inputs.directory_monitor] Error while moving file '/data/A70084_20220101050342.asc' to another directory. Error: rename /data/A70084_20220101050342.asc /data-finished/A70084_20220101050342.asc: invalid cross-device link
telegraf_1  | 2022-10-28T06:52:50Z E! [inputs.directory_monitor] Error while moving file '/data/A70084_20220101050342.asc' to another directory. Error: rename /data/A70084_20220101050342.asc /data-finished/A70084_20220101050342.asc: invalid cross-device link
telegraf_1  | 2022-10-28T06:53:00Z E! [inputs.directory_monitor] Error while moving file '/data/A70084_20220101050342.asc' to another directory. Error: rename /data/A70084_20220101050342.asc /data-finished/A70084_20220101050342.asc: invalid cross-device link
telegraf_1  | 2022-10-28T06:53:10Z E! [inputs.directory_monitor] Error while moving file '/data/A70084_20220101050342.asc' to another directory. Error: rename /data/A70084_20220101050342.asc /data-finished/A70084_20220101050342.asc: invalid cross-device link
```

### System info

latest Telegraf others not relevant

### Docker

version: '3.6'
services:

  telegraf:
    image: telegraf:latest
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - ./telegraf/data/:/data/
    - ./telegraf/data-finished/:/data-finished/
    - ./telegraf/data-error/:/data-error/
    networks:
    - default
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
     - '127.0.0.1:8125:8125/udp'

  influxdb:
    image: influxdb:latest
    env_file: configuration.env
    networks:
    - default
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: configuration.env
    links:
      - influxdb
    ports:
      - '127.0.0.1:3000:3000'

volumes:
  influxdb_data: {}

networks:
  default:

### Steps to reproduce

Simply docker-compose up and the error is shown.

### Expected behavior

The file gets moved.

### Actual behavior

The file gets not moved, instead we got an error.

### Additional info

The problem is that it is not possible to move a file between different devices.
The solution is to use copy/delete.
