### ISSUE TITLE
Socket listener only processes first 1 or 2 batches of metrics with errors

### ISSUE THREAD

**Issue by 7Hazard** [influxdata/telegraf#12176]
### Relevant telegraf.conf

```toml
[agent]
    debug = true
    logfile = ""
    interval = "10s"
    round_interval = true
    # metric_batch_size = 1000
    metric_buffer_limit = 50000
    # collection_jitter = "0s"
    # flush_interval = "10s"
    # flush_jitter = "0s"
    # precision = ""
    # hostname = ""
    # omit_hostname = false

[[outputs.influxdb_v2]]
    urls = ["http://localhost:8086"]
    token = "$TELEGRAF_INFLUX_TOKEN"
    organization = "devops"
    bucket = "devops"

[[outputs.file]]
    data_format = "influx"
    files = ["stdout"]

[[inputs.socket_listener]]
    service_address = "udp://:25826"

    ## Data format to consume.
    ## Each data format has its own unique set of configuration options, read
    ## more about them here:
    ##   https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
    data_format = "collectd"

    ## Authentication file for cryptographic security levels
    #   collectd_auth_file = "/etc/collectd/auth_file"
    ## One of none (default), sign, or encrypt
    #   collectd_security_level = "encrypt"
    collectd_security_level = "none"
    ## Path of to TypesDB specifications
    collectd_typesdb = ["/usr/share/collectd/types.db"]

    ## Multi-value plugins can be handled two ways.
    ## "split" will parse and store the multi-value plugin data into separate measurements
    ## "join" will parse and store the multi-value plugin as a single multi-value measurement.
    ## "split" is the default behavior for backward compatibility with previous versions of influxdb.
    collectd_parse_multivalue = "split"
```

### Logs from Telegraf
https://gist.github.com/7Hazard/c3e7b49b8d2981cb99a6b8a0cc9e3238

### System info

Docker Image - telegraf:1.24-alpine

### Docker

FROM telegraf:1.24-alpine

COPY telegraf.conf /etc/telegraf/telegraf.conf
COPY collectd-types.db /usr/share/collectd/types.db

### Steps to reproduce

These collectd metrics are forwarded from GitHub Enterprise to Telegraf.

### Expected behavior

That metrics are continually sent to InfluxDB, not just during the first batches of Telegraf's program life.

### Actual behavior

The first batches of metrics that are received, are processed with some errors and sent to InfluxDB successfully. But later on, it does no longer send any metrics to InfluxDB.

### Additional info

Might be related to https://github.com/influxdata/telegraf/issues/5858
