### ISSUE TITLE
cloudwatch input plugin config example with multiple namespaces

### ISSUE THREAD

**Issue by atartareanu** [influxdata/telegraf#12172]
### Use Case

Hello
Thank you for making this possible: configure multiple namespaces in telegraf cloudwatch input
https://github.com/influxdata/telegraf/pull/9386

However there is no concrete example how to configure this, especially for the three of metrics and dimensions. I have tried multiple combinations and some do not make sense, but still work  like:

namespaces = ["AWS/Billing", "AWS/ECS"]
    
	[[inputs.cloudwatch.metrics]]
	names = ["MemoryUtilization", "CPUUtilization"]
	  
	[[inputs.cloudwatch.metrics.dimensions]]
	name = "ServiceName"
    value = "*"
	
	[[inputs.cloudwatch.metrics.dimensions]]
	name = "ClusterName"
    value = "*"
	
	[[inputs.cloudwatch.metrics]]
	names = ["EstimatedCharges"]
	  
	[[inputs.cloudwatch.metrics.dimensions]]
	name = "ServiceName"
    value = "*"
	
	[[inputs.cloudwatch.metrics.dimensions]]
	name = "Currency"
    value = "*"
	
	[[inputs.cloudwatch.metrics]]
	names = ["EstimatedCharges"]
	
	[[inputs.cloudwatch.metrics.dimensions]]
	name = "Currency"
    value = "USD"

so I put AWS/Billing first in the namespaces and AWS/ECS second, but the associated metrics are reversed, however it's the only combination that works, but where is the logic ?

Also when trying to add another namespace, e.g. , "AWS/ApplicationELB" the previous config does not work, I will only get data for a single namespace.

Can you please provide an example of configuration with 3 namespaces + random metrics and dimensions.

Thank you.

### Expected behavior

The documentation/config example should contain configuration for multiple namespaces

### Actual behavior

there is no logic on how this works. we want to understand and make it better.

**Comment by powersj** [comment]
Hi,

This sounds more like a support request, that would be better asked in Slack or on our community forums.

Can you show your full cloudwatch config as well as logs, please? I ask because you have one "namespace" option that isn't even in the cloudwatch plugin section and it helps to not hide any config options from us if we are trying to support you.

It sounds like you are doing the right thing, but running into actual issues, as such showing your logs would really help us understand what you are seeing, rather than needing to guess.

Let's try with a single namespace and the three metrics:

```toml
[[inputs.cloudwatch]]
  <add your auth items>
  <are there any other options outside of auth you are using, if so please let us know>
  namespaces = ["AWS/Billing"]

  [[inputs.cloudwatch.metrics]]
    names = ["MemoryUtilization", "CPUUtilization"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "ServiceName"
      value = "*"
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "ClusterName"
      value = "*"

  [[inputs.cloudwatch.metrics]]
    names = ["EstimatedCharges"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "ServiceName"
      value = "*"
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "Currency"
      value = "*"

  [[inputs.cloudwatch.metrics]]
    names = ["EstimatedCharges"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "Currency"
      value = "USD"
```

Does that work? If so, great, try the other namespace by itself. Does that work?

If this does not work, then remove metrics one at a time.
