### ISSUE TITLE
undefined but requested input: google_cloud_storage

### ISSUE THREAD

**Issue by darjisanket** [influxdata/telegraf#12200]
### Relevant telegraf.conf

```toml
[[inputs.google_cloud_storage]]
      bucket = "my-bucket"
      offset_key = "offset_key"
      objects_per_iteration = 10
      data_format = "influx"
      credentials_file = "path/to/my/creds.json"
```

### Logs from Telegraf

```text
I! Using config file: /etc/telegraf/telegraf.conf
[telegraf] Error running agent: error loading config file /etc/telegraf/telegraf.conf: error parsing google_cloud_storage, undefined but requested input: google_cloud_storage
```

### System info

telegraf:1.24.3

### Docker

FROM telegraf:1.24.3-alpine

### Steps to reproduce

1. apply input plugin
.

### Expected behavior

telegraf not starting

### Actual behavior

should start and give metrics for gcs
