### ISSUE TITLE
Telegraf abandoned subscription for Kafka Consumer

### ISSUE THREAD

**Issue by pratikdas44** [influxdata/telegraf#12210]
### Relevant telegraf.conf

```toml
[agent]
metric_batch_size = 10000
metric_buffer_limit = 70000
round_interval = true
# metric_buffer_limit = 40000
debug = true

[[inputs.kafka_consumer]]
  brokers = ["provided"]
  topics = ["provided"]
  offset = "newest"
  #balance_strategy = "roundrobin"
  consumer_group = "svt_new_consumer3"
  max_processing_time = "6000ms"
  max_message_len = 1000000
  max_undelivered_messages = 2000
  ## Data format to consume.
  data_format = "json"
  json_time_key = "beginTime"
  json_time_format = "unix"
  tag_keys = ["provided"]
  json_string_fields = ["provided"]
  name_override = "gnb_om"
  interval = "5m"
  
[[processors.starlark]]
  order = 2
  ## The Starlark source can be set as a string in this configuration file, or
  ## by referencing a file containing the script.  Only one source or script
  ## should be set at once.

  ## Source of the Starlark script.
  source = '''
def apply(metric):
  gnbid = metric.tags['GNBID']
  setup_name = metric.tags['setup']
  k = metric.tags['name']
  val = k.split("_",2)[1] 
  vale = k.split("_",2)[2]
  val_cell=''
  if(val.find("cellId") != -1 and val.find("ruInstanceId") != -1):
    val_cell = val.split(",")
    val_cell_one = val_cell[0]
    val_ru_one = val_cell[1]
    val_cell_two = val_cell_one.split("=")[1]
    val_ru_two = val_ru_one.split("=")[1]
    metric.tags["cell"] = str(val_cell_two)
    metric.tags["ruId"] = str(val_ru_two)
  elif(val.find("cellId") != -1):
    val_cell = val.split("=")[1]
    # print(val_cell)
    metric.tags["cell"] = str(val_cell)
  elif(val.find("ruInstanceId") != -1):
    val_cell = val.split("=")[1]
    metric.tags["ruId"] = str(val_cell)
  else:
    metric.tags["cell"] = str(val)
  metric.fields[str(vale)] = metric.fields['value']
  metric.tags["FriendlyName"] = str(setup_name) + "_" + str(gnbid)
  metric.fields.pop('value')
  metric.tags.pop('name')
  # print(metric)
  return metric
'''

[[processors.converter]]
  order = 5
  [processors.converter.fields]
    integer = ["*"]
    tags = ["provided"]

[[processors.regex]]
  order = 4
  [[processors.regex.tags]]
      key = "VNFID"
      pattern = "(\\w+)(du|cucp|cuup).*"
      replacement = "${1}"
      result_key = "cluster_id"


[[processors.strings]]
  order = 3
  [[processors.strings.replace]]
    field_key = "*"
    old = "."
    new = "_"

[[processors.unpivot]]
  order = 1
  tag_key = "name"
  value_key = "value"
```

### Logs from Telegraf

```text
client/metadata fetching metadata for all topics from broker url
2022-11-09T08:50:19Z D! [sarama] consumer/broker/2 abandoned subscription to topicname/0 because consuming was taking too long
```

### System info

Telegraf - 1.23.3

### Steps to reproduce

1. Use the telegraf configuration for kafka consumer
2.
3.
...

### Expected behavior

Seeing message Abandoned subscription to Kafka topic, even after providing "max_processing_time"

### Actual behavior

Telegraf kafka consumer should be working properly. 

### Additional info

I am getting messages every 5 mins. Every time, due to the current processor plugins I am generating 60-70k metrics. This issue is happening only for some topics having more volume of data than others, and this is occurring once in every few hours but that is not fixed, sometimes it's in the next 3 hours or the next 24 hours.
