### ISSUE TITLE
Null delimiter cannot be used

### ISSUE THREAD

**Issue by Meceron** [influxdata/telegraf#12243]
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
## Topics that will be subscribed to.
  topics = [
    "+/+/measurements"
  ]
  data_format = "csv"
  csv_header_row_count = 0
  csv_column_names = ["Timestamp","Temp1","Temp2","Temp3","Temp4","Temp5","Temp6","Temp7","Temp8","Temp9","Temp10","Temp11","Temp12","Temp13","Freq1","Vibr1","Vibr2"]
  csv_column_types = ["string","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float"]
  csv_delimiter = "\u0000"
  csv_comment = "#"
```

### Logs from Telegraf

```text
telegraf   | 2022-11-15T09:44:09Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf   | 2022-11-15T09:44:09Z I! Starting Telegraf 1.24.2
telegraf   | 2022-11-15T09:44:09Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
telegraf   | 2022-11-15T09:44:09Z I! Loaded inputs: mqtt_consumer
telegraf   | 2022-11-15T09:44:09Z I! Loaded aggregators:
telegraf   | 2022-11-15T09:44:09Z I! Loaded processors:
telegraf   | 2022-11-15T09:44:09Z I! Loaded outputs: influxdb_v2
telegraf   | 2022-11-15T09:44:09Z I! Tags enabled: host=localhost
telegraf   | 2022-11-15T09:44:09Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"localhost", Flush Interval:10s
telegraf   | 2022-11-15T09:44:09Z D! [agent] Initializing plugins
telegraf   | 2022-11-15T09:44:09Z D! [agent] Connecting outputs
telegraf   | 2022-11-15T09:44:09Z D! [agent] Attempting connection to [outputs.influxdb_v2]
telegraf   | 2022-11-15T09:44:09Z D! [agent] Successfully connected to outputs.influxdb_v2
telegraf   | 2022-11-15T09:44:09Z D! [agent] Starting service inputs
telegraf   | 2022-11-15T09:44:09Z I! [inputs.mqtt_consumer] Connected [tcp://mosquitto:1883]
telegraf   | 2022-11-15T09:44:19Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf   | 2022-11-15T09:44:27Z E! [inputs.mqtt_consumer] Error in plugin: csv: invalid field or comment delimiter
telegraf   | 2022-11-15T09:44:28Z E! [inputs.mqtt_consumer] Error in plugin: csv: invalid field or comment delimiter
telegraf   | 2022-11-15T09:44:29Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf   | 2022-11-15T09:44:29Z E! [inputs.mqtt_consumer] Error in plugin: csv: invalid field or comment delimiter
telegraf   | 2022-11-15T09:44:30Z E! [inputs.mqtt_consumer] Error in plugin: csv: invalid field or comment delimiter
telegraf   | 2022-11-15T09:44:31Z E! [inputs.mqtt_consumer] Error in plugin: csv: invalid field or comment delimiter
```

### System info

Telegraf 1.24.2 (telegraf:lastest image)

### Docker

Docker 20.10.20

### Steps to reproduce

1. Set up config to null delimiters
2. Start up env
3. send csv data separated with  "\u000"
...

### Expected behavior

Like its works with tab ("\u0009"), data parsed and send to influx

### Actual behavior

Throw error : "Error in plugin: csv: invalid field or comment delimiter" 

### Additional info

The device setting cannot be changed , it's sending line data with "\u0000"., one line per cycle, without header.

Thank for your help.
