### ISSUE TITLE
telegraf: Error running agent, plugin inputs.http - configuration specified the fields ["tag_keys"], but they weren't used

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [influxdata/telegraf#12265]
### Relevant telegraf.conf

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  debug = true
  quiet = false
  logtarget = "stderr"
  hostname = ""
  omit_hostname = false
[[outputs.influxdb_v2]]
   urls = ["http://192.168.x.x:8086"]
   token = "xxxxxxxxxxxxxxxxxxxxx-yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy=="
   organization = "home"
   bucket = "telegraf"
[[inputs.http]]
  urls = [
    "http://192.168.x.y:zzzz/custom_metrics"
  ]
  method = "GET"
  timeout = "5s"
   data_format = "influx"
   name_override = "mycustommetrics"
   tag_keys = [
    "mycustommetrics",
   ]
```

### Logs from Telegraf

```text
docker logs telegraf-telegraf-1
2022-11-21T17:13:12Z I! Using config file: /etc/telegraf/telegraf.conf
2022-11-21T17:13:12Z E! [telegraf] Error running agent: error loading config file /etc/telegraf/telegraf.conf: plugin inputs.http: line 4510: configuration specified the fields ["tag_keys"], but they weren't used
```

### System info

Ubuntu 22.04.1 LTS, docker 20.10.17, telegraf 1.24.3

### Docker

```
version: '3'
services:
  telegraf:
    image: telegraf
    restart: always
    volumes:
      # Mount for telegraf config
      - /root/telegraf/mytelegraf.conf:/etc/telegraf/telegraf.conf
    environment: 
      - DOCKER_INFLUXDB_INIT_ORG=home
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xxxxxxxxxxxxxxxxxxxxx-yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy==

```

### Steps to reproduce

1. docker compose up 
(using portainer though)

### Expected behavior

no occurence of error "configuration specified the fields ["tag_keys"], but they weren't used"

### Actual behavior

- image exiting with error from log file
- image restarting over and over due to chosen startup mechanism: docker compose / portainer

### Additional info

The error occurred after an update of the telegraf docker image to version 1.24.3
