### ISSUE TITLE
Agent ignores DNS settings, tries Google DNS instead

### ISSUE THREAD

**Issue by giddyhup** [influxdata/telegraf#12263]
### Relevant telegraf.conf

```toml
[agent]
  interval = "20s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
```

### Logs from Telegraf

```text
Nov 19 10:32:52 REDACTEDSOURCEHOST telegraf[491]: 2022-11-19T09:32:52Z E! [agent] Error writing to outputs.influxdb_v2: Post "http://REDACTEDHOST:8086/api/v2/write?bucket=pribuck&org=REDACTEDORG": dial tcp: lookup REDACTEDHOST on 8.8.8.8:53: dial udp 8.8.8.8:53: connect: network is unreachable
```

### System info

 Telegraf 1.22.1, Raspbian 10 (buster), local DNS set via /etc/resolv.conf

### Steps to reproduce

1. High wifi latency
2. Local InfluxDB slow/hard to reach
3.
...

### Expected behavior

Use system DNS setting

### Actual behavior

Google DNS is queried (which is blocked in my network)

### Additional info

Nowhere on the host is 8.8.8.8 set as DNS. Telegraf ping plugin, where it seems to be a possible config entry, is not configured or used.  

Google DNS should not be hardcoded. Actually, integrating/relying on Google service and contacting them without user/operator consent can invite a lot of privacy issues (cf. current discussions about Google Fonts).
