### ISSUE TITLE
Telegraf output plugin for postgresql 

### ISSUE THREAD

**Issue by gssprakash** [influxdata/telegraf#12277]
### Relevant telegraf.conf

```toml
[[outputs.postgresql]]
  ## Specify connection address via the standard libpq connection string:
     host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=xxxxx
```

### Logs from Telegraf

```text
2022-11-24T05:09:46Z E! [telegraf] Error running agent: Error loading config file csvtelegraf.conf: Error parsing data: line 386: invalid TOML syntax
```

### System info

telegraf 1.24.2  on windows 11 

### Steps to reproduce

1. Just add the output plugin postgresql  with [outputs.postgresql]
2. enter the line host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=anydb
3. telegraf throws TOML error 
...

### Expected behavior

No  TOML error as the libpq  syntax is valid  and it is working  fine when  tried to connect  directly using psql . It seems  telegraf is unable to find the right parser for the output plugin of postgresql 

### Actual behavior

telegraf  throwing  TOML error  as invalid TOML syntax

**Comment by srebhan** [comment]
I'm pretty sure your line `host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=xxxxx` is the value for the `connection` option. Have you tried
```toml
[[outputs.postgresql]]
  ## Specify connection address via the standard libpq connection string:
  connection="host=localhost port=5432 user=postgres password=xxxxx sslmode=disable dbname=xxxxx"
```

Anyway, as the error message suggests, the config part you sent is _not_ vaild TOML!
