### ISSUE TITLE
[inputs.sql] measurement_column set but type assertion failed

### ISSUE THREAD

**Issue by jinuxx** [influxdata/telegraf#12322]
### Relevant telegraf.conf

```toml
[[inputs.sql.query]]
  query="SELECT tag_one as tag_one,tag_two,int64_one,int64_two,`timestamp` FROM metric_one"
  measurement_column = "tag_one"
  tag_columns_include = ["int64_one"]
  field_columns_string = ["tag_two"]
  field_columns_include = ["int64_two"]
```

### Logs from Telegraf

```text
Error in plugin: measurement column type "[]uint8" unsupported
```

### System info

telegraf 1.24.3 ubuntu 18.04 docker 20.10.17

### Steps to reproduce

docker run -d --name=sql -v $PWD/telegraf-sql.conf:/etc/telegraf/telegraf.conf:ro telegraf:1.24.3-alpine

### Expected behavior

Telegraf should add data to influxdb

### Actual behavior

Error in plugin: measurement column type "[]uint8" unsupported
