### ISSUE TITLE
I want to set a custom tag in [[inputs.http.json_v2.object]]

### ISSUE THREAD

**Issue by virtualdreams** [influxdata/telegraf#12325]
### Relevant telegraf.conf

```toml
[[inputs.http]]
  urls = [
    "http://192.168.0.123/status"
  ]
  interval = "4s"
  timeout = "1s"
  data_format = "json_v2"
  [[inputs.http.json_v2]]
    measurement_name = "shelly 3em"
    timestamp_format = "unix"

    [[inputs.http.json_v2.object]]
      path = "emeters.0"
      disable_prepend_keys = true
      tag = "my custom tag"
    [[inputs.http.json_v2.object]]
      path = "emeters.1"
      disable_prepend_keys = true
    [[inputs.http.json_v2.object]]
      path = "emeters.2"
      disable_prepend_keys = true
```

### Logs from Telegraf

```text
2022-12-02T15:04:03Z I! Tags enabled:
2022-12-02T15:04:03Z E! [inputs.http] Error in plugin: [url=http://192.168.0.22/status]: instantiating parser failed: line 345: (json_v2.Object.TagPaths) cannot unmarshal TOML string into []json_v2.DataSet
```

### System info

1.12.4

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

I want the curcuit=# in every line.

```
2022-12-02T15:06:12Z I! Tags enabled:
> shelly\ 3em,circuit=0,url=http://192.168.0.22/status current=1.43,is_valid=true,pf=0.85,power=281.13,total=8618.4,total_returned=0,voltage=234.04 1669993572000000000
> shelly\ 3em,circuit=1,url=http://192.168.0.22/status current=0.29,is_valid=true,pf=0.45,power=30.29,total=1714.9,total_returned=0,voltage=234.22 1669993572000000000
> shelly\ 3em,circuit=2,url=http://192.168.0.22/status current=10.35,is_valid=true,pf=0.94,power=2272.95,total=2138.7,total_returned=0,voltage=234.61 1669993572000000000
```

### Actual behavior

```
2022-12-02T15:06:12Z I! Tags enabled:
> shelly\ 3em,url=http://192.168.0.22/status current=1.43,is_valid=true,pf=0.85,power=281.13,total=8618.4,total_returned=0,voltage=234.04 1669993572000000000
> shelly\ 3em,url=http://192.168.0.22/status current=0.29,is_valid=true,pf=0.45,power=30.29,total=1714.9,total_returned=0,voltage=234.22 1669993572000000000
> shelly\ 3em,url=http://192.168.0.22/status current=10.35,is_valid=true,pf=0.94,power=2272.95,total=2138.7,total_returned=0,voltage=234.61 1669993572000000000
```

### Additional info

I want to set a manual tag in an [[inputs.http.json_v2.object]] that does not exist as a key. How can I do this?

```json
{
   "wifi_sta":{
      "connected":true,
      "ssid":"xxxxxx",
      "ip":"192.168.0.123",
      "rssi":-76
   },
   "cloud":{
      "enabled":false,
      "connected":false
   },
   "mqtt":{
      "connected":false
   },
   "time":"16:09",
   "unixtime":1669993777,
   "serial":11363,
   "has_update":false,
   "mac":"C45BBE5527B7",
   "cfg_changed_cnt":0,
   "actions_stats":{
      "skipped":0
   },
   "relays":[
      {
         "ison":false,
         "has_timer":false,
         "timer_started":0,
         "timer_duration":0,
         "timer_remaining":0,
         "overpower":false,
         "is_valid":true,
         "source":"http"
      }
   ],
   "emeters":[
      {
         "power":364.48,
         "pf":0.88,
         "current":1.76,
         "voltage":232.23,
         "is_valid":true,
         "total":8635.9,
         "total_returned":0.0
      },
      {
         "power":35.52,
         "pf":0.47,
         "current":0.32,
         "voltage":234.53,
         "is_valid":true,
         "total":1716.6,
         "total_returned":0.0
      },
      {
         "power":62.94,
         "pf":0.92,
         "current":0.29,
         "voltage":237.38,
         "is_valid":true,
         "total":2164.8,
         "total_returned":0.0
      }
   ],
   "total_power":462.94,
   "emeter_n":{
      "current":0.00,
      "ixsum":1.77,
      "mismatch":false,
      "is_valid":false
   },
   "fs_mounted":true,
   "v_data":1,
   "ct_calst":0,
   "update":{
      "status":"idle",
      "has_update":false,
      "new_version":"20221027-110030/v1.12.1-ga9117d3",
      "old_version":"20221027-110030/v1.12.1-ga9117d3"
   },
   "ram_total":49928,
   "ram_free":32004,
   "fs_size":233681,
   "fs_free":154867,
   "uptime":107843
}
```

**Comment by powersj** [comment]
You can add custom [tags per input plugin](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins), via global tags, or even in processors.

In this case, I think you are after:

```
  [inputs.http.tags]
    tag1 = "foo"
    tag2 = "bar"
```

Note this needs to be specified at the very end of the http input plugin configuration.

**Comment by virtualdreams** [comment]
> You can add custom [tags per input plugin](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-plugins), via global tags, or even in processors.
> 
> In this case, I think you are after:
> 
> ```
>   [inputs.http.tags]
>     tag1 = "foo"
>     tag2 = "bar"
> ```
> 
> Note this needs to be specified at the very end of the http input plugin configuration.

Thank you, that works, unfortunately only globally. I would prefer per block, but unfortunately that does not work.

Like:

```toml
    [[inputs.http.json_v2.object]]
      path = "emeters.0"
      disable_prepend_keys = false
    [inputs.http.tags]
      line = "0"
    [[inputs.http.json_v2.object]]
      path = "emeters.1"
      disable_prepend_keys = false
    [inputs.http.tags]
      line = "1"
```

**Comment by Hipska** [comment]
This is invalid TOML anyway and also doesn't make much sense.

I tried something with GJSON syntax, but it seems there is no way the get the array index of an object. And alternatively, it seems telegraf is not supporting its `!"test"` syntax for static values..

**Comment by virtualdreams** [comment]
I have solved it differently now. I read the desired fields and rename them. This way I can read everything separately in Grafana.

```toml
[[inputs.http]]
  urls = [
    "http://192.168.0.123/status"
  ]
  interval = "5s"
  timeout = "1s"
  data_format = "json_v2"
  [[inputs.http.json_v2]]
    measurement_name = "shelly3em"
    timestamp_format = "unix"

    # input 0
    [[inputs.http.json_v2.field]]
      path = "emeters.0.power"
      type = "float"
      rename = "power0"
    [[inputs.http.json_v2.field]]
      path = "emeters.0.current"
      type = "float"
      rename = "current0"
    [[inputs.http.json_v2.field]]
      path = "emeters.0.voltage"
      type = "float"
      rename = "voltage0"

    # input 1
    [[inputs.http.json_v2.field]]
      path = "emeters.1.power"
      type = "float"
      rename = "power1"
    [[inputs.http.json_v2.field]]
      path = "emeters.1.current"
      type = "float"
      rename = "current1"
    [[inputs.http.json_v2.field]]
      path = "emeters.1.voltage"
      type = "float"
      rename = "voltage1"

    # input 2
    [[inputs.http.json_v2.field]]
      path = "emeters.2.power"
      type = "float"
      rename = "power2"
    [[inputs.http.json_v2.field]]
      path = "emeters.2.current"
      type = "float"
      rename = "current2"
    [[inputs.http.json_v2.field]]
      path = "emeters.2.voltage"
      type = "float"
      rename = "voltage2"

    # general
    [[inputs.http.json_v2.field]]
      path = "wifi_sta.rssi"
      type = "float"
    [[inputs.http.json_v2.field]]
      path = "total_power"
      type = "float"
      rename = "power_total"
```

**Comment by Hipska** [comment]
What would be needed to have the best solution for you would be something like a `index_as_tag` config option. So in the case you can't distinguish json array items by any json field, you have the option to have the number of occurrence as a tag in the resulting metric.

Would you like to create a [feature request](https://github.com/influxdata/telegraf/issues/new?assignees=&labels=feature+request,area/json,plugin/parser&template=FEATURE_REQUEST.yml) for that? In your scenario, the following config would then be sufficient:
```toml
    [[inputs.http.json_v2.object]]
      path = "emeters"
      index_as_tag = true
```
Would result in the following metrics:
```
> shelly\ 3em,index=0 current=1.76,is_valid=true,pf=0.88,power=364.48,total=8635.9,total_returned=0,voltage=232.23 1670322270000000000
> shelly\ 3em,index=1 current=0.32,is_valid=true,pf=0.47,power=35.52,total=1716.6,total_returned=0,voltage=234.53 1670322270000000000
> shelly\ 3em,index=2 current=0.29,is_valid=true,pf=0.92,power=62.94,total=2164.8,total_returned=0,voltage=237.38 1670322270000000000
```


PS: You still need to set `timestamp_path = "unixtime"` for it to work correctly.
