### ISSUE TITLE
Modbus plugin "controller" input not valid for windows users.

### ISSUE THREAD

**Issue by OranMZT** [influxdata/telegraf#12331]
### Relevant telegraf.conf

```toml
# # Retrieve data from MODBUS slave devices
[[inputs.modbus]]
#   ## Device name
name = "Device"
slave_id = 254
#
#   ## Timeout for each request
timeout = "1s"
#
#   ## Serial (RS485; RS232)
controller = "file://COM2"
baud_rate = 9600
data_bits = 8
parity = "N"
stop_bits = 1

transmission_mode = "RTU"


debug_connection = true

#   ## Define the configuration schema
configuration_type = "register"
   input_registers = [
     { name = "CO2_PPM",   byte_order = "AB",   data_type = "INT16",   scale=1.0,     address = [3]}
   ]
```

### Logs from Telegraf

```text
2022-12-05T18:15:30Z E! [inputs.modbus] Error in plugin: The system cannot find the path specified.
```

### System info

Telegraf 1.24.2, WIndows 11 

### Steps to reproduce

1. Launch telegraf on Windows 11 with the included input plugin

### Expected behavior

Telegraf should read the given register on com port 2

### Actual behavior

Telegraf is unable to locate the com port

### Additional info

Using the same [modbus library](https://github.com/grid-x/modbus) Telegraf uses I was able to read the register on my Modbus device with the same parameters. On this just "COM2" was passed too the the "NewRTUClientHandler" method.

I've tried this an a number of other combinations for the "controller" value on the Modbus input.
