### ISSUE TITLE
telegraf : Input is DNS , Output is prometheusRemoteWrite

### ISSUE THREAD

**Issue by pmathur231** [influxdata/telegraf#12333]
I would like to write dns data into a prom url which is already existing. I am able to write DNS input data into a file on my local , but prometheusremotewrite isnt writing data into the url that i have mentioned in its config 

```toml
[[outputs.http]]
  ## URL is the address to send metrics to
  url = "http://GEM HOSTNAME/api/prom/push"

  ## Optional TLS Config
  tls_ca = "CERTS"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  insecure_skip_verify = true

  ## Data format to output.
  data_format = "prometheusremotewrite"
  ## HTTP Basic Auth credentials
  username = "REDACTED"
  password = "REDACTED"

  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
     X-Prometheus-Remote-Write-Version = "0.1.0"
```

Link to doc - 
https://github.com/influxdata/telegraf/blob/master/plugins/serializers/prometheusremotewrite/README.md

Any help is appreciated

Thanks,
pmathur
