### ISSUE TITLE
connections leak triggered by auto reload config mechanism

### ISSUE THREAD

**Issue by zhiyuan-mojie** [influxdata/telegraf#12336]
### Relevant telegraf.conf

```toml
[agent]
interval = "30s"
round_interval = false
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
precision = "s"
debug = false
quiet = true
logtarget = ""
logfile = ""logfile_rotation_max_archives = 5
hostname = ""
omit_hostname = false

[global_tags]
point_id = "600a95a2db699236fd60a192"

[[inputs.mongodb]]
servers = ["mongodb://xxx:xxx@127.0.0.1:27017"]
gather_cluster_status = true
gather_perdb_stats = true
gather_col_stats = false

[inputs.mongodb.tags]
task_id = "638ded70b4e458e6bb962ebe"
task_name = "test"
```

### Logs from Telegraf

```text
much mongo connections from telegraf
```

### System info

telegraf master centos8

### Steps to reproduce

1.  ./telegraf --config=./telegraf.conf --watch-config=notify
2. loop change config file: echo "" >> ./telegraf.conf 

### Expected behavior

every time file changed, release previous mongo connections

### Actual behavior

every time file changed, lead to connections leak
