### ISSUE TITLE
telegraf output plugin for postgresql reading all records from the beginning with tail plugin when a new record is added 

### ISSUE THREAD

**Issue by gssprakash** [influxdata/telegraf#12337]
### Relevant telegraf.conf

```toml
Input Plugin tail Config: 
[[inputs.tail]]
  
  files = ["C:\\Test\\supporttest\\myfile.csv"]

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ##   https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  
  #from_beginning = true
  data_format = "csv"

  ## Indicates how many rows to treat as a header. By default, the parser assumes
  ## there is no header and will parse the first row as data. If set to anything more
  ## than 1, column names will be concatenated with the name listed in the next header row.
  ## If `csv_column_names` is specified, the column names in header will be overridden.
  csv_header_row_count = 1

  ## For assigning custom names to columns
  ## If this is specified, all columns should have a name
  ## Unnamed columns will be ignored by the parser.
  ## If `csv_header_row_count` is set to 0, this config must be used
  csv_column_names = []

  ## Indicates the number of rows to skip before looking for header information.
  csv_skip_rows = 0

  ## Indicates the number of columns to skip before looking for data to parse.
  ## These columns will be skipped in the header as well.
  csv_skip_columns = 0

  ## The seperator between csv fields
  ## By default, the parser assumes a comma (",")
  csv_delimiter = ","

  ## The character reserved for marking a row as a comment row
  ## Commented rows are skipped and not parsed
  csv_comment = "#"

  ## If set to true, the parser will remove leading whitespace from fields
  ## By default, this is false
  csv_trim_space = true

  ## Columns listed here will be added as tags. Any other columns
  ## will be added as fields.
  
  csv_column_types=["string","string","string","string","string","string","integer","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","integer","string","string","string","string","string","string","string","string","string","string","string","string","string","integer","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string","string"]

  ## The column to extract the name of the metric from
  csv_measurement_column = ""

  ## The column to extract time information for the metric
  ## `csv_timestamp_format` must be specified if this is used
  csv_timestamp_column = ""

  ## The format of time data extracted from `csv_timestamp_column`
  ## this must be specified if `csv_timestamp_column` is specified
  csv_timestamp_format = ""
  [inputs.tail.tags]
	tag2 = "dbalerts"

[[outputs.postgresql]]
  ## Specify connection address via the standard libpq connection string:
     connection="host=localhost port=5432 user=postgres password=xxxxxx sslmode=disable dbname=dbalerts"
	 
	
	 
  ## Or a URL:
  ##   postgres://[user[:password]]@localhost[/dbname]?sslmode=[disable|verify-ca|verify-full]
       
  ## See https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING
  ##
  ## All connection parameters are optional. Environment vars are also supported.
  ## e.g. PGPASSWORD, PGHOST, PGUSER, PGDATABASE
  ## All supported vars can be found here:
  ##  https://www.postgresql.org/docs/current/libpq-envars.html
  ##
  ## Non-standard parameters:
  ##   pool_max_conns (default: 1) - Maximum size of connection pool for parallel (per-batch per-table) inserts.
  ##   pool_min_conns (default: 0) - Minimum size of connection pool.
  ##   pool_max_conn_lifetime (default: 0s) - Maximum age of a connection before closing.
  ##   pool_max_conn_idle_time (default: 0s) - Maximum idle time of a connection before closing.
  ##   pool_health_check_period (default: 0s) - Duration between health checks on idle connections.
  # connection = ""

  ## Postgres schema to use.
  # schema = "public"

  ## Store tags as foreign keys in the metrics table. Default is false.
  # tags_as_foreign_keys = false

  ## Suffix to append to table name (measurement name) for the foreign tag table.
  # tag_table_suffix = "_tag"

  ## Deny inserting metrics if the foreign tag can't be inserted.
  # foreign_tag_constraint = false

  ## Store all tags as a JSONB object in a single 'tags' column.
  # tags_as_jsonb = false

  ## Store all fields as a JSONB object in a single 'fields' column.
  # fields_as_jsonb = false

  ## Templated statements to execute when creating a new table.
  # create_templates = [
  #   '''CREATE TABLE {{ .table }} ({{ .columns }})''',
  # ]

  ## Templated statements to execute when adding columns to a table.
  ## Set to an empty list to disable. Points containing tags for which there is no column will be skipped. Points
  ## containing fields for which there is no column will have the field omitted.
  # add_column_templates = [
  #   '''ALTER TABLE {{ .table }} ADD COLUMN IF NOT EXISTS {{ .columns|join ", ADD COLUMN IF NOT EXISTS " }}''',
  # ]

  ## Templated statements to execute when creating a new tag table.
  # tag_table_create_templates = [
  #   '''CREATE TABLE {{ .table }} ({{ .columns }}, PRIMARY KEY (tag_id))''',
  # ]

  ## Templated statements to execute when adding columns to a tag table.
  ## Set to an empty list to disable. Points containing tags for which there is no column will be skipped.
  # tag_table_add_column_templates = [
  #   '''ALTER TABLE {{ .table }} ADD COLUMN IF NOT EXISTS {{ .columns|join ", ADD COLUMN IF NOT EXISTS " }}''',
  # ]

  ## The postgres data type to use for storing unsigned 64-bit integer values (Postgres does not have a native
  ## unsigned 64-bit integer type).
  ## The value can be one of:
  ##   numeric - Uses the PostgreSQL "numeric" data type.
  ##   uint8 - Requires pguint extension (https://github.com/petere/pguint)
  # uint64_type = "numeric"

  ## When using pool_max_conns>1, and a temporary error occurs, the query is retried with an incremental backoff. This
  ## controls the maximum backoff duration.
  # retry_max_backoff = "15s"

  ## Approximate number of tag IDs to store in in-memory cache (when using tags_as_foreign_keys).
  ## This is an optimization to skip inserting known tag IDs.
  ## Each entry consumes approximately 34 bytes of memory.
  # tag_cache_size = 100000

  ## Enable & set the log level for the Postgres driver.
  # log_level = "warn" # trace, debug, info, warn, error, none
   [outputs.postgresql.tagpass] 
     tag2 = ["dbalerts"]
```

### Logs from Telegraf

```text
No issue in log
```

### System info

telegraf 1.24.2  on windows 11 

### Steps to reproduce

1. Add input and output plugins as shown in the config file to telegraf config file .
2.  Create a new record in the file attached myfile.csv with just 2 columns as "","Severity 1"
3.  Add another record in the file with 2 columns as "","Severity 2" 
4.  You can see multiple records in postgresql  as it reads all records from first record  whenever a new record is added 
5.  This is the same situation irrespective  from_beginning = true or false in the input plugin that reads csv file  
...
[myfile.csv](https://github.com/influxdata/telegraf/files/10164940/myfile.csv)

### Expected behavior

Only  the last record should be added to postgresql 

### Actual behavior

When a new record is added all records from the beginning are added to postgres database . Attahced grafana screenshot.

![issuewith_postgresql_output_plugin](https://user-images.githubusercontent.com/46620247/205881989-185e9a1d-0134-4187-92bf-fc49420885d4.jpg)

**Comment by gssprakash** [comment]
Sure I will check and let you know powersj. But intension is to read continously records in a file that are in  csv format with tail plugin . 

Thanks for your quick verification of the issue .

**Comment by gssprakash** [comment]
Added below lines to my telegraf config file but don't see any record in mycsvmetrics.out file .Did I miss anything powersj?  Tried by removing specially handled file "stdout" and keeping only xxx.out file also. But no bytes. 

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout", "C:\\Test\\supporttest\\mycsvmetrics.out"]

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "csv"
  [outputs.file.tagpass] 
     tag2 = ["dbalerts"]

**Comment by powersj** [comment]
That tag pass will only pass metrics with a tag named "tag2" and a value of "dbalerts" is that valid based on your data?

**Comment by gssprakash** [comment]
It is valid.  However, I tried with attached config file.  Now I could create output file mycsvmetrics.txt (extensions changed to txt for uploading files) with data . It seems there is an issue with input plugin tail . It reads all records from the beginning irrespective of from_beginning = false or true or completely commented out .  

Telegraf config file : 

[postgresql_csvtelegraf.txt](https://github.com/influxdata/telegraf/files/10169264/postgresql_csvtelegraf.txt)

Also attached the sample output file:

[false_mycsvmetrics.txt](https://github.com/influxdata/telegraf/files/10169254/false_mycsvmetrics.txt)

Input file used for adding records : 
[myfile.csv](https://github.com/influxdata/telegraf/files/10169279/myfile.csv)

**Comment by powersj** [comment]
Hi @gssprakash looks like you are running on Windows, can you try setting `watch_method = "poll"` and try again?

**Comment by gssprakash** [comment]
Tried with watch_method ="poll"  but no luck .  tail plugin could not read any record if from_beginning = false 
but with from_beginning = true , it could read only first records after that not reading any record added to the file . 

telegraf config file :

[postgresql_csvtelegraf.txt](https://github.com/influxdata/telegraf/files/10182383/postgresql_csvtelegraf.txt)

Output file with from_beginning = false and watch_method = "poll"

[mycsvmetrics_poll_beginning_false.txt](https://github.com/influxdata/telegraf/files/10182393/mycsvmetrics_poll_beginning_false.txt)

Output file with from_beginning = true and watch_method = "poll"

[mycsvmetrics_poll_beginning_true.txt](https://github.com/influxdata/telegraf/files/10182396/mycsvmetrics_poll_beginning_true.txt)

telegraf log file taken in debug mode: 

[telegraf.log](https://github.com/influxdata/telegraf/files/10182401/telegraf.log)

csv file being used for reading the records entered manually

[myfile.csv](https://github.com/influxdata/telegraf/files/10182405/myfile.csv)

**Comment by powersj** [comment]
ok I wanted to simplify this config to read the CSV and output to stdout. I removed all the config options that are not changing anything.

```toml
[[outputs.file]]

[[inputs.tail]]
  files = ["myfile.csv"]
  from_beginning = true
   # use "poll" on windows, "inotify" on unix
  watch_method = "inotify" 
  data_format = "csv"

  csv_header_row_count = 1
  csv_comment = "#"
  csv_trim_space = true
  csv_column_types=[
    "string","string","string","string","string","string","integer","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","integer","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","integer","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string","string","string","string",
    "string","string","string","string","string"
  ]
  [inputs.tail.tags]
    tag2 = "dbalerts"
```

If I start with your example CSV file, and then echo into the file a couple more entries I get:


```s
./telegraf --config config.toml --debug
2022-12-08T15:49:53Z I! Starting Telegraf 1.25.0-f2729298
2022-12-08T15:49:53Z I! Available plugins: 227 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs
2022-12-08T15:49:53Z I! Loaded inputs: tail
2022-12-08T15:49:53Z I! Loaded aggregators: 
2022-12-08T15:49:53Z I! Loaded processors: 
2022-12-08T15:49:53Z I! Loaded outputs: file
2022-12-08T15:49:53Z I! Tags enabled: host=ryzen
2022-12-08T15:49:53Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ryzen", Flush Interval:10s
2022-12-08T15:49:53Z D! [agent] Initializing plugins
2022-12-08T15:49:53Z D! [agent] Connecting outputs
2022-12-08T15:49:53Z D! [agent] Attempting connection to [outputs.file]
2022-12-08T15:49:53Z D! [agent] Successfully connected to outputs.file
2022-12-08T15:49:53Z D! [agent] Starting service inputs
2022-12-08T15:49:53Z D! [inputs.tail] Tail added for "myfile.csv"
tail,host=ryzen,path=myfile.csv,tag2=dbalerts Last\ Update="",Business\ Impact="Severity 1" 1670514593039917059
tail,host=ryzen,path=myfile.csv,tag2=dbalerts Business\ Impact="Severity 2",Last\ Update="" 1670514593039967489
tail,host=ryzen,path=myfile.csv,tag2=dbalerts Last\ Update="",Business\ Impact="Severity 3" 1670514593039981579
tail,host=ryzen,path=myfile.csv,tag2=dbalerts Last\ Update="",Business\ Impact="Severity 4" 1670514593039988759
2022-12-08T15:50:03Z D! [outputs.file] Wrote batch of 4 metrics in 53.71µs
2022-12-08T15:50:03Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
# in another terminal I run:
# echo "\"\",\"Severity 42\"" >> myfile.csv && echo "\"\",\"Severity 43\"" >> myfile.csv
tail,host=ryzen,path=myfile.csv,tag2=dbalerts Last\ Update="",Business\ Impact="Severity 42" 1670514609851795760
tail,host=ryzen,path=myfile.csv,tag2=dbalerts Last\ Update="",Business\ Impact="Severity 43" 1670514609851807540
2022-12-08T15:50:13Z D! [outputs.file] Wrote batch of 2 metrics in 30.46µs
2022-12-08T15:50:13Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
```

This looks like the behavior you are after. Confirmed on arch + windows 11 with the only change being the `watch_method` option.
