### ISSUE TITLE
float change to with input mqtt

### ISSUE THREAD

**Issue by nicho2** [influxdata/telegraf#12349]
### Relevant telegraf.conf

```toml
[[inputs.mqtt_consumer]]
name_override = "3ddlmlite"
servers = ["tcp://127.0.0.1:1883"]
   ## Topics that will be subscribed to.
topics = [
		"+/sensor/+/metrics/avg-sound-level",
		"+/sensor/+/metrics/co2",
		"+/sensor/+/metrics/iaq-index",
		"+/sensor/+/metrics/luminosity",
		"+/sensor/+/metrics/max-sound-level",
		"+/sensor/+/metrics/occupancy",
		"+/sensor/+/metrics/people-count",
		"+/sensor/+/metrics/relative-humidity",
		"+/sensor/+/metrics/sound-level",
		"+/sensor/+/metrics/t-voc",
		"+/sensor/+/metrics/temperature-indoor",
		
   ]
	topic_tag = "namespace"  # permet d'enlever le tag "topic" si ""
	data_format = "value"
	data_type = "float" # required
	precision = "10s"		# précision du timestamp pour le merge
	
	[[inputs.mqtt_consumer.topic_parsing]]
        topic = "+/+/+/+/+"  # all topics with 5 segments
        tags = "_/type/device_id/_/field"
        measurement = "_/_/_/_/measurement"
		
		
		
[[processors.pivot]]
	tag_key = "field"
	value_key = "value"
	order = "1"
	
# # Transforms tag and field values as well as measurement, tag and field names with regex pattern
[[processors.regex]]
#   ## Tag and field conversions defined in a separate sub-tables
    [[processors.regex.tags]]
    ## Tag to change
    #key = "topic"
	key = "namespace"
    ## Regular expression to match on a tag value
    #pattern = "^([\\w/]+)/metrics/\\S*$"  # attention pattern de match du topic complet + groupe pour le résultat
	pattern = "^([\\w]+)/sensor/[\\w]+/metrics/\\S*$"
    ## Matches of the pattern will be replaced with this string.  Use ${1}
    ## notation to use the text of the first submatch.
    replacement = "${1}"
	order = "2"

[[aggregators.merge]]
#   ## If true, the original metric will be dropped by the
#   ## aggregator and will not get sent to the output plugins.
	drop_original = true
	period = "10s"
```

### System info

windows 10, Telegraf 1.25.0

### Steps to reproduce

1. i send topic : Activity_4/sensor/0004742C0004/metrics/temperature-indoor
with payload  = 22.0

2. and i obtain measure:

3ddlmlite,device_id=0004742C0004,host=FRL17172,namespace=Activity_4,type=sensor avg-sound-level=47,iaq-index=3.15,luminosity=347,occupancy=1,people-count=2,relative-humidity=30,sound-level=55,t-voc=580,temperature-indoor=**22** 1670419268098294600

temperature-indoor is now an integer
5.
...

### Expected behavior

 value keep a float 

### Actual behavior

 the value is convert to an int (22)
