### ISSUE TITLE
sflow cannot parse mikrotik v5 data

### ISSUE THREAD

**Issue by syadnom** [influxdata/telegraf#12359]
### Relevant telegraf.conf

```toml
[[inputs.sflow]]
   service_address = "udp://:6343"
```

### Logs from Telegraf

```text
[inputs.sflow] Error in plugin: unable to parse incoming packet: Version 327710 not supported, only version 5
```

### System info

Ubuntu 18.04, influx 1.8.10, telegraf 1.24.4

### Steps to reproduce

send netflow v5 from mikrotik

### Expected behavior

parse data

### Actual behavior

error in logs
