### ISSUE TITLE
 input.*.tags are excluded by taginclude on the same input

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#12361]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
...
taginclude = [ "namespace", "pod_name" ]

[inputs.prometheus.tags]
app = "promtail"
```

### Logs from Telegraf

```text
not relevant
```

### System info

1.24

### Steps to reproduce

1. specify tags in `taginclude` list
2. specify different tags in the `tags` map in the same input

### Expected behavior

Tags specified statically are kept even if not included in the `taginclude`

### Actual behavior

Unless tag is not specified in **both** `taginclude` and `tags` map it is removed from the metric

### Additional info

`global_tags` is not subject to `taginclude` processing, I'd expect static `tags` to behave the same. I can't think of a situation when user specified static `tags`, but  don't want them to be actually inlcluded. `tags` should be added to input plugin tags at the very end, after all filtering is done.

**Comment by powersj** [comment]
> global_tags is not subject to taginclude processing

This is not accurate. The global tag `host` for example will be excluded in the following config and only the key tag from my file is included

```
[[outputs.file]]
[[inputs.file]]
  files = ["file.influx"]
  data_format = "influx"
  taginclude = ["key"]
```

Produces:

```
metric,key=value field=1 1670529066000000000
```

versus the following without the taginclude

```
metric,host=ryzen,key=value field=1 1670529047000000000
```

> I can't think of a situation when user specified static tags, but don't want them to be actually inlcluded

Neither can I, but if you going to specify what tags to include, you need to be explicit about which ones you want, whether that tag is global, specified by the input, or included in the data.

**Comment by redbaron** [comment]
> The global tag host for example will be excluded in the following config and only the key tag from my file is included

This is not what I see. Following config:

```toml
[global_tags]
mc_zone = "zone1"

[[inputs.internal]]
interval = 60
collect_memstats = false

[[inputs.prometheus]]
monitor_kubernetes_pods = true
metric_version = 2
monitor_kubernetes_pods_method = "settings+annotations"
kubernetes_label_selector = "app in (app1,app2)"
monitor_kubernetes_pods_port = 7354
pod_scrape_interval = 60
taginclude = [ "app", "namespace", "pod_name" ]
```

produces metrics with app, namespace, pod_name, mc_zone and host tags
