### ISSUE TITLE
http_headers doesn't work on prometheus input

### ISSUE THREAD

**Issue by brianzer0** [influxdata/telegraf#12364]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  urls = ["https://127.0.0.1:9644/metrics"]

  [inputs.prometheus.http_headers]
     Connection = "keep-alive"
```

### Logs from Telegraf

```text
Dec  8 22:25:57 x telegraf[869809]: 2022-12-08T22:25:57Z E! [telegraf] Error running agent: error loading config file /etc/telegraf/telegraf.d/input_.conf: plugin inputs.prometheus: line 1: configuration specified the fields ["http_headers"], but they weren't used
```

### System info

telegraf 1.24.24, rocky linux 9

### Steps to reproduce

1. Try to use "http_headers" config on prometheus input

### Expected behavior

Should be able to set http headers for plugin. Also doc seems to be wrong as it tells you to set "headers" which also does not work

### Actual behavior

Cant set headers for prometheus plugin

### Additional info

Not sure how the unused field tracking really works, but can we just add "http_headers" to the exclude case statement in config.go?
