### ISSUE TITLE
SNMP telegraf not outputting string data via plugin snmp  in telegraf --config  --test --dubug

### ISSUE THREAD

**Issue by avelok** [influxdata/telegraf#12365]
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
    agents = [ "xx.xx.xx.xx:161" ]
    version = 2
    community = "dssl"
    interval = "60s"
    timeout = "5s"
    retries = 3

[[inputs.snmp.table]]
    name = "trassir"

    [[inputs.snmp.table.field]]
        name = "Trassir.db_ok"
        oid = "1.3.6.1.4.1.3333.1.1"

    [[inputs.snmp.table.field]]
        name = "Trassir.archive_days"
        oid = "1.3.6.1.4.1.3333.1.2"

    [[inputs.snmp.table.field]]
        name = "Trassir.disks_ok"
        oid = "1.3.6.1.4.1.3333.1.3"

    [[inputs.snmp.table.field]]
        name = "Trassir.network_ok"
        oid = "1.3.6.1.4.1.3333.1.4"

    [[inputs.snmp.table.field]]
        name = "Trassir.cameras"
        oid = "1.3.6.1.4.1.3333.1.5"

    [[inputs.snmp.table.field]]
        name = "Trassir.scripts_ok"
        oid = "1.3.6.1.4.1.3333.1.6"

    [[inputs.snmp.table.field]]
        name = "Trassir.cloud_ok"
        oid = "1.3.6.1.4.1.3333.1.7"

    [[inputs.snmp.table.field]]
        name = "Trassir.cpu_usage"
        oid = "1.3.6.1.4.1.3333.1.8"
```

### Logs from Telegraf

```text
2022-12-09T08:45:12Z I! Starting Telegraf 1.24.0
2022-12-09T08:45:12Z I! Available plugins: 222 inputs, 9 aggregators, 26 processors, 20 parsers, 57 outputs
2022-12-09T08:45:12Z I! Loaded inputs: snmp
2022-12-09T08:45:12Z I! Loaded aggregators: 
2022-12-09T08:45:12Z I! Loaded processors: 
2022-12-09T08:45:12Z W! Outputs are not used in testing mode!
2022-12-09T08:45:12Z I! Tags enabled: host=myserver
2022-12-09T08:45:12Z D! [agent] Initializing plugins
2022-12-09T08:45:12Z D! [agent] Starting service inputs
2022-12-09T08:45:12Z D! [agent] Stopping service inputs
2022-12-09T08:45:12Z D! [agent] Input channel closed
2022-12-09T08:45:12Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.24.0 ubuntu 20.04

### Steps to reproduce

1.  I run snmpwalk on the server itself, where telegraf is located

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.1
iso.3.6.1.4.1.3333.1.1 = STRING: "OK"

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.2
iso.3.6.1.4.1.3333.1.2 = STRING: "20"

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.3
iso.3.6.1.4.1.3333.1.3 = STRING: "OK"

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.4
iso.3.6.1.4.1.3333.1.4 = STRING: "OK"

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.5
iso.3.6.1.4.1.3333.1.5 = STRING: "115 / 126"

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.6
iso.3.6.1.4.1.3333.1.6 = STRING: "OK"

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.7
iso.3.6.1.4.1.3333.1.7 = STRING: "2"

snmpwalk -v2c -c dssl xx.xx.xx.xx .1.3.6.1.4.1.3333.1.8
iso.3.6.1.4.1.3333.1.8 = STRING: "24.1"

2.  But when output telegraf --config trassirhealth.conf --test --debug
i am not receiving anything and not sending to influxdb

3. tcpdump host xx.xx.xx.xx and port 161

11:55:00.002380 IP xx.xx.xx.xx.snmp > xx.xx.xx.xx.33629:    C="dssl" GetBulk(29)  N=0 M=10 E:3333.1.1

11:55:00.003670 IP  xx.xx.xx.xx.snmp > xx.xx.xx.xx.33629:  C="dssl" GetRequest(29)  E:3333.1.1
11:55:00.003830 IP  xx.xx.xx.xx.snmp > xx.xx.xx.xx.33629:  C="dssl" GetResponse(31)  E:3333.1.1="OK"

11:55:00.003236 IP xx.xx.xx.xx.snmp > xx.xx.xx.xx.33629:  C="dssl" GetResponse(201)  E:3333.1.2="20" E:3333.1.3="OK" E:3333.1.4="OK" E:3333.1.5="115 / 126" E:3333.1.6="OK" E:3333.1.7="2" E:3333.1.8="26.8" E:3333.2.1="" E:8072.1.2.1.1.4.0.1.0.0="" E:8072.1.2.1.1.4.0.1.1.0=""

that is, I receive requests and responses via snmp in string format

### Expected behavior

Get oids values ​​using telegraf.snmp via configuration file trassirhealth.conf and pass to influxDB

### Actual behavior

I don’t get oids values ​​​​from the configuration file trassirhealth.conf via telegraf snmp since --test --debug don't get any values, but at the same time, there are requests via snmpwalk directly from the server and via tcpdump too.
Could it be wrong that I'm getting a STRING?
Other configuration files for telegraf work, but not this one.

**Comment by Hipska** [comment]
It looks those are not indexed OID's. So if they are not a table, but fixed, they should be added as a field to the main `inputs.snmp` config. Ty this:
```toml
[[inputs.snmp]]
    agents = [ "xx.xx.xx.xx:161" ]
    version = 2
    community = "dssl"
    interval = "60s"
    timeout = "5s"
    retries = 3

    [[inputs.snmp.field]]
        name = "Trassir.db_ok"
        oid = "1.3.6.1.4.1.3333.1.1"

    [[inputs.snmp.field]]
        name = "Trassir.archive_days"
        oid = "1.3.6.1.4.1.3333.1.2"

    [[inputs.snmp.field]]
        name = "Trassir.disks_ok"
        oid = "1.3.6.1.4.1.3333.1.3"

    [[inputs.snmp.field]]
        name = "Trassir.network_ok"
        oid = "1.3.6.1.4.1.3333.1.4"

    [[inputs.snmp.field]]
        name = "Trassir.cameras"
        oid = "1.3.6.1.4.1.3333.1.5"

    [[inputs.snmp.field]]
        name = "Trassir.scripts_ok"
        oid = "1.3.6.1.4.1.3333.1.6"

    [[inputs.snmp.field]]
        name = "Trassir.cloud_ok"
        oid = "1.3.6.1.4.1.3333.1.7"

    [[inputs.snmp.field]]
        name = "Trassir.cpu_usage"
        oid = "1.3.6.1.4.1.3333.1.8"
```
