### ISSUE TITLE
Telegraf installed via telegraf-0.25.0 debian package fails to start

### ISSUE THREAD

**Issue by Tetha** [influxdata/telegraf#12397]
### Relevant telegraf.conf

```toml
# This is an unmodified telegraf.conf as <apt install telegraf> deploys it
# I've remove all lines starting with "^#", because otherwise the config is positively enormous
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Collection offset is used to shift the collection by the given amount.
  ## This can be be used to avoid many plugins querying constraint devices
  ## at the same time by manually scheduling them in time.
  # collection_offset = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"
## Collected metrics are rounded to the precision specified. Precision is
  ## specified as an interval with an integer + unit (e.g. 0s, 10ms, 2us, 4s).
  ## Valid time units are "ns", "us" (or "<C2><B5>s"), "ms", "s".
  ##
  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s:
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ##
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  precision = "0s"

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0h"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false

  ## Method of translating SNMP objects. Can be "netsnmp" which
  ## translates by calling external programs snmptranslate and snmptable,
  ## or "gosmi" which translates using the built-in gosmi library.
  # snmp_translator = "netsnmp"
```

### Logs from Telegraf

```text
[telegraf] Error running agent: no outputs found, did you provide a valid config file?
```

### System info

telegraf-0.25.0.deb on Debian 11

### Steps to reproduce

1. Start with an empty system, especially no `/etc/telegraf/telegraf.conf`
2. apt install telegraf

### Expected behavior

Telegraf should either be running (that's the debian way), or not get started.

### Actual behavior

Telegraf crashes:

```
vagrant@instance:~$ sudo apt install telegraf
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  telegraf
0 upgraded, 1 newly installed, 0 to remove and 30 not upgraded.
Need to get 0 B/45.0 MB of archives.
After this operation, 160 MB of additional disk space will be used.
(Reading database ... 45217 files and directories currently installed.)
Preparing to unpack .../telegraf_1.25.0-1_amd64.deb ...
Unpacking telegraf (1.25.0-1) ...
Setting up telegraf (1.25.0-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/telegraf.service → /lib/systemd/system/telegraf.service.
Job for telegraf.service failed because the control process exited with error code.
See "systemctl status telegraf.service" and "journalctl -xe" for details.
```

Systemd subsequently tries to restart telegraf 3-5 times, which all fail. Afterwards, the unit hits the systemd restart limit and you have to reset it via `systemctl reset-failed telegraf` to get telegraf back to working

### Additional info

Moin,

I've been chasing around failures in our Ansible CI system. It looks like - on an empty system - the debian package telegraf-1.25.0-1 deploys a config which causes telegraf to fail and systemd to lock the unit due to too many restarts (which then fails my ansible CI :( )

I've been poking around a bit, and if I install telegraf-1.24.4-1, the service starts up properly.

As far as I can see, telegraf-1.24.4-1 deploys a `telegraf.conf` which contains an `outputs.influxdb` by default:

```
###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
  # urls = ["http://127.0.0.1:8086"]
```

This output usually doesn't work, but it's an output. The `telegraf.conf` for telegraf-1.25.0-1 does not contain this default output, and thus telegraf complains about not having an output configured and refuses to start.

Note that this problem can be hidden, because `/etc/telegraf/telegraf.conf` is a config file. So if you have a working config file (or install telegraf < 1.25.0-1 beforehand), an installation of telegraf-1.25.0-1 won't cause an issue, since it'll leave the config file alone.
