### ISSUE TITLE
need to get the xml data from kafka topic in altiplano kafka sserver  and send to another kafka topic

### ISSUE THREAD

**Issue by jgeorge1234** [influxdata/telegraf#12425]
### Please direct all support questsions to slack or the forums. Thank you.

I am trying to get the  xml data from kafka topic in altiplano kafka server  and send to another kafka topic

While trying to get the data its throwing error

```text
telegraf  | 2022-12-20T12:06:02Z E! [inputs.kafka_consumer] Error in plugin: metric parse error: expected field at 1:70: "<notification xmlns=\"urn:ietf:params:xml:ns:netconf:notification:1.0\"<-- here"
telegraf  | 2022-12-20T12:06:02Z E! [inputs.kafka_consumer] Error in plugin: metric parse error: expected field at 1:70: "<notification xmlns=\"urn:ietf:params:xml:ns:netconf:notification:1.0\"<-- here"
telegraf  | 2022-12-20T12:06:02Z E! [inputs.kafka_consumer] Error in plugin: metric parse error: expected field at 1:70: "<notification xmlns=\"urn:ietf:params:xml:ns:netconf:notification:1.0\"<-- here"
telegraf  | 2022-12-20T12:06:02Z E! [inputs.kafka_consumer] Error in plugin: metric parse error: expected field at 1:70: "<notification xmlns=\"urn:ietf:params:xml:ns:netconf:notification:1.0\"<-- here"
telegraf  | 2022-12-20T12:06:02Z E! [inputs.kafka_consumer] Error in plugin: metric parse error: expected field at 1:70: "<notification xmlns=\"urn:ietf:params:xml:ns:netconf:notification:1.0\"<-- here"
telegraf  | 2022-12-20T12:06:02Z E! [inputs.kafka_consumer] Error in plugin: metric parse error: expected field at 1:70: "<notification xmlns=\"urn:ietf:params:xml:ns:netconf:notification:1.0\"><eventTime>2022-12-14T11:12:46.433+00:00</eventTime><alarms:alarm-notification xmlns:alarms=\"http://www.nokia.com/management-solutions/ams-alarms\"><alarms:alarm><alarms:resource xmlns=\"http://www.nokia.com/management-solutions/manager-directory-service\">CAL-AMS</alarms:resource><alarms:alarm-type-id>sync-active-alarms</alarms:alarm-type-id><alarms:last-status-change>2022-12-14T11:12:46.433+00:00</alarms:last-status-change><alarms:last-perceived-severity>minor</alarms:last-perceived-severity><alarms:last-alarm-text>success</alarms:last-alarm-text><alarms:last-alarm-condition>ALARM_OFF</alarms:last-alarm-condition></alarms:alarm></alarms:alarm-notification></notification>"
```
telegraf configs

```toml
[[inputs.kafka_consumer]]
        brokers = ["kafka server ip:9093"]
        topics = ["CAL-AMS_ALARM"]
        topic_tag = "altiplano"
        max_processing_time = "100s"

    enable_tls = true
    tls_ca = "/etc/telegraf/ca-cert.pem"
    insecure_skip_verify = true
    #tls_cert = "/etc/telegraf/client-cert.pem"
    #tls_key = "/etc/telegraf/client_https_rsa4096.key.pem"



[[outputs.kafka]]
        brokers = ["kafka broker ip:9092"]
        topic = "split_topic_1"
        flush_interval = "5s"
        metric_batch_size = 160000
        metric_buffer_limit = 2000000
        required_acks = 1
        tagpass = ["altiplano"]


       [outputs.kafka.topic_suffix]
                method = "measurement"
                separator = "_"
```
