### ISSUE TITLE
Stream metrics from Telegraf to Grafana: Subscription to the channel already exists

### ISSUE THREAD

**Issue by limecat-ss** [influxdata/telegraf#12438]
### Relevant telegraf.conf

```toml
[agent]
  interval = "1s"
  flush_interval = "1s"

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[outputs.http]]
  url = "http://localhost:3000/api/live/push/custom_stream_id"
  data_format = "influx"
  [outputs.http.headers]
    Authorization = "Bearer <API Key>"
```

### Logs from Telegraf

```text
there is no error in the log
```

### System info

Telegraf 1.25  ,  Grafana 9.3.2

### Steps to reproduce

Following this tutorial: https://grafana.com/tutorials/stream-metrics-from-telegraf-to-grafana/

### Expected behavior

I should be able to receive stream metrics from telegraf to grafana in two dashboards in playlist

### Actual behavior

When I use Stream metrics from Telegraf to Grafana I get the error: 'Streaming channel error: Subscription to the channel already exists'. And this usually happens when I use the playlist in kiosk mode (in Grafana)

Remembering that apparently this error only appears if you use more than one dashboard in grafana, alternating in playlist

### Additional info

I opened a problem in the Grafana community, and when analyzing the case, they said that it must be a bug in telegraf

error image:

![grafana_error](https://user-images.githubusercontent.com/103083073/209547589-097d7c7b-1513-46c0-aeb7-63953f0e1094.png)

Issue in grafana community:

https://github.com/grafana/grafana/issues/60570
