### ISSUE TITLE
Telegraf not sending timestamp to InfluxDB_v2

### ISSUE THREAD

**Issue by TheNemesis584** [influxdata/telegraf#12441]
### Relevant telegraf.conf

```toml
[[inputs.tail]]
 files = ["/var/log/nginx/json.access.log"]
 from_beginning = true 
 name_override = "nginxjson"
 json_name_key = "nginxjson"
 data_format = "json"
 json_time_key = "@timestamp"
 json_time_format = "2006-01-02T15:04:05Z07:00"
 tag_keys = ["client_ip", "domain", "request", "host", "status"]
 json_string_fields = ["@timestamp", "responsetime"]
```

### Logs from Telegraf

```text
there is no error in the log
```

### System info

Telegraf 1.25, InfluxDB 2.6

### Steps to reproduce

1. configure nginx access logs like this:
        ```
 log_format elk_logs escape=json
        '{"@timestamp":"$time_iso8601",'
        '"client_ip":"$remote_addr",'
        '"domain":"$host",'
        '"request":"$request_uri",'
        '"responsetime":"$request_time",'
        '"host":"$server_addr",'
        '"status":"$status"'
        '}';

        access_log /var/log/nginx/json.access.log elk_logs;
```
2. configure proper permission for json.access.log file so telegraf can access to file
3. 
...

### Expected behavior

I should be able to see timestamp as data point in influxdb

### Actual behavior

I'm not getting timestamp as datapoint

### Additional info

This is example of json log
{"@timestamp":"2022-12-26T04:27:24-05:00","client_ip":"xx.xx.xx.xx","domain":" somedomain.com ","request":"/404","responsetime":"0.001","host":"xx.xx.xx.xx","status":"404"}

I'm not getting timestamp as datapoint, I really don't know if this is a bug, but I'm getting everything else normally, no errors in logs. I’ve tried also with timestamp as tag, but same, no errors and timestamp doesn’t write to influxdb, nothing happens, every other field or string is inserting normally.

<img width="824" alt="Screenshot 2022-12-27 at 3 38 19 PM" src="https://user-images.githubusercontent.com/15105372/209682110-7f64d27b-8874-49e0-b510-52ee266f6a52.png">
