### ISSUE TITLE
Telegraf not able to process datetime received from SNMP Input plugin

### ISSUE THREAD

**Issue by Dhyanesh97** [influxdata/telegraf#12456]
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
   agents = ["udp://IP:Port"]
   interval = "60s"
   timeout = "30s"
   retries = 3
   version = 2
   community = "public"
   max_repetitions = 30
   name = "snmp"

 
  [[inputs.snmp.table]]
    name = "alarmsTable"
    oid = ".1.3.6.1.4.1.331.1.2.1.1.2.6"


[[processors.starlark]]
  source = '''
def apply(metric):
  if metric.name == "table":
    print(metric)

  return metric
'''
```

### Logs from Telegraf

```text
# Telegraf Logs
table,agent_host=IP,eventDateTime="�0+",eID=8060i 1672842224000000000
table,agent_host=IP,eventDateTime="�88+",eID=8063i 1672842224000000000

# Telegraf Logs from starlark plugin after print
"eventDateTime": "\a\xe6\x04\v\x15,2\x00+\x00\x00"
"eventDateTime": "\a\xe6\x05\x1f\x1788\x00+\x00\x00"
"eventDateTime": "\a\xe4\x04\x0f\x13\x130\x00+\x00\x00"
```

### System info

Telegraf:1.24, Ubuntu 20.04, Docker version 20.10.18

### Steps to reproduce

1. Configure SNMP input plugin to fetch the data.
2. Date format from source end look like **1992-5-26,13:30:15.0,-4:0**
3. Convert this data into string or date format while inserting into influxdb.
...

### Expected behavior

Data should be inserted in datetime or string format in influxdb

### Actual behavior

It is treating it as junk character which we are not able to handle properly.

### Additional info

 Date format from source end look like **1992-5-26,13:30:15.0,-4:0**

A date-time specification.

field  octets  contents                  range
-----  ------  --------                  -----
  1      1-2   year                      0..65536
  2       3    month                     1..12
  3       4    day                       1..31
  4       5    hour                      0..23
  5       6    minutes                   0..59
  6       7    seconds                   0..60
               (use 60 for leap-second)
  7       8    deci-seconds              0..9
  8       9    direction from UTC        '+' / '-'
  9      10    hours from UTC            0..11
10      11    minutes from UTC          0..59

For example, Tuesday May 26, 1992 at 1:30:15 PM EDT would be
displayed as:

                1992-5-26,13:30:15.0,-4:0

Note that if only local time is known, then timezone
information (fields 8-10) is not present.
