### ISSUE TITLE
Multiple config files gives bogus netsnmp deprecation warning if agent section isn't in first file read 

### ISSUE THREAD

**Issue by poodad** [influxdata/telegraf#12454]
### Relevant telegraf.conf

```toml
#main.conf
[agent]
 snmp_translator = "gosmi"

#inputs-windows.conf

[[inputs.win_perf_counters.object]]
  ObjectName = "PhysicalDisk"
  Instances = ["*"]
  Counters = ["Avg. disk sec/read","Avg. disk sec/write"]
  Measurement = "win_disk"
```

### Logs from Telegraf

```text
2023-01-03T21:19:42Z W! DeprecationWarning: Value "netsnmp" for option "snmp_translator" of plugin "agent" deprecated since version 1.25.0 and will be removed in 2.0.0: Use 'gosmi' instead
2023-01-03T21:19:42Z W! DeprecationWarning: Value "netsnmp" for option "snmp_translator" of plugin "agent" deprecated since version 1.25.0 and will be removed in 2.0.0: Use 'gosmi' instead
```

### System info

telegraf 1.25.0 on Windows

### Steps to reproduce

1. Create config file main.conf - populate with [agent] section stuff including snmp_translator = "gosmi" and outputs section
2. Create other config files named "inputs-whatever" with input sections
3. run telegraf in --test mode
...

### Expected behavior

expect telegraf to read all config files in --config-directory before complaining about deprecated features.

### Actual behavior

Telegraf complains about deprecated snmp_translator for every config file read until the file with [agent] snmp_translator is read.

### Additional info

renaming files such that the file with snmp_translator is read first (ie from main.conf to 00main.conf) is a workaround.
