### ISSUE TITLE
[inputs.vsphere] Error in plugin: while collecting host: ServerFaultCode: A specified parameter was not correct: querySpec.startTime, querySpec.endTime

### ISSUE THREAD

**Issue by chench00** [influxdata/telegraf#12455]
### Relevant telegraf.conf

```toml
## Realtime instance
[[inputs.vsphere]]
  interval = "20s"
  vcenters = [ "https://192.168.139.25/sdk" ]
  username = "administrator@vsphere.local"
  password = "REDACTED"
  use_int_samples = false

  # Exclude all historical metrics
  datastore_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]

  max_query_metrics = 256
  timeout = "60s"
  insecure_skip_verify = true

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "vsphere"
  namepass = ["vsphere*"] #Only points whose measurement name matches a pattern in this list are emitted.

# Historical instance
[[inputs.vsphere]]
  interval = "300s"
  vcenters = [ "https://192.168.139.25/sdk" ]
  username = "administrator@vsphere.local"
  password = "REDACTED"
  use_int_samples = false

  insecure_skip_verify = true

  # Exclude all realtime metrics
  host_metric_exclude = ["*"]
  vm_metric_exclude = ["*"]

  max_query_metrics = 256
  collect_concurrency = 3

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "vsphere"
  namepass = ["vsphere*"] #Only points whose measurement name matches a pattern in this list are emitted.
```

### Logs from Telegraf

```text
Jan  3 16:59:20 u1804tig telegraf[4057]: 2023-01-03T21:59:20Z E! [inputs.vsphere] Error in plugin: while collecting host: ServerFaultCode: A specified parameter was not correct: querySpec.startTime, querySpec.endTime
```

### System info

Telegraf 1.25.0 (git: HEAD@4d17ec79) - Ubuntu 18.04

### Steps to reproduce

1. Upgrade vCenter to 7.0.3.01200
2. Errors begin
3.
...

### Expected behavior

No errors.

### Actual behavior

Logs show `Jan  3 16:59:20 u1804tig telegraf[4057]: 2023-01-03T21:59:20Z E! [inputs.vsphere] Error in plugin: while collecting host: ServerFaultCode: A specified parameter was not correct: querySpec.startTime, querySpec.endTime`

### Additional info

After upgrading vCenter today I started receiving these errors. I enabled the debug flag and the only helpful bit is posted above.
