### ISSUE TITLE
Telegraf 1.25.0-1 breaks protobuf wire-format interpretation

### ISSUE THREAD

**Issue by dmgeurts** [influxdata/telegraf#12475]
Discovered today that after the Telegraf update from 1.25.0-0 to 1.25.0-1. Our PowerDNS-recursor Protobuf input stopped working.

### Relevant telegraf.conf

```toml
[[inputs.socket_listener]]
  ## Protobuf listener for RPZ matched query logging
  service_address = "tcp://127.0.0.1:8000"
  splitting_strategy = "variable length"
  splitting_length_field = {offset = 0, bytes = 2, endianness = "be", header_length = 0}

  data_format = "xpath_protobuf"
  xpath_native_types = true
  xpath_protobuf_file = "/etc/telegraf/dnsmessage.proto"
  xpath_protobuf_type = "PBDNSMessage"
```

### Logs from Telegraf

```text
E! [inputs.socket_listener] Error in plugin: parsing error: proto: cannot parse invalid wire-format data
```

### System info

Telegraf 1.25.0-1, Ubuntu 22.04

### Docker

n/a

### Steps to reproduce

1. Configure [[input.socket_listener]]
2. Verify working with Telegraf 1.25.0-0
3. Update Telegraf and observe the error in the journal/logs

### Expected behavior

No errors and Protobuf input accepted as valid.

### Actual behavior

See error message and no input accepted.
