### ISSUE TITLE
inputs.socketstat: sample config does not match struct

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#12479]
### Relevant telegraf.conf

```toml
# Gather indicators from established connections, using iproute2's ss command.
[[inputs.socketstat]]
  ## ss can display information about tcp, udp, raw, unix, packet, dccp and sctp sockets
  ## Specify here the types you want to gather
  socket_types = [ "tcp", "udp" ]
  ## The default timeout of 1s for ss execution can be overridden here:
  # timeout = "1s"
```

### Logs from Telegraf

```text
2023-01-05T19:16:31Z E! [telegraf] Error running agent: error loading config file /etc/telegraf/telegraf.conf: plugin inputs.socketstat: line 123: configuration specified the fields ["socket_types"], but they weren't used
```

### System info

master

### Steps to reproduce

use the config above to get the error message

### Expected behavior

no error message, the settings used are those provided by the sample config.

### Actual behavior

error message

### Additional info

This is a very, very long standing issue that that toml tags for a setting are wrong compared to the sample config!
