### ISSUE TITLE
Nokia sensor broken after 1.15.4

### ISSUE THREAD

**Issue by bofh16** [influxdata/telegraf#12504]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
        addresses = ["host:57400"]
        username = "user"
        password = "pass"
        encoding = "json"
        redial = "10s"

        [[inputs.gnmi.subscription]]
                name = "sros_chassis_stats"
                path = "/state/chassis[chassis-class=*]chassis-number[chassis-number=*]/fan[fan-slot=*]"
                subscription_mode = "sample"
                sample_interval = "30s"
```

### Logs from Telegraf

```text
2023-01-13T18:28:35Z E! [telegraf] Error running agent: starting input inputs.gnmi: invalid string path /state/chassis[chassis-class=*]chassis-number[chassis-number=*]/fan[fan-slot=*]: invalid path element chassis[chassis-class=*]chassis-number[chassis-number=*]: malformed List key-value pair string: chassis-number[chassis-number=*], in: [chassis-class=*]chassis-number[chassis-number=*]
```

### System info

Telegraf 1.25.0 on various distributions.

### Steps to reproduce

1. Configure the input plugin as above.
2. Restart the service.

### Expected behavior

Telegraf to collect the sensor data. It works on 1.15.4.

### Actual behavior

It doesn't work in 1.2[45]. Can't say for sure, where exactly it went wrong in between.

### Additional info

The sensor path has been also verified with gNMI client from cli.
