### ISSUE TITLE
statsd to Opentelemetry conversion issue

### ISSUE THREAD

**Issue by povilasv** [influxdata/telegraf#12507]
### Relevant telegraf.conf

```toml
[global_tags]
  env = "stage"
[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  logfile_rotation_max_size = "5000MB"
  logfile_rotation_max_archives = 2
  log_with_timezone = "local"
  omit_hostname = true
[[inputs.statsd]]
   protocol = "udp"
   max_tcp_connections = 250
   tcp_keep_alive = false
   service_address = ":8080"
   delete_gauges = true
   delete_counters = true
   delete_sets = true
   delete_timings = true
   percentiles = [90.0, 95.0, 99.0]
   metric_separator = "."
   parse_data_dog_tags = false
   allowed_pending_messages = 100000
   percentile_limit = 100
[[outputs.opentelemetry]]
    service_address = "endpont-here"
    compression = "gzip"
```
```


### Logs from Telegraf

```text
unrelated
```

### System info

1.25.0

### Steps to reproduce

1. Run this app https://github.com/devlibx/gox-metrics
2. Setup Telegraf
3. Send metrics to OpenTelemetry backend
...

### Expected behavior

When `delete_counters= true`, the OpenTelemetry Counter should be sent with Delta Temporality. As Telegraf accumulates data for every interval and then resets counters. Example we send `200` every interval, we see telegraf outputs following:

T0: 200
T1: 200
T2: 200

Which is Delta Temporality, more info -> https://opentelemetry.io/docs/reference/specification/metrics/supplementary-guidelines/#aggregation-temporality

When `delete_counters= false`, the OpenTelemetry Counter should be sent with Cumulative Temporality. As Telegraf accumulates the data and reports cumulative counter. For example:

T0: 200
T1: 400
T2: 600

### Actual behavior

We always send Temporality as Cumulative in this code:

 https://github.com/influxdata/influxdb-observability/blob/28e34bc69b46ddaab673aa784e67e467f08902e8/influx2otel/metrics.go#L158-L161
