### ISSUE TITLE
Allow any Successful response to http cookie auth

### ISSUE THREAD

**Issue by gazpachoking** [influxdata/telegraf#12510]
### Relevant telegraf.conf

```toml
[[inputs.http]]
    urls = ["http://host/data"]
    ## Optional Cookie authentication
    cookie_auth_url = "http://host/rest/authentication"
    cookie_auth_method = "POST"
    cookie_auth_headers = { Content-Type = "application/x-www-form-urlencoded"}
    cookie_auth_body = 'username=user&password=password'
    cookie_auth_renewal = "15m"
```

### Logs from Telegraf

```text
2023-01-16T18:14:10Z E! [telegraf] Error running agent: could not initialize input inputs.http: cookie auth renewal received status code: 204 (No Content) []
```

### System info

Telegraf 1.24.3

### Steps to reproduce

1. Try to use cookie auth in http input plugin with an auth endpoint that returns a 204
2. Plugin reports failure.

### Expected behavior

Cookies are saved and flow continues, as all 2XX responses are considered a success.

### Actual behavior

204 is considered a failure, and plugin aborts.

### Additional info

The issue is here, 200 and 201 are hard coded as the only success codes. Doesn't include 204, or other successful response codes.
https://github.com/influxdata/telegraf/blob/c79edb5b0573eada382eef21dd9f9a882132f3d4/plugins/common/cookie/cookie.go#L118-L119
