### ISSUE TITLE
prometheus input attempts to contact deleted pods

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#12527]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
monitor_kubernetes_pods = true
metric_version = 1
monitor_kubernetes_pods_method = "settings+annotations"
kubernetes_label_selector = "app = myapp"
monitor_kubernetes_pods_port = 7354
pod_scrape_interval = 60
```

### Logs from Telegraf

```text
Don't have exact line, because it was fixed in our systems, but error was from the `inputs.prometheus` and error text is clear that it network error while contact Pod metrics endpoint.
```

### System info

1.25.0

### Steps to reproduce

Left running telegraf with inputs.prometheus and monitor_kubernetes_pods enabled long enough in the active cluster, where pods ofter recreated, control plane upgraded, etc.

### Expected behavior

Deleted pods are never contacted by the telegraf

### Actual behavior

Observe telegraf eventually reporting error contact URL to scrape. When checking for the IP used in the URL there is no pod with such IP, meaning telegraf missed pod deletion.
