### ISSUE TITLE
[[outputs.file]] is resetting the produced files to filelength 0 ramdomly

### ISSUE THREAD

**Issue by Member0815** [influxdata/telegraf#12532]
### Relevant telegraf.conf

```toml
[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "120s"
  flush_jitter = "0s"
  precision = "1s"
  debug = true
  quiet = false
  logtarget = "file"
  logfile = "/var/log/telegraf/telegraf.log"
  logfile_rotation_interval = "24h"
  logfile_rotation_max_size = "100MB"
  logfile_rotation_max_archives = 5
  log_with_timezone = "local"

[[outputs.file]]
  files = ["/var/log/telegraf/tracenewtek.log"]
  rotation_interval = "24h"
  rotation_max_size = "100MB"
  rotation_max_archives = 10
  data_format = "influx"

[[processors.converter]]
  namepass = ["DataS0"]
  [processors.converter.fields]
    integer = ["totCnt"]

[[processors.converter]]
  namepass = ["SG600"]
  [processors.converter.fields]
    integer = ["state", "temp"]

# # Read metrics from MQTT topic(s)--------------------------------------------
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  topics = ["tele/newtek/DataS0","tele/newtek/SG600"]
  qos = 0
  persistent_session = false
  connection_timeout = "60s"
  client_id = "TelegrafNewtek"
  username = "${mquser}"
  password = "${mqpwd}"
  data_format = "json_v2"
  topic_tag = ""

[[inputs.mqtt_consumer.topic_parsing]]
  topic = "tele/newtek/+"
  measurement = "_/_/measurement"

[[inputs.mqtt_consumer.json_v2]]

[[inputs.mqtt_consumer.json_v2.object]]
  path = "@this"
  disable_prepend_keys = true

  timestamp_key = "TIME"
  timestamp_format = "2006-01-02T15:04:05"
  timestamp_timezone = "Europe/Berlin"

# # Read TRACE from MQTT topic(s)--------------------------------------------
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  topics = ["stat/newtek/TRACE", "tele/newtek/LWT"]
  qos = 0
  persistent_session = false
  connection_timeout = "60s"
  client_id = "TelegrafTrace"
  username = "${MQUSER}"
  password = "${MQPWD}"

  name_override = "Trace"
  data_format = "value"
  data_type = "string"
  topic_tag = ""

[[inputs.mqtt_consumer.topic_parsing]]
  topic = "stat/newtek/+"
  measurement = "_/_/measurement"

# ---------------------------------------------------------------------------
```

### Logs from Telegraf

```text
Not possible, because the logs are also resetted to length 0 or deleted
At any time, looking into the log or own output file the content seems to be reasonable
```

### System info

Telegraf 1.25.0 (git: HEAD@4d17ec79), DietPi:RPi-ARMv8-Bullseye, latest updates 

### Steps to reproduce

1. Incoming mqtt telegrams at a low rate of 1 or 2 telegrams per minute are corrct booked into InfluxDB and logged to the output file
2.
3.
...

### Expected behavior

Log rotation for Telegraf log works like configured in [agent]
Log rotation for own outputfile works like configured in [[outputs.file]]

### Actual behavior

Telegraf log file(s) and my own output file for logging is ramdomly set to length 0 or deleted, starting with new files. This looks like this:
dietpi@IoBroker:/var/log/telegraf$ ls -l
insgesamt 48
-rw-r--r-- 1 telegraf telegraf     0 21. Jan 22:17 telegraf.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf  7678 22. Jan 15:02 telegraf.log
-rw-r--r-- 1 telegraf telegraf     0 20. Jan 22:17 tracenewtek.2023-01-20-1674246078.log
-rw-r--r-- 1 telegraf telegraf     0 21. Jan 22:17 tracenewtek.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf 37760 22. Jan 15:02 tracenewtek.log
dietpi@IoBroker:/var/log/telegraf$ ls -l
insgesamt 16
-rw-r--r-- 1 telegraf telegraf    0 21. Jan 22:17 telegraf.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf 2001 22. Jan 15:28 telegraf.log
-rw-r--r-- 1 telegraf telegraf    0 20. Jan 22:17 tracenewtek.2023-01-20-1674246078.log
-rw-r--r-- 1 telegraf telegraf    0 21. Jan 22:17 tracenewtek.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf 9562 22. Jan 15:28 tracenewtek.log
dietpi@IoBroker:/var/log/telegraf$ ls -l
insgesamt 60
-rw-r--r-- 1 telegraf telegraf     0 21. Jan 22:17 telegraf.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf  9349 22. Jan 16:12 telegraf.log
-rw-r--r-- 1 telegraf telegraf     0 20. Jan 22:17 tracenewtek.2023-01-20-1674246078.log
-rw-r--r-- 1 telegraf telegraf     0 21. Jan 22:17 tracenewtek.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf 45164 22. Jan 16:12 tracenewtek.log
dietpi@IoBroker:/var/log/telegraf$ ls -l
insgesamt 0
-rw-r--r-- 1 telegraf telegraf 0 21. Jan 22:17 telegraf.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf 0 22. Jan 16:17 telegraf.log
-rw-r--r-- 1 telegraf telegraf 0 20. Jan 22:17 tracenewtek.2023-01-20-1674246078.log
-rw-r--r-- 1 telegraf telegraf 0 21. Jan 22:17 tracenewtek.2023-01-21-1674332522.log
-rw-r--r-- 1 telegraf telegraf 0 22. Jan 16:17 tracenewtek.log
dietpi@IoBroker:/var/log/telegraf$

### Additional info

Slack Community (Sven Rebhan) proposed to open an issue as a potential bug here
