### ISSUE TITLE
[inputs.openweathermap] Error in plugin: error making HTTP request

### ISSUE THREAD

**Issue by Ashcora** [influxdata/telegraf#12540]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  #container_names = []
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  #perdevice = true
  perdevice_include = []
  total = false
  docker_label_include = []
  docker_label_exclude = []
  tag_env = ["JAVA_HOME", "HEAP_SIZE"]
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.file]]
[[inputs.filecount]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.netstat]]
[[inputs.openweathermap]]
  app_id = "XXXXXXXXXXXXXXXXX- is provided in my conf -XXXXXXXXXXXXXXXXXXXXXX"
  city_id = ["3214104"]
  base_url = "http://api.openweathermap.org/"
  lang = "de"
  fetch = ["weather","forecast"]
  units = "metric"
  interval = "10m"
[[inputs.processes]]
[[inputs.ping]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.temp]]
[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  token = "XXXXXXXXXXXXXXXXX- is provided in my conf -XXXXXXXXXXXXXXXXXXXXXX"
  organization = "InfluxOrgDocker"
  bucket = "Telegraf"
```

### Logs from Telegraf

```text
2023-01-24T17:00:00Z E! [inputs.openweathermap] Error in plugin: error making HTTP request to https://api.openweathermap.org/data/2.5/forecast?APPID=MY_API_KEY&id=5391959&lang=en&units=metric: Get "https://api.openweathermap.org/data/2.5/forecast?APPID=MY_API_KEY&id=5391959&lang=en&units=metric": dial tcp: lookup api.openweathermap.org on [::1]:53: read udp [::1]:43933->[::1]:53: read: connection refused
2023-01-24T17:10:00Z E! [inputs.openweathermap] Error in plugin: error making HTTP request to https://api.openweathermap.org/data/2.5/group?APPID=MY_API_KEY&id=5391959&lang=en&units=metric: Get "https://api.openweathermap.org/data/2.5/group?APPID=MY_API_KEY&id=5391959&lang=en&units=metric": dial tcp: lookup api.openweathermap.org on [::1]:53: read udp [::1]:34897->[::1]:53: read: connection refused
```

### System info

TELEGRAF_VERSION: 1.25.0 - Docker 20.10.23 - Server Ubuntu 22.04.1 LTS

### Docker

name: telegraf-influxdb

services:

  telegraf:
    image: telegraf
    container_name: telegraf
    privileged: true
    user: telegraf:1000
    volumes:
    - /opt/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    network_mode: "host"
    ports:
    - '127.0.0.1:8125:8125/udp'

  influxdb:
    image: influxdb:2.4.0
    container_name: influxdb
    env_file: .env
    environment:
      - INFLUXDB_INIT_MODE:$INFLUXDB_INIT_MODE
      - INFLUXDB_INIT_USERNAME:$INFLUXDB_INIT_USERNAME
      - INFLUXDB_INIT_PASSWORD:$INFLUXDB_INIT_PASSWORD
      - INFLUXDB_INIT_ORG:$INFLUXDB_INIT_ORG
      - INFLUXDB_INIT_BUCKET:$INFLUXDB_INIT_BUCKET
      - INFLUXDB_INIT_ADMIN_TOKEN:$INFLUXDB_INIT_ADMIN_TOKEN
      - INFLUXD_LOG_LEVEL:$INFLUXD_LOG_LEVEL
      - TZ:$TZ
    labels:
        com.centurylinklabs.watchtower.enable: "true"
    network_mode: "host"
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - /opt/influxdb/imports:/imports
      - /opt/influxdb/data_v1:/var/lib/influxdb
      - /opt/influxdb/data_v2:/var/lib/influxdb2
      - /opt/influxdb/config/:/etc/influxdb2

### Steps to reproduce

1. Enable openweather-input in telegraf.conf and enter API key (as well as InfluxDB output)
2. Open Portainer in Webbrowser
3. Restart Telegraf container
4. Open Logfile within Portainer

### Expected behavior

Weather data is saved in Influx-DB

### Actual behavior

Error message is thrown in Portainer log file, no data is written
