### ISSUE TITLE
secret-store for postgresql_extensible and postgresql plugins

### ISSUE THREAD

**Issue by slobsv** [influxdata/telegraf#12578]
### Use Case

feat:secret-store https://github.com/influxdata/telegraf/pull/11232 exists, but has not yet been implemented in the postgresql_extensible and postgresql plugins. It would be awesome if we could avoid putting passwords in plain text in the input plugin configuration files. This secret-store feature should unlock that capability for these plugins. 

### Expected behavior

Set secrets
`telegraf secrets set my-secretstore-id my-secret-key my-secret-value`

Plugin configs
```
[[inputs.postgresql_extensible]]
  address = "host=localhost user=telegraf password=@{my-secretstore-id:my-secret-key} dbname=postgres"
  prepared_statements = true
  [[inputs.postgresql_extensible.query]]
    sqlquery="SELECT * FROM pg_stat_database"
    version=901
    withdbname=false
    tagvalue=""

[[inputs.postgresql]]
  address = "host=localhost user=telegraf password=@{my-secretstore-id:my-secret-key}"
  prepared_statements = true
```

### Actual behavior

You can't use secret-store in the postgresql_extensible and postgresql plugins

### Additional info

I expect the change we need is probably similar to the one made on the sql plugin [here](https://github.com/influxdata/telegraf/pull/11232/files#diff-ba02904434f70d93543c9a2d8e0b724cad553e0d0340791033f942ca6d8702a3L205).

**Comment by powersj** [comment]
next steps: look at migrating postgresql and postgresql_extensible's address to `config.Secret`

**Comment by srebhan** [comment]
@slobsv (and @powersj) both `postgresql` and `postgresql_extensible` already support secrets. However, secrets cannot be embedded into strings! So in your example the secret should be `host=localhost user=telegraf password=my-secret-value dbname=postgres` and the reference should be
```toml
[[inputs.postgresql_extensible]]
  address = "@{my-secretstore-id:my-secret-key}"
  prepared_statements = true
  [[inputs.postgresql_extensible.query]]
    sqlquery="SELECT * FROM pg_stat_database"
    version=901
    withdbname=false
    tagvalue=""

[[inputs.postgresql]]
  address = "@{my-secretstore-id:my-secret-key}"
  prepared_statements = true
```
