### ISSUE TITLE
timestamp modifier not working telegraf 1.25

### ISSUE THREAD

**Issue by diegobelotti** [influxdata/telegraf#12596]
### Relevant telegraf.conf

```toml
[[inputs.tail]]
    name_override = "tail.nginxdocker"
    files = ["/logs/nginx/acc*log"]
    from_beginning = true
    pipe = false
    watch_method = "inotify"
    max_undelivered_lines = 30
    data_format = "grok"
    grok_patterns = ['(%{IP:clientip}|%{HOSTNAME:clienth}) %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp:ts-httpd}\] "%{WORD:verb} %{NOTSPACE:request} HTTP/%{NUMBER:httpversion}" %{NUMBER:response} (%{NUMBER:bytes}|-) "(%{URI:referer}|-)" %{QUOTEDSTRING:agent} %{QUOTEDSTRING:domain} %{QUOTEDSTRING:xport} %{BASE10NUM:trisposta} - - - %{QUOTEDSTRING:ipXfor}']
    [inputs.tail.tags]
        destinazione = "logs"
```

### Logs from Telegraf

```text
2023-02-02T13:41:58Z E! [agent] Error writing to outputs.loki: when writing to [https://loki.mimir.subcom.it:443/loki/api/v1/push] received status code: 400
```

### System info

Telegraf 1.25.0 (git: HEAD@4d17ec79) Rocky Linux release 8.7 (Green Obsidian)

### Steps to reproduce

1. install telegraf using provided instruction
cat <<EOF | sudo tee /etc/yum.repos.d/influxdb.repo
[influxdb]
name = InfluxData Repository - Stable
baseurl = https://repos.influxdata.com/stable/\$basearch/main
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdata-archive_compat.key
EOF

sudo yum install telegraf

(from https://docs.influxdata.com/telegraf/v1.24/install/?t=RedHat+%26amp%3B+CentOS)

2. Configure inputs.tail
3. Send them to loki API

### Expected behavior

Should import lines into Loki DB

\[%{HTTPDATE:timestamp}\] works, without setting the correct timestamp

\[%{HTTPDATE:timestamp:ts-httpd}\] doesn't work, giving error on Loki

### Actual behavior

No import

### Additional info

I see 1.24 as the latest version, but using provided instruction install 1.25

https://docs.influxdata.com/telegraf/v1.24/install/?t=RedHat+%26amp%3B+CentOS
