### ISSUE TITLE
Telegraf install of version 1.25.1 fails GPG check

### ISSUE THREAD

**Issue by dit101** [influxdata/telegraf#12602]
### Relevant telegraf.conf

```toml
/etc/yum.repos.d/influx.repo as follows
[influxdb]
baseurl = https://repos.influxdata.com/centos/$releasever/$basearch/stable
enabled = 1
gpgcheck = 1
gpgkey = https://repos.influxdata.com/influxdb.key
ip_resolve = IPv4
name = InfluxDB Repository - RHEL $releasever
```

### Logs from Telegraf

```text
The GPG keys listed for the "InfluxDB Repository - RHEL 7" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.
```

### System info

Telegraf 1.25.1 Centos 7

### Steps to reproduce

1. yum install telegraf

### Expected behavior

telegraf should install

### Actual behavior

I receive this error
The GPG keys listed for the "InfluxDB Repository - RHEL 7" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.
