### ISSUE TITLE
parser json_v2 and timezones on a unix timestamp

### ISSUE THREAD

**Issue by ccoenen** [influxdata/telegraf#12612]
### Relevant telegraf.conf

```toml
[[inputs.http]]
  urls = [
    "http://shellyplug-1/status/0",
  ]
  timeout = "1s"
  data_format = "json_v2"
  [[inputs.http.json_v2]]
    measurement_name = "shellies"
    timestamp_path = "meters.0.timestamp"
    timestamp_format = "unix"
```

### Logs from Telegraf

```text
(no logs)
```

### System info

Telegraf 1.25.0 (git: HEAD@4d17ec79) within the docker container

### Docker

```yml
version: '3'

services:
  telegraf:
    dns: "(exact content redacted)"
    image: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
     - /share/Container/telegraf:/etc/telegraf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
    command: "telegraf --config-directory /etc/telegraf/telegraf.d"
```

### Steps to reproduce

1. Query a http/json source that includes a correct unix timestamp in seconds
2. configure `timestamp_path` and `timestamp_format="unix"`
3. Your server timestamp might need to be in a particular timezone itself, I am not sure, but my server is in GMT+01:00 / Europe Berlin.

### Expected behavior

I would expect the forwarded timestamp to be exactly the same as the one from the json, with the only difference being that it's nanosecond precision.

### Actual behavior

The output on the line protocol will differ:
* `1675422316` from the json turns into
* `1675425916000000000` on the line protocol. To make this clear: the nanosecond part is expected, but this is also **3600 seconds** later.

### Additional info

This came up during a [debugging of a telegraf example configuration over here](https://codeberg.org/ccoenen/ShellyToInflux/pulls/2#issuecomment-790480) (and following post), in case you want to know more about the background.

**I believe somewhere within the json_v2 plugin, the unix timestamp is somehow converted and then a timezone is applied to it, where it should not.**

**Comment by powersj** [comment]
Hi,

If I take this input:

```json
{
    "temp": 34,
    "timestamp": 1675433639
}
```

With this config:

```toml
[[outputs.file]]
[[inputs.file]]
    files = ["input.json"]
    data_format = "json_v2"
    [[inputs.file.json_v2]]
        timestamp_path = "timestamp"
        timestamp_format = "unix"
        [[inputs.file.json_v2.field]]
            path = "temp"
```

I get this result:

```s
file,host=ryzen temp=34 1675433639000000000
```

This seems to match your expected behavior:

```
Input:  1675433639
Output: 1675433639000000000
```

> my server is in GMT+01:00 / Europe Berlin.

```
❯ date +%s && date
1675434032
Fri Feb  3 07:20:32 AM MST 2023
```

Do you see the same running the above?
