### ISSUE TITLE
[inputs.gnmi] Got empty name

### ISSUE THREAD

**Issue by anpedro** [influxdata/telegraf#12642]
### Relevant telegraf.conf

```toml
[global_tags]
  namespace = "lab"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "20s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  hostname = "telegraf-2"
  omit_hostname = false

[[inputs.gnmi]]
  addresses = ["10.8.90.121:57400"]
  username = "lab"
  password = "lab123"
  encoding = "json_ietf"
  enable_tls = false
  redial = "10s"
  insecure_skip_verify = true
 # name_override = “interfaces”


  [inputs.gnmi.aliases]
    ifcounters = "openconfig:/interfaces/interface/state/counters"


  [[inputs.gnmi.subscription]]
    name = "ifcounters"
    origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/counters/in-pkts"
    subscription_mode = "sample"
    sample_interval = "30s"



[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  insecure_skip_verify = true
  # InfluxDB's admin Token for simplicity
  token = "Qy-c3KkLOG84V_W9QMm867wr5bQ7BGy0Ab0yS0uMauHfsyFR7inEaCtxG_Jtoek9JbQST83H1gCVuecUSTja9A=="
  organization = "Meta"
  bucket = "cisco_mdt_dialin_ios_xr"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
  json_timestamp_units = "1ms"
```

### Logs from Telegraf

```text
Feb 07 07:14:14 facebook-podman-1 telegraf-mdt-dialin[28904]: 2023-02-07T12:14:14Z W! [inputs.gnmi] Got empty metric-name for response, usually indicating
Feb 07 07:14:14 facebook-podman-1 telegraf-mdt-dialin[28904]: configuration issues as the response cannot be related to any subscription.
13
Feb 06 22:12:10 server-1 telegraf-mdt-dialin[26391]: 2023-02-07T03:12:10Z D! [outputs.file] Could not serialize metric: invalid name
Feb 06 22:12:10 server-1 telegraf-mdt-dialin[26391]: 2023-02-07T03:12:10Z D! [outputs.file] Could not serialize metric: invalid name
Feb 06 22:12:10 server-1 telegraf-mdt-dialin[26391]: 2023-02-07T03:12:10Z D! [outputs.file] Could not serialize metric: invalid name
```

### System info

Rocky Linux release 9.1 (Blue Onyx)

### Docker

this is running inside docker container 

### Steps to reproduce

start telegraf container with the above configuration.

I am subscribing to an IOS XR router. 

### Expected behavior

this should work as I am configuring the name in the telegraf conf file. 

### Actual behavior

getting the error shown above.

**Comment by powersj** [comment]
> [inputs.gnmi] Got empty metric-name for response, usually indicating configuration issues as the response cannot be related to any subscription.

There should be a longer message here as this message was added in https://github.com/influxdata/telegraf/commit/d10ab3a417895c7e4fe1dc863f5ba808fb3cda18

> 13

Was this the response data that was printed out? 
What is the exact device model you are using and OS version?

**Comment by anpedro** [comment]
hello @powersj  - thanks for looking into this.

Yes, that's the exact message I get:

// Define the warning to show if we cannot get a metric name.
const emptyNameWarning = `Got empty metric-name for response, usually indicating
configuration issues as the response cannot be related to any subscription.
Please open an issue on https://github.com/influxdata/telegraf including your
device model and the following response data:
%+v
This message is only printed once.`

then I see the below logs right after:
Feb 06 22:12:10 server-1 telegraf-mdt-dialin[26391]: 2023-02-07T03:12:10Z D! [outputs.file] Could not serialize metric: invalid name
Feb 06 22:12:10 server-1 telegraf-mdt-dialin[26391]: 2023-02-07T03:12:10Z D! [outputs.file] Could not serialize metric: invalid name
Feb 06 22:12:10 server-1 telegraf-mdt-dialin[26391]: 2023-02-07T03:12:10Z D! [outputs.file] Could not serialize metric: invalid name

the device is Cisco 8000 and running IOS XR 754.

Can you spot anything wrong in my telegraf.conf ?

**Comment by powersj** [comment]
@srebhan - any thoughts on this one with the short response data?

**Comment by anpedro** [comment]
I can share more logs or discuss on a call, if needed.

**Comment by srebhan** [comment]
@anpedro which version of Telegraf are you using?

**Comment by srebhan** [comment]
Ok. Can you test the binary in #12512 with setting `trace = true` i.e.
```toml
[global_tags]
  namespace = "lab"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "20s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  hostname = "telegraf-2"
  omit_hostname = false

[[inputs.gnmi]]
  addresses = ["10.8.90.121:57400"]
  username = "lab"
  password = "lab123"
  encoding = "json_ietf"
  enable_tls = false
  redial = "10s"
  insecure_skip_verify = true
  trace = true
 
  [[inputs.gnmi.subscription]]
    name = "ifcounters"
    origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/counters/in-pkts"
    subscription_mode = "sample"
    sample_interval = "30s"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```
