### ISSUE TITLE
Otel output is not setting the start time on non-gauge values

### ISSUE THREAD

**Issue by timperrett** [influxdata/telegraf#12664]
### Relevant telegraf.conf

```toml
[agent]
  interval = "30s"

[[inputs.mem]]

[[outputs.file]]
  files = ["stdout"]

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  core_tags = false

[[inputs.diskio]]
  devices = ["nvme*"]
  device_tags = ["ID_FS_LABEL", "ID_SERIAL_SHORT"]

[[outputs.opentelemetry]]
  service_address = "<service provider endpoint>"
  tls_ca = "/etc/ssl/certs/ca-certificates.crt"

  [outputs.opentelemetry.attributes]
    "service.name" = "<redacted>"

  [outputs.opentelemetry.headers]
    lightstep-access-token = "<redacted>"
```

### Logs from Telegraf

```text
> cpu,cpu=cpu-total,host=REDACTED,location=sjc usage_guest=0,usage_guest_nice=0,usage_idle=99.93757808692158,usage_iowait=0,usage_irq=0,usage_nice=0,usage_softirq=0,usage_steal=0,usage_system=0.062421972666786965,usage_user=0 1675722610000000000
> diskio,ID_SERIAL_SHORT=50FF306WFY8L,host=REDACTED,location=sjc,name=nvme0n1p2 io_time=5201120i,iops_in_progress=0i,merged_reads=0i,merged_writes=5260106i,read_bytes=65475343360i,read_time=2442680i,reads=1441098i,weighted_io_time=30143220i,write_bytes=1147246014464i,write_time=51269676i,writes=15001487i 1675722610000000000
```

### System info

1.25.0

### Steps to reproduce

1. Configure telegraf per the supplied configuration
2. Fill in the otel endpoint information
3. All values are sent to the remote API, but not all are valid. This can result in only gauges being displayed by your otel compliant vendor (behavior depends on your otel service vendor)

### Expected behavior

Metrics of all telegraf types are converted to the otel type such that the start time represents the intended semantics per the otel spec.

### Actual behavior

This appears to be due to the conversion of telegraf metrics to otel ones such that sum types lack a `StartTimeUnixNano`. I'm not at all familiar with the code base, however 😄
