### ISSUE TITLE
My script works when I run it by hand, but not when Telegraf is running as a service

### ISSUE THREAD

**Issue by rwb196884** [influxdata/telegraf#12689]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  commands = ["sensors | grep Core | awk '{print \$1 substr(\$2, 1, length(\$2)-1) \\"=\\" substr(\$3, 2, length(\$3)-3) }'"]
  timeout = "3s"
  interval = "34s"
  name_suffix = "_CPU_temp"
  data_format = "influx"
  [inputs.exec.tags]
    bucket = "system"
```

### Logs from Telegraf

```text
E! [telegraf] Error running agent: error loading config file /etc/telegraf/telegraf.conf: error parsing data: line 3197: invalid TOML syntax
```

### System info

Telegraf 1.25.0 (git: HEAD@4d17ec79)  Debian 4.19.269-1 (2022-12-20) x86_64 GNU/Linux

### Steps to reproduce

Add the above config.

### Expected behavior

It works.

### Actual behavior

It doesn't work.

### Additional info

My guess is that it's probably something to do with quoting quotes and backslashes but I think I've tried about every combination.

This works:
```
c="sensors | grep Core | awk '{print \$1 substr(\$2, 1, length(\$2)-1) \"=\" substr(\$3, 2, length(\$3)-3) }'"; eval $c
```
