### ISSUE TITLE
My script (another one) works when I run it by hand, but not when Telegraf is running as a service

### ISSUE THREAD

**Issue by rwb196884** [influxdata/telegraf#12706]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
     commands = ["python -c \"import sys; sys.path.append('/usr/local/lib/python2.7'); import sun; print sun.getSEA(52.6476943, -2.47296, 0)\" | awk '{ print \"sea sea=\" $0 }' | tee -a /root/sea"]
     #commands = ["echo \"1\" | awk '{ print \"one one=\" $0 }' | tee -a /root/sea"]
     timeout = "3s"
     interval = "1m"
     data_format = "influx"
     [inputs.exec.tags]
       bucket = "solar"
```

### Logs from Telegraf

```text
E! [inputs.exec] Error in plugin: metric parse error: expected tag at 1:15: "-40.1217819452"
```

### System info

Telegraf 1.25.0 (git: HEAD@4d17ec79) Debian 4.19.269-1 (2022-12-20) x86_64 GNU/Linux

### Steps to reproduce

1. Add a `inputs.exec`
2. Restart telegraf

### Expected behavior

It works.

### Actual behavior

It doesn't work.

### Additional info

If I copy the output of my script into the Influx website UI then it loads, so I think this is a bug in `inputs.exec`
```
# python -c "import sys; sys.path.append('/usr/local/lib/python2.7'); import sun; print sun.getSEA(52.001, -2.001, 0)" | awk -v d="$(date +%s%N)" '{ print "sea sea=" $0 " " d }' | tee -a /root/sea
sea sea=-40.1217819452 1676673974778859342
```

Same with
```
commands = ["echo \"1\" | awk '{ print \"one one=\" $0 }' | tee -a /root/sea"]
```

And again the output
```
# echo \"1\" | awk '{ print "one one=" $0 }' | tee -a /root/sea
one one="1"
```
loads fine in the web UI.

No output from the `tee` (the file is `chmod a+rw`) but on the ohter hand the error message contains the value; very strange.
