### ISSUE TITLE
vsphere plugin: Unable to find metric name for id 608

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#12716]
### Relevant telegraf.conf

```toml
[[inputs.vsphere]]
  interval = "60s"											# default: 180s
  vcenters = [ 	
				"https://vcXXX/sdk",
				"https://vcXXX/sdk"
			 ]
			
  username = "xxx"
  password = "xxx"

  insecure_skip_verify = true

  # Exclude all historical metrics
  datastore_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]

  collect_concurrency = 5									# default: 5
  discover_concurrency = 5									# default: 5
```

### Logs from Telegraf

```text
[inputs.vsphere] Unable to find metric name for id 608. Skipping!
```

### System info

Telegraf 1.25.2-67c08c51 on Windows

### Steps to reproduce

1. Apply config
2. execute telegraf
3.
...

### Expected behavior

metrics ingested

### Actual behavior

metrics not ingested
