### ISSUE TITLE
Weird behaviour with JSON-transformation after first collection interval

### ISSUE THREAD

**Issue by teereks** [influxdata/telegraf#12734]
### Relevant telegraf.conf

```toml
[agent]
  omit_hostname = true

###############################################################################
[[inputs.file]]
  files = ["./inputdata.influx"]
  data_format = "influx"

###############################################################################

[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
  use_batch_format = true

  json_transformation = '''
  {
      "valueRows": metrics{$string(timestamp): fields.value[]} ~> $each(function($v, $k) {
          {
              "timestamp": $number($k),
              "values": $v
          }
      })
  }
  '''
```

### Logs from Telegraf

```text
2023-02-17T10:45:13Z E! [outputs.file::file-debug] Could not serialize metric: function "each" takes 2 argument(s), got 3
2023-02-17T10:45:23Z E! [outputs.file::file-debug] Could not serialize metric: function "each" takes 2 argument(s), got 4
2023-02-17T10:45:33Z E! [outputs.file::file-debug] Could not serialize metric: function "each" takes 2 argument(s), got 5
2023-02-17T10:45:43Z E! [outputs.file::file-debug] Could not serialize metric: function "each" takes 2 argument(s), got 6
```

### System info

Telegraf 1.25.0, Debian 11.6

### Steps to reproduce

1. Run the given configuration (do not use the --once flag).
2. Wait for `Telegraf` to run the first collection interval. Result should be written successfully to `stdout`.
3. Wait for the second collection interval. Write to `stdout` will fail, error is produced.
4. Let `Telegraf` to run for more collection intervals. Information in the error-message will change on every collection attempt, indicating that more and more arguments are given to the `$each` -function.
...

### Expected behavior

This configuration is expected to produce the same result (successful JSON-transformation) on every single collection interval, no matter how many times you let the collection run. In this case the input-data doesn't change so the write to `stdout` should be identical between all the collections.

### Actual behavior

Currently `Telegraf` manages to run the collection successfully only once. All the collections after the initial one will fail. The information given in the error-message will change on every failed collection, just like shown in the error-logs given in this issue.

### Additional info

- Previous conversation around this issue on InfluxData Community Forums can be seen here: https://community.influxdata.com/t/telegraf-weird-behaviour-with-json-transformation-after-first-collection-interval/28671

- JSONata playground example can be found here: https://try.jsonata.org/SgXkPh4LO
This shows the desired result for the JSON-transformation, but the query should be valid JSONata version 1.5.4 query anyway, so it shouldn't be the issue here.

Here is the example data used to reproduce error. This can be used as the content of `inputdata.influx` which was referenced in the configuration given in this issue:

```
data,key=FII-ACT value=3751.3 1676285135457000000
data,key=FII-SET value=2383.5 1676285135457000000
data,key=CMD value=-14.478 1676285135457000000
data,key=AQP-FII_S value=2620.9 1676285135457000000
data,key=AQP_RPM value=305.07 1676285135457000000
data,key=N2-ACTUAL value=1339.8 1676285135457000000
data,key=P-CORR value=234.77 1676285135457000000
data,key=MIN-RPM value=1850.6 1676285135457000000
data,key=N1-RPM value=-2867.8 1676285135457000000
data,key=LOCAL value=1 1676285135457000000
data,key=CL-TEMP-H value=0 1676285135457000000
data,key=FAILURE value=1 1676285135457000000
data,key=WARNING value=1 1676285135457000000
data,key=SC-MODE value=1 1676285135457000000
data,key=CL-EN-P value=0 1676285135457000000
data,key=Modbus_register_20009_6 value=1 1676285135457000000
data,key=Modbus_register_20009_7 value=1 1676285135457000000
data,key=Modbus_register_20009_8 value=1 1676285135457000000
data,key=Modbus_register_20009_9 value=1 1676285135457000000
data,key=Modbus_register_20009_10 value=1 1676285135457000000
data,key=Modbus_register_20009_11 value=1 1676285135457000000
data,key=Modbus_register_20009_12 value=1 1676285135457000000
data,key=Modbus_register_20009_13 value=1 1676285135457000000
data,key=Modbus_register_20009_14 value=0 1676285135457000000
data,key=Modbus_register_20009_15 value=1 1676285135457000000
data,key=FII-ACT value=2064.8 1676285140456000000
data,key=FII-SET value=441.1 1676285140456000000
data,key=CMD value=-30.786 1676285140456000000
data,key=AQP-FII_S value=5086.6 1676285140456000000
data,key=AQP_RPM value=275.56 1676285140456000000
data,key=N2-ACTUAL value=2831.5 1676285140456000000
data,key=P-CORR value=204.31 1676285140456000000
data,key=MIN-RPM value=-3214 1676285140456000000
data,key=N1-RPM value=2238.4 1676285140456000000
data,key=LOCAL value=0 1676285140456000000
data,key=CL-TEMP-H value=1 1676285140456000000
data,key=FAILURE value=1 1676285140456000000
data,key=WARNING value=1 1676285140456000000
data,key=SC-MODE value=1 1676285140456000000
data,key=CL-EN-P value=0 1676285140456000000
data,key=Modbus_register_20009_6 value=0 1676285140456000000
data,key=Modbus_register_20009_7 value=1 1676285140456000000
data,key=Modbus_register_20009_8 value=0 1676285140456000000
data,key=Modbus_register_20009_9 value=0 1676285140456000000
data,key=Modbus_register_20009_10 value=1 1676285140456000000
data,key=Modbus_register_20009_11 value=0 1676285140456000000
data,key=Modbus_register_20009_12 value=0 1676285140456000000
data,key=Modbus_register_20009_13 value=0 1676285140456000000
data,key=Modbus_register_20009_14 value=0 1676285140456000000
data,key=Modbus_register_20009_15 value=0 1676285140456000000
```
