### ISSUE TITLE
inputs.ethtool :: use only physical interfaces

### ISSUE THREAD

**Issue by adriansev** [influxdata/telegraf#12737]
### Relevant telegraf.conf

```toml
[[inputs.ethtool]]
down_interfaces = "skip"
normalize_keys = ["snakecase", "trim", "lower", "underscore"]
```

### Logs from Telegraf

```text
messages of type:
Feb 24 14:54:30 fst05.spacescience.ro telegraf[13404]: 2023-02-24T14:54:30+02:00 E! [inputs.ethtool] Error in plugin: enp65s0f1.200 stats: operation not supported
```

### System info

telegraf 1.25.2, centos 7, alma 9, fedora 36 and 37

### Steps to reproduce

use inputs.ethtool on machines with bridges, vlans or wireguard endpoints

### Expected behavior

no spamming messages like in the above log excerpt

### Actual behavior

only physical interfaces should be queried by ethtool
the bash version for finding physical interfaces would be:
```
for eth_path in $(find /sys/class/net -type l); do PHYS=$(echo $(realpath ${eth_path}| grep -v virtual)); [[ -n ${PHYS} ]] && echo $(basename ${PHYS}) ; done
```

these can be further filtered by checking if they are connected
