### ISSUE TITLE
Missing metrics for Docker input plugin

### ISSUE THREAD

**Issue by Camiyo** [influxdata/telegraf#12738]
### Use Case

I installed Telegraf on my Swarm node with the Docker Input Plugin and the Prometheus Outputs Plugin.

I'm trying to create Prometheus alerts rules from the templates on the site: [awesome.prometeus](https://awesome-prometheus-alerts.grep.to/rules.html#docker-containers-1)

I would like to create : 
- 1 alert when a "container is absent" 
- 1 alert when a "container is killed" 

Like those (but for Kubernetes) : 

```
  # This rule can be very noisy in dynamic infra with legitimate container start/stop/deployment.
  - alert: ContainerAbsent
    expr: absent(container_last_seen)
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Container absent (instance {{ $labels.instance }})
      description: "A container is absent for 5 min\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

```
  # This rule can be very noisy in dynamic infra with legitimate container start/stop/deployment.
  - alert: ContainerKilled
    expr: time() - container_last_seen > 60
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Container killed (instance {{ $labels.instance }})
      description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
```

But I can't reproduce the equivalent with Telegraf metrics because there is no "container_last_seen" metric.

### Expected behavior

Have a new metric like "container_last_seen"

### Actual behavior

Missing some better metrics for Docker
