### ISSUE TITLE
processors.converter - convert time 

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#12746]
### Use Case

The idea is to improve `processors.converter` and allow it to manage timestamps.
Currently, there is no "easy" way to override/set the timestamp of a point by getting it from a tag/field, the only option is to use `processors.starlark`.

This is a rare use case, but still, I think it's worth having it

### Expected behavior

Being able to override/set the time of a point base on a field/tag value using `processors.converter`.

As done for "generic" input plugins I just expect to specify the source tag/field and time format

### Actual behavior

The only way to override/set the time of a point base on a field/tag value is to use `processors.starlark`

**Comment by powersj** [comment]
The current `processors.converter` config to convert a field looks like:

```toml
  ## Fields to convert
  ##
  ## The table key determines the target type, and the array of key-values
  ## select the keys to convert.  The array may contain globs.
  ##   <target-type> = [<field-key>...]
  [processors.converter.fields]
    measurement = []
    tag = []
    string = []
    integer = []
    unsigned = []
    boolean = []
    float = []
```

If I had a metric like the following, and I would want to convert the `time` field to a timestamp.

```s
metric,name=hosta time=1677597608,temp=64
```

I presume we would want to add two new options:

```toml
    timestamp = ""
    timestamp_format = ""
```

Such that I could say:

```toml
[[processors.converter]]
  [processors.converter.fields]
    timestamp = "time"
    timestamp_format = "unix"
```

Where timestamp is the name of the field to get the time from and the timestamp_format is the usually formatting that should be applied. Unlike the other options time would not be an array but a single field since a metric cannot have more than one timestamp.

Does this look like what you would expect?

Would we want this available under `[processors.converter.tags]` as well? Or tell the user to first convert to a field?
