### ISSUE TITLE
[json_v2 Paser] How do I configure the time format "2023-03-01T00:00:42.586+0800"

### ISSUE THREAD

**Issue by Guomz86** [influxdata/telegraf#12774]
### Use Case

input:
{
    "timestamp":"2023-03-01T00:00:42.586+0800"
}
paser:
[[inputs.mqtt_consumer.json_v2]]
  timestamp_path = "timestamp"
  timestamp_format = "UTC+0800"
  timestamp_timezone = "Asia/Shanghai"

### Expected behavior

...

### Actual behavior

cannot paser

**Comment by powersj** [comment]
Hi,

Please ask questions like this on our [Community Slack](https://influxdata.com/slack) or [Community Forums](https://community.influxdata.com/). The GitHub issues are for actually issues, not support.

Given this data:

```json
{
	"host": "host1",
	"temp": 0,
	"timestamp": "2023-03-01T00:00:42.586+0800"
}
```

and this config which uses [go standard time]() to set the format:

```toml
[agent]
   precision = "1ms"

[[inputs.file]]
    files = ["data"]
    data_format = "json_v2"

    [[inputs.file.json_v2]]
        measurement_name = "data"

        timestamp_path = "timestamp"
        timestamp_format = "2006-01-02T15:04:05.000-0700"
        timestamp_timezone = "Asia/Shanghai"

        [[inputs.file.json_v2.field]]
            path = "temp"

        [[inputs.file.json_v2.tag]]
            path = "host"

[[outputs.file]]
```


```s
data,host=host1 temp=0 1677600042586000000
```

You can play with the format option more on the [go playground](https://goplay.tools/snippet/hi9GIOG_gVQ).
