### ISSUE TITLE
Telegraf Error FATAL -- failed to create Watcher

### ISSUE THREAD

**Issue by rsarpal** [influxdata/telegraf#12771]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "3s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = false

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 200

  ## Maximum number of unwritten metrics per output.
  metric_buffer_limit = 1000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "5s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "15s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  # quiet = false

  ## Log file name, the empty string means to log to stderr.
  #logfile = "/var/log/telegraf/telegraf.log"

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

 

## Added C Telegraf
[[outputs.influxdb]]
 namepass=["j_tps_*","j_Results_*"]
 tagexclude=["Environment","Datacenter","Layer","Server"]
 ## urls will be written to each interval.
 urls = [ "https://influxdb.xxx:8086" ]
 database = "jm1"
 skip_database_creation = true
 ## HTTP Basic Auth
 username = "xxx"
 password = "xxx"
 ## Optional TLS Config for use on HTTP connections.
 #tls_ca = "/etc/telegraf/CA_Influx_AWS.crt"
 insecure_skip_verify = true

## Added - S telegraf
[[outputs.influxdb]]
  namepass=["s_telegraf_*","a_telegraf_*"]
  tagexclude=["Environment","Datacenter","Layer","Server"]
  ## urls will be written to each interval.
  urls = [ "https://influxdb.xxx:8086" ]
  database = "jm"
  retention_policy="twenty_weeks"
  skip_database_creation = true
  ## HTTP Basic Auth
  username = "xxx"
  password = "xxx"
  ## Optional TLS Config for use on HTTP connections.
  #tls_ca = ""
  insecure_skip_verify = true



###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

 
[[inputs.tail]]
  name_prefix="j_tps_"
  data_format = "csv"
  files = ["/z/Logs/tps.csv"]
  csv_delimiter = ","
  csv_timestamp_column = "timeStamp"
  csv_timestamp_format = "unix_ms"
  csv_header_row_count = 1
  csv_tag_columns = ["label"]
  csv_column_names = ["timeStamp","elapsed","label","responseCode","threadName","success","bytes","sentBytes","grpThreads","allThreads","Latency","IdleTime","Connect"]
  csv_column_types = ["string","string","string","string","string","string","int","int","int","int","int","int","int"]
  from_beginning = true


## Added C Telegraf
[[inputs.tail]]
  ##
  name_prefix="j_Results_"
  data_format = "csv"
  files = ["/z/Logs/Results.csv"]
  csv_timestamp_column = "timeStamp"
  csv_delimiter = ","
  csv_timestamp_format = "unix_ms"
  csv_header_row_count = 1
  csv_tag_columns = ["label","responseCode"]
  csv_column_names = ["timeStamp","elapsed","label","responseCode","responseMessage","threadName","dataType","success","failureMessage","bytes","sentBytes","grpThreads","allThreads","URL","Latency","IdleTime","Connect"]
  csv_column_types = ["string","string","string","int","string","string","string","string","string","int","int","int","int","string","int","int","int"]
 # from_beginning = true

#
## Added  - S Telegraf 
 [[inputs.tail]]
  name_prefix="s_telegraf_"
  data_format = "csv"
  files = ["/xxx/Results.csv"]
  csv_timestamp_column = "timeStamp"
  csv_delimiter = ","
  csv_timestamp_format = "unix_ms"
  csv_header_row_count = 1
  csv_tag_columns = ["label","threadName","Exporter_NameOfTest","Exporter_TestCategory","TestScenario"]
  csv_column_names = ["timeStamp","elapsed","label","responseCode","responseMessage","threadName","dataType","success","failureMessage","bytes","sentBytes","grpThreads","allThreads","URL","Latency","IdleTime","Connect","Exporter_NameOfTest","Exporter_TestCategory","TestScenario","Username"]
  csv_column_types = ["string","string","string","int","string","string","string","string","string","int","int","int","int","string","int","int","int","string","string","string","string"]
  from_beginning = true
  [inputs.tail.multiline]
   pattern = '^[\s\*\/]'
   match_which_line = "previous"

## Added  - S1 Telegraf 
 [[inputs.tail]]
  name_prefix="s_telegraf_"
  data_format = "csv"
  files = ["/yyy/Results.csv"]
  csv_timestamp_column = "timeStamp"
  csv_delimiter = ","
  csv_timestamp_format = "unix_ms"
  csv_header_row_count = 1
  csv_tag_columns = ["label","threadName","Exporter_NameOfTest","Exporter_TestCategory","TestScenario"]
  csv_column_names = ["timeStamp","elapsed","label","responseCode","responseMessage","threadName","dataType","success","failureMessage","bytes","sentBytes","grpThreads","allThreads","URL","Latency","IdleTime","Connect","Exporter_NameOfTest","Exporter_TestCategory","TestScenario","Username"]
  csv_column_types = ["string","string","string","int","string","string","string","string","string","int","int","int","int","string","int","int","int","string","string","string","string"]
  from_beginning = true
  [inputs.tail.multiline]
   pattern = '^[\s\*\/]'
   match_which_line = "previous"

## Added  - S2 Telegraf 
 [[inputs.tail]]
  name_prefix="s_telegraf_"
  data_format = "csv"
  files = ["/zzz/Results.csv"]
  csv_timestamp_column = "timeStamp"
  csv_delimiter = ","
  csv_timestamp_format = "unix_ms"
  csv_header_row_count = 1
  csv_tag_columns = ["label","threadName","Exporter_NameOfTest","Exporter_TestCategory","TestScenario"]
  csv_column_names = ["timeStamp","elapsed","label","responseCode","responseMessage","threadName","dataType","success","failureMessage","bytes","sentBytes","grpThreads","allThreads","URL","Latency","IdleTime","Connect","Exporter_NameOfTest","Exporter_TestCategory","TestScenario","Username"]
  csv_column_types = ["string","string","string","int","string","string","string","string","string","int","int","int","int","string","int","int","int","string","string","string","string"]
  from_beginning = true
  [inputs.tail.multiline]
   pattern = '^[\s\*\/]'
   match_which_line = "previous"

## Added - A1 telegraf
 [[inputs.tail]]
  name_prefix="a_telegraf_"
  data_format = "csv"
  files = ["/a/Results.csv"]
  csv_timestamp_column = "timeStamp"
  csv_delimiter = ","
  csv_timestamp_format = "unix_ms"
  csv_header_row_count = 1
  csv_tag_columns = ["label","threadName","Exporter_NameOfTest","Exporter_TestCategory","TestScenario"]
  csv_column_names = ["timeStamp","elapsed","label","responseCode","responseMessage","threadName","dataType","success","failureMessage","bytes","sentBytes","grpThreads","allThreads","URL","Latency","IdleTime","Connect","Exporter_NameOfTest","Exporter_TestCategory","TestScenario","Username"]
  csv_column_types = ["string","string","string","int","string","string","string","string","string","int","int","int","int","string","int","int","int","string","string","string","string"]
  from_beginning = true
  [inputs.tail.multiline]
   pattern = '^[\s\*\/]'
   match_which_line = "previous"
```

### Logs from Telegraf

```text
telegraf --debug
2023-03-01T15:01:30Z I! Using config file: /etc/telegraf/telegraf.conf
2023-03-01T15:01:30Z I! Starting Telegraf 1.25.2
2023-03-01T15:01:30Z I! Available plugins: 228 inputs, 9 aggregators, 26 processors, 21 parsers, 57 outputs, 2 secret-stores
2023-03-01T15:01:30Z I! Loaded inputs: tail (6x)
2023-03-01T15:01:30Z I! Loaded aggregators:
2023-03-01T15:01:30Z I! Loaded processors:
2023-03-01T15:01:30Z I! Loaded secretstores:
2023-03-01T15:01:30Z I! Loaded outputs: influxdb (2x)
2023-03-01T15:01:30Z I! Tags enabled: Datacentre=xxx Environment=xx Layer=JMeter Server=xx host=abc
2023-03-01T15:01:30Z I! [agent] Config: Interval:3s, Quiet:false, Hostname:"abc", Flush Interval:10s
2023-03-01T15:01:30Z D! [agent] Initializing plugins
2023-03-01T15:01:30Z D! [agent] Connecting outputs
2023-03-01T15:01:30Z D! [agent] Attempting connection to [outputs.influxdb]
2023-03-01T15:01:30Z D! [agent] Successfully connected to outputs.influxdb
2023-03-01T15:01:30Z D! [agent] Attempting connection to [outputs.influxdb]
2023-03-01T15:01:30Z D! [agent] Successfully connected to outputs.influxdb
2023-03-01T15:01:30Z D! [agent] Starting service inputs
2023-03-01T15:01:30Z D! [inputs.tail] Tail added for "/xxx/Results.csv"
2023-03-01T15:01:30Z D! [inputs.tail] Tail added for "/yyy/Results.csv"
2023/03/01 17:01:30 FATAL -- failed to create Watcher
goroutine 141 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/tail/util.Fatal({0x6229266?, 0x0?}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20210707231403-b283181d1fa7/util/util.go:22 +0x97
github.com/influxdata/tail/watch.(*InotifyTracker).run(0xc001a42780)
	/go/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20210707231403-b283181d1fa7/watch/inotify_tracker.go:219 +0x6e
created by github.com/influxdata/tail/watch.glob..func1
	/go/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20210707231403-b283181d1fa7/watch/inotify_tracker.go:54 +0x16e
```

### System info

 Operating System: Red Hat Enterprise Linux 8.5 (Ootpa),  Kernel: Linux 4.18.0-425.3.1.el8.x86_64 , telegraf.x86_64  1.25.2-1

### Steps to reproduce

1. Running telegraf --test or telegraf --debug throws the error
2.
3.
...

### Expected behavior

No error 

### Actual behavior

2023/03/01 17:01:30 FATAL -- failed to create Watcher
goroutine 141 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/influxdata/tail/util.Fatal({0x6229266?, 0x0?}, {0x0, 0x0, 0x0})
	/go/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20210707231403-b283181d1fa7/util/util.go:22 +0x97
github.com/influxdata/tail/watch.(*InotifyTracker).run(0xc001a42780)
	/go/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20210707231403-b283181d1fa7/watch/inotify_tracker.go:219 +0x6e
created by github.com/influxdata/tail/watch.glob..func1
	/go/pkg/mod/github.com/influxdata/tail@v1.0.1-0.20210707231403-b283181d1fa7/watch/inotify_tracker.go:54 +0x16e
