### ISSUE TITLE
Add processor to rename tag into fields

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#12770]
### Use Case

Prometheus plugin reports metric labels as tags. Not all of them (actually very little of them) should form a group key in the influx db. Things like kubernetes pod `uid` or `container_id` are not "primary key" and should be just fields, not tags. These change often and cause unnecessary cardinality problems on Influx side.

One way would be to have this capability added just to the prometheus plugin, but IMHO having a generic processor to do that makes more sense.

### Expected behavior

 There are many measurements many should share common set of tags, so something like `tag_keep`   processor option to allowlist tags to keep as tags and "demote" rest of tags to fields will do the trick for my usecase.

### Actual behavior

-

**Comment by powersj** [comment]
Hi,

The [converter processor](https://github.com/influxdata/telegraf/blob/master/plugins/processors/converter/README.md)  can already convert a tag into a field and it even takes globs. The first README example shows a tag to a string field.

Here is an example of a numeric tag to field:

```toml
[[outputs.file]]

[[inputs.exec]]
  commands = ["echo metric,id=1 value=42i"]
  data_format = "influx"

[[processors.converter]]
  [processors.converter.tags]
    integer = ["id"]
```

```diff
+ metric,host=ryzen,id=1 value=42i 1677677887000000000
- metric,host=ryzen value=42i,id=1i 1677677946000000000
```

If you strongly need the ability to have a list of tags to keep and make everything else a field, then I would suggest using starlark to filter those out.
