### ISSUE TITLE
inputs.prometheus require cluster level permissions even when scoped to a namespace

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#12780]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
monitor_kubernetes_pods = true
monitor_kubernetes_pods_namespace = "ns1"
monitor_kubernetes_pods_port = 7354
```

### Logs from Telegraf

```text
E0302 16:25:26.890248       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Pod: failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:ns1:telegraf-prometheus" cannot list resource "pods" in API group "" at the cluster scope
```

### System info

1.25.1

### Steps to reproduce

Grant kubernetes service account used to run telegraf  followig role (important, NOT cluster role)

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: telegraf-prometheus
  namespace: n1
  rules:
  - verbs:
      - list
      - watch
      - get
    apiGroups:
      - ''
    resources:
      - namespaces
      - pods
 ```
 
 Run telegraf with config from the above in the namespace `ns1`

### Expected behavior

Unable to list pods

### Actual behavior

Scrapes metrics successfully
