### ISSUE TITLE
deprecated warning when "brokers" used for inputs.amqp_consumer

### ISSUE THREAD

**Issue by patman-cp** [influxdata/telegraf#12811]
### Relevant telegraf.conf

```toml
[[inputs.amqp_consumer]]
  brokers = ["amqp://queue:5672"]
  exchange = "metrics"
  exchange_durability = "transient"
  queue = "telegraf"
  queue_durability = "transient"
  binding_key = "#"
  data_format = "influx"
```

### Logs from Telegraf

```text
telegraf        | 2023-03-07T17:02:36Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf        | 2023-03-07T17:02:36Z W! DeprecationWarning: Option "url" of plugin "inputs.amqp_consumer" deprecated since version 1.7.0 and will be removed in 2.0.0: use 'brokers' instead
```

### System info

Telegraf 1.25.3

### Docker

I know this does not completely work, but I used this docker-compose.yaml to reproduce the problem:

```
version: '3'
services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb
    volumes:
      - influxdbv2:/root/.influxdbv2
    ports:
      - "8086:8086"
  influxdb_cli:
    links:
      - influxdb
    image: quay.io/influxdb/influxdb:v2.0.3
    container_name: influxdb_cli
    entrypoint: influx setup --bucket telegraf -t secretToken -o Stangneth --username=admin --password=Passsw0rd! --host=http://influxdb:8086 -f
    restart: on-failure:10
    depends_on:
      - influxdb
  queue:
    image: rabbitmq
    ports:
      - 127.0.0.1:5672:5672
  telegraf:
    image: telegraf
    container_name: telegraf
    links:
      - influxdb
    volumes:
      - /home/pmansfield/cstor40/issues_bugs.d/sap-1810-telegraf-url-deprecated.d/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb_cli
volumes:
  influxdbv2:
```

### Steps to reproduce

1. Use a telegraf.conf with "brokers" per the supplied telegraf.conf
2. Start telegraf

### Expected behavior

No warnings about url vs brokers.

### Actual behavior

This warning is output, even though it's using `brokers`:

```
telegraf        | 2023-03-07T17:02:36Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf        | 2023-03-07T17:02:36Z W! DeprecationWarning: Option "url" of plugin "inputs.amqp_consumer" deprecated since version 1.7.0 and will be removed in 2.0.0: use 'brokers' instead
```
