### ISSUE TITLE
lustre: please add /sys/fs/lustre/health_check

### ISSUE THREAD

**Issue by lukeyeager** [influxdata/telegraf#12836]
### Use Case

I would like to switch from the defunct [HewlettPackard/lustre_exporter](https://github.com/HewlettPackard/lustre_exporter) to telegraf, but the fact that the health of the lustre storage targets isn't monitored is a blocker.

### Expected behavior

I would expect to see something like the following in `:9273/metrics`:
```
# HELP lustre2_health Current health check status
# TYPE lustre2_health gauge
lustre2_health 1
```

### Actual behavior

Instead, I don't see any monitoring of the current health status

### Additional info

If it helps, here's how lustre_exporter added it: https://github.com/HewlettPackard/lustre_exporter/commit/762b9838152323b942ac74737e7ec8d5099b88ac

**Comment by powersj** [comment]
Hi,

After a quick read, the current `lustre2` input plugin, I assume this is what you are using, looks to monitor lustre stats via files under `/proc/fs/lustre/*/stats`.

> /sys/fs/lustre/health_check

Is this different than what is [documented in this paper](https://cug.org/5-publications/proceedings_attendee_lists/CUG11CD/pages/1-program/final_program/Wednesday/13A-Hill-Paper.pdf), namely `/proc/fs/lustre/healthcheck`? Does one exist in some versions and not others?

Based on the HP code, it looks like if this file contains "healthy", then all is well and a 1 is returned. And if anything else is read, then return 0. Can you confirm that is the intended behavior as well?

If so, you could easily do this today with:

```toml
[[inputs.file]]
    name_override = "/sys/fs/lustre/health_check"
    files = ["health_check"]
    data_format = "value"
    data_type = "string"
```

```s
lustre2_health value="healthy" 1678477350000000000
```

And if you wanted a number of `1` for healthy and `0` for everything else:

```toml
[[processors.enum]]
  [[processors.enum.mapping]]
    namepass = "lustre2_health"
    field = "value"
    dest = "value"
    default = 0
    [processors.enum.mapping.value_mappings]
      healthy = 1
```
```s
lustre2_health value=1i 1678477561000000000
```
