### ISSUE TITLE
Allow Credentials to be read from files

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/telegraf#12848]
## Description

It is quite a common practice, especially in containerized environments, to let the application read credentials from files. The credentials DO NOT need to be encrypted in such cases. 

Many databases e.g. MariaDB enable this feature when using it as docker container to mount database credentials as a file that can be used to initialize the container. Similar options are available for tools like Portainer.

A useful case can be made when using `telegraf` as a docker container, especially with the updated __Docker Compose V2__ tool, whereby the user can mount environment variables now as docker secrets (essentially, run-time mounts by docker on `/run/secrets/<secret_name>`. This strategy to deploy an application stack is beneficial as upon performing commands such as `docker inspect -f '{{ .Config.Env }}' <telegraf_container_name>` or `docker exec <telegraf_container_name> env` will not yield the  environment variables as they are now available only in `/run/secrets/` directory by docker.

### Simple Example

[Proof of Concept Repo](https://github.com/shantanoo-desai/docker-compose-secrets-envvars) which explains the new feature of mounting environment variables as docker secrets

### Potential Implementation

Build upon the concept of `secretstores.jose` which will essentially read the files under `/run/secrets` directory without having decrypt the contents of the folder

```toml
[[secretstore.file]]
  id = "file_secretstore"
  path = "/run/secrets"

[[ inputs.opcua ]]
   # snip for brevity

   username = "@{file_secretstore:opcua_user}"
   password = "@{file_secretstore:opcua_password}"
```

for a potential compose file:

```yaml
services:
  telegraf:
    image: telegraf:latest
    container_name: telegraf-opcua
    user: "1000"
    network_mode: host
    volumes:
      - ./telegraf.toml:/etc/telegraf/telegraf.conf:ro
    secrets:
      - opcua_user
      - opcua_password
secrets:
  # use the new feature of loading an environment variable in docker to a dedicate secret under `/run/secrets/<secret_name>`
  opcua_user:
    environment: OPCUA_USER
  opcua_password:
    environment: OPCUA_PASSWORD
```

Or maybe some form of implementation that lets the user mention whether the value passed is to be obtained from environment variable or a file

```toml
   password = "file:/my/secret/location" # or something similar
```

## Behaviour

- Assuming that `secretstores.jose` performs a larger chunk of the functionality to read information from dedicated directory, this implementation should let the user define such paths where the files exist, and the value can be passed to the dedicated plugins section
- If either the directory / files do not exist telegraf exits
- if the file contents are empty then telegraf exits

### Actual behavior

No implementation exists at this point except from core functionality (maybe) under the `JOSE` plugin for secret stores
