### ISSUE TITLE
Adapt secretstore for OPCUA input plugins

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/telegraf#12862]
### Use Case

OPCUA Servers can be configured with Username and Password. These credentials can be store uniquely with the new `secretstores` plugins in Telegraf.

The respective password for OPCUA servers can be set and served to the input plugins via the secretstore syntax making the deployments secure.

### Set Secret

```bash
docker run -u 1000  \
          -v $(pwd)/telegraf.toml:/etc/telegraf/telegraf.conf:ro \
          -v $(pwd):/etc/telegraf \
          telegraf:latest telegraf secrets set jose_test opcua_password testpassword
```

This will be able to set a JOSE type credential under `secrets` directory within a file called `opcua_password`

### Get Secret

check the value of the secret

```bash

docker run -u 1000  \
          -v $(pwd)/telegraf.toml:/etc/telegraf/telegraf.conf:ro \
          -v $(pwd):/etc/telegraf \
          telegraf:latest telegraf secrets get jose_test opcua_password
```

Output

```
2023/03/14 11:10:11 I! Using config file: /etc/telegraf/telegraf.conf
jose_test:opcua_password = testpassword
```

### Expected behavior

Upon spinning up a docker container:

```bash
docker run -u 1000 \
           -e OPCUA_PASSWORD=testpassword \
           -v $(pwd)/telegraf.toml:/etc/telegraf/telegraf.conf:ro \
           -v $(pwd):/etc/telegraf \
           telegraf:latest telegraf
```

for the following configuration:

```toml
[agent]
    interval = "20s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    debug = true
    quiet = false
    hostname = ""
    omit_hostname = true

[[secretstores.jose]]
  id = "jose_test"
  path = "/etc/telegraf/secrets"
  password = "tester" # dummy skeleton password for jose

[[outputs.file]]
  data_format = "json"

[[inputs.opcua]]
  ## Metric name
  name = "ftFabrik"
  #
  ## OPC UA Endpoint URL
  endpoint = "opc.tcp://192.168.4.201:4840"
  #
  ## Maximum time allowed to establish a connect to the endpoint.
  connect_timeout = "60s"
  #
  ## Maximum time allowed for a request over the established connection.
  request_timeout = "60s"
  #
  ## Security policy, one of "None", "Basic128Rsa15", "Basic256",
  ## "Basic256Sha256", or "auto"
  security_policy = "None"
 
  ## Security mode, one of "None", "Sign", "SignAndEncrypt", or "auto"
  security_mode = "None"

  ## Authentication Method, one of "Certificate", "UserName", or "Anonymous".  To
  ## authenticate using a specific ID, select 'Certificate' or 'UserName'
  auth_method = "UserName"

  ## Username. Required for auth_method = "UserName"
  username = "OpcUser"
 
  ## Password. Required for auth_method = "UserName"
  password = "@{jose_test:opcua_password}"

  ## Option to select the metric timestamp to use. Valid options are:
  ##     "gather" -- uses the time of receiving the data in telegraf
  ##     "server" -- uses the timestamp provided by the server
  ##     "source" -- uses the timestamp provided by the source
  timestamp = "source"

  nodes = [ {name="test", namespace="2", identifier_type="s", identifier="IX_SSC_LightBarrierOutsource_I4"}  ]
  
  data_format = "json"
```

should be able to connect to an OPCUA server with credentials `OpcUser:testpassword`

### Actual behavior

Currently secretstore is not setup for the OPCUA input plugins, hence the output logs:

```
2023-03-14T11:29:20Z E! [inputs.opcua] Error in plugin: error in Client Connection: User does not have permission to perform the requested operation. StatusBadUserAccessDenied (0x801F0000)
```

## Gist Documenting trials with secretstore JOSE and telegraf

tested for `v1.25.3` as well as `v1.26.0`

[Gist URL](https://gist.github.com/shantanoo-desai/7ed17c3ea439812ea0113789e3013965)
