### ISSUE TITLE
Add to inputs.win_eventlog documentation: --test-wait does not work and event_tags is mandatory

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#12868]
### Relevant telegraf.conf

```toml
[[inputs.win_eventlog]]
  from_beginning = false
  xpath_query = '''
  <QueryList>
    <Query Id="0" Path="System">
    <Select Path="System">*[System[Provider[@Name='Dodo'] and (EventID=1000)]]</Select>
    </Query>
  </QueryList>
   '''
  timestamp_from_event = true
  event_fields = ["Source", "Channel", "EventID"]
  event_tags = []  
  exclude_fields = ["Data"]
```

### Logs from Telegraf

```text
n/a
```

### System info

Telegraf 1.25.2, Windows 2019

### Steps to reproduce

1. telegraf -config telegraf.d\wineventlog_test.conf --test-wait 30
2. Powershell: Write-EventLog -LogName System -Source "Dodo" –EventID 1000 –Message "Test"
3. No output on stdout

### Expected behavior

Should output new event on stdout (as influxdb line protocol)

### Actual behavior

No output on stdout. Test mode does not seem to work with [[inputs.win_eventlog]]

### Additional info

We got follwing answer from InfluxDB support regarding not working "--test-wait" :
_It looks that this plugin uses a subscription to Windows events, and every time the agent "gathers" for each plugin, that is when it will check whether the subscription has any new events. With the test mode, Telegraf immediately checks for events, finds none, and completes. I think the "--test-wait" parameter might be a little misleading in this context, as the "waiting" aspect is used because the inputs are gathered asynchronously._

So please can you add a hint to https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_eventlog/README.md that --test-wait makes no sense/is not possible for this plugin.

Also figured out that Windows Eventlog Input Plugin documentation regarding "event_tags" should tell, that this directive is mandatory (always necessary to include), configuration without it will not produce any output.
So at least you have to insert `event_tags = [ ]`

**Comment by powersj** [comment]
Hi,

> So please can you add a hint to https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_eventlog/README.md that > --test-wait makes no sense/is not possible for this plugin.

This applies to all the service plugins or where a plugin sits and waits to listen for data. @srebhan and I should talk about the best way to document this across these types of plugins because it applies more broadly.

> Also figured out that Windows Eventlog Input Plugin documentation regarding "event_tags" should tell, that this directive is mandatory (always necessary to include), configuration without it will not produce any output.
> So at least you have to insert event_tags = [ ]

In your example, if you do not provide `event_tags`, then the [defaults are used](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_eventlog/win_eventlog.go#L563-L564). In this case, it means that `"Source", "EventID", "Level", "LevelText", "Keywords", "Channel", "Computer"` will all be used as tags. That only leaves the `Data` field, which you are also excluding. As a result, your metric has no fields and therefore no metric. 

I do agree, that the docs should be updated, but it should be updated with the default values to help remove this confusion about what will end up where by default.

Steps I used to reproduce:

```powershell
New-EventLog -LogName Application -Source "testing"
Write-EventLog -LogName Application -Source "testing" -EventID 1000 -Message "test"
```

```toml
[[inputs.win_eventlog]]
  from_beginning = false
  xpath_query = '''
  <QueryList>
    <Query Id="0" Path="Application">
    <Select Path="Application">*[System[Provider[@Name='testing'] and (EventID=1000)]]</Select>
    </Query>
  </QueryList>
   '''
  timestamp_from_event = true
  event_fields = ["Source", "Channel", "EventID"]
  #event_tags = []
  #exclude_fields = ["Data"]
```

```s
2023-03-14T16:44:14Z D! [agent] Starting service inputs
2023-03-14T16:44:14Z D! [inputs.win_eventlog] Subscription handle id:2
win_eventlog,host=win11 Source="testing",EventID=1000i,Channel="Application",Data="test" 1678812259000000000
2023-03-14T16:44:24Z D! [outputs.file] Wrote batch of 1 metrics in 0s
```
