### ISSUE TITLE
inputs.internet_speed | Telegraf 1.26.0 overrides generic host tag

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#12876]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]

  interval = "20s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  debug = true
  omit_hostname = false

[[inputs.internet_speed]]
```

### Logs from Telegraf

```text
#Telegraf 1.25.3
internet_speed,host=QDLP03 download=142.37877559592192,latency=24.13065,upload=17.010222891462274 1678880362000000000

#Telegraf 1.26.0
internet_speed,host=test.netoip.com.prod.hosts.ooklaserver.net:8080,server_id=21160 download=168.954956,jitter=1.185362,latency=26.025385,upload=17.760916 1678880125000000000
```
```


### System info

any

### Docker

_No response_

### Steps to reproduce

Just run  `.\telegraf.exe --config .\Ping.conf --test` on the different versions of telegraf to see the difference in the output

I think it’s all due to the update on the speedtest-go package #12707 

```
#Telegraf 1.25.3
internet_speed,host=QDLP03 download=142.37877559592192,latency=24.13065,upload=17.010222891462274 1678880362000000000

#Telegraf 1.26.0
internet_speed,host=test.netoip.com.prod.hosts.ooklaserver.net:8080,server_id=21160 download=168.954956,jitter=1.185362,latency=26.025385,upload=17.760916 1678880125000000000
```

### Expected behavior

the current/local hostname is reported

### Actual behavior

the current/local hostname is overriden by the plugin

### Additional info

ref: https://community.influxdata.com/t/telegraf-1-26-problem-with-input-internet-speed-on-linux/29065
