### ISSUE TITLE
Linter: gosec, Rule: G101 - Look for hard coded credentials. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#12889]
### Use Case

This issue starts discussion about enabling:
- linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
- rule: [G101 - Look for hard coded credentials](https://github.com/securego/gosec#usage)

Rule is mapped to [CWE-798: Use of Hard-coded Credentials](https://cwe.mitre.org/data/definitions/798.html).

### Expected behavior

Decision if rule should be enabled or not.

### Actual behavior

For this rule following findings were found in current code:
```
plugins/inputs/http/http_test.go:316:6                                   gosec  G101: Potential hardcoded credentials
plugins/inputs/openweathermap/openweathermap_test.go:107:7               gosec  G101: Potential hardcoded credentials
plugins/outputs/http/http_test.go:448:6                                  gosec  G101: Potential hardcoded credentials
plugins/outputs/loki/loki_test.go:295:6                                  gosec  G101: Potential hardcoded credentials
plugins/outputs/sensu/sensu_test.go:81:2                                 gosec  G101: Potential hardcoded credentials
plugins/outputs/yandex_cloud_monitoring/yandex_cloud_monitoring.go:68:2  gosec  G101: Potential hardcoded credentials
```

Two of them seem to be false positives (can be muted by `//#nosec` comment), rest of them are contained in tests.

### Additional info

For this rule additional configuration can be provided:
```
      G101:
        # Regexp pattern for variables and constants to find.
        # Default: "(?i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer|cred"
        pattern: "(?i)example"
        # If true, complain about all cases (even with low entropy).
        # Default: false
        ignore_entropy: false
        # Maximum allowed entropy of the string.
        # Default: "80.0"
        entropy_threshold: "80.0"
        # Maximum allowed value of entropy/string length.
        # Is taken into account if entropy >= entropy_threshold/2.
        # Default: "3.0"
        per_char_threshold: "3.0"
        # Calculate entropy for first N chars of the string.
        # Default: "16"
        truncate: "32"
```
