### ISSUE TITLE
"Could not initialize input inputs.mysql" while testing #12591 

### ISSUE THREAD

**Issue by jfrye121** [influxdata/telegraf#12916]
### Relevant telegraf.conf

```toml
# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  user = "sumomonitoring"

###############################################################################
#                            SECRETSTORE PLUGINS                              #
###############################################################################


# # File based Javascript Object Signing and Encryption based secret-store
[[secretstores.jose]]
#   ## Unique identifier for the secret-store.
#   ## This id can later be used in plugins to reference the secrets
#   ## in this secret-store via @{<id>:<secret_key>} (mandatory)
id = "my_secrets"
#
#   ## Directory for storing the secrets
path = "/etc/telegraf/secrets"
#
#   ## Password to access the secrets.
#   ## If no password is specified here, Telegraf will prompt for it at startup time.
#   # password = ""


[[inputs.mysql]]
  servers = ["${user}:@{my_secrets:sumomonitoring}@tcp(internalip:3306)/?tls=false"]
  metric_version = 2
  table_schema_databases = []
  perf_summary_events = []
  gather_table_schema = true
  gather_process_list = true
  gather_info_schema_auto_inc = true
  gather_user_statistics = true
  gather_slave_status = true
  gather_table_io_waits = true
  gather_table_lock_waits = true
  gather_index_io_waits = true
  gather_event_waits = true
  gather_file_events_stats = true
  gather_perf_events_statements = true
  interval_slow = "30m"
[inputs.mysql.tags]
  environment="prod"
  component="database"
  db_system="mariadb"
  db_cluster="default"
  db_cluster_address = "publicip"
  db_cluster_port = "3306"
[[outputs.sumologic]]
  url = "urlgoeshere"
  data_format = "prometheus"
```

### Logs from Telegraf

```text
2023-03-21T08:27:02-05:00 I! Starting Telegraf 1.26.0
2023-03-21T08:27:02-05:00 I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-03-21T08:27:02-05:00 I! Loaded inputs: cpu disk diskio kernel mem mysql processes swap system
2023-03-21T08:27:02-05:00 I! Loaded aggregators:
2023-03-21T08:27:02-05:00 I! Loaded processors:
2023-03-21T08:27:02-05:00 I! Loaded secretstores: my_secrets
2023-03-21T08:27:02-05:00 I! Loaded outputs: sumologic
2023-03-21T08:27:02-05:00 I! Tags enabled: host=ipaddress user=sumomonitoring
2023-03-21T08:27:02-05:00 I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ipaddress", Flush Interval:10s
2023-03-21T08:27:02-05:00 E! [telegraf] Error running agent: could not initialize input inputs.mysql: getting server 0 failed
```

### System info

Telegraf 1.26.0, Ubuntu Server 22.04 LTS, AWS ec2 instance

### Steps to reproduce

1. Install Telegraf
2. Enable secretsstore by editing config file, un-commenting per documentation on github page (https://github.com/influxdata/telegraf/tree/master/config)
3. Store a secret, and verify it is written to secrets subfolder. 
4. Run `telegraf --password "enteryourpasswordtoallowaccess"`
5. No error thrown here, but service does not start and the log shows as provided in this bug report
...

### Expected behavior

Telegraf starts, with provided password to unlock secret store

### Actual behavior

Telegraf command does not error out, however, the service does not start and error thrown in log 

`E! [telegraf] Error running agent: could not initialize input inputs.mysql: getting server 0 failed`

### Additional info

I was testing  #12591 when I ran into this issue. DM'd Sven Rebhan as I was working with him prior, and was advised to open an issue.
