### ISSUE TITLE
gnmi plugin: got empty metric-name for response on Nokia SRLinux

### ISSUE THREAD

**Issue by protonmarco** [influxdata/telegraf#12931]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
  alias = "leaf1"
  ## Address and port of the gNMI GRPC server
  addresses = ["leaf1:57400"]
  username = "admin"
  password = "NokiaSrl1!"
  redial = "10s"
  encoding="json_ietf"
  tagexclude = ["path","host"]
  enable_tls = true
  tls_ca = "/etc/telegraf/ssl-ca/ca.pem"
  tls_cert = "/etc/telegraf/ssl-cert/telegraf.pem"
  tls_key = "/etc/telegraf/ssl-cert/telegraf.key"
  insecure_skip_verify = false
  [[inputs.gnmi.subscription]]
    name = "interface"
    origin = ""
    path = "/interface"
    subscription_mode = "sample"
    sample_interval = "10s"
```

### Logs from Telegraf

```text
2023-03-24T10:02:10+01:00 W! [inputs.gnmi::leaf1] Got empty metric-name for response, usually indicating
configuration issues as the response cannot be related to any subscription.
Please open an issue on https://github.com/influxdata/telegraf including your
device model and the following response data:
timestamp:1679648530391910312  update:{path:{origin:"srl_nokia-interfaces"  elem:{name:"interface"  key:{key:"name"  value:"ethernet-1/1"}}}  val:{json_ietf_val:"{\"admin-state\": \"disable\", \"ifindex\": 16382, \"oper-state\": \"down\", \"oper-down-reason\": \"port-admin-disabled\", \"last-change\": \"2023-03-24T09:02:02.518Z\"}"}}  update:{path:{origin:"srl_nokia-interfaces"  elem:{name:"interface"  key:{key:"name"  value:"ethernet-1/1"}}  elem:{name:"transceiver"}}  val:{json_ietf_val:"{\"tx-laser\": false, \"oper-state\": \"down\", \"oper-down-reason\": \"not-present\", \"ddm-events\": false, \"forward-error-correction\": \"disabled\"}"}}  update:{path:{origin:"srl_nokia-interfaces"  elem:{name:"interface"  key:{key:"name"  value:"ethernet-1/1"}}  elem:{name:"ethernet"}}  val:{json_ietf_val:"{\"dac-link-training\": true, \"port-speed\": \"25G\", \"hw-mac-address\": \"1A:FB:03:FF:00:01\"}"}}  update:{path:{origin:"srl_nokia-interfaces"  elem:{name:"interface"  key:{key:"name"  value:"ethernet-1/1"}}  elem:{name:"ethernet"}  elem:{name:"flow-control"}}  val:{json_ietf_val:"{\"receive\": false}"}}  update:{path:{origin:"srl_nokia-interfaces"  elem:{name:"interface"  key:{key:"name"  value:"ethernet-1/1"}}  elem:{name:"sflow"}}  val:{json_ietf_val:"{\"admin-state\": \"disable\"}"}}
This message is only printed once.
```

### System info

Telegraf 1.26, Nokia SR Linux v22.11.2

### Docker

The problem can be reproduced with containerlab on the lab created with [this repo](https://github.com/marco-minervino/containerlab-collectors-test).
Once everything is up, it can be seen with `docker logs clab-collectors-telegraf`.

### Steps to reproduce

1. Turn on the lab as explained in the readme
2. Check:
 - the empty metric-name logs of the telegraf container 

### Expected behavior

No such logs.

### Actual behavior

Empty metric-name logs are present.
