### ISSUE TITLE
[inputs.http] crashes when using cookie_auth_url and the host is unreachable

### ISSUE THREAD

**Issue by Mokson** [influxdata/telegraf#12959]
### Relevant telegraf.conf

```toml
...
[[inputs.http]]
  urls = ["https://$IP_ADDRESS/v1/version"]
  method = "GET"
  interval="$ACU_INFO_INTERVAL"
  timeout = "7s"
  insecure_skip_verify = true
  cookie_auth_url = "https://$IP_ADDRESS/v1/login"
  cookie_auth_method = "POST"
  cookie_auth_headers = { Content-Type = "application/json"}
  cookie_auth_body = '{"user": "$USER", "password": "$PASSWORD"}'
  cookie_auth_renewal = "$COOKIE_RENEWAL_INTERVAL"
  success_status_codes = [200]
  tagexclude = ["host"]
  data_format="json_v2"
  [[inputs.http.json_v2]]
...
```

### Logs from Telegraf

```text
2023-03-27T08:51:52Z D! [agent] Initializing plugins
2023-03-27T08:52:00Z E! [telegraf] Error running agent: could not initialize input inputs.http: Post "https://172.16.2.166:4432/v1/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2023-03-27T08:53:00Z I! Loading config file: /etc/telegraf/telegraf.conf
```

### System info

ubuntu + latest telegraf

### Steps to reproduce

1. create config that points to the host which is unreachable
2. run telegraf

### Expected behavior

telegraf keeps running and will retry to get cookies in accordance with the interval settings

### Actual behavior

telegraf crashes
