### ISSUE TITLE
Telegraf/golang does not parse timezone correctly from timestamp

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#12960]
### Relevant telegraf.conf

```toml
## The column to extract time information for the metric
  ## `csv_timestamp_format` must be specified if this is used.
  ## Will not be included as field in metric.
  csv_timestamp_column = "Timestamp"

  ## The format of time data extracted from `csv_timestamp_column`
  ## this must be specified if `csv_timestamp_column` is specified
  csv_timestamp_format = "2006-01-02 15:04:05 MST"

  ## The timezone of time data extracted from `csv_timestamp_column`
  ## in case of there is no timezone information.
  ## It follows the  IANA Time Zone database.
  csv_timezone = "Local"
```

### Logs from Telegraf

```text
N/A
```

### System info

Telegraf 1.26

### Steps to reproduce

TBD

### Expected behavior

Telegraf to parse the timestamp in the correct timezone.

### Actual behavior

Metric timestamp has incorrect offset.

### Additional info

Golang-nuts conversation: [Parsing time with timezones seem to fail](https://groups.google.com/g/golang-nuts/c/hDMdnm_jUFQ/m/yeL9IHOsAQAJ)

Workaround seems to be like this:
```golang
stamp, _ := time.Parse(layout, v)
loc, _ := time.LoadLocation(stamp.Location().String())
stamp, _ = time.ParseInLocation(layout, v, loc)
```
