### ISSUE TITLE
Trying to use the new scheduling features for input.exec. 

### ISSUE THREAD

**Issue by kaunix** [influxdata/telegraf#12975]
### Relevant telegraf.conf

```toml
trying to add the new scheduling features to inputs after doing that telegraf won't restart or start.

[[inputs.exec]]
commands=["/usr/bin/iperf3 -O 7 -c 192.168.1.1 --json"]
#interval = "1783s"
interval = "1800s"
collection_jitter= "0s"
round_interval = true
collection_offset = "54s"
timeout = "40s"
data_format = "json"
json_query = "end"
name_override = "server.example.com-write"

[[inputs.exec]]
commands=["/usr/bin/iperf3 -O 7 -c 192.168.1.1 -R --json"]
#interval = "1801s"
interval = "1800s"
collection_jitter= "0s"
round_interval = true
collection_offset = "1"
timeout = "40s"
data_format = "json"
json_query = "end"
name_override = "server.example.com-read"

[[inputs.exec]]
commands=["/usr/bin/iperf3 -O 7 -c 192.168.1.2 --json"]
#interval = "1831s"
interval = "1800s"
collection_jitter= "0s"
round_interval = true
collection_offset = "15"
timeout = "40s"
data_format = "json"
json_query = "end"
name_override = "server2.example.com-write"

[[inputs.exec]]
commands=["/usr/bin/iperf3 -O 7 -c 192.168.1.2 -R --json"]
#interval = "1867s"
interval = "1800s"
collection_jitter= "0s"
round_interval = true
collection_offset = "35"
timeout = "40s"
data_format = "json"
json_query = "end"
name_override = "server2.example.com-read"
```

### Logs from Telegraf

```text
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ An ExecStart= process belonging to unit telegraf.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
Mar 28 09:36:07 mint-nuc systemd[1]: telegraf.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit telegraf.service has entered the 'failed' state with result 'exit-code'.
Mar 28 09:36:07 mint-nuc systemd[1]: Failed to start Telegraf.
░░ Subject: A start job for unit telegraf.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit telegraf.service has finished with a failure.
░░
░░ The job identifier is 28861 and the job result is failed.
Mar 28 09:36:07 mint-nuc systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ Automatic restarting of the unit telegraf.service has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Mar 28 09:36:07 mint-nuc systemd[1]: Stopped Telegraf.
░░ Subject: A stop job for unit telegraf.service has finished
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A stop job for unit telegraf.service has finished.
░░
░░ The job identifier is 28960 and the job result is done.
Mar 28 09:36:07 mint-nuc systemd[1]: telegraf.service: Start request repeated too quickly.
Mar 28 09:36:07 mint-nuc systemd[1]: telegraf.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ The unit telegraf.service has entered the 'failed' state with result 'exit-code'.
Mar 28 09:36:07 mint-nuc systemd[1]: Failed to start Telegraf.
░░ Subject: A start job for unit telegraf.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░
░░ A start job for unit telegraf.service has finished with a failure.
░░
░░ The job identifier is 28960 and the job result is failed.


systemctl status telegraf.service
× telegraf.service - Telegraf
     Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-03-28 09:36:07 AKDT; 1h 5min ago
       Docs: https://github.com/influxdata/telegraf
    Process: 83964 ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF>
   Main PID: 83964 (code=exited, status=1/FAILURE)
        CPU: 89ms

Mar 28 09:36:07 mint-nuc systemd[1]: telegraf.service: Scheduled restart job, restart counter is at 5.
Mar 28 09:36:07 mint-nuc systemd[1]: Stopped Telegraf.
Mar 28 09:36:07 mint-nuc systemd[1]: telegraf.service: Start request repeated too quickly.
Mar 28 09:36:07 mint-nuc systemd[1]: telegraf.service: Failed with result 'exit-code'.
Mar 28 09:36:07 mint-nuc systemd[1]: Failed to start Telegraf.
```

### System info

Telegraf 1.26, Linux Mint 21.1 

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

expected behavior is that the telegraf would restart after the config change was complete. it did not start.

### Actual behavior

failed to start after change.
