### ISSUE TITLE
Secrets on PostgreSQL plugin require increased limit on locked memory 

### ISSUE THREAD

**Issue by PierreF** [influxdata/telegraf#12980]
### Relevant telegraf.conf

```toml
[[inputs.postgresql]]
  address = "host=172.17.0.2 port=5432 user=postgres password=abc dbname=postgres sslmode=disable"
[[inputs.postgresql]]
  address = "host=172.17.0.3 port=5432 user=postgres password=abc dbname=postgres sslmode=disable"
[[inputs.postgresql]]
  address = "host=172.17.0.4 port=5432 user=postgres password=abc dbname=postgres sslmode=disable"
[[inputs.postgresql]]
[...]
[[inputs.postgresql]]
  address = "host=172.17.0.17 port=5432 user=postgres password=abc dbname=postgres sslmode=disable"
```

### Logs from Telegraf

```text
2023-03-29T12:17:39Z W! [inputs.postgresql] Collection took longer than expected; not complete after interval of 10s
2023-03-29T12:17:39Z W! [inputs.postgresql] Collection took longer than expected; not complete after interval of 10s
2023-03-29T12:17:39Z W! [inputs.postgresql] Collection took longer than expected; not complete after interval of 10s
2023-03-29T12:17:39Z W! [inputs.postgresql] Collection took longer than expected; not complete after interval of 10s
```

### System info

Telegraf 1.26.0 Ubuntu 22.04

### Steps to reproduce

1. Start multiple (at least 7) PostgreSQL containers:
```
for i in $(seq 1 10); do docker run -d --name postgresql$i -e POSTGRES_PASSWORD=abc postgres:14;done 
```
2. Configure telegraf to gather all those PostgreSQL (cf part of the telegraf.conf above)
3. Start telegraf as user with the ulimit for memory locked that match what systemd would do (64kb):
```
sudo -u telegraf -i
ulimit -Hl 64; ulimit -l 64  # This is needed because sudo increase the limit. A service started with systemd had 64kb by default, at least on Ubuntu 22.04

./usr/bin/telegraf --config ./etc/telegraf/telegraf.conf --config-directory ./etc/telegraf/telegraf.d/
```
4. Wait a bit, it should be rather fast
5. Start to have "Collection took longer than expected" and all PostgreSQL stop being monitored
6. Telegraf will no longer stop cleanly

### Expected behavior

PostgreSQL metrics still being sent.

### Actual behavior

PostgreSQL stop being monitored and part of Telegraf (anything that depend on blocked PostgreSQL input) will hang

### Additional info

The hang itself is due to https://github.com/awnumar/memguard/issues/147

The cause of the hang is due to each Gather() from PostgreSQL input required some new locked memory pages:
* At rest, Telegraf require 3 pages of locked memory (you can check the number of pages locked with `cat /proc/$PID/smaps_rollup`). Those 3 pages come from: [left, right and rand](https://github.com/awnumar/memguard/blob/v0.22.3/core/coffer.go#L30) of memguard
* During each gather, PostgreSQL plugin will add up to 2 new locked pages:
  * This is due to [SanitizedAddress](https://github.com/influxdata/telegraf/blob/v1.26.0/plugins/inputs/postgresql/service.go#L152) that is called by Gather()
  * SanitizedAddress read the secret (`p.Address.Get()`).
  * Reading the secret will [open the enclave](https://github.com/influxdata/telegraf/blob/v1.26.0/config/secret.go#L128) which internally will required 2 pages (at least): one for the key - destroyed before returning - one for the secret which is returned
  * Telegraf secret will protect the secret (needing a locked page) while the enclave buffer is not yet destroyed
* At the ends, with the 64kb default limit, we could have up to 16 pages of locked memory:
   * 3 usage permanently used by memguard Coffer
   * 2 temporary PER concurrent Gather(). So as soon as 7 Gather are run concurrently: 3 + 2 * 7 == 17, one page allocation will fail.

It might be possible to reduce requirement for locked memory, we could do the Sanitize address once ? It don't seems to contains the password and don't need locked memory.
We might also say that Telegraf require more locked memory and increase the limit in the Telegraf SystemD unit ( LimitMEMLOCK).
