### ISSUE TITLE
Consider introducing tag and field length limit

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#12987]
### Use Case

There is already a limit on number of metrics Telegraf can hold. It works well and allows to control Telegraf memory usage until apps exposing metrics start to abuse tags/fields and put unnecessary long values in there.

It would be nice if there was a way to limit maximum tag/field size.

### Expected behavior

New agent level config option `tagsize_limit` and `fieldsize_limit` in bytes. Values which exceed limit are truncated to the limit.

### Actual behavior

multi kilobytes values are allowed in tags

**Comment by Hipska** [comment]
Hi, this is already possible with the strings processor:

```toml
# Perform string processing on tags, fields, and measurements
[[processors.strings]]

  # Trims strings based on width
  [[processors.strings.left]]
    field = "message"
    width = 10
```
