### ISSUE TITLE
Telegraf does not run as a Windows 10 Service

### ISSUE THREAD

**Issue by jackbenimble999** [influxdata/telegraf#12999]
### Relevant telegraf.conf

```toml
# Telegraf Configuration

[agent]
  ## Log at debug level.
  debug = true
  quiet = false
  

###############################################################################
#                             SECRET STORE OS                                 #
###############################################################################
  
  
  [[secretstores.os]]
  id = "os_secrets"
  
    
###############################################################################
#                             INPUT PLUGINS                                   #
###############################################################################

  
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]

  ## Topics that will be subscribed to.
  topics = [
 	"influxtopic/#",
  ]

  qos = 2

  max_undelivered_messages = 1000

  persistent_session = true

  client_id = "InfluxDataStandalone"

  username = "admin"

  
  password = "@{os_secrets:my_secret_password}"

  data_format = "influx"




###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


[[outputs.influxdb_v2]]
  
  ## Use below when InfluxDB is running in HTTPS mode
  ## urls = ["https://127.0.0.1:8086"]
  urls = ["http://127.0.0.1:8086"]
  
  token = "@{os_secrets:my_secret_token}"
  organization = "SICK"

  bucket = "events"

  ## Use TLS but skip chain & host verification
  ## insecure_skip_verify = true
  
#[[outputs.file]]
#  files = ["stdout"]
```

### Logs from Telegraf

```text
Unable to find any
```

### System info

Windows 10

### Steps to reproduce

Exactly as described here:

https://docs.influxdata.com/telegraf/v1.21/administration/windows_service/

### Expected behavior

Service created and functions correctly

### Actual behavior

The service is created by doesn't work. No data as transferred into influx. When running standalone (from a command line) it works fine. 

### Additional info

Also tried with WinSW, nssm and forked from a java program. The first two no results, the third works briefly then stops. 

Also, the WinSW log showed the following error: 

2023/03/30 16:15:04 E! flag provided but not defined: -config telegraf_mqtt_to_influxdb_standalone.conf

Here's the winsw configuration:

<service>
  <id>telegraf-service</id>
  <name>Telegraf Service</name>
  <description>Service for Telegraf</description>
  <executable>telegraf.exe</executable>
   <startargument>--config telegraf_mqtt_to_influxdb_standalone.conf</startargument>
  <logmode>rotate</logmode>
</service>

Thanks!
