### ISSUE TITLE
opcua: remote key size should be 128-256 bytes, got 512 bytes

### ISSUE THREAD

**Issue by aoehme123** [influxdata/telegraf#12995]
### Relevant telegraf.conf

```toml
[[inputs.opcua_listener]]
   name = "opcua_listener"
   endpoint = "opc.tcp://xyz.xyz.xyz.xyz:4880"
   #security_policy = "None"
   #security_mode = "None"
   security_policy = "auto"
   security_mode = "auto"
   certificate = "cert.pem"
   private_key = "key.pem"
   auth_method = "UserName"
   username = "userXXXXX"
   password = "XXXXXXXXXX"
   timestamp = "server"
   nodes = [
     {name="RACTSimuClk", namespace="2", identifier_type="s", identifier="_RACTUAL_SIMU_CLK"},
     {name="UserLevel", namespace="2", identifier_type="s", identifier="_ILEVEL"},
   ]
```

### Logs from Telegraf

```text
2023-03-30T19:44:05Z D! [inputs.opcua_listener] security policy from configuration
2023-03-30T19:44:05Z I! error encrypting user password: opcua: remote key size should be 128-256 bytes, got 512 bytes
2023-03-30T19:44:05Z E! [telegraf] Error running agent: starting input inputs.opcua_listener: error in Client Connection: opcua: remote key size should be 128-256 bytes, got 512 bytes
```

### System info

Telegraf 1.27.0, Win 11 Pro 64Bit

### Steps to reproduce

1. Connect to an OPC UA Server with a Certificate signature algorithm sha512RSA  (type is RSA 4096 Bit)
2. (in this case it also works with security_policy ="none" and security_mode ="none" 
3.
...

### Expected behavior

accept the certificate with the 512 bytes...

### Actual behavior

MEntiones error "error in Client Connection: opcua: remote key size should be 128-256 bytes, got 512 bytes" and does not connect.

### Additional info
If I use a certificate with sha256 signature algorithm and RSA with 2048 bit it works...
