### ISSUE TITLE
inputs.procstat should return pidfile tag if lookup_error happens

### ISSUE THREAD

**Issue by genofire** [influxdata/telegraf#13016]
### Relevant telegraf.conf

```toml
[[outputs.prometheus_client]]
  listen = "0.0.0.0:9200"
  path = "/metrics/"
  metric_version = 2

# a
[[inputs.procstat]]
  pid_finder = "native"
  pid_file = "a.pid"
  pid_tag = true

# b
[[inputs.procstat]]
  pid_finder = "native"
  pid_file = "b.pid"
  pid_tag = true
```

### Logs from Telegraf

```text
irrelevant
```

### System info

FreeBSD

### Steps to reproduce

1. config like above with correct pidfiles
2. `curl "http://127.0.0.1:9200"`

### Expected behavior

Get output:
```
procstat_lookup_pid_count{host="localhost",pid_finder="native",pidfile="a.pid",result="lookup_error"} 0
procstat_lookup_pid_count{host="localhost",pid_finder="native",pidfile="b.pid",result="success"} 1
```

### Actual behavior

Get output:
```
procstat_lookup_pid_count{host="localhost",pid_finder="native",result="lookup_error"} 0
procstat_lookup_pid_count{host="localhost",pid_finder="native",pidfile="b.pid",result="success"} 1
```

### Additional info

using: [telegraf-1.20.4](https://freshports.org/net-mgmt/telegraf)
