### ISSUE TITLE
Review not needed and missing blank identifiers used for `error`

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#13013]
### Use Case

`errcheck` linter has default exclusion list (which can be extended in `.golangci.yml`) 
https://github.com/kisielk/errcheck/blob/master/errcheck/excludes.go#L11
```go
	// bytes
	"(*bytes.Buffer).Write",
	"(*bytes.Buffer).WriteByte",
	"(*bytes.Buffer).WriteRune",
	"(*bytes.Buffer).WriteString",

	// fmt
	"fmt.Print",
	"fmt.Printf",
	"fmt.Println",
	"fmt.Fprint(*bytes.Buffer)",
	"fmt.Fprintf(*bytes.Buffer)",
	"fmt.Fprintln(*bytes.Buffer)",
	"fmt.Fprint(*strings.Builder)",
	"fmt.Fprintf(*strings.Builder)",
	"fmt.Fprintln(*strings.Builder)",
	"fmt.Fprint(os.Stderr)",
	"fmt.Fprintf(os.Stderr)",
	"fmt.Fprintln(os.Stderr)",

	// io
	"(*io.PipeReader).CloseWithError",
	"(*io.PipeWriter).CloseWithError",

	// math/rand
	"math/rand.Read",
	"(*math/rand.Rand).Read",

	// strings
	"(*strings.Builder).Write",
	"(*strings.Builder).WriteByte",
	"(*strings.Builder).WriteRune",
	"(*strings.Builder).WriteString",

	// hash
	"(hash.Hash).Write",
```

### Expected behavior

For excluded functions, there is no need to simulate handling `error` by using `_ := function1(...)`, or `_, _ := function2(...)`.
Remove blank identifiers for such cases (to find them something like this can be used: `grep -nr '_, _ = (\w\+\.)\+Write' * `).

### Additional info

Also, it would be good to handle errors properly for cases when blank identifier is used for non-excluded functions.

This configuration can find such cases:
```
linters-settings:
  errcheck:
    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`.
    # Such cases aren't reported by default.
    # Default: false
    check-blank: true
```
