### ISSUE TITLE
socket_listener: keep_alive_period non-functional with TLS

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#13046]
### Relevant telegraf.conf

```toml
[[inputs.socket_listener]]
service_address = "tcp://:8085"
tls_cert = "/cert.crt"
tls_key = "/cert.key"
keep_alive_period = "1m"
```

### Logs from Telegraf

```text
E! [inputs.socket_listener] Error in plugin: connection not a TCP connection (*tls.Conn)
```

### System info

35edd18

### Steps to reproduce

1. Run the above config
2. Connect to socket
3.
...

### Expected behavior

no error

### Actual behavior

E! [inputs.socket_listener] Error in plugin: connection not a TCP connection (*tls.Conn)
