### ISSUE TITLE
AWS Timestream Empty MeasureValue

### ISSUE THREAD

**Issue by hadiel05** [influxdata/telegraf#13073]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "1s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Pick a timezone to use when logging or type 'local' for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true

[[inputs.file]]
    files = ["test.json"]
    data_format = "json_v2"
       [[inputs.file.json_v2]]
           measurement_name = "hadieltest"
           [[inputs.file.json_v2.object]]
              path = "token_infos"
              tags = ["token_id"]


 [[outputs.timestream]]
    region = "us-east-1"
    database_name = "dev-ts"
    describe_database_on_start = false
    mapping_mode = "multi-table"
    create_table_if_not_exists = true
    use_multi_measure_records = true
    measure_name_for_multi_measure_records = "telegraf_measure"
    create_table_magnetic_store_retention_period_in_days = 120
    create_table_memory_store_retention_period_in_hours = 24
    max_write_go_routines = 25
```

### Logs from Telegraf

```text
! [outputs.timestream] Failed to write to Timestream database "dev-ts" table "hadieltest": operation error Timestream Write: WriteRecords, https response error StatusCode: 400, RequestID: ZNH77HW3QVFQVWGUEBV2TXO2OY, ValidationException: . Skipping metric!
```

### System info

Docker Latest 

### Steps to reproduce

1. create test.json file 
```
## test.json file 

{
  "token_infos": [
    {
      "token_id": "123456",
      "field1": 123,
      "field2": 123,
      "field3": 123,
      "emptyfield": ""
    }

  ]
}
```
2. run with the given telegraf config file ` telegraf --config telegraf.conf --once`

...

### Expected behavior

write data to timestream

### Actual behavior

error E! [outputs.timestream] Failed to write to Timestream database

**Comment by hadiel05** [comment]
Looking at aws [docs](https://docs.aws.amazon.com/timestream/latest/developerguide/API_Record.html) looks like their is a constraint (Length Constraints: Minimum length of 1. Maximum length of 2048.)

**Comment by gerardocorea** [comment]
Would the best thing be to simply log out something saying that it hitting that constraint?

**Comment by powersj** [comment]
Internally your example JSON creates the following metric in Telegraf:

```
hadieltest,token_id=123456 field1=123,field2=123,field3=123,emptyfield="" 1681830045000000000
```

I assume the issue is with the emptyfield? Couple ideas for a workaround if that is the case:

1) use the defaults processor to set a value there when it is empty

```toml
[[processors.defaults]]
  [processors.defaults.fields]
    emptyfield = "default_value"
```

2) use starlark processor to drop the field if it is empty

```toml
[[processors.starlark]]
  source = '''
def apply(metric):
   if "emptyfield" in metric.fields and metric.fields["emptyfield"] == "":
      metric.fields.pop("emptyfield")

   return metric
'''
```

Would either of these help in your situation?
