### ISSUE TITLE
telegraf service status claims inactive/not running when telegraf is

### ISSUE THREAD

**Issue by jfrye121** [influxdata/telegraf#13086]
### Relevant telegraf.conf

```toml
###############################################################################
#                            SECRETSTORE PLUGINS                              #
###############################################################################


# # File based Javascript Object Signing and Encryption based secret-store
[[secretstores.jose]]
#   ## Unique identifier for the secret-store.
#   ## This id can later be used in plugins to reference the secrets
#   ## in this secret-store via @{<id>:<secret_key>} (mandatory)
 id = "my_secretstore"
#
#   ## Directory for storing the secrets
 path = "/etc/telegraf/secrets"
#
#   ## Password to access the secrets.
#   ## If no password is specified here, Telegraf will prompt for it at startup time.
#   # password = ""

[[inputs.mysql]]
  servers = ["SumoMonitoring:@{my_secretstore:SumoMonitoring}@tcp(redacted:3306)/?tls=false"]
  metric_version = 2
  table_schema_databases = []
  perf_summary_events = []
  gather_table_schema = true
  gather_process_list = true
  gather_info_schema_auto_inc = true
  gather_user_statistics = true
  gather_slave_status = true
  gather_table_io_waits = true
  gather_table_lock_waits = true
  gather_index_io_waits = true
  gather_event_waits = true
  gather_file_events_stats = true
  gather_perf_events_statements = true
  interval_slow = "30m"
[inputs.mysql.tags]
  environment="prod"
  component="database"
  db_system="mariadb"
  db_cluster="default"
  db_cluster_address = "redacted"
  db_cluster_port = "3306"
[[outputs.sumologic]]
  url = "redacted"
  data_format = "prometheus"
```

### Logs from Telegraf

```text
2023-04-13T20:03:24Z I! Starting Telegraf 1.26.1
2023-04-13T20:03:24Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-04-13T20:03:24Z I! Loaded inputs: cpu disk diskio kernel mem mysql processes swap system
2023-04-13T20:03:24Z I! Loaded aggregators:
2023-04-13T20:03:24Z I! Loaded processors:
2023-04-13T20:03:24Z I! Loaded secretstores: my_secretstore
2023-04-13T20:03:24Z W! ^[[31mOutputs are not used in testing mode!^[[0m
2023-04-13T20:03:24Z I! Tags enabled: host=ip-10-0-0-25
2023-04-13T20:03:24Z D! [agent] Initializing plugins
2023-04-13T20:03:24Z D! [agent] Starting service inputs
2023-04-13T20:03:24Z D! [agent] Stopping service inputs
2023-04-13T20:03:24Z D! [agent] Input channel closed
2023-04-13T20:03:24Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.26.1 (git: HEAD@8f421f25)

### Steps to reproduce

1. Update Telegraf to latest version (1.26.1)
2. Update config to take advantage of secret store
3. Store Secrets 
4. Run `telegraf` 
5. Enter passphrase to unlock secretstore
6. No additional lines outputted on shell
7. Check telegraf logs-they are showing no errors and that telegraf is running
8. Run `service telegraf status` to see if service is running
...

### Expected behavior

telegraf service is running/shows active

### Actual behavior

shows inactive or failed if attempts to start via `service telegraf start` are passed. The only way to get telegraf "running" is to execute `telegraf` in shell.

### Additional info

I was going through the process of updating telegraf to the latest version that includes some bugfixes for utilizing secret store. In order to start telegraf, I execute `telelgraf` and I am asked to enter passphrase to unlock secret store secrets. Once completed, my session behaves as follows:

![runningtelegraf](https://user-images.githubusercontent.com/34147973/231873170-7c0b2dfd-f986-46f0-8e95-8a13377ff280.png)

The log fills with information, no errors, and I am getting metrics in sumologic. So it seems to be working as it should.
![telegraflog](https://user-images.githubusercontent.com/34147973/231873582-790a9683-78fd-4095-a50b-7435902fe345.png)

However, if you check to see if the service is running (ie `service telegraf status` or `systemctl status telegraf`) it shows that the service is not running.
![servicestatus](https://user-images.githubusercontent.com/34147973/231873665-7a7d1656-703a-4e0b-9381-f8cbe574c9e8.png)

 htop...you can see a pid of "telegraf" is indeed running

![htop](https://user-images.githubusercontent.com/34147973/231873752-0c90d5f5-306d-4614-a2bf-0d5c669a38f2.png)

I am unsure if this is the expected behavior or unintended behavior.
