### ISSUE TITLE
Lustre2 Jobstats read_bytes line beeing overwriten by read latency

### ISSUE THREAD

**Issue by mjurksa** [influxdata/telegraf#13083]
### Relevant telegraf.conf

```toml
[[inputs.lustre2]]
  alias = "lustre2-ost-jobstats"
  mds_procfiles = [""]
  ost_procfiles = ["/proc/fs/lustre/obdfilter/*/job_stats"]
  # measurement name for OST jobstats
  name_override = "ost_jobstats"

[[inputs.lustre2]]
  alias = "lustre2-mdt-jobstats"
  ost_procfiles = [""]
  mds_procfiles = ["/proc/fs/lustre/mdt/*/job_stats"]
  # measurement name for MDT jobstats
  name_override = "mdt_jobstats"

[[processors.strings]]
  alias = "jobstats-strings"
  # Trim prefix from the field keys (e.g. jobstats_read_bytes => read_bytes)
  [[processors.strings.trim_prefix]]
    measurement = "*_jobstats"
    field_key = "*"
    prefix = "jobstats_"
```

### Logs from Telegraf

```text
ost_jobstats,fs_name=xxxx,host=xxxx,jobid=xxx,jobnode=xxx,jobuid=xxx,target=xxx write_max_size=20601i,quotactl=0i,punch=52491i,ost_sync=0i,read_min_size=1i,ost_statfs=0i,set_info=0i,write_calls=5607608i,ost_getattr=0i,write_min_size=3i,read_max_size=447440i,read_bytes=628435720i,ost_setattr=0i,write_bytes=451436126i,destroy=0i,read_calls=1525515i,get_info=0i,create=0i 1681372300000000000
```

### System info

Telegraf 1.26, CentOS Linux release 7.9.2009, lustre-server-2.12.8

### Steps to reproduce

Enable Jobstats

### Expected behavior

Jobstats values from line read/write_bytes beeing written to database

### Actual behavior

Jobstats read/write_bytes stats is beeing overwriten by read/write line from jobstats (latency) instead. 

### Additional info

Lustre read_bytes metric is definied in the lustre2 plugin as follows:
https://github.com/influxdata/telegraf/blob/302ac88bdbedb11020ba82a8f715f3cb0bd6290a/plugins/inputs/lustre2/lustre2.go#L86-L123

The code then overwrites read_bytes by read (latency in line[5] example below) as they have the same 'reportAs' name to keep compability between lustre versions, when both lines exists. This is an issue for "newer" lustre builds. Tested on 2.12.8 and 2.14.0:

```
- job_id:          xxxx:xxx:xxxx
  snapshot_time:   1681372306
  read_bytes:      { samples:     1523680, unit: bytes, min:     4096, max:   524288, sum:     205693874176, sumsq:  41153530404274176 }
  write_bytes:     { samples:     5602760, unit: bytes, min:       48, max:   524288, sum:    2935700676043, sumsq: 1538734750279526901 }
  read:            { samples:     1525515, unit: usecs, min:        1, max:   447440, sum:        628435720, sumsq:     28075770829850 }
  write:           { samples:     5607608, unit: usecs, min:        3, max:    20601, sum:        451436126, sumsq:        40139939376 }
  getattr:         { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  setattr:         { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  punch:           { samples:       52491, unit: usecs, min:       11, max:   685124, sum:        367120431, sumsq:     12123013355015 }
  sync:            { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  destroy:         { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  create:          { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  statfs:          { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  get_info:        { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  set_info:        { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  quotactl:        { samples:           0, unit: usecs, min:        0, max:        0, sum:                0, sumsq:                  0 }
  prealloc:        { samples:           0, unit:  reqs }
```

Overwritten by:
https://github.com/influxdata/telegraf/blob/302ac88bdbedb11020ba82a8f715f3cb0bd6290a/plugins/inputs/lustre2/lustre2.go#L431-L435

Metric results then to 451436126 micro seconds instead of 2935700676043 bytes:
```
ost_jobstats,fs_name=xxxx,host=xxxx,jobid=xxx,jobnode=xxx,jobuid=xxx,target=xxx write_max_size=20601i,quotactl=0i,punch=52491i,ost_sync=0i,read_min_size=1i,ost_statfs=0i,set_info=0i,write_calls=5607608i,ost_getattr=0i,write_min_size=3i,read_max_size=447440i,read_bytes=628435720i,ost_setattr=0i,write_bytes=451436126i,destroy=0i,read_calls=1525515i,get_info=0i,create=0i 1681372300000000000
```
