### ISSUE TITLE
internet_speed - function "test_mode" and "connections" do not work

### ISSUE THREAD

**Issue by dontobi** [influxdata/telegraf#13080]
### Relevant telegraf.conf

```toml
[[inputs.internet_speed]]
  interval = "1h"
  memory_saving_mode = false
  cache = false
  connections = 8
  test_mode = "multi"
  # server_id_exclude = []
  server_id_include = ["1746"]
```

### Logs from Telegraf

```text
2023-04-13T06:25:13Z I! Loading config file: /etc/telegraf/telegraf.conf
2023-04-13T06:25:13Z E! error loading config file /etc/telegraf/telegraf.conf: plugin inputs.internet_speed: line 44: configuration specified the fields ["connections" "test_mode"], but they weren't used
```

### System info

Telegraf 1.26.1, Raspbian GNU/Linux 11 (bullseye), Docker 23.0.3

### Steps to reproduce

1. activate "test_mode" and "connections" in telegraf.conf
2. restart telegraf
3. check the log file

### Expected behavior

The documentation describes the options, so I assumed that they would work. Apparently they do not.
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/internet_speed/README.md

### Actual behavior

I receive the error messages listed. If I delete the lines in telegraf.conf, the speed test works without problems and I get no error messages.
