### ISSUE TITLE
Does  outputs.http support the Content-Type as "application/proto;charset=utf-8"? 

### ISSUE THREAD

**Issue by iceyfighting** [influxdata/telegraf#13097]
### Relevant telegraf.conf

```toml
[[outputs.http]]
  ## URL is the address to send metrics to
  url = "http://127.0.0.1:8080/telegraf"

  ## Timeout for HTTP message
  # timeout = "5s"

  ## HTTP method, one of: "POST" or "PUT"
  # method = "POST"
  ## Additional HTTP headers
  [outputs.http.headers]
  #   # Should be set manually to "application/json" for json data_format
   Content-Type = "application/proto;charset=utf-8"
```

### Logs from Telegraf

```text
无
```

### System info

Telegraf 1.24.0 Centos6.5

### Steps to reproduce

none

### Expected behavior

none

### Actual behavior

none
