### ISSUE TITLE
Smart attributes can not be fully collected

### ISSUE THREAD

**Issue by zzcpower** [influxdata/telegraf#13090]
### Relevant telegraf.conf

```toml
[[inputs.smart]]
attributes = true
namepass = ['smart_attribute']
fielddrop = ["exit_status","threshold","value","worst"]
tagexclude = ["flags"]
[[processors.pivot]]
tag_key = "id"
value_key = "raw_value"
[[processors.converter]]
[processors.converter.tags]
measurement = ["name"]
[[aggregators.merge]]
drop_original = true
```

### Logs from Telegraf

```text
There is no error logs.
```

### System info

Telegraf 1.15.4, CentOS Linux release 7.4.1708 (Core) 

### Steps to reproduce

smartctl -A /dev/sde -d megaraid,19

<img width="929" alt="image" src="https://user-images.githubusercontent.com/41858357/232038244-64bb9351-6459-4b85-b595-522b8f6356f7.png">

telegraf --config smart.conf --test|grep sde
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/41858357/232034816-469cfcfb-b233-41cb-b6ab-75f23d7cd76e.png">

### Expected behavior

Expect all smart attributes can be collected

### Actual behavior

Only smart attribute 194(Temperature_Celsius) can be collected.

### Additional info

Hi, there
I would like to collect smart attributes by using telegraf smart inputs plugin, anyone can help please?

Any further information will be applied if needed. Appreciate it!
