### ISSUE TITLE
json_v2 parser ignoring keys

### ISSUE THREAD

**Issue by davidaugustin1** [influxdata/telegraf#13111]
### Relevant telegraf.conf

```toml
[agent]
    omit_hostname = true
[[inputs.file]]
    files = ["input.json"]
    data_format = "json_v2"
    [[inputs.file.json_v2]]
        measurement_name = "prometheus_query"
        timestamp_path = "data.result.0.value.0"
        timestamp_format = "unix"
        [[inputs.file.json_v2.object]]
            path = "data.result"
            disable_prepend_keys = true
            [[inputs.file.json_v2.object.field]]
                path = "#.value.1"
                rename = "sap_availability"
                type = "int"
            [[inputs.file.json_v2.object.tag]]
                path = "#.metric.instance"
            [[inputs.file.json_v2.object.tag]]
                path = "#.metric.system"
            [[inputs.file.json_v2.object.tag]]
                path = "#.metric.sammlung"
```

### Logs from Telegraf

```text
M:\teletest>telegraf1261.exe -config "sap_availability_wintest3.conf" --test --debug
2023-04-19T06:20:58Z I! Loading config file: sap_availability_wintest3.conf
2023-04-19T06:20:58Z I! Starting Telegraf 1.26.1
2023-04-19T06:20:58Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
2023-04-19T06:20:58Z I! Loaded inputs: file
2023-04-19T06:20:58Z I! Loaded aggregators:
2023-04-19T06:20:58Z I! Loaded processors:
2023-04-19T06:20:58Z I! Loaded secretstores:
2023-04-19T06:20:58Z W! ←[31mOutputs are not used in testing mode!←[0m
2023-04-19T06:20:58Z I! Tags enabled:
2023-04-19T06:20:58Z D! [agent] Initializing plugins
2023-04-19T06:20:58Z D! [agent] Starting service inputs
2023-04-19T06:20:58Z D! [agent] Stopping service inputs
> prometheus_query sap_availability=1i 1681809388000000000
2023-04-19T06:20:58Z D! [agent] Input channel closed
> prometheus_query sap_availability=1i 1681809388000000000
2023-04-19T06:20:58Z D! [agent] Stopped Successfully
```

### System info

Telegraf 1.26.1, Telegraf 1.23.0, Telegraf 1.22.4, Windows 10

### Steps to reproduce

1. Save json text to file `{
	"status":"success",
	"data":{
		"resultType":"vector",
		"result":[
			{
				"metric":{
					"__name__":"sap_availability",
					"instance":"server1",
					"sammlung":"sap",
					"system":"C22"
				},
				"value":[
					1681809388.095,
					"1"
				]
			},{
				"metric":{
					"__name__":"sap_availability",
					"instance":"server2",
					"sammlung":"sap",
					"system":"POP"
				},
				"value":[
					1681809388.095,
					"1"
				]
			}
		]
	}
}`
2. Run config with Telegraf 1.22.4 => Expected behavior
3. Run config with any Telegraf after 1.22.4 => Actual behavior
...

### Expected behavior

Get this as output
`prometheus_query,instance=server1,sammlung=sap,system=C22 sap_availability=1i 1681809388000000000`
`prometheus_query,instance=server2,sammlung=sap,system=POP sap_availability=1i 1681809388000000000`

### Actual behavior

Tags are missing in output
`prometheus_query sap_availability=1i 1681809388000000000` 
`prometheus_query sap_availability=1i 1681809388000000000`

### Additional info

It seems to me, that the missing keys are ignored, no matter if configured as tag or as field. The only difference between the metric and the value node is, that the key I want to read rom value is stored in an array. 
The closest example I found is the "[subfieldtag_in_object](https://github.com/influxdata/telegraf/blob/master/plugins/parsers/json_v2/testdata/subfieldtag_in_object/telegraf.conf)" configuration in testdata. There, the tags are stored in arrays, or without a sub node like #.abbr.
When I try my configuration at the gjson playground at https://gjson.dev/ , it shows the right keys.

![image](https://user-images.githubusercontent.com/52286398/232991679-b80bd66b-4f6b-4b13-9647-aa13efd6d786.png)

The json is from a Prometheus API query.
I also tried using only tags, excluded_keys and included_keys but because the value key is stored in an array, I get the timestamp, which is stored in the same array as additional value with the same name and the same labelset.
Mixing included_keys[], tags[] and json_v2.object.field/json_v2.object.tag didnt work either.

**Comment by davidaugustin1** [comment]
As a workaround I use this configuration:

`[agent]
    omit_hostname = true
[[inputs.file]]
    files = ["input.json"]
    data_format = "json_v2"
    [[inputs.file.json_v2]]
        measurement_name = "prometheus_query"
        timestamp_path = "data.result.0.value.0"
        timestamp_format = "unix"
        [[inputs.file.json_v2.object]]
          path = "data.result"
          tags = ["metric_sammlung", "metric_system", "metric_instance", "metric___name__"]
          excluded_keys = []
          included_keys = ["value"]
          disable_prepend_keys = true

[[processors.regex]]
  order = 1
  namepass = ["prometheus_query"]
  [processors.regex.tagpass]
    __name__ = ["sap_availability"]
  [[processors.regex.fields]]
    key = "value"
    pattern = "^(\\d)$"
    replacement = "$1"
    result_key = "sap_availability"
[[processors.converter]]
  order = 2
  namepass = ["prometheus_query"]
  fielddrop = ["value"]
  tagexclude = ["__name__"]
  [processors.converter.tagpass]
    __name__ = ["sap_availability"]
  [processors.converter.fields]
    integer = ["sap_availability"]`

The unwanted timestamp value gets dropped. But this just works if the values are easy distinguishable.

**Comment by srebhan** [comment]
@davidaugustin1 you should use the [xpath parser]() for extracting the data with
```toml
[[inputs.file]]
  files = ["test_configs/jsontest_issue_13111.json"]

  tagexclude = ["__name__"]
  data_format = "xpath_json"
  xpath_native_types = true

  [[inputs.file.xpath]]
    metric_name = "'prometheus_query'"
    timestamp = "value/*[1]"
    timestamp_format = "unix"
    metric_selection = "//result/*"
    tag_selection = "metric/*"
    field_selection = "value/*[2]"
    field_name = "../../metric/__name__"
```
you get
```
> prometheus_query,host=Hugin,instance=server1,sammlung=sap,system=C22 sap_availability="1" 1681809388000000000
> prometheus_query,host=Hugin,instance=server2,sammlung=sap,system=POP sap_availability="1" 1681809388000000000
```
