### ISSUE TITLE
"invalid TOML syntax" for inputs.kafka_consumer - avro_schema

### ISSUE THREAD

**Issue by dan-m-joh** [influxdata/telegraf#13123]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]
  brokers = ["localhost:9092"]
  topics = ["perfmon_metrics_switch"]
  max_message_len = 1000000
  data_format = "avro"
  #avro_schema = """
  #        {
  #          "type":"record",
  #          "name":"Value",
  #          "namespace":"com.example",
  #          "fields":[
  #              {
  #                  "name":"tag",
  #                  "type":"string"
  #              },
  #              {
  #                  "name":"field",
  #                  "type":"long"
  #              },
  #              {
  #                  "name":"timestamp",
  #                  "type":"long"
  #              }
  #          ]
  #      }
  #"""

  avro_schema = """
        {
                "type":"record",
                "name":"fibrechannel_switch_statistics",
                "namespace":"com.brocade.streaming",
                "fields":[
                        {
                                "name":"switch_wwn",
                                "type":"string"
                        },
                        {
                                "name":"statistics_collection_time",
                                "type":"long"
                        },
                        {
                                "name":"up_time",
                                "type":"long"
                        },
                        {
                                "name":"cpu_utilization",
                                "type":"float"
                        },
                        {
                                "name":"memory_utilization",
                                "type":"float"
                        }
                ]
        }
  """

  avro_timestamp_format = "unix"
```

### Logs from Telegraf

```text
As telegraf does not even start with the inputs.kafka_consumer "enabled" I have no logs to share.
```

### System info

Telegraf 1.26.1, AlmaLinux release 8.7 (Stone Smilodon), Kafka-Version: 7.3.3-ccs

### Steps to reproduce

Enable the inputs.kafka_consumer section in telegraf.conf using the parameter avro_schema=...
Even using the default example it does not work and telegraf does not start.

### Expected behavior

Telegraf starts and consumes streams from Kafka.

### Actual behavior

Here is what the output looks like using the above config (yes output plugin is missing, but that is not the issue):
```
# telegraf --config /etc/telegraf/kafka_input.conf  --test --debug
2023-04-21T12:13:01Z I! Loading config file: /etc/telegraf/kafka_input.conf
2023-04-21T12:13:01Z E! error loading config file /etc/telegraf/kafka_input.conf: error parsing data: line 30: invalid TOML syntax
```
