### ISSUE TITLE
Syslog input + Graylog output failing parsing timestamp field

### ISSUE THREAD

**Issue by estigma88** [influxdata/telegraf#13134]
### Relevant telegraf.conf

```toml
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "token"
  organization = "primary"
  bucket = "streaming-engine"
[[inputs.syslog]]
  server = "udp://:5514"
[[outputs.graylog]]
  namepass = [
    "syslog*"
  ]
  servers = [
    "udp://graylog:12201"
  ]
  short_message_field = "message"
```

### Logs from Telegraf

```text
graylog          | [1]: index [graylog_0], type [_doc], id [501e84a0-e2c7-11ed-a906-0242c0a84006], message [ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [timestamp] of type [date] in document with id '501e84a0-e2c7-11ed-a906-0242c0a84006'. Preview of field's value: '292278994-08-17 07:12:55.807']]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to parse date field [292278994-08-17 07:12:55.807] with format [uuuu-MM-dd HH:mm:ss.SSS]]]; nested: ElasticsearchException[Elasticsearch exception [type=date_time_parse_exception, reason=Text '292278994-08-17 07:12:55.807' could not be parsed at index 0]];]
```

### System info

Telegraf 1.24, Ubuntu 20.04, Influx 2.3.0

### Docker

```
version: '3.6'
services:
  influxdb:
    image: bitnami/influxdb:2.3.0-debian-11-r15
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=admin1234
      - INFLUXDB_ORG=primary
      - INFLUXDB_ADMIN_BUCKET=streaming-engine
      - INFLUXDB_ADMIN_USER_TOKEN=token
    volumes:
      - influx_data:/bitnami/influxdb
    ports:
      - '8086:8086'
  telegraf:
    image: telegraf:1.24
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'
      - "5514:5514/udp"
  mongodb:
    image: mongo:6.0.4
    ports:
      - '27017:27017'
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  #    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:5.0.6
    container_name: graylog
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_EXTERNAL_URI: http://127.0.0.1:9000/
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api/
      GRAYLOG_HTTP_ENABLE_CORS: 'true'
      # configuration script env vars
      GRAYLOG_USER: admin
      GRAYLOG_PASSWORD: admin
      GRAYLOG_URL: http://127.0.0.1:9000
    links:
      - mongodb:mongo
      - elasticsearch
    restart: always
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
```

### Steps to reproduce

1. Set the telegraf.conf file alonside the docker compose file
2. Start the docker compose file
3. Wait for containers to stabilize
4. Log in to graylog UI at [http://localhost:9000](http://localhost:9000)
5. Go to [http://localhost:9000/system/inputs](http://localhost:9000/system/inputs)
6. Launch a new GELF UDP input, with default values, and Global checked, similar to the following image
![image](https://user-images.githubusercontent.com/27821251/234074080-82ed2314-c9a8-46c7-9294-59c94a2ad83a.png)
7. Input should mark green as running
8. Send a Syslog RFC5424 message to `udp://:5514` including a timestamp. You will see the following graylog log:
```
graylog          | [1]: index [graylog_0], type [_doc], id [501e84a0-e2c7-11ed-a906-0242c0a84006], message [ElasticsearchException[Elasticsearch exception [type=mapper_parsing_exception, reason=failed to parse field [timestamp] of type [date] in document with id '501e84a0-e2c7-11ed-a906-0242c0a84006'. Preview of field's value: '292278994-08-17 07:12:55.807']]; nested: ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=failed to parse date field [292278994-08-17 07:12:55.807] with format [uuuu-MM-dd HH:mm:ss.SSS]]]; nested: ElasticsearchException[Elasticsearch exception [type=date_time_parse_exception, reason=Text '292278994-08-17 07:12:55.807' could not be parsed at index 0]];]
```

### Expected behavior

The GELF message sent from telegraf to graylog succeed

### Actual behavior

An exception is thrown:

```failed to parse date field [292278994-08-17 07:12:55.807] with format [uuuu-MM-dd HH:mm:ss.SSS]]```

### Additional info

I did some debugging, checking the souce code of the `input.syslog`, I see how the timestamp [is saved in Influx as UNIX nano](https://github.com/influxdata/telegraf/blob/release-1.24/plugins/inputs/syslog/syslog.go#L394), which I can confirm in the Influx UI:
![image](https://user-images.githubusercontent.com/27821251/234075698-b2c4080a-5920-445c-a48d-dac09d6a5925.png)

The `output.graylog` is parsing that timestamp to milliseconds plus decimal data, [here](https://github.com/influxdata/telegraf/blob/release-1.24/plugins/outputs/graylog/graylog.go#L385), which complies with the [GELF standard](https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html#gelf-payload-specification).

Finally, if we stop the graylog UDP GELF input and send a Syslog message, we get the following telegraf error:

```
telegraf         | 2023-04-24T17:49:08Z E! [agent] Error writing to outputs.graylog: error writing message: "{\"_App@1_category\":\"io.micrometer.influx.InfluxMeterRegistry\",\"_App@1_exception\":\"java.net.UnknownHostException: host.docker.internal\n\",\"_App@1_priority\":\"ERROR\",\"_App@1_thread\":\"influx-metrics-publisher\",\"_appname\":\"control-api\",\"_facility_code\":16,\"_hostname\":\"Precision-3551\",\"_msgid\":\"Audit\",\"_name\":\"syslog\",\"_procid\":\"67059\",\"_severity\":\"err\",\"_severity_code\":3,\"_source\":\"192.168.64.1\",\"_streaming_id\":\"123456\",\"facility\":\"local0\",\"host\":\"39379784fdd1\",\"short_message\":\"failed to send metrics to influx\",\"timestamp\":1682358546849000000,\"version\":1}", write udp 192.168.64.5:42187->192.168.64.6:12201: write: connection refused
```

It gets connection refused, which makes sense, however, the interesting part is the printed JSON:
```
{
  "_App@1_category": "io.micrometer.influx.InfluxMeterRegistry",
  "_App@1_exception": "java.net.UnknownHostException: host.docker.internal",
  "_App@1_priority": "ERROR",
  "_App@1_thread": "influx-metrics-publisher",
  "_appname": "control-api",
  "_facility_code": 16,
  "_hostname": "Precision-3551",
  "_msgid": "Audit",
  "_name": "syslog",
  "_procid": "67059",
  "_severity": "err",
  "_severity_code": 3,
  "_source": "192.168.64.1",
  "_streaming_id": "123456",
  "facility": "local0",
  "host": "39379784fdd1",
  "short_message": "failed to send metrics to influx",
  "timestamp": 1682358546849000000,
  "version": 1
}
```

The timestamp is not decimal, as we expect from [this code](https://github.com/influxdata/telegraf/blob/release-1.24/plugins/outputs/graylog/graylog.go#L385) , and the version must be 1.1, as [for this code](https://github.com/influxdata/telegraf/blob/release-1.24/plugins/outputs/graylog/graylog.go#L384) . Although, regarding the version field, I do see 1 in Influxdb:
![image](https://user-images.githubusercontent.com/27821251/234078910-2b1bae2f-382c-4e12-8a5e-cc4aa67715fe.png)

Could this be a problem of JSON serialization? thanks in advance

**Comment by powersj** [comment]
Hi,

Is the graylog output failing on any udp syslog message? If not can you find the syslog message that this is failing on. Presumably I could take that message and reproduce this.

```
failed to parse date field [292278994-08-17 07:12:55.807] with format [uuuu-MM-dd HH:mm:ss.SSS]]];
```

That certainly does not look like a valid timestamp :)

Thanks

**Comment by estigma88** [comment]
Hi,

You can use `logger` in Linux systems to send the RFC5424 message, for instance:

```
logger -n localhost -P 5514 -p user.notice -t appname '[exampleSDID@32473 iut="3" eventSource="Application" eventID="1011"] - This is a sample syslog message in RFC5424 format.'
```

This is the generated RFC5424 message for the previous command:

```
<13>1 2023-04-26T10:30:00.123456-07:00 hostname appname procid msgid [exampleSDID@32473 iut="3" eventSource="Application" eventID="1011"] - This is a sample syslog message in RFC5424 format.
```

Using `logger` the weird date appears, hope this is enough for debugging proposes.

Regards.

**Comment by powersj** [comment]
Thanks for the command. What is the failure rate you are seeing? All messages to graylog fail? some? one or two?

Using that produces a line protocol of:

```
syslog,appname=appname,facility=user,host=ryzen,hostname=ryzen,severity=notice,source=::1 severity_code=5i,timestamp=1682611057616299000i,message="[exampleSDID@32473 iut=\"3\" eventSource=\"Application\" eventID=\"1011\"] - This is a sample syslog message in RFC5424 format.",version=1i,timeQuality_tzKnown="1",timeQuality_isSynced="1",timeQuality_syncAccuracy="190500",facility_code=1i 1682611057616426625
```

I added a quick test using that and was able to verify it parsed the line as expected.

> The timestamp is not decimal, as we expect from [this code](https://github.com/influxdata/telegraf/blob/release-1.24/plugins/outputs/graylog/graylog.go#L385) , and the version must be 1.1, as [for this code](https://github.com/influxdata/telegraf/blob/release-1.24/plugins/outputs/graylog/graylog.go#L384) . Although, regarding the version field, I do see 1 in Influxdb:

You noticed that when telegraf runs serialize it sets up some initial tags, like version = 1.1, the timestamp divided, etc. However, if you go further down in the serialize function telegraf will loop through the tag and field lists, which can override these keys. 

This means, that if your original message had version 1, which your example logger command provides, the version will report as 1. This is also why you see version 1 in influxdata.

I used the [Graylog docker compose files](https://github.com/Graylog2/docker-compose) to set up Graylog and was able to successfully send messages using the logger command you provided:

```s
2023-04-27T17:01:06Z D! [agent] Attempting connection to [outputs.graylog]
2023-04-27T17:01:06Z D! [agent] Successfully connected to outputs.graylog
2023-04-27T17:01:06Z D! [agent] Attempting connection to [outputs.file]
2023-04-27T17:01:06Z D! [agent] Successfully connected to outputs.file
2023-04-27T17:01:06Z D! [agent] Starting service inputs
2023-04-27T17:01:16Z D! [outputs.graylog] Buffer fullness: 0 / 10000 metrics
2023-04-27T17:01:16Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
syslog,appname=appname,facility=user,host=ryzen,hostname=ryzen,severity=notice,source=::1 version=1i,timeQuality_syncAccuracy="52000",timeQuality_tzKnown="1",timeQuality_isSynced="1",facility_code=1i,severity_code=5i,timestamp=1682614877447786000i,message="[exampleSDID@32473 iut=\"3\" eventSource=\"Application\" eventID=\"1011\"] - This is a sample syslog message in RFC5424 format." 1682614877447912236
2023-04-27T17:01:26Z D! [outputs.file] Wrote batch of 1 metrics in 55.8µs
2023-04-27T17:01:26Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-04-27T17:01:26Z D! [outputs.graylog] Wrote batch of 1 metrics in 261.132µs
2023-04-27T17:01:26Z D! [outputs.graylog] Buffer fullness: 0 / 10000 metrics
2023-04-27T17:01:36Z D! [outputs.graylog] Buffer fullness: 0 / 10000 metrics
2023-04-27T17:01:36Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
syslog,appname=appname,facility=user,host=ryzen,hostname=ryzen,severity=notice,source=::1 timeQuality_isSynced="1",timeQuality_syncAccuracy="63000",facility_code=1i,severity_code=5i,timestamp=1682614899440045000i,message="[exampleSDID@32473 iut=\"3\" eventSource=\"Application\" eventID=\"1011\"] - This is a sample syslog message in RFC5424 format.",version=1i,timeQuality_tzKnown="1" 1682614899440131143
2023-04-27T17:01:46Z D! [outputs.file] Wrote batch of 1 metrics in 41.73µs
2023-04-27T17:01:46Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-04-27T17:01:46Z D! [outputs.graylog] Wrote batch of 1 metrics in 188.991µs
2023-04-27T17:01:46Z D! [outputs.graylog] Buffer fullness: 0 / 10000 metrics
syslog,appname=appname,facility=user,host=ryzen,hostname=ryzen,severity=notice,source=::1 message="[exampleSDID@32473 iut=\"3\" eventSource=\"Application\" eventID=\"1011\"] - This is a sample syslog message in RFC5424 format.",version=1i,timeQuality_tzKnown="1",timeQuality_isSynced="1",timeQuality_syncAccuracy="67000",facility_code=1i,severity_code=5i,timestamp=1682614907319891000i 1682614907319957783
syslog,appname=appname,facility=user,host=ryzen,hostname=ryzen,severity=notice,source=::1 facility_code=1i,severity_code=5i,timestamp=1682614907648203000i,message="[exampleSDID@32473 iut=\"3\" eventSource=\"Application\" eventID=\"1011\"] - This is a sample syslog message in RFC5424 format.",version=1i,timeQuality_tzKnown="1",timeQuality_isSynced="1",timeQuality_syncAccuracy="67000" 1682614907648304818
syslog,appname=appname,facility=user,host=ryzen,hostname=ryzen,severity=notice,source=::1 timeQuality_syncAccuracy="67000",facility_code=1i,severity_code=5i,timestamp=1682614907984137000i,message="[exampleSDID@32473 iut=\"3\" eventSource=\"Application\" eventID=\"1011\"] - This is a sample syslog message in RFC5424 format.",version=1i,timeQuality_tzKnown="1",timeQuality_isSynced="1" 1682614907984223135
syslog,appname=appname,facility=user,host=ryzen,hostname=ryzen,severity=notice,source=::1 facility_code=1i,severity_code=5i,timestamp=1682614908304169000i,message="[exampleSDID@32473 iut=\"3\" eventSource=\"Application\" eventID=\"1011\"] - This is a sample syslog message in RFC5424 format.",version=1i,timeQuality_tzKnown="1",timeQuality_isSynced="1",timeQuality_syncAccuracy="67500" 1682614908304256657
2023-04-27T17:01:56Z D! [outputs.file] Wrote batch of 4 metrics in 61.371µs
2023-04-27T17:01:56Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2023-04-27T17:01:56Z D! [outputs.graylog] Wrote batch of 4 metrics in 716.566µs
2023-04-27T17:01:56Z D! [outputs.graylog] Buffer fullness: 0 / 10000 metrics
```

I think understanding how often are messages failing and what message is causing this would be the next step.

**Comment by estigma88** [comment]
It happens every time, if I run multiple times `logger`, multiple times the parser error appears:

![image](https://user-images.githubusercontent.com/27821251/234959080-c2b5756b-89cc-4cff-9926-0a2cf8df0a02.png)

Doing more testing, I realized that the `outputs.influxdb_v2` in the telegraf config is not needed (and therefore the `influxdb` container), so, the final telegraf config looks like:

```
[[inputs.syslog]]
  server = "udp://:5514"
[[outputs.graylog]]
  namepass = [
    "syslog*"
  ]
  servers = [
    "udp://graylog:12201"
  ]
  short_message_field = "message"
```

Also, I updated my docker-compose with the [Graylog docker compose files](https://github.com/Graylog2/docker-compose), as follows:

```
version: '3.6'
services:
  telegraf:
    image: telegraf:1.24
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - '8125:8125'
      - "5514:5514/udp"
  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - "os_data:/usr/share/opensearch/data"
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.0}"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_USER: admin
      GRAYLOG_PASSWORD: admin
      GRAYLOG_URL: http://127.0.0.1:9000
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW TCP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      #- "10000:10000/tcp" # Custom TCP port
      #- "10000:10000/udp" # Custom UDP port
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"

volumes:
  mongodb_data:
  os_data:
  graylog_data:
  graylog_journal:
```

It still fails in my tests.
