### ISSUE TITLE
Support JSON encoding for avro parser

### ISSUE THREAD

**Issue by dan-m-joh** [influxdata/telegraf#13155]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]
  brokers = ["<hostname>:9093"]
  topics = ["perfmon_metrics_switch"]
  version = "7.3.3"
  insecure_skip_verify = true
  max_message_len = 1000000
  data_format = "avro"
  avro_schema = '''
        {
                "namespace": "com.brocade.streaming",
                "name": "fibrechannel_switch_statistics",
                "type": "record",
                "version": "1",
                "fields": [
                        {"name": "switch_wwn", "type": "string", "doc": "WWN of the Physical Switch."},
                        {"name": "statistics_collection_time", "type": "long", "doc": "Epoch time when statistics is collected."},
                        {"name": "up_time", "type": "long", "doc": "Switch Up Time (in hundredths of a second)"},
                        {"name": "cpu_utilization", "type": "float", "default": 0, "doc": "CPU Utilization in %"},
                        {"name": "memory_utilization", "type": "float", "default": 0, "doc": "Memory Utilization in %"}
                ]
        }
  '''
  avro_measurement = "Switch"
  avro_tags = ["switch_wwn"]
  avro_fields = ["up_time", "cpu_utilization", "memory_utilization"]
  avro_timestamp = "statistics_collection_time"
  avro_timestamp_format = "unix_ms"

[[outputs.file]]
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "influx"
```

### Logs from Telegraf

```text
# telegraf --config ./telegraf.conf --debug
2023-04-27T13:02:22Z I! Loading config: ./telegraf.conf
fibrechannel_switch_statistics up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i 0
fibrechannel_switch_statistics up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i 0
fibrechannel_switch_statistics statistics_collection_time=0i,up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823 0
fibrechannel_switch_statistics cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i,up_time=0i 0
fibrechannel_switch_statistics up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i 0
fibrechannel_switch_statistics cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i,up_time=0i 0
fibrechannel_switch_statistics memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i,up_time=0i,cpu_utilization=0.0000000025322037799924146 0
fibrechannel_switch_statistics up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i 0
fibrechannel_switch_statistics cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i,up_time=0i 0
fibrechannel_switch_statistics statistics_collection_time=0i,up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823 0
fibrechannel_switch_statistics up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i 0
```

### System info

OS: AlmaLinux release 8.7 (Stone Smilodon), Telegraf: 1.26.1 (git: HEAD@8f421f25), Kafka: Confluent Kafka 7.3.3-ccs (Commit:37ce202868a57983d7f28fdeb51e9147ba8e3f95)

### Docker

N/A

### Steps to reproduce

Start Telegraf with the above config.

The "input" data viewed with kafka-avro-console-consumer looks like this:

```
{"switch_wwn":"10:00:50:EB:1A:0B:84:3A","statistics_collection_time":1682509200092,"up_time":1166984904,"cpu_utilization":14.0,"memory_utilization":20.0}
{"switch_wwn":"10:00:D8:1F:CC:5B:3E:77","statistics_collection_time":1682509200224,"up_time":164446104,"cpu_utilization":4.0,"memory_utilization":10.0}
```

### Expected behavior

The following output:
```
Switch,switch_wwn=10:00:50:EB:1A:0B:84:3A up_time=1166984904,cpu_utilization=14.0,memory_utilization=20.0 1682509200092000
Switch,switch_wwn=10:00:D8:1F:CC:5B:3E:77 up_time=164446104,cpu_utilization=4.0,memory_utilization=10.0 1682509200224000
```

### Actual behavior

The output looks like this:
```
Switch cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i,up_time=0i 0
Switch memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i,up_time=0i,cpu_utilization=0.0000000025322037799924146 0
Switch up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i 0
Switch statistics_collection_time=0i,up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823 0
Switch up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823,statistics_collection_time=0i 0
Switch statistics_collection_time=0i,up_time=0i,cpu_utilization=0.0000000025322037799924146,memory_utilization=0.0000000006411111641568823 0
```

### Additional info

Trying to capture "raw" data I did this:
```
kafka-console-consumer --topic perfmon_metrics_switch | tee kafka.raw
base64 kafka.raw > kafka.base64.txt
```
And kafka.base64.txt then looks like this:
```
AAAAAAMuMTA6MDA6NTA6RUI6MUE6MEI6ODQ6M0HK25qo+GGQ85ThCAAAYEEAAKBBCgAAAAADLjEw
OjAwOkQ4OjFGOkNDOjVCOjNFOjc33t2aqPhhsNaIpQEAAKBAAAAgQQoAAAAAAy4xMDowMDpEODox
RjpDQzo1OTo2MjpGRtzfmqj4YeCOuUIAAKBAAAAgQQoAAAAAAy4xMDowMDpDNDpGNTo3QzpCNzpG
RTo5Qb7hmqj4YYDfouEIAABQQQAAoEEKAAAAAAMuMTA6MDA6RDg6MUY6Q0M6NTk6MkY6MEbc45qo
+GHoyrNKAACgQAAAIEEKAAAAAAMuMTA6MDA6QzQ6RjU6N0M6QzI6QUY6NDKm5Zqo+GHIs86aCQAA
UEEAAKBBCgAAAAADLjEwOjAwOjUwOkVCOjFBOjBCOjg1OjNBxueaqPhhsOi/mgkAAFBBAACgQQoA
AAAAAy4xMDowMDpEODoxRjpDQzo1QjozRDpBN9Dpmqj4YejvmKUBAACgQAAAMEEK
```
(Please not that this data is **not** the same data as in the example above).
If this is not the "correct" way to capture “raw” data then please tell me how to correctly collect the data.

Any Idea what I am doing wrong and what I can do to correct it?

Regards,
Dan
