### ISSUE TITLE
With 1.26.2 update wavefront output plugin fails with 404 error if the URL has path

### ISSUE THREAD

**Issue by pavanrangain** [influxdata/telegraf#13166]
### Relevant telegraf.conf

```toml
[[outputs.wavefront]]
  url = "http://localhost:29999/wavefront-proxy"
  metric_separator = "."
  source_override = ["hostname", "agent_host", "node_host"]
  convert_paths = true
  immediate_flush = true
```

### Logs from Telegraf

```text
wavefront flushing error: error reporting wavefront format data to Wavefront. status=404
```

### System info

Telegraf 1.26.2, Docker 20.10.14

### Steps to reproduce

1. Have a reverse proxy like nginx/tarefik which forwards a particular URL path to wavefront proxy (strips the base path before forwarding)
2. Have telegraf configured with output config as above (change the host and port part to that of the proxy)
3. Run telegraf
...

### Expected behavior

telegraf should be able to forward metrics to wavefront proxy through the reverse proxy

### Actual behavior

telegraf is failing to send metrics and erroring out with 404

### Additional info

This started happening with 1.26.2 update where Wavefront sdk is updated to 0.12.0. With 1.26.1 we see no issues
We have upstream issue created https://github.com/wavefrontHQ/wavefront-sdk-go/issues/133
