### ISSUE TITLE
Parse JSON array as combined string field with json_v2

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#13235]
### Use Case

```json
{
  "head": [
    {
      "name": "test_a",
      "array": ["foo", "bar", "baz"]
    },
    {
      "name": "test_b",
      "array": [1, 2, 3]
    }
  ]
}
```

### Expected behavior

```s
file,name=test_a array="foo, bar, baz" 1683143788000000000
file,name=test_b array="1, 2, 3" 1683143788000000000
```

### Actual behavior

```s
file,name=test_a array="foo" 1683145288000000000
file,name=test_a array="bar" 1683145288000000000
file,name=test_a array="baz" 1683145288000000000
file,name=test_b array=1 1683145288000000000
file,name=test_b array=2 1683145288000000000
file,name=test_b array=3 1683145288000000000
```

### Additional info

We need to consider other uses cases, for example when there are multiple arrays, what happens? Today is combines them into m*n metrics.

Possible config:

```toml
[[inputs.file.json_v2.object.field_array]]
    path = "" # # A string with valid GJSON path syntax, can include array's and object's
    rename = "new name" # A string with a new name for the tag key
```

Limitations, would only work with string and numeric values.

Output would be a CSV string (e.g. field="a,b,c").

**Comment by srebhan** [comment]
Flattening of JSON arrays can be done with the XPath JSON parser already. Here is a working config for the data in the issue.

```toml
[[inputs.file]]
  files = ["test_configs/jsontest_array_flatten.json"]
  data_format = "xpath_json"

  [[inputs.file.xpath]]
    metric_name = "'json_test_1'"
    metric_selection = "//head/*"
    [inputs.file.xpath.tags]
        name = "name"
    [inputs.file.xpath.fields]
        array = "string-join(array/*, ',')"
```

Closing as a solution exists.
