### ISSUE TITLE
Generate multiple metrics out of a single CSV file

### ISSUE THREAD

**Issue by opobla** [influxdata/telegraf#13251]
### Use Case

Let's assume that we have a CSV with the following data:

`timestamp`, `sensor1_channel1`, `sensor1_channel2`, `sensor2_channel1`, `sensor2_channel2`

That is, two sensor of the same nature, with two channels each. It would be great to generate two metrics, labeled accordingly like `sensor1` and `sensor2`.

### Expected behavior

Two metrics:

`timestamp`, `sensor1 channel1=123, channel2=23`
`timestamp`, `sensor2 channel1=312, channel2=432`

### Actual behavior

It is not possible to do that. In my current setup, I am using a `tail` input to read a CSV dumped and updated by a legacy system. To work around this issue I am planning on using `starlak` to process the output manually.

**Comment by powersj** [comment]
Hi,

> To work around this issue I am planning on using starlak to process the output manually.

This might be the answer, but let me get back to you about other options.

**Comment by powersj** [comment]
>  The unpivot processor might also be of help in this case.

Not really. In the example @opobla provided that would create 4 metrics. 

> This might be the answer, but let me get back to you about other options.

This is a question that comes up from time to time. While this is entirely possible with starlark it seems there is a bit of push back or desire for a no-code solution as well.

What @srebhan and I would propose then is a new processor, a `split` processor. A user would provide a recipe for creating a new metric based on incoming metrics. 

Using the provided example:

```s
metric sensor1_channel1=4i,sensor1_channel2=2i,sensor2_channel1=1i,sensor2_channel2=2i 1684784689000000000
```

Then a user could define two new metrics:

```toml
[[processors.split]]
  drop_original = true
  [[processors.split.metric]]
    name = "sensor1"
    tags = []
    fields = ["sensor1_channel1","sensor1_channel2"]
    timestamp = "original"
  [[processors.split.metric]]
    name = "sensor2"
    tags = []
    fields = ["sensor1_channel1","sensor1_channel2"]
    timestamp = "original"
```

The config should be explicite for each newly created metric and not make any assumptions about what tags, fields, or timestamps are used.

That would then produce:

```s
sensor1 sensor1_channel1=4i,sensor1_channel2=2i 1684784689000000000
sensor2 sensor2_channel1=1i,sensor2_channel2=2i 1684784689000000000
```

We would need to agree on behavior of what to do with the original metric as well. Do we keep it? Or drop it? Have a setting for this?

Thoughts?

**Comment by Hipska** [comment]
> Not really. In the example @opobla provided that would create 4 metrics.

I said it might be of help, not that it was the only one to be used or the solution. It would be possible with a combination of multiple processors, one of which might be the unpivot.

**Comment by opobla** [comment]
> Using the provided example:
> 
> ```m68k
> metric sensor1_channel1=4i,sensor1_channel2=2i,sensor2_channel1=1i,sensor2_channel2=2i 1684784689000000000
> ```
> 
> Then a user could define two new metrics:
> 
> ```toml
> [[processors.split]]
>   drop_original = true
>   [[processors.split.metric]]
>     name = "sensor1"
>     tags = []
>     fields = ["sensor1_channel1","sensor1_channel2"]
>     timestamp = "original"
>   [[processors.split.metric]]
>     name = "sensor2"
>     tags = []
>     fields = ["sensor1_channel1","sensor1_channel2"]
>     timestamp = "original"
> ```
> 
> The config should be explicite for each newly created metric and not make any assumptions about what tags, fields, or timestamps are used.
> 
> That would then produce:
> 
> ```m68k
> sensor1 sensor1_channel1=4i,sensor1_channel2=2i 1684784689000000000
> sensor2 sensor2_channel1=1i,sensor2_channel2=2i 1684784689000000000
> ```
> 
> We would need to agree on behavior of what to do with the original metric as well. Do we keep it? Or drop it? Have a setting for this?
> 
> Thoughts?

Building from your `split` processor configuration I would suggest to include what will be the original `input_fields` (coming from the CVS parsing), and what will be the `output_fields`

```toml
[[processors.split]]
  drop_original = true
  [[processors.split.metric]]
    name = "sensor1"
    tags = ["sensor1"]
    input_fields = ["sensor1_channel1","sensor1_channel2"]
    output_fields = ["channel1", "channel2"]
    timestamp = "original"
  [[processors.split.metric]]
    name = "sensor2"
    tags = ["sensor2"]
    input_fields = ["sensor1_channel1","sensor1_channel2"]
    output_fields = ["channel1", "channel2"]
    timestamp = "original"
```

Maybe a mapping could be more elegant, but I am not sure if it would be more readable.

This will allow to query by `channel1` regardless of the `sensor` it came from, and also allow ugly-csv-names renaming.

As for the question about keeping or not the original metric, the `drop_original` approach looks nice.
