### ISSUE TITLE
Authorization Issues 

### ISSUE THREAD

**Issue by rsuplina** [influxdata/telegraf#13259]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false



[[outputs.influxdb_v2]]


  urls = ["http://${DOCKER_INFLUXDB_INIT_HOST}:8086"]
  # urls = ["http://localhost:8086"]
  token = "$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"
  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "changeme"
  ## Destination bucket to write into.
  bucket = "changeme"
```

### Logs from Telegraf

```text
tig-stack-influxdb-1  | ts=2023-05-09T10:32:43.981703Z lvl=info msg=Unauthorized log_id=0hh0p2eW000 error="authorization not found"
tig-stack-telegraf-1  | 2023-05-09T10:32:43Z E! [outputs.influxdb_v2] When writing to [http://influxdb:8086]: failed to write metric (401 Unauthorized): unauthorized: unauthorized access
tig-stack-telegraf-1  | 2023-05-09T10:32:43Z E! [agent] Error writing to outputs.influxdb_v2: failed to write metric (401 Unauthorized): unauthorized: unauthorized access
```

### System info

telegraf:1.19

### Docker
```
version: "3"
services:
  influxdb:
    image: influxdb:2.1.1
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana-oss:8.4.3
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  grafana-storage:
  influxdb-storage:
```

THIS IS MY ENV FILE :
```
DOCKER_INFLUXDB_INIT_MODE=setup

DOCKER_INFLUXDB_INIT_USERNAME=changeme
DOCKER_INFLUXDB_INIT_PASSWORD=changeme 
DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=wBz60U3tgfUldCemwvKRi0twXCCTmFMYr5un2uf2a02gAOreX7cwIO9Z4vVfgHuZJXd965mCjy5eJn9_3lLHuQ== 


DOCKER_INFLUXDB_INIT_ORG=changeme 
DOCKER_INFLUXDB_INIT_BUCKET=changeme 

DOCKER_INFLUXDB_INIT_RETENTION=4d 

DOCKER_INFLUXDB_INIT_PORT=8086 
DOCKER_INFLUXDB_INIT_HOST=influxdb 


TELEGRAF_CFG_PATH=./telegraf/telegraf.conf

GRAFANA_PORT=3000
```

### Steps to reproduce

1.Run Dcoker-Compose
2. Log to Console without problems
3.
...

### Expected behavior

Working without Erros

### Actual behavior

Logs with Unauthorized Access 

### Additional info

Same configuration as this guide 
 https://github.com/huntabyte/tig-stack
