### ISSUE TITLE
[outputs.cratedb] telegraf never sends data when network is down at service startup

### ISSUE THREAD

**Issue by h49nakxs** [influxdata/telegraf#13278]
### Relevant telegraf.conf

```toml
[agent]
  interval = "20s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 50000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "1ms"
  debug = true
  logtarget = "eventlog"
  omit_hostname = false

[[outputs.cratedb]]
  url = "postgres://user:pass@CRATEDBHOST/schema?sslmode=verify-full"
  timeout = "30s"
  table = "table"
  table_create = true
  key_separator = "_"
```

### Logs from Telegraf

```text
[agent] Failed to connect to [outputs.cratedb], retrying in 15s, error was "failed to connect to `host=CRATEDBHOST user=user database=db`: hostname resolving error (lookup CRATEDBHOST: no such host)"
```

### System info

Telegraf 1.26.2, Windows 10 Professionnal 21H2

### Steps to reproduce

1. Unplug the network cable or disable the wifi connection of a client on which telegraf is installed.
2. Reboot the client.
3. Wait around 30 seconds before re-plugging the network cable or re-enabling the wifi connection.
4. Notice that telegraf service is started but no data is sent to the output.

### Expected behavior

When telegraf is starting and the output host is not available yet, telegraf should retry the network connection at least every X seconds for X times.

### Actual behavior

Telegraf service is started but no data is sent in the outputs.

### Additional info

- If the network is cut when telegraf service is already started, telegraf correctly sends data to the output as soon as the network is back.

- This issue is very problematic for clients that takes a bit of time to get the network connection (eg : laptops connected to a wifi network only) because it makes telegraf unusable on those.

- Not sure if this should be fixed at the agent level or at the output plugin level.
