### ISSUE TITLE
Cisco MDT Telemetry Input Plugin Max Msg Size Rollover

### ISSUE THREAD

**Issue by tylersiemers** [influxdata/telegraf#13270]
### Relevant telegraf.conf

```toml
###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

# # Cisco model-driven telemetry (MDT) input plugin for IOS XR, IOS XE and NX-OS platforms
[[inputs.cisco_telemetry_mdt]]
#  ## Telemetry transport can be "tcp" or "grpc".  TLS is only supported when
#  ## using the grpc transport.
transport = "tcp"
max_msg_size = 5000000000
include_delete_field = true
#
#  ## Address and port to host telemetry listener
service_address = ":57590"
[inputs.cisco_telemetry_mdt.tags]
```

### Logs from Telegraf

```text
2023-05-11T14:03:58Z E! [inputs.cisco_telemetry_mdt] Error in plugin: dialout packet too long: 1651402591

Custom DEBUG Log
2023-05-12T14:30:07Z D! [inputs.cisco_telemetry_mdt] MAX MSG SIZE: 705032704
```

### System info

Telegraf 1.26.1, Ubuntu 22.04

### Steps to reproduce

1. Configure max_msg_size to a value higher than 4294967295
2. Add debug logs into handleTCPClient that prints the maxMsgSize
3. See that setting the max_msg_size to a value higher than uint32 causes it to rollover
...

### Expected behavior

The telegraf.conf input should warn users that a hard limit of the uint32 is 4294967295 or set the max_msg_size to a uint64 so it can handle larger messages.

### Actual behavior

If max_msg_size is set to a number higher than 4294967295 it will rollover essentially making the size 

user set max_msg_size - 4294967295

So in a case where you set the size to 5000000000, you actually rollover and it becomes 705032704.

5000000000 - 4294967295 = 705032704

### Additional info

https://community.influxdata.com/t/cisco-mdt-telemetry-input-plugin-max-msg-size/29890
