### ISSUE TITLE
Telegraf 1.26.2. Memory Input Plugin - inputs.mem. mem.write_back - zero value.

### ISSUE THREAD

**Issue by syatihoko** [influxdata/telegraf#13299]
### Relevant telegraf.conf

```toml
[global_tags]


[agent]
  interval = "30s"
  round_interval = false

  metric_batch_size = 10000

  metric_buffer_limit = 100000

  collection_jitter = "0s"

  flush_interval = "10s"
  flush_jitter = "0s"

  precision = ""

  debug = true


  logfile = "/var/log/telegraf/telegraf.log"



  hostname = "name_host"
  omit_hostname = false


 [[outputs.graphite]]
   servers = ["MY_HIDDEN_HOST:2003"]
   prefix = "servers"
   template = "host.measurement.tags.field"
   timeout = 17
```

### Logs from Telegraf

```text
2023-05-22T07:52:46Z I! [agent] Hang on, flushing any cached metrics before shutdown
2023-05-22T07:52:46Z I! [agent] Stopping running outputs
2023-05-22T07:52:46Z I! Starting Telegraf 1.26.2
2023-05-22T07:52:46Z I! Available plugins: 235 inputs, 9 aggregators, 27 processors, 22 parsers, 57 outputs, 2 secret-stores
@@@
```

### System info

Telegraf 1.26.2.  Ubuntu 18.04, 22.04

### Steps to reproduce

1. telegraf --test -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d/common.conf --input-filter=mem

### Expected behavior

write_back= and write_back_tmp more 0

### Actual behavior

write_back=0i,write_back_tmp=0i 

### Additional info

After update to Telegraf 1.26.2, the metric  "mem.write_back"  began to accept only a zero value on all servers. 
OS - Ubuntu 18.04, 22.04

**telegraf --test -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d/ --input-filter=mem:**
`active=24328122368i,available=25401221120i,available_percent=75.5993608248227,buffered=135442432i,cached=25453924352i,commit_limit=18947371008i,committed_as=8156454912i,dirty=37199872i,free=299200512i,high_free=0i,high_total=0i,huge_page_size=2097152i,huge_pages_free=0i,huge_pages_total=0i,inactive=7386312704i,low_free=0i,low_total=0i,mapped=164855808i,page_tables=23384064i,shared=917504i,slab=1301299200i,sreclaimable=1240989696i,sunreclaim=60309504i,swap_cached=278528i,swap_free=2143285248i,swap_total=2147479552i,total=33599782912i,used=7711215616i,used_percent=22.95019475630593,vmalloc_chunk=0i,vmalloc_total=35184372087808i,vmalloc_used=0i,write_back=0i,write_back_tmp=0i 1684741645000000000`
