### ISSUE TITLE
Documentation Bug - And improvement request

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13329]
### Relevant telegraf.conf

```toml
[[secretstores.os]]
id = "secretstore"

## this is verbatim from the README.md of the secretstores-plugin:
##
## * Windows: keys follow a fixed pattern in the form
##     `<keyring>:<collection>:<key>`. Please keep this in mind when creating
##     secrets with the Windows credential tool.

keyring = "telegraf"
collection = "tg-coll"
```

### Logs from Telegraf

```text
Logs not relevant.
```

### System info

1.25.0, Windows Server 2022

### Steps to reproduce

I created a secret with
```
telegraf.exe --config-directory <dir> secrets set secretstore <somethingsomething> <secret>
```
Looking into the Windows Credentials Manager I find a Generic Credential with 
"Internet or network address"
`tg-coll:telegraf:<somethingsomething>`

Which is not, as the documentation says, `<keyring>:<collection>:<key>`, but `<collection>:<keyring>:<keyname>`

### Expected behavior

The documentation stating the correct order

### Actual behavior

The documentation states the wrong order. 

### Additional info

Improvement request:
"Please keep in mind ..." didn't tell me where to put this `<collection>:<keyring>:<keyname>`-string.
There are two fields available in the GUI: "Internet and network address" (<- the string goes here), and "User name" which (using the GUI) can't be left blank.

So:
I would mention in the docs where the `<c>:<k>:<k>`-string goes and that you have to put sth. into the "User name" field which then will be ignored.

--- 
Half-related:
Also it seems to be a potential problem when pasting passwords into the credential-manager from textfiles. When it didn't work and I looked at what I got back from `telegraf secrets get secretstore ...`, I saw that my password was indispersed with spaces (or something) like `p a s s w o r d 1 2 3 ` instead of `password123`. Probably some Windows/Unicode-problem. You probably can't solve this, but you can make people aware that they should use `telegraf secrets get ...` to check back that their passwords are recorded correctly.
