### ISSUE TITLE
win perf counters handling of bytes

### ISSUE THREAD

**Issue by rismoney** [influxdata/telegraf#13373]
### Relevant telegraf.conf

```toml
[[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = [
      "% Processor Time",
       "Working Set"
      ]
    Instances = ["*"]
    Measurement = "win_proc"
    #UseRawValues= true
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).
```

### Logs from Telegraf

```text
n/a
```

### System info

windows 2019 - telegraf latest 1.26.2

### Docker

n/a

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

a value like 7484747776

### Actual behavior

1.74329856e+08

### Additional info

I am outputing to prometheus client, and I am seeing 
win_proc_Working_Set{host="server-D05",instance="msmdsrv",objectname="Process",source="server-D05"} 1.74329856e+08

which is not the correct value from the counter...  
Would a processor work, I believe the value here is just wrong.
powershell:
```
Get-Counter "\Process(msmdsrv)\Working Set"

Timestamp                  CounterSamples
---------                  --------------
5/31/2023 3:51:58 PM       \\nyvmwssql-d05\process(msmdsrv)\working set :
7484747776
```

I thought this was related to #5747 but I believe it is just the wrong value, not just a notation issue.
