### ISSUE TITLE
[outputs.sql] Error loading config if connection_max_lifetime is set

### ISSUE THREAD

**Issue by empty88** [influxdata/telegraf#13406]
### Relevant telegraf.conf

```toml
[[outputs.sql]]
  ## Database driver
  ## Valid options: mssql (Microsoft SQL Server), mysql (MySQL), pgx (Postgres),
  ##  sqlite (SQLite3), snowflake (snowflake.com) clickhouse (ClickHouse)
  driver = "mysql"

  ## Data source name
  ## The format of the data source name is different for each database driver.
  ## See the plugin readme for details.
  data_source_name = "test:gQ0.TdgTSp@tcp(127.0.0.1:3306)/pvanlage?tls=false"
  
  ## Timestamp column name
  timestamp_column = "timestamp"

  ## Table creation template
  ## Available template variables:
  ##  {TABLE} - table name as a quoted identifier
  ##  {TABLELITERAL} - table name as a quoted string literal
  ##  {COLUMNS} - column definitions (list of quoted identifiers and types)
  table_template = "CREATE TABLE {TABLE}({COLUMNS})"

  ## Table existence check template
  ## Available template variables:
  ##  {TABLE} - tablename as a quoted identifier
  table_exists_template = "SELECT 1 FROM {TABLE} LIMIT 1"

  ## Initialization SQL
  init_sql = "SET sql_mode='ANSI_QUOTES';"

  connection_max_lifetime = "1h"
```

### Logs from Telegraf

```text
E! error loading config file /etc/telegraf/telegraf.conf: error parsing sql array, line 150: (sql.SQL.ConnectionMaxLifetime) cannot unmarshal TOML string into time.Duration
```

### System info

Telegraf 1.26.3 (official docker image)

### Steps to reproduce

1. add connection_max_lifetime = "1h" to outputs.sql config
2. start telegraf

### Expected behavior

load config successfully

### Actual behavior

loading config failed, docker restarts
