### ISSUE TITLE
Wrong values for memory procstat input

### ISSUE THREAD

**Issue by nektarios-d** [influxdata/telegraf#13402]
### Relevant telegraf.conf

```toml
[[inputs.procstat]]
  pattern = "."
  pid_tag = true
  cmdline_tag = true
  pid_finder = "native"
  include_systemd_children = true
  fieldpass = [
	"cpu_time_user",
	"cpu_usage",
	"memory_rss",
	"read_bytes",
	"write_bytes"
  ]

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.prometheus_client]]
  listen = ":9125"
  path = "/metrics"
```

### System info

Telegraf 1.26.2, Ubuntu 22.04 with prometheus output and grafana

### Steps to reproduce

1. Collect the metrics with procstat input plugin
2. View the metrics in Grafana dashboard
3. Sum memory_rss based on the process_name label
4. View memory usage in server with htop
5. Compare values

### Expected behavior

The sum is the amount of memory a process is using on the system.

### Actual behavior

The value is bigger than the actual memory on the system.

### Additional info

I am trying to monitor the Top5 processes by memory usage on a server but get unexpected results. For example apache2 showing a sum of 20GB of memory_rss on a server with 4 GB RAM. Setting the pid_tag=false results in also inaccurate results with smaller than actual memory value.
