### ISSUE TITLE
name_templates of diskio plugin is invalid

### ISSUE THREAD

**Issue by devome** [influxdata/telegraf#13438]
### Relevant telegraf.conf

```toml
[[inputs.diskio]]
  devices = ["sda", "sdb", "sdc", "sdd", "sde", "sdf", "sdg", "sdh", "sdi", "nvme0n1", "nvme1n1", "dm-*"]
  device_tags = ["ID_SERIAL"]
  name_templates = ["${ID_SERIAL}", "${DM_VG_NAME}/${DM_LV_NAME}"]
```

### Logs from Telegraf

```text
time="2023-06-14T05:18:08Z" level=warning msg="The \"ID_SERIAL\" variable is not set. Defaulting to a blank string."
time="2023-06-14T05:18:08Z" level=warning msg="The \"DM_VG_NAME\" variable is not set. Defaulting to a blank string."
time="2023-06-14T05:18:08Z" level=warning msg="The \"DM_LV_NAME\" variable is not set. Defaulting to a blank string."
```

### System info

Telegraf 1.27.0, Debian 11, Docker 24.0.2

### Docker

```yaml
version: '3.8'
services:
  telegraf:
    image: telegraf:alpine
    container_name: telegraf
    hostname: telegraf
    restart: always
    volumes:
      - /:/hostfs
      - /run/udev:/run/udev
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      nginx:
        ipv4_address: 172.18.0.152
        aliases:
          - telegraf
    user: 1000:1000
    group_add:
      - "997"  # docker group
    environment:
      - HOST_PROC=/hostfs/proc
      - INFLUX_TOKEN=XXXX
    privileged: true
    command: >
      --config http://influxdb:8086/api/v2/telegrafs/0a647e6eff41f000
      --config http://influxdb:8086/api/v2/telegrafs/0a649a121dc1f000
      --config http://influxdb:8086/api/v2/telegrafs/0a64ae606e41f000

networks: 
  nginx:
    external: true
```

### Steps to reproduce

Recreate the Docker container, the problem still exists.

### Expected behavior

Before Telegraf version 1.26.0, name_templates can be processed normally. In the output data, the `name` field exists.

### Actual behavior

Telegraf version 1.27.0, in the output data, the `name` field does not exist.
