### ISSUE TITLE
custom_builder no find serializer

### ISSUE THREAD

**Issue by nicho2** [influxdata/telegraf#13441]
### Relevant telegraf.conf

```toml
...
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]

  ## Data format to output.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
  data_format = "json"
...
```

### Logs from Telegraf

```text
error parsing file array, undefined but requested serializer: json
```

### System info

Telegraf 1.27.0 (git: release-1.27@dd48ee81)

### Steps to reproduce

1. compile custom telegraf from .conf file
2. start telegraf in test mode
3. 
...

### Expected behavior

no error

### Actual behavior

2023-06-14T09:44:01Z E! error loading config file C:\Users\...\telegraf.custom_services\services\weather_air_quality\telegraf_weather_air_quality.conf: error parsing file array, undefined but requested serializer: json

### Additional info

during compilation:

        2023/06/14 13:04:58 Importing configuration file(s)...
        2023/06/14 13:04:59 Found 1 configuration files...
        -------------------------------------------------------------------------------
        Enabled plugins:
        -------------------------------------------------------------------------------
        aggregators (0):
        -------------------------------------------------------------------------------
        inputs (1):
          http                            plugins/inputs/http
        -------------------------------------------------------------------------------
        outputs (2):
          file                            plugins/outputs/file
          mqtt                            plugins/outputs/mqtt
        -------------------------------------------------------------------------------
        parsers (1):
          json_v2                         plugins/parsers/json_v2
        -------------------------------------------------------------------------------
        processors (1):
          starlark                        plugins/processors/starlark
        -------------------------------------------------------------------------------
2023/06/14 13:05:11 Running build...
CGO_ENABLED=0 go build -tags "custom,inputs.http,outputs.file,outputs.mqtt,parsers.json_v2,processors.starlark" -ldflags " -X github.com/influxdata/telegraf/internal.Commit=dd48ee81 -X github.com/influxdata/telegraf/internal.Branch=release-1.27 -X github.com/influxdata/telegraf/internal.Version=1.27.0" ./cmd/telegraf
