### ISSUE TITLE
Environment variables in configs do not resolve anymore

### ISSUE THREAD

**Issue by pichlermarc** [influxdata/telegraf#13456]
### Relevant telegraf.conf

```toml
[global_tags]
[agent]
  interval = "${MY_TELEGRAF_INTERVAL}"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = false
[[inputs.mem]]
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### Logs from Telegraf

```text
2023-06-16T09:02:51Z I! Loading config: telegraf.conf
2023-06-16T09:02:51Z E! error loading config file telegraf.conf: error parsing [agent]: line 3: (config.AgentConfig.Interval) time: invalid duration "${MY_TELEGRAF_INTERVAL}"
```

### System info

Telegraf 1.28.0-1cfa48ee (git: master@1cfa48ee), Ubuntu 22.04

### Steps to reproduce

1. Use the config provided above
2. Use build from default branch `1.28.0-1cfa48ee (git: master@1cfa48ee)`

### Expected behavior

Telegraf starts up as it did with `1.27.0` and earlier

### Actual behavior

Telegraf exits with `2023-06-16T09:02:51Z E! error loading config file telegraf.conf: error parsing [agent]: line 3: (config.AgentConfig.Interval) time: invalid duration "${MY_TELEGRAF_INTERVAL}"`

### Additional info

We initially discovered this in one of our tests, using an environment variable containing an URL for the Dynatrace output plugin.
