### ISSUE TITLE
tagpass giving error with prometheus_client output plugin

### ISSUE THREAD

**Issue by 33Fraise33** [influxdata/telegraf#13475]
### Relevant telegraf.conf

```toml
[[inputs.http_listener_v2]]
  service_address = ":8094"
  [inputs.http_listener_v2.tags]
    customer = "customer1"
  basic_username = "foobar"
  basic_password = "barfoo"
[[inputs.http_listener_v2]]
  service_address = ":8095"
  [inputs.http_listener_v2.tags]
    customer = "customer2"
  # basic_username = "foobar"
  # basic_password = "barfoo"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/customer1"
  collectors_exclude = ["gocollector", "process"]
  string_as_label = false
  export_timestamp = true

  tagexclude = ["customer", "host", "basic_username", "basic_password"]
  [outputs.prometheus_client.tagpass]
    customer = [ "customer1" ]
  data_format = "prometheus"
```

### Logs from Telegraf

```text
2023-06-21T12:51:32Z I! Loading config: /etc/telegraf/telegraf.conf
2023-06-21T12:51:32Z E! error loading config file /etc/telegraf/telegraf.conf: error parsing prometheus_client array, line 14:{295 540}: found unexpected format while parsing "tagpass", expecting string array/slice format on each entry
```

### System info

Telegraf 1.27.0, Docker 24.0.2

### Steps to reproduce

1. Create a telegraf config with above items
2. Try to start telegraf
3. Receive error that tagpass is not in the correct format (while it is taking from an example here: https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#routing-metrics-to-different-outputs-based-on-the-input)
...

### Expected behavior

Telegraf should accept the config

### Actual behavior

Telegraf does not
