### ISSUE TITLE
Missing some information when using OpenTelemetry Output Plugin 

### ISSUE THREAD

**Issue by haihh05** [influxdata/telegraf#13474]
### Relevant telegraf.conf

```
#telegraf1.conf
[[inputs.jti_openconfig_telemetry]]
  servers = ["my_network_device:4317"]

  sample_frequency = "10000ms"

  sensors = [
    "2000ms intefaces /interfaces",
  ]

[[outputs.opentelemetry]]
  service_address = "0.0.0.0:30003"

[[outputs.file]]
  files = ["stdout"]

  data_format = "influx"
```

```
#telegraf2.conf

[[inputs.opentelemetry]]
  service_address = "0.0.0.0:30003"

[[outputs.file]]
  files = ["stdout"]

  data_format = "influx"
```

### Logs from Telegraf

```
telegraf1  | intefaces,/interfaces/interface/@name=ae0,device=...,host=...,path=sensor_1004_5_1:/interfaces/:/interfaces/:mib2d,system_id=... _component_id=65535i,/interfaces/interface/state/type="other",/interfaces/interface/state/description="...",/interfaces/interface/state/oper-status="UP",/interfaces/interface/ethernet/state/enable-flow-control=false,/interfaces/interface/state/name="ae0",_timestamp=1687351346281i,/interfaces/interface/state/admin-status="UP",/interfaces/interface/ethernet/state/mac-address="...",/interfaces/interface/ethernet/state/negotiated-port-speed="SPEED_10GB",_subcomponent_id=0i,/interfaces/interface/state/enabled=true,/interfaces/interface/state/last-change=1687025787040761000i,/interfaces/interface/hold-time/state/up=0i,/interfaces/interface/hold-time/state/down=0i,/interfaces/interface/ethernet/state/port-speed="SPEED_10GB",/interfaces/interface/ethernet/state/hw-mac-address="...",_sequence=292i,/interfaces/interface/state/ifindex=517i,/interfaces/interface/state/logical=false,/interfaces/interface/state/mtu=9192i,/interfaces/interface/state/loopback-mode=false 1687322708946903506

telegraf2  | intefaces_/interfaces/interface/state/ifindex,/interfaces/interface/@name=ae0,device=...,host=...,path=sensor_1004_5_1:/interfaces/:/interfaces/:mib2d,system_id=... gauge=517i 168732270894690350
```

### System info

Telegraf 1.26.3

### Docker

```
#docker-compose.yaml
version: '3.3'

services:
  telegraf1:
    image: telegraf:1.26.3
    container_name: telegraf1
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./telegraf1.conf:/etc/telegraf/telegraf.conf

  telegraf2:
    image: telegraf:1.26.3
    container_name: telegraf2
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./telegraf2.conf:/etc/telegraf/telegraf.conf

```
### Steps to reproduce

1. Run docker-compose file with telegraf1.conf and telegraf2.config : `docker compose up -d`
2. Check logs and compare (results as logs above)

### Expected behavior

Logs of telegraf2 are the same logs of telegraf1

### Actual behavior

Logs of telegraf2 are not the same logs of telegraf1
