### ISSUE TITLE
External output plugin - configuration not applied

### ISSUE THREAD

**Issue by muhlba91** [influxdata/telegraf#13488]
### Relevant telegraf.conf

```toml
[[outputs.execd]]
   command = [ "/plugins/bin/firehose/telegraf-output-kinesis-data-firehose", "-config", "/plugins/config/plugin.conf" ]
   restart_delay = "10s"
   ignore_serialization_error = true
   data_format = "influx"
```

```toml
[[outputs.firehose]]
  region = "${AWS_REGION}"
  access_key = "${AWS_ACCESS_KEY_ID}"
  secret_key = "${AWS_SECRET_ACCESS_KEY}"

  streamname = "${FIREHOSE_DELIVERY_STREAM}"

  batchsize = 500

  [format]
    flatten = true
    normalize_keys = true
    name_key_rename = "unit"
    timestamp_as_rfc3339 = false
    timestamp_units = "1ms"
```

### Logs from Telegraf

```text
This is kind of a reopen of https://github.com/influxdata/telegraf/issues/8272.
```

### System info

Telegraf 1.27.1, Docker Image

### Steps to reproduce

Use an execd output plugin with nested configuration.

### Expected behavior

The specified configuration to be applied in the output plugin.
The contents are read though.

### Actual behavior

The specified configuration in the file is not applied.

### Additional info

N/A
