### ISSUE TITLE
Telegraf doesn't re-resolve graphite server, even if it is not available

### ISSUE THREAD

**Issue by dibilder** [influxdata/telegraf#13491]
### Relevant telegraf.conf

```toml
[[inputs.statsd]]
  protocol = "udp"
  service_address = "127.0.0.1:30001"
  metric_separator = "."
  max_ttl = "1h" 
[[outputs.graphite]]
  servers = ["graphite.test:30000"]
  template = "host.measurement.field"
  graphite_tag_support = false
```

### Logs from Telegraf

```text
E! [agent] Error writing to outputs.graphite: could not write to any Graphite server in cluster
```

### System info

Ubuntu 22.04, telegraf 1.27.1

### Steps to reproduce

(1) In the example config, telegraf sends output to a graphite server graphite.test:30000. Create host for fake graphite server. Create DNS record for "graphite.test" with IP of this host. Or use /etc/hosts on the host with telegraf agent, with the hosts file the problem is reproduced too.
(2) Start telegraf using the attached config.
(3) In another shell of the host with telegraf agent, start sending input to the configured statsd UDP input at port 30001, for example using
`while true; do echo "test:50|g" | nc -u -w1 127.0.0.1 30001; done`
(4) Start a TCP server listening on 30000 on the fake graphite host server. You will see received metrics from telegraf agent on this host.
`nc -l -k 30000`
(5) Stop the graphite server. Telegraf agent will report that it can't connect to any graphite output server:
`E! [agent] Error writing to outputs.graphite: could not write to any Graphite server in cluster`
(6) Now change ip of the graphite server, update the DNS record (or change it in /etc/hosts), and start to listen 30000 port again. Telegraf will still try to send metrics to the old IP.

### Expected behavior

Telegraf re-resolve dns record and start sending metrics to the new host IP. 

### Actual behavior

Telegraf continue try to send metric to the old IP, which is unavailable.

### Additional info

I get this issue every time when IP of graphite server is changed. So I have to restart telegraf service on every hosts.
