### ISSUE TITLE
SQLServer plugin defaults to 1434 UDP

### ISSUE THREAD

**Issue by csupi003** [influxdata/telegraf#13498]
### Relevant telegraf.conf

```toml
[[inputs.sqlserver]]
  servers = [
    "Server=IP\\MSSQLSERVER;Port=1433;app name=telegraf;log=1;",
  ]
```

### Logs from Telegraf

```text
instances from Sql Server Browser on host SQL_IP: read udp Telegraf_IP:39848->SQL_IP:1434: i/o timeout
```

### System info

Telegraf 1.25.2

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

Run on the port mentioned in the config

### Actual behavior

Defaults to udp 1434

### Additional info

After allowing UDP 1434 on the server the error is gone
