### ISSUE TITLE
[plugins/inputs/gnmi] leading slash dropped from all paths in v1.27

### ISSUE THREAD

**Issue by clsmyth** [influxdata/telegraf#13512]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
  addresses     = ["rt-01:32767"]
  name_override = "gnmi_ifcounters"
  redial        = "10s"
  [[inputs.gnmi.subscription]]
    name              = "ifcounters"
    origin            = "openconfig-interfaces"
    path              = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval   = "10s"
  [[inputs.gnmi.tag_subscription]]
    name              = "descr"
    origin            = "openconfig-interfaces"
    path              = "/interfaces/interface/state/description"
    subscription_mode = "on_change"
    elements          = ["interface"]
```

### Logs from Telegraf

```text
from outputs.file:

{
  "fields": {
    "interfaces/interface/init_time": 1646756972,
    "interfaces/interface/state/high_speed": 10000,
    "interfaces/interface/state/parent_ae_name": "ae4"
  },
  "name": "gnmi_ifcounters",
  "tags": {
    "xxx_bps": "10000000000",
    "xxx_cat": "ix",
    "xxx_dc": "aaa",
    "xxx_gbps": "10",
    "xxx_ifcomplete": "aaa-rt-01 xe-0/1/11:2 (ProviderMLPE)",
    "xxx_iflong": "xe-0/1/11:2(aaa-ProviderMLPE)",
    "xxx_iflongrev": "aaa-ProviderMLPE(xe-0/1/11:2)",
    "xxx_ifshort": "aaa-ProviderMLPE",
    "xxx_mbps": "10000",
    "xxx_provider": "equinix",
    "xxx_reg": "amer",
    "collector_dc": "PHX1",
    "collector_host": "ntw-monicol-01",
    "collector_region": "AMER",
    "descr/description": "aaa-ProviderMLPE",
    "host": "ntw-monicol-01",
    "kafka_topic": "telegraf_influx_gnmi_ifcounters",
    "name": "xe-0/1/11:2",
    "path": "/interfaces/interface",
    "source": "aaa-rt-01.net.xxx.dev"
  },
  "timestamp": 1687532297
}
```

### System info

Telegraf 1.27.0-7ced2606 (git: master@7ced2606), Rocky Linux 8.8

### Steps to reproduce

Configure  GNMI *at all*
Observe measurements data.
Note that all GNMI field keys lack a leading slash.

### Expected behavior

Leading slashes were present before 1.27.

### Actual behavior

Leading slashes are absent in 1.27.
