### ISSUE TITLE
Telegraf will not load when splunkmetric_multimetric is enabled

### ISSUE THREAD

**Issue by ryanoneil2** [influxdata/telegraf#13510]
### Relevant telegraf.conf

```toml
[[outputs.http]]
   url = "http://xx.xx.xx.xx:8088/services/collector/event"
   insecure_skip_verify = true
   ## Data format to output.
   data_format = "splunkmetric"
   splunkmetric_multimetric = true
   #splunkmetric_omit_event_tag = false
    ## Provides time, index, source overrides for the HEC
   splunkmetric_hec_routing = true
   ## Additional HTTP headers
    [outputs.http.headers]
      Content-Type = "application/json"
      Authorization = "Splunk xxxxxx"
      X-Splunk-Request-Channel = "xxxxxx"
```

### Logs from Telegraf

```text
023-06-27T16:54:10Z I! Loading config: /etc/telegraf/telegraf.conf
2023-06-27T16:54:10Z E! error loading config file /etc/telegraf/telegraf.conf: plugin outputs.http: line 22: configuration specified the fields ["splunkmetric_multimetric"], but they weren't used
```

### System info

1.27.1

### Docker

version: "3.8"
volumes:
  telegraf_logs:

services:
  telegraf:
    image: telegraf:latest
    #user: 1001:1001
    ports:
      - "57344:57344"
    deploy:
      replicas: 6
    volumes:
      - telegraf_logs:/telegraf_logs
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  # Map location of TLS custom TLS
  #     - /opt/sc4s/tls:/etc/syslog-ng/tls:z

### Steps to reproduce

1.  enable splunkmetric_multimetric = true option
2.
3.
...

### Expected behavior

Telegraf to start and receive metrics

### Actual behavior

Telegraf fails to start
