### ISSUE TITLE
Hi, please correct the filter examples.

### ISSUE THREAD

**Issue by filatov95** [influxdata/telegraf#13521]
### Use Case

If you write as in your example, the tag metrics won't drop, because you can't see that the tagdrop parameter is one level higher than inputs.win_perf_counters.object

### Expected behavior

```
[[inputs.win_perf_counters]]
# Don't send metrics where the Windows interface name (instance) begins with isatap or Local
# This illustrates the inline table syntax
tagdrop = {instance = ["isatap*", "Local*"]}
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec"
    ]
    Measurement = "win_net"

```

### Actual behavior

```
[[inputs.win_perf_counters]]

  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec"
    ]
    Measurement = "win_net"
  # Don't send metrics where the Windows interface name (instance) begins with isatap or Local
  # This illustrates the inline table syntax
 tagdrop = {instance = ["isatap*", "Local*"]}
```

### Additional info

I spent hours looking for a solution to the tagdrop issue and why it doesn't work.
In the end, I had to contact a colleague who suggested that I move tagdrop up a level. A big request, please correct your example and check the others.

**Comment by powersj** [comment]
Hi,

Can you please point to what example you are referring to? The [filtering examples](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#filtering-examples) shows an actual example of `win_perf_counters` with it at the end.

> I had to contact a colleague who suggested that I move tagdrop up a level.

Your actual behavior is not moving tagdrop "up" a level. It is moving it to the end of the plugin configuration under the object. The docs above already call out that this should be at the end of the plugin definition as well.

**Comment by filatov95** [comment]
Yes, I saw what you are talking about further down the line. In my opinion it would be just as clear if it was stated in the example itself.
I also used [[inputs.win_perf_counters]] plugin to collect data from ethernet adapter.
But for some reason the configuration below works the way you don't specify.
```
[[inputs.win_perf_counters]]
  tagdrop = {instance =["__TEAMNIC_*"]}
  [[inputs.win_perf_counters.object]]
    ObjectName = "Hyper-V Virtual Network Adapter"
    Instances = ["*"]
    Counters = ["Bytes/sec", "Bytes Received/sec", "Bytes Sent/Sec", "Packets Sent/sec", "Packets Received/sec", "Packets/sec"]
    Measurement = "hyperv.virtual.net.adapter"
    IncludeTotal = true
```
Maybe it can work either way.
I tried to write it the way you have it in your documentation, but tagdrop didn't work. Here's an example of a configuration that doesn't work
```
[[inputs.win_perf_counters]]

  [[inputs.win_perf_counters.object]]
    ObjectName = "Hyper-V Virtual Network Adapter"
    Instances = ["*"]
    Counters = ["Bytes/sec", "Bytes Received/sec", "Bytes Sent/Sec", "Packets Sent/sec", "Packets Received/sec", "Packets/sec"]
    Measurement = "hyperv.virtual.net.adapter"
    IncludeTotal = true
  tagdrop = {instance =["__TEAMNIC_*"]}
```
Anyway, either the documentation implies two ways to use tagdrop, or I'm doing something wrong :)

**Comment by filatov95** [comment]
I tried running these two configurations through the converter to json format. 
In the first version according to your example in the [documentation](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#filtering-examples):
```TOML
[[inputs.win_perf_counters]]
  
  [[inputs.win_perf_counters.object]]
    ObjectName = "Hyper-V Virtual Network Adapter"
    Instances = ["*"]
    Counters = ["Bytes/sec", "Bytes Received/sec", "Bytes Sent/Sec", "Packets Sent/sec", "Packets Received/sec", "Packets/sec"]
    Measurement = "hyperv.virtual.net.adapter"
    IncludeTotal = true
  tagdrop = {instance =["__TEAMNIC_*"]}
```
We get the following json:
```JSON
{
  "inputs": {
    "win_perf_counters": [
      {
        "object": [
          {
            "ObjectName": "Hyper-V Virtual Network Adapter",
            "Instances": [
              "*"
            ],
            "Counters": [
              "Bytes/sec",
              "Bytes Received/sec",
              "Bytes Sent/Sec",
              "Packets Sent/sec",
              "Packets Received/sec",
              "Packets/sec"
            ],
            "Measurement": "hyperv.virtual.net.adapter",
            "IncludeTotal": true,
            "tagdrop": {
              "instance": [
                "__TEAMNIC_*"
              ]
            }
          }
        ]
      }
    ]
  }
}

```
This is not the expected behavior, tagdrop cannot be child win_perf_counters.object
In my example, it works the way you describe in your documentation, filtering works at the end of the plugin
```TOML
[[inputs.win_perf_counters]]
  tagdrop = {instance =["__TEAMNIC_*"]}
  [[inputs.win_perf_counters.object]]
    ObjectName = "Hyper-V Virtual Network Adapter"
    Instances = ["*"]
    Counters = ["Bytes/sec", "Bytes Received/sec", "Bytes Sent/Sec", "Packets Sent/sec", "Packets Received/sec", "Packets/sec"]
    Measurement = "hyperv.virtual.net.adapter"
    IncludeTotal = true
```
This is what you get if you convert it to json:
```JSON
{
  "inputs": {
    "win_perf_counters": [
      {
        "tagdrop": {
          "instance": [
            "__TEAMNIC_*"
          ]
        },
        "object": [
          {
            "ObjectName": "Hyper-V Virtual Network Adapter",
            "Instances": [
              "*"
            ],
            "Counters": [
              "Bytes/sec",
              "Bytes Received/sec",
              "Bytes Sent/Sec",
              "Packets Sent/sec",
              "Packets Received/sec",
              "Packets/sec"
            ],
            "Measurement": "hyperv.virtual.net.adapter",
            "IncludeTotal": true
          }
        ]
      }
    ]
  }
}
```
So to you, a big request to correct your documentation and examples in them
