### ISSUE TITLE
Telegraf tail plugin with grok data format is giving wrong timestamp

### ISSUE THREAD

**Issue by spesalvi** [influxdata/telegraf#13523]
### Relevant telegraf.conf

```toml
[[outputs.file]]
	files = ['stdout']

[[processors.clone]]
          order=5
          namepass=["iislogs_saluto"]
          name_override = "app_request_logs_saluto"
 
 [[processors.regex]]
       order=6
       namepass=["app_request_logs_saluto"]
   [[processors.regex.fields]]
       key="request"
       pattern="/influencer.svc/(.*)"
       replacement="${1}"
       result_key="api"
[[processors.converter]]
     order=7
     namepass=["app_request_logs_saluto"]
     [processors.converter.fields]
         tag = ['api']	

[[inputs.tail]]
    files = ["C:\\inetpub\\logs\\LogFiles\\W3SVC*\\*.log", "*.log"]
    from_beginning = false
    name_override = "iislogs_saluto"
    watch_method = "poll"
    tagexclude = ["path"]
    data_format = "grok"
    grok_patterns = ["^%{CUSTOM_LOG_1}", "^%{CUSTOM_LOG_2}"]
    grok_custom_patterns = ''' 
		CUSTOM_LOG_1 %{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02 15:04:05"} %{IP:serverip:drop} %{URIPROTO:verb} %{URIPATH:request} (?:%{NOTSPACE:csquery}|-) %{NUMBER:csport:drop} (?:%{WORD:username:drop}|-) %{IP:clientip:drop} %{NOTSPACE:agent} (?:%{NOTSPACE:referer:drop}|-) (?:%{NOTSPACE:sitename:tag}|-) %{NUMBER:responsecode:tag} %{NUMBER:scsubstatus:drop} %{NUMBER:scwin32status:drop} %{NUMBER:timetaken:int}
		CUSTOM_LOG_2 %{TIMESTAMP_ISO8601:timestamp:ts-"2006-01-02 15:04:05"} %{IP:serverip:drop} %{URIPROTO:verb} %{URIPATH:request} (?:%{NOTSPACE:csquery}|-) %{NUMBER:csport:drop} (?:%{WORD:username:drop}|-) %{IP:clientip:drop} %{NOTSPACE:agent} (?:%{NOTSPACE:referer:drop}|-) %{NUMBER:responsecode:tag} %{NUMBER:scsubstatus:drop} %{NUMBER:scwin32status:drop} %{NUMBER:timetaken:int}
    '''
```

### Logs from Telegraf

```text
2023-06-30T14:13:52Z D! [outputs.file] Buffer fullness: 0 / 20000 metrics
app_request_logs_saluto,dc=AWS,env=prod,host=QCLAP1641P270,qcinstance=SALUTO,responsecode=200,sitename=qcperflab.qwikcilver.com request="/QwikCilver.RC/egms.httpprocessor2/transactionpost.aspx",csquery="-",verb="POST",agent="Java/1.8.0_341",timetaken=2676i 1688139939000000000
iislogs_saluto,dc=AWS,env=prod,host=QCLAP1641P270,qcinstance=SALUTO,responsecode=200,sitename=qcperflab.qwikcilver.com request="/QwikCilver.RC/egms.httpprocessor2/transactionpost.aspx",csquery="-",verb="POST",agent="Java/1.8.0_341",timetaken=2676i 1688139939000000000
app_request_logs_saluto,dc=AWS,env=prod,host=QCLAP1641P270,qcinstance=SALUTO,responsecode=200,sitename=qcperflab.qwikcilver.com agent="Java/1.8.0_341",timetaken=2676i,verb="POST",request="/QwikCilver.RC/egms.httpprocessor2/transactionpost.aspx",csquery="-" 1688139939001000000
iislogs_saluto,dc=AWS,env=prod,host=QCLAP1641P270,qcinstance=SALUTO,responsecode=200,sitename=qcperflab.qwikcilver.com agent="Java/1.8.0_341",timetaken=2676i,verb="POST",request="/QwikCilver.RC/egms.httpprocessor2/transactionpost.aspx",csquery="-" 1688139939001000000
```

### System info

Telegraf 1.27.1, Windows 

### Steps to reproduce

Use following log entry
```2023-06-30 11:45:39 192.168.38.171 POST /QwikCilver.RC/egms.httpprocessor2/transactionpost.aspx - 80 - 192.168.36.141 Java/1.8.0_341 - qcperflab.qwikcilver.com 200 0 0 2676```

### Expected behavior

Timestamp expected 1688125539000000000

### Actual behavior

Telegraf is giving timestamp 1688139939001000000

### Additional info

This issue is not present in Telegraf 1.14.x. Not sure from which version this issue is introduced
