### ISSUE TITLE
[outputs.mqtt] is not respecting retain = true configuration, retain flag is not set

### ISSUE THREAD

**Issue by oh2th** [influxdata/telegraf#13535]
### Relevant telegraf.conf

```toml
# Telegraf Configuration
#
###############################################################################

# Configuration for sending metrics to MQTT
[[outputs.mqtt]]
  servers = ["tcp://localhost:1883"]

  topic = '{{ .PluginName }}/{{.Tag "source"}}/{{.Tag "sensor"}}'
  layout = "field"

  #homie_device_name ='{{.PluginName}} plugin'
  #homie_node_id = '{{.Tag "source"}}-{{.Tag "sensor"}}'

  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"

  retain = true

  namepass = ["easymqtt"]

  data_format = "influx"
```

### Logs from Telegraf

```text
No relevant log
```

### System info

Telegraf 1.27.1 (git: HEAD@a830df8f)

### Steps to reproduce

1. Data is processed and succefully sent to MQTT in expected format
2. as per configuration retain flag should be set on topics sent to MQTT
3. MQTT Explorer is not showing that the flag is set.
...

### Expected behavior

Retain flag on topic to be set. And shown with MQTT Explorer:

<img width="379" alt="Screenshot 2023-07-03 at 21 20 49" src="https://github.com/influxdata/telegraf/assets/59442255/b4c29d24-bdb6-4988-a810-2e0d3d420e00">

### Actual behavior

No flaf set for topics published by output_mqtt
<img width="380" alt="Screenshot 2023-07-03 at 21 21 44" src="https://github.com/influxdata/telegraf/assets/59442255/b7bcff1f-a1e6-49d4-9c5f-101f8318f449">
