### ISSUE TITLE
Nebius Cloud Monitoring has reserved "name" tag, so it must be replaced

### ISSUE THREAD

**Issue by abrekhov** [influxdata/telegraf#13596]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true
  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000
  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000
  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"
  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"
  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""
  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  # quiet = false
  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"
  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""
  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"
  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"
  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to
  ## Note: Most, but not all, udev properties can be accessed this way. Properties
  ## that are currently inaccessible include DEVTYPE, DEVNAME, and DEVPATH.
  # device_tags = ["ID_FS_TYPE", "ID_FS_USAGE"]
  #
  ## Using the same metadata source as device_tags, you can also customize the
  ## name of the device via templates.
  ## The 'name_templates' parameter is a list of templates to try and apply to
  ## the device. The template may contain variables in the form of '$PROPERTY' or
  ## '${PROPERTY}'. The first template which does not contain any variables not
  ## present for the device is used as the device name tag.
  ## The typical use case is for LVM volumes, to get the VG/LV name instead of
  ## the near-meaningless DM-0 name.
  # name_templates = ["$ID_FS_LABEL","$DM_VG_NAME/$DM_LV_NAME"]
# fieldpass = ["reads","writes","read_bytes","write_bytes"]
[[inputs.netstat]]
[[inputs.ntpq]]

[[inputs.procstat]]
  exe = "docker"
# Get kernel statistics from /proc/stat
[[inputs.kernel]]
  # no configuration
# Read metrics about memory usage
[[inputs.mem]]
  # no configuration
  fieldpass = ["available","used_percent"]
# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration
# Read metrics about swap memory usage
[[inputs.swap]]
  # no configuration
  fieldpass = ["free","used_percent"]
# Read metrics about system load & uptime
[[inputs.system]]
  ## Uncomment to remove deprecated metrics.
  # fielddrop = ["uptime_format"]
  fieldpass = ["uptime"]
[[inputs.systemd_units]]
  unittype="service"
  #pattern = "telegraf*"
[[inputs.net_response]]
  protocol = "tcp"
  address = "localhost:22"
[[outputs.nebius_cloud_monitoring]]
```

### Logs from Telegraf

```text
2023-07-11T13:11:52Z I! Loading config: /etc/telegraf/telegraf.conf                                                               2023-07-11T13:11:52Z W! DeprecationWarning: Option "dns_lookup" of plugin "inputs.ntpq" deprecated since version 1.24.0 and will b
e removed in 2.0.0: add '-n' to 'options' instead to skip DNS lookup                                                              2023-07-11T13:11:52Z I! Starting Telegraf 1.28.0-35010d74
2023-07-11T13:11:52Z I! Available plugins: 237 inputs, 9 aggregators, 28 processors, 23 parsers, 59 outputs, 4 secret-stores      2023-07-11T13:11:52Z I! Loaded inputs: cpu disk kernel mem net_response netstat ntpq processes procstat swap system systemd_units
2023-07-11T13:11:52Z I! Loaded aggregators:                                                                                       2023-07-11T13:11:52Z I! Loaded processors:
2023-07-11T13:11:52Z I! Loaded secretstores:                                                                                      2023-07-11T13:11:52Z W! Outputs are not used in testing mode!
2023-07-11T13:11:52Z I! Tags enabled: datacenter=hrc host=ua-vm-exporter                                                          2023-07-11T13:11:52Z W! Deprecated inputs: 0 and 1 options
2023-07-11T13:11:52Z D! [agent] Initializing plugins                                                                              2023-07-11T13:11:52Z D! [agent] Starting service inputs
> systemd_units,active=active,datacenter=hrc,host=ua-vm-exporter,load=loaded,name=accounts-daemon.service,sub=running active_code=0i,load_code=0i,sub_code=0i 1689081113000000000
```

### System info

Telegraf 1.28.0? Ubuntu 20.04.6 LTS

### Steps to reproduce

1. Launch 1.28 telegraf agent on ubuntu with outputs.nebius_cloud_monitoring plugin

### Expected behavior

systemd metrics must be written to Nebius Monitoting backend.

### Actual behavior

systemd metrics will not be written to Nebius Monitoting backend.

### Additional info

Answer from Nebius support:

> 
> Indeed you cannot use:
> %%(json)
> {
> "name": "systemd_units_load_code",
> "labels": {
> "active": "active",
> "datacenter": "hrc",
> "host": "ua-vm-exporter",
> "load": "loaded",
> "name": "accounts-daemon.service",
> "sub": "running"
> },
> "ts": "2023-06-06T11:10:50Z",
> "value": 0
> }
> %%
> where "name" is defined twice (one at top level of JSON metric, one at labels section)
> 
> => Can you try to remove the %%(json).labels.name%% and use only "name" at top level?
> 
> Thanks in advance for your attention and feedback
> 
> >
