### ISSUE TITLE
input snmp field value prefix / suffix

### ISSUE THREAD

**Issue by tallexer** [influxdata/telegraf#13634]
### Use Case

There are SNMP MIBs that do not implement name / description OIDs of entries in a given table. In those situations, the index is too cryptic and adding some more context will require extra processing. The proposal here is to allow prefix/suffix functionality on field values right at the input as a simple and efficient way to deal with this use case.

For example:
```sh
snmpwalk -v 2c -c public hostname F5-BIGIP-SYSTEM-MIB::sysChassisFanTable
F5-BIGIP-SYSTEM-MIB::sysChassisFanIndex.1 = INTEGER: 1
F5-BIGIP-SYSTEM-MIB::sysChassisFanIndex.2 = INTEGER: 2
F5-BIGIP-SYSTEM-MIB::sysChassisFanIndex.3 = INTEGER: 3
F5-BIGIP-SYSTEM-MIB::sysChassisFanIndex.4 = INTEGER: 4
F5-BIGIP-SYSTEM-MIB::sysChassisFanStatus.1 = INTEGER: good(1)
F5-BIGIP-SYSTEM-MIB::sysChassisFanStatus.2 = INTEGER: good(1)
F5-BIGIP-SYSTEM-MIB::sysChassisFanStatus.3 = INTEGER: good(1)
F5-BIGIP-SYSTEM-MIB::sysChassisFanStatus.4 = INTEGER: good(1)
F5-BIGIP-SYSTEM-MIB::sysChassisFanSpeed.1 = Gauge32: 16266
F5-BIGIP-SYSTEM-MIB::sysChassisFanSpeed.2 = Gauge32: 15913
F5-BIGIP-SYSTEM-MIB::sysChassisFanSpeed.3 = Gauge32: 16266
F5-BIGIP-SYSTEM-MIB::sysChassisFanSpeed.4 = Gauge32: 16266
```

### Expected behavior

Define additional field keys *prefix* and *suffix* to transform the field value with a prefix and/or a suffix:

For example:

```toml
[[inputs.snmp.table.field]]
    name = 'name'
    oid = 'F5-BIGIP-SYSTEM-MIB::sysChassisFanIndex'
    is_tag = true
    prefix = 'fan'
```

This should concatenate the prefix and the value:
```
> fans,name=fan2 speed=16266i,status="good" 1689599481000000000
> fans,name=fan3 speed=16266i,status="good" 1689599481000000000
> fans,name=fan4 speed=16266i,status="good" 1689599481000000000
> fans,name=fan1 speed=16266i,status="good" 1689599481000000000
```

### Actual behavior

Without a prefix, the tag will only use the Index value:

```toml
[[inputs.snmp.table.field]]
    name = 'name'
    oid = 'F5-BIGIP-SYSTEM-MIB::sysChassisFanIndex'
    is_tag = true
```

```
> fans,name=2 speed=16266i,status="good" 1689599481000000000
> fans,name=3 speed=16266i,status="good" 1689599481000000000
> fans,name=4 speed=16266i,status="good" 1689599481000000000
> fans,name=1 speed=16266i,status="good" 1689599481000000000
```
