### ISSUE TITLE
Cannot use hash (#) in exec input - invalid TOML syntax

### ISSUE THREAD

**Issue by moorglade** [influxdata/telegraf#13643]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  commands = ["echo \"abc#def\""]
```

### Logs from Telegraf

```text
error loading config file /etc/telegraf/inputs/my_exec.conf: error parsing data: line 3: invalid TOML syntax
```

### System info

Telegraf 1.27.2

### Steps to reproduce

I want to use the `exec` input with a command containing a hash (`#`) symbol. It used to work before, but now Telegraf seems to treat `#` inside of a string as a beginning of a comment.   

### Expected behavior

The hash inside a string should be parsed normally.

### Actual behavior

Telegraf fails to parse TOML.

**Comment by powersj** [comment]
Hi,

This appears to be another regression from https://github.com/influxdata/telegraf/commit/7c636b4b6b38e7da4446a48854b5fc55b8b78104

As a temporary work around you can use a string literal (single quotes) instead:

```toml
[[inputs.exec]]
  commands = ['echo \"abc#def\"']
  data_format = "influx"
```
