### ISSUE TITLE
Randomly stops doing anything

### ISSUE THREAD

**Issue by sezanzeb** [influxdata/telegraf#13648]
### Relevant telegraf.conf

```toml
[agent]
	interval = "1s"
	flush_interval = "1s"

	debug = true
	quiet = false

[[inputs.mqtt_consumer]]
	servers = [ "mqtt://broker:1883" ]
	topics = [ "#" ]

	data_format = "json"
	tag_keys = [ "device" ]
	json_time_key = "time"
	json_time_format = "2006-01-02T15:04:05.000Z"

	[[inputs.mqtt_consumer.topic_parsing]]
		topic = "foo/+/+"
		measurement = "_/_/measurement"
		tags = "_/foo_serial/_"

    #[[inputs.mqtt_consumer.json_v2]]
    #	timestamp_path = "time"
    #	timestamp_format = "2006-01-02T15:04:05.000Z"
    #	[[inputs.mqtt_consumer.json_v2.tag]]
    #		path = "device"
	#	[[inputs.mqtt_consumer.json_v2.field]]
	#		path = "power1"
	#		type = "float"


[[processors.unpivot]]
	tag_key = "field"
	value_key = "value"

[[outputs.file]]
	files = ["stdout"]

[[outputs.postgresql]]
	connection = "host=database user=postgres password=password dbname=bar"

	tag_table_add_column_templates = []
	tag_table_create_templates = []
	add_column_templates = []
	create_templates = []

	tagexclude = [ "topic", "host" ]
```

### Logs from Telegraf

```text
telegraf-1           | 2023-07-20T07:12:33Z D! [outputs.postgresql] Wrote batch of 2 metrics in 7.919442ms
telegraf-1           | 2023-07-20T07:12:33Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:34Z D! [outputs.file] Wrote batch of 2 metrics in 59.361µs
telegraf-1           | 2023-07-20T07:12:34Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
telegraf-1           | telemetry,device=foo-el-1,field=power1,host=3d36e81418bf,foo_serial=simulated,topic=foo/simulated/telemetry value=2327.1 1689837153178000000
telegraf-1           | telemetry,device=foo-el-1,field=power2,host=3d36e81418bf,foo_serial=simulated,topic=foo/simulated/telemetry value=-3658.7 1689837153178000000
```

Has been writing stuff up to this point for a few minutes every second.

From here on it just keeps repeating that the buffer is empty

```text
telegraf-1           | 2023-07-20T07:12:34Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:35Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
foo-simulator-1  | [Nest] 61  - 07/20/2023, 7:12:35 AM     LOG [SimulatorService] Publishing: {"time":"2023-07-20T07:12:35.179Z","foo_serial":"simulated","device":"foo-el-1","power1":2204.6,"power2":-3189.8}
telegraf-1           | 2023-07-20T07:12:35Z D! [outputs.postgresql] Wrote batch of 2 metrics in 2.297379ms
telegraf-1           | 2023-07-20T07:12:35Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:36Z D! [outputs.file] Wrote batch of 2 metrics in 60.203µs
telegraf-1           | 2023-07-20T07:12:36Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
telegraf-1           | telemetry,device=foo-el-1,field=power1,host=3d36e81418bf,foo_serial=simulated,topic=foo/simulated/telemetry value=2204.6 1689837155179000000
telegraf-1           | telemetry,device=foo-el-1,field=power2,host=3d36e81418bf,foo_serial=simulated,topic=foo/simulated/telemetry value=-3189.8 1689837155179000000
telegraf-1           | 2023-07-20T07:12:36Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:37Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
foo-simulator-1  | [Nest] 61  - 07/20/2023, 7:12:37 AM     LOG [SimulatorService] Publishing: {"time":"2023-07-20T07:12:37.179Z","foo_serial":"simulated","device":"foo-el-1","power1":2666,"power2":-3899.9}
telegraf-1           | 2023-07-20T07:12:37Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:38Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:38Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:39Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
foo-simulator-1  | [Nest] 61  - 07/20/2023, 7:12:39 AM     LOG [SimulatorService] Publishing: {"time":"2023-07-20T07:12:39.181Z","foo_serial":"simulated","device":"foo-el-1","power1":2448,"power2":-3439.4}
telegraf-1           | 2023-07-20T07:12:39Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:40Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:40Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:41Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
foo-simulator-1  | [Nest] 61  - 07/20/2023, 7:12:41 AM     LOG [SimulatorService] Publishing: {"time":"2023-07-20T07:12:41.182Z","foo_serial":"simulated","device":"foo-el-1","power1":2375.7,"power2":-4005.5}
telegraf-1           | 2023-07-20T07:12:41Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:42Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:42Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:43Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
foo-simulator-1  | [Nest] 61  - 07/20/2023, 7:12:43 AM     LOG [SimulatorService] Publishing: {"time":"2023-07-20T07:12:43.185Z","foo_serial":"simulated","device":"foo-el-1","power1":2483.6,"power2":-3497.3}
telegraf-1           | 2023-07-20T07:12:43Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:44Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:44Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
telegraf-1           | 2023-07-20T07:12:45Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
foo-simulator-1  | [Nest] 61  - 07/20/2023, 7:12:45 AM     LOG [SimulatorService] Publishing: {"time":"2023-07-20T07:12:45.186Z","foo_serial":"simulated","device":"foo-el-1","power1":1980.1,"power2":-4123.9}
telegraf-1           | 2023-07-20T07:12:45Z D! [outputs.postgresql] Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.27.2 (git: HEAD@9356fd83); Docker version 23.0.4, build f480fb1e37

### Docker

    telegraf:
        image: telegraf
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
        depends_on:
            - database
            - broker

### Steps to reproduce

I just run the above configuration and start pulishing messages

### Expected behavior

To not stop doing stuff

### Actual behavior

Won't do anything until I restart the container (`docker-compose restart telegraf`)
