### ISSUE TITLE
conntrack input module ignores settings

### ISSUE THREAD

**Issue by maintain3r** [influxdata/telegraf#13686]
### Relevant telegraf.conf

```toml
[[inputs.conntrack]]
  files = ["nf_conntrack_count","nf_conntrack_max"]
  dirs = ["/proc/sys/net/netfilter"]
  collect = ["all", "percpu"]
```

### Logs from Telegraf

```text
Jul 27 17:39:30 prox-01 telegraf[3773920]: 2023-07-27T21:39:30Z E! [inputs.conntrack] Error in plugin: failed to retrieve conntrack statistics: open /proc/net/stat/nf_conntrack: no such file or directory
Jul 27 17:39:30 prox-01 telegraf[3773920]: 2023-07-27T21:39:30Z E! [inputs.conntrack] Error in plugin: conntrack input failed to collect stats
```

### System info

Telegraf 1.27.2 (git: HEAD@9356fd83)

### Steps to reproduce

1. Run telegraf with input config specified above
2. OS Ubuntu srv 22.04
3. tail -f /var/log/syslog

### Expected behavior

Telegraf should not spit errors about /proc/net/stat/nf_conntrack. There's no entry in config pointing to '/proc/net/stat/nf_conntrack'

### Actual behavior

Jul 27 17:39:30 prox-01 telegraf[3773920]: 2023-07-27T21:39:30Z E! [inputs.conntrack] Error in plugin: failed to retrieve conntrack statistics: open /proc/net/stat/nf_conntrack: no such file or directory
Jul 27 17:39:30 prox-01 telegraf[3773920]: 2023-07-27T21:39:30Z E! [inputs.conntrack] Error in plugin: conntrack input failed to collect stats
