### ISSUE TITLE
[BUG] unable to parse complex protobuf message

### ISSUE THREAD

**Issue by jcpunk** [influxdata/telegraf#13715]
### Relevant telegraf.conf

```toml
[[outputs.postgresql]]    
  connection = "postgres://username:password@postgresql.dbs.svc/ApplicationDbErrorReporting?sslmode=disable"

[[inputs.kafka_consumer]]
    brokers = [
    "kafka.cern.ch:30092"
  ]
  client_id = "ers-telegraf"

  consumer_group = "ers-telegraf"
  data_format = "xpath_protobuf"
  topics = [
    "ers_stream"
  ]
  xpath_protobuf_file = "/mnt/issue.proto"
  xpath_protobuf_type = "dunedaq.ersschema.Context"
  [[inputs.kafka_consumer.xpath]]
    metric_name = "string('ProtobuffReports')"
```

### Logs from Telegraf

```text
2023-07-27T23:34:34Z D! [parsers.xpath_protobuf::kafka_consumer] raw data (hex): "0ae6020afe010a1c2f6166732f6365726e2e63682f757365722f722f7269656865636b791283012f746d702f726f6f742f737061636b2d73746167652f737061636b2d73746167652d6572736b61666b612d4e4232332d30372d32362d69616f37626f67666c6373796f7a72686d7a626e6f74643667667178367079652f737061636b2d7372632f746573742f617070732f70726f746f6275665f73747265616d5f746573742e6378781a15696e74206d61696e28696e742c20636861722a2a2922116c78706c75733739302e6365726e2e636828213207756e6b6e6f776e58b7f80160b7f80168e48d0872087269656865636b797a0d45525353747265616d5465737412136572736b61666b613a3a5465737449737375651a0a6572733a3a49737375651a136572736b61666b613a3a54657374497373756522197468697320697320697373756520776974682049443a2031342a013430aaeae8cc99313a080a02696412023134520d54657374506172746974696f6e5a0d45525353747265616d54657374" (skip 0 bytes)
2023-07-27T23:34:34Z E! [inputs.kafka_consumer] Error in plugin: proto: field dunedaq.ersschema.Context.cwd contains invalid UTF-8
```

### System info

telegraf-1.27.2

### Docker

Running inside kubernetes

### Steps to reproduce

1. serialize complex message using provided schema
2. send to kafka
3. try to collect via telegraf

### Expected behavior

Parse the message out into some sort of object tree

### Actual behavior

Unable to parse message

### Additional info

protobuf schema : https://github.com/DUNE-DAQ/ers/blob/develop/schema/ers/issue.proto
https://github.com/DUNE-DAQ/erskafka/issues/20
