### ISSUE TITLE
postgresql_extensible: datname is not removed from fields

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#13729]
### Relevant telegraf.conf

```toml
[agent]
omit_hostname = true

[outputs.file]

[inputs.postgresql_extensible]
address = "postgresql://USER:PASSWORD@127.0.0.1:7777/mydb?default_transaction_read_only=on"

[[inputs.postgresql_extensible.query]]
measurement="pg_stat_database"
sqlquery="""
    SELECT datname,
            numbackends
    FROM pg_stat_database
    WHERE datname NOT IN ('template0', 'template1')
"""
```

### Logs from Telegraf

```text
pg_stat_database,db=postgres datname="postgres",numbackends=0i 1691385991000000000
pg_stat_database,db=mydb datname="mydb",numbackends=262i 1691385991000000000
```

### System info

latest master

### Steps to reproduce

Run with provided config

### Expected behavior

`datname` to be removed from fields

### Actual behavior

`datname` to be stays in fields

### Additional info

`datname` columns tratment is hardcoded in the plugin, its value is used for `db` tag when column is present. When it happens I'd expect `datname` to be removed from the fields, because it adds not value having it there.
