### ISSUE TITLE
postgresql_extensible: max_version doesn't work without specifying min_version

### ISSUE THREAD

**Issue by redbaron** [influxdata/telegraf#13771]
### Relevant telegraf.conf

```toml
[[inputs.postgresql_extensible]]

[[inputs.postgresql_extensible.query]]
sqlquery = "SELECT 1"
max_version = 1100
```

### Logs from Telegraf

```text
-
```

### System info

1.27.3

### Steps to reproduce

specify `max_version` without `min_version`

### Expected behavior

`max_version` is respected

### Actual behavior

`max_version` is ignored
