### ISSUE TITLE
TOML parsed wrong if options in example configuration are enabled / Option ordering in example configuration is wrong

### ISSUE THREAD

**Issue by UweSauter** [influxdata/telegraf#13781]
### Relevant telegraf.conf

```toml
[global_tags]
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "300s"
  flush_jitter = "0s"
  precision = "0s"
  log_with_timezone = "Europe/Berlin"
  hostname = ""
  omit_hostname = false
[[outputs.kafka]]
  brokers = ["admin:9092"]
  topic = "telegraf"
  [outputs.kafka.topic_suffix]
    method = "measurement"
    separator = "_"
  data_format = "json"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  core_tags = false
[[inputs.mem]]
```

### Logs from Telegraf

```text
Logs not relevant as the read configuration is not shown.
```

### System info

Telegraf v1.27.3, Rocky Linux 8.8

### Steps to reproduce

1. Use above configuration.
2. Watch the data format that is sent to Kafka, e.g. by using `tcpdump -i $INTERFACE -Annvv tcp dst port 9092`
3. See that the InfluxDB line protocol is used.

### Expected behavior

Instead of the default data format (InfluxDB line protocol) the configured data format should be used.

### Actual behavior

The default data format is used. The configured data format is ignored.

### Additional info

As far as I can get a grasp of the issue it simply is a question of ordering the options in the configuration file.

The configuration file is using the [TOML file format](https://toml.io/en/v1.0.0). That means that the file is segmented where each section starts with a `[section name]` headline. (This statement is a bit simplified but enough to show my point.)
Every key-value pair following the headline will belong to that section. Leading whitespaces are ignored.

Take a look at the `outputs.kafka` section of the configuration file created by `telegraf config`. The only changes made here are the section has been enabled, comments have been stripped and `data_format` has been set.
```toml
[[outputs.kafka]]
  brokers = ["localhost:9092"]
  topic = "telegraf"
  # topic_tag = ""
  # exclude_topic_tag = false
  # client_id = "Telegraf"
  # version = ""

  # [outputs.kafka.topic_suffix]
  #   method = "measurement"
  #   separator = "_"

  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo"]
  #   separator = "__"

  # [outputs.kafka.topic_suffix]
  #   method = "tags"
  #   keys = ["foo", "bar"]
  #   separator = "_"

  routing_tag = "host"
  # routing_key = ""
  # compression_codec = 0
  # idempotent_writes = false
  # required_acks = -1
  # max_retry = 3
  # max_message_bytes = 1000000
  # enable_tls = false
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  # insecure_skip_verify = false
  # keep_alive_period = "15s"
  # socks5_enabled = true
  # socks5_address = "127.0.0.1:1080"
  # socks5_username = "alice"
  # socks5_password = "pass123"
  # sasl_username = "kafka"
  # sasl_password = "secret"
  # sasl_mechanism = ""
  # sasl_gssapi_service_name = ""
  # sasl_gssapi_auth_type = "KRB5_USER_AUTH"
  # sasl_gssapi_kerberos_config_path = "/"
  # sasl_gssapi_realm = "realm"
  # sasl_gssapi_key_tab_path = ""
  # sasl_gssapi_disable_pafxfast = false
  # sasl_access_token = ""
  # sasl_version = 1
  # metadata_full = false
  data_format = "json"
```

If this section is used as is then `data_format` belongs to `[[outputs.kafka]]`.
But if one of the sub-sections `[outputs.kafka.topic_suffix]` is used, then `data_format` (really everything below the sub-section headline) belongs to the sub-section.

This causes problems because settings configured in the file are not honored.

The same applies to almost every other plugin section in the configuration file generated by Telegraf.

In order to resolve the issue Telegraf / the plugins would need to re-order the configuration sub-sections of plugin configurations so that settings belonging to the plugin section appear above of the sub-sections.

(My current work-around is to put `data_format` right after `brokers` but I think that an example configuration should not need this.)
