### ISSUE TITLE
Dynamically Set the Project Config Option for outputs.stackdriver

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#13784]
### Use Case

Telegraf agent is sending to a Telegraf server and those metrics are being sent out via outuputs.stackdriver. The `project` top level configuration option is used to determine which Google project the metrics are sent to. It would be cool if that `project` configuration option could be set simialiry to how the `tags_as_resource_label` config option is set now, where the tag `project_id` could be inherited as the `project` label.  

### Expected behavior

I don't believe this is possible now. 

### Actual behavior

I don't think this feature exists.

**Comment by powersj** [comment]
Hey @crflanigan,

I think we could make this work. It looks like the project field is only used in two places:

1. Set as a resource label called `project_id`, currently do this in `Connect()`
2. Name of the time series request via `projects/$PROJECT` in `sendBatch()`

I think we could:

* Add a new option `project_tag` that when set will use that tag to determine the project to use
* Expect either `project_tag` or `projet` to be set, not both in the config
* When creating a batch, find that tag, set the project to that and drop the tag from the original metric

```toml
[[outputs.stackdriver]]
  ## Project tag
  ## When defined this tag is used to determine the project to
  ## use when sending metrics
  project_tag = "project"
```

What happens however when a metric has no project tag defined? Do we drop the metric?
