### ISSUE TITLE
inputs.cisco_telemetry_mdt giving panic: runtime error: index out of range [0] with length 0 when using with TCP protocol

### ISSUE THREAD

**Issue by Rajat0312** [influxdata/telegraf#13789]
### Relevant telegraf.conf

```toml
apiVersion: v1
data:
  telegraf.conf: |
    [agent]
      collection_jitter = "0s"
      debug = true
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
    [[processors.enum]]
       [[processors.enum.mapping]]
        dest = "status_code"
        field = "status"
        [processors.enum.mapping.value_mappings]
            critical = 3
            healthy = 1
            problem = 2


    [[inputs.cisco_telemetry_mdt]]
      transport = "tcp"
      service_address = ":57000" # instruct telegraf to listen on port 57000 for TCP telemetry
      max_msg_size = 2000000000
 
    [[inputs.cisco_telemetry_mdt]]
      transport = "grpc"
      service_address = ":57001" # instruct telegraf to listen on port 57001 for grpc telemetry
      max_msg_size = 2000000000
 

    [[outputs.file]]
      files = ["stdout"] # files to write to, "stdout" is a specially handled file
      data_format = "json"

    [[outputs.kafka]]
      brokers = ["localhost:9092"]
      topic = "test"
      ssl_cert = "/etc/telegraf/kafka.cert"
      insecure_skip_verify = true
      data_format = "json"
      # ssl_ca = "ca.pem"
      # ssl_key = "elvarx1.key"
```

### Logs from Telegraf

```text
2023-08-16T12:48:42Z I! Loading config: /etc/telegraf/telegraf.conf
2023-08-16T12:48:42Z W! DeprecationWarning: Option "ssl_cert" of plugin "outputs.kafka" deprecated since version 1.7.0 and will be removed in 2.0.0: use 'tls_cert' instead
2023-08-16T12:48:42Z E! Unsupported logtarget: stdout, using stderr
2023-08-16T12:48:42Z I! Starting Telegraf 1.27.3
2023-08-16T12:48:42Z I! Available plugins: 237 inputs, 9 aggregators, 28 processors, 23 parsers, 59 outputs, 4 secret-stores
2023-08-16T12:48:42Z I! Loaded inputs: cisco_telemetry_mdt (2x)
2023-08-16T12:48:42Z I! Loaded aggregators:
2023-08-16T12:48:42Z I! Loaded processors: enum
2023-08-16T12:48:42Z I! Loaded secretstores:
2023-08-16T12:48:42Z I! Loaded outputs: file kafka prometheus_client
2023-08-16T12:48:42Z I! Tags enabled: host=telegraf
2023-08-16T12:48:42Z W! Deprecated outputs: 0 and 1 options
2023-08-16T12:48:42Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
2023-08-16T12:48:42Z I! [outputs.prometheus_client] Listening on http://[::]:9091/metrics
panic: runtime error: index out of range [0] with length 0
```

### System info

Telegraf 1.27.3 alpine 3.18.2 

### Docker

FROM alpine:3.18

RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
RUN apk add --no-cache iputils ca-certificates net-snmp-tools procps lm_sensors tzdata su-exec libcap && \
    update-ca-certificates

ENV TELEGRAF_VERSION 1.27.3

RUN ARCH= && \
    case "$(apk --print-arch)" in \
        x86_64) ARCH='amd64';; \
        aarch64) ARCH='arm64';; \
        *) echo "Unsupported architecture: $(apk --print-arch)"; exit 1;; \
    esac && \
    set -ex && \
    mkdir ~/.gnupg; \
    echo "disable-ipv6" >> ~/.gnupg/dirmngr.conf; \
    apk add --no-cache --virtual .build-deps wget gnupg tar && \
    for key in \
        9D539D90D3328DC7D6C8D3B9D8FF8E1F7DF8B07E ; \
    do \
        gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys "$key" ; \
    done && \
    wget --no-verbose https://dl.influxdata.com/telegraf/releases/telegraf-${TELEGRAF_VERSION}_linux_${ARCH}.tar.gz.asc && \
    wget --no-verbose https://dl.influxdata.com/telegraf/releases/telegraf-${TELEGRAF_VERSION}_linux_${ARCH}.tar.gz && \
    gpg --batch --verify telegraf-${TELEGRAF_VERSION}_linux_${ARCH}.tar.gz.asc telegraf-${TELEGRAF_VERSION}_linux_${ARCH}.tar.gz && \
    mkdir -p /usr/src /etc/telegraf && \
    tar -C /usr/src -xzf telegraf-${TELEGRAF_VERSION}_linux_${ARCH}.tar.gz && \
    mv /usr/src/telegraf*/etc/telegraf/telegraf.conf /etc/telegraf/ && \
    mkdir /etc/telegraf/telegraf.d && \
    cp -a /usr/src/telegraf*/usr/bin/telegraf /usr/bin/ && \
    gpgconf --kill all && \
    rm -rf *.tar.gz* /usr/src /root/.gnupg && \
    apk del .build-deps && \
    addgroup -S telegraf && \
    adduser -S telegraf -G telegraf && \
    chown -R telegraf:telegraf /etc/telegraf

EXPOSE 8125/udp 8092/udp 8094

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["telegraf"]

### Steps to reproduce

1.start telegraf with tcp and grpc both cisco mdt plugin
2.input data from source -{"fields":{"threshold":346,"speed":327},"name":"cisco","tags":{"host":"telegraf","name":"1","path":"cisco-path","source":"router-1","subscription":"1"},"timestamp":1631191178} 
3.it was working in telegraf 1.23.3
...

### Expected behavior

It should be running with no error . Right now it gets down

### Actual behavior

It gets down with error panic: runtime error: index out of range [0] with length 0

### Additional info

It is running in telegraf 1.23.3 but not in latest versions
