### ISSUE TITLE
metricpass: python compatibility regex alters real data, breaks filtering

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#13790]
### Relevant telegraf.conf

```toml
~$ cat filter-bug.conf
## BROKEN BEHAVIOUR

[[inputs.mock]]
metric_name = "bugreport"
tags = { "this" = "should not pass unmodified" }            # <-
[[inputs.mock.constant]]                                    #   \
name  = "but"                                               #   |
value = "does pass unmodified"                              #   | These are equal, but the metric DOESN'T pass
                                                            #   |
[[processors.regex]]                                        #   /
metricpass = "tags.this == 'should not pass unmodified'"    # <-
[[processors.regex.fields]]
key = "but"
pattern = ".*"
replacement = "is modified"

# > bugreport,host=host,this=should\ not\ pass\ unmodified but="does pass unmodified" 1692356637000000000

############

[[inputs.mock]]
metric_name = "bugreport"
tags = { "this" = "shouldn't ! be modified" }              # <-
[[inputs.mock.constant]]                                   #   \
name  = "and"                                              #   |
value = "is not modified"                                  #   | These are NOT equal, but the metric DOES pass
                                                           #   |
[[processors.regex]]                                       #   /
metricpass = "tags.this == 'shouldn\\'t not be modified'"  # <-
[[processors.regex.fields]]
key = "and"
pattern = ".*"
replacement = "is modified"


# > bugreport,host=host,this=shouldn't\ !\ be\ modified and="is modified" 1692356637000000000

~$ cat filter-bug-expected.conf
#################################################################################
## EXPECTED BEHAVIOUR
## (I just took the filter-bug.conf, did a s/not/NOT/ and fixed the comments)

[[inputs.mock]]
metric_name = "bugreport"
tags = { "this" = "should NOT pass unmodified" }            # <-
[[inputs.mock.constant]]                                    #   \
name  = "but"                                               #   |
value = "does pass unmodified"                              #   | These are equal, and the metric does pass, as expected
                                                            #   |
[[processors.regex]]                                        #   /
metricpass = "tags.this == 'should NOT pass unmodified'"    # <-
[[processors.regex.fields]]
key = "but"
pattern = ".*"
replacement = "is modified"

# > bugreport,host=host,this=should\ NOT\ pass\ unmodified but="is modified" 1692357673000000000


############

[[inputs.mock]]
metric_name = "bugreport"
tags = { "this" = "shouldn't ! be modified" }              # <-
[[inputs.mock.constant]]                                   #   \
name  = "and"                                              #   |
value = "is NOT modified"                                  #   | These are NOT equal, and the metric doesn't pass, as expected
                                                           #   |
[[processors.regex]]                                       #   /
metricpass = "tags.this == 'shouldn\\'t NOT be modified'"  # <-
[[processors.regex.fields]]
key = "and"
pattern = ".*"
replacement = "is modified"

# > bugreport,host=host,this=shouldn't\ !\ be\ modified and="is NOT modified" 1692357673000000000
```

### Logs from Telegraf

```text
see in the comments above.
```

### System info

doesn't matter

### Steps to reproduce

You use the metricpass to check for equality with a string containing "and", "or" or "not"

### Expected behavior

Correct matching of equal strings

### Actual behavior

No correct matching of equal strings

### Additional info

https://github.com/influxdata/telegraf/blob/168d9272752a81ea9df9f48998a25026debe4cb5/models/filter.go#L261
This is wrong as you can't assume that there won't ever be a "not", "and" or "or" which you must not replace. This makes the feature unrealiable und therefore potentially useless (if you know about the problem) or dangerous (if you don't).
It is generally a very bad idea to modify complex language structures by regex. You shouldn't do that.

This also is also a very nasty bug, because you can't fix it without breaking existing config. I would argue that you can't fix the regex, b/c the underlying structure of CEL is more complex than what can be described by regular languages (and therefore regex). But I am not completely sure. (you can check if a number is prime with regex, after all)

You could deprecate metricpass and have, idk, "celpass" instead with those three regex-replaces removed.
