### ISSUE TITLE
[inputs.modbus] FLOAT32 in config_style registers broken

### ISSUE THREAD

**Issue by MyChaOS87** [influxdata/telegraf#13827]
### Relevant telegraf.conf

```toml
[[inputs.modbus]]    
      configuration_type = "register"
      controller = "tcp://<IP>:502"
      name = "modbus"
      slave_id = 1
      timeout = "1s"
      [[inputs.modbus.holding_registers]]  
        address = [
          132,
          133
        ]
        byte_order = "CDAB"
        data_type = "FLOAT32"
        name = "Broken"
        scale = 1.0000001
      [[inputs.modbus.holding_registers]]  
        address = [
          132,
          133
        ]
        byte_order = "CDAB"
        data_type = "FLOAT32-IEEE"
        name = "Working"
        scale = 1.0000001
```

### Logs from Telegraf

```text
2023-08-24T09:18:30Z D! [inputs.modbus] got holding@132[2]: [114 155 65 184]
2023-08-24T09:18:30Z D! [inputs.modbus]   field Broken with offset 0 with len 4: [114 155 65 184] --> 1.1026071132607005e+09
2023-08-24T09:18:30Z D! [inputs.modbus] trying to read holding@132[8]...
2023-08-24T09:18:30Z D! [inputs.modbus] got holding@132[2]: [114 155 65 184]
2023-08-24T09:18:30Z D! [inputs.modbus]   field Working with offset 0 with len 4: [114 155 65 184] --> 23.055962
```

### System info

Telegraf 1.27.3

### Steps to reproduce

1. Configure any Modbus import for `FLOAT32` via register config_style
2. Get a completely wrong result back

### Expected behavior

get result as `FLOAT32`

e.g from logs: [114 155 65 184] --> 23.055962  

### Actual behavior

get your result [114 155 65 184]  interpreted as an `INT32` (=1.10261e+09) cast into `FLOAT32` for output

eg from logs: [114 155 65 184] --> 1.1026071132607005e+09

using the undocumented type `FLOAT32-IEEE` works as expected though... 

### Additional info

from `telegraf/plugins/inputs/modbus/configuration_register.go`
```go
func (c *ConfigurationOriginal) normalizeInputDatatype(dataType string, words int) (string, error) {
	// Handle our special types
	switch dataType {
	case "FIXED":
		switch words {
		case 1:
			return "INT16", nil
		case 2:
			return "INT32", nil
		case 4:
			return "INT64", nil
		default:
			return "unknown", fmt.Errorf("invalid length %d for type %q", words, dataType)
		}
	case "FLOAT32", "UFIXED":
		switch words {
		case 1:
			return "UINT16", nil
		case 2:
			return "UINT32", nil
		case 4:
			return "UINT64", nil
		default:
			return "unknown", fmt.Errorf("invalid length %d for type %q", words, dataType)
		}
	case "FLOAT16-IEEE":
		return "FLOAT16", nil
	case "FLOAT32-IEEE":
		return "FLOAT32", nil
	case "FLOAT64-IEEE":
		return "FLOAT64", nil
	}
	return normalizeInputDatatype(dataType)
}
```

`FLOAT32` gets changed here into `INT32` which is clearly unwanted. `FLOAT32-IEEE` in turn gets converted into `FLOAT32`

I'll prepare a PR for this
