### ISSUE TITLE
Cyclictest utility reports latency increase when telegraf is running with intel-powerstat plugin on preempt-rt kernel

### ISSUE THREAD

**Issue by alysondeives** [influxdata/telegraf#13828]
### Relevant telegraf.conf

```toml
[agent]
  collection_jitter = "0s"
  debug = false
  flush_interval = "10s"
  flush_jitter = "0s"
  hostname = "$HOSTNAME"
  interval = "10s"
  logfile = ""
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = false
  precision = ""
  quiet = false
  round_interval = true


[[outputs.prometheus_client]]
  listen = ":9273"


[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.linux_cpu]]
  metrics = ["cpufreq"]
  interval = "30s"
[[inputs.ipmi_sensor]]
  interval = "30s"
  timeout = "20s"
  metric_version = 1
  use_sudo = false
[[inputs.intel_powerstat]]
  cpu_metrics = ["cpu_frequency", "cpu_busy_frequency", "cpu_temperature", "cpu_c0_state_residency","cpu_c1_state_residency", "cpu_c6_state_residency", "cpu_busy_cycles"]
  package_metrics = ["current_power_consumption", "current_dram_power_consumption" ,"thermal_design_power", "cpu_base_frequency" ,"uncore_frequency"]
[[inputs.mem]]
```

### Logs from Telegraf

```text
This issue does not show any relevant information on logs
```

### System info

Telegraf 1.27.3, Debian 11, linux-yocto-rt kernel 5.10 with upstream patches

### Steps to reproduce

1. Use a preempt-rt kernel on a linux distribution
2. Install rt-tests package from your linux distribution (or compile it from source at https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git)
3. With the system on steady state, execute cyclictest utility from a long period of time (at least 6 hrs) and save latency output data for reference.
4. Start telegraf without intel-powerstat plugin enabled
5. Execute cyclictest utility and save latency output data
6. Start telegraf with intel-powerstat plugin enabled
7. Execute cyclictest utility and save latency output data

### Expected behavior

Latencies from telegraf execution with and without intel-powerstat plugin should not differ so much

### Actual behavior

There is a huge difference on latencies when telegraf is running with intel-powerstat plugin

### Additional info
Further investigation indicated this occurs because of the concurrent read of MSR with goroutines.
