### ISSUE TITLE
Agent Configuration issue in combination of setting logfile & logtarget in snmp input

### ISSUE THREAD

**Issue by fahad15o7** [influxdata/telegraf#13831]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  logfile = "/var/log/telegraf/telegraf.log"

# Retrieves SNMP values from remote agents
[[inputs.snmp]]
```

### Logs from Telegraf

```text
No logs are generated, once the config file is loaded, it crashes and telegraf stops.

Using "telegraf --config telegraf.conf --test 

Output ->  "2023-08-24T08:01:49Z I! Loading config: Telegraf.conf"
```

### System info

Telegraf v1.27.3 / 4 ,  CentOS

### Steps to reproduce

1. For the Agent configuration part set  logtarget = "file"
2. Provide the path logfile = "/path/to/logs"
3. Input plugin snmp 
4. Continue with relevant configuration fetching any OIDs lets say sysDesc.
5. Run telegraf with "telegraf --config telegraf.conf --test"  / "telegraf --config telegraf.conf"
...

### Expected behavior

The file should have run as expected and started with agent configuration, moving to the input snmp part and then finally the output.

### Actual behavior

The file crashes once loaded and doesnt reproduce any logs.

### Additional info

Additionally, with  `logtarget = "stderr"` and 
`logfile = "/path/to/log"` disabled the file runs as normal.
