### ISSUE TITLE
Ability to specify metric type (counter, gauge, etc.) for Prometheus client

### ISSUE THREAD

**Issue by eyJhb** [influxdata/telegraf#13844]
### Use Case

When the following flow is setup `mqtt -> json_v2 -> prometheus_client`, it would be ideal if a metric type (counter, etc.), could be specified as well as a description for the metric. So that when Prometheus scrapes the API, there is some more information.

### Expected behavior

An example of this could be 

```
# HELP home_sensors_powerplugs_energy Measured power in kWh
# TYPE home_sensors_powerplugs_energy counter
home_sensors_powerplugs_energy{host="servername",metric_type="counter",topic="test/sensors/powerplug-servers"} 3.09
```

### Actual behavior

Current output is

```
# HELP home_sensors_powerplugs_energy Telegraf collected metric
# TYPE home_sensors_powerplugs_energy untyped
home_sensors_powerplugs_energy{host="servername",metric_type="counter",topic="test/sensors/powerplug-servers"} 3.09
```

### Additional info

If this is already available, I am not seeing how. This is my current configuration file

```toml
[inputs.mqtt_consumer]
data_format = "json_v2"
password = "<nope>"
servers = ["tcp://127.0.0.1:1883"]
topics = ["test/sensors/+"]
username = "telegraf"

[[inputs.mqtt_consumer.json_v2]]
measurement_name = "home_sensors_powerplugs"
[[inputs.mqtt_consumer.json_v2.field]]
path = "energy"
type = "counter"

[inputs.mqtt_consumer.tagpass]
topic = ["*/powerplug-*"]

[outputs.prometheus_client]
listen = ":9273"
metric_version = 2
```

**Comment by srebhan** [comment]
This is similar to #13079. @eyJhb would it be an option to define the type(s) in the output e.g.

```toml
[outputs.prometheus_client]
  listen = ":9273"
  metric_version = 2
  gauges = ["home_sensors_powerplugs_energy", ...]
  counters = ["my_metric_errors", ...]
  ...
```

**Comment by eyJhb** [comment]
That would work yes. However, it seems like in this case, there is some translation between telegraf types, and Prometheus types. Would it maybe make sense, to have a middlelayer between input/output, which could define the metric type? I would have expected it to be in the json module.

**Comment by srebhan** [comment]
@eyJhb we could do this as a processor but this has the drawback that Telegraf cannot handle per-field metric types. They are always __per-metric__. Imagine you do have a metric with the fields `error_count` and `power_consumption`, you certainly want to be the `error_count` a `Counter` but the `power_consumption`  to be a `Gauge`... To do this you would need to split the metric first to one metric per field and then assign the types. 

Long story short, I think doing this as a processor either is very limited (to metrics with only a single field) or very complex (basically reproducing the [`split` processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/split) plus annotation)). As this requires some mapping to the output format as well, I think it would be best to do it really in the output.

For the existing logic or already annotated metrics, I propose to do check if the generated prometheus metric name is in any of the type annotations. If so apply the given type, otherwise use the current logic for typing.

Does that sound good?

**Comment by eyJhb** [comment]
I think it makes sense @srebhan. Maybe it would be nice if one could do glob matches in the counter, gauges, etc.? Also would it be possible to add any description while we're at it?


Also, I trust your judgement of what makes the most sense, since I've only used Telegraf for an entire 2 days, and still don't grasp all the concepts. I appreciate your detailed responses and quick replies :)

**Comment by srebhan** [comment]
@eyJhb please test the binary produced in PR #13874 and let me know if this fixes your issue!

**Comment by eyJhb** [comment]
Sorry, been away all weekend and no time to test. I'll test it when I find more time :) Thanks for the aid!

**Comment by ololobus** [comment]
@eyJhb @srebhan @powersj Can someone please hint on how to use this new `prometheus_metric_types`?

I use telegraf Helm chart and I try to set
```toml
    [[outputs.prometheus_client]]
      collectors_exclude = [
        "gocollector",
        "process"
      ]
      expiration_interval = "120s"
      listen = ":9273"
      metric_version = 2
      [outputs.prometheus_client.prometheus_metric_types]
        counter = [
            "metric_a"
        ]
        gauge = [
            "metric_b",
            "metric_c"
        ]
```
and getting
```
error loading config file /etc/telegraf/telegraf.conf: plugin outputs.prometheus_client: line 18: configuration specified the fields ["prometheus_metric_types"], but they weren't used
```

Helm chart version is `1.8.38`, telegraf `1.28.5`. Based on the release notes it should include this feature

Helm values part is
```yaml
config:
  outputs:
    - prometheus_client:
        listen: ":9273"
        metric_version: 2
        expiration_interval: "120s"
        collectors_exclude: ["gocollector", "process"]
        prometheus_metric_types:
          counter: ["metric_a"]
          gauge: ["metric_b", "metric_c"]
```
