### ISSUE TITLE
driver "sqlite" not supported

### ISSUE THREAD

**Issue by xtcw255** [influxdata/telegraf#13859]
### Relevant telegraf.conf

```toml
# # Read metrics from SQL queries
[[inputs.sql]]
#   ## Database Driver
#   ## See https://github.com/influxdata/telegraf/blob/master/docs/SQL_DRIVERS_INPUT.md for
#   ## a list of supported drivers.
driver = "sqlite"
#
```

### Logs from Telegraf

```text
2023-09-04T11:13:32Z E! [telegraf] Error running agent: could not initialize input inputs.sql: driver "sqlite" not supported use one of [clickhouse cockroach flightsql maria mssql mysql pgx pgx/v4 postgres snowflake sqlserver tidb]
```

### System info

Telegraf 1.27.4, Winserver 2019

### Steps to reproduce

1. Read https://github.com/influxdata/telegraf/blob/master/docs/SQL_DRIVERS_INPUT.md
2. Set driver to sqlite
3. Observe the error
...

### Expected behavior

Expect to not get an error about sqlite being unsupported

### Actual behavior

Get an error about it being unsupported
