### ISSUE TITLE
[outputs.sql] create table data-type BIGINT doubled in create statement

### ISSUE THREAD

**Issue by JSXRED** [influxdata/telegraf#13869]
### Relevant telegraf.conf

```toml
[[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[outputs.sql]]
  driver = "pgx"
  data_source_name = "postgres://telegraf:xxxx@[0000:0000:0000:0000:0000:0000:0000:0000]:5432/database"
  table_template = "CREATE TABLE {TABLE}({COLUMNS})"
[outputs.sql.convert]
    integer = "BIGINT"
    real = "REAL"
    text = "TEXT"
    timestamp = "TIMESTAMP"
    defaultvalue = "TEXT"
    unsigned = "BIGINT"
```

### Logs from Telegraf

```text
[agent] Error writing to outputs.sql: ERROR: syntax error at or near "BIGINT" (SQLSTATE 42601)
```

### System info

Telegraf 1.27.4; Debian 12; Postgresql15

### Steps to reproduce

1. Configure telegraf
2. Start service
3.
...

### Expected behavior

tables are created inside of postgresql

### Actual behavior

error is displayed

### Additional info

When you check last queries on pg_stat_activity you see:

`CREATE TABLE "disk"("timestamp" TIMESTAMP,"device" TEXT,"fstype" TEXT,"host" TEXT,"mode" TEXT,"path" TEXT,"free" BIGINT BIGINT,"used" BIGINT BIGINT,"used_percent" REAL,"inodes_total" BIGINT BIGINT,"inodes_free" BIGINT BIGINT,"inodes_used" BIGINT BIGINT,"total" BIGINT BIGINT);`

It's look like when he use bigint as data-type he duplicate it.
