### ISSUE TITLE
Processor plugin processors.regex.tags not transforming tags correctly in V1.27

### ISSUE THREAD

**Issue by PriD98** [influxdata/telegraf#13860]
### Relevant telegraf.conf

```toml
# # Transforms tag and field values as well as measurement, tag and field names with regex pattern
# [[processors.regex]]
#   namepass = ["nginx_requests"]
#
#   # Tag and field conversions defined in a separate sub-tables
#   [[processors.regex.tags]]
#     ## Tag to change, "*" will change every tag
#     key = "resp_code"
#     ## Regular expression to match on a tag value
#     pattern = "^(\\d)\\d\\d$"
#     ## Matches of the pattern will be replaced with this string.  Use ${1}
#     ## notation to use the text of the first submatch.
#     replacement = "${1}xx"
```

### Logs from Telegraf

```text
No logs - bug was found by running Telegraf and noticing unexpected output in dashboards.
```

### System info

Telegraf 1.27.0, Ubuntu 20.04.5 LTS, Docker 24.0.2

### Steps to reproduce

1. Run _telegraf --test_ on a telegraf.conf file using Telegraf v1.27
2. Look at any tags which are transformed using the regex.processor.plugin
3. Note that they are showing as 1}, 2} etc. where the number corresponds to the submatch you were referencing for replacement
4. Replace the line:
          replacement = "${1}xx"
    in your [[processors.regex.tags]] config with:
          replacement = "$1xx"
(i.e. drop the curly brackets around the submatch number)
5. Re-run _telegraf --test_
6. Check tags - they should now be correctly translated

### Expected behavior

resp_code = [first submatch]

i.e. based on above config, response code would be the value of: (\\d)

### Actual behavior

resp_code=1}

Fix: 
If you replace:

      replacement = "${1}xx"

with:

      replacement = "$1xx"

in the conf file, i.e. drop the curly brackets, translation works as expected.

**Comment by powersj** [comment]
> Telegraf 1.27.0

Please update to v1.27.4, I believe this was already fixed in v1.27.1, but it would be best to try the latest release.

**Comment by powersj** [comment]
Step to reproduce:

```
metric,tag=foo,resp_code=400 value=42
```

```toml
[agent]
  debug = true
  omit_hostname = true

[[outputs.file]]

[[inputs.file]]
  files = ['data']
  data_type = "influx"


[[processors.regex]]
  [[processors.regex.tags]]
    key = "resp_code"
    pattern = "^(\\d)\\d\\d$"
    replacement = "${1}xx"
```

produces:

v1.27.0

```
metric,resp_code=1}xx,tag=foo value=42 1693934924000000000
```

v1.27.1 and newer

```
metric,resp_code=4xx,tag=foo value=42 1693934931000000000
```
