### ISSUE TITLE
inputs.kafka_consumer: parser fails to process data

### ISSUE THREAD

**Issue by toanju** [influxdata/telegraf#13888]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]                                                                                                                              
  brokers = [                                                                                                                                          
    "YOUR_BROKER"                                                                                                                                      
  ]                                                                                                                                                    
  client_id = "client"                                                                                                                                 
  consumer_group = "group"                                                                                                                             
  topic_tag = "topic"                                                                                                                                  
  topics = [                                                                                                                                           
    "gnm-pm-metrics"                                                                                                                                   
  ]                                                                                                                                                    
  version = "2.0.0"                                                                                                                                    
                                                                                                                                                       
  data_format = "json_v2"                                                                                                                              
  [[inputs.kafka_consumer.json_v2]]                                                                                                                    
    measurement_name_path = "measurement_path"                                                                                                         
    timestamp_format = "unix_ms"                                                                                                                       
    timestamp_path = "timestamp"                                                                                                                       
    [[inputs.kafka_consumer.json_v2.field]]                                                                                                            
      optional = true                                                                                                                                  
      path = "metrics.m1"                                                                                                                              
      type = "uint"                                                                                                                                    
    [[inputs.kafka_consumer.json_v2.field]]                                                                                                            
      optional = true                                                                                                                                  
      path = "metrics.m2"                                                                                                                              
      type = "uint"                                                                                                                                    
    [[inputs.kafka_consumer.json_v2.tag]]                                                                                                              
      optional = true                                                                                                                                  
      path = "tag1"                                                                                                                                    
    [[inputs.kafka_consumer.json_v2.tag]]                                                                                                              
      optional = true                                                                                                                                  
      path = "tag2"                                                                                                                                    
                                                                                                                                                       
[[outputs.file]]                                                                                                                                       
  files = ["stdout"]                                                                                                                                   
  use_batch_format = true        
  prometheus_export_timestamp = true                                                                                                                      
  data_format = "prometheus"
```


### Logs from Telegraf

```text
see behaviour
```


### System info

dockerhub :latest

### Docker

_No response_

### Steps to reproduce

1. Stream JSON data via Kafka having a format like

```json
{                                                                                                                                                      
        "tag1": "asdf",                                                                                                                                
        "tag2": "qwer",                                                                                                                                
        "metrics": {                                                                                                                                   
                "m1": 0,                                                                                                                               
                "m2": 2                                                                                                                                
        },                                                                                                                                             
        "measurement_path": "some_name",                                                                                                               
        "timestamp": 1693991509359                                                                                                                     
}  
```

3. 
4.
...


### Expected behavior

outputs like

```
some_name_m1{host="hostname",tag1="asdf",tag2="qwer"} 0 1693991509000
some_name_m2{host="hostname",tag1="asdf",tag2="qwer"} 2 1693991509000
```

### Actual behavior

Kafka consumer groups seem to work in parallel and the Parse() function is called from multiple callers at the same time that the output is like

```
some_name_m1{host="hostname",tag1="asdf",tag2="qwer"} 0 1693991509000
some_name_m2{host="hostname",tag1="asdf",tag2="qwer"} 2 1693991509000
some_nm2{host="hostname",tag1="asdf",tag2="qwer"} 2 1693991509000
some_name_m1{host="hostname",tag1="asdf",tag2="qwer"} 2 1693991509000
kafka_consumer_m1{host="hostname",tag1="asdf",tag2="qwer"} 2 1693991509000

```

### Additional info

_No response_
