### ISSUE TITLE
Redis input plugin misspelled input parameter for password on telegraf 1.28.0

### ISSUE THREAD

**Issue by campbelljlowman** [influxdata/telegraf#13908]
### Relevant telegraf.conf

```toml
[[inputs.redis]]
    ## specify servers via a url matching:
    ##  [protocol://][:password]@address[:port]
    ##  e.g.
    ##    tcp://localhost:6379
    ##    tcp://:password@192.168.99.100
    ##
    ## If no servers are specified, then localhost is used as the host.
    password = "${REDIS_PASSWORD}"
```

### Logs from Telegraf

```text
2023-09-12T06:21:37Z I! Loading config: /etc/vmware/telegraf.conf
2023-09-12T06:21:37Z E! error loading config file /etc/vmware/telegraf/telegraf.d/redis.telegraf.conf: plugin inputs.redis: line 4: configuration specified the fields ["password"], but they weren't used
```

### System info

telegraf 1.28.0

### Steps to reproduce

Deploy Redis input plugin with documented configuration on new telegraf version 1.28.0

### Expected behavior

I expect our old configuration to work with the new version of telegraf

### Actual behavior

After upgrading to telegraf version 1.28.0, we get the above error when deploying

### Additional info

Believe the issue is because of this change merged yesterday: https://github.com/influxdata/telegraf/pull/13864/files#diff-93b1ae5dc306e310ee12e6cb293849e9847f8b39aa458ddf119604bca289a154R38

I verified that if I change the `password` configuration parameter to `passowrd` the input plugin starts successfully. Should be a simple fix
