### ISSUE TITLE
Outputs.Stackdriver `tags_as_resource_labels` config option doesn't appear to be working as expected

### ISSUE THREAD

**Issue by crflanigan** [influxdata/telegraf#13911]
### Relevant telegraf.conf

```toml
## Relevant Agent Configuration

[inputs.mem]
  [inputs.mem.tags]
    job = "inputs.mem"

[inputs.processes]
  [inputs.processes.tags]
    job = "inputs.processes"

[[outputs.opentelemetry]]
  service_address = "server:4317"


## Relevant Server Config
## Server (Values that are {{}} are hydrated by a key value store when
## Telegraf is deployed):

[global_tags]

# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 199
  metric_buffer_limit = {{.METRIC_BUFFER}}
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = {{.DEBUG}}
  quiet = false

# Receive OpenTelemetry traces, metrics, and logs over gRPC
[[inputs.opentelemetry]]
  ## Override the default (0.0.0.0:4317) destination OpenTelemetry gRPC service
  ## address:port
  service_address = "0.0.0.0:4317"

[[processors.regex]]
  # Rename metric names (measurement names) that don't match Prometheus requirements
  [[processors.regex.metric_rename]]
    pattern = "[^a-zA-Z0-9_]+"
    replacement = "_"

  # Rename tag keys that don't match Prometheus requirements
  [[processors.regex.tag_rename]]
    pattern = "[^a-zA-Z0-9_]+"
    replacement = "_"

  # Rename field keys that don't match Prometheus requirements
  [[processors.regex.field_rename]]
    pattern = "[^a-zA-Z0-9_]+"
    replacement = "_"

    # Configuration for sending metrics to GMP
[[outputs.stackdriver]]
  project = "{{.PROJECT_ID}}"
  resource_type = "prometheus_target"
  metric_name_format = "official"
  metric_data_type = "double"
  metric_type_prefix = "prometheus.googleapis.com"
  tags_as_resource_label = ["instance", "job"]
  # Ignore metrics from inputs.internal
  namedrop = ["internal_*"]
  [outputs.stackdriver.resource_labels]
    cluster = "{{.CLUSTER_NAME}}"
    job = "Telegraf"
    instance = "{{.CLUSTER_NAME}}"
    location = "{{.LOCATION}}"
    namespace = "{{.NAMESPACE_LABEL}}"
```

### Logs from Telegraf

The logs are unremarkable, but when outputting what the agent is sending to outputs.stackdriver using outputs.file I see that the tags are set correctly. 

Example:
Memory metric has `job=inputs.mem`
Processes metric has `job=inputs.processes`

```
mem,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.mem active=965160960i,available=1003286528i,used_percent=94.1601037979126,available_percent=5.839896202087402,inactive=954462208i,wired=693956608i,total=17179869184i,used=16176582656i,free=48824320i 1694460660000000000
processes,env=Production_MacOS,host=hostname,instance=hostname,job=inputs.processes blocked=0i,zombies=1i,stopped=0i,running=3i,sleeping=428i,total=432i,unknown=0i,idle=0i 1694460660000000000
```

But when I look at the metrics in Google or Grafana I notice that it looks like the metrics are sometimes tagged with another inputs tag, IE `job=inputs.mem` but for a processes metric. From what I can tell it's usually the busiest metric. Additionally, it appears to be the last metric's `tag` that is sent is the one that is used for all the entire batch of metrics. Including metrics that don't contain a job `tag`. Meaning that the default value isn't applied, instead whatever the last value for the `tag` is used.

```
### System info

1.27.4

### Docker

_No response_
```

### Steps to reproduce

1. Send metrics from a Telegraf client with a tag called job configured for each input plugin to a Telegraf server
2. Configure the Telegraf server such that it uses `tags_as_resource_labels` for `job` tag.
3. Send metrics to Google
...

### Expected behavior

Each metric will have their job tag (or any other applicable tag) applied as a resource label. 

### Actual behavior

The tag appears to change depending on what the last tag was sent. As you can see in the screenshot the job tag changed between `inputs.mem` and `inputs.processes`, even though the sending agent didn't change. Here's an example of it changing applying a mismatched `job` label on two different inputs:

<img width="1091" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/6662ff7a-960f-4705-a2b1-376b641bd4bf">

![image](https://github.com/influxdata/telegraf/assets/69858641/96158186-37f3-4fea-b2c7-1fb778b14c31)

What also seems weird is that you can stop sending a tag altogether and the last sent tag is what continues to be sent instead of the default value:

```
[inputs.mem]
  # [inputs.mem.tags]
  #   job = "inputs.mem"

[inputs.processes]
  # [inputs.processes.tags]
  #   job = "inputs.processes"
  ```

Telegraf Client `outputs.file` output showing no `job` tag:

```
mem,env=Production_MacOS,host=hostname,instance=hostname total=17179869184i,available_percent=5.273199081420898,active=885673984i,free=24256512i,wired=659767296i,available=905928704i,used=16273940480i,used_percent=94.7268009185791,inactive=881672192i 1694532100000000000
```  
  
<img width="847" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/ef1eb2b2-fe97-4b9a-9315-86c10c06ff08">

**Comment by crflanigan** [comment]
@powersj 
Created per your request.

**Comment by crflanigan** [comment]
FWIW I duplicated this behavior on a standard Ubuntu server as well, in addition to our Kubernetes Telegraf deployment.

**Comment by crflanigan** [comment]
Thanks!

**Comment by crflanigan** [comment]
Ok, 

I think I see the logs you're looking for:

```
Creating timeseries:
mem_active map[env:Production_MacOS host:hostname] map[gauge:1370566656] 1694536580000000000
metric labels: map[env:Production_MacOS host:hostname]
resource labels: map[cluster:onprem instance:hostname job:inputs.mem location:us-east1-b namespace:store_pc_metrics project_id:io1-sandbox]
```
This looks right, but when I look at the metric in Google I see the `job` resource label as `inputs.disk`:

<img width="1082" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/c2b8caf8-85a3-4d8e-a662-43ccc1797dc7">

**Comment by powersj** [comment]
That does look right from telegraf. Is this something you could ask Google? Happy to work through this further, but I'm not sure what else to look at given the labels do look right.

**Comment by crflanigan** [comment]
I sure can! Is there any reason why this time series would have its label changed as it's being sent?

**Comment by crflanigan** [comment]
From Google:

```
The only things I can think of are either 1. Telegraf logging isn't correct, and it's sending the wrong label to us (maybe you can check by using Wireshark or something) or 2. it's sending a different metric name when you mutate job, so your query isn't retrieving the right data or 3. the new data is being rejected for some unrelated reason, causing it to not make it into our system at all. Kinda just stabs in the dark...
```

**Comment by crflanigan** [comment]
One other thing that I should emphasize is that once a tag comes through which sets the `tag_as_resource_label` setting (like job), even if I stop the Telegraf client and send without the job tag, the resource label is still showing in Google with whatever it was set as last (job="inputs.disk").

**Comment by powersj** [comment]
> even if I stop the Telegraf client and send without the job tag, the resource label is still showing in Google with whatever it was set as last (job="inputs.disk").

Doesn't that eliminate telegraf as the cause?

Out of his options I would second the wireshark if we really do think it is a telegraf issue.

**Comment by crflanigan** [comment]
>Doesn't that eliminate telegraf as the cause?

I mean, not sure. The problem resolves if I restart the agent. It almost seems like when sending it is set to whatever it was set to last. 

> Out of his options I would second the wireshark if we really do think it is a telegraf issue.

I agree, just not sure how to decrypt the traffic since this is sending to Google. Would be lovely to output the data stream to a file instead of to Google or something.

**Comment by crflanigan** [comment]
Seeing if I can get some logging from Google of what we're sending.

**Comment by powersj** [comment]
I pushed some additional logging right before we send the request. The only thing I would wonder is if something is getting mixed up during the request creation.

**Comment by crflanigan** [comment]
Hi @powersj,

Here's the response from Google:

I'm seeing the following in the logs:

prometheus.googleapis.com/mem_available_gauge/gauge 
io1-sandbox
us-east1-b
onprem
store_pc_metrics
inputs.processes
HOSTNAME REDACTED

I'm also seeing
io1-sandbox
us-east1-b
onprem
store_pc_metrics
inputs.mem
HOSTNAME REDACTED

and 

io1-sandbox
us-east1-b
onprem
store_pc_metrics
inputs.disk
HOSTNAME REDACTED

So it looks like all 3 values are making it in... however I can't really reconstruct any time series through the logs so all I can really say is that over the last few days we have seen all 3 values.

It does look like you can see all 3 values in Metrics Explorer as well. inputs.processes and inputs.mem are only transiently seen, however - the most recent data is for inputs.disk:

![image](https://github.com/influxdata/telegraf/assets/69858641/9a582b0f-7aaf-4b55-a570-8538234d8dcb)

**Comment by crflanigan** [comment]
> I pushed some additional logging right before we send the request. The only thing I would wonder is if something is getting mixed up during the request creation.

Sure, I can test it!

**Comment by crflanigan** [comment]
Looks like something happened with a test in the GitOps.

<img width="937" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/74c151cd-45d0-46fb-bdd5-3067b946e8f4">

**Comment by crflanigan** [comment]
Ok, I tested it. 

There's a lot of new lines that look like this:

metric: type:"prometheus.googleapis.com/disk_used_percent_gauge/gauge"  labels:{key:"device"  value:"disk3s6"}  labels:{key:"env"  value:"Production_MacOS"}  labels:{key:"fstype"  value:"apfs"}  labels:{key:"host"  value:"hostname"}  labels:{key:"mode"  value:"rw"}  labels:{key:"path"  value:"/System/Volumes/VM"}
points: [interval:{end_time:{seconds:1694630580}}  value:{double_value:29.258641050723256}]

Is that what you wanted?
Did you want me to email you the log file, if so, how long did you want me to let the agent run?

**Comment by crflanigan** [comment]
Hi @powersj,

When I looked at the logging I actually didn't see any of the tags represented (as shown above). 

One thing to keep in mind though is that if I send two metrics with different job tags, whatever the last metric that was sent will be the job tag for both. Additionally, if disable the job tag for one of the input plugins (comment it out), while the other one is still active, the metric without a job tag defined will get the job label for the other metric. On top of that, if you disable the job tag from both plugins, it still persists in sending the last defined tag (in this case inputs.disk). Example:

```
# Note that inputs.disk generates far more metrics than inputs.mem and will have more job tags
[inputs.disk]
  [inputs.disk.tags]
      job = "inputs.disk"

[inputs.mem] 
  [inputs.mem.tags]
      job = "inputs.mem"
```
Note: The inputs.disk and inputs.mem values in the attached images are the values for the job resource label:

<img width="344" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/d94f2a0f-b8bb-4304-be77-7536e31c522f">

<img width="802" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/70f331b0-231c-45b4-83dd-69ec0cc51337">


As you can see, there's the correct label for inputs.mem, because it worked correctly once, but then the more aggressive inputs.disk metric came and took presidence. 

After that I went ahead and disabled the job tag for inputs.mem:

```
[inputs.disk]
  [inputs.disk.tags]
      job = "inputs.disk"

[inputs.mem] 
  #[inputs.mem.tags]
      #job = "inputs.mem"
```

And even still the job label was applied to the inputs.mem metric:

<img width="1290" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/608882a1-0135-49b2-9d01-166e20c1d5f5">

Then I go ahead and remove the job label from both metrics and still the job label persists. Here's the outputs.file metric before it's sent to the Telegraf proxy (outputs.stackdriver) server (note no job label):

```
disk,device=disk3s5,env=Production_MacOS,fstype=apfs,host=host,instance=host,mode=rw,path=/System/Volumes/Data total=494384795648i,free=358247702528i,used=136137093120i,used_percent=27.536666644766534,inodes_total=3500345821i,inodes_free=3498512720i,inodes_used=1833101i 1695658020000000000
mem,env=Production_MacOS,host=host,instance=host available=827138048i,used=16352731136i,active=822763520i,wired=989003776i,total=17179869184i,used_percent=95.18542289733887,available_percent=4.814577102661133,free=7979008i,inactive=819159040i 1695658020000000000
```


<img width="1569" alt="image" src="https://github.com/influxdata/telegraf/assets/69858641/5557c812-13b3-40d3-8df7-6eb6762a8cf8">


Does that help?

**Comment by powersj** [comment]
> Does that help?

Unfortunately, I am not following. Let's look back and the code and make sure my understanding is correct:

Resource labels are [generated at each metric](https://github.com/influxdata/telegraf/blob/master/plugins/outputs/stackdriver/stackdriver.go#L226-L232), however there is another place where it is set initially via the `resource_label` config option. You have the following:

```toml
  [outputs.stackdriver.resource_labels]
    cluster = "{{.CLUSTER_NAME}}"
    job = "Telegraf"
    instance = "{{.CLUSTER_NAME}}"
    location = "{{.LOCATION}}"
    namespace = "{{.NAMESPACE_LABEL}}"
```

This means that all metrics should get the above resource labels no matter what. You also have the following `tags_as_resource_labels` set:

```toml
  tags_as_resource_label = ["instance", "job"]
```

Which means if we come across a metric with a tag called `instance` or `job` we will set these resource labels as well and remove them from metric labels.

There is no sharing between metrics beyond what `s.ResourceLabels` is set to in your config. Once created, the time series is not modified in anyway either by Telegraf.

Can you please share your metrics explorer query. Are you sure you aren't grouping by job?
