### ISSUE TITLE
JTI input plugin stopped working after upgrade to 1.28.1

### ISSUE THREAD

**Issue by rapik0088** [influxdata/telegraf#13917]
### Relevant telegraf.conf

```toml
[global_tags]
[agent]
  interval = "8s"
  round_interval = false
  metric_batch_size = 10000
  metric_buffer_limit = 1000000
  collection_jitter = "0s"
  collection_offset = "0s"
  flush_interval = "8s"
  flush_jitter = "0s"
  precision = "1ms"
  omit_hostname = false

[[inputs.jti_openconfig_telemetry]]
   servers = [ "cut" ]

   sensors = [  "8000ms /junos/system/linecard/interface/logical/usage/",
                "8000ms /junos/system/linecard/interface/traffic/",
                "30000ms /junos/system/linecard/interface/queue/",
                "30000ms /junos/twamp/client/probe-test-results/",
                "30000ms /interfaces/"]
timestamp_source = "data"


[[outputs.influxdb]]
   urls = ["cut"]
   database = "telegraf"

[[processors.rename]]
[[processors.rename.replace]]
   tag = "/interfaces/interface/@name"
   dest = "interface_name"
[[processors.rename.replace]]
   tag = "/interfaces/interface/subinterfaces/subinterface/@index"
   dest = "subinterface_index"

[[processors.converter]]
  [processors.converter.fields]
    tag = [ "/interfaces/interface/state/parent-ae-name", "/interfaces/interface/subinterfaces/subinterface/state/parent-ae-name" ]
  [processors.converter.tags]
     string = [ "path" ]
```

### Logs from Telegraf

```text
no errors in logs
```

### System info

telegraf 1.28.1, Ubuntu 22.04

### Steps to reproduce

just install 1.28.1 and restart

### Expected behavior

expected it to be run

### Actual behavior

no any packets observed with tcpdump toward jti targets.
