### ISSUE TITLE
Generate parsing error for smart field value "<not available>"

### ISSUE THREAD

**Issue by sdalu** [influxdata/telegraf#13926]
### Relevant telegraf.conf

```toml
[[inputs.smart]]
  path_smartctl		= "/usr/local/sbin/smartctl"
  use_sudo		= true
  nocheck		= "standby"
  tagexclude		= [ "capacity", "enabled" ]
```

### Logs from Telegraf

```text
2023-09-14T18:07:40Z E! [inputs.smart] Error in plugin: error parsing Temperature_Celsius: "<not available>": expected integer
```

### System info

Telegraf 1.28.0 FreeBSD

### Steps to reproduce

1. run the configuration

### Expected behavior

Don't generate error on Temperature_Celsius with value `<not available>`, just ignore it

### Actual behavior

Error in log file
