### ISSUE TITLE
Mock plugin not aligned with documentation

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#13950]
### Relevant telegraf.conf

```toml
# Generate metrics for test and demonstration purposes
[[inputs.mock]]
  ## Set the metric name to use for reporting
  metric_name = "mock"

  [[inputs.mock.step]]
    name = "plus_one"
    start = 0.0
    step = 1.0
```

### Logs from Telegraf

```text
E! error loading config file telegraf.conf: plugin inputs.mock: line 2: configuration specified the fields ["start" "step"], but they weren't used
```

### System info

Telegraf 1.27.3 (git: HEAD@afcf0133)

### Steps to reproduce

1. `telegraf --test`

### Expected behavior

Telegraf to work with the config parameters as explained in the docs.

### Actual behavior

Telegraf stops with the mentioned error.
