### ISSUE TITLE
intel_pmt input plugin fails initialization looking for numa_node in sysfs

### ISSUE THREAD

**Issue by bensallen** [influxdata/telegraf#13976]
### Relevant telegraf.conf

```toml
[[inputs.intel_pmt]]
  ## Filepath to PMT XML within local copies of XML files from PMT repository.
  ## The filepath should be absolute.
  spec = "/etc/telegraf/Intel-PMT/xml/pmt.xml"

  ## Enable metrics by their datatype.
  ## See the Enabling Metrics section in README for more details.
  ## If empty, all metrics are enabled.
  ## When used, the alternative option samples_enabled should NOT be used.
  # datatypes_enabled = []

  ## Enable metrics by their name.
  ## See the Enabling Metrics section in README for more details.
  ## If empty, all metrics are enabled.
  ## When used, the alternative option datatypes_enabled should NOT be used.
  # samples_enabled = []
```

### Logs from Telegraf

```text
telegraf[47878]: 2023-09-21T22:27:09Z E! [telegraf] Error running agent: could not initialize input inputs.intel_pmt: error while exploring pmt sysfs: error while evaluating symlink "/sys/class/intel_pmt/telem0/numa_node": lstat /sys/devices/pci0000:00/0000:00:0a.0/intel_vsec.telemetry.0/intel_pmt/telem0/numa_node: no such file or directory
```

### System info

Telegraf v1.28.1, Fedora 38 / OpenSuse 15.4

### Steps to reproduce

Enable the intel_pmt input plugin and start telegraf.

### Expected behavior

Telegraf starts and produces metrics from intel_pmt devices.

### Actual behavior

Telegraf fails to start due to attempting to find a numa_node attribute in sysfs in intel_pmt devices, which do not have that attribute.
