### ISSUE TITLE
Inconsistent metric emitting with `final` aggregator

### ISSUE THREAD

**Issue by rplevka** [influxdata/telegraf#13981]
### Relevant telegraf.conf

```toml
[agent]
  interval = "5s"
  flush_interval = "1s"
  omit_hostname = true
​
​
# Generate metrics for test and demonstration purposes
[[inputs.mock]]
  ## Set the metric name to use for reporting
  metric_name = "mock"
​
  [[inputs.mock.step]]
    name = "plus_one"
    min = 0.0
    max = 1.0
​
# Report the final metric of a series
[[aggregators.final]]
  ## The period on which to flush & clear the aggregator.
  period = "15s"
  ## If true, the original metric will be dropped by the
  ## aggregator and will not get sent to the output plugins.
  drop_original = false
​
  ## The time that a series is not updated until considering it final.
  series_timeout = "1s"
​
[[outputs.file]]
	files = ["stdout"]
```

### Logs from Telegraf

```text
2023-09-19T09:26:25Z I! [agent] Config: Interval:5s, Quiet:false, Hostname:"", Flush Interval:1s
mock plus_one=0 1695115590000000000
mock plus_one=1 1695115595000000000
mock plus_one=2 1695115600000000000
mock plus_one_final=2 1695115600000000000
mock plus_one=3 1695115605000000000
mock plus_one=4 1695115610000000000
mock plus_one=5 1695115615000000000
mock plus_one=6 1695115620000000000
mock plus_one=7 1695115625000000000
mock plus_one=8 1695115630000000000
mock plus_one_final=8 1695115630000000000
mock plus_one=9 1695115635000000000
mock plus_one=10 1695115640000000000
mock plus_one=11 1695115645000000000
mock plus_one_final=11 1695115645000000000
mock plus_one=12 1695115650000000000
mock plus_one=13 1695115655000000000
mock plus_one=14 1695115660000000000
mock plus_one_final=14 1695115660000000000
mock plus_one=15 1695115665000000000
mock plus_one=16 1695115670000000000
mock plus_one=17 1695115675000000000
mock plus_one_final=17 1695115675000000000
mock plus_one=18 1695115680000000000
mock plus_one=19 1695115685000000000
mock plus_one=20 1695115690000000000
mock plus_one=21 1695115695000000000
mock plus_one=22 1695115700000000000
mock plus_one=23 1695115705000000000
mock plus_one_final=23 1695115705000000000
```

### System info

Telegraf v1.28.1

### Steps to reproduce

1. just apply the config and run
...

### Expected behavior

since `period = "15s"` and `series_timeout = "1s"` is used in the aggregator,
I'd expect to see ` _final` metric emitted for every 15 seconds.

### Actual behavior

the `_final` metrics are emitted in inconsistent intervals.

### Additional info

raised and discussed in [this](https://influxcommunity.slack.com/archives/CH99HUH8V/p1695115869397799) slack thread
