### ISSUE TITLE
Telegraf prometheus_client output is not exposing multiple time series samples for a particular metric

### ISSUE THREAD

**Issue by srinivas974** [influxdata/telegraf#14002]
### Relevant telegraf.conf

```toml
[agent]
  interval = "30s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "10s"
  flush_jitter = "5s"
  precision = "1s"
...
[[inputs.exec]]
  commands = ["/etc/telegraf/scripts/monitoring.py"]
  data_format = "prometheus"
  interval = "15m"
  timeout = "5m"
...
[[outputs.prometheus_client]]
  listen = "10.10.20.112:9126"
  expiration_interval = "10m"
  collectors_exclude = ["gocollector", "process"]
  string_as_label = true
  export_timestamp = true
  metric_version = 1
```

### Logs from Telegraf

```text
Script Output:

deviceCPU{region="na",Version="1.3.5.18"} 52.6666666667 1695286260000
deviceCPU{region="na",Version="1.3.5.18"} 16.5 1695286320000
deviceCPU{region="na",Version="1.3.5.18"} 35.3333333333 1695286380000
deviceCPU{region="na",Version="1.3.5.18"} 52.6666666667 1695286440000
deviceCPU{region="na",Version="1.3.5.18"} 17.0 1695286500000
deviceCPU{region="na",Version="1.3.5.18"} 32.4545454545 1695286560000
deviceCPU{region="na",Version="1.3.5.18"} 46.3333333333 1695286620000
deviceCPU{region="na",Version="1.3.5.18"} 17.0 1695286680000
deviceCPU{region="na",Version="1.3.5.18"} 32.4545454545 1695286740000
deviceCPU{region="na",Version="1.3.5.18"} 47.3333333333 1695286800000
deviceCPU{region="na",Version="1.3.5.18"} 21.0 1695286860000

Metrics
```

### System info

Telegraf 1.26.0, Linux OS 

### Steps to reproduce

We can echo the above samples from input plugin.

Example:
[[inputs.exec]]
  commands = ["/usr/bin/echo -e deviceCPU{region=\\\"na\\\",FwVersion=\\\"1.3.5.18\\\"} 51\\\\ndeviceCPU{region=\\\"na\\\",Version=\\\"1.3.5.18\\\"} 54"]
  data_format = "prometheus"
  interval = "15m"
  timeout = "5m"

### Expected behavior

We would like to see all data exported to the metrics endpoint.

prometheus /etc/telegraf/scripts # curl -s 10.10.20.112:9126/metrics |grep -i "deviceCPU"
\# HELP deviceCPU Telegraf collected metric
\# TYPE deviceCPU untyped
deviceCPU{region="na",Version="1.3.5.18"} 52.6666666667 1695286260000
deviceCPU{region="na",Version="1.3.5.18"} 16.5 1695286320000
deviceCPU{region="na",Version="1.3.5.18"} 35.3333333333 1695286380000
deviceCPU{region="na",Version="1.3.5.18"} 52.6666666667 1695286440000
deviceCPU{region="na",Version="1.3.5.18"} 17.0 1695286500000
deviceCPU{region="na",Version="1.3.5.18"} 32.4545454545 1695286560000
deviceCPU{region="na",Version="1.3.5.18"} 46.3333333333 1695286620000
deviceCPU{region="na",Version="1.3.5.18"} 17.0 1695286680000
deviceCPU{region="na",Version="1.3.5.18"} 32.4545454545 1695286740000
deviceCPU{region="na",Version="1.3.5.18"} 47.3333333333 1695286800000
deviceCPU{region="na",Version="1.3.5.18"} 21.0 1695286860000

### Actual behavior

Only one data sample exported to metrics endpoint.

prometheus /etc/telegraf/scripts # curl -s 10.10.20.112:9126/metrics |grep -i "deviceCPU"
\# HELP deviceCPU Telegraf collected metric
\# TYPE deviceCPU untyped
deviceCPU{region="na",Version="1.3.5.18"} 21.0 1695286860000

### Additional info

We cannot see all the data samples produced by the script output for specific metric in the exported output endpoint. In any case, we are seeing only one data point. 

If this is a restriction by the Prometheus client output plugin, Could you guys provide us with another alternative to resolve the issue?
