### ISSUE TITLE
rhel8-rpm: Broken permission 

### ISSUE THREAD

**Issue by genofire** [influxdata/telegraf#14019]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  logfile = "/var/log/telegraf/telegraf.log"
  logfile_rotation_interval = "24h"
  logfile_rotation_max_size = "100MB"
  logfile_rotation_max_archives = 2
  quiet = true
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = "0.0.0.0:9270"
  path = "/metrics/"
  metric_version = 2           # sonst Warnung im Logfile

# Read metrics about cpu usage
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = false

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]
  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
```

### Logs from Telegraf

```text
does not matter
```

### System info

rhel8

### Steps to reproduce

1. Install
2. Start

### Expected behavior

1. Install
  - /var/log/telegraf created with permission of user:group : telegraf:telegraf
  - telegraf.service use telegraf user
2. Start
3. running

### Actual behavior

1. Install
  - /var/log/telegraf created with permission of user root:root
  - telegraf.service use telegraf user
2. start
3. failed, because it has no permission to write 

### Additional info

```
# rpm -qp --dump telegraf-1.28.1-1.x86_64.rpm 
/etc/logrotate.d/telegraf 131 1694532127 9ab14f18106cb6f1bd55733eea61d7ab5242691defa17aec275bb2a26fe26955 0100644 root root 1 0 0 X
/etc/telegraf/telegraf.conf 497518 1694532127 c10f04d852e349a679290f4987cad0a1ad8e764f1f3b26adb65af23506f10c3a 0100644 root root 1 0 0 X
/etc/telegraf/telegraf.d/.ignore 97 1694532127 1c72cadef1352129f026d6bdb749c9b91e1dec97056339a1d553214aacc0c70a 0100644 root root 1 0 0 X
/usr/bin/telegraf 197279744 1694532127 ac9e1ce28391e2369b767d414a96f201d8407b6b38b40f66c9e0b03d058be318 0100755 root root 0 0 0 X
/usr/lib/telegraf/scripts/init.sh 5803 1694532127 46098761230fb7850ae97b4d1134a782d80633bd14eaf94582539338738a7345 0100755 root root 0 0 0 X
/usr/lib/telegraf/scripts/telegraf.service 509 1694532127 a941ff3e6d63bcf72340d85ea7ac104dd41f3d4a100eb0e0ed0739add660775d 0100644 root root 0 0 0 X
/var/log/telegraf 0 1694532127 0000000000000000000000000000000000000000000000000000000000000000 040755 root root 0 0 0 X
```
