### ISSUE TITLE
processor.regex mixing non capture groups and named capture groups gives incorrect result

### ISSUE THREAD

**Issue by richardeaxon** [influxdata/telegraf#14028]
### Relevant telegraf.conf

```toml
[[processors.regex]]
  order = 20
  namepass = ["arista"]
  metricpass = "fields.process == 'Bgp'"

  [[processors.regex.fields]]
    # extract peer
    key = "message"
    #pattern = '.*(peer|neighbor) (?P<ip_addr>\d+\.\d+\.\d+\.\d+).*'     # this does not work
    pattern = '.*neighbor (?P<ip_addr>\d+\.\d+\.\d+\.\d+).*'    # this works
```

### Logs from Telegraf

```text
N/A
```

### System info

Telegraf nightly build

### Steps to reproduce

Using nightly build to test https://github.com/influxdata/telegraf/pull/13971 I get unexpected results when mixing non capture and named capture groups.

Using this input line:

received from neighbor 1.1.1.1 (VRF default AS 4200099061) 6/5 (Cease/connection rejected) 0 bytes

And telegraf.conf using regex pattern '.*(peer|neighbor) (?P<ip_addr>\d+\.\d+\.\d+\.\d+).*' is get this:

arista process="Bgp",event="BGP-3-NOTIFICATION",message="",source="lab" 1696045222031424000

The message is replaced with "". Note the above regex works correctly in regex101 tester.

### Expected behavior

Should result in:

arista source="lab",process="Bgp",event="BGP-3-NOTIFICATION",message="received from neighbor 1.1.1.1 (VRF default AS 4200099061) 6/5 (Cease/connection rejected) 0 bytes",ip_addr="1.1.1.1",vrf="default",resource_index="4200099061" 1696045740257530000

### Actual behavior

Orignal source field is replaced with "".

### Additional info

Possibly an additional code check is required to check if the 'replacement = ' config option is defined. If not, assume named capture groups used and don't fall through into replacement mode with empty key.
