### ISSUE TITLE
GNMI / Got empty metric-name for response / 

### ISSUE THREAD

**Issue by jorisd** [influxdata/telegraf#14044]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
  addresses = ['${addresses}']
  username = "xxx"
  password = "xxx"
  redial = "60s"
  encoding = "json_ietf"
  [[inputs.gnmi.subscription]]
    name = "ifdesc"
    origin = "openconfig-interfaces"
    path = '/interfaces/interface[name=FourHundredGigE*]/state/description'
    subscription_mode = "sample"
    sample_interval = "60s"
  [[inputs.gnmi.subscription]]
    name = "temperature"
    origin = "openconfig-platform"
    path = '/components/component[name=FourHundredGigE*]/state/temperature/avg'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-lanes"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-lanes/optics-lane'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-info"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-info'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name="Cisco-controller-otu"
    origin = "Cisco-IOS-XR-controller-otu-oper"
    path = '/otu/controllers/controller[controller-name=CoherentDSP0/2/0/*]/info'
    subscription_mode = "target_defined"
```

### Logs from Telegraf

```text
023-10-03T09:08:02Z D! [inputs.gnmi] Connection to gNMI device 10.44.250.93:12346 established
2023-10-03T09:08:02Z W! [inputs.gnmi] Got empty metric-name for response, usually indicating
configuration issues as the response cannot be related to any subscription.
Please open an issue on https://github.com/influxdata/telegraf including your
device model and the following response data:
timestamp:1696324083211000000 prefix:{origin:"openconfig-interfaces"} update:{path:{elem:{name:"interfaces"} elem:{name:"interface" key:{key:"name" value:"FourHundredGigE0/2/0/3"}} elem:{name:"state"}} val:{json_ietf_val:"{\"description\":\"REDACTED \"}"}}
This message is only printed once.
```

### System info

Telegraf 1.28.1 / Cisco ASR 9922

### Steps to reproduce

1. Regroup all subscription under 1 input
2. Telegraf will start but will emit the initial error message and "Could not serialize metric: invalid name" 

### Expected behavior

Telegraf doesn't create any error and we expect to get the desired data from the openconfig-interfaces. 

### Actual behavior

Telegraf display an error at startup, and we don't get the desired data from the openconfig-interfaces. 
Moreover, we get lots of errors like this :
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name
2023-10-03T09:08:09Z D! [outputs.file] Could not serialize metric: invalid name

### Additional info

The workaround we use is define 2 inputs gnmi like this :
```
[[inputs.gnmi]]
  addresses = [${addresses}]
  username = "xxx"
  password = "xxx"
  redial = "60s"
  encoding = "json_ietf"
  name_override = "Cisco"
  [[inputs.gnmi.subscription]]
    name = "ifdesc"
    origin = "openconfig-interfaces"
    path = '/interfaces/interface[name=FourHundredGigE*]/state/description'
    subscription_mode = "sample"
    sample_interval = "60s"
  [[inputs.gnmi.subscription]]
    name = "temperature"
    origin = "openconfig-platform"
    path = '/components/component[name=FourHundredGigE*]/state/temperature/avg'
    subscription_mode = "target_defined"
 
[[inputs.gnmi]]
  addresses = [${addresses}]
  username = "xxx"
  password = "xxx"
  redial = "60s"
  encoding = "json_ietf"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-lanes"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-lanes/optics-lane'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name = "Cisco-optics-info"
    origin = "Cisco-IOS-XR-controller-optics-oper"
    path = '/optics-oper/optics-ports/optics-port[name=Optics0/2/0/*]/optics-info'
    subscription_mode = "target_defined"
  [[inputs.gnmi.subscription]]
    name="Cisco-controller-otu"
    origin = "Cisco-IOS-XR-controller-otu-oper"
    path = '/otu/controllers/controller[controller-name=CoherentDSP0/2/0/*]/info'
    subscription_mode = "target_defined"
 ```
