### ISSUE TITLE
processors.split: template is recognized as a field

### ISSUE THREAD

**Issue by Lprod** [influxdata/telegraf#14067]
### Relevant telegraf.conf

```toml
[[processors.split]]
  [[processors.split.prometheus_remote_write]]
    name = "kid"
    tags = [ "*" ]
    fields = [ "kid*" ]
```

### Logs from Telegraf

```text
<30> 2023-10-09T11:12:50.382034+02:00 telegraf[43678]: 2023-10-09T09:12:50Z I! Loading config: /etc/telegraf/telegraf.d/processor_split.conf
<30> 2023-10-09T11:12:50.382500+02:00 telegraf[43678]: 2023-10-09T09:12:50Z E! error loading config file /etc/telegraf/telegraf.d/processor_split.conf: plugin processors.split: line 1: configuration specified the fields ["prometheus_remote_write"], but they weren't used
```

### System info

Telegraf 1.28.1, Suse Linux Enterprise 15 SP4

### Steps to reproduce

1. deploy telegraf with split processor
2. check the logs

### Expected behavior

I would expect the measurement to be split into two new ones. I would expect the measurement "prometheus_remote_write" and "kid".

### Actual behavior

error and telegraf fails to start

**Comment by srebhan** [comment]
@Lprod I don't think you are using the processor correctly. Please take a look at the [documentation](https://github.com/influxdata/telegraf/tree/master/plugins/processors/split#configuration), your config should look similar to this

```toml
[[processors.split]]
  [[processors.split.template]]
    name = "kid"
    tags = [ "*" ]
    fields = [ "kid*" ]
```
i.e. `processors.split.template` instead of `processors.split.prometheus_remote_write`!

You also should think about [filtering your metric](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) to only split the ones you are intending to split.
