### ISSUE TITLE
OPC UA server restart

### ISSUE THREAD

**Issue by kbonnot** [influxdata/telegraf#14066]
### Relevant telegraf.conf

```toml
[[inputs.opcua]]
	endpoint = "opc.tcp://HOST:PORT"
	connect_timeout = "10s"
	request_timeout = "5s"
	security_policy = "None"
	security_mode = "None"
	certificate = ""
	private_key = ""
	auth_method = "Anonymous"
	username = ""
	password = ""
	interval = "1m"
	collection_jitter = "45s"

	[[inputs.opcua.group]]
		name = "Name"
		namespace="4"
		identifier_type="s"
		nodes = [
			{name="NODE_NAME", identifier="OpcUa.NameSpace "}, 
		]
```

### Logs from Telegraf

```text
2023-10-07T18:05:00Z E! [inputs.opcua] status not OK for node NODE_NAME: The node id refers to a node that does not exist in the server address space. StatusBadNodeIDUnknown (0x80340000)
```

### System info

Telegraf 1.28.1, Windows 10

### Steps to reproduce

1. Run Telegraf, input on an OPC UA server made by beckhoff
2. Restart the OPC UA server

...

### Expected behavior

One the UA server is restarted, the nodes are back to being available, telegraf should be able to retrieve data from them

### Actual behavior

Node ID uknown on all nodes until restart of telegraf service. 

### Additional info

in previous versions, telegraf fully crashed during these servers restart, so we could automatically restart the service.
