### ISSUE TITLE
protocol misspelled in `outputs.mqtt` configuration sample

### ISSUE THREAD

**Issue by caallinson** [influxdata/telegraf#14072]
### Relevant telegraf.conf

```toml
# Configuration for MQTT server to send metrics to
[[outputs.mqtt]]
  ## Protocol can be `3.1.1` or `5`. Default is `3.1.1`
  procotol = "3.1.1"
```

### Logs from Telegraf

```text
E! error loading config file /etc/telegraf/telegraf.conf: plugin outputs.mqtt: line 172: configuration specified the fields ["procotol"], but they weren't used
```

### System info

Telegraf 1.29.0

### Steps to reproduce

1. Load `outputs/mqtt` example configuration
2. Un-comment `procotol` configuration
3. Run telegraf

### Expected behavior

Runs without error

### Actual behavior

Errors with `configuration specified the fields ["procotol"], but they weren't used`

### Additional info

[`common/mqtt`](https://github.com/influxdata/telegraf/blob/master/plugins/common/mqtt/mqtt.go) expected configuration:

```
type MqttConfig struct {
        ...
	Protocol            string             `toml:"protocol"`
        ...
}
```
