### ISSUE TITLE
http_response - first url is a bit longer to check

### ISSUE THREAD

**Issue by olc** [influxdata/telegraf#14082]
### Relevant telegraf.conf

```toml
[[inputs.http_response]]
  urls = ["http://127.0.0.1/ping1.html", "http://127.0.0.1/ping2.html"]
  response_timeout = "10s"
  method = "GET"
  follow_redirects = false
```

### Logs from Telegraf

```text
-none-
```

### System info

telegraf 1.20.4-1, on Debian Bullseye

### Steps to reproduce

1. Place two identical files on a web server
2. Configure the plugin in order to check the response time of both files

### Expected behavior

The response time should be +/- the same

### Actual behavior

The response time of the first check (on file1.html) is several ms (sometimes longer than 20 ms) when the second check (on file2.html) only takes less than 1ms, which is the expected response time.
