### ISSUE TITLE
inputs.http_listener_v2: parser reuse and csv state

### ISSUE THREAD

**Issue by is191018** [influxdata/telegraf#14099]
### Relevant telegraf.conf

```toml
[[inputs.http_listener_v2]]
    alias = "http_listener_v2"
  ## Address and port to host HTTP listener on
  service_address = ":8080"

  ## Paths to listen to.
  paths = ["/x", "/y"]
  
  ## Save path as http_listener_v2_path tag if set to true
  path_tag = true

  ## HTTP methods to accept.
  methods = ["POST"]

  http_header_tags = {"BUCKET_HEADER" = "bucket"}

  data_format = "csv"
  csv_header_row_count = 1
  csv_timestamp_column = "timestamp"
  csv_timestamp_format = "unix"
```

### Logs from Telegraf

```text
grafana-telegraf-1  | 2023-10-12T16:56:54+02:00 D! [outputs.influxdb_v2::influxdb-he] Wrote batch of 3 metrics in 5.751655ms
grafana-telegraf-1  | 2023-10-12T16:56:54+02:00 D! [outputs.influxdb_v2::influxdb-he] Buffer fullness: 0 / 10000 metrics
grafana-telegraf-1  | 2023-10-12T16:57:00+02:00 D! [inputs.http_listener_v2::http_listener_v2] Parse error: invalid number
```

### System info

Telegraf 1.28.2, Ubuntu 22.04.1 LTS, Docker version 24.0.6, build ed223bc

### Steps to reproduce

curl -i -XPOST -H 'Content-Type: text/csv' http://localhost:8080/x -d 'timestamp,pressure
1697111290,"10.0"
1697111291,"11.0"
1697111292,"12.0"'

### Expected behavior

curl -i -XPOST -H 'Content-Type: text/csv' http://localhost:8080/x -d 'timestamp,pressure
1697111290,"10.0"
1697111291,"11.0"
1697111292,"12.0"'
HTTP/1.1 204 No Content
Content-Type: text/csv
Date: Thu, 12 Oct 2023 13:50:54 GMT

### Actual behavior

When shutting down telegraf and starting it again, the curl post with csv data works flawlessly, but if I want to send new data, I get an error 400 Bad Request. Shutting down and starting again, it works. So for every new request I have to kill the telegraf container.

xxx@vm:~/$ curl -i -XPOST -H 'Content-Type: text/csv' 
http://localhost:8080/x -d 'timestamp,pressure
1697111290,"10.0"
1697111291,"11.0"
1697111292,"12.0"'
HTTP/1.1 204 No Content
Content-Type: text/csv
Date: Thu, 12 Oct 2023 13:50:54 GMT

xxx@vm:~/$ curl -i -XPOST -H 'Content-Type: text/csv' http://localhost:8080/x -d 'timestamp,pressure
1697111390,"10.0"
1697111391,"11.0"
1697111392,"12.0"'
HTTP/1.1 400 Bad Request
Content-Type: application/json
Date: Thu, 12 Oct 2023 14:09:27 GMT
Content-Length: 29

{"error":"http: bad request"}
