### ISSUE TITLE
outputs.elasticsearch: Not dropping bad metrics after failure

### ISSUE THREAD

**Issue by Livel-tempest** [influxdata/telegraf#14110]
### Relevant telegraf.conf

```toml
[[outputs.elasticsearch]]
  urls = ["http://elasticsearch:10086"]
  timeout = 5
  enable_sniffer = false
  index_name = "region-00000000000000000000000000000000@mcelog_log"
  enable_gzip = true
  health_check_interval = 0
  [outputs.elasticsearch.tagpass]
      index = ["mcelog_log"]
```

### Logs from Telegraf

```text
Oct 15 18:20:25 pve telegraf[1560016]: 2023-10-15T16:20:25Z D! [outputs.elasticsearch] elasticsearch failed to index 2 metrics
```

### System info

Telegraf 1.28.1 (git: HEAD@3ea9ffbe), Debian GNU/Linux 11 (bullseye), Proxmox

### Steps to reproduce

1. The es output plugin writes data into es in batches.
2. Part of the data write to es failed
...

### Expected behavior

Only rewrite the data that failed to write es in the current batch

### Actual behavior

all the data in the current batch will be rewritten.

### Additional info

The es output plugin writes indicators into es in batches. When part of the data fails to be written, all the data in the current batch will be rewritten, this will eventually lead to duplicate data in es.
