### ISSUE TITLE
Plugin Vault: status 307 Temporary Redirect

### ISSUE THREAD

**Issue by stackshadow** [influxdata/telegraf#14138]
### Relevant telegraf.conf

```toml
[[inputs.vault]]
      url = "http://vaulty-0.dev:8200"
      token = "XXX"
      interval = "30s"

      [inputs.vault.tags]
        namespace = "dev"
```

### Logs from Telegraf

```text
2023-10-18T09:23:30Z E! [inputs.vault] Error in plugin: http://vaulty-0.dev:8200/v1/sys/metrics returned HTTP status 307 Temporary Redirect
```

### System info

Telegraf 1.28.2 on Kubernetes v1.26.3

### Steps to reproduce

1. Use Vault in a cluster with 3 nodes
2. Add config to scrape all 3 nodes
3. Scrape of "standby"-node emit the "redirect-error" in the logs

### Expected behavior

Follow the redirect

### Actual behavior

Only the master-node will be scraped and for standby nodes we got these redirect-error
