### ISSUE TITLE
Kubernetes Input Prometheus plugin needs to use the service bearer token from file (instead of using bearer  token) to handle the timebound service account and workload identity scenarios  

### ISSUE THREAD

**Issue by ganga1980** [influxdata/telegraf#14188]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  interval = "1m"

  ## Scrape Kubernetes pods for the following prometheus annotations:
  ## - prometheus.io/scrape: Enable scraping for this pod
  ## - prometheus.io/scheme: If the metrics endpoint is secured then you will need to
  ##     set this to `https` & most likely set the tls config.
  ## - prometheus.io/path: If the metrics path is not /metrics, define it with this annotation.
  ## - prometheus.io/port: If port is not 9102 use this annotation
  monitor_kubernetes_pods = true 
  pod_scrape_scope = "node"

  metric_version = 2
  url_tag = "scrapeUrl"
  ## Kubernetes config file to create client from.
  # kube_config = "/path/to/kubernetes.config"

  ## Use bearer token for authorization. ('bearer_token' takes priority)
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  ## OR
  # bearer_token_string = "abc_123"

  ## Specify timeout duration for slower prometheus clients (default is 3s)
  response_timeout = "15s"

  ## Optional TLS Config
  tls_ca = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  ## Use TLS but skip chain & host verification
  insecure_skip_verify = true

  ## Default is 'namespace' but this can conflict with metrics that have the label 'namespace'
  pod_namespace_label_name = "pod_namespace"
```

### Logs from Telegraf

```text
Unable to monitor pods with node scrape scope: error initially updating pod list: error when making request for pod list with status 401 Unauthorized.

Unable to monitor pods with node scrape scope: error initially updating pod list: error when making request for pod list with status 401 Unauthorized.
```

### System info

Telegraf 1.28.3 Kubernetes version 1.20.* or higher

### Steps to reproduce

1.  Configure timebound service account token - https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#:~:text=from%20kube%2Dapiserver.-,The%20kubelet%20fetches%20time%2Dbound%20tokens%20using%20the%20TokenRequest%20API,A%20configMap%20source
2. Enable Pod annotation scraping with node scope

### Expected behavior

Pod annotation based scraping (when the pod_scrape_scope = "node") should succeed 

### Actual behavior

Unable to monitor pods with node scrape scope: error initially updating pod list: error when making request for pod list with status 401 Unauthorized.

### Additional info

Input Prometheus plugin reads bearer token as part of  startK8s function - https://github.com/influxdata/telegraf/blob/64ae51e6ff60ae5592025ac292ba1cfa0fb293ba/plugins/inputs/prometheus/kubernetes.go#L53C22-L53C30 and uses the token for the node scraping as below 
https://github.com/influxdata/telegraf/blob/64ae51e6ff60ae5592025ac292ba1cfa0fb293ba/plugins/inputs/prometheus/kubernetes.go#L95

In-memory bearer token can become invalid if timebound service account token configured in the Kubernetes yaml - https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#:~:text=from%20kube%2Dapiserver.-,The%20kubelet%20fetches%20time%2Dbound%20tokens%20using%20the%20TokenRequest%20API,A%20configMap%20source.  In this case service account token only valid for 1 hour and similarly this token becomes invalid  in case of the Workload Identity enabled Kubernetes clusters where the service account  signing key rotated.
