### ISSUE TITLE
ECS plugin: panic: runtime error: slice bounds out of range [:2]

### ISSUE THREAD

**Issue by SrDayne** [influxdata/telegraf#14196]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  omit_hostname = false

[outputs]

[[outputs.influxdb_v2]]
  urls = ['<URL>']
  token = "<TOKEN>"
  organization = "<ORGANIZATION>"
  bucket = "<BUCKET>"
  timeout = "5s"

[[inputs.ecs]]
  container_name_include = []
  container_name_exclude = []
  ecs_label_include = []
  ecs_label_exclude = []
  timeout = "5s"
```

### Logs from Telegraf

```text
2023-10-26T13:38:25Z I! Loading config: /etc/telegraf/telegraf.conf
2023-10-26T13:38:25Z I! Starting Telegraf 1.28.3 brought to you by InfluxData the makers of InfluxDB
2023-10-26T13:38:25Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
2023-10-26T13:38:25Z I! Loaded inputs: ecs
2023-10-26T13:38:25Z I! Loaded aggregators: 
2023-10-26T13:38:25Z I! Loaded processors: 
2023-10-26T13:38:25Z I! Loaded secretstores: 
2023-10-26T13:38:25Z I! Loaded outputs: influxdb_v2
2023-10-26T13:38:25Z I! Tags enabled: host=ip-10-1-3-163.eu-west-2.compute.internal
2023-10-26T13:38:25Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ip-10-1-3-163.eu-west-2.compute.internal", Flush Interval:10s
panic: runtime error: slice bounds out of range [:2] with capacity 0
```

### System info

Telegraf 1.28.3, Ubuntu 22.04, Docker 24.0.6

### Docker

Container is started by ECS, but you can run this command. It produces same error:

`docker run --rm -h ip-10-1-3-163.eu-west-2.compute.internal -v /tmp/telegraf.conf:/etc/telegraf/telegraf.conf -e ECS_CONTAINER_METADATA_URI=<metadata_uri> telegraf:latest`

### Steps to reproduce

1. Create task definition with two containers: Nginx and Telegraf
2. Run new Task in EC2 environment
3. Check logs of the telegraf container. You will get the error.
...

### Expected behavior

Running telegraf, collecting metrics from the docker containers and sending them to Influxdb.

### Actual behavior

Telegraf container exits with the next error:

`panic: runtime error: slice bounds out of range [:2] with capacity 0`

### Additional info

Following this code, ecs plugin tries to parse `cpu_stats.cpu_usage.percpu_usage` array:

https://github.com/influxdata/telegraf/blob/321c5a4070cd46d699826432ab4858224f25001d/plugins/inputs/ecs/stats.go#L129

However, regarding Docker docs, Docker API doesn't return such metrics if cgroups v2 is using:

https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerStats

> On a cgroup v2 host, the following fields are not set:
>     `blkio_stats`: all fields other than `io_service_bytes_recursive`
>     **`cpu_stats`: `cpu_usage.percpu_usage`**
>     `memory_stats`:` max_usage` and `failcnt` Also, `memory_stats.stats` fields are incompatible with cgroup v1.

In other words, ecs plugin tries to parse empty array of metrics. Here is part of the data which was used in ecs plugin tests:

```
    "cpu_stats": {
      "cpu_usage": {
        "percpu_usage": [
          26426156,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ],
        "usage_in_usermode": 20000000,
        "total_usage": 26426156
      },
      "system_cpu_usage": 2336100000000,
      "online_cpus": 1,
      "throttling_data": {}
    },
```

And here is actual response from the metadata endpoint:

```
  "cpu_stats": {
    "cpu_usage": {
      "total_usage": 111340000,
      "usage_in_kernelmode": 35166000,
      "usage_in_usermode": 76174000
    },
    "system_cpu_usage": 153618620000000,
    "online_cpus": 2,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
```
