### ISSUE TITLE
Timestream Output Plugin Unconditionally Classifies `uint64` to `bigint` (signed)

### ISSUE THREAD

**Issue by jodoma** [influxdata/telegraf#14212]
### Relevant telegraf.conf

```toml
# Global tags can be specified here in key="value" format.
[global_tags]
    instance = "${INSTANCE}"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  round_interval = false
  metric_batch_size = 2000
  metric_buffer_limit = 2000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for sending metrics to Amazon Timestream.
 [[outputs.timestream]]
   namedrop = ["internal*"]

   region = "${REGION}"
   access_key = "${AWS_ACCESS_KEY_ID}"
   secret_key = "${AWS_SECRET_ACCESS_KEY}"
   database_name = "${MY_DB}"

   describe_database_on_start = false
   mapping_mode = "multi-table"
   create_table_if_not_exists = true

   create_table_magnetic_store_retention_period_in_days = 365
   create_table_memory_store_retention_period_in_hours = 24
   use_multi_measure_records = true

   measure_name_for_multi_measure_records = "telegraf_measure"

   ## Specify the maximum number of parallel go routines to ingest/write data
   ## If not specified, defaulted to 1 go routines
   max_write_go_routines = 25

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

[[inputs.procstat]]
    pattern = "."
    pid_tag = true
```

### Logs from Telegraf

```text
2023-10-27T12:50:40Z E! [outputs.timestream] Failed to write to Timestream database "****" table "procstat": operation error Timestream Write: WriteRecords, https response error StatusCode: 400, RequestID: ****************, ValidationException: Invalid value 18446744073709551615 for bigint measure value type.. Skipping metric!
```

This error message seems to be triggered here: https://github.com/influxdata/telegraf/blob/73aa12e5a54bb043fb4e6a157c10841b0be8c61f/plugins/outputs/timestream/timestream.go#L324

### System info

telegraf:1.28.2 (docker image), Ubuntu 20.04.06, Docker 24.0.7

### Docker

Telegraf is run in a Docker container using the Telegraf Image available on docker hub: 
https://hub.docker.com/_/telegraf

### Steps to reproduce

1. Run Telegraf container make sure, any of the limits file (`/proc/<pid>/limits`) within the container has `unlimited` entries

### Expected behavior

best case: `procstat` metrics get reported to Timestream 
second best case: irregular data is dropped and remaining data are stored in Timestream

### Actual behavior

* as `procstat` contains `unlimited` entries, these are [mapped to `math.MaxUint64`](https://github.com/shirou/gopsutil/blob/a7e2bdf91ca2f5a93f7b1cf413e5ef526f78cba3/process/process_linux.go#L499)
* This `uint64` value is then stringified in the [Timestream output plugin](https://github.com/influxdata/telegraf/blob/73aa12e5a54bb043fb4e6a157c10841b0be8c61f/plugins/outputs/timestream/timestream.go#L610) and claimed to be of type `bigint` ignoring the fact [that `bigint` is a **signed** 64 bit integer](https://docs.aws.amazon.com/timestream/latest/developerguide/supported-data-types.html). In case the value is larger than 2^63-1 Timestream will reject it.
