### ISSUE TITLE
Config - Cannot use hash (#) inside of inner single quotes within multi-line literal string

### ISSUE THREAD

**Issue by joahwoodward-sfmc** [influxdata/telegraf#14237]
### Relevant telegraf.conf

```toml
[[inputs.myplugin]]
value = '''This isn't a #comment.'''
```

### Logs from Telegraf

```text
error loading config file /etc/telegraf/inputs/myplugin.conf: error parsing data: line 3: invalid TOML syntax
```

### System info

Telegraf 1.28.2

### Steps to reproduce

We are using a custom input plugin to execute sql queries read from config files, some of which operate on temp tables or have single quotes and/or `#`'s inside of SQL comments. Telegraf is truncating lines from these queries if it finds a `#` after a single quote inside of a multiline literal string and causing unexpected behavior and syntax errors.

### Expected behavior

Valid TOML is supported and `#`'s inside multi-line literal strings are never treated as comments or stripped by the config preprocessor.

### Actual behavior

Telegraf is treating the `#` as the beginning of a comment, resulting in invalid toml syntax or unexpected values.
From the example, the config preprocessor will turn it into:
```
[[inputs.myplugin]]
value = '''This isn't a 
```

### Additional info

Seems to be a regression caused by [7c636b4](https://github.com/influxdata/telegraf/commit/7c636b4b6b38e7da4446a48854b5fc55b8b78104)

**Comment by powersj** [comment]
Hi,

Can you modify the following to give me an actual example:

```toml
[agent]
    debug = true
    omit_hostname = true

[[inputs.exec]]
    commands = ["echo influx value=42"]
    data_format = "influx"

[[processors.starlark]]
  source = '''
# this is a comment
def apply(metric):
  metric.tags["tag"] = "foo#bar"
  return metric
'''

[[outputs.file]]
```

As-is this returns the following and I don't seem to treat it as a comment:

```s
influx,tag=foo#bar value=42 1698880266000000000
```

Additionally, do you know if a previous version worked and then a new version did?
