### ISSUE TITLE
Environment variable ${TEMP} causes TOML syntax error on telegraf >= 1.27.0

### ISSUE THREAD

**Issue by Space2Man** [influxdata/telegraf#14239]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
   interval = "60s"
   logtarget = "file"
   logfile = "${TEMP}/telegraf.log"
   logfile_rotation_max_size = "5MB"
   logfile_rotation_max_archives = 5
   log_with_timezone = "Europe/Berlin"
```

### Logs from Telegraf

```text
C:\Program Files\telegraf>.\telegraf-1.28.3.exe --config C:\windows\temp\telegraf.conf
2023-11-02T10:50:09Z I! Loading config: C:\windows\temp\telegraf.conf
2023-11-02T10:50:09Z E! error loading config file C:\windows\temp\telegraf.conf: error parsing data: line 5: invalid TOML syntax
```

### System info

>= telegraf-1.27.0 on Windows

### Steps to reproduce

1. run telegraf -config with the above config 
2. versions <= 1.26.3 work fine but >= 1.27.0 do not

### Expected behavior

Telegraf uses ${TEMP} to decide where to put the logfile. ${TEMP} is set to "C:\Windows\Temp" on Windows.

### Actual behavior

Telegraf stops with above error

### Additional info

I checked https://github.com/influxdata/telegraf/pull/13457 and it does not help to use $${TEMP} ... then the error is gone but it does not write to the log file.
