### ISSUE TITLE
input.ecs - 404 page not found

### ISSUE THREAD

**Issue by xavier-romero** [influxdata/telegraf#14291]
### Relevant telegraf.conf

```toml
[agent]
  interval = "20s"
  round_interval = true

[[inputs.ecs]]
  container_name_exclude = ["log_router*", "telegraf-*"]
  container_status_include = ["RUNNING"]
  ecs_label_include = [ "com.amazonaws.ecs.*" ]
  ecs_label_exclude = []

[[outputs.influxdb]]
  urls = ["http://${INFLUXDB_HOST}:8086"]
  database = "grafana"
```

### Logs from Telegraf

```text
2023-11-14T11:50:00Z E! [inputs.ecs] Error in plugin: http://169.254.170.2/v4/c88ff02a586a44bdb903a51300734228-1597264354/v2/stats returned HTTP status 404 Not Found: "404 page not found\n"
```

### System info

AWS ECS - public.ecr.aws/docker/library/telegraf

### Steps to reproduce

1. Deploy service on ECS with Telegraf task
2.
3.
...

### Expected behavior

To gather docker stats

### Actual behavior

Error trying to get the info

### Additional info

Using default image public.ecr.aws/docker/library/telegraf stopped working today with the current vesion 1.28.4, with this same config and version 1.28.3 everything works.
