### ISSUE TITLE
Error: Connection context exceeded

### ISSUE THREAD

**Issue by parvez-cet21** [influxdata/telegraf#14299]
### Please direct all support questsions to slack or the forums. Thank you.

I'm trying to remote MySQL Historian Server using input.sql, I can connect successfully with ODBC Sever Test Connection in Windows but unable to connect through telegraf in Ubuntu.
Complete logs are here:
```
Loading config: ./telegraf.conf

34 2023-11-15T07:05:32Z I! Starting Telegraf 1.28.3 brought to you by InfluxData th

35 e makers of InfluxDB

36 2023-11-15T07:05:32Z I! Available plugins: 240 inputs, 9 aggregators, 29 process

NECK

37 ors, 24 parsers, 59 outputs, 5 secret-stores

38 2023-11-15T07:05:32Z I! Loaded inputs: sql

39 2023-11-15T07:05:32Z

I! Loaded aggregators: 40 2023-11-15T07:05:32Z I! Loaded processors:

LUMN

41 2023-11-15T07:05:32Z I! Loaded secretstores:

42 2023-11-15T07:05:32Z I! Loaded outputs: postgresql

43

2023-11-15T07:05:32Z I! Tags enabled:

2023-11-15T07:05:32Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"

44 45 Flush Interval:10s

2023-11-15T07:05:32Z D! [agent] Initializing plugins

46 2023-11-15T07:05:32Z D! [agent] Connecting outputs

47 48 2023-11-15T07:05:32Z D! [agent] Attempting connection to [outputs.postgresql]

2023-11-15T07:05:32Z D! [agent] Successfully connected to outputs.postgresql

49 2023-11-15T07:05:32Z D! [agent] Starting service inputs

50 2023-11-15T07:05:32Z D! [inputs.sql] Connecting...

51 2023-11-15T07:05:32Z D! [inputs.sql] Testing connectivity...

52 2023-11-15T07:05:37Z E! [telegraf] Error running agent: starting input inputs.sq

53 1: unable to connect to database: context deadline exceeded
```

Here is my telegraf.conf
```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 1000

  metric_buffer_limit = 10000

  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  # logtarget = "file"
  # logfile = ""
  # logfile_rotation_interval = "0h"
  # logfile_rotation_max_size = "0MB"
  # logfile_rotation_max_archives = 5
  # hostname = "192.168.1.100"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true

# Publishes metrics to a postgresql database
[[outputs.postgresql]]
  connection = "postgres://test:Password1@localhost/telegraf?sslmode=disable"
  # schema = "public"
  # create_templates = [
  #   '''CREATE TABLE IF NOT EXISTS datasets(["time","name","quantity"])'''
  # ]

  ## Schema to create the tables into
  # schema = "public"
  # ## Templated statements to execute when creating a new table.
  create_templates = [
      '''CREATE TABLE {{ .table }} ({{ .columns }})''',
  ]
  # add_column_templates = [
  #     '''ALTER TABLE {{ .table }} ADD COLUMN IF NOT EXISTS {{ .columns|join ", ADD COLUMN IF NOT EXISTS " }}''',
  # ]
  # tag_table_add_column_templates = [
  #     '''ALTER TABLE {{.table}} ADD COLUMN IF NOT EXISTS {{.columns|join ", ADD COLUMN IF NOT EXISTS "}}''',
  # ]

###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################
[[inputs.sql]]
  driver = "mysql"
  dsn = "sa:Password@tcp(52.146.17.139:1433)/master&connection+timeout=30"

  timeout = "5s"


  [[inputs.sql.query]]
    query_script = "test.sql"
    measurement = "test"
    ## Column name containing the name of the measurement
    ## If given, this will take precedence over the 'measurement' setting. In case a query result
    ## does not contain the specified column, we fall-back to the 'measurement' setting.
    # measurement_column = ""

    ## Column name containing the time of the measurement
    ## If ommited, the time of the query will be used.
    # time_column = ""

    ## Format of the time contained in 'time_col'
    ## The time must be 'unix', 'unix_ms', 'unix_us', 'unix_ns', or a golang time format.
    ## See https://golang.org/pkg/time/#Time.Format for details.
    # time_format = "unix"

    ## Column names containing tags
    ## An empty include list will reject all columns and an empty exclude list will not exclude any column.
    ## I.e. by default no columns will be returned as tag and the tags are empty.
    # tag_columns_include = []
    # tag_columns_exclude = []

    ## Column names containing fields (explicit types)
    ## Convert the given columns to the corresponding type. Explicit type conversions take precedence over
    ## the automatic (driver-based) conversion below.
    ## NOTE: Columns should not be specified for multiple types or the resulting type is undefined.
    # field_columns_float = []
    # field_columns_int = []
    # field_columns_uint = []
    # field_columns_bool = []
    # field_columns_string = []

    ## Column names containing fields (automatic types)
    ## An empty include list is equivalent to '[*]' and all returned columns will be accepted. An empty
    ## exclude list will not exclude any column. I.e. by default all columns will be returned as fields.
    ## NOTE: We rely on the database driver to perform automatic datatype conversion.
    # field_columns_include = []
    # field_columns_exclude = []

  [[inputs.sql.query]]
    query_script = "datasets.sql"
    measurement = "datasets"
    ## Column name containing the name of the measurement
    ## If given, this will take precedence over the 'measurement' setting. In case a query result
    ## does not contain the specified column, we fall-back to the 'measurement' setting.
    # measurement_column = ""

    ## Column name containing the time of the measurement
    ## If ommited, the time of the query will be used.
    # time_column = ""

    ## Format of the time contained in 'time_col'
    ## The time must be 'unix', 'unix_ms', 'unix_us', 'unix_ns', or a golang time format.
    ## See https://golang.org/pkg/time/#Time.Format for details.
    # time_format = "unix"

    ## Column names containing tags
    ## An empty include list will reject all columns and an empty exclude list will not exclude any column.
    ## I.e. by default no columns will be returned as tag and the tags are empty.
    # tag_columns_include = []
    # tag_columns_exclude = []


    ## Column names containing fields (explicit types)
    ## Convert the given columns to the corresponding type. Explicit type conversions take precedence over
    ## the automatic (driver-based) conversion below.
    ## NOTE: Columns should not be specified for multiple types or the resulting type is undefined.
    # field_columns_float = []
    # field_columns_int = []
    # field_columns_uint = []
    # field_columns_bool = []
    # field_columns_string = []

    ## Column names containing fields (automatic types)
    ## An empty include list is equivalent to '[*]' and all returned columns will be accepted. An empty
    ## exclude list will not exclude any column. I.e. by default all columns will be returned as fields.
    ## NOTE: We rely on the database driver to perform automatic datatype conversion.
    # field_columns_include = []
    # field_columns_exclude = []
```
