### ISSUE TITLE
inputs.http plugin does not respect token_file

### ISSUE THREAD

**Issue by jyrkih** [influxdata/telegraf#14347]
### Relevant telegraf.conf

```toml
[[inputs.http]]

  ## One or more URLs from which to read formatted metrics.
  urls = [
    "https://xxxxxx",
  ]
  token_file = "/tmp/bearer_token_file"
```

### Logs from Telegraf

```text
docker-telegraf-1  | 2023-11-27T14:00:00Z E! [inputs.http] Error in plugin: [url=https://xxxxxx]: open : no such file or directory
```

### System info

Telegraf 1.28.5

### Docker

FROM telegraf:latest

### Steps to reproduce

1. define custom bearer token using `token_file`

...

### Expected behavior

http input plugin should open the file containing the bearer token

### Actual behavior

error which says that file cannot be opened.

### Additional info

I think it's part in http.go:

`} else if h.TokenFile != "" { `
`   token, err := os.ReadFile(h.BearerToken)`

I.e. it tries to open file given in the deprecated `bearer_token`
