### ISSUE TITLE
Helm chart does not properly template out config YAML

### ISSUE THREAD

**Issue by erkexzcx** [influxdata/telegraf#14368]
Here is my relevant helm chart values part:
```yaml
config:
  inputs:
    - mock:
        metric_name: "mock"
        constant:
          - name: "constant"
            value: 123
```

Expected output (it works fine):
```toml
[[inputs.mock]]
  metric_name = "mock"
  [[inputs.mock.constant]]
     name = "constant"
     value = 123
```

Actual output (it does NOT work):
```toml
[[inputs.mock]]
  [[inputs.mock.constant]]
     name = "constant"
     value = 123
  metric_name = "mock"
```

Which leads to this kind of error:
```
2023-11-30T12:07:00Z I! Loading config: /etc/telegraf/telegraf.conf
2023-11-30T13:07:00.549733400+01:00 2023-11-30T12:07:00Z E! error loading config file /etc/telegraf/telegraf.conf: plugin inputs.mock: line 35: configuration specified the fields ["metric_name"], but they weren't used
```

Any suggestions on how to fix it?

**Comment by powersj** [comment]
Hi,

The GitHub tracker is not for support nor for the helm charts. The helm-chart repo is at: https://github.com/influxdata/helm-charts

The short answer to your question is to use `tplVersion: 2` at the top of your config.

```toml
tplVersion: 2
config:
  inputs:
    - mock:
        metric_name: "mock"
        constant:
          - name: "constant"
            value: 123
```

which in turn produces:

```toml
    [[inputs.mock]]    
      metric_name = "mock"
      [[inputs.mock.constant]]  
        name = "constant"
        value = 123
```

Going to close this as this is not an issue or feature request relevant to telegraf.
