### ISSUE TITLE
Freebsd 14 telegraf inputs.wireguard is silent.

### ISSUE THREAD

**Issue by bunnyevans** [influxdata/telegraf#14397]
### Relevant telegraf.conf

```toml
# 3------1---------2---------3---------4---------5---------6---------7---------8
# 2023.12.07 test
# 3------1---------2---------3---------4---------5---------6---------7---------8
#
[[inputs.wireguard]]
  # does this work?
  devices = ["wg0", "wg1"]
```

### Logs from Telegraf

```text
2023-12-07T05:01:28Z I! Starting Telegraf 1.21.4
```

### System info

Telegraf 1.21.4, freebsd, FreeBSD 14.0-RELEASE

### Steps to reproduce

1. create simple config based on: https://github.com/influxdata/telegraf/tree/release-1.21/plugins/inputs/wireguard
2. , above config  is in telegraf.conf.TEST here.
3.  /usr/local/bin/telegraf --config=/usr/local/etc/telegraf.conf --config-directory=/usr/local/etc/telegraf.conf.TEST --test --debug

4.
...

### Expected behavior

results of some sort as per the documentation.

### Actual behavior

silence

### Additional info

Both wg0 and wg1 exist, but even removing the "devices =" line produces only silence.
