### ISSUE TITLE
gocritic->rangeExprCopy - Detects expensive copies of for loop range expressions. Should we enable it?

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#14410]
### Description

This issue starts a discussion about enabling:
- linter: [gocritic](https://github.com/go-critic/go-critic/) - Highly extensible Go source code linter providing checks currently missing from other linters.
- group: [performance](https://go-critic.com/overview.html#checkers-from-the-performance-group) - Performance checks tell you about potential issues that can make your code run slower than it could be.
- checker: [rangeExprCopy](https://go-critic.com/overview.html#rangeexprcopy) - Detects expensive copies of for loop range expressions. Suggests to use pointer to array to avoid the copy using & on range expression (see Go issue for details: https://github.com/golang/go/issues/15812).

### Example

**Before:**
```
var xs [2048]byte
for _, x := range xs { // Copies 2048 bytes
	// Loop body.
}
```

**After:**
```
var xs [2048]byte
for _, x := range &xs { // No copy
	// Loop body.
}
```

### Expected output

Decision about enabling or not enabling this checker.

### Findings

For this checker, no findings were found in the current codebase.

### Additional configuration

For this checker, additional configuration can be provided:
```
      rangeExprCopy:
        # Size in bytes that makes the warning trigger.
        # Default: 512
        sizeThreshold: 516
        # Whether to check test functions
        # Default: true
        skipTestFuncs: false
```
