### ISSUE TITLE
v1.29 not sending metrics to CloudWatch

### ISSUE THREAD

**Issue by jami3cressey** [influxdata/telegraf#14439]
### Relevant telegraf.conf

```toml
[agent]
  omit_hostname = true

[[outputs.cloudwatch]]
  region = "${AWS_REGION}"
  namespace = "${CLOUDWATCH_NAMESPACE}"
```

### Logs from Telegraf

```
2023-12-12T10:53:02Z E! [outputs.cloudwatch] Unable to write to CloudWatch : not found, ResolveEndpointV2
2023-12-12T10:53:02Z E! [agent] Error writing to outputs.cloudwatch: not found, ResolveEndpointV2
```

### System info

Telegraf 1.29

### Steps to reproduce

1. Attempt to use the CloudWatch output plugin

### Expected behavior

Metrics are sent successfully to CloudWatch

### Actual behavior

Metrics do not get sent to CloudWatch and error is reported

### Additional info

Downgrading to 1.28.5 resolves the problem. 

Possibly related to - https://github.com/aws/aws-sdk-go-v2/issues/2370
