### ISSUE TITLE
LDAP docs show openldap as the input in example

### ISSUE THREAD

**Issue by tiny6996** [influxdata/telegraf#14445]
### Relevant telegraf.conf

```toml
[[inputs.openldap]]
  server = "ldap://ldap.example.com"
  bind_dn = "uid=admin,cn=users,cn=accounts,dc=local,dc=example,dc=com"
  bind_password = "NOT_MY_P@$$W0rd"
```

### Logs from Telegraf

```text
2023-12-13T00:28:48Z I! Loading config: ldap.conf
2023-12-13T00:28:48Z E! error loading config file ldap.conf: plugin inputs.openldap: line 1: configuration specified the fields ["server"], but they weren't used
```

### System info

Telegraf 1.29, Fedora 39

### Docker

N/A

### Steps to reproduce

1. Open Relavent Docs ()
2. create config above
3. run telegraf --config ldap.conf --test --debug
...

### Expected behavior

making a config based on the docs should show results if ldap server is configured properly

### Actual behavior

input error shown above

### Additional info

changing the config to use `[[inputs.ldap]]` the issue is resolved

```
[[inputs.ldap]]
  server = "ldap://ldap.example.com"
  bind_dn = "uid=admin,cn=users,cn=accounts,dc=local,dc=example,dc=com"
  bind_password = "NOT_MY_P@$$W0rd"
```
