### ISSUE TITLE
[outputs.prometheus_client] generates an error in 1.29.1 version

### ISSUE THREAD

**Issue by wally007** [influxdata/telegraf#14468]
### Relevant telegraf.conf

```toml
[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "1s"
  flush_interval = "10s"
  flush_jitter = "3s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.prometheus_client]]
   listen = "localhost:9012"
   metric_version = 2
   export_timestamp = true
```

### Logs from Telegraf

```text
Dec 17 12:43:57 refinst-capture1 telegraf[2428]: 2023-12-17T12:43:57Z E! [telegraf] Error running agent: connecting output outputs.prometheus_client: error connecting to output "outputs.prometheus_client": Unknown scheme
```

### System info

RHEL9.3, telegraf 1.29.1

### Steps to reproduce

1. Update telegraf from 1.28.5 to 1.29.1 with prometheus output plugin
2. Start Telegraf service 
3. Watch the logs 
...

### Expected behavior

Service should start up and telegraf output plugin should work in 1.29 version same as 1.28

### Actual behavior

Telegraf does not start and generates an error

Dec 17 12:43:57 refinst-capture1 telegraf[2428]: 2023-12-17T12:43:57Z E! [telegraf] Error running agent: connecting output outputs.prometheus_client: error connecting to output "outputs.prometheus_client": Unknown scheme

### Additional info

Configuration that works in 1.28.5 version when upgraded to 1.29.1 fails to start Telegraf with an error 

Dec 17 12:43:57 refinst-capture1 telegraf[2428]: 2023-12-17T12:43:57Z E! [telegraf] Error running agent: connecting output outputs.prometheus_client: error connecting to output "outputs.prometheus_client": Unknown scheme

When I remove the 1.29.1 version with `yum remove telegraf` and install `1.28.5` explicitly with `yum install telegraf-1.28.5-1` - the same configuration as aboev works fine.
