### ISSUE TITLE
RabbitMQ plugin <=1.29.1: queue idle_since value can be empty, isn't handled correctly: elasticsearch indexing fails.

### ISSUE THREAD

**Issue by sandervandegeijn** [influxdata/telegraf#14499]
### Relevant telegraf.conf

```toml
Contains the fix in a starlark script, but shouldn't be necessary:

[global_tags]
  environment = "${DIP_ENVIRONMENT}"

[agent]
interval = "60s"
round_interval = false
metric_batch_size = 10
metric_buffer_limit = 1000
collection_jitter = "2s"
flush_interval = "1s"
flush_jitter = "5s"
precision = ""
debug = true
quiet = false
logfile = ""
hostname = ""
omit_hostname = false

[[inputs.rabbitmq]]
  url = "http://xxxxx-xxxx:15672"
  username = "xxxxx"
  password = "xxxx"
   [inputs.rabbitmq.tags]
    input = "rabbitmq"

[[processors.starlark]]
  source = '''
def apply(metric):
    # Check if 'idle_since' field exists and is not empty
    if 'idle_since' in metric.fields and metric.fields['idle_since'] != '':
        return metric  # Keep the metric if 'idle_since' is not empty
    else:
        metric.fields.pop('idle_since', None)  # Remove 'idle_since' if empty
        return metric  # Return the modified metric
'''

[[outputs.elasticsearch]]
  urls = [ "${DIP_MONITORING_URL}" ] # required.
  timeout = "5s"
  enable_sniffer = false
  health_check_interval = "15s"
  username = "xxxx"
  password = "xxxx"
  index_name = "telegraf-{{input}}-{{environment}}-%Y.%m.%d" # required.
  insecure_skip_verify = true
  manage_template = true
  template_name = "telegraf"
  overwrite_template = false
```

### Logs from Telegraf

```text
Can't generate the logs anymore because I'm running into https://github.com/influxdata/telegraf/issues/14497 ... But opensearch was complaining telegraf was trying to insert a empty string in a date field. Doesn't like that.
```

### System info

Telegraf 1.29.1, opensearch 2.11.1

### Docker

Default image

### Steps to reproduce

See above

### Expected behavior

Handle an empty date field correctly.

### Actual behavior

Writing to elasticsearch fails
