### ISSUE TITLE
Output Kafka is missing important parameter when using Kerberos

### ISSUE THREAD

**Issue by akarneliuk** [influxdata/telegraf#14514]
### Relevant telegraf.conf

```toml
[[outputs.kafka]]
  brokers = ["b-0.hl.kafka.svc:9092", "b-1.hl.kafka.svc:9092", "b-2.hl.kafka.svc:9092"]

  topic = "test-topic"

  client_id = "my-collector"
  
  version = "1.5.0"

  routing_tag = "source"

  ## Optional SASL:
  ## one of: OAUTHBEARER, PLAIN, SCRAM-SHA-256, SCRAM-SHA-512, GSSAPI
  ## (defaults to PLAIN)
  sasl_mechanism = "GSSAPI"

  ## used if sasl_mechanism is GSSAPI
  sasl_gssapi_service_name = "my_kafka_service"
  ## One of: KRB5_USER_AUTH and KRB5_KEYTAB_AUTH
  sasl_gssapi_auth_type = "KRB5_KEYTAB_AUTH"
  sasl_gssapi_kerberos_config_path = "/krb5/krb.conf"
  sasl_gssapi_realm = "realm"
  sasl_gssapi_key_tab_path = "/krb5/my.keytab"
  sasl_gssapi_disable_pafxfast = false
```

### Logs from Telegraf

```text
2024-01-01T12:07:03Z E! [agent] Failed to connect to [outputs.kafka], retrying in 15s, error was "kafka: invalid configuration (Net.SASL.GSSAPI.Username must not be empty when GSS-API mechanism is used)"
```

### System info

Telegraf 1.29.1

### Steps to reproduce

1. Configure Kafka output in Telegraf using GSSAPI and Kerberos.
2. Authentication type is KRB5_KEYTAB_AUTH.
3. Try to connect to Kafka and produce data
4. It will fail.

### Expected behavior

Telegraf connects to Kafka and start producing information collected from my relevant inputs

### Actual behavior

Telegraf throw an error that there is no username provided. And there is no key in documentation, which suggests how to provide username.
However, the underlying IBM library, which you use, requires this parameter: https://github.com/IBM/sarama/blob/main/kerberos_client.go#L42

You can see the very same error message in this test https://github.com/IBM/sarama/blob/main/config_test.go#L181, which relates to missing username.

### Additional info

I suppose, the solution can be to expose all the possible keys (starting at least with username) from IBM/sarama, so that we can authenticate using Kerberos.
