### ISSUE TITLE
IoTDB device_id [ILLEGAL_PATH(509)] Exception occurred: insertRecord failed

### ISSUE THREAD

**Issue by giovanni-bellini-argo** [influxdata/telegraf#14518]
### Relevant telegraf.conf

```toml
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Counters = ["Bytes Received/sec","Bytes Sent/sec","Packets Received/sec","Packets Sent/sec"]
    Instances = ["*"]
    Measurement = "root.WinPerfCounters.$COMPUTERNAME.WinNet"

[[outputs.iotdb]]
  # host, port, user, password have been purposefully omitted
  # to avoid exposing sensitive data
  host = ""
  port = ""
  user = ""
  password = ""
  uint64_conversion = "int64_clip"
  timestamp_precision = "millisecond"
  convert_tags_to = "device_id"
  timeout = "0s"
```

### Logs from Telegraf

```text
2023/12/05 14:59:21 [ERROR]  Error Code: 509, Message: [ILLEGAL_PATH(509)] Exception occurred: insertRecord failed. root.WinPerfCounters.DC5.WinNet.Adattatore Ethernet vmxnet3 is not a legal path
2023/12/05 14:59:22 [ERROR]  Error Code: 509, Message: [ILLEGAL_PATH(509)] Exception occurred: insertRecord failed. root.WinPerfCounters.DC5.WinNet.isatap.{DAACFE3D-0417-4B20-8F47-9599B4C94381} is not a legal path
```

### System info

Telegraf 1.29.1, Windows Server 2019

### Steps to reproduce

1. Configure telegraf to use IoTDB output
2. Set convert_tag_to = "device_id"
3. Run telegraf in debug mode

### Expected behavior

The path should be corrected by enclosing the tags wich contain a character not supported by IoTDB in ``

### Actual behavior

Telegraf simply tryes to add the path as it is and dosen't give any way to correct such behaviour

### Additional info

Host, port, user, password have been purposefully omitted to avoid exposing sensitive data.

We got a little working fix which is running on our production sites, and are willing to share the current code to get some reviews and maybe improvements.
