### ISSUE TITLE
Parallelism / RTU over TCP

### ISSUE THREAD

**Issue by Ogy** [influxdata/telegraf#14528]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  data_format = "json"
  commands = [
    "systemctl start socat@1",
    "sleep 2s"
  ]
  timeout = "10s"

[[inputs.modbus]]
  name = "modbus1"
  slave_id = 1
  timeout = "2s"
  controller = "file:///socat/1"
  configuration_type = "register"
 baud_rate = 9600
 data_bits = 8
 parity = "N"
 stop_bits = 1

discrete_inputs = [
  { name = "DI1", address = [0]},
]

[[inputs.exec]]
  data_format = "json"
  commands = [
    "systemctl stop socat@1",
    "sleep 1"
  ]
  timeout = "2s"
```

### Logs from Telegraf

```text
2024-01-05T00:40:23Z E! [inputs.modbus] Error in plugin: no such file or directory
2024-01-05T00:40:23Z E! [inputs.exec] Error in plugin: exec: exit status 1 for command "systemctl stop socat@1": Job for socat@1.service canceled.
```

### System info

Telegraf 1.29.1 (git: HEAD@9a469977)

### Steps to reproduce

run multiple exec

### Expected behavior

working

### Actual behavior

doesn't work

### Additional info

Hello, I was not able to run Modbus RTU over TCP. I gave it up, as, in my humble opinion, it's not implemented or I'm dumb. I came up with a socat workaround, which works well. Unfortunately, I have more readers, so I must close socat after reading data.

The questions are:

Is RTU over TCP implemented?
Can jobs in one configuration be run sequentially, not in parallel?
Can jobs be set to run even if one fails? (e.g., Modbus doesn't have a PTY - fails, and the last job (kill socat) is canceled)
Are there any pre / post actions?

Many thanks in advance
