### ISSUE TITLE
(inputs.gnmi): Parsing field names incorrectly

### ISSUE THREAD

**Issue by greenfox878** [influxdata/telegraf#14530]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
  addresses = ["gnmi_dut:xxx"]

  ## define credentials
  username = "xxxxx"
  password = "xxxxx"

  encoding = "json_ietf"
  tagexclude = ["path"]


  [inputs.gnmi.tags]
    test_tag = "test"

  # Define additional aliases to map encoding paths to measurement names
  [inputs.gnmi.aliases]
    origin = "openconfig"
    ifcounters = "/interfaces/interface/state/counters"

  [[inputs.gnmi.subscription]]
    name = "ifcounters"
    origin = "openconfig"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"
```

### Logs from Telegraf

```text
no error messages
```

### System info

Telegraf 1.29.1, Ubuntu 22.04.3 LTS (latest updates)

### Steps to reproduce

1. Download compiled telegraf release "wget https://dl.influxdata.com/telegraf/releases/telegraf-1.29.1_linux_amd64.tar.gz", untar
2. Run with the command "./telegraf-1.29.1/usr/bin/telegraf --config ./test_telegraf_conifg.cfg --debug"

### Expected behavior

Correct output. v1.28.5 or older
```
ifcounters,host=test_telegraf_host,name=Ethernet40,source=gnmi_dut,test_tag=test in_broadcast_pkts=0i,in_discards=0i,in_errors=0i,in_fcs_errors=0i,in_multicast_pkts=0i,in_octets=0i,in_pkts=0i,in_unicast_pkts=0i,out_broadcast_pkts=0i,out_discards=0i,out_errors=0i,out_multicast_pkts=0i,out_octets=0i,out_pkts=0i,out_unicast_pkts=0i 1704442117721474264
ifcounters,host=test_telegraf_host,name=Ethernet26,source=gnmi_dut,test_tag=test in_broadcast_pkts=0i,in_discards=0i,in_errors=0i,in_fcs_errors=0i,in_multicast_pkts=0i,in_octets=0i,in_pkts=0i,in_unicast_pkts=0i,out_broadcast_pkts=0i,out_discards=0i,out_errors=0i,out_multicast_pkts=0i,out_octets=0i,out_pkts=0i,out_unicast_pkts=0i 1704442117721474264
```

### Actual behavior

Corrupted outptu. v1.29.1:
```
ifcounters,host=test_telegraf_host,name=Ethernet40,source=gnmi_dut,test_tag=test t_pkts=0i,in_errors=0i,rs=0i,in_octets=0i,in_pkts=0i,pkts=0i,st_pkts=0i,s=0i,out_errors=0i,out_octets=0i,out_pkts=0i,_pkts=0i 1704442117721474264
ifcounters,host=test_telegraf_host,name=Ethernet26,source=gnmi_dut,test_tag=test t_pkts=0i,in_errors=0i,rs=0i,in_octets=0i,in_pkts=0i,pkts=0i,st_pkts=0i,s=0i,out_errors=0i,out_octets=0i,out_pkts=0i,_pkts=0i 1704442117721474264
```
here we see "_pkts", "t_pkts", "st_pkts" instead of "out_pkts", "out_multicast_pkts"...
