### ISSUE TITLE
[inputs.exec] Error in plugin: exec: exit status 255

### ISSUE THREAD

**Issue by electronics-nik** [influxdata/telegraf#14556]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = "/var/log/telegraf/rpi-metrics.log"
  hostname = ""
  omit_hostname = false
[[outputs.influxdb_v2]]
  urls = ["http://IP:8086"]
  token = "token"
  organization = "home"
  bucket = "rasp-pi"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]

[[inputs.exec]]
  commands = ["/usr/bin/vcgencmd measure_temp"]
  name_override = "temperature_gpu"
  data_format = "grok"
  grok_patterns = ["%{NUMBER:value:float}"]

[[inputs.temp]]
```

### Logs from Telegraf

```text
2024-01-09T20:00:20Z E! [inputs.exec] Error in plugin: exec: exit status 255 for command "/usr/bin/vcgencmd measure_temp": 
2024-01-09T20:00:25Z E! [inputs.exec] Error in plugin: exec: exit status 255 for command "/usr/bin/vcgencmd measure_temp": 
2024-01-09T20:00:30Z E! [inputs.exec] Error in plugin: exec: exit status 255 for command "/usr/bin/vcgencmd measure_temp":
```

### System info

Telegraf 1.29.1, Debian GNU/Linux 12.4, Linux 6.1.0-rpi7-rpi-v8, arm64

### Steps to reproduce

If I run telegraph from the command line:

`telegraf --config ~/rpi_metrics.conf`

there are no errors

but if I load the cofig file into the `/etc/telegraf/telegraf.d` folder, I get an error in the logs

`[inputs.exec] Error in plugin: exec: exit status 255 for command "/usr/bin/vcgencmd measure_temp"`

### Expected behavior

No any errors in the log

### Actual behavior

I get error in the log
