### ISSUE TITLE
[opcua_listener] 1000 Nodes will get EOF[failed to start monitoring items: EOF]

### ISSUE THREAD

**Issue by yang750418** [influxdata/telegraf#14568]
### Relevant telegraf.conf

```toml
.....
[[inputs.opcua_listener]]
  name = "Mapping"
  endpoint = "opc.tcp://192.168.1.xx" 
  connect_timeout = "100s"
  request_timeout = "50s"
  subscription_interval = "100ms"
  security_policy = "auto"
  security_mode = "auto"
  certificate = "/etc/telegraf/ua.pem"
  private_key = "/etc/telegraf/ua_key.pem"
  auth_method = "UserName"
  username = "user"
  password = "123456"
  timestamp = "gather"
......
```

### Logs from Telegraf

```text
failed to start monitoring items: EOF
```

### System info

Telegraf 1.29.0  ,docker 24.0.2, IGS OPCUA

### Steps to reproduce

1. Setting security_policy=auto & security_mode=auto
2. Setting certificate & private_key
3. Config 2000~3000 Nodes 
4. Run Telegraf Connection OPC Ua
...

### Expected behavior

start monitoring items success

### Actual behavior

failed to start monitoring items: EOF

### Additional info

Telegraf Logs 
![292698453-edb572ff-e1de-42f4-ac8f-0cd3ebb23b4f](https://github.com/influxdata/telegraf/assets/85604615/d29f25a4-814c-470f-b80d-64cc74e86aab)
When I cancel the use of security settings, I can configure 20000 NodeID.
