### ISSUE TITLE
[outputs.mqtt] The leading forward slash in mqtt topic is removed

### ISSUE THREAD

**Issue by zhangyuan** [influxdata/telegraf#14583]
### Relevant telegraf.conf

```toml
[[outputs.mqtt]]
servers = ["tls://x.x.x.x:31883"]
username = "xxxx"
#password = "xxxx"
client_id = "xxx"
password = "xxx"
topic = "/sys/ProductKey/DeviceId/thing/event/property/post"
protocol = "3.1.1"
qos = 1
tls_ca = "certs/root.crt"
keep_alive = 3000
connection_timeout = "5s"
insecure_skip_verify = true
timeout = "2s"
```

### Logs from Telegraf

```text
timeout error (will provide tomorrow once I have access)
```

### System info

Telegraf 1.29.1

### Steps to reproduce

1. use `[outputs.mqtt]` and the topic name with leading forward slash, e.g. `/sys/ProductKey/DeviceId/thing/event/property/post`.
2. run telegraf with the config file

### Expected behavior

The plugin should send the messages to the MQTT topic.

### Actual behavior

The error `Could not publish message to MQTT server: timeout` is printed to stdout.

If the MQTT debug log is enabled, the target topic is printed (the topic is `sys/ProductKey/DeviceId/thing/event/property/post`). To enable MQTT debug logs,  add the code snippets from `paho.mqtt.golang`'s [README](https://github.com/eclipse/paho.mqtt.golang?tab=readme-ov-file#logging) to the function `NewMQTTv311Client` in telegraf source code.

As I see the leading forward slash is trimed.

### Additional info

The leading forward slash is not recommended in the topic:
* https://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices/#avoid-leading-forward-slash
* https://docs.aws.amazon.com/whitepapers/latest/designing-mqtt-topics-aws-iot-core/mqtt-design-best-practices.html

However, some of the IoT platform doesn't respect the recommendation.
