### ISSUE TITLE
xpath_json format can use the default type defined in the JSON (int, float, string)

### ISSUE THREAD

**Issue by MuChenMuXuan** [influxdata/telegraf#14597]
### Use Case

```
 data_format = "xpath_json"
  [[inputs.kafka_consumer.xpath]]
```
xpath_json format,  By default (type not explicitly specified), the type of field value is a string

### Expected behavior

json_v2 format:
For each field you have the option to define the types. The following rules are in place for this configuration:
- If a type is explicitly defined, the parser will enforce this type and convert the data to the defined type if possible. If the type can't be converted then the parser will fail.
- If a type isn't defined, the parser will use the default type defined in the JSON (int, float, string)

xpath_json can support this feature ?

### Actual behavior

xpath_json format,  By default (type not explicitly specified), the type of field value is a string

**Comment by srebhan** [comment]
@MuChenMuXuan I'm not sure I do understand what you are trying to achieve. Lets's assume you do have a JSON with
```json
{
  "value": 5
}
```

Now if you set
```toml
[[inputs.kafka_consumer]]
  ...
 data_format = "xpath_json"
 xpath_native_types = true

 [[inputs.kafka_consumer.xpath]]
  [inputs.kafka_consumer.xpath.fields]
    value = "/value"  
```
you will get `value` as a `float64` field. That is because the _native_ JSON type for the field is a number (aka floating point value).

When using
```toml
[[inputs.kafka_consumer]]
  ...
 data_format = "xpath_json"
 xpath_native_types = true

 [[inputs.kafka_consumer.xpath]]
  [inputs.kafka_consumer.xpath.fields_int]
    value = "/value"  
```

you will get the value as  `int64` as `fields_int` will try to convert the value to integer.

You can also do explicit typing by omitting the ` xpath_native_types = true` setting... With
```toml
[[inputs.kafka_consumer]]
  ...
 data_format = "xpath_json"

 [[inputs.kafka_consumer.xpath]]
  [inputs.kafka_consumer.xpath.fields]
    value = "/value"  
```

you will get `value` as a `string` because the JSON document is converted to XML and the element is a string by default.
To get `float64` in this setting you do
```toml
[[inputs.kafka_consumer]]
  ...
 data_format = "xpath_json"

 [[inputs.kafka_consumer.xpath]]
  [inputs.kafka_consumer.xpath.fields]
    value = "number(/value)"  
```
and to get an integer you should use `fields_int` as above
```toml
[[inputs.kafka_consumer]]
  ...
 data_format = "xpath_json"

 [[inputs.kafka_consumer.xpath]]
  [inputs.kafka_consumer.xpath.fields_int]
    value = "/value"  
```
