### ISSUE TITLE
Telegraf Windows Registry Input Plugin

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#14653]
### Use Case

We want to consume string and numeric values from Windows registry. Here you can find usefull generic windows information like windows version, settings and much more. Also some apps are storing important information here.

### Expected behavior

Telegraf can read values (String, DWORD, QWORD) from given Windows Registry path like
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\InstallDate

### Actual behavior

Currently getting string and numeric values from Windows registry is not possible with Telegraf _standard_ plugins. Also no chance with `inputs.win_wmi` because it uses WQL-Interface which does not support method-calls.

### Additional info

Currently you have to use `inputs.exec` to execute a custom poweshell script to get Windows Regitry values. Executing powershell scripts is not always a good solution because of security concerns and for users without Powershell coding knowledge.

**Comment by Flightliner380** [comment]
We need also, this feature to get values from the registry.

**Comment by PSHWorkShop** [comment]
Yes, would be a  very useful feature , we need.

**Comment by srebhan** [comment]
@1tft and @PSHWorkShop, please test the binary in PR #15300 and let me know if that works for you! The new feature adds more than only querying the registry but allows to invoke arbitrary WMI methods. Therefore, to read a registry value you should do

```toml
# Input plugin to query Windows Management Instrumentation
# This plugin ONLY supports Windows
[[inputs.win_wmi]]
  ## Hostname or IP for remote connections, by default the local machine is queried
  # host = ""
  ## Credentials for the connection, by default no credentials are used
  # username = ""
  # password = ""

  [[inputs.win_wmi.method]]
    ## WMI namespace, class and method to use
    namespace = 'root\default'
    class_name = "StdRegProv"
    method = "GetStringValue"
    ## Returned WMI method values to use as tags instead of fields
    # tag_properties = ["ReturnValue"]
    ## Named arguments for the method call
    [inputs.win_wmi.method.arguments]
      hDefKey = '2147483650'
      sSubKeyName = 'Software\Microsoft\windows NT\CurrentVersion'
      sValueName = 'ProductName'
```

to read `HKLM\Software\Microsoft\windows NT\CurrentVersion\ProductName`...
