### ISSUE TITLE
plugin inputs.systemd_units: configuration specified the fields ["subcommand"], but they weren't used

### ISSUE THREAD

**Issue by matusnovak** [influxdata/telegraf#14663]
### Relevant telegraf.conf

```toml
# File: /etc/telegraf/telegraf.conf
# This is the entire configuration
[agent]
  interval = "10s" # Does not matter in here, just to fill in the agent section.

[[inputs.systemd_units]]
  interval = "30s"
  timeout = "10s"
  unittype = "service"
  subcommand = "show" # Or with a value of "list-units", does not matter, same error.

[[outputs.file]]
  files = ["/tmp/metrics.influx"]
  data_format = "influx"
```

### Logs from Telegraf

```text
2024-02-01T10:48:34Z I! Loading config: /etc/telegraf/telegraf.conf
2024-02-01T10:48:34Z E! error loading config file /etc/telegraf/telegraf.conf: plugin inputs.systemd_units: line 4: configuration specified the fields ["subcommand"], but they weren't used
```

### System info

Telegraf 1.29.4 HEAD@4441c4ed, Ubuntu 22.04 LTS

### Docker

N/A

### Steps to reproduce

1. Download and install the latest Telegraf
2. Copy paste the configuration from above
3. Run telegraf
4. Telegraf fails to start

### Expected behavior

Telegraf should start successfully and should accept `subcommand = "show"` as shown in the configuration section in here: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/systemd_units/README.md

Other fields such as `unittype` and `pattern` are accepted correctly. It is only the `subcommand` that causes the failure.

### Actual behavior

Fails to start with error:
```txt
2024-02-01T10:48:34Z E! error loading config file /etc/telegraf/telegraf.conf: plugin inputs.systemd_units: line 4: configuration specified the fields ["subcommand"], but they weren't used
```

### Additional info

I am a bit puzzled about this error, because the configuration is specified in here:
https://github.com/influxdata/telegraf/blob/master/plugins/inputs/systemd_units/systemd_units.go#L123-L130

All of the other properties, except the `SubCommand` on line 125, are accepted. Removing `subcommand = "show"` (or `subcommand = "list-units"` from the configuration file will make it to work, the Telegraf starts successfully, and I can see the metrics for systemd services appearing in the output.
