### ISSUE TITLE
bug(secretstores): Invalid secret names are silently ignored

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#14662]
### Relevant telegraf.conf

```toml
[[secretstores.docker]]
  id = "secrets"  
  path = "/secrets"

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]
  bucket = "k8s-deployment-tests"
  organization = "org"
  token = "@{secrets:infl_w_k8s-deployment-tests}"
  influx_uint_support = true
```

### Logs from Telegraf

```text
2024-02-01T09:17:36Z E! [outputs.influxdb_v2] When writing to [http://localhost:8086]: Post "http://localhost:8086/api/v2/write?bucket=k8s-deployment-tests&org=org": net/http: invalid header field value for "Authorization"
2024-02-01T09:17:36Z E! [agent] Error writing to outputs.influxdb_v2: failed to send metrics to any configured server(s)
```

### System info

Telegraf 1.29.1

### Steps to reproduce

1. Configure an invalid secret name (i.e. it contains characters other than letters, numbers or underscores)
2. Start Telegraf

### Expected behavior

1. Telegraf stops with an error pointing out the invalid secret name

### Actual behavior

1. Telegraf starts without issues
2. Data will not be written because the secret name is not replaced with its value but just passed as the secret

### Additional info

Finding the cause of the write failures was very difficult and I only managed to do it by running Telegraf locally without HTTPS and seeing the value for the Authorization header being equal to `Token @{secrets:infl_w_k8s-deployment-tests}` instead of the actual secret value.
