### ISSUE TITLE
${}-Variable expansion doesn't work with user-agent in influxdb output plugin

### ISSUE THREAD

**Issue by knollet** [influxdata/telegraf#14674]
### Relevant telegraf.conf

```toml
[[outputs.influxdb]]
  urls = ["https://myinfluxdb:8086"]
  database = "somedatabase"
  username = "someuser"
  password = "someuserspassword"
  retention_policy = ""

  skip_database_creation = true
  write_consistency = "any"
  timeout = "5s"
  user_agent = "telegraf ${HOSTNAME}"
  content_encoding = "gzip"
```

### Logs from Influxdb

```
Feb  2 16:52:21 myhostname.mydomain influxd-systemd-start.sh[1562]: [httpd] 1.2.3.4 - notadmin [02/Feb/2024:16:52:21 +0100] "POST /write?consistency=any&db=testdb HTTP/1.1 "
204 0 "-" "telegraf ${HOSTNAME}" 0ccff0e0-c1e3-11ee-b3c4-0050569fc026 5017

```

### System info

Telegraf 1.28.3 (git: HEAD@a72550a0)

### Docker

nope.

### Steps to reproduce

1. Use `${HOSTNAME}` in your user-agent string in the influxdb output plugin config.

### Expected behavior

`${HOSTNAME}` to be replaced by the actual hostname, which it actually did some versions ago.

### Actual behavior

`${HOSTNAME}` is not replaced by actual hostname
