### ISSUE TITLE
Mqtt output plugin doesnt recognize topic field in configuration

### ISSUE THREAD

**Issue by fahadalisarwar1** [influxdata/telegraf#14672]
### Please direct all support questsions to slack or the forums. Thank you.

here is my output plugin
```toml
    [[outputs.mqtt]]
        servers=[
            "${MQTT_SERVER}"
        ]
        topic = "telegraf/{{ .PluginName }}"
        username="${MQTT_USERNAME}"
        password="${MQTT_PASSWORD}"
        protocol="5"

        data_format = "influx"
```

I am trying to build a modbus to mqtt bridge but mqtt output plugin is not working
