### ISSUE TITLE
[processors.enum] Handle boolean and numeric values

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#14804]
### Use Case

Be able to use the enum processor against more than just strings: this should include boolean and numeric values. However, need to put a big fat warning about floats. As these will not consistently work since we have to convert the values to strings.

### Expected behavior

Can use enum on integers and booleans

### Actual behavior

Does not work

### Additional info

The steps required would include:

- Convert the field value to a string
- Add big warning/error/something when used with floats that this will probably not work
- No need to update the config, maybe add docs about floats and give examples of int and boolean
- Add tests for all scenarios

**Comment by Hipska** [comment]
Can you provide a use case? IMO the enum processor works perfectly fine with numeric (integer) values:

```toml
[[inputs.mock]]
  metric_name = "some_metric"

  [inputs.mock.tags]
    foo = "bar"
	status = "2"

  [[inputs.mock.constant]]
    name = "value"
    value = 1


[[processors.enum]]
  namepass = ["some_metric"]

  [[processors.enum.mapping]]
    field = "value"

    [processors.enum.mapping.value_mappings]
      1 = "up"
      2 = "down"
      3 = "testing"

  [[processors.enum.mapping]]
    tag = "status"

    [processors.enum.mapping.value_mappings]
      1 = "up"
      2 = "down"
      3 = "testing"
```
Resulting in:
```diff
-some_metric,foo=bar,status=2 value=1i 1708944201000000000
+some_metric,foo=bar,status=down value="up" 1708944201000000000
```
