### ISSUE TITLE
Inputs.prometheus fails to start with `content_length_limit`

### ISSUE THREAD

**Issue by stakauskas** [influxdata/telegraf#14827]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  urls = ["http://localhost:8080/metrics"]

  ## Content length limit
  ## When set, telegraf will drop responses with length larger than the configured value.
  ## Default is "0KB" which means unlimited.
  content_length_limit = "10KB"
```
```


### Logs from Telegraf

```text
2024-02-14T11:05:33Z I! Loading config: telegraf.conf
2024-02-14T11:05:33Z E! error loading config file telegraf.conf: plugin inputs.prometheus: line 14: configuration specified the fields ["content_length_limit"], but they weren't used
```
```


### System info

Linux, telegraf 1.29.4

### Docker

_No response_

### Steps to reproduce

1. Add `content_length_limit = "10KB"` to `[[inputs.prometheus]]` 
2. Start telegraf 1.29.4

### Expected behavior

Telegraf to start and use the feature describetd at this [link](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/prometheus/README.md).

### Actual behavior

Error, does not start.

### Additional info

_No response_
