### ISSUE TITLE
outputs.http doesn't support json_transformation

### ISSUE THREAD

**Issue by fossilscm** [influxdata/telegraf#14842]
### Relevant telegraf.conf

```toml
# Telegraf configuration
# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"

# Configuration for telegraf agent
[agent]
  interval = "5s"
  round_interval = true
  metric_buffer_limit = 10000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  hostname = ""

# A plugin that can transmit metrics over HTTP
[[outputs.http]]
  url = "https://umamiproxy.my.domain:8018/proxy/send"
  method = "POST"
  ## Use TLS but skip chain & host verification
  insecure_skip_verify = true
  data_format = "json"
  #next line this is line 54 in original conf file
  json_transformation = '''
  $merge([$, {"websiteId": "1b57e25f-101e-4279-a4ef-d1769fee655b"}])
  '''


# Read logging output from the Docker engine
[[inputs.docker_log]]

  endpoint = "unix:///var/run/docker.sock"
  from_beginning = false
  timeout = "5s"
  container_name_include = ["traefik-rpx"]
  source_tag = false
```

### Logs from Telegraf

```text
telegraf_1  | 2024-02-18T06:45:28Z I! Starting Telegraf 1.18.3
telegraf_1  | 2024-02-18T06:45:28Z I! Using config file: /etc/telegraf/telegraf.conf
telegraf_1  | 2024-02-18T06:45:28Z E! [telegraf] Error running agent: Error loading config file /etc/telegraf/telegraf.conf: plugin outputs.http: line 54: configuration specified the fields ["json_transformation"], but they weren't used
```

### System info

Telegraf 1.18.3, Ubuntu 22.04.2 LTS, Docker version 20.10.21

### Docker

version: '3.6'

services:
  telegraf:
    image: telegraf:1.18-alpine

    volumes:
      - "./telegraf.conf.toml:/etc/telegraf/telegraf.conf:ro"
      ## do chmod 666 /var/run/docker.sock
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

### Steps to reproduce

1.put json_transformation into telegraf config
2. start container using docker-compose up
3. got error msg on stdout
...

### Expected behavior

need to add some info to metrics using json_transformation when output to http

### Actual behavior

got error in log see above
