### ISSUE TITLE
[inputs.gnmi] metrics prefixes are corrupted in 1.29.0

### ISSUE THREAD

**Issue by egr3s** [influxdata/telegraf#14889]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
   addresses = [ "ip:port" ]
   username = "user"
   password = "pass"
   encoding = "json"
   redial = "10s"
   enable_tls = false
  [[inputs.gnmi.subscription]]
   name = "port_stats"
   origin = "nokia-state"
   path = "/state/port[port-id=*]/statistics/"
   subscription_mode = "sample"
   sample_interval = "60s"
  [[inputs.gnmi.subscription]]
   name = "flash_free_space"
   origin = "nokia-state"
   path = "/state/cpm[cpm-slot=*]/flash[flash-id=*]/free-space"
   subscription_mode = "sample"
   sample_interval = "60s"
```

### Logs from Telegraf

```text
2024-02-05T18:28:55Z E! [inputs.gnmi] Invalid empty path "/state/port/statistics/out-discards" with alias "nokia-state:/state/port/statistics"
2024-02-05T18:28:55Z E! [inputs.gnmi] Invalid empty path "/state/port/statistics/out-discards" with alias "nokia-state:/state/port/statistics"
```

### System info

telegraf:1.29.0

### Steps to reproduce

1. configure gNMI input plugin to subscribe to port statistics metrics
2. redirect output to a file
3. open the file and see that metrics prefixes are broken

### Expected behavior

Metrics shouldn't be corrupted, e.g. with 1.28.5:
`path=/state/port/statistics,port_id=A/1,rmrw=allowed,source=ip in_discards="0",in_errors="0",in_octets="52732623",in_packets="573811",in_unknown_protocol_discards="0",in_broadcast_packets="1303",in_multicast_packets="1",in_unicast_packets="572507",out_discards="0",out_errors="0",out_octets="432940948",out_packets="844057",out_broadcast_packets="236",out_multicast_packets="0",out_unicast_packets="843821"
`

### Actual behavior

Metrics names are corrupted
`path=/state/port/statistics,port_id=A/1,rmrw=allowed,source=ip in_discards="0",in_errors="0",in_octets="52683510",in_packets="573230",rotocol_discards="0",_packets="1",ackets="571926",out_errors="0",out_octets="432484117",out_packets="842751",t_packets="0",packets="842515"`
