### ISSUE TITLE
[inputs.upsd] Inconsistent output type for multi-state variables containing "enabled"/"disabled"

### ISSUE THREAD

**Issue by masterwishx** [influxdata/telegraf#14908]
### Relevant telegraf.conf

```toml
[[inputs.upsd]]
  ## A running NUT server to connect to.
  ## IPv6 addresses must be enclosed in brackets (e.g. "[::1]")
   server = "192.168.0.199"
   port = 3493
  # username = "user"
  # password = "password"

  ## Force parsing numbers as floats
  ## It is highly recommended to enable this setting to parse numbers
  ## consistently as floats to avoid database conflicts where some numbers are
  ## parsed as integers and others as floats.
  # force_float = false

  ## Collect additional fields if they are available for the UPS
  ## The fields need to be specified as NUT variable names, see
  ## https://networkupstools.org/docs/developer-guide.chunked/apas02.html
  ## Wildcards are accepted.
   additional_fields = ["*"]

  ## Dump information for debugging
  ## Allows to print the raw variables (and corresponding types) as received
  ## from the NUT server ONCE for each UPS. The output is only available when
  ## running Telegraf in debug-mode.
  ## Please attach this information when reporting issues!
  # dump_raw_variables = false

to influxdbv2
```

### Logs from Telegraf

```text
2024-02-28T18:44:31Z E! [outputs.influxdb_v2] Failed to write metric to upsd-Telegraf (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "ups_beeper_status" on measurement "upsd" is type string, already exists as type boolean dropped=1
28.02.2024
20:44:41
2024-02-28T18:44:41Z E! [outputs.influxdb_v2] Failed to write metric to upsd-Telegraf (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "ups_beeper_status" on measurement "upsd" is type string, already exists as type boolean dropped=1
28.02.2024
20:44:51
2024-02-28T18:44:51Z E! [outputs.influxdb_v2] Failed to write metric to upsd-Telegraf (will be dropped: 422 Unprocessable Entity): unprocessable entity: failure writing points to database: partial write: field type conflict: input field "ups_beeper_status" on measurement "upsd" is type string, already exists as type boolean dropped=1
```

### System info

latest alpine version of Docker in Unraid

### Docker

..

### Steps to reproduce

export all values from upsd to influxdbv2

### Expected behavior

..

### Actual behavior

..

### Additional info

![image](https://github.com/influxdata/telegraf/assets/28630321/c0874917-8bfc-43b9-9415-4de91172dc6f)

**Comment by masterwishx** [comment]
from https://networkupstools.org/docs/developer-guide.chunked/apas02.html
![image](https://github.com/influxdata/telegraf/assets/28630321/0fe58b2c-2b48-4e21-81a2-c83ad331cbd6)

**Comment by masterwishx** [comment]
it seems error appear when `muted` instead of enabled or disabled

**Comment by masterwishx** [comment]
@srebhan @powersj can you please check this out ....

**Comment by powersj** [comment]
I did not think we did any transformation of enabled/disabled to true or false. Were you using another collector before?

@masterwishx can you set `dump_raw_variables = false` please I want to see an entry with both a disabled/enabled and one with muted.

**Comment by masterwishx** [comment]
> I did not think we did any transformation of enabled/disabled to true or false. Were you using another collector before?
> 
> @masterwishx can you set `dump_raw_variables = false` please I want to see an entry with both a disabled/enabled and one with muted.

Do you mean to test on windows? I was tested on windows befor...
I can check disabled/muted enabled somehow not working for me now becose of some kind of bug in upsd, when I set enabled it's goes to mute value but in real the sound is working so it's enabled

**Comment by masterwishx** [comment]
@powersj 

disabled:  

![image](https://github.com/influxdata/telegraf/assets/28630321/49b6878d-00c0-4b97-8b3d-a7f549831e33)

![image](https://github.com/influxdata/telegraf/assets/28630321/65944252-ed16-42f6-8f9b-d18c3dc79371)

mute: 

![image](https://github.com/influxdata/telegraf/assets/28630321/dc9e062a-9a1a-4dfd-9251-fc59b31bbf21)

![image](https://github.com/influxdata/telegraf/assets/28630321/3536efa6-7116-46fa-8435-fbbc54f94b70)

**Comment by powersj** [comment]
In line protocol `false` and `true` are booleans, not strings. As a result, your very first value was probably either `false` or `true` and InfluxDB went "that's a boolean". Then you sent a "muted" string, which InfluxDB rejects becuase of the type conflict.

My suggestion is for you to is to use a processor in telegraf to convert the values to booleans, and/or drop your data and use a processor to convert them all to strings. For the first, you could use the strings processor to match on "muted" and change it to true/false.

@srebhan any other thoughts?

**Comment by masterwishx** [comment]
> In line protocol `false` and `true` are booleans, not strings. As a result, your very first value was probably either `false` or `true` and InfluxDB went "that's a boolean". Then you sent a "muted" string, which InfluxDB rejects becuase of the type conflict.
> 
> My suggestion is for you to is to use a processor in telegraf to convert the values to booleans, and/or drop your data and use a processor to convert them all to strings. For the first, you could use the strings processor to match on "muted" and change it to true/false.
> 
> @srebhan any other thoughts?

can you give an example for it please?

**Comment by srebhan** [comment]
@powersj the problem here is that the plugin wants to be too clever as it will detect `enabled` and `disabled` strings and convert them to booleans. However, there are multiple non-binary strings also containing other things like `muted`... So again auto-typing bites us. :-(

The correct way would be to _not_ do any auto-type conversions for strings, but this certainly breaks backward compatibility...

@masterwishx you might use the [enum processor]() to convert the value. Here an untested suggestion

```toml
[[processors.enum]]
  [[processors.enum.mapping]]
    field = "ups_beeper_status"
    default = false
    [processors.enum.mapping.value_mappings]
      enabled = true
      disabled = false
      muted = false
```
