### ISSUE TITLE
Input plugin - Netflow incorrect ip_dscp field mapping for NetflowV9

### ISSUE THREAD

**Issue by SirBreadc** [influxdata/telegraf#14902]
### Relevant telegraf.conf

```toml
[[inputs.netflow]]
  service_address = "udp4://:2055"

  ## Protocol version to use for decoding.
  ## Available options are
  ##   "ipfix"      -- IPFIX / Netflow v10 protocol (also works for Netflow v9)
  ##   "netflow v5" -- Netflow v5 protocol
  ##   "netflow v9" -- Netflow v9 protocol (also works for IPFIX)
  ##   "sflow v5"   -- sFlow v5 protocol
  protocol = "ipfix"

  dump_packets = false
```
or 

```toml
[[inputs.netflow]]
  service_address = "udp4://:2055"

  ## Protocol version to use for decoding.
  ## Available options are
  ##   "ipfix"      -- IPFIX / Netflow v10 protocol (also works for Netflow v9)
  ##   "netflow v5" -- Netflow v5 protocol
  ##   "netflow v9" -- Netflow v9 protocol (also works for IPFIX)
  ##   "sflow v5"   -- sFlow v5 protocol
  protocol = "netflow v9"

  dump_packets = false

# # Configuration for sending metrics to InfluxDB 2.0
 [[outputs.influxdb_v2]]
#   ## The URLs of the InfluxDB cluster nodes.
#   ##
#   ## Multiple URLs can be specified for a single cluster, only ONE of the
#   ## urls will be written to each interval.
#   ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
   urls = ["https://"]
#
#   ## Token for authentication.
   token = ""
#
#   ## Organization is the name of the organization you wish to write to.
   organization = ""
#
#   ## Destination bucket to write into.
   bucket = ""
```

### Logs from Telegraf

```text
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [46]}
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [0]}
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [0]}
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [0]}
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [0]}
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [0]}
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [48]}
2024-02-28T02:11:00Z D! [inputs.netflow] unknown Netflow v9 data field {false 195 0 [48]}
```

### System info

Telegraf 1.30, Centos,CentOS Linux 7

### Steps to reproduce

1. Send NetFlow V9 from an IOSXE device with 'collect ipv4 dscp' command inside the flow record template

### Expected behavior

the dscp field would show in influx

### Actual behavior

We see a field call type_195

### Additional info

I tested a fix locally and by moving 
```
	195: {{"dscp", decodeUint}},                     // ipDiffServCodePoint
``` 
from `var fieldMappingsIPFIX = map[uint16][]fieldMapping{` to `var fieldMappingsNetflowCommon = map[uint16][]fieldMapping{`

in `telegraf/plugins/inputs/netflow/netflow_decoder.go`

to fix the issue. :) 

Can anyone suggest other ways we could go about handling this?
