### ISSUE TITLE
Can't move key-value pairs from fields to tags

### ISSUE THREAD

**Issue by wpesotsky** [influxdata/telegraf#14925]
### Relevant telegraf.conf

```toml
[[processors.starlark]]
#   ## The Starlark source can be set as a string in this configuration file, or
#   ## by referencing a file containing the script.  Only one source or script
#   ## should be set at once.
#
#   ## Source of the Starlark script.
  source = '''

def apply(metric):
  
  for k, v in metric.fields.items():
    if type(v) != "float" and type(v) != "int":

      metric.tags.update({k:str(v)})
      metric.fields.pop(k)

  return metric
    '''
```

### Logs from Telegraf

```text
.
```

### System info

Telegraf 1.29.5

### Steps to reproduce

1. Run Telegraf without the Starlark script
2. Find some field-values that are non-numeric
3. Run Telegraf with the Starlark script
4. Look at the same metric
5. Check if the entry has been moved from fields to tags

### Expected behavior

The non-numeric key-value pairs should be removed in fields and be added to tags

### Actual behavior

Either the entries are in fields AND tags or they disappear in both dicts. 
There is no way to remove the exact same entry from fields without deleting it from tags
