### ISSUE TITLE
fields vary over and do not match documentation

### ISSUE THREAD

**Issue by schaefer01** [influxdata/telegraf#14926]
### Relevant telegraf.conf

```toml
#
# -----------------------------------------
#
#                                    # 11 nstat
[[inputs.mqtt_consumer]]

 servers = ["tcp://127.0.0.1:1883"]

  ## Topics that will be subscribed to.
  topics = [
    "test_00/#",
    "telemetry/+/nstat/#",
  ]

   data_format = "json_v2"

   [[inputs.mqtt_consumer.json_v2]]  
     [[inputs.mqtt_consumer.json_v2.field]]     # 1
            path = "fields.IpExtInBcastOctets"
            type = "int"
     [[inputs.mqtt_consumer.json_v2.field]]     # 2
            path = "fields.IpExtInBcastPkts"
            type = "int"
     [[inputs.mqtt_consumer.json_v2.field]]     # 3
            path = "fields.IpExtInCEPkts"
            type = "float"
     [[inputs.mqtt_consumer.json_v2.field]]     # 4
            path = "fields.IpExtInCsumErrors"
            type = "int"
     [[inputs.mqtt_consumer.json_v2.field]]     # 5
            path = "fields.IpExtInECT0Pkts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 6
            path = "fields.IpExtInECT1Pkts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 7
            path = "fields.IpExtInMcastOctets"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 8
            path = "fields.IpExtInMcastPkts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 9
            path = "fields.IpExtInNoECTPkts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 10
            path = "fields.IpExtInNoRoutes"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 11
            path = "fields.IpExtInOctets"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 12
            path = "fields.IpExtInTruncatedPkts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 13
            path = "fields.IpExtOutBcastOctets"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 14
            path = "fields.IpExtOutBcastPkts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 15
            path = "fields.IpExtOutMcastOctets"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 16
            path = "fields.IpExtOutMcastPkts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 17
            path = "fields.IpExtOutOctets"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 18
            path = "fields.IpExtReasmOverlaps"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 19
            path = "fields.TcpExtArpFilter"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 20
            path = "fields.TcpExtBusyPollRxPackets"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 21
            path = "fields.TcpExtDelayedACKLocked"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 22
            path = "fields.TcpExtDelayedACKLost"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 23
            path = "fields.TcpExtDelayedACKs"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 24
            path = "fields.TcpExtEmbryonicRsts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 25
            path = "fields.TcpExtIPReversePathFilter"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 26
            path = "fields.TcpExtListenDrops"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 27
            path = "fields.TcpExtListenOverflows"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 28
            path = "fields.TcpExtLockDroppedIcmps"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 29
            path = "fields.TcpExtOfoPruned"
            type = "float"
    [[inputs.mqtt_consumer.json_v2.field]]      # 30
            path = "fields.TcpExtOutOfWindowIcmps"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 31
            path = "fields.TcpExtPAWSActive"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 32
            path = "fields.TcpExtPAWSEstab"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 33
            path = "fields.TcpExtPFMemallocDrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 34
            path = "fields.TcpExtPruneCalled"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 35
            path = "fields.TcpExtRcvPruned"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 36
            path = "fields.TcpExtSyncookiesFailed"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 37
            path = "fields.TcpExtSyncookiesRecv"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 38
            path = "fields.TcpExtSyncookiesSent"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 39
            path = "fields.TcpExtTCPACKSkippedChallenge"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 40
            path = "fields.TcpExtTCPACKSkippedFinWait2"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 41
            path = "fields.TcpExtTCPACKSkippedPAWS"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 42
            path = "fields.TcpExtTCPACKSkippedSeq"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 43
            path = "fields.TcpExtTCPACKSkippedSynRecv"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 44
            path = "fields.TcpExtTCPACKSkippedTimeWait"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 45
            path = "fields.TcpExtTCPAbortFailed"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 46
            path = "fields.TcpExtTCPAbortOnClose"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 47
            path = "fields.TcpExtTCPAbortOnData"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 48
            path = "fields.TcpExtTCPAbortOnLinger"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 49
            path = "fields.TcpExtTCPAbortOnMemory"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 50
            path = "fields.TcpExtTCPAbortOnTimeout"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 51
            path = "fields.TcpExtTCPAckCompressed"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 52
            path = "fields.TcpExtTCPAutoCorking"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 53
            path = "fields.TcpExtTCPBacklogCoalesce"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 54
            path = "fields.TcpExtTCPBacklogDrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 55
            path = "fields.TcpExtTCPChallengeACK"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 56
            path = "fields.TcpExtTCPDSACKIgnoredDubious"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 57
            path = "fields.TcpExtTCPDSACKIgnoredNoUndo"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 58
            path = "fields.TcpExtTCPDSACKIgnoredOld"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 59
            path = "fields.TcpExtTCPDSACKOfoRecv"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 60
            path = "fields.TcpExtTCPDSACKOfoSent"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 61
            path = "fields.TcpExtTCPDSACKOldSent"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 62
            path = "fields.TcpExtTCPDSACKRecv"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 63
            path = "fields.TcpExtTCPDSACKRecvSegs"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 64
            path = "fields.TcpExtTCPDSACKUndo"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 65
            path = "fields.TcpExtTCPDeferAcceptDrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 66
            path = "fields.TcpExtTCPDelivered"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 67
            path = "fields.TcpExtTCPDeliveredCE"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 68
            path = "fields.TcpExtTCPFastOpenActive"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 69
            path = "fields.TcpExtTCPFastOpenActiveFail"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 70
            path = "fields.TcpExtTCPFastOpenBlackhole"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 71
            path = "fields.TcpExtTCPFastOpenCookieReqd"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 72
            path = "fields.TcpExtTCPFastOpenListenOverflow"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 73
            path = "fields.TcpExtTCPFastOpenPassive"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 74
            path = "fields.TcpExtTCPFastOpenPassiveAltKey"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 75
            path = "fields.TcpExtTCPFastOpenPassiveFail"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 76
            path = "fields.TcpExtTCPFastRetrans"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 77
            path = "fields.TcpExtTCPFromZeroWindowAdv"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 78
            path = "fields.TcpExtTCPFullUndo"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 79
            path = "fields.TcpExtTCPHPAcks"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 80
            path = "fields.TcpExtTCPHPHits"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 81
            path = "fields.TcpExtTCPHystartDelayCwnd"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 82
            path = "fields.TcpExtTCPHystartDelayDetect"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 83
            path = "fields.TcpExtTCPHystartTrainCwnd"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 84
            path = "fields.TcpExtTCPHystartTrainDetect"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 85
            path = "fields.TcpExtTCPKeepAlive"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 86
            path = "fields.TcpExtTCPLossFailures"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 87
            path = "fields.TcpExtTCPLossProbeRecovery"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 88
            path = "fields.TcpExtTCPLossProbes"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 89
            path = "fields.TcpExtTCPLossUndo"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 90
            path = "fields.TcpExtTCPLostRetransmit"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 91
            path = "fields.TcpExtTCPMD5Failure"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 92
            path = "fields.TcpExtTCPMD5NotFound"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 93
            path = "fields.TcpExtTCPMD5Unexpected"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 94
            path = "fields.TcpExtTCPMTUPFail"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 95
            path = "fields.TcpExtTCPMTUPSuccess"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 96
            path = "fields.TcpExtTCPMemoryPressures"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 97
            path = "fields.TcpExtTCPMemoryPressuresChrono"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 98
            path = "fields.TcpExtTCPMinTTLDrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 99
            path = "fields.TcpExtTCPOFODrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 100
            path = "fields.TcpExtTCPOFOMerge"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 101
            path = "fields.TcpExtTCPOFOQueue"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 102
            path = "fields.TcpExtTCPOrigDataSent"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 103
            path = "fields.TcpExtTCPPartialUndo"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 104
            path = "fields.TcpExtTCPPureAcks"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 105
            path = "fields.TcpExtTCPRcvCoalesce"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 106
            path = "fields.TcpExtTCPRcvCollapsed"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 107
            path = "fields.TcpExtTCPRcvQDrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 108
            path = "fields.TcpExtTCPRenoFailures"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 109
            path = "fields.TcpExtTCPRenoRecovery"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 110
            path = "fields.TcpExtTCPRenoRecoveryFail"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 111
            path = "fields.TcpExtTCPRenoReorder"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 112
            path = "fields.TcpExtTCPReqQFullDoCookies"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 113
            path = "fields.TcpExtTCPReqQFullDrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 114
            path = "fields.TcpExtTCPRetransFail"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 115
            path = "fields.TcpExtTCPSACKDiscard"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 116
            path = "fields.TcpExtTCPSACKReneging"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 117
            path = "fields.TcpExtTCPSACKReorder"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 118
            path = "fields.TcpExtTCPSYNChallenge"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 119
            path = "fields.TcpExtTCPSackFailures"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 120
            path = "fields.TcpExtTCPSackMerged"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 121
            path = "fields.TcpExtTCPSackRecovery"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 122
            path = "fields.TcpExtTCPSackRecoveryFail"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 123
            path = "fields.TcpExtTCPSackShiftFallback"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 124
            path = "fields.TcpExtTCPSackShifted"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 125
            path = "fields.TcpExtTCPSlowStartRetrans"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 126
            path = "fields.TcpExtTCPSpuriousRTOs"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 127
            path = "fields.TcpExtTCPSpuriousRtxHostQueues"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 128
            path = "fields.TcpExtTCPSynRetrans"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 129
            path = "fields.TcpExtTCPTSReorder"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 130
            path = "fields.TcpExtTCPTimeWaitOverflow"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 131
            path = "fields.TcpExtTCPTimeouts"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 132
            path = "fields.TcpExtTCPToZeroWindowAdv"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 133
            path = "fields.TcpExtTCPWantZeroWindowAdv"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 134
            path = "fields.TcpExtTCPWinProbe"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 135
            path = "fields.TcpExtTCPWqueueTooBig"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 136
            path = "fields.TcpExtTCPZeroWindowDrop"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 137
            path = "fields.TcpExtTW"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 138
            path = "fields.TcpExtTWKilled"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 139
            path = "fields.TcpExtTWRecycled"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 140
            path = "fields.TcpExtTcpDuplicateDataRehash"
            type = "int"
    [[inputs.mqtt_consumer.json_v2.field]]      # 141
            path = "fields.TcpExtTcpTimeoutRehash"
            type = "int"

    [[inputs.mqtt_consumer.json_v2.field]]      # 
            path = "timestamp"
            type = "int"
```

### Logs from Telegraf

```text
Mar 04 14:10:41 eclipse-control telegraf[94359]: 2024-03-04T14:10:41Z E! [inputs.mqtt_consumer] Error in plugin: the path "fields.IpExtInBcastOctets" doesn't exist
```

### System info

Telegraf 1.29.4 (git: HEAD@4441c4ed), Ubuntu 22.04.3 LTS

### Steps to reproduce

1. load the vm
2.start telegraf
3.look at telegraf status
...

### Expected behavior

I expected the fields per the documentation

### Actual behavior

fields not found. 
Using mosquitto_sub, different structures are being passed:
telemetry/mahali-sdr-rx-002/nstat {"fields":{"Icmp6InCsumErrors":0,"Icmp6InDestUnreachs":0,"Icmp6InEchoReplies":0,"Icmp6InEchos":0,"Icmp6InErrors":0,"Icmp6InGroupMembQueries":0,"Icmp6InGroupMembReductions":0,"Icmp6InGroupMembResponses":0,"Icmp6InMLDv2Reports":4,"Icmp6InMsgs":251,"Icmp6InNeighborAdvertisements":247,"Icmp6InNeighborSolicits":0,"Icmp6InParmProblems":0,"Icmp6InPktTooBigs":0,"Icmp6InRedirects":0,"Icmp6InRouterAdvertisements":0,"Icmp6InRouterSolicits":0,"Icmp6InTimeExcds":0,"Icmp6InType136":247,"Icmp6InType143":4,"Icmp6OutDestUnreachs":0,"Icmp6OutEchoReplies":0,"Icmp6OutEchos":0,"Icmp6OutErrors":0,"Icmp6OutGroupMembQueries":0,"Icmp6OutGroupMembReductions":0,"Icmp6OutGroupMembResponses":0,"Icmp6OutMLDv2Reports":12,"Icmp6OutMsgs":19,"Icmp6OutNeighborAdvertisements":0,"Icmp6OutNeighborSolicits":1,"Icmp6OutParmProblems":0,"Icmp6OutPktTooBigs":0,"Icmp6OutRedirects":0,"Icmp6OutRouterAdvertisements":0,"Icmp6OutRouterSolicits":6,"Icmp6OutTimeExcds":0,"Icmp6OutType133":6,"Icmp6OutType135":1,"Icmp6OutType143":12,"Ip6FragCreates":0,"Ip6FragFails":0,"Ip6FragOKs":0,"Ip6InAddrErrors":0,"Ip6InBcastOctets":0,"Ip6InCEPkts":0,"Ip6InDelivers":140689,"Ip6InDiscards":0,"Ip6InECT0Pkts":0,"Ip6InECT1Pkts":0,"Ip6InHdrErrors":0,"Ip6InMcastOctets":31482340,"Ip6InMcastPkts":148015,"Ip6InNoECTPkts":148616,"Ip6InNoRoutes":0,"Ip6InOctets":31524413,"Ip6InReceives":148616,"Ip6InTooBigErrors":0,"Ip6InTruncatedPkts":0,"Ip6InUnknownProtos":0,"Ip6OutBcastOctets":0,"Ip6OutDiscards":271,"Ip6OutForwDatagrams":0,"Ip6OutMcastOctets":59298,"Ip6OutMcastPkts":333,"Ip6OutNoRoutes":24745,"Ip6OutOctets":126476,"Ip6OutRequests":1201,"Ip6ReasmFails":0,"Ip6ReasmOKs":0,"Ip6ReasmReqds":0,"Ip6ReasmTimeout":0,"Udp6IgnoredMulti":0,"Udp6InCsumErrors":0,"Udp6InDatagrams":139842,"Udp6InErrors":0,"Udp6NoPorts":0,"Udp6OutDatagrams":315,"Udp6RcvbufErrors":0,"Udp6SndbufErrors":0,"UdpLite6InCsumErrors":0,"UdpLite6InDatagrams":0,"UdpLite6InErrors":0,"UdpLite6NoPorts":0,"UdpLite6OutDatagrams":0,"UdpLite6RcvbufErrors":0,"UdpLite6SndbufErrors":0},"name":"telemetry/mahali-sdr-rx-002/nstat","tags":{"host":"EAC-5000","name":"snmp6"},"timestamp":1709560200}

### Additional info

I could add these fields but really different things are showing up at different times
