### ISSUE TITLE
When a RR does not exist anymore telegraf inputs.dns_query produces errors in its logfile.

### ISSUE THREAD

**Issue by maintain3r** [influxdata/telegraf#14941]
### Relevant telegraf.conf

```toml
[[outputs.prometheus_client]]
  listen = ":9303"
  path = "/metrics"
  collectors_exclude = ["gocollector", "process"]
  export_timestamp = false

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[inputs.dns_query]]
  servers = ["1.1.1.1"]
  network = "udp"
  timeout = 1
  port = 53
  record_type = "A"
  domains = [
              "qwe.example.com",
            ]
```

### Logs from Telegraf

```text
2024-03-05T21:09:20Z E! [inputs.dns_query] Error in plugin: Invalid answer (NXDOMAIN) from 1.1.1.1 after A query for qwe.example.com
```

### System info

Telegraf 1.12.6

### Steps to reproduce

Get Telegraf 1.12.6 and use config provided in this ticket.
Run telegraf with the config provided. It can be a telegraf docker img.
Check for the logs coming out of telegraf.

### Expected behavior

 Expected behaviour  is just to reflect the fact in the metric dns_query_rcode_value with  rcode="NXDOMAIN" and result="error".
 Maybe there's a way to prevent the plugin from logging?

### Actual behavior

2024-03-05T21:09:20Z E! [inputs.dns_query] Error in plugin: Invalid answer (NXDOMAIN) from 1.1.1.1 after A query for qwe.example.com

### Additional info

Many thanks!
