### ISSUE TITLE
Kapacitor Alert Parsing

### ISSUE THREAD

**Issue by forestmvey** [influxdata/telegraf#14976]
### Use Case

json
```
    "data": {
        "series": [
            {
                "name": "measure_name",
                "tags": {
                    "tag_key_1": "tag_val_1",
                    "tag_key_2": "tag_val_2"
                },
                "columns": [
                    "time",
                    "field_key_1",
                    "field_key_2"
                ],
                "values": [
                    [
                        "2024-02-08T17:30:32Z",
                        11,
                        99.99
                    ]
                ]
            }
        ]
    }
```

### Expected behavior

Expected line protocol output:

```
measure_name,tag_key_1=tag_val_1,tag_key_2=tag_val_2 field_key_1=11,field_key_2=99.99 1707413432000000000
```

### Actual behavior

Unable to figure out how to parse this using JSON, JSON_V2, or XPATH parsers.

### Additional info

Kapacitor alerts send the dataset of the measure that triggered the alert in this JSON format.

**Comment by forestmvey** [comment]
Note I was able to resolve this issue as well with the starlark processor. Here is my fix:

```
[[processors.starlark]]
  source = '''
load("json.star", "json")
load("logging.star", "log")
load("time.star", "time")

# The 0 index of columns is always timestamp
TIMESTAMP_COLUMN_INDEX = 0

# Beginning at index 1 of columns is the list of field_set keys
INITIAL_COLUMNS_FIELD_INDEX = 1


def apply(metric):

    j = json.decode(metric.fields.get("value"))
    metrics = []
    for measure in j["data"]["series"]:

        for field_set in measure["values"]:
            fields = {}
            counter = INITIAL_COLUMNS_FIELD_INDEX
            measure_timestamp = time.parse_time(field_set[TIMESTAMP_COLUMN_INDEX], format="2006-01-02T15:04:05Z").unix_nano
            for field in measure["columns"][INITIAL_COLUMNS_FIELD_INDEX:]:
                fields[field] = field_set[counter]
                counter += 1
            new_metric = Metric(measure["name"], tags=measure["tags"], fields=fields)
            new_metric.time = measure_timestamp
            metrics.append(new_metric)

    log.debug("result: {}".format(metrics))
    
    return metrics
'''
```

**Comment by srebhan** [comment]
@forestmvey thanks for filing this issue. The problem is in the upstream library and I already submitted a fix as https://github.com/antchfx/jsonquery/pull/18.

**Comment by srebhan** [comment]
@forestmvey the upstream PR is merged and I prepared #15004 to update the library. Please test the binary of the pull-request, available once CI finished the tests, and let me know if it works with the below config:

```toml
[[inputs.file]]
  files = ["test_configs/jsontest_slack_ForestVey.json"]
  data_format = "xpath_json"
  xpath_print_document = true

  [[inputs.file.xpath]]
    timestamp = "/time"
    timestamp_format = "2006-01-02T15:04:05Z"
    metric_name = "//name"
    metric_selection = "//data/series/*"
    tag_selection = "tags/*"
    field_selection = "descendant::*[not(*)]"

[[processors.starlark]]
  source = '''
def apply(metric):
  fields = [k for k in metric.fields.keys() if k.startswith("values")]

  for k in fields:
    idx = ""
    parts = k.rsplit("_", 1)
    if len(parts) == 2:
      idx = "_"+parts[1]

    name = metric.fields.pop("columns"+idx)
    metric.fields[name] = metric.fields.pop(k)

  return metric
'''
```

We need starlark because we cannot "zip" the two arrays as the XPath parser is stateless...

**Comment by forestmvey** [comment]
@srebhan Thank you very much for the fix. This change did resolve my issue, and I did one quick change to your starlark processor that was required to get the metric time set correctly.

```
[[processors.starlark]]
  source = '''
load("time.star", "time")
def apply(metric):
  fields = [k for k in metric.fields.keys() if k.startswith("values")]
  timestamp_set = False

  for k in fields:
    idx = ""
    parts = k.rsplit("_", 1)
    if len(parts) == 2:
      idx = "_"+parts[1]

    name = metric.fields.pop("columns"+idx)
    if name == "time":
      metric.time = time.parse_time(metric.fields.pop(k), format="2006-01-02T15:04:05Z").unix
      continue
    metric.fields[name] = metric.fields.pop(k)

  return metric
'''
```

**Comment by srebhan** [comment]
@forestmvey unfortunately the upstream fix broke other metrics so I needed to revert. However, I think the above configuration also works with currently released Telegraf versions. Could you please try e.g. v1.30.0 and close this issue if it works?!?

**Comment by forestmvey** [comment]
@srebhan I tested again on a build from master - Telegraf 1.31.0-6e8e7e5c (git: master@6e8e7e5c).

Unfortunately the configuration you noted [here](https://github.com/influxdata/telegraf/issues/14976#issuecomment-2000225767) did not produce the expected output.

Unexpected output:
```
measure_name,host=...,tag_key_1=tag_val_1,tag_key_2=tag_val_2 columns_0="time",tag_key_1="tag_val_1",_0="2024-02-08T17:30:32Z",_1="11",columns_1="field_key_1",columns_2="field_key_2",name="measure_name",tag_key_2="tag_val_2",_2="99.99" 1711664735000000000
```

**Comment by srebhan** [comment]
@forestmvey you need to adapt the config slightly:
```toml
[[inputs.file]]
  fieldexclude = ["name", "time", "tag_*"]
  files = ["test_configs/json_issue_14976.json"]
  data_format = "xpath_json"
  xpath_native_types = true
  
  [[inputs.file.xpath]]
    timestamp = "/time"
    timestamp_format = "2006-01-02T15:04:05Z"
    metric_name = "//name"
    metric_selection = "//data/series/*"
    tag_selection = "tags/*"
    field_selection = "descendant::*[not(*)]"

[[processors.starlark]]
  source = '''
def apply(metric):
  fields = [k for k in metric.fields.keys() if k.startswith("_")]

  for k in fields:
    name = metric.fields.pop("columns"+k)
    metric.fields[name] = metric.fields.pop(k)

  return metric
'''
```
