### ISSUE TITLE
Docker Secretstore Require Root

### ISSUE THREAD

**Issue by DaAwesomeP** [influxdata/telegraf#14997]
### Relevant telegraf.conf

```toml
[[secretstores.docker]]
  id = "docker_secretstore"

[[outputs.influxdb]]
  urls = ["${INFLUX_URL}"]
  skip_database_creation = ${INFLUX_SKIP_DATABASE_CREATION}
  database = "${INFLUX_DB}"
  username = "@{docker_secretstore:influxdb_user}"
  password = "@{docker_secretstore:influxdb_password}"
```

### Logs from Telegraf

```text
Attaching to telegraf-1
telegraf-1  | 2024-03-15T05:43:51Z I! Loading config: /etc/telegraf/telegraf.conf
telegraf-1  | 2024-03-15T05:43:51Z I! Loading config: /etc/telegraf/telegraf.d/outputs.influxdb.conf
telegraf-1  | 2024-03-15T05:43:51Z I! Loading config: /etc/telegraf/telegraf.d/secretstores.docker_secretstore.conf
telegraf-1  | 2024-03-15T05:43:51Z E! retrieving resolver failed: linking secrets failed: resolving "@{docker_secretstore:influxdb_user}" failed: cannot read the secret's value under the directory: open /run/secrets/influxdb_user: permission denied
telegraf-1 exited with code 0
```

### System info

Telegraf 1.29, Docker version 25.0.4, build 1a576c5

### Docker

```yaml
version: "3.8"
services:
  telegraf:
    image: telegraf:1.29
    ports: []
    restart: always
    environment:
      INFLUX_SKIP_DATABASE_CREATION: "true"
      INFLUX_URL: 'unix:///path/to/my.sock'
      INFLUX_DB: 'my-db'
    networks:
      - telegraf
    volumes:
      - ./telegraf/etc/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/etc/telegraf/telegraf.d/:/etc/telegraf/telegraf.d/:ro
      - /path/to/my.sock:/path/to/my.sock
    secrets:
       - influxdb_user
       - influxdb_password
networks:
  telegraf:
secrets:
  influxdb_user:
    file: ./secrets/influxdb_user.txt
  influxdb_password:
    file: ./secrets/influxdb_password.txt
```

### Steps to reproduce

1. Run the `docker compose up` with the config above
2. See error

### Expected behavior

Telegraf should be able to read Docker secrets

### Actual behavior

Telegraf cannot read secrets because it is running as the `telegraf` user (UID 999), but the secrets files may only be read by root:
```
$ ls -al /run/secrets/influxdb_user 
-rw-r----- 1 root root 57 Mar 15 05:17 /run/secrets/influxdb_user
```

### Additional info

Possible solution from https://stackoverflow.com/a/65787066:

```
RUN --mount=type=secret,id=secrets,uid=999 cat /run/secrets
```

**Comment by DaAwesomeP** [comment]
I also tried:
```yaml
secrets:
   - source: influxdb_user
     uid: "999"
     gid: "999"
   - source: influxdb_password
     uid: "999"
     gid: "999"
```
but it did not work:
```
WARN[0000] secrets `uid`, `gid` and `mode` are not supported, they will be ignored 
WARN[0000] secrets `uid`, `gid` and `mode` are not supported, they will be ignored
```
