### ISSUE TITLE
inputs.knx_listener is writing wrong "source" tag

### ISSUE THREAD

**Issue by userwithoutpassword** [influxdata/telegraf#15006]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "Âµs"), "ms", "s".
  precision = ""

  
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://127.0.0.1:8086"]

  ## Token for authentication.
  token = 

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "Home"

  ## Destination bucket to write into.
  bucket = "knx"









# Listener capable of handling KNX bus messages provided through a KNX-IP Interface.
[[inputs.knx_listener]]
  ## Type of KNX-IP interface.
  ## Can be either "tunnel" or "router".
  service_type = "tunnel"

  ## Address of the KNX-IP interface.
  service_address = "192.168.1.106:3671"




[[inputs.knx_listener.measurement]]
  name = "Alarm"
  dpt = "1.005"
  addresses = ["0/2/2", # Windalarm (Markise)
               "0/2/3",  # Windalarm (Raffstores)
               "0/2/4"] # Regenalarm
```

### Logs from Telegraf

```text
Actual behavior
```

### System info

Telegraf 1.19.0+

### Steps to reproduce

Actual behavior

### Expected behavior

GroupValue_Read messages should been ignored because there is no valid payload data

### Actual behavior

When Im using DPT 1.005
knx listener
![Screenshot 2024-03-16 144056](https://github.com/influxdata/telegraf/assets/146129024/62b8b6b4-1b5b-4f98-bbc2-8fca8fb09004)
![Screenshot 2024-03-16 163431](https://github.com/influxdata/telegraf/assets/146129024/e429352c-e615-47cc-951e-830fbabc9912)
![Screenshot 2024-03-16 170011](https://github.com/influxdata/telegraf/assets/146129024/40212051-abe9-49b6-b6b8-f18771c10a42)
 is writing wrong source tag in some situations.

Situation: my sensor is having PA 1.1.50.
At the same time im using ETS6 connected to my KNX-IP Interface (Gira X1) via tunneling connection, having PA 1.1.6

Now i do a "GroupValue_Read" for example on 0/2/2. my Sensor (1.1.50) is responding via GroupValue_Response with its address. But in telegraf im getting 1.1.6 as source tag, but it has to be 1.1.50 instead.

For now other DPTs dont have this problem. First time I notice this but only with DPT 1.005.

I looks like knx-go is taking the PA from the GroupValue_Read message but the correct address is in the GroupValue_Response message
