### ISSUE TITLE
[inputs.mongodb] All nodes are set to PRIMARY (state) (even for secondary one)

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#15002]
### Relevant telegraf.conf

```toml
[[inputs.mongodb]]                                                                                                                                                                                                gather_cluster_status = true
gather_cluster_status = true
gather_perdb_stats = true
disconnected_servers_behavior = "skip"
```

### Logs from Telegraf

```text
NC
```

### System info

1.29-alpine, K8S 1.28 via telegraf operator

### Docker

Using bitnami mongodb chart with these values:
```yaml
architecture: replicaset
auth:
  enabled: false
directoryPerDB: true
podAnnotations: {
  "prometheus.io/port": "9273",
  "prometheus.io/scrape": "true",
  "telegraf.influxdata.com/class": "XXXX",
  "telegraf.influxdata.com/inputs": "[[inputs.mongodb]]\n  gather_cluster_status = true\n  gather_perdb_stats = true\n  disconnected_servers_behavior = \"skip\"",
}
networkPolicy:
  enabled: false
```

### Steps to reproduce

1. Install the helm chart
2. Once it's init, all node are set to PRIMARY

### Expected behavior

I guess:
filtered:
mongodb,host=mongodb-1,hostname=127.0.0.1:27017,node_type=SEC,rs_name=rs0,member_status="SEC",state="SECONDARY",state=2i 1710501321000000000

### Actual behavior

filtered:
mongodb,host=mongodb-1,hostname=127.0.0.1:27017,node_type=PRI,rs_name=rs0,member_status="PRI",state="PRIMARY",state=1i 1710501321000000000

### Additional info
rs.status on secondary node:
```json
  members: [
    {
      _id: 0,
      name: 'mongodb-0XXXXXXXXXXXX',
      health: 1,
      state: 1,
      stateStr: 'PRIMARY',
    },
    {
      _id: 1,
      name: 'mongodb-1XXXXXXXXXXXXX',
      health: 1,
      state: 2,
      stateStr: 'SECONDARY',
    }
  ],
```
