### ISSUE TITLE
outputs.sql not accepting bool type conversion

### ISSUE THREAD

**Issue by Ghandi256** [influxdata/telegraf#15022]
### Relevant telegraf.conf

```toml
[[outputs.sql]]
   convert = {timestamp = "datetime", real = "float", integer = "bigint", defaultvalue = "NVARCHAR(Max)", text = "NVARCHAR(Max)", bool = "bit"}
```

### Logs from Telegraf

```text
2024-03-19T14:38:26Z E! [telegraf] Error running agent: Error loading config file C:\Program Files\Telegraf\telegraf.conf: plugin outputs.sql: line 211: configuration specified the fields ["bool"], but they weren't used
```

### System info

1.19.2

### Steps to reproduce

1. Utilize the SQL output plugin and try to remap the bool datatype to anything else

### Expected behavior

Should be able to remap datatype to other values

### Actual behavior

Not passing as a valid config field.

### Additional info

Example text even includes this datatype as valid to remap.

  #[outputs.sql.convert]
  #  integer              = "INT"
  #  real                 = "DOUBLE"
  #  text                 = "TEXT"
  #  timestamp            = "TIMESTAMP"
  #  defaultvalue         = "TEXT"
  #  unsigned             = "UNSIGNED"
  #  bool                 = "BOOL"

I tried both the table formatting as in the example text, at the bottom of the config, per the note:

  ## NOTE: Due to the way TOML is parsed, tables must be at the END of the
  ## plugin definition, otherwise additional config options are read as part of
  ## the table

Same result no matter the formatting.
