### ISSUE TITLE
pprof does not work for custom builds?

### ISSUE THREAD

**Issue by rebrendov** [influxdata/telegraf#15053]
### Relevant telegraf.conf

```toml
`telegraf --config-directory local/telegraf --pprof-addr 0.0.0.0:6060`
```

### Logs from Telegraf

```text
...
2024-03-23T08:09:17Z I! Starting pprof HTTP server at: http://0.0.0.0:6060/debug/pprof
...
```

### System info

not relevant

### Steps to reproduce

1. Run telegraf with default config and `--pprof-addr localhost:6060`.
2. Go to http://localhost:6060/debug/pprof/.
3. Get 404.
Additionally:
1. Check docs/PROFILING.md: `Telegraf uses the standard package net/http/pprof`.
2. Search code for mentions of net/http/pprof.

### Expected behavior

net/http/pprof registers endpoints on /debug/pprof

### Actual behavior

net/http/pprof is lost to the void, doesn't register anything.

**Comment by srebhan** [comment]
Hmmm work for me on current master... I used the following config for testing

```toml
[agent]
interval = "1m"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 75000
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
precision = ""
hostname = ""
omit_hostname = false

[[inputs.cpu]]

[[outputs.file]]
  files = ["stdout"]
```

and ran `/telegraf --config test.conf --debug --pprof-addr localhost:6060` and get a page on 

http://localhost:6060/debug/pprof/
