### ISSUE TITLE
Prometheus input plugin fails to parse 'info' type

### ISSUE THREAD

**Issue by aaronkvanmeerten** [influxdata/telegraf#15055]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  http_headers = {"Accept" = "application/openmetrics-text"}
  [inputs.prometheus.consul]
    enabled = true
    agent = "{{ env "attr.unique.network.ip-address" }}:8500"
    query_interval = "1m"
    [[inputs.prometheus.consul.query]]
      name = "jicofo"
      tag = "ip-{{ env "attr.unique.network.ip-address" }}"
      url = 'http://{{"{{"}}if ne .ServiceAddress ""}}{{"{{"}}.ServiceAddress}}{{"{{"}}else}}{{"{{"}}.Address}}{{"{{"}}end}}:{{"{{"}}.ServicePort}}/{{"{{"}}with .ServiceMeta.metrics_path}}{{"{{"}}.}}{{"{{"}}else}}metrics{{"{{"}}end}}'
      [inputs.prometheus.consul.query.tags]
        host = "{{"{{"}}.Node}}"
        shard = "{{"{{"}}with .ServiceMeta.shard}}{{"{{"}}.}}{{"{{"}}else}}shard{{"{{"}}end}}"
        release_number = "{{"{{"}}with .ServiceMeta.release_number}}{{"{{"}}.}}{{"{{"}}else}}0{{"{{"}}end}}"
        shard-role = "core"
        role = "core"
```

### Logs from Telegraf

```text
2024-03-25T12:45:23Z E! [inputs.prometheus] Error in plugin: error reading metrics for "http://10.84.70.39:27884/metrics": reading text format failed: text format parsing error in line 54: unknown metric type "info"
```

### System info

Telegraf 1.29.5 and 1.28.5 in docker, scraping other services in docker on the same node

### Docker

Running in host network mode in docker in nomad.  Example nomad snippet below:
```
      config {
        network_mode = "host"
        privileged = true
        image        = "telegraf:1.29.5"
        ports = ["telegraf-statsd","telegraf-prometheus"]
        volumes = ["local/telegraf.conf:/etc/telegraf/telegraf.conf", "local/consul-resolved.conf:/etc/systemd/resolved.conf.d/consul.conf", "/var/run/docker.sock:/var/run/docker.sock"]
      }
      env {
	    HOST_ETC = "/hostfs/etc"
	    HOST_PROC = "/hostfs/proc"
	    HOST_SYS = "/hostfs/sys"
	    HOST_VAR = "/hostfs/var"
	    HOST_RUN = "/hostfs/run"
	    HOST_MOUNT_PREFIX = "/hostfs"
      }
```

### Steps to reproduce

1. Point telegraf to a prometheus scraping endpoint that includes an info reading
2. Start container and wait for scraping to be discovered and occur
3. See that metrics aren't parsed properly
...

### Expected behavior

Expected that prometheus parser would accept 'info' type as defined here:

https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#info

### Actual behavior

The prometheus input plugin gives the following output:

2024-03-25T12:45:23Z E! [inputs.prometheus] Error in plugin: error reading metrics for "http://10.84.70.39:27884/metrics": reading text format failed: text format parsing error in line 54: unknown metric type "info"

### Additional info

Line 54 in this case reads:

# TYPE jitsi_jvb_region info
# HELP jitsi_jvb_region The currently configured region.
jitsi_jvb_region_info{region="us-phoenix-1"} 1.0
