### ISSUE TITLE
Filter out unnecessary integer from telegraf json

### ISSUE THREAD

**Issue by JW623** [influxdata/telegraf#15067]
Hi i would like to filter out unnecessary integer from my telegraf. I have tried namedrop, tagdrop, tagexclude but does not seems work for me. any solutions for filtering integer?

**Comment by srebhan** [comment]
@JW623 without seeing the JSON input data, your (redacted) configuration and the output you expect it is really hard to say anything... Please also use the support channels suggested by our bot (forum & slack) for support questions like this!

**Comment by JW623** [comment]
> @JW623 without seeing the JSON input data, your (redacted) configuration and the output you expect it is really hard to say anything... Please also use the support channels suggested by our bot (forum & slack) for support questions like this!

Sorry my bad, here is my telegraf configuration
[[inputs.file]]
files = [""]
tagexclude = ["Status"]
data_format = "json"
tag_keys = ["Client", "Asset", "Tag", "Timestamp"]
json_time_key = "Timestamp"
json_time_format = "2006-01-02 02:00:00.0000000"
tagdrop = ["Status"]
  
[[outputs.postgresql]]
 connection = "host=localhost user=s password= dbname="

    schema = "public"
	name_override = ""

my json data
[
	{
		"Client": "B",
		"Asset": "ABCASSET",
		"Tag": "ABCTAG",
		"Value": 12.1235,
		"Status": 192,
		"Timestamp": "2023-08-17 02:00:00.0000000"
	},
	{
		"Client": "A",
		"Asset": "ABCASSET",
		"Tag": "ABCTAG",
		"Value": 13.1235,
		"Status": 192,
		"Timestamp": "2023-08-17 02:00:00.0000000"
	},
	{
		"Client": "B",
		"Asset": "ABCASSET",
		"Tag": "ABCTAG",
		"Value": 13.1235,
		"Status": 192,
		"Timestamp": "2023-08-17 03:00:00.0000000"
	},
	{
		"Client": "A",
		"Asset": "ABCASSET",
		"Tag": "ABCTAG",
		"Value": 14.1235,
		"Status": 192,
		"Timestamp": "2023-08-17 03:00:00.0000000"
	}
]

i would like to ignore Status from my data collection

**Comment by srebhan** [comment]
`Status` is not a **tag** but a **field** so using
```toml
[[inputs.file]]
  files = ["test_configs/jsontest_issue_15067.json"]
  data_format = "json"
  tag_keys = ["Client", "Asset", "Tag", "Timestamp"]
  json_time_key = "Timestamp"
  json_time_format = "2006-01-02 02:00:00.0000000"

  fieldexclude = ["Status"]
```
will solve your issue!
