### ISSUE TITLE
Timestamp date is not correct

### ISSUE THREAD

**Issue by JW623** [influxdata/telegraf#15068]
### Relevant telegraf.conf

```toml
[[inputs.file]]
files = [""]
tagexclude = ["Status"]
data_format = "json"
tag_keys = ["Client", "Asset", "Tag", "Timestamp"]
json_time_key = "Timestamp"
json_time_format = "2006-01-02 02:00:00.0000000"
tagdrop = ["Status"]
  
[[outputs.postgresql]]
 connection = "host=localhost user=s password= dbname="

    schema = "public"
	name_override = ""
```

### Logs from Telegraf

```text
Json Data:

{
		"Client": "B",
		"Asset": "ABCASSET",
		"Tag": "ABCTAG",
		"Value": 12.1235,
		"Status": 192,
		"Timestamp": "2023-08-17 02:00:00.0000000"
	}
```

### System info

telegraf 1.30.0

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

expected timestamp should be 2023-08-17 02:00:00.0000000

### Actual behavior

but somehow in PostgreSQL shows "2023-08-02 00:00:00"
