### ISSUE TITLE
Missing NetFlow Option packets

### ISSUE THREAD

**Issue by SirBreadc** [influxdata/telegraf#15075]
### Relevant telegraf.conf

```toml
[global_tags]
  VM = "${HOSTNAME}"

[agent]
  debug = false
  quiet = true
  metric_batch_size = 5000

  metric_buffer_limit = 2000000

  flush_interval = "1s"
 
  flush_jitter = "5s"

  precision = "0s"



  hostname = "${HOST_HOSTNAME}"
  omit_hostname = false

# Netflow v5, Netflow v9 and IPFIX collector
[[inputs.netflow]]

  service_address = "udp4://:2055"
  

  protocol = "ipfix"


  private_enterprise_number_files = ["conf/custom_fields.csv"]

  dump_packets = false

# # Configuration for sending metrics to InfluxDB 2.0
[[outputs.influxdb_v2]]
   
   urls = ["host1","host2","host3"]

   token = "{INFLUXADMINTOKEN}"

   organization = "org"
   namepass = ["netflow"]

   bucket = "${BUCKET_NAME}"
   content_encoding = "gzip"
   timeout = "15s"

    insecure_skip_verify = true
```

### Logs from Telegraf

```text
See attached file
```

### System info

Telegraf 1.30, Centos,CentOS Linux 7

### Steps to reproduce

1. Send Netflow from device.

### Expected behavior

Option packets are also writen to output

### Actual behavior

Option packets are not written to outputs
