### ISSUE TITLE
wrong timestamp in line protocol "influx" file input

### ISSUE THREAD

**Issue by RodrigoDornelles** [influxdata/telegraf#15120]
### Relevant telegraf.conf

```toml
[[inputs.file]]
  files = ["/logs/*.log"]
  data_format = "influx"

[[outputs.file]]
  files = ["stdout"]
  data_format = "json"
```

### Logs from Telegraf

```text
{"fields":{"data":"IiI==","foo":"bar"},"name":"index_name","tags":{"zip":"zap"},"timestamp":2}
2024-04-08T17:59:42Z D! [outputs.file] Wrote batch of 1 metrics in 317.708µs
```

### System info

Linux 5.15, Docker 26.0, Telegraf 1.30.1

### Steps to reproduce

write an file log like:
```
index_name,data=IiI==,foo=bar zip="zap" 1711190482
```

### Expected behavior

1711190482 in the unixtimestamp json.

### Actual behavior

wrong date!
