### ISSUE TITLE
feat: exclude tags or fields after input

### ISSUE THREAD

**Issue by RodrigoDornelles** [influxdata/telegraf#15131]
### Use Case

I'm loading my fields in base64 from a json, I believe the resource must exist and lack documentation, if it's not very important, I would like to eliminate a field after being used as part of processing.

```toml
[[processors.string.base64decode]]
  field = "data"

[[processors.parser]]
  parse_fields = ["data"]
  merge = "override"
  data_format = "json"
```

### example 1

```toml
[[processors.string.base64decode]]
  field = "data"

[[processors.parser]]
  parse_fields = ["data"]
  merge = "override"
  data_format = "json"
  
[[processor.remove]]
  fields=["data"]
```

### Actual behavior

 _

### Additional info

related #
