### ISSUE TITLE
feat(processors.parser): Add base64 decode option

### ISSUE THREAD

**Issue by RodrigoDornelles** [influxdata/telegraf#15130]
### Use Case

can be used to decode in specific fields, remove old fields parsed and add preffix/suffix.

#### actual 

```toml
[[processors.strings]]
  [[processors.strings.base64decode]]
    field = "data"

[[processors.parser]]
  parse_fields = ["data"]
  merge = "override"
  data_format = "json"
```

#### proposal

```toml
[[processors.parser]]
  parse_fields = ["data"]
  merge = "override"
  data_format = "json"
  json_base64_decode = true 
  json_exclude_fields = true
  json_prefix_fields = "new_"

[[processors.parser]]
  parse_fields = ["data_old"]
  merge = "override"
  data_format = "json"
  json_base64_decode = true 
  json_exclude_fields = true
  json_prefix_fields = "old_"
```

### Expected behavior

which base-64 decodes before reading the json string.

### Actual behavior

-

### Additional info

It is interesting because when using a cross data format, it can end up shortening the work. such as a jsonbase64 field in my line protocol (influx).
