### ISSUE TITLE
feat: add path tag to file input

### ISSUE THREAD

**Issue by RodrigoDornelles** [influxdata/telegraf#15133]
### Use Case

my use case would be as follows, I am using the `hostname` of the container in the folder path, I would like to retrieve it as `host` in my indexing. I think it would be interesting to have a `path_tag` configuration to extract this! or `file_tag_fullname` to set to `true` or `false` to get all filepath name with file.

### Expected behavior

```toml
[[inputs.file]]
  files = ["/logs/*/*.log"]
  file_tag = "system"
  path_tag = "host"
  influx_timestamp_precision = "1s"

[[processors.regex]]
 [[processors.regex.tags]]
    key = "system"
    pattern = "^([a-z0-9]+)(-.+)"
    replacement = "${1}"
 [[processors.regex.tags]]
    key = "host"
    pattern = "^/logs/(\\w+)/$"
    replacement = "${1}"
```

get tags `system` and `host`

### Actual behavior

only can get file.
