### ISSUE TITLE
Scale processor example doesn't work

### ISSUE THREAD

**Issue by llamafilm** [influxdata/telegraf#15134]
### Relevant telegraf.conf

```toml
[[processors.scale]]
  [processors.scale.scaling]
    factor = 10.0
    offset = -5.0
    fields = ["voltage*"]
```

### Logs from Telegraf

```text
2024-04-10T06:54:06Z E! error loading config file barco-temp.conf: error parsing scale, unmarshalling failed: line 63: cannot unmarshal TOML table into []scale.Scaling (need struct or map)
```

### System info

Telegraf 1.29.2

### Steps to reproduce

1. Run telegraf with some input plugin and this processor block

### Expected behavior

no error

### Actual behavior

errors

### Additional info

The example TOML given in the [scale processor documentation](https://github.com/influxdata/telegraf/blob/release-1.29/plugins/processors/scale/README.md) doesn't work.  I had to add another square bracket to fix it:
```diff
-  [processors.scale.scaling]
+  [[processors.scale.scaling]]
```
