### ISSUE TITLE
[aggregators.derivative] plugin not working

### ISSUE THREAD

**Issue by PriD98** [influxdata/telegraf#15156]
### Relevant telegraf.conf

```toml
## Read metrics about disk IO by device
[[inputs.diskio]]
  # no custom configuration

# Read metrics about memory usage
[[inputs.mem]]
  # no custom configuration

[[aggregators.derivative]]
  ## Specific Derivative Aggregator Arguments:

  ## Configure a custom derivation variable. Timestamp is used if none is given.
  # variable = ""

  ## Suffix to add to the field name for the derivative name.
  # suffix = "_rate"

  ## Roll-Over last measurement to first measurement of next period
  # max_roll_over = 10

  ## General Aggregator Arguments:

  ## calculate derivative every 30 seconds
  period = "30s"
```

### Logs from Telegraf

```text
CPU1:horizpd8-uksouth-peri1:/etc/opt/MetaSwitch/geneva$ telegraf --debug
2024-04-15T14:28:19Z I! Loading config: /etc/telegraf/telegraf.conf
2024-04-15T14:28:19Z E! [telegraf] Error running agent: no outputs found, did you provide a valid config file?


Unsure why I'm getting this error when I try to run telegraf --debug
```

### System info

Telegraf v1.30.1, Ubuntu 20.04, Docker version 20.10.27

### Steps to reproduce

1. Added the attached config to the telegraf.conf file
2. "systemctl restart telegraf"
3. ran "telegraf.conf --test" command to print output
4. did not see the derivative stats appearing

### Expected behavior

I expected derivative stats to appear when running 'telegraf --test'

### Actual behavior

seeing the same stats that I saw before I added the [[aggregators.derivative]] config block to telegraf.conf

### Additional info

I've simplified the config file to just the relevant bits above, but fundamentally the [[aggregators.derivative]] plugin doesn't seem to be working. 

As a test, I tried replacing the [[aggregators.derivative]] config block with [[aggregators.basicstats]]. I did this to check if the indentation/positioning of the config block was correct. This gave the expected output. So it seems to be something specific with the [[aggregators.derivative]] plugin.
