### ISSUE TITLE
inputs.prometheus - http_headers - host header ignored

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#15192]
### Relevant telegraf.conf

```toml
[[inputs.prometheus]]
  urls = ["http://127.0.0.1/metrics"]
  http_headers = {"host" = "example.org"}
```

### Logs from Telegraf

```text
NC
```

### System info

telegraf 1.29, k8s 1.28

### Steps to reproduce

1. telegraf --test

### Expected behavior

The Host header is forwarded

### Actual behavior

The Host header is not forwarded

### Additional info

The goal is request the pod itself via sidecar based on a specific virtual host.

Currently, if I try curl -H 'Host: example.org' http://127.0.0.1/metrics, I can extract datas.

But with telegraf, the Host is not forwarded.
Host received from access log: localhost
