### ISSUE TITLE
Telegraf doesnt fully reload configuration upon file addition/deletion

### ISSUE THREAD

**Issue by Andrene** [influxdata/telegraf#15210]
### Relevant telegraf.conf

```toml
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 10000

  metric_buffer_limit = 100000

  collection_jitter = "0s"

  flush_interval = "10s"

  flush_jitter = "0s"

  precision = "0s"

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
```

### Logs from Telegraf

```text
2024-04-23T01:44:40Z E! [inputs.gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp x.x.x.x:x: i/o timeout"
2024-04-23T01:44:47Z W! Config file deleted
2024-04-23T01:45:10Z E! [inputs.gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp x.x.x.x:x: i/o timeout"
```

### System info

Telegraf 1.30.1, RHEL 9

### Steps to reproduce

1. Launch telegraf `telegraf --watch-config poll --config-directory /home/user/telegraf.conf.d/`
2. Add and or delete a input file from /home/user/telegraf.conf.d/, I was testing with gnmi
3. Notice that it hasnt reached out to the new host, nor has it stopped trying to reachout to an old host

### Expected behavior

If a config file is added to the watched directory then it's loaded and the device is polled
If a config file is deleted from the watched directory then its removed and the device is no longer polled

### Actual behavior

If a config file is added to the watched directory nothing is logged and the config file isnt loaded and the device isnt polled
If a config file is deleted the `2024-04-23T01:44:47Z W! Config file deleted` is logged and the config remains loaded and the device is continued to be polled
