### ISSUE TITLE
inputs.gnmi: Authentication Broken starting in 1.29.2

### ISSUE THREAD

**Issue by whizkidTRW** [influxdata/telegraf#15236]
### Relevant telegraf.conf

```toml
# Ciena gNMI
[agent]
  interval = "5m"
    
[[inputs.gnmi]]
  alias = "ciena-gnmi"
  addresses = [ "10.144.248.21:6702" ]
      
  username = "XXXXXXXXXXXXXXXXX"
  password = "XXXXXXXXXXXXXXXXX"
  encoding = "proto"
  redial = "10s"
  tls_enable = true
  insecure_skip_verify = true
  tls_ca = "/etc/telegraf/ciena-ca.cert.pem"
  tls_cert = "/etc/telegraf/ciena-client.cert.pem"
  tls_key = "/etc/telegraf/ciena-client.key.pem"
  name_override = "saos10xgnmi"
  updates_only = true
      
  fieldpass = [ "name","source","ifIndex","in_crc_error_pkts","in_discards","in_errors","in_octets","out_errors","out_octets" ]
  tagexclude = ["path"]

  [[inputs.gnmi.subscription]]
     name = "ifcounters"
     origin = "Ciena"
     path = "/oc-if:interfaces/oc-if:interface[name=9]/oc-if:state/oc-if:counters"
     subscription_mode = "sample"
     sample_interval = "30s"
  

[[processors.converter]]
    order = 1
    namepass = ["saos10xgnmi"]

    [processors.converter.fields]
        tag = ["name"]

[[processors.strings]]
    order = 2
    namepass = ["saos10xgnmi"]

    [[processors.strings.replace]]
        tag = "name"
        old = "\""
        new = ""

[[processors.rename]]
    order = 3
    namepass = ["saos10xgnmi"]

    [[processors.rename.replace]]
        field = "in_octets"
        dest = "ifHCInOctets"

    [[processors.rename.replace]]
        field = "out_octets"
        dest = "ifHCOutOctets"

    [[processors.rename.replace]]
        field = "in_errors"
        dest = "ifInErrors"

    [[processors.rename.replace]]
        field = "out_errors"
        dest = "ifOutErrors"

    [[processors.rename.replace]]
        field = "in_discards"
        dest = "ifInDiscards"

    [[processors.rename.replace]]
        field = "in_crc_error_pkts"
        dest = "ifInCrcErrors"

    [[processors.rename.replace]]
        tag = "name"
        dest = "ifIndex"

    [[processors.rename.replace]]
        tag = "source"
        dest = "agent_host"

    [[processors.rename.replace]]
        measurement = "saos10xgnmi"
        dest = "interface"
```

### Logs from Telegraf

```text
v1.29.1:
telegraf  | 2024-04-25T22:03:46Z I! Loading config: /etc/telegraf/telegraf.conf
telegraf  | 2024-04-25T22:03:46Z I! Loading config: /etc/telegraf/telegraf.d/ciena.conf
telegraf  | 2024-04-25T22:03:46Z W! DeprecationWarning: Option "fieldpass" of plugin "inputs.gnmi" deprecated since version 1.29.0 and will be removed in 2.0.0: use 'fieldinclude' instead
telegraf  | 2024-04-25T22:03:46Z I! Starting Telegraf 1.29.1 brought to you by InfluxData the makers of InfluxDB
telegraf  | 2024-04-25T22:03:46Z I! Available plugins: 241 inputs, 9 aggregators, 30 processors, 24 parsers, 60 outputs, 6 secret-stores
telegraf  | 2024-04-25T22:03:46Z I! Loaded inputs: gnmi
telegraf  | 2024-04-25T22:03:46Z I! Loaded aggregators: 
telegraf  | 2024-04-25T22:03:46Z I! Loaded processors: converter rename strings
telegraf  | 2024-04-25T22:03:46Z I! Loaded secretstores: 
telegraf  | 2024-04-25T22:03:46Z W! Outputs are not used in testing mode!
telegraf  | 2024-04-25T22:03:46Z I! Tags enabled: host=10.5.200.224
telegraf  | 2024-04-25T22:03:46Z D! [agent] Initializing plugins
telegraf  | 2024-04-25T22:03:46Z D! [inputs.gnmi::ciena-gnmi] Internal alias mapping: map[oc-if:/interfaces/oc-if:interface/oc-if:state/oc-if:counters:ifcounters]
telegraf  | 2024-04-25T22:03:46Z D! [agent] Starting service inputs

telegraf  | 2024-04-25T22:03:47Z D! [inputs.gnmi::ciena-gnmi] Connection to gNMI device 10.144.248.21:6702 established
telegraf  | > interface,agent_host=10.144.248.21,host=10.5.200.224,ifIndex=9 ifHCInOctets=0i,ifHCOutOctets=0i,ifInCrcErrors=0i,ifInDiscards=0i,ifInErrors=0i,ifOutErrors=0i 1714082658121000000

telegraf  | 2024-04-25T22:04:26Z D! [agent] Stopping service inputs
telegraf  | 2024-04-25T22:04:26Z D! [inputs.gnmi::ciena-gnmi] Connection to gNMI device 10.144.248.21:6702 closed
telegraf  | 2024-04-25T22:04:26Z D! [agent] Input channel closed
telegraf  | 2024-04-25T22:04:26Z D! [agent] Processor channel closed
telegraf  | 2024-04-25T22:04:26Z D! [agent] Processor channel closed
telegraf  | 2024-04-25T22:04:26Z D! [agent] Processor channel closed
telegraf  | 2024-04-25T22:04:26Z D! [agent] Stopped Successfully
telegraf exited with code 0



v1.29.2:
telegraf  | 2024-04-25T22:04:35Z I! Loading config: /etc/telegraf/telegraf.conf
telegraf  | 2024-04-25T22:04:35Z I! Loading config: /etc/telegraf/telegraf.d/ciena.conf
telegraf  | 2024-04-25T22:04:35Z W! DeprecationWarning: Option "fieldpass" of plugin "inputs.gnmi" deprecated since version 1.29.0 and will be removed in 2.0.0: use 'fieldinclude' instead
telegraf  | 2024-04-25T22:04:35Z I! Starting Telegraf 1.29.2 brought to you by InfluxData the makers of InfluxDB
telegraf  | 2024-04-25T22:04:35Z I! Available plugins: 241 inputs, 9 aggregators, 30 processors, 24 parsers, 60 outputs, 6 secret-stores
telegraf  | 2024-04-25T22:04:35Z I! Loaded inputs: gnmi
telegraf  | 2024-04-25T22:04:35Z I! Loaded aggregators: 
telegraf  | 2024-04-25T22:04:35Z I! Loaded processors: converter rename strings
telegraf  | 2024-04-25T22:04:35Z I! Loaded secretstores: 
telegraf  | 2024-04-25T22:04:35Z W! Outputs are not used in testing mode!
telegraf  | 2024-04-25T22:04:35Z I! Tags enabled: host=10.5.200.224
telegraf  | 2024-04-25T22:04:35Z D! [agent] Initializing plugins
telegraf  | 2024-04-25T22:04:35Z D! [inputs.gnmi::ciena-gnmi] Internal alias mapping: map[oc-if:/interfaces/oc-if:interface/oc-if:state/oc-if:counters:ifcounters]
telegraf  | 2024-04-25T22:04:35Z D! [agent] Starting service inputs

telegraf  | 2024-04-25T22:04:35Z E! [inputs.gnmi::ciena-gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"
telegraf  | 2024-04-25T22:04:46Z E! [inputs.gnmi::ciena-gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"
telegraf  | 2024-04-25T22:04:56Z E! [inputs.gnmi::ciena-gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"
telegraf  | 2024-04-25T22:05:07Z E! [inputs.gnmi::ciena-gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: remote error: tls: handshake failure"

telegraf  | 2024-04-25T22:05:15Z D! [agent] Stopping service inputs
telegraf  | 2024-04-25T22:05:15Z D! [agent] Input channel closed
telegraf  | 2024-04-25T22:05:15Z D! [agent] Processor channel closed
telegraf  | 2024-04-25T22:05:15Z D! [agent] Processor channel closed
telegraf  | 2024-04-25T22:05:15Z D! [agent] Processor channel closed
telegraf  | 2024-04-25T22:05:15Z D! [agent] Stopped Successfully
telegraf  | 2024-04-25T22:05:15Z E! [telegraf] Error running agent: input plugins recorded 4 errors
telegraf exited with code 1
```

### System info

Telegraf 1.29.2, MacOs 14.4.1, Docker 26.0.0

### Docker

```
services:
  telegraf:
    image: telegraf:1.29.2
    container_name: telegraf
    restart: no
    command: telegraf --debug --test-wait 40
    volumes:
      - /etc/snmp:/etc/snmp:ro
      - ./mibs:/usr/share/snmp/mibs:rw
      - ./telegraf/etc:/etc/telegraf:rw
    ports:
      - '8125:8125'
    logging:
      options:
        max-size: "1m"
        max-file: "5"
```

### Steps to reproduce

1. Use telegraf:1.29.2 (or higher) in docker-compose.yml
2. insecure_skip_verify = true 
3. tls_enable = true

### Expected behavior

Proper subscription is authenticated and able to subscribe to data

### Actual behavior

Authentication handshake fails

### Additional info

Exact same config was working in `1.29.1` and prior. I was attempting to upgrade my system from `1.28.2` to the latest, `1.30.2`, when I experienced this behavior. Backing down in versions, I identified it works in `1.29.1` and fails starting in `1.29.2`. No configuration was changed between `1.29.1` working and `>1.29.2` failing.
