### ISSUE TITLE
inputs.http_listener_v2: Even MORE debugging output

### ISSUE THREAD

**Issue by IngwiePhoenix** [influxdata/telegraf#15237]
### Use Case

I am trying to develop a webhook-to-influx bridge by using Kentix AccessManager Webhooks to send them to Telegraf's HTTP listener as JSON objects and then put those into InfluxDB.

While debugging my configuration, all i get is this:

```
Apr 26 09:31:45 SENST-ND-MTAG01 telegraf[1803065]: 2024-04-26T07:31:45Z D! [inputs.http_listener_v2] Parse error: invalid number
```

Bluntly speaking, that's not a whole lot...

### Expected behavior

I expected to see either the fully received message, or at least an information on what exactly it couldn't parse.

### Actual behavior

Introduce `inputs.http_listener_v2.accesslog` or something alike that would allow one to configure a better way to debug incoming HTTP traffic. In my case, I would like to see what exactly is being received.

### Additional info

This all works over plain HTTP - inside an internal network. Sadly, our Kentix box is quite old and thus does not deliver all the neccessary information through SNMP. Technically we could use SNMP Trap, but we weren't very successful with our tests here either - so we changed to Webhooks.

In Kentix, you have to manually define the payload being sent to the server, in my case it looks like this:

```json
{
    "user_id": "$USER_ID$",
    "user_name": "$USER_NAME$",
    "user_fullname": "$USER_FULLNAME$",
    "rfid_uid": "$USER_RFID_UID$",
    "rfid_data": "$USER_RFID_DATA$",
    "access_state": "$ACCESS_STATE$",
    "device_id": "$DEVICE_ID$",
    "device_name": "$DEVICE_NAME$",
    "device_type": "$DEVICE_TYPE$",
    "group_id": "$GROUP_ID$",
    "group_name": "$GROUP_NAME$",
    "group_state": "$GROUP_STATE$",
    "unix_time": "$SYSTEM_UNIXTIME$"
}
```

Thing is, when I use the "Test Webhook" button, it will send this string _verbatim_; no variable substitution is performed. This means, that "debugging" it is difficult; you have to hope that you got the values right, as well as the configuration.

Speaking of, here is mine:
```toml
[[inputs.http_listener_v2]]
basic_password = ""
basic_username = ""
data_format = "json_v2"
methods = ["POST"]
name_override = "webhook"
path_tag = false
paths = ["/telegraf"]
service_address = ":9999"

[[inputs.http_listener_v2.json_v2]]
measurement_name = "http.webhook"
timestamp_format = "unix"
timestamp_path = "unix_time"
timestamp_timezone = "Europe/Berlin"
[[inputs.http_listener_v2.json_v2.field]]
path = "rfid_uid"
type = "string"

[[inputs.http_listener_v2.json_v2.field]]
path = "rfid_data"
type = "string"

[[inputs.http_listener_v2.json_v2.field]]
path = "access_state"
type = "int"

[[inputs.http_listener_v2.json_v2.field]]
path = "device_id"
type = "int"

[[inputs.http_listener_v2.json_v2.field]]
path = "device_type"
type = "string"

[[inputs.http_listener_v2.json_v2.field]]
path = "group_id"
type = "int"

[[inputs.http_listener_v2.json_v2.field]]
path = "group_name"
type = "name"

[[inputs.http_listener_v2.json_v2.field]]
path = "group_state"
type = "int"

[[inputs.http_listener_v2.json_v2.tag]]
path = "user_id"
type = "int"

[[inputs.http_listener_v2.json_v2.tag]]
path = "user_name"
type = "string"

[[inputs.http_listener_v2.json_v2.tag]]
path = "user_fullname"
type = "string"

[[inputs.http_listener_v2.json_v2.tag]]
path = "device_name"
type = "string"
```

This is automatically generated off a Nix config; hence why the structure might seem a little shuffled.

Thanks and kind regards!

EDIT: Misread "Actual behaviour" somehow and thought it was where to put an implementation suggestion. Brainfart... sorry.
