### ISSUE TITLE
[processors.scale] incorrect rounding

### ISSUE THREAD

**Issue by llamafilm** [influxdata/telegraf#15248]
### Relevant telegraf.conf

```toml
[[processors.scale]]
  [[processors.scale.scaling]]
    factor = 0.1
    fields = ["input_frequency"]
```

### Logs from Telegraf

```text
n/a
```

### System info

Telegraf 1.29.2

### Steps to reproduce

Use scale processor on an SNMP metric which looks like this: `input_frequency=599i`

### Expected behavior

`input_frequency=59.9`

### Actual behavior

`input_frequency=59.900000000000006`
