### ISSUE TITLE
Got empty metric-name for response on Ciena WaveServer

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#15286]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
  name_override = "components"
  addresses = ["ws5site102lab.mgt.cox.net:10161"]
  username = "$user"
  password = "$password"
  redial = "10s"
  tls_enable = true
  insecure_skip_verify = true
  tls_ca = "/etc/telegraf/router_ca.pem"
  # [inputs.gnmi.aliases]
    # components = "/openconfig-platform:components"
  [[inputs.gnmi.subscription]]
    name = "optical_channel"
    path = "/components/component[name=*]"
    subscription_mode = "sample"
    origin = "openconfig-platform"
    sample_interval = "10s"
```

### Logs from Telegraf

```text
2024-05-01T21:17:02Z W! [inputs.gnmi] Got empty metric-name for response, usually indicating
configuration issues as the response cannot be related to any subscription.
Please open an issue on https://github.com/influxdata/telegraf including your
device model and the following response data:
timestamp:1714598222912553000  update:{path:{elem:{name:"openconfig-platform:components"}  elem:{name:"component"  key:{key:"name"  value:"CM-1"}}  elem:{name:"name"}}  val:{string_val:"CM-1"}}  update:{path:{elem:{name:"openconfig-platform:components"}  elem:{name:"component"  key:{key:"name"  value:"CM-1"}}     
This message is only printed once.
```

### System info

telegraf:1.29.3

### Steps to reproduce

1. Run Telegraf using the above config

### Expected behavior

Have Telegraf handle this error:
```
update:{path:{elem:{name:"openconfig-platform:components"}
```

### Actual behavior

We see the error message from above. Other data does continue to process through Telegraf

### Additional info

Similar issue to https://github.com/influxdata/telegraf/issues/12831
