### ISSUE TITLE
[processsors.enum] allow list of fields

### ISSUE THREAD

**Issue by llamafilm** [influxdata/telegraf#15305]
### Use Case

I have some JSON data sources which use string values like true/false on several fields and I use `processors.enum` to map these to 0/1.  The names do not follow a consistent glob pattern, so my config file includes a separate mapping block for each field like this:

```toml
[[processors.enum]]
  namepass = ["roomalert"]
  [[processors.enum.mapping]]
    field = "state"
    default = -1
    [processors.enum.mapping.value_mappings]
      false = 0
      true = 1
  [[processors.enum.mapping]]
    field = "power_connected"
    default = -1
    [processors.enum.mapping.value_mappings]
      false = 0
      true = 1
```

It would be convenient to reduce this using a list of fields like this:

```toml
[[processors.enum]]
  namepass = ["roomalert"]
  [[processors.enum.mapping]]
    fields = ["state", "power_connected"]
    default = -1
    [processors.enum.mapping.value_mappings]
      false = 0
      true = 1
```

### Expected behavior

n/a

### Actual behavior

n/a
