### ISSUE TITLE
Recent telegraf versions panic when receiving invalid errorstats entries

### ISSUE THREAD

**Issue by nicois** [influxdata/telegraf#15311]
### Relevant telegraf.conf

```toml
[[inputs.redis]]
servers = ["tcp://[(redacted)"]
password = "(redacted)"
  fieldpass = ["clients", "connected_clients", "client_longest_output_list", "client_biggest_input_buf", "blocked_clients", "rejected_connections", "clients_in_timeout_table", "used_memory", "used_memory_peak", "used_memory_dataset", "used_memory_rss", "mem_fragmentation_ratio", "maxmemory", "lazyfree_pending_objects", "rdb_changes_since_last_save", "rdb_last_save_time", "rdb_last_bgsave_time_sec", "rdb_last_cow_size", "total_connections_received", "total_commands_processed", "total_net_input_bytes", "total_net_output_bytes", "total_reads_processed", "total_writes_processed", "master_repl_offset", "second_repl_offset", "repl_backlog_active", "repl_backlog_size", "repl_backlog_histlen", "slave_repl_offset", "master_sync_left_bytes", "master_sync_last_io_seconds_ago", "master_link_down_since_seconds", "connected_slaves", "min_slaves_good_slaves", "keyspace_hitrate", "keys", "expires", "avg_ttl"]
```

### Logs from Telegraf

```text
goroutine 130 [running]:
github.com/influxdata/telegraf/plugins/inputs/redis.gatherErrorstatsLine({0xc0027f06c0, 0xb}, {0xc0027f06cc, 0x1}, {0x5571a3867ab0, 0xc001410dc0}, 0xc0027ee2d0)
        plugins/inputs/redis/redis.go:623 +0x30e
github.com/influxdata/telegraf/plugins/inputs/redis.gatherInfoOutput({0x5571a37bdf18?, 0xc0016721e0?}, {0x5571a3867ab0, 0xc001410dc0}, 0x0?)
        plugins/inputs/redis/redis.go:425 +0x655
github.com/influxdata/telegraf/plugins/inputs/redis.(*Redis).gatherServer(0x0?, {0x5571a383c748, 0xc0018c2740}, {0x5571a3867ab0, 0xc001410dc0})
        plugins/inputs/redis/redis.go:354 +0xc7
github.com/influxdata/telegraf/plugins/inputs/redis.(*Redis).Gather.func1({0x5571a383c748, 0xc0018c2740})
        plugins/inputs/redis/redis.go:318 +0x7b
created by github.com/influxdata/telegraf/plugins/inputs/redis.(*Redis).Gather in goroutine 128
        plugins/inputs/redis/redis.go:316 +0x75
```

### System info

1.28.5

### Steps to reproduce

Install dragonfly and cause it to modify its replica configuration, resulting in https://github.com/dragonflydb/dragonfly/blob/main/src/server/debugcmd.cc#L523 being exercised

### Expected behavior

telegraf does not panic

### Actual behavior

Telegraf panics, showing the stack trace above

### Additional info

In addition to not panicing, telegraf should produce debug-level logs to assist in understanding what invalid values are being received.
