### ISSUE TITLE
[inputs.win_eventlog] Telegraf agent not collecting custom event logs

### ISSUE THREAD

**Issue by bloodmc** [influxdata/telegraf#15326]
### Relevant telegraf.conf

```toml
# # Input plugin to collect Windows Event Log messages
# # This plugin ONLY supports Windows

  [[inputs.win_eventlog]]
    locale = 1033
    eventlog_name = "WEC-Account-Management"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Application-Crashes"
    locale = 1033
    eventlog_name = "WEC-Application-Crashes"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Autoruns"
    locale = 1033
    eventlog_name = "WEC-Autoruns"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Authentication"
    locale = 1033
    eventlog_name = "WEC-Authentication"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-External-Devices"
    locale = 1033
    eventlog_name = "WEC-External-Devices"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Windows-Firewall"
    locale = 1033
    eventlog_name = "WEC-Windows-Firewall"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-GPO-Errors"
    locale = 1033
    eventlog_name = "WEC-GPO-Errors"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Log-Deletion-Security"
    locale = 1033
    eventlog_name = "WEC-Log-Deletion-Security"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Log-Deletion-System"
    locale = 1033
    eventlog_name = "WEC-Log-Deletion-System"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-MSI-Packages"
    locale = 1033
    eventlog_name = "WEC-MSI-Packages"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Object-Manipulation"
    locale = 1033
    eventlog_name = "WEC-Object-Manipulation"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Powershell"
    locale = 1033
    eventlog_name = "WEC-Powershell"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]
   # exclude_fields = ["Message"]

  [[inputs.win_eventlog]]
    alias = "WEC-Process-Execution"
    locale = 1033
    eventlog_name = "WEC-Process-Execution"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Services"
    locale = 1033
    eventlog_name = "WEC-Services"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Sysmon"
    locale = 1033
    eventlog_name = "WEC-Sysmon"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Registry"
    locale = 1033
    eventlog_name = "WEC-Registry"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Task-Scheduler"
    locale = 1033
    eventlog_name = "WEC-Task-Scheduler"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Terminal-Services"
    locale = 1033
    eventlog_name = "WEC-Terminal-Services"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]

  [[inputs.win_eventlog]]
    alias = "WEC-Windows-Updates"
    locale = 1033
    eventlog_name = "WEC-Windows-Updates"
    from_beginning = false
    process_userdata = true
    process_eventdata = true
    event_tags = ["Source", "EventID", "Level", "LevelText", "Task", "TaskText", "Opcode", "OpcodeText", "Keywords", "Channel", "Computer"]
    event_fields = ["*"]
```

### Logs from Telegraf

```text
2024-05-08T18:29:17Z I! Starting Telegraf 1.31.0-6f575a2f brought to you by InfluxData the makers of InfluxDB
2024-05-08T18:29:17Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 25 parsers, 60 outputs, 5 secret-stores
2024-05-08T18:29:17Z I! Loaded inputs: win_eventlog (19x)
2024-05-08T18:29:17Z I! Loaded aggregators: 
2024-05-08T18:29:17Z I! Loaded processors: 
2024-05-08T18:29:17Z I! Loaded secretstores: 
2024-05-08T18:29:17Z I! Loaded outputs: loki
2024-05-08T18:29:17Z I! Tags enabled: host=smevent
2024-05-08T18:29:17Z I! [agent] Config: Interval:20s, Quiet:false, Hostname:"smevent", Flush Interval:20s
2024-05-08T18:29:17Z D! [agent] Initializing plugins
2024-05-08T18:29:17Z D! [agent] Connecting outputs
2024-05-08T18:29:17Z D! [agent] Attempting connection to [outputs.loki]
2024-05-08T18:29:17Z D! [agent] Successfully connected to outputs.loki
2024-05-08T18:29:17Z D! [agent] Starting service inputs
```

### System info

Telegraf 1.30.1, Windows Server 2022 Standard and pushing logs to loki

### Docker

Manual setup. (No docker used)

### Steps to reproduce

1. Start telegraf agent using above config.
2. It gets stuck after startup and stops logging

### Expected behavior

To collect the custom windows event channels without failing.

### Actual behavior

The telegraf agent starts and gets into a bad state where it stops logging or collecting logs.

### Additional info

Following https://github.com/palantir/windows-event-forwarding as a great reference for setting up windows event forwarding. One reference in the [guide](https://github.com/palantir/windows-event-forwarding/tree/master/windows-event-channels) is to setup custom windows event channels as the default windows events can be limited based on what you need to audit. I was able to successfully configure all custom event channels as per the guide and everything logs correctly but fails to be collected by Telegraf. Using the debug build from another ticket, it shows no relevant logs to pinpoint issue. If I attempt to shutdown the service after startup, it always gives the following error

```
Windows could not stop the Telegraf Data Collector Service service on Local Computer
Error 1067: The process terminated unexpectedly
```
