### ISSUE TITLE
Cisco_telemetry_mdt input plugin incorrect parsing of child policy

### ISSUE THREAD

**Issue by GeorgeMaged** [influxdata/telegraf#15387]
### Relevant telegraf.conf

```toml
###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################

[[inputs.cisco_telemetry_mdt]]
transport = "tcp"
service_address = ":5432"
max_msg_size=20000000
embedded_tags = [
"Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics/class-stats/class-name",
"Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics/class-stats/class-name",
"Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/member-interfaces/member-interface/input/service-policy-names/service-policy-instance/statistics/class-stats/class-name",
"Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/member-interfaces/member-interface/output/service-policy-names/service-policy-instance/statistics/class-stats/class-name"
]

[inputs.cisco_telemetry_mdt.aliases]
   cpu = "Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization"
   memory-summary = "Cisco-IOS-XR-nto-misc-oper:memory-summary/nodes/node/summary"
   memory-detail = "Cisco-IOS-XR-nto-misc-shmem-oper:memory-summary/nodes/node/detail"
   interface_QoS_In = "Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics"
   interface_QoS_Out = "Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics"
   if_stats = "Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters"
```

### Logs from Telegraf

```text
.
```

### System info

Telegraf 1.20.4 , Debian GNU/Linux 10 (buster)             Kernel: Linux 4.19.0-6-amd64

### Steps to reproduce

1.Cisco equipment details
Cisco IOS XR Software, Version 6.5.3
Version : 6.5.3

2.Configuration in Router : 

Router(config)#telemetry model-driven
Router(config-model-driven)#destination-group GROUP1
Router(config-model-driven-dest)#address family ipv4  10.53.225.254 port 5432  
Router(config-model-driven-dest-addr)#encoding self-describing-gpb  
Router(config-model-driven-dest-addr)#protocol tcp  
Router(config-model-driven-dest-addr)#commit 

Sensor Groups: Sensor Group Id:S-Group1
    Sensor Path:        Cisco-IOS-XR-wdsysmon-fd-oper:system-monitoring/cpu-utilization
    Sensor Path State:  Resolved

  Sensor Group Id:S-Group2
    Sensor Path:        Cisco-IOS-XR-nto-misc-shmem-oper:memory-summary/nodes/node/detail
    Sensor Path State:  Resolved

  Sensor Group Id:S-Group3
    Sensor Path:        Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/input/service-policy-names/service-policy-instance/statistics
    Sensor Path State:  Resolved

  Sensor Group Id:S-Group4
    Sensor Path:        Cisco-IOS-XR-infra-statsd-oper:infra-statistics/interfaces/interface/latest/generic-counters
    Sensor Path State:  Resolved

  Sensor Group Id:S-Group5
    Sensor Path:        Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics
    Sensor Path State:  Resolved
    Sensor Path:        Cisco-IOS-XR-qos-ma-oper:qos/interface-table/interface/output/service-policy-names/service-policy-instance/statistics
    Sensor Path State:  Resolved

Subscribe to these sensor groups.

3. Send these data into influxDB.

### Expected behavior

The expected behaviour is to be able to parse the different classes in the child policy.
Expected to get all class names related to child class name but we receive only "class default"

### Actual behavior

convert only class name for parent policy not child and hence get only all class names for parent not child policy .
