### ISSUE TITLE
port_name plugin errors for unknown protocols cannot be silenced

### ISSUE THREAD

**Issue by cnemo-cenic** [influxdata/telegraf#15394]
### Use Case

I am trying to use the port_name plugin with ipfix data, and my data has a lot of protocols, not just tcp and udp.

My configuration looks like this:

```toml
[[processors.port_name]]
  protocol_field = "protocol"
  field = "src_port"
  dest = "src_port_name"

[[processors.port_name]]
  protocol_field = "protocol"
  field = "dst_port"
  dest = "dst_port_name"
```

I am seeing the following errors in my logs, which I really don't care about:

```
2024-05-22T20:45:36Z E! [processors.port_name] protocol not found in services map: esp
2024-05-22T20:45:38Z E! [processors.port_name] protocol not found in services map: icmp
```

### Expected behavior

A config option to be available to silence errors when the protocol is not found in the services map, and the logs to be clean when the option is set.

### Actual behavior

No config option, must either accept the errors in the logs or not use the plugin.

**Comment by powersj** [comment]
Hi,

If you have protocols that will not work with the plugin then please use the metricpass to exclude those metrics from the processor and only pass metrics with udp or tcp as the protocol:

```toml
[[processors.port_name]]
  metricpass="fields.protocol == 'udp' || fields.protocol == 'tcp'"
```
