### ISSUE TITLE
SNMP Plugin: input.snmp.table (input.snmp.table.field) is not processed correctly

### ISSUE THREAD

**Issue by RobertCrash** [influxdata/telegraf#15442]
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
  ## Agent addresses to retrieve values from.
  ##   format:  agents = ["<scheme://><hostname>:<port>"]
  ##   scheme:  optional, either udp, udp4, udp6, tcp, tcp4, tcp6.
  ##            default is udp
  ##   port:    optional
  ##   example: agents = ["udp://127.0.0.1:161"]
  ##            agents = ["tcp://127.0.0.1:161"]
  ##            agents = ["udp4://v4only-snmp-agent"]
  #agents = ["udp://127.0.0.1:161"]
  agents = ["udp://192.168.10.21:161", "udp://192.168.10.22:161"]

  ## Timeout for each request.
  # timeout = "5s"

  ## SNMP version; can be 1, 2, or 3.
  version = 2

  ## Path to mib files
  ## Used by the gosmi translator.
  ## To add paths when translating with netsnmp, use the MIBDIRS environment variable
  # path = ["/usr/share/snmp/mibs"]

  ## Agent host tag; the tag used to reference the source host
  agent_host_tag = "source"

  ## SNMP community string.
  community = "public"

  ## Number of retries to attempt.
  # retries = 3

  ## The GETBULK max-repetitions parameter.
  # max_repetitions = 10

  ## SNMPv3 authentication and encryption options.
  ##
  ## Security Name.
  # sec_name = "myuser"
  ## Authentication protocol; one of "MD5", "SHA", "SHA224", "SHA256", "SHA384", "SHA512" or "".
  # auth_protocol = "MD5"
  ## Authentication password.
  # auth_password = "pass"
  ## Security Level; one of "noAuthNoPriv", "authNoPriv", or "authPriv".
  # sec_level = "authNoPriv"
  ## Context Name.
  # context_name = ""
  ## Privacy protocol used for encrypted messages; one of "DES", "AES" or "".
  # priv_protocol = ""
  ## Privacy password used for encrypted messages.
  # priv_password = ""

  #name_override = "general"

  #tags = {switch = "source", switch = "hostname"}

  #[inputs.cpu.tags]
  # switch = "hostname"
  # tag2 = "bar"

  ## Add fields and tables defining the variables you wish to collect.  
  [[inputs.snmp.field]]
    oid = "RFC1213-MIB::sysName.0"
    #oid = "1.3.6.1.2.1.1.5.0"
    name = "hostname"
    is_tag = true

  # Standard
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "RFC1213-MIB::sysUpTime.0"


  ## Vendor/Device specific
  [[inputs.snmp.field]]
    name = "productIdentDisplayName"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.100.1.0"
  [[inputs.snmp.field]]
    name = "productIdentVersion"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.100.4.0"
  [[inputs.snmp.field]]
    name = "productIdentBuildNumber"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.100.5.0"


  ## Vendor/Device specific
  [[inputs.snmp.field]]
    name = "CPU1m"
    #oid = "DNOS-SWITCHING-MIB::agentSwitchCpuProcessTotalUtilizationSixty"
    oid = "1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.11.0"
  [[inputs.snmp.field]]
    name = "MemAvailable"
    #oid = "DNOS-SWITCHING-MIB::agentSwitchCpuProcessMemAvailable"
    oid = "1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.2.0"
  [[inputs.snmp.field]]
    name = "MemFree"
    #oid = "DNOS-SWITCHING-MIB::agentSwitchCpuProcessMemFree"
    oid = "1.3.6.1.4.1.674.10895.5000.2.6132.1.1.1.1.4.1.0"
  ## Calculated via Processor
  #[[inputs.snmp.table.field]]
  #  name = "MemUsage"
  #  oid =

  # !!! relevant table !!!
  [[inputs.snmp.table]]
    name = "LolLol"
    inherit_tags = [ "hostname" ]
    # Dell-Vendor-MIB::envMonFanStatusTable
    #oid = 1.3.6.1.4.1.674.10895.3000.1.2.110.7.1
    [[inputs.snmp.table.field]]
      name = "lolSer"
      oid = "RFC1213-MIB::sysServices.0"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "lolLoc"
      oid = "RFC1213-MIB::sysLocation.0"


  [[inputs.snmp.table]]
    name = "MonFanStatusTable"
    inherit_tags = [ "hostname" ]
    # Dell-Vendor-MIB::envMonFanStatusTable
    #oid = 1.3.6.1.4.1.674.10895.3000.1.2.110.7.1
  [[inputs.snmp.table.field]]
    name = "MonFanStatusIndex"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.1"
    is_tag = true
  [[inputs.snmp.table.field]]
    name = "MonFanStatusDescr"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.2"
    is_tag = true
  [[inputs.snmp.table.field]]
    name = "MonFanState"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.3"
  [[inputs.snmp.table.field]]
    name = "MonFanSpeed"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.1.1.4"


  [[inputs.snmp.table]]
    name = "MonSupplyStatusTable"
    inherit_tags = [ "hostname" ]
    # Dell-Vendor-MIB::envMonSupplyStatusTable
    #oid = 1.3.6.1.4.1.674.10895.3000.1.2.110.7.2
  [[inputs.snmp.table.field]]
    name = "MonSupplyStatusIndex"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.1"
    is_tag = true
  [[inputs.snmp.table.field]]
    name = "MonSupplyStatusDescr"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.2"
    is_tag = true
  [[inputs.snmp.table.field]]
    name = "MonSupplyState"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.3"
  [[inputs.snmp.table.field]]
    name = "MonSupplyCurrentPower"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.5"
  [[inputs.snmp.table.field]]
    name = "MonSupplyAveragePower"
    oid = "1.3.6.1.4.1.674.10895.3000.1.2.110.7.2.1.6"

  [[inputs.snmp.table]]
    name = "Interfaces"
    inherit_tags = [ "hostname" ]
    # Interface tag - used to identify interface in metrics database [[inputs.snmp.table.field]]
    #oid = "IF-MIB::ifXTable" # Don't walk the whole table, just single metrics specified
  [[inputs.snmp.table.field]]
    name = "ifIndex"
    oid = "IF-MIB::ifIndex"
    is_tag = true
  [[inputs.snmp.table.field]]
    name = "ifName"
    oid = "IF-MIB::ifName"
    is_tag = true
  [[inputs.snmp.table.field]]
    name = "ifAlias"
    oid = "IF-MIB::ifAlias"
    is_tag = true
  [[inputs.snmp.table.field]]
     oid = "IF-MIB::ifType"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifSpeed"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifAdminStatus"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifOperStatus"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifHCInOctets"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifHCOutOctets"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifInDiscards"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifOutDiscards"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifInErrors"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifOutErrors"
  [[inputs.snmp.table.field]]
    oid = "IF-MIB::ifInUnknownProtos"

  [[inputs.snmp.table]]
    name = "dot1qVlanCurrentEntry"
    inherit_tags = [ "hostname" ]
    #index_as_tag = true
   ## Attention: added trailing .0
   [[inputs.snmp.table.field]]
    name = "VlanIndex"
    oid = "1.3.6.1.2.1.17.7.1.4.2.1.3.0"
    is_tag = true
    #oid_index_length = 2
    #oid_index_suffix = ".0"
   [[inputs.snmp.table.field]]
    name = "VlanStatus"
    oid = "1.3.6.1.2.1.17.7.1.4.2.1.6.0"
    #oid_index_suffix = ".0."
   [[inputs.snmp.table.field]]
    name = "VlanCurrentEgressPorts"
    oid = "1.3.6.1.2.1.17.7.1.4.2.1.4.0"
   [[inputs.snmp.table.field]]
    name = "VlanCurrentUntaggedPorts"
    oid = "1.3.6.1.2.1.17.7.1.4.2.1.5.0"

  [[inputs.snmp.table]]
    name = "dot1qVlanStaticEntry"
    inherit_tags = [ "hostname" ]
    #index_as_tag = true
   [[inputs.snmp.table.field]]
    name = "VlanStaticName"
    oid = "1.3.6.1.2.1.17.7.1.4.3.1.1"
    is_tag = true
   [[inputs.snmp.table.field]]
    name = "VlanStaticEgressPorts"
    oid = "1.3.6.1.2.1.17.7.1.4.3.1.2"
   #[[inputs.snmp.table.field]]
   # name = "VlanForbiddenEgressPorts"
   # oid = "1.3.6.1.2.1.17.7.1.4.3.1.3"
   [[inputs.snmp.table.field]]
    name = "VlanStaticUntaggedPorts"
    oid = "1.3.6.1.2.1.17.7.1.4.3.1.4"
```

### Logs from Telegraf

```text
telegraf-snmp  | 2024-06-01T10:32:29Z I! Loading config: /etc/telegraf/telegraf.conf
telegraf-snmp  | 2024-06-01T10:32:29Z I! Starting Telegraf 1.28.5 brought to you by InfluxData the makers of InfluxDB
telegraf-snmp  | 2024-06-01T10:32:29Z I! Available plugins: 240 inputs, 9 aggregators, 29 processors, 24 parsers, 59 outputs, 5 secret-stores
telegraf-snmp  | 2024-06-01T10:32:29Z I! Loaded inputs: snmp (2x)
telegraf-snmp  | 2024-06-01T10:32:29Z I! Loaded aggregators: 
telegraf-snmp  | 2024-06-01T10:32:29Z I! Loaded processors: starlark
telegraf-snmp  | 2024-06-01T10:32:29Z I! Loaded secretstores: 
telegraf-snmp  | 2024-06-01T10:32:29Z I! Loaded outputs: influxdb_v2
telegraf-snmp  | 2024-06-01T10:32:29Z I! Tags enabled: host=space-docker.telegraf-snmp
telegraf-snmp  | 2024-06-01T10:32:29Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"space-docker.telegraf-snmp", Flush Interval:10s
telegraf-snmp  | 2024-06-01T10:32:29Z D! [agent] Initializing plugins
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysServices.0"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysLocation.0"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifIndex"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifName"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifAlias"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifType"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifSpeed"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifAdminStatus"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifOperStatus"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifHCInOctets"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifHCOutOctets"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifInDiscards"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifOutDiscards"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifInErrors"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifOutErrors"
telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "IF-MIB::ifInUnknownProtos"
telegraf-snmp  | 2024-06-01T10:32:30Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysName.0"
telegraf-snmp  | 2024-06-01T10:32:30Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysUpTime.0"
telegraf-snmp  | 2024-06-01T10:32:30Z D! [agent] Connecting outputs
telegraf-snmp  | 2024-06-01T10:32:30Z D! [agent] Attempting connection to [outputs.influxdb_v2]
telegraf-snmp  | 2024-06-01T10:32:30Z D! [agent] Successfully connected to outputs.influxdb_v2
telegraf-snmp  | 2024-06-01T10:32:30Z D! [agent] Starting service inputs
telegraf-snmp  | 2024-06-01T10:32:40Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:32:50Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 35.402849ms
telegraf-snmp  | 2024-06-01T10:32:50Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:33:00Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 34.991316ms
telegraf-snmp  | 2024-06-01T10:33:00Z D! [outputs.influxdb_v2] Buffer fullness: 1 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:33:10Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 34.063892ms
telegraf-snmp  | 2024-06-01T10:33:10Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:33:20Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 35.039278ms
telegraf-snmp  | 2024-06-01T10:33:20Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:33:30Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 33.146009ms
telegraf-snmp  | 2024-06-01T10:33:30Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:33:40Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 45.663456ms
telegraf-snmp  | 2024-06-01T10:33:40Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:33:50Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 39.01151ms
telegraf-snmp  | 2024-06-01T10:33:50Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:34:00Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 41.442624ms
telegraf-snmp  | 2024-06-01T10:34:00Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:34:10Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 34.614871ms
telegraf-snmp  | 2024-06-01T10:34:10Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:34:20Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 32.969555ms
telegraf-snmp  | 2024-06-01T10:34:20Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:34:30Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 39.588878ms
telegraf-snmp  | 2024-06-01T10:34:30Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
telegraf-snmp  | 2024-06-01T10:34:40Z D! [outputs.influxdb_v2] Wrote batch of 406 metrics in 32.489472ms
```

### System info

Docker v24.0.6 (build ed223bc) ,Telegraf 1.28.5, Influxdb 2.6 (alpine)

### Docker

version: '3.8'

networks:
  monitoring:
    name: monitoring
    #driver: bridge

volumes:
  #prometheus_data: {}
  influxdb_data: {}

services:
 influxdb:
    image: influxdb:2.6-alpine
    container_name: influxdb
    hostname: influxdb
    restart: unless-stopped
    env_file:
      - influxdb.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb_data:/var/lib/influxdb2
      - ./influxdb/config.yml:/etc/influxdb2/config.yml
    ports:
      - "8086:8086"
    networks:
      - monitoring

  telegraf-snmp:
    image: telegraf:1.28.5-alpine
    #image: telegraf/telegraf-1.25-alpine-python
    #build: ./telegraf-snmp
    #depends_on:
    #  - influxdb
    container_name: telegraf-snmp
    hostname: space-docker.telegraf-snmp
    restart: unless-stopped
    volumes:
      # Mount for telegraf config
      - ./telegraf-snmp/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf-snmp/mibs/:/home/telegraf/.snmp/mibs
    #env_file:
    #  - ./telegraf/env
    networks:
      - monitoring
  

### Steps to reproduce

N/A

### Expected behavior

All fields and tables (including table fields) should be written into DB (influxdb).

For:
- tables ([[inputs.snmp.table]]) as measurements with name of table
- fields  ([[inputs.snmp.field]])  & table fields  ([[inputs.snmp.table.field]]) as fields with name of field or as tags with name of field
- ...

### Actual behavior

The defined Table
  [[inputs.snmp.table]]
    name = "LolLol"
in the telegraf.conf for SNMP Input Plugin is NOT written into InfluxDB.

The other fields and tables & table fields are written into DB (influxdb) as expected.

### Additional info

As you can see in the log
  telegraf-snmp  | 2024-06-01T10:32:29Z D! [inputs.snmp] executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysServices.0"

In the relevant table the table.field is at least somehow processed, But again NOT written into InfluxDB!

The DB connection ( [[outputs.influxdb_v2]] ) is working, because the other fields and tables & table fields are written into DB (influxdb) as expected.
