### ISSUE TITLE
Otel Get error when set service_address = "${OTEL_EXPORTER_OTLP_ENDPOINT}"

### ISSUE THREAD

**Issue by michaelkira** [influxdata/telegraf#15450]
### Relevant telegraf.conf

```toml
[[outputs.opentelemetry]]
  ## Override the default (localhost:4317) OpenTelemetry gRPC service
  ## address:port
  service_address = "${OTEL_EXPORTER_OTLP_ENDPOINT}"
```

### Logs from Telegraf

```text
2024-06-04T07:58:05Z E! [agent] Error writing to outputs.opentelemetry: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: address
http://localhost:4317:
too many colons in address"
```

### System info

telegraf:latest

### Docker

telegraf:latest

### Steps to reproduce

1. Set service_address = "${OTEL_EXPORTER_OTLP_ENDPOINT}"
2. OTEL_EXPORTER_OTLP_ENDPOINT = http://localhost:4317
3. Getting error above
...

### Expected behavior

We try to leverage existing well known env vars for open telemetry OTEL_EXPORTER_OTLP_ENDPOINT  https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter/

The format for it is http://localhost:4317

While it seems telegraf is expecting values localhost:4317 (with out http )

Which leave us no choice but creating a separate env vars just for telegraf to work.
Not sure this expected or a missed parse logic bug

### Actual behavior

2024-06-04T07:58:05Z E! [agent] Error writing to outputs.opentelemetry: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp: address
http://localhost:4317:
too many colons in address"
