### ISSUE TITLE
Telegraf Docker Container is loading config indefinitely

### ISSUE THREAD

**Issue by Maulai** [influxdata/telegraf#15494]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true

[[outputs.influxdb_v2]]
  urls = ["http://influxdb-url:8086"]
  token = "token"
  organization = "organization"
  bucket = "bucket"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
```

### Logs from Telegraf

```text
2024-06-12T15:30:50Z I! Loading config: /etc/telegraf/telegraf.conf
```

### System info

Latest Docker Image (v1.31) running on QNAP NAS with latest firmware

### Steps to reproduce

1. Start a Container with volume mapping to the config file and standard container configuration

### Expected behavior

Config file loads successfully

### Actual behavior

The only output from telegraf is: `2024-06-12T15:30:50Z I! Loading config: /etc/telegraf/telegraf.conf`
No other output or error is sown

### Additional info

I tried the following without success:
- `cat /etc/telegraf/telegraf.conf` to verify access permissions
- `telegraf --test --debug`
- telegraf-alpine image
- curl of influxdb server to verify network and database connectivity
- running the container with host and bridge adapter
- change of config multiple times

Thank you in advance!
