### ISSUE TITLE
gNMI plugin error

### ISSUE THREAD

**Issue by bofh16** [influxdata/telegraf#15500]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
        addresses = [
                "host:57400"
        ]

#       encoding = "proto"

        canonical_field_names = true
        guess_path_tag = false
        trim_field_names = false

        enable_tls = false
        insecure_skip_verify = true

        [[inputs.gnmi.subscription]]
               name = "jti_optics"
               path = "/junos/system/linecard/optics"
               subscription_mode = "sample"
               sample_interval = "10s"
```

### Logs from Telegraf

```text
2024-06-13T10:28:20Z W! [inputs.gnmi] Got empty metric-name for response (field "/interfaces/interface/snmp_if_index"), usually
indicating configuration issues as the response cannot be related to any
subscription.Please open an issue on https://github.com/influxdata/telegraf
including your device model and the following response data:
{"Update":{"timestamp":1718274499992117914,"prefix":{"elem":[{"name":"interfaces"},{"name":"interface","key":{"name":"et-0/0/0"}}]},"update":[{"path":{"elem":[{"name":"snmp_if_index"}]},"val":{"Value":{"UintVal":507}}}],"atomic":true}}
This message is only printed once.
```

### System info

Telegraf 1.31.0 (git: HEAD@fbfaba05), Ubuntu 22.04.4

### Steps to reproduce

1. Start Telegraf with gNMI plugin configuration.
2.
3.
...

### Expected behavior

gNMI plugin to work.

### Actual behavior

No data is ingested in the database.
