### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#15509]
### Relevant telegraf.conf

```toml
[[inputs.socket_listener]]
service_address = "tcp://1.2.3.4:8085"
tls_cert = "/etc/ssl/host/cert.crt"
tls_key = "/etc/ssl/host/cert.key"
tls_allowed_cacerts = ["/usr/local/share/ca-certificates/edge-ca.crt"]
content_encoding = "gzip"
keep_alive_period = "2m"

[[inputs.socket_listener]]
service_address = "tcp://:8185"
tls_cert = "/etc/ssl/host/cert.crt"
tls_key = "/etc/ssl/host/cert.key"
tls_allowed_cacerts = ["/usr/local/share/ca-certificates/edge-ca.crt"]
content_encoding = "gzip"
keep_alive_period = "2m"
```

### Logs from Telegraf

```text
.
```

### System info

telegraf 1.30.2

### Steps to reproduce

1. run the above config for a while
2.
3.
...

### Expected behavior

no infinite memory growth

### Actual behavior

infinite memory growth

### Additional info

So a few days ago we encountered an OOM on one of our hosts, which was due to telegraf. On another host we also noticed elevated memory usage from telegraf, as it was consuming approximately 41GB. After enabling pprof, heap profiles were captured a few days apart (where telegraf had gone up to a few GB memory). It's clear from the profiles that there are several memory leaks going on.

![heap](https://github.com/influxdata/telegraf/assets/1826947/052ade06-5711-4bca-a488-b3db0452f88c)

We did not start experiencing this issue until upgrading to version 1.30.2 from 1.26.0
