### ISSUE TITLE
Allow setting custom HTTP headers for Elasticsearch input

### ISSUE THREAD

**Issue by robsears** [influxdata/telegraf#15543]
### Use Case

Have an Elasticsearch cluster that requires custom headers in order to play nice with some custom plugins. The Elasticsearch input plugin needs to supply these for us to be able to get useful metrics about the cluster.

### Expected behavior

Given the config below, the input plugin should properly pass custom headers to Elasticsearch:

```toml
[[inputs.elasticsearch]]
  servers = ["http://localhost:9200"]

  [inputs.elasticsearch.headers]
    "X-Custom-Header" = "Custom"
```

### Actual behavior

Currently there is no way for the Elasticsearch input plugin to pass custom headers to Elasticsearch.

### Additional info

In researching this issue, I found that there was [a recent PR](#15477) for a similar option for the Elasticsearch output plugin. I'm using the same key name of `headers` here to main consistency.
