### ISSUE TITLE
overriding hostname stopped working

### ISSUE THREAD

**Issue by fireba11** [influxdata/telegraf#15594]
### Relevant telegraf.conf

```toml
## Override default hostname, if empty use os.Hostname()
  hostname = "my.host.name"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
```

### Logs from Telegraf

```text
no log
```

### System info

telegraf > 1.25

### Steps to reproduce

1. set a hostname
2. check your influxdb

### Expected behavior

configured hostname is used

### Actual behavior

value is ignoried, system hostname is used
*this is a major bug for usage with docker*
