### ISSUE TITLE
amd_rocm_smi plugin missing field and tag

### ISSUE THREAD

**Issue by NISHIY-EKSDEE** [influxdata/telegraf#15620]
### Relevant telegraf.conf

```toml
[agent]
  debug = true

### INPUTS ###

[[inputs.amd_rocm_smi]]


### OUTPUTS ###

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["/telegraf-metrics/metrics.log"]

  ## Data format to output.
  data_format = "influx"

  ## The file will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.
  # rotation_interval = "0h"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  rotation_max_size = "500MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  rotation_max_archives = 5

[[outputs.influxdb_v2]]
  urls = ["http://localhost:8086"]

  ## API token for authentication.
  token = ""

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "test_org"

  ## Destination bucket to write into.
  bucket = "test_bucket"
```

### Logs from Telegraf

```text
2024-07-14T22:49:37Z I! Loading config: /etc/telegraf/telegraf.conf
2024-07-14T22:49:37Z I! Starting Telegraf 1.31.0 brought to you by InfluxData the makers of InfluxDB
2024-07-14T22:49:37Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 60 outputs, 6 secret-stores
2024-07-14T22:49:37Z I! Loaded inputs: amd_rocm_smi
2024-07-14T22:49:37Z I! Loaded aggregators: 
2024-07-14T22:49:37Z I! Loaded processors: 
2024-07-14T22:49:37Z I! Loaded secretstores: 
2024-07-14T22:49:37Z I! Loaded outputs: file influxdb_v2
2024-07-14T22:49:37Z I! Tags enabled: host=nishiy-pc
2024-07-14T22:49:37Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"nishiy-pc", Flush Interval:10s
2024-07-14T22:49:37Z D! [agent] Initializing plugins
2024-07-14T22:49:37Z D! [agent] Connecting outputs
2024-07-14T22:49:37Z D! [agent] Attempting connection to [outputs.file]
2024-07-14T22:49:37Z D! [agent] Successfully connected to outputs.file
2024-07-14T22:49:37Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2024-07-14T22:49:37Z D! [agent] Successfully connected to outputs.influxdb_v2
2024-07-14T22:49:37Z D! [agent] Starting service inputs
2024-07-14T22:49:47Z D! [outputs.file]  Wrote batch of 1 metrics in 84.286µs
2024-07-14T22:49:47Z D! [outputs.file]  Buffer fullness: 0 / 10000 metrics
2024-07-14T22:49:47Z D! [outputs.influxdb_v2]  Wrote batch of 1 metrics in 38.609011ms
2024-07-14T22:49:47Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.31.0, Ubuntu 22.04, ROCm 6.1.2

### Docker

```yml
services:
  telegraf:
    build:
      context: .
      dockerfile_inline: |
        FROM rocm/dev-ubuntu-22.04:latest

        RUN apt-get update && apt-get install wget
        RUN wget -q https://repos.influxdata.com/influxdata-archive_compat.key && \
            echo '393e8779c89ac8d958f81f942f9ad7fb82a25e133faddaf92e15b16e6ac9ce4c influxdata-archive_compat.key' | sha256sum -c && cat influxdata-archive_compat.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null && \
            echo 'deb [signed-by=/etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg] https://repos.influxdata.com/debian stable main' | sudo tee /etc/apt/sources.list.d/influxdata.list && \
            apt-get update && sudo apt-get install telegraf

        COPY telegraf-cfg.toml /etc/telegraf/telegraf.conf

        ENTRYPOINT [ "telegraf" ]
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
    uts: "host"
    network_mode: "host"
    volumes:
      - /etc/telegraf-metrics:/telegraf-metrics

```

### Steps to reproduce

1. Prepare environment with ROCm installed
2. Deploy InfluxDB
3. Start telegraf with amd_rocm_smi plugin
4. Check metrics in output file or Data Explorer in InfluxDB

### Expected behavior

All fields and tags listed in the README are present

### Actual behavior

`unitlization_memory` field and `gpu_id` tag are missing

### Additional info

I am attaching the rocm-smi outputs of different ROCm versions for MI100 and RX6700XT GPUs
https://gist.github.com/NISHIY-EKSDEE/2ea9ee3d9749d64537271b703a5cff40

The table below describes the differences I found between the expected field names in the plugin source code and the output I provided:

| Field                | Expected field name in current version | ROCm 5.7.1                           | ROCm 6.0.2                           | ROCm 6.1.2                           |
| -------------------- | -------------------------------------- | ------------------------------------ | ------------------------------------ | ------------------------------------ |
| GpuID                | `GPU ID`                               |                                      | `Device ID`                          | `Device ID`                          |
| GpuDcefClkClockSpeed | `dcefclk clock speed`                  | `dcefclk clock speed:` (added colon) | `dcefclk clock speed:` (added colon) | `dcefclk clock speed:` (added colon) |
| GpuDcefClkClockLevel | `dcefclk clock level`                  | `dcefclk clock level:` (added colon) | `dcefclk clock level:` (added colon) | `dcefclk clock level:` (added colon) |
| GpuFclkClockSpeed    | `fclk clock speed`                     | `fclk clock speed:` (added colon)    | `fclk clock speed:` (added colon)    | `fclk clock speed:` (added colon)    |
| GpuFclkClockLevel    | `fclk clock level`                     | `fclk clock level:` (added colon)    | `fclk clock level:` (added colon)    | `fclk clock level:` (added colon)    |
| GpuSocclkClockSpeed  | `socclk clock speed`                   | `socclk clock speed:` (added colon)  | `socclk clock speed:` (added colon)  | `socclk clock speed:` (added colon)  |
| GpuSocclkClockLevel  | `socclk clock level`                   | `socclk clock level:` (added colon)  | `socclk clock level:` (added colon)  | `socclk clock level:` (added colon)  |
| GpuCardSeries        | `Card series`                          |                                      |                                      | `Card Series` (Capital letter)       |
| GpuCardModel         | `Card model`                           |                                      |                                      | `Card Model` (Capital letter)        |
| GpuCardVendor        | `Card vendor`                          |                                      |                                      | `Card Vendor` (Capital letter)       |
