### ISSUE TITLE
inputs.http_response: When specifying an interface, hostnames cannot be used as opposed to ip addresses

### ISSUE THREAD

**Issue by Mic92** [influxdata/telegraf#15662]
### Relevant telegraf.conf

```toml
[[inputs.http_response]]
interface = "tinc.retiolum"
response_status_code = 200
response_string_match = "Index of /"
urls = ["http://yellow.r", "http://flix.r/"]
```

### Logs from Telegraf

```text
Error running agent: could not initialize input inputs.http_response: cannot create local address for interface "tinc.retiolum" and server address "http://transmission.r/transmission/web/"
```

### System info

Telegraf 1.31.1

### Steps to reproduce

telegraf -config /var/run/telegraf/config.toml

### Expected behavior

no error

### Actual behavior

See error message
