### ISSUE TITLE
Add ZFS ARC support for inputs.mem in Linux

### ISSUE THREAD

**Issue by taoky** [influxdata/telegraf#15663]
### Use Case

In Linux, ZFS ARC cache would be shown as "used" instead of "cached", which makes the used memory in Linux with ZFS systems reported by telegraf abnormally high.

htop (<https://github.com/htop-dev/htop/pull/1003>) and netdata (<https://github.com/netdata/netdata/pull/12847>) gets shrinkable ARC size from `/proc/spl/kstat/zfs/arcstats` in Linux and reports used memory size correctly in this case.

### Expected behavior

The "used", "cached" and "available" memory reported by inputs.mem are considered with ZFS ARC in Linux.

### Actual behavior

Currently, "used" is too high and "cached" & "available" are too low under Linux system reported by inputs.mem.

### Additional info

To prevent breaking existing configurations, an extra option might be added to `inputs.mem` to parse `/proc/spl/kstat/zfs/arcstats` in Linux and do correct calculations (and no-op in other OSes).

**Comment by powersj** [comment]
Hi,

Why not use the existing ZFS specific plugin which collects and reports ARC stats?

**Comment by iBug** [comment]
> Why not use the existing ZFS specific plugin

Because we're concerning the memory usage report. We have alerts for memory usage but would like to discount ZFS ARC for this purpose as it can be released under memory pressure. The main problem is ZFS ARC resides in a different series, so it's impossible to implement this on Grafana's side with simple queries like `SELECT mean(used) - mean(zfs_arc)`, hence this feature request.

**Comment by powersj** [comment]
> The main problem is ZFS ARC resides in a different series, so it's impossible to implement this on Grafana's side with simple queries like SELECT mean(used) - mean(zfs_arc), hence this feature request.

This is why we have processors

Having the memory plugin start to read other data that is already collected by another plugin is not likely something we would want to maintain and manage.

**Comment by taoky** [comment]
Thank you for the idea of processors, as I had never known about that before. However, after reading [Starlark Processor Plugin docs](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark), I doubt whether processors could handle the case in this issue. The `apply()` function could only accept one metric at a time, and even with state stored in `state` variable, it is uncertain whether metrics from `inputs.zfs` have been processed when handling metric of `inputs.mem`. 

Another approach considered is to "merge" `inputs.zfs` to `inputs.mem`, and then do the calculation and removes unnecessary fields. However, according to [Transform data with aggregator and processor plugins](https://docs.influxdata.com/telegraf/v1/configure_plugins/aggregator_processor/), aggregator is done after processor, and it does not look like I could `processors.clone` -> `aggregator.merge` (?) -> `processors.starlark`.

I really have no idea how to implement this with telegraf's aggregator and processor plugins :-(, and please correct me if I got the wrong idea.

**Comment by powersj** [comment]
Please provide an example mem and zfs metric that you are trying to combine. Showing the line protocol via outputs.file is preferred.

**Comment by taoky** [comment]
With this configuration file:

```toml
[[inputs.mem]]

[[inputs.zfs]]
  kstatMetrics = ["arcstats"]

[[outputs.file]]
  files = ["stdout"]
```

And `telegraf --once --config ./telegraf.conf`:

```
mem,host=example dirty=12288i,free=21401366528i,sunreclaim=57691877376i,swap_free=0i,swap_total=0i,used=243849175040i,active=877862912i,mapped=264413184i,vmalloc_used=12186030080i,low_free=0i,low_total=0i,page_tables=15589376i,total=270332604416i,available_percent=8.468654856285998,cached=4984139776i,commit_limit=135166300160i,huge_pages_free=0i,shared=916725760i,swap_cached=0i,inactive=1796681728i,available=22893535232i,huge_page_size=2097152i,huge_pages_total=0i,write_back_tmp=0i,write_back=0i,used_percent=90.20339058501204,committed_as=9374679040i,high_total=0i,sreclaimable=3765948416i,vmalloc_total=35184372087808i,buffered=97923072i,high_free=0i,slab=61457825792i,vmalloc_chunk=0i 1721938672000000000
zfs,host=example,pools=pool0::pool1 arcstats_mru_hits=221262064i,arcstats_access_skip=62i,arcstats_hdr_size=1198870304i,arcstats_mru_ghost_size=55249732608i,arcstats_l2_hits=17366144i,arcstats_misses=73793460i,arcstats_demand_data_iohits=1145238i,arcstats_prefetch_metadata_misses=7257777i,arcstats_l2_prefetch_asize=4155392i,arcstats_l2_writes_error=0i,arcstats_mfu_ghost_evictable_metadata=47997284352i,arcstats_demand_metadata_misses=10678451i,arcstats_mru_evictable_metadata=3105994240i,arcstats_mfu_ghost_metadata=47997284352i,arcstats_l2_writes_lock_retry=39i,arcstats_mfu_ghost_hits=16935051i,arcstats_dbuf_size=4512409608i,arcstats_uncached_size=0i,arcstats_arc_tempreserve=4096i,arcstats_mru_ghost_hits=2459779i,arcstats_pm=1162076328i,arcstats_l2_io_error=0i,arcstats_memory_all_bytes=270332604416i,arcstats_async_upgrade_sync=1161308i,arcstats_arc_need_free=0i,arcstats_demand_metadata_hits=2019239348i,arcstats_evict_l2_eligible_mfu=68496072192i,arcstats_l2_log_blk_count=12961i,arcstats_hash_chains=2099666i,arcstats_data_size=168742359040i,arcstats_demand_hit_prescient_prefetch=3367928i,arcstats_mru_ghost_data=55249732608i,arcstats_mfu_evictable_data=90850320896i,arcstats_uncached_evictable_metadata=0i,arcstats_l2_log_blk_asize=223916032i,arcstats_l2_rebuild_asize=55996870656i,arcstats_hits=2587574159i,arcstats_pd=1796776035i,arcstats_overhead_size=13018967040i,arcstats_l2_rebuild_success=1i,arcstats_l2_rebuild_bufs_precached=514i,arcstats_demand_iohit_predictive_prefetch=1346228i,arcstats_evict_skip=3863i,arcstats_size=207874293160i,arcstats_l2_bufc_metadata_asize=52989065216i,arcstats_metadata_size=16420070400i,arcstats_l2_mru_asize=46625204736i,arcstats_uncached_hits=0i,arcstats_l2_mfu_asize=11022145536i,arcstats_l2_cksum_bad=12202i,arcstats_cached_only_in_progress=8i,arcstats_demand_metadata_iohits=174408i,arcstats_prefetch_data_misses=27896716i,arcstats_l2_read_bytes=41091560960i,arcstats_hash_collisions=30036083i,arcstats_hash_chain_max=7i,arcstats_c_max=214748364800i,arcstats_mru_evictable_data=72125943808i,arcstats_uncached_metadata=0i,arcstats_prefetch_data_hits=1320902i,arcstats_evict_l2_ineligible=36006551641600i,arcstats_hash_elements=13550342i,arcstats_l2_rebuild_dh_errors=0i,arcstats_arc_dnode_limit=171798691840i,arcstats_arc_meta_used=37611127208i,arcstats_demand_iohit_prescient_prefetch=43805i,arcstats_l2_abort_lowmem=1226i,arcstats_arc_loaned_bytes=0i,arcstats_demand_data_misses=27960516i,arcstats_l2_evict_reading=0i,arcstats_l2_evict_l1cached=0i,arcstats_l2_writes_done=142647i,arcstats_memory_available_bytes=4438855680i,arcstats_arc_raw_size=0i,arcstats_hash_elements_max=13910151i,arcstats_mru_ghost_evictable_data=55249732608i,arcstats_mfu_data=91193199616i,arcstats_mru_ghost_metadata=0i,arcstats_mfu_evictable_metadata=2169664512i,arcstats_uncached_data=0i,arcstats_l2_feeds=534344i,arcstats_arc_sys_free=17179869184i,arcstats_iohits=3594782i,arcstats_anon_data=218888192i,arcstats_anon_evictable_data=0i,arcstats_abd_chunk_waste_size=1519964160i,arcstats_mfu_ghost_evictable_data=42588640768i,arcstats_meta=443236948i,arcstats_anon_evictable_metadata=0i,arcstats_mfu_size=103903696384i,arcstats_mfu_ghost_size=90585925120i,arcstats_l2_writes_sent=142647i,arcstats_l2_data_to_meta_ratio=680i,arcstats_demand_hit_predictive_prefetch=34390921i,arcstats_demand_data_hits=541159025i,arcstats_mfu_hits=2366312095i,arcstats_evict_not_enough=215i,arcstats_l2_log_blk_writes=994i,arcstats_l2_rebuild_size=706190059520i,arcstats_memory_direct_count=0i,arcstats_c_min=171798691840i,arcstats_mru_data=77330271232i,arcstats_uncached_evictable_data=0i,arcstats_compressed_size=172144305152i,arcstats_l2_rebuild_log_blks=11967i,arcstats_deleted=57331138i,arcstats_mutex_miss=12912i,arcstats_evict_l2_eligible=172624029696i,arcstats_evict_l2_cached=510498055680i,arcstats_l2_write_bytes=5737374720i,arcstats_arc_prune=31394i,arcstats_l2_rebuild_io_errors=0i,arcstats_uncompressed_size=441127063040i,arcstats_mfu_ghost_data=42588640768i,arcstats_l2_size=710518437376i,arcstats_l2_misses=37040006i,arcstats_l2_rebuild_cksum_lb_errors=0i,arcstats_prescient_prefetch=3411840i,arcstats_dnode_size=11102098080i,arcstats_mru_size=81039383040i,arcstats_prefetch_metadata_hits=25854884i,arcstats_prefetch_metadata_iohits=2275009i,arcstats_c=209054653992i,arcstats_l2_rebuild_lowmem=0i,arcstats_arc_no_grow=1i,arcstats_anon_metadata=461824i,arcstats_mfu_metadata=12710496768i,arcstats_l2_log_blk_avg_asize=15624i,arcstats_l2_rebuild_bufs=12230274i,arcstats_mru_metadata=3709111808i,arcstats_mru_ghost_evictable_metadata=0i,arcstats_l2_rebuild_unsupported=0i,arcstats_l2_evict_lock_retry=0i,arcstats_predictive_prefetch=61193575i,arcstats_l2_asize=57651505664i,arcstats_prefetch_data_iohits=127i,arcstats_evict_l2_eligible_mru=104127957504i,arcstats_l2_bufc_data_asize=4662440448i,arcstats_bonus_size=3551058240i,arcstats_l2_free_on_write=8i,arcstats_anon_size=219350016i,arcstats_memory_throttle_count=0i,arcstats_memory_indirect_count=5738i,arcstats_memory_free_bytes=21618724864i,arcstats_evict_l2_skip=0i,arcstats_l2_rw_clash=0i,arcstats_l2_hdr_size=826620576i 1721938672000000000
```

`arcstats_size - arcstats_c_min` in `zfs` is the "shrinkable ARC cache size"

**Comment by powersj** [comment]
I am going to use the file input to replicate your metrics, but it is the same idea:

```toml
[agent]
  debug = true
  omit_hostname = true

[[inputs.file]]
  files = ["mem.influx"]
  data_format = "influx"

[[inputs.file]]
  files = ["zfs.influx"]
  data_format = "influx"
  tagexclude = ["pools"]

[[processors.rename]]
  [[processors.rename.replace]]
    measurement = "zfs"
    dest = "mem"

[[aggregators.merge]]
  period = "10s"
  drop_original = true

[[outputs.file]]
```

There are two things to do to the `zfs` metrics 1) drop the pools tag so it has the same tags as the `mem` metrics and then rename the `zfs` metric to `mem`. Then the merge aggregator can combine them all into one series with the combined metrics of both.

You could even filter out all the various zfs metrics if you don't want them and only pass on the arcstats size field(s) that you want.

**Comment by taoky** [comment]
Thank you for this example. For future readers, we're currently using this configuration:

```toml
[[processors.clone]]
  namepass = ["zfs"]
  name_override = "mem"

[[processors.tag_limit]]
  namepass = ["mem"]
  limit = 1
  keep = ["host"]

[[aggregators.merge]]
  namepass = ["mem"]
  period = "10s"
  drop_original = true

[[processors.starlark]]
  namepass = ["mem"]
  source = '''
# load("logging.star", "log")
def apply(metric):
  if "used" in metric.fields and "arcstats_c_min" in metric.fields:
    c_min = metric.fields["arcstats_c_min"]
    size = metric.fields["arcstats_size"]
    arc = max(size - c_min, 0)
    metric.fields["used"] -= arc
    metric.fields["cached"] += arc
    metric.fields["available"] += arc
    metric.fields["used_percent"] = 100 * metric.fields["used"] / metric.fields["total"]
    metric.fields["available_percent"] = 100 * metric.fields["available"] / metric.fields["total"]
    for k in metric.fields.keys():
      if k.startswith("arcstats"):
        metric.fields.pop(k)
  return metric
'''
```

It works mostly, though sometimes it has some strange peaks in our grafana panel (deployed at ~00:53):

![image](https://github.com/user-attachments/assets/f5f6e59a-95d0-4267-b5e8-f8402048040e)

It does not trigger alerts so this little glitch seems OK in our own case.
