### ISSUE TITLE
Prometheus remoteWrite to Splunk HEC format metric_name fail

### ISSUE THREAD

**Issue by alexgdmx** [influxdata/telegraf#15674]
### Relevant telegraf.conf

```toml
[[inputs.http_listener_v2]]
      service_address = ":1234"
      paths = ["/receive"]
      data_format = "prometheusremotewrite"
  
    [[processors.starlark]]
      source = '''
    def apply(metric):
      if metric.name == "prometheus_remote_write":
        for k, v in metric.fields.items():
          metric.name = k
          metric.fields["value"] = v
          metric.fields.pop(k)
      return metric
    '''

    [[outputs.http]]
      url = "tld/services/collector"
      data_format = "splunkmetric"
      splunkmetric_hec_routing = true
      [outputs.http.headers]
        Content-Type = "application/json"
        Authorization = "Splunk xxxxx"
        X-Splunk-Request-Channel = "xxxx"
```

### Logs from Telegraf

```text
No logs, is a formatting issue
```

### System info

telegraf 1.31.x  linux x86_64 and s390x

### Docker

docker container v1.31.x

### Steps to reproduce

According to Splunk documentation
https://docs.splunk.com/Documentation/Splunk/9.2.2/Data/HECExamples

The format expected is the following:  "metric_name:cpu.usr": 11.12,
```
{
  "time": 1486683865,
  "event": "metric",
  "source": "metrics",
  "sourcetype": "perflog",
  "host": "host_1.splunk.com",
  "fields": {
    "region": "us-west-1",
    "datacenter": "dc2",
    "rack": "63",
    "os": "Ubuntu16.10",
    "arch": "x64",
    "team": "LON",
    "service": "6",
    "service_version": "0",
    "service_environment": "test",
    "path": "/dev/sda1",
    "fstype": "ext3",
    "metric_name:cpu.usr": 11.12,
    "metric_name:cpu.sys": 12.23,
    "metric_name:cpu.idle": 13.34
  }
}
```

Once Telegraf gets the metric from **remoteWrite**  ("splunkmetric"), it is transformed by **[[processors.starlark]]** to the following format: 
```
{
    "fields": {
      "apiserver_request_slo_duration_seconds_bucket": 5,
    },
    "name": "apiserver_request_slo_duration_seconds_bucket",
    "tags": {
      "agent_location": "MyCluster",
      "apiserver": "openshift-apiserver",
      "cluster": "vmw.openshift.training",
      "component": "apiserver",
      "container": "openshift-apiserver",
      "datacenter": "DC",
      "endpoint": "https",
      "environment": "Production",
      "group": "image.openshift.io",
      "host": "openshift.training",
      "index": "mainframe_na",
      "instance": "10.128.0.53:8443",
      "job": "api",
      "le": "0.6",
      "namespace": "openshift-apiserver",
      "pod": "apiserver-79d4d767b5-6k979",
      "prometheus": "openshift-monitoring/k8s",
      "prometheus_replica": "prometheus-k8s-1",
      "resource": "imagestreams",
      "role": "kubernetes",
      "scope": "resource",
      "service": "api",
      "source": "OpenShift_remote_write",
      "sourcetype": "prometheus",
      "verb": "POST",
      "version": "v1"
    },
    "timestamp": 1722062518
  }
``` 

finally when **[[outputs.http]] data_format = "splunkmetric"** takes the follow format:  

**"metric_name": "apiserver_request_slo_duration_seconds_bucket.value"**, not **"metric_name: apiserver_request_slo_duration_seconds_bucket.value": 5**
```
{
    "time": 1722062238.324,
    "event": "metric",
    "host": "openshift.training",
    "index": "mainframe_na",
    "source": "OpenShift_remote_write",
    "fields": {
      "_value": 5,
      "agent_location": "MyCluster",
      "cluster": "vmw.openshift.training",
      "datacenter": "DC",
      "endpoint": "https-metrics",
      "environment": "Production",
      "id": "/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod559918cf_1869_40d9_b60d_5715e3932692.slice/crio-conmon-746527b58db5566f9e2d25c8dfc949ca75e60c6fc95e52a3495c05764524c0ec.scope",
      "instance": "192.168.0.108:10250",
      "job": "kubelet",
      "metric_name": "apiserver_request_slo_duration_seconds_bucket.value",
      "metrics_path": "/metrics/cadvisor",
      "node": "vmw-xwgg9-master-2",
      "prometheus": "openshift-monitoring/k8s",
      "prometheus_replica": "prometheus-k8s-0",
      "role": "kubernetes",
      "service": "kubelet",
      "sourcetype": "prometheus"
    }
  }
```

### Expected behavior

Output format **I'm removing additional** fields to remark the **metric_name** issue of this bug
```
{
    "time": 1722062238.324,
    "event": "metric",
    "host": "openshift.training",
    "index": "mainframe_na",
    "source": "OpenShift_remote_write",
    "fields": {
      "_value": 5,
      "metric_name:apiserver_request_slo_duration_seconds_bucket.value": 5,
    }
  }
```

### Actual behavior

Output format **I'm removing additional** fields to remark the **metric_name** issue of this bug
```
{
    "time": 1722062238.324,
    "event": "metric",
    "host": "openshift.training",
    "index": "mainframe_na",
    "source": "OpenShift_remote_write",
    "fields": {
      "_value": 5,
      "metric_name": "apiserver_request_slo_duration_seconds_bucket.value"
    }
  }
```
