### ISSUE TITLE
buffer_size for execd processor not working

### ISSUE THREAD

**Issue by SirBreadc** [influxdata/telegraf#15684]
### Relevant telegraf.conf

```toml
[[inputs.netflow]]
  metric_buffer_limit = 500000
  flush_interval = "60s"
  service_address = "udp4://:2055"
  protocol = "ipfix"
  private_enterprise_number_files = ["telegraf_conf/netflow_ingestion/custom_fields.csv"]
  dump_packets = false

[[processors.execd]]
  command = ["telegraf_conf/netflow_ingestion/netflow_options_packet_parser.py"]
  namepass = ["netflow_options"]
  buffer_size ="1Mib"
```

### Logs from Telegraf

```text
2024-07-29T23:56:51Z E! error loading config file telegraf_conf/netflow_ingestion/telegraf_netflow copy.conf: plugin processors.execd: line 70: configuration specified the fields ["buffer_size"], but they were not used. This is either a typo or this config option does not exist in this version.
```

### System info

1.32.0

### Steps to reproduce

1. add  buffer_size ="1Mib" to your telegarf file and run it
2.
3.
...

### Expected behavior

We'd like a similar option to what is seen here https://github.com/influxdata/telegraf/blob/release-1.31/plugins/inputs/execd/README.md the reason for this ask is due to stderr messaged we need to log out are quite large, this is to assist us with debugging

### Actual behavior

2024-07-29T23:56:51Z E! error loading config file telegraf_conf/netflow_ingestion/telegraf_netflow copy.conf: plugin processors.execd: line 70: configuration specified the fields ["buffer_size"], but they were not used. This is either a typo or this config option does not exist in this version.

### Additional info

We are wanting to increase the stderr buffer to show more verbose logs 
atm we are seeing 
2024-07-29T23:58:50Z E! [processors.execd] Error reading stderr: bufio.Scanner: token too long
