### ISSUE TITLE
Mongodb Output Plugin Error - Invalid namespace specified

### ISSUE THREAD

**Issue by rexcys** [influxdata/telegraf#15729]
### Relevant telegraf.conf

```toml
root@telegraf:/# cat /etc/telegraf/telegraf.conf
[agent]
  interval = "10s"
  round_interval = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""

[[outputs.mongodb]]
  dsn = "mongodb://mongodb:27017"
  #database = "telegraf_metrics"
  #granularity = "seconds"
  #timeout = "10s"
  #ttl = "3h"

[[inputs.gnmi]]
  ## Address and port of the gNMI GRPC server
  addresses = ["192.168.1.1:32768"]

  ## gNMI encoding requested (one of: "proto", "json", "json_ietf", "bytes")
  encoding = "proto"

  [[inputs.gnmi.subscription]]
    name = "ifcounters"
    origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/counters"
    subscription_mode = "sample"
    sample_interval = "10s"
```

### Logs from Telegraf

```text
2024-08-12T10:36:59Z E! [agent] Error writing to outputs.mongodb: unable to create time series collection: (InvalidNamespace) Invalid namespace specified 'telegraf.'
2024-08-12T10:37:09Z E! [agent] Error writing to outputs.mongodb: unable to create time series collection: (InvalidNamespace) Invalid namespace specified 'telegraf.'
2024-08-12T10:37:19Z E! [agent] Error writing to outputs.mongodb: unable to create time series collection: (InvalidNamespace) Invalid namespace specified 'telegraf.'
2024-08-12T10:37:29Z E! [agent] Error writing to outputs.mongodb: unable to create time series collection: (InvalidNamespace) Invalid namespace specified 'telegraf.'
2024-08-12T10:37:39Z E! [agent] Error writing to outputs.mongodb: unable to create time series collection: (InvalidNamespace) Invalid namespace specified 'telegraf.'
```

### System info

MongoDB v7.0.12, Telegraf 1.31.2 (git: HEAD@854ac83b), 22.04.2 LTS (Jammy Jellyfish), Docker version 20.10.17, build 100c701

### Docker

version: "3.0"

volumes:
  prometheus_data: {}
  grafana_data: {}
  mongodb_data: {}

services:
  telegraf:
    image: telegraf:latest
    restart: always
    container_name: telegraf
    hostname: telegraf
    volumes:
      # - ./telegraf/mibs/:/usr/share/snmp/mibs/
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    ports:
      - 9126:9126
    command: telegraf --config /etc/telegraf/telegraf.conf
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

### Steps to reproduce

1. docker compose up -d
2. docker logs -f telegraf
3. Error message as above

### Expected behavior

Expect Time series collection is created without error

### Actual behavior

Error when creating collection from default config.. looks like trailing "." is seen from the logs
