### ISSUE TITLE
Template serializer does not work on 

### ISSUE THREAD

**Issue by sebastianrothbucher** [influxdata/telegraf#15739]
### Relevant telegraf.conf

```toml
[[outputs.mqtt]]
  servers = ["localhost:1883", ]
  topic = 'telegraf/{{ .Tag "topic" }}'
  batch = false
  data_format = "template"
  template = '{{ .Field "msg" }}'
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  topics = [ "test/#" ]
  data_format = "value"
  data_type = "string"
  value_field_name = "msg"
```

### Logs from Telegraf

```text
2024-08-13T23:00:25Z E! [serializers.template::mqtt] metric of type *metric.trackingMetric is not a template metric
```

### System info

Telegraf 1.31.3 (MacOS Silicon)

### Steps to reproduce

1. run above config (i.e. bridge messages verbatim)
2. send mqtt to test/one (or test/something)
3. observe error and empty message being written to telegraf/test/one

### Expected behavior

Incoming message is written to outgoing topic verbatim

### Actual behavior

Message is empty

### Additional info

I already have a fix for this, can submit a PR shortly.
