### ISSUE TITLE
TeamSpeak plugin "unexpected EOF" error

### ISSUE THREAD

**Issue by dlmw** [influxdata/telegraf#15738]
### Relevant telegraf.conf

```toml
[[inputs.teamspeak]]
  server = "teamspeak-host:10011"
  username = "monitoring"
  password = "MY_PASSWORD"
  nickname = "telegraf"
  [inputs.teamspeak.tags]
    service = "teamspeak"
```

### Logs from Telegraf

```text
2024-08-13T15:49:30Z E! [inputs.teamspeak] Error in plugin: unexpected EOF
```

### System info

telegraf 1.31.2

### Steps to reproduce

1. Restart the telegraf service
2. Notice "nickname is already in use" error
3. After a while, the error transforms to "Error in plugin: unexpected EOF"

### Expected behavior

The plugin should disconnect from ServerQuery gracefully in order to "free" the nickname.

### Actual behavior

Nickname isn't freed. Potentially causing the EOF error down the line.

### Additional info

Sometimes when telegraf is restarted, it has trouble connecting to the same TeamSpeak server because "nickname is already in use". The errors might be related.
