### ISSUE TITLE
feat(inputs.mysql): Add support gather replica status

### ISSUE THREAD

**Issue by hungnt1** [influxdata/telegraf#15748]
### Info
Due to from MYSQL 8.4 removed `show slave status` command and replace by `show replica status` command. this cause issue when collect from MYSQL 8.4 release and further.
More: https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html#mysqld-8-4-0-deprecation-removal
### Relevant telegraf.conf

```toml
[[inputs.mysql]]
  metric_version = 2
  gather_all_slave_channels = true
  servers = ['root:test@tcp(127.0.0.1:34306)/']
  gather_slave_status = true
```

### Logs from Telegraf

```text
2024-08-16T01:11:30Z E! [inputs.mysql] Error in plugin: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SLAVE STATUS' at line 1
```

### System info

Telegraf 1.31.3 (git: HEAD@ecf94b12)

### Steps to reproduce

1. Setup MYSQL 8.4 replication
2. Enable collect slave status with option `gather_slave_status`
3. Check log and see issue 

### Expected behavior

- Have metric related replica in mysql 8.4 like 
```
Replica_IO_Running
Replica_SQL_Running
```

### Actual behavior

2024-08-16T01:11:30Z E! [inputs.mysql] Error in plugin: Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SLAVE STATUS' at line 1

```[tasklist]
### Tasks
- [ ] https://github.com/influxdata/telegraf/pull/15749
```
