### ISSUE TITLE
Systemd Units config errors on being given scope

### ISSUE THREAD

**Issue by Tasty213** [influxdata/telegraf#15745]
### Relevant telegraf.conf

```toml
[[inputs.systemd_units]]
  ## Pattern of units to collect
  ## A space-separated list of unit-patterns including wildcards determining
  ## the units to collect.
  ##  ex: pattern = "telegraf* influxdb* user@*"
  # pattern = "*"

  ## Filter for a specific unit type
  ## Available settings are: service, socket, target, device, mount,
  ## automount, swap, timer, path, slice and scope
  # unittype = "service"

  ## Collect system or user scoped units
  ##  ex: scope = "user"
  scope = "system"

  ## Collect also units not loaded by systemd, i.e. disabled or static units
  ## Enabling this feature might introduce significant load when used with
  ## unspecific patterns (such as '*') as systemd will need to load all
  ## matching unit files.
  # collect_disabled_units = false

  ## Collect detailed information for the units
  # details = false

  ## Timeout for state-collection
  # timeout = "5s"
[[outputs.file]]
  files = ["stdout"]
```

### Logs from Telegraf

```text
2024-08-15T16:09:30Z I! Loading config: /etc/telegraf/telegraf.conf
2024-08-15T16:09:30Z E! error loading config file /etc/telegraf/telegraf.conf: plugin inputs.systemd_units: line 1: configuration specified the fields ["scope"], but they were not used. This is either a typo or this config option does not exist in this version.
```

### System info

Podman 5.1.2

### Docker

FROM docker.io/library/telegraf:1.31.3

ADD ./telegraf.conf /etc/telegraf/telegraf.conf

### Steps to reproduce

Build the above container using podman build
`podman build -f ./Containerfile --env=INFLUX_TOKEN=insert_token_here`

run it
`podman run --cap-add cap_net_raw --env=DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus --mount=type=bind,src=/run/user/1000,dst=/run/user/1000 --mount=type=bind,src=/run/user/1000/bus,ro=true,dst=/run/user/1000/bus --mount=type=bind,src=/var/run/dbus/system_bus_socket,ro=true,dst=/var/run/dbus/system_bus_socket {insert hash from build}`

### Expected behavior

Telegraf monitors systemd units in the scope of the user who ran the container.

### Actual behavior

Telegraf errors claiming it can't accept the scope value despite this being [shown in the documentation](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/systemd_units).
