### ISSUE TITLE
Failing AMQP input is not ignored

### ISSUE THREAD

**Issue by sebplorenz** [influxdata/telegraf#15767]
### Relevant telegraf.conf

```toml
[[inputs.amqp_consumer]]
alias = "msg_infrastructure_event_consumer"
startup_error_behavior = "ignore"
brokers = ["amqp://${RMQ_HOST}/${RMQ_VHOST}"]
username = "${RMQ_USER}"
password = "${RMQ_PASSWORD}"
exchange = "exchange.infra.ul"
```

### Logs from Telegraf

```text
telegraf-1  | 2024-08-22T14:04:00Z I! [agent] Config: Interval:1s, Quiet:false, Hostname:"", Flush Interval:1s
telegraf-1  | 2024-08-22T14:04:01Z E! [telegraf] Error running agent: starting input inputs.amqp_consumer::msg_infrastructure_event_consumer: error declaring exchange: Exception (404) Reason: "NOT_FOUND - no exchange 'exchange.infra.ul' in vhost '/'"
telegraf-1 exited with code 1
```

### System info

telegraf:1.31.3-alpine

### Expected behavior

Telegraf should ignore the failing AMQP plugin if started with ```startup_error_behavior = "ignore"```.

### Actual behavior

Telegraf keeps restarting.
