### ISSUE TITLE
Input: Bind - strconv.ParseInt : value out of range

### ISSUE THREAD

**Issue by rumanmaharjan** [influxdata/telegraf#15866]
telegraf configuration::
```toml
[[inputs.bind]]
urls = ["http://localhost:8053/xml/v3"]
```
error message:
```text
[inputs.bind] Error in plugin: unable to decode XML document: strconv.ParseInt: parsing "18446744073709546041": value out of range
```
telegraf version v1.31.2

related to #6059
