### ISSUE TITLE
Many memory allocations with multiple output plugins

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#15882]
### Relevant telegraf.conf

```toml
[[outputs.influxdb_v2]]
  tagpass = {"batch"="0"}
  ...
[[outputs.influxdb_v2]]
  tagpass = {"batch"="1"}
  ...
[[outputs.influxdb_v2]]
  tagpass = {"batch"="2"}
  ...
...

# Reads and parses about 40kb of data at 50Hz
[[inputs.socket_listener]]
  ...
```
```


### Logs from Telegraf

```text
No relevant entries
```

### System info

Telegraf 1.31.2, Ubuntu 24.02

### Steps to reproduce

1. Receive 40KB of data at 50Hz
2. Telegraf will not be able to keep up and will start dropping UDP packets
3. 
...

### Expected behavior

Telegraf is able to keep up with the amount of data.

### Actual behavior

Telegraf drops several of the UDP packets because it is waiting on GOGC. 

I profiled Telegraf and noticed that about 28% of all allocations were done by the `metric.Copy` function called from `agent.runOutputs` at https://github.com/influxdata/telegraf/blob/ffee74c1886736f172909481f6b61e091d11c9a2/agent/agent.go#L879. This seemed strange to me because each metric should only be output to 1 output plugin. Indeed, when I move the Copy call over to the `runningOutput.AddMetric` _after_ the metric is filtered out by a filter, the amount of allocations drops drastically and performance increases. (this is a hack and should be implemented in a different way!)

I think it might be worth it to change this mechanism and only copy a metric when an output will accept a metric, i.e. it is not filtered by a Filter.

### Additional info

[heap](https://github.com/user-attachments/assets/d0a68b56-f075-44ed-ba34-72ce02d09401)
[profile](https://github.com/user-attachments/assets/1953c4eb-eba0-44a5-b7d3-7713da3641b8)

[profiles.zip](https://github.com/user-attachments/files/17002231/profiles.zip)
