### ISSUE TITLE
Telegraf config doesn't accept single quotes for table keys

### ISSUE THREAD

**Issue by cheshar** [influxdata/telegraf#15928]
### Relevant telegraf.conf

```toml
[global_tags]
  Account = 'MyAccount'
  "Key1" = 'Value1'
  'my.key' = 'Value2'

[inputs]
[[inputs.cpu]]
...
```

### Logs from Telegraf

```text
2024-09-23T17:11:25Z I! Loading config: tgraf-test.conf
2024-09-23T17:11:25Z E! loading config file tgraf-test.conf failed: error parsing data: line 4: invalid TOML syntax
```

### System info

Telegraf 1.32.0 (git: HEAD@dcfadf8b)

### Steps to reproduce

1. Create the test config as provided
2. Run command to start telegraf. Command: telegraf --config <config-name>

### Expected behavior

Telegraf should start without any error

### Actual behavior

Telegraf throws invalid TOML config as error

### Additional info

I've sample telegraf configuration that I'm using to start telegraf. Even though the configuration is a valid toml document, the telegraf doesn't seem to like it and keep complaining about the quotes around the table keys. I couldn't find any documentation around not being allowed to use quotes around the table keys. Is this a bug?
