### ISSUE TITLE
Possible breaking change in 1.31.0+ for hex binary filters 

### ISSUE THREAD

**Issue by mtucker119** [influxdata/telegraf#16000]
### Relevant telegraf.conf

```toml
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]
  namepass = ["snmp*"]

[agent]
  interval = "10s"
  round_interval = true


# # Brother Printer Toner Levels SNMP Collection
[[inputs.snmp]]
  agents = ["udp://192.168.XXX.XXX"]
  name = "snmp.printers"
  version = 1
  community = "public"
  interval = "30s"

  [[inputs.snmp.field]]
    name = "sysName"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.field]]
   name = "hexValues"
   oid = ".1.3.6.1.4.1.2435.2.3.9.4.2.1.5.5.8.0"
   
  [inputs.snmp.tags]
    prtMarkerSuppliesMaxCapacity = "100"
    specialHandling = "brother"



[[processors.parser]]
  order = 1
  parse_fields = ["hexValues"]
  merge = "override"
  data_format = "binary"

  [[processors.parser.binary]]
    entries = [
      { bits = 944, omit = true },
      { name = "Cyan Toner Cartridge", type = "uint8", assignment="field" },
      { bits = 160, omit = true },
      { name = "Magenta Toner Cartridge", type = "uint8", assignment="field" },
      { bits = 160, omit = true },
      { name = "Yellow Toner Cartridge", type = "uint8", assignment="field" },
      { bits = 160, omit = true },
      { name = "Black Toner Cartridge", type = "uint8", assignment="field" }
    ]

    [processors.parser.binary.filter]
      selection = [{ offset = 896, bits = 8, match = "0x82" }]

  [[processors.parser.binary]]
    entries = [
      { bits = 328, omit = true },
      { name = "Black Toner Cartridge", type = "uint8", assignment="field" }
    ]

    [processors.parser.binary.filter]
      selection = [{ offset = 280, bits = 8, match = "0x81" }]
      
      
[[processors.unpivot]]
  order = 3
  fieldexclude = ["hexValues"]
  tag_key = "prtMarkerSuppliesDescription"
  value_key ="prtMarkerSuppliesLevel"
  [processors.unpivot.tagpass]
    specialHandling = ["brother"]

[[processors.converter]]
  order = 4
  [processors.converter.tags]
    integer = ["prtMarkerSuppliesMaxCapacity"]
        string = ["specialHandling"]
```

### Logs from Telegraf

```text
2024-10-09T14:31:15Z E! [processors.parser] could not parse field hexValues: no matching configuration
```

### System info

telegraf 1.31.0+

### Steps to reproduce

1. Have a binary parser in conf file with a filter matching a hex value
2. Test with a version of telegraf < 1.31.0
3. The binary filter works
4. Test with version > 1.31.0
5. Receive the error message above when the filter doesn't work

The config above collects toner levels for Brother printers. The first filter matches color printers and the second one matches monochrome ones.  This can be easily reproduced by anyone with a Brother printer using the config above. 

### Expected behavior

The filter to still apply the same way it did in previous versions.

### Actual behavior

The filter doesn't work. 

### Additional info

This appears to be related to #14961 as adding `binary_encoding = "hex"` to the processors.parser options section fixes the issue.

I don't know if this is so much a bug as something that should be noted in the documentation as I didn't see it noted as a breaking change. Previous to this change the filter would match hex values without being explicitly told to, afterwards the encoding must be specified as hex, which took me a little bit to figure out.

Looking through the documentation, prior to this change there is an optional option, `hex_encoding`. It doesn't mention that it is enabled by default though.

```
#### 'hex_encoding' (optional)

If `true`, the input data is interpreted as a string containing hex-encoded
data like `C0 C7 21 A9`. The value is _case insensitive_ and can handle spaces,
however prefixes like `0x` or `x` are _not_ allowed.
```

Was this option enabled by default but not documented as such? I went over the docs/release notes very carefully, but I still could have missed something that pointed all this out. In which case, my apologies for wasting time.
