### ISSUE TITLE
SAP Hana input plugin

### ISSUE THREAD

**Issue by pyriand3r** [influxdata/telegraf#16024]
### Use Case

This is a proposal for a SAP Hana input plugin, allowing the Telegraf to execute queries against the SAP Hana database. We need the plugin to monitor SAP Systems with the Hana database. We would like to build the plugin oursef and contribute the plugin when it is finished. 

Our idea is to build a simple plugin that is able to execute arbitrary sql queries against a hana database server. The queries can be provided via the input plugin configuration and would consist of three parts:

- `name` - will be used as the measurement-name for the data
- `query` - the query itself
- `field_config` - a list of select-attributes from the query that will be used as fields. All other select-attributes will be considered as tags

For that we had two ideas. First one would be a list-in-list configuration:

```toml
[[inputs.hana]]
  queries = [
      [
          "<name = measurement>",
          "<query>",
          "<select1>,<select2>"
      ],
  ]
```

Second idea is more readable i guess but more complicated to write:

```toml
[[inputs.hana]]
    [[inputs.hana.query]]
        name = "<name = measurement>"
        query = "<query>"
        field_config = ["select1", "select2"]
    [[inputs.hana.query]]
        name = "<name2 = measurement>"
        query = "<query2>"
        field_config = ["select1"]
```

Rest of the configuration will be straight forward:

```toml
[[inputs.hana]]
  host = ""
  port = ""
  
  tls = false

  # for tls
  server_name = ""
  insecure_skip_verify = false
  root_ca_file = ""
  
  connection_type = "basic|dsn|jwt|x509"
  
  # for basic auth
  user = ""
  password = ""
  
  # for dsn auth
  dsn = ""
  
  # for jwt
  token = ""

  # for x509
  client_cert_file = ""
  client_key_file = ""
```

We wouldn't provide any queries, as everyone can build his/her own queries to gather the information he/she wants.

### Expected behavior

With this plugin one will be able to monitor hana databases and create queries by his/her own needs to gather the metrics that are needed.

### Actual behavior

No hana input plugin exist as far as we know, so it is atm not possible to fetch data from hana databases.
