### ISSUE TITLE
[inputs.modbus] Group coil/discrete/holding/input metric together

### ISSUE THREAD

**Issue by ffutop** [influxdata/telegraf#16031]
### Use Case

I know modbus plugin will provide predefined tags: slave_id, type

but even I force tag `type = ""`, the result still split in two records.

```toml
[[inputs.modbus]]
  name_override = "modbus"
  name = "modbus"
  timeout = "1s"
  controller = "tcp://172.16.2.31:502"
  configuration_type = "request"
  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "holding"
    fields = [{address = 101, name = '4x0102:INT', type = 'INT16'}]
    fields = [{address = 102, name = '4x0103:INT', type = 'INT16'}]

    [inputs.modbus.request.tags]
      type = ""

  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "input"
    fields = [{address = 134, name = '3x0135:INT', type = 'INT16'}]

    [inputs.modbus.request.tags]
      type = ""

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### Expected behavior

```
modbus,name=modbus,slave_id=1 4x0102:INT=0i,4x0103:INT=0i,3x0135:INT=0i 1729060160000000000
```

### Actual behavior

```
modbus,name=modbus,slave_id=1 4x0102:INT=0i,4x0103:INT=0i 1729060160000000000
modbus,name=modbus,slave_id=1 3x0135:INT=0i 1729060160000000000
```

### Additional info

I read the source, the code force split in four types.

Should we modify it, and group metric together if user-defined tag set `type = ""` or set same `type`?

```go
// https://github.com/influxdata/telegraf/blob/master/plugins/inputs/modbus/modbus.go#L245
tags := map[string]string{
	"name":     m.Name,
	"type":     cCoils,
	"slave_id": strconv.Itoa(int(slaveID)),
}
m.collectFields(acc, timestamp, tags, requests.coil)

tags["type"] = cDiscreteInputs
m.collectFields(acc, timestamp, tags, requests.discrete)

tags["type"] = cHoldingRegisters
m.collectFields(acc, timestamp, tags, requests.holding)

tags["type"] = cInputRegisters
m.collectFields(acc, timestamp, tags, requests.input)
```

```go
// https://github.com/influxdata/telegraf/blob/master/plugins/inputs/modbus/modbus.go#L520C1-L547C2
func (m *Modbus) collectFields(acc telegraf.Accumulator, timestamp time.Time, tags map[string]string, requests []request) {
	grouper := metric.NewSeriesGrouper()
	for _, request := range requests {
		for _, field := range request.fields {
			// Collect tags from global and per-request
			ftags := map[string]string{}
			for k, v := range tags {
				ftags[k] = v
			}
			for k, v := range field.tags {
				ftags[k] = v
			}
			// In case no measurement was specified we use "modbus" as default
			measurement := "modbus"
			if field.measurement != "" {
				measurement = field.measurement
			}

			// Group the data by series
			grouper.Add(measurement, ftags, timestamp, field.name, field.value)
		}
	}

	// Add the metrics grouped by series to the accumulator
	for _, x := range grouper.Metrics() {
		acc.AddMetric(x)
	}
}
```

**Comment by R290** [comment]
Any reason you can't use the merge aggregator? https://github.com/influxdata/telegraf/blob/master/plugins/aggregators/merge/README.md

**Comment by srebhan** [comment]
@ffutop please use the [`metric` configuration style](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/modbus#metric-configuration-style) which does exactly this!

**Comment by ffutop** [comment]
Hi, @srebhan . I tried metric configuration style, but there is no different.

### Configuration

```toml
[[inputs.modbus]]
  name_override = "modbus"
  name = "modbus"
  timeout = "1s"
  controller = "tcp://172.16.2.31:502"
  configuration_type = "metric"
  [[inputs.modbus.metric]]
    slave_id = 1
    byte_order = "ABCD"
    fields = [
      {register = "holding", address = 101, name = '4x0102:INT', type = 'INT16'},
      {register = "holding", address = 102, name = '4x0103:INT', type = 'INT16'},
      {register = "input", address = 134, name = '3x0135:INT', type = 'INT16'},
    ]

    [inputs.modbus.metric.tags]
      type = ""

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```

### Actual behavior

```
modbus,name=modbus,slave_id=1 4x0102:INT=0i,4x0103:INT=0i 1729125830000000000
modbus,name=modbus,slave_id=1 3x0135:INT=0i 1729125830000000000
```

### Extra

I'm not sure if I missed something. I've read the source code, and it force split four types.
