### ISSUE TITLE
[inputs.procstat] unable to filter by systemd_units with filter block

### ISSUE THREAD

**Issue by BDelacour** [influxdata/telegraf#16059]
### Relevant telegraf.conf

```toml
[[inputs.procstat.filter]]
     ## Name of the filter added as 'filter' tag
     name = "some-service"
  
     ## Service filters, only one is allowed
     ## Systemd unit names (wildcards are supported)
     systemd_units = ["some-service"]
     ## CGroup name or path (wildcards are supported)
     # cgroups = []
     ## Supervisor service names of hypervisorctl management
     # supervisor_units = []
     ## Windows service names
     # win_service = []
  
     ## Process filters, multiple are allowed
     ## Regular expressions to use for matching against the full command
     # patterns = ['.*']
     ## List of users owning the process (wildcards are supported)
     # users = ['*']
     ## List of executable paths of the process (wildcards are supported)
     # executables = ['*']
     ## List of process names (wildcards are supported)
     # process_names = ['*']
     ## Recursion depth for determining children of the matched processes
     ## A negative value means all children with infinite depth
     # recursion_depth = 0
```

### Logs from Telegraf

```text
N/A
```

### System info

Telegraf 1.31.3, Debian 11

### Steps to reproduce

1. Setup a systemd service
2. Make sure `telegraf` user has enough permissions
3. Configure `inputs.procstat.filter` block with the `systemd` service you create
4. Run a `telegraf --test` and see that nothing is detected

### Expected behavior

We should be able to filter by systemd units

### Actual behavior

We have a typo in the code, we are using `CGroups` instead of `SystemdUnits` to filter

### Additional info

https://github.com/influxdata/telegraf/blob/master/plugins/inputs/procstat/filter.go#L110
