### ISSUE TITLE
v1.32.X Windows logtarget setting deprecation seems like a breaking change

### ISSUE THREAD

**Issue by Hr0bar** [influxdata/telegraf#16100]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 100
  metric_buffer_limit = 1000
  collection_jitter = "0s"
  flush_interval = "1m"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
  logtarget = "eventlog"
```

### Logs from Telegraf

```text
[telegraf] Error running agent: contradicting setting between 'logtarget' and 'logformat'
```

### System info

v1.32.2 Windows server 2019

### Steps to reproduce

1. Upgrade from v1.31.2 to  v1.32.2 on Windows, dont touch any configs
2. telegraf.exe --service start
3. Get startup error "[telegraf] Error running agent: contradicting setting between 'logtarget' and 'logformat'"
...

### Expected behavior

Telegraf starts

### Actual behavior

Telegraf doesnt start

### Additional info

Hi, we upgraded telegraf on Windows from 1.31.2 to 1.32.2 and we get an error startup error that is supposed to be only a deprecation until v1.40.0:

```
	case "eventlog":
		msg := "Agent setting %q is deprecated, please set %q to %q and remove this setting!"
		deprecation := "The setting will be removed in v1.40.0."
		log.Printf("W! "+msg+" "+deprecation, "logtarget", "logformat", "eventlog")
		if cfg.LogFormat != "" && cfg.LogFormat != "eventlog" {
			return errors.New("contradicting setting between 'logtarget' and 'logformat'")
		}
		cfg.LogFormat = "eventlog"
```

We use the deprecated:
`  logtarget = "eventlog"`

in config and we get the ""contradicting setting between 'logtarget' and 'logformat'"" startup error.

The issue is that we DO NOT set "logformat" anywhere so this error seems wrongly raised.

The error condition has "cfg.LogFormat != """ so it must be filled somehow to some default value and then this error is raised ?
