### ISSUE TITLE
query single bits from registers

### ISSUE THREAD

**Issue by spkis** [influxdata/telegraf#16117]
### Relevant telegraf.conf

```toml
[[inputs.modbus.metric]]
    slave_id = 1
    
    ##  |---ABCD -- Big Endian (Motorola)
    ##  |---DCBA -- Little Endian (Intel)
    ##  |---BADC -- Big Endian with byte swap
    ##  |---CDAB -- Little Endian with byte swap    
    byte_order = "ABCD"
    measurement = "Telemetry"

    # From sungrow documentation: visit all register by subtracting 1 from the register address
    # the address here is already decremented from the documentation's value

    fields = [
  #  { register="input", name = "Positive_Ground_Resistance",             type = "UINT16",  scale=0.1,  address = 10147}, # 82. 
  #     { register="input", name = "Negative_Ground_Resistance",             type = "UINT16",  scale=0.1,  address = 10148}, # 83.

  #     { register="input", name = "Low_Insulation_Resistance",              type = "UINT16",  scale=1.0,  address = 10149}, # 84. 0: normal, 1: warning; SC500TL only
  #     { register="input", name = "Module_A3_Temperature",                  type = "INT16",   scale=0.1,  address = 10150}, # 85.      
  #     { register="input", name = "Module_B3_Temperature",                  type = "INT16",   scale=0.1,  address = 10151}, # 86.     
  #     { register="input", name = "Module_C3_Temperature",                  type = "INT16",   scale=0.1,  address = 10152}, # 87.      
  #     { register="input", name = "Carrier_Wave_Sync_Master_Slave",         type = "UINT16",  scale=1.0,  address = 10153}, # 88. 0: Master, 1: Slave; SC500TL-V25 only                                      
   
      { register="input", name = "Device_State_bit",                           type = "UINT32",  scale=1.0,  address = 10199, bit = 0},
      { register="input", name = "Device_State_bit2",                           type = "UINT32",  scale=1.0,  address = 10199, bit = 1},
      { register="input", name = "Device_State_bit3",                           type = "UINT32",  scale=1.0,  address = 10199, bit = 2}, # 1. TODO Appendix 1
      { register="input", name = "Fault_State_1",                          type = "UINT32",  scale=1.0,  address = 10201}, # 2. TODO Appendix 2     
      { register="input", name = "Fault_State_2",                          type = "UINT32",  scale=1.0,  address = 10203}, # 3. TODO Appendix 2      
      { register="input", name = "Alarm_State",                            type = "UINT32",  scale=1.0,  address = 10205}, # 4. TODO Appendix 2            
   
   
   
    ]
```

### Logs from Telegraf

```text
2024-10-31T15:54:56Z I! Loading config: telegraf/telegraf_test.conf
2024-10-31T15:54:56Z I! Starting Telegraf 1.32.2 brought to you by InfluxData the makers of InfluxDB
2024-10-31T15:54:56Z I! Available plugins: 235 inputs, 9 aggregators, 32 processors, 26 parsers, 62 outputs, 5 secret-stores
2024-10-31T15:54:56Z I! Loaded inputs: modbus
2024-10-31T15:54:56Z I! Loaded aggregators:
2024-10-31T15:54:56Z I! Loaded processors:
2024-10-31T15:54:56Z I! Loaded secretstores:
2024-10-31T15:54:56Z I! Loaded outputs: file
2024-10-31T15:54:56Z I! Tags enabled: host=MacBookPro
2024-10-31T15:54:56Z I! [agent] Config: Interval:2s, Quiet:false, Hostname:"MacBookPro", Flush Interval:10s
2024-10-31T15:54:56Z D! [agent] Initializing plugins
2024-10-31T15:54:56Z E! [telegraf] Error running agent: could not initialize input inputs.modbus: configuration invalid: bit option cannot be used for type "UINT32" of field "Device_State_bit2"
```

### System info

1.32.2

### Steps to reproduce

1. If I just read bit 0 from the first, it works. 
2. If I want the other bits read out, it doesn't work. 

### Expected behavior

My expectation is, that I can query OR define multiple times the same register and then add the bit to it, and give it a unique name. 

### Actual behavior

Doesn't work, saying uint32 doesn't support bits. 

### Additional info

<img width="1146" alt="image" src="https://github.com/user-attachments/assets/58595bcf-57c9-484b-9681-0ef05292bed9">
