### ISSUE TITLE
Issue with telegraf exeeding ~1000 input nodes

### ISSUE THREAD

**Issue by Sakamichy** [influxdata/telegraf#16128]
### Relevant telegraf.conf

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = "1s"

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true
  
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  urls = ["https://localhost:8086"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "INNOVAFEED"

  ## Destination bucket to write into.
  bucket = "SCADA_PROD_HIST"

  ## Use TLS but skip chain & host verification
  insecure_skip_verify = true
# Retrieve data from OPCUA devices
[[inputs.opcua]]
  ## Metric name
  name = "opcua_prod"
  #
  ## OPC UA Endpoint URL
  endpoint = "opc.tcp://$OPC_URL:49320"
  #
  ## Maximum time allowed to establish a connect to the endpoint.
  connect_timeout = "5s"
  #
  ## Maximum time allowed for a request over the estabilished connection.
  request_timeout = "4s"
  #
  ## Security policy, one of "None", "Basic128Rsa15", "Basic256",
  ## "Basic256Sha256", or "auto"
  security_policy = "Basic256Sha256"
  #security_policy = "None"
  #
  ## Security mode, one of "None", "Sign", "SignAndEncrypt", or "auto"
  security_mode = "SignAndEncrypt"
  #security_mode = "None"
  #
  ## Path to cert.pem. Required when security mode or policy isn't "None".
  ## If cert path is not supplied, self-signed cert and key will be generated.
  certificate = "$CERT_PATH"
  #
  ## Path to private key.pem. Required when security mode or policy isn't "None".
  ## If key path is not supplied, self-signed cert and key will be generated.
  private_key = "$KEY_PATH"
  #
  ## Authentication Method, one of "Certificate", "UserName", or "Anonymous".  To
  ## authenticate using a specific ID, select 'Certificate' or 'UserName'
  auth_method = "Anonymous"
  #
  ## Option to select the metric timestamp to use. Valid options are:
  ##     "gather" -- uses the time of receiving the data in telegraf
  ##     "server" -- uses the timestamp provided by the server
  ##     "source" -- uses the timestamp provided by the source
  timestamp = "gather"

  [[inputs.opcua.group]]
    name = "SENSOR"
    namespace = "2"
    identifier_type = "s"
    default_tags = {zone = "zone_5130"}
    nodes = [
      {name="5130_HR_ECART_TYPE_MAINTENANCE.5130_HR_ECART_TYPE_MAINTENANCE", identifier="API15_Histo1.zone_5130.5130_HR_ECART_TYPE_MAINTENANCE.5130_HR_ECART_TYPE_MAINTENANCE"},
      ...(x1000)
identifier="API15_Histo1.zone_5130.5130CTA2100_PSET_FC2101.5130CTA2100_PSET_FC2101"},
      {name="5130CTA2100_PSET_HV2101_DEFGEL.5130CTA2100_PSET_HV2101_DEFGEL", 
    ]
```

### Logs from Telegraf

```text
root@SRV-INNOV-INFLUX:/var/log/telegraf# sudo journalctl -u API15_Histo1.zone_5130.service --since "3 minutes ago"
-- Journal begins at Wed 2024-09-25 17:42:40 CEST, ends at Thu 2024-09-26 17:42:19 CEST. --
sept. 26 17:40:17 SRV-INNOV-INFLUX systemd[1]: Starting "Historisation zone_5130 sur API15"...
sept. 26 17:40:17 SRV-INNOV-INFLUX curl[3159]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
sept. 26 17:40:17 SRV-INNOV-INFLUX curl[3159]:                                  Dload  Upload   Total   Spent    Left  Speed
sept. 26 17:40:17 SRV-INNOV-INFLUX curl[3159]: [158B blob data]
sept. 26 17:40:17 SRV-INNOV-INFLUX systemd[1]: Started "Historisation zone_5130 sur API15".
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Loading config: /etc/telegraf/API15_Histo1.zone_5130.conf
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Starting Telegraf 1.31.0 brought to you by InfluxData the makers of InfluxDB
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Available plugins: 234 inputs, 9 aggregators, 32 processors, 26 parsers, 60 outputs, 6 secret-stores
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Loaded inputs: opcua
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Loaded aggregators:
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Loaded processors:
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Loaded secretstores:
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Loaded outputs: influxdb_v2
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! Tags enabled:
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [agent] Initializing plugins
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [inputs.opcua] Initialising OpcUAInputClient
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [inputs.opcua] Initialising OpcUAClient
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [inputs.opcua] Initialising node to metric mapping
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [agent] Connecting outputs
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [agent] Attempting connection to [outputs.influxdb_v2]
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [agent] Successfully connected to outputs.influxdb_v2
sept. 26 17:40:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:17Z D! [agent] Starting service inputs
sept. 26 17:40:20 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:20Z D! [inputs.opcua] Connecting OPC UA Client to server
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua] Configuring OPC UA connection options
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  security policy from configuration http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  User cares about both the policy (http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256) and security mode (MessageSecurityModeSignAndEncrypt)
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  Server has 4 endpoints
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#None, mode MessageSecurityModeNone, level 16
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256, mode MessageSecurityModeSignAndEncrypt, level 51
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua]  Security policy and mode found. Using server endpoint opc.tcp://192.168.10.169:49320 for security. Policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z D! [inputs.opcua] Connected to OPC UA Server
sept. 26 17:40:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:21Z E! [inputs.opcua] Error in plugin: registering nodes failed: EOF
sept. 26 17:40:27 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:27Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:40:30 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:30Z D! [inputs.opcua] Disconnecting from OPC UA Server
sept. 26 17:40:30 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:30Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: No processing could be done because there was nothing to do. StatusBadNothingToDo (0x800F0000)
sept. 26 17:40:37 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:37Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:40:40 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:40Z D! [inputs.opcua] Connecting OPC UA Client to server
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua] Configuring OPC UA connection options
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  security policy from configuration http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  User cares about both the policy (http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256) and security mode (MessageSecurityModeSignAndEncrypt)
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  Server has 4 endpoints
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#None, mode MessageSecurityModeNone, level 16
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256, mode MessageSecurityModeSignAndEncrypt, level 51
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua]  Security policy and mode found. Using server endpoint opc.tcp://192.168.10.169:49320 for security. Policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z D! [inputs.opcua] Connected to OPC UA Server
sept. 26 17:40:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:41Z E! [inputs.opcua] Error in plugin: registering nodes failed: EOF
sept. 26 17:40:47 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:47Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:40:50 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:50Z D! [inputs.opcua] Disconnecting from OPC UA Server
sept. 26 17:40:50 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:50Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: No processing could be done because there was nothing to do. StatusBadNothingToDo (0x800F0000)
sept. 26 17:40:57 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:40:57Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:41:00 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:00Z D! [inputs.opcua] Connecting OPC UA Client to server
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua] Configuring OPC UA connection options
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  security policy from configuration http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  User cares about both the policy (http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256) and security mode (MessageSecurityModeSignAndEncrypt)
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  Server has 4 endpoints
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#None, mode MessageSecurityModeNone, level 16
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256, mode MessageSecurityModeSignAndEncrypt, level 51
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua]  Security policy and mode found. Using server endpoint opc.tcp://192.168.10.169:49320 for security. Policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z D! [inputs.opcua] Connected to OPC UA Server
sept. 26 17:41:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:01Z E! [inputs.opcua] Error in plugin: registering nodes failed: EOF
sept. 26 17:41:07 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:07Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:41:11 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:11Z D! [inputs.opcua] Disconnecting from OPC UA Server
sept. 26 17:41:11 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:11Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: No processing could be done because there was nothing to do. StatusBadNothingToDo (0x800F0000)
sept. 26 17:41:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:17Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:41:20 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:20Z D! [inputs.opcua] Connecting OPC UA Client to server
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua] Configuring OPC UA connection options
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  security policy from configuration http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  User cares about both the policy (http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256) and security mode (MessageSecurityModeSignAndEncrypt)
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  Server has 4 endpoints
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#None, mode MessageSecurityModeNone, level 16
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256, mode MessageSecurityModeSignAndEncrypt, level 51
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua]  Security policy and mode found. Using server endpoint opc.tcp://192.168.10.169:49320 for security. Policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z D! [inputs.opcua] Connected to OPC UA Server
sept. 26 17:41:21 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:21Z E! [inputs.opcua] Error in plugin: registering nodes failed: EOF
sept. 26 17:41:27 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:27Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:41:30 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:30Z D! [inputs.opcua] Disconnecting from OPC UA Server
sept. 26 17:41:30 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:30Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: No processing could be done because there was nothing to do. StatusBadNothingToDo (0x800F0000)
sept. 26 17:41:37 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:37Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:41:40 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:40Z D! [inputs.opcua] Connecting OPC UA Client to server
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua] Configuring OPC UA connection options
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  security policy from configuration http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  User cares about both the policy (http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256) and security mode (MessageSecurityModeSignAndEncrypt)
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  Server has 4 endpoints
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#None, mode MessageSecurityModeNone, level 16
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256, mode MessageSecurityModeSignAndEncrypt, level 51
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua]  Security policy and mode found. Using server endpoint opc.tcp://192.168.10.169:49320 for security. Policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z D! [inputs.opcua] Connected to OPC UA Server
sept. 26 17:41:41 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:41Z E! [inputs.opcua] Error in plugin: registering nodes failed: EOF
sept. 26 17:41:47 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:47Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:41:50 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:50Z D! [inputs.opcua] Disconnecting from OPC UA Server
sept. 26 17:41:50 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:50Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: No processing could be done because there was nothing to do. StatusBadNothingToDo (0x800F0000)
sept. 26 17:41:57 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:41:57Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:42:00 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:00Z D! [inputs.opcua] Connecting OPC UA Client to server
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua] Configuring OPC UA connection options
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  security policy from configuration http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  User cares about both the policy (http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256) and security mode (MessageSecurityModeSignAndEncrypt)
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  Server has 4 endpoints
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#None, mode MessageSecurityModeNone, level 16
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256, mode MessageSecurityModeSignAndEncrypt, level 0
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  Evaluating endpoint opc.tcp://192.168.10.169:49320, policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256, mode MessageSecurityModeSignAndEncrypt, level 51
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua]  Security policy and mode found. Using server endpoint opc.tcp://192.168.10.169:49320 for security. Policy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z D! [inputs.opcua] Connected to OPC UA Server
sept. 26 17:42:01 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:01Z E! [inputs.opcua] Error in plugin: registering nodes failed: EOF
sept. 26 17:42:07 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:07Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
sept. 26 17:42:10 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:10Z D! [inputs.opcua] Disconnecting from OPC UA Server
sept. 26 17:42:10 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:10Z E! [inputs.opcua] Error in plugin: RegisterNodes Read failed: No processing could be done because there was nothing to do. StatusBadNothingToDo (0x800F0000)
sept. 26 17:42:17 SRV-INNOV-INFLUX telegraf[3160]: 2024-09-26T15:42:17Z D! [outputs.influxdb_v2]  Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf 1.31.0,  Debian GNU/Linux 11 (bullseye)

### Steps to reproduce

PREREQUISITE
- OPC UA server (Kepware) running
- ore than 1000 tags configured on the opc server
STEP
1.create the config file 
2.start telegraf with the config file created earlier (telegraf --config telegraf_config_file)

### Expected behavior

The Telegraf agent is able to obtain data from the OPC server regardless of the number of input nodes

### Actual behavior

Impossible to get the data 
> Error in plugin: registering nodes failed: EOF
