### ISSUE TITLE
DeprecationWarning: Option “timeout” of plugin inputs.snmp_trap

### ISSUE THREAD

**Issue by Nagendra1995** [influxdata/telegraf#16137]
### Relevant telegraf.conf

```toml
[[inputs.snmp_trap]]
path = [ “/usr/share/snmp/mibs” ]
service_address = “udp://:162”
version = “2c”
```

### Logs from Telegraf

```text
"DeprecationWarning: Option “timeout” of plugin “inputs.snmp_trap” deprecated since version 1.20.0 and will be removed in 2.0.0: unused option"
```

### System info

1.27.3

### Steps to reproduce

1. Restarting the Telegraf service after adding new community strings for the V2 Input

### Expected behavior

There shouldn't be this warning because “timeout” of plugin “inputs.snmp_trap” is not used in the confing file

### Actual behavior

Getting this deprecation warning

### Additional info

Operating System: Red Hat Enterprise Linux 8.10 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-553.22.1.el8_10.x86_64
Architecture: x86-64

NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
