### ISSUE TITLE
Deprecate `processors.ifname` plugin

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#16152]
### Use Case

With the addition of the `processors.snmp_lookup`, the `processors.ifname` has become redundant.

### Expected behavior

Users of `processors.ifname` plugin should receive a deprecation warning.

### Actual behavior

No deprecation warning.

### Additional info

The following config will use the same `ifDescr` fallback as `processors.ifname` when there is no `ifName` value on the device.

```toml
[[processors.snmp_lookup]]
  agent_tag = "agent"
  index_tag = "ifIndex"

  [[processors.snmp_lookup.tag]]
    oid = ".1.3.6.1.2.1.2.2.1.2"
    name = "ifName"

  [[processors.snmp_lookup.tag]]
    oid = ".1.3.6.1.2.1.31.1.1.1.1"
    name = "ifName"
```

```diff
- foo,agent=127.0.0.1,ifIndex=2 field=123
+ foo,agent=127.0.0.1,ifIndex=2,ifName=eth0 field=123
```
