### ISSUE TITLE
Docker container not starting due to Kubernetes security constraints.

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#16168]
### Please direct all support questsions to slack or the forums. Thank you.

Telegraf Container Image: telegraf:1.29.5-alpine
Environment: Kubernetes
After some security policies were implemented on my Kubernetes cluster my Telegraf container is not able to run as it once was.

This is the error I am getting in the container logs:
```
Failed to set additional capabilities on /usr/bin/telegraf
su-exec: setgroups: Operation not permitted
unable to set CAP_SETFCAP effective capability: Operation not permitted
```
From what I understood this is because the security policies will block any container from starting if it:
- Tries to escalate to root privileges. Pod cannot contain - securityContext: `allowPrivilegeEscalation: true`
- If a seccomp profile is not set.
- If any sysctls are in the deployment configuration.
- If containers perform a restricted host OS capability such as: raw packet generation, host device exposer, or mounting the docker socker outside of the Kubernetes context.

Would it be possible to update the container configurations so that it complies with these security policies?

**Comment by adamanteye** [comment]
I don't understand why encouraging users to use "slack" or "forums". They are less likely to be indexed by Google. Actually this issue is still there.

**Comment by adamanteye** [comment]
```yaml
        - name: telegraf
          image: telegraf:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9273
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
          command: ["/usr/bin/telegraf"]
          args:
            - "--config"
            - "/etc/telegraf/telegraf.conf"
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
```

This might be of help. Skip entrypoint to avoid ad-hoc CAP settings.
