### ISSUE TITLE
[[inputs.win_wmi]] dropped values - Error in plugin: Object server is stopping when OLE service contacts it

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#16179]
### Relevant telegraf.conf

```toml
[[inputs.win_wmi]]
   name_override = "mymeasurement"
   interval = "1m"

   [[inputs.win_wmi.method]]
     namespace = 'root\default'
     class_name = "StdRegProv"
     method = "GetDWordValue"
     [inputs.win_wmi.method.arguments]
       hDefKey = '2147483650'
       sSubKeyName = 'Software\Microsoft\windows NT\CurrentVersion'
       sValueName = 'UBR'
     [inputs.win_wmi.method.fields]
       uValue = "ole_stop_test01"

  [[inputs.win_wmi.method]]
    namespace = 'root\default'
    class_name = "StdRegProv"
    method = "GetStringValue"
    [inputs.win_wmi.method.arguments]
      hDefKey = '2147483650'
      sSubKeyName = 'Software\Microsoft\windows NT\CurrentVersion'
      sValueName = 'CurrentBuild'
    [inputs.win_wmi.method.fields]
         sValue = "ole_stop_test02"
```

### Logs from Telegraf

```text
[inputs.win_wmi] Error in plugin: Object server is stopping when OLE service contacts it
```

### System info

Telegraf 1.31.3, 1.32.1 e.g. Windows 2019/2016

### Steps to reproduce

1. Run given telegraf config (query at least two values with `[[inputs.win_wmi.method]]`
2. Usually after some hours You will see inside Telegraf log ERROR messages "_[inputs.win_wmi] Error in plugin: Object server is stopping when OLE service contacts it_"
3. When this error occurs, `[[inputs.win_wmi.method]]` does not successfully query value, so "sValue" is null/empty/<no value>

### Expected behavior

In case of this error "Object server is stopping when OLE service contacts it" (CO_E_SERVER_STOPPING 0x80080008), Telegraf should retry query until inputs timeout has been reached or try to avoid this error.

### Actual behavior

Error occurs and metric is not created.
