### ISSUE TITLE
Slurm plugin error getting diag

### ISSUE THREAD

**Issue by romxero** [influxdata/telegraf#16170]
### Relevant telegraf.conf

```toml
[[inputs.slurm]]
name_prefix = "ctx_dojo_slurm_metrics_"
## Slurmrestd URL. Both http and https can be used as schemas.
url = "http://dojo-controller:6842"
username = "telegraf"
token = ""

[[outputs.file]]
files = ["stdout"]
namepass = ["ctx_dojo_slurm_metrics_*"]
data_format = "csv"
```

### Logs from Telegraf

```text
2024-11-09T00:35:00Z E! [inputs.slurm] Error in plugin: error getting diag: json: cannot unmarshal number 20360765221 into Go struct field V0038DiagRpcm.statistics.rpcs_by_message_type.total_time of type int32
```

### System info

Telegraf 1.32.2, Ubuntu 20.04, Slurm 23.07

### Steps to reproduce

1. Write the configuration with port number.
2. Start Telegraf
3. Error happening
...

### Expected behavior

Expected behavior would be to have the slurm metrics dumped out into stdout

### Actual behavior

error when getting info from slurm
