### ISSUE TITLE
always_include_global_tags depends on config file naming/order

### ISSUE THREAD

**Issue by 1tft** [influxdata/telegraf#16226]
### Relevant telegraf.conf

```toml
# general config file telegraf.conf
[global_tags]
  globaltag = "globaltagvalue"

[agent]
  always_include_global_tags = true


# custom config file myconfig.conf
[[inputs.mock]]
  metric_name = "mock"
  taginclude = [ "mylocaltag" ]

 [[inputs.mock.constant]]
   name = "constant"
   value = "myvalue"

 [inputs.mock.tags]
   mylocaltag = "mylocaltagvalue"
```

### Logs from Telegraf

```text
[...]
2024-11-25T11:21:40Z I! Loading config: /etc/telegraf/telegraf.conf
2024-11-25T11:21:40Z I! Loading config: /etc/telegraf/telegraf.d/myconfig.conf
[...]

vs.

[...]
2024-11-25T11:23:13Z I! Loading config: /etc/telegraf/telegraf.d/myconfig.conf
2024-11-25T11:23:13Z I! Loading config: /etc/telegraf/telegraf.conf
[...]
```

### System info

Telegraf 1.32.1

### Steps to reproduce

telegraf  --config /etc/telegraf/telegraf.d/telegraf.conf  --config /etc/telegraf/myconfig.conf --test
produces a different/correct result
`> mock,globaltag=globaltagvalue,host=abc,mylocaltag=mylocaltagvalue constant="myvalue" 1732533700000000000`
than
telegraf  --config /etc/telegraf/myconfig.conf --config /etc/telegraf/telegraf.d/telegraf.conf --test
`> mock,mylocaltag=mylocaltagvalue constant="myvalue" 1732533794000000000`

### Expected behavior

We expect same result, independent from config file name/order, because when you write same config in only one global file it is working correctly:
```
[[inputs.mock]]
  metric_name = "mock"
  taginclude = [ "mylocaltag" ]

 [[inputs.mock.constant]]
   name = "constant"
   value = "myvalue"

 [inputs.mock.tags]
   mylocaltag = "mylocaltagvalue"


[global_tags]
  globaltag = "globaltagvalue"

[agent]
  always_include_global_tags = true
```

### Actual behavior

Telegraf produces differents results depending on order of config file reading/naming.

### Additional info

Outside of `--test` modus you dont see this error, when you use general /etc/telegraf/telegraf.conf and custom configs inside /etc/telegraf/telegraf.d(*.conf, because telegraf.conf is always loaded at beginning.
So its not so important for us, to fix this bug soon.
