### ISSUE TITLE
tagexclude does not work with tagpass

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#1623]
### Relevant telegraf.conf:
```
[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "telegraf"
  [outputs.influxdb.tagpass]
    foo = ["bar"]
  tagexclude = ["foo"]

[[inputs.exec]]
  commands = ["echo test,foo=bar value=1i"]
  data_format = "influx"
```
### System info:

Telegraf 1.0 beta 3

### Steps to reproduce:

1. run telegraf with above config
2. query influxdb with `select * from test`

### Expected behavior:
`foo` tag to not be present
```
name: test
----------
time				host		value
1470869730000000000		xxxxxxxxxxx	1
```

### Actual behavior:
`foo` tag is present
```
name: test
----------
time			foo	host		value
1470869730000000000	bar	xxxxxxxxxxx	1
```

### Additional info:
Works as expected without the `[outputs.influxdb.tagpass]` config param.

The intent here is to have multiple influxdb databases, and use tags to control which data points go to which database, but to not actually insert those tags into the database.

**Comment by sparrc** [comment]
looks like this is a documentation issue around an annoying toml eccentricity, putting the tagpass map at the end will fix it:

```toml
[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "telegraf"
  tagexclude = ["foo"]
  [outputs.influxdb.tagpass]
    foo = ["bar"]

[[inputs.exec]]
  commands = ["echo test,foo=bar value=1i"]
  data_format = "influx"
```
