### ISSUE TITLE
[inputs.syslog] Allow setting `MaxMessageLength` under octet counting mode from config

### ISSUE THREAD

**Issue by falau** [influxdata/telegraf#16249]
### Use Case

Hello,

I occasionally need to receive messages larger than the limit per RFC5425 (8192 bytes), but this is currently unsupported and hardcoded in the parser. Is it possible to make it a configurable option for using octet counting framing & TCP? Like:
```toml
[[inputs.syslog]]
  server = "tcp://127.0.0.1:6514"
  framing = "octet-counting"
  # Allow the octet-counting parser to process messages larger than the default limit 8192
  max_message_length = 16384
  # ...
```
Thanks :)

### Expected behavior

https://github.com/influxdata/telegraf/blob/26366121a8f3d34b917996f6f66bf22da709b2e6/plugins/inputs/syslog/syslog.go#L160-L169

Something like this can be inserted in the createStreamDataHandler function:
(for `non-transparent`, setting this option is a no-op, but it can be put under a `== "octet-counting"` condition to be more specific for sure)
```go
if s.MaxMessageLength > 0 {
  opts = append(opts, syslog.WithMaxMessageLength(s.MaxMessageLength))
}
```

### Actual behavior

Currently, there is no such option, so this default value will be used:

https://github.com/leodido/go-syslog/blob/46afcecb86058ec9598480d6140f404266a02868/octetcounting/parser.go#L29
