### ISSUE TITLE
Telegraf knx:listener - does not load with DPT 9.029

### ISSUE THREAD

**Issue by Ing-Dom** [influxdata/telegraf#16294]
### Relevant telegraf.conf

```toml
[[inputs.knx_listener]]
  ## Type of KNX-IP interface.
  ## Can be either "tunnel" or "router".
  service_type = "tunnel"

  ## Address of the KNX-IP interface.
  service_address = "192.168.178.101:3671"

  ## Measurement definition(s)

  [[inputs.knx_listener.measurement]]
    name = "Zentral - HKL - Zuluft Feuchte Absolut"
    dpt = "9.029"
    addresses = ["30/2/102"]
```

### Logs from Telegraf

```text
2024/12/10 22:29:46	stdout	2024-12-10T21:29:46Z E! [telegraf] Error running agent: could not initialize input inputs.knx_listener: cannot create datapoint-type "9.029" for address "30/2/102"
2024/12/10 22:29:46	stdout	2024-12-10T21:29:46Z I! Loading config: /etc/telegraf/telegraf.conf
```

### System info

not relevant

### Steps to reproduce

1. use knx_listener
2. use dpt 9.029
3. start telegraf

### Expected behavior

parse dpt correctly

### Actual behavior

error in logfile, does not start up
