### ISSUE TITLE
telegraf 1.33.0 does not start with a valid certificate in inputs.influxdb_listener

### ISSUE THREAD

**Issue by wargamez** [influxdata/telegraf#16306]
### Relevant telegraf.conf

```toml
[[inputs.influxdb_listener]]
#   ## Address and port to host InfluxDB listener on
  service_address = ":8186"
#
#   ## maximum duration before timing out read of the request
  read_timeout = "10s"
#   ## maximum duration before timing out write of the response
  write_timeout = "10s"
#
#   ## Maximum allowed HTTP request body size in bytes.
#   ## 0 means to use the default of 32MiB.
#   max_body_size = "32MiB"
#
#   ## Optional tag name used to store the database.
#   ## If the write has a database in the query string then it will be kept in this tag name.
#   ## This tag can be used in downstream outputs.
#   ## The default value of nothing means it will be off and the database will not be recorded.
#   # database_tag = ""
#
#   ## If set the retention policy specified in the write query will be added as
#   ## the value of this tag name.
#   # retention_policy_tag = ""
#
#   ## Set one or more allowed client CA certificate file names to
#   ## enable mutually authenticated TLS connections
#   tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]
#
#   ## Add service certificate and key
  tls_cert = "/etc/nginx/ssl/server.crt"
  tls_key = "/etc/nginx/ssl/private.key"
```

### Logs from Telegraf

```text
N/A
```

### System info

telegraf 1.33.0

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

I expect it to start

### Actual behavior

It does not start. However downgrading to 1.32.3 makes it work again...
