### ISSUE TITLE
intel_powerstat plugin fails to parse removal version

### ISSUE THREAD

**Issue by alysondeives** [influxdata/telegraf#16376]
### Relevant telegraf.conf

```toml
[agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "$HOSTNAME"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true
 
 
    [[outputs.prometheus_client]]
      listen = ":9273"
 
 
    [[inputs.intel_powerstat]]
      cpu_metrics = [
        "cpu_frequency",
        "cpu_busy_frequency",
        "cpu_temperature",
        "cpu_c0_state_residency",
        "cpu_c1_state_residency",
        "cpu_c6_state_residency"
      ]
      package_metrics = [
        "current_power_consumption",
        "current_dram_power_consumption",
        "thermal_design_power",
        "cpu_base_frequency",
        "uncore_frequency"
      ]
    [[inputs.intel_pmu]]
      event_definitions = [
        "/etc/telegraf/events_definition.json"
      ]
      [[inputs.intel_pmu.core_events]]
         events = [
             "INST_RETIRED.ANY",
             "CPU_CLK_UNHALTED.THREAD",
             "CPU_CLK_UNHALTED.C01",
             "CPU_CLK_UNHALTED.C02"
         ]
         events_tag = "c0wait"
         perf_group = true
    [[inputs.ipmi_sensor]]
      interval = "30s"
      metric_version = 1
      timeout = "20s"
    [[inputs.mem]]
    [[inputs.cpu]]
      collect_cpu_time = false
      core_tags = false
      percpu = true
      report_active = false
      totalcpu = true
```

### Logs from Telegraf

```text
2025-01-06T19:58:23Z E! Determining log-level for option cpu_metrics in plugin inputs.intel_powerstat failed: cannot parse 'removal' version "1.35.0;": strconv.ParseInt: parsing "0;": invalid syntax
```

### System info

Telegraf 1.33

### Steps to reproduce

1. Run telegraf with intel_powerstat input plugin enabled

### Expected behavior

Telegraf should run with no issues.

### Actual behavior

Telegraf fails at parsing removal version "1.35,0;"
