### ISSUE TITLE
inputs.x509_cert trims leading 0 for serial_number

### ISSUE THREAD

**Issue by atartareanu** [influxdata/telegraf#16418]
### Relevant telegraf.conf

```toml
[[inputs.x509_cert]]
  ## List certificate sources, support wildcard expands for files
  ## Prefix your entry with 'file://' if you intend to use relative paths
	sources = ["https://example.com:443"]
```

### Logs from Telegraf

```text
> x509_cert,common_name=*.example.com,country=US,host=EC2AMAZ-O9TGCGG,issuer_common_name=DigiCert\ Global\ G3\ TLS\ ECC\ SHA384\ 2020\ CA1,locality=Los\ Angeles,ocsp_stapled=yes,ocsp_status=good,ocsp_verified=yes,organization=Internet\ Corporation\ for\ Assigned\ Names\ and\ Numbers,province=California,public_key_algorithm=ECDSA,san=*.example.com\,example.com,serial_number=ad893bafa68b0b7fb7a404f06ecaf9a,signature_algorithm=ECDSA-SHA384,source=https://example.com:443,type=leaf,verification=valid age=578404i,enddate=1768521599i,expiry=31043994i,ocsp_next_update=1738013222i,ocsp_produced_at=1737412984i,ocsp_status_code=0i,ocsp_this_update=1737412022i,startdate=1736899200i,verification_code=0i 1737477606000000000
```

### System info

Telegraf 1.33.1 (git: HEAD@44f3a504)

### Docker

As you can see, the serial number for the certificate is 
serial_number=ad893bafa68b0b7fb7a404f06ecaf9a
but the true certificate serial is
0AD893BAFA68B0B7FB7A404F06ECAF9A

### Steps to reproduce

all the details are in the log, also the true serial number can be obtained with the command
openssl s_client -connect example.com:443 2>/dev/null | openssl x509 -serial -noout
serial=0AD893BAFA68B0B7FB7A404F06ECAF9A

### Expected behavior

the serial_number should be 0AD893BAFA68B0B7FB7A404F06ECAF9A

### Actual behavior

the serial number is ad893bafa68b0b7fb7a404f06ecaf9a
