### ISSUE TITLE
filter processor has error in the sample configuration

### ISSUE THREAD

**Issue by ceri** [influxdata/telegraf#16433]
### Relevant telegraf.conf

```toml
# currently suggested at bottom of https://github.com/influxdata/telegraf/tree/master/plugins/processors/filter

[[processors.filter]]
  namepass = ["machine"]

  [[processors.filter.rule]]
    tags = {"status" = "OK"}
```

### Logs from Telegraf

```text
2025-01-26T18:48:27Z E! loading config file /usr/local/etc/telegraf.conf failed: error parsing filter, unmarshalling failed: line 73: cannot unmarshal TOML string into []string
```

### System info

Telegraf 1.33, FreeBSD 15-CURRENT

### Steps to reproduce

1. Read the configuration at https://github.com/influxdata/telegraf/tree/master/plugins/processors/filter
2. Try to use it

### Expected behavior

It works

### Actual behavior

It throws the error
