### ISSUE TITLE
gNMI depth extension

### ISSUE THREAD

**Issue by Mrflatt** [influxdata/telegraf#16432]
### Use Case

gMNI has few well-known extensions, which telegraf does not support yet. 
[Depth](https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-depth.md) extension would be good first one, to allow controlling depth which response is parsed.

I already have made changes to use with our usecases, and will open pr, if well-known extensions should be supported by telegraf

### Expected behavior

If depth value is added, `[]*gnmi_ext.Extension` should be added to `gnmi.SubscribeRequest`.
```toml
[[inputs.gnmi]]
  ## Address and port of the gNMI GRPC server
  addresses = ["127.0.0.1:57777"]

  ## define credentials
  username = "cisco"
  password = "cisco"

  ## gRPC Depth Extension
  ## See https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-depth.md
  ## If specified, adds gNMI depth extension, which controls depth of the subtree to be returned in the response.
  depth = 2
```

### Actual behavior

No depth option
