### ISSUE TITLE
"time" field from libvirt input plugin never reach influxdb

### ISSUE THREAD

**Issue by elacour** [influxdata/telegraf#16443]
### Relevant telegraf.conf

```toml
[[inputs.libvirt]]
statistics_groups = ["cpu_total"]
```

### Logs from Telegraf

```text
libvirt_cpu,domain_name=xxxxx,host=yyyyyy system=1595411964000u,time=16924971591000u,user=15329559626000u 1738079263000000000
```

### System info

telegraf 1.33.1-1, debian 12, influxdb 2.7.11-1

### Steps to reproduce

Configure libvirt input plugin to export cpu stats to influxdb

### Expected behavior

Cpu "time" is available as a field in influxdb

### Actual behavior

Only "system" and "user" fields are available on InfluxDB.

### Additional info

Seems related to InfluxDB "bug" https://github.com/influxdata/influxdb/issues/23024 suggesting "time" cannot be used as a field name. Solution may be to use another name such as using metric prefix like "cpu_time" ?

**Comment by srebhan** [comment]
@elacour while I agree that naming the field `time` is unfortunate, renaming it will cause trouble for users of other outputs. So we do have three ways forward:
1. Keep the current naming and use
```toml
[[processors.rename]]
  namepass = ["libvirt_cpu"]
  [[processors.rename.replace]]
    field = "time"
    dest = "cpu_time"
  [[processors.rename.replace]]
    field = "user"
    dest = "cpu_user"
  [[processors.rename.replace]]
    field = "system"
    dest = "cpu_system"
```
2. Add a flag to prefix the three CPU fields with `cpu_` and make this the default in some future.
3. Rename the fields and add a big fat warning to the readme (and changelog).

I will discuss this with the team and come back to you next week...
