### ISSUE TITLE
socket listener collectd stops working on v1.33.1

### ISSUE THREAD

**Issue by dmgeurts-mm** [influxdata/telegraf#16455]
### Relevant telegraf.conf

```toml
[[inputs.socket_listener]]
  service_address = "udp://127.0.0.1:25826"
  data_format = "collectd"
  collectd_typesdb = ["/usr/share/collectd/types.db", "/usr/local/share/freeradius/radsniff_types.db"]
  collectd_security_level = "none"
  collectd_parse_multivalue = "split"
```

### Logs from Telegraf

```text
Apologies, I failed to collect debug logs as I encountered this on a production Radius server.

Nothing was logged in the systemd journal and when I verified output via stdin nothing was shown.
```

### System info

Ubuntu 20.04

### Steps to reproduce

1. Upgrade from <1.33.x to 1.33.1 and lo
2. Spend a few hours checking everything but Telegraf
3. Downgrade to v1.32.3 and metrics are back.
...

### Expected behavior

Unaffected collectd processing

### Actual behavior

No errors logged, and no output at all.
