### ISSUE TITLE
inputs.proxmox not supports additional_vmstats_tags = ["vmid"]

### ISSUE THREAD

**Issue by enrico-nxw** [influxdata/telegraf#16457]
### Relevant telegraf.conf

```toml
[inputs]
[[inputs.proxmox]]
  base_url = "https://MY_IP:8006/api2/json"
  api_token = "MY_TOKEN"
  node_name = "MY_NODE"
  additional_vmstats_tags = ["vmid"] #TODO: there is a bug
  insecure_skip_verify = true
```

### Logs from Telegraf

```text
E! loading config file /etc/telegraf/telegraf.conf failed: plugin inputs.proxmox: line 17: configuration specified the fields ["additional_vmstats_tags"], but they were not used. This is either a typo or this config option does not exist in this version.
```

### System info

image: telegraf:1.33.1 (telegraf:1.33.1-alpine)

### Steps to reproduce

1. docker run -v telegraf.conf:/etc/telegraf/telegraf.conf telegraf:1:33.1-alpine

### Expected behavior

vm_id=xxx as tag

### Actual behavior

configuration specified the fields ["additional_vmstats_tags"], but they were not used.
