### ISSUE TITLE
Telegraf Containers Crashing with Exit Code 137

### ISSUE THREAD

**Issue by Noy-Simon** [influxdata/telegraf#16460]
We have Telegraf running in our environment, and recently, our containers started crashing unexpectedly, entering a CrashLoopBackOff state with exit code 137.

Upon reviewing the logs, we observed that Telegraf initializes successfully but crashes immediately afterward. There are no error events available for analysis, including in the Kubelet logs.

An unusual observation is that when we modify the container's entrypoint to ["tail", "-f", "/dev/null"] (essentially keeping it alive without executing Telegraf), and then manually start Telegraf using kubectl exec, it runs without any issues.

**Troubleshooting Steps & Findings:**

- The issue persists across different versions of Telegraf, including the latest release.
- Other clusters running the same setup are unaffected.
- The underlying nodes have not changed since before the crashes began.
- The issue is not related to insufficient resource allocation.

Would appreciate any insights or suggestions on potential causes or further debugging approaches.

**Comment by Noy-Simon** [comment]
up

**Comment by jdaleyftp** [comment]
@Noy-Simon i think im seeing the same -- did you ever get anywhere with this?

**Comment by Noy-Simon** [comment]
nope... @jdaleyftp

**Comment by jerry1333** [comment]
I have same issue when upgrading from 1.26.0 to any higher version. Nothing else changes but telegraf doesnt even create log file to show what's wrong. When i get back to 1.26.0 everything works again.

docker-compose.yml
```
services:
  telegraf-otherdata:
    container_name: telegraf-otherdata
    hostname: telegraf-otherdata
    network_mode: bridge
    dns:
      - 10.0.30.1
      - 1.1.1.1
    restart: always
    volumes:
      - './data:/etc/telegraf'
    image: telegraf:1.26.0
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128M
```
