### ISSUE TITLE
inputs.sflow unable to record the tcp_flags in fields in Telegraf inputs

### ISSUE THREAD

**Issue by vinodsapavat** [influxdata/telegraf#16498]
### Relevant telegraf.conf

```toml
[[inputs.sflow]]
  ## Address to listen for sFlow packets.
  ##   example: service_address = "udp://:6343"
  ##            service_address = "udp4://:6343"
  ##            service_address = "udp6://:6343"
  service_address = "udp://:6343"

  ## Set the size of the operating system's receive buffer.
  ##   example: read_buffer_size = "64KiB"
  # read_buffer_size = ""
#
#
#
#
[[outputs.file]]
 files = ["stdout"]
 data_format = "influx"
```

### Logs from Telegraf

```text
sflow,agent_address=175.20.201.11,device_role=Sflow-switch,dst_ip=175.16.0.10,dst_mac=50:00:00:72:8b:31,dst_port=4784,ether_type=IPv4,header_protocol=ETHERNET-ISO88023,host=netengtgrafa01,hostname=$HOST_NAME,input_ifindex=2,output_ifindex=1073741823,sample_direction=ingress,source_id_index=2,source_id_type=0,src_ip=172.16.0.4,src_mac=00:00:00:cb:00:00,src_port=57123 ip_fragment_offset=0i,bytes=4480i,header_length=66i,sampling_rate=64i,udp_length=32i,ip_dscp="48",ip_ecn="0",ip_flags=0i,ip_total_length=52i,ip_ttl=255i,frame_length=70i,drops=0i 1739201667470663023

Device is sending the below FLOWSAMPLE with field "TCPFlags":"16", however inputs.sflow Telegraf connector not capturing the field in inputs.


  "sampleType_tag":"0:1",
   "sampleType":"FLOWSAMPLE",
   "sampleSequenceNo":"12986",
   "sourceId":"0:1002000",
   "meanSkipCount":"64",
   "samplePool":"832064",
   "dropEvents":"0",
   "inputPort":"1002000",
   "outputPort":"1073741823",
   "elements":[{
     "flowBlock_tag":"0:1001",
     "extendedType":"SWITCH",
     "in_vlan":"4094",
     "in_priority":"0",
     "out_vlan":"4094",
     "out_priority":"0"
    },
    {
     "flowBlock_tag":"0:1",
     "flowSampleType":"HEADER",
     "headerProtocol":"1",
     "sampledPacketSize":"74",
     "strippedBytes":"4",
     "headerLen":"70",
     "headerBytes":"50-00-00-72-8B-31-50-00-00-15-F4-E8-81-00-0F-FE-08-00-45-E0-00-34-7B-23-40-00-FF-06-AB-BE-A9-FE-00-02-A9-FE-00-03-11-50-B0-32-D8-8B-9E-C9-8E-18-38-68-80-10-01-FA-A0-B0-00-00-01-01-08-0A-CA-8B-42-9D-4E-0A-25-85",
     "dstMAC":"500000728b31",
     "srcMAC":"50000015f4e8",
     "decodedVLAN":"4094",
     "decodedPriority":"0",
     "ethernet_type":"2048",
     "IPSize":"52",
     "ip.tot_len":"52",
     "srcIP":"169.254.0.2",
     "dstIP":"169.254.0.3",
     "IPProtocol":"6",
     "IPTOS":"224",
     "IPTTL":"255",
     "IPID":"9083",
     "TCPSrcPort":"4432",
     "TCPDstPort":"45106",
     "TCPFlags":"16"
    }
   ]
  }
 ]
}
```

### System info

Telegraf  version 1.31.0

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

sflow,agent_address=175.20.201.11,device_role=Sflow-switch,dst_ip=175.16.0.10,dst_mac=50:00:00:72:8b:31,dst_port=4784,ether_type=IPv4,header_protocol=ETHERNET-ISO88023,host=netengtgrafa01,hostname=$HOST_NAME,input_ifindex=2,output_ifindex=1073741823,sample_direction=ingress,source_id_index=2,source_id_type=0,src_ip=172.16.0.4,src_mac=00:00:00:cb:00:00,src_port=57123 ip_fragment_offset=0i,bytes=4480i,header_length=66i,sampling_rate=64i,udp_length=32i,ip_dscp="48",ip_ecn="0",ip_flags=0i,ip_total_length=52i,ip_ttl=255i,frame_length=70i,drops=0i 1739201667470663023, TCPFlags = 0i 16

### Actual behavior

TCPFlags = 0i 16 is not captured

**Comment by srebhan** [comment]
@vinodsapavat could you please test the [netflow input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/netflow) with

```toml
[[inputs.netflow]]
  service_address = "udp://:6343"
  protocol = "sflow v5"
```

and check if that's what you want? The netflow plugin is the successor of the sflow plugin...
