### ISSUE TITLE
Openweathermap plugin for Telegraf - **forecast** Endpoint Superseeded

### ISSUE THREAD

**Issue by suckowbiz** [influxdata/telegraf#16536]
### Relevant telegraf.conf

```toml
[[inputs.openweathermap]]
  ## OpenWeatherMap API key.
  app_id = "*********" # Obfuscated

  ## City ID's to collect weather data from.
  city_id = ["2950159"]

  ## Language of the description field. Can be one of "ar", "bg",
  ## "ca", "cz", "de", "el", "en", "fa", "fi", "fr", "gl", "hr", "hu",
  ## "it", "ja", "kr", "la", "lt", "mk", "nl", "pl", "pt", "ro", "ru",
  ## "se", "sk", "sl", "es", "tr", "ua", "vi", "zh_cn", "zh_tw"
  lang = "de"

  ## APIs to fetch; can contain "weather" or "forecast".
  fetch = ["weather", "forecast"]

  ## OpenWeatherMap base URL
  base_url = "https://api.openweathermap.org/"

  ## Timeout for HTTP response.
  response_timeout = "5s"

  ## Preferred unit system for temperature and wind speed. Can be one of
  ## "metric", "imperial", or "standard".
  units = "metric"

  ## Style to query the current weather; available options
  ##   batch      -- query multiple cities at once using the "group" endpoint
  ##   individual -- query each city individually using the "weather" endpoint
  ## You should use "individual" here as it is documented and provides more
  ## frequent updates. The default is "batch" for backward compatibility.
  query_style = "individual"

  ## Query interval to fetch data.
  ## By default the global 'interval' setting is used. You should override the
  ## interval here if the global setting is shorter than 10 minutes as
  ## OpenWeatherMap weather data is only updated every 10 minutes.
  interval = "10s"
```

### Logs from Telegraf

```text
telegraf  | 2025-02-20T15:45:01Z I! Loading config: /etc/telegraf/telegraf.conf
telegraf  | 2025-02-20T15:45:01Z I! Starting Telegraf 1.33.1 brought to you by InfluxData the makers of InfluxDB
telegraf  | 2025-02-20T15:45:01Z I! Available plugins: 236 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
telegraf  | 2025-02-20T15:45:01Z I! Loaded inputs: openweathermap
telegraf  | 2025-02-20T15:45:01Z I! Loaded aggregators:
telegraf  | 2025-02-20T15:45:01Z I! Loaded processors:
telegraf  | 2025-02-20T15:45:01Z I! Loaded secretstores:
telegraf  | 2025-02-20T15:45:01Z I! Loaded outputs: file influxdb_v2
telegraf  | 2025-02-20T15:45:01Z I! Tags enabled: host=telegraf
telegraf  | 2025-02-20T15:45:01Z I! [agent] Config: Interval:5s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
telegraf  | 2025-02-20T15:45:01Z D! [agent] Initializing plugins
telegraf  | 2025-02-20T15:45:01Z D! [agent] Connecting outputs
telegraf  | 2025-02-20T15:45:01Z D! [agent] Attempting connection to [outputs.influxdb_v2]
telegraf  | 2025-02-20T15:45:01Z D! [agent] Successfully connected to outputs.influxdb_v2
telegraf  | 2025-02-20T15:45:01Z D! [agent] Attempting connection to [outputs.file]
telegraf  | 2025-02-20T15:45:01Z D! [agent] Successfully connected to outputs.file
telegraf  | 2025-02-20T15:45:01Z D! [agent] Starting service inputs
telegraf  | weather,city=GothamCity,city_id=4711,condition_id=803,condition_main=Clouds,country=DE,forecast=*,host=telegraf cloudiness=63i,condition_description="Überwiegend bewölkt",condition_icon="04d",humidity=61i,rain=0,temperature=4,wind_degrees=154,wind_speed=5.92,sunrise=1740032673000000000i,sunset=1740069290000000000i,feels_like=-0.34,visibility=10000i,pressure=1024,snow=0 1740066310000000000
```

### System info

Telegraf 1.33.1

### Steps to reproduce

1. Configure Telegraf to query Openweathermap
2. Run Telegraf
3. Find **no** data for **forecast** but only for **current** endpoint.

### Expected behavior

Telegraf allows to configure the new endpoints:

- **forecast16** (Daily Forecast 16 days)
- **forecast5** (3-hour forecast for 5 days)*
- **hourly-forecast** (Hourly Forecast, 4 days)

*Comes in "Free Access" subscription.

Source:  https://openweathermap.org/price

At the moment there is no such field as **forecast** but the input validator allows only for that value and gives an error when using others (see above).

### Actual behavior

"forecast" endpoint is not queried as it seems to be replaced by forecast5|forecast16|hourly-forecast.

### Additional info

This portion of code:

```golang
for _, fetch := range n.Fetch {
		switch fetch {
		case "forecast":
			for _, cityID := range n.CityID {
				wg.Add(1)
				go func(city string) {
					defer wg.Done()
					acc.AddError(n.gatherForecast(acc, city))
				}(cityID)
			}
		case "weather":
			switch n.QueryStyle {
			case "individual":
				for _, cityID := range n.CityID {
					wg.Add(1)
					go func(city string) {
						defer wg.Done()
						acc.AddError(n.gatherWeather(acc, city))
					}(cityID)
				}
			case "batch":
				for _, cityIDs := range n.cityIDBatches {
					wg.Add(1)
					go func(cities string) {
						defer wg.Done()
						acc.AddError(n.gatherWeatherBatch(acc, cities))
					}(cityIDs)
				}
			}
		}
	}
```

... is topic to change.

Is this situation known and under development?
