### ISSUE TITLE
TOML Parsing Error with kafka_consumer and json_v2 (and other parsers): cannot unmarshal TOML array table

### ISSUE THREAD

**Issue by akeeltaj** [influxdata/telegraf#16541]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[inputs.kafka_consumer]]
  brokers = ["kafka:9092"]
  topics = ["netflowOut"]
  consumer_group = "telegraf_minimal_group"
  data_format = "json_v2"

  [[inputs.kafka_consumer.json_v2]]
    [[inputs.kafka_consumer.json_v2.object]]
      measurement_name = "test_measurement"
      timestamp_path = "_time_ns"
      timestamp_format = "unix_ns"
      tags = []
      fields = []

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = $INFLUX_TOKEN
  organization = "home"
  bucket = "test_bucket"
```

### Logs from Telegraf

```text
2025-02-22T18:46:14Z E! loading config file /etc/telegraf/telegraf.conf failed: error parsing kafka_consumer, adding parser failed: line 25: (json_v2.Object.Fields) cannot unmarshal TOML array into map[string]string (need slice)
```

### System info

Telegraf Versions Tested:  latest (1.33.2) 1.32.3 1.31.3 1.27.0 (tested with json parser) ; Operating System:  Distributor ID: Ubuntu Description:    Ubuntu 24.04.1 LTS Release:        24.04 Codename:       noble ;  Docker Version:  Client:  Version:           26.1.3  API version:       1.45  Go version:        go1.22.2  Git commit:        26.1.3-0ubuntu1~24.04.1  Built:             Mon Oct 14 14:29:26 2024  OS/Arch:           linux/amd64  Context:           default  Server:  Engine:   Version:          26.1.3   API version:      1.45 (minimum version 1.24)   Go version:       go1.22.2   Git commit:       26.1.3-0ubuntu1~24.04.1   Built:            Mon Oct 14 14:29:26 2024   OS/Arch:          linux/amd64   Experimental:     false  containerd:   Version:          1.7.12   GitCommit:  runc:   Version:          1.1.12-0ubuntu3.1   GitCommit:  docker-init:   Version:          0.19.0   GitCommit:

### Docker

 telegraf:
    image: telegraf:latest
    volumes:
      - /mnt/data/configs/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
    environment:
      - INFLUX_TOKEN="<my influxdb token>"

    restart: always

### Steps to reproduce

1. Create a telegraf.conf file with the minimal json_v2 configuration provided above. Ensure the INFLUX_TOKEN environment variable is correctly set
2. Create a docker-compose.yml file with the content provided above. Update the image tag in the telegraf service to match the Telegraf version being tested (e.g., telegraf:1.33.2, telegraf:1.31.3). Also, update the InfluxDB password and token.
3. Run docker-compose up -d to start the containers
4. Check the Telegraf logs using docker logs <telegraf_container_id> (or docker-compose logs telegraf).
5. Observe the TOML parsing error in the logs.

### Expected behavior

Telegraf should parse the configuration file without errors and begin consuming data from the netflowOut Kafka topic. Data should be written to the test_bucket in InfluxDB.

### Actual behavior

Telegraf fails to start due to the TOML parsing error: cannot unmarshal TOML array table into map[string]string (need slice).

### Additional info

We have tried numerous variations of the configuration, including:

Different Telegraf versions (listed above).
The json parser (with tag_keys and json_string_fields).
The xpath_json parser (with correct array-of-tables syntax).
Minimal configurations with no tags or fields.
Hardcoding the InfluxDB token.
Testing with a different input plugin (inputs.cpu), which also resulted in a TOML parsing error.
We have checked for hidden characters in the configuration file using xxd.

A detailed history of our troubleshooting steps can be found in this Google Gemini chat: (Paste the link to this chat here)

Sample Kafka Data (from netflowOut topic):

`{
    "Time": "2025-02-22T18:23:05.000Z",
    "Device": "192.168.1.1:2055",
    "FlowVersion": 10,
    "First": 127120970,
    "Last": 127120970,
    "Bytes": 40,
    "Packets": 1,
    "InEthernet": 0,
    "OutEthernet": 2,
    "SrcIP": "27.58.200.224",
    "DstIP": "23.95.132.53",
    "SrcPort": 59046,
    "DstPort": 44338,
    "NextHop": "27.58.200.1",
    "SrcMask": 0,
    "DstMask": 0,
    "Protocol": 6,
    "TCPFlags": 20,
    "DstMAC": "00-00-00-00-00-00",
    "SrcMAC": "00-00-00-00-00-00",
    "Measurement": "netflow_flow",
    "FlowID": "aib4eO3koT4",
    "DstDNS": "23-95-132-53-host.colocrossing.com",
    "_time_ns": 1740248585000000000
}`

**Comment by srebhan** [comment]
Please note the `fields` setting in the `[[inputs.kafka_consumer.json_v2.object]]` denotes an **array** in your configuration, as the error says, but we do expect a **map** there like in the [README of the parser](https://github.com/influxdata/telegraf/blob/master/plugins/parsers/json_v2/README.md)

```toml
            [inputs.file.json_v2.object.fields]
                key = "int"
```

Anyway, if you don't have any fields to specify you can also remove the line entirely.
