### ISSUE TITLE
Telegraf 1.33.2 unable to send windows metrics to Amazon Managed Prometheus

### ISSUE THREAD

**Issue by arjunkchr** [influxdata/telegraf#16550]
### Relevant telegraf.conf

```toml
[[inputs.mem]]
  fieldpass = ["used_percent"]

[[inputs.win_perf_counters]]
  UseWildcardsExpansion = true

  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["_Total"]
    Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% Processor Time", "% User Time", "Interrupts/sec"]
    Measurement = "win.cpu"
    IncludeTotal = true

[[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Counters = ["Bytes Received/sec", "Bytes Sent/sec", "Packets Outbound Discarded",
                "Packets Outbound Errors", "Packets Received Discarded", "Packets Received Errors",
                "Packets Received/sec", "Packets Sent/sec"]
    Instances = ["*"]
    Measurement = "win.net"
    IncludeTotal = true

[[outputs.http]]
  url = "<amp_url>"
  ## Data format to output.
  data_format = "prometheusremotewrite"
  ## AWS Configuration
  region = "<aws_region>"
  aws_service = "<aws_service>"
  access_key = "<aws_access_key>"
  secret_key = "<aws_secret_key>"

  [outputs.http.headers]
     Content-Type = "application/x-protobuf"
     Content-Encoding = "snappy"
     X-Prometheus-Remote-Write-Version = "0.1.0"
```

### Logs from Telegraf

```text
2025-02-24T20:06:34Z E! [agent] Error writing to outputs.http: when writing to [https://<amp_workspace>/api/v1/remote_write] received status code: 400. body: sample invalid metric name: "win.net_Bytes_Sent_persec"
2025-02-24T20:06:59Z E! [agent] Error writing to outputs.http: when writing to [https://<amp_workspace>/api/v1/remote_write] received status code: 400. body: sample invalid metric name: "win.net_Packets_Sent_persec"
```

### System info

1.33.2

### Steps to reproduce

1.Deploy telegraf 1.33.2 on windows node to collect windows host metrics and use http output plugin to send to amazon managed prometheus.
2. Notice AMP doesn't accept the incoming metrics.
3. Revert back to 1.33.1 and observe everything works as expected.
...

### Expected behavior

AMP should accept the incoming metrics. 

### Actual behavior

AMP doesn't accept the incoming metrics

### Additional info

Revert back to 1.33.1 and observe everything works as expected.
