### ISSUE TITLE
Incorrect Host Network Statistics in Docker Environment – inputs.net Collects Container Instead of Host

### ISSUE THREAD

**Issue by kpinarci** [influxdata/telegraf#16564]
### Relevant telegraf.conf

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 50000
  precision = ""
  omit_hostname = false
  debug = false
  quiet = false

[[outputs.prometheus_client]]
  listen = ":9274"
  metric_version = 2
  expiration_interval = "0s"
  collectors_exclude = ["gocollector", "process"]
  string_as_label = true
  export_timestamp = false

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]
  devices = ["sd*", "vd*", "rbd*"]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.net]]
  ignore_protocol_stats = true

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  timeout = "5s"
  perdevice = false
  total = true
  container_name_include = []
  container_name_exclude = []
  docker_label_include = []
  docker_label_exclude = []
```

### Logs from Telegraf

```text
Host: cat /proc/net/dev
      Receive      | Transmit
eth0: 384698420779 105473786 

telegraf-container:  cat /hostfs/proc/net/dev
      Receive      | Transmit
eth0: 1165882    6379
```

### System info

Telegraf: 1.33.3-alpine docker: 26.1.5-ce docker-compose: version 2.22.0 VM: SLES VERSION_ID="15.6"

### docker-compose.yaml
```yaml
services:
  telegraf:
    image: "telegraf/bare:1.33.3-alpine"
    container_name: telegraf
    hostname: "test-server"
    stdin_open: true
    tty: true
    restart: always
    user: "1000:476"
    command: [ "telegraf", "--config", "/etc/telegraf/config_telegraf.conf" ]
    privileged: true
    environment:
      HOST_MOUNT_PREFIX: "/hostfs"
      HOST_PROC: "/hostfs/proc"
      HOST_SYS: "/hostfs/sys"
      HOST_ETC: "/hostfs/etc"
      HOST_VAR: "/hostfs/var"
      HOST_RUN: "/hostfs/run"
      TZ: "Europe/Berlin"
    volumes:
      - ./conf/config_telegraf.conf:/etc/telegraf/config_telegraf.conf:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    networks:
      - monitoring
    healthcheck:
      test: ["CMD-SHELL", "telegraf -test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
```

### Steps to reproduce

I am running Telegraf (Version 1.33.3, Alpine Image) in a Docker container via docker-compose on a SLES 15 SP6 host. The goal is to collect all host metrics (CPU, memory, disk, and network). However, the network statistics are not captured correctly:

When mounting the entire root filesystem as /hostfs, the inputs.net plugin only collects the container’s network statistics, not those of the host.
A separate mount (e.g., /proc/1) provides correct values under /proc/1/net/dev but results in the loss of other system metrics, as these are typically sourced from /hostfs/proc.
Using the network_host mode is not an option in our environment. Additionally, the documentation for inputs.net does not offer an option to configure an alternative proc path (e.g., /hostfs_net) to exclusively capture host network statistics. Selective mounting of the required files is also not feasible.

### Expected behavior

Telegraf should fully and accurately collect all host metrics with the current configuration. In particular, the inputs.net plugin must be able to capture the host’s network statistics—such as those from /proc/1/net/dev or via a configurable alternative proc path—without losing other metrics (e.g., CPU, memory, disk, etc.). 

### Actual behavior

- With the volume mount /hostfs, only the container's network statistics are collected.
- A separate mount of /proc/1 (e.g., to capture host network stats) provides correct network data (e.g., under /proc/1/net/dev) but causes the loss of other critical metrics (CPU, disk, memory, etc.) which are gathered from /hostfs/proc.

- The documentation for the inputs.net plugin does not allow for an alternative proc path, so switching to inputs.nstat does not completely resolve the issue.

### Additional info

Is there any plan to extend inputs.net to allow configuration of an alternative proc path (e.g., /hostfs_net)?
Are there alternative best practices to correctly capture host network statistics in Docker environments when the network_host mode is not an option?

I look forward to your feedback and thank you for your support.

**Comment by srebhan** [comment]
@kpinarci please test the binary in PR #16580, available as soon as CI finished the tests, and let me know if this fixes the issue!

**Comment by kpinarci** [comment]
Hi @srebhan ,

Thank you for the quick support. I installed the binary you provided in an Alpine container and tested it, but even with version 1.34.0, the issue persists. I'm comparing the values from `/proc/net/dev` and `/hostfs/proc/net/dev` on the host, and they differ. However, the values under `/hostfs/proc/1/net/dev` appear to be correct.

Dockerfile: 
```
FROM alpine:3.21.3

RUN apk add --no-cache \
        iputils=20240905-r0 \
        ca-certificates=20241121-r1 \
        net-snmp-tools=5.9.4-r1\
        procps \
        lm_sensors \
        tzdata=2025a-r0 \
        su-exec=0.2-r3 \
        libcap \
        curl \
    && update-ca-certificates

# The binary is from the PR #16580
# https://github.com/influxdata/telegraf/issues/16564
RUN curl -fsSL "https://output.circle-artifacts.com/output/job/501beca0-279d-4399-ab2f-0586c2ffba0a/artifacts/0/build/dist/telegraf-1.34.0~81973666_linux_amd64.tar.gz" -o /tmp/telegraf.tar.gz \
  && tar -xzf /tmp/telegraf.tar.gz -C /tmp \
  && mv /tmp/telegraf-1.34.0/usr/bin/telegraf /usr/bin/telegraf \
  && chmod +x /usr/bin/telegraf \
  && rm -rf /tmp/telegraf.tar.gz \
  && mkdir -p /etc/telegraf/telegraf.d \
  && mv /tmp/telegraf-1.34.0/etc/telegraf/telegraf.conf /etc/telegraf/ \
  && addgroup -S telegraf \
  && adduser -S telegraf -G telegraf \
  && chown -R telegraf:telegraf /etc/telegraf

EXPOSE 8125/udp 8092/udp 8094

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["telegraf"]
```

docker-compose volumes:
```
volumes:
  - ./conf/config_telegraf.conf:/etc/telegraf/config_telegraf.conf:ro
  - /var/run/docker.sock:/var/run/docker.sock:rw
  - /:/hostfs:ro
```

Telegraf version:
```
telegraf --version
Telegraf 1.34.0-81973666 (git: pull/16580@81973666)
```

Output from host: 
```
cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:    3956      26    0    0    0     0          0         0     3956      26    0    0    0     0       0          0
  eth0: 269423032463 47933356    0 2039    0     0          0         0 202184146582 25399362    0    0    0     0       0          0
br-309ec3c88403: 209317131362 29845769    0    0    0     0          0         0 276047511397 47153254    0    0    0     0       0          0
docker0: 2840536   53779    0    0    0     0          0         0 433765072   68201    0    0    0     0       0          0
veth57ebce6: 1272701098  929479    0    0    0     0          0         0 2283546294 1231694    0    0    0     0       0          0
veth1747c64: 295496812769 38616724    0    0    0     0          0         0 305845136874 47711309    0    0    0     0       0          0
vethdba9003:       0       0    0    0    0     0          0         0   189228    3160    0    0    0     0       0          0
veth691d0b9: 1103148171 5264109    0    0    0     0          0         0 84112713715 7573397    0    0    0     0       0          0
vethcbee97f: 27497561860 3401087    0    0    0     0          0         0 126820166305 10224642    0    0    0     0       0          0
veth4ecc140: 34234719   13078    0    0    0     0          0         0  1392237    8920    0    0    0     0       0          0
vethde59138: 3628365    1665    0    0    0     0          0         0   652112    2506    0    0    0     0       0          0
veth037ca10:       0       0    0    0    0     0          0         0      788       8    0    0    0     0       0          0
vethd0a6112: 3921337519  186022    0    0    0     0          0         0 16256552  201825    0    0    0     0       0          0
```

Output from inside of new telegraf:1.34.0-alpine:
```
docker exec -it telegraf sh
cat /hostfs/proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eth0:  676354    2599    0    0    0     0          0         0  3764152    1727    0    0    0     0       0          0
```

Output from inside of new telegraf:1.34.0-alpine "/hostfs/proc/1/net/dev"
```
cat /hostfs/proc/1/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:    3956      26    0    0    0     0          0         0     3956      26    0    0    0     0       0          0
  eth0: 269846047431 47997188    0 2039    0     0          0         0 202525545924 25432537    0    0    0     0       0          0
br-309ec3c88403: 209666072961 29883550    0    0    0     0          0         0 276478278461 47217509    0    0    0     0       0          0
docker0: 2840536   53779    0    0    0     0          0         0 433765072   68201    0    0    0     0       0          0
veth57ebce6: 1274134945  930324    0    0    0     0          0         0 2285342175 1232782    0    0    0     0       0          0
veth1747c64: 295926901384 38664908    0    0    0     0          0         0 306274789776 47763319    0    0    0     0       0          0
vethdba9003:       0       0    0    0    0     0          0         0   189228    3160    0    0    0     0       0          0
veth691d0b9: 1104411709 5269838    0    0    0     0          0         0 84208799478 7581667    0    0    0     0       0          0
vethcbee97f: 27503374218 3404174    0    0    0     0          0         0 127153015813 10246517    0    0    0     0       0          0
veth4ecc140: 35966410   13737    0    0    0     0          0         0  1462389    9367    0    0    0     0       0          0
vethde59138: 3812421    1749    0    0    0     0          0         0   684956    2632    0    0    0     0       0          0
veth037ca10:       0       0    0    0    0     0          0         0      788       8    0    0    0     0       0          0
vethd0a6112: 4261371428  201729    0    0    0     0          0         0 17614047  218778    0    0    0     0       0          0
```

Output from nload (Outgoing) 
```
Curr: 1666423.00 Byte/s
Avg: 1478626.00 Byte/s
Min: 1334429.00 Byte/s
Max: 2001753.00 Byte/s
Ttl: 189.82 GByte
````

**Comment by srebhan** [comment]
Well the Telegraf plugin reads `$HOST_PROC/proc/net/dev` so the values in there must be correct. I don't know why the values between the hostfs file in the container and you host do differ but that's certainly outside of Telegrafs scope... :-)

**Comment by srebhan** [comment]
@kpinarci please let me know if I should reopen this issue!

**Comment by kpinarci** [comment]
Hi @srebhan,

Thanks for pointing me to the discussion. What confuses me is that, despite mounting the directory `/:/hostfs`, the container still overrides it with its own values.  
Any data mounted into a container should be accessible within it and should not be replaced by the container itself (since it originates from a different location).  
Here’s the output from inside the container, where I can see that `/proc/net/dev` and `/hostfs/proc/net/dev` contain the same values:  

```
cat /proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eth0:  145408     562    0    0    0     0          0         0   788790     370    0    0    0     0       0          0
/ # cat /hostfs/proc/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
  eth0:  146972     568    0    0    0     0          0         0   797425     374    0    0    0     0       0          0
```

However, when checking `/hostfs/proc/1/net/dev`, I can see the correct host values:  

```
/ # cat /hostfs/proc/1/net/dev
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
    lo:    3956      26    0    0    0     0          0         0     3956      26    0    0    0     0       0          0
  eth0: 397489253630 68575777    0 2094    0     0          0         0 307795926685 35756025    0    0    0     0       0          0
```

Unfortunately, `pid=host` did not resolve the issue, but `--net=host` did. However, I am using Docker precisely because I want to **isolate my host and network**. If I now switch to `network_mode=host`, there are no real restrictions anymore—I might as well just run the binary directly, which defeats the purpose of using Docker.  

Using **`--pid=host` and `--net=host`** may work as a temporary workaround, but they are **not a proper solution**.  

Wouldn't it be better to make the `[[inputs.net]]` plugin configurable? The documentation states that Telegraf uses the (gopsutil) package, which under Linux reads the `/proc/net/dev` file. Keeping this as the default makes sense, but there should be an option to override it for cases like this.  

For example:
```toml
[[inputs.net]]
path_net = "/hostfs/1/net/dev"
```

To double-check if this issue is related to my host OS, I tested it on Ubuntu WSL, and the behavior is exactly the same.
