### ISSUE TITLE
Getting error "Invalid metric names or labels" on v.1.33.3

### ISSUE THREAD

**Issue by ssumsam** [influxdata/telegraf#16563]
### Relevant telegraf.conf

```toml
[agent]
interval = "10s"
round_interval = true
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
precision = "0s"
omit_hostname = true
snmp_translator = "gosmi"
debug = false
logfile = "/var/log/telegraf/telegraf.log"
metric_batch_size = 2000
metric_buffer_limit = 20000


[[outputs.http]]
alias = "prometheus_remotewrite"
data_format = "prometheusremotewrite"
url = "${PROMETHEUS_LTS}"

[outputs.http.headers]
Content-Type = "application/x-protobuf"
Content-Encoding = "snappy"
X-Prometheus-Remote-Write-Version = "0.1.0"

[[outputs.file]]
files = [
    "/tmp/metrics.out",
]
data_format = "influx"

[[inputs.gnmi]]
alias = "juniper"
addresses = [
    "xxxx:50051",
    "xxxx:50051",
]
encoding = "proto"
tagexclude = [
    "path",
]
fieldexclude = [
    "type",
]

[inputs.gnmi.aliases]
ifalias = "/interfaces/interface/"

[[inputs.gnmi.subscription]]
name = "ifstate"
origin = "openconfig-interfaces"
path = "/interfaces/interface/state"
subscription_mode = "sample"
sample_interval = "30s"
```

### Logs from Telegraf

```text
## docker logs prometheus


ts=2025-02-26T22:26:37.236Z caller=write_handler.go:240 level=warn component=web msg="Invalid metric names or labels" got="{__name__=\"ifstate_counters/out_queue/allocated_buffer_size\", datacenter=\"vad\", device_role=\"junos_qfx\", instance=\"xxx\", interface=\"et-0/0/16:1\", queue_number=\"2\", rack=\"baa\"}"
ts=2025-02-26T22:26:37.236Z caller=write_handler.go:240 level=warn component=web msg="Invalid metric names or labels" got="{__name__=\"ifstate_counters/out_queue/allocated_buffer_size\", datacenter=\"vad\", device_role=\"junos_qfx\", instance=\"xxx\", interface=\"et-0/0/21:0\", queue_number=\"4\", rack=\"baa\", team=\"NET\"}"
```

### System info

Telegraf 1.33.3

### Docker

```
volumes:
  prometheus_data: {}
  grafana-storage: {}


networks:
  default:
    name: telegraf-network

services:
  telegraf:
    build:
      context: .
      args:
        POETRY_VERSION: 1.6.1
      dockerfile: Dockerfile
    container_name: telegraf
    hostname: telegraf
    volumes:
     - ./app/mibs:/usr/share/snmp/mibs/
    environment:
      ENVIRONMENT: local
      DATACENTER: "xxx"
      PROMETHEUS_LTS: "http://prometheus:9090/api/v1/write"
      CUMULUS_RO_COMMUNITY: ${CUMULUS_RO_COMMUNITY}
      SMARTOPTICS_COMMUNITY: ${SMARTOPTICS_COMMUNITY}
   ports:
      - 9126:9126

  prometheus:
    image: prometheus:latest
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-remote-write-receiver
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus/prometheus_conf.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus

  grafana:
    image: proxy.docker.adsrvr.org/grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
    environment:
      GF_APP_MODE: development
    volumes:
      - grafana-storage:/var/lib/grafana
```

### Steps to reproduce

1. ```local-dev: ## Setup docker container for local dev
	POETRY_VERSION=${POETRY_VERSION} docker compose up -d ```
2.
3.
...

### Expected behavior

- When using Telegraf v.1.33.1, metrics are written successfully to Prometheus, using the `[[outputs.http]]` plugin.
- When using Telegraf v1.33.3, seeing `Invalid metric names or labels` errors on Prometheus.

### Actual behavior

- When using Telegraf v.1.33.1, metrics are written successfully to Prometheus, using the `[[outputs.http]]` plugin.

## docker logs prometheus

```
ts=2025-02-26T22:26:37.236Z caller=write_handler.go:240 level=warn component=web msg="Invalid metric names or labels" got="{__name__=\"ifstate_counters/out_queue/allocated_buffer_size\", datacenter=\"vad\", device_role=\"junos_qfx\", instance=\"xxx\", interface=\"et-0/0/16:1\", queue_number=\"2\", rack=\"baa\"}"
ts=2025-02-26T22:26:37.236Z caller=write_handler.go:240 level=warn component=web msg="Invalid metric names or labels" got="{__name__=\"ifstate_counters/out_queue/allocated_buffer_size\", datacenter=\"vad\", device_role=\"junos_qfx\", instance=\"xxx\", interface=\"et-0/0/21:0\", queue_number=\"4\", rack=\"baa\", team=\"NET\"}"
```
