### ISSUE TITLE
Same objects received from Telegraf are present multiple times

### ISSUE THREAD

**Issue by vridsar** [influxdata/telegraf#16561]
Hello,
I'm trying to check some http endpoint using Telegraf agent and output the data to VMware Aria Operations. Everything works fine but I have the output objets all mixed up. As you can see in the attached image, I have  configured 3 endpoints but in VMware Aria Operations, I see the same objets multiple times. Could you help me please? Thanks!

![Image](https://github.com/user-attachments/assets/ae5aba5e-b028-427b-a630-acd2675831a0)

I have configured these http_reponse input plugin :
```toml
[[inputs.exec]]
  commands = ["/bin/bash \"/etc/telegraf/telegraf.d/mandatory_tags.sh\" \"/usr/bin/telegraf\""]
  timeout = "5s"
  data_format = "influx"

[[inputs.http_response]]
  name_override = "http_service_health"
  urls = ["X"]
  method = "GET"
  follow_redirects = true
  insecure_skip_verify = true
  [inputs.http_response.tags]
    service = "applmgt"
    instance_id = "service2"

[[inputs.http_response]]
  name_override = "service_health"
  urls = ["X"]
  method = "GET"
  follow_redirects = true
  insecure_skip_verify = true
  tags = {service = "db", instance_id = "service2"}

[[inputs.http_response]]
  name_override = "health"
  urls = ["X"]
  method = "GET"
  follow_redirects = true
  insecure_skip_verify = true
  tags = {service = "mem", instance_id = "service3"} 
```

**Comment by srebhan** [comment]
@vridsar as discussed on Slack, please post the output using a

```toml
[[outputs.file]]
    files = ["/tmp/metrics.influx"]
```

and point to duplicate entries in _that file_! I'm not familiar with "VMWare Aria Operations" and it is not clear to me what I'm seeing there nor how this relates to the input plugins you show in your config. I'm also not seeing any duplicate metrics to be honest...

Please understand that we can only support you with the Telegraf side and _NOT_ the "VMware Aria Operations" side of things!
