### ISSUE TITLE
Telegraf plugin doesnot extract Kafka message header json and store into influx db

### ISSUE THREAD

**Issue by ss85705** [influxdata/telegraf#16573]
Hi Team. 

I am using telegraf to utilize kafka consumer input plugin to get the kafka payload and store into influx db.

Kafka payload is also having header with the message that is json format. I am using below config in telegraf config file

This is the header json.

```json
{
	"area": "area1",
	"unit": "unit1",
	"station": "stn1",
	"department": "dept1"
}
```

```toml
[[inputs.kafka_consumer]]
  brokers = ["broker:9092"]  # Replace with your Kafka service address
  topics = ["influx_topic1"]  # Replace with your Kafka topic
  consumer_group = "telegraf-consumer-3"
  offset = "oldest"
  sasl_username = "xxxxxx"  # Username for SASL
  sasl_password = "***********"  # Password for SASL
  sasl_mechanism = "SCRAM-SHA-256"               # SASL mechanism (e.g., PLAIN, SCRAM-SHA-256, SCRAM-SHA-512)   
  data_format = "json"  # Change to match your data format 
  # Pass Kafka message headers as tags       
  msg_headers_as_tags = ["*"]  
  kafka_version = "3.4.0" 
```
Further i am using starlark scripting to get all the kafka message (body) stored into influx as metrics fields and then header json message as tag key, but its not working for me.. 

```toml
 [[processors.starlark]]
      source = '''
    def apply(metric):    
      def parse_json(json_str):
        result = {}
        json_str = json_str.strip('{}')
        for item in json_str.split(','):
            key, value = item.split(':')
            key = key.strip().strip('"')
            value = value.strip().strip('"')
            result[key] = value
        return result

      # Debug logging: Print raw tags
      print("Raw tags:", metric.tags)      

      # Parse the JSON header
      if "unit" in metric.tags:
          header = parse_json(metric.tags["unit"])
          for key, value in header.items():
              metric.tags[key] = str(value)
       # Debug logging
      print("Parsed tags:", metric.tags)
      # Set the measurement name based on the deviceName field
      if "deviceName" in metric.fields:
          metric.name = metric.fields["deviceName"]
      elif "deviceName" in metric.tags:
          metric.name = metric.tags["deviceName"]
      
      # Convert all fields and tags to strings
      for key, value in metric.fields.items():
          metric.fields[key] = str(value)
      for key, value in metric.tags.items():
          metric.tags[key] = str(value)
      
      return metric
    '''
```
i cant see tag keys coming into influx db , however fields are storing as expected.

Can someone pleas ehelp me here .

I am using telegraf:latest docker image and influxdb v2 latest image. 

If i get a reference example , would be great.
