### ISSUE TITLE
Graphite parser ignores tags

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#16616]
### Relevant telegraf.conf

```toml
[[inputs.exec]]
  commands = [
    "echo disk.used?device=sda2&fstype=xfs&host=grw-pol-u1&mode=rw 650"
  ]
  data_format = "graphite"
```

### Logs from Telegraf

```text
> disk.used?device=sda2&fstype=xfs&host=grw-pol-u1&mode=rw,host=MacBook-Pro.local value=650 1741774106000000000
```

### System info

Telegraf 1.34.0

### Steps to reproduce

Run the given config

### Expected behavior

This is the metric I would expect:
```diff
-disk.used?device=sda2&fstype=xfs&host=grw-pol-u1&mode=rw,host=MacBook-Pro.local value=650 1741774106000000000
+disk.used,device=sda2,fstype=xfs,host=grw-pol-u1,mode=rw value=650 1741774106000000000
```

### Actual behavior

Telegraf does not detect/use the graphite tags.

### Additional info

Even when setting the template as `*.* measurement.field`, this is what should be expected:

```diff
-disk,host=MacBook-Pro.local used?device\=sda2&fstype\=xfs&host\=grw-pol-u1&mode\=rw=650 1741774452000000000
+disk,device=sda2,fstype=xfs,host=grw-pol-u1,mode=rw used=650 1741774452000000000
```
