### ISSUE TITLE
nvidia_smi  utilization_memory not correct

### ISSUE THREAD

**Issue by Qedr1** [influxdata/telegraf#16617]
### Relevant telegraf.conf

```toml
[[inputs.nvidia_smi]]
bin_path = "/usr/bin/nvidia-smi"
timeout = "5s"
fieldinclude=["utilization_gpu","memory_total","memory_used","utilization_memory"]
tagexclude=["pstate","uuid","compute_mode"]
```

### Logs from Telegraf

```text
"fields": {               
    "gpu_used_percent": 0,  
    "utilization_memory": 0,  
    "index": 0,             
    "memory_total": 11178,  
    "memory_used": 3843,    
}
```

### System info

Telegraf 1.33, Nvidia 1080Ti

### Steps to reproduce

1. Add to telegraf.conf 
[[inputs.nvidia_smi]]
bin_path = "/usr/bin/nvidia-smi"
timeout = "5s"
fieldinclude=["utilization_gpu","memory_total","memory_used","utilization_memory"]
tagexclude=["pstate","uuid","compute_mode"]

### Expected behavior

 "utilization_memory": 34.38
//  utilization_memory= memory_used/memory_total*100= 3843/11178 *100

### Actual behavior

 "utilization_memory": 0
