### ISSUE TITLE
feat(outputs.sql): Support Secrets for outputs.sql DataSourceName

### ISSUE THREAD

**Issue by LarsStegman** [influxdata/telegraf#16626]
### Use Case

I want to hide the password to connect to my SQL server

```toml
[[outputs.sql]]
  driver = "mssql"
  data_source_name = "@{k8s_secrets:conn_string_sql}"
```

### Expected behavior

Reads secret for data_source_name.

### Actual behavior

Tries to use the secret notation to connect to a database.
