### ISSUE TITLE
telegraf stuck on kafka offset which doesn't exist

### ISSUE THREAD

**Issue by Digl** [influxdata/telegraf#16633]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]
  alias = "ALIAS"
  brokers = ["BROKERLIST"]
  topics = ["TOPICNAME"]
  enable_tls = true
  tls_ca = "CRT"
  tls_cert = "CRT"
  tls_key = "KEY"
  consumer_group = "CONSUMERGROUP"
  compression_codec = 1
  data_format = "influx"
```

### Logs from Telegraf

```text
no relevant entries in the log
```

### System info

telegraf-1.34.0_linux_amd64

### Docker

A customer is using the confluent kafka library for java. 
They are using transactions to produce messages to kafka. 
Sometimes an offset is skipped during the produce process.
e.g. offset 144906143470 exists, 144906143471 does not exist, 144906143472 exists

### Steps to reproduce

- use transactions to produce messages
- consume them with telegraf

### Expected behavior

telegraf should skip the missing offset

### Actual behavior

telegraf keeps trying to read the missing offset and gets stuck at that point.
the offset lag keeps increasing until the offset for the affected partition is manually corrected.
