### ISSUE TITLE
[outputs.opentelemetry] Unsupported Type Error for Span Fields (span.name, span.kind, attributes)

### ISSUE THREAD

**Issue by bkochauri-memphis** [influxdata/telegraf#16634]
### Relevant telegraf.conf

```toml
[[outputs.opentelemetry]]
  service_address = "opentelemetry-collector.server:4317"

[[inputs.opentelemetry]]
  service_address = "0.0.0.0:4317"
```

### Logs from Telegraf

```text
[outputs.opentelemetry] field has unsupported type measurement="spans" field="span.name" type="string"
[outputs.opentelemetry] field has unsupported type measurement="spans" field="span.kind" type="string"
[outputs.opentelemetry] field has unsupported type measurement="spans" field="attributes" type="string"
```

### System info

Telegraf 1.32.1

### Steps to reproduce

1. Start Telegraf with the following configuration:
   ```toml
   [[outputs.opentelemetry]]
     service_address = "opentelemetry-collector.server:4317"

   [[inputs.opentelemetry]]
     service_address = "0.0.0.0:4317"
  ```
2. Run a Go application that sends traces via OTLP GRPC (4317).
3. See the following error messages:
```toml
[outputs.opentelemetry] field has unsupported type measurement="spans" field="span.name" type="string"
[outputs.opentelemetry] field has unsupported type measurement="spans" field="span.kind" type="string"
[outputs.opentelemetry] field has unsupported type measurement="spans" field="attributes" type="string"
```

### Expected behavior

Telegraf should correctly process span fields (span.name, span.kind, attributes) and forward traces to the OpenTelemetry Collector without type conversion issues.

### Actual behavior

Traces do not reach the OpenTelemetry Collector when sent through Telegraf. Instead, Telegraf logs unsupported type errors, and no traces appear in the OpenTelemetry system.

Logs from Telegraf:
[outputs.opentelemetry] field has unsupported type measurement="spans" field="span.name" type="string"
[outputs.opentelemetry] field has unsupported type measurement="spans" field="span.kind" type="string"
[outputs.opentelemetry] field has unsupported type measurement="spans" field="attributes" type="string"

### Additional info

When sending traces directly from the Go application to the OpenTelemetry Collector (without Telegraf), they are processed successfully without any issues.
