### ISSUE TITLE
the new telegraf disk buffer option does not set proper log messages

### ISSUE THREAD

**Issue by spkis** [influxdata/telegraf#16670]
### Relevant telegraf.conf

```toml
#buffer strategy
  buffer_strategy = "disk"
  buffer_directory = "/harvest/${TE_ID}"
```

### Logs from Telegraf

```text
2025-03-20T14:56:43Z I! Loading config: /etc/telegraf/telegraf.conf
2025-03-20T14:56:43Z W! Using disk buffer strategy for plugin outputs.influxdb_v2, this is an experimental feature
```

### System info

telegraf 1.34-alpine and latest

### Steps to reproduce

1. Setup the new disk buffer.
2. Add output to quix.
3. Execute telegraf file and notice you only get notified about it for output_influxdbv2.
...

### Expected behavior

It shows that message for all configured outputs, which support it! 

### Actual behavior

Does only say it would work for influxdbv2.
