### ISSUE TITLE
Wrong parameter for detecting the lockable memory on *BSDs

### ISSUE THREAD

**Issue by stepga** [influxdata/telegraf#16681]
### Relevant telegraf.conf

```toml
[global_tags]

[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "30s"
  flush_jitter = "2s"
  precision = ""
  debug = false
  quiet = false
  logfile = "/var/log/telegraf.log"
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  bucket = "telegraf"
  token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=="
  organization = "xxx"
  timeout = "5s"

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[inputs.diskio]]

[[inputs.mem]]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.netstat]]

[[inputs.snmp]]
 # removed input fields/tables
```

### Logs from Telegraf

```text
2025-03-24T04:08:49Z I! Found 1 secrets...
2025-03-24T04:08:49Z W! Insufficient lockable memory 8kb when 12kb is required. Please increase the limit for Telegraf in your Operating System!
```

### System info

Telegraf 1.29.5, OpenBSD 7.5

### Steps to reproduce

1. start telegraf on openbsd (should also affect freebsd/netbsd/dragonfly)
2. look into configured telegraf.log
3. see warning about insufficient lockable memory

### Expected behavior

No warning about insufficient lockable memory appears, if the operating system has configured enough lockable memory.

### Actual behavior

Independent of the operating system's memory settings, a warning with always the same amount of lockable memory (in my case 8kb) appears.

### Additional info

The bug was introduced in https://github.com/influxdata/telegraf/commit/69cc03a455a6502e4857fd116ba4698d36daffe9.

The problem is the hardcoded `getrlimit(2)` parameter `rLimitMemlock` in https://github.com/influxdata/telegraf/commit/69cc03a455a6502e4857fd116ba4698d36daffe9#diff-89111aece88d8d0f7f4ed071ee44b947acc0339b8278a996b2ade633b8c2d0b8R13-R23:

```
func getLockedMemoryLimit() uint64 {
        // From https://elixir.bootlin.com/linux/latest/source/include/uapi/asm-generic/resource.h#L35
        const rLimitMemlock = 8   // <- FIXME

        var limit syscall.Rlimit
        if err := syscall.Getrlimit(rLimitMemlock, &limit); err != nil {
                log.Printf("E! Cannot get limit for locked memory: %v", err)
                return 0
        }
        //nolint:unconvert // required for e.g. FreeBSD that has the field as int64
        return uint64(limit.Max)
}
```

The respective link to the Linux resource.h attests the value's correctness, at least for Linux (https://elixir.bootlin.com/linux/v6.13.7/source/include/uapi/asm-generic/resource.h#L35):
```
#ifndef [RLIMIT_MEMLOCK](https://elixir.bootlin.com/linux/v6.13.7/C/ident/RLIMIT_MEMLOCK)
# define [RLIMIT_MEMLOCK](https://elixir.bootlin.com/linux/v6.13.7/C/ident/RLIMIT_MEMLOCK)              8       /* max locked-in-memory address space */
#endif
```

Sadly, on OpenBSD/FreeBSD/NetBSD/DragonFly (all BSDs?), the relevant constant is different (https://cgit.freebsd.org/src/tree/sys/sys/resource.h#n107):
```
#define RLIMIT_MEMLOCK  6               /* locked-in-memory address space */
#define RLIMIT_NPROC    7               /* number of processes */
#define RLIMIT_NOFILE   8               /* number of open files */
```

This explains the telegraf warning always complaining about the same amount of lockable memory (8192), seemingly unaffected of the system's actual memory settings (via `login.conf`, see https://man.openbsd.org/login.conf.5):
On *BSD, the code does not get the maximum locked-in-memory address space, but rather always the maximum **number of open files**.
