### ISSUE TITLE
Enable / Disable plugin instances

### ISSUE THREAD

**Issue by neelayu** [influxdata/telegraf#16704]
### Use Case

In one of our deployments, we plan to deploy multiple instances of telegraf and all of them fetching the config from an HTTP endpoint. Each running instance is only supposed to "activate" certain set of plugins for which it is configured. Although there is a way to achieve it by some tedious configurations, I think a more elegant solution would be to have a method similar to what k8s does using its Labels and Selector logic. 

There have been requests for this feature dating back to 2016!
https://github.com/influxdata/telegraf/issues/9304
https://github.com/influxdata/telegraf/issues/1317
https://github.com/influxdata/telegraf/issues/10543

### Expected behavior

Telegraf runs with only "enabled" plugins

### Actual behavior

No such provision directly.

### Additional info

Few of the solutions offered previously-
Comment the plugin to "disable" it. This works, but for a centralized config this approach is not feasible.
Rename the file to ignore. Since Telegraf only reads .conf files, we can effectively disable set of plugins if we rename the file to something like .conf.ignore. This approach is complex to manage. Good for debugging.

The proposed solutions using selectors and labels makes it extensible. To ensure backward compatibility, we need to define certain rules.

# Compatibility Matrix: Telegraf Plugin Selector System

| **Telegraf Run State**            | **Selector Present** | **Behavior**                                   |
|-----------------------------------|----------------------|-----------------------------------------------|
| **Running with `--label`**        | **Selector Present**  | Plugin is **selected** if the selector matches the label. Else if selector doesn't match, plugin is **not selected**. |
|                                   | **Selector Not Present** | Plugin is selected (backward compatibility). |
| **Running without `--label`**     | **Selector Present**  | Plugin is selected (no label to compare against). |
|                                   | **Selector Not Present** | Plugin is selected (current behavior).        |

***In essence, if we want to disable the plugin, all we need to do is run telegraf with a label and without a matching selector. It will act as a negative selector.***

For users who wish to take full advantage of this feature, will eventually provide matching selectors for their running instances of telegraf.

As an example, we have the following

```
telegraf --config-directory selectors/ --label="app:frontend" --label="drop:news-1" --watch-config=notify --print-plugin-config-source=true
```
Lets say we have
```
selectors/
  one.conf
  two.conf
```

one.conf
```toml
[[outputs.http]]
    selector = {app = "frontend"}

[[inputs.mem]]
    selector = {app = "frontend2"}

[[inputs.cpu]]
    selector = {app = "backend"}
```

two.conf
```toml
[[inputs.disk]]
    selector = {app = "frontend", drop = "news-2"}

[[inputs.netstat]]
    [inputs.netstat.selector]
        app = "frontend"
        drop = "news-1"

[[inputs.powerdns]]
    selector = {app = "frontend"}
```

The following would be selected
```
outputs.http
inputs.netstat
inputs.powerdns
```

The following would be dropped
```
inputs.mem
inputs.cpu
inputs.disk
```

Suggestions are welcome to improve this. I have created a PR for the same #16705

**Comment by srebhan** [comment]
@neelayu hmmm why wouldn't a slice be enough something like

```toml
[[outputs.http]]
    selectors = ["frontend", "backend"]

[[inputs.mem]]
    selectors =["backend"]

[[inputs.cpu]]
    selectors =["backend"]

[[inputs.modbus]]
    selectors =["factory"]
```

be enough? This way the checking is pretty easy I think.

My biggest concern is the complexity this might grow into. What if you specify

```toml
telegraf --label frontend --label factory
```

Does it mean `"frontend" and "factory"` or does it mean `"frontend" or "factory"`?

**Comment by neelayu** [comment]
I see the confusion-

The `--label` flag is essentially what k8s has in `metadata.labels`. It is a way of attaching objects. In a way, it's just a list.

The `selectors` on the other hand are similar to k8s `matchLabels`. ie all selectors should match labels (Selectors are supposed to be subset of labels)

I have kept it similar to k8s since it provides a way to expand our capabilities in the future to incorporate selections based on `matchExpressions` and operator.

Let me know your thoughts. As @Hipska also mentions, wildcardmatching is also an option. But this gives us a strict matching.

**Comment by srebhan** [comment]
@neelayu I'm not familiar with k8s selection mechanism but I don't want to make things more complicated in Telegraf as they need to be. Using maps has the drawback that, if you use tables for declarations, the table must be at the end of the plugin declaration. Furthermore, we can still have label pairs by doing

```toml
[[inputs.foo]]
  selectors = ["apps.backend", "source.backend", ...]
```

or

```toml
[[inputs.foo]]
  selectors = ["apps=backend", "source=backend", ...]
```

If you then use a filter expression and specify the dot (`.`) or equal-sign (`=`) as separator you can easily do expressions like `*.backend` or `apps.*`.
