### ISSUE TITLE
Telegraf process does not release the log files after writing

### ISSUE THREAD

**Issue by chancham** [influxdata/telegraf#16750]
### Relevant telegraf.conf

```toml
Hi,

I am testing telegraf on an EC2 instance. The process is keeping too many log file descriptors open. Sometimes it hits the open files ulimit for the user (65535). 
Shouldn't the process release file descriptors to log file after writing?

The version I am testing is 1.24.2. Is this a known bug thats fixed in new version?
Do you have a work around for this version?


These are the only log specific config I have:


  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  logfile = "/var/log/telegraf/telegraf.log"
```

### Logs from Telegraf

```text
From "lsof -p <telegraf-pid>"


telegraf 15580 telegraf  444r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  445r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  446r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  447r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  449r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  450r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log
telegraf 15580 telegraf  451r      REG              259,2   5291575  8885586 /var/log/telegraf/telegraf.log


At normal times:

$lsof -p 15580   | grep telegraf.log | wc -l
419


When it hits open files limit:


$lsof -p 2650 | wc -l
65539
$lsof -p 2650   | grep telegraf.log | wc -l
65502
```

### System info

Telegraf 1.24.2, Amazon linux 2 OS

### Steps to reproduce

Run "lsof" on the telegraf process, and check for how many instances of log files is open at a time. 

### Expected behavior

I expected a lower number as the log streams are closed after each execution or hit a timeout.

### Actual behavior

High number of file descriptors open accessing telegraf.log.
