### ISSUE TITLE
[inputs.proctstat] allow to set "all" in supervisor_units

### ISSUE THREAD

**Issue by matiasba** [influxdata/telegraf#16774]
### Use Case

Currently there is not any way to monitor all supervisor procs. It would be very useful to allow the key word "all" or some sort of wildcard to monitor all services. 
Looking at https://github.com/influxdata/telegraf/blob/8c5114b0673b5c52b6281ed0c276e1a7edc2171a/plugins/inputs/procstat/service_finders.go#L106
It seems that it just runs a simple "supervisorctl status <unit>" then filters by name. 
The command "supervisorctl status all" returns all units, so maybe we could handle "all" as an especial case that doesn't filter by name and instead returns all units.

Just to clarify, setting this config does not work:
```
[[inputs.procstat]]
  supervisor_units = ["all"]
```

### Expected behavior

procstat_lookup_running{pid_finder="pgrep",result="success",supervisor_unit="<discovered_unit_1>"} 1
procstat_lookup_running{pid_finder="pgrep",result="success",supervisor_unit="<discovered_unit_2>"} 0
procstat_lookup_running{pid_finder="pgrep",result="success",supervisor_unit="<discovered_unit_3>"} 1

### Actual behavior

procstat_lookup_running{pid_finder="pgrep",result="success",supervisor_unit="all"} 0

**Comment by srebhan** [comment]
Please try the new-style `filter`s

```toml
[[inputs.procstat.filter]]
  [[inputs.procstat.filter]]
    supervisor_units = ["all"]
```

**Comment by matiasba** [comment]
Is that new filter available in the latest version? I'm trying with 1.34.3-1 on ubuntu and it fails to load the config.

**Comment by srebhan** [comment]
Yeah it is available but my config was wrong, here is the corrected one: :-/
```toml
[[inputs.procstat]]
  [[inputs.procstat.filter]]
    supervisor_units = ["all"]
```
