### ISSUE TITLE
Telegraf service to read data from kepware

### ISSUE THREAD

**Issue by Saddy96** [influxdata/telegraf#16776]
### Relevant telegraf.conf

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "60s"
  ## Rounds collection interval to "interval"
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 500

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 5000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system. Old value 10ms
  collection_jitter = "5s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "5s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "s"), "ms", "s".
  precision = ""

  ## Log at debug level.
  # debug = false
  ## Log only error level messages.
  quiet = false

  debug = true
  #logtarget = "file"
  logfile = "C:\\Influx_Service\\Telegraf_Logs\\OPC_Logs\\telegraf_opc.logs"
  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  logfile_rotation_interval = "1h"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  logfile_rotation_max_archives = 24

  ## Pick a timezone to use when logging or type "local" for local time.
  ## Example: America/Chicago
  # log_with_timezone = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = true
[[inputs.opcua]]
  ## Metric name
  name = "opcua"
  #
  ## OPC UA Endpoint URL
  endpoint = "opc.tcp://12.25.106.262:49320"
  #
  ## Maximum time allowed to establish a connect to the endpoint.
  connect_timeout = "20s"
  #
  ## Maximum time allowed for a request over the estabilished connection.
  request_timeout = "10s"
  #
  ## Security policy, one of "None", "Basic128Rsa15", "Basic256",
  ## "Basic256Sha256", or "auto"
  security_policy = "auto"
  #
  ## Security mode, one of "None", "Sign", "SignAndEncrypt", or "auto"
  security_mode = "auto"
  #
  ## Path to cert.pem. Required when security mode or policy isn"t "None".
  ## If cert path is not supplied, self-signed cert and key will be generated.
  certificate = "C:/Program Files/InfluxData/telegraf/certs/opcuacert.pem"
  #
  ## Path to private key.pem. Required when security mode or policy isn"t "None".
  ## If key path is not supplied, self-signed cert and key will be generated.
  ## private_key = "/etc/telegraf/key.pem"
  private_key = "C:/Program Files/InfluxData/telegraf/certs/opcuakey.pem"
  #
  ## Authentication Method, one of "Certificate", "UserName", or "Anonymous".  To
  ## authenticate using a specific ID, select "Certificate" or "UserName"
  auth_method = "UserName"
  #
  ## Username. Required for auth_method = "UserName"
  username = "OPC_user"
  #
  ## Password. Required for auth_method = "UserName"
  password = "Password"
  #
  ## Option to select the metric timestamp to use. Valid options are:
  ##     "gather" -- uses the time of receiving the data in telegraf
  ##     "server" -- uses the timestamp provided by the server
  ##     "source" -- uses the timestamp provided by the source
  timestamp = "source"
  #
  ## Node ID configuration
  ## name              - field name to use in the output
  ## namespace         - OPC UA namespace of the node (integer value 0 thru 3)
  ## identifier_type   - OPC UA ID type (s=string, i=numeric, g=guid, b=opaque)
  ## identifier        - OPC UA ID (tag as shown in opcua browser)
  ## tags              - extra tags to be added to the output metric (optional)
  ## Example:
  ## {name="ProductUri", namespace="0", identifier_type="i", identifier="2262", tags=[["tag1","value1"],["tag2","value2]]}
 
  #
  ## Node Group
  ## Sets defaults for OPC UA namespace and ID type so they aren"t required in
  ## every node.  A group can also have a metric name that overrides the main
  ## plugin metric name.
  ##
  ## Multiple node groups are allowed
  #[[inputs.opcua.group]]
  ## Group Metric name. Overrides the top level name.  If unset, the
  ## top level name is used.
  # name =
  #
  ## Group default namespace. If a node in the group doesn"t set its
  ## namespace, this is used.
  # namespace =
  #
  ## Group default identifier type. If a node in the group doesn"t set its
  ## namespace, this is used.
  # identifier_type =
  #
  ## Node ID Configuration.  Array of nodes with the same settings as above.
  # nodes = [
  #  {name="", namespace="", identifier_type="", identifier=""},
  #  {name="", namespace="", identifier_type="", identifier=""},
  #]
 nodes = [
  {name = "Tag_K1_OXYGEN", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.K1_Oxygen"},
  #{name = "Tag_K1_LVF8_SPEED", namespace = "2", identifier_type = "s", identifier = "ABE.K1.LVF8_SPEED"},
  {name = "Tag_K1_LVF6_SPEED", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LVF6_SPEED"},
  {name = "Tag_K1_LVF5_SPEED", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LVF5_SPEED"},
  {name = "Tag_K1_LVF4_SPEED", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LVF4_SPEED"},
  {name = "Tag_K1_LVF3_SPEED", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LVF3_SPEED"},
  {name = "Tag_K1_LVF2_SPEED", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LVF2_SPEED"},
  {name = "Tag_K1_LVF1_SPEED", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LVF1_SPEED"},
  #{name = "Tag_K1_LB4_RATE", namespace = "2", identifier_type = "s", identifier = "ABE.K1.LB4_RATE"},
  #{name = "Tag_K1_LB19_TOTAL", namespace = "2", identifier_type = "s", identifier = "ABE.K1.LB19_TOTAL"},
  {name = "Tag_K1_LB19_RATE", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LB19_RATE"},
  #{name = "Tag_K1_LB16_TOTAL", namespace = "2", identifier_type = "s", identifier = "ABE.K1.LB16_TOTAL"},
  {name = "Tag_K1_LB16_RATE", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.LB16_RATE"},
  {name = "Tag_WQY1040_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WQY1040_Day_Totalizer"},
  {name = "Tag_WQY1040_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WQY1040_Yesterdays_Totalizer"},
  {name = "Tag_WQY1040_Lifetime_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WQY1040_Lifetime_Totalizer"},
  {name = "Tag_WT1040_L_bin", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WT1040_L"},
  {name = "Tag_WT1040_H_bin", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WT1040_H"},
  {name = "Tag_WT1040_HH_bin", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WT1040_HH"},
  #{name = "Tag_WQY1072_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.K1.Group1.WQY1072_Day_Totalizer"},
  #{name = "Tag_WQY1072_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.K1.WQY1072_Yesterday_Totalizer"},
  #{name = "Tag_WQY1072_Lifetime_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.K1.WQY1072_Lifetime_Totalizer"},
  {name = "Tag_WQY1081_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WQY1081_Day_Totalizer"},
  {name = "Tag_WQY1081_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WQY1081_Yesterdays_Totalizer"},
  {name = "Tag_WQY1081_Lifetime_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WQY1081_Lifetime_Totalizer"},
  {name = "Tag_WT1081_L_bin", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WT1081_L"},
  {name = "Tag_WT1081_H_bin", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WT1081_H"},
  {name = "Tag_WT1081_HH_bin", namespace = "2", identifier_type = "s", identifier = "AB.K1.Group1.WT1081_HH"},
  #{name = "Tag_WT1072_L_bin", namespace = "2", identifier_type = "s", identifier = "ABE.K1.WT1072_L"},
  #{name = "Tag_WT1072_H_bin", namespace = "2", identifier_type = "s", identifier = "ABE.K1.WT1072_H"},
  #{name = "Tag_WT1072_HH_bin", namespace = "2", identifier_type = "s", identifier = "ABE.K1.WT1072_HH"},

  #{name = "Tag_K1_LB4_TPH", namespace = "2", identifier_type = "s", identifier = "ABE.K1.LB1_TPH"},
  #{name = "Tag_K1_LB15_TPH", namespace = "2", identifier_type = "s", identifier = "ABE.K1.LB15_TPH"},


  {name = "Tag_K3_FI_K3_FEED", namespace = "2", identifier_type = "s", identifier = "AB.K3.Global.FI_K3_FEED"}, 
  {name = "Tag_K3_FI_BP3_GAS", namespace = "2", identifier_type = "s", identifier = "AB.K3.Global.FI_BP3_GAS"},


  #{name = "Tag_FT1_GEAR_COUNT", namespace = "2", identifier_type = "s", identifier = "AB.PLC1.Global.FT1.GEAR_COUNT"},


  {name = "Tag_PRIMARY_ROCK_BOX_LEVEL", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Global.Rock_Box_Level"},
  {name = "Tag_QB_1_DAILY_TOTAL", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Global.QB_1_Daily_Total"},
  {name = "Tag_QB_1_TOTAL", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Global.QB_1_Total"},
  {name = "Tag_Primary_Q_C1_I", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Global.Q_C1.I"},
  {name = "Tag_Primary_Q_B1_I", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Global.QB_1.I"},
  {name = "Tag_PRIMARY_MAG_SCALE_KGS", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Prgm_MainProgram.MAG.SCALE_KGS"},
  {name = "Tag_PRIMARY_VIB_CALCULATED_SPEED", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Prgm_MainProgram.VIB.CALCULATED_SPEED"},
  {name = "Tag_PRIMARY_ROCKBOXAVG_00", namespace = "2", identifier_type = "s", identifier = "AB.Primary.Prgm_MainProgram.RockBoxAvg_x.RockBoxAvg_00"},


  {name = "Tag_PS1_RD_BC2925_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.BC2925_WeightScale"},
  {name = "Tag_PS1_RD_BC2926_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.BC2926_WeightScale"},
  {name = "Tag_PS1_RD_BC2902_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.BC2902_DailyOffTime"},
  {name = "Tag_PS1_RD_TE2912_1_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.TE2912_1_INPUT"},
  {name = "Tag_PS1_RD_TE2912_3_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.TE2912_3_INPUT"},
  {name = "Tag_PS1_RD_TE2914_1_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.TE2914_1_INPUT"},
  {name = "Tag_PS1_RD_TE2914_2_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.TE2914_2_INPUT"},
  {name = "Tag_PS1_RD_VFD2901_calc", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.VFD2901_DailyRunTime"},
  {name = "Tag_PS1_RD_VFD2915_calc", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.VFD2915_DailyRunTime"},
  {name = "Tag_PS1_RD_WIT2902_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2902_TPH_REAL"},
  {name = "Tag_PS1_RD_WIT2902_PREV_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2902_PrevDailyTotal"},
  {name = "Tag_PS1_RD_WIT2902_TOTAL_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2902_Total"},
  {name = "Tag_PS1_RD_WIT2925_PREV_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2925_PrevDailyTotal"},
  {name = "Tag_PS1_RD_WIT2925_TOTAL_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2925_Total"},
  {name = "Tag_PS1_RD_WIT2926_PREV_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2926_PrevDailyTotal"},
  {name = "Tag_PS1_RD_WIT2926_TOTAL_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2926_Total"},
  {name = "Tag_PS1_RD_WIT2961_PREV_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2961_PrevDailyTotal"},
  {name = "Tag_PS1_RD_WIT2961_TOTAL_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2961_Total"},
  {name = "Tag_PS1_RD_WIT2961_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.WIT2961_TPH"},
  {name = "Tag_PS1_RD_LT2912_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.LT2912_INPUT"},
  {name = "Tag_PS1_RD_BE2918_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.BE2918.AMPS"},
  {name = "Tag_PS1_RD_CR2950_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.CR2950.AMPS"},
  {name = "Tag_PS1_RD_PT2931_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.PT2931.INPUT"},
  {name = "Tag_PS1_RD_TE2931_2_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.TE2931_2.INPUT"},
  {name = "Tag_PS1_RD_TE2931_1_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.TE2931_2.INPUT"},
  {name = "Tag_PS1_RD_VFD2901_entry", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.VFD2901.HMI_POS_CMD"},
  {name = "Tag_PS1_RD_DA2905_ana", namespace = "2", identifier_type = "s", identifier = "AB.PSP.Global.Z2905.HMI_POS_REF"},


  {name = "Tag_LLI_RD_BIN_1_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_1_LEVEL"},
  {name = "Tag_LLI_RD_BIN_1_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_1_TONNES"},
  {name = "Tag_LLI_RD_BIN_11_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_11_LEVEL"},
  {name = "Tag_LLI_RD_BIN_11_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_11_TONNES"},
  {name = "Tag_LLI_RD_BIN_12_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_12_LEVEL"},
  {name = "Tag_LLI_RD_BIN_12_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_12_TONNES"},
  {name = "Tag_LLI_RD_BIN_2_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_2_LEVEL"},
  {name = "Tag_LLI_RD_BIN_2_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_2_TONNES"},
  {name = "Tag_LLI_RD_BIN_3_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_3_LEVEL"},
  {name = "Tag_LLI_RD_BIN_3_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_3_TONNES"},
  {name = "Tag_LLI_RD_BIN_4_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_4_LEVEL"},
  {name = "Tag_LLI_RD_BIN_4_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_4_TONNES"},
  {name = "Tag_LLI_RD_BIN_5_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_5_LEVEL"},
  {name = "Tag_LLI_RD_BIN_5_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_5_TONNES"},
  {name = "Tag_LLI_RD_BIN_6_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_6_LEVEL"},
  {name = "Tag_LLI_RD_BIN_6_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_6_TONNES"},
  {name = "Tag_LLI_RD_BIN_7_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_7_LEVEL"},
  {name = "Tag_LLI_RD_BIN_7_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_7_TONNES"},
  {name = "Tag_LLI_RD_BIN_8_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_8_LEVEL"},
  {name = "Tag_LLI_RD_BIN_8_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_8_TONNES"},
  {name = "Tag_LLI_RD_BIN_9_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_9_LEVEL"},
  {name = "Tag_LLI_RD_BIN_9_TONNES_ana", namespace = "2", identifier_type = "s", identifier = "ABE.LimeHandling.BIN_9_TONNES"},


  #{name = "Tag_PL1_RD_BIN_1_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.RaymondMill.BIN_1_LEVEL"},
  #{name = "Tag_PL1_RD_BIN_2_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.RaymondMill.BIN_2_LEVEL"},
  #{name = "Tag_PL1_RD_BIN_3_LEVEL_ana", namespace = "2", identifier_type = "s", identifier = "ABE.RaymondMill.BIN_3_LEVEL"},
  

  {name = "Tag_K1_B1_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.B1_LEVEL"},
  {name = "Tag_K1_B2_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.B2_LEVEL"},
  {name = "Tag_K1_B3_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.B3_LEVEL"},
  {name = "Tag_K1_B4_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.B4_LEVEL"},
  {name = "Tag_STONE_CB4_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB4_AMPS"},
  {name = "Tag_STONE_CB1_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB1_AMPS"},
  {name = "Tag_STONE_CR1_WEST_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CR1_WEST_AMPS"},
  {name = "Tag_STONE_CR1_EAST_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CR1_EAST_AMPS"},
  {name = "Tag_STONE_CR2_A_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CR2_A_AMPS"},
  {name = "Tag_STONE_CR2_WEST_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CR2_WEST_AMPS"},
  {name = "Tag_STONE_CR2_EAST_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CR2_EAST_AMPS"},
  {name = "Tag_STONE_DC1_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.DC1_AMPS"},
  {name = "Tag_STONE_LB1_TOTAL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.LB1_TOTAL"},
  {name = "Tag_STONE_LB1_RATE", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.LB1_RATE"},
  {name = "Tag_STONE_LB1_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.LB1_AMPS"},
  {name = "Tag_STONE_QB2", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.QB2"},
  {name = "Tag_STONE_QB2_RATE", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.QB2_RATE"},
  {name = "Tag_STONE_QB2_AMPS", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.QB2_AMPS"},
  {name = "Tag_STONE_QBF-3_SPEED", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.QBF-3_SPEED"},
  {name = "Tag_STONE_QBF-2_SPEED", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.QBF-2_SPEED"},
  {name = "Tag_SILO1_EAST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S1_EAST_LEVEL"},
  {name = "Tag_SILO1_WEST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S1_WEST_LEVEL"},
  {name = "Tag_SILO2_EAST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S2_EAST_LEVEL"},
  {name = "Tag_SILO2_WEST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S2_WEST_LEVEL"},
  {name = "Tag_SILO3_EAST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S3_EAST_LEVEL"},
  {name = "Tag_SILO3_WEST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S3_WEST_LEVEL"},
  {name = "Tag_SILO4_EAST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S4_EAST_LEVEL"},
  {name = "Tag_SILO4_WEST_LEVEL", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.S4_WEST_LEVEL"},
  #{name = "Tag_STONE_F_SPEED", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.F_SPEED"},
  {name = "Tag_WQYCB1_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB1_DAY_TOTALIZER"},
  {name = "Tag_WQYCB1_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB1_YESTERDAY_TOTALIZER"},
  {name = "Tag_WQYCB1_Lifetime_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB1_LIFETIME_TOTALIZER"},
  {name = "Tag_CB1WT_L_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB1WT_L"},
  {name = "Tag_CB1WT_H_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB1WT_H"},
  {name = "Tag_CB1WT_HH_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB1WT_HH"},
  {name = "Tag_WQYCB4_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB4_DAY_TOTALIZER"},
  {name = "Tag_WQYCB4_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB4_YESTERDAY_TOTALIZER"},
  {name = "Tag_WQYCB4_Lifetime_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB4_LIFETIME_TOTALIZER"},
  {name = "Tag_CB4WT_L_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB4WT_L"},
  {name = "Tag_CB4WT_H_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB4WT_H"},
  {name = "Tag_CB4WT_HH_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB4WT_HH"},
  {name = "Tag_WQYCB14_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB14_DAY_TOTALIZER"},
  {name = "Tag_WQYCB14_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB14_YESTERDAY_TOTALIZER"},
  {name = "Tag_WQYCB14_Lifetime_Totalizer_v2", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB14_LIFETIME_TOTALIZER"},
  {name = "Tag_STONE_WQYCB14_Lifetlime_Totalizer", namespace = "2", identifier_type = "s", identifier = "ABE.STONE.WQYCB14_LIFETIME_TOTALIZER"},
  {name = "Tag_CB14WT_L_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB14WT_L"},
  {name = "Tag_CB14WT_H_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB14WT_H"},
  {name = "Tag_CB14WT_HH_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB14WT_HH"},
  {name = "Tag_WQYCB15_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB15_DAY_TOTALIZER"},
  {name = "Tag_WQYCB15_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB15_YESTERDAY_TOTALIZER"},
  {name = "Tag_WQYCB15_Lifetime_Totalizer_v2", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB15_Lifetime_Totalizer"},
  {name = "Tag_STONE_WQYCB15_Lifetlime_Totalizer", namespace = "2", identifier_type = "s", identifier = "ABE.STONE.WQYCB15_LIFETIME_TOTALIZER"},
  {name = "Tag_CB15WT_L_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB15WT_L"},
  {name = "Tag_CB15WT_H_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB15WT_H"},
  {name = "Tag_CB15WT_HH_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB15WT_HH"},
  {name = "Tag_WQYCB44_Day_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB44_DAY_TOTALIZER"},
  {name = "Tag_WQYCB44_Yesterday_Totalizer_ana", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB44_YESTERDAY_TOTALIZER"},
  {name = "Tag_WQYCB44_Lifetime_Totalizer_v2", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB44_LIFETIME_TOTALIZER"},
  {name = "Tag_STONE_WQYCB44_Lifetime_Totalizer", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.WQYCB44_LIFETIME_TOTALIZER"},
  {name = "Tag_CB44WT_L_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB44WT_L"},
  {name = "Tag_CB44WT_H_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB44WT_H"},
  {name = "Tag_CB44WT_HH_bin", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB44WT_HH"},
  {name = "Tag_STONE_CB1_TPH", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB1_TPH"},
  {name = "Tag_STONE_CB4_TPH", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB4_TPH"},
  {name = "Tag_STONE_CB14_TPH", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB14_TPH"},
  {name = "Tag_STONE_CB15_TPH", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB15_TPH"},
  {name = "Tag_STONE_CB44_TPH", namespace = "2", identifier_type = "s", identifier = "ABE.Stone.CB44_TPH"}
  ]


  fieldexclude = ["Quality", "Timestamp", "id"]
  tagexclude = ["id"]
  ## Enable workarounds required by some devices to work correctly
  # [inputs.opcua.workarounds]
    ## Set additional valid status codes, StatusOK (0x0) is always considered valid
    # additional_valid_status_codes = ["0xC0"]
    [[processors.converter]]
      [processors.converter.fields]
        float = ["*_bin"]

[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.

  urls = ["http://localhost:8086"]
  ## Token for authentication.
  token = "************************************************8"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "opc_data"

  ## Destination bucket to write into.
  bucket = "opc_data_bucket"
  

# Retrieve data from OPCUA devices
```

### Logs from Telegraf

```text
e! [inputs.opc ua] error in plugin: registernodes read failed: the operation timed out. status bad timeout (0x800a0000)
```

### System info

InfluxDB v2.7.6, Telegraf 1.32.0 (git: HEAD@dcfadf8b)

### Steps to reproduce

1. Use this config 
2. and then run the telegraf service using this config
3.After couple of days it stops and starts giving an issue
...

### Expected behavior

The data get logged to influx bucket automatically and it should not stop at any point of time.

### Actual behavior

I have a telegraf agent that pulls data from opc there are almost 180 tags that i am using inside the agent, and all of the tags are being added to the single node. i can see all the tags are having status as good in Kepware. the agent pulls the data for some days and then stops saying source id not available, I can see the status of tags on Kepware still having as good. Not sure why the service stops all of a sudden. I have been facing this from many months.

It works after restarting my PC one or two time. I can’t keep on restarting my machine every two days. Need a solution to resolve this.
