### ISSUE TITLE
fritzbox input not functional

### ISSUE THREAD

**Issue by overlinden** [influxdata/telegraf#16813]
### Relevant telegraf.conf

```toml
# Gather fritzbox status
[[inputs.fritzbox]]
  ## URLs of the devices to query including login credentials  
  urls = [ "http://admin:$FRITZBOX_PASSWOTRD@fritz.box:49000/" ]

  ## The information to collect (see README for further details).
  collect = [
  #   "device",
    "wan",
  #   "ppp",
  #   "dsl",
    "wlan",
    "hosts"
  ]

  ## The http timeout to use.
  # timeout = "10s"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  # tls_key_pwd = "secret"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false
```

### Logs from Telegraf

```text
2025-04-17T06:33:21Z I! Loading config: http://influxdb:8086/api/v2/telegrafs/xxxxxxxxxxx

2025-04-17T06:33:34Z E! loading config file http://influxdb:8086/api/v2/telegrafs/xxxxxxxxxxx failed: error parsing fritzbox, undefined but requested input: fritzbox
```

### System info

Telegraf version 1.34.2 on docker 28.0.4 configured with docker compose 

### Docker

`  telegraf-fritzbox:
    image: "telegraf:latest"
    container_name: "telegraf-fritzbox"
    restart: "unless-stopped"
    command: 
      - "telegraf"
      - "--config"
      - "http://influxdb:8086/api/v2/telegrafs/xxxxxxxxxx"
    environment:
      - "INFLUX_TOKEN=yyyyyyyyyyyy"
      - "FRITZBOX_PASSWORD=zzzzzzzzzzz"
    depends_on:
      - "influxdb"`

### Steps to reproduce

Start telegraf with the config file above using the fritzbox input node and any output node.

### Expected behavior

The fritzbox input node should be known and functional

### Actual behavior

The configuration of the fritzbox input node seems to be unknown. The configuration section could not be processed. See log messages above.
