### ISSUE TITLE
input.redis are not fully compatable with prometheusremotewrite

### ISSUE THREAD

**Issue by jryberg** [influxdata/telegraf#16814]
### Relevant telegraf.conf

```toml
[[outputs.http]]
  url = "https://.../write"
  insecure_skip_verify = false
  timeout = "30s"
  data_format = "prometheusremotewrite"

[[inputs.redis]]
  servers = ["tcp://redis:6379"]
```

### Logs from Telegraf

```text
2025-04-17T13:25:00Z E! [serializers.prometheusremotewrite::http] some series were dropped, 1280 series left to send; last recorded error: failed to parse "redis_rdb_last_bgsave_status": bad sample value "ok"
2025-04-17T13:26:00Z E! [serializers.prometheusremotewrite::http] some series were dropped, 1280 series left to send; last recorded error: failed to parse "redis_master_failover_state": bad sample value "no-failover"
```

### System info

Telegraf 1.34.2, Debian Bookworm, Redis 7.4.2

### Steps to reproduce

Collect Redis logs and send them to http output for prometheusremotewrite

### Expected behavior

No warnings

### Actual behavior

A lot of warnings
