### ISSUE TITLE
Quix output plugin fails with new Quix Cloud product

### ISSUE THREAD

**Issue by tomas-quix** [influxdata/telegraf#16856]
### Relevant telegraf.conf

```toml
# Global Agent Configuration
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]
  ## Collect memory usage metrics

[[inputs.disk]]
  ## Collect disk usage metrics
  ignore_fs = ["tmpfs", "devtmpfs"]

[[outputs.quix]]
  workspace = "${Quix__Workspace__Id}"
  token = "${Quix__Sdk__Token}"
  url = "${Quix__Portal__Api}"
  topic = "${output}"
  data_format = "json"
```

### Logs from Telegraf

```text
403
```

### System info

Telegraf in Quix

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

Sends data to Quix broker

### Actual behavior

It fails on start
