### ISSUE TITLE
inputs.modbus plugin supports custom maxBatchSize

### ISSUE THREAD

**Issue by zqm6133** [influxdata/telegraf#16873]
### Use Case

Hello, I found that while using the inputs.modbus plugin, the maximum number of single requests for coils and discrete is 2000, and the maximum number of single requests for holding registers and input registers is 125. However, the device does not support this. I would like to customize the maximum read limit. How can I set it? Can you help me develop it if it's not supported? Thank you

2025-04-24T08:06:51Z I! [inputs.modbus::inputs@modbus@3OSIS9jSTq] Got 5 request(s) touching 501 holding registers for 498 fields (slave 1) on device "3OSIS9jSTq"
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #1: @0 with length 125
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #2: @125 with length 125
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #3: @250 with length 125
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #4: @375 with length 124
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #5: @499 with length 2
2025-04-24T08:06:51Z I! [inputs.modbus::inputs@modbus@3OSIS9jSTq] Got 5 request(s) touching 501 inputs registers for 498 fields (slave 1) on device "3OSIS9jSTq"
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #1: @0 with length 125
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #2: @125 with length 125
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #3: @250 with length 125
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #4: @375 with length 124
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #5: @499 with length 2
2025-04-24T08:06:51Z I! [inputs.modbus::inputs@modbus@3OSIS9jSTq] Got 3 request(s) touching 5000 discrete registers for 5000 fields (slave 1) on device "3OSIS9jSTq"
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #1: @0 with length 2000
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #2: @2000 with length 2000
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #3: @4000 with length 1000
2025-04-24T08:06:51Z I! [inputs.modbus::inputs@modbus@3OSIS9jSTq] Got 3 request(s) touching 5000 coil registers for 5000 fields (slave 1) on device "3OSIS9jSTq"
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #1: @0 with length 2000
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #2: @2000 with length 2000
2025-04-24T08:06:51Z D! [inputs.modbus::inputs@modbus@3OSIS9jSTq]     #3: @4000 with length 1000

### Expected behavior

inputs.modbus plugin supports custom maxBatchSize

### Actual behavior

I couldn't find where to set maxBatchSize

**Comment by srebhan** [comment]
@zqm6133 what device are we talking about? I'm asking because the device does _NOT_ implement the [Modbus specification](https://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf) then, which demands being able to read up to 125 holding registers in a batch (see section 6.3) and 2000 discrete states (see section 6.1)...

This being said, can you post your (redacted) config please? What you can do is to define the batches yourself with the `request`-style configuration and disabling any optimization...

**Comment by zqm6133** [comment]
@srebhan Thank you for your reply, I also believe that the device is not a standard modbus protocol and does not support read up to 125 holding registers in a batch. I have considered splitting it into multiple **inputs.modbus.requests**, but the actual device performance is poor and I have to enable optimization to reduce the number of requests. Here is my configuration,This is an example, in reality, there are more fields
:
```
[[inputs.modbus]]
  name_override = "3OSIS9jSTq"
  name = "3OSIS9jSTq"
  alias = "inputs@modbus@3OSIS9jSTq"
  timeout = "1s"
  controller = "tcp://10.3.150.158:502"
  configuration_type = "request"

  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "discrete"
    optimization = "max_insert"
    optimization_max_register_fill = 2000
    fields = [{address = 999, name = '1x1000:BOOL', type = ''}, {address = 0, name = '1x0001:BOOL', type = ''}, {address = 2299, name = '1x2300:BOOL', type = ''}]

    [inputs.modbus.request.tags]
      device_id = "200027"
  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "coil"
    optimization = "max_insert"
    optimization_max_register_fill = 2000
    fields = [{address = 129, name = '0x0130:BOOL', type = ''}, {address = 105, name = '0x0106:BOOL', type = ''}, {address = 99, name = '0x0100:BOOL', type = ''}, {address = 106, name = '0x0107:BOOL', type = ''}, {address = 2129, name = '0x2130:BOOL', type = ''}, {address = 1099, name = '0x1100:BOOL', type = ''}]

    [inputs.modbus.request.tags]
      device_id = "200027"
  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "holding"
    optimization = "max_insert"
    optimization_max_register_fill = 125
    fields = [{address = 99, name = '4x0100:WORD', type = 'UINT16'}, {address = 117, name = '4x0118:REAL', type = 'FLOAT32'}, {address = 0, name = '4x0001:REAL', type = 'FLOAT32'}, {address = 105, name = '4x0106:REAL', type = 'FLOAT32'}, {address = 507, name = '4x0508:REAL', type = 'FLOAT32'}, {address = 199, name = '4x0200:REAL', type = 'FLOAT32'}]

    [inputs.modbus.request.tags]
      device_id = "200027"
  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "input"
    optimization = "max_insert"
    optimization_max_register_fill = 125
    fields = [{address = 0, name = '3x0001:REAL', type = 'FLOAT32'}, {address = 119, name = '3x0120:REAL', type = 'FLOAT32'}, {address = 199, name = '3x0200:REAL', type = 'FLOAT32'}]

    [inputs.modbus.request.tags]
      device_id = "200027"

```

**Comment by srebhan** [comment]
What would be your `max_register` values you would configure? Would they be smaller than the spec-max of 125 and 2000 respectively?

>  I have considered splitting it into multiple inputs.modbus.requests, but the actual device performance is poor and I have to enable optimization to reduce the number of requests. so I need to configure the maximum read limit in the plugin configuration

You can sort the registers by address and then fill the holes manually using the `omit` flag. This will group the registers into batches, or you add multiple `requests` per register type and use the optimization e.g. for `holding` and the config above:

```toml
[[inputs.modbus]]
  ...
  configuration_type = "request"

  ...

  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "holding"
    fields = [
      {address = 0, name = '4x0001:REAL', type = 'FLOAT32'},
    ]
    [inputs.modbus.request.tags]
      device_id = "200027"

  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "holding"
    optimization = "max_insert"
    optimization_max_register_fill = 100
    fields = [
      {address = 99, name = '4x0100:WORD', type = 'UINT16'},
      {address = 105, name = '4x0106:REAL', type = 'FLOAT32'},
      {address = 117, name = '4x0118:REAL', type = 'FLOAT32'},
      {address = 199, name = '4x0200:REAL', type = 'FLOAT32'}
    ]
    [inputs.modbus.request.tags]
      device_id = "200027"

  [[inputs.modbus.request]]
    slave_id = 1
    byte_order = "ABCD"
    register = "holding"
    fields = [
      {address = 507, name = '4x0508:REAL', type = 'FLOAT32'},
    ]
    [inputs.modbus.request.tags]
      device_id = "200027"

  ...
```

which would issue three requests...
