### ISSUE TITLE
Allow UNIX timestamp parsing in a Timezone

### ISSUE THREAD

**Issue by ErmakovDmitriy** [influxdata/telegraf#16875]
### Use Case

I have a configuration:

```toml
    [[inputs.file]]                                                                                                                                                                                                                                                                                                           
      files = ["/config/data.csv"]                                                                                                                                                                                                                                                                                        
      csv_delimiter = ";"                                                                                                                                                                                                                                                                                                     
      csv_header_row_count = 1                                                                                                                                                                                                                                                                                                
      csv_timestamp_column = "(s)"                                                                                                                                                                                                                                                                                            
      csv_timestamp_format = "unix"                                                                                                                                                                                                                                                                                           
      csv_timezone = "Europe/Stockholm"                                                                                                                                                                                                                                                                                         
      data_format = "csv"                                                                                                                                                                                                                                                                                                     
      interval = "60s"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
```

which is supposed to read a CSV file with metrics and ingest them.

The CSV file is below:

```csv
(s);Temp 1;Temp 2;Temp 3;Temp 4;Temp 5;Temp 6;Temp KB1 Tillopp;Temp 7;Temp 7 RH;Temp 8;Temp 9;Temp 10
1745482082;22.6;23.2;23.2;22.0;23.2;24.5;10.3;20.9;19.0;20.2;23.0;21.7
```

The reading part works well but there is an issue that the UNIX timestamp is not UTC but local time which causes the resulting metric timestamp to be in future.

I see that the CSV parser has [parseTimestamp](https://github.com/influxdata/telegraf/blob/master/plugins/parsers/csv/parser.go#L473) function which calls [ParseTimestamp](https://github.com/influxdata/telegraf/blob/master/internal/internal.go#L263).

The `ParseTimestamp`  always parses UNIX timestamp in UTC ( [parseUnix](https://github.com/influxdata/telegraf/blob/master/internal/internal.go#L281) ).

If this is a necessary feature, I can try to provide a PR.

### Expected behavior

It would be nice to parse UNIX timestamps with respect to the provided Timezone similar to how it is done for non-timestamp formats so that the resulting metric time is correct and the behavior for both unix, unix_ms, unix_ns, unix_us and custom time formats are the same.

### Actual behavior

UNIX timestamps are always parsed in UTC.

### Additional info

_No response_
