### ISSUE TITLE
inputs.snmp does not reconnect after network issue

### ISSUE THREAD

**Issue by Hr0bar** [influxdata/telegraf#16880]
### Relevant telegraf.conf

```toml
[[inputs.snmp]]
  alias = "CENSORED"
  name_override = "CENSORED"
  agents = ["TARGET.com,..."]
  timeout = "5s"
  version = 3
  sec_name = "CENSORED"
  auth_protocol = "SHA"
  auth_password = "CENSORED"
  sec_level = "authPriv"
  priv_protocol = "AES"
  priv_password = "CENSORED"
  agent_host_tag = "source"

  [[inputs.snmp.field]]
    oid = ".1.3.6.1.2.1.1.3.0"
    name = "uptime"
```

### Logs from Telegraf

```text
Apr 25 09:37:20 HOSTNAME.com telegraf[1405]: 2025-04-25T09:37:20Z E! [inputs.snmp::CENSORED] Error in plugin: agent udp://TARGET.com:161: performing get on field uptime: request timeout (after 3 retries)
...
ABOVE ERROR REPEATS FOREVER
...
RESTART TELEGRAF
...
NO MORE ERRORS
```

### System info

Telegraf 1.34.1 (git: HEAD@6d52cd2f), RHEL9 latest updates

### Steps to reproduce

1. Add firewall (but likely can be any other network change or temporary issue) in front of target system being monitored through telegraf inputs.snmp
2. Telegraf stops collecting data
3. Restarting telegraf resolves the issue
...

### Expected behavior

Telegraf reconnects after error is detected

### Actual behavior

Telegraf errors out forever

### Additional info

Hi, we have added a firewall in front of a system being monitored by inputs.snmp, after that the already mentioned error appears in logs indefinitely (in our case 24 hours+).   Restarting telegraf resolved the issue. 

There seems to be some sort of connection cache, it even has a Reconnect implemented on error, but for some reason it doesnt kick in / works correctly in this case.
