### ISSUE TITLE
inputs.kafka_consumer: Write kafka message key fields into the metric tags

### ISSUE THREAD

**Issue by BelousovAntonV** [influxdata/telegraf#16912]
### Use Case

For cases, when Kafka message has a key the only one way to load its fields as the tags into Influx is to duplicate these key fileds in the message itself. We have to store data in Kafka message with the composite keys and the same value structure. And when we want to load it to Influx we got all of them as the only one time series, with some points overwritten in case when they had the same timestamp. 

Here is an example of the Kafka message:
`{
    'key':{
         'code1':'some_value_1',
         'code2':'some_value 2'
    }
    'value':{
         'metric_name1':'value1',
         'timestamp':'unix_time'
    }
}`

We have to modify the message as follows:
`{
    'key':{
         'code1':'some_value_1',
         'code2':'some_value 2'
    }
    'value':{
         'metric_name1':'value1',
         'timestamp':'unix_time',
         'code 1':'some_value_1',
         'code2':'some_value 2'
    }
}`

Which is not optimal.

### Expected behavior

In case when the option `msg_keys_as_tags` is provided with an array of field names, the values of these key fields are added to the metric tags.

### Actual behavior

No such option.

### Additional info

The most issue I see here is that the Kafka message key also could be serialized as well as the message value and could use another SerDe at the same time.

**Comment by srebhan** [comment]
@BelousovAntonV I'm not sure I do understand the issue, especially how this is Kafka specific. To me it looks like a parsing problem... So given the following payload

```json
{
    "key": {
        "code1": "some_value_1",
        "code2": "some_value 2"
    },
    "value": {
        "metric_name": "value1",
        "timestamp": 1746780414
    }
}
```

you can parse it using the [xpath parser](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/xpath) using

```toml
[[inputs.kafka_consumer]]
  ...

  data_format = "xpath_json"
  xpath_native_types = true
  [[inputs.kafka_consumer.xpath]]
    metric_name = "/value/metric_name"
    field_selection = "/key/*"
    tag_selection = "/key/*"
    timestamp = "/value/timestamp"
    timestamp_format = "unix"
```

resulting in the following metric

```
value1,code1=some_value_1,code2=some_value\ 2,host=Hugin code1="some_value_1",code2="some_value 2" 1746780414000000000
```

Isn't this what you are looking for?
