### ISSUE TITLE
[gnmi] Empty metric name for qfx5120-32c with Junos 23.4R2-S3.9 flex

### ISSUE THREAD

**Issue by lkowolowski-fa** [influxdata/telegraf#17020]
### Relevant telegraf.conf

```toml
[[inputs.gnmi]]
    ## Address and port of the gNMI GRPC server
    addresses = ["qfx5120-32c-switch.domain:30000"]

    ## define credentials
    #   username = "cisco"
    #   password = "cisco"
    ## gNMI encoding requested (one of: "proto", "json", "json_ietf", "bytes")
    # encoding = "proto"

    ## redial in case of failures after
    redial = "10s"

    ## enable client-side TLS and define CA to authenticate the device
    # enable_tls = true
    # tls_ca = "/etc/telegraf/ca.pem"
    # insecure_skip_verify = true

    ## define client-side TLS certificate & key to authenticate to the device
    # tls_cert = "/etc/telegraf/cert.pem"
    # tls_key = "/etc/telegraf/key.pem"

    ## gNMI subscription prefix (optional, can usually be left empty)
    ## See: https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#222-paths
    # origin = ""
    # prefix = ""
    # target = ""

    ## Define additional aliases to map telemetry encoding paths to simple measurement names
    # [inputs.gnmi.aliases]
    #   ifcounters = "openconfig:/interfaces/interface/state/counters"
  [[inputs.gnmi.subscription]]
    ## Name of the measurement that will be emitted
    name = "ifcounters"

    ## Origin and path of the subscription
    ## See: https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#222-paths##
    ## origin usually refers to a (YANG) data model implemented by the device
    ## and path to a specific substructure inside it that should be subscribed to (similar to an XPath)
    ## YANG models can be found e.g. here: https://github.com/YangModels/yang/tree/master/vendor/cisco/xr
    origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/counters"

    # Subscription mode (one of: "target_defined", "sample", "on_change") and interval
    subscription_mode = "sample"
    sample_interval = "10s"
    ## Suppress redundant transmissions when measured values are unchanged
    # suppress_redundant = false
    ## If suppression is enabled, send updates at least every X seconds anyway
    # heartbeat_interval = "60s"
  [[inputs.gnmi.subscription]]
    name = "descr"
    origin = "openconfig-interfaces"
    path = "/interfaces/interface/state/description"
    subscription_mode = "on_change"
    # If tag_only is set, the subscription in question will be utilized to maintain a map of
    # tags to apply to other measurements emitted by the plugin, by matching path keys
    # All fields from the tag-only subscription will be applied as tags to other readings,
    # in the format <name>_<fieldBase>.
    tag_only = true
```

### Logs from Telegraf

```text
telegraf-1  | 2025-05-19T14:46:20Z I! Loading config: /etc/telegraf/telegraf.conf
telegraf-1  | 2025-05-19T14:46:20Z W! DeprecationWarning: Option "tag_only" of plugin "inputs.gnmi" deprecated since version 1.25.0 and will be removed in 1.35.0: please use 'tag_subscription's instead
telegraf-1  | 2025-05-19T14:46:20Z I! Starting Telegraf 1.34.3 brought to you by InfluxData the makers of InfluxDB
telegraf-1  | 2025-05-19T14:46:20Z I! Available plugins: 239 inputs, 9 aggregators, 33 processors, 26 parsers, 63 outputs, 6 secret-stores
telegraf-1  | 2025-05-19T14:46:20Z I! Loaded inputs: exec gnmi
telegraf-1  | 2025-05-19T14:46:20Z I! Loaded aggregators:
telegraf-1  | 2025-05-19T14:46:20Z I! Loaded processors:
telegraf-1  | 2025-05-19T14:46:20Z I! Loaded secretstores:
telegraf-1  | 2025-05-19T14:46:20Z I! Loaded outputs: prometheus_client
telegraf-1  | 2025-05-19T14:46:20Z I! Tags enabled: host=host.domain.com
telegraf-1  | 2025-05-19T14:46:20Z W! Deprecated inputs: 0 and 1 options
telegraf-1  | 2025-05-19T14:46:20Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"host.domain.com", Flush Interval:10s
telegraf-1  | 2025-05-19T14:46:20Z W! [agent] The default value of 'skip_processors_after_aggregators' will change to 'true' with Telegraf v1.40.0! If you need the current default behavior, please explicitly set the option to 'false'!
telegraf-1  | 2025-05-19T14:46:20Z D! [agent] Initializing plugins
telegraf-1  | 2025-05-19T14:46:20Z D! [inputs.gnmi] Internal alias mapping: map[openconfig-interfaces:/interfaces/interface/state/counters:ifcounters openconfig-interfaces:/interfaces/interface/state/description:descr]
telegraf-1  | 2025-05-19T14:46:20Z D! [agent] Connecting outputs
telegraf-1  | 2025-05-19T14:46:20Z D! [agent] Attempting connection to [outputs.prometheus_client]
telegraf-1  | 2025-05-19T14:46:20Z I! [outputs.prometheus_client] Listening on http://[::]:9273/metrics
telegraf-1  | 2025-05-19T14:46:20Z D! [agent] Successfully connected to outputs.prometheus_client
telegraf-1  | 2025-05-19T14:46:20Z D! [agent] Starting service inputs
telegraf-1  | 2025-05-19T14:46:21Z D! [inputs.gnmi] Connection to gNMI device cfr01-mgmt.den.flightaware.com:30000 established
telegraf-1  | 2025-05-19T14:46:24Z D! [inputs.gnmi] No measurement alias for gNMI path: /interfaces/interface/init-time
telegraf-1  | 2025-05-19T14:46:24Z W! [inputs.gnmi] Got empty metric-name for response (field "/interfaces/interface/init-time"), usually
telegraf-1  | indicating configuration issues as the response cannot be related to any
telegraf-1  | subscription.Please open an issue on https://github.com/influxdata/telegraf
telegraf-1  | including your device model and the following response data:
telegraf-1  | {"Update":{"timestamp":1747665984658000000,"prefix":{"elem":[{"name":"interfaces"},{"name":"interface","key":{"name":"gr-0/0/0"}}]},"update":[{"path":{"elem":[{"name":"init-time"}]},"val":{"Value":{"UintVal":1738203675}}},{"path":{"elem":[{"name":"state"},{"name":"parent-ae-name"}]},"val":{"Value":{"StringVal":""}}},{"path":{"elem":[{"name":"state"},{"name":"high-speed"}]},"val":{"Value":{"UintVal":800}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-octets"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-unicast-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-multicast-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-broadcast-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-pause-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-octets"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-unicast-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-multicast-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-broadcast-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-pause-pkts"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-errors"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-fcs-errors"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"in-discards"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"carrier-transitions"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-errors"}]},"val":{"Value":{"UintVal":0}}},{"path":{"elem":[{"name":"state"},{"name":"counters"},{"name":"out-discards"}]},"val":{"Value":{"UintVal":0}}}]}}
telegraf-1  | This message is only printed once.
```

### System info

Model: qfx5120-32c Junos: 23.4R2-S3.9 flex Telegraf 1.34.3 (git: HEAD@983d399f)

### Docker

Dockerfile

```
FROM telegraf:latest

RUN apt-get update && apt-get install -y --no-install-recommends mtr-tiny && \
	rm -rf /var/lib/apt/lists/*
```

docker-compose.yml

```
version: '3'
services:
  telegraf:
    image: "docker-registry.domain.com/telegraf:${TELEGRAF_VERSION}"
    environment:
      DOCKER_BUILDKIT: '1'
      COMPOSE_DOCKER_CLI_BUILD: '1'
    hostname: "${HOSTNAME}"
    network_mode: host
    volumes:
      - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file:
      - settings.env
    logging:
      driver: "syslog"
      options:
        tag: "{{.Name}}"
    restart: unless-stopped
```

### Steps to reproduce

1. using the gnmi config, docker compose up it spits out the above message with a request to file a bug

### Expected behavior

expected somebody else would have run into this (for this platform).

### Actual behavior

it requested opening an issue to have the problem fixed

### Additional info

thank you for having the output in the log directing me here. wasn't sure what kind of issue to file, if there is a way to make that clear in the telegraf output, that would be great.

**Comment by srebhan** [comment]
@lkowolowski-fa your device seems to send some additional data that you did not subscribe to under `/interfaces/interface` like `init-time`, `state/parent-ae-name` , `state/highspeed` etc. This is unexpected behavior and given the configuration we don't know how to name those metrics as we don't have a corresponding subscription. You can fix this by providing an alias like

```toml
 [inputs.gnmi.aliases]
   additional = "/interfaces/interface"
```
