### ISSUE TITLE
Question about inputs.mysql to outputs.clickhouse

### ISSUE THREAD

**Issue by spihiker** [influxdata/telegraf#17050]
### Relevant telegraf.conf

```toml
conf:
[[inputs.mysql]]
   servers = ["***:***@tcp(127.0.0.1:3308)/?tls=false"]
   metric_version = 2

[[outputs.sql]]
   driver = "clickhouse"
   data_source_name = "clickhouse://***:***@127.0.0.1:9000/mydb?dial_timeout=200ms&max_execution_time=60"
[outputs.sql.convert]
    conversion_style     = "literal"
    integer              = "Int64"
    text                 = "String"
    timestamp            = "DateTime"
    defaultvalue         = "String"
    unsigned             = "UInt64"
    bool                 = "UInt8"
    real                 = "Float64"
```

### Logs from Telegraf

```text
no
```

### System info

Telegraf 1.34.4, Centos-7.9

### Steps to reproduce

(1)conf:
[[inputs.mysql]]
   servers = ["***:***@tcp(127.0.0.1:3308)/?tls=false"]
   metric_version = 2

[[outputs.sql]]
   driver = "clickhouse"
   data_source_name = "clickhouse://***:***@127.0.0.1:9000/mydb?dial_timeout=200ms&max_execution_time=60"
[outputs.sql.convert]
    conversion_style     = "literal"
    integer              = "Int64"
    text                 = "String"
    timestamp            = "DateTime"
    defaultvalue         = "String"
    unsigned             = "UInt64"
    bool                 = "UInt8"
    real                 = "Float64"

(2)Problem:
I found that the table in the clickhouse database has duplicate data。As follow:
 
    ┌───────────timestamp─┬─host────────┬─queries─┐
 1. │ 2025-05-23 18:02:40 │ dev-mysql01 │ 5703865 │
 2. │ 2025-05-23 18:02:40 │ dev-mysql01 │       0 │
 3. │ 2025-05-23 18:02:40 │ dev-mysql01 │       0 │
 4. │ 2025-05-23 18:02:40 │ dev-mysql01 │       0 │
 5. │ 2025-05-23 18:02:40 │ dev-mysql01 │       0 │
 6. │ 2025-05-23 18:02:30 │ dev-mysql01 │ 5703863 │
 7. │ 2025-05-23 18:02:30 │ dev-mysql01 │       0 │
 8. │ 2025-05-23 18:02:30 │ dev-mysql01 │       0 │
 9. │ 2025-05-23 18:02:30 │ dev-mysql01 │       0 │
10. │ 2025-05-23 18:02:30 │ dev-mysql01 │       0 │
    └─────────────────────┴─────────────┴─────────┘

### Expected behavior

I hope to put the data collected by the inputs.mysql module together. This way there will be no duplicate data when writing to the clickhosue database

### Actual behavior

 No duplicate data when writing to the clickhosue database
