### ISSUE TITLE
Datadog Output should accept ApiKey as an environment variable

### ISSUE THREAD

**Issue by MathewBoyles** [influxdata/telegraf#17075]
### Use Case

My use-case is inside Kubernetes. I am using a `Secret` so the apikey does not need to be hard-coded into the config. My Helmfile is kept inside source control, but the key remains only inside the Kubernetes cluster.

```yaml
releases:
  - name: telegraf
    namespace: telegraf
    createNamespace: true
    chart: influxdata/telegraf
    version: 1.8.57
    needs:
      - datadog-api-key
    values:
      - config:
          agent:
            env:
              - name: DD_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: datadog-api-key
                    key: token
          processors: []
          outputs:
            - datadog:
                apikey: ""
                envvar: "DD_API_KEY"
```

### Expected behavior

When enabled, Datadog output plugin will use the value of the specified environment variable for the api key.

### Actual behavior

The Datadog output plugin does not use envrionment variables and requires the API key to be hard-coded into the config file.
