### ISSUE TITLE
outputs.nats.jetstream Attempts to Modify Existing Stream incorrectly

### ISSUE THREAD

**Issue by mgale** [influxdata/telegraf#17072]
### Relevant telegraf.conf

```toml
[[outputs.nats]]
  servers = ["nats://nats:4222"]
  subject = "mymetrics.events.foo.bar"
  data_format = "influx"
  name = "myhostname"
  credentials = "/etc/telegraf/nats.cred"

[outputs.nats.jetstream]
  name = "mymetrics" ## This is the name of the JetStream stream
```

### Logs from Telegraf

```text
2025-05-29T15:42:56Z I! [outputs.nats] Stream (mymetrics) successfully created or updated
```

### System info

Telegraf 1.34.4 Ubuntu 22.04

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

The stream is managed on the NATS Cluster and is configured to contain all messages using the subject filter `mymetrics.events.>`. The plugin should use the stream as-is.

### Actual behavior

The plugin updates the stream and replaces the subject filter with its own.

### Additional info

A simple fix could be that there is param for managed streams, like:
```
[outputs.nats.jetstream]
  name = "mymetrics"
  server_managed = true
```

Possible param names:
server_managed = true
stream_autocreate = false
ensure_stream = false
