### ISSUE TITLE
Telegraf Configuration Reload Issue: Increasing Memory Requirement & Secrets Count

### ISSUE THREAD

**Issue by someya-iim** [influxdata/telegraf#17099]
### Relevant telegraf.conf

```toml
[[outputs.influxdb_v2]]
  urls = ["http://172.16.111.174:8086"]
  token = "dWqvPccUMIa-pPhfRUa64yq0dJgdnEVhZYYXTxLLzcphSYIfZfu-X1py2NvS9vzI0rb2rEdI0W6X_8BVr4comQ=="
  organization = "shelty_org"
  bucket = "shelty_db/rp_modular_store"
  namepass = ["cpu_core_usage"]
```

### Logs from Telegraf

```text
2025-05-13T11:27:39+09:00 I! Found 3433 secrets..
2025-05-13T11:27:39+09:00 W! Insufficient lockable memory 64kb when 41196kb is required. Please increase the limit for Telegraf in your Operating System!
```

### System info

Telegraf 1.33.3 RHEL8

### Steps to reproduce

**Use Case**
We are using the outputs.influxdb_v2 plugin for Telegraf. 
Command line arguments used at startup. 
```
/opt/telegraf/telegraf -config /etc/telegraf/telegraf.conf -watch-config notify
```
When the Telegraf configuration is repeatedly modified, the settings are successfully loaded each time, and eventually, the following message is displayed.

```
2025-05-13T11:27:39+09:00 I! Found 3433 secrets..
2025-05-13T11:27:39+09:00 W! Insufficient lockable memory 64kb when 41196kb is required. Please increase the limit for Telegraf in your Operating System!
```
After that, with each update, the 'Found ... secrets.' and 'when ...kb is required.' ...parts in the log keep increasing.(One instance of the outputs.influxdb_v2 plugin is configured in the Telegraf config file.)

### Expected behavior

It is desirable that memory usage and the number of secrets do not increase.

### Actual behavior

Increasing Memory Requirement & Secrets Count
