### ISSUE TITLE
outputs.prometheus_client overwrites input go_ metrics

### ISSUE THREAD

**Issue by Deshke** [influxdata/telegraf#17108]
### Relevant telegraf.conf

```toml
#
# OUTPUTS:
#
[[outputs.prometheus_client]]
listen = ":9273"


#
# INPUTS:
#
[[inputs.cpu]]
percpu = true
totalcpu = true
[[inputs.prometheus]]
urls = ["http://localhost:9090/metrics"]
```

### Logs from Telegraf

```text
/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --debug
2025-06-04T11:49:39Z I! Loading config: /etc/telegraf/telegraf.conf
2025-06-04T11:49:39Z I! Loading config: /etc/telegraf/telegraf.d/some-input-config.conf
```

### System info

Telegraf 1.34.4 (git: HEAD@e7ce1e1e) 

### Steps to reproduce

steps 

1. have another application provide `go_*` metrics  
2. have telegraf scrape and output them

```bash
curl -s "localhost:9273/metrics" | grep goro
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 31
```

and from the scrape target at `:9090`

```bash
curl -s http://localhost:9090/metrics | grep goro
# HELP go_goroutines Number of goroutines that currently exist.
# TYPE go_goroutines gauge
go_goroutines 4273
```

### Expected behavior

metrics from the input section get properly labled

### Actual behavior

`go_` metrics provided by application at `localhost:9090/metrics` get ignored and overwritten
