### ISSUE TITLE
[processors.converter] Converting to base64_ieee_float32 [string] failed: illegal base64 data at input byte 0

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#17154]
### Relevant telegraf.conf

```toml
[agent]
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 500000
  flush_interval = "10s"
  debug = true
  quiet = false
  hostname = "$containerName-telegraf-agent"
  omit_hostname = false
  skip_processors_after_aggregators = false

# Setting up input for sensors that emit a measurement name#
[[inputs.gnmi]]
  dump_responses = true
  addresses = ["labbbrj11.mgt.net:50051"]
  username = "$user"
  password = "$password"
  encoding = "proto"
  redial = "10s"
  tls_enable = true
  tls_ca = "/etc/telegraf/router_ca.pem"
  insecure_skip_verify = true
  vendor_specific = ["juniper_header"]

  [inputs.gnmi.aliases]
    optics = "/interfaces/interface/optics"
    snmp_if_index = "/interfaces/interface/snmp_if_index"

  [[inputs.gnmi.subscription]]
      name = "optics"
      origin = "junos"
      path = "/junos/system/linecard/optics"
      subscription_mode = "sample"
      sample_interval = "60s"
  
[[processors.converter]]
  namepass = ["optics"]
  [processors.converter.fields]
    base64_ieee_float32 = ["*lane_laser_receiver_power_dbm","*lane_laser_output_power_dbm"]


[[outputs.influxdb]]
  urls = ["http://1.2.1.2:8086"]
  database = "basic-config-data"

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]
  # data_format = "json"
```

### Logs from Telegraf

```text
2025-06-10T22:35:14Z E! [processors.converter] Converting to base64_ieee_float32 [string] failed: illegal base64 data at input byte 0
2025-06-10T22:35:14Z E! [processors.converter] Converting to base64_ieee_float32 [string] failed: illegal base64 data at input byte 0
```

### System info

Telegraf 1.34.4-alpine docker image and Telegraf executable 1.34.4

### Steps to reproduce

1. Use either Telegraf container or executable with Telegraf config provided above to connect to a Juniper PTX device.

### Expected behavior

Expecting Telegraf to convert the ieeefloat32 values for lane_laser_receiver_power_dbm and lane_laser_output_power_dbm fields correctly.

### Actual behavior

Receiving error:
2025-06-10T22:35:14Z E! [processors.converter] Converting to base64_ieee_float32 [string] failed: illegal base64 data at input byte 0

### Additional info

@srebhan , this appears to be related to 
https://github.com/influxdata/telegraf/issues/15046
https://github.com/influxdata/telegraf/issues/16365

[telegraf_output.json](https://github.com/user-attachments/files/20680993/telegraf_output.json)
