### ISSUE TITLE
[inputs.teamspeak] Telegraf makes TeamSpeak server inaccessible

### ISSUE THREAD

**Issue by dlmw** [influxdata/telegraf#17179]
### Relevant telegraf.conf

```toml
[[inputs.teamspeak]]
  server = "teamspeak:10011"
  username = "REDACTED"
  password = "REDACTED"
  nickname = "telegraf"
  [inputs.teamspeak.tags]
    service = "teamspeak"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "REDACTED"
  organization = "REDACTED"
  bucket = "influxdb"
```

### Logs from Telegraf

```text
Not applicable, but see "Additionnal info" for TeamSpeak logs
```

### System info

Telegraf 1.34.3; Docker version 26.1.5-ce, build 411e817ddf71; openSUSE Leap

### Docker

```yml
services:
  grafana:
    image: grafana/grafana:12.0.0
    deploy:
      placement:
        constraints:
          - "node.labels.grafana==true"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - reverse-proxy-network
      - monitoring-network

  influxdb:
    image: influxdb:2.7.10-alpine
    deploy:
      placement:
        constraints:
          - "node.labels.influxdb==true"
    volumes:
      - influxdb-config:/etc/influxdb2
      - influxdb-data:/var/lib/influxdb2
    networks:
      - monitoring-network
      - reverse-proxy-network

  telegraf:
    image: telegraf:1.34.3
    deploy:
      placement:
        constraints:
          - "node.labels.telegraf==true"
    configs:
      - source: telegraf-conf
        target: /etc/telegraf/telegraf.conf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: telegraf:475
    networks:
      - monitoring-network

networks:
  reverse-proxy-network:
    external: true
  monitoring-network:
    external: true

configs:
  telegraf-conf:
    external: true

volumes:
  grafana-data:
  influxdb-config:
  influxdb-data:
```

### Steps to reproduce

1. Create a Telegraf service that has a TeamSpeak input
2. Make it collect metrics for a long time (one week is more than enough, but I don't know the exact duration as of writing this)
3. Try to connect to the TeamSpeak server using the TeamSpeak client, but you will get `database error`. Try again (4-5, sometimes 10 times) until you succeed

### Expected behavior

Telegraf shouldn't eat up TeamSpeak server resources. I'm assuming it's the network part. Stopping Telegraf made connection attempts work instantly.

### Actual behavior

If running for a long time (specific duration unknown at the moment), Telegraf makes connection to a TeamSpeak server harder.

### Additional info

I've described everything in detail [here](https://community.teamspeak.com/t/database-error-lost-connection-to-mysql-server-during-query/60392) as I thought it was an issue with TeamSpeak at first.
