### ISSUE TITLE
Telegraf appends _value to all my metrics

### ISSUE THREAD

**Issue by diogorib94** [influxdata/telegraf#17204]
### Relevant telegraf.conf

```toml
[agent]
  logfile = "/var/log/telegraf/telegraf.log"

[[inputs.exec]]
  commands = ["/usr/bin/python3 collector.py"]
  data_format = "xpath_json"
  timeout = "29s"
  interval = "30s"
  [[inputs.exec.xpath]]
    metric_selection = "/*"
    metric_name = "name"
    field_selection = "value"
    tag_selection = "tags/*"

[[processors.converter]]
  namepass = ["*"]
  [processors.converter.fields]
    float = ["value"]

[[outputs.opentelemetry]]
  service_address = "127.0.0.1:4317"
```

### Logs from Telegraf

```text
2025-06-17T17:27:13Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2025-06-17T17:27:16Z D! [parsers.xpath_json::exec] Number of configs: 1
2025-06-17T17:27:16Z D! [parsers.xpath_json::exec] Number of selected metric nodes: 726
2025-06-17T17:27:16Z D! [parsers.xpath_json::exec] Number of selected tag nodes: 0
2025-06-17T17:27:16Z D! [parsers.xpath_json::exec] Number of selected field nodes: 1
...
2025-06-17T17:27:16Z D! [parsers.xpath_json::exec] Number of selected tag nodes: 2
2025-06-17T17:27:16Z D! [parsers.xpath_json::exec] Number of selected field nodes: 1
2025-06-17T17:27:23Z D! [outputs.opentelemetry] Received 726 metrics and split into 1 groups by timestamp
2025-06-17T17:27:23Z D! [outputs.file] Wrote batch of 726 metrics in 28.938597ms
2025-06-17T17:27:23Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
2025-06-17T17:27:23Z D! [outputs.opentelemetry] Wrote batch of 726 metrics in 34.88422ms
2025-06-17T17:27:23Z D! [outputs.opentelemetry] Buffer fullness: 0 / 10000 metrics
```

### System info

Telegraf: 1.34.2

### Steps to reproduce

1. My script output:
```
[
    {
        "name": "errors.bolts.failed",
        "value": 0.0,
        "tags": {
            "bolt": "bol1",
            "host": "host1"
        }
    },
    {
        "name": "latency.bolts.process.latency",
        "value": 0.2,
        "tags": {
            "bolt": "bol2",
            "host": "host2"
        }
    },
    {
        "name": "traffic.bolts.transferred",
        "value": 0.5,
        "tags": {
            "bolt": "bol3",
            "host": "host3"
        }
    }
]
```
2. run telegraf with provided config.

### Expected behavior

On SignalFX I wanted to have metric name 'errors.bolts.failed', 'latency.bolts.process.latency' and 'traffic.bolts.transferred'

### Actual behavior

What I actual have is 'errors.bolts.failed_value', 'latency.bolts.process.latency_value' and 'traffic.bolts.transferred_value'
I have tried with json and the behaviour is the same.

### Additional info

Is there a way to tell telegraf to not add that '_value' suffix before sending to SignalFX?

**Comment by skartikey** [comment]
The issue you're experiencing is due to how Telegraf's `xpath_json` parser handles field naming. When you specify `field_selection = "value"`, Telegraf creates a field called "value" and then appends it to your metric name with an underscore, resulting in names like `errors.bolts.failed_value`.

Use the `rename` processor to remove the `_value` suffix, add this processor to your config after the converter:

```
[[processors.converter]]
  namepass = ["*"]
  [processors.converter.fields]
    float = ["value"]

[[processors.rename]]
  namepass = ["*"]
  [[processors.rename.replace]]
    measurement = "*"
    dest = "$1"
    pattern = "^(.*)_value$"

[[outputs.opentelemetry]]
  service_address = "127.0.0.1:4317"
```
This will strip the `_value` suffix from all your metric names before they're sent to your output.

**Comment by diogorib94** [comment]
I have tried but got this error, I will keep searching for something similar with your solution

`2025-06-18T10:36:49Z E! loading config file /etc/telegraf/telegraf.conf failed: plugin processors.rename: line 17: configuration specified the fields ["pattern"], but they were not used. This is either a typo or this config option does not exist in this version.`

**Comment by diogorib94** [comment]
Hello @skartikey I have tried with `processors.regex` and got the same result, on SignalFX it has the "_value" suffix on all metrics

![Image](https://github.com/user-attachments/assets/8e257208-38e6-4bc6-88e5-cb953b022a41)

```
[[processors.regex]]
  namepass = ["*"]
  [[processors.regex.metric_rename]]
    #measurement = "*"
    pattern = "^(.*)_value$"
    replacement = "$1"
```

**Comment by skartikey** [comment]
For Telegraf 1.34.2, you should use the regex processor instead. Here's the correct configuration:

```
[[processors.regex]]
  namepass = ["*"]
  [[processors.regex.metric_rename]]
    pattern = "^(.*)_value$"
    replacement = "$1"
```

So your complete configuration should look like this:

```
[agent]
  logfile = "/var/log/telegraf/telegraf.log"

[[inputs.exec]]
  commands = ["/usr/bin/python3 collector.py"]
  data_format = "xpath_json"
  timeout = "29s"
  interval = "30s"
  [[inputs.exec.xpath]]
    metric_selection = "/*"
    metric_name = "name"
    field_selection = "value"
    tag_selection = "tags/*"

[[processors.converter]]
  namepass = ["*"]
  [processors.converter.fields]
    float = ["value"]

[[processors.regex]]
  namepass = ["*"]
  [[processors.regex.metric_rename]]
    pattern = "^(.*)_value$"
    replacement = "$1"

[[outputs.opentelemetry]]
  service_address = "127.0.0.1:4317"
```

**Comment by skartikey** [comment]
Here are a couple of options you can try to fix this:

**1. Using a Starlark Processor:**

```toml
[[processors.starlark]]
  source = '''
def apply(metric):
    if "value" in metric.fields:
        # Remove the _value suffix that gets appended
        metric.name = metric.name.replace("_value", "")
    return metric
'''
```

**2. Adjusting the Field Name in XPath Input:**

```toml
[[inputs.exec.xpath]]
  metric_selection = "/*"
  metric_name = "name"  
  field_selection = "value"
  field_name = "metric_value"  # This should prevent the _value suffix
  tag_selection = "tags/*"
```

**Comment by diogorib94** [comment]
I have tested both and the result remains the same, we think the issue is in the output, somehow it is adding "_<value_name>" to the metric.

if I run with `telegraf --config /etc/telegraf/telegraf.conf --test --input-filter exec`
```
> traffic.bolts.executed,bolt=bolt1,host=host1 value=0 1750255053000000000
> errors.bolts.failed,bolt=bolt2,host=host2 value=0 1750255053000000000
> latency.bolts.process.latency,bolt=bolt3,host=host3 value=0 1750255053000000000
```

If you check the output above the metric does not have the "_value" here, only on SignalFX.

There should be a flag to disable appending "_value", but it would only work with 1 field

**Comment by srebhan** [comment]
@skartikey and @diogorib94 you are thinking _way_ to complex... How about

```toml

[[inputs.exec]]
  commands = ["/usr/bin/python3 collector.py"]
  timeout = "29s"
  interval = "30s"
  data_format = "xpath_json"

  xpath_native_types = true

  [[inputs.exec.xpath]]
    metric_selection = "/*"
    metric_name = "name"
    tag_selection = "tags/*"

    [inputs.exec.xpath.fields]
      value = "value"
```

This produces

```
> errors.bolts.failed,bolt=bol1,host=host1 value=0 1750690283000000000
> latency.bolts.process.latency,bolt=bol2,host=host2 value=0.2 1750690283000000000
> traffic.bolts.transferred,bolt=bol3,host=host3 value=0.5 1750690283000000000
```

for the initial example
