### ISSUE TITLE
processors.strings.replace no long works in 1.35.0

### ISSUE THREAD

**Issue by fhriley** [influxdata/telegraf#17208]
### Relevant telegraf.conf

```toml
[[processors.strings]]
    [[processors.strings.replace]]
      tag = "panel"
      old = "482329026807"
      new = "west01"
```

### Logs from Telegraf

```text
2025-06-18T16:59:34Z E! loading config file /etc/telegraf/solar.conf failed: plugin processors.strings: line 208: configuration specified the fields ["new" "tag" "old"], but they were not used; this is either a typo or this config option does not exist in this version
```

### System info

Telegraf 1.35.0, Docker

### Steps to reproduce

1. Use the above config

### Expected behavior

It doesn't fail

### Actual behavior

It fails with the above log message

### Additional info

Reverting to `1.34.4` fixes the issue.

**Comment by cschug** [comment]
Thanks for opening the issue, I'm seeing the same problem and was just about to report this, too.

**Comment by cschug** [comment]
According to `git bisect` the issue was introduced by https://github.com/influxdata/telegraf/commit/7bffe32f190971e7c6c8a95685803e60dc78d4c6

**Comment by cschug** [comment]
Thanks for the quick attempt to fix the issue per commit https://github.com/influxdata/telegraf/pull/17210/commits/c24078fda21402599e387c0f6ee65bcf8d60dbf0 in #17210 but unfortunately this doesn't resolve the issue, the problem persists.

**Comment by yubbz** [comment]
Small edit below:

I'm just adding that:
```
[[processors.strings]]
  [[processors.strings.trim_prefix]]
    tag = "topic"
    prefix = "abc/"
  [[processors.strings.trim_prefix]]
    tag = "topic"
    prefix = "a/b/"
  [[processors.strings.trim_prefix]]
    tag = "topic"
    suffix = "str/"
  [[processors.strings.trim_suffix]]
    tag = "topic"
    suffix = "/str"
```
is broken too... It works in `1.34.4` and does not in `1.35.0`

docker image returns this:
```
2025-06-19T00:37:56Z I! Loading config: /etc/telegraf/telegraf.conf
2025-06-19T00:37:56Z E! loading config file /etc/telegraf/telegraf.conf failed: plugin processors.strings: line 352: configuration specified the fields ["tag" "prefix" "suffix"], but they were not used; this is either a typo or this config option does not exist in this version
```

**Comment by jwyse** [comment]
`processors.strings.lowercase` is similarly broken.

```toml
# This works in v1.34.4 but is broken in 1.35:

[[processors.strings]]
  [[processors.strings.lowercase]]
    tag_key   = "*" # make all tag keys lowercase
    field_key = "*" # make all field keys lowercase
```

Telegraf (Docker container) does not start and logs the error:
```
telegraf configuration specified the fields ["tag_key" "field_key"], but they were not used; this is either a typo or this config option does not exist in this version
```
