### ISSUE TITLE
kafka: client has run out of available brokers to talk to: local error: tls: unexpected message

### ISSUE THREAD

**Issue by prawen** [influxdata/telegraf#17209]
### Relevant telegraf.conf

```toml
[[inputs.kafka_consumer]]
brokers = ["kafkaserver.mydomain.net:9092"]
version = "1.0.0"
tls_min_version = "TLS12"
tls_server_name = "kafkaserver.mydomain.net"
topics = ["sometopic"]
consumer_group = "someconsumer"
enable_tls = true
tls_ca = "pathtocacert"
tls_cert = "pathtoclientcert"
tls_key = "pathtokey"
insecure_skip_verify = true
```

### Logs from Telegraf

```text
kafka: client has run out of available brokers to talk to: local error: tls: unexpected message
```

### System info

1.34.4

### Steps to reproduce

Connect to Kafka running on SSL with client.auth need

### Expected behavior

Should be able to connect to kafka

### Actual behavior

With the same settings and certs and from same machine, I'm able to connect to Kafka using a python client. But from telegraf I'm unable to connect

### Additional info

Request is going to kafka and in server logs seeing tls handshake failed.
