### ISSUE TITLE
Debugging/Tracing input.exec: Sometimes it sends, sometimes it does not.

### ISSUE THREAD

**Issue by senpro-ingwersenk** [influxdata/telegraf#17235]
### Use Case

We are currently stuck in a situation, were we have five `inputs.exec` entries in our config - but out of all the five, _sometimes_ two of them do something and sometimes they do not. There are no errors in the Telegraf log, and none we could find in Event Viewer in general - yes, this is on Windows. All five of them have the same layout:

```toml
[[inputs.exec]]
  commands = [ "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"&'C:/(...)/backupReplication.ps1' -ReportType backupRepository\"" ]
  interval = "1h"
  timeout = "180s"
  data_format = "json_v2"
  [[inputs.exec.json_v2]]
    measurement_name = "veeam.backupReplication.backupRepository"
    [[inputs.exec.json_v2.object]]
      path = "@this"
      tags = [ "RepositoryName" ]
```

This is why we need more debugging or tracing. Having gone through the recent releases and their changelogs, we have also played around with `debug = true`, as well as `log_level = "trace"` as recently introduced. Unfortunately, to no avail.

He spent the most time with the actual debugging and I went to read the commits, releases and code to try and find him pointers as to what he could try to do. Interestingly, this _did_ use to work in 1.27.

His summary:
- Using Telegraf 1.34.1 with multiple `inputs.exec` plugins scheduled at the same interval (e.g., every 10 minutes).
 - PowerShell processes for each `inputs.exec` are correctly launched (confirmed by observing Task Manager).
 - No errors, timeouts, or scheduling warnings are logged in Telegraf (debug logging enabled).
 - Some `inputs.exec` executions randomly fail to deliver metrics to InfluxDB despite the script always producing valid JSON output (verified via local file logging).
 - Issue did not occur in Telegraf 1.27 with identical configuration and system load. We only recently upgraded to 1.34.
 - Changing GOMAXPROCS had no effect.
  * This was my idea, as this behaviour was talked about a lot lately on r/golang and was mentioned to have it's behaviour changed. Mainly for containers, but I'd thought to just give it a try.
- Appears related to Telegraf’s stricter input scheduling since v1.30, where `inputs.exec` commands scheduled at the same interval may conflict or be silently skipped even when system resources are available.

### Expected behavior

Telegraf should either multi-thread `inputs.exec` properly or log skipped executions clearly.

Or, it should produce apropriate logs in debug/trace logging to indicate:
- When the command (and which one) was started,
- If it exited with a non-zero exit code
- If it was perhaps killed due to timeout or alike.

### Actual behavior

It quietly fails with no indication as to why or what caused it. Observing the logs on both InfluxDB and Telegraf brought us no closer. I will likely monkey-patch a local copy of Telegraf (local build) to use Go's stdlib `fmt.Println(...)` calls to just output _something_ to help us understand more about what is going on - or rather, what isn't.

### Additional info

As mentioned previously, this used to work just fine in 1.27. But due to other requirements, we opted to update the version of Telegraf we used in hopes to incorporate new plugins and features - but were now met with this. Veeam is a cruicial part of what we monitor here, and not having it reliably return information is a bit of a problem... Aside from wrapping the VBR Cmdlets in scripts and producing JSON out of it which can be parsed and understood by Telegraf, we hadn't found a better alternative. So, we rely on `inputs.exec` for the various information from this instead. It also gives us flexibility in perhaps adding other metadata from other Cmdlet calls in the future if we need or want to.
