### ISSUE TITLE
status_code field for kibana inputs plugin not correct in 8.15.2 version of kibana

### ISSUE THREAD

**Issue by krpt** [influxdata/telegraf#17250]
### Relevant telegraf.conf

```toml
# # Read status information from one or more Kibana servers
[[inputs.kibana]]
#   ## Specify a list of one or more Kibana servers
   servers = ["https://xxx:5601"]
#
#   ## Timeout for HTTP requests
#   timeout = "5s"
#
#   ## HTTP Basic Auth credentials
#
#   ## Optional TLS Config
#   ## Use TLS but skip chain & host verification
#   # insecure_skip_verify = false
```

### Logs from Telegraf

```text
>kibana,appli=kibana,cluster=prd,env=prd,host=xxx,name=xxx,os=linux,projet=elk,source=xxx:5601,version=8.15.2 concurrent_connections=1i,heap_max_bytes=505769984i,heap_size_limit=2197815296i,heap_total_bytes=505769984i,heap_used_bytes=411445984i,requests_per_sec=0.4,response_time_avg_ms=6,response_time_max_ms=11i,status_code=0i,uptime_ms=1039853908i 1751014604000000000
```

### System info

Kibana 8.15.2  Telegraf 1.24 Rhel 9.5

### Steps to reproduce

Kibana 8.15.2 seems to not output the same json on the endpoint "api/status"

I don't find anymore a status.overall.state, instead there's a status.overall.level : available, degraded, unavailable, or critical

As the plugin doesn't find the json field it outputs the generic 'Unknown' , 0 value in the field status_code

I hope the issue is clear enough

### Expected behavior

status_code field relevant 

### Actual behavior

status_code always 0
