### ISSUE TITLE
SNMP plugin mapping

### ISSUE THREAD

**Issue by mattbakerau** [influxdata/telegraf#1729]
I have started using the new Telegraf SNMP plugin, and so far working really well but I have hit an issue that I am trying to either work around or see if could get a fix for?

I am using the mib cbgpPeer2Table to get BGP session information from a Cisco router.  Most of the stats are collected fine, but the number of prefixes for each peer is kept in a seleparate table with a suffix on the mapping.

For example if I snmpwalk cbgpPeer2RemoteIdentifier I see:

```
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.12.1.4.192.168.0.1 = IpAddress: 119.168.0.1
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.12.1.4.192.168.0.2 = IpAddress: 119.168.0.2
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.12.1.4.192.168.0.4 = IpAddress: 119.168.0.4
```

If I then fetch cbgpPeer2State I get:

```
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.3.1.4.192.168.0.1 = INTEGER: 6
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.3.1.4.192.168.0.2 = INTEGER: 6
SNMPv2-SMI::enterprises.9.9.187.1.2.5.1.3.1.4.192.168.0.4 = INTEGER: 6
```

To collect this I use the following telegraf config works and it works as expected:

```toml
[[inputs.snmp.table]]
 name = "BGP"
 inherit_tags = [ "hostname" ]
   [[inputs.snmp.table.field]]
     name = "remoteAS"
     oid = ".1.3.6.1.4.1.9.9.187.1.2.5.1.11"
     is_tag = true

   [[inputs.snmp.table.field]]
     name = "remoteID"
     oid = ".1.3.6.1.4.1.9.9.187.1.2.5.1.12"
     is_tag = true

   [[inputs.snmp.table.field]]
     name = "state"
     oid = ".1.3.6.1.4.1.9.9.187.1.2.5.1.3"
```

My problem occurs when I try to include data from cbgpPeer2AcceptedPrefixes. The results from an snmpwalk looks like:

```
SNMPv2-SMI::enterprises.9.9.187.1.2.8.1.1.1.4.192.168.0.1.1.1 = Counter32: 0
SNMPv2-SMI::enterprises.9.9.187.1.2.8.1.1.1.4.192.168.0.2.1.1 = Counter32: 15464
SNMPv2-SMI::enterprises.9.9.187.1.2.8.1.1.1.4.192.168.0.4.1.1 = Counter32: 11
```

As you can see there is a suffix of ".1.1" on these results, so telegraf is just ignoring the entries as they don't match any tag.

Is there some way to work around this, maybe applying either a "map" or somehow specify a suffix?
