### ISSUE TITLE
SNMP plugin IF-MIB::ifTable physical interface problem

### ISSUE THREAD

**Issue by mnctech** [influxdata/telegraf#1755]
## Bug report

Utilizing the new (and old) SNMP plugin for IF-MIB::ifTable there is an issue where the physaddress is being returned via SNMP correctly but Telegraf is turning it into characters before outputting it. 

### Relevant telegraf.conf:

```toml
[[inputs.snmp]]
  agents = [ "172.16.1.13" ]
  version = 2
  community = "public"
  interval = "10s"
  timeout = "10s"

  name = "pts_stats"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "ifTable"
    oid = "IF-MIB::ifPhysAddress.1"
```

### System info:
ubuntu 16.04 desktop with Telegraf 1.0 and the new SNMP plugin

### telegraf output
interface_stats,agent_host=172.16.1.13,host=Dell210,hostname=unnamed ifTable="�>" 1473690400000000000

### tcpdump of SNMP response
10:33:00.000413 IP 172.16.3.13.50536 > 172.16.1.13.161:  GetRequest(28)  .1.3.6.1.2.1.1.5.0
10:33:00.043629 IP 172.16.1.13.161 > 172.16.3.13.50536:  GetResponse(51)  .1.3.6.1.2.1.1.5.0="development-server"
10:33:00.043877 IP 172.16.3.13.50536 > 172.16.1.13.161:  GetRequest(30)  .1.3.6.1.2.1.2.2.1.6.1
10:33:00.082439 IP 172.16.1.13.161 > 172.16.3.13.50536:  GetResponse(36)  .1.3.6.1.2.1.2.2.1.6.1=fa_16_3e_ee_85_8c
