### ISSUE TITLE
Routing metrics by plugin

### ISSUE THREAD

**Issue by joakimberglund** [influxdata/telegraf#1778]
## Feature Request

Add the possibility to select which inputs a certain output should use.
### Proposal:

```
[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "DB1"
  inputs = [ "exec" ]

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "DB2"
  inputs = [ "mem", "cpu" ]
```

And/or.....

```
[[outputs.influxdb]]
  name ="output1"
  urls = ["http://localhost:8086"]
  database = "linux"

[[inputs.cpu]]
  output = ["output1", "output2"]
  percpu = false
  totalcpu = true
```

Default should be that it behaves as it does today.
### Current behavior:

Not possible
### Use case: [Why is this important (helps with prioritizing requests)]

Using the namepass/fieldpass/tagpass is not flexible enough especially when using the exec och httpjson inputs where the name can change or contain multiple names which might collide namewise with other inputs.

Also supporting dividing up the measurements in different databases so that 1) it's easier to scale influxdb instanses 2) get better performance and 3) easier for users to design dashboards

**Comment by sparrc** [comment]
this would be a nice feature to have, but it's actually quite a tricky problem. Internally all plugins are placed in lists and there is no way to differentiate between two different `[[outputs.influxdb]]` output instances.

FWIW, the 2 current best workarounds are:

1. use name_override, name_suffix, or name_prefix config options to prepend names to your measurements on the input-side, then use namepass to filter output-side.
```toml
[[inputs.exec]]
  # ...
  name_prefix = "exec1_"

[[inputs.exec]]
  # ...
  name_prefix = "exec2_"

# this influxdb will only get exec1
[[outputs.influxdb]]
  # ...
  namepass = "exec1_*"

# this will only get exec2
[[outputs.influxdb]]
  # ...
  namepass = "exec2_*"
```
2. run multiple telegraf processes.
