### ISSUE TITLE
Telegraf issues with Windows multi instance processes

### ISSUE THREAD

**Issue by willemdh** [influxdata/telegraf#1827]
## Bug report

I noticed in Grafana that some Windows process % Processor Time was incorrect on one server for one process. The process is called UserMonitor showed as using 100 % CPU for almost all the time. 

![image](https://cloud.githubusercontent.com/assets/6462991/18956830/260fcc64-865d-11e6-85f6-111dbeeaa0e5.png)

Doublechecking the perfmon on the Windows Server showed that this process was actually only using +- 8 % CPU.

![image](https://cloud.githubusercontent.com/assets/6462991/18956843/3595d174-865d-11e6-9278-47ec02de33cf.png)

The config in Grafana:

![image](https://cloud.githubusercontent.com/assets/6462991/18956867/50b509ac-865d-11e6-9da1-d96755ec3572.png)

And a query qhowing the UserMonitor process data coming in as 100%:

![image](https://cloud.githubusercontent.com/assets/6462991/18957096/10862c66-865e-11e6-80c3-56339232ca33.png)
### Relevant telegraf.conf:

```
  [[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    Counters = ["% Processor Time","Pool Nonpaged Bytes","Pool Paged Bytes","Working Set - Private"]
    Instances = ["*"]
    Measurement = "win_processes"
    IncludeTotal=true
```
### System info:

Telegraf 1.0.0
Windows Server 2012 R2

**Comment by willemdh** [comment]
I'm seeing more abnormal Windows process results. One of my colleagues pointed out for example that Telegraf.exe was using more then 10 % CPU on some servers in Grafana. I doublechecked this on the server and it was only using 1 % CPU.
Is someone able to reproduce these issues?

**Comment by francoishill** [comment]
When there are multiple of the same processes it seems to only pick one of them, my config is also as follows:

```toml
  [[inputs.win_perf_counters.object]]
    # Process metrics, in this case for IIS only
    ObjectName = "Process"
    Counters = ["% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set"]
    # Instances = ["gitkraken"]
    Instances = ["*"]
    Measurement = "win_proc"
    IncludeTotal=true
```
