### ISSUE TITLE
CSV data input format (for use with exec, tail)

### ISSUE THREAD

**Issue by stanch** [influxdata/telegraf#2108]
It would be great to have CSV among the supported data input formats. In particular, this allows to leverage the `tail` plugin to integrate with existing tools outputting CSV, instead of e.g. using a named pipe (see also: https://github.com/influxdata/telegraf/issues/2089) as an adapter.

According to the [input format documentation](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md), there are four components that need to be extracted:
> 1. Measurement Name
> 2. Tags
> 3. Fields
> 4. Timestamp

Here is the suggested configuration format that allows to map those to CSV columns:
```toml
# The new data format
data_format = "csv"
data_separator = ","
data_quote_char = "\""

# List of column names in the CSV, in order of appearance on each line
data_columns = [
  "ts",
  "system_id",
  "client_id",
  "request_type",
  "latency"
]

# The column containing the measurement name
name_column = "request_type"

# The column containing the timestamp
timestamp_column = "ts"

# List of columns containing tags
tag_columns = [
  "system_id",
  "client_id"
]

# List of columns containing fields
field_columns = [
  "latency"
]
```
