### ISSUE TITLE
The http_reponse_code of a http request in the http_reponse plugin should be a tag

### ISSUE THREAD

**Issue by tevjef** [influxdata/telegraf#2129]
## Feature Request

Status Code of a http request in the http_reponse plugin should be a tag.

### Proposal:

```
The HTTP response code of the request

This item has a defined cardinality of, at the very max, several dozen (even though most
applications only use a handful). This value also has no need for math and does not need
to be typed, so we will store this in InfluxDB as a tag.
``` 
excerpt from [InfluxDB Performance Tuning Tips](https://www.influxdata.com/technical-papers/influxdb-performance-tuning-tips/) teechnical paper.

### Current behavior:

`http_reponse_code` is currently a field and cannot used performatively in GROUP BY and WHERE clauses

### Desired behavior:

`http_reponse_code` should be a tag.

### Use case:

- This would be useful when we want to count the number of non 200 requests. 
- When needing to use inequality operator to return data for all `http_reponse_code >= 400 AND http_reponse_code < 500`

**Comment by tevjef** [comment]
I see the usefulness of a feature to promote tags -> fields and fields -> tags. This would all users to have more power over the builtin plugins. For example, `exec` has the `json` format but you cannot, at a higher level, define tag keys. 

In the case here where changing `http_reponse_code` to a tag could potentially break many users configs, promoting a field to tag could be a nice bandaid over the problem.

```toml
[[inputs.http_response]]
  address = "http://google.com"
  [inputs.http_response.tags]
    field_override = ["http_reponse_code"]
   # maybe even support regex
    field_regex = ["allmytags.*"]
  [inputs.http_response.fields]
    tag_override = ["some_field"]
```
