### ISSUE TITLE
Docker plugin doesn't log correctly CPU and Mem per container

### ISSUE THREAD

**Issue by mvaude** [influxdata/telegraf#2182]
### Relevant telegraf.conf:

```toml
# Read metrics about docker containers
[[inputs.docker]]
  ## Docker Endpoint
  ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
  ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"
  ## Only collect metrics for these containers, collect all if empty
  container_names = []
  ## Timeout for docker list, info, and stats commands
  timeout = "5s"

  ## Whether to report for each container per-device blkio (8:0, 8:1...) and
  ## network (eth0, eth1, ...) stats or not
  perdevice = true
  ## Whether to report for each container total blkio and network stats or not
  total = false
```

### System info:

- `Telegraf v1.1.1 (git: release-1.1.0 94de9dca1fc6efb3a4bf3ec6869c356278c6755a)`
- `Linux version 3.14.28-031428-generic (apw@tangerine) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #201501081937 SMP Thu Jan 8 19:39:13 UTC 2015`
- (circle CI container)

### Steps to reproduce:

1. run telegraf with docker input plugin in circle CI
2. run computation tasks in some containers
3. analyze output in influxdb (ex: through chronograf)

#### Query Example

```
SELECT "usage_percent" FROM "metrics"."autogen"."docker_container_cpu" WHERE time > now() - 30m GROUP BY "host", "container_name"
```

#### Expected result

- Values variation regarding containers activities.

### Actual behavior:

- Static values: 0

### Use case:

- Running telegraf locally or inside CI to be able to gather some metrics from each run.
