### ISSUE TITLE
Docker metrics to influxdb not being sent when running from ansible

### ISSUE THREAD

**Issue by rashtisouciance** [influxdata/telegraf#2273]
I have an ansible playbook which based on a role installs and runs telegraf.

Most of the input plugins work correctly. However the docker plugin does not seem send anything to influxdb. When I go to grafana the fields are not there. If I run telegraf on the server after the play has finished and run telegraf as sudo then it works. So it seems to be some sort of permission thing?

Here is the core part of the play. Is there anything obvious I need to change or?

```
- name: telegraf configure
  hosts: "tag_integration_{{ test_environment_name }}"
  remote_user: ec2-user
  become: yes
  become_method: sudo
  
  gather_facts: true
  roles:
    - role: dj-wasabi.telegraf
      become: yes
      become_method: sudo
      telegraf_plugins_default:
        - plugin: cpu
          config:
          - percpu = true
        - plugin: disk
        - plugin: io
        - plugin: mem
        - plugin: system
        - plugin: swap
        - plugin: netstat
        - plugin: processes
        - plugin: net
          config:
          - interfaces = ["eth0"]
        - plugin: docker
          config:
          - endpoint = "unix:///var/run/docker.sock"
```

This is the telegraf.conf that is being generated.

```
[tags]

# Configuration for telegraf agent
[agent]
    interval = "30s"
    debug = false
    hostname = "dsfsdf"
    round_interval = false
    flush_interval = "30s"
    flush_jitter = "15s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    logfile = ""
    omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.influxdb]]
    urls = ["http://dsfsdfs:8086"]
    database = "telegraf"

###############################################################################
#                                  INPUTS                                     #
###############################################################################

[[inputs.cpu]]
    percpu = true
[[inputs.disk]]
[[inputs.io]]
[[inputs.mem]]
[[inputs.system]]
[[inputs.swap]]
[[inputs.netstat]]
[[inputs.processes]]
[[inputs.net]]
    interfaces = ["eth0"]
[[inputs.docker]]
    endpoint = "unix:///var/run/docker.sock"
```
