### ISSUE TITLE
mongodb input plugin failed to load when SSL authentication required

### ISSUE THREAD

**Issue by ankitjain2** [influxdata/telegraf#2519]
Hi,
I am trying to use mongodb input plugin. My mongodb needs ssl authentication, so I am using following command to connect to mongodb : 
./mongo --ssl --sslAllowInvalidCertificates     OR
./mongo --ssl --sslCAFile /data/mongo/certs/mongoCA.pem 

### **telegraf mongodb input plugin used :** 

[[inputs.mongodb]]
servers = ["127.0.0.1:27017"]
gather_perdb_stats = false
[ssl]
  enabled = true
  cacerts = ["/data/mongo/certs/mongoCA.pem"]

### **System info:**
Telegraf v1.2.1 (git: release-1.2 3b6ffb344e5c03c1595d862282a6823ecb438cff)
OS : CentOS

### **Steps to reproduce:**

1. add mongo_db.conf file with telegraf input plugin under ../telegraf.d/mongo_db.conf
2. run telegraf test 
/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d/mongo_db.conf --test

### Actual behavior: It throws an ERROR 
**2017/03/08 23:28:45 E! Error parsing /etc/telegraf/telegraf.d/mongo_db.conf, Undefined but requested input: ssl**

My mongodb needs ssl authentication. Can someone also post the example or test for ssl authentication with the mongo plugin.

**Comment by danielnelson** [comment]
Does this work?  Let me know and I'll update the documentation.
```toml
[[inputs.mongodb]]
  servers = ["mongodb://127.0.0.1:27017"]
  gather_perdb_stats = false
  [inputs.mongodb.ssl]
  enabled = true
  cacerts = ["/data/mongo/certs/mongoCA.pem"]
```
