### ISSUE TITLE
custom tags are not per input instance

### ISSUE THREAD

**Issue by lucadistefano** [influxdata/telegraf#2535]
## Feature Request
Assign a custom tag for each input plugin instance.
Actually you can add custom tags only per plugin class

For instance in the case of win_perf_counters could be very useful because the ObjectName often contains the application instance name and this info should be traced in a separate tag (as per influxdb guidelines)
Example:
\SQLServer$PROD:Memory Manager\Total Server Memory (KB)

		ObjectName = "SQLServer$PROD:Memory Manager"
		Counters = ["Total Server Memory (KB)"]
		Instances = ["-----"]
		Measurement = "sqlserver"
		[inputs.win_perf_counters.object.tags]
		      application_instance = "PROD"
			parent_instance = "SQLServer"
SQLServer
actually in influx the tag added by the plugin is objectname="SQLServer$PROD:Memory Manager" but it is a compund of 3 infos: the application instance the 'parent' and the performance counter objectname

The custom tag per plugin instance could be a useful mechanism for all plugins.

### Relevant telegraf.conf:
```toml
[[inputs.win_perf_counters]]
	[[inputs.win_perf_counters.object]]
		ObjectName = "Process"
		Counters = ["Handle Count"]
		Instances = ["telegraf"]
		Measurement = "win_proc"

	[[inputs.win_perf_counters.object]]
		ObjectName = "Process"
		Counters = ["Handle Count"]
		Instances = ["nsi"]
		Measurement = "win_proc"
		  
	[[inputs.win_perf_counters.object]]
		ObjectName = "Process"
		Counters = ["Handle Count"]
		Instances = ["csrss"]
		Measurement = "win_proc0"
	 [inputs.win_perf_counters.object.tags]
		  application_instance = "ZZZ"
	  
	[[inputs.win_perf_counters.object]]
	   ObjectName = "Process"
	   Counters = ["IO Data Operations/sec"]
	   Instances = ["_Total"]
	   Measurement = "win_proc1"
      
	[[inputs.win_perf_counters.object]]
	   ObjectName = "Process"
	   Counters = ["IO Data Operations/sec"]
	   Instances = ["*"]
	   Measurement = "win_proc2"
```
### System info:
windows server 2012R2
telegraf win 64 bit 1.2.1

### Steps to reproduce:
use the inputs of above for put data in influxdb

### Expected behavior:
only data for process instance csrss in measurement win_proc0 should have additional tag  application_instance = "ZZZ"

### Actual behavior:
all metrics of plugin inputs.win_perf_counters in all measurements contains additional tag
application_instance = "ZZZ"

Thanks
