### ISSUE TITLE
The httpjson input is documented incorrectly.

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2536]
## Bug report

The documented format for the httpjson input does match the actual format.

### Relevant telegraf.conf:
```toml
[[inputs.httpjson]]
  name = "mycollector"
  servers = [
    "http://localhost:8080/_stats",
  ]
  response_timeout = "5s"
  method = "GET"
  tag_keys = ["service"]
```

### System info:
$ telegraf version
Telegraf vdev-85-g7a5d8578 (git: master 7a5d8578)

### Steps to reproduce:

1. Setup server for metrics
```
$ curl localhost:8080/_stats
{
        "service": "service01",
        "a": 0.5,
        "b": {
                    "c": "some text",
                    "d": 0.1,
                    "e": 5
                }
}
```
2. Run telegraf

### Expected behavior:
According to the documentation, I should have:
```
httpjson_mycollector_a,service='service01',server='http://localhost:8080/_stats' value=0.5
httpjson_mycollector_b_d,service='service01',server='http://localhost:8080/_stats' value=0.1
httpjson_mycollector_b_e,service='service01',server='http://localhost:8080/_stats' value=5
```

### Actual behavior:
```
httpjson_mycollector,server=http://localhost:8080/_stats,service=service01,host=loaner b_d=0.1,b_e=5,response_time=0.005005947,a=0.5 1489606940000000000
```
