### ISSUE TITLE
MySQL input plugin no longer reporting metrics for slave replication

### ISSUE THREAD

**Issue by m4ce** [influxdata/telegraf#2836]
Today, one MySQL slave instance stopped replicating due to a network glitch.

```
*************************** 1. row ***************************                                                                                                                                    [353/9644]
               Slave_IO_State: Connecting to master
                  Master_Host: db01
                  Master_User: repl
                  Master_Port: 3306
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000417
          Read_Master_Log_Pos: 120
               Relay_Log_File: mysql-relay-log.000835
                Relay_Log_Pos: 4
        Relay_Master_Log_File: mysql-bin.000417
             Slave_IO_Running: Connecting
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table: data.%
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 120
              Relay_Log_Space: 120
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: NULL
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 2005
                Last_IO_Error: error connecting to master 'repl@db01:3306' - retry-time: 60  retries: 1
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 0
                  Master_UUID: b30c58d4-4d1c-11e6-89b1-000c29d1da9b
             Master_Info_File: /var/lib/mysql/master.info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for the slave I/O thread to update it
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp: 170520 15:36:30
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
1 row in set (0.00 sec)
```

Telegraf reported the following errors:

```
2017-05-20T14:35:09Z E! Error in plugin [inputs.mysql]: strconv.ParseInt: parsing "18446744073709547936": value out of range
2017-05-20T14:36:09Z E! Error in plugin [inputs.mysql]: strconv.ParseInt: parsing "18446744073709547996": value out of range
2017-05-20T14:37:09Z E! Error in plugin [inputs.mysql]: strconv.ParseInt: parsing "18446744073709548056": value out of range
2017-05-20T14:38:09Z E! Error in plugin [inputs.mysql]: strconv.ParseInt: parsing "18446744073709548116": value out of range
2017-05-20T14:39:09Z E! Error in plugin [inputs.mysql]: strconv.ParseInt: parsing "18446744073709548176": value out of range
```

However, no slave information would be sent to Influx. As a result, our monitoring wasn't detecting the issue since we monitor the status of Slave_IO_Running and Slave_SQL_Running.

Telegraf version: 1.3.0
