### ISSUE TITLE
Cannot create influx database containing hyphen

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#2850]
## Bug report

InfluxQL databases containing a hyphen cannot be created.

### Relevant telegraf.conf:
```toml
[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = 'telegraf-mssql'
```

### System info:

Telegraf 1.3.0

### Steps to reproduce:

1. Start telegraf with above config

### Expected behavior:
No errors and database created

### Actual behavior:
```
Database creation failed: Response Error: Status Code [400], expected [200], [error parsing query: found -, expected ; at line 1, char 25]
```
