### ISSUE TITLE
Problems using UDP influxdb output

### ISSUE THREAD

**Issue by mcfedr** [influxdata/telegraf#2862]
Looks like telegraf is splitting a udp message and this means its not getter parsed properly by influxdb.

This has started happening since update to telegraf 1.3

### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
  urls = ["udp://influxdb:8089"]
  database = "telegraf"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s

[[inputs.system]]
```

### System info:

Telegraf 1.3 docker image
Influxdb 1.2 docker image

### Log message

```
influxdb_1    | [I] 2017-05-29T09:25:00Z Failed to parse points: unable to parse 'system,host=proxy-docker uptime_format="5 days 1496049900000000000': unbalanced quotes service=udp
influxdb_1    | [I] 2017-05-29T09:25:00Z Failed to parse points: unable to parse 'system,host=proxy-docker   1:26" 1496049900000000000': invalid field format service=udp
```
