### ISSUE TITLE
Telegraf trims quotes from string fields but not tags in logparser

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3092]
## Bug report

If a string is captured with quotes, such as with the `%{QS}` pattern,
logparser will trim the outside quotes if it is a [field](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/logparser/grok/grok.go#L254) but not if it is a [tag](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/logparser/grok/grok.go#L252).

This results in inconsistent behavior.

### Relevant telegraf.conf:

```toml
[[inputs.logparser]]
  files = ["simple.log"]
  from_beginning = true
  [inputs.logparser.grok]
    patterns = ["%{QS:a:tag} %{QS:b}"]
    measurement = "test"
```

```
$ cat simple.log
"foo" "bar"
```

### System info:

360d03e3

### Steps to reproduce:

1. Run logparser with the above config and input file

### Expected behavior:

`test,a=foo b="bar"`
or
`test,a=\"foo\" b="\"bar\""`

### Actual behavior:

`test,a=\"foo\" b="bar"`

### Additional info:

https://community.influxdata.com/t/telegraf-qs-for-log-parser-input-behavior/1889/3
