### ISSUE TITLE
Address already in use with webhooks input during reload

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3136]
## Bug report

If you send Telegraf a SIGHUP when using the webhooks input, an error is emitted.  Most likely the webhook server is not restarted.

### Relevant telegraf.conf:
```toml
[[inputs.webhooks]]
  service_address = ":1619"
  [inputs.webhooks.github]
    path = "/github"
```

### System info:

Telegraf v1.5.0~pre3006ccbf (git: master 3006ccbf)

### Steps to reproduce:

1. Start Telegraf with webhooks input
2. `pkill -HUP telegraf`

### Expected behavior:

Webhooks server restarted

### Actual behavior:
```
2017-08-18T01:45:44Z E! Error in plugin [inputs.webhooks]: E! Error starting server: listen tcp :1619: bind: address already in use
```
