### ISSUE TITLE
Add input that accepts all input data formats using HTTP

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3226]
## Feature Request

The current `http_listener` input only accepts influx data format and attempts to behave like an InfluxDB server with respect to parsing, paths, headers, etc.

### Proposal:

Add a plugin alias for the current http_listener plugin: `influxdb_listener`, at some point in the future we remove the old http_listener.

Create a new input from scratch called `http_listener_ng`, or a good name if anyone has ideas.  The initial configuration could look something like:

```toml
[[inputs.http_listener_ng]]
  address = ":8186"

  paths = ["/telegraf"]
  methods = ["POST", "PUT"]

  read_timeout = "10s"
  write_timeout = "10s"

  tls_cert= "/etc/telegraf/server/cert.pem"
  tls_key = "/etc/telegraf/server/key.pem"
  tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]

  data_format = "influx"
```

### Current behavior:

No plugin exists that accepts the input data formats over HTTP.

### Desired behavior:

Plugin exists.

### Use case: [Why is this important (helps with prioritizing requests)]

Allows pushing application metrics to Telegraf over http in any format.

This is commonly needed:
- https://github.com/influxdata/telegraf/pull/3216
- https://community.influxdata.com/t/json-http-plugin-es/2313
