### ISSUE TITLE
How to add a static tag or field and value to  inputs.snmp

### ISSUE THREAD

**Issue by wade-lich** [influxdata/telegraf#3279]
I am trying to find a way to define my data centers in my configuration for inputs.snmp.

I have devices that are the same in two DC A/B.  I want to have either a field or tag I can reference as a filter in my select statements in Grafana.  Is this possible?

e.g.

[[inputs.snmp.tags]]
  dc = "A"

This example I feel is less likely.

[[inputs.snmp.field]]
  name = "DataCenter"
  value = "B"

If I can't do it in this manner, is there a way around it?

Regards,
  Wade

**Comment by danielnelson** [comment]
You can add static tags like:
```toml
[[inputs.snmp]]
  # other stuff
  [inputs.snmp.tags]
    site=“EZE”
```
Make sure you put the table after any options to the plugin.

You can't add static fields, although there is an issue open to allow this #2564

All that said it might be better to use a snmp field:
```toml
[[inputs.snmp]]
  # other stuff
  [[inputs.snmp.field]]
    name = "sys_name"
	oid = "SNMPv2-MIB::sysName.0"
	is_tag = true
```
