### ISSUE TITLE
Add ability to limit stats in the basicstats aggregator

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3413]
## Feature Request

Option to limit the new values to a single calculation (stdv or median or all)

Requested in #3402 by @xkilian

### Proposal:

Add method to select which statistics are collected, perhaps:
```toml
[[aggregators.basicstats]]
  stats = ["stdev", "s2"]
```

### Current behavior:

Must generate all stats.

Due to the way measurement filtering works with processors/aggregators, you cannot use the filtering option to limit the output.  This is because filtering applies to the metrics that enter the plugin, but not to the output.  Unlike inputs/outputs, these plugins really need two sets of filters.

### Desired behavior:

A method for limiting the output.

### Use case: [Why is this important (helps with prioritizing requests)]

This will make the new aggregator much more flexible for hosts that generate lots of metrics.

**Comment by JeffAshton** [comment]
I'd be interested in implementing this functionality.  I'd like to amend the proposal to allow configuration  per field.  For example, one field I might want Min/Max computed, and another field I might just want the mean computed.

A default configuration for non matched fields makes sense to me.

**Comment by danielnelson** [comment]
Thanks for the offer @JeffAshton, the first step I would take is to design the configuration.

I'll also mention a workaround for this issue, you can use the standard [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) on the output plugins to remove stats you don't want.

**Comment by JeffAshton** [comment]
@danielnelson ,  I've send you a PR for the first part.  I'll look at adding the field specific stuff as a separate PR.

**Comment by danielnelson** [comment]
Maybe we can do something similar to how the histogram aggregator is configured, here is an example of how it looks:
```toml
[[aggregators.histogram]]
  [[aggregators.histogram.config]]
  #   ## The set of buckets.
  buckets = [0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0]
  #   ## The name of metric.
  measurement_name = "diskio"
  #   ## The concrete fields of metric
  fields = ["io_time", "read_time", "write_time"]
```

So fields is a list, and you can specify the measurement name (actually you must set this in the histogram aggregator) which might be useful for conflicts.
