### ISSUE TITLE
Set measurement name based on matched pattern in logparser

### ISSUE THREAD

**Issue by botzill** [influxdata/telegraf#3484]
Hi.

Seems to not be possible to define smth like this? Can we somehow define it without redefining the hole ``[[inputs.logparser]]`` again?

```
[[inputs.logparser]]
  files = ["/var/log/supervisor/app.log"]
  from_beginning = false
  watch_method = "poll"
  [inputs.logparser.grok]
    measurement = "measurement_1"
    custom_pattern_files = ["..."]
    patterns = ["..."]
  [inputs.logparser.grok]
    measurement = "measurement_2"
    custom_pattern_files = ["..."]
    patterns = ["..."]
  [inputs.logparser.tags]
    app = "tag1"

```

**Comment by danielnelson** [comment]
The best you can do is to have a multiple patterns:
```toml
[[inputs.logparser]]
  files = ["/var/log/supervisor/app.log"]
  from_beginning = false
  watch_method = "poll"
  [inputs.logparser.grok]
    patterns = [
      "pattern1",
      "pattern2"
    ]
    custom_pattern_files = [
	  "CP1 ...",
	  "CP2 ..."
    ]
```

Once you have that working you may also want to combine your patterns for increased performance:
```toml
[[inputs.logparser]]
  files = ["/var/log/supervisor/app.log"]
  from_beginning = false
  watch_method = "poll"
  [inputs.logparser.grok]
    patterns = [
      "%{PATTERN1}|%{PATTERN2}"
    ]
    custom_pattern_files = [
      "PATTERN1 ...",
      "PATTERN2 ...",
	  "CP1 ...",
	  "CP2 ..."
    ]
```

Unfortunately you won't be able to name the measurements differently.
