### ISSUE TITLE
Log warning if a metric is added with no fields

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3685]
## Bug report

Plugins allowing flexible creation of metrics may result in a metric with no fields, currently this metric is ignored and no warning is produced.

### Relevant telegraf.conf:

This is just one possible config, I have not done a full investigation but I assume something similar could be done with plugins like `postgresql_extensible` or `httpjson`.

```toml
[[inputs.snmp]]
agents = [ "switchname.example.com" ]
version = 2
community = "public"

name = "snmp"
[[inputs.snmp.field]]
name = "sysName"
oid = "1.3.6.1.2.1.1.5.0"
is_tag = true
```

### System info:

Telegraf 1.5.1

### Steps to reproduce:

1. Use config above
2. `telegraf --test`

### Expected behavior:

A warning that a metric was added with no fields

### Actual behavior:

No warning
