### ISSUE TITLE
Tomcat input does not add a tag based on connection url

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#3780]
## Bug report

Since no tag is added, you use multiple copies of the plugin without manually adding a tag.

### System info:

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. Configure multiple tomcat inputs
2. telegraf --input-filter tomcat --test

### Expected behavior:

```
tomcat_jvm_memory,url=http://foo:8080/manager/status/all?XML\=true free=17895344i,total=39092224i,max=508952576i 1518213238000000000
```

### Actual behavior:

```
tomcat_jvm_memory free=17895344i,total=39092224i,max=508952576i 1518213238000000000
```

### Additional info:

Workaround is to add the tag manually:
```toml
[[inputs.tomcat]]
 url = "http://foo:8080/manager/status/all?XML=true"
 [inputs.tomcat.tags]
    url = "http://foo:8080/manager/status/all?XML=true"

[[inputs.tomcat]]
 url = "http://bar:8080/manager/status/all?XML=true"
 [inputs.tomcat.tags]
    url = "http://bar:8080/manager/status/all?XML=true"
```
