### ISSUE TITLE
Add an input plugin for jenkins "Global Build Stats"

### ISSUE THREAD

**Issue by fchiorascu** [influxdata/telegraf#3791]
New Feature:

Kindly is possible to have:
1\. Input plugins: [[inputs.jenkins]] ?
2\. This oprion it seems that already exists. InfluxDB plugin: https://plugins.jenkins.io/influxdb

The second option I think is more reliable, but for 1\. will be developed something in future?

Kind Regards,

**Comment by danielnelson** [comment]
This would be nice, we also have a pull request open for a plugin to monitor Jenkins itself: https://github.com/influxdata/telegraf/pull/3292

**Comment by lpic10** [comment]
I have something working with that already internally. It makes use of [gojenkins](https://github.com/bndr/gojenkins) that uses only Jenkins API (so no need to install a jenkins plugin) to retrieve jobs data (job name, id, duration, result) and some monitoring info from the nodes like memory, swap and disk space. 

I'm my internal fork I call this input plugin "jenkins", but I see there are #3292 that uses this name as well.

If you are interested I can do some cleaning and open a PR, but I'd need to rename it.

**Comment by danielnelson** [comment]
Searching for metrics at https://plugins.jenkins.io/, it seems there are quite a few options.  It should already be possible to use the influxdb plugin sending to http_listener, the prometheus exporter, the graphite plugin, etc.  It should also be possible to replicate #3292 now in master by using the http input with the dropwizard parser.

Perhaps it's not worth creating more code for this considering there are so many possible integration points?

I do see a big advantage to your design @lpic10, since you wouldn't need to add any plugins.  Can you post the output of `telegraf --input-filter jenkins --test`?

**Comment by fchiorascu** [comment]
I think will be great to have:
- [[inputs.jenkins]]
- and also to monitor jenkins itself.

Kind Regards,

**Comment by lpic10** [comment]
@danielnelson , see below from an initial readme I wrote. 

There are 2 important details:

The jenkins API is not very efficient, so to gather all this data a lot of http calls are needed (to get a list of jobs, then to get a list of builds for a particular job, then for each build). This can escalate rather quickly depending on the number of jobs and builds in a jenkins instance. That's the reason I implemented two basic filters, one by job name and another one to ignore old builds (as telegraf will be collecting data regularly I don't need to get same data again and again). 

The timestamp of the job build is used instead of the collection time. This works fine with influxDB as it does not duplicate the point, I don't know about other output plugins.

If this interests you or anybody else, let me know, I should be able to create a PR in the coming days.

### Configuration:

```toml
  url = "http://my-jenkins-instance:8080"
  user = "admin"
  passwd = "admin"
  ## Set response_timeout
  response_timeout = "5s"

  ## Optional SSL Config
  # ssl_ca = /path/to/cafile
  # ssl_cert = /path/to/certfile
  # ssl_key = /path/to/keyfile
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false

  ## Job & build filter
  lastbuild_interval = "1h"
  # job_exclude = [ "MyJob", "MyOtherJob" ]
```

### Measurements & Fields:

- jenkins_node
    - disk_available
    - temp_available
    - memory_available
    - memory_total
    - swap_available
    - swap_total
    - response_time
    - online

- jenkins_job
    - duration
    - result_code

### Tags:

- jenkins_node
    - arch
    - disk_path
    - temp_path
    - node_name

- jenkins_job
    - job_name
    - result

### Example Output:

```
$ ./telegraf --config telegraf.conf --input-filter jenkins --test
jenkins_node,arch=Linux\ (amd64),disk_path=/var/jenkins_home,temp_path=/tmp,host=myhost,node_name=master swap_total=4294963200,memory_available=586711040,memory_total=6089498624,online=true,response_time=1000i,disk_available=152392036352,temp_available=152392036352,swap_available=3503263744 1516031535000000000
jenkins_job,host=myhost,job_name=JOB1,result=SUCCESS duration=2831i,result_code=0i 1516026630000000000
jenkins_job,host=myhost,job_name=JOB2,result=SUCCESS duration=2285i,result_code=0i 1516027230000000000
