### ISSUE TITLE
Add ability to monitor size of specific directory on server

### ISSUE THREAD

**Issue by ewillia1983** [influxdata/telegraf#3945]
### Use case:

According to support tickets filed with influxdata, they do not recommend enabling internal monitoring on production clusters.  The main thing you lose in that scenario is the ability to see the data backing up in the hinted handoff queues / directories, which is the easiest way to tell if one of the nodes has fallen behind.

I'd like to be able to ask telegraf to specifically watch the size of /var/lib/influxdb/hh, and then use kapacitor to generate an alert if data starts backing up.

**Comment by danielnelson** [comment]
Seems like a good idea, possibly it could become part of the filestat plugin or a similar plugin.

Have you tried the influxdb input plugin?  You might be able to get the desired info from here though I don't have a clustered InfluxDB in front of me.

I also did try to come up with a workaround with some success, it requires the nightly build (1.6) for the sum operation in basicstats:
```toml
[[inputs.filestat]]
  name_override = "dirstat"
  interval = "10s"
  files = ["/foo/*"]
  tagexclude = ["file"]
  fieldpass = ["size_bytes"]

[[aggregators.basicstats]]
  namepass = "dirstat"
  period = "10s"
  drop_original = true
  stats = ["sum"]
  [[aggregators.basicstats.tags]]
    path = "/foo"
```

There are a few problems, this counts directories as having 4096 bytes and the first result when you start Telegraf is 2x the actual value.
