### ISSUE TITLE
Could you please tell me how to write multiple service url monitoring so that I can only support one?

### ISSUE THREAD

**Issue by zy93xy** [influxdata/telegraf#3952]
Hello, am I configured to support multiple url monitoring?

![image](https://user-images.githubusercontent.com/28784625/38137257-4f7ca970-3456-11e8-83e1-3bc8155258da.png)

![image](https://user-images.githubusercontent.com/28784625/38137218-fe7fc87c-3455-11e8-9e49-acdbcb885c0c.png)

**Comment by danielnelson** [comment]
I'm not sure I understand.  Are you asking about how to gather metrics from multiple jolokia hosts with a single plugin definition?  If the metric definitions are the same you just add multiple urls:
```toml
[[inputs.jolokia2_agent]]
  urls = ["http://a.example.org/jolokia", "http://b.example.org/jolokia"]
```

We try to reserve GitHub Issues for actionable bug reports or feature requests. Please ask general questions at the [InfluxData Community](https://community.influxdata.com) site.
