### ISSUE TITLE
Input: CloudWatch - Partial Wildcard or Regexp support?

### ISSUE THREAD

**Issue by mooyoul** [influxdata/telegraf#4046]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal: 

Support Partial Wildcard (e.g. `*prod*`, like glob) or RegExp support (e.g. `/prod/`) to filter out unwanted metrics

For example, below configuration will pull production metrics only:

Using RegExp:

```toml
[[inputs.cloudwatch]]
  namespace = "AWS/Lambda"
  [[inputs.cloudwatch.metrics]]
    names = ["Invocations", "Errors", "Duration"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "FunctionName"
      value = "/prod/"
```

... or partial wildcard (globbing): 

```toml
[[inputs.cloudwatch]]
  namespace = "AWS/Lambda"
  [[inputs.cloudwatch.metrics]]
    names = ["Invocations", "Errors", "Duration"]
    [[inputs.cloudwatch.metrics.dimensions]]
      name = "FunctionName"
      value = "*prod*"
```

### Current behavior:

There's no easy way to select production-only metrics without specifying them.

### Desired behavior:

Users can filter metrics using Glob or RegExp

### Use case:

Since our architecture of our application is microservices, We have 300+ lambda functions and we have 3 stages (production, staging, development) and number of functions are growing.
We replicate cloudwatch metrics to our InfluxDB using Telegraf with Cloudwatch Input Plugin to detect anomaly metrics (e.g. Latency Spikes). When something goes wrong, we receive alarms from Bosun.

Anyway currently filtering production resources is so hard. everytime we release new "service" to  production, we need to change bunch line in the telegraf configuration to filter non-production metrics.
