### ISSUE TITLE
Filtering metrics in processors.override

### ISSUE THREAD

**Issue by Braynid** [influxdata/telegraf#4075]
## Feature Request
It's hard if not impossible to filter metrics affected by processors.override.

### Current behavior:
Fieldpass is not allowed within processor plugins:
```Error parsing mqtt.conf, fieldpass is not supported for processor plugins (override).```

Tagpass doesn't throw an error but it also doesn't work for processors. I assume usage would be as follows:
```
[processors.override.tagpass]
  tag = ["value"]
```

### Desired behavior:
Have all `Measurement Filters` working under processors.

### Use case: [Why is this important (helps with prioritizing requests)]

It would be helpful to be able to filter metrics within override processors in cases such as mqtt here the topic is added as a tag. In such a case tagpass would help but as mentioned above it doesn't seem to work.

### Telegraf version
Telegraf v1.7.0~74caafc4

**Comment by danielnelson** [comment]
All of the [measurement filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#measurement-filtering) operate only to filter the input of the processor, items which are not matched as passed downstream bypassing the processor.  I tried to describe this in the [processor configuration](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#processor-configuration) docs:

> The measurement filtering parameters can be used to limit what metrics are handled by the processor. Excluded metrics are passed downstream to the next processor.

It's not really obvious how it works, and I needed to look through the code originally to determine how it worked.

I think it would make sense to have support for filtering of emitted metrics from a processor and perhaps a way to make it more intuitive how these operate, perhaps by scoping the filtering options like:
```toml
[[processors.override]]
  [processors.override.filter_input]
    [processors.override.filter_input.tagpass]
      tag = ["foo"]

  [processors.override.filter_output]
    [processors.override.filter_output.tagpass]
      tag = ["bar"]
```

However, the table naming does start to get out of hand with this layout.
