### ISSUE TITLE
Kafka Producer & Consumer - Topic based routing based on criteria specified in an expression

### ISSUE THREAD

**Issue by edbernier** [influxdata/telegraf#4170]
## Feature Request

Proposal:

Wayfair is requesting this capability to enable smarter routing of Kafka traffic to various Topics.
Telegraf Kafka Consumer could then direct the data to different InfluxDB instances based on the Topic.

Below is an example of what this would look like:
We are looking to have  flexible Kafka routing engine for both the Telegraf Kafka consumer and producer.
 
For Kafka Producer…
 
We are looking for something that works sort of like a map data structure (or something like a case statement).  Imagine the following…
 
TOPIC_ROUTES:
    CRITERIA_SET_1:
        TOPIC(S)
    CRITERIA_SET_2:
        TOPIC(S)
    CRITERIA_SET_3:
        TOPIC(S)
    DEFAULT:
         TOPIC(S)
 
NOTE: we want the option of using measurement name or tag based criteria sets.  Note we may want the flexibility of replicating data to more than one topic.
 
For the Kafka Consumer we are looking for a routing scheme that will enable us to specify a specific cluster and DB destination per topic set (not necessarily a v1 feature)
 
                NOTE: HOW CAN WE COMBINE TOPIC AND MEASUREMENT_TAG based filtering?
 
                      DB_ROUTES:
                          TOPIC_AND_MEASUREMENT_TAG_SET_1:
                              DB(s)
                          TOPIC_AND_MEASUREMENT_TAG_SET_1:
                              DB(s)
                           DEFAULT:
                              DB(s)
 
Note we may want the flexibility of replicating data to more than one db (not necessarily a v1 feature)

It would allow Telegraf to direct data to appropriate InfluxDB cluster or instance.  A very powerful feature which will greatly simplify scaling up or segmenting workloads.

**Comment by JimHagan** [comment]
@danielnelson Topic suffix tags do not meet our needs for the Kafka output plugin.  We have tried it and we are looking to have more flexibility as we

1. Cannot always control what tags metrics will contain in them
2. We need a fallback topic which is not supported by the current capability as we cannot guarantee a topic will always exist.

The suggestion for the Kafka input may be workable.  I will look into it.

**Comment by sgtsquiggs** [comment]
@danielnelson your example is invalid (maybe it wasn't at the time?) because tagpass/tagdrop is OR and not AND according to the docs at https://docs.influxdata.com/telegraf/v1.9/administration/configuration/#aggregator-configuration-examples

**Comment by danielnelson** [comment]
Yes that's a good point, the comments should read "must have foo or bar tags"

**Comment by JimHagan** [comment]
I was the originator of the requested use case.  We are going to be posting a pull request at some point soon that has a somewhat generic implementation where we use measurement name regexp as the criteria to drive the mapping to topic name.  @scottgrover Will be working on it for us.

**Comment by danielnelson** [comment]
Sounds good, update us with a sample of what the configuration design could be before getting to deep into implementation.

**Comment by scottgrover** [comment]
Hi there,

After reviewing how the kafka output plugin works, I was thinking about adding the logic Jim and I discussed in the GetTopicName function. 

We want to add something similar to the topic_suffix logic, possibly named topic_routing to avoid any naming confusion. It's possible this could grow to multiple types of routing but we'd like to start out with regex based routing to start.

Here's an example of what the configuration could look like. Let me know your thoughts.  

```toml
[kafka.output.topic_routing]
method = "regex"

[[route]]
# Route measurement names ending in 0-9 to topic1
routeregex = "measurement_\d{1}\b"
topicname = "topic1"


[[route]]
# Route measurement name ending in double digits to topic2
routeregex = "measurement_\d{2}\b"
topicname = "topic2"

[[route]]
# Route measurement name starting with 3 a's to topic3
routeregex = "[a]{3}.*"
topicname = "topic3"

```

Scott

**Comment by danielnelson** [comment]
This type of functionality, routing based on the metric data, is useful in many or even most of the outputs,.  This makes me think that whatever solution we do should be pulled back into the filtering options and/or processors.  I feel the same way about the topic_suffix work from before as well.

In these examples, I notice that the topic is static, so it should be possible to do something today like:
```toml
[[outputs.kafka]]
  topic = "topic1"
  namepass = ["measurement_[0-9]"]
[[outputs.kafka]]
  topic = "topic2"
  namepass = ["measurement_[0-9][0-9]"]
[[outputs.kafka]]
  topic = "topic3"
  namepass = ["aaa*"]
```

Of course these are just examples, and obviously the glob syntax is not as advanced as a regular expressions.  Can you describe some cases where you are routing off of the measurement but globs are not powerful enough?

Generally, I think of the measurement name to be similar to the name of a class or struct, and so it wouldn't have a ton of variation, could you give me some more information on how they are being assigned?
