### ISSUE TITLE
Counter names are always localized

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4257]
### Relevant telegraf.conf:
```toml
[[inputs.win_perf_counters]]
	[[inputs.win_perf_counters.object]]
	ObjectName = "Processor Information"
	Instances = [""]
	Counters = [
		"% Privileged Time",
		"% User Time",
	]
```

### System info:

Telegraf 1.7

### Steps to reproduce:

1. Run win_perf_counters on non-English Windows version

### Expected behavior:

Counters are returned in English

### Actual behavior:

Counters are returned in local language

### Additional info:

#4243
