### ISSUE TITLE
Test more than one port [up or down]

### ISSUE THREAD

**Issue by SongYg** [influxdata/telegraf#4279]
## Test more than one port [up or down] on my server

When I use the Telegraf to test UDP/TCP connections and check my server port status [up or down], I read https://github.com/influxdata/telegraf/tree/release-1.7/plugins/inputs/net_response and I can test one port. But I don't know how to find two ports. I modified the configuration.:
address = ["localhost:80","localhost:22"]

It didn't work. And I read the  net_response.go. And I got that "address" is string. But I still don't know how to test two ports.

### Current behavior:
address = "localhost:80"
### Desired behavior:
It can test more ports

**Comment by danielnelson** [comment]
You can specify the plugin as many times as needed:
```toml
[[inputs.net_response]]
  address = "localhost:80"

[[inputs.net_response]]
  address = "localhost:22"
```
