### ISSUE TITLE
run dep will cause Gopkg.lock file changed

### ISSUE THREAD

**Issue by pytimer** [influxdata/telegraf#4410]
### System info:

- branch: master

### Steps to reproduce:

1. fork telegraf repos
2. git clone fork repository.
3. run `dep ensure -v`

### Expected behavior:

`Gopkg.lock` not changed.

### Actual behavior:

`Gopkg.lock` has changed.

### Additional info:

[Include gist of relevant config, logs, etc.]

original file:
```toml
[[projects]]
  name = "github.com/Microsoft/ApplicationInsights-Go"
  packages = [
    "appinsights",
    "appinsights/contracts"
  ]
  revision = "d2df5d440eda5372f24fcac03839a64d6cb5f7e5"
  version = "v0.4.2"
```

changed file:
```toml
[[projects]]
  branch = "master"
  digest = "1:c1269bfaddefd090935401c291ad5df6c03de605a440e941ecc568e19f0f9e3b"
  name = "github.com/Microsoft/ApplicationInsights-Go"
  packages = [
    "appinsights",
    "appinsights/contracts",
  ]
  pruneopts = ""
  revision = "d2df5d440eda5372f24fcac03839a64d6cb5f7e5"
```

I don't know is this result normal? Is it improperly operated?
