### ISSUE TITLE
inputs.snmp don't get data / snmpwalk get data

### ISSUE THREAD

**Issue by golemiii** [influxdata/telegraf#4486]
### Relevant telegraf.conf:
```toml
[[inputs.snmp]]
agents = [ "raspberrypi" ]
  version = 2
  community = "xxxxxxxxxx"
  interval = "300s"
  timeout = "10s"
  retries = 3
  [[inputs.snmp.table]]
    name = "temperature"
    inherit_tags = [ "hostname" ]
  [[inputs.snmp.table.field]]
    name = "lmTempSensorsDevice"
    oid = "SNMPv2-MIB::sysName"
    is_tag = true
   [[inputs.snmp.table.field]]
    name = "lmTempSensorsValue"
    oid = ".1.3.6.1.2.1.25.1.8"
```
### System info:
host
Telegraf v1.7.1 (git: release-1.7 4be18c1e)
Linux snmp 4.9.0-7-amd64 #1 SMP Debian 4.9.110-1 (2018-07-05) x86_64 GNU/Linux
Client : raspberry
### Steps to reproduce:
1.on client raspberry: snmpd.conf add line
pass .1.3.6.1.2.1.25.1.8 /bin/sh /usr/local/bin/snmp-cpu-temp
2. on telegraf host
2.1 to check network : tcpdump -pni ens3 port 161
2.2 telegraf -config /etc/telegraf/telegraf.d/snmp-pi-sensors.conf -test
-> 2.2.1 empty result output
-> 2.1.1 from tcpdump
12:32:00.966812 IP xxx.xxx.xxx.xxx.xxxx > xxx.xxx.xxx.xx.161:  C="xxxxx" GetRequest(28)  .1.3.6.1.2.1.25.1.8
12:32:00.980380 IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.xxxxx:  C="xxxxxx" GetResponse(31)  .1.3.6.1.2.1.25.1.8=47774
2.3 with snmpwalk -c xxxx -v2c raspberrypi .1.3.6.1.2.1.25.1.8
-> 2.3.1 HOST-RESOURCES-MIB::hrSystem.8 = Gauge32: 48312
-> from tcpdump
12:40:39.218701 IP xxx.xxx.xxx.xxx.xxxxx > xxx.xxx.xxx.xxx.161:  C="xxxxxxxx" GetNextRequest(28)  .1.3.6.1.2.1.25.1.8
12:40:39.220546 IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.xxx:  C="xxxxx" GetResponse(32)  .1.3.6.1.2.1.25.2.2.0=885364
12:40:39.220756 IP xxx.xxx.xxx.xxx.xxxx > xxx.xxx.xxx.xxx.161:  C="xxxxxxx" GetRequest(28)  .1.3.6.1.2.1.25.1.8
12:40:39.234324 IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.xxxx:  C="xxxxxx" GetResponse(31)  .1.3.6.1.2.1.25.1.8=48312
### Expected behavior:
from telegraf -config /etc/telegraf/telegraf.d/snmp-pi-sensors.conf -test, no empty value.
like > temperature,agent_host=raspberrypi,host=snmp,lmTempSensorsDevice=raspberrypi lmTempSensorsValue=90i 1532861137000000000
### Actual behavior:
no output line
### Additional info:
if I use .1.3.6.1.2.1.25.1.6 instead , it's work as exepected.
but .1.3.6.1.2.1.25.1.6 is standard OID instead .1.3.6.1.2.1.25.1.8 is introduce with pass option in snmpd.conf file

**Comment by glinton** [comment]
@golemiii can you paste the output of `telegraf --input-filter=snmp --test`

**Comment by golemiii** [comment]
**result for telegraf --input-filter=snmp --test**
2018/08/01 21:06:03 I! Using config file: /etc/telegraf/telegraf.conf
2018/08/01 21:06:03 E! Error: no inputs found, did you provide a valid config file?

**Comment by golemiii** [comment]
due to this result, I wonder if for your test , we need to precise some snmp config ( define in other config file for me ).
**result for telegraf --input-filter=snmp -config /etc/telegraf/telegraf.d/snmp-pi-sensors.conf --test**
empty result

**Comment by danielnelson** [comment]
@golemiii Can you rerun the test with tcpdump with both of these full commands and please make sure to paste the full output from tcpdump for each command separately:
```
telegraf --input-filter=snmp -config /etc/telegraf/telegraf.d/snmp-pi-sensors.conf --test
```
```
snmpbulkwalk -c xxxx -v2c raspberrypi .1.3.6.1.2.1.25.1.8
```

**Comment by golemiii** [comment]
**for telegraf --input-filter=snmp -config /etc/telegraf/telegraf.d/snmp-pi-sensors.conf --test , tcdump result :**
IP xxx.xxx.xxx.xxx.41468 > xxx.xxx.xxx.xxx.161:  C="xxxxxxxxxxxx" GetBulk(27)  N=0 M=10 .1.3.6.1.2.1.1.5
IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.41468:  C="xxxxxxxxxxxx" GetResponse(232)  .1.3.6.1.2.1.1.5.0="raspberrypi" .1.3.6.1.2.1.1.6.0="Home" .1.3.6.1.2.1.1.7.0=72 .1.3.6.1.2.1.1.8.0=1 .1.3.6.1.2.1.1.9.1.2.1=.1.3.6.1.6.3.11.3.1.1 .1.3.6.1.2.1.1.9.1.2.2=.1.3.6.1.6.3.15.2.1.1 .1.3.6.1.2.1.1.9.1.2.3=.1.3.6.1.6.3.10.3.1.1 .1.3.6.1.2.1.1.9.1.2.4=.1.3.6.1.6.3.1 .1.3.6.1.2.1.1.9.1.2.5=.1.3.6.1.6.3.16.2.2.1 .1.3.6.1.2.1.1.9.1.2.6=.1.3.6.1.2.1.49
IP xxx.xxx.xxx.xxx.41468 > xxx.xxx.xxx.xxx.161:  C="xxxxxxxxxxxx" GetBulk(28)  N=0 M=10 .1.3.6.1.2.1.25.1.8
IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.41468:  C="xxxxxxxxxxxx" GetResponse(195)  .1.3.6.1.2.1.25.2.2.0=885364 .1.3.6.1.2.1.25.2.3.1.1.1=1 .1.3.6.1.2.1.25.2.3.1.1.3=3 .1.3.6.1.2.1.25.2.3.1.1.6=6 .1.3.6.1.2.1.25.2.3.1.1.7=7 .1.3.6.1.2.1.25.2.3.1.1.8=8 .1.3.6.1.2.1.25.2.3.1.1.10=10 .1.3.6.1.2.1.25.2.3.1.1.36=36 .1.3.6.1.2.1.25.2.3.1.1.38=38 .1.3.6.1.2.1.25.2.3.1.1.39=39
IP xxx.xxx.xxx.xxx.41468 > xxx.xxx.xxx.xxx.161:  C="xxxxxxxxxxxx" GetRequest(28)  .1.3.6.1.2.1.25.1.8
IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.41468:  C="xxxxxxxxxxxx" GetResponse(31)  .1.3.6.1.2.1.25.1.8=52616

**Comment by golemiii** [comment]
**FOR snmpbulkwalk -c xxxx -v2c raspberrypi .1.3.6.1.2.1.25.1.8, tcpdump result :**
IP xxx.xxx.xxx.xxx.37213 > xxx.xxx.xxx.xxx.161:  C="xxxxxxxxxxxx" GetBulk(28)  N=0 M=10 .1.3.6.1.2.1.25.1.8
IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.37213:  C="xxxxxxxxxxxx" GetResponse(195)  .1.3.6.1.2.1.25.2.2.0=885364 .1.3.6.1.2.1.25.2.3.1.1.1=1 .1.3.6.1.2.1.25.2.3.1.1.3=3 .1.3.6.1.2.1.25.2.3.1.1.6=6 .1.3.6.1.2.1.25.2.3.1.1.7=7 .1.3.6.1.2.1.25.2.3.1.1.8=8 .1.3.6.1.2.1.25.2.3.1.1.10=10 .1.3.6.1.2.1.25.2.3.1.1.36=36 .1.3.6.1.2.1.25.2.3.1.1.38=38 .1.3.6.1.2.1.25.2.3.1.1.39=39
IP xxx.xxx.xxx.xxx.37213 > xxx.xxx.xxx.xxx.161:  C="xxxxxxxxxxxx" GetRequest(28)  .1.3.6.1.2.1.25.1.8
IP xxx.xxx.xxx.xxx.161 > xxx.xxx.xxx.xxx.37213:  C="xxxxxxxxxxxx" GetResponse(31)  .1.3.6.1.2.1.25.1.8=51540

**Comment by danielnelson** [comment]
I think you will want to move both items to be top level fields.  This will influence the plugin to use a GET on each field instead of BULKWALK.

```toml
[[inputs.snmp]]
  agents = [ "raspberrypi" ]
  version = 2
  community = "xxxxxxxxxx"
  interval = "300s"
  timeout = "10s"
  retries = 3

  [[inputs.snmp.field]]
    name = "lmTempSensorsDevice"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "lmTempSensorsValue"
    oid = ".1.3.6.1.2.1.25.1.8"
```

I believe an alternative would be to change the `/usr/local/bin/snmp-cpu-temp` script to return a walk over a table, but that would be more complicated.  You can kind of get a hint about the cause by comparing it against the working `.6` oid, you will notice that snmpbulkwalk actually returns a different oid.
```
$ snmpwalk -v2c -On -c public localhost .1.3.6.1.2.1.25.1.6
.1.3.6.1.2.1.25.1.6.0 = Gauge32: 182
$ snmpwalk -v2c -On -c public localhost .1.3.6.1.2.1.25.1.8
.1.3.6.1.2.1.25.1.8 = Gauge32: 42
```

Let us know how it goes.
