### ISSUE TITLE
Implement usage of 'graphite tag support' and 'templates'

### ISSUE THREAD

**Issue by kkzinger** [influxdata/telegraf#4543]
## Feature Request

When testing out Graphite Tag support we discoverd that it is exclusive to the usage of templates. This leads to a very work intensive migration of our dashboards, because they rely on a specific graphite path.

### Proposal:
When using `graphite_tag_support` the `template` should also be considerd.

### Current behavior:
```toml
[[outputs.file]]
  files = ["stdout"]
  data_format = "graphite"
  prefix = "telegraf"
  template = "domain.host.measurement.tags.field"
  graphite_tag_support = true 
```

This configuration leads to

```
telegraf.win_memory.active;domain=fnord.cc;host=labwintest004.fnord.cc;objectname=Memory_system_input 0 1533889770
```

### Desired behavior:
```toml
[[outputs.file]]
  files = ["stdout"]
  data_format = "graphite"
  prefix = "telegraf"
  template = "domain.host.measurement.tags.field"
  graphite_tag_support = true 
```

This configuration should lead to

```
telegraf.fnord_cc.labwintest004_fnord_cc.win_memory.Memory_system_input.active;domain=fnord.cc;host=labwintest004.fnord.cc;objectname=Memory_system_input 0 1533889730
```

### Use case: 
At the moment the change to graphite tags includes a "big bang" migration on the dasboard side. This is due to the number of manual created dashboards no option.

 The usage of Tags with graphite is a feature which could be very useful in some parametrized dashboards we have and would allow to introduce more information in our dashboards.
