### ISSUE TITLE
Use in snmp.input agents "network" or large number of devices

### ISSUE THREAD

**Issue by skipper00** [influxdata/telegraf#4556]
### Relevant telegraf.conf:

[[inputs.snmp]]
  agents = ["172.19.253.0/24"]
  version = 2
  community = "Technet"
  name = "system"
### System info:

Telegraf v1.7.3 (git: release-1.7 4dc29d0e)

### Steps to reproduce:

1. Just to use as network instead of a sigle list of IP, as agent in SNMP input

### Expected behavior:
Snmp Input try ro reach every single IP of a network

### Actual behavior:
E! Error in plugin [inputs.snmp]: agent 172.19.253.0/24: performing get on field hostname: reconnecting: Error establishing connection to host: dial udp: lookup 172.19.253.0/24: no such host
### Additional info:

[Include gist of relevant config, logs, etc.]

**Comment by danielnelson** [comment]
@skipper00 This isn't something we would normally add support for, are there existing SNMP tools that have this behavior?

**Comment by skipper00** [comment]
@danielnelson you're right, it is usually used for autodiscovery....anyway....how can I list a large number of switches (50 unit), without creating an infinite list of object as:
....
agents = ["172.19.253.2" , "172.19.253.3" , "172.19.253.33" , .......]
.....
thanks

**Comment by Hipska** [comment]
I use Ansible to generate a config file for every host we need to collect data. (FYI)

**Comment by skipper00** [comment]
So interesting.....con you share a playbook?

**Comment by Hipska** [comment]
Can't share the whole playbook, but here are the 3 tasks where it comes down to:
```yaml
- name: Install network devices configuration files
  template:
    src: telegraf/device.toml.j2
    dest: "{{telegraf_include_dir}}/{{item.hostname}}.conf"
    owner: telegraf
    group: telegraf
  loop: "{{network_devices}}"
  register: managed_device_configs
  notify: reload telegraf

- name: Find all files in include directory
  find:
    paths: "{{telegraf_include_dir}}"
    recurse: yes
  register: all_device_configs

- name: Remove unmanaged files from include directory
  file:
    path: "{{item.path}}"
    state: absent
  loop: "{{all_device_configs.files}}"
  when: item.path not in managed_device_configs.results|selectattr('dest','defined')|map(attribute='dest')
  notify: reload telegraf
```

Then in the `device.toml.j2` you can use everything in the `item` var.
