### ISSUE TITLE
Windows Performance Counters Parenthesis in Instance Name do not output

### ISSUE THREAD

**Issue by co-al-re** [influxdata/telegraf#4558]
### Relevant telegraf.conf:
```toml
[[inputs.win_perf_counters]]
  PrintValid=true
  UseWildcardsExpansion=true
  [[inputs.win_perf_counters.object]]
    ObjectName = "SQLServer:Batch Resp Statistics"
    Instances = ["CPU Time:Requests", "CPU Time:Total\\(ms\\)"]
    Counters = ["*"]
    WarnOnMissing = true
    Measurement = "sql_server"
```

2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000000ms & <000001ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000001ms & <000002ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000002ms & <000005ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000005ms & <000010ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000010ms & <000020ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000020ms & <000050ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000050ms & <000100ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000100ms & <000200ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000200ms & <000500ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=000500ms & <001000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=001000ms & <002000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=002000ms & <005000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=005000ms & <010000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=010000ms & <020000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=020000ms & <050000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=050000ms & <100000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Requests)\Batches >=100000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000000ms & <000001ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000001ms & <000002ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000002ms & <000005ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000005ms & <000010ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000010ms & <000020ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000020ms & <000050ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000050ms & <000100ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000100ms & <000200ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000200ms & <000500ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=000500ms & <001000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=001000ms & <002000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=002000ms & <005000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=005000ms & <010000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=010000ms & <020000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=020000ms & <050000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=050000ms & <100000ms
2018-08-14T23:48:09Z I! Valid: \\[REDACTED]\SQLServer:Batch Resp Statistics(CPU Time:Total\(ms\))\Batches >=100000ms

Even though it shows valid, there is no output.

Also this next config fails a step sooner, it will actually tell you it can't find a performance counter, whereas the config above will tell you the counter is valid.

```toml
[[inputs.win_perf_counters]]
  PrintValid=true
  UseWildcardsExpansion=true
  [[inputs.win_perf_counters.object]]
    ObjectName = "SQLServer:Batch Resp Statistics"
    Instances = ["*"]
    Counters = ["*"]
    WarnOnMissing = true
    Measurement = "sql_server"
```

2018-08-15T00:01:52Z I! Invalid counterPath: '\SQLServer:Batch Resp Statistics(*)\*'. Error: The specified instance is not present.

### System info:
Telegraf 1.7.3
Windows Server 2012 R2

### Steps to reproduce:

1. telegraf.exe --config db.conf --test > test.out

### Expected behavior:
Data in the output file.

### Actual behavior:
Zero byte file.

### Additional info:
I already use the same Agent and Output settings for other counters and I get output, so I know its specifically this counter set.
