### ISSUE TITLE
Telegraf failing to start

### ISSUE THREAD

**Issue by juergenschubert** [influxdata/telegraf#4560]
### Relevant telegraf.conf:

```toml
# Configuration for telegraf agent
[agent]

  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  urls = ["http://192.168.1.50:8086"]
  database = "telegraf"
  skip_database_creation = true
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################
[[inputs.mqtt_consumer]]
   servers = ["tcp://192.168.1.44:1883"]
   qos = 0
   topics = ["influx/#"]
    username = login##
    password = pw##
    data_format = "JSON"


#############################
#######
##########################
```

### System info:
influx -version
InfluxDB shell version: 1.5.0
telegraf -version
Telegraf v1.5.3 (git: release-1.5 1e519698)
RapsberryPi 3 Model B
debian_version 9.4
Mosquitte MQTT on a differnete PI

### Steps to reproduce:

#systemctl status telegraf
● telegraf.service - The plugin-driven server agent for reporting metrics into InfluxDB
   Loaded: loaded (/lib/systemd/system/telegraf.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-08-15 15:51:58 CEST; 30min ago
     Docs: https://github.com/influxdata/telegraf
  Process: 9074 ExecStart=/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d $TELEGRAF_OPTS (code=exited, status=1/FAILURE)
 Main PID: 9074 (code=exited, status=1/FAILURE)

Aug 15 15:51:57 grafana-pi systemd[1]: telegraf.service: Unit entered failed state.
Aug 15 15:51:57 grafana-pi systemd[1]: telegraf.service: Failed with result 'exit-code'.
Aug 15 15:51:58 grafana-pi systemd[1]: telegraf.service: Service hold-off time over, scheduling restart.
Aug 15 15:51:58 grafana-pi systemd[1]: Stopped The plugin-driven server agent for reporting metrics into InfluxDB.
Aug 15 15:51:58 grafana-pi systemd[1]: telegraf.service: Start request repeated too quickly.
Aug 15 15:51:58 grafana-pi systemd[1]: Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.
Aug 15 15:51:58 grafana-pi systemd[1]: telegraf.service: Unit entered failed state.
Aug 15 15:51:58 grafana-pi systemd[1]: telegraf.service: Failed with result 'exit-code'.

### Actual behavior:
no chance to get telegraf started

### Additional info:
the MQTT message which arrives locks like:
{"time":"2018-08-15 15:34:12","model":"Prologue sensor","id":5,"rid":201,"channel":3,"battery":"OK","button":0,"temperature_C":24.4,"humidity":17}

**Comment by glinton** [comment]
Are you quoting your username/password perchance? Can you run `/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d` manually and post any new output?

**Comment by juergenschubert** [comment]
Sure I do use "username" and "password" in my config !
when I start I got an error telling me that "iskip_database_creation = true" is not valid and I added ## infront of that line. After the correction I do see no more error on the " plugin-driven server agent". What I do see is, but still no

pi@grafana-pi:/etc/telegraf $ /usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
2018-08-15T16:54:15Z I! Starting Telegraf v1.5.3
2018-08-15T16:54:15Z I! Loaded outputs: influxdb
2018-08-15T16:54:15Z I! Loaded inputs: inputs.processes inputs.swap inputs.disk inputs.kernel inputs.mem inputs.mqtt_consumer inputs.cpu inputs.diskio inputs.system
2018-08-15T16:54:15Z I! Tags enabled: host=grafana-pi
2018-08-15T16:54:15Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"grafana-pi", Flush Interval:10s 

rigth now it does not show any content coming accros. All I do see is:
show measurements
name: measurements
name
----
cpu
disk
diskio
kernel
mem
processes
swap
system

while I do have generated two messages posting to MQTT Topic but do not find them into my influxdb

**Comment by glinton** [comment]
Interesting, can you append `--test` to the `telegraf` command (`/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --test`) and try again. Let it run for ~20 seconds (your interval is 10s, so we should be able to see some output, once it picks up newly generated MQTT messages.

**Comment by juergenschubert** [comment]
Where do I get the measurement value set for influxdb?

**Comment by juergenschubert** [comment]
/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d --test
* Plugin: inputs.kernel, Collection 1
> kernel,host=grafana-pi interrupts=39826089i,context_switches=53709249i,boot_time=1533984538i,processes_forked=43701i 1534354704000000000
* Plugin: inputs.swap, Collection 1
> swap,host=grafana-pi free=104853504i,used_percent=0,total=104853504i,used=0i 1534354704000000000
> swap,host=grafana-pi in=0i,out=0i 1534354704000000000
* Plugin: inputs.system, Collection 1
> system,host=grafana-pi load1=0.03,load5=0.03,load15=0.08,n_users=3i,n_cpus=4i 1534354705000000000
> system,host=grafana-pi uptime=370166i 1534354705000000000
> system,host=grafana-pi uptime_format="4 days,  6:49" 1534354705000000000

WARNING: skipping plugin [[inputs.mqtt_consumer]]: service inputs not supported in --test mode
* Plugin: inputs.disk, Collection 1
> disk,path=/,device=root,fstype=ext4,mode=rw,host=grafana-pi inodes_free=423814i,inodes_used=41578i,total=7744622592i,free=5985226752i,used=1411485696i,used_percent=19.082608738989876,inodes_total=465392i 1534354705000000000
> disk,fstype=vfat,mode=rw,host=grafana-pi,path=/boot,device=mmcblk0p1 inodes_used=0i,total=43141632i,free=21148160i,used=21993472i,used_percent=50.97969404588125,inodes_total=0i,inodes_free=0i 1534354705000000000
* Plugin: inputs.diskio, Collection 1
> diskio,name=mmcblk0,host=grafana-pi read_time=26420i,write_time=855850i,io_time=523980i,writes=184300i,read_bytes=238809600i,write_bytes=1770473472i,reads=8307i,weighted_io_time=882080i,iops_in_progress=0i 1534354705000000000
> diskio,name=mmcblk0p1,host=grafana-pi writes=4i,read_bytes=2518528i,write_bytes=2048i,read_time=400i,write_time=30i,weighted_io_time=430i,iops_in_progress=0i,reads=93i,io_time=360i 1534354705000000000
> diskio,name=mmcblk0p2,host=grafana-pi read_bytes=235754496i,write_bytes=1770471424i,write_time=855820i,weighted_io_time=901880i,iops_in_progress=0i,reads=8199i,writes=184296i,read_time=25980i,io_time=523880i 1534354705000000000
* Plugin: inputs.mem, Collection 1
> mem,host=grafana-pi inactive=146001920i,used_percent=19.728300933044082,total=972369920i,available=780537856i,used=191832064i,cached=257536000i,available_percent=80.27169906695592,free=535576576i,buffered=48775168i,active=249208832i,slab=29040640i 1534354705000000000
* Plugin: inputs.processes, Collection 1
> processes,host=grafana-pi zombies=0i,running=1i,unknown=0i,dead=0i,total_threads=177i,idle=0i,blocked=0i,stopped=0i,sleeping=133i,total=134i,paging=0i 1534354705000000000
* Plugin: inputs.cpu, Collection 1
* Plugin: inputs.cpu, Collection 2
> cpu,cpu=cpu0,host=grafana-pi usage_softirq=0,usage_guest=0,usage_guest_nice=0,usage_system=0,usage_irq=0,usage_nice=0,usage_iowait=0,usage_steal=0,usage_user=0,usage_idle=100 1534354705000000000
> cpu,cpu=cpu1,host=grafana-pi usage_system=0,usage_nice=0,usage_iowait=0,usage_irq=0,usage_softirq=0,usage_steal=0,usage_guest=0,usage_guest_nice=0,usage_user=0,usage_idle=100 1534354705000000000
> cpu,cpu=cpu2,host=grafana-pi usage_steal=0,usage_user=0,usage_system=0,usage_idle=100,usage_iowait=0,usage_irq=0,usage_softirq=0,usage_nice=0,usage_guest=0,usage_guest_nice=0 1534354705000000000
> cpu,cpu=cpu3,host=grafana-pi usage_guest_nice=0,usage_idle=100,usage_nice=0,usage_iowait=0,usage_softirq=0,usage_steal=0,usage_guest=0,usage_user=0,usage_system=0,usage_irq=0 1534354705000000000
> cpu,host=grafana-pi,cpu=cpu-total usage_guest_nice=0,usage_irq=0,usage_softirq=0,usage_steal=0,usage_user=0,usage_system=0,usage_idle=100,usage_nice=0,usage_iowait=0,usage_guest=0 1534354705000000000

**Comment by juergenschubert** [comment]
no input MQTT !

**Comment by juergenschubert** [comment]
If there is no MQTT message it won't have anything to import. Let me implement a "every second" mqtt messsage to make sure there is something to import

**Comment by juergenschubert** [comment]
I do a ping and send the responsetim to MQTT Topic influx/response

**Comment by glinton** [comment]
ok, also you can add `--input-filter mqtt_consumer` to only show output from that

**Comment by juergenschubert** [comment]
/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d -input-filter mqtt_consumer --test

WARNING: skipping plugin [[inputs.mqtt_consumer]]: service inputs not supported in --test mode

**Comment by juergenschubert** [comment]
/usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d -input-filter mqtt_consumer
2018-08-15T17:54:29Z I! Starting Telegraf v1.5.3
2018-08-15T17:54:29Z I! Loaded outputs: influxdb
2018-08-15T17:54:29Z I! Loaded inputs: inputs.mqtt_consumer
2018-08-15T17:54:29Z I! Tags enabled: host=grafana-pi
2018-08-15T17:54:29Z I! Agent Config: Interval:10s, Quiet:false, Hostname:"grafana-pi", Flush Interval:10s

**Comment by glinton** [comment]
Ah, then just add an output block in your config file that dumps to stdout:
```toml
[[outputs.file]]
  files = ["stdout"]
```
