### ISSUE TITLE
Converter does not convert

### ISSUE THREAD

**Issue by 6d6178** [influxdata/telegraf#4582]
### Relevant telegraf.conf:

```
[[inputs.snmp]]
        agents = [ "xxx ]     ## Timeout for each SNMP query.
        timeout = "45s"
        ## Number of retries to attempt within timeout.
        retries = 2
        ## SNMP version, values can be 1, 2, or 3
        version = 2

        ## SNMP community string.
        community = "xxx"

        ## The GETBULK max-repetitions parameter
        max_repetitions = 10

        ## SNMPv3 auth parameters
        #sec_name = "myuser"
        #auth_protocol = "md5"      # Values: "MD5", "SHA", ""
        #auth_password = "pass"
        #sec_level = "authNoPriv"   # Values: "noAuthNoPriv", "authNoPriv", "authPriv"
        #context_name = ""
        #priv_protocol = ""         # Values: "DES", "AES", ""
        #priv_password = ""

        name = "sdx"

        [[inputs.snmp.table]]
            ## measurement name
            name = "sdx.ports"
            inherit_tags = [ "hostname" ]
            [[inputs.snmp.table.field]]
              name = "interfacePort"
              oid = "1.3.6.1.4.1.5951.6.2.1000.5.1.1"
              is_tag = true
            [[inputs.snmp.table.field]]
              name = "interfaceRxBytes"
              oid = "1.3.6.1.4.1.5951.6.2.1000.5.1.7"
            [[inputs.snmp.table.field]]
              name = "interfaceTxBytes"
              oid = "1.3.6.1.4.1.5951.6.2.1000.5.1.8"

        [[inputs.snmp.table]]
            ## measurement name
            name = "sdx.vpx"
            inherit_tags = [ "hostname" ]
            [[inputs.snmp.table.field]]
              name = "nsName"
              oid = "1.3.6.1.4.1.5951.6.3.2.1.10"
              is_tag = true
            [[inputs.snmp.table.field]]
              name = "nsNsCPUUsage"
              oid = "1.3.6.1.4.1.5951.6.3.2.1.33"
            [[inputs.snmp.table.field]]
              name = "nsNsMemoryUsage"
              oid = "1.3.6.1.4.1.5951.6.3.2.1.35"

[[processors.converter]]
  [processors.converter.fields] 
    integer = ["sdx.ports.interfaceRxBytes"]
    integer = ["interfaceRxBytes"]
    integer = ["*interfaceRxBytes*"]
```

### System info:

Telegraf v1.7.3 (git: release-1.7 4dc29d0e)
CentOS Linux release 7.4.1708 (Core) 

### Steps to reproduce:

The device I poll answers with a numeric string. I was happy to find that you implemented a converter recently. When I added the converter it didn't change the output. I used 

 `telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ --test --debug`
to look at the output.

I do have several files in the config directory and added the processor at the end of the config of this device.
I did try it with several files and several datatypes but it didn't change the datatype at any point.

### Expected behavior:

```
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=0/2 interfaceRxBytes=0i,interfaceTxBytes="0" 1534936998000000000
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/9 interfaceRxBytes=0i,interfaceTxBytes="0" 1534936998000000000
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/6 interfaceRxBytes=0i,interfaceTxBytes="0" 1534936998000000000
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/4 interfaceRxBytes=0i,interfaceTxBytes="0" 1534936998000000000
...
```

### Actual behavior:

```
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=0/2 interfaceRxBytes="0",interfaceTxBytes="0" 1534936998000000000
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/9 interfaceRxBytes="0",interfaceTxBytes="0" 1534936998000000000
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/6 interfaceRxBytes="0",interfaceTxBytes="0" 1534936998000000000
> sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/4 interfaceRxBytes="0",interfaceTxBytes="0" 1534936998000000000
...
```

### Additional info:

I hope you can tell me what I do wrong or if it is a bug.

**Comment by danielnelson** [comment]
Do you just need to change the field name from Rx to Tx?
```
[[processors.converter]]                                                                                                                                                                                                                                                                                                                                                     
  [processors.converter.fields]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    integer = ["interfaceTxBytes"]
```

**Comment by 6d6178** [comment]
I would love if that was the solution.
Sadly all numeric values are given as string so I need to convert them all. (You'd think that a billion dollar company can get this right) I tried to show that it doesn't affect a value but I probably make it more complicated than needed.

**Comment by danielnelson** [comment]
Maybe something like this would work, it should convert all fields for the `sdx.ports` to integer:

```toml
[[processors.converter]]
  namepass = ["sdx.ports"]                                                                                                                                                                                                                                                                                                                                                    
  [processors.converter.fields]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    integer = ["*"]
```

**Comment by 6d6178** [comment]
Sorry for not getting back to you sooner.
I tried it with namepass but it didn't change the output. Is the placement of the Processor part in the config important? I have it in a file in the config directory. Or is it more likely that the processor doesn't match the field for some reason? 
On that note, is there a way to show all the plugins (inputs,outputs,processors) that are loaded on startup to check if that is what is going wrong? I remember seeing it like this at one point.

**Comment by 6d6178** [comment]
You are absolutely right. I totally forgot about that when I saw the processor plugin. I tested it and it does indeed work.
It's up to you if we mark this as solved with this "workaround" or try to find out what is wrong as the processor is seemingly not working as intended.

**Comment by danielnelson** [comment]
It would be nice to figure out what the converter issue is, but it seems to be working for me.  Here is how I'm testing:
```toml
[[inputs.socket_listener]]
  service_address = "udp://:8094"

[[processors.converter]]
  namepass = ["sdx.ports"]                                                                                                                                                                                                                                                                                                                                                    
  [processors.converter.fields]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
    integer = ["*"]

[[outputs.file]]
  files = ["stdout"]
```

Then I start Telegraf and from another shell run:
```
echo 'sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/4 interfaceRxBytes="0",interfaceTxBytes="0" 1534936998000000000' > /dev/udp/localhost/8094
```

Telegraf outputs the converted integer values:
```
sdx.ports,agent_host=xxx,host=xxx,interfacePort=10/4 interfaceRxBytes=0i,interfaceTxBytes=0i 1534936998000000000
```

Can you try that out and see if it works for you?
