### ISSUE TITLE
Headers are treated as data when CSV file is rotated by tail plugin.

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#4711]
### System info:

Telegraf master 44c2435f6471859381650700a28eaf0382851ce9

### Steps to reproduce:

```toml
[[inputs.tail]]
  files = ["test.csv"]
  from_beginning = true
  data_format = "csv"
  csv_header_row_count = 1
```

```
cat test.csv
a,b
1,2
```

1. `telegraf --input-filter tail --output-filter file`
2. `echo a,b > test.csv`

### Expected behavior:

Headers are updated or ignored in truncated file:

```
csv a=1i,b=2i
```

### Actual behavior:

Headers are treated as new data:
```
csv a=1i,b=2i
csv a="a",b="b"
```

### Additional info:

The hpcloud/tail library silently reopens a truncated file when in follow mode, so it does not appear to be possible to know when the file has been rotated.
