### ISSUE TITLE
JSON parser panic if name key returns nil

### ISSUE THREAD

**Issue by glinton** [influxdata/telegraf#4734]
If the `json_name_key` doesn't exist, telegraf panics.

### telegraf.conf
```toml
[[inputs.file]]
  files = ["/tmp/test.json"]
  data_format = "json"
  tag_keys = [
    "tags_eventType",
    "tags_EventId",
    "tags_created_by"
  ]
  json_name_key = "not_present"
```

### /tmp/test.json
```json
{
  "measurement": "myEvents",
  "tags": {
    "eventType": "Open",
    "created_by": "Biff",
    "EventId": "123"
  },
  "duration": 127
}
```
