### ISSUE TITLE
[jolokia2] support wildcard mbean non-map values

### ISSUE THREAD

**Issue by albundy83** [influxdata/telegraf#4748]
### Relevant telegraf.conf:
The configuration described here https://github.com/influxdata/telegraf/blob/f72e52528d1edf757a068c059fcebf23ad27f29f/plugins/inputs/jolokia2/examples/java.conf#L24

which should allow to filter LastGcInfo metrics does not work.
Or you specify the configuration described but you won't collect anything or you specify only : 
```toml
[[inputs.jolokia2_agent.metric]]
    name  = "java_last_garbage_collection"
    mbean = "java.lang:name=G1 Young Generation,type=GarbageCollector"
    paths = ["LastGcInfo"]
```
But you will collect all the values under...

### System info:
OS: Ubuntu 14.04.5 LTS
telegraf version: 1.7.4 / 1.8.0
jolokia: jolokia-jvm-1.6.0-agent

**Comment by albundy83** [comment]
When I put the configuration described:
```toml
[[inputs.jolokia2_agent.metric]]
    name  = "GarbageCollector"
    mbean = "java.lang:name=*,type=GarbageCollector"
    paths = ["CollectionCount", "CollectionTime", "LastGcInfo/duration"]
    tag_keys = ["name"]
    field_prefix = "$1_"
```
and I run command:
```bash
/usr/bin/telegraf -pidfile /var/run/telegraf/telegraf.pid -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --test
```
I have this output:
```bash
panic: There should be a map here for java.lang:name=*,type=GarbageCollector!


goroutine 42 [running]:
github.com/influxdata/telegraf/plugins/inputs/jolokia2.(*pointBuilder).Build(0xc42054e800, 0xc4208f8061, 0x26, 0x0, 0x0, 0x3, 0x3, 0x0)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/jolokia2/point_builder.go:38 +0x447
github.com/influxdata/telegraf/plugins/inputs/jolokia2.(*Gatherer).generatePoints(0xc420a18060, 0xc4203be341, 0x10, 0xc4208f8061, 0x26, 0xc4201a4a50, 0x3, 0x3, 0x0, 0x0, ...)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/jolokia2/gatherer.go:101 +0x4d7
github.com/influxdata/telegraf/plugins/inputs/jolokia2.(*Gatherer).gatherResponses(0xc420a18060, 0xc42024f200, 0x4, 0x4, 0xc420a3dcb0, 0x2149840, 0xc420a16020)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/jolokia2/gatherer.go:57 +0x42c
github.com/influxdata/telegraf/plugins/inputs/jolokia2.(*Gatherer).Gather(0xc420a18060, 0xc420a161a0, 0x2149840, 0xc420a16020, 0x0, 0x0)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/jolokia2/gatherer.go:42 +0x212
github.com/influxdata/telegraf/plugins/inputs/jolokia2.(*JolokiaAgent).Gather.func1(0xc420a24000, 0xc4208e4ea0, 0x2149840, 0xc420a16020, 0xc420a161a0)
	/go/src/github.com/influxdata/telegraf/plugins/inputs/jolokia2/jolokia_agent.go:84 +0x8a
created by github.com/influxdata/telegraf/plugins/inputs/jolokia2.(*JolokiaAgent).Gather
	/go/src/github.com/influxdata/telegraf/plugins/inputs/jolokia2/jolokia_agent.go:81 +0x122
```
And as I explain, when I put configuration without "duration", like this:
```toml
[[inputs.jolokia2_agent.metric]]
    name  = "GarbageCollector"
    mbean = "java.lang:name=*,type=GarbageCollector"
    paths = ["CollectionCount", "CollectionTime", "LastGcInfo"]
    tag_keys = ["name"]
    field_prefix = "$1_"
```

I have all the metrics under LastGcInfo
```bash
java_GarbageCollector,jolokia_agent_url=http://localhost:8778/jolokia,name=ConcurrentMarkSweep,rack=d06 ConcurrentMarkSweep_CollectionCount=1,ConcurrentMarkSweep_CollectionTime=60,ConcurrentMarkSweep_LastGcInfo.GcThreadCount=24,ConcurrentMarkSweep_LastGcInfo.duration=2344,ConcurrentMarkSweep_LastGcInfo.endTime=7264,ConcurrentMarkSweep_LastGcInfo.id=1,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.CMS\ Old\ Gen.committed=6442450944,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.CMS\ Old\ Gen.init=6442450944,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.CMS\ Old\ Gen.max=6442450944,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.CMS\ Old\ Gen.used=0,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Code\ Cache.committed=19857408,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Code\ Cache.init=2555904,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Code\ Cache.max=251658240,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Code\ Cache.used=19221760,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Compressed\ Class\ Space.committed=5275648,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Compressed\ Class\ Space.init=0,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Compressed\ Class\ Space.max=1073741824,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Compressed\ Class\ Space.used=5024744,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Metaspace.committed=37367808,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Metaspace.init=0,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Metaspace.max=-1,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Metaspace.used=36338584,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Eden\ Space.committed=1718091776,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Eden\ Space.init=1718091776,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Eden\ Space.max=1718091776,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Eden\ Space.used=907843016,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Survivor\ Space.committed=214695936,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Survivor\ Space.init=214695936,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Survivor\ Space.max=214695936,ConcurrentMarkSweep_LastGcInfo.memoryUsageAfterGc.Par\ Survivor\ Space.used=28507224,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.CMS\ Old\ Gen.committed=6442450944,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.CMS\ Old\ Gen.init=6442450944,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.CMS\ Old\ Gen.max=6442450944,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.CMS\ Old\ Gen.used=0,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Code\ Cache.committed=12189696,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Code\ Cache.init=2555904,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Code\ Cache.max=251658240,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Code\ Cache.used=12092928,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Compressed\ Class\ Space.committed=4636672,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Compressed\ Class\ Space.init=0,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Compressed\ Class\ Space.max=1073741824,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Compressed\ Class\ Space.used=4460648,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Metaspace.committed=31887360,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Metaspace.init=0,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Metaspace.max=-1,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Metaspace.used=31156056,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Eden\ Space.committed=1718091776,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Eden\ Space.init=1718091776,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Eden\ Space.max=1718091776,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Eden\ Space.used=21991696,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Survivor\ Space.committed=214695936,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Survivor\ Space.init=214695936,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Survivor\ Space.max=214695936,ConcurrentMarkSweep_LastGcInfo.memoryUsageBeforeGc.Par\ Survivor\ Space.used=28507224,ConcurrentMarkSweep_LastGcInfo.startTime=4920 1537986807000000000
```
But that's not what I want :-)

I hope that the filter "LastGcInfo/duration" could produce me just this metric.

**Comment by glinton** [comment]
I'm just guessing here, but can you modify your `mbean` line to be
`mbean = "java.lang:name=ConcurrentMarkSweep,type=GarbageCollector"`. It seems that if the `mbean` has an `*`, we [don't handle plain/other values](https://github.com/influxdata/telegraf/blob/f72e52528d1edf757a068c059fcebf23ad27f29f/plugins/inputs/jolokia2/point_builder.go#L31-L39).
I'm hoping the `ConcurrentMarkSweep` is the mbean name that gets prepended to the output field.

**Comment by albundy83** [comment]
Yes it works :-)
when I put:
```toml
 [[inputs.jolokia2_agent.metric]]
    name  = "GarbageCollector"
    mbean = "java.lang:name=ConcurrentMarkSweep,type=GarbageCollector"
    paths = ["CollectionCount", "CollectionTime", "LastGcInfo/duration"]
```
It produces:
```bash
java_GarbageCollector,jolokia_agent_url=http://localhost:8778/jolokia,rack=d06 CollectionCount=1,CollectionTime=60,LastGcInfo.duration=2344 1537995461000000000
```
Just what I expect, thanks a lot for your help.

I will just need to duplicate lines for each GarbageCollector type:
```toml
  [[inputs.jolokia2_agent.metric]]
    name  = "GarbageCollector"
    mbean = "java.lang:name=ConcurrentMarkSweep,type=GarbageCollector"
    paths = ["CollectionCount", "CollectionTime", "LastGcInfo/duration"]
    field_prefix = "ConcurrentMarkSweep"

  [[inputs.jolokia2_agent.metric]]
    name  = "GarbageCollector"
    mbean = "java.lang:name=ParNew,type=GarbageCollector"
    paths = ["CollectionCount", "CollectionTime", "LastGcInfo/duration"]
    field_prefix = "ParNew"
```
And I have:
```bash
java_GarbageCollector,jolokia_agent_url=http://localhost:8778/jolokia,rack=d06 ConcurrentMarkSweepCollectionCount=1,ConcurrentMarkSweepCollectionTime=60,ConcurrentMarkSweepLastGcInfo.duration=2344,ParNewCollectionCount=202,ParNewCollectionTime=5360,ParNewLastGcInfo.duration=21 1537996077000000000
```
