### ISSUE TITLE
logparser broken on 1.8.x

### ISSUE THREAD

**Issue by law** [influxdata/telegraf#4816]
### Relevant telegraf.conf:
```toml
[[inputs.logparser]]
  files = ["/var/log/nginx/cdn_access.log"]
  from_beginning = true
  name_override = "nginx_access_log"
  [inputs.logparser.grok]
    patterns = ["%{COMBINED_LOG_FORMAT}"]
```

### System info:
telegraf 1.8.x (tested on .0 and .1), Ubuntu 16.04.5

### Steps to reproduce:

1. Define a standard nginx 'combined' logfile
2. configure telegraf with a logparser as per above
3. restart telegraf

### Expected behavior:

telegraf should send metrics from the parsed logfile to the defined 'output' (the above config works with telegraf 1.7.x, tested with .0, .1, and .4) 

### Actual behavior:

telegraf 1.8.x's logfile shows it loads the 'inputs.logparser', but does not actually send metrics.  No additional info, error, or debug output is provided.

**Comment by danielnelson** [comment]
Looks like the measurement name is not being set properly, this shouldbe a workaround and we will fix this in 1.8.2:
```toml
[[inputs.logparser]]
  files = ["/var/log/nginx/cdn_access.log"]
  from_beginning = true
  [inputs.logparser.grok]
    measurement = "nginx_access_log"
    patterns = ["%{COMBINED_LOG_FORMAT}"]
```
