### ISSUE TITLE
Unable to parse JSON input from HTTP

### ISSUE THREAD

**Issue by ea1dof** [influxdata/telegraf#4822]
I am trying to acquire metrics formatted in JSON and available with a simple HTTP query.

Here is an example of the JSON object that I get:
```json
{
  "clients": [
    {
      "clientIp": "192.168.0.11",
      "target": "2"
    }
  ],
  "defaultTarget": "1"
}
```

The configuration in the input.http section is:
```toml
  urls = ["http://192.168.0.1:5000/current-config"]
  method = "GET"
  timeout = "5s"
  data_format = "json"
  tag_keys = ["clientIp"]
```

When I run:
   telegraf --config /etc/telegraf/telegraf.d/mytelegraf2.conf --input-filter http --debug --test
nothing happens. Telegraf finishes and nothing is reported on the screen or the log file

However, I have been successful in acquiring data from the same source using the httpjson input. The problem is that httpjson does not support strings, which should be my next step to record "clientIp". Thus, I moved to http input, where I don't get even the basic values read.

Any hint is highly appreciated.

Thanks,
       Miguel

**Comment by glinton** [comment]
You'll need to specify the member [as documented](https://github.com/influxdata/telegraf/blob/1.8.1/plugins/parsers/json/README.md), summarized here:
```toml
  tag_keys = ["clients_0_clientIp"]
  json_string_fields = ["defaultTarget"]
```
output:
```
file,clientIp=192.168.0.11,host=hilldale target="2" 1539017545000000000
```

You can alternatively add `json_query` to apply tags/fields based on the subset of that query (best if there will be more than one member of `clients`):
```toml
  json_query = "clients"
  tag_keys = ["clientIp"]
  json_string_fields = ["target"]
```

output:
```
file,clientIp=192.168.0.11 target="2" 1539017575000000000
file,clientIp=192.168.0.12 target="1" 1539017575000000000
```


Both using a modified version of your input:
```json
{
  "clients": [
    {
      "clientIp": "192.168.0.11",
      "target": "2"
    },
    {
      "clientIp": "192.168.0.12",
      "target": "1"
    }
  ],
  "defaultTarget": "1"
}
```
