### ISSUE TITLE
How to templates the input of influxdb_listener

### ISSUE THREAD

**Issue by jenningsloy318** [influxdata/telegraf#4891]
## Feature Request

add support for templates setting in influxdb_listener

### Proposal:

add configuration to this plugin which can recieved Graphite metrics into influxdb metrics
```
templates = [
    "netapp-performance.Clusters.*.SVMs.*.Volumes.*.Luns.* ..cluster..SVM.measurement.volume..lun..field*",
    "netapp-performance.Clusters.*.SVMs.*.Volumes.* ..cluster..SVM.measurement.volume.field*",

    "netapp-performance.Clusters.*.SVMs.*.NFSV3.* ..cluster.SVMs.SVM.measurement.field*",
    "netapp-performance.Clusters.*.SVMs.*.NFSV4.* ..cluster.SVMs.SVM.measurement.field*",
    "netapp-performance.Clusters.*.SVMs.*.NFSV41.* ..cluster.SVMs.SVM.measurement.field*",

    "netapp-performance.Clusters.*.Nodes.*.Network_Ports.* ..cluster..node.measurement.port..field*",
    "netapp-performance.Clusters.*.Nodes.*.Aggregates.* ..cluster..node.measurement.aggregate.field*",
    "netapp-performance.Clusters.*.Nodes.* ..cluster.measurement.node.field*"
]
```
### Current behavior:
no templates support 
### Desired behavior:
add support for https://github.com/Oxalide/NetApp-OCPM-InfluxDB and https://github.com/Oxalide/netapp-harvest-influxdb which make it possible to export metrics to telegraf
### Use case: [Why is this important (helps with prioritizing requests)]

to monitor netapp storage systems with netapp harvest, which only support Graphite  format, desire to support to exported to influxdb also with this plugin as an entry of monitoring system.

**Comment by glinton** [comment]
I believe you can already export these things to telegraf. Use the socket listener and graphite parser:

```toml
[[inputs.socket_listener]]
  service_address = "tcp://:2003"

  data_format = "graphite"

  ## Each template line requires a template pattern. It can have an optional
  ## filter before the template and separated by spaces. It can also have optional extra
  ## tags following the template. Multiple tags should be separated by commas and no spaces
  ## similar to the line protocol format. There can be only one default template.
  ## Templates support below format:
  ## 1. filter + template
  ## 2. filter + template + extra tag(s)
  ## 3. filter + template with field key
  ## 4. default template
  templates = [
    "netapp-performance.Clusters.*.SVMs.*.Volumes.*.Luns.* ..cluster..SVM.measurement.volume..lun..field*",
    "netapp-performance.Clusters.*.SVMs.*.Volumes.* ..cluster..SVM.measurement.volume.field*",

    "netapp-performance.Clusters.*.SVMs.*.NFSV3.* ..cluster.SVMs.SVM.measurement.field*",
    "netapp-performance.Clusters.*.SVMs.*.NFSV4.* ..cluster.SVMs.SVM.measurement.field*",
    "netapp-performance.Clusters.*.SVMs.*.NFSV41.* ..cluster.SVMs.SVM.measurement.field*",

    "netapp-performance.Clusters.*.Nodes.*.Network_Ports.* ..cluster..node.measurement.port..field*",
    "netapp-performance.Clusters.*.Nodes.*.Aggregates.* ..cluster..node.measurement.aggregate.field*",
    "netapp-performance.Clusters.*.Nodes.* ..cluster.measurement.node.field*"
  ]
```
