### ISSUE TITLE
JSON Parsing

### ISSUE THREAD

**Issue by orcunbaslak** [influxdata/telegraf#4943]
Hello,

I'm trying to parse a JSON at Telegraf and failing at it.

JSON is like this.
```json
{
  "timestamp": 1541021024224,
  "values": [
    {
      "id": "Raspberry.Pi.Ucuncu",
      "t": 1541021024193,
      "v": 7
    },
    {
      "id": "Raspberry.Pi.Dorduncu",
      "t": 1541021024193,
      "v": 0
    },
    {
      "id": "Raspberry.Pi.Ikinci",
      "t": 1541021024193,
      "v": 4
    },
    {
      "id": "Raspberry.Pi.Birinci",
      "t": 1541021024193,
      "v": 3
    }
  ]
}
```

and my Telegraf config is like this

```toml
#KEPSERVER
[[inputs.mqtt_consumer]]
  servers = ["tcp://localhost:1883"]
  qos = 0
  connection_timeout = "30s"
  topics = [
    "kesy",
  ]
  persistent_session = true
  client_id = "OrcunMQTT"
  data_format = "json"
  name_suffix = "_kesy_vm"
```

In the json; id will be the tag, t will be the timestamp and v is the value of the tag. timestamp at the top can be ignored.

Any help on this structure is very much appreciated.

Br,

**Comment by danielnelson** [comment]
@orcunbaslak Try these settings out:

```toml
[[inputs.mqtt_consumer]]
  # ... snip...
  json_query = "values"
  tag_keys = ["id"]
  json_time_key = "t"
  json_time_format = "unix_ms"
  data_format = "json"
  fielddrop = ["t"]
```
