### ISSUE TITLE
Extend socket_listener input plugin to write data to and to preprocess read data from sockets

### ISSUE THREAD

**Issue by mjf** [influxdata/telegraf#4984]
## Feature Request

Extend `socket_listener` input plugin to write data to sockets on connect so that control sequences or commands could be sent to the sockets to invoke response to gather data to be collected, preprocessed and parsed, primarily for use with interactive or non-standard interfaces.

### Proposal:

Allow for the following (or similar) configuration options to the `socket_listener` input plugin:

```toml
[[inputs.socket_listener]]

  service_address = "tcp://host.domain.tld:7505"  # OpenVPN management as an example

  # ...

  write_data_text = "status\nquit\n"  # write data in textual
  write_data_base64 = "c3RhdHVzXG5xdWl0XG4="  # or base64 representation (for binary data)

  read_data_strip = "\r+"  # strip all Carriage Return control characters
  read_data_beginning = "^Updated,.+$"
  read_data_beginning_drop = true  # data matching read_data_beginning won't be included (default: true)
  read_data_end = "^post-decompress\s+bytes,\d+.+$"
  read_data_end_drop = false  # data matching read_data_end will be included (default: true)

  # ...

  data_format = "grok"
  name_override = "openvpn"
  grok_custom_pattern_files = ["/path/to/openvpn_status.grok"]
  grok_patterns = ["%{OPENVPN_STATUS}"]

```

### Current behavior:

I see no way to achieve this except using `exec` and calling external tool or pipeline, as far as I know.

### Desired behavior:

To enable to send commands to interactive socket interfaces and parse result with for example *Grok* rulesets and to avoid using the `exec` plugin workarounds.

### Use case:

There would be plenty of use cases imaginable...

For instance, I would like to connect to the *OpenVPN* management *CLI* as I do with `telnet` or `socat`

    $ telnet localhost 7505
    status
    OpenVPN STATISTICS
    Updated,Tue Nov 13 09:48:06 2018
    TUN/TAP read bytes,648
    TUN/TAP write bytes,0
    TCP/UDP read bytes,295989
    TCP/UDP write bytes,328425
    Auth read bytes,96720
    pre-compress bytes,0
    post-compress bytes,0
    pre-decompress bytes,0
    post-decompress bytes,0
    END
    quit
    $

and gather the metrices with *Grok* ruleset. Using the proposal example above the resulting data
to be further parsed would be the following:

    TUN/TAP read bytes,648
    TUN/TAP write bytes,0
    TCP/UDP read bytes,295989
    TCP/UDP write bytes,328425
    Auth read bytes,96720
    pre-compress bytes,0
    post-compress bytes,0
    pre-decompress bytes,0
    post-decompress bytes,0

**Note:** The examples given in this feature request are intentionaly written in a little weird way to demonstrate desired features and function.

**Comment by danielnelson** [comment]
I think this is too much of a change for socket_listener and it would't mesh well with the declarative style of the config file, you really do need to write a program to describe what actions to take to have the right amount of control.

I think instead we should add an plugin for OpenVPN to gather these statistics.  I've wanted to add something to parse the `status` file and it could also run the status command and possibly other commands on the management interface.  If you think this is a good idea could you open an issue for adding an OpenVPN plugin?

BTW here is what the status file shows:
```
OpenVPN CLIENT LIST
Updated,Tue Nov 13 11:43:40 2018
Common Name,Real Address,Bytes Received,Bytes Sent,Connected Since
loaner.lan,xxx.xxx.xxx.xxx:xxxx,165980,182333,Tue Nov 13 11:32:22 2018
ROUTING TABLE
Virtual Address,Common Name,Real Address,Last Ref
52:54:00:5b:93:55,loaner.lan,xxx.xxx.xxx.xxx:xxxx,Tue Nov 13 11:43:38 2018
GLOBAL STATS
Max bcast/mcast queue length,5
END
```

**Comment by mjf** [comment]
@danielnelson I think some people would like to have the general ability to write to sockets running *CLI*. There is so many software you could gather measurements from using it's interactive *CLI* out there! Not every piece of software is so modern to provide *InfluxDB* line format to be consumed by *Telegraf* or even sent directly to *InfluxDB*... Therefore to have the ability to perform at least such a *minimalistic* (or rather "limited") interaction as shown in this feature request would be **IMHO** simply splendid.

The problem with custom input plugins is that not everyone is a programmer in *Go*, thus completely dependant upon the community effort. There is plenty of (often custom) software only few people use but still would like to gather metrices from too where there is almost no chance to get community write some plugin etc. The *OpenVPN* was given as an example only (the first thing that came into on my mind the time I was writing it).

For me calling an external script every 10th second or so seems to be quite wasteful and slow in some cases. The general purpose *Grok* plugin is fast enough for most situations (as far as I know for now) and it suites many cases very well. To connect to a socket and have the possibility to perform some basic stuff such as to write some request and sanitize response from the *CLI* and then parse it using *Grok* or another filter is quite a good idea (imagine that for example *HAProxy* does similar thing for service checks). Why not *Telegraf*?

Why not to provide some **general** feature to interact with "things" like sockets (*TCP*, *UDP*, *Unix Domain*), *named pipes*, or ordinary *files* (imagine *Telegraf* writes something somewhere and somewhere else something appears and *Telegraf* collects and processes it - why not), or even `input.exec`s `STDIN`, `STDOUT` and `STDERR`, etc.?

**OT:**

Is it because you managed people to have to write specialized plugins you benefit from stating *"Hey, we have got input and output plugins for this and that already included..."* where simple general purpose interface would be good enough in many cases, at least for the beginning solution to a problem if there is the need? I personaly strongly **agree** with custom plugins in general for it would be always better, more performant (and perhaps more secure), than *Grok* parsing, that's clear! 

But, when you want to monitor something and need to wait half of an year to get the possibility - that's really bad. And that's exactly what I think general purpose capabilities should be included (of course, there's still the `input.exec` posibility, right). There would be always the risk then you would never know what are people using the capabilities for for they will be satisfied with it and have no reason to share what are they (ab)using it for. But it could **IMHO** make *Telegraf* better and more usable product...

Or is it because you simply do not want people asking for help with such rather general purpose capabilities? Because, yes, once existing, people would (ab)use it for many many weird things! But that's what's it all about, right? Give the users as much powers as you could and do not bother with what they use the powers for. You still can just deny to answer such questions without loosing your face, that's all. (By the way, me for instance already abuse the `input.file` plugin with *Grok* [ruleset](https://gist.github.com/mjf/dd5eee89d59a13ac5e470e64b4092565) to gather *XFS* statistics from `/proc` and/or `/sys` and it works like charm and without some significant or bad overhead. And there is so many interesting numbers all around the `/proc` and `/sys` filesystems there is still no native *Go* input plugin written for yet! And many software with interactive interface too...)

**Comment by danielnelson** [comment]
I wouldn't be opposed to a new input plugin that writes to a socket and reads the response, socket_listener just accepts data so it wouldn't work, but I don't want to get into scripting the protocol interaction as it could be very complicated and this would be poorly described in toml.  I also don't want to add a preprocessing stage that runs before the parser, it complicates the parser model because now there are two parse steps and actually I think grok can handle the example without these options.

I do prefer to add a custom plugin for things like this though because it will be much easier to use and provide a consistent and curated metric schema.

These types of monitoring tasks are exactly the use case for the exec plugin, the only real downside is the cost of fork/exec the command.  We are planning to add a form that will control a long running subprocess so that won't necessarily be a limiting feature either.  I also want to add more plugins that can interact with user customizable code: exec processor, exec parser, exec serializer.  These should all support long running programs too.

**Comment by mjf** [comment]
@danielnelson I mostly agree with you. But the problem of the `[input.exec]` plugin is the cost of it, as you say...

Consider I would like to collect some measurement every second or few of them using the `[input.exec]` plugin with *i.e.* some *Perl* script just because I need to perform such a simple interaction with some sort of *CLI* simply because of having no other chance to obtain the measurement. That would surely produce lot of *CPU* workload I could avoid most of if only a native (very simple one, as suggested, of course) and consistent support for interactive interfaces existed.

**Comment by danielnelson** [comment]
I think this would make sense, a plugin that works somewhat like telnet or a restricted netcat.  It would just send a string and would read from the socket until EOF, a new connection would be made every interval.  I think TOML has flexible enough strings that we could just use a single string for sending, as it supports the normal escapes or multiline strings.


```toml
[[inputs.socket_response]]
  service_address = "tcp://host.domain.tld:7505"
  send_data = """\
              status\
              quit\
              """
  data_format = "grok"
  name_override = "openvpn"
  grok_custom_pattern_files = ["/path/to/openvpn_status.grok"]
  grok_patterns = ["%{OPENVPN_STATUS}"]
```

The parser, selected by `data_format`, would deal with newlines however it likes, but most of them today would split by line.  I'm not 100% sure if the grok parser handles being given multiple lines, but it should be made to handle it as we want to be able to have it deal with multiline logs using a join rule.
