### ISSUE TITLE
Add sudo support to processes input plugin when using ps method

### ISSUE THREAD

**Issue by enigma62333** [influxdata/telegraf#5004]
### Relevant telegraf.conf:
```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
[[inputs.diskio]]
  devices = ["ada*", "da*"]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.system]]
[[inputs.ipmi_sensor]]
  servers = ["user:password@lan(192.168.80.248)","user:password@lan(192.168.80.251)"]
  interval = "30s"
  timeout = "20s"
[[inputs.net]]
[[inputs.ntpq]]
  dns_lookup = true
[[inputs.smart]]
  use_sudo = true
  attributes = true
  excludes = [ "/dev/pass*", "/dev/ses*" ]
[[inputs.zfs]]
  poolMetrics = true
```

### System info:
```sh
root@freebsd-nas-1:~ # uname -a
FreeBSD freebsd-nas-1.local 11.2-RELEASE-p4 FreeBSD 11.2-RELEASE-p4 #0: Thu Sep 27 08:16:24 UTC 2018

root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

root@freebsd-nas-1:~ # pkg info | grep telegraf
telegraf-1.8.3                 Time-series data collection
```

[Include Telegraf version, operating system name, and other relevant details]

### Steps to reproduce:

1. Simply configure the processes input plugin on FreeBSD

### Expected behavior:

The values reported when running telegraf with the test parameter be recorded in influxdb.

Output of telegraf with the test parameter:
```
[root@freebsd-nas-1 ~]# for i in {1..6} ; do telegraf --config /usr/local/etc/telegraf.conf --input-filter processes --test ; sleep 10 ; done 
> processes,host=freebsd-nas-1.local blocked=22i,idle=34i,running=2i,sleeping=21i,stopped=0i,total=80i,unknown=0i,wait=1i,zombies=0i 1542586179000000000
> processes,host=freebsd-nas-1.local blocked=22i,idle=34i,running=2i,sleeping=21i,stopped=0i,total=80i,unknown=0i,wait=1i,zombies=0i 1542586189000000000
> processes,host=freebsd-nas-1.local blocked=22i,idle=33i,running=2i,sleeping=22i,stopped=0i,total=80i,unknown=0i,wait=1i,zombies=0i 1542586199000000000
> processes,host=freebsd-nas-1.local blocked=22i,idle=32i,running=2i,sleeping=23i,stopped=0i,total=80i,unknown=0i,wait=1i,zombies=0i 1542586209000000000
> processes,host=freebsd-nas-1.local blocked=22i,idle=31i,running=2i,sleeping=24i,stopped=0i,total=80i,unknown=0i,wait=1i,zombies=0i 1542586219000000000
> processes,host=freebsd-nas-1.local blocked=22i,idle=31i,running=2i,sleeping=24i,stopped=0i,total=80i,unknown=0i,wait=1i,zombies=0i 1542586229000000000
```
### Actual behavior:

Much smaller numbers are recorded:
```
SELECT "blocked", "dead", "idle", "paging", "running", "sleeping", "stopped", "total", "total_threads", "unknown", "wait", "zombies" FROM "telegraf"."autogen"."processes" WHERE time > now() - 5m AND "host"='freebsd-nas-1.local' GROUP BY "host"
name: processes
tags: host=freebsd-nas-1.local
time                blocked dead idle paging running sleeping stopped total total_threads unknown wait zombies
----                ------- ---- ---- ------ ------- -------- ------- ----- ------------- ------- ---- -------
1542586009000000000 0            0           4       0        0       4                   0       0    0
1542586019000000000 0            0           3       3        0       6                   0       0    0
1542586029000000000 0            0           3       1        0       4                   0       0    0
1542586039000000000 0            0           3       1        0       4                   0       0    0
1542586049000000000 0            0           3       2        0       5                   0       0    0
1542586059000000000 0            0           3       1        0       5                   0       0    1
1542586069000000000 0            0           2       1        0       3                   0       0    0
1542586079000000000 0            0           3       1        0       5                   0       0    1
1542586089000000000 0            0           2       1        0       3                   0       0    0
1542586099000000000 0            0           3       1        0       4                   0       0    0
1542586109000000000 0            0           4       1        0       5                   0       0    0
1542586119000000000 0            0           2       1        0       3                   0       0    0
1542586129000000000 0            0           3       1        0       4                   0       0    0
1542586139000000000 0            0           2       1        0       4                   0       0    1
1542586149000000000 0            0           4       1        0       5                   0       0    0
1542586159000000000 0            0           2       1        0       3                   0       0    0
1542586169000000000 0            0           3       1        0       5                   0       0    1
1542586179000000000 3            0           2       1        0       6                   0       0    0
1542586189000000000 0            0           3       0        0       3                   0       0    0
1542586199000000000 0            0           4       0        0       4                   0       0    0
1542586209000000000 0            0           3       1        0       4                   0       0    0
1542586219000000000 0            0           3       1        0       4                   0       0    0
1542586229000000000 0            0           3       1        0       5                   0       0    1
1542586239000000000 0            0           2       1        0       3                   0       0    0
1542586249000000000 0            0           2       1        0       3                   0       0    0
1542586259000000000 0            0           4       1        0       5                   0       0    0
1542586269000000000 0            0           4       1        0       5                   0       0    0
1542586279000000000 0            0           3       1        0       4                   0       0    0
1542586289000000000 0            0           4       1        0       5                   0       0    0
```
