### ISSUE TITLE
Feature Request: Add ability to add subnet / IP range to ping input

### ISSUE THREAD

**Issue by n1nj4888** [influxdata/telegraf#5020]
## Feature Request

Feature Request: Add ability to add subnet / IP range to ping input

### Proposal:
Would it be possible to add the ability to ping a subnet in the ping input? This would take the parameter of something like xxx.yyyy.zzzz.0/24 and recursively ping through the subnet hosts so, for example, all of the hosts on the internal LAN could be monitored via ping?

For internal LAN hosts, I think this is currently possible by entering all of the LAN host IPs explicitly in the urls config item but it would be useful to also be able to specify the short-hand subnet? 

### Current behavior:
All ping hosts have to be added explicitly to the urls config parameter 

### Desired behavior:
A subnet / range of IPs could be added to the urls config parameter

### Use case: [Why is this important (helps with prioritizing requests)]
To more easily configure the ping input to ping all hosts on the local LAN

**Comment by glinton** [comment]
I believe something similar has been brought up before, though i think it was with the snmp plugin. If I'm remembering correctly, it was denied due to the ease of abusing it, though more likely just a lack of interest/use cases for it. We'll think on this though

**Comment by danielnelson** [comment]
This could definitely get out of hand from a cardinality point of view, and another problem would be that this plugin fork/exec's the ping command and would need to do it once per address in the range.  So even though you could fill out the urls option with all the hosts it probably would be very expensive.

At the very least we need to implement a native Go ping as an option for this https://github.com/influxdata/telegraf/issues/2833, but even then I'm not crazy about the idea of supporting CIDR notation because it won't work well when using the ping command.

**Comment by n1nj4888** [comment]
Thanks for the comments guys,

@danielnelson sounds right that it would likely be too costly to do a subnet ping across each device since not sure ping can do this in parallel? It can do a broadcast ping to x.x.x.255/x.x.x.0 but most devices default to not responding to broadcast pings where they would respond to a normal direct ping...

I have also raised Feature Request #5042 (Add nmap as supported input plugin) as nmap is seemingly able to much more quickly return the current devices, hostnames, IPs, MAC address, MAC vendor and, importantly, latency, of each of the hosts detected on the network... I guess that this is ultimately the information I was after and this is likely to be much quicker than a recursive ping...

**Comment by Hipska** [comment]
Support could be added by using `fping` instead of `ping` as command to execute.

**Comment by reimda** [comment]
In @Hipska's comment he mentioned running nmap through the exec plugin https://github.com/influxdata/telegraf/issues/5042#issuecomment-1012970863. Using nmap with the exec plugin is one way to ping a range of hosts with telegraf. The metric format isn't exactly the same as telegraf's ping input plugin, but it allows you to use all of nmap's features.

Using nmap's xml output (`-oX -`) with telegraf's xml parser means there's less reason to have a dedicated nmap plugin or to add the ability to the ping plugin to ping a range.

Here's an example.

```toml
[agent]
  interval = "10s"
  flush_interval = "10s"
  omit_hostname = true

[[inputs.exec]]
  commands = ["nmap -sP 192.168.0.1-254 -n -oX -"]
  timeout = "8s"
  data_format = "xml"
  [[inputs.exec.xpath]]
    timestamp = "/nmaprun/@start"
    timestamp_format = "unix"
    metric_selection = "/nmaprun/host"
    [inputs.exec.xpath.tags]
      host = "address/@addr"
    [inputs.exec.xpath.fields]
      foo = "123"
      state = "status/@state"
      roundTrip = "times/@srtt"
  
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
```
