### ISSUE TITLE
Add tag by BasicStats aggregator

### ISSUE THREAD

**Issue by akamac** [influxdata/telegraf#5028]
### Proposal:
Add specific tag to metrics produced by BasicStats aggregator, like `aggr = basicstats`
### Current behavior:
> No tags are applied by this aggregator.
```
system,host=tars load1=1 1475583980000000000
system,host=tars load1=1 1475583990000000000
system,host=tars load1_count=2,load1_max=1,load1_min=1,load1_mean=1,load1_sum=2,load1_s2=0,load1_stdev=0 1475584010000000000
```
### Desired behavior:
```
system,host=tars load1=1 1475583980000000000
system,host=tars load1=1 1475583990000000000
system,host=tars,aggr=basicstats load1_count=2,load1_max=1,load1_min=1,load1_mean=1,load1_sum=2,load1_s2=0,load1_stdev=0 1475584010000000000
```
### Use case:
I would like to do basic downsampling in Telegraf and put aggregated values to another retention policy, all without using CQ / Kapacitor. Once the tag is applied, one can use `[outputs.influxdb.tagpass]` to route the metric to appropriate output.

If there is another way to achieve that with Telegraf only, feel free to share.

**Comment by danielnelson** [comment]
Should be able to do this using the [tags](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#aggregator-configuration) option:
```toml
[[aggregators.basicstats]]
  period = "30s"
  drop_original = false
  stats = ["count","min","max","mean","stdev","s2","sum"]
  [aggregators.basicstats.tags]
    aggr = "basicstats"
```
