### ISSUE TITLE
Memory Leak in 1.9.0

### ISSUE THREAD

**Issue by cxcv** [influxdata/telegraf#5035]
Hi there,

looks like telegraf 1.9.0 introduced some memory leak, I see a steady growth here:

![image](https://user-images.githubusercontent.com/234864/49000160-07338380-f159-11e8-92e9-9abb4ba64732.png)

### Relevant telegraf.conf:
```toml
[global_tags]
  foo  = "bar"
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "5s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "server.example.com"
  omit_hostname = false
[[outputs.influxdb]]
  urls = ['https://influxdb.example.com:8086']
  database = "telegraf"
  username = "telegraf"
  password = "s3cr3t"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.kernel_vmstat]]
[[inputs.net]]
[[inputs.netstat]]
```

### System info:

Telegraf 1.9.0 release on Debian 9 AMD64

### Steps to reproduce:

1. start telegraf (in mostly the default config)
2. watch memory consumption over time

### Expected behavior:
memory consumption should be steady

### Actual behavior:
memory consumption grows

### Additional info:
Growth rate is ~1.5 MB/hour
