### ISSUE TITLE
Basicstats aggregator (1.9.0) failing to "drop_original"

### ISSUE THREAD

**Issue by glinton** [influxdata/telegraf#5084]
### Relevant telegraf.conf:
```toml
[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  omit_hostname = true

[[inputs.exec]]
  command = "echo -en '{\"verb\":\"GET\",\"request\":\"/time/to/awesome\", \"status\":200}'"
  data_format = "json"
  json_string_fields = ["request"]
  tag_keys = ["verb"]
  timeout = "1s"

[[aggregators.basicstats]]
	period = "5s"
	stats = ["count"]
	name_suffix = "_count"
	drop_original = true

[[outputs.file]]
```
### System info:

Telegraf 1.8.3 and 1.9.0
Ubuntu 18.04

### Steps to reproduce:

1. `telegraf-1.9.0 --config telegraf.conf`

### Expected behavior:
```
exec_count,verb=GET status_count=6 1543938920000000000
exec_count,verb=GET status_count=5 1543938925000000000
exec_count,verb=GET status_count=5 1543938930000000000
exec_count,verb=GET status_count=5 1543938935000000000
exec_count,verb=GET status_count=5 1543938940000000000
exec_count,verb=GET status_count=5 1543938945000000000
exec_count,verb=GET status_count=5 1543938950000000000
exec_count,verb=GET status_count=5 1543938955000000000
exec_count,verb=GET status_count=5 1543938960000000000
exec_count,verb=GET status_count=5 1543938965000000000
exec_count,verb=GET status_count=5 1543938970000000000
```

### Actual behavior:
```
exec_count,verb=GET status_count=5 1543938854000000000
exec_count,verb=GET status_count=5 1543938859000000000
exec_count,verb=GET status_count=5 1543938864000000000
exec_count,verb=GET status_count=5 1543938869000000000
exec_count,verb=GET status_count=5 1543938874000000000
exec,verb=GET request="/time/to/awesome",status=200 1543938874000000000
exec_count,verb=GET status_count=4 1543938879000000000
exec,verb=GET request="/time/to/awesome",status=200 1543938879000000000
exec_count,verb=GET status_count=4 1543938884000000000
exec,verb=GET request="/time/to/awesome",status=200 1543938884000000000
```
