### ISSUE TITLE
telegraf influx communication error help wanted

### ISSUE THREAD

**Issue by Thomas-van-Dijk** [influxdata/telegraf#5147]
### System info:
docker-compose:
```yaml
version: '3'

services:
  telegraf:
    image: telegraf:latest
    volumes:
    - ./telegraf/telegraf.conf:/merged/etc/telegraf/telegraf.conf:ro
    depends_on:
    - influxdb
    environment:
      INFLUXDB_URL: http://influxdb:8086
    ports:
    - "092:8092/udp"
    - "094:8094"
    - "8125:8125/udp"
    links:
    - influxdb
  influxdb:
    image: influxdb:latest
    volumes:
    - ./influxdb/data:/var/lib/influxdb
    ports:
    - "8086:8086"
  chronograf:
    image: chronograf:latest
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
    - "8888:8888"
    links:
    - influxdb
    - kapacitor
  kapacitor:
    image: kapacitor:latest
    volumes:
    - ./etc/kapacitor.conf:/merged/etc/kapacitor/kapacitor.conf:ro
    - ./var/kapacitor:/var/lib/kapacitor
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
    - influxdb
    ports:
    - "9092:9092"

  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb
    entrypoint:
    - influx
    - -host
    - influxdb
    links:
    - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: kapacitor
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
    - kapacitor
```

### Steps to reproduce:
docker-compose -f docker-compose-tick.yml logs -f telegraf
-->
telegraf_1       | 2018-12-14T14:12:20Z E! [agent] Error writing to output [influxdb]: could not write any address

### Expected behavior:
give no errror
### Actual behavior:
error

### Additional info:

[Include gist of relevant config, logs, etc.]

any help is appreciated!
