### ISSUE TITLE
The exclude directive does not work correctly if the label contains a symbol "_"

### ISSUE THREAD

**Issue by abhinand-tw** [influxdata/telegraf#5183]
### Relevant telegraf.conf:

# Configuration for telegraf agent
```toml
[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 1000

  metric_buffer_limit = 10000

  collection_jitter = "1s"

  flush_interval = "10s"
  flush_jitter = "5s"

  precision = "1s"

  debug = false
  quiet = false
  logfile = ""

  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

[[outputs.prometheus_client]]
  listen = ":9273"

  expiration_interval = "60s"

  path = "/metrics"

  collectors_exclude = ["gocollector", "process"]



###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]

  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

[[inputs.filestat]]
  files = ["/etc/telegraf/telegraf.conf", "/var/log/**.log"]
  md5 = false


[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"

  gather_services = false

  container_names = []

  container_name_include = []
  container_name_exclude = []


  timeout = "15s"

  perdevice = false
  total = true

  docker_label_include = []
  docker_label_exclude = ["traefik*", "com_docker*", "org*"]
```

### System info:
Telegraf version 1.7.4-alpine docker container

OS: Ubuntu 16.04

### Steps to reproduce:

1. Start telegraf docker image with this config file

## Expected behavior:
All records with "com_docker*" not exist in metrics strings

### Actual behavior:

If I write in config file:
docker_label_exclude = ["com_docker*"]
Don't work and metrics strings contain record with "com_docker*", for example:
"com_docker_compose_project", "com_docker_compose_service".

### Additional info:

If I write in config file:
docker_label_exclude = ["com*"]
Work ok, metrics strings not contain any record with "com*"

[Include gist of relevant config, logs, etc.]
