### ISSUE TITLE
Fieldpass Configuration on Aggregators Filters Original Metrics

### ISSUE THREAD

**Issue by KarstenSchnitter** [influxdata/telegraf#5209]
When configuring a 'fieldpass' property on an aggregator, all metrics including the originals are filtered. Previously the originals where passed on unaltered.

### Relevant telegraf.conf:
```toml
[[inputs.net]]
  fieldpass = ["bytes_recv", "bytes_sent"]

[[aggregators.minmax]]
  period = "30s"
  drop_original = false
  fieldpass = ["bytes_recv"]
```
### System info:

failure noticed in Telegraf 1.9.1, 
previous behaviour verified with Telegraf 1.8.1

### Steps to reproduce:

Start Telegraf with above configuration. You can choose a different input if you adjust the fields accordingly.

### Expected behavior:

original metrics are passed unaltered, aggregator is applied to filtered fields

```
net,host=redacted,interface=en0 bytes_sent=100i,bytes_recv=1000i 1546427377100000000
net,host=redacted,interface=en0 bytes_recv=2000i,bytes_sent=200i 1546427377200000000
...
net,host=redacted,interface=en0 
bytes_recv_max=2000i,bytes_recv_min=1000i 1546427377300000000
```

### Actual behavior:

original metrics and aggregations only contain filtered fields from aggregator

```
net,host=redacted,interface=en0 bytes_recv=1000i 1546427377100000000
net,host=redacted,interface=en0 bytes_recv=2000i 1546427377200000000
...
net,host=redacted,interface=en0 
bytes_recv_max=2000i,bytes_recv_min=1000i 1546427377300000000
```
### Additional info:

full config used:

```toml
[agent]
  interval = "10s"
  debug = true
  quiet = false
  logfile = "./telegraf.log"

[[outputs.file]]
   data_format = "influx"
   files = ["stdout"]
   
[[inputs.net]]
  fieldpass = ["bytes_recv", "bytes_sent"]

[[aggregators.minmax]]
  period = "30s"
  drop_original = false
  fieldpass = ["bytes_recv"]
```
