### ISSUE TITLE
Timestamp always results in seconds

### ISSUE THREAD

**Issue by asdptkt** [influxdata/telegraf#5332]
### Relevant telegraf.conf:

```toml
[global_tags]

[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "1s"
  flush_interval = "5s"
  flush_jitter = "1s"
  precision = "1ms"
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[outputs.http]]
  url = "http://recorder:8080/v1/data"
  timeout = "5s"
  method = "POST"
  data_format = "json"

  [outputs.http.headers]
    Content-Type = "application/json"
    Authorization = "Bearer mytoken"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mqtt:1883"]
  qos = 2
  connection_timeout = "5s"
  topics = [
    "$share/telegraf/data",
  ]
  persistent_session = true
  client_id = "admin"
  username = "admin"
  password = "admintoken"
  data_format = "json"
  tag_keys = [
    "id"
  ]
```

### System info:

Telegraf 1.9.2-Alpine via Docker

### Expected behavior:

Timestamp in milliseconds.

### Actual behavior:

Timestamp in seconds.

### Additional info:
I think this is parser problem because if I change the output data format to `influx` the resulting timestamp will be in nanoseconds.
