### ISSUE TITLE
[inputs.neptune_apex] - Return status messages as numerical values rather than as strings

### ISSUE THREAD

**Issue by chvvkumar** [influxdata/telegraf#5377]
### Proposal:
Return status messages as numerical values rather than text. This allows for creation of Grafana single stat tiles with background coloring based off of numerical values. 
### Current behavior:
Currently, the values for outlet status are returned as strings of text (ex. AON, AOF, ON, OFF). 
### Desired behavior:
If these statuses are sent to Influxdb as numerical values like below for example:
AON = 001
AOF = 002
ON = 003
OFF = 004

In grafana these can be mapped to thresholds for singlestat panel background colors. For example

AON = 001 = Green
AOF = 002 = Yellow
ON = 003 = Green
OFF = 004 = Red

### Use case: [Why is this important (helps with prioritizing requests)]

This makes viewing outlet status at a glance easier from across the room. From my current dashboard as an example:

![Neptune Apex Grafana Dashboard](https://i.imgur.com/0iA8Fd3.png)

Coloring the status panels based on outlet status makes it easy to tell the status from a distance. This will also allow us to use custom status messages (by mapping these numerical values to strings) rather than the four builtin messages.

**Comment by danielnelson** [comment]
We could potentially add a `state_code` with a mapping of these values, however, I'm not sure that we have a complete list of all values.  @MaxRenaud what do you think?

It is possible to do this mapping in Telegraf with the `enum` processor:
```toml
[[processors.enum]]
  namepass = ["neptune_apex"]
  [[processors.enum.mapping]]
    field = "state"
    dest = "state_code"
    default = 0
    [processors.enum.mapping.value_mappings]
      AON = 1
      AOF = 2
      ON = 3
      OFF = 4
```
