### ISSUE TITLE
CloudWatch Input: Use GetMetricData vs. GetMetricStatistics API

### ISSUE THREAD

**Issue by druchoo** [influxdata/telegraf#5420]
## Feature Request
Would it be possible to use GetMetricData vs. GetMetricStatistics calls for CloudWatch input?

GetMetricData is more efficient vs. GetMetricStatistics and is [recommended by AWS](https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-getmetricdata-api/). Switching calls will save money and allow large namespaces to be consumed more efficiently and timely.

From AWS support:
> The Service Team found that in the third party tool that was provided, the Go program is making GetMetricStatistics API calls instead of GetMetricData. They recommend using GetMetricData since it's always efficient and it's the recommended solution for metric retrieval over GetMetricStatistics. GetMetricData is also more cost effective. You can ask for more data points for a single metric by using GetMetricData rather than by using GetMetricStatistics. To get the same number of data points, you must perform 70 GetMetricStatistics calls. Here is a reference with more information: https://aws.amazon.com/premiumsupport/knowledge-center/cloudwatch-getmetricdata-api/

### Proposal:
Use GetMetricData vs. GetMetricStatistics calls for CloudWatch input.

### Current behavior:
GetMetricStatistics calls are used

### Desired behavior:
Use GetMetricData calls

### Use case: [Why is this important (helps with prioritizing requests)]
Real example:

AWS/SQS in one of our accounts has ~40k MetricName's which takes ~15m to complete using:

```TOML
[[inputs.cloudwatch]]
delay = "1m"
fieldpass = ["approximate_number_of_messages_visible_maximum"]
interval = "5m"
namespace = "AWS/SQS"
period = "5m"
ratelimit = 20
```

For the sake of argument, let's say we need all that data. Rate limit can be increased, but I also have 12 other namespaces that need to be consumed.

Rates can be increased on AWS side but if consuming can be more efficient, that would be preferred.

**Comment by danielnelson** [comment]
Yeah, I think this could be done and it appears it would help quite a lot.

**Comment by glinton** [comment]
@druchoo Does the Telegraf config for your account with ~40k MetricNames use Dimensions at all, whether unique per metric or the same for all 40k Metrics? Is it possible for you to paste a portion of your config file, or some fabricated example that simulates your current config? Thanks.

**Comment by druchoo** [comment]
@glinton, Here's our complete non prod configs.

https://gist.github.com/druchoo/1f2fdd38df415d6b49331def0fc50499

**Comment by glinton** [comment]
When you list a namespace in your config without any further metric/dimension filtering, are you intending to get an aggregate of the namespace per metric, or are you still looking for individual metrics?

Ex:
```toml
[[inputs.cloudwatch]]
  delay = "1m"
  interval = "1m"
  namespace = "AWS/EC2"
  period = "1m"
  profile = "dev"
  ratelimit = 20
  region = "us-east-1"
  [inputs.cloudwatch.tags]
    environment = "dev"
```
Are you expecting aggregates for an individual instance?:
```
cloudwatch_aws_ec2,instance_id=i-abc123,region=us-west-2 status_check_failed_sum=0,status_check_failed_average=0,status_check_failed_maximum=0,status_check_failed_minimum=0,status_check_failed_sample_count=1 1552081080000000000
cloudwatch_aws_ec2,instance_id=i-def456,region=us-west-2 status_check_failed_sum=0,status_check_failed_average=0,status_check_failed_maximum=0,status_check_failed_minimum=0,status_check_failed_sample_count=1 1552081080000000000
...
```
or an aggregate of all instances?:
```
cloudwatch_aws_ec2,region=us-west-2 status_check_failed_sum=0,status_check_failed_average=0,status_check_failed_maximum=0,status_check_failed_minimum=0,status_check_failed_sample_count=100 1552081080000000000
```
