### ISSUE TITLE
Debug a new output plugin 

### ISSUE THREAD

**Issue by littlespace** [influxdata/telegraf#5422]
Hi,

If I create a new output plugin, how can i run or test the plugin to make sure it does the job.

Thanks

**Comment by glinton** [comment]
You import it into `plugins/outputs/all/all.go`, build telegraf with your code (`make telegraf` if you have `make` installed) then create a configuration file.

```toml
[[outputs.mynewoutputplugin]]
  option="allthethings"
```

Also, for general discussion, please use the [community forums](https://community.influxdata.com/)
