### ISSUE TITLE
 Telegraf causes server system load to rise

### ISSUE THREAD

**Issue by navyaijm2017** [influxdata/telegraf#5423]
### Relevant telegraf.conf:

[ops@instance-61qmogd4-3 telegraf]$ tree  /etc/telegraf/
```
/etc/telegraf/
├── telegraf.conf
└── telegraf.d
    ├── diskcheck.conf
    ├── exec.conf
    ├── linux.conf
    └── local_tcp.conf
1 directory, 5 files
```

[ops@instance-61qmogd4-3 telegraf]$ cat /etc/telegraf/telegraf.conf  |grep -v '#'|more
```toml
[global_tags]
  ip= "172.xx.xxx.82"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://172.xx.xxx.5:8086"]
```

[ops@instance-61qmogd4-3 telegraf]$ cat /etc/telegraf/telegraf.d/linux.conf |grep -v "#"
```toml
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  fielddrop = ["time_*"]

- 1. 

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
[[inputs.netstat]]
[[inputs.interrupts]]
[[inputs.linux_sysctl_fs]]
```

### Steps to reproduce:

All of our servers (several hundred), as well as new servers that don't run any applications above, will increase the system load every 7 hours or so. I will stop the system's crontab, it will still be like that, and the system load will increase. At the time, the CPU and disk IO of the machine have not changed, so I would like to ask is there a timed task inside telegraf?
