### ISSUE TITLE
inputs.socket_listener TCP + TLS

### ISSUE THREAD

**Issue by BrudnyHarry** [influxdata/telegraf#5448]
### Relevant telegraf.conf:
```toml
[global_tags]
 
[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"

  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""

  debug = false
  quiet = false
  logfile = ""

  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
   urls = ["http://127.0.0.1:8086"]

   database = "serwery"

   username = "user"
   password = "pass"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

 [[inputs.socket_listener]]
    service_address = "tcp://:8094"
    max_connections = 1024
    read_timeout = "30s"
    tls_cert = "/etc/pki/server-cert.pem"
    tls_key  = "/etc/pki/server-key.pem"
    tls_allowed_cacerts = ["/etc/pki/ca.pem"]
    data_format = "influx"
```

### System info:
Telegraf 1.9.0
4.9.0-3-amd64 Debian 4.9.30-2+deb9u5

### Steps to reproduce:

1. Put in /etc/pki/  files: ca.pem , cert.pem , key.pem  (self signed certificate)
2. Set input.socket_listener section in telegraf.conf
3. Restart telegraf

### Expected behavior:
Information that listening on tcp:8094 is set or if not a error message why
### Actual behavior:
There will be no information that something is listening on port 8094 and if checked with netstat -tpl nothing with that port will be presented

###Additional info
When I set socket_listener without tls options it work and is presented in netstat -tpl

**Comment by danielnelson** [comment]
@BrudnyHarry I am adding the logging in #5454, there should already be an error displayed if the socket cannot be listened on though, so I can't explain why its not listed in netstat.  I tested locally with TLS and it seems to be working for me:
```toml
[[inputs.socket_listener]]
  service_address = "tcp://:8094"
  tls_cert = "/home/dbn/.ssl/server/cert.pem"
  tls_key  = "/home/dbn/.ssl/server/key.pem"
  tls_allowed_cacerts = ["/home/dbn/.ssl/ca/cacert.pem"]
```

Tested sending line protocol with:
```
openssl s_client -connect localhost:8094 -CAfile /home/dbn/.ssl/ca/cacert.pem -cert /home/dbn/.ssl/client/cert.pem -key /home/dbn/.ssl/client/key.pem
```

Can you test with this build of the pull request and show the output:
- [telegraf_1.10.0~f67f5c98-0_amd64.deb](https://27795-33258973-gh.circle-artifacts.com/0/build/linux/amd64/telegraf_1.10.0~f67f5c98-0_amd64.deb)
