### ISSUE TITLE
Invalid telegraf cast for bigger numbers than int32 

### ISSUE THREAD

**Issue by fernandobeltranjsc** [influxdata/telegraf#5491]
Reproduced in both input.exec and inputs.win_perf_counters plugins

### Relevant telegraf.conf:

[[inputs.exec]]
  interval = "60s"
  name_override = "win_proc2"
  commands = ["powershell C:/JSC/GOLEM/Powershell/GetProcessMemoryPerformanceCounters.ps1"]
  timeout = "59s"
  data_format = "influx"  
  [inputs.exec.tags]
    destination_database = "host"
    server_type = "FARM"

[[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = [
      "% Processor Time",
      "Handle Count",
      "Private Bytes",
      "Thread Count",
      "Virtual Bytes",
      "Working Set",
      "IO Read Bytes/sec",
      "IO Read Operations/sec",
      "IO Write Bytes/sec",
      "IO Write Operations/sec"
      ]
    Instances = ["*"]
    Measurement = "win_proc"
    

### System info:

Tested on Telegraf 1.7.0 and 1.9.4 same behaviour
Windows Server 2012R2 64 bits

### Steps to reproduce:

Get any metric greater than a int32 value , 4294967295

Powershell output 
win_proc,instance=svc_ds,objectname=Process Private_Bytes=**7421108224**

Telegraf output
win_proc,instance=svc_ds,objectname=Process Private_Bytes=**4294967295**

### Expected behavior:

Telegraf output
win_proc,instance=svc_ds,objectname=Process Private_Bytes=**7421108224**

### Actual behavior:

Telegraf output
win_proc,instance=svc_ds,objectname=Process Private_Bytes=**4294967295**

### Additional info:

Data captured with wireshark to see the telegraf output

![2019-02-22_13-10-59](https://user-images.githubusercontent.com/17269717/53472019-dc620f80-3a66-11e9-8ef9-7e749f77de70.png)

**Comment by danielnelson** [comment]
I'm unable to reproduce this issue, can you try the config below and see if the output matches your system?
```
2019-02-28T07:56:48Z I! Starting Telegraf 1.9.5
2019-02-28T07:56:48Z I! Loaded inputs: inputs.exec inputs.win_perf_counters
2019-02-28T07:56:48Z I! Loaded aggregators:
2019-02-28T07:56:48Z I! Loaded processors:
2019-02-28T07:56:48Z I! Loaded outputs: file
2019-02-28T07:56:48Z I! Tags enabled:
2019-02-28T07:56:48Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"", Flush Interval:10s
win_mem,instance=*,objectname=Memory Available_Bytes=14874497024 1551340611000000000
cpu value=9999999999999999i 1551340610000000000
```

```toml
[agent]
  omit_hostname = true

[[inputs.exec]]
  commands = ["test.bat"]
  data_format = "influx"

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Counters = [
    "Available Bytes",
    ]
    Instances = ["*"]
    Measurement = "win_mem"
```

test.bat
```
@echo off
echo cpu value=9999999999999999i
```
