### ISSUE TITLE
Undefined but requested input: ouput - no line indication

### ISSUE THREAD

**Issue by darox** [influxdata/telegraf#5494]
Ubuntu 16.04
Telegraf 1.8.2

I made some config adjustments to my telegraf.conf in order to use the tagpass feature. Now it throws the following error:
2019/02/27 15:18:26 E! Error parsing /etc/telegraf/telegraf.conf, Undefined but requested input: ouputs
Without any indication on which line the issue is happening. 

My config:
```toml
[[outputs.influxdb]]
  [outputs.influxdb.tagdrop]
    influxdb_database = ["*"]

[[outputs.influxdb]]
   tagexclude = ["influxdb_database"]       
  [ouputs.influxdb.tagpass]
    influxdb_database = ["e2e_service_mon"]

[[inputs.ping]]
  urls = ["amazon.com"]
  [inputs.ping.tags]
        tag1 = "house"
        tag2 = "tree"
        influxdb_database = "e2e_service_mon"
```
