### ISSUE TITLE
Prometheus output plugin error.

### ISSUE THREAD

**Issue by vaspas** [influxdata/telegraf#5511]
### Relevant telegraf.conf:
```toml
[agent]
  interval = "10s"
  round_interval = true

  metric_buffer_limit = 1000
  flush_buffer_when_full = true

  collection_jitter = "0s"

  flush_interval = "10s"
  flush_jitter = "0s"

  debug = true
  quiet = false
  logfile = "/logs/telegraf/telegraf.log"

[[aggregators.valuecounter]]
  period = "300s"
  drop_original = false
  fields = ["count"]

[[outputs.prometheus_client]]
  listen = ":18888"
  collectors_exclude = ["gocollector", "process"]

 [[aggregators.basicstats]]
   period = "300s"
   drop_original = false
   stats = ["count","min","max","mean","stdev","s2","sum"]
                           
[[inputs.statsd]]
  protocol = "udp"
  max_tcp_connections = 250
  tcp_keep_alive = false
  service_address = ":8125"
  delete_gauges = true
  delete_counters = true
  delete_sets = true
  delete_timings = true
  percentiles = [90,99]
  metric_separator = "."
  parse_data_dog_tags = true
  allowed_pending_messages = 10000
  percentile_limit = 1000

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  fieldpass = ["usage_user*"]

[[inputs.disk]]
  fielddrop = ["inodes*","total*","used*"]
```

### System info:

Telegraf version 1.10.0-rc1
OS Windows Server 2012 RC2

### Steps to reproduce:
1. Start telegraf.
2. Get metrics from http://x.x.x.x:18888/metrics

### Expected behavior:
Metrics returned after request.

### Actual behavior:
No metrics, but errors in telegraf log.

### Additional info:
Works fine in 1.9.4 version.

[Include gist of relevant config, logs, etc.]
Telegraf log:
```
2019-02-28T11:03:43Z I! http: panic serving x.x.x.x:57654: runtime error: invalid memory address or nil pointer dereference
goroutine 60 [running]:
net/http.(*conn).serve.func1(0xc000075ae0)
	C:/test/Go/src/net/http/server.go:1746 +0xd7
panic(0x1f160a0, 0x3f7c2c0)
	C:/test/Go/src/runtime/panic.go:513 +0x1c7
github.com/influxdata/telegraf/vendor/github.com/prometheus/client_golang/prometheus.processMetric(0x0, 0x0, 0xc0005117c0, 0xc0005117f0, 0x0, 0x7ffbfee6fc00, 0x0)
	C:/test/src/github.com/influxdata/telegraf/vendor/github.com/prometheus/client_golang/prometheus/registry.go:579 +0x41
github.com/influxdata/telegraf/vendor/github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc00012af50, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/test/src/github.com/influxdata/telegraf/vendor/github.com/prometheus/client_golang/prometheus/registry.go:507 +0xbda
github.com/influxdata/telegraf/vendor/github.com/prometheus/client_golang/prometheus/promhttp.HandlerFor.func1(0x26cb3c0, 0xc00015e2a0, 0xc0003c8200)
	C:/test/src/github.com/influxdata/telegraf/vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go:105 +0x5d
net/http.HandlerFunc.ServeHTTP(0xc00012aff0, 0x26cb3c0, 0xc00015e2a0, 0xc0003c8200)
	C:/test/Go/src/net/http/server.go:1964 +0x4b
github.com/influxdata/telegraf/plugins/outputs/prometheus_client.(*PrometheusClient).auth.func1(0x26cb3c0, 0xc00015e2a0, 0xc0003c8200)
	C:/test/src/github.com/influxdata/telegraf/plugins/outputs/prometheus_client/prometheus_client.go:153 +0xa4
net/http.HandlerFunc.ServeHTTP(0xc0003a8220, 0x26cb3c0, 0xc00015e2a0, 0xc0003c8200)
	C:/test/Go/src/net/http/server.go:1964 +0x4b
net/http.(*ServeMux).ServeHTTP(0xc0005214d0, 0x26cb3c0, 0xc00015e2a0, 0xc0003c8200)
	C:/test/Go/src/net/http/server.go:2361 +0x12e
net/http.serverHandler.ServeHTTP(0xc000118f70, 0x26cb3c0, 0xc00015e2a0, 0xc0003c8200)
	C:/test/Go/src/net/http/server.go:2741 +0xb2
net/http.(*conn).serve(0xc000075ae0, 0x26ce6c0, 0xc0001136c0)
	C:/test/Go/src/net/http/server.go:1847 +0x64d
created by net/http.(*Server).Serve
	C:/test/Go/src/net/http/server.go:2851 +0x2fc
```
