### ISSUE TITLE
kube_inventory RBAC ClusterRole aggregation documentation issue.

### ISSUE THREAD

**Issue by iramiller** [influxdata/telegraf#5562]
On the readme.md the example cluster role is as follows:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influx:telegraf
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
      rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: [] # Rules are automatically filled in by the controller manager.
```
But this match label expression does  not appear to be correct.  A list of labels to match is an `AND` expression so I updated it to the following to make the aggregation work as intended:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: influx:telegraf
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: [] # Rules are automatically filled in by the controller manager.
```
Note the two separate matchLabel expressions.  HTH.
