### ISSUE TITLE
Output plugin "file" does not close the file after flush.

### ISSUE THREAD

**Issue by Nyyr1** [influxdata/telegraf#5581]
### Relevant telegraf.conf:
```toml
[global_tags]
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.file]]
  files = ["/tmp/metrics.out"]
  data_format = "json"
[[inputs.statsd]]
  protocol = "udp"
  max_tcp_connections = 250
  tcp_keep_alive = false
  service_address = ":8125"
  delete_gauges = true
  delete_counters = true
  delete_sets = true
  delete_timings = true
  percentiles = [90]
  metric_separator = "."
  parse_data_dog_tags = false
  allowed_pending_messages = 10000
  percentile_limit = 1000
```

### System info:

telegraf-1.10.0-1.x86_64
NAME="Amazon Linux AMI"
VERSION="2015.09"
Linux 66185ca101a9 4.1.17-22.30.amzn1.x86_64 #1 SMP Fri Feb 5 23:44:22 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce:

1. echo "statsd.test.metric:a|s" | ncat -u localhost 8125
2. wait for "flush_interval"
3. delete the file
4. wait for "flush_interval"
5. no new file appears

If you just truncate the file, the new metric does not appear till the file grows to its previous size (filled with zeros).

### Expected behavior:
If the file is deleted then at the end of the flush_interval new one appears with the new metric.

### Actual behavior:
See "Steps to reproduce".
