### ISSUE TITLE
Support closing environment variables in configuration file

### ISSUE THREAD

**Issue by bharathcp** [influxdata/telegraf#5646]
### Relevant telegraf.conf:
```toml
[[processors.rename]]
  [[processors.rename.replace]]
    measurement = "cloudwatch_foo-qual_$VPC_bar-_metrics"
    dest = "cloudwatch_foo_bar-_metrics"

```
### System info:

telegraf:1.10.1-alpine

### Steps to reproduce:

`rename.replace` processor does not process the measurements if the `measurement` value has a environment variable in the config.
