### ISSUE TITLE
Support --config-directory in Docker

### ISSUE THREAD

**Issue by kylerw** [influxdata/telegraf#5656]
## Feature Request

Would like an option to use --config-directory in docker rather than one telegraf.conf

### Proposal:
Map host/container directory and default config will be stored here and --config-directory used.

### Current behavior:
defaults to /etc/telegraf/telegraf.conf

### Use case: [Why is this important (helps with prioritizing requests)]

allows for cleaner management of plugins and other services

**Comment by danielnelson** [comment]
You can of course run the container with `--config-directory /etc/telegraf/telegraf.d` set, any arguments are passed to Telegraf.

I think this really boils down to deciding if the `--config-directory` option should have a default directory, which seems like a reasonable thing to me.

**Comment by glinton** [comment]
According to #5703, this has been ["put it on ice until we have time to revamp the config loading in depth."](https://github.com/influxdata/telegraf/pull/5703#discussion_r276448439)

**Comment by n1nj4888** [comment]
Hi Guys,

It seems, by default, the /etc/telegraf/telegraf.d/*.conf files are not picked up by the official telegraf image, only the /etc/telegraf/telegraf.conf file?

Is there anyway (for example an environment variable configured for the container) to get the telegraf service inside the docker image/container to load the .conf files from /etc/telegraf/telegraf.d/ in addition to the standard /etc/telegraf/telegraf.conf file?

Thanks!

**Comment by danielnelson** [comment]
You can run the container with `--config-directory /etc/telegraf/telegraf.d`.

**Comment by russorat** [comment]
For anyone else who comes across this while trying to use the `--config-directory` option with kubernetes (as i did), you need to also pass a dummy config file like so:

```
    spec:
      containers:
      - name: telegraf
        image: telegraf:1.12.3-alpine
        volumeMounts:
        - name: config-volume
          mountPath: /etc/telegraf.d
        command: ["telegraf"]
        args: ["--config","/etc/telegraf.d/dummy.conf","--config-directory","/etc/telegraf.d/"]
```
