### ISSUE TITLE
telegraf statsd input plugin with spaces in metric names are not supported with graphite parser

### ISSUE THREAD

**Issue by sravankorumilli** [influxdata/telegraf#5662]
apache flink in some cases has metric names with spaces & statsd doesn't have any limitation of not supporting whitespaces. But graphite parser, doesn't support that. Looked into the graphite parser code, it ignores the measurement name post space. Is there a better way of parsing statsd metrics with templates other than graphite? Thanks.

### System info:
Telegraf version : 1.10.0
OS : Mac OS X

### Steps to reproduce:

1. Start telegraf with statsd as input plugin 
2. echo "my service:1|c" | nc -w 1 -u localhost 8125

telegraf Configuration
```toml
[[inputs.statsd]]
  allowed_pending_messages = 10000
  delete_counters = true
  delete_gauges = true
  delete_sets = false
  delete_timings = false
  metric_separator = "-"
  parse_data_dog_tags = false
  percentile_limit = 1000
  percentiles = [
    50,
    95,
    99
  ]
  service_address = ":8125"

[[outputs.file]]
files = ["/tmp/metrics.out"]
data_format = "json"
```

### Expected behavior:
measurement name should be "my service"
### Actual behavior:
measurement name coming as "my"
