### ISSUE TITLE
logfmt input not parsing sample log

### ISSUE THREAD

**Issue by sawo1337** [influxdata/telegraf#5674]
### Relevant telegraf.conf:
```toml
[[inputs.file]]
  files = ["/var/log/test.log"]
  data_format = "logfmt"
  name_override = "logfmt"
```
### System info:

Telegraf 1.10 on Ubuntu and 1.10.11 on Windows

### Steps to reproduce:

1. ... create /var/log/test.log with the following contents:
```
method="GET",host="example.org",ts="2018-07-24T19:43:40.275Z",connect="4ms",service="8ms",status=200i,bytes=1653i
```
2. ... run telegraf

### Expected behavior:
metrics are parsed and stored in the logfmt measurement

### Actual behavior:
Nothing gets imported

### Additional info:
The debug mode is activated on the config, but no error messages are shown

**Comment by glinton** [comment]
I'm guessing your errors are going to a log file (you can verify in the `agent` section of your config file). The issue I see is that your log file isn't in `logfmt` format, it looks like almost complete influx line protocol. Try removing the `,`s (though I suspect this won't provide the metrics you're looking for):

```
## cat test.log
# method="GET",host="example.org",ts="2018-07-24T19:43:40.275Z",connect="4ms",service="8ms",status=200i,bytes=1653i

E! [inputs.file]: Error in plugin: logfmt syntax error at pos 108 on line 1: unexpected '='

## cat test.log
# method="GET" host="example.org" ts="2018-07-24T19:43:40.275Z" connect="4ms" service="8ms" status=200i bytes=1653i

logfmt service="8ms",status="200i",bytes="1653i",method="GET",host="example.org",ts="2018-07-24T19:43:40.275Z",connect="4ms" 1554304277000000000

**Comment by sawo1337** [comment]
I'm looking for a sample log that I can parse successfully, I've been looking at the examples at https://docs.influxdata.com/telegraf/v1.10/data_formats/input/logfmt/ and thought that is a valid sample log to parse?

I'm logging to a log file indeed, but can't see any errors there, here is the log output after few iterations:

2019-04-03T15:22:09Z I! Loaded inputs: file
2019-04-03T15:22:09Z I! Loaded aggregators: 
2019-04-03T15:22:09Z I! Loaded processors: 
2019-04-03T15:22:09Z I! Loaded outputs: influxdb
2019-04-03T15:22:09Z I! Tags enabled: host=nnn
2019-04-03T15:22:09Z I! [agent] Config: Interval:30s, Quiet:false, Hostname:"nnn", Flush Interval:30s
2019-04-03T15:22:09Z D! [agent] Connecting outputs
2019-04-03T15:22:09Z D! [agent] Attempting connection to output: influxdb
2019-04-03T15:22:09Z D! [agent] Successfully connected to output: influxdb
2019-04-03T15:22:09Z D! [agent] Starting service inputs
2019-04-03T15:23:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
2019-04-03T15:23:30Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
2019-04-03T15:24:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
2019-04-03T15:24:30Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 
2019-04-03T15:25:00Z D! [outputs.influxdb] buffer fullness: 0 / 10000 metrics. 

The contents of test.log are as follows:
service="8ms",status="200i",bytes="1653i",method="GET",host="example.org",ts="2018-07-24T19:43:40.275Z",connect="4ms" 1554304277000000000

**Comment by glinton** [comment]
![image](https://user-images.githubusercontent.com/2653109/55491892-86e3ca00-55f3-11e9-8261-e02cf6608740.png)
Ah, yes. So the first line in that example is the actual logfmt data:
```
method=GET host=example.org ts=2018-07-24T19:43:40.275Z connect=4ms service=8ms status=200 bytes=1653
```
The second is the influx line protocol data that gets output.

This is a complete telegraf config that parses logfmt data, and outputs to influx line protocol:
```toml
[agent]
  interval = "1s"
  flush_interval="1s"
  omit_hostname=true

[[inputs.exec]]
  command = "echo 'method=GET host=example.org ts=2018-07-24T19:43:40.275Z connect=4ms service=8ms status=200 bytes=1653'"
  data_format = "logfmt"
  name_override="logfmt"

[[outputs.file]]
  files = ["stdout"]
```

I'm going to close this as it's config related. If you require more assistance, refer to our community: https://community.influxdata.com/
