### ISSUE TITLE
 Infiniband Statistics Input

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#5686]
### Proposal:
Add a new plugin for ingesting Infiniband Statistics (available with Mellanox perfquery) including transmit/receive throughput, port counters (packets sent/received, etc.) and error counters.  https://community.mellanox.com/s/article/understanding-mlx5-linux-counters-and-status-parameters

### Current behavior:
No plugin exists

### Desired behavior:
Plugin exists

### Use case: [Why is this important (helps with prioritizing requests)]
user has several hundred linux hosts that they would like to gather these metrics on.

**Comment by russorat** [comment]
Here is an example of how the data is structured for infiniband:

```
[user@host counters]$ ls

excessive_buffer_overrun_errors  local_link_integrity_errors  port_rcv_constraint_errors  port_rcv_packets                 port_xmit_constraint_errors  port_xmit_packets  unicast_rcv_packets

link_downed                      multicast_rcv_packets        port_rcv_data               port_rcv_remote_physical_errors  port_xmit_data               port_xmit_wait     unicast_xmit_packets

link_error_recovery              multicast_xmit_packets       port_rcv_errors             port_rcv_switch_relay_errors     port_xmit_discards           symbol_error       VL15_dropped

[user@host counters]$ cat port_rcv_data

2827997279383

[user@host counters]$ pwd

/sys/class/infiniband/mlx5_5/ports/1/counters
```

**Comment by danielnelson** [comment]
The structure of this path is documented in the kernel [here](https://www.kernel.org/doc/Documentation/ABI/stable/sysfs-class-infiniband).

In the meantime, you can use the multifile plugin.  It would be a bit tedious as you would need to create a plugin for each port and device and specify all the fields, but the end result should be quite fast and give nicely structured results:
```toml
[[inputs.multifile]]
  name_override = "infiniband"
  base_dir = "/sys/class/infiniband"

  [inputs.multifile.tags]
    port = "1"
    device = "mlx5_5"

  [[inputs.multifile.file]]
    file = "mlx5_5/ports/1/counters/port_rcv_data"
    conversion = "int"

  [[inputs.multifile.file]]
    file = "mlx5_5/ports/1/counters/multicast_rcv_packets"
    conversion = "int"
```

Output would look like:
```
infiniband,device=mlx5_5,host=loaner,port=1 multicast_rcv_packets=42i,port_rcv_data=42i 1555358744000000000
```
