### ISSUE TITLE
input.github: undefined but requested

### ISSUE THREAD

**Issue by thibmaek** [influxdata/telegraf#5694]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "300s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://x.x.x.x:8086"]

  database = "telegraf"
  username = "xxxxx"
  password = "xxxxxxx"

[[inputs.github]]
	repositories = [
		"inthepocket/hubble-scripts",
		"inthepocket/hubble-sketch-plugin",
		"inthepocket/hubble-app",
	]

	access_token = "xxxxxx"
```

### System info:

- Telegraf 1.10.2 (git: HEAD 3303f5c3)
- Linux chilipie-kiosk 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

### Steps to reproduce:

1. Enable inputs.github like described here: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/github
2. Restart or test telegraf.conf

### Expected behavior:

Github input works

### Actual behavior:

Github input throws error when trying to start Telegraf

### Additional info:

```log
pi@chilipie-kiosk:/etc/telegraf$ telegraf --config ./telegraf.conf --test
2019-04-08T11:32:42Z I! Starting Telegraf 1.10.2
2019-04-08T11:32:42Z E! [telegraf] Error running agent: Error parsing ./telegraf.conf, Undefined but requested input: github
```
