### ISSUE TITLE
Add healthcheck output

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#5707]
### Proposal:
add the ability for load balancers to determine if a telegraf service is healthy via an http(s) endpoint that returns 200 for OK or not 200 for NOT_OK. 

### Current behavior:
no plugin exists

### Desired behavior:
this plugin would have the following capabilities:
 - the ability to configure a threshold for output buffers to be considered healthy. For example, if the buffer is >=90% full, the service is unhealthy
 - the plugin should expose a url on a configurable port and path
 - the plugin should get its information from the `internal` plugin
 - a threshold should be applied to each output buffer for each plugin, with the ability to specify a default if none exists

### Use case: [Why is this important (helps with prioritizing requests)]
this would enable telegraf to be used effectively behind a load balancer. today, there are workarounds, but this would allow health to be determined via buffer size, and reduce the probability that telegraf might drop metrics when the buffer size limit is reached.

**Comment by docmerlin** [comment]
the unhealthy would also need to be able to be specified as greater than or less than the threshhold.

**Comment by danielnelson** [comment]
Looking at this closer, here are some notes.

It will be an unfortunate implementation if it only works with `internal`, because we will have no way to trigger the output, would need to special case the output.  I think it makes sense to try to do some limited metric selection and thresholding.

Are ratio's a requirement?  We could do something like this without a ratio, you would need to know the buffer_limit to set the right buffer_size. Sounds bad but it is set statically, so it would be doable:
```toml
[[outputs.health]]
  service_address = ":8080"

  [[outputs.health.check]]
    field = "buffer_size"
    gt = 42.0
    ## other comparisons
    # lt = 42
    # le = 42
    # ge = 42
    # eq = 42

    ## any of the normal "selector" metric filters
    # namepass = "internal_write"
	# namedrop = ""
	# [outputs.health.check.tagpass]
	#   plugin = "influxdb"
	# [outputs.health.check.tagdrop]
	#   plugin = "influxdb"
```

If ratios are required, maybe something like this?  If no denominator then it will be treated as 1:
```toml
[[outputs.health]]
  service_address = ":8080"

  [[outputs.health.check]]
    numerator = "buffer_size"
    denominator = "buffer_limit"
    gt = 42.0
    ## other comparisons
    # lt = 42
    # le = 42
    # ge = 42
    # eq = 42

    ## any of the normal "selector" metric filters
    # namepass = "internal_write"
	# namedrop = ""
	# [outputs.health.check.tagpass]
	#   plugin = "influxdb"
	# [outputs.health.check.tagdrop]
	#   plugin = "influxdb"
```

What if there is no data, do we want a deadman's switch on a timeout?
