### ISSUE TITLE
Plugin: procstat: PidFile doesn't verify process is still running

### ISSUE THREAD

**Issue by rawkode** [influxdata/telegraf#5746]
### Relevant telegraf.conf:

```toml
[[inputs.procstat]]
  pid_file = "/tmp/mongodb.pid"
```

### System info:

Linux 5.x

### Steps to reproduce:

1. Run mongod --pidfile=/tmp/mongodb.pid
2. Kill -9 <mongd pid>

### Expected behavior:

State would change to `running=0i`

### Actual behavior:

State continues to be `running=1i`
