### ISSUE TITLE
[input.httpjson]

### ISSUE THREAD

**Issue by badgerman11** [influxdata/telegraf#5748]
Hi,
I've stuck on this problem for about a week. Sorry for this stupid question. I'm not a programmer, just trying to make MagicMirror with smog measurements. Read everything about it and still no clue why I can't make it work.

I need to put data form this link to ifnluxdb
http://api.gios.gov.pl/pjp-api/rest/data/getData/18038

This is my telegraf.config:
```toml
[[outputs.influxdb]]
  urls = [
    "http://localhost:8086",
  ]
  database = "domoticz"

[agent]
  interval = "30m"
  round_interval = true

[[inputs.httpjson]]
  name = "PM25"

  servers = [
    "http://api.gios.gov.pl/pjp-api/rest/data/getData/18038",
  ]
  response_timeout = "15s"

  method = "GET"

  tag_keys = [
    "key"
  ]
```

Thanks for help!

**Comment by glinton** [comment]
The [json parser docs](https://github.com/influxdata/telegraf/tree/release-1.10/plugins/parsers/json) are a great place to learn about json parsing options.

As the `httpjson` plugin is going to be deprecated, please use the `http` input plugin.
```toml
[[inputs.http]]
  urls = ["http://api.gios.gov.pl/pjp-api/rest/data/getData/18038"]
  data_format = "json"
  json_query = "values"
  name_override="PM2.5"
  json_time_key = "date"
  json_time_format = "2006-01-02 15:04:05"
```

Also, we try to keep github issues reserved for actionable code issues. Please post general config/usage questions to [our community forum](https://community.influxdata.com/).
