### ISSUE TITLE
input.exec multi-line input timestamp

### ISSUE THREAD

**Issue by juno-velociti** [influxdata/telegraf#5788]
### Relevant telegraf.conf:

```toml
 [[inputs.exec]]
   commands = ["/tmp/influxdb_check.sh"]
   timeout = "5s"
   name_suffix = "_influxdb_storage"
   data_format = "influx"
```

### System info:
Telegraf 1.10.1 (git: HEAD a6778f46)

docker-compose
```
service:
  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/config/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegraf/influxdb_check.sh:/tmp/influxdb_check.sh
      - influxdb:/var/lib/influxdb
volumes:
  influxdb:
    driver: local-persist
```

### Steps to reproduce:

1. Using the script file /tmp/influxdb_check.sh
```
#!/bin/bash
while read -a LIST; \
do timestamp=$(date +%s%N); \
        printf '%s\n' 'usage folder="'${LIST[1]}'",bytes='${LIST[0]}' '$timestamp; \
done < <(du --max-depth=2 /var/lib/influxdb/data)
```

The script is to get the disk usage size of influxdb/data folder, which outputs multiple line

2. The output of the script when executed directly is already in a proper influx line format:
     `docker exec -it telegraf  ./tmp/influxdb_check.sh`

> usage folder="/var/lib/influxdb/data/velolabdock2/autogen",bytes=93668 1556651821139833420
> usage folder="/var/lib/influxdb/data/velolabdock2/_series",bytes=132 1556651821141265536
> usage folder="/var/lib/influxdb/data/velolabdock2",bytes=93804 1556651821143739128
> usage folder="/var/lib/influxdb/data/lab_nagflux_xi/autogen",bytes=360 1556651821146568741
> usage folder="/var/lib/influxdb/data/lab_nagflux_xi/_series",bytes=68 1556651821150087884
> usage folder="/var/lib/influxdb/data/lab_nagflux_xi",bytes=432 1556651821152422896
> usage folder="/var/lib/influxdb/data/_internal/monitor",bytes=10164 1556651821155373894
> usage folder="/var/lib/influxdb/data/_internal/_series",bytes=32804 1556651821156942489
> usage folder="/var/lib/influxdb/data/_internal",bytes=42972 1556651821158714368
> usage folder="/var/lib/influxdb/data",bytes=137212 1556651821160145262

Note the timestamp increment appended for each output line

### Expected behavior:
When telegraf executes the command either the timestamp from the output is included, or at least each line output is given a unique (incrementing) time stamp

### Actual behavior:
Output of `docker exec -it telegraf telegraf --debug --input-filter exec --test`
> usage_influxdb_storage,host=telegraf bytes=93668,folder="/var/lib/influxdb/data/velolabdock2/autogen" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=132,folder="/var/lib/influxdb/data/velolabdock2/_series" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=93804,folder="/var/lib/influxdb/data/velolabdock2" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=360,folder="/var/lib/influxdb/data/lab_nagflux_xi/autogen" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=68,folder="/var/lib/influxdb/data/lab_nagflux_xi/_series" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=432,folder="/var/lib/influxdb/data/lab_nagflux_xi" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=10164,folder="/var/lib/influxdb/data/_internal/monitor" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=32804,folder="/var/lib/influxdb/data/_internal/_series" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=42972,folder="/var/lib/influxdb/data/_internal" 1556651979000000000
> usage_influxdb_storage,host=telegraf bytes=137212,folder="/var/lib/influxdb/data" 1556651979000000000

All lines have the same timestamp

### Additional info:
Because InfluxDB is time series database, when multiple lines/records are issued with the same timestamp, the last line entered is the one that is kept
https://community.influxdata.com/t/why-measurements-points-count-is-less-than-inserted/1265

Can the telegraf input.exec parser be modified to process the timestamp for each line parsed on the inside of the loop, instead of applied as a single variable outside the loop.
