### ISSUE TITLE
[inputs.win_perf_counters]: Error in plugin: No data to return.

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#5793]
### Relevant telegraf.conf:

```toml
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "AD FS"
    Counters = ["Token Requests"]
    Instances = ["*"]
    Measurement = "win_adfs"
    #IncludeTotal=true #Set to true to include _Total instance when querying for all (*).

```

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:
verified perf counter exists and has a value in it
expect it to end up in prometheus

### Actual behavior:
getting error [inputs.win_perf_counters]: Error in plugin: No data to return.
