### ISSUE TITLE
MongoDB plugin SSL connects but fails to authenticate

### ISSUE THREAD

**Issue by malake** [influxdata/telegraf#5795]
### Relevant telegraf.conf:

```toml
[[inputs.mongodb]]
  servers = ["mongodb://host-1.datacenter.project.domain.com:27017,host-2.datacenter.project.domain.com:27017,host-3.datacenter.project.domain.com:27017/replicaSet=my-replSet&ssl=true&authMechanism=MONGODB-X509&authSource=$external"]

  ## When true, collect per database stats
  gather_perdb_stats = true

  ## Optional TLS Config
  ssl_ca = "/etc/telegraf/ca.pem"
  ssl_cert = "/etc/telegraf/cert.pem"
  ssl_key = "/etc/telegraf/key.pem"

  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false
```

### System info:

Telegraf Version: Telegraf 1.10.3 (git: HEAD 294bb666)
MongoDB Version: 4.0.9
OS: Ubuntu 16.06 x86_64
SSL
### Steps to reproduce:

1. User is created in $external db for external x509 authentication
2. Start telegraf service with above configuration

### Expected behavior:
The plugin should feed the output source (in my case influxdb) with metrics relating to the databases. 

### Actual behavior:

Error generated in log.
I'm able to log into the database using the same certificates provided to telegraf remotely with the mongo CLI and I'm able to successfully run the db.serverStatus() command

#### Telegraf Log
```
2019-05-02T16:40:30Z E! [inputs.mongodb]: Error in plugin: command serverStatus requires authentication
```
#### MongoDB auth info

```
{
	"_id" : "$external.CN=telegraf-monitor,OU=dev-mongo,O=Acme International Corp.,L= Arrakeen,ST= Arrakis,C=DN",
	"user" : "CN=telegraf-monitor,OU=dev-mongo,O=Acme International Corp.,L= Arrakeen,ST= Arrakis,C=DN",
	"db" : "$external",
	"roles" : [
		{
			"role" : "clusterMonitor",
			"db" : "admin"
		}
	],
	"mechanisms" : [
		"external"
	]
}
```
