### ISSUE TITLE
input did not complete within its interval

### ISSUE THREAD

**Issue by dynek** [influxdata/telegraf#5796]
### Relevant telegraf.conf:

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://influxdb.domain.net:8086"]
  database = "fibaro"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.fibaro]]
  url = "http://fibaro.domain.net:80"
  username = "admin"
  password = "<password>"
```
### System info:

I tried both 1.8.0 and 1.10.3 running in containers on a Debian 9.8 system with docker-ce 18.09.5~3-0~debian-stretch

### Steps to reproduce:

1. Run the container with the above config
2. Wait

### Expected behavior:

Metrics flowing smoothly from Fibaro to InfluxDB.

### Actual behavior:

After a random amount of time, I start seeing the following message every ten seconds:
```
2019-05-02T17:52:00Z W! [agent] input "inputs.fibaro" did not complete within its interval
```

### Additional info:

This configuration used to work as-is on another host so I'm not too sure what's wrong here.
What actually lead me to open a bug report is that I ran a tcpdump and netstat (loop) on both sides and when this happens, the Fibaro box (10.1.0.31) doesn't see a single TCP SYN or whatever coming from the Docker container, and netstat in the docker container running Telegraf shows:
```
tcp        0      0 172.17.0.5:35192        10.1.0.31:80            ESTABLISHED 1/telegraf
```
Once again 10.1.0.31 in this case (Fibaro box) doesn't see an established connection from the container. I don't see how the Fibaro box, the host running the container or my network could be guilty for that.

Running telegraf a second time (docker exec -ti <xyz> sh) inside that container works, meaning metrics make it again to InfluxDB, restarting it completely also workarounds things.

Any hint to debug it further?

Thank you
