### ISSUE TITLE
Input plugin nginx_plus_api http request throws "404 Not Found" error

### ISSUE THREAD

**Issue by sushant-jaiswal** [influxdata/telegraf#5807]
### Relevant telegraf.conf:

```toml
# Read Nginx Plus API advanced status information
[[inputs.nginx_plus_api]]
  ## An array of Nginx API URIs to gather stats.
  urls = ["http://127.0.0.1/api"]
  # Nginx API version, default: 3
  api_version = 4
```

### System info:

Ubuntu Xenial (16.04)
Nginx Plus R18
Telegraf 1.10.2

### Steps to reproduce:

1. Added following block to enable ngx_http_api_module in /etc/nginx/nginx.conf-
```
    server {
        listen 127.0.0.1;

        location /api {
            api write=on;
            allow 127.0.0.1;
            deny all;
        }
    }
```
2. Changed telegraf.conf as mentioned in the beginning, to add input plugin nginx_plus_api.
3. Restarted telegraf
4. Check Telegraf log

### Expected behavior:
Ngnix metrics data through the API

### Actual behavior:
Getting following error-

`
2019-05-06T10:06:19Z E! [inputs.nginx_plus_api]: Error in plugin: http://127.0.0.1/api returned HTTP status 404 Not Found
`
### Additional info:
Checked `gatherUrl` function in file "nginx_plus_api_metrics.go". Just to see some more error details, changed the `urls` value in "telegraf.conf" to `127.0.0.` (removed 1 from last). Restarted Telegraf and got the error as below-

`
2019-05-06T10:07:54Z E! [inputs.nginx_plus_api]: Error in plugin: error making HTTP request to http://127.0.0./api: Get http://127.0.0./api/4/processes: dial tcp: lookup 127.0.0.: no such host
`

When opening the correct URL `http://127.0.0.1/api/4/processes` from the machine, it is accessible and response is Successful.

Not sure why should we get "HTTP status 404 Not Found" as mentioned in Actual Behavior. The URLs seem to be good, then why it should go the block `if resp.StatusCode != http.StatusOK {`. It brings my doubt on `resp, err := n.client.Get(url)`, which is very unlikely to be an issue.

We want to start using this plugin, so any help is appreciated. Thanks.
