### ISSUE TITLE
vsphere: root Folder prevents metrics collection

### ISSUE THREAD

**Issue by meerkampdvv** [influxdata/telegraf#5818]
### Relevant telegraf.conf:

```toml
[[inputs.vsphere]]
    username = "user@comp.loc"
    insecure_skip_verify = true
    password = "secret"
    vcenters = [ "https://host.comp.loc/sdk" ]

```

### System info:

CentOS Linux release 7.6.1810 (Core)
telegraf-1.10.3-1.x86_64

### Steps to reproduce:

1. use the vsphere input
2. have a top level Folder in the vcenter as seen below :
![image](https://user-images.githubusercontent.com/42608682/57370695-059eca80-7191-11e9-8d25-fd48567e5b30.png)

### Expected behavior:

All Metrics will be collected

### Actual behavior:

only the Metrics of the Datacenter IAC_Test are collected but nothing below the Produktion folder.

### Additional info:

current workaround :
```toml
[[inputs.vsphere]]
    username = "user@comp.loc"
    insecure_skip_verify = true
    password = "secret"
    vcenters = [ "https://host.comp.loc/sdk" ]
    vm_include = [ "/**"]
    host_include =  [ "/**"]
    cluster_include =  [ "/**"]
    datastore_include =  [ "/**"]
    datacenter_include = [ "/**"]

```
