### ISSUE TITLE
Host Resource MIB does not work in Telegraf container 

### ISSUE THREAD

**Issue by utamav** [influxdata/telegraf#5837]
### Problem Statement:

Deployed a new telegraf container for SNMP monitoring. Telegraf does not automatically get the HOST-RESOURCE-MIB. So it was added in `/usr/share/snmp/mibs/` within the container. Now I am getting an error.

### Relevant telegraf.conf:

```toml
   ## Host/System Resources
   ##
   #  System uptime
   [[inputs.snmp.field]]
     name = "sysUpTime"
     oid = "HOST-RESOURCES-MIB::hrSystemUptime.0"
   #  Number of user sessions
   [[inputs.snmp.field]]
     name = "hrSystemNumUsers"
     oid = "HOST-RESOURCES-MIB::hrSystemNumUsers.0"
   #  Number of process contexts
   [[inputs.snmp.field]]
     name = "hrSystemProcesses"
     oid = "HOST-RESOURCES-MIB::hrSystemProcesses.0"
   #  Device Listing
   [[inputs.snmp.table]]
     oid = "HOST-RESOURCES-MIB::hrDeviceTable"
     [[inputs.snmp.table.field]]
       oid = "HOST-RESOURCES-MIB::hrDeviceIndex"
       is_tag = true
```

### System info:

Telegraf 1.10.3 (git: HEAD 294bb666) running in a container on Ubuntu 18.04 server

### Steps to reproduce:

1. Run a telegraf container with input SNMP input plugin which uses HOST-RESOURCE-MIB
2. Add HOST-RESOURCE-MIB in the telegraf container

### Expected behavior:

Telegraf to run without errors

### Actual behavior:

Errors seen in the container logs.
```
2019-05-11T14:19:00Z E! [inputs.snmp]: Error in plugin: initializing table : translating: exit status 2: MIB search path: /root/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
Cannot find module (SNMPv2-SMI): At line 5 in /usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt
Cannot find module (SNMPv2-TC): At line 8 in /usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt
Cannot find module (IF-MIB): At line 12 in /usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt
Did not find 'mib-2' in module #-1 (/usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt)
Did not find 'DisplayString' in module #-1 (/usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt)
Did not find 'TruthValue' in module #-1 (/usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt)
Did not find 'DateAndTime' in module #-1 (/usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt)
Did not find 'AutonomousType' in module #-1 (/usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt)
Did not find 'InterfaceIndexOrZero' in module #-1 (/usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt)
Unlinked OID in HOST-RESOURCES-MIB: host ::= { mib-2 25 }
Undefined identifier: mib-2 near line 100 of /usr/share/snmp/mibs/HOST-RESOURCES-MIB.txt
HOST-RESOURCES-MIB::hrDeviceTable: Unknown Object Identifier
```
