### ISSUE TITLE
Telegraf unresponsive, cannot capture stack trace

### ISSUE THREAD

**Issue by soumya92** [influxdata/telegraf#5839]
### Relevant telegraf.conf:
```toml
[global_tags]
  # some tags
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["**influx-url**"]
  username = "telegraf"
  password = "**password**"
# and nothing but [[input]] blocks.
```

### System info:

Telegraf 1.10.2 (git: HEAD 3303f5c3)
Linux host 4.19.32-1-ARCH #1 SMP PREEMPT Thu Apr 4 00:12:02 UTC 2019 armv7l GNU/Linux

### Steps to reproduce:

1. No concrete steps. Just wait a few days.

### Expected behavior:

Telegraf keeps publishing metrics continuously.

### Actual behavior:

Telegraf stops publishing metrics. Logs initially start with `input "..." did not complete within its interval`, but eventually even those stop. Does not respond to SIGTERM, and does not print a stack trace with SIGQUIT.

### Additional info:

Some logs for the unresponsive case and the normal case are here: https://gist.github.com/soumya92/8038a56f47f61b86aa2e1ab92972018d
