### ISSUE TITLE
multuple instance of processors.strings.replace not working as expected

### ISSUE THREAD

**Issue by ajaywazir** [influxdata/telegraf#5843]
### Relevant telegraf.conf:

```toml
[[processors.strings]]  
order = 102 
   [[processors.strings.replace]]
   tag = "SenderId"
   old = "IPC_123456_01"
   new = "SITE01"
   dest = "site_id"  
    
   [[processors.strings.replace]]
   tag = "SenderId"
   old = "IPC_812345_01"
   new = "SITE02"
   dest = "site_id" 
```

### System info:

1.10.1
### Steps to reproduce:

The telgraf uses infux output to store data.
In above situation, only the second tag value is replaced, not the first one.

### Expected behavior:
Both tag values should be converted to SITE01 and SITE02 respectively.
### Actual behavior:
Only IPC_123456_01 is converter to SITE02 is stored

**Comment by glinton** [comment]
I believe the enum processor is a better fit for what you are trying to do. You can use a build from [the recent patch](https://github.com/influxdata/telegraf/issues/5033#issuecomment-492733318) and something like the following config:
```toml
  [[processors.enum]]
    [[processors.enum.mapping]]
      tag = "SenderId"
      dest = "site_id"
      [processors.enum.mapping.value_mappings]
        "IPC_123456_01" = "SITE01"
        "IPC_812345_01" = "SITE02"
```
