### ISSUE TITLE
Telegraf deadlocked

### ISSUE THREAD

**Issue by soumya92** [influxdata/telegraf#5844]
### Relevant telegraf.conf:
```toml
[global_tags]
  # some tags
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["**influx-url**"]
  username = "telegraf"
  password = "**password**"
# and nothing but [[input]] blocks.
```

### System info:

Telegraf 1.10.2 (git: HEAD 3303f5c)
Linux host 4.19.32-1-ARCH #1 SMP PREEMPT Thu Apr 4 00:12:02 UTC 2019 armv7l GNU/Linux

### Steps to reproduce:

1. Wait for a while

### Expected behavior:

Telegraf keeps publishing metrics

### Actual behavior:

Telegraf deadlocks, nothing is printed to the logs, no metrics are sent. Stack dump from sigquit is attached.

### Additional info:

Stack dump captured by `kill -SIGQUIT (pgrep telegraf)` is here: https://gist.github.com/soumya92/5078d2a64306ec93931e99eff4c7b441

This may or may not be related to #5839, so filing separately in case it isn't.
