### ISSUE TITLE
Allow an input's name_override to be blank / null

### ISSUE THREAD

**Issue by musicsnob** [influxdata/telegraf#5849]
## Feature Request

I hope that I am not misunderstanding the current name_override functionality! I suspect name_override currently works correctly and as designed, but is not granular enough. Thanks for reading.

### Proposal:
For input plugins, allow name_override to be blank/null. Or, allow name_override to work at the field level in addition to the input level.

### Current behavior:
Per https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md,
> name_override: Override the base name of the measurement. (Default is the name of the input).

Within the telegraf config, setting an input's name_override = "" causes the measurement's base name to remain the name of the input. Setting name_override = null causes an config file error. 

### Desired behavior:
Use only the field's name without prepending the name of the input, if desired by the user, or allow name_override to function at the input field level. 

### Use case: 
With the SNMP plugin, the user may wish to name metrics like so:
```
    [[inputs.snmp.field]]
        name = "system.host"
        oid = "SNMPv2-MIB::sysName.0"
        is_tag = true
    [[inputs.snmp.field]]
        name = "system.uptime"
        oid = "HOST-RESOURCES-MIB::hrSystemUptime.0"
    [[inputs.snmp.field]]
        name = "system.n_users"
        oid = "HOST-RESOURCES-MIB::hrSystemNumUsers.0"
    [[inputs.snmp.field]]
        name = "mem.total"
        oid = "UCD-SNMP-MIB::memTotalReal.0"
    [[inputs.snmp.field]]
        name = "mem.available"
        oid = "UCD-SNMP-MIB::memAvailReal.0"
```

However, the plugin behavior results in measurements named "snmp.system.uptime", "snmp.mem.total", etc. There does not appear to be a way to instead output only "system.uptime", "mem.total", etc. This can cause downstream data integration issues when combining metrics from different inputs, such as inputs.system, inputs.mem, and inputs.snmp.

**Comment by danielnelson** [comment]
Telegraf's [metric] model requires both a "measurement name" and one more more field names.  The measurement name should be something that describes the category of items, here you would want `system` or `mem`.  The field name would describe the individual values `host`, `uptime`, `total`, `available`.

Exactly how this ends up being output depends on the output plugin, with InfluxDB the translation is direct, but it looks like maybe you are using the graphite or wavefront outputs.

Either way, I think what might work well for you is to have multiple plugins defined, one for each measurement.
```toml
[[inputs.snmp]]
    name_override = "system"
    [[inputs.snmp.field]]
        name = "host"
        oid = "SNMPv2-MIB::sysName.0"
        is_tag = true
    [[inputs.snmp.field]]
        name = "uptime"
        oid = "HOST-RESOURCES-MIB::hrSystemUptime.0"
    [[inputs.snmp.field]]
        name = "n_users"
        oid = "HOST-RESOURCES-MIB::hrSystemNumUsers.0"

[[inputs.snmp]]
    name_override = "mem"
    [[inputs.snmp.field]]
        name = "total"
        oid = "UCD-SNMP-MIB::memTotalReal.0"
    [[inputs.snmp.field]]
        name = "available"
        oid = "UCD-SNMP-MIB::memAvailReal.0"
```

[metric]: https://github.com/influxdata/telegraf/blob/master/docs/METRICS.md

**Comment by musicsnob** [comment]
Hi Daniel, thanks, I appreciate the quick response. I'd considered having one plugin per SNMP / MIB measurement, but didn't pursue it for concern it was maybe too hacky... I am using outputs.http to send to Splunk's HEC using `data_format = "splunkmetric"`.

**Comment by danielnelson** [comment]
It occurs to me that something like this should work as well:
```toml
[[inputs.snmp]]
    agents = ["127.0.0.1"]
    community = "public"
    version = 2

    [[inputs.snmp.field]]
        name = "host"
        oid = "SNMPv2-MIB::sysName.0"
        is_tag = true

    [[inputs.snmp.table]]
        name = "system"
        inherit_tags = ["host"]
        [[inputs.snmp.table.field]]
            name = "uptime"
            oid = "HOST-RESOURCES-MIB::hrSystemUptime"
        [[inputs.snmp.table.field]]
            name = "n_users"
            oid = "HOST-RESOURCES-MIB::hrSystemNumUsers"

    [[inputs.snmp.table]]
        name = "mem"
        inherit_tags = ["host"]
        [[inputs.snmp.table.field]]
            name = "total"
            oid = "UCD-SNMP-MIB::memTotalReal"
        [[inputs.snmp.table.field]]
            name = "available"
            oid = "UCD-SNMP-MIB::memAvailReal"
```
