### ISSUE TITLE
Logparser drops entire line when field doesn't match modifier

### ISSUE THREAD

**Issue by blindrood** [influxdata/telegraf#5876]
### Relevant telegraf.conf:

```toml
[inputs.logparser]]
  files = ["/var/log/test.log"]
  from_beginning = true
  [inputs.logparser.grok]
    patterns = ["%{REQUEST}"]
    custom_patterns = '''
  REQUEST %{IPORHOST:client_ip} - \[%{TS_ISO8601:ts:ts}\] "%{WORD:verb:tag} (?:%{NOTSPACE:request:drop}) (?:HTTP/%{NUMBER:http_version:float})" %{NUMBER:resp_code:tag} %{NUMBER:resp_bytes:int} tt\: %{NUMBER:req_time:float}\[sec\] ttuc\: %{NUMBER:upstream_connect_time:float}\[sec\] ttuh: %{NUMBER:upstream_header_time:float}\[sec\] tturs\: %{NUMBER:upstream_response_time:float}\[sec\] rid\: %{NUMBER:request_x_rid:float}
    '''
```

### System info:

Tests on composed TICK stack with latest images

### Steps to reproduce:
file with data to parse, sample line (this is nginx access log)
1.2.3.4 - [2019-05-17T06:45:32+00:00] "POST /q HTTP/1.1" 200 24610 tt: 0.084[sec] ttuc: 0.000[sec] ttuh: 0.002[sec] tturs: 0.002[sec] rid: 5417066305679228636

Some lines in the file can contain dash, when numbered value is not provided
e.g.
1.2.3.4 - [2019-05-17T06:45:32+00:00] "POST /q HTTP/1.1" 499 25 tt: 0.224[sec] ttuc: -[sec] ttuh: -[sec] tturs: -[sec] rid: 5206836045584104289

### Expected behavior:

telegraf, during parsing, should drop failed fields only (e.g. put null value) and still keep rest of line field values

### Actual behavior:
Line is dropped with "grok no match" entry notification in telegraf log
If I modify grok to use NUMORDASH instead of NUMBER it still fails with error while parsing value to float
NUMORDASH (%{NUMBER}|\-)

### Additional info:

I'm happy to reconfigure pattern if there's already way to achieve this
