### ISSUE TITLE
inputs.http json wont parse anything

### ISSUE THREAD

**Issue by meerkampdvv** [influxdata/telegraf#5886]
### Relevant telegraf.conf:

```toml
[outputs]
[[outputs.prometheus_client]]
  listen = ":9273"
  collectors_exclude = ["gocollector", "process"]
[inputs]
[[inputs.http]]
  urls = [
    "https://cloudian.domain:19443/monitor"
  ]
  method = "GET"
  username = "sysadmin"
  password = "public"
  insecure_skip_verify = true
  data_format = "json"
```

### System info:

CentOS Linux release 7.6.1810 (Core)
telegraf-1.10.3-1.x86_64

### Steps to reproduce:

curl -k -H "Authorization: Basic $(echo -n sysadmin:public | base64 )" -X GET https://cloudian.domain:19443/monitor | jq

gives me following output :
```
{
  "status": {
    "value": "[OK]",
    "timestamp": "1558423023320",
    "status": [
      "OK"
    ],
    "ipaddr": ""
  },
  "s3GetTPS": {
    "value": "1.1",
    "timestamp": "1558422783156"
  },
  "s3PutTPS": {
    "value": "0.4",
    "timestamp": "1558422783156"
  },
  "s3PutThruput": {
    "value": "8110",
    "timestamp": "1558422783156"
  },
  "s3GetThruput": {
    "value": "423743",
    "timestamp": "1558422783156"
  },
  "s3GetLatency": {
    "value": "31.2",
    "timestamp": "1558422783156"
  },
  "s3PutLatency": {
    "value": "160.8",
    "timestamp": "1558422783156"
  },
  "diskAvailKb": {
    "value": "859135797182",
    "timestamp": "1558422783156"
  },
  "diskUsedKb": {
    "value": "1347628929796",
    "timestamp": "1558422783156"
  },
  "diskTotalKb": {
    "value": "2451964739912",
    "timestamp": "1558422783156"
  },
  "nodeStatuses": [
    {
      "value": "[OK]",
      "timestamp": "1558423023320",
      "status": [
        "OK"
      ],
      "ipaddr": null,
      "hostname": "s3node0"
    },
    {
      "value": "[LOG_WARN]",
      "timestamp": "1558423023320",
      "status": [
        "LOG_WARN"
      ],
      "ipaddr": null,
      "hostname": "s3node1"
    }
  ]
}

```

### Expected behavior:

something gets parsed like : 
s3PutThruput value=8110,timestamp=1558422783156

### Actual behavior:
prometheus_client output is empty

### Additional info:
The api which is accessed is a Cloudian HyperStore and i see https traffic between telegraf and the api.
