### ISSUE TITLE
Arbitrary rule can cause all Graphite templates to be ignored

### ISSUE THREAD

**Issue by Crack** [influxdata/telegraf#5894]
### Relevant telegraf.conf:
```toml
[agent]
  omit_hostname = true

[[inputs.socket_listener]]
  service_address = "tcp://:2000"
  data_format = "graphite"
  templates = [
    "taskmanagerTask.alarm-detector.Assign.alarmDefinitionId metricsType.process.nodeId.x.alarmDefinitionId.measurement.field rule=1",
    "taskmanagerTask.*.*.*.*                                 metricsType.process.nodeId.measurement rule=2"
  ]
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"
  flush_interval = "1s"
```

### System info:

Telegraf 1.10.4

### Steps to reproduce:

1. `telegraf --config conf-from-bug-report.conf`
2. ```
    echo "taskmanagerTask.alarm-detector.Assign.alarmDefinitionId.timeout_errors.duration.p75 100 $(date +%s)" | nc 127.0.0.1 2000
    echo "taskmanagerTask.alarm-detector.Assign.numRecordsInPerSecond.m5_rate 100 $(date +%s)" | nc 127.0.0.1 2000
    ````

### Expected behavior:

Telegraf output:
```
duration,alarmDefinitionId=timeout_errors,metricsType=taskmanagerTask,nodeId=Assign,process=alarm-detector,rule=1,x=alarmDefinitionId p75=100 1558538449000000000
numRecordsInPerSecond,metricsType=taskmanagerTask,nodeId=Assign,process=alarm-detector,rule=2 value=100 1558537634000000000
```

### Actual behavior:

Telegraf output:
```
duration,alarmDefinitionId=timeout_errors,metricsType=taskmanagerTask,nodeId=Assign,process=alarm-detector,rule=1,x=alarmDefinitionId p75=100 1558538449000000000
taskmanagerTask.alarm-detector.Assign.numRecordsInPerSecond.m5_rate value=100 1558537531000000000
```

### Additional info:

I get expected behavior when I remove first template, but I need both of them to work correctly.
