### ISSUE TITLE
External Environment Variables are not set when running Telegraf

### ISSUE THREAD

**Issue by js-mode** [influxdata/telegraf#5909]
### Relevant telegraf.conf:

``` 
[global_tags]
  env = "ENVIRONMENT"
[agent]
  interval = "60s"
  hostname = "telegraf-snmp-compute-leafs"
  omit_hostname = false
[[outputs.wavefront]]
  host = "$WF_PROXY"
  port = $WF_PORT1
  metric_separator = "."
  convert_paths = true
  use_regex = false

[[inputs.snmp]]
  agents = [AGENTS]
  version = 3
  auth_password = "$TELEGRAF_SNMP_TOKEN"
  auth_protocol = "MD5"
  priv_password = "$TELEGRAF_SNMP_TOKEN"
  priv_protocol = "AES"
  sec_name = "$SNMP_SECURITY_USER"
  sec_level = "authPriv"
  max_repetitions = 10
  timeout = "10s"
  retries = 1
  name_prefix = "dev."

  [[inputs.snmp.field]]
    name = "hostname"
    oid = ".1.3.6.1.2.1.1.5.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "cseSysCPUutilization"
    oid = ".1.3.6.1.4.1.9.9.305.1.1.1.0"
  [[inputs.snmp.field]]
    name = "cseSysUpTime"
    oid = ".1.3.6.1.4.1.9.9.305.1.1.10.0"
  [[inputs.snmp.field]]
    name = "cseSysMemoryUtilization"
    oid = ".1.3.6.1.4.1.9.9.305.1.1.2.0"

  [[inputs.snmp.table]]
    name = "interfaceStats"
    inherit_tags = ["hostname"]
    [[inputs.snmp.table.field]]
      name = "ifAlias"
      oid = ".1.3.6.1.2.1.31.1.1.1.18"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "ifName"
      oid = ".1.3.6.1.2.1.31.1.1.1.1"
      is_tag = true
    [[inputs.snmp.table.field]]
	    name = "ifType"
  	  oid = ".1.3.6.1.2.1.2.2.1.3"
    [[inputs.snmp.table.field]]
      name = "ifInNUcastPkts"
      oid = "1.3.6.1.2.1.2.2.1.12"
    [[inputs.snmp.table.field]]
      name = "ifInDiscards"
      oid = "1.3.6.1.2.1.2.2.1.13"
    [[inputs.snmp.table.field]]
      name = "ifInErrors"
      oid = "1.3.6.1.2.1.2.2.1.14"
    [[inputs.snmp.table.field]]
      name = "ifOutUcastPkts"
      oid = "1.3.6.1.2.1.2.2.1.14"
    [[inputs.snmp.table.field]]
      name = "ifOutNUcastPkts"
      oid = "1.3.6.1.2.1.2.2.1.18"
    [[inputs.snmp.table.field]]
      name = "ifOutDiscards"
      oid = "1.3.6.1.2.1.2.2.1.19"
    [[inputs.snmp.table.field]]
      name = "ifOutErrors"
      oid = "1.3.6.1.2.1.2.2.1.20"
    [[inputs.snmp.table.field]]
      name = "ifMtu"
      oid = "1.3.6.1.2.1.2.2.1.4"
```

### System info:
DOCKER CONTAINER RUNNING telegraf:1.10-alpine

### Steps to reproduce:

1. Build Docker Container and set appropriate Environment Variables. Afterwards the config file in the container does not have the appropriate values. 
2. When creating env variable that is not a string, get a `Error running agent: Error parsing /etc/telegraf/telegraf.conf, toml: line 9: parse error`
3.  Have tried the variables with "${SNMP_SECURITY_USER}" and with just "$SNMP_SECURITY_USER" and neither seem to work. Currently it works when I run the config with a sed command, but would like to pass in the variables directly instead. 

### Expected behavior:

The environment variables that are set in the container are populated in the config file when telegraf starts. 

### Actual behavior:

Getting either a parse error or the environment variable is just showing up with the variable name instead of the value. 

### Additional info:

Have tried the Telegraf Alpine versions 9, 10 and 10.5 and still not working.

**Comment by danielnelson** [comment]
Can you paste the command you are using to start the container?

**Comment by js-mode** [comment]
Dockerfile is just running an init.sh that runs through to verify all of the variables are properly set and then runs `/usr/bin/telegraf` from within the container when it is built. When I log into the container I can see that the telegraf.conf only has the variables that are replaced using the sed command and not the variables that have the $ format. 

When I build the telegraf.conf file it has everything working fine, but if I add any $variable in the file it will not resolve properly.  If i log into the container after it is built and running and type in `set` - i see the variable created, but the value is not getting added to the .conf file.  I am going to try the exact same set up on an ubuntu VM without docker and use the latest version and see if that changes anything.  Please let me know if there is a way to run a verbose mode or some other logs that can tell me where to look to troubleshoot.

**Comment by danielnelson** [comment]
> Please let me know if there is a way to run a verbose mode or some other logs that can tell me where to look to troubleshoot.

There is not any additional debugging currently.

One thing you could try is calling `env` instead of Telegraf, and make sure the variables are set in its output.  Make sure the environment variables are exported.

The configuration file looks correct btw.

**Comment by vjanssens** [comment]
@danielnelson I'm having the same issue as @js-mode describes.

I'm running Telegraf with InfluxDB inside Docker containers, passing environment variables in through `docker-compose.yml`. 

`docker-compose.yml`
```
telegraf:
    image: telegraf:1.10.4
    env_file:
      - ./.env
    volumes:
       - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
       - /var/run/docker.sock:/var/run/docker.sock
```

`telegraf.conf`
```
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] 
  username = "${INFLUXDB_ADMIN_USER}"
  password = "<working_password_redacted>"
```

There are two ways I tested to see if the environment variables are correctly passed to the container:
```
docker exec -it <container_name> bash
echo $INFLUXDB_ADMIN_USER
> outputs correct variable definition
xargs -0 -L1 -a /proc/1/environ
> also outputs the same variable definition
```

> Telegraf runs on pid 1

In the output of telegraf, I observe the following:

> 401 Unauthorized: authorization failed

When replacing `${INFLUXDB_ADMIN_USER}` in `telegraf.conf` with the working password, telegraf works as expected and is able to push data to InfluxDB.

Also found https://github.com/influxdata/telegraf/issues/5866#issue-445118659, which describes the same issue.

**Comment by danielnelson** [comment]
With Telegraf 1.10.4 you will need to use the format without braces: `$INFLUXDB_ADMIN_USER`.  The `${}` format will be new in 1.11.

**Comment by js-mode** [comment]
@danielnelson -- i have tried using the $INFLUXDB_ADMIN_USER format and still no luck.  And how long does it usually take for the 1.11 to be available in the ALPINE package?  Is that something that takes a while to become available?

**Comment by js-mode** [comment]
> One thing you could try is calling `env` instead of Telegraf, and make sure the variables are set in its output. Make sure the environment variables are exported.
> 
I am using env and I know the variables are being set in the container properly, but they are not being read ini by Telegraf.  I have tried the ${var} and $var formats and still does not work.  I am using Alpine 1.10.4 -- so will wait for Alpine 1.11 and try again then.

**Comment by danielnelson** [comment]
The `$var` format should work today, I wouldn't expect 1.11 to fix your issue.  

I just ran the `docker-compose.yml` script from @vjanssens with the 1.10.4 image, but setting the `database` instead of the `username` as it is printed out to the log so easier to debug and it worked for me.  I would try setting it up outside of docker first, should be easier to debug.

**Comment by hmojic200** [comment]
I can confirm that the `$var` format doesn't work in docker image `1.10.4-alpine` and `1.10.4`.  Neither setting environment variables nor using `/etc/default/telegraf` file works.

Example: the following will output graphite metrics at `__METRIC_PREFIX_`
```
[[outputs.graphite]]
  servers = ["localhost:2003"]
  prefix = "$METRIC_PREFIX"
  template = "tags.measurement.field"
  timeout = 10
```

**Comment by danielnelson** [comment]
I wouldn't expect `/etc/default/telegraf` to work in the docker container, normally this is read by the init system, and the docker container doesn't do it: https://github.com/influxdata/influxdata-docker/blob/master/telegraf/1.10/entrypoint.sh.  We could add support for this though.

Can you show the command you used to start the docker container?

**Comment by hmojic200** [comment]
I was just falling back on the image's `CMD`, so it was just `telegraf`.  Shouldn't environment variables still work though, or was I missing a command line argument or something else for that?

**Comment by danielnelson** [comment]
They should work and it is working for me. I'm running the container like:
```
docker run --rm -e METRIC_PREFIX=xyzzy -v /home/foo/telegraf.conf:/etc/telegraf/telegraf.conf telegraf
```

**Comment by vjanssens** [comment]
Thanks for the help @danielnelson, I got it working with the example I provided before, but with `$VARNAME` instead of `${VARNAME}`.

**Comment by js-mode** [comment]
I am unable to still get this working -- not sure if it is an alpine issue, but I will wait for the latest telegraf:alpine version to include telegraf 1.11 version.  If anyone else is able to get this working in Alpine, please let me know.

**Comment by danielnelson** [comment]
@js-mode The official alpine 1.10.4 image is working for me too, try running these steps and see if it works for you, if it works we can try to build out to your actual config:

```
$ cat tmp.conf 
[global_tags]
  test = "$HOWDY"

[[inputs.net]]
  fieldpass = ["packets_sent"]

[[outputs.file]]
$ docker run --rm -e HOWDY=xyzzy -v /home/dbn/tmp.conf:/etc/telegraf/telegraf.conf telegraf:alpine
2019-06-14T00:11:06Z I! Starting Telegraf 1.10.4
2019-06-14T00:11:06Z I! Using config file: /etc/telegraf/telegraf.conf
2019-06-14T00:11:06Z I! Loaded inputs: net
2019-06-14T00:11:06Z I! Loaded aggregators: 
2019-06-14T00:11:06Z I! Loaded processors: 
2019-06-14T00:11:06Z I! Loaded outputs: file
2019-06-14T00:11:06Z I! Tags enabled: host=235f992b72e3 test=xyzzy
2019-06-14T00:11:06Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"235f992b72e3", Flush Interval:10s
net,host=235f992b72e3,interface=eth0,test=xyzzy packets_sent=0i 1560471080000000000
net,host=235f992b72e3,interface=eth0,test=xyzzy packets_sent=0i 1560471070000000000
```

**Comment by spmatich** [comment]
I saw this TOML error and eventually traced it to doing this:
echo <secret> | base64
and pasting the resulting output into my secrets. Of course includes a newline in the echo output unless you use echo -n, which is faithfully reproduced and substituted in the telegraf.conf where it is invalid. using the echo -n <secrete>|base64 fixed the issue for me.

**Comment by bamne123** [comment]
Can anyone summaries the solution?
I tried all possible solutions but not working for me.
My Telegraf version is 1.13.2

Running Telegraf in docker-compose.

I receive `unsupported scheme ["${INFLUX_URL}"] `error.

**Comment by fuzxi** [comment]
I am having this same issue, running Telegraf version 1.13.4 installed from the official repo via apt (i.e., not running through Docker). 

`sudo cat /proc/${telegram_pid}/environ` returns the expected values. Presence or absence of curly braces makes no difference, it still returns an `unsupported scheme` error.

**Comment by MattBrauer** [comment]
Any followup on this issue? Running telegraf and influxdb in docker, via `docker-compose` only works when the token is hard-coded into `telegraf.conf`. (Note that `docker-compose config` shows that the environment variable is being passed to the container.)

**Comment by michealroberts** [comment]
I am wondering if users here are confusing what's outside their containers to what is inside (maybe @MattBrauer), e.g., if you're using the following docker-compose configuration, you need to ensure that your environment is configured correctly inside the container:

```yaml
  ...
  
  telegraf:
    image: telegraf:latest
    container_name: spaceflux_telegraf
    entrypoint: /bin/bash -c "chmod 777 /var/run/docker.sock && /entrypoint.sh telegraf"
    environment:
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_ORG}
      - INFLUX_ADMIN_TOKEN=${INFLUX_TOKEN}
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    volumes:
      # Map Telegraf configuration file from the host to the container:
      - $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      # Map Docker socket from the host to the container:
      - /var/run/docker.sock:/var/run/docker.sock
      # Map the root directory of the host to the container for collecting host metrics:
      - /:/hostfs:ro
    depends_on:
      - influxdb
    restart: unless-stopped
```

Your toml file is then:

```toml
# Configuration for influxdb server to send metrics to
[[outputs.influxdb_v2]]
  ## The full HTTP or UDP endpoint URL for your InfluxDB instance.
  ## Multiple urls can be specified as part of the same cluster,
  ## this means that only ONE of the urls will be written to each interval.
  # urls = ["udp://localhost:8089"] # UDP endpoint example
  urls = ["http://influxdb:8086"] # required

  organization = "$INFLUX_ORG"

  bucket = "$INFLUX_BUCKET"

  token = "$INFLUX_ADMIN_TOKEN"
 ``` 

If anyone wants to see my minimum setup for a the tig stack please message me here and I can share the repository with you ...
