### ISSUE TITLE
[jolokia2_proxy] Custom tags not supported

### ISSUE THREAD

**Issue by prandelicious** [influxdata/telegraf#5913]
### Relevant telegraf.conf:

```toml
[[inputs.jolokia2_proxy.target]]
    url = "service:jmx:rmi:///jndi/rmi://10.1.xx.xx:4091/jmxrmi"
    [[inputs.jolokia2_proxy.target.tags]]
      host = "hostname01"
 ```
### System info:
Telegraf 1.10.4 (git: HEAD 3548ce47)
CentOS Linux release 7.6.1810 (Core)

### Expected behavior:
Custom tags doesn't appear to be supported.

### Actual behavior:
Custom tags should be supported.

### Additional info:
`telegraf: 2019-05-27T05:10:22Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.d/jolokia.conf, line 30: field corresponding to `tags' is not defined in `*jolokia2.JolokiaProxyTargetConfig'`

**Comment by danielnelson** [comment]
The tags must be set on the plugin level, `inputs.jolokia2_proxy.tags`:

```toml
[[inputs.jolokia2_proxy]]
  [[inputs.jolokia2_proxy.target]]
    url = "service:jmx:rmi:///jndi/rmi://10.1.xx.xx:4091/jmxrmi"
  [[inputs.jolokia2_proxy.tags]]
    host = "hostname01"
```
