### ISSUE TITLE
Missing metrics (database stats, database size, volume space) for inputs.sqlserver

### ISSUE THREAD

**Issue by ruth108** [influxdata/telegraf#5915]
### Relevant telegraf.conf:

```toml
[[inputs.sqlserver]]
servers = ["Server=localhost;Port=1433;User Id=telegraf;Password=Mystrongpassword@01;app name=telegraf;log=1;",]
  query_version = 2
```

### System info:

telegraf version : 1.10.0
sqlserver : win 2012R2
prometheus database

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:
Find the above metrics in --test and also prometheus

### Actual behavior:
Unable to find metrics in --test and also in prometheus. Surprisingly able to find the same metrics in version1

### Additional info:

text1 (Version1) : telegraf --test
text2 (Version2) : telegraf --input-filter sqlserver --test
