### ISSUE TITLE
parameters output in telegraf and pdns are mismatch

### ISSUE THREAD

**Issue by niks12** [influxdata/telegraf#5916]
### Relevant telegraf.conf:

```toml
module-dir=/usr/lib64/pdns
master=yes
slave=no
write-pid=yes
socket-dir=
security-poll-suffix=secpoll.powerdns.com.

local-address=**ip address**
query-local-address=**ip address**
local-port=5300
reuseport=yes
udp-truncation-threshold=1680
allow-axfr-ips=192.168.60.0/24,172.16.26.0/24
also-notify=192.168.60.222:5300,192.168.60.223:5300,172.16.26.9:5300
dnsupdate=yes

server-id=---server id----
version-string=full

setuid=pdns
setgid=pdns

tcp-control-address=127.0.0.1
tcp-control-port=53000
tcp-control-range=127.0.0.0/8
tcp-control-secret=

api=yes
api-key=xyz
api-logfile=/var/log/pdns.log
api-readonly=no


log-dns-details=no
log-dns-queries=no
log-timestamp=yes
disable-syslog=no
logging-facility=
loglevel=4
query-logging=no
```

### System info:

telegraf-1.10.3-1.x86_64 
Centos 7.6
### Steps to reproduce:

1. ...configure telegraf for pdns and get pdns parameters in grafana 
2. ...the value  of  parameters in grafana and in pdns admin board are different.
example in my case fd-usage value is showing 28 in pdns admin while grafana is showing 26, and I checked few more parameters all are having difference. 

changed data gathering time line (since I deploy the instance) but no help!

I believe there could be some bug for mismatch

on admin board I am looking at "PDNS Statistics" value and on grafana I am trying to capture "time series" data for fd-usage(example) for pdns.

### Expected behavior:
Ideally grafana and pdns parameter values should be identical 
### Actual behavior:
values are showing different on grafana and pdns admin 
### Additional info:
I tried to verify config,unit,matrix in grafana settings but did not help
