### ISSUE TITLE
ECS input plugin does not send stats metrics, only metadata info

### ISSUE THREAD

**Issue by NikitaGl** [influxdata/telegraf#5935]
### Relevant telegraf.conf:
```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 10000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  debug = false
  quiet = false

[[outputs.influxdb]]
  urls = ["http://influx:8086"]
  database = "telegraf"
  precision = "s"
  timeout = "5s"

[[inputs.ecs]]
  ecs_label_include = [ "com.amazonaws.ecs.*" ]
  ecs_label_exclude = []
  timeout = "5s"
```

### System info:

alpine 3.9.4 x86_64, telegraf a0213d9c built from master

### Steps to reproduce:

1. Run task/service via Fargate with Telegraf container

### Expected behavior:

Chronograf should display metrics for `ecs_task`, `ecs_cpu`, `ecs_mem`, `ecs_net`, etc.

### Actual behavior:

It only receive `ecs_task` metrics.

### Additional info:

Telegraf container log reports zero exceptions.
