### ISSUE TITLE
SNMP Plugin timing out with "write udp i/o timeout"

### ISSUE THREAD

**Issue by tgolder** [influxdata/telegraf#5936]
### Relevant telegraf.conf:
```toml
[agent]
  interval = "30s"
  round_interval = true
  metric_buffer_limit = 1000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "30s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  logfile = "/ProgramData/Telegraf/telegraf.log"
  hostname = ""

[[outputs.file]]
  files = ["stdout", "/ProgramData/Telegraf/metrics.out"]
  data_format = "influx"

[[inputs.snmp]]
  agents = [ "(IP of the remote server):161" ]
  timeout = "30000"
  version = 2
  community = "secret"

  name = "system"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "1.3.6.1.2.1.1.5.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "uptime"
    oid = "1.3.6.1.2.1.1.3.0"
```

### System info:

Telegraf Agent v1.10.4_windows_amd64
Attempting to get SNMP data from a remote linux server. 

### Steps to reproduce:

1. Start the telegraf agent 

### Expected behavior:
1.Expecting to get hostname and uptime for the remote server.

### Actual behavior:
Find the following in the log:
```
2019-05-31T15:50:00Z E! [inputs.snmp]: Error in plugin: agent (IP of the remote server):161: performing get on field hostname: write udp (IP of local server):53154->(IP of remote server):161: i/o timeout
```
### Additional info:
Have confirmed that I can do an snmpget from the remote  server with the agent.
