### ISSUE TITLE
exec input : wanted format

### ISSUE THREAD

**Issue by osd42** [influxdata/telegraf#5950]
In order not to grant privileges to telegraf UNIX account on docker socket and Postgresql datadir, I am trying to create a telegraf check as root user with sudo, using the sudoers for user telegraf).

So I tried to use unprivileged telegraf to "exec" (input) telegraf as root for a specific check.

I read some documentation to know which is the best format output for my script. But the data never go to my outputs (prometheus and influxdb) :
- measurement,tags fields timestamp
- measurement,tags fields (as said in exec input documentation)

I use "telegraf --test" so my command itself is not the thing that sends data to the telegraf outputs. I thought the bash output format is important for the telegraf outputs plugins. But I cannot see what I did the bad way.

### Relevant telegraf.conf:

```toml
[[inputs.exec]]
  ## Commands array
  commands = [
    "/etc/telegraf/scripts/x509-postgresql.conf.sh"
  ]
  timeout = "5s"
  data_format = "influx"
```

**_normal telegraf check : (/etc/telegraf/scripts/x509-postgresql.conf)_**
```toml
[[inputs.x509_cert]]
  ## List certificate sources
  sources = ["/PGDATA/PGCMPPPROX01B/server.crt"]
  interval = "1m"
```

**_called script :_** 
```bash
#!/bin/bash

# Hide everything to prevent telegraf header on CLI
exec > /dev/null 2>&1

TOTO=$(sudo /bin/telegraf --config /etc/telegraf/scripts/x509-postgresql.conf --quiet --test)
# | sed -e "s/^> //g -- |awk -F" " {'print $1 $2'}")

#x509_cert,common_name=postgresql.service.sims,host=cmpp5,source=/PGDATA/PGCMPPPROX01B/server.crt age=394i,enddate=1559734802i,expiry=172435i,startdate=1559561972i 1559562367000000000
OUTERR=$?

# Restore visibility on stdout
exec &>/dev/tty

if [ $OUTERR -eq 0 ]; then
    #echo -n "$TOTO" | sed -e "s/^> //g" |awk -F" " {'print $1" "$2" "$3'}
    echo -n "$TOTO" | sed -e "s/^> //g"
    #echo -n "$TOTO" | sed -e "s/^> //g"  | awk -F" " {'print $1" "$2'}
    exit 0
else
    echo "KO"
    exit 1
fi
```

**_This script output as telegraf user :_** 
```
bash-4.2$ whoami
telegraf
bash-4.2$ /etc/telegraf/scripts/x509-postgresql.conf.sh
x509_cert,common_name=postgresql.service.sims,host=cmpp5,source=/PGDATA/PGCMPPPROX01B/server.crt age=626i,enddate=1559826601i,expiry=172203i,startdate=1559653771i 1559654397000000000
```
I also tried without the timestamp at the end !

### System info:

- centos 7.6
- telegraf 1.10.4

### Expected behavior:

informations should be passed to outputs (influxdb and prometheus in my case)

### Actual behavior:

- no information on /metrics
- nothing sent to telegraf outputs (influxdb+prometheus)
