### ISSUE TITLE
Redis input plugin - conflicting field name, series type mismatch errors in telegraf log

### ISSUE THREAD

**Issue by rhajek** [influxdata/telegraf#5957]
I try to create a chronograf dashboard for redis monitoring for InfluxDB 2.0. I was able to get some metrics from Redis, but following errors are shown in telegraf log output. 

### Relevant telegraf.conf:

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb_v2]]	
  urls = ["http://localhost:9999"]
  token = "$INFLUX_TOKEN"
  organization = "my-org"
  bucket = "my-bucket"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
[[inputs.nginx]]
  urls = ["http://localhost:9090/nginx_status"]
[[inputs.redis]]
```

### System info:
```
 Telegraf 1.10.4
 Redis server v=5.0.5 sha=00000000:0 malloc=libc bits=64 build=31cd6e21ec924b46
 MacOS 10.14.5
 InfluxDB 2.0 build 5. Jun 2019, dd27089
```
### Steps to reproduce:
 Run telegraf, redis on localhost and run redis-benchmark

### Actual behavior:

When stressing redis with `redis-benchmark -P 100 -e -l`

Following errors are found in telegraf log:
```
2019-06-05T13:13:10Z E! [agent] Error writing to output [influxdb_v2]: 500 Internal Server Error: internal error: unable to write points to database: partial write: conflicting field type: �2w?�2w?,=redis,host=macek.local,port=6379,replication_role=master,server=localhost,�=allocator_frag_bytes has field type int64 but expected float64 dropped=1

2019-06-05T13:20:30Z E! [agent] Error writing to output [influxdb_v2]: 500 Internal Server Error: internal error: unable to write points to database: partial write: series type mismatch: already Float but got Integer dropped=1
```
