### ISSUE TITLE
Telegraf 1.11.0 Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 2868: field corresponding to `metrics' is not defined in jolokia2.JolokiaAgent

### ISSUE THREAD

**Issue by guitoulefoux** [influxdata/telegraf#5981]
### Relevant telegraf.conf:

```toml
[[inputs.jolokia2_agent.metrics]]
    name  = "java_threading"
    mbean = "java.lang:type=Threading"
    paths = ["TotalStartedThreadCount", "ThreadCount", "DaemonThreadCount", "PeakThreadCount"]

 [[inputs.jolokia2_agent.metrics]]
    name     = "java_memory_pool"
    mbean    = "java.lang:name=*,type=MemoryPool"
    paths    = ["Usage", "PeakUsage", "CollectionUsage"]
    tag_keys = ["name"]
```

### System info:

Telegraf 1.11.0

### Steps to reproduce:

1. /usr/bin/telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d

### Error:
[telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 2868: field corresponding to `metrics' is not defined in jolokia2.JolokiaAgent

I have not this problem on old version.

Thanks for your help
