### ISSUE TITLE
mount_points value in inputs.disk can't be declared in TOML anymore ?

### ISSUE THREAD

**Issue by dynek** [influxdata/telegraf#5984]
### Relevant telegraf.conf:

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"] # required
  database = "regular-metrics" # required
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
```

### System info:

Telegraf has been updated from 1.10.4 to 1.11.0 via https://repos.influxdata.com/debian

```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Steps to reproduce:

1. Install version 1.11.0
2. Start telegraf

### Expected behavior:

Telegraf starts

### Actual behavior:

Telegraf doesn't start and displays an error message:
```
2019-06-13T07:40:14Z I! Starting Telegraf 1.11.0
2019-06-13T07:40:14Z I! Using config file: /etc/telegraf/telegraf.conf
2019-06-13T07:40:14Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 28: field corresponding to `mount_points' in disk.DiskStats cannot be set through TOML
```

### Additional info:

This config was running fine until I updated to 1.11.0.
The doc says syntax is correct: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/disk
