### ISSUE TITLE
Telegraf 1.10 : high CPU usage since update

### ISSUE THREAD

**Issue by nicolinuxfr** [influxdata/telegraf#5989]
I updated several servers to Telegraf 1.10 today, and since then, CPU usage is high on all of them : 

![Capture d’écran 2019-06-13 à 16 44 37](https://user-images.githubusercontent.com/2078386/59447564-bab54a00-8e03-11e9-899e-86978a280aee.png)

On each server, I have one Telegraf process at around 100 % of CPU usage, and two or three more around 50 %.

I did not change the configuration from before, so I think it's something wrong on my part.

### Relevant telegraf.conf:

Default `/etc/telegraf/telegraf.conf`, except for the default output, which is commented and taken care with a configuration file inside `/etc/telegraf/telegraf.d` folder.

Here are the configuration used on a server : 

```toml
# Output Plugin InfluxDB
[[outputs.influxdb]]
  database = "telegraf"
  urls = [ "" ]
  username = ""
  password = ""

# Input Plugins
[[inputs.cpu]]
    percpu = true
    totalcpu = true
    collect_cpu_time = false
    report_active = false
[[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
[[inputs.diskio]]
[[inputs.io]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.system]]
[[inputs.swap]]
[[inputs.netstat]]
[[inputs.processes]]
[[inputs.kernel]]
[[inputs.interrupts]]
[[inputs.linux_sysctl_fs]]

[[inputs.syslog]]
    server = "tcp://localhost:6515"

[[inputs.apache]]
  urls = ["http://localhost:7430/server-status?auto"]
[[inputs.logparser]]
  files = ["/var/log/telegraf/apache.log"]
  from_beginning = true
  [inputs.logparser.grok]
    patterns = ["%{COMBINED_LOG_FORMAT}"]
    measurement = "apache_access_log"

[agent]
    logfile = "/var/log/telegraf/telegraf.log"

[[inputs.logparser]]
  files = ["/var/log/telegraf/telegraf.log"]

  [inputs.logparser.grok]
    measurement = "telegraf_log"
    patterns = ['^%{TIMESTAMP_ISO8601:timestamp:ts-rfc3339} %{TELEGRAF_LOG_LEVEL:level:tag}! %{GREEDYDATA:msg}']
    custom_patterns = '''
TELEGRAF_LOG_LEVEL (?:[DIWE]+)
'''

```

### System info:

- Telegraf 1.10.0
- Ubuntu 18.04.2 LTS

Let me know if you need more information.
