### ISSUE TITLE
not all the VMs of my vcenter are collected

### ISSUE THREAD

**Issue by pyves06** [influxdata/telegraf#5993]
### Relevant telegraf.conf:

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  #interval = "10s"
  interval = "60s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  #metric_batch_size = 1000
  metric_batch_size = 25000

  ## Maximum number of unwritten metrics per output.
  #metric_buffer_limit = 10000
  metric_buffer_limit = 500000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  #flush_interval = "10s"
  flush_interval = "60s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "Âµs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  # debug = false
  debug = true
  ## Log only error level messages.
  # quiet = false

  ## Log file name, the empty string means to log to stderr.
  # logfile = ""
  logfile = "/var/log/telegraf/telegraf.log"

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
  # urls = ["http://127.0.0.1:8086"]

  ## The target database for metrics; will be created as needed.
  ## For UDP url endpoint database needs to be configured on server side.
  # database = "telegraf"
database = "influx_db_telegraf"

  ## The value of this tag will be used to determine the database.  If this
  ## tag is not set the 'database' option is used as the default.
  # database_tag = ""

  ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
  ## Telegraf with a user without permissions to create databases or when the
  ## database already exists.
  # skip_database_creation = false

  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
  # retention_policy = ""

  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all".
  ## Only takes effect when using HTTP.
  # write_consistency = "any"

  ## Timeout for HTTP messages.
  # timeout = "5s"

  ## HTTP Basic Auth
  # username = "telegraf"
username = "user_telegraf"

  # password = "metricsmetricsmetricsmetrics"
password = "password"

  ## HTTP User-Agent
  # user_agent = "telegraf"

  ## UDP payload size is the maximum packet size to send.
  # udp_payload = "512B"

  ## Optional TLS Config for use on HTTP connections.
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## HTTP Proxy override, if unset values the standard proxy environment
  ## variables are consulted to determine which proxy, if any, should be used.
  # http_proxy = "http://corporate.proxy:3128"


  ## Additional HTTP headers
  # http_headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "identity"

  ## When true, Telegraf will output unsigned integers as unsigned values,
  ## i.e.: "42u".  You will need a version of InfluxDB supporting unsigned
  ## integer values.  Enabling this option will result in field type errors if
  ## existing data has been written.
  # influx_uint_support = false


###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################

# Read metrics from one or many vCenters
[[inputs.vsphere]]
## List of vCenter URLs to be monitored. These three lines must be uncommented
## and edited for the plugin to work.
vcenters = [ "https://vcenter.sop.renault.fr/sdk" ]
username = "user@vsphere.local"
password = "password"

## VMs
  ## Typical VM metrics (if omitted or empty, all metrics are collected)
  vm_metric_include = [
    "cpu.demand.average",
    "cpu.idle.summation",
    "cpu.latency.average",
    "cpu.readiness.average",
    "cpu.ready.summation",
    "cpu.run.summation",
    "cpu.usagemhz.average",
    "cpu.used.summation",
    "cpu.wait.summation",
    "mem.active.average",
    "mem.granted.average",
    "mem.latency.average",
    "mem.swapin.average",
    "mem.swapinRate.average",
    "mem.swapout.average",
    "mem.swapoutRate.average",
    "mem.usage.average",
    "mem.vmmemctl.average",
    "net.bytesRx.average",
    "net.bytesTx.average",
    "net.droppedRx.summation",
    "net.droppedTx.summation",
    "net.usage.average",
    "power.power.average",
    "virtualDisk.numberReadAveraged.average",
    "virtualDisk.numberWriteAveraged.average",
    "virtualDisk.read.average",
    "virtualDisk.readOIO.latest",
    "virtualDisk.throughput.usage.average",
    "virtualDisk.totalReadLatency.average",
    "virtualDisk.totalWriteLatency.average",
    "virtualDisk.write.average",
    "virtualDisk.writeOIO.latest",
    "sys.uptime.latest",
  ]
  # vm_metric_exclude = [] ## Nothing is excluded by default
  # vm_instances = true ## true by default
## Hosts
  ## Typical host metrics (if omitted or empty, all metrics are collected)
  host_metric_include = [
    "cpu.coreUtilization.average",
    "cpu.costop.summation",
    "cpu.demand.average",
    "cpu.idle.summation",
    "cpu.latency.average",
    "cpu.readiness.average",
    "cpu.ready.summation",
    "cpu.swapwait.summation",
    "cpu.usage.average",
    "cpu.usagemhz.average",
    "cpu.used.summation",
    "cpu.utilization.average",
    "cpu.wait.summation",
    "disk.deviceReadLatency.average",
    "disk.deviceWriteLatency.average",
    "disk.kernelReadLatency.average",
    "disk.kernelWriteLatency.average",
    "disk.numberReadAveraged.average",
    "disk.numberWriteAveraged.average",
    "disk.read.average",
    "disk.totalReadLatency.average",
    "disk.totalWriteLatency.average",
    "disk.write.average",
    "mem.active.average",
    "mem.latency.average",
    "mem.state.latest",
    "mem.swapin.average",
    "mem.swapinRate.average",
    "mem.swapout.average",
    "mem.swapoutRate.average",
    "mem.totalCapacity.average",
    "mem.usage.average",
    "mem.vmmemctl.average",
    "net.bytesRx.average",
    "net.bytesTx.average",
    "net.droppedRx.summation",
    "net.droppedTx.summation",
    "net.errorsRx.summation",
    "net.errorsTx.summation",
    "net.usage.average",
    "power.power.average",
    "storageAdapter.numberReadAveraged.average",
    "storageAdapter.numberWriteAveraged.average",
    "storageAdapter.read.average",
    "storageAdapter.write.average",
    "sys.uptime.latest",
  ]
  # host_metric_exclude = [] ## Nothing excluded by default
  # host_instances = true ## true by default

## Clusters
  # cluster_metric_include = [] ## if omitted or empty, all metrics are collected
  # cluster_metric_exclude = [] ## Nothing excluded by default
  # cluster_instances = true ## true by default

## Datastores
  # datastore_metric_include = [] ## if omitted or empty, all metrics are collected
  # datastore_metric_exclude = [] ## Nothing excluded by default
  # datastore_instances = false ## false by default for Datastores only

## Datacenters
  datacenter_metric_include = [] ## if omitted or empty, all metrics are collected
  datacenter_metric_exclude = [ "*" ] ## Datacenters are not collected by default.
  # datacenter_instances = false ## false by default for Datastores only

  ## Plugin Settings
  ## separator character to use for measurement and field names (default: "_")
  # separator = "_"

  ## number of objects to retreive per query for realtime resources (vms and hosts)
  ## set to 64 for vCenter 5.5 and 6.0 (default: 256)
  # max_query_objects = 256

  ## number of metrics to retreive per query for non-realtime resources (clusters and datastores)
  ## set to 64 for vCenter 5.5 and 6.0 (default: 256)
  # max_query_metrics = 256

  ## number of go routines to use for collection and discovery of objects and metrics
  # collect_concurrency = 1
  collect_concurrency = 8
  # discover_concurrency = 1
  discover_concurrency = 8

  ## whether or not to force discovery of new objects on initial gather call before collecting metrics
  ## when true for large environments this may cause errors for time elapsed while collecting metrics
  ## when false (default) the first collection cycle may result in no or limited metrics while objects are discovered
  # force_discover_on_init = false
  force_discover_on_init = true

  ## the interval before (re)discovering objects subject to metrics collection (default: 300s)
  # object_discovery_interval = "300s"

  ## timeout applies to any of the api request made to vcenter
  # timeout = "20s"
  timeout = "60s"

  ## Optional SSL Config
  # ssl_ca = "/path/to/cafile"
  # ssl_cert = "/path/to/certfile"
  # ssl_key = "/path/to/keyfile"
  ## Use SSL but skip chain & host verification
  # insecure_skip_verify = false
  insecure_skip_verify = true


```

### System info:

/usr/bin/telegraf version
Telegraf 1.11.0 (git: HEAD c9d8f7b0)
Debian 8.10
### Steps to reproduce:

1. ...just starting telegraph using systemctl start telegraf
2. ...

### Expected behavior:
collecting all the infos from my vcenter (17 hosts, 306 VMs)

### Actual behavior:
not collecting all the VMs 

### Additional info:

from the logs : 
2019-06-14T13:01:49Z I! [agent] Config: Interval:1m0s, Quiet:false, Hostname:"nabox", Flush Interval:1m0s
2019-06-14T13:01:49Z D! [agent] Connecting outputs
2019-06-14T13:01:49Z D! [agent] Attempting connection to output: influxdb
2019-06-14T13:01:49Z D! [agent] Successfully connected to output: influxdb
2019-06-14T13:01:49Z D! [agent] Starting service inputs
2019-06-14T13:01:49Z D! [inputs.vsphere]: Starting plugin
2019-06-14T13:01:49Z D! [inputs.vsphere]: Running initial discovery and waiting for it to finish
2019-06-14T13:01:49Z D! [inputs.vsphere]: Creating client: vcenter.sop.renault.fr
2019-06-14T13:01:49Z D! [inputs.vsphere] vCenter maxQueryMetrics is defined: -1
2019-06-14T13:01:49Z D! [inputs.vsphere] vCenter says max_query_metrics should be 10000
2019-06-14T13:01:49Z D! [inputs.vsphere]: Discover new objects for vcenter.sop.renault.fr
2019-06-14T13:01:49Z D! [inputs.vsphere] Discovering resources for datacenter
2019-06-14T13:01:49Z D! [inputs.vsphere] Find(Datacenter, /*) returned 1 objects
2019-06-14T13:01:49Z D! [inputs.vsphere]: No parent found for Folder:group-d1 (ascending from Folder:group-d1)
2019-06-14T13:01:49Z D! [inputs.vsphere] Discovering resources for cluster
2019-06-14T13:01:49Z D! [inputs.vsphere] Find(ClusterComputeResource, /*/host/**) returned 3 objects
2019-06-14T13:01:49Z D! [inputs.vsphere] Found 31 metrics for Compute
2019-06-14T13:01:49Z D! [inputs.vsphere] Found 31 metrics for Infrastructure
2019-06-14T13:01:49Z D! [inputs.vsphere] Found 30 metrics for GPU
2019-06-14T13:01:49Z D! [inputs.vsphere] Discovering resources for host
2019-06-14T13:01:49Z D! [inputs.vsphere] Find(HostSystem, /*/host/**) returned 17 objects
2019-06-14T13:01:49Z D! [inputs.vsphere] Using fast metric metadata selection for host
2019-06-14T13:01:49Z D! [inputs.vsphere] Discovering resources for vm
2019-06-14T13:01:49Z D! [inputs.vsphere] Find(VirtualMachine, /*/vm/**) returned 306 objects -> GOOD NUMBER OF VMs !
2019-06-14T13:01:49Z D! [inputs.vsphere] Using fast metric metadata selection for vm
2019-06-14T13:01:49Z D! [inputs.vsphere] Discovering resources for datastore
2019-06-14T13:01:49Z D! [inputs.vsphere] Find(Datastore, /*/datastore/**) returned 21 objects
2019-06-14T13:02:01Z D! [inputs.vsphere]: Collecting metrics for 247 objects of type vm for vcenter.sop.renault.fr -> WHY ONLY 247 INSTEAD OF 306 ???
2019-06-14T13:02:01Z D! [inputs.vsphere]: Queuing query: 247 objects, 8398 metrics (0 remaining) of type vm for vcenter.sop.renault.fr. Total objects 247 (final chunk)
2019-06-14T13:02:01Z D! [inputs.vsphere] Query for vm has 247 QuerySpecs
