### ISSUE TITLE
socket_listener splits incoming data by line when using TCP, does not when using UDP

### ISSUE THREAD

**Issue by sgtsquiggs** [influxdata/telegraf#6025]
### Relevant telegraf.conf:

```toml
[[inputs.socket_listener]]
  service_address = "tcp://127.0.0.1:7778"
  read_timeout = "10s"
  data_format = "protobuf"
```
(protobuf is my own parser plugin)

### Expected behavior:

socket_listener passes entire buffer to parser (since using Parse not ParseLine)

### Actual behavior:

socket_listener splits buffer on LF character, passes tokens to parser using Parse. This breaks when parsing protobuf because protobuf makes use of LF characters in its encoding.

[Offending code here](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/socket_listener/socket_listener.go#L107-L124)

### Solutions?:

* A `strategy` option for socket_listener to allow splitting on LF vs feeding full buffer
* Expect parser.Parse(buf []byte) to split by LF (if necessary) and have socket_listener pass the entire conn.Read buffer
