### ISSUE TITLE
Can't start Telegraf Service Inputs.exec Linux

### ISSUE THREAD

**Issue by raider111111** [influxdata/telegraf#6028]
### Relevant telegraf.conf:

```toml

[[inputs.exec]]
  ## Commands array
  commands = ["telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1"."$2)}'"]
  ## Timeout for each command to complete.
  timeout = "5s"

  ## measurement name suffix (for separating different commands)
  name_suffix = "_mycollector"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"

```

### Steps to reproduce:

1. Place command in the command block

### Expected behavior:
Display Telegraf version number
### Actual behavior:
Process fails to start
### Additional info:
Failed to start The plugin-driven server agent for reporting metrics into InfluxDB.

Command executes sucessfully in the terminal:
telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1"."$2)}'
1.11

This is probably just formatting but I'm not sure what I'm doing wrong.

**Comment by goller** [comment]
Hey @raider111111 , would you try escaping the double quotes like this:

```toml
  commands = ["telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1\".\"$2)}'"]
```

**Comment by raider111111** [comment]
That worked!

Thanks!

**Comment by raider111111** [comment]
Hi!

That worked but for some reason it isn't sending the data correctly:


```
[[inputs.exec]]
  ## Commands array
  commands = ["telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1\".\"$2)}'"]
  ## Timeout for each command to complete.
  #timeout = "5s"
  ## Timeout for each command to complete.
  timeout = "5s"

Here's my config:

  ## measurement name suffix (for separating different commands)
  #name_suffix = "_mycollector"
  name_override = "TelegrafVersion"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "value"
  data_type = "integer"
```

I'm just trying to send only the Telegraf version number out without the second period, like this:"1.11".

Any idea?

**Comment by goller** [comment]
Hey @raider111111 , because your data_type is `integer` is it trying to convert the output of your awk command to an integer.

What is the output of your command now?  I suspect you have the SHA in there as well.

The resolution will likely be to change the datatype to something other than an integer.

**Comment by raider111111** [comment]
Hi @goller ,
I've tried sending it as a string, float, and integer. 

Here is what I see:
String:
`2019-06-21T17:32:00Z E! [inputs.exec]: Error in plugin: strconv.Atoi: parsing "c9d8f7b0)": invalid syntax`

Float:
`
2019-06-21T17:36:00Z E! [inputs.exec]: Error in plugin: strconv.ParseFloat: parsing "c9d8f7b0)": invalid syntax`

**Comment by goller** [comment]
Yes, I read that as telegraf is not able to parse your awk output as either a pure float or integer.  Your string example looks like it is running Atoi (that'd be converting the output to an integer).

What is the output of the command line when you run it outside of telegraf?

**Comment by raider111111** [comment]
1.11

**Comment by raider111111** [comment]
Well, actually it doesn't work with your edits, but I've encountered Telegraf parsing commands differently so I assumed that was probably fine.

```
telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1\".\"$2)}'
awk: cmd. line:1: {print($1\".\"$2)}
awk: cmd. line:1:          ^ backslash not last character on line
awk: cmd. line:1: {print($1\".\"$2)}
awk: cmd. line:1:          ^ syntax error
```

```telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1"."$2)}'
1.11
```

**Comment by goller** [comment]
yes, my edits with the escaping of " are only applicable in the telegraf YAML.  Those escapes would not be needed when running from the CLI.

try this:

```toml
[[inputs.exec]]
  ## Commands array
  commands = ["sh -c \"telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1\".\"$2)}'\""]
  ## Timeout for each command to complete.
  ## Timeout for each command to complete.
  timeout = "5s"


  ## measurement name suffix (for separating different commands)
  #name_suffix = "_mycollector"
  name_override = "TelegrafVersion"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "value"
  data_type = "string"

```

**Comment by raider111111** [comment]
Sure thing!

That looks better, though I lose the period in the 1.11.

`TelegrafVersion,host=ld08382.homedepot.com value="111" 1561139280000000000
`
Progress!

Any way to get that . back so it's 1.11?

**Comment by goller** [comment]
Yup, so, we can't use an integer in this case, so, you'll need to doubly escape the period and use a string:


```toml
[[inputs.exec]]
  ## Commands array
  commands = ["sh -c \"telegraf --version | awk '{print($2)}' | awk -F '.' '{print($1\\\".\\\"$2)}'\""]
  ## Timeout for each command to complete.
  ## Timeout for each command to complete.
  timeout = "5s"


  ## measurement name suffix (for separating different commands)
  #name_suffix = "_mycollector"
  name_override = "TelegrafVersion"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "value"
  data_type = "string"

```

```sh
 telegraf --test --config howdy.conf
2019-06-21T17:51:58Z I! Starting Telegraf 1.11.0
> TelegrafVersion,host=ip-192-168-194-137.ec2.internal value="1.11" 1561139519000000000

```
