### ISSUE TITLE
Procstat don't send running=0 if process down when use pid_file

### ISSUE THREAD

**Issue by Smiton2006** [influxdata/telegraf#6046]
### Relevant telegraf.conf:
```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.file]]
  files = ["/tmp/metrics.out"]
  data_format = "influx"

[[inputs.procstat]]
   pid_file = "/home/smiton/telegraf/telegraf.pid"
   pid_finder = "native"
```

### System info:
Telegraf 1.11
Debian GNU/Linux 9
### Steps to reproduce:
1. kill -9 `cat /home/smiton/influxdb-1.7.6-1/influx.pid`

### Expected behavior:
procstat_lookup,host=host,pid_finder=native,result=lookup_error pid_count=0i,running=0i,result_code=0i 1561529910000000000
### Actual behavior:
procstat_lookup,host=host,pid_finder=native,result=lookup_error pid_count=1i,running=1i,result_code=0i 1561529910000000000
