### ISSUE TITLE
Azure Monitor - prefix name like procstat for each mount or disk e.g. /sda or /testmount1

### ISSUE THREAD

**Issue by egondalia** [influxdata/telegraf#6055]
See screenshot of current procstats I want same for each disk or mount

Currently I have example:
```toml
# Monitor process cpu and memory usage
[[inputs.procstat]]
  pid_file = "/var/run/cron.pid"
  # Field name prefix
  prefix = "/cron-service"

[[inputs.procstat]]
  pid_file = "/var/run/waagent.pid"
  # Field name prefix
  prefix = "/waaagent-svc"
```
When I go into the Azure Monitor Portal I can select the Process by name e.g.
1) telegraf/procstat >>> Metric = _cron_cpu_time
and
2) telegraf/procstat >>> Metric = _waagent_cpu_time

I now want to do the same for DISK MOUNTS but there doeesnt appear to be a ##Field name prefix so unable to find specifc MOUNTS or DISK any of them would be a good start

```toml
[[inputs.disk]]
  mount_points = ["/testmount11"]
 # Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]

[[inputs.disk]]
  mount_points = ["/testmount22"]
 # Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
```

So I want to be able to select options for 
a) telegraf/disk >> METRIC for /testmount11 
b) telegraf/disk >> METRIC for /testmount22

The option to do this for Disks doesnt seem to be available, appreciate any help on this.
![telegraf issue](https://user-images.githubusercontent.com/33747007/60355420-3a2b4780-99c6-11e9-87ca-52fffe773be2.png)

**Comment by glinton** [comment]
Similar to #3929, but it looks like you want to use `name_override` to override the metric name? See [input docs](https://github.com/influxdata/telegraf/blob/release-1.11/docs/CONFIGURATION.md#input-plugins) for more info on available options.

If you want to see a prefix for disk fields, please indicate and I'll mark this as a feature request.

**Comment by danielnelson** [comment]
What you will want to do is click on the "apply splitting" option in Azure Monitor, this will allow you to split out the series by a tag instead of aggregated across all hosts and mounts.  You can use this with the "add filter" option to limit which series are shown.

You can combine the plugins into a single instance too if you use this method:
```toml
[[inputs.disk]]
  mount_points = ["/testmount11", "/testmount22"]
 # Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
```

I don't recommend using the `prefix` option on the `procstat` plugin anymore either, prefer using the tags instead.
