### ISSUE TITLE
Statsd input plugin crashing

### ISSUE THREAD

**Issue by diraol** [influxdata/telegraf#6075]
### Relevant telegraf.conf:

```toml
[[inputs.statsd]]
  protocol = "udp"
  service_address = ":8123"
  delete_gauges = true
  delete_counters = true
  delete_sets = true
  delete_timings = true
  percentiles = [90, 95, 99]
  metric_separator = "."
  datadog_extensions = true
  allowed_pending_messages = 10000
  percentile_limit = 1000
```

### System info:

Telegraf: 1.11.1 (docker version)
OS: Ubuntu 14.04
Datadog agent version: 1:5.32.4-1

### Steps to reproduce:

1. Run telegraf with statsd plugin enabled (and parsing datadog_extensions).
2. Configure a datadog agent to send metrics to telegraf/statsd.
3. Send invalid metrics to datadog agent (from telegraf/statsd perspective).

Metric example:
> measure.outgoing_requests.response.size:-1.000000|h

### Expected behavior:
telegraf/statsd should log this message (preferably as a warning message, but it can be as error message) and keep going.

### Actual behavior:
telegraf/statsd just blows up.

### Additional info:

Error Logs:

![image](https://user-images.githubusercontent.com/192702/60741825-56d4fb80-9f41-11e9-811e-9be7d73a8b39.png)
