### ISSUE TITLE
ActiveMQ input plugin fails with HTTPS targets

### ISSUE THREAD

**Issue by lbatalha** [influxdata/telegraf#6076]
### Relevant telegraf.conf:

```toml
[[inputs.activemq]]
  server = "https://somebroker.mq.eu-west-1.amazonaws.com"
  port = 8162
  username = "admin"
  password = "admin"
  webadmin = "admin"
  response_timeout = "5s"
```

### System info:
Telegraf 1.11.1, MacOS Mojave, ActiveMQ 5.15.0 (AmazonMQ)

### Steps to reproduce:

1. Set target URL to an HTTPS broker admin page
2. Start Telegraf
3. Plugin errors: `E! [inputs.activemq]: Error in plugin: EOF`

### Expected behavior:
Telegraf plugin connects to activemq admin page and gets metrics
### Actual behavior:
Telegraf fails to connect and get metrics
### Additional info:
SSL certificate is valid, but testing with `insecure_skip_verify = true` (this is actually missing from the README example for the activemq plugin) and tested without uri protocol in target.

Tested with non https activemq locally and works correctly.
