### ISSUE TITLE
Json array it seems doesn't work for http_listener.

### ISSUE THREAD

**Issue by DenKn** [influxdata/telegraf#6082]
### Relevant telegraf.conf:

```toml
# # Generic HTTP write listener
[[inputs.http_listener_v2]]
#   ## Address and port to host HTTP listener on
	service_address = ":8080"
#
#   ## Path to listen to.
	path = "/telegraf"
#
#   ## HTTP methods to accept.
	methods = ["POST", "PUT"]
#   ## Data format to consume.
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
	data_format = "json"

# # Send telegraf metrics to file(s)
[[outputs.file]]
#   ## Files to write to, "stdout" is a specially handled file.
#   files = ["stdout", "/tmp/metrics.out"]
    files = ["/etc/telegraf/metrics.out"]
#
#   ## Data format to output.
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
    data_format = "json"
```
### System info:
telegraf:1.10.4

### Steps to reproduce:

When I sent to http
`{
	"a": 5,
    "test": [
    	{
    		"b": 1
    	},
    	{
        	"b": 2
    	}
	]
}`

### Expected behavior:
{"fields":{"a":5,"test_b":1},"name":"log","tags":{"host":"testhost-elk-g"},"timestamp":1562513750},
{"fields":{"a":5,"test_b":2},"name":"log","tags":{"host":"testhost-elk-g"},"timestamp":1562513750}

Like we see in https://github.com/influxdata/telegraf/tree/master/plugins/parsers/json first arrays example, for array with two values we get two records in file output.

### Actual behavior:
{"fields":{"a":5,"test_0_b":1,"test_1_b":2},"name":"log","tags":{"host":"testhost-elk-g"},"timestamp":1562513750}

How to get expected behavior when we send json array?

Thanks in advance.
