### ISSUE TITLE
global replace not working

### ISSUE THREAD

**Issue by danielarkins** [influxdata/telegraf#6087]
expecting this to replace all occurences of / in fieldname to _per
perhaps this is not supported? my config looks like this:

```toml
[[processors.strings]]
	[[processors.strings.replace]]
		field = "*"
		old = "/"
		new = "_per"
```

but output still has / in field nmae. Also tried this but no luck

```toml
[[processors.strings]]
	[[processors.strings.replace]]
		field = ""
		old = "/"
		new = "_per"
```

**Comment by glinton** [comment]
In the future, please follow the [provided template for issues](https://github.com/influxdata/telegraf/issues/new?template=Bug_report.md)

What version of telegraf are you running?

The following config works with telegraf 1.11. Note the processor doesn't get applied when running telegraf with `--test`
```toml
[agent]
  interval = "1s"
  flush_interval="1s"
  omit_hostname=true

[[inputs.exec]]
  command = "echo 'logfmt thing=\"stuff/\"'"
  data_format = "influx"

[[processors.strings]]
  [[processors.strings.replace]]
    field = "*"
    old = "/"
    new = "_per"

[[outputs.file]]
```
