### ISSUE TITLE
nvidia_smi Fail

### ISSUE THREAD

**Issue by yppdr** [influxdata/telegraf#6106]
### Relevant telegraf.conf:

```toml
###############################################################################
#                                   AGENT                                     #
###############################################################################
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = "telegraf.log"
  hostname = ""
  omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

####################
#  InfluxDB Local  #
####################
[[outputs.influxdb]]
  urls = ["http://192.168.0.41:8086"]
  database = "windows_stats"
  skip_database_creation = false
  # username = "telegraf"
  # password = "metricsmetricsmetricsmetrics"
####################
#  InfluxDB Remote #
####################
#[[outputs.influxdb]]
#  urls = ["http://192.168.1.60:8086"]
#  database = "windows_stats"
#  skip_database_creation = false
#  # username = "telegraf"
#  # password = "metricsmetricsmetricsmetrics"

###############################################################################
#                                  INPUTS                                     #
###############################################################################

############################
#    win_perf_counters     #
############################
[[inputs.win_perf_counters]]
  ###################################
  #               CPU               #
  ###################################
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",
      "% DPC Time",
    ]
    Measurement = "win_cpu"
    IncludeTotal=true
  ###################################
  #               Disk              #
  ###################################
  [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
      "% User Time",
      "% Free Space",
      "Current Disk Queue Length",
      "Free Megabytes",
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Disk Reads/sec",
      "Disk Writes/sec"
    ]
    Measurement = "win_disk"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false
  ###################################
  #               NET               #
  ###################################
  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec",
      "Packets Received Discarded",
      "Packets Outbound Discarded",
      "Packets Received Errors",
      "Packets Outbound Errors",
    ]
    Measurement = "win_net"
  ###################################
  #             System              #
  ###################################
  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [
      "Context Switches/sec",
      "System Calls/sec",
      "Processor Queue Length",
      "Threads",
      "System Up Time",
      "Processes"
    ]
    Instances = ["------"]
    Measurement = "win_system"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false
  ###################################
  #             Memory              #
  ###################################
  [[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes",
      "Standby Cache Reserve Bytes",
      "Standby Cache Normal Priority Bytes",
      "Standby Cache Core Bytes"
    ]
    Instances = ["------"]
    Measurement = "win_mem"
    #IncludeTotal=false
  ###################################
  #              SWAP               #
  ###################################
  [[inputs.win_perf_counters.object]]
    # Example query where the Instance portion must be removed to get data back,
    # such as from the Paging File object.
    ObjectName = "Paging File"
    Counters = [
      "% Usage",
    ]
    Instances = ["_Total"]
    Measurement = "win_swap"
  ###################################
  #              PROC               #
  ###################################
  [[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = [
      "% Processor Time",
      "Handle Count",
      "Private Bytes",
      "Thread Count",
      "Virtual Bytes",
      "Working Set"
      ]
    Instances = ["*"]
    Measurement = "win_proc"
    #IncludeTotal=false

######################################
#             nvidia_smi             #
######################################
[[inputs.nvidia_smi]]
  # bin_path = "/usr/bin/nvidia-smi"
  bin_path = "C:/Program Files/NVIDIA Corporation/NVSMI/nvidia-smi.exe"
  timeout = "5s"
```

### System info:

Win 10 Pro, Telegraf 1.11.2

### Explanation of the bug:

After a fresh installation of telegraf and nvidia smi (via cuda-toolkit) I see in my log that I have an error with the smi:
```
2019-07-10T20: 48: 50Z E! [inputs.nvidia_smi]: Error in plugin: exit status 255
```
I do not understand or could come the mistake because the path is the right one.

### Additional info (log):
```
2019-07-10T20:55:19Z I! Loaded inputs: win_perf_counters nvidia_smi
2019-07-10T20:55:19Z I! Loaded aggregators: 
2019-07-10T20:55:19Z I! Loaded processors: 
2019-07-10T20:55:19Z I! Loaded outputs: influxdb
2019-07-10T20:55:19Z I! Tags enabled: host=LowasPc
2019-07-10T20:55:19Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"LowasPc", Flush Interval:10s
2019-07-10T20:55:20Z E! [inputs.nvidia_smi]: Error in plugin: exit status 255
2019-07-10T20:55:30Z E! [inputs.nvidia_smi]: Error in plugin: exit status 255
2019-07-10T20:55:33Z I! [agent] Hang on, flushing any cached metrics before shutdown
```
