### ISSUE TITLE
kube_inventory not using namespace for persistentvolumes

### ISSUE THREAD

**Issue by Esity** [influxdata/telegraf#6150]
### Relevant telegraf.conf:

```toml
[[inputs.kube_inventory]]
  url = "https://openshift.default.svc.cluster.local" 
  namespace = "telegraf"
  bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
  response_timeout = "10s"
  insecure_skip_verify = true
```

### System info:
Telegraf v1.11.2

### Steps to reproduce:

Collect metrics with limited access in Openshift/kubernetes and set the namespace.

### Expected behavior:
Telegraf should collect persistentvolumes metrics

### Actual behavior:
Telegraf throws an error complaining about how it can't access persistentvolumes at the cluster scope. 

```console
2019-07-22T20:37:00Z E! [inputs.kube_inventory]: Error in plugin: kubernetes api: Failure 403 persistentvolumes is forbidden: User "system:serviceaccount:telegraf:default" cannot list persistentvolumes at the cluster scope: User "system:serviceaccount:telegraf:default" cannot list all persistentvolumes in the cluster
```

### Additional info:
The default telegraf user was given admin access to the namespace
