### ISSUE TITLE
/etc/telegraf.conf needs new sql plugin options

### ISSUE THREAD

**Issue by denzilribeiro** [influxdata/telegraf#6169]
### Relevant telegraf.conf:

```toml
[[inputs.sqlserver]]
  ## Specify instances to monitor with a list of connection strings.
  ## All connection parameters are optional.
  ## By default, the host is localhost, listening on default port, TCP 1433.
  ##   for Windows, the user is the currently running AD user (SSO).
  ##   See https://github.com/denisenkom/go-mssqldb for detailed connection
  ##   parameters.
  # servers = [
  #  "Server=192.168.1.10;Port=1433;User Id=<user>;Password=<pw>;app name=telegraf;log=1;",
  # ]

  ## Optional parameter, setting this to 2 will use a new version
  ## of the collection queries that break compatibility with the original
  ## dashboards. All new functionality is under V2
  query_version = 2

  ## If you are using AzureDB, setting this to true will gather resource utilization metrics
  # azuredb = true 

  ## If you would like to exclude some of the metrics queries, list them here
  ## Possible choices:
  ## - PerformanceCounters
  ## - WaitStatsCategorized
  ## - DatabaseIO
  ## - DatabaseProperties
  ## - CPUHistory
  ## - DatabaseSize
  ## - DatabaseStats
  ## - MemoryClerk
  ## - VolumeSpace
  ## - Schedulers
  ## - AzureDBResourceStats
  ## - AzureDBResourceGovernance 
  ## - SqlRequests
  exclude_query = [ 'Schedulers' , 'SqlRequests']
```

### System info:
Nightly Telegraf build

### Expected behavior:
Telegraf options mentioned here :
https://github.com/influxdata/telegraf/tree/master/plugins/inputs/sqlserver
### Actual behavior:
https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf  missing some of the newer options
### Additional info:
As part of prior pull requests for SQL was I supposed to also updated the telegraf.conf? I didn't realize had to update the conf file
