### ISSUE TITLE
Allow multiple path and name in inputs.cisco_telemetry_gnmi.subscription

### ISSUE THREAD

**Issue by yongz2** [influxdata/telegraf#6176]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Does it possible define multiple path and name in inputs.cisco_telemetry_gnmi.subscription in one confg file?
### Current behavior:
I can define single measurement name and path under inputs.cisco_telemetry_gnmi.subscription now, but if multiple name and path defined it went error. Created multiple "[[inputs.cisco_telemetry_gnmi.subscription]]" doesn't work too. does it possible to crate multiple name and path in one conf file?

[[inputs.cisco_telemetry_gnmi.subscription]]
    ## Name of the measurement that will be emitted
    name = "trafficstats"

    #origin = "openconfig-interfaces"
    path = "/state/port[port-id=*]/ethernet/statistics"

    # Subscription mode (one of: "target_defined", "sample", "on_change") and interval
    subscription_mode = "sample"
    sample_interval = "30s"

    ## Suppress redundant transmissions when measured values are unchanged
    # suppress_redundant = false

    ## If suppression is enabled, send updates at least every X seconds anyway
    # heartbeat_interval = "60s"

### Desired behavior:

[[inputs.cisco_telemetry_gnmi.subscription]]
    ## Name of the measurement that will be emitted
    name1 = "trafficstats"
    name2 = "interface"

    #origin = "openconfig-interfaces"
    path = "/state/port[port-id=*]/ethernet/statistics"
    path2 = "/state/router[router-name=Base]/interface[interface-name=*]"

    # Subscription mode (one of: "target_defined", "sample", "on_change") and interval
    subscription_mode = "sample"
    sample_interval = "30s"

    ## Suppress redundant transmissions when measured values are unchanged
    # suppress_redundant = false

    ## If suppression is enabled, send updates at least every X seconds anyway
    # heartbeat_interval = "60s"

**Comment by danielnelson** [comment]
You should be able to do multiple paths with a configuration like this:
```toml
[[inputs.cisco_telemetry_gnmi]]
  addresses = ["10.49.234.114:57777"]

  [[inputs.cisco_telemetry_gnmi.subscription]]
    name = "foo"
    origin = "openconfig-interfaces"
    path = "/state/port[port-id=*]/ethernet/statistics"
    subscription_mode = "sample"
    sample_interval = "10s"

  [[inputs.cisco_telemetry_gnmi.subscription]]
    name = "bar"
    origin = "openconfig-interfaces"
    path = "/state/router[router-name=Base]/interface[interface-name=*]"
    subscription_mode = "sample"
    sample_interval = "10s"
```

Let me know if it works and if you are still having trouble with a config like this, add the details about what is happening.
