### ISSUE TITLE
Unbound on windows cannot find unbound-control

### ISSUE THREAD

**Issue by pvandervelde** [influxdata/telegraf#6182]
#### Main configuration

Stored in `c:\telegraf\telegraf.conf`

```toml
# Telegraf Configuration

# Global tags can be specified here in key="value" format.
[global_tags]
environment = "environment"
os = "windows"
consul = "client"
category = "my_category"

# Configuration for telegraf agent
[agent]
## Default data collection interval for all inputs
interval = "10s"

## Rounds collection interval to 'interval'
## ie, if interval="10s" then always collect on :00, :10, :20, etc.
round_interval = true

## Telegraf will send metrics to outputs in batches of at most
## metric_batch_size metrics.
## This controls the size of writes that Telegraf sends to output plugins.
metric_batch_size = 1000

## For failed writes, telegraf will cache metric_buffer_limit metrics for each
## output, and will flush this buffer on a successful write. Oldest metrics
## are dropped first when this buffer fills.
## This buffer only fills when writes fail to output plugin(s).
metric_buffer_limit = 10000

## Collection jitter is used to jitter the collection by a random amount.
## Each plugin will sleep for a random time within jitter before collecting.
## This can be used to avoid many plugins querying things like sysfs at the
## same time, which can have a measurable effect on the system.
collection_jitter = "0s"

## Default flushing interval for all outputs. You shouldn't set this below
## interval. Maximum flush_interval will be flush_interval + flush_jitter
flush_interval = "10s"
## Jitter the flush interval by a random amount. This is primarily to avoid
## large write spikes for users running a large number of telegraf instances.
## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
flush_jitter = "0s"

## By default or when set to "0s", precision will be set to the same
## timestamp order as the collection interval, with the maximum being 1s.
##   ie, when interval = "10s", precision will be "1s"
##       when interval = "250ms", precision will be "1ms"
## Precision will NOT be used for service inputs. It is up to each individual
## service input to set the timestamp at the appropriate precision.
## Valid time units are "ns", "us" (or "µs"), "ms", "s".
precision = ""

## Logging configuration:
## Run telegraf with debug log messages.
debug = true
## Run telegraf in quiet mode (error log messages only).
quiet = false
## Specify the log file name. The empty string means to log to stderr.
logfile = "c:/logs/telegraf/telegraf.log"

## Override default hostname, if empty use os.Hostname()
hostname = ""
## If set to true, do no set the "host" tag in the telegraf agent.
omit_hostname = false
```
#### Input / Output configuration

Stored in `c:\config\telegraf\inputs.conf`

```toml
# Telegraf Configuration

# # A plugin to collect stats from Unbound - a validating, recursive, and caching DNS resolver
[[inputs.unbound]]
    ## If running as a restricted user you can prepend sudo for additional access:
    # use_sudo = false

    ## The default location of the unbound-control binary can be overridden with:
    binary = "c:/Program Files/Unbound/unbound-control.exe"

    ## The default timeout of 1s can be overriden with:
    # timeout = "1s"

    ## Use the builtin fielddrop/fieldpass telegraf filters in order to keep/remove specific fields
    # fieldpass = ["total_*", "num_*","time_up", "mem_*"]
    [inputs.unbound.tags]
    influxdb_database = "system"

# Configuration for influxdb server to send metrics to
[[outputs.influxdb]]
    ## The full HTTP or UDP URL for your InfluxDB instance.
    ##
    ## Multiple urls can be specified as part of the same cluster,
    ## this means that only ONE of the urls will be written to each interval.
    # urls = ["udp://127.0.0.1:8089"] # UDP endpoint example
    ## The target database for metrics (telegraf will create it if not exists).
    database = "system" # required

    ## Name of existing retention policy to write to.  Empty string writes to
    ## the default retention policy.
    retention_policy = ""
    ## Write consistency (clusters only), can be: "any", "one", "quorum", "all"
    write_consistency = "any"

    ## Write timeout (for the InfluxDB client), formatted as a string.
    ## If not provided, will default to 5s. 0s means no timeout (not recommended).
    timeout = "5s"
    # username = "telegraf"
    # password = "metricsmetricsmetricsmetrics"
    ## Set the user agent for HTTP POSTs (can be useful for log differentiation)
    user_agent = "telegraf"
    ## Set UDP payload size, defaults to InfluxDB UDP Client default (512 bytes)
    # udp_payload = 512

    ## Optional SSL Config
    # ssl_ca = "/etc/telegraf/ca.pem"
    # ssl_cert = "/etc/telegraf/cert.pem"
    # ssl_key = "/etc/telegraf/key.pem"
    ## Use SSL but skip chain & host verification
    # insecure_skip_verify = false

    ## HTTP Proxy Config
    # http_proxy = "http://corporate.proxy:3128"

    ## Optional HTTP headers
    # http_headers = {"X-Special-Header" = "Special-Value"}

    ## Compress each HTTP request payload using GZIP.
    # content_encoding = "gzip"
    [outputs.influxdb.tagpass]
    influxdb_database = ["system"]
```
### System info:

Telegraf version: `1.10.3`
OS: `Windows 2016 Core (10.0.17134.0)`
Unbound version 1.9.0 installed in the default location (`c:\Program Files\Unbound`)

### Steps to reproduce:

Execute telegraf with the following command line

    telegraf.exe --config c:\telegraf\telegraf.conf --config-directory c:\config\telegraf

### Expected behavior:

Telegraf uses `unbound-control.exe` to gather metrics from unbound

### Actual behavior:

No metrics are gathered from unbound (other system metrics are collected). And the log contains an error saying:

    [inputs.unbound]: Error in plugin: error gathering metrics: error running unbound-control: exec: "c:/Program Files/Unbound/unbound-control.exe": file does not exist (c:/Program Files/Unbound/unbound-control.exe [stats_noreset])

### Additional info:

I've tried different ways to write the path:

    c:/Program Files/Unbound/unbound-control.exe
    c:\Program Files\Unbound\unbound-control.exe
    c:\\Program Files\\Unbound\\unbound-control.exe

But all those variants lead to the same error message. Looking at the code I think the unbound plugin isn't able to handle unbound on windows but there is nothing in the documentation that indicates that.
