### ISSUE TITLE
docker_log input plugin not working

### ISSUE THREAD

**Issue by mmriis** [influxdata/telegraf#6188]
### Relevant telegraf.conf:
```toml
[global_tags]
env = "test"

[agent]
quiet = false
debug = true
interval = "10s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
precision = ""
hostname = ""
omit_hostname = false

[[outputs.influxdb]]
urls = ["https://influxdb:8086"]
database = "metrics"
skip_database_creation = true
timeout = "5s"
username = "telegraf"
password = "xxx"

[[inputs.docker_log]]
endpoint = "unix:///var/run/docker.sock"
container_name_include = ["*mmrtest2*"]
```

### System info:

nightly build 2019/7/31

Running from a daemonset pod in kubernetes that has /var/run/docker.run attached, docker cli works:

```bash
$ docker info
Containers: 87
 Running: 56
 Paused: 0
 Stopped: 31
Images: 44
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
[...]
```
```bash
root@telegraf-logs-h55vb:/# docker ps | grep mmrtest2
98d417188418        strm/helloworld-http                   "/main.sh"               3 weeks ago         Up 3 weeks                              k8s_mmrtest2_mmrtest2-84d96f868d-bx6nx_default_7bfcf44f-9e5f-11e9-840b-d0946682c5ee_0
0dc8252e6f7a        rancher/pause:3.1                      "/pause"                 3 weeks ago         Up 3 weeks                              k8s_POD_mmrtest2-84d96f868d-bx6nx_default_7bfcf44f-9e5f-11e9-840b-d0946682c5ee_0
root@telegraf-logs-h55vb:/# docker logs k8s_mmrtest2_mmrtest2-84
Error: No such container: k8s_mmrtest2_mmrtest2-84
root@telegraf-logs-h55vb:/# docker logs 98d417188418            
Serving HTTP on 0.0.0.0 port 80 ...
10.200.1.17 - - [04/Jul/2019 13:27:49] "GET / HTTP/1.1" 200 -
10.200.1.17 - - [04/Jul/2019 13:27:49] code 404, message File not found
10.200.1.17 - - [04/Jul/2019 13:27:49] "GET /favicon.ico HTTP/1.1" 404 -
10.200.1.17 - - [04/Jul/2019 13:27:51] "GET / HTTP/1.1" 200 -
10.200.1.17 - - [04/Jul/2019 13:27:52] "GET / HTTP/1.1" 200 -
10.200.1.17 - - [04/Jul/2019 13:27:54] "GET / HTTP/1.1" 200 -
10.200.1.17 - - [04/Jul/2019 13:27:54] "GET / HTTP/1.1" 200 -
10.42.2.0 - - [31/Jul/2019 13:58:27] "GET / HTTP/1.1" 200 -
10.42.2.0 - - [31/Jul/2019 13:58:30] "GET / HTTP/1.1" 200 -
root@telegraf-logs-h55vb:/# 
```

### Steps to reproduce:

```bash
$ telegraf -config telegraf.conf -test
```

### Expected behavior:
Collecting logs.

### Actual behavior:
It gets container list, but gives the following error for each container:
```bash
telegraf -config telegraf.conf -test
2019-07-31T14:04:42Z I! Starting Telegraf 
2019-07-31T14:04:42Z D! [agent] Initializing plugins
2019-07-31T14:04:42Z D! [agent] Starting service inputs
2019-07-31T14:04:42Z D! [agent] Waiting for service inputs
2019-07-31T14:04:42Z D! [agent] Stopping service inputs
2019-07-31T14:04:42Z E! [inputs.docker_log]: Error in plugin: context canceled
2019-07-31T14:04:42Z E! [inputs.docker_log]: Error in plugin: context canceled
```
