### ISSUE TITLE
--test flag doesn't run processors or aggregators

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#6190]
Looks like processors and aggregators are not being applied when the `--test` flag is enabled.

I think we need to add this code block:
https://github.com/influxdata/telegraf/blob/master/agent/agent.go#L89

to the test function, but i'm not sure.

### Relevant telegraf.conf:
```toml
[[inputs.exec]]
  commands = ['sh ./test.sh']
  data_format = "influx"

[[processors.strings]]
  [[processors.strings.left]]
    field = "l"
    width = 4

[[processors.converter]]
  [processors.converter.fields]
    integer = ["m"]
    
[[outputs.file]]
  files = ["stdout"]
```

test.sh
```
#!/bin/sh

echo 'example,tag1=a,tag2=b i=42i,j=43i,k=44i,l="anything",m=true'
```
