### ISSUE TITLE
Ping Input Plugin settings

### ISSUE THREAD

**Issue by eaidland** [influxdata/telegraf#6217]
### Relevant telegraf.conf:

```toml
[[inputs.ping]]
  ## List of urls to ping
  urls = [ "http://localhost:8086/ping" ]

  ## Number of pings to send per collection (ping -c <COUNT>)
  # count = 1

  ## Interval, in s, at which to ping. 0 == default (ping -i <PING_INTERVAL>)
  ## Not available in Windows.
  # ping_interval = 1.0

  ## Per-ping timeout, in s. 0 == no timeout (ping -W <TIMEOUT>)
  # timeout = 1.0

  ## Total-ping deadline, in s. 0 == no deadline (ping -w <DEADLINE>)
  # deadline = 10

  ## Interface or source address to send ping from (ping -I <INTERFACE/SRC_ADDR>)
  ## on Darwin and Freebsd only source address possible: (ping -S <SRC_ADDR>)
  # interface = ""

  ## Specify the ping executable binary, default is "ping"
  # binary = "ping"
 ## Arguments for ping command
  ## when arguments is not empty, other options (ping_interval, timeout, etc) will be ignored
  # arguments = ["-c", "3"]

```

### System info:
ubuntu 16.04
Telegraf 1.10.3

https://github.com/influxdata/telegraf/tree/master/plugins/inputs/ping

How to one change the settings so that it's not only the field result_code that's stored, but also e.g "average_response_ms"?

Thanks
