### ISSUE TITLE
'tls_ca' is not defined in jti_openconfig_telemetry

### ISSUE THREAD

**Issue by ladvocat** [influxdata/telegraf#6219]
### Relevant telegraf.conf:

```toml
  tls_ca = "/etc/telegraf/certs/ca.pem"
  ssl_cert = "/etc/telegraf/certs/server.pem"
```

### System info:

telegraf 1.7
docker 18.09.6
ubuntu server 16.04

When I run the container I receive the following log:

[telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, line 11: field corresponding to **`tls_ca' is not defined** in jti_openconfig_telemetry.OpenConfigTelemetry

It seems that tls_ca is not supported. I also tried to set the **insecure_skip_verify = true**, but it is not supported.

How could I enable the TLS handshake with a self-signed certificate?
