### ISSUE TITLE
docker_log does not work correctly with multiple like containers on a host and has var inconsistency

### ISSUE THREAD

**Issue by pschwartz** [influxdata/telegraf#6220]
### Relevant telegraf.conf:
```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.elasticsearch]]
  urls = [ "<ES url>" ]
  timeout = "5s"
  enable_sniffer = false
  health_check_interval = "10s"
  index_name = "gitlab-runner-%Y.%m.%d" # required.
  manage_template = true
  template_name = "gitlab-runner"
  overwrite_template = false

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
[[inputs.docker_log]]
  endpoint = "unix:///var/run/docker.sock"
```

### System info:

RHEL 7.3
Lastest nightly 08-05-2019

### Steps to reproduce:

1. Setup docker
2. Setup Telegraf with config (external ES server needed)
3. Start multiple containers from the same container image and add multiple labels to the container. 
    `docker run -it -label "foo=bar, blah=blah, container_num=1" --name "container-1" alpine:latest` (exit container)
    `docker run -it -label "foo=bar, blah=blah, container_num=2" --name "container-2" alpine:latest` (exit container)
4. View data in ES.

### Expected behavior:
Log lines should have all labels from the containers as tags. As well as records for each container

Tags seen on records:
```
    "tag": {
      `-label "foo=bar, blah=blah, container_num=1"`
      "foo": "bar",
      "blah": "blah",
      "container_num": 1,
      "container_image": "alpine",
      "container_name": "container-1",
      "container_version": "latest",
      "host": "localhost",
      "stream": "stdout"
    }
```
```
    "tag": {
      `-label "foo=bar, blah=blah, container_num=1"`
      "foo": "bar",
      "blah": "blah",
      "container_num": 2,
      "container_image": "alpine",
      "container_name": "container-2",
      "container_version": "latest",
      "host": "localhost",
      "stream": "stdout"
    }
```

### Actual behavior:

Log lines should have all labels from the containers as tags. But only records from a single container is seen. Also, `container_image` is being filled in as the term `sha256` instead of the container image.

Tags seen on records:
```
    "tag": {
      `-label "foo=bar, blah=blah, container_num=1"`
      "foo": "bar",
      "blah": "blah",
      "container_num": 1,
      "container_image": "sha256",
      "container_name": "container-1",
      "container_version": "latest",
      "host": "localhost",
      "stream": "stdout"
    }
```
