### ISSUE TITLE
Direct traffic to desired destinations based on a given tag in the metric provided by source.

### ISSUE THREAD

**Issue by wltu** [influxdata/telegraf#6239]
## Feature Request
Currently, multiple instances of the output plugins are needed for any metrics to be send to a specific destination of a given output type. This requires filtering configuration for the output plugins using either `tagpass/tagexclude`. There should be a way to have one instance of the output plugin and uses the tag that specify the output destination to direct the metrics.

### Proposal:
Have a setting to configure the tag key that will be used to direct the traffic. Set to empty string will act as if no change happened. 

In the proposed feature, the batch of metrics will be separated out into sub buckets based on the output destination. Each bucket will then be sent to the specific destination specified by the tag value. Any metrics with the specific tag key will be sent to normal writing method.

### NOTE:
As a proof of concept I will just be talking specifically about `outputs.influxdb`, however, this could work for many more output plugins.

### Current behavior:
To direct metrics to specific output, multiple output plugins are required with filter to separate out the traffic as shown with the configuration below.
``` toml
[[outputs.influxdb]]
  urls = [ "http://influxdb0:8086" ]
  database = "telegraf"
  # Only store measurements where the tag "host" matches the value "host0"
  [outputs.influxdb.tagpass]
    host = ["host0"]

[[outputs.influxdb]]
  urls = [ "http://influxdb1:8086" ]
  database = "telegraf"
  # Only store measurements where the tag "host" matches the value "host1"
  [outputs.influxdb.tagpass]
    host = ["host1"]
```

With the configuration as shown, we can separate out the metrics sent by different hosts into its own influxDB database. However, we needed to add more output instances as the number of hosts increases. 

### Desired behavior:
With the proposed feature, we can do it all one instance of the output plugin as long as it has enough resources as shown below.

``` toml
[[outputs.influxdb]]
  urls = [ "http://influxdb-default:8086" ]
  database = "telegraf"
  # Enabling the new feature
  direct_from_tag = "__url__"
```

With the configuration above, the output plugin will traffic base on the value in the `__url__` tag. The `__url__` can be added by the source to target the desired destination.

### Use case: 
The use cases includes whenever we want to separate out the metrics by some of the tag value and can easily be determined by the source. This can allow better analysis of the data if all the related data are in the same backend database.
