### ISSUE TITLE
StatsD input plugin  do not works with UDP

### ISSUE THREAD

**Issue by acanimal** [influxdata/telegraf#6244]
Hi,
my problem seems reparted in this closed issue: https://github.com/influxdata/telegraf/issues/6227

The issue is if I configure the statsd input with UDP (the default) no metric is collected and I can't see any error in logs.
If I change to use TCP all seems to works fine.

### Relevant telegraf.conf:

```toml
[[inputs.statsd]]
  name_prefix = "local_statsd_"
 # I need to user `protocol = "tcp"` to make it work
  service_address = ":8125"

[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "xxx"
  username = "xxx"
  password = "xxx"
```

### System info:

Working with docker container 1.9 version:

```
  telegraf:
    image: telegraf:1.9
    # network_mode: "host"
    networks:
      - monitoring
    ports:
      - "8125:8125"
    volumes:
      - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf
    restart: always
```
### Steps to reproduce:

1. Configure statsd to use udp
2. Send some info `echo "user.logins:1|c" | nc -D -v -u localhost 8125`
3. Nothin is stored in influxdb

4. Configure statsd to use tcp
5. send some info `echo "user.logins:1|c" | nc -D -v localhost 8125`
6. a new `local_stats_user_login measure appears in influxdb
