### ISSUE TITLE
Logparser & Docker logs

### ISSUE THREAD

**Issue by IosifZ** [influxdata/telegraf#6252]
Hello people,

I'm in desperate need of some help.

Architecture:

OS: Windows 10 Pro
Docker for Windows
 - 18 containers, among other things, InfluxDB, Chronograf and Grafana.
Telegraf installed on Windows and reporting host and Docker metrics to InfluxDB and displayed in Grafana. All ok.

Now I'm trying to get all Docker logs to InfluxDB. Why InfluxDB and not ELK you might wonder. I am in no means an expert in programing stuff. So if I managed to get the TIG stack working and getting friendly I prefer to keep all things there.

Using Portainer I observed that all the containers logs are in the below location:
/var/lib/docker/containers/containerID/container ID-json.log

Here is my docker compose file (only Influxdb and telegraf parts)
```
version: '3.3'
services:
  influxdb-telegraf:
    image: 'influxdb:latest'
    container_name: influxdb-telegraf
    hostname: influxdb-telegraf
    volumes:
      - '.\influxdb-telegraf:/var/lib/influxdb'
      - '.\influxdb-telegraf\etc:/etc/influxdb/'
    ports:
      - '8086:8086'
    restart: unless-stopped
    labels:
      - 'traefik.frontend.rule=Host:influxdb-telegraf.localhost'
      - traefik.backend=influxdb-telegraf
    env_file:
      - .env
    environment:
      - 'TZ=${TZ}'
      - com.ouroboros.enable=true
  telegraf:
      image: 'telegraf:latest'
      container_name: telegraf
      hostname: telegraf
      volumes:
        - '.\telegraf\telegraf.conf:/etc/telegraf/telegraf.conf'
        - '.\telegraf\logs\:/var/lib/docker/containers/'
        - '/var/run/docker.sock:/var/run/docker.sock'
      ports:
        - '8092:8092/udp'
        - '8094:8094'
        - '8125:8125/udp'
```
Telegraf container conf:
```
[[outputs.influxdb]]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  ## urls = ["udp://127.0.0.1:8089"]
  urls = ["http://influxdb-telegraf:8086"]

  ## The target database for metrics; will be created as needed.
  ## For UDP url endpoint database needs to be configured on server side.
   database = "containers"

  ## The value of this tag will be used to determine the database.  If this
  ## tag is not set the 'database' option is used as the default.
   database_tag = "containers"

  ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
  ## Telegraf with a user without permissions to create databases or when the
  ## database already exists.
   skip_database_creation = true

  ## Name of existing retention policy to write to.  Empty string writes to
  ## the default retention policy.  Only takes effect when using HTTP.
   retention_policy = ""

  ## Write consistency (clusters only), can be: "any", "one", "quorum", "all".
  ## Only takes effect when using HTTP.
   write_consistency = "any"

  ## Timeout for HTTP messages.
   timeout = "5s"

  ## HTTP Basic Auth
   username = "containers"
   password = "containers"

  ## HTTP User-Agent
   user_agent = "telegraf"
[[inputs.logparser]]
  ## Log files to parse.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   /var/log/**.log     -> recursively find all .log files in /var/log
  ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
  ##   /var/log/apache.log -> only tail the apache log file
  'files = ["/var/lib/docker/containers/*/*.log"]'

  ## Read files that currently exist from the beginning. Files that are created
  ## while telegraf is running (and that match the "files" globs) will always
  ## be read from the beginning.
  from_beginning = false

  ## Method used to watch for file updates.  Can be either "inotify" or "poll".
  # watch_method = "inotify"

  ## Parse logstash-style "grok" patterns:
  [inputs.logparser.grok]
    ## This is a list of patterns to check the given log file(s) for.
    ## Note that adding patterns here increases processing time. The most
    ## efficient configuration is to have one pattern per logparser.
    ## Other common built-in patterns are:
    ##   %{COMMON_LOG_FORMAT}   (plain apache & nginx access logs)
    ##   %{COMBINED_LOG_FORMAT} (access logs + referrer & agent)
    patterns = ["%{COMBINED_LOG_FORMAT}"]

    ## Name of the outputted measurement name.
    measurement = "apache_access_log"

    ## Full path(s) to custom pattern files.
    custom_pattern_files = []

    ## Custom patterns can also be defined here. Put one pattern per line.
    custom_patterns = '''
```
Telegraf container log:
```
2019-08-13T20:13:32Z I! Starting Telegraf 1.11.3,
2019-08-13T20:13:32Z I! Using config file: /etc/telegraf/telegraf.conf,
2019-08-13T20:13:32Z I! Loaded inputs: logparser,
2019-08-13T20:13:32Z I! Loaded aggregators: ,
2019-08-13T20:13:32Z I! Loaded processors: ,
2019-08-13T20:13:32Z I! Loaded outputs: influxdb,
2019-08-13T20:13:32Z I! Tags enabled: host=containers,
2019-08-13T20:13:32Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"containers", Flush Interval:10s,
```
So it seems fine. But in Choronograf I don't see anything being stored in containers db.

InfluxDB works fine as it receives metrics received from the Telegraf Windows installation without any problems.

I have a sserious doubt that I'm the first one trying to accomplish this. Can anyone please help me with my config issues ?

Thanks.
