### ISSUE TITLE
thousands of "awk" and "sed" zombie processes with the native procstat plugin on MacOS

### ISSUE THREAD

**Issue by jimis** [influxdata/telegraf#6265]
### Relevant telegraf.conf:

```toml
[[inputs.procstat]]
  exe = "coin-"
  pid_finder = "native"
```

### System info:

Telegraf 1.11.4
MacOS X 10.13

### More details

"sed" and "awk" processes flood the process table until the system comes down to a halt. I'm quite sure it's because of the procstat plugin, as the problem went away once I used "pgrep" as the pid_finder.
