### ISSUE TITLE
Minecraft input plugin isn't loading metrics

### ISSUE THREAD

**Issue by AWegnerGitHub** [influxdata/telegraf#6287]
### Relevant telegraf.conf:

```toml
[[inputs.minecraft]]
  ## Address of the Minecraft server.
  server = "192.168.10.187"
  ## Server RCON Port.
  port = "25575"
  ## Server RCON Password.
  password = "AREALPASSWORD"
  [inputs.minecraft.tags]
    influx_database = "telegraf_server"

```

### System info:

```$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
Telegraf version: 1.11.4-1 (installed via apt-get)
Minecraft server: 1.14.4
Only plugins installed on minecraft are EssentialsX and Dynmap. 
Rcon is enabled. Correct password, port and host are provided. 
Scoreboard is set up and objectives can be seen in game.

### Steps to reproduce:

1. Enabled minecraft telegraf plugin with the configuration above
2. Restarted Telegraf
3. Logged into Minecraft server. Checked score board and see that results are changing as expected
4. Check influxdb for minecraft measurements. Nothing.

### Expected behavior:

Minecraft measurements would be sent to influxdb like all my other metrics. None of those metrics are failing unexpectedly.

### Actual behavior:

No minecraft measurements are sent. 

### Additional info:

Minecraft plugin is listed as being loaded in the telegraf log:

    2019-08-20T19:24:45Z I! Loaded inputs: diskio minecraft exec internal cpu disk kernel mem processes swap system influxdb zfs snmp snmp snmp

Doing a test run of telegraf doesn't show any minecraft metrics:

    $ sudo -u telegraf telegraf --config /etc/telegraf/telegraf.conf --test --input-filter=minecraft
    2019-08-20T19:52:54Z I! Starting Telegraf 1.11.4

(Other filtered metrics product a result)

No errors are appearing in 

    $ sudo journalctl -u telegraf
    Aug 20 14:24:45 mc-server systemd[1]: Started The plugin-driven server agent for reporting metrics into InfluxDB.
    Aug 20 14:24:45 mc-server telegraf[18978]: 2019-08-20T19:24:45Z I! Starting Telegraf 1.11.4

All of my other metrics are loading as expected and are using `[inputs.*.tags]`
