### ISSUE TITLE
Enum documentation is incorrect when value is unknown and dest is set

### ISSUE THREAD

**Issue by Woodz** [influxdata/telegraf#6291]
The documentation for the default value reads `Default value to be used for all values not contained in the mapping table. When unset, the unmodified value for the field will be used if no match is found.`

However, if default value is unset and `dest` is set, the unmodified value is not used - the dest field is missing.

Version: 0a4d74c82714da656ea454969c2083ef1d1bacfa

Reproducible:
### Configuration: 
```toml
[[processors.enum]]
[[processors.enum.mapping]]
## Name of the field to map
field = "status"
## Name of the tag to map
# tag = "status"
## Destination tag or field to be used for the mapped value. By default the 
## source tag or field is used, overwriting the original value.
dest = "status_code"
## Default value to be used for all values not contained in the mapping
## table. When unset, the unmodified value for the field will be used if no
## match is found.
# default = 0
## Table of mappings
[processors.enum.mapping.value_mappings]
green = 1
amber = 2
red = 3 
```

### Expected (based on doc):
```diff
- xyzzy status="black" 1502489900000000000
+ xyzzy status="black",status_code="black" 1502489900000000000
```

### Actual:
```diff
- xyzzy status="black" 1502489900000000000
+ xyzzy status="black" 1502489900000000000
```

Now, I don't think the expected is sensible, but there is no unit test to show the correct expected behaviour, but my recommendation would be to correct the documentation and add a unit test to match the current implementation.
