### ISSUE TITLE
Logs full of `Error killing process: os: process already finished`

### ISSUE THREAD

**Issue by glinton** [influxdata/telegraf#6294]
### Relevant telegraf.conf:
```toml
[[inputs.exec]]
  timeout="1s"
  command = "echo"
```

### Actual behavior:
Every `interval`, the following is logged:
`E! [agent] Error killing process: os: process already finished`
