### ISSUE TITLE
Telegraf jenkins plugin example config missing header

### ISSUE THREAD

**Issue by perzizzle** [influxdata/telegraf#6310]
### Relevant telegraf.conf:
```toml
[[inputs.jenkins]]
  url = "http://localhost:8080"
...
```

### Additional info:
The jenkins plugin documentation is missing the header [[inputs.jenkins]] in the example config
