### ISSUE TITLE
SNMP integer fields are not translated

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#6330]
It seems that integer fields that have translations available, are actually not translated. I thought it should have been set in the field `conversion` parameter, but it seems there is no `translate` or similar option.

It seems like I could work around by using something as the reverse of the enum processor plugin. (not sure if this is possible)

### Relevant telegraf.conf:
```toml
  [[inputs.snmp.table]]
    name = "interface"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifName"
      is_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifAdminStatus"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "ifInOctets"
      oid = "IF-MIB::ifHCInOctets"

    [[inputs.snmp.table.field]]
      name = "ifOutOctets"
      oid = "IF-MIB::ifHCOutOctets"
```

### System info:

Telegraf 1.11.4 (git: HEAD d9ca76e4)
RedHat 7.4

### Expected behavior:
```
> interface,ifAdminStatus=up(1),ifName=InLoopBack0 ifInOctets=0i,ifOutOctets=0i
```
### Actual behavior:
```
> interface,ifAdminStatus=1,ifName=InLoopBack0 ifInOctets=0i,ifOutOctets=0i
```
### Additional info:
Mib:
```mib
ifAdminStatus OBJECT-TYPE
    SYNTAX INTEGER {
        up(1),
        down(2),
        testing(3)
        }
    ACCESS read-write
    STATUS mandatory
    DESCRIPTION
        "The desired state of the interface.  The testing(3) state
        indicates that no operational packets can be passed.  When a
        managed system initializes, all interfaces start with
        ifAdminStatus in the down(2) state.  As a result of either
        explicit management action or per configuration information
        retained by the managed system, ifAdminStatus is then
        changed to either the up(1) or testing(3) states (or remains
        in the down(2) state)."
    ::= { ifEntry 7 }
```
Output from `snmpget`:
```
IF-MIB::ifAdminStatus.1 = INTEGER: up(1)
```

**Comment by goller** [comment]
@Hipska I like your idea of using the entire enum value as the tag.

comes from:

```
SYNTAX INTEGER {
       up(1),
       down(2),
       testing(3)
       }
```

Previously, I had been thinking of just `up` rather than `up(1)`... I like your way better for sure.

**Comment by Hipska** [comment]
It would be nice if it was an option to choose which you want.

**Comment by Hipska** [comment]
Does anyone knows if this can be worked around by using Enum processor plugin? And how should it be done?

**Comment by danielnelson** [comment]
I think this will handle it:
```toml
[[processors.enum]]
  namepass = ["interface"]
  [[processors.enum.mapping]]
    tag = "ifAdminStatus"
    default = "unknown"
    [processors.enum.mapping.value_mappings]
      1 = "up"
      2 = "down"
      3 = "testing"
```

**Comment by Hipska** [comment]
@danielnelson Damn, I missed that comment. I just came back to this issue to report that I figured out the following workaround:
```toml
# Translate tag and field values for interface table
[[processors.enum]]
  namepass = ["interface"]

  [[processors.enum.mapping]]
    ## Name of the tag to map
    tag = "ifAdminStatus"

    ## Table of mappings
    [processors.enum.mapping.value_mappings]
      1 = "up"
      2 = "down"
      3 = "testing"

  [[processors.enum.mapping]]
    ## Name of the field to map
    field = "status"

    ## Table of mappings
    [processors.enum.mapping.value_mappings]
      1 = "up"
      2 = "down"
      3 = "testing"
      4 = "unknown"
      5 = "dormant"
      6 = "notPresent"
      7 = "lowerLayerDown"
```

But the issue needs to stay open as it is double work if this is doing something that can be done by `snmptranslate` immediately.
