### ISSUE TITLE
Telegraf cloudwatch inputs throws errors like *E! [inputs.cloudwatch]: Error in plugin: no metrics found to collect* 

### ISSUE THREAD

**Issue by hflamboauto1** [influxdata/telegraf#6337]
### Relevant telegraf.conf:

```toml
[[inputs.cloudwatch]]
  region = "eu-west-1"
  interval = "5m"
  namespace = "AWS/RDS"
  period = "1m"
  delay = "0s"
```

### System info:

Telegraf 1.11.5

### Steps to reproduce:

1. ... Add cloudwatch input to a region / namespace that has no activity e.g **AWS/RDS** with no running instances from a while.

### Expected behavior:

Error message should be a **WARN** and not an _ERROR_ and logged message would be great to have more info(s) like the relevant **namespace** and **region** of target cloudwatch input

I n case **warn** is found to not be useful ..  then **info** would be great

### Actual behavior:

**Current**
```
E! [inputs.cloudwatch]: Error in plugin: no metrics found to collect
```

Also would be very useful to output on message the relevant input namespace .eg **AWS/RDS**

**Wanted**
```
W! [inputs.cloudwatch]: Error in plugin: no metrics found to collect from namespace: AWS/RDS
```
### Additional info:
```
2019-09-02T12:15:00Z E! [inputs.cloudwatch]: Error in plugin: no metrics found to collect
```
