### ISSUE TITLE
inputs.exec for windows not working with spaces

### ISSUE THREAD

**Issue by TheSilverHawkx** [influxdata/telegraf#6339]
This post is less of an issue / or bug, but I think could greatly benefit users running telegraf in a Windows environment.

After reading almost every issue regarding having spaces inside a path in Windows and having this problem myself, an old colleague of mine introduced me to "Short Path Names".

Basically windows as an OS shortens names of files to fit their file name structure of 8.3 characters.

Therefore names which are longer than 8 character are reduced to a shorter name,example:
"C:\Program Files\" will be reduced to "C:\PROGRA~1"

This option works with a telegraf agent and therefore is a good solution in case you have to have spaces in your path.

Here's my working exec:
```toml
[[inputs.exec]]
  commands = [ "powershell 'C:/PROGRA~1/Telegraf/Configs/WinCluster/WinClusterSharedVolumeSpace.ps1' "]
  timeout = "5s"
  data_format = "influx"
```
Notice the following things:
1. Script Path is wrapped with single quotation mark ( `'` ) and not double (`"`)
2. Instead of using backslash (`\\` or `\`) use regular slash (`/`) like in linux.

In order to find the "Short Path Name" of a file or folder open a cmd window and type the following:
```
cd [folder containing file (or folder) with spaces]
cd /x
```
To the left of the regular file name you'll have the short file name. 

To read more about the subject you can look up "windows short path names" or "8.3 filename"
