### ISSUE TITLE
Add node name prefix to Jenkins input plugin so that we can separate multiple master on the same Docker instance. 

### ISSUE THREAD

**Issue by KjellTillstrand** [influxdata/telegraf#6359]
Add node name prefix to Jenkins input plugin so that we can separate multiple masters on the same Docker instance. 

### Proposal:
```
[[inputs.jenkins]]
url = "http://localhost:8080"
username = "username"
password = "pass"
nodeprefix = XX

[[inputs.jenkins]]
url = "http://localhost:8081"
username = "username"
password = "pass"
nodeprefix = YY
```

The nodeprefix string should the be concatenated to the node name if it exist in the 

### Current behavior:
All Jenkins masters will have node name "master" when telegraf is run outside the container which makes it impossible to separate the node metrics in influx.   

### Desired behavior:
Separation between node metrics in influx when multiple Jenkins masters are present on the same host. 

### Use case: 
Running multiple Jenkins masters in docker on the same host I would guess is a common use case. The Telegraf Jenkins plugin would be mor effictive in this scenario if we could have this feature.

**Comment by danielnelson** [comment]
As a workaround you can add a static tag to each plugin:
```toml
[[inputs.jenkins]]
  url = "http://localhost:8080"
  username = "username"
  password = "pass"
  [inputs.jenkins.tags]
    node = "XX"

[[inputs.jenkins]]
  url = "http://localhost:8081"
  username = "username"
  password = "pass"
  [inputs.jenkins.tags]
    node = "YY"
```

I'd like to address this by adding `source` and `port` tags to the plugin.
