### ISSUE TITLE
telegraf run as a windows service not working properly, the service is running but no data send out.

### ISSUE THREAD

**Issue by michaelpassion** [influxdata/telegraf#6370]
### Relevant telegraf.conf:

```toml
[global_tags]
vm_uuid = "xxxxxxxxxxxxxxxxxxxx"
vm_os_type = "windows"
[agent]
interval = "60s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
flush_buffer_when_full = true
collection_jitter = "5s"
flush_interval = "60s"
flush_jitter = "10s"
debug = false
quiet = false
[[outputs.socket_writer]]
address = "tcp4://169.254.169.254:8094"
data_format = "influx"
[[inputs.win_perf_counters]]
[[inputs.win_perf_counters.object]]
ObjectName = "Processor"
Instances = ["*"]
Counters = ["% Idle Time","% Interrupt Time","% Privileged Time","% User Time", "% Processor Time","% DPC Time",]
Measurement = "vm_win_cpu"
IncludeTotal = true
[[inputs.win_perf_counters.object]]
ObjectName = "LogicalDisk"
Instances = ["*"]
Counters = ["% Idle Time","% Disk Time","% Disk Read Time","% Disk Write Time", "Current Disk Queue Length","% Free Space","Free Megabytes",]
Measurement = "vm_win_disk"
[[inputs.win_perf_counters.object]]
ObjectName = "PhysicalDisk"
Instances = ["*"]
Counters = ["Disk Read Bytes/sec","Disk Write Bytes/sec","Current Disk Queue Length","Disk Reads/sec", "Disk Writes/sec","% Disk Time","% Disk Read Time","% Disk Write Time",]
Measurement = "vm_win_diskio"
[[inputs.win_perf_counters.object]]
ObjectName = "Network Interface"
Instances = ["*"]
Counters = ["Bytes Received/sec","Bytes Sent/sec","Packets Received/sec","Packets Sent/sec", "Packets Received Discarded","Packets Outbound Discarded","Packets Received Errors","Packets Outbound Errors",]
Measurement = "vm_win_net"
[[inputs.win_perf_counters.object]]
ObjectName = "Memory"
Instances = ["------"]
Counters = ["Available Bytes","Cache Faults/sec","Demand Zero Faults/sec","Page Faults/sec", "Pages/sec","Transition Faults/sec","Pool Nonpaged Bytes","Pool Paged Bytes","Standby Cache Reserve Bytes","Standby Cache Normal Priority Bytes","Standby Cache Core Bytes",]
Measurement = "vm_win_mem"
[[inputs.win_perf_counters.object]]
ObjectName = "Process"
Instances = ["*"]
Counters = ["% Processor Time","Handle Count","Private Bytes","Thread Count","Virtual Bytes","Working Set",]
Measurement = "vm_win_proc"
[[inputs.win_perf_counters.object]]
ObjectName = "System"
Instances = ["------"]
Counters = ["Context Switches/sec","System Calls/sec","Processor Queue Length","System Up Time",]
Measurement = "vm_win_system"
```

### System info:

Telegraf v1.7.4
Windows Server 2012R2

### Steps to reproduce:

1. very hard to reproduce. Telegraf agent on Windows 2012R2 stop to report data to socket listener after it has run a period of time. This phenomenon happed to serval windows machine.

### Expected behavior:
Write data to socket listener continually
### Actual behavior:
Stop write data after a period time, but the telegraf service is still running
### Additional info:

The service is still at running state
![image](https://user-images.githubusercontent.com/6369683/64519563-f12d3300-d326-11e9-96a9-43177123e28b.png)
![image](https://user-images.githubusercontent.com/6369683/64519607-04400300-d327-11e9-8203-950c7d64f611.png)

![image](https://user-images.githubusercontent.com/6369683/64519579-f7231400-d326-11e9-978b-6b3ece2d99d8.png)

No warning or error reported to Windows Event Viewer
![image](https://user-images.githubusercontent.com/6369683/64519596-fc805e80-d326-11e9-82b8-f90fa9659b92.png)

Is there anything I can do to investigate this problem as the the config file has no log file information.
