### ISSUE TITLE
apcupsd missing field

### ISSUE THREAD

**Issue by MorphBonehunter** [influxdata/telegraf#6373]
### Relevant telegraf.conf:

```toml
# Monitor APC UPSes connected to apcupsd
[[inputs.apcupsd]]
  # A list of running apcupsd server to connect to.
  # If not provided will default to tcp://127.0.0.1:3551
  servers = ["tcp://127.0.0.1:3551"]

  ## Timeout for dialing server.
  timeout = "5s"
```

### System info:

Telegraf 1.12.0 (git: master 43bb6941d2f9f8430241986c485082e7d85310d2)
OS: Archlinux

### Steps to reproduce:
Based on the [Doku](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/apcupsd/README.md) there should be an field `online` in the plugin output but this is missing.
There is an undokumented field `status_flags` in the output.

1. telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d/ --input-filter apcupsd --test

### Expected behavior:
The field `online` should be printed.

### Actual behavior:
There is an field `status_flags` but no `online`.

### Additional info:
Example Output:
```
2019-09-10T07:02:34Z I! Starting Telegraf 1.12.0
> apcupsd,host=pandora,serial=3B0746X61711,status=ONLINE,ups_name=pandora battery_charge_percent=100,battery_voltage=13.5,input_frequency=50,input_voltage=224,internal_temp=29.2,load_percent=16,output_voltage=230,status_flags=83886088i,time_left_ns=594000000000i,time_on_battery_ns=0i 1568098954000000000
```
