### ISSUE TITLE
[telegraf] Error running agent: Error parsing /Aniket_testing/tel egraf_Backnet.conf, line 33: field corresponding to `dstaddr' is not defined in BACnet.BA Cnet

### ISSUE THREAD

**Issue by Pradeep-raj544** [influxdata/telegraf#6380]
I am getting this error when i am running telegraf.
config file--
```toml
[[inputs.BACnet]]
  dstaddr = "192.168.5.32:65490"
  objectID = 8388608
  ProperityID = 85
  parmName = "name of parameter"
  invokeID = 0
```

my structure defination
```go
type BACnet struct {
	dstaddr     string //"ip:port"
	objectID    uint32 //obTy<<22 | obInst
	ProperityID uint8
	parmName    string
	invokeID    uint8
}
```
@danielnelson please suggest the sollution.
