### ISSUE TITLE
Could not serialize metric: invalid name from cisco_telemetry_gnmi with gNMI interface on Arista

### ISSUE THREAD

**Issue by dgarros** [influxdata/telegraf#6391]
I'm getting some issue while testing the input plugin `cisco_telemetry_gnmi` with an arista device. 
The plugin is able to open the session but it's having some issue to read the data

```
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
```
Since gNMI is a standard interface, it would expect it that to work.

### Relevant telegraf.conf:
```toml

[[inputs.cisco_telemetry_gnmi]]
    [[inputs.cisco_telemetry_gnmi.subscription]]
        origin = "openconfig-interfaces"
        path = "/interfaces"
        # Subscription mode (one of: "target_defined", "sample", "on_change") and interval
        subscription_mode = "target_defined"
        sample_interval = "10s"
```

### System info:
- Telegraf 1.11.4
- Mac OS 10.14.6
- Arista EOS 4.21.1F

### Steps to reproduce:

Configure gRPC on Arista device
Start telegraf

### Expected behavior:
Since gNMI is a standard interface, the plugin should be able to read the metrics 

### Actual behavior:
the plugin is reporting some serialization issues
```
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
2019-09-13T12:39:07Z D! [outputs.file] Could not serialize metric: invalid name
```

### Arista Configuration
```
management api gnmi
   transport grpc TELEMETRY
      port 3333
      vrf MGMT
```

**Comment by danielnelson** [comment]
This error can be triggered when the measurement name is the empty string `""`.  Can you try setting `name = "interfaces"` to verify this is the issue?
```toml
[[inputs.cisco_telemetry_gnmi]]
    [[inputs.cisco_telemetry_gnmi.subscription]]
        name = "interfaces"
        origin = "openconfig-interfaces"
        path = "/interfaces"
        # Subscription mode (one of: "target_defined", "sample", "on_change") and interval
        subscription_mode = "target_defined"
        sample_interval = "10s"
```

**Comment by dgarros** [comment]
@danielnelson unfortunately the issue is the same when i configure `name` as well

**Comment by danielnelson** [comment]
Do you only have this single subscription?  If so you can try a more heavy handed `name_override` which will modify all metrics from the entire plugin.
```toml
[[inputs.cisco_telemetry_gnmi]]
  name_override = "interfaces"

  [[inputs.cisco_telemetry_gnmi.subscription]]
    name = "interfaces"
    origin = "openconfig-interfaces"
    path = "/interfaces"
    # Subscription mode (one of: "target_defined", "sample", "on_change") and interval
    subscription_mode = "target_defined"
    sample_interval = "10s"
```

@sbyx Can you take a look into what might be causing this?
