### ISSUE TITLE
Cannot send data to influxDB

### ISSUE THREAD

**Issue by linhphamspn** [influxdata/telegraf#6414]
### Relevant telegraf.conf:

```toml
[[inputs.exec]]
  commands = [
    "sh /etc/telegraf/telegraf.d/get_io_metrics.sh tomcat '/opt/tomcat'"
  ]
 timeout = "5s"
interval = "5s"
 name_suffix = "_tomcat_io"
 data_format = "json"
```
in get_io_metrics.sh, I put a sudo command to read diskio metrics
### System info:

Linux
Telegraf v1.7.2 (git: release-1.7 c6feb056)
### Steps to reproduce:

1. run with telegraf user:
sudo -u telegraf -s telegraf --config ./diskio.conf --test|grep io
```toml
> exec_tomcat_io,host=abc cancelled_write_bytes=10997706752,rchar=737767137775,read_bytes=8839832064,syscr=171418778,syscw=105986775,wchar=167440594299,write_bytes=20259930112 1568774797000000000
```
2. start telegraf with user  telegraf

### Expected behavior:
metrics should be sent to influxDB( because metrics are extracted successful with --test command
### Actual behavior:
No metric is sent to influxDB with below error:
```toml
2019-09-18T02:48:45Z E! Error in plugin [inputs.exec]: unable to parse out as JSON, unexpected end of JSON input
```
