### ISSUE TITLE
Output exec plugin does not use Serialise batch function

### ISSUE THREAD

**Issue by morfien101** [influxdata/telegraf#6445]
### Relevant telegraf.conf:

```toml
[[output.exec]]
  command = ["cat"]
  data_format = "json"
```

### System info:

Any system
Telegraf 1.12.2 (git: HEAD 8b4c9a0e)

### Steps to reproduce:

Send more than a single metric into the output stream

### Expected behavior:

Data format should be parsable using the format specified.
 
### Actual behavior:

Data is given as if it was a single metric over many lines.
