### ISSUE TITLE
bulk walk timeout results in no data

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#6450]
### Relevant telegraf.conf:
```toml
  [[inputs.snmp.table]]
    name = "storage"

    [[inputs.snmp.table.field]]
      oid = "HOST-RESOURCES-MIB::hrStorageDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "usage"
      oid = "JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed"
```

### System info:

Telegraf 1.12.2 (git: HEAD 8b4c9a0e)

### Expected behavior:

Return the already received data (if any)

### Actual behavior:

> E! [inputs.snmp] Error in plugin: agent x.x.x.x:161: gathering table storage: performing bulk walk for field usage: Request timeout (after 3 retries)
 E! [telegraf] Error running agent: One or more input plugins had an error

### Additional info:

This is what is returned from `snmpwalk` or `snmpbulkwalk`:

>... (removed outputs of index 1 to 50) ...
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.51 = Gauge32: 0
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.52 = Gauge32: 100
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.53 = Gauge32: 8
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.54 = Gauge32: 100
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.55 = Gauge32: 8
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.56 = Gauge32: 8
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.57 = Gauge32: 8
JUNIPER-HOSTRESOURCES-MIB::jnxHrStoragePercentUsed.58 = Gauge32: 100
Timeout: No Response from x.x.x.x

Note that there are 60 indexes on this device, so index 59 and 60 are having issues.
