### ISSUE TITLE
SNMP input not being sent to different output plugins

### ISSUE THREAD

**Issue by amoonrah** [influxdata/telegraf#6453]
### Relevant telegraf.conf:

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  #round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid

  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = "0s"

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  quiet = false

  ## Log file name, the empty string means to log to stderr.
  #logfile = "/tmp/telegraf.log"

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  logfile_rotation_max_size = "10MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  logfile_rotation_max_archives = 5

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


# # Send telegraf metrics to file(s)
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = [ "stdout" ]
  # rotation_interval = "0d"
  # rotation_max_size = "1MB"
  # rotation_max_archives = 5
  data_format = "json"


###################################################################
## Configuration for sending metrics to InfluxDB
###################################################################
[[outputs.influxdb_v2]]
   ## The URLs of the InfluxDB cluster nodes.
   ##
   ## Multiple URLs can be specified for a single cluster, only ONE of the
   ## urls will be written to each interval.
   urls = ["http://192.168.194.6:9999"]

   ## Token for authentication.
   token = "rp2EfQRiwlnvBzWxYgtgXWrAuJD9B1a4cfFAK7g7ysB5w5JBgcIXQpVmQt-LudRdRJkqDJi03obS1reuKCdc-A=="

   ## Organization is the name of the organization you wish to write to; must exist.
   organization = "Bell Canada"

   ## Destination bucket to write into.
   bucket = "loadmetrics"
#
#   ## The value of this tag will be used to determine the bucket.  If this
#   ## tag is not set the 'bucket' option is used as the default.
#   # bucket_tag = ""
#
#   ## If true, the bucket tag will not be added to the metric.
#   exclude_bucket_tag = true
#
#   ## Timeout for HTTP messages.
#   # timeout = "5s"
#
#   ## Additional HTTP headers
#   # http_headers = {"X-Special-Header" = "Special-Value"}
#
#   ## HTTP Proxy override, if unset values the standard proxy environment
#   ## variables are consulted to determine which proxy, if any, should be used.
#   # http_proxy = "http://corporate.proxy:3128"
#
#   ## HTTP User-Agent
#   # user_agent = "telegraf"
#
#   ## Content-Encoding for write request body, can be set to "gzip" to
#   ## compress body or "identity" to apply no encoding.
#   # content_encoding = "gzip"
#
#   ## Enable or disable uint support for writing uints influxdb 2.0.
#   # influx_uint_support = false
#
#   ## Optional TLS Config for use on HTTP connections.
#   # tls_ca = "/etc/telegraf/ca.pem"
#   # tls_cert = "/etc/telegraf/cert.pem"
#   # tls_key = "/etc/telegraf/key.pem"
#   ## Use TLS but skip chain & host verification
#   # insecure_skip_verify = false



###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################


###################################################################
# Retrieves SNMP values from remote agents
###################################################################
[[inputs.snmp]]
  name = "snmp"
  agents = [ "10.140.20.11:161" ]
  ## Timeout for each SNMP query.
  timeout = "5s"
  ## Number of retries to attempt within timeout.
  retries = 3
  ## SNMP version, values can be 1, 2, or 3
  version = 2
  ## SNMP community string.
  community = "public"
  ## The GETBULK max-repetitions parameter
  max_repetitions = 10

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.table]]
    ## measurement name
    name = "sipMetrics"
    inherit_tags = [ "hostname" ]
    [[inputs.snmp.table.field]]
      name = "globalStatActiveCalls"
      oid = "1.2.826.0.1.1578918.8.2.1.98.1"
      is_tag = true
    [[inputs.snmp.table.field]]
      name = "globalStatCallAttemptRate"
      oid = "1.2.826.0.1.1578918.8.2.1.101.1"
      is_tag = true
  [[inputs.snmp.table]]
    ## measurement name
    name = "systemMetric"
    inherit_tags = [ "hostname" ]
    [[inputs.snmp.table.field]]
      name = "globalStatCPUMaxSig"
      oid = "1.2.826.0.1.1578918.8.2.1.178.1"
      is_tag = true
```

### System info:

Telegraf 1.12.2 (git: HEAD 8b4c9a0e)
fredora 30
### Steps to reproduce:
run telegraf

### Expected behavior:

I expect telegraf to output data collected by snmp to stdout and to influxdb

### Actual behavior:

telegraf does snmpgets agains the remote system, remote system does reply with values.
telegraf does not send output to stdout or to influxdb

### Additional info:

I enabled the disk input plug in and values are being outputed to stdout and influxdb

[root@ltmonitor telegraf]# telegraf --input-filter snmp --test
2019-09-26T19:21:47Z I! Starting Telegraf 1.12.2
2019-09-26T19:21:47Z I! Using config file: /etc/telegraf/telegraf.conf
2019-09-26T19:21:47Z D! [agent] Initializing plugins
2019-09-26T19:21:47Z D! [inputs.snmp] Executing "snmptranslate" "-Td" "-Ob" "-m" "all" "1.2.826.0.1.1578918.8.2.1.98.1"
2019-09-26T19:21:47Z D! [inputs.snmp] Executing "snmptranslate" "-Td" "-Ob" "-m" "all" "1.2.826.0.1.1578918.8.2.1.101.1"
2019-09-26T19:21:47Z D! [inputs.snmp] Executing "snmptranslate" "-Td" "-Ob" "-m" "all" "1.2.826.0.1.1578918.8.2.1.178.1"
2019-09-26T19:21:47Z D! [inputs.snmp] Executing "snmptranslate" "-Td" "-Ob" "RFC1213-MIB::sysName.0"

**Comment by danielnelson** [comment]
Based on the output of the `--test` command it doesn't look like the snmp input is collecting any data.  You must have at least one field, I wonder if everything is being converted to tags?

Could you run these commands:
```
snmptable -v2c -c public 10.140.20.11:161 sipMetrics
snmptable -v2c -c public 10.140.20.11:161 systemMetric

**Comment by amoonrah** [comment]
I dont' think it is 

15:44:00.000469 IP ltmonitor.56162 > 10.140.20.11.snmp:  GetRequest(28)  system.sysName.0
15:44:00.003502 IP 10.140.20.11.snmp > ltmonitor.56162:  GetResponse(37)  system.sysName.0="uat-ssc-1"
15:44:00.003599 IP ltmonitor.56162 > 10.140.20.11.snmp:  GetBulk(33)  N=0 M=10 .iso.2.826.0.1.1578918.8.2.1.98.1
15:44:00.008709 IP 10.140.20.11.snmp > ltmonitor.56162:  GetResponse(215)  .iso.2.826.0.1.1578918.8.2.1.99.1=0 .iso.2.826.0.1.1578918.8.2.1.100.1=0 .iso.2.826.0.1.1578918.8.2.1.101.1=10 .iso.2.826.0.1.1578918.8.2.1.102.1=0 .iso.2.826.0.1.1578918.8.2.1.103.1=0 .iso.2.826.0.1.1578918.8.2.1.104.1=0 .iso.2.826.0.1.1578918.8.2.1.105.1=0 .iso.2.826.0.1.1578918.8.2.1.106.1=0 .iso.2.826.0.1.1578918.8.2.1.107.1=0 .iso.2.826.0.1.1578918.8.2.1.108.1=0
15:44:00.008810 IP ltmonitor.56162 > 10.140.20.11.snmp:  GetRequest(33)  .iso.2.826.0.1.1578918.8.2.1.98.1
15:44:00.014296 IP 10.140.20.11.snmp > ltmonitor.56162:  GetResponse(34)  .iso.2.826.0.1.1578918.8.2.1.98.1=101
15:44:00.014371 IP ltmonitor.56162 > 10.140.20.11.snmp:  GetBulk(33)  N=0 M=10 .iso.2.826.0.1.1578918.8.2.1.101.1
15:44:00.017783 IP 10.140.20.11.snmp > ltmonitor.56162:  GetResponse(215)  .iso.2.826.0.1.1578918.8.2.1.102.1=0 .iso.2.826.0.1.1578918.8.2.1.103.1=0 .iso.2.826.0.1.1578918.8.2.1.104.1=0 .iso.2.826.0.1.1578918.8.2.1.105.1=0 .iso.2.826.0.1.1578918.8.2.1.106.1=0 .iso.2.826.0.1.1578918.8.2.1.107.1=0 .iso.2.826.0.1.1578918.8.2.1.108.1=0 .iso.2.826.0.1.1578918.8.2.1.109.1=0 .iso.2.826.0.1.1578918.8.2.1.110.1=0 .iso.2.826.0.1.1578918.8.2.1.111.1=0
15:44:00.017857 IP ltmonitor.56162 > 10.140.20.11.snmp:  GetRequest(33)  .iso.2.826.0.1.1578918.8.2.1.101.1
15:44:00.021354 IP 10.140.20.11.snmp > ltmonitor.56162:  GetResponse(34)  .iso.2.826.0.1.1578918.8.2.1.101.1=10
15:44:00.021440 IP ltmonitor.56162 > 10.140.20.11.snmp:  GetBulk(34)  N=0 M=10 .iso.2.826.0.1.1578918.8.2.1.178.1
15:44:00.025119 IP 10.140.20.11.snmp > ltmonitor.56162:  GetResponse(231)  .iso.2.826.0.1.1578918.8.2.1.179.1=306358 .iso.2.826.0.1.1578918.8.2.1.180.1=306358 .iso.2.826.0.1.1578918.8.2.1.181.1=4630 .iso.2.826.0.1.1578918.8.2.1.183.1=0 .iso.2.826.0.1.1578918.8.2.1.184.1=1186 .iso.2.826.0.1.1578918.8.2.1.187.1=0 .iso.2.826.0.1.1578918.8.2.1.189.1=0 .iso.2.826.0.1.1578918.8.2.1.190.1=0 .iso.2.826.0.1.1578918.8.2.1.191.1=0 .iso.2.826.0.1.1578918.8.2.1.192.1=0
15:44:00.025203 IP ltmonitor.56162 > 10.140.20.11.snmp:  GetRequest(34)  .iso.2.826.0.1.1578918.8.2.1.178.1
15:44:00.028582 IP 10.140.20.11.snmp > ltmonitor.56162:  GetResponse(37)  .iso.2.826.0.1.1578918.8.2.1.178.1=306358
^C
30 packets captured
30 packets received by filter
0 packets dropped by kernel
[root@ltmonitor ~]# fg
-bash: fg: current: no such job
[root@ltmonitor ~]# snmptable -v2c -c public 10.140.20.11:161 sipMetrics
sipMetrics: Unknown Object Identifier (Sub-id not found: (top) -> sipMetrics)
[root@ltmonitor ~]#

below is a tcpdump on port 161 it's going after the proper OIDs

**Comment by danielnelson** [comment]
I see what is wrong, when using a `table` it is really expecting an `oid` for the a table, and it expects it to point at a conceptual table:
```
  [[inputs.snmp.table]]
    name = "interface"
    oid = "IF-MIB::ifTable"
```

I don't recommend using a table without a top level `oid`, although it will try to talk over the values in the subfields I don't believe it was intended behavior.

Instead, you should move the fields up to be top level fields:
```
[[inputs.snmp]]
  name_override = "my_metric_name"
  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true
  [[inputs.snmp.field]]
    name = "globalStatActiveCalls"
    oid = "1.2.826.0.1.1578918.8.2.1.98.1"
  [[inputs.snmp.field]]
    name = "globalStatCallAttemptRate"
    oid = "1.2.826.0.1.1578918.8.2.1.101.1"
  [[inputs.snmp.field]]
    name = "globalStatCPUMaxSig"
    oid = "1.2.826.0.1.1578918.8.2.1.178.1"
```

With this configuration all data will be emitted as a single metric:
```
my_metric_name,hostname=foo globalStatCallAttemptRate=42,globalStatCPUMaxSig=42
```

**Comment by amoonrah** [comment]
thank you so much for the quick response, this seems to have been the issue.

now to learn how to see this info in influxdb :)

**Comment by amoonrah** [comment]
how do I make each OID a field on it's own?

**Comment by danielnelson** [comment]
With the above each OID will be a field, with the exception of the hostname OID which will be a tag thanks to `is_tag = true`.

**Comment by Hipska** [comment]
@danielnelson  This one can be closed? It is not a bug, but misconfiguration.

Also, using a `table` doesn't require a top level `oid`, but the fields below it does need to be walk-able:
```toml
  [[inputs.snmp.table]]
    name = "interface"

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifDescr"
      is_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifName"
      is_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifAlias"
      is_tag = true

    [[inputs.snmp.table.field]]
      oid = "IF-MIB::ifAdminStatus"
      is_tag = true

    [[inputs.snmp.table.field]]
      name = "status"
      oid = "IF-MIB::ifOperStatus"

    [[inputs.snmp.table.field]]
      name = "in_octets"
      oid = "IF-MIB::ifHCInOctets"

    [[inputs.snmp.table.field]]
      name = "out_octets"
      oid = "IF-MIB::ifHCOutOctets"
```
