### ISSUE TITLE
docker_log include only one label - even with a exclude *

### ISSUE THREAD

**Issue by farfeduc** [influxdata/telegraf#6456]
### Relevant telegraf.conf:
```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_jitter = "0s"
  precision = "ms"
  hostname = ""
  omit_hostname = true

[[inputs.docker_log]]
  docker_label_include = ['java-logs']
  docker_label_exclude = ['*']

[[outputs.socket_writer]]
  address = "tcp4://172.24.0.21:20002"
  data_format = "json"
```

### System info:
Docker version : `1.03.2`
Telegraf version : `1.12.2` deployed as a docker service with the docker.sock mapped as a volume.

### Relevant docker-compose.yml

```
version: "3.7"
services:
  telegraf-java:
    image: telegraf:1.12.2
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    configs:
      - source: telegraf-config-java
        target: /etc/telegraf/telegraf.conf

configs:
  telegraf-config-java:
    external: true
    name: "config-telegraf-log-containers-java"
```

### Steps to reproduce:

1. Deploy Telegraf (change output for anything you like)
2. Deploy a service with label : `java-logs=true` (added on service and container levels)
3. Deploy another service with no labels.

### Expected behavior:
Only get the logs of the container with the `java-logs` label.

### Actual behavior:
I get the logs from all containers, none are excluded.

### Additional info:
Currently the logs are sent to Fluentd tcp listener that will then parse with grok the relevant log messages. But I would like only my java labeled containers to be parsed. Not all the cluster containers logs.
