### ISSUE TITLE
How to use regex or inlist to filter spesific set of Cassandra mbean "name" parms?

### ISSUE THREAD

**Issue by verzlo** [influxdata/telegraf#6499]
We tried to use posted casandra.conf with upgraded jolokia2 agent - but since all metrics/names are mostly wildcarded there with `*` it does generate too much input and we see a errors/timeouts on sending it to influx DB.
So now we are trying to trim it to match close to original jolokia/telegraf config where all metrics were specifically defined - but we can not seem to find a good example on how to use inlist/regex for scope/name . 
Here is example of OLD config:
```
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=LiveSSTableCount",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=LiveDiskSpaceUsed",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=MaxRowSize",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=TotalDiskSpaceUsed",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=PendingCompactions",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=PendingFlushes",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=EstimatedPartitionCount",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=ReadLatency",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=WriteLatency",
"/org.apache.cassandra.metrics:type=ColumnFamily,keyspace=*,scope=*,name=SnapshotsSize",
```

Here is example of new DEFAULT config section:
```toml
  [[inputs.jolokia2_agent.metric]]
    name  = "ColumnFamily"
    mbean = "org.apache.cassandra.metrics:keyspace=*,name=*,scope=*,type=ColumnFamily"
    tag_keys = ["keyspace", "name", "scope"]
    field_prefix = "$2_"
```

Can someone give us example how to use regex/widlcard this OLD into custom NEW with regex or inlist  those in 1 section?
