### ISSUE TITLE
'Error in plugin: E! Query path must lead to a JSON object or array of objects, but lead to: Null '

### ISSUE THREAD

**Issue by mbathe19** [influxdata/telegraf#6509]
### Relevant telegraf.conf:
```toml
# # Reload and gather from file[s] on telegraf's interval.
[[inputs.file]]
#   ## Files to parse each interval.
#   ## These accept standard unix glob matching rules, but with the addition of
#   ## ** as a "super asterisk". ie:
#   ##   /var/log/**.log     -> recursively find all .log files in /var/log
#   ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
#   ##   /var/log/apache.log -> only read the apache log file
 files = ["pathToFile/test.json"]
 data_format = "json"
 json_query = "Cluster.?????"
 tag_keys = ["State","partitions","node","user"]
#   ## json_string_fields = []
#   ## The dataformat to be read from files
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
#   data_format = "influx"
```

### System info:
Telegraf Version: Telegraf 1.12.2 (git: HEAD 8b4c9a0e)
Operating System: Ubuntu 18.04 LTS

JSON Input: 
```json
{
  "Cluster": {
    "nodes_all": 100,
    "mem_total": 120000,
    "nodes": [
      {
        "node": "node001",
        "State": "UP",
        "partitions": "galaxy-test",
        "CPU": 24,
        "MEM-G": 120
      },
      {
        "node": "node002",
        "State": "UP",
        "partitions": "galaxy-test",
        "CPU": 24,
        "MEM-G": 120
      },
      {
        "node": "node002",
        "State": "UP",
        "partitions": "galaxy-test",
        "CPU": 24,
        "MEM-G": 120
      },
      {
        "node": "node004",
        "State": "DOWN",
        "partitions": "galaxy-lowprio",
        "CPU": 24,
        "MEM-G": 100
      },
      {
        "node": "node005",
        "State": "DOWN",
        "partitions": "galaxy-lowprio",
        "CPU": 24,
        "MEM-G": 100
      }
    ],
    "jobs": [
      {
        "user": "test001",
        "State": "pending",
        "partitions": "galaxy-test",
        "count": 24,
        "max_duration": 120
      },
      {
        "user": "test002",
        "State": "pending",
        "partitions": "galaxy-test",
        "count": 42,
        "max_duration": 120
      },
      {
        "user": "test003",
        "State": "allocated",
        "partitions": "galaxy-test",
        "count": 5,
        "max_duration": 120
      },
      {
        "user": "test004",
        "State": "allocated",
        "partitions": "galaxy-lowprio",
        "count": 13,
        "max_duration": 100
      },
      {
        "user": "test005",
        "State": "allocated",
        "partitions": "galaxy-lowprio",
        "count": 72,
        "max_duration": 100
      }
    ]
  }
}
```

Hey,

I want to input this json via telegraf into my influxdb. I have two objects: cluster.nodes and cluster.jobs. 
I not able to get both objects into my database. 
My error is every time: 
```
Error in plugin: E! Query path must lead to a JSON object or array of objects, but lead to: Null
```
What I tried was: 

```toml
 json_query = ["Cluster.nodes","Cluster.jobs"]
 tag_keys = ["State","partitions","node","user"]
```

### Steps to reproduce:

to reproduce try to import the given json

### Expected behavior:

2 objects imported

### Actual behavior:

```
Error in plugin: E! Query path must lead to a JSON object or array of objects, but lead to: Null
```
