### ISSUE TITLE
inputs.exec starting powershell process even when it shouldn't because of interval

### ISSUE THREAD

**Issue by andrew1381** [influxdata/telegraf#6512]
### Relevant telegraf.conf:

```toml
[[inputs.exec]]
commands = ['''powershell.exe -noprofile -command ". C:/Scripts/Get-PrinterStatus.ps1; Get-PrinterStatus -PrinterName 'Printer PS' -PropertyToReturn PrinterStatus"''']
timeout = "60s"
interval = "90s"
data_format = "value"
data_type = "integer"
name_suffix = "_PrinterServer PS_printerStatus"
```

**The global interval is set to 10s.**

### System info:

Telegraf Ver: 1.12.1 Windows Server 2012 R2

### Expected behavior:
Powershell process to start every 90s due to interval

### Actual behavior:
Powershell process starts ever 10 seconds.
