### ISSUE TITLE
List of multiple grok_patterns is not working for tail plugin with grok data_format

### ISSUE THREAD

**Issue by patoliyam** [influxdata/telegraf#6525]
### Relevant telegraf.conf:

```toml
[[inputs.tail]]

  files = ["/etc/telegraf/telegraf.d/gc-log/node1"]
  ## Read file from beginning.
  from_beginning = false
  pipe = false
  data_format = "grok"
  watch_method = "inotify"
  grok_patterns = ["real=%{NUMBER:RealPauseTimeInSec:float}","user=%{NUMBER:UserTimeInSec:float}"]
  ## Full path(s) to custom pattern files.
  grok_custom_pattern_files = []
  ## Custom patterns can also be defined here. Put one pattern per line.
  grok_custom_patterns = '''
  '''
```

### System info:

Telegraf: 1.12.3 (Latest on repository)
OS: Ubuntu 18.04.1 LTS
### Steps to reproduce:

1.  Run the command to append a log line constantly:
>`while true; do (echo '2019-10-11T14:24:34.708-0400: 29.009: [GC (Allocation Failure) [PSYoungGen: 12233201K->1747433K(9639424K)] 14493615K->4700231K(37601792K), 1.4137800 secs] [Times: user=27.13 sys=5.15, real=1.43 secs]'>>/etc/telegraf/telegraf.d/gc-log/node1); sleep 0.01; done`
2. On separate tab on same host, test telegraf config file `gc.conf` using:
>`while true; do telegraf --config gc.conf --test; sleep 0.1; done`

### Expected behavior:
> tail,host=node1,path=/etc/telegraf/telegraf.d/gc-log/node1 RealPauseTimeInSec=1.43 UserTimeInSec=27.13 1571072571513895612
### Actual behavior:
>tail,host=node1,path=/etc/telegraf/telegraf.d/gc-log/node1 RealPauseTimeInSec=1.43 1571072571513895612
### Additional info:
* Only first pattern's match is being recorded. On switching order of patterns in `grok_patterns` list, only `UserTimeInSec` is being recorded.
* Though in given example I can combine two patterns into one and get both variables, in real scenario I am not able to that due to additional info coming in between and their order is not preserved.

[dummy_gc.log](https://github.com/influxdata/telegraf/files/3725675/dummy_gc.log)
