### ISSUE TITLE
JSON parser: how to handle data with missing time keys

### ISSUE THREAD

**Issue by russorat** [influxdata/telegraf#6532]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add a way to handle json data with missing time keys

### Current behavior:
json parsing fails the entire document

### Desired behavior:
1. the json parser should have a more helpful error message than "JSON time key could not be found". Ideally it would print the record it failed on
1. there could be a config option to ignore records with missing time keys, or an option to use a default time for missing time keys

### Use case: 
extends the capability of the json parser. enables more json files to be parsed without the need for custom application logic.

``` toml
[[inputs.http]]
  interval = "10s"
  urls = [
    "https://data.nasa.gov/resource/y77d-th95.json"
  ]
  name_override = "meteorevent"
  method = "GET"
  timeout = "5s"
  data_format = "json"
  json_query = ""
  tag_keys = [
    "nametype",
    "recclass",
    "fall",
    "geolocation_latitude",
    "geolocation_longitude",
    "year"
  ]
  json_string_fields = [
    "name",
    "id"
  ]
  json_name_key = ""
  json_time_key = "year"
  json_time_format = "2006-01-02T15:04:05.000"
```
