### ISSUE TITLE
Telegraf internal agent metrics are not being exposed with Prometheus output plugin

### ISSUE THREAD

**Issue by obitech** [influxdata/telegraf#6534]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 30000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[outputs.prometheus_client]]
  listen = "..."

[[inputs.internal]]
  collect_memstats = true

[[inputs.vsphere]]
...omitted...
```

### System info:

- Ubuntu 18.04
- Linux 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Telegraf 1.12.3

### Steps to reproduce:

1. Use [internal input plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internal)
2. Use [Prometheus output plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/prometheus_client)

### Expected behavior:
All metrics described in the internal input plugin:
- `internal_memstats`
- `internal_agent`
- `internal_gather`
- `internal_write`
- `internal_<plugin_name>`

are being exposed to Prometheus via `/metrics`.

### Actual behavior:
Of the above metrics described by the internal input plugin, only `internal_memstats` are being exposed.
