### ISSUE TITLE
cpu plugin doesn't work on osx 

### ISSUE THREAD

**Issue by zibuyu1995** [influxdata/telegraf#6577]
### Relevant telegraf.conf:

```toml
[global_tags]
  dc = "denver-1"

[agent]
  interval = "10s"

# OUTPUTS
[[outputs.influxdb]]
  url = "http://192.168.59.103:8086" # required.
  database = "telegraf" # required.
  precision = "s"

# INPUTS
[[inputs.cpu]]
  percpu = true
  totalcpu = false
  # filter all fields beginning with 'time_'
  fielddrop = ["time_*"]

```

### System info:
Mac OS 10.15
telegraf: 1.12.4

### Expected behavior:

![image](https://user-images.githubusercontent.com/17525759/67555366-b8fd7a80-f743-11e9-9f2d-606eb5210fe4.png)
