### ISSUE TITLE
Openweathermap input uses 3h rain value instead of 1h

### ISSUE THREAD

**Issue by lhanson** [influxdata/telegraf#6583]
### Relevant telegraf.conf:
```toml
[[inputs.openweathermap]]
  app_id = "my openweathermap API token"
  city_id = "[5261457]"
  fetch = ["weather"]
  units = "imperial"
  interval = "10m"
```

### System info:

Telegraf 1.12.4
Raspbian Linux, kenrel 4.19.66

### Steps to reproduce:

It's raining at my location right now. Temperature, humidity, and other values are refreshed every 10m by the plugin. The [sample plugin configuration](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/openweathermap/README.md) says that API data is updated every 10 minutes, though the openweathermap site merely indicates "[<2 hours](https://openweathermap.org/price)".

A call to the API shows this:

```sh
$ curl --silent "http://api.openweathermap.org/data/2.5/weather?id=5261457&units=imperial&appid=$OPENWEATHERMAP_TOKEN" | jq '.rain' 
{
  "1h": 0.91
}
```
Because the plugin [references the 3h value](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/openweathermap/openweathermap.go#L182) which isn't present at the moment in the API, my graphs do not show that it is currently raining.

### Expected behavior:

I'd like my data points to reflect current rain values as much as possible.

### Actual behavior:

Current rain values aren't shown as the API isn't returning a "3h" average.
