### ISSUE TITLE
Enum Processor works across config file scope?

### ISSUE THREAD

**Issue by n1nj4888** [influxdata/telegraf#6592]
### Relevant telegraf.conf:

```toml
###############################################################################
#                                INPUT PLUGINS                                #
###############################################################################

##################### INPUT = SNMP (snmp.synology.upsTableTEST) ###################

[[inputs.snmp]]

   agents = [  "AGENT_IP" ]
   interval = "60s"
   timeout = "5s"
   retries = 0
   version = 2
   community = "COMMUNITY_ID"
   max_repetitions = 30

   # SYNOLOGY-UPS-MIB.txt - Writes to snmp.synology.upsTableTEST
   # [[inputs.snmp.table]]
     name = "snmp.synology.upsTableTEST"
   [[inputs.snmp.field]]
     name = "upsInfoStatus"
     oid =  "SYNOLOGY-UPS-MIB::upsInfoStatus.0"
  
[[processors.enum]]
  [[processors.enum.mapping]]
    ## Name of the field to map
    field = "upsInfoStatus"

    ## Name of the tag to map
    # tag = "status"

    ## Destination tag or field to be used for the mapped value.  By default the
    ## source tag or field is used, overwriting the original value.
    dest = "upsInfoStatusValue"

    ## Default value to be used for all values not contained in the mapping
    ## table.  When unset and no match is found, the original field will remain 
    ## unmodified and the destination tag or field will not be created.
    # default = 0

    ## Table of mappings
    [processors.enum.mapping.value_mappings]
      OL = 5
      "OL CHRG" = 4
      "OL DISCHRG" = 3
      "OB CHRG" = 2
      "OB DISCHRG" = 1
      "FSD OB DISCHRG" = 0
      "LB" = -1
      "OVERLOADED" = -2
      "RB" = -3
      "OFF" = -4

############################# END OF FILE #####################################

```

### System info:

Telegraf Official Docker - 1.12.3

### Steps to reproduce:

I have two files as follows:

(1) telegraf-input-snmp.synology.upsTableTEST.conf - This file is the same as (2) but writes to a measurement called **snmp.synology.upsTableTEST** and has the Telegraf Enum Processor configured to add an additional (integer) field based on the value of the "upsInfoStatus" SNMP lookup - This file is as above TOML example
(2) telegraf-input-snmp.synology.upsTable.conf - This file is the same as (1) however it writes to a measurement called **snmp.synology.upsTable** and **does not have the Telegraf Enum Processor configured**

Both of these .conf files are located in the docker container directory /etc/telegraf/telegaf.d and both are picked up by telegraf

### Expected behavior:

Given the Enum Processor is only configured in the snmp.synology.upsTableTEST measurement config file, I would only expect the Enum Value for upsInfoStatusValue to be present in the snmp.synology.upsTableTEST measurement, but it is present in both the snmp.synology.upsTableTEST and snmp.synology.upsTable measurements.

### Additional info:

I recall the way telegraf works is to combine all the .conf files into a single logical .conf file so this behaviour may be expected, but it would be good to understand if there is a way to limit the scope of the Enum (and other) Processors to the scope of the file it is specified in?

Thanks!
