### ISSUE TITLE
tags config option should not accept slice

### ISSUE THREAD

**Issue by andig** [influxdata/telegraf#6594]
By mistake I have configured `tags` using a slice instead of a single value

### Relevant telegraf.conf:

```toml
[[inputs.influxdb_listener]]
  service_address = ":9986"
  tags = { influx_routing = ["volkszaehler"] }
```

Testing this config (`-test`) succeeds, but tags are not applied to the input. This is e.g. noticable when using tags for routing.

### System info:

Telegraf: 1.12.3
