### ISSUE TITLE
Ignore mountpoints based on filesystem paths

### ISSUE THREAD

**Issue by tjnome** [influxdata/telegraf#6595]
## Feature Request

It want to ignore mountpoints based on paths.

### Proposal:

Have a value that we can list paths that telegraf should ignore. Example:
ignore_path = [ "/mnt", "/cdrom". "/usb"]

### Current behavior:

None, we can only ignore mount point based on file system type

### Desired behavior:

To ignore mount points based on paths. 

### Use case:

This can be used to ignore mount points in certain paths. Think this is a nice feature as we set certain paths that telegraf ignores. Like a USB stick or external drive that is temporary mounted in /mnt as a example

**Comment by glinton** [comment]
Am I correct in assuming you are referring to the `disk` input? If so, as an interim workaround is it feasible for you to specify `mount_points` containing the paths that you with to collect stats for?

**Comment by tjnome** [comment]
> Am I correct in assuming you are referring to the `disk` input? If so, as an interim workaround is it feasible for you to specify `mount_points` containing the paths that you with to collect stats for?

Yeah it's for `disk` input. I agree current workaround is possible, but it's simpler to ignore some paths then specify all `mount_points` for each system

**Comment by kumaresan078** [comment]
Hi,

I am facing same issue to ignore certain mount points.

Is there alternate way to ignore mount points with influxdb query?

select free,used,total,used_percent,total - used - free as "zeroKO",fstype FROM disk WHERE device !- /^backup/ GROUP BY host,path,device LIMIT 1

Regards
Kumar

**Comment by danielnelson** [comment]
For this you can use the general [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering) options, these work with all plugins.

```toml
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]
  # put subtable at end of plugin to avoid having other options "fall" under it
  [inputs.disk.tagdrop]
    path = "/mnt"
```
