### ISSUE TITLE
Redis stream output plugin

### ISSUE THREAD

**Issue by tagantroy** [influxdata/telegraf#6601]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Add support for Redis stream as an output plugin
### Current behavior:
Not implemented yet
### Desired behavior:
Data added to Redis stream
### Use case: 
In our case, we have two components: runner and client. These two components are running on different hosts.
Runner produces logs and writes it to file. Client showing these logs. Currently, we are using the HTTP output plugin + HTTP server which adds logs to Redis stream(we run it as sidecars in k8s pod). It would be great to have this plugin as a part of Telegraf. 

I know about the previous try: https://github.com/influxdata/telegraf/pull/3105/
It looks like nobody working on a replacement. I would be happy to contribute to it.

**Comment by glinton** [comment]
Seems reasonable. Before starting on the PR, we can use this as a place to hash out the design as stated in [this comment](https://github.com/influxdata/telegraf/pull/3105#issuecomment-533280851).
> "We should probably start over at the design phase"

**Comment by danielnelson** [comment]
@tagantroy Thanks for the offer to help, I haven't done much research but here is my idea about how it might look.

I'm thinking the configuration would look similar to the redis input:
```toml
[[outputs.redis_streams]]
  server = "tcp://localhost:6379"

  # password = ""

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = true
```

Metric conversion might be like:
```
cpu,cpu=cpu0,host=localhost time_idle=42i,time_guest=42i 1573002706000000000
```

Use series key as stream name, split the timestamp:
```
XADD cpu,cpu=cpu0,host=localhost 1573002706000-0 time_idle 42 time_guest 42
```

We should use a pipeline to and a transaction (multi/exec) to allow retries.

One tricky part will be the generating of IDs.  These apparently must be in increasing order, something not promised by Telegraf.  I have some long term ideas on improving this but for now we can sort the metrics within a batch, and we may need to ignore errors.  This would be similar to what we have in the stackdriver output.
