### ISSUE TITLE
Support Prometheus Operator

### ISSUE THREAD

**Issue by rawkode** [influxdata/telegraf#6608]
## Feature Request

Currently, Telegraf supports the Prometheus annotations for service discovery in Kubernetes. With CRDs hitting GA, there's growing support for this workflow within the Kubernetes community; particularly around Prometheus.

The Prometheus Operator provides CRDs for directing Prometheus servers to metric endpoints, which Telegraf should support too.

### Proposal:

Support the `ServiceMonitor` CRD, with the same behaviour as the annotation approach.

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
```

### Current behavior:

Not supported

### Desired behavior:

Scrape metrics as per instructions in `ServiceMonitor` CRD

### Use case: 

The Prometheus Operator is becoming the standard for Kubernetes monitoring and Telegraf could provide a drop-in replacement

**Comment by danielnelson** [comment]
High level sounds good, I'm assuming you are referring to the [CoreOS Prometheus Operator](https://github.com/coreos/prometheus-operator)?  Can you pseudocode the calls we would make and what example responses would look like?

**Comment by M0rdecay** [comment]
You need to support the definition of the destination port, getting them not from labels, but from `spec.ports[%PORT_NAME%]`

Example service manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: pili
  labels:
    app: pili
spec:
  type: ClusterIP
  ports:
  - name: uwsgi
    protocol: TCP
    port: 8080
    targetPort: uwsgi
  selector:
    app: pili-web
    tier: backend
```

Then the configuration of Prometheus is something like this:
```toml
[[inputs.prometheus]]
...

kubernetes_lablel_selector = "appl=pili"
kubernetes_monitor_endpoint = "uwsgi"
kubernetes_monitor_path = "/metrics"
kubernetes_monitor_scheme = "http"
...
```
In this form, it will be necessary to create one input line per service, but this is seen as a plus rather than a minus.
It might be worth using an array of endpoints:
```toml
[[inputs.prometheus]]
  [[inputs.prometheus.endpoints]]
    selector = "appl=pili"
    endpoint = "uwsgi"
    path = "/metrics"
    scheme = "http"
...
```
But, as it seems to me, such a refinement will cost more.

ServiceMonitor configuration example for the above service:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-pili
  namespace: monitoring
  labels:
    app: pili-service-monitor
spec:
  selector:
    matchLabels:
      # Target app service
      app: pili
  endpoints:
  - interval: 15s
    path: /metrics
    port: uwsgi
    scheme: http
  namespaceSelector:
    matchNames:
    - default
```
