### ISSUE TITLE
Docker container uptime_ns may be negative

### ISSUE THREAD

**Issue by gotson** [influxdata/telegraf#6615]
### Relevant telegraf.conf:

```toml
# Read metrics about docker containers
[[inputs.docker]]
  ## Docker Endpoint
  ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
  ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  endpoint = "unix:///var/run/docker.sock"

  ## Set to true to collect Swarm metrics(desired_replicas, running_replicas)
  gather_services = false

  ## Only collect metrics for these containers, collect all if empty
  container_names = []

  ## Containers to include and exclude. Globs accepted.
  ## Note that an empty array for both will include all containers
  container_name_include = []
  container_name_exclude = []

  ## Container states to include and exclude. Globs accepted.
  ## When empty only containers in the "running" state will be captured.
  ## example: container_state_include = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  ## example: container_state_exclude = ["created", "restarting", "running", "removing", "paused", "exited", "dead"]
  # container_state_include = []
  # container_state_exclude = []

  ## Timeout for docker list, info, and stats commands
  timeout = "5s"

  ## Whether to report for each container per-device blkio (8:0, 8:1...) and
  ## network (eth0, eth1, ...) stats or not
  perdevice = true
  ## Whether to report for each container total blkio and network stats or not
  total = false
  ## Which environment variables should we use as a tag
  ##tag_env = ["JAVA_HOME", "HEAP_SIZE"]

  ## docker labels to include and exclude as tags.  Globs accepted.
  ## Note that an empty array for both will include all labels as tags
  docker_label_include = []
  docker_label_exclude = []
```

### System info:

Telegraf v1.12.4 running inside Docker on Ubuntu 19.04

### Steps to reproduce:

1. Run some containers

### Expected behavior:

`docker_container_status`.`uptime_ns` should be positive.

### Actual behavior:

For some containers, `docker_container_status`.`uptime_ns` is negative.

### Additional info:

I have 23 containers running, and 7 of them have a negative uptime.

Here is a list of the uptimes extracted from Chronograf:

```
1225819351060780
1791733604813900
-1002174896
22861001160934
-852099304
16538947268714
889544877443432
889547034686139
-295827770
94724723108097
207720147185631
15383184878473
15383266074614
-35407018583
-28587512725
-484100573
-41658487591
6101729087168
429114049532334
414113293415570
28229441453406
475919373816345
381711068671320
```
