### ISSUE TITLE
NATS consumer breaks when outputs are enabled

### ISSUE THREAD

**Issue by Freakin** [influxdata/telegraf#6628]
### Relevant telegraf.conf:

```toml
    # NATS Consumer
    [[inputs.nats_consumer]]
      servers = ["nats://influx-nats-client:4222"]
      subjects = ["telegraf"]
      queue_group = "telegraf_consumers"
      data_format = "influx"
    
    #Influx Output
    [[outputs.influxdb]]
     urls = ["http://telegraf-influx-svc:8186"]
     skip_database_creation = true
     retention_policy = ""
     write_consistency = "any"
     timeout = "5s"
```

### System info:

Kubernetes `1.13`
Docker Image: `telegraf:1.12.3-alpine` from Docker Hub

### Steps to reproduce:

1. Enable telegraf to consume from NATS
2. Use Inch to produce a decent amount of metrics.  ~35k pps were emitted for this test
3. With no outputs of metrics from NATS, verify that messages are being consumed by looking at `internal_write` metrics for `filtered`.  
`telegraf.internal_write,host=telegraf-consumer-0,output=file,version=1.12.3 metrics_dropped=0i,buffer_size=0i,buffer_limit=100000i,metrics_filtered=5825000i,write_time_ns=2073539i,errors=0i,metrics_added=2080i,metrics_written=2080i 1573070550000000000`

4. Enable an output to `influxdb` or `http` or `datadog` with filters that will output the metrics received from NATS_consumer
5. Observe that NATS is throwing slow consumer errors continually, and rate of metrics being dropped/filtered/output is much lower than previously
```
2019-11-06T20:20:23Z E! [inputs.nats_consumer] Error in plugin: nats: slow consumer, messages dropped url:nats://influx-nats-client:4222 id:NDKOFMXQPMRYYIKZOA6HGL34PNJ3SNX3KBTTAXH5MPO3MJKFJQAN4XWM sub:telegraf queue:telegraf_consumers
telegraf.internal_write,host=telegraf-consumer-0,output=influxdb,version=1.12.3 metrics_filtered=0i,write_time_ns=35997653i,errors=0i,metrics_added=7393i,metrics_written=6393i,metrics_dropped=0i,buffer_size=1000i,buffer_limit=100000i 1573071660000000000
```
### Expected behavior:
When an output is added, I do not expect it to change behavior of the nats_consumer to the point that it is unusable

### Actual behavior:
NATS consumer appears to be tied to the output, almost that it will not ack the message from NATS until it has finished writing the message to the output.

### Additional info:
I put together deployments for Kubernetes to simulate this behavior, which can be tested with Inch.  The manifests are here
https://github.com/Freakin/telegraf-nats
