### ISSUE TITLE
pings.input native bind to interface doesn't work?

### ISSUE THREAD

**Issue by Marctraider** [influxdata/telegraf#6642]
### Relevant telegraf.conf:

```toml
[agent]
  hostname = "192.168.1.1"
  interval = "1s"
  logfile = "/var/log/telegraf/telegraf.log"
  flush_interval = "1s"
  metric_batch_size = 250
  metric_buffer_limit = 2500


[[inputs.cpu]]

[[inputs.mem]]

[[inputs.system]]

[[inputs.disk]]
  mount_points = ["/"]

[[inputs.processes]]

[[inputs.net]]
  fieldpass = [ "bytes_*" ]


[[inputs.ping]]
  ## Hosts to send ping packets to.
name_suffix = "_eth1"
  urls = ["46.19.33.172"]
  method = "exec"
  #count = 1
  #ping_interval = 1.0
  #timeout = 1.0
  #interface = "eth1"
  binary = "ping"
  arguments = ["-W", "0.250", "-c", "4", "-i", "0.25", "-I", "eth1", "-Q", "192", "-s", "20"]

[[inputs.ping]]
name_suffix = "_eth2"
  ## Hosts to send ping packets to.
  urls = ["46.19.33.172"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
  interface = "eth2"
#  binary = "ping"
#  arguments = ["-W", "0.250", "-c", "4", "-i", "0.5", "-I", "eth2", "-Q", "192", "-s", "20"]



[[outputs.influxdb]]
  database = "telegraf"
  urls = [ "http://127.0.0.1:8086" ]
  username = "telegraf"
  password = "telegraf"
  timeout = "5s"


```

### System info:

On both of these anyway:

Telegraf unknown (git: bugfix/6576 25a212c2)
Telegraf unknown (git: master 58df6f6c)

### Steps to reproduce:

1. Use one ping to isp interface with binary exec method
2. Use one ping to isp interface with native method

### Expected behavior:

tcpdump -nni eth1 icmp
and
tcpdump -nni eth2 icmp
should both show icmp activity?

### Actual behavior:

Ping with native doesn't work with bind to interface.

### Additional info:

The only output i get from telegraf.log is a huge load of lines of
"2019-11-09T01:50:04Z W! [agent] [inputs.ping] did not complete within its interval"

Which don't seem to be there when i just use exec for all of them.
