### ISSUE TITLE
Non textual field string data in sqlserver plugin with SqlRequests query

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#6679]
### Relevant telegraf.conf:

```toml
[[inputs.sqlserver]]
  servers = ["..."]
  query_version = 2

[[outputs.file]]
  files = ["tmp"]
```

### System info:

Telegraf 1.12.5

### Steps to reproduce:

1. Run input plugin without excluding the SqlRequests query.
2. Check output file.

### Expected behavior:

All string fields are valid UTF-8 text.

### Actual behavior:

The `query_hash` and `query_plan_hash` appear to be binary data.

### Additional info:

Small selection of example output:
[input-filter.txt](https://github.com/influxdata/telegraf/files/3861598/input-filter.txt)
