### ISSUE TITLE
field corresponding to `flush_jitter' is not defined in cloudwatch.CloudWatch

### ISSUE THREAD

**Issue by adisharoon** [influxdata/telegraf#6698]
### Relevant telegraf.conf:

```toml
[[outputs.cloudwatch]]
 region = "us-west-2"
 namespace = "Telegraf"
 flush_interval = "30s"
 flush_jitter = "30s"
 tagexclude = ["host"]
```

### System info:
Telegraf 1.12.6 (git: HEAD 6c7f2d62)
Ubuntu 16.04.6 LTS
### Steps to reproduce:

Added flush_jitter config to previously working cloudwatch output. A default flush_jitter is already defined at the agent level; this is intended to be an override, as described in the documentation (https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#output-plugins)

### Expected behavior:
flush_jitter configuration for this output applied to just this output

### Actual behavior:
telegraf fails to start with the following error:

telegraf[6248]: 2019-11-21T19:49:43Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.d/cloudwatch.conf, line 5: field corresponding to `flush_jitter' is not defined in cloudwatch.CloudWatch
