### ISSUE TITLE
net_response does not have a "success" field

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#6749]
### Relevant telegraf.conf:

```toml
[[inputs.net_response]]
  protocol = "tcp"
  address = "127.0.0.1:60013"
```

### System info:

Telegraf 1.11.3

### Steps to reproduce:

1. Run telegraf -test -config <providedConfig>
2. Check the output

### Expected behavior:
A field called ``success``.

Or maybe better, remove that field from the docs, as ``result_code`` has more information.

### Actual behavior:

```
> net_response,host=hostA,port=60013,protocol=tcp,result=connection_failed,server=127.0.0.1 result_code=2i,result_type="connection_failed" 1575377951000000000
```

### Additional info:
