### ISSUE TITLE
Improve temp input support on Windows

### ISSUE THREAD

**Issue by Aqualie** [influxdata/telegraf#6750]
### Relevant telegraf.conf:

```toml
[global_tags]
[agent]
	interval = "10s"
	round_interval = true
	metric_batch_Size = 1000
	metric_buffer_limit = 10000
	collection_jitter = "0s"
	flush_interval = "10s"
	flush_jitter = "0s"
	precision = ""
	debug = true
	quiet = false
	logfile = "C:\telegraf.debug"
	hostname = ""
	omit_hostname = false
[[outputs.influxdb]]
	urls = ["http://influxdb.lan:8086"]
	database = "telegraf"
[[inputs.temp]]
```

### System info:

Telegraf-1.12.5_windows_amd64
Windows 10 Enterprise 1909

### Steps to reproduce:

1. Use windows OS
2. Enable telegraf with inputs.temp plugin

### Expected behavior:

Receive temperature statistics in configured output host
### Actual behavior:
Receiving error message:
[inputs.temp] Error in plugin: error getting temperatures info: Exception occurred. (Not supported )

### Additional info:
github page for inputs.temp **Currently supports Linux and Windows.**
