### ISSUE TITLE
HOST_MOUNT_PREFIX not supported in kubernetes deploy

### ISSUE THREAD

**Issue by like-inspur** [influxdata/telegraf#6754]
I create telegraf 1.9.1 daemonset on kubernetes, and want to test disk monitor. Although I config HOST_MOUNT_PREFIX  in telegraf daemonset, but the output of disk path still has container path

telegraf config is like this:
```
    [[inputs.disk]]
        ignore_fs = ["aufs", "rootfs", "sysfs", "proc", "devtmpfs", "devpts", "tmpfs", "fusectl", "cgroup", "overlay"]
```
telegraf daemonset is like this:
```
      containers:
      - env:
        - name: HOST_PROC
          value: /host/proc
        - name: HOST_SYS
          value: /host/sys
        - name: HOST_ETC
          value: /host/etc
        - name: HOST_VAR
          value: /host/var
        - name: HOST_RUN
          value: /host/run
        - name: HOST_MOUNT_PREFIX
        image: registry.icp.com:5000/library/common/telegraf:1.9.1
        volumeMounts:
        - mountPath: /etc/telegraf
          name: config
        - mountPath: /host
          name: rootfs
          readOnly: true
      hostNetwork: true
      hostPID: true
      volumes:
      - configMap:
          defaultMode: 420
          name: node-telegraf
        name: config
      - hostPath:
          path: /
          type: ""
        name: rootfs
```
the output of disk_used is like this, which path has /host from container mount by hostPath
```
disk_used_percent{device="sda1",fstype="ext4",host="k8s01",mode="rw",path="/host/var/lib/kubelet/pods/f7de0523-e700-11e9-bc20-52540088b5d1/volume-subpaths/config/core/0"} 32.450540711562006
```
