### ISSUE TITLE
Memory Leak with procstat

### ISSUE THREAD

**Issue by mafinn** [influxdata/telegraf#6807]
### Relevant telegraf.conf:
```toml
[global_tags]
  sc = "daf"
  p = "32"
  custom_version = "1.x"
  os_type = "win2016s"

[agent]
  interval = "1s"
  round_interval = false
  metric_batch_size = 1000
  metric_buffer_limit = 5000
  collection_jitter = "1s"
  flush_interval = "1s"
  flush_jitter = "1s"
  precision = "s"
  debug = true
  quiet = false
  logfile = "/Program Files/Telegraf/telegraf.log"
  hostname = "win2016s"
  omit_hostname = false

[[outputs.influxdb]]
  urls = [ "http://1.1.1.1:8086" ]
  database = "telegraf"
  retention_policy = "24hours"
  precision = "m"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.mem]]  

[[inputs.procstat]]
  interval = "1s"
  exe = ".*"
  pid_finder = "native"

[[inputs.internal]]


```

### System info:
![image](https://user-images.githubusercontent.com/47539414/70962409-20082300-2053-11ea-8827-8b3f8f24d889.png)

![image](https://user-images.githubusercontent.com/47539414/70962390-0ebf1680-2053-11ea-8f74-024ec2b68415.png)

### Steps to reproduce:

No special steps, memory leak appears to be related to procstat input plugin:
![image](https://user-images.githubusercontent.com/47539414/70962479-68274580-2053-11ea-8700-ed370071d366.png)

![image](https://user-images.githubusercontent.com/47539414/70962498-74ab9e00-2053-11ea-9738-de0e86f6a806.png)
