### ISSUE TITLE
x509_cert: allow specifying target hostname

### ISSUE THREAD

**Issue by hackery** [influxdata/telegraf#6809]
The current configuration syntax provides no way to override the host name (or IP address) given in a `sources` entry and used for CN validation. This would be useful for testing hosts with multiple vhosts, service groups behind load balancers, and staging hosts which don't resolve from the domain name being tested.

```
[[inputs.x509_cert]]
  sources = [
    "https://example.org:443",
    # staging hosts offer certs for "example.org"
    { source = "https://staging-01.example.org:443", hostname="example.org" }
    { source = "https://staging-02.example.org:443", hostname="example.org" }
    # qa hosts offer certs for qa.example.org
    { source = "https://qa-01.example.org:443", hostname="qa.example.org" }
    # dev hosts offer certs for dev.example.org
    { source = "https://127.0.0.1:443", hostname="dev.example.org" }
    # do not want to share certs with SAN for *.example.org or IPs
  ]
```

**Comment by danielnelson** [comment]
My first instinct is that we shouldn't do this, we are essentially asking the plugin to report an invalid certificate as valid.  It seems to me that the system offering the certificate should serve it on the correct CN or SAN.  Workarounds could be modifying dns lookup (for example `/etc/hosts`), adding a SAN to the certificate, or collecting the certificate from the server system using a file path.

I'll leave this open for further discussion.

**Comment by ruatag** [comment]
openssl s_client can do this. This check valid certificate on specified host and no reason to add individual host names to SAN as they never used. There can be many different names identified by SNI. If hosts balanced you can't connect exactly to one of them. If SNI checked you won't ever connect
echo | openssl s_client -connect servername.com:443 -servername realserver.com -CAfile ca.crt

**Comment by danielnelson** [comment]
It sounds like we need more control for SNI.  Something like this would be backwards compatibile with the current settings, does this have the expected control?

```toml
[[inputs.x509_cert]]
  sources = ["example.org"]

  ## Method for handling Server Name Indication.  Can be set to "auto",
  ## "manual", or "disable".
  ##
  ## In "auto" mode the source hostname will be used on certificates retrieved
  ## over the network.  When set to "manual" the contents of "server_name" will
  ## be sent.  If set to "disable" then the server name extension will not be
  ## sent.
  # sni = "auto"

  ## Server name to send when "sni" is set to "manual".
  # server_name = ""
```
