### ISSUE TITLE
Prometheus serializer config params not present in serializer config

### ISSUE THREAD

**Issue by ibspoof** [influxdata/telegraf#6824]
Prometheus serializer enables several configuration parameters to change the output of the serializer.  When using data_format=prometheus with http output telegraf config parsing errors on prometheus_* config params since they are not included in the config -> buildSerializer method.

### Relevant telegraf.conf:

```toml
  data_format = "prometheus"

  prometheus_export_timestamp = true

```

### System info:
Telegraf version 1.13

### Steps to reproduce:
1. Enable outputs http w/ data_format= prometheus
2. Set prometheus_* config values in output config
```toml
[[outputs.http]]

  url = "http://127.0.0.1:3000/telegraf"

  data_format = "prometheus"
  
  prometheus_export_timestamp = true

  prometheus_sort_metrics = true

  prometheus_string_as_label = true
```
### Expected behavior:

Startup will continue without error and prometheus data_format will serialize output

### Actual behavior:

```
Error running agent: Error parsing ./telegraf.conf, line 17: field corresponding to `prometheus_sort_metrics' is not defined in http.HTTP
```

### Additional info:
PR: #6823
