### ISSUE TITLE
Duplicate entries when several output (in differents files) in telegraf.d

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#6836]
### Relevant telegraf.d/a.conf:
```toml
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "a"

[[inputs.cpu]]
  percpu = false
  totalcpu = true
  collect_cpu_time = false
  report_active = false
```
### Relevant telegraf.d/b.conf:
```toml
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "b"

[[inputs.exec]]
  commands = [ "sh /usr/bin/sensors.sh" ]
  timeout = "5s"
  data_format = "influx"
```

### System info:
Telegraf 1.13.0 on Debian 9.11

### Steps to reproduce:
1. Copy these 2 examples in /etc/telegraf/telegraf.d/
2. restart telegraf

### Expected behavior:
Separation of config in /etc/telegraf/telegraf.d/
So the input of /etc/telegraf/telegraf.d/a.conf can only be imported in the output of a.conf and the input of /etc/telegraf/telegraf.d/b.conf can only be imported in the output of b.conf

### Actual behavior:
Both inputs are duplicated in both output of these files
So I can see by example the inputs of telegraf.d/b.conf in the output of telegraf.d/a.conf & telegraf.d/b.conf

How can I like "partition" conf files between them in telegraf.d?
