### ISSUE TITLE
inputs vsphere : collect inventory metrics

### ISSUE THREAD

**Issue by BenoitPoulet** [influxdata/telegraf#6838]
## Feature Request

Il would be nice to collect inventory metrics like : 
- number of VM presents
- number of running VM
- number of paused VM
- number of CPU cores present on host
- number of virtual cores on the VM
...

### Use case: 
All theses informations car be used to build dashboards for provisioning and capacity planning.

**Comment by danielnelson** [comment]
> - number of CPU cores present on host
> - number of virtual cores on the VM

I believe these metrics can already be retrieved, look at the available [host metrics][1] and add them to `host_metric_include`.

> - number of VM presents
> - number of running VM
> - number of paused VM

I'm not sure if there is a vSphere metric to check a VMs state (running/paused), would be nice to have these though.  @prydin Do you know?

In general for counting the number of VMs, unless vSphere will give us this data directly I would prefer to leave it to the query side, and not compute them on collection.  What you need to do is determine the number of reporting series.  Here are some example queries that get the number of cpus using the cpu measurement.  They use time_idle, but they could use any field.

Here is an example using Flux:
```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "cpu")
  |> filter(fn: (r) => r._field == "time_idle")
  |> aggregateWindow(every:1m, fn:last, timeSrc: "_start", createEmpty:false)
  |> group()
  |> aggregateWindow(every:1m, fn:count, timeSrc: "_start")
```

With InfluxQL, the best you can do is get a single value, I believe you would need to use a continuous query to create the series:
```
> SELECT count(last) FROM (SELECT last(time_idle) FROM cpu where time > now() - 30m GROUP BY cpu)
name: cpu
time count
---- -----
0    2
```

It is also possible to use an aggregator to count them on collection:
```toml
[[aggregators.basicstats]]
  ## set period to match the input
  period = "10s"
  drop_original = false
  namepass = ["cpu"]
  ## removing this tag groups all cpus into a single series
  tagexclude = ["cpu"]
  fieldpass = ["time_idle"]
  stats = ["count"]
```

[1]: https://github.com/influxdata/telegraf/blob/master/plugins/inputs/vsphere/METRICS.md#host-system-metrics
