### ISSUE TITLE
counter value jumps with promethues client? 

### ISSUE THREAD

**Issue by Logic0** [influxdata/telegraf#6862]
Value report path: process use statsd protocol to report request count to telegraf, and prometheus get metrics from telegraf.

We have a problem with using prometheus ouput: a counter value changes from 1 to random number sometimes, shows in pic

![image](https://user-images.githubusercontent.com/3375925/71811840-a642e280-30b0-11ea-97a3-d665831e3505.png)

### Relevant telegraf.conf:
```toml
[[inputs.statsd]]
#   ## Protocol, must be "tcp", "udp", "udp4" or "udp6" (default=udp)
    protocol = "udp"
#
#   ## MaxTCPConnection - applicable when protocol is set to tcp (default=250)
#   max_tcp_connections = 250
#
#   ## Enable TCP keep alive probes (default=false)
#   tcp_keep_alive = false
#
#   ## Specifies the keep-alive period for an active network connection.
#   ## Only applies to TCP sockets and will be ignored if tcp_keep_alive is false.
#   ## Defaults to the OS configuration.
#   # tcp_keep_alive_period = "2h"
#
#   ## Address and port to host UDP listener on
    service_address = ":8125"
#
#   ## The following configuration options control when telegraf clears it's cache
#   ## of previous values. If set to false, then telegraf will only clear it's
#   ## cache when the daemon is restarted.
#   ## Reset gauges every interval (default=true)
    delete_gauges = false
#   ## Reset counters every interval (default=true)
    delete_counters = false
#   ## Reset sets every interval (default=true)
    delete_sets = true
#   ## Reset timings & histograms every interval (default=true)
    delete_timings = true
#
#   ## Percentiles to calculate for timing & histogram stats
#   percentiles = [90]
#
#   ## separator to use between elements of a statsd metric
    metric_separator = "_"
#
#   ## Parses tags in the datadog statsd format
#   ## http://docs.datadoghq.com/guides/dogstatsd/
#   parse_data_dog_tags = false
#
#   ## Statsd data translation templates, more info can be read here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/TEMPLATE_PATTERN.md
#   # templates = [
#   #     "cpu.* measurement*"
#   # ]
#
#   ## Number of UDP messages allowed to queue up, once filled,
#   ## the statsd server will start dropping packets
    allowed_pending_messages = 100000
#
#   ## Number of timing/histogram values to track per-measurement in the
#   ## calculation of percentiles. Raising this limit increases the accuracy
#   ## of percentiles but also increases the memory usage and cpu time.
#   percentile_limit = 1000

[[outputs.prometheus_client]]
#   ## Address to listen on
    listen = ":9273"
#
#   ## Use HTTP Basic Authentication.
#   # basic_username = "Foo"
#   # basic_password = "Bar"
#
#   ## If set, the IP Ranges which are allowed to access metrics.
#   ##   ex: ip_range = ["192.168.0.0/24", "192.168.1.0/30"]
#   # ip_range = []
#
#   ## Path to publish the metrics on.
    path = "/metrics"
#
#   ## Expiration interval for each metric. 0 == no expiration
    expiration_interval = "30d"
#
#   ## Collectors to enable, valid entries are "gocollector" and "process".
#   ## If unset, both are enabled.
    collectors_exclude = ["gocollector", "process"]
#
#   ## Send string metrics as Prometheus labels.
#   ## Unless set to false all string metrics will be sent as labels.
#   # string_as_label = true
#
#   ## If set, enable TLS with the given certificate.
#   # tls_cert = "/etc/ssl/telegraf.crt"
#   # tls_key = "/etc/ssl/telegraf.key"
#
#   ## Set one or more allowed client CA certificate file names to
#   ## enable mutually authenticated TLS connections
#   # tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]
#
#   ## Export metric collection time.
    export_timestamp = false
```

### System info:
$ telegraf --version
Telegraf 1.12.3 (git: HEAD 16784bca)

$ uname -a
Linux VM_41_234_centos 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by danielnelson** [comment]
We will have to collect more information before we can take an action.  Try adding a file output with `data_format = "influx"` only for this single field and checking the output:
```toml
[[outputs.file]]
  files = ["/tmp/telegraf-debug"]
  data_format = "influx"
  namepass = ["iov_vehicle_gateway_get_capability_total"]
  [outputs.file.tagpass]
    host = ["VM_41_234_centos"]
```

**Comment by Logic0** [comment]
It has recovered after restarting telegraf. This happens about half an month.
I will do it when it happens again. Thanks.

**Comment by Logic0** [comment]
It happens again, luckly the same metric. But not jumps to 1 very frequently.
test_metric.py
![image](https://user-images.githubusercontent.com/3375925/72033502-76bcf180-32cd-11ea-8b38-d50155367761.png)

#./test_metric.py scrap content:
![image](https://user-images.githubusercontent.com/3375925/72033809-517cb300-32ce-11ea-9956-ffe3f061bed3.png)

telegraf outputs.file config:
```toml
# # Send telegraf metrics to file(s)
[[outputs.file]]
#   ## Files to write to, "stdout" is a specially handled file.
   files = ["/root/telegraf/debug/metrics-debug.out"]
#
#   ## Data format to output.
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
   data_format = "influx"
```

grafana value graph
![image](https://user-images.githubusercontent.com/3375925/72034078-feefc680-32ce-11ea-91e1-0d2d2bc03676.png)


size of metrics-debug.out grows too quickly, so I greped iov_vehicle_gateway_get_capability_total to cap.txt
[cap.txt](https://github.com/influxdata/telegraf/files/4038367/cap.txt)

thanks for help
