### ISSUE TITLE
SQL Server Input Plugin - Some counters are missing with CS or BIN server  collations 

### ISSUE THREAD

**Issue by mikedavem** [influxdata/telegraf#6867]
### Relevant telegraf.conf:

```toml
[[inputs.sqlserver]]

  servers = [
     "Server=xxxx;Port=xxxx;User Id=telegraf;Password=xxxx;app name=telegraf;log=1;"
  ]

  query_version = 2

  ## If you would like to exclude some of the metrics queries, list them here
  ## Possible choices:
  ## - PerformanceCounters
  ## - WaitStatsCategorized
  ## - DatabaseIO
  ## - DatabaseProperties
  ## - CPUHistory
  ## - DatabaseSize
  ## - DatabaseStats
  ## - MemoryClerk
  ## - VolumeSpace
  ## - Schedulers
  ## - AzureDBResourceStats
  ## - AzureDBResourceGovernance
  ## - SqlRequests
  ## - ServerProperties
  ## exclude_query = ['PerformanceCounters']

```

### System info:

Microsoft Windows Server 2016 Datacenter

### Steps to reproduce:

1. With SQL Server collation Latin1_General_100_BIN2

### Expected behavior:

All counters defined in PerformanceCounters metric queries should be collected

### Actual behavior:

Some counters PerformanceCounters metric queries are not collected due to their wrong case if we are using CS or BIN based server collation including:

'Page Lookups/sec'     --> 'Page lookups/sec'
'Page Reads/sec'       --> 'Page reads/sec',
'Page Writes/sec'      --> 'Page writes/sec',
'Readahead Pages/sec'  --> 'Readahead pages/sec'
'Lazy Writes/sec'      --> Lazy writes/sec
'Checkpoint Pages/sec' --> Checkpoint pages/sec
'Group Commits/sec'    --> Group Commits/Sec
