### ISSUE TITLE
Inputs consul missing tag "service_name" in output

### ISSUE THREAD

**Issue by smitjainsj** [influxdata/telegraf#6872]
### `service_name` tag is missing in the final output of the Telegraf.
running a local consul with registered named `web` should be visible ideally, however, its not visible in the output of Telegraf when using consul plugin

### Relevant telegraf.conf:

```toml
# Telegraf configuration
# Configurations for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "5s"
  round_interval = true
  metric_batch_size = 10
  metric_buffer_limit = 100
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "5s"
  debug = true
  quiet = true
  hostname = ""
  omit_hostname = false
  logfile = "logs/telegraf.log"
```

### System info:

```
❯ telegraf --version
Telegraf 1.13.0
```

### Actual behavior:

`telegraf -config telegraf.conf -config-directory config`

### Additional info:

config/consul.conf
```
[[inputs.consul]]
  address = "localhost:8500"
  scheme = "http"
  tag_delimiter = ":"
```

config/output.conf
```
[[outputs.file]]
  files = ["stdout", "logs/metrics.out"]
  data_format = "influx"%
```
------

output
``` 
❯ telegraf -config telegraf.conf -config-directory config
2020-01-07T17:17:15Z I! Starting Telegraf 1.13.0
consul_health_checks,check_id=serfHealth,host=smits-MBP.local,node=smits-MBP.local check_name="Serf Health Status",service_id="",status="passing",passing=1i,critical=0i,warning=0i 1578417445000000000
consul_health_checks,check_id=serfHealth,host=smits-MBP.local,node=smits-MBP.local service_id="",status="passing",passing=1i,critical=0i,warning=0i,check_name="Serf Health Status" 1578417440000000000
consul_health_checks,check_id=serfHealth,host=smits-MBP.local,node=smits-MBP.local status="passing",passing=1i,critical=0i,warning=0i,check_name="Serf Health Status",service_id="" 1578417450000000000
consul_health_checks,check_id=serfHealth,host=smits-MBP.local,node=smits-MBP.local check_name="Serf Health Status",service_id="",status="passing",passing=1i,critical=0i,warning=0i 1578417455000000000
```
