### ISSUE TITLE
plugin x509_certs fails when a key is included in local files

### ISSUE THREAD

**Issue by benschweizer** [influxdata/telegraf#6890]
Software like haproxy require ssl keys to be in the same pem file like certs and chains.
Though, the plugins fails to handle that case when using local file input.

### Relevant telegraf.conf:
```toml
[[inputs.x509_cert]]
  # parse a local pem file that includes cert+chain+key
  sources= ["/etc/ssl/private/something.pem"]
~
```

### System info:
Telegraf 1.13.0 (git: HEAD 773e4ca5)

### Steps to reproduce:
1. create a pem file that contains a ssl key aside the certs
2. use local file as source

### Expected behavior:

The plugin should just skip over the ssl key and only parse certificates.

### Actual behavior:

The plugin aborts as the ssl key is not a valid certificate.

### Additional info:

The [pem module](https://golang.org/pkg/encoding/pem/#example_Decode) has an example how to parse this:
```
	block, rest := pem.Decode(pubPEMData)
	if block == nil || block.Type != "PUBLIC KEY" {
		log.Fatal("failed to decode PEM block containing public key")
	}
```
