### ISSUE TITLE
logroll issues with inputs.parser plugin enabled

### ISSUE THREAD

**Issue by Kedesai** [influxdata/telegraf#6900]
### Relevant telegraf.conf:

```toml
 [[inputs.logparser]]
#   ## Log files to parse.
#   ## These accept standard unix glob matching rules, but with the addition of
#   ## ** as a "super asterisk". ie:
#   ##   /var/log/**.log     -> recursively find all .log files in /var/log
#   ##   /var/log/*/*.log    -> find all .log files with a parent dir in /var/log
#   ##   /var/log/apache.log -> only tail the apache log file
   files = ["/www/allmylogfiles/logs/*_log.*"]
#
#   ## Read files that currently exist from the beginning. Files that are created
#   ## while telegraf is running (and that match the "files" globs) will always
#   ## be read from the beginning.
   from_beginning = false
#
#   ## Method used to watch for file updates.  Can be either "inotify" or "poll".
     watch_method = "poll"
#   [inputs.logparser.grok]
#     ## This is a list of patterns to check the given log file(s) for.
#     ## Note that adding patterns here increases processing time. The most
#     ## efficient configuration is to have one pattern per logparser.
#     ## Other common built-in patterns are:
#     ##   %{COMMON_LOG_FORMAT}   (plain apache & nginx access logs)
#     ##   %{COMBINED_LOG_FORMAT} (access logs + referrer & agent)
#     patterns = ["%{COMBINED_LOG_FORMAT}"]
#
#     ## Name of the outputted measurement name.
#     measurement = "apache_access_log"
#
#     ## Full path(s) to custom pattern files.
#     custom_pattern_files = []
#
#     ## Custom patterns can also be defined here. Put one pattern per line.
#     custom_patterns = '''
#     '''
timezone = "America/New_York"
```

### Steps to reproduce:

1. With this input set the inputs.logparser holds on to all the files in the directory
when I do a lsof and grep for telegraf I see that it is reading all the 100k log files in that directory even the ones that have rolled.  I am pasting a sample lsof
telegraf   1198 11529  telegraf    6r      REG     253,11   1389224   33565233 /www/allmylogfiles/access_log.20191130
telegraf   1198 11529  telegraf    7r      REG     253,11   1385613   33563495 /www/allmylogfiles/access_log.20191103
telegraf   1198 11529  telegraf    8r      REG     253,11   1389218   33563500 /www/allmylogfiles/access_log.20191104
telegraf   1198 11529  telegraf    9r      REG     253,11   1403586   33554543 /www/allmylogfiles/access_log.20191105
telegraf   1198 11529  telegraf   10r      REG     253,11      4094   33554540 /www/allmylogfiles/error_log.20191105
telegraf   1198 11529  telegraf   11r      REG     253,11   1403117   33554554 /www/allmylogfiles/access_log.20191107
telegraf   1198 11529  telegraf   12r      REG     253,11   2050047   33563530 /www/allmylogfiles/access_log.20191108
telegraf   1198 11529  telegraf   13r      REG     253,11   1386133   33554544 /www/allmylogfiles/access_log.20191109
telegraf   1198 11529  telegraf   14r      REG     253,11   1387769   33563493 /www/allmylogfiles/access_log.20191110
telegraf   1198 11529  telegraf   15r      REG     253,11   1385342   33563504 /www/allmylogfiles/access_log.20191111
telegraf   1198 11529  telegraf   16r      REG     253,11   1560924   33563509 /www/allmylogfiles/access_log.20191112
telegraf   1198 11529  telegraf   17r      REG     253,11   1392318   33563489 /www/allmylogfiles/access_log.20191113
telegraf   1198 11529  telegraf   18r      REG     253,11   1390370   33563499 /www/allmylogfiles/access_log.20191114
telegraf   1198 11529  telegraf   19r      REG     253,11   1387839   33554555 /www/allmylogfiles/access_log.20191029
telegraf   1198 11529  telegraf   20r      REG     253,11   1386936   33563508 /www/allmylogfiles/access_log.20191030
telegraf   1198 11529  telegraf   21r      REG     253,11   1389297   33554534 /www/allmylogfiles/access_log.20191031

2. ...
