### ISSUE TITLE
Telegraf Doesn't Send Data When There Is Error

### ISSUE THREAD

**Issue by mertbakir** [influxdata/telegraf#6904]
### Relevant telegraf.conf:

```toml
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Paging File"
    Instances = ["*"]
    Counters = ["% Usage"]
    Measurement = "win_pagingfile"
    # Set to true to include _Total instance when querying for all (*).
    IncludeTotal=true
```

### System info:

Telegraf 1.12.5
OS Windows 2008 R2

### Behavior:

![image](https://user-images.githubusercontent.com/43188411/72409081-cf7d0600-3775-11ea-9b07-32ef3907781c.png)

Telegraf returns error when there is no instance on a specific object in this case "Paging File"
Returning error is normal but when it returns error it doesn't send data to influxdb. I expect it to send the data for working plugins and skip the non working ones.
