### ISSUE TITLE
inputs.jenkins plugin fails with "Error in plugin: empty monitor data, please check your permission" in Node collection

### ISSUE THREAD

**Issue by akagalkararkin** [influxdata/telegraf#6929]
### Relevant telegraf.conf:

```toml
[[inputs.jenkins]]
  ## The Jenkins URL in the format "schema://host:port"
  url = "https://<jenkins-host>/"

  ## Set response_timeout
  response_timeout = "5s"
  name_prefix = "jenkinsmaster"
```

### Steps to reproduce:

1.  Run - telegraf --config jenkinsMaster.conf --input-filter jenkins --test
2. Output is
2020-01-21T11:41:52Z I! Starting Telegraf 1.11.3
2020-01-21T11:41:53Z E! [inputs.jenkins]: Error in plugin: empty monitor data, please check your permission
2020-01-21T11:41:53Z E! [inputs.jenkins]: Error in plugin: empty monitor data, please check your permission
2020-01-21T11:41:53Z E! [inputs.jenkins]: Error in plugin: empty monitor data, please check your permission
2020-01-21T11:41:53Z E! [inputs.jenkins]: Error in plugin: empty monitor data, please check your permission
 jenkinsmasterjenkins_job,host=ec3-10-79-43-46,name=job1,result=SUCCESS duration=3523i,result_code=0i 1579604920000000000
> jenkinsmasterjenkins_job,host=ec3-10-79-43-46,name=job3,result=SUCCESS duration=21315i,result_code=0i 1579603369000000000
2020-01-21T11:42:11Z E! [inputs.jenkins]: Error in plugin: net/http: request canceled (Client.Timeout exceeded while reading body)
> jenkinsmasterjenkins_job,host=ec3-10-79-43-46,name=job3,result=SUCCESS duration=293129i,result_code=0i 1579603509000000000
> jenkinsmasterjenkins_job,host=ec3-10-79-43-46,name=job2,result=SUCCESS duration=19014i,result_code=0i 1579606245000000000

### Expected behavior:
Job and Nodes data to be collected
I h

### Actual behavior:
Only job data is being collected. Error has been recorded in case of node collection
