### ISSUE TITLE
FreeBSD - Delayed writing of log files

### ISSUE THREAD

**Issue by billyhudson** [influxdata/telegraf#6936]
I'm finding that telegraf is not writing to it's log file consistently.
Sometimes logs are not written until the `telegraf` service is stopped.

After running `/usr/local/bin/telegraf` directly I can see that the `stopping` logs are also absent when stopping the service via `service telegraf stop`

### Relevant telegraf.conf:

```toml
[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "10s"
  precision = ""
  debug = true
  quiet = false
  omit_hostname = false
```

### System info:

```
# pkg info telegraf
telegraf-1.12.5
# freebsd-version
12.0-RELEASE-p12
```

### Steps to reproduce:

`service telegraf start`
observe log file, empty.
wait 5 minutes
observe log file, empty.
metrics have been written to output (influx)
observe log file, empty.
`service telegraf stop`
observe log file, telegraf start is present along with last 5 minutes of debug.
`service telegraf start`
observe log file, most recent start logs not present.
wait 15 minutes
observe log file, most recent start logs not present.
`service telegraf stop`
observe log file, telegraf start is present along with last 15 minutes of debug

### Expected behavior:

logs entries are written to `/var/log/telegraf/telegraf.log` in a timely manner.

### Actual behavior:

They're not.
