### ISSUE TITLE
Question: metrics not generated by input_plugin postgresql_extensible

### ISSUE THREAD

**Issue by gowtham500** [influxdata/telegraf#6939]
1. Below is the config in postgresql_extensible.  There are 3 fields in the output - db,table, table size.
2. Table size is casted as integer. 
3. Still there are no metrics.  
4. They query when run under the user - monitor_user on the DB directly fetches output. So there is no permission issue.
5. This is being run on postgres 12.1 and telegraf 1.10.2

```
[[inputs.postgresql_extensible]]
  address = "postgres://monitor_user:pwd@hostname:5432/postgres"
[[inputs.postgresql_extensible.query]]
  sqlquery="SELECT current_database() as db,relname AS table,pg_table_size(C.oid)::integer as table_size FROM pg_class C LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r') ORDER BY pg_table_size(C.oid) DESC;"
  version=801
  withdbname=false
  tagvalue="db,table,table_size"
  measurement=""

```

I dont see any metrics generated by below command as well.

```
/usr/bin/telegraf -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d --input-filter postgresql_extensible --output-filter prometheus_client --test
```

Manually inspecting the http://hostname:9126/metrics shows no metrics as well.
Can you please help to resolve this issue.

**Comment by russorat** [comment]
@gowtham500 thanks for the issue. This might sound silly, but have you verified the query returns results when run manually against the database?  

Since we don't see a lot of other comments from people using this plugin about this error, my guess is that this has something to do with the query.

**Comment by gowtham500** [comment]
Yes, it does.  Ok let me put this in this way. Lets say we are running a query and it gives output as follows.

col1, col2, col3
a1      b1      1
a2      b2      2
a3      b3      3

|col1| col2 |col3|
|---|---|---|
|    |     |    |
|    |     |    |

Now let say name of this metric is metric_A, how do we get Telegraf to dump this data for prometheus output client as follows.

metric_A{col1=a1,col2=b1} @timestamp,1
metric_A{col1=a2,col2=b2} @timestamp,2
metric_A{col1=a1,col2=b1} @timestamp,3

**Comment by danielnelson** [comment]
You must have at least one non-tag value, does it help if you remove `table_size` from the list of tag values?

**Comment by gowtham500** [comment]
@danielnelson Thanks, In above configuration, I removed the tablesize from tags column and I do get output. But I get it for only the DB which is in [[inputs.postgresql]] connection string.
I am not getting for other dbs. How do we do that ?

**Comment by danielnelson** [comment]
For each database you will need to create a new plugin instance:
```toml
[[inputs.postgresql_extensible]]
  address = "postgres://monitor_user:pwd@hostname:5432/a"
  [[inputs.postgresql_extensible.query]]
    sqlquery="SELECT current_database() as db,relname AS table,pg_table_size(C.oid)::integer as table_size FROM pg_class C LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r') ORDER BY pg_table_size(C.oid) DESC;"
    version=801
    withdbname=false
    tagvalue="db,table"
    measurement=""

[[inputs.postgresql_extensible]]
  address = "postgres://monitor_user:pwd@hostname:5432/b"
  [[inputs.postgresql_extensible.query]]
    sqlquery="SELECT current_database() as db,relname AS table,pg_table_size(C.oid)::integer as table_size FROM pg_class C LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace) WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND nspname !~ '^pg_toast' AND relkind IN ('r') ORDER BY pg_table_size(C.oid) DESC;"
    version=801
    withdbname=false
    tagvalue="db,table"
    measurement=""
```
