### ISSUE TITLE
Telegraf | Change the tag name for "agent_host"

### ISSUE THREAD

**Issue by timwellman** [influxdata/telegraf#6943]
No sure if I am in the correct place for this ask.

I am looking to change the tag name for "agent_host"
example.

2020-01-27T13:45:52Z I! Starting Telegraf 1.10.4
> SysServices,SysDescr=Cisco\ IOS\ XR\ Software\ (NCS-5500)\,\ Version\ 6.3.2\r\nCopyright\ (c)\ 2013-2017\ by\ Cisco\ Systems\,\ Inc.,**_agent_host_**=1.1.1.7,host=4fe16b5db921,hostname=default UpTime=1817106218i 1580132754000000000

I would like to change the "agent_host" tag to "ip_addr"

**Comment by danielnelson** [comment]
You can use the rename processor to do this type of modification:
```toml
[[processors.rename]]
  namepass = ["SysServices"]
  [[processors.rename.replace]]
    tag = "agent_host"
    dest = "ip_addr"
```
