### ISSUE TITLE
[regression] amqp output over TLS does not work since 1.13.0

### ISSUE THREAD

**Issue by lassizci** [influxdata/telegraf#6949]
amqp output with TLS+certificate authentication seems to be broken since version 1.13.0. I was upgrading from 1.9.4 and noticed the telegrafs were no longer able to connect to the brokers.

The latest version I got it to work as it used to is 1.12.6-1

### Relevant telegraf.conf:

```toml
[outputs]
[[outputs.amqp]]
brokers = [ "amqps://rmq1:5672/"]
exchange = "telegraf_exchange"
delivery_mode = "persistent"
max_messages = 1000
username = "telegraf_user"
password = "telegraf_password"
tls_ca = "/etc/telegraf/ssl/ca-chain.crt"
tls_cert = "/etc/telegraf/ssl/telegraf-client.crt"
tls_key = "/etc/telegraf/ssl/telegraf-client.key"

```

### System info:

```
Telegraf 1.13.2 (git: HEAD 6dad859d)
```
Ubuntu 18.04

RabbitMQ 3.7.7

### Steps to reproduce:

1. setup a rabbitmq 3.7 with TLS/certificate authentication. Example config for rabbitmq:
```
listeners.ssl.1 = 0.0.0.0:5672
ssl_options.cacertfile = /etc/rabbitmq/cert/ca-chain.cert.pem
ssl_options.certfile = /etc/rabbitmq/cert/server.cert.pem
ssl_options.fail_if_no_peer_cert = true
ssl_options.keyfile = /etc/rabbitmq/cert/server.key.pem
ssl_options.verify = verify_peer
tcp_listen_options.backlog = 4096
tcp_listen_options.exit_on_close = false
tcp_listen_options.linger.on = true
tcp_listen_options.linger.timeout = 0
tcp_listen_options.nodelay = true
vm_memory_high_watermark.relative = 0.8
ssl_options.cacertfile = /etc/rabbitmq/cert/ca-chain.cert.pem
ssl_options.certfile = /etc/rabbitmq/cert/server.cert.pem
ssl_options.keyfile = /etc/rabbitmq/cert/server.key.pem
```
2. start telegraf with above `telegraf.conf` configuration

### Expected behavior:

Telegraf should connect to rabbitmq

### Actual behavior:
```
2020-01-28T17:17:55Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf_client", Flush Interval:10s
2020-01-28T17:17:55Z D! [agent] Initializing plugins
2020-01-28T17:17:55Z D! [agent] Connecting outputs
2020-01-28T17:17:55Z D! [agent] Attempting connection to [outputs.amqp]
2020-01-28T17:17:55Z D! Output [amqp] connecting to "amqps://rmq1:5672/"
2020-01-28T17:17:55Z D! Output [amqp] error connecting to "amqps://rmq1:5672/" - read tcp 10.0.0.10:35071->10.0.0.50:5672: read: connection reset by peer
```

### Additional info:
Like I mentioned, exactly the same configuration works up to 1.12.6. If I remove the username and password from telegraf's configuration, that doesn't result in any different log, which makes me suspect there's something up with the connection itself.
