### ISSUE TITLE
telegraf 1.13.x: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by itn3rd77** [influxdata/telegraf#6972]
Since an update from telegraf 1.12.6 to telgraf 1.13.1 or 1.13.2 all input plugins using HTTP/HTTPS (e.g. inputs.http_response or inputs.jolokia2_agent) are throwing errors when monitoring the server where telegraf is running. No matter if localhost or the fqdn is defined. 

```
Error in plugin: Unable to gather metrics for http://127.0.0.1:14115/jolokia: Post http://travic:***@127.0.0.1:14115/jolokia/read: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

When reverting back to telegraf 1.12.6 everything is fine again.

### Relevant telegraf.conf:

```toml
[[inputs.http_response]]
  ## List of urls to query.
  urls = ["https://localhost:8443"]

  ## Optional TLS Config
  insecure_skip_verify = true
```

### System info:
telegraf 1.13.1/1.13.2
Red Hat Enterprise Linux 7.6

### Steps to reproduce:

1. Define one ore more input plugins making use of http/https protocoll to localhost (e.g. inputs.http_response or inputs.jolokia2_agent)
2. After 10 seconds the first error messages appear in the log

```
Error in plugin: Unable to gather metrics for http://127.0.0.1:14115/jolokia: Post http://travic:***@127.0.0.1:14115/jolokia/read: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

### Expected behavior:

No errors are logs

### Actual behavior:

After 10 seconds the first error messages appear in the log

```
Error in plugin: Unable to gather metrics for http://127.0.0.1:14115/jolokia: Post http://travic:***@127.0.0.1:14115/jolokia/read: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by danielnelson** [comment]
Strange, I'm not sure what the issue might be.  Can you try with this configuration:
```toml
[[inputs.http_response]]
  urls = ["http://www.example.org"]
```
