### ISSUE TITLE
Allow using name_override for output plugins.

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#7033]
## Feature Request

Opening a feature request kicks off a discussion.

### Proposal:
Allow the use of the name_override parameter for output plugins.

### Current behavior:
Currently, renaming the target table is only available for input plugins.

### Desired behavior:
The ability to rename a table should be available both at the input and at the output. Right now, only filtering options are available to us.

### Use case: 
Such a proposal arose during the work with the Prometheus input plugin. 
The case is this - one container with an agent is placed in the k8s cluster, the input plugin is configured with the parameter `monitor_kubernetes_pods = true`.

After that, the agent starts collecting metrics from absolutely all application endpoints. Moreover, if we want to distribute the metrics of different applications into different tables, we are forced to create many input lines, which creates a load on the polling points of applications.

If we had the opportunity to specify the name of the table on the output line, we could limit ourselves to only one input line, creating the necessary number of output lines for distributing metrics according to the specified filtering rules.

Telegraf version - 1.13.0.

**Comment by M0rdecay** [comment]
I will add that initially I planned to create a proposal to improve the Prometheus input plugin - to set an array of annotations to limit the list of polled applications like:
```
[prometheus.inputs.annotations]
  "app.kubernetes.io/name" = [ "app1", "app2" ]
```

However, the option of renaming tables on the output lines seems more universal.

**Comment by danielnelson** [comment]
I'm not sure I understand how this might be used, it doesn't seem useful to have all measurements set to the same value for an output. Could you add an example of how you might setup and use this functionality?

For the prometheus/k8s use case you might be interested in #6969.

**Comment by M0rdecay** [comment]
Sure
We see it something like this:
```toml
[[inputs.prometheus]]    #Collect all metrics from all applications in k8s
  monitor_kubernetes_pods = true
  metric_version = 2       #All metrics will be recorded in one measurement - https://github.com/influxdata/telegraf/blob/3f7198fca5a063610c293ca26128c243a17d7ba1/plugins/inputs/prometheus/parser.go#L85

[[outputs.influxdb]]
  urls = [ "http://influx_one:8086" ]
  name_override = "app_one_general"
  [outputs.influxdb.tagpass]
    "kubernetes.io/name" = [ "application_one" ]

[[outputs.influxdb]]
  urls = [ "http://influx_one:8086" ]
  name_override = "app_two_general"
  [outputs.influxdb.tagpass]
    "kubernetes.io/name" = [ "application_two" ]

....

[[outputs.influxdb]]
  urls = [ "http://influx_one:8086" ]
  name_override = "app_ten_general"
  [outputs.influxdb.tagpass]
    "kubernetes.io/name" = [ "application_ten" ]

....
```
We also have several instances of various TSDBs on which we distribute metrics. The ability to specify measurement names within output lines would be convenient.

**Comment by danielnelson** [comment]
I don't see any reason why not to do this, and it gives us more consistency between plugins.  As a workaround, you could handle this with 3 `override` processors:
```toml
[[processors.override]]
  name_override = "app_one_general"
  [outputs.influxdb.tagpass]
    "app.kubernetes.io/name" = [ "application_one" ]

[[processors.override]]
  name_override = "app_two_general"
  [outputs.influxdb.tagpass]
    "app.kubernetes.io/name" = [ "application_two" ]

[[processors.override]]
  name_override = "app_ten_general"
  [outputs.influxdb.tagpass]
    "app.kubernetes.io/name" = [ "application_ten" ]
```

You might also be interested in following #6970 which would allow setting the measurement name to a tag value.

**Comment by M0rdecay** [comment]
I tried the option you proposed, thanks. It looks even better than my original decision.
Everything works fine until I start using something like:
```toml
[[processors.override]]
  name_override = "app_one_general"
  fieldpass = [ "general_metric_one" ] 
  [processors.override.tagpass]
    "app.kubernetes.io/name" = [ "application_one" ]

[[processors.override]]
  name_override = "app_two_general"
  fieldpass = [ "general_metric_two" ] 
  [processors.override.tagpass]
    "app.kubernetes.io/name" = [ "application_two" ]

...

[[processors.override]]
  name_override = "app_ten_general"
  fieldpass = [ "general_metric_ten" ] 
  [processors.override.tagpass]
    "app.kubernetes.io/name" = [ "application_ten" ]


[[processors.override]]
  name_override = "applications_common"
  fieldpass = [ "some_common_metric_*" ] 
  [processors.override.tagpass]
    "app.kubernetes.io/name" = [ "application_one" ,"application_two", "application_ten" ]

```
In this configuration, no metric reaches the output.

It seems that processors delete metrics that satisfy the `tagpass` condition, but do not fit the `fieldpass`, and the metrics simply do not reach the next processor.
It is expected that indicators that do not meet both conditions will be passed on and not deleted.


Is there a way to avoid deleting metrics?

**Comment by M0rdecay** [comment]
Although, this is, in fact, logical. Metrics pass through all processors sequentially. If I specify `fieldpass` somewhere, the rest of the series will be dropped...

**Comment by M0rdecay** [comment]
It turns out that the solution using `processors` closes my case only partially, because it processes the metrics in the pipeline, while I need to distribute them in parallel.

**Comment by danielnelson** [comment]
Unfortunately, tagpass and fieldpass operate differently and it's rather confusing.  Using tagpass will "select" a metric to be processed by a plugin, while fieldpass and name_override modify the metrics selected.   If all fields are removed the metric is removed.  With a processor plugin, only if the metric is "selected" then the modifiers are applied.  Otherwise the metric moves on to the next possible processor.

It isn't possible currently to have a plugin "select" a metric based on if it has a field, put another way, there isn't an equivalent of tagpass for fields.

**Comment by M0rdecay** [comment]
You're right. At the same time, I checked - using `fieldpass` on the output line does not remove the metric from the internal buffer:
```toml
[[inputs.prometheus]]
  urls = [ "http://demo.robustperception.io:9090/metrics" ]
  metric_version = 2
  
[[outputs.file]]
  files = [ "stdout" ]
  fieldpass = [ "go_gc_duration_seconds" ]
  
[[outputs.file]]
  files = [ "stdout" ]
  fieldpass = [ "go_gc_duration_seconds" ]
```
out:
`prometheus,quantile=1,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000207696 1582226220000000000
prometheus,quantile=0.75,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000028836 1582226220000000000
prometheus,quantile=0.5,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000025411 1582226220000000000
prometheus,quantile=0.25,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000022771 1582226220000000000
prometheus,quantile=1,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000207696 1582226220000000000
prometheus,quantile=0.75,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000028836 1582226220000000000
prometheus,quantile=0.5,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000025411 1582226220000000000
prometheus,quantile=0.25,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000022771 1582226220000000000
prometheus,quantile=0,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000014941 1582226220000000000
prometheus,quantile=0,url=http://demo.robustperception.io:9090/metrics go_gc_duration_seconds=0.000014941 1582226220000000000`

A short summary is what my case would solve:
 - `name_override` on the output line
 - settings for filtering scrapping pods in k8s, based on annotations for `prometheus` input plugin

**Comment by M0rdecay** [comment]
Hey. I would like to share a workaround that I managed to pick up for my case during evening reflections.
It looks like the following approach might work:
```toml
[[inputs.prometheus]]
  urls = [ "http://demo.robustperception.io:9090/metrics" ]
  metric_version = 2
  
[[outputs.file]]
  files = [ "stdout" ]
  tagexclude = [ "url" ]


[[processors.clone]]
  order = 1
  namepass = [ "prometheus" ] 
  name_override = "prometheus_2"

[[processors.override]]
  order = 2
  namepass = [ "prometheus_2" ]
  fieldpass = [ "go_gc_duration_seconds_*", "go_memstats_alloc_bytes_*" ]
  
[[processors.override]]
  order = 3
  namepass = [ "prometheus" ]
  fieldpass = [ "go_gc_duration_seconds_*" ]
```
Out:

> prometheus go_gc_duration_seconds_count=9652963,go_gc_duration_seconds_sum=317.42028282 1582824700000000000
> prometheus_2 go_gc_duration_seconds_count=9652963,go_gc_duration_seconds_sum=317.42028282 1582824700000000000
> prometheus_2 go_memstats_alloc_bytes_total=654735685808984 1582824700000000000

I will definitely check this solution tomorrow in the working environment and I can say for sure whether it is suitable.
