### ISSUE TITLE
Logparser sends not all metrics in one bundle (batch)

### ISSUE THREAD

**Issue by gassanpavel** [influxdata/telegraf#7038]
###Relevant telegraf.conf:

```toml
[global_tags]
[agent]
    interval = "10s"
    debug = true
    hostname = ""
    round_interval = false
    flush_interval = "5s"
    flush_jitter = "0s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 1000
    quiet = false
    logfile = "/var/log/telegraf/telegraf.log"
    omit_hostname = false

[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[outputs.http]]
  url = "https://webhook.site/c902cbda-5313-478a-951c-3fb64f46d62d"
  data_format = "json"

[[inputs.logparser]]
 files = ["/var/log/mdadm.log"]
  name_override = "log"
  from_beginning = false
  watch_method = "pool"
[inputs.logparser.grok]
    patterns = ['^%{TIMESTAMP_ISO8601:EVENT_TIMESTAMP} %{WORD:EVENT_LEVEL:tag} %{ID:EVENT_ID:tag} %{WORD:PROCESS_ID:tag} %{WORD:EVENT_SOURCE:tag} %{WORD:FUNCTION_NAME:tag}: %{DT:PARAM} - info(.*)']
    custom_patterns = '''
        ID (?:3[0-9][0-9][0-1]+)
        DT (/%{WORD}/%{WORD})
	'''

[[inputs.logparser]]
  files = ["/var/log/mdadm.log"]
  name_override = "log"
  from_beginning = false
  watch_method = "pool"
[inputs.logparser.grok]
    patterns = ['^%{TIMESTAMP_ISO8601:EVENT_TIMESTAMP} %{WORD:EVENT_LEVEL:tag} %{ID:EVENT_ID:tag} %{WORD:PROCESS_ID:tag} %{WORD:EVENT_SOURCE:tag} %{WORD:FUNCTION_NAME:tag}: %{DT:PARAM} -> %{DT:PARAM1} - info(.*)']
    custom_patterns = '''
        ID (?:4[0-9][0-9][0-1]+)
        DT (/%{WORD}/%{WORD})
        '''

[[inputs.logparser]]
  files = ["/var/log/mdadm.log"]
  name_override = "log"
  from_beginning = false
  watch_method = "pool"
[inputs.logparser.grok]
    patterns = ['^%{TIMESTAMP_ISO8601:EVENT_TIMESTAMP} %{WORD:EVENT_LEVEL:tag} %{ID:EVENT_ID:tag} %{WORD:PROCESS_ID:tag} %{WORD:EVENT_SOURCE:tag} %{WORD:FUNCTION_NAME:tag}: %{DT:PARAM} - fail(.*). Error message %{GREEDYDATA:ERROR_MESSAGE}. Error command %{GREEDYDATA:ERROR_COMMAND}']
    custom_patterns = '''
        ID (?:3[0-9][0-9]2+)
        DT (/%{WORD}/%{WORD})
	'''

[[inputs.logparser]]
  files = ["/var/log/mdadm.log"]
  name_override = "log"
 from_beginning = false
 watch_method = "pool"
[inputs.logparser.grok]
    patterns = ['^%{TIMESTAMP_ISO8601:EVENT_TIMESTAMP} %{WORD:EVENT_LEVEL:tag} %{ID:EVENT_ID:tag} %{WORD:PROCESS_ID:tag} %{WORD:EVENT_SOURCE:tag} %{WORD:FUNCTION_NAME:tag}: %{DT:PARAM} -> %{DT:PARAM1} - fail(.*). Error message %{GREEDYDATA}. Error command %{GREEDYDATA}']
    custom_patterns = '''
        ID (?:4[0-9][0-9]2+)
        DT (/%{WORD}/%{WORD})
    '''


```

### System info:

Telegraf 1.13.3
UBUNTU 18.04

### Steps to reproduce:
write 2 line into the log (/var/log/mdadm.log) file several times
2020-02-17 16:24:48 INFO 4050 11936 mdadm mdadm_add_spare: /dev/sdc -> /dev/md127 - info: try to add spare
2020-02-17 16:24:48 ERROR 4052 11936 mdadm mdadm_add_spare: /dev/sdc -> /dev/md127 - fail: add spare. Error message [mdadm: Cannot open /dev/sdc: Device or resource busy]. Error command ['mdadm /dev/md127 --add-spare /dev/sdc']

### Expected behavior:
Expect that telegraf will catch all lines write to log file and send it to output plugin

### Actual behavior:
When I write log file 2 lines - telegraf sometimes send 1 metric to output plugin
Then I write same 2 lines to log file and telegraf send 3 metric to output plugin

### Additional info:
Sometimes I got DEBUG messages in telegraf log
2020-02-17T16:24:48Z D! Grok no match found for: "2020-02-17 16:24:48 INFO 4050 11936 mdadm mdadm_add_spare: /dev/sdc -> /dev/md127 - info: try to add spare"
but Grok pattern for this line is correct, in my telegraf.conf
