### ISSUE TITLE
Question regarding to separate plugins to certain graphic databases.  

### ISSUE THREAD

**Issue by microwave012** [influxdata/telegraf#7058]
Our current set up is to let telegraf sending metrics to both influxdb and graphite. Is there are possible way to control the xyz plugins to send metrics to influxdb and abc plugins to graphite? 

All the telegraf setups are running as the service on Centos Environments. 

Thank you very much

**Comment by danielnelson** [comment]
This can be accomplished using [metric filtering](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#metric-filtering).

If the plugins always use a known measurement name, then namepass/namedrop work well:
```toml
[[inputs.xyz]]
[[inputs.abc]]

# Send abc to graphite
[[outputs.graphite]]
  namepass = ["abc*"]

# Everything else to InfluxDB
[[outputs.influxdb]]
  namedrop = ["abc*"]
```

For inputs with more dynamic naming you can add a tag to aid with routing, then remove it before writing:
```toml
[[inputs.xyz]]
  [inputs.xyz.tags]
    plugin = "xyz"

[[inputs.abc]]
  [inputs.abc.tags]
    plugin = "abc"

[[outputs.graphite]]
  tagexclude = ["plugin"]
  [outputs.graphite.tagpass]
    plugin = ["abc"]

[[outputs.influxdb]]
  tagexclude = ["plugin"]
  [outputs.graphite.tagpass]
    plugin = ["xyz"]
```
