### ISSUE TITLE
SqlServer Input - Missing "Batch Resp Statistics" for named instances

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7059]
Soon I will open a PR with the fix

### Relevant telegraf.conf:

```toml
[[inputs.sqlserver]]
  servers = [
    "Server=__AnyNamedInstance__;User Id=<user>;Password=<pw>;app name=telegraf;log=1;",
  ]

  query_version = 2
  ## Just Don't exclude 'PerformanceCounters'
  exclude_query = [ 'Schedulers' , 'SqlRequests']
```

### System info:
Not relevant, it happens on every (on-prem) named instance, regardless of Windows server or SQL Server version (from SQL Server 2012 and above)

### Steps to reproduce:

Compare the data gathered with the plugin, between a default instance and a named instance, i.e:
- QDSRVMONITOR → This is a default instance, its hidden name is "MSSQLSERVER" but does not need to be specified
- QDSRVMONITOR\SQL2017 → This is a named instance ("SQL2017" in this case)

In the measurement "sqlserver_performance", you will miss a series of tags for the SQL Instance, their name pattern is "Batches >= __value__ms & < __value__ms 

### Expected behavior:

Those counters are gathered also for named instances

### Actual behavior:
Those counters are not gathered

### Additional info:

This is due to a filter in the query, which excludes this counter for named instances
```sql
  {etc}
  ) OR (
    object_name LIKE 'SQLServer:Batch Resp Statistics%'
  ) OR {etc}
```

For default instances, the "object_name" will match, but named instances have a different value for "object_name", which is like this "MSSQL$<InstanceName>"
