### ISSUE TITLE
Prometheus output (metric_version = 2) prepends prometheus to all metrics

### ISSUE THREAD

**Issue by salarali** [influxdata/telegraf#7062]
All metrics being read by prometheus have prometheus prepended to the name.

### Relevant telegraf.conf:

```toml
# Read metrics from various Prometheus clients
[[inputs.prometheus]]

	name_prefix = "super_secret_"

	# Mapping from Prometheus to Telegraf metrics
	metric_version = 2

	# An array of urls to scrape metrics from
	urls = [ "http://localhost:9280/metrics" ]

	# Specify timeout for Prometheus clients
	response_timeout = "5s"

[[outputs.prometheus_client]]
	# Address to listen on
	listen = ":9273"

	# Export metric collection time
	export_timestamp = true

	# Mapping from Prometheus to Telegraf metrics
	metric_version = 2

```

### System info:

Telegraf 1.13.2 (git: HEAD 6dad859d)

Amazon Linux 2: 4.14.165-133.209.amzn2.x86_64

### Steps to reproduce:

1. Expose prometheus metrics in your service
2. Read metrics from your service in telegraf
3. Look at the metrics being sent to prometheus

### Expected behavior:

Does not prepend anything to the metric name.

```
super_secret_go_info{aws_name="super_secret",dc="us-east-1a",host="54.x.x.x",local_ip="172.x.x.x",os="centos",type="xxx",url="http://localhost:9280/metrics",version="go1.13.7"} 1
```

### Actual behavior:

Prepends prometheus to the metric name

```
super_secret_prometheus_go_info{aws_name="super_secret",dc="us-east-1a",host="54.x.x.x",local_ip="172.x.x.x",os="centos",type="xxx",url="http://localhost:9280/metrics",version="go1.13.7"} 1
```

**Comment by danielnelson** [comment]
With `metric_version = 2`, instead of `name_prefix` you will need to switch to `name_override` to get this behavior:
```toml
[[inputs.prometheus]]
	name_override = "super_secret"
	metric_version = 2
	urls = [ "http://localhost:9280/metrics" ]
	response_timeout = "5s"
```

I think this will solve the issue for you, but let us know if you run into any more problems.
