### ISSUE TITLE
win_perf_counters input: "counter with a negative denominator" error fails whole gather operation

### ISSUE THREAD

**Issue by rsirny** [influxdata/telegraf#7072]
We use telegraf to collect IIS app pools as well as other windows perf. counters. Occasionally, an app pool returns `counter with a negative denominator value was detected` error (see logs below) for `APP_POOL_WAS(app_pool)\Time Since Last Worker Process Failure` which causes the gather operation for ALL performance coutners to fail.

### Relevant telegraf.conf:

```toml
[[inputs.win_perf_counters]]
  UseWildcardsExpansion=true

# SECTIONS OMITTED

    [[inputs.win_perf_counters.object]]
    ObjectName = "APP_POOL_WAS"
    Counters = [
      "Current Application Pool State",
      "Current Application Pool Uptime",
      "Current Worker Processes",
      "Maximum Worker Processes",
      "Recent Worker Process Failures",
      "Time Since Last Worker Process Failure"
    ]
    Instances = ["*"]
    Measurement = "win_app_pool"
    IncludeTotal=false

```

### System info:
OS: Windows Server 2012 R2
Telegraf: 1.12.2

### Steps to reproduce:

This issue happens only occasionally.

### Expected behavior:

When `counter with a negative denominator value was detected`, it should be logged, but the gather operation should succeed.

### Actual behavior:

When `counter with a negative denominator value was detected`, it is logged, but the gather operation fails. As a result, we lose information about all the perf. counters due to one perf. counter misbehaving.

### Additional Info:

```
2020-02-23T10:35:39Z E! [inputs.win_perf_counters] Error in plugin: error while getting value for counter \\MYSERVER\APP_POOL_WAS(my_iis_app_pool)\Time Since Last Worker Process Failure: A counter with a negative denominator value was detected. 
```
