### ISSUE TITLE
ping: method native: percent_packet_loss=100 on Windows

### ISSUE THREAD

**Issue by dex4er** [influxdata/telegraf#7088]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "2s"
  round_interval = true

[[inputs.ping]]
  urls = ["8.8.8.8"]
  method = "native"
  count = 1
  ping_interval = 1.0
  timeout = 1.0
```

### System info:

Telegraf 1.13.3

Microsoft Windows [Version 10.0.19041.84]

### Steps to reproduce:

1. `.\telegraf.exe -config .\telegraf.conf -test`

### Expected behavior:

```
ping,host=NB0026,url=8.8.8.8 average_response_ms=191.7426,maximum_response_ms=191.7426,minimum_response_ms=191.7426,packets_received=1i,packets_transmitted=1i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0,ttl=53i 1582756206000000000
```

### Actual behavior:

```
ping,host=NB0026,url=8.8.8.8 packets_received=0i,packets_transmitted=1i,percent_packet_loss=100,result_code=1i 1582756226000000000
```
### Additional info:

It works correctly on Linux. On Windows always I get 100% packet lost which is not true because I see this traffic in Wireshark:

```
612	2020-02-26 23:30:25.127459	192.168.1.245	8.8.8.8	ICMP	98	Echo (ping) request  id=0x0000, seq=1/256, ttl=128 (reply in 613)
613	2020-02-26 23:30:25.192640	8.8.8.8	192.168.1.245	ICMP	98	Echo (ping) reply    id=0x0000, seq=1/256, ttl=54 (request in 612)
```
