### ISSUE TITLE
win_perf_counters -> No data to return.

### ISSUE THREAD

**Issue by dcst55** [influxdata/telegraf#7117]
If I run the telegraf.exe as a Service like: 
`net start telegraf`

in telegraf.log displayed the following Error message in the log:

```
2020-03-05T11:43:00Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2020-03-05T11:43:10Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2020-03-05T11:43:20Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
```

But if I start telegraf.exe per CMD like: 
`.\telegraf.exe -config .\telegraf.conf `
(So if I don't start it as a service) the Error Message not appear in the Log.

# Relevant telegraf.conf:

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/telegraf/telegraf.log"
  logfile_rotation_interval = 86400
  logfile_rotation_max_archives = 2
  hostname = ""
  omit_hostname = false

  [[processors.pivot]]
  tag_key = "counter"
  value_key = "value"

[[aggregators.merge]]
  drop_original = true


###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

 [[outputs.file]]
   files = ["C:/telegraf/output/metrics.json"]
   data_format = "json"

###############################################################################
#                                  INPUTS                                     #
###############################################################################

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",
      "% DPC Time",
    ]
    Measurement = "win_cpu"
    IncludeTotal=true

  [[inputs.win_perf_counters.object]]
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
      "Current Disk Queue Length",
      "% Free Space",
      "Free Megabytes",
    ]
    Measurement = "win_disk"
    IncludeTotal=true

  [[inputs.win_perf_counters.object]]
    ObjectName = "PhysicalDisk"
    Instances = ["*"]
    Counters = [
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Current Disk Queue Length",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
    ]
    Measurement = "win_diskio"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec",
      "Packets Received Discarded",
      "Packets Outbound Discarded",
      "Packets Received Errors",
      "Packets Outbound Errors",
    ]
    Measurement = "win_net"
	IncludeTotal=true

  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [
      "Context Switches/sec",
      "System Calls/sec",
      "Processor Queue Length",
      "System Up Time",
    ]
    Instances = ["------"]
    Measurement = "win_system"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes",
      "Standby Cache Reserve Bytes",
      "Standby Cache Normal Priority Bytes",
      "Standby Cache Core Bytes",
    ]
    Instances = ["------"]
    Measurement = "win_mem"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Paging File"
    Counters = [
      "% Usage",
    ]
    Instances = ["_Total"]
    Measurement = "win_swap"

 [[inputs.cpu]]
   percpu = false
   totalcpu = true
   collect_cpu_time = false
   report_active = false

fielddrop = ["usage_iowait", "usage_irq", "usage_nice", "usage_softirq", "usage_steal", "usage_system", "usage_user"]


 [[inputs.disk]]
  fielddrop = ["inodes*"]
  tagexclude = ["mode", "path"]

[[inputs.mem]]
fieldpass = ["swap_cached", "swap_free", "swap_total", "total", "used", "used_percent", "available", "available_percent", "name"]

[[inputs.sqlserver]]
  servers = ["Server=192.169.11.1;Port=1433;app name=telegraf;log=1;"]
  query_version = 2
  exclude_query = []

[inputs.sqlserver.tagpass]
counter = ["Lock Wait Count", 
            "Lock Wait Time", 
            "CPU Usage (time)", 
            "CPU usage %", 
            "Requests completed/sec", 
            "Queued requests", 
            "Logins/sec", 
            "Logouts/sec", 
            "Transactions/sec",
            "User Connections",
            "Backup/Restore Throughput/sec"
]
scheduler_id = ["*"]
wait_category = ["*"]
hardware_type = ["*"]
statement_text = ["*"]

[inputs.sqlserver.tagdrop]
instance = ["internal"]


```

### System info:

Telegraf Version 1.13.3
Windows Server 2019

### Steps to reproduce:

1. Install Telegraf as a Windows Service like https://github.com/influxdata/telegraf/blob/master/docs/WINDOWS_SERVICE.md
2. start Telegraf per Command Line:
`net start telegraf`

### Expected behavior:

Log without the following Message:

`E! [inputs.win_perf_counters] Error in plugin: No data to return.`

### Actual behavior:

The message always appears:
`E! [inputs.win_perf_counters] Error in plugin: No data to return.`
