### ISSUE TITLE
Unable to receive SNMP traps from Palo Alto Firewall

### ISSUE THREAD

**Issue by micruzz82** [influxdata/telegraf#7131]
I am trying to send SNMP traps from a Palo Alto firewall to my TIC server instance. The Palo Alto firewall need to have the SNMP server as well as the community value configured. However the telegraf snmp trap plugin does not have any documentation for the community value. What would be the way for the PA firewall to send traps to the snmp trap plugin.

### Relevant telegraf.conf:

```toml
cat /etc/telegraf/snmptraps.conf
[[inputs.snmp_trap]]
   service_address = "udp://:162"

[[inputs.snmp]]
  agents = [ "10.0.0.1","10.0.0.2" ]
  version = 2
  community = "public"
  interval = "60s"



# Output Plugin InfluxDB
[[outputs.influxdb]]
  database = "snmptraps"
  urls = [ "http://127.0.0.1:8086" ]
  username = "snmp"
  password = "snmptraps"

```

### System info:

telegraf -version
Telegraf 1.13.4 (git: HEAD ffabd6b5)

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

influx -version
InfluxDB shell version: 1.7.10

PA firewall 8.1.10

### Steps to reproduce:

1. ... Any device which can send SNMP trap with community value set
2. ... Does not get received on the box.

### Expected behavior:

Expect SNMP trap to be received when community value is mandatory field on the device sending the trap

### Actual behavior:

telegraf -config /etc/telegraf/snmptraps.conf
2020-03-08T03:06:16Z I! Starting Telegraf 1.13.4
2020-03-08T03:06:16Z I! Loaded inputs: snmp_trap snmp
2020-03-08T03:06:16Z I! Loaded aggregators:
2020-03-08T03:06:16Z I! Loaded processors:
2020-03-08T03:06:16Z I! Loaded outputs: influxdb
2020-03-08T03:06:16Z I! Tags enabled: host=df-snmp-trap-1
2020-03-08T03:06:16Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"snmp-trap-srv", Flush Interval:10s
2020-03-08T03:06:16Z I! [inputs.snmp_trap] Listening on udp://:162

[No output received]
