### ISSUE TITLE
Missing docker_container_blkio

### ISSUE THREAD

**Issue by bugsyb** [influxdata/telegraf#7153]
### Relevant telegraf.conf:

```toml
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  container_names = []
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  perdevice = false
  total = false
```

### System info:

```
telegraf --config /etc/telegraf/telegraf.conf --test|grep docker_container_blkio 
2020-03-11T10:01:18Z I! Starting Telegraf 1.13.4
```
### Steps to reproduce:

1. Docker container stood up with following config:
```
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    network_mode: host
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
      HOST_MOUNT_PREFIX: /hostfs
    volumes:
    - ${APPO}/telegraf/:/etc/telegraf/:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /sys:/rootfs/sys:ro
    - /proc:/rootfs/proc:ro
    - /etc:/rootfs/etc:ro
    - /:/hostfs:ro
```
### Expected behavior:

Data returned for docker_container_blkio same as for rest of nodes.
Docker host level data are returned properly, it seems to be an issue with docker_container_io only, excluding potential issue with docker.socket connection.

### Actual behavior:
Returns status and mem info, cpu and total network usage too.
```
### telegraf --config /etc/telegraf/telegraf.conf --test|grep docker_|grep -v "docker_container_cpu"|grep portainer

docker_container_status,container_image=portainer/portainer,container_name=portainer,container_status=running,container_version=unknown,engine_host=n2test,host=n2.local,server_version=18.09.7, container_id="container_ID_here",exitcode=0i,oomkilled=false,pid=8698i,started_at=1583790923725726385i,uptime_ns=130205275664882i 1583921129000000000

docker_container_mem,container_image=portainer/portainer,container_name=portainer,container_status=running,container_version=unknown,engine_host=n2test,host=n2.local,server_version=18.09.7, active_anon=8339456i,active_file=1474560i,cache=6656000i,container_id="container_ID_here",hierarchical_memory_limit=9223372036854771712i,inactive_anon=0i,inactive_file=5181440i,limit=3889528832i,mapped_file=4796416i,max_usage=22659072i,pgfault=250358i,pgmajfault=76i,pgpgin=248407i,pgpgout=244746i,rss=8339456i,rss_huge=0i,total_active_anon=8339456i,total_active_file=1474560i,total_cache=6656000i,total_inactive_anon=0i,total_inactive_file=5181440i,total_mapped_file=4796416i,total_pgfault=250358i,total_pgmajfault=76i,total_pgpgin=248407i,total_pgpgout=244746i,total_rss=8339456i,total_rss_huge=0i,total_unevictable=0i,total_writeback=0i,unevictable=0i,usage=9928704i,usage_percent=0.25526752542144415,writeback=0i 1583921129000000000
```

### Additional info:
Host system:
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.12.6
 Git commit:        18.09.7
 Built:             Mon Feb  3 04:56:39 UTC 2020
 OS/Arch:           linux/arm
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.6
  Git commit:       18.09.7
  Built:            Mon Feb  3 04:56:39 UTC 2020
  OS/Arch:          linux/arm
  Experimental:     true

```
On hardware side it is Odroid N2
Docker container shows:
```
dpkg --print-architecture
armhf

```
For some of containers it has been forced to arm64/v8, but not required. The docker host level somehow suggests to use v7 aka armhf instead of v8 but this is not causing this issue.
