### ISSUE TITLE
Disable Telegraf log file server Windows

### ISSUE THREAD

**Issue by guidovbrakel** [influxdata/telegraf#7156]
I would like to have option in the telegraf windows client configuration to compeltely disable the log file.

**Comment by danielnelson** [comment]
I believe you can do this on Windows to throw away all logging output:
```toml
[agent]
  logtarget = "file"
  logfile = "NUL"
```
