### ISSUE TITLE
SqlServer PerformanceCountersV2 - won't work except for SQL Server 2019 and Azure SQL DB

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7164]
### Relevant telegraf.conf:
Just do not exclude the PerfCounter Query (every other query excluded in this conf)
```toml
[[inputs.sqlserver]]
  ## Specify instances to monitor with a list of connection strings
  
  servers = [
    "Server=<Srv>;app name=telegraf;log=1;",
  ]

  query_version = 2

  ## If you would like to exclude some of the metrics queries, list them here
  ## Possible choices:
  ## - PerformanceCounters
  ## - WaitStatsCategorized
  ## - DatabaseIO
  ## - DatabaseProperties
  ## - CPUHistory
  ## - DatabaseSize
  ## - DatabaseStats
  ## - MemoryClerk
  ## - VolumeSpace
  ## - Schedulers
  ## - AzureDBResourceStats
  ## - AzureDBResourceGovernance
  ## - SqlRequests
  ## - ServerProperties
  exclude_query = [ 'Schedulers','SqlRequests','DatabaseIO','WaitStatsCategorized','DatabaseProperties','ServerProperties','MemoryClerk']
```

### System info:
OS not relevant.
It **won't work** on any version different from SQL Server 2019 or Azure SQL DB

### Steps to reproduce:
Just run 
> telegraf --config <cong> --test

### Expected behavior:
It should work form SQL Server 2012+

### Actual behavior:
Will work only on SQL 2019 and Azure SQL DB

Any other version will fail to validate the query
>I! Invalid column name 'physical_database_name'.
E! [inputs.sqlserver] Error in plugin: mssql: Invalid column name 'physical_database_name'.

### Additional info:

Issue introduced in January (see this [commit](https://github.com/influxdata/telegraf/commit/1df88dd22bf372327f24341b4043bb383e33529c#diff-5359fe28fcc15fe8b504f2d8033ce59d))

As of now, it does not affect any released telegraf verion
