### ISSUE TITLE
inputs.system plugin gives path-error when started by docker-compose.

### ISSUE THREAD

**Issue by number4jazz** [influxdata/telegraf#7178]
### Relevant telegraf.conf:
```
# Read metrics about system load & uptime
[[inputs.system]]
  ## Uncomment to remove deprecated metrics.
  # fielddrop = ["uptime_format"]
```

### System info:
```
# telegraf --version
Telegraf 1.13.4 (git: HEAD ffabd6b5)       (regular pull from docker hub)

OS: Alpine Linux 3.11

# cat /proc/version
Linux version 5.4.12-1-lts (buildozer@build-3-11-x86_64) (gcc version 9.2.0 (Alpine 9.2.0)) #2-Alpine SMP Thu, 16 Jan 2020 12:53:54 UTC

# docker --version
Docker version 19.03.5, build 633a0ea838f10e000b7c6d6eed1623e6e988b5bb
(regular docker package from Alpine repository)
```

### This works fine - starting telegraf container from CLI:
```
# docker run -d --name=telegraf_test \
      -e HOST_PROC=/host/proc \
      -v /proc:/host/proc:ro \
      -v /data/telegraf/config:/etc/telegraf:rw \
      telegraf
```
### This gives an error - starting container from docker-compose:
```
    telegraf:
      image: "telegraf"
      container_name: "telegraf"
      restart: "always"
      volumes:
        - "/data/telegraf/config:/etc/telegraf:rw"
        - "/proc:/host/proc:ro"
      environment:
        - HOST_PROC=/host/proc
```

### Expected behavior:
Regular startup.

### Actual behavior / Error message in telegraf.log:
An error occures which can be traced back in the telegraf logfile:
```
2020-03-16T13:22:50Z E! [inputs.system] Error in plugin: open '/host/proc'/loadavg: no such file or directory
```

This error message is repeated multiple times.

Notice the two single-quotes before and after /host/proc in the error message. It appears that somehow the path-string is not constructed in the correct way.

I tried to find a solution by Googling it .. but couldn't find it. Can someone help me with how to correct this?
