### ISSUE TITLE
inputs.exec plugin did not accept ' in dict

### ISSUE THREAD

**Issue by nicolargo** [influxdata/telegraf#7197]
### Relevant telegraf.conf:

```toml
[[inputs.exec]]
  commands = [ "/usr/bin/python /opt/facilities/openscc/satetl/bin/kafka-consumer-lag.py" ]
  timeout = "30s"
  interval = "1m"
  name_suffix = "_kafka_consumer_lag"
  data_format = "json"
  tag_keys = [ "client-id", "group", "partition", "topic", "host" ]
```

### System info:

Telegraf 1.12.6

### Steps to reproduce:

1. Create a Python script. This script will return a standard JSON object:

```
['foo': 1, 'bar': 2]
```

2. Execute this script through an inputs.exec 

3. Following error:

```
2020-03-18T20:15:02Z E! [inputs.exec] Error in plugin: invalid character '\'' looking for beginning of object key string
```

Change the script to return:

```
["foo": 1, "bar": 2]
```

Note " instead of ' 

and everything work fine !

### Expected behavior:

Accept '
