### ISSUE TITLE
CSV parser includes csv_measurement_name as a field

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/telegraf#7203]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "1m"
  round_interval = true
  metric_batch_size = 5000
  metric_buffer_limit = 5000000
  # collection_jitter = "0s"
  # flush_interval = "10s"
  # flush_jitter = "0s"
  precision = "us"
  debug = true
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = true

[[outputs.influxdb]]

  urls = ["http://localhost:8086"]
  database = "pressure"
  skip_database_creation = false
  ## Timeout for HTTP messages.
  timeout = "10s"

[[inputs.file]]

  ## Files to parse each interval.
  files = ["../datasets/data/PressureSensor1.csv"]
  
  data_format = "csv"
  csv_header_row_count = 1
  csv_skip_columns = 0
  csv_measurement_column = "measurement_name"
  csv_field_columns = ["damage", "value", "warning"]
  csv_tag_columns = ["description", "datatype"]
  csv_timestamp_column = "time"
  csv_timestamp_format = "unix_us"

```

### System info:

__Telegraf Version__: `Telegraf 1.13.4 (git: HEAD ffabd6b5)`
__OS__: Windows 10

### Steps to reproduce:

1. I have a csv file as the following:

         measurement_name,description,datatype,damage,value,warning,time
         Machine,Left,pressure,130.0,203.0,230.0,1581677425059610
2. On Windows within the `telegraf` directory:

         telegraf.exe --config .\csvconfig.conf

### Expected behavior:

In chronograf 

when the measurement `Machine` is clicked the fields should be:

    damage, value, warning

### Actual behavior:

![image](https://user-images.githubusercontent.com/12070966/77107212-a2243100-6a20-11ea-89ce-561a3247796c.png)

Event though the fields are specifically mentioned in the array (e.g. `["damage", "value", "warning"]`)

Based on [InfluxData's Blog about Write Points from CSV](https://www.influxdata.com/blog/how-to-write-points-from-csv-to-influxdb/).
### Additional info:

I have tried adding `skip_csv_columns=1` to skip the `measurment_name` but that still add it as a field.
