### ISSUE TITLE
Json Parser User Number as json_name_key

### ISSUE THREAD

**Issue by aretakisv** [influxdata/telegraf#7212]
I am receiving data from MQTT in json format
The standard format is:

```
{
  "value_id": "52-32-1-0",
  "node_id": 52,
  "class_id": 32,
  "type": "byte",
  "genre": "basic",
  "instance": 1,
  "index": 0,
  "label": "Basic",
  "units": "",
  "help": "Basic status of the node",
  "read_only": false,
  "write_only": false,
  "min": 0,
  "max": 255,
  "is_polled": false,
  "value": 0,
  "lastUpdate": 1584636017962
}
```
My measurement should be class_id. As class_id is the class of Zwave (32 in this case)
this is a number, and json parser cannot use it as name_key. is there a way for this to happen?

**Comment by danielnelson** [comment]
You could bring it in as a `tag_key`, then use the `converter` processor to set the tag to the measurement.  Might make sense to give it a good name using the enum processor while you are at it:
```toml
[[inputs.mqtt_consumer]]
  data_format = "json"
  tag_keys = ["class_id"]

[[processors.enum]]
  namepass = ["mqtt_consumer"]
  order = 1
  [[processors.enum.mapping]]
    tag = "class_id"
    [processors.enum.mapping.value_mappings]
      32 = "zwave"

[[processors.converter]]
  namepass = ["mqtt_consumer"]
  order = 2
  [processors.converter.tags]
    measurement = ["class_id"]
```
