### ISSUE TITLE
InfluxDB Output repeats create database indefinitely if it fails to create it

### ISSUE THREAD

**Issue by morfien101** [influxdata/telegraf#7235]
```toml
[outputs.influxdb]
urls = ["https://influxdburl:8086"]
database = "metrics"
username = "DevUser"
password = "SuperSecret"
database_tag = "influx_database"
exclude_database_tag = true
precision = "s"
skip_database_creation = true
```

### Expected behaviour:

Telegraf should check if it needs to create the database that it is about to write to, rather than blindly creating the database.

### Actual behaviour:

When running telegraf with the influxdb output and the "database_tag" option, telegraf will try to create the database on every flush interval. If it fails to create that database it will keep trying forever and log the failure excessively. The write itself works but there is no context in the code between the two processes.

### Additional info:

This is an example of the log that we get

```text
telegraf 2020-03-26T10:57:26Z W! [outputs.influxdb] When writing to [https://influxdburl:8086]: database "metrics" creation failed: 403 Forbidden
```
