### ISSUE TITLE
SqlServer: some tags have whitespaces appended up to a total length of 128 characters

### ISSUE THREAD

**Issue by leepfrog-ger** [influxdata/telegraf#7241]
### Relevant telegraf.conf:
```toml
[[inputs.sqlserver]]
  ## Specify instances to monitor with a list of connection strings.
  ## All connection parameters are optional.
  ## By default, the host is localhost, listening on default port, TCP 1433.
  ##   for Windows, the user is the currently running AD user (SSO).
  ##   See https://github.com/denisenkom/go-mssqldb for detailed connection
  ##   parameters.
  servers = [
    "Server=REDACTED"
  ]

  ## Optional parameter, setting this to 2 will use a new version
  ## of the collection queries that break compatibility with the original
  ## dashboards.
  query_version = 2
```

### System info:

- Telegraf 1.14.0-rc1 on Windows Server 2012 R2
- Querying SQL 2014/2016 on Windows Server 2012 R2
- Writing to InfluxDB

### Steps to reproduce:

1. Collect SQL Metrics
2. View tag values that are written to the InfluxDB Database

### Expected behavior:

Tags, e.g. the `instance` tag that can contain values like the database name for a specific metric are a string that contains exactly the name of the object (e.g. `tempdb`)

### Actual behavior:

Some tags seem to be appended with spaces to be exactly 128 characters in length (e.g. `tempdb                                                                                                                         [put 122 spaces here]`)

### Additional info:

1. Issue did not exist with Telegraf 1.10.4 and appeard when running 1.14.0-rc1, so it was introduced somewhere between those versions
2. The issue did start exactly when switching to the new Telegraf version, when taking the `tempdb` example there are *NO* entries with appended spaces *before* before the upgrade. There are *NO* entries without appended spaces *after* the time when the new version was deployed. 
3. From what I can tell the SQL query that is reading the values from the SQL server is returning correct data (so in the example it would return `tempdb` without any appended spaces)
4. This issue breaks several things down the line, e.g. dashboards and search filters, you now have two "different" entries for all objects
5. Github is truncating the spaces so I cannot post the influx query output here, but see the following screenshot to understand the issue:

![influx_sql](https://user-images.githubusercontent.com/10974885/77773529-0448eb80-704a-11ea-9214-7e13858e75be.png)

**Comment by leepfrog-ger** [comment]
Update:  can be reproduced with 1.14.0 release. Also observable when using file output: [sql_output_json.txt](https://github.com/influxdata/telegraf/files/4394862/sql_output_json.txt)

**Comment by leepfrog-ger** [comment]
Is there any other data I can provide to help to narrow this issue down?
Or does someone have an idea where that behaviour is caused?

**Comment by danielnelson** [comment]
I'm planning to take a look soon, in the meantime can you try this workaround:
```toml
[[processors.strings.trim]]
  namepass = ["sqlserver_performance"]
  tag = "instance"
```
