### ISSUE TITLE
Add processor that does service port to name translation

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#7244]
### Proposal:

Add a new processor that can convert a tag containing a well-known port number to the registered service name, according to the net.LookupPort function or similar.

### Current behavior:

N/A

### Desired behavior:

```toml
[[processors.lookup_port]]
  tag = "port"

  ## If set, write port to new tag key
  # dest = "service"
```

```diff
- foo,port=443 bar=42
+ foo,port=443,service=https bar=42
```

### Use case: 

Enrich the output of the sflow input.
