### ISSUE TITLE
Add processor that does a reverse dns lookup on a tag value

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#7245]
### Proposal:

Add a new processor that can convert a tag containing an IP address into a hostname, using a reverse dns lookup.

### Current behavior:

N/A

### Desired behavior:

```toml
[[processors.lookup_ip]]
  tag = "src_ip"

  ## If set, write port to new tag key
  # dest = "source"
```

```diff
- foo,src_ip=93.184.216.34 bar=42
+ foo,src_ip=93.184.216.34,source=example.org bar=42
```

### Use case: 

Enrich the output of the sflow input.

**Comment by neeles83** [comment]
This would be very helpful. But can we also use this processor in lets say SNMP Traps, so we can convert the "source" field to a DNS name or add an field by resolving the source field. 

Thus if the below is the trap received add an field sysname or dns which holds the resolved "source" field.

snmp_trap_ifType_259{
agent_address="10.128.x.x"
ciscoMgmt_276_1_1_2_1_3_259="up"
host="e955e22ac07f"
ifDescr_259="TenGigE0/1/0/19"
instance="10.215.X.x:9126"
job="telegraf"
mib="IF-MIB"
name="linkUp"
oid=".1.3.6.1.6.3.1.1.5.4"
**source**="10.128.1.1"
version="1"
**dns**="name.domain.com"
}

**Comment by danielnelson** [comment]
Yes you will be able to use this with the SNMP trap input, the processor will be separate plugin so you will want to configure the processor to match the desired traps:
```toml
[[inputs.snmp_trap]]
  # normal options

[[processors.lookup_ip]]
  namepass = ["snmp_trap"]
  tagpass = ["linkUp", "linkDown"]

  tag = "source"
  dest = "dns"
```

There are ideas for allowing processors to be directly included on an input, but that would be separate work sometime in the future.
