### ISSUE TITLE
Add processor to lookup SNMP ifName from ifIndex

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#7246]
### Proposal:

Add a new processor that can convert a tag containing an SNMP ifIndex into an ifName, using SNMP.

### Current behavior:

N/A

### Desired behavior:

```toml
[[processors.lookup_interface]]
  tag = "ifIndex"

  ## If set, write port to new tag key
  # dest = "ifName"
```

```diff
- foo,ifIndex=1 bar=42
+ foo,ifIndex=1,ifName=eth0 bar=42
```

### Use case: 

Enrich the output of the sflow input.

**Comment by Hipska** [comment]
Maybe make it more generic so that other fields can be retrieved as well? And also from other tables?

I would need this. Currently, this kind of lookup needs to be done by collecting the values via external script.

**Comment by danielnelson** [comment]
@Hipska This is a good idea, but it's a more complicated task and not in the design right now, maybe we can do it as a follow up.  Would be interested to hear more about your use case and what other tags you could use though.

**Comment by Hipska** [comment]
Have a look at [HUAWEI-XQoS-MIB::hwXQoSPortQueueStatisticsEntry](https://circitor.fr/Mibs/Html/H/HUAWEI-XQoS-MIB.php#HwXQoSPortQueueStatisticsEntry). There you have a table where the first 3 fields are the index. The first one is a reference to the `ifIndex`. I would like to be able to get the `ifName` and `ifAlias` or other fields if possible.

Same counts for [JUNIPER-DOM-MIB::JnxDomCurrentLaneEntry](http://oid-info.com/get/1.3.6.1.4.1.2636.3.60.1.2.1.1), but in this case the `ifIndex` is not available as a field, only as part of the index, so other processing will need to be done first.

**Comment by Hipska** [comment]
Sad to see this ticket already closed without any feedback on my comments @reimda @danielnelson. Anyone care to give feedback anyway?

**Comment by danielnelson** [comment]
@Hipska I think we may be able to add this sort of functionality in the future.  This plugin is a bit of an experiment and I hope we can gather ideas about what features we really need.

Right now the plugin is using a fallback method: ifName,  ifDescr.  Perhaps in the future we would want to provide control over the fallback order from the plugin so you could ask for: ifAlias, ifName, ifDescr:
```
collect = ["ifAlias", "ifName", "ifDescr"]
```

What do you think about the fallback strategy that the plugin is using?  I can also imagine adding in a way to do more explicit lookups:
```
[[processors.ifname.lookups]]
  ifName = "IF-MIB::ifName"
  ifAlias = "IF-MIB::ifAlias"
```

For the Juniper case, if the data provided to the processor is from the `snmp` input you could use `index_as_tag = true` on a table to include the index number.

**Comment by Hipska** [comment]
I like the multiple lookups definition! But I would rename the plugin, as it does not have much to do with ifname anymore:
```toml
[[processors.snmp_lookup]]
  ## Name of tag holding the index
  tag = "ifIndex"
  
  [[processors.snmp_lookup.lookups]]
    ifName = "IF-MIB::ifName"
    ifAlias = "IF-MIB::ifAlias"
```
Doing this would cover the most possible use-cases.
