### ISSUE TITLE
win_perf_counter input plugin - issue when instances are not always present

### ISSUE THREAD

**Issue by bielawb** [influxdata/telegraf#7281]
### Relevant telegraf.conf:

```toml
[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "RemoteFX Network"
    Instances = ["*"]
    Counters = [
      "Total Received Bytes",
    ]
    Measurement = "remotefx.network"
    IncludeTotal = false
```

### System info:

Any version of windows.
Any version of telegraf.

### Steps to reproduce:

1. Make sure there are no Remote Desktop connection active to the machine where telegraf is running.
2. Watch telegraf.log filling up with the errors about the missing data:
```
2020-04-02T13:05:05Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2020-04-02T13:05:10Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
```
3. Once Remote Desktop session is started, logging stops.

### Expected behaviour:

I'd like to be able to ignore these symptoms. As that might not be desired for all users of the plugin, I'd like to make it configurable option.
The best would be have it as an option on the individual measurement level, but having it at plugin level would also work.

### Actual behaviour:

No way to ignore missing instances, configurable or not.

### Additional info:
The way I would like to have that configured:

```toml
[[inputs.win_perf_counters]]
  # Possible solution: have that as a configuration option on the plugin level, default to false.
  IgnoreMissingInstance = true
  [[inputs.win_perf_counters.object]]
    ObjectName = "RemoteFX Network"
    Instances = ["*"]
    Counters = [
      "Total Received Bytes",
    ]
    Measurement = "remotefx.network"
    IncludeTotal = false
    # Preferred solution: be able to configure that on the measurement level.
    IgnoreMissingInstance = true
```

I have PR ready that allows plugin-wide configuration (unfortunately, I couldn't figure out proper testing for it).
