### ISSUE TITLE
SNMP input slow warning with just 18 snmp clients

### ISSUE THREAD

**Issue by leonv024** [influxdata/telegraf#7300]
### Relevant telegraf.conf:

```toml
[[inputs.snmp]]
  agents = [ "8.8.8.8" ]
  version = 2
  community = "public"
  interval = "60s"
  timeout = "10s"
  retries = 3
  [inputs.snmp.tags]
    name = "Home Router"

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "RFC1213-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"

  # IF-MIB::ifTable contains counters on input and output traffic as well as errors and discards.
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # IF-MIB::ifXTable contains newer High Capacity (HC) counters that do not overflow as fast for a few of the ifTable counters
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "IF-MIB::ifXTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
      is_tag = true

  # EtherLike-MIB::dot3StatsTable contains detailed ethernet-level information about what kind of errors have been logged on an interface (such as FCS error, frame too long, etc)
  [[inputs.snmp.table]]
    name = "interface"
    inherit_tags = [ "hostname" ]
    oid = "EtherLike-MIB::dot3StatsTable"

    # Interface tag - used to identify interface in metrics database
    [[inputs.snmp.table.field]]
      name = "ifDescr"
      oid = "IF-MIB::ifDescr"
```

### System info:

Ubuntu Server 18.04
Fiber connection
Telegraf 1.14.0
### Steps to reproduce:

1. add multiple configs with snmp clients, remote routers in my case. With a interval of 60 seconds.
2. Eventually, in my case around 18 clients, it can not longer retrieve the data
3. Telegraf stops working entirely. 

### Expected behavior:
Telegraf collects snmp data.

### Actual behavior:
SNMP error in the log and telegraf stops working entirely.

### Additional info:
Log is filled with:
2020-04-08T18:29:00Z W! [agent] [inputs.snmp] did not complete within its interval
2020-04-08T18:30:00Z W! [agent] [inputs.snmp] did not complete within its interval
