### ISSUE TITLE
Wireguard input plugin can't find device

### ISSUE THREAD

**Issue by kimdre** [influxdata/telegraf#7307]
### Relevant telegraf.conf:

```toml
# # Collect Wireguard server interface and peer statistics
[[inputs.wireguard]]
#   ## Optional list of Wireguard device/interface names to query.
#   ## If omitted, all Wireguard interfaces are queried.
   devices = ["wg0"]
```

### System info:

OS: Ubuntu 18.04.4 LTS
Telegraf 1.14.0
wireguard-tools v1.0.20200319 

### Steps to reproduce:

1. Activate Wireguard Plugin in Config with wg device name from `wg show`
2. Restart Telegraf

### Expected behavior:

Telegraf sends wg meaurements to influxdb

### Actual behavior:

Telegraf can't find wireguard device

### Additional info:

```
$ sudo wg show
interface: wg0
...
```

From telegraf.log:

> 2020-04-10T13:14:50Z W! [inputs.wireguard] No Wireguard device found with name wg0

I tried to add user telegraf to group root but that didn't help.
