### ISSUE TITLE
exclude_retention_policy_tag and exclude_database_tag excludes both DB and RP tags from metrics even if the other exclude_ parameter is set to false

### ISSUE THREAD

**Issue by abalone23** [influxdata/telegraf#7310]
### Relevant telegraf.conf:

```toml
 database_tag = "thedb"
## If true, the database tag will not be added to the metric.
  # exclude_database_tag = false

 retention_policy_tag = "therp"
 ## If true, the 'retention_policy_tag' will not be removed from the metric.
  exclude_retention_policy_tag = true
```

### System info:

telegraf 1.14

### Steps to reproduce:

1. Set `exclude_retention_policy_tag = true` and `exclude_database_tag = false` (or vice-versa)
2. `curl -i -XPOST 'http://localhost:8186/write' --data-binary 'cpu_load_short,thedb=mydb,therp=one_week,host=server01,region=us-west value=0.65 1586387198000700200'`

### Expected behavior:
```
> select * from cpu_load_short
name: cpu_load_short
time                host     region  thedb    value
----                ----     ------  -----    -----
1586387198000700200 server01 us-west mydb 0.65
```
### Actual behavior:

```
> select * from cpu_load_short
name: cpu_load_short
time                host     region  value
----                ----     ------  -----
1586387198000700200 server01 us-west 0.65
```
### Additional info:

`exclude_retention_policy_tag` should only exclude the rp
`exclude_database_tag` should only exclude the db
