### ISSUE TITLE
azure_monitor send fails with 400 - bad request due to more than 10 dimensions in metric

### ISSUE THREAD

**Issue by thecrazymonkey** [influxdata/telegraf#7318]
### Relevant section of values.yaml:

```
 outputs:
    - azure_monitor:
        timeout: "10s"
        skip_invalid: true
        namespace_prefix: "cp/"
    - health:
        service_address: "http://:8888"
  inputs:
    - prometheus:
        metric_version: 2
        response_timeout: "10s"
        monitor_kubernetes_pods: true
        monitor_kubernetes_pods_namespace: "test"
```

### System info:
Telegraf 1.14
Azure AKS

### Steps to reproduce:

1. Configure Prometheus input plugin to scrape from prometheus endpoints
2. Deploy telegraf using helm chart

### Expected behavior:
Prometheus metrics delivered to Azure Monitor

### Actual behavior:

Send fails with response
Error writing to outputs.azure_monitor: failed to write batch: [400] 400 Bad Request {"error":{"code":"BadRequest","message":"'dimValues' and 'dimNames' lengths should be lesser than 10\r\n"}}

### Additional info:

The issue is here:

https://github.com/influxdata/telegraf/blob/fefd7ff1919d8dbea0e9d1a9df9b8ca77d4c476b/plugins/outputs/azure_monitor/azure_monitor.go#L395

The logic above allows 11 items in the array - should be **>= 10**
