### ISSUE TITLE
Input execd is not flushing metrics

### ISSUE THREAD

**Issue by dgarros** [influxdata/telegraf#7337]
Looks like the new `execd` input plugin is not flushing the metrics properly. I tried with and without signal but the behavior is the same.

When I stop telegraf I see all my metrics coming up after the message `Hang on, flushing any cached metrics before shutdown`
```
2020-04-15T02:40:22Z I! [agent] Hang on, flushing any cached metrics before shutdown
test,host=damiens-mbp.lan bob=10i,alice=20i 1586918422765532000
```

### Relevant telegraf.conf:

```toml
[agent]
debug = true
interval = "10s"
flush_interval = "10s"
round_interval = tru

[[outputs.file]]
  files = ["stdout"]

[[inputs.execd]]

  command = [
      "python", "myscript.py"
  ]

  signal = "none"
  data_format = "influx"
```

### System info:

Version : Telegraf 1.14.0
OS: Mac OS / Linux

### Steps to reproduce:

Run a simple script with the `execd` input plugin and print the metrics to STDOUT
After 1min, stop telegraf with Ctrl+C

### Expected behavior:

since the script is generating metrics every 20s and the flush interval is set to 10s I'm expecting to see metrics on screen every ~20s. 
 
### Actual behavior:

Nothing is display on screen and when telegraf is stopped, all metrics are showing up

### Additional info:
here is the simplest python file I could find to reproduce the issue
```python
#myscript.py
import time

while 1: 
    print("test bob=10i,alice=20i")
    time.sleep(20)
```
