### ISSUE TITLE
Systemd Units Plugin: allow to have a white/blacklist of units you are interested in

### ISSUE THREAD

**Issue by schlitzered** [influxdata/telegraf#7341]
## Feature Request
allow to specify a regex white/blacklist to filter for services you are actually interested in

### Proposal:
allow to specify a regex white/blacklist to filter for services you are actually interested in

### Current behavior:
all services are reported, which might not be what you want

### Desired behavior:

allow to limit number of units that are reported

### Use case: 
save load on tss database

**Comment by ssoroka** [comment]
You should be able to do this already with [tagexclude and taginclude, fieldpass, and fielddrop](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#modifiers).

**Comment by schlitzered** [comment]
thanks! i will take a look at this.

**Comment by bencarlton** [comment]
@schlitzered, assuming you only wanted to emit metrics for the ssh service and any service with a name that starts with "myservice", you could add a tagpass block to your configuration like so:

### Configuration
```toml
[[inputs.systemd_units]]
  # input config omitted for brevity
  [inputs.systemd_units.tagpass]
    name = ["ssh.service", "myservice*"]
```
