### ISSUE TITLE
[Bind9] Parsing Error on DNS-Servers with values greater INT64

### ISSUE THREAD

**Issue by sankura** [influxdata/telegraf#7380]
### Relevant telegraf.conf:

```toml
[[inputs.bind]]
#   ## An array of BIND XML statistics URI to gather stats.
#   ## Default is "http://localhost:8053/xml/v3".
    urls = ["http://localhost:8053/xml/v3"]
#   # gather_memory_contexts = false
#   # gather_views = false
```

### System info:

Debian 10
Telegraf 1.14.1 (git: HEAD 33dd867d)
BIND 9.11.5-P4-5.1-Debian

### Steps to reproduce:

1. Use Bind Plugin on long running high load Bind9 servers with values greater then int64 

### Expected behavior:

stats get gathered

### Actual behavior:

[inputs.bind] Error in plugin: Unable to decode XML document: strconv.ParseInt: parsing "18446744073709550898": value out of range

### Additional info:

-
