### ISSUE TITLE
Testing mode does not include processors data

### ISSUE THREAD

**Issue by johnatannvmd** [influxdata/telegraf#7381]
### Relevant telegraf.conf:
<!-- Place config in the toml code section. -->
```toml
[[inputs.smart]]                                                                                                                                                                                                                                                                  
  path = "/usr/sbin/smartctl"                                                                                                                                                                                                                                                     
  use_sudo = true                                                                                                                                                                                                                                                                 
  nocheck = "standby"                                                                                                                                                                                                                                                             
  attributes = true                                                                                                                                                                                                                                                               
  devices = [ "/dev/sda1 -d megaraid,1" ]                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
[[processors.enum]]                                                                                                                                                                                                                                                               
  [[processors.enum.mapping]]                                                                                                                                                                                                                                                     
    field = "health_ok"                                                                                                                                                                                                                                                           
    dest = "health_ok_int"                                                                                                                                                                                                                                                        
    default = 0                                                                                                                                                                                                                                                                   
    [processors.enum.mapping.value_mappings]                                                                                                                                                                                                                                      
      true = 1                                                                                                                                                                                                                                                                    
      false = 0                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                  
[[outputs.influxdb]]                                                                                                                                                                                                                                                              
  urls = ["http://localhost:9999"]                                                                                                                                                                                                                                                
  database = "test_stats"                                                                                                                                                                                                                                                         
  retention_policy = ""                                                                                                                                                                                                                                                           
  write_consistency = "any"                                                                                                                                                                                                                                                       
  timeout = "5s"                                                                                                                                                                                                                                                                  
  namepass = ["smart_*"]
```

### System info:

Telegraf 1.14.0

### Steps to reproduce:

1. telegraf --config config.conf --test

### Expected behavior:

```
smart_device,capacity=1000204886016,device=sda1,enabled=Enabled,host=host_name,model=Samsung\ SSD\ 850\ EVO\ 1TB,serial_no=<redacted>,wwn=<redacted> exit_status=4i,health_ok=true,temp_c=40i,udma_crc_errors=0i,health_ok_int=1i 1587466631000000000
```

### Actual behavior:

```
smart_device,capacity=1000204886016,device=sda1,enabled=Enabled,host=host_name,model=Samsung\ SSD\ 850\ EVO\ 1TB,serial_no=<redacted>,wwn=<redacted> exit_status=4i,health_ok=true,temp_c=40i,udma_crc_errors=0i 1587466631000000000
```
