### ISSUE TITLE
[inputs.ping] Error when trying to lookup hosts

### ISSUE THREAD

**Issue by oijkn** [influxdata/telegraf#7386]
### Relevant telegraf.conf:

```toml
[global_tags]


# Configuration for telegraf agent
[agent]
    interval = "60s"
    debug = false
    hostname = "CentOS8"
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "0s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    logfile = "/var/log/telegraf/telegraf.log"
    omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.influxdb]]
    urls = ["http://192.168.1.19:8086"]
    skip_database_creation = true
    database = "Ping"
    timeout = "10s"
    retention_policy = ""

###############################################################################
##                                  INPUTS                                     #
################################################################################

# Ping given url(s) and return statistics
[[inputs.ping]]
  interval = '300s'
  urls = ['host01']
  count = 5
  ping_interval = 1.0
  timeout = 3.0
  deadline = 3
  method = 'native'
  interface = 'eth0'
  [inputs.ping.tags]
     plaque = '01'
     equipement = 'bng'

[[inputs.ping]]
  interval = '300s'
  urls = ['host02']
  count = 5
  ping_interval = 1.0
  timeout = 3.0
  deadline = 3
  method = 'native'
  interface = 'eth0'
  [inputs.ping.tags]
     plaque = '02'
     equipement = 'bng'

[[inputs.ping]]
  interval = '300s'
  urls = ['host03']
  count = 5
  ping_interval = 1.0
  timeout = 3.0
  deadline = 3
  method = 'native'
  interface = 'eth0'
  [inputs.ping.tags]
     plaque = '03'
     equipement = 'bng'

[[inputs.ping]]
  interval = '300s'
  urls = ['host04']
  count = 5
  ping_interval = 1.0
  timeout = 3.0
  deadline = 3
  method = 'native'
  interface = 'eth0'
  [inputs.ping.tags]
     plaque = '04'
     equipement = 'bng'

[[inputs.ping]]
  interval = '300s'
  urls = ['host05']
  count = 5
  ping_interval = 1.0
  timeout = 3.0
  deadline = 3
  method = 'native'
  interface = 'eth0'
  [inputs.ping.tags]
     plaque = '05'
     equipement = 'bng'
```

### System info:

```
# uname -a
Linux TIG 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# telegraf --version
Telegraf 1.14.1 (git: HEAD 33dd867d)
# influx --version
InfluxDB shell version: 1.8.0
```

### Steps to reproduce:

1. Setup ping telegraf and ping plugin with single host per plugin -> 5 hosts for testing
2. Ping a host that is or not resolvable using DNS server

### Expected behavior:

No such host if it's not resolvable or if it can be reached wait for the response from the DNS server.

### Actual behavior:

```
2020-04-22T15:35:40Z E! [inputs.ping] Error in plugin: lookup host1 on dns02.server:53: no such host
2020-04-22T15:37:14Z E! [inputs.ping] Error in plugin: lookup host2 on dns01.server:53: read udp 192.168.6.128:36283->dns01.server:53: i/o timeout
2020-04-22T15:37:14Z E! [inputs.ping] Error in plugin: lookup host1 on dns02.server:53: read udp 192.168.6.128:53474->dns02.server:53: i/o timeout
2020-04-22T15:37:14Z E! [inputs.ping] Error in plugin: lookup host3 on dns01.server:53: read udp 192.168.6.128:39761->dns01.server:53: i/o timeout
2020-04-22T15:37:38Z E! [inputs.ping] Error in plugin: lookup host2 on dns02.server:53: no such host
2020-04-22T15:37:38Z E! [inputs.ping] Error in plugin: lookup host3 on dns02.server:53: no such host
```

### Additional info:

Well I don't really know where to start because I did a lot of tests before creating this issue.
First of all I've already discussed a little bit about it  about it on https://github.com/influxdata/telegraf/pull/6743.

At first I thought that the error could be due to the fact that we are trying to search for so many hosts at the same time or that one or more hosts are not reachable. Later I realized that even if I remove the unreachable host from the list, I still get errors in the log file.

At first I was on the following configuration :

- VirtualBox with CentOS 7 (2vcpu / 4Go RAM)
- Network :
    - eth0 (NAT -> connexion LAN to DNS + Hosts)
    - eth1 (Bridge -> connexion with my Laptop)

With this configuration I had buffer problems with the ARP table, certainly caused to the large number of requests because initially I had +500 hosts in my list. So I decided to check with a different environment.

Second configuration :

- VMware Workstation with CentOS 8 (2vcpu / 4Go RAM)
- Network :
    - eth0 (NAT -> connexion LAN to DNS + Hosts) -> burst mode + DNS forced in settings
    - eth1 (Bridge -> connexion with my Laptop)

I guess VMware is more robust because I didn't have any buffer problem or anything else but the issue with the plugin remains the same :(

When I do a `dig` command of the host the answer is : 37 msec. But if I do a `ping`, it takes at least 3 or 4 seconds before the ping responds.

By modifying the settings of `/etc/resolv.conf` I get better results but that's not it yet...
```
search my.suffix
nameserver dns01.server
nameserver dns02.server

options timeout:1
options attempts:3
options rotate
```

I tried it anyway with the `method = 'exec'` and it seems that the problem does not appear (just once when launching the telegraf service).
On the other hand I see the 's' option for the packet size which is 16. The default packet size is 56, is this a bug ? `/usr/sbin/ping -c 5 -n -s 16 -i 1 -W 3 -w 3 -I eth0 host1`

Thank you for your support and help.
