### ISSUE TITLE
telegraf --test fails with bind: address already in use

### ISSUE THREAD

**Issue by Genda1ph** [influxdata/telegraf#7415]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "30s"
  flush_jitter = "5s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  retention_policy = ""
  write_consistency = "any"
  timeout = "20s"
  urls = ["snip"]
  database = "snip"
  username = "snip"
  password = "snip"


[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  fielddrop = ["time_*"]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "overlay2", "aufs"]

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.internal]]
  collect_memstats = true

[[inputs.interrupts]]

[[inputs.linux_sysctl_fs]]

[[inputs.net]]
  interfaces = ["bond*", "eth*", "em*", "eno*", "enp*", "ens*", "p*p*", "docker*"]

[[inputs.netstat]]

[[inputs.nstat]]

[[inputs.socket_listener]]
  service_address = "udp://127.0.0.1:8094"
```

### System info:

* Ubuntu Xenial, all packages are current.
* Telegraf  1.14.1-1 from official deb repo.
* The only process occupying mentioned port is `telegraf`:
    ```
    udp        0      0 127.0.0.1:8094          0.0.0.0:*                           124737/telegraf
    ```

### Steps to reproduce:

1. Add any plugin, that is listening on a port and restart Telegraf.
2. Run `telegraf --test` with the new config.
3. Test should fail with a message similar to this:

```
E! [agent] Service for [inputs.socket_listener] failed to start: listen udp 127.0.0.1:8094: bind: address already in use
```

I saw this happen with `inputs.socket_listener` and `inputs.syslog`.

### Expected behavior:

Either ignore any attempts to bind to a port during `--test` or check if it's already bound by `telegraf` before attempting anything (would require for `--test` to be run as `root` or same user as currently active agent).

### Actual behavior:

During `--test` Telegraf attempts to bind to sockets and fails if there's an already active agent with this config.

### Additional info:

My scenario is rather simple: I apply changes to Telegraf's config and run `--test` to ensure I haven't messed up, before I restart it to apply the changes. To my dismay, this fails if there's anything bound to those port, even Telegraf itself.

As far as I know Nginx tests only syntax and SSL key accessibility, Apache also checks root directories existence and they both don't check ports.

I think `--test` should be changed to not attempt to bind to ports, since this behavior makes it basically useless for automation purposes, or there should be added a different key, `--configtest`, which would only check if config is syntactically correct, but not run actual plugins.
