### ISSUE TITLE
Sql Server - VolumeSpace query not executed even if included

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7437]
### Relevant telegraf.conf:

```toml
# Read metrics from Microsoft SQL Server
[[inputs.sqlserver]]

  servers = [
    _myServer_
  ]
  query_version = 2
  include_query = [ 'VolumeSpace' ]
  # or just comment the whole include_query option
```

### System info:

Telegraf 1.14.2

### Steps to reproduce:

1. Run the Sql server plugin on an on-prem instance (SQL 2008 R2 or later versions)
2. even if you put the 'VolumeSpace' query in include_query it won't be gathered

### Expected behavior:

'VolumeSpace' query is executed and its measurement created

### Actual behavior:

no data is gathered, there are no errors in the log

### Additional info:

The query has been added in this release, but it worked _before the actual release_.
I still have an edited version of telegraf, made the 26th of April, its last commit (before my own) is "Document distinction between file and tail inputs (#7353)"  -"be1dc49ad9384e28a067a2c9134b9192100eca35" so by rolling back to that (included) you should be able to check what was changed.

here is a sample of the measurement output
```
sqlserver_disk_space,server_name=SRV-APPFFSDE02,sql_instance=SRV-APPFFSDE02:SQLFDE11TST,volume_mount_point=D: available_space_bytes=39450836992i,total_space_bytes=53550710784i,used_space_bytes=14099873792i 1588173917000000000
sqlserver_disk_space,server_name=SRV-APPFFSDE02,sql_instance=SRV-APPFFSDE02:SQLFDE11TST,volume_mount_point=L: available_space_bytes=102739542016i,total_space_bytes=107237801984i,used_space_bytes=4498259968i 1588173917000000000
```

**Update:**
After listening for executed query on the SQL Server instance, it turns out the query is not executed by telegraf.
