### ISSUE TITLE
HAProxy input : being able to set a timeout

### ISSUE THREAD

**Issue by odoucet** [influxdata/telegraf#7458]
## Feature Request

At least when using socket input for haproxy, if one socket is not responding, the whole capture failed. This can happen if we have one socket per core, and one core is at 100% CPU.

We would want a timeout to be set, to not wait on this socket but still be able to get stats from others.

### Proposal:

Syntax could be : 

### Relevant telegraf.conf:
```toml
[[inputs.haproxy]]
servers = ["socket:/var/run/haproxy-*.sock"]
timeout = 1s
```

### Current behavior:
If one socket is blocking, no stats is sent at all.

### Desired behavior:
At least send stats from socket that are responding.

### Use case: 
If one HAProxy instance (when forking) is not responding, it's critical to get stats from other processes for a sysadmin.
