### ISSUE TITLE
Tagpass doesn't work with multiple processors.renames

### ISSUE THREAD

**Issue by glisignoli** [influxdata/telegraf#7469]
### Relevant telegraf.conf:

```toml
[global_tags]

[agent]
  interval = "60s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[inputs.influxdb_listener]]
  service_address = ":8088"
  [inputs.influxdb_listener.tags]
    splunk_server = "yes"

[[inputs.influxdb_listener]]
  service_address = ":8086"
  [inputs.influxdb_listener.tags]
    influx_server = "yes"

[[processors.rename]]
  [[processors.rename.tagpass]]
     splunk_server = "yes"
  [[processors.rename.replace]]
    field = "usage_idle"
    dest = "idle"
  [[processors.rename.replace]]
    field = "usage_interrupt"
    dest = "interrupt"
  [[processors.rename.replace]]
    field = "usage_nice"
    dest = "nice"

[[outputs.file]]
  files = ["/var/telegraf/influx.out"]
  rotation_interval = "1m"
  rotation_max_size = "50MB"
  rotation_max_archives = 10
  data_format = "influx"
  [[outputs.file.tagpass]]
    influx_server = "yes"

[[outputs.http]]
 url = "http://123.123.123.123:8088/services/collector"
 data_format = "splunkmetric"
 splunkmetric_hec_routing = true
 splunkmetric_multimetric = false

 [outputs.http.headers]
  Content-Type = "application/json"
  Authorization = "Splunk some auth"
  X-Splunk-Request-Channel = "some auth"

 [outputs.http.tagpass]
   splunk_server = "yes"
```

### System info:

Telegraf 1.14.1 (git: HEAD 33dd867d)

Centos 7.7.1908

### Steps to reproduce:

See attached toml

### Expected behavior:

With the above configuration, I would expect only one input tag to be renamed. But it seems to apply to both.

### Actual behavior:

Looks like the tagpass is being ignored

### Additional info:

No errors indicated in telegraf logs.
