### ISSUE TITLE
procstat didn't collect correct processes

### ISSUE THREAD

**Issue by Karmenzind** [influxdata/telegraf#7471]
### Relevant telegraf.conf:

```toml
[global_tags]

[agent]
interval = "60s"
round_interval = true
metric_batch_size = 20
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "180s"
flush_jitter = "5s"
precision = ""
hostname = "ais-pc-109048"
omit_hostname = false

[outputs]
[[outputs.influxdb]]
url = "xxxx"
database = "telegraf"
precision = "s"

[[outputs.exec]]
command = [ "tee", "/tmp/_telegraf_data_watcher.log",]
data_format = "influx"

[inputs]
[[inputs.procstat]]
interval = "60s"
pattern = "activemq"
cmdline_tag = true

[processors]
[[processors.converter]]
namepass = [ "procstat",]

[processors.converter.tags]
string = [ "cmdline",]
                                                                                                                                                                            
```

### System info:

```
[root@localhost ~]# telegraf --version
Telegraf 1.14.1 (git: HEAD 33dd867d)

[root@localhost ~]# cat /proc/version
Linux version 3.10.0-957.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 8 23:39:32 UTC 2018
```

### Steps to reproduce:

1. Run telegraf service and check the data in influxdb.

### Expected behavior:

procstat will collect every running process by the pattern `activemq`

### Actual behavior:

![image](https://user-images.githubusercontent.com/17923071/81166091-bb2f7400-8fc5-11ea-92ab-701ddbfdb4bc.png)

As you can see, pid 58605 only showed at 10:07 and 10:08. But this process has been running for more than 300 hours.

![image](https://user-images.githubusercontent.com/17923071/81166213-ee720300-8fc5-11ea-9fe6-65ada3aa2e9e.png)

![image](https://user-images.githubusercontent.com/17923071/81168807-49a5f480-8fca-11ea-8abf-10886ff793e8.png)

I have executed `while true; do echo -ne $(pgrep -f activemq) '\n' >> somefile; sleep 3; done` for an hour and it turned out that 58605 showed in every line. So I guess there is something wrong with procstat.

### Additional info:

No error in `journactl -fu telegraf`.
