### ISSUE TITLE
MQTT/SSL not working and no explicit error

### ISSUE THREAD

**Issue by jlandercy** [influxdata/telegraf#7476]
My goal is to consume MQTT topic over internet (target is https://portal.thingstream.io) using SSL mode.

When I perform the operation using port 1883, it works like a charm but it is totally clear (credentials and messages are exposed).
When is switch to SSL (changing scheme and port as stated in https://github.com/influxdata/telegraf/blob/master/etc/telegraf.conf#L5833-L5835), nothing works but no error returning.

I spent the two last day trying to make MQTT over SSL working with Telegraf Integration without any success or reliable error to get on the right track.

The interesting point is when I use tcp://mqtt.thingstream.io:8883, the only log I have is:

```
2020-05-07T07:38:38Z D! [inputs.mqtt_consumer] Connecting [tcp://mqtt.thingstream.io:8883]
```

But when I switch to ssl://mqtt.thingstream.io:8883, I get an additional information:

```
2020-05-07T07:33:00Z D! [inputs.mqtt_consumer] Connecting [ssl://mqtt.thingstream.io:8883]
2020-05-07T07:33:10Z W! [agent] [inputs.mqtt_consumer] did not complete within its interval
```

If using the underlying IP to prevent DNS resolution, it cannot connect but the warning disappears:

```
2020-05-07T11:53:20Z D! [inputs.mqtt_consumer] Connecting [ssl://34.241.226.35:8883]
```

But did not help me that much to solve my problem.

I have tried a lot of settings combination, mainly:

  - Tuned Connection Timeout from 30s to 120s
  - Toggled SSL insecure skip verify
  - Changed scheme and port (tcp, ssl) x (1883, 8883)
  - Added target CA PEM full chain

No matter what I tried the problem is still there and the log does not show any explicit error.

### Relevant telegraf.conf:

This is a parametric config file, see docker-compose for Environment Variables:

```toml
# # Read metrics from MQTT topic(s)
[[inputs.mqtt_consumer]]
#   ## MQTT broker URLs to be used. The format should be scheme://host:port,
#   ## schema can be tcp, ssl, or ws.
    servers = ["${TELEGRAF_MQTT_INPUT_URI}"]
#
#   ## Topics that will be subscribed to.
    topics = [
      "${TELEGRAF_MQTT_INPUT_TOPIC}",
    ]
#
#   ## The message topic will be stored in a tag specified by this value.  If set
#   ## to the empty string no topic tag will be created.
#   # topic_tag = "topic"
#
#   ## QoS policy for messages
#   ##   0 = at most once
#   ##   1 = at least once
#   ##   2 = exactly once
#   ##
#   ## When using a QoS of 1 or 2, you should enable persistent_session to allow
#   ## resuming unacknowledged messages.
    qos = ${TELEGRAF_MQTT_INPUT_QOS}
#
#   ## Connection timeout for initial connection in seconds
    connection_timeout = "${TELEGRAF_MQTT_INPUT_CON_TIMEOUT}"
#
#   ## Maximum messages to read from the broker that have not been written by an
#   ## output.  For best throughput set based on the number of metrics within
#   ## each message and the size of the output's metric_batch_size.
#   ##
#   ## For example, if each message from the queue contains 10 metrics and the
#   ## output metric_batch_size is 1000, setting this to 100 will ensure that a
#   ## full batch is collected and the write is triggered immediately without
#   ## waiting until the next flush_interval.
    max_undelivered_messages = 5000
#
#   ## Persistent session disables clearing of the client session on connection.
#   ## In order for this option to work you must also set client_id to identify
#   ## the client.  To receive messages that arrived while the client is offline,
#   ## also set the qos option to 1 or 2 and don't forget to also set the QoS when
#   ## publishing.
#   # persistent_session = false
#
#   ## If unset, a random client ID will be generated.
    client_id = "${TELEGRAF_MQTT_INPUT_CLIENTID}"
#
#   ## Username and password to connect MQTT server.
    username = "${TELEGRAF_MQTT_INPUT_USERNAME}"
    password = "${TELEGRAF_MQTT_INPUT_PASSWORD}"
#
#   ## Optional TLS Config
    tls_ca = "${TELEGRAF_MQTT_INPUT_SSL_CA_KEY}"
#   # tls_cert = "/etc/telegraf/cert.pem"
#   # tls_key = "/etc/telegraf/key.pem"
#   ## Use TLS but skip chain & host verification
    insecure_skip_verify = ${TELEGRAF_MQTT_INPUT_SSL_SKIP_VERIFY}
#
#   ## Data format to consume.
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
    data_format = "${TELEGRAF_MQTT_INPUT_DATAFORMAT}"
```

### System info:
```bash
docker exec -it sc-db-telegraf /bin/bash

telegraf --version
Telegraf 1.14.2 (git: HEAD fb74eaf2)

uname -a
Linux scweb.hpc.ulb.ac.be 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 GNU/Linux
```
### Docker
```yaml
version: "3.6"
services:
  sc-db-telegraf:
    image: telegraf
    container_name: sc-db-telegraf
    depends_on:
      - sc-db-influx
    command: telegraf --debug
    env_file:
      # Defines:
      # TELEGRAF_USER=
      # TELEGRAF_PASS=
      - ../secrets/telegraf.env
      # Defines:
      # TELEGRAF_MQTT_INPUT_CLIENTID=
      # TELEGRAF_MQTT_INPUT_USERNAME=
      # TELEGRAF_MQTT_INPUT_PASSWORD=
      - ../secrets/mqttin.env
    environment:
      # https://hub.docker.com/_/telegraf
      - INFLUXDB_URL=https://sc-db-influx:8086
      - INFLUXDB_SKIP_TLS_VERIFY=true
      # MQTT Intergation:
      - TELEGRAF_MQTT_INPUT_URI=ssl://mqtt.thingstream.io:8883
      - TELEGRAF_MQTT_INPUT_QOS=0
      - TELEGRAF_MQTT_INPUT_TOPIC=test/sensors
      - TELEGRAF_MQTT_INPUT_DATAFORMAT=influx
    volumes:
      - ./sc-db-telegraf/config:/etc/telegraf
    networks:
      - sc-db-backend
```

### Steps to reproduce:

1. Try to connect a MQTT through the port 8883 but nothing occurs.

### Expected behavior:

A SSL connection should be initialized.

### Actual behavior:

Cannot connect the MQTT over SSL using the port 8883, no explicit error.
