### ISSUE TITLE
ZFS pool with IO values greater than INT64 

### ISSUE THREAD

**Issue by mulroony** [influxdata/telegraf#7502]
### Relevant telegraf.conf:

```toml
# Read metrics of ZFS from arcstats, zfetchstats, vdev_cache_stats, and pools
[[inputs.zfs]]
  ## ZFS kstat path. Ignored on FreeBSD
  ## If not specified, then default is:
  # kstatPath = "/proc/spl/kstat/zfs"

  ## By default, telegraf gather all zfs stats
  ## If not specified, then default is:
  # kstatMetrics = ["arcstats", "zfetchstats", "vdev_cache_stats"]
  ## For Linux, the default is:
  # kstatMetrics = ["abdstats", "arcstats", "dnodestats", "dbufcachestats",
  #   "dmu_tx", "fm", "vdev_mirror_stats", "zfetchstats", "zil"]
  ## By default, don't gather zpool stats
  poolMetrics = true
```

### System info:

kernel-3.10.0-1127.el7.x86_64
redhat-release-server-7.8-2.el7.x86_64
telegraf-1.14.2-1.x86_64
zfs-0.8.3-1.el7.x86_64

### Steps to reproduce:

1. Enable ZFS input module
2. Enable pool statistics
3. Have a pool with a statistic > INT64

### Expected behavior:

Be able to handle large integers, or catch the error and still collect other stats.

### Actual behavior:

[inputs.zfs] Error in plugin: strconv.ParseInt: parsing "15708770957432056996": value out of range

### Additional info:

```bash
cat /proc/spl/kstat/zfs/zdata/io
```

|                |               |          |          |                |                    |                |                |                  |                |    |    |
|----------------|---------------|----------|----------|----------------|--------------------|----------------|----------------|------------------|----------------|----|----|
|64              |3              |0x00      |1         |80              |1559694066680       |2814880137852481|                |                  |                |    |    |
|nread           |nwritten       |reads     |writes    |wtime           |wlentime            |wupdate         |rtime           |rlentime          |rupdate         |wcnt|rcnt|
|1991388487303168|281035540668416|2773546755|3790027449|1369155734128164|15708777337377171995|2814879891741232|1851453894946502|464328081809849506|2814879892282255|0   |0   |
