### ISSUE TITLE
postgresql_extensible: `withdbname` causes more problems than it solves

### ISSUE THREAD

**Issue by satyanash** [influxdata/telegraf#7505]
### Current behavior:
Currently the `inputs.postgresql_extensible.query` plugin has a boolean attribute `withdbname` which essentially allows users to specify if they'd like a predicate to be appended to their specified `sqlquery`. The behaviour when `withdbname` is set to `true` is as follows:

* If `databases` is set to `["foo", "bar"]` in `inputs.postgresql_extensible`, then append `IN ('foo', 'bar')` to the query.
* If `databases` is not set in `inputs.postgresql_extensible`, then append `IS NOT NULL` to the query.

There are multiple issues I see with this behaviour:
* It is not obvious for what kind of queries this behavior would be useful. None of the real-world examples use `withdbname` set to `true` in the docs.
* In the configuration, the attribute is called `databases`. However, it doesn't actually "switch" to those databases before running the specified query as one would expect.
* Finally, the `db` tag that is emitted also has a non-intuitive behaviour where it looks for a column called `datname` in the query result for the value. If such a column is not found, it defaults to `postgres` as the db. This can be completely incorrect information if the configured connection is not to the `postgres` database and does not have the `datname` column in the query result.

### Desired behavior:

Ideally, one should be able to specify one or more `inputs.postgresql_extensible` blocks for every database they want to connect to:
```
[[inputs.postgresql_extensible]]
  address="host=localhost dbname=postgres user=postgres"
  connection_name="conn1"

[[inputs.postgresql_extensible]]
  address="host=localhost dbname=foodb user=postgres"
  connection_name="conn2"
```

Once this is specified, for every `[[inputs.postgresql_extensible.query]]`, one should be able to specify a new attribute `with_connections` which specifies the connections this query should get executed for:

```
[[inputs.postgresql_extensible.query]]
  sqlquery="SELECT COUNT(*) AS active_connections FROM pg_stat_activity;"
  with_connections = ["conn1", "conn2"]
```

* It is immediately obvious which database is being connected to, what queries are being run where. There is no counter-intuitive behaviour of appending hard-coded predicates to SQL queries.
* The above query should result in the plugin emitting the metric `active_connections` twice. Once tagged with `db: foodb` and the second tagged with `db: postgres`, the values for `db` being extracted from the address string specified in the connection. This is much cleaner than simply assuming that all queries will have a `datname` column in the response or will always be run when connected to the `postgres` db.
* This also allows us to correctly override the existing `server` tag to be `conn1` instead of the entire clunky address string.

**Comment by satyanash** [comment]
There is a temporary workaround to ensure all emitted metrics for queries without `datname` as a column have the right value for the `db` tag.
Adding `current_database() AS datname` to the `SELECT` clause which causes the current code to read it and use it as the `db` tag for the emitted metrics..

**Comment by danielnelson** [comment]
We are planning to rewrite this plugin to match newly planned equivalents for mysql and sqlserver, but will probably go with a more basic configuration layout than you have proposed.  I want to defer as much behavior as possible to the query.  Here is what I currently have in my prototype:
```toml
[[inputs.postgresql_query]]
  servers = ["host=localhost user=postgres sslmode=disable"]

  ## list of keys from the dsn that will be added as tags
  server_tags = []

  max_lifetime = "0s"

  [[inputs.postgresql_query.query]]
    ## query can be a string or in a separate file
    query = "SELECT * FROM pg_stat_database"
    # script = "/etc/telegraf/query.sql"

    ## column in the results to use as the measurement
    measurement_column = ""

    ## columns in the results to add as tags
    tag_columns = []

    ## column in the results to add as a timestamp
    timestamp_column = ""
```

In order to query multiple servers and databases, I recommend using individual plugins except in the most basic cases.  This ensures that one slow database doesn't interfere with others connections.
