### ISSUE TITLE
prometheus output plugin metric name collide 

### ISSUE THREAD

**Issue by fredwangwang** [influxdata/telegraf#7509]
### Relevant telegraf.conf:

```toml
[[outputs.prometheus_client]]
  listen = ":10200"

[[inputs.prometheus]]
  urls = ["https://localhost:2379/metrics"]
  tls_cert = "/etcd/config/peer.crt"
  tls_key = "/etcd/config/peer.key"
  insecure_skip_verify = true
```

### System info:

Telegraf 1.14.2 (git: HEAD fb74eaf2)
Linux 0281ec69-3d61-4ea5-be58-147cdd1dd0eb 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce:

1. set up telegraf input to get metrics from etcd metrics endpoint
1. set up telegraf prometheus output to expose metrics 
1. `curl http://localhost:10200/metrics | grep process_resident_memory_bytes` a couple times

### Expected behavior:

telegraf consistently report `process_resident_memory_bytes` from etcd as well as from itself

### Actual behavior:

same metric name from two different sources seems collide with each other resulting inconsistent output depending on the timing of curl:
```
# curl -s http://localhost:10200/metrics | grep '^process_resident_memory_bytes'
process_resident_memory_bytes 6.6187264e+07
# curl -s http://localhost:10200/metrics | grep '^process_resident_memory_bytes'
process_resident_memory_bytes{host="0281ec69-3d61-4ea5-be58-147cdd1dd0eb",url="https://localhost:2379/metrics"} 1.80314112e+08
```

Not sure this is only related to prometheus output plugin or a broader issue
