### ISSUE TITLE
Cannot see rlimit metrics for darwin

### ISSUE THREAD

**Issue by godev-learner** [influxdata/telegraf#7511]
### Relevant telegraf.conf:

```toml
[[inputs.procstat]]
    fieldpass = ["realtime_priority", "rlimit_cpu_time_hard", "rlimit_cpu_time_soft", "rlimit_file_locks_hard", "rlimit_file_locks_soft", "rlimit_memory_data_hard", "rlimit_memory_data_soft", "rlimit_memory_locked_hard", "rlimit_memory_locked_soft", "rlimit_memory_rss_hard", "rlimit_memory_rss_soft", "rlimit_memory_stack_hard", "rlimit_memory_stack_soft", "rlimit_memory_vms_hard", "rlimit_memory_vms_soft", "rlimit_nice_priority_hard", "rlimit_nice_priority_soft", "rlimit_num_fds_hard", "rlimit_num_fds_soft", "rlimit_realtime_priority_hard", "rlimit_realtime_priority_soft", "rlimit_signals_pending_hard", "rlimit_signals_pending_soft", "signals_pending", "voluntary_context_switches", "write_bytes", "write_count", "pid_count"]
    pid_file = "/opt/telegraf/telegraf/var/test.pid"
    pid_finder = "native"
    [inputs.procstat.tags]
      metricPath = "metrics

```

### System info:
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

### Steps to reproduce:

1. create darwin build 
2. start the telegraf with the above toml file

### Expected behavior:

should emit metrics related to rlimit

### Actual behavior:

not showing metrics related to rlimit

### Additional info:

no error in the log files.
