### ISSUE TITLE
[[input.kapacitor]] Invalid character 'x' in string escape code

### ISSUE THREAD

**Issue by mertbakir** [influxdata/telegraf#7563]
I've tried to use kapacitor.input plugin and get the error below. Couldn't find a way to solve it. I think it's about the kapacitor's json output. I get the json output when manually typing the url into browser.

### Relevant telegraf.conf:

```toml
[[inputs.kapacitor]]
  urls = ["http://localhost:9092/kapacitor/v1/debug/vars"]
  timeout = "5s"
```

### Telegraf Log

```
E! [inputs.kapacitor] Error in plugin: [url=http://localhost:9092/kapacitor/v1/debug/vars]: invalid character 'x' in string escape code
```

### System info:

Centos 7.6
Telegraf: 14.2
Kapacitor: 1.5
