### ISSUE TITLE
E! [inputs.win_perf_counters] Error in plugin: No data to return.

### ISSUE THREAD

**Issue by PPerminov** [influxdata/telegraf#7571]
### Relevant telegraf.conf:

```toml
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 100000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "telegraf"

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    ObjectName = "ICMP"
    Counters = ["Messages/sec"]
    Measurement = "icmp"
```

### System info:
Telegraf: 1.14.2
OS: Windows Server 2019 Essentials (1809)

### Docker
-
### Steps to reproduce:
1. Install Telegraf
2. Run it in command line using config from above
3. See errors in console instead of metrics in InfluxDB

### Expected behavior:
I was expected to see the metrics

### Actual behavior:
I'm getting `E! [inputs.win_perf_counters] Error in plugin: No data to return.`

### Additional info:
Config at the top is a very simplified config. I have a lot of **objects** to monitor. Some of objects are working and some of them are not without any visible reason. When I'm trying to get that metrics through command `typeperf.exe "\ICMP\Messages/sec"` I''m getting next: 
```
"(PDH-CSV 4.0)","\\SERVER2\ICMP\Messages/sec"
"05/24/2020 13:26:47.040","3.992923"
"05/24/2020 13:26:48.041","3.994130"
"05/24/2020 13:26:49.042","3.995622"
"05/24/2020 13:26:50.044","3.992844"
```
I am successfully rebuilt counters with command `lodctr /r` and it does not helped.
