### ISSUE TITLE
metric_version = 2 setting of inputs.prometheus ignores namepass and namedrop 

### ISSUE THREAD

**Issue by x70b1** [influxdata/telegraf#7574]
I tried to read metrics from Grafana. It uses the prometheus exporter format. 

The `namedrop` and `namepass` option only seem to work with `metric_version = 1`.
When I set it to version 2, the filters are not applied.

### telegraf.conf:
```toml
[[inputs.prometheus]]
  urls = ["https://grafana.example.org/metrics"]
  username = "example"
  password = "XXXX"

  metric_version = 1
  namedrop = ["go_*", "http_request_duration_*"]

```

```
telegraf --version
Telegraf 1.14.3 (git: HEAD 1b35d6c2)
```
