### ISSUE TITLE
mysql - gather_global_variables  doesn't works -> no result

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#7578]
### Relevant telegraf.conf:
```toml
[[inputs.mysql]]
  servers = ["user:pass@tcp(127.0.0.1:3306)/"]
  gather_process_list = true
  gather_global_variables = true
```
**Tested also with metric_version = 2**

### System info:
- Telegraf 1.14.3
- Percona XtraDB Cluster 5.7

### Steps to reproduce:
Via MySQL:
```
$ echo "SHOW GLOBAL VARIABLES LIKE 'wsrep_cluster_name%' \G" | mysql -u user -p -h 127.0.0.1
Enter password:
*************************** 1. row ***************************
Variable_name: wsrep_cluster_name
        Value: cluster-1
```
All is OK

Via telegraf:
```
telegraf --config telegraf.conf --test | grep cluster_name
2020-05-25T13:09:34Z I! Starting Telegraf 1.14.3
```
-> no result
Same with boolean/int value... (example: wsrep_slave_threads)

If I check measurements in InfluxDB:
```
> SHOW MEASUREMENTS WITH MEASUREMENT =~ /mysql.*/
name: measurements
name
----
mysql
mysql_info_schema
mysql_users
```
No result concerning mysql_variables.

### Expected behavior:
Results via telegraf

### Actual behavior:
0 result via telegraf (but ok via MySQL)
