### ISSUE TITLE
Redis subscriber input plugin.

### ISSUE THREAD

**Issue by OrangeTux** [influxdata/telegraf#759]
It would be nice to have an input plugin which subscribes to one or more channels using Redis pubsub system, somewhat like the Kafka Consumer plugin. Applications can publish metrics on the selected channels. These metrics must be formatted according to configured [data format](https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md).

Sample configuration:  

```
[[input.redis_subscriber]]
  # The plugin can subscribe to multiple channels using patterns.
  channels = ["channel:*", "errors"]

  servers = ["tcp://localhost:6379"]
```

**Comment by sparrc** [comment]
:+1:, we should probably do [disque](https://github.com/antirez/disque) too while we're at it!

**Comment by jipperinbham** [comment]
:+1: to both! I may have some time today to hack on it.

**Comment by jipperinbham** [comment]
@sparrc would you want a new dir `redis_consumer`/`disque_consumer` for these or add new classes `redis_consumer.go` to the existing plugin dirs?

**Comment by sparrc** [comment]
redis_consumer & disque_consumer, thanks @jipperinbham

**Comment by darinfisher** [comment]
closing due to inactivity

**Comment by ssoroka** [comment]
I have a solution for this. Will post soon.

**Comment by ssoroka** [comment]
Ok so I wrote up something like this for an output plugin, but it'd be easy enough to make a subscriber input plugin using the same pattern. Here's what I did:

```toml
[agent]
  flush_interval = "1s"
  interval = "1s"
  omit_hostname = true

[[inputs.execd]]
  # make use of the existing count.rb example to create dummy metrics for testing.
  command = ["ruby", "plugins/inputs/execd/examples/count.rb"]
  signal = "none"

[[outputs.execd]]
  # make a custom output
  command = ["ruby", "plugins/outputs/execd/examples/redis/redis_influx.rb"]
  data_format = "influx"
```

Contents of redis_influx.rb output:
```ruby
#!/usr/bin/env ruby
#
# An example of funneling metrics to Redis pub/sub.
#
# to run this, you may need to:
#   gem install redis
#
require 'redis'

r = Redis.new(host: "127.0.0.1", port: 6379, db: 1)

loop do
  # example input: "counter_ruby count=0 1591741648101185000"
  line = STDIN.readline.chomp

  key = line.split(" ")[0]
  key = key.split(",")[0]
  r.publish(key, line)
end
```
