### ISSUE TITLE
[inputs.vsphere] strange time behaviour with unreachable nodes

### ISSUE THREAD

**Issue by adrianlzt** [influxdata/telegraf#7608]
### Relevant telegraf.conf:
Config without ``sys.uptime.latest``:
```toml
[[inputs.vsphere]]
  interval = "120s"
  vcenters = [ "https://10.2.1.2" ]
  username = "user"
  password = "admin"

  datastore_metric_include = [ "disk.capacity.latest" ]

  cluster_metric_include = []
  datacenter_metric_exclude = [ "*" ]
  insecure_skip_verify = true
  force_discover_on_init = true
  host_metric_exclude = ["*"] # Exclude realtime metrics
  vm_metric_exclude = ["*"] # Exclude realtime metrics

  max_query_metrics = 256
  collect_concurrency = 1

  taginclude = ["dcname", "dsname"]
```

Config with ``sys.uptime.latest``:
```toml
[[inputs.vsphere]]
  interval = "120s"
  vcenters = [ "https://10.2.1.2" ]
  username = "user"
  password = "admin"

  datastore_metric_include = [ "sys.uptime.latest", "disk.capacity.latest" ]

  cluster_metric_include = []
  datacenter_metric_exclude = [ "*" ]
  insecure_skip_verify = true
  force_discover_on_init = true
  host_metric_exclude = ["*"] # Exclude realtime metrics
  vm_metric_exclude = ["*"] # Exclude realtime metrics

  max_query_metrics = 256
  collect_concurrency = 1

  taginclude = ["dcname", "dsname"]
```

### System info:

Telegraf compiled from master commit 573f14460740327a129b28cd0d0298dda370673c

vSphere Client 6.5.0.13000

### Steps to reproduce:

1. Having a vSphere cluster with two unreachable nodes
2. Gather metrics from the datastore of those unreachable nodes using ``-test``

### Expected behavior:

Get the same metrics no matter which config is used.

### Actual behavior:

If the _without ``sys.uptime.latest``_ config is used, the metric received is dated on 2016:
```
>  vsphere_datastore_disk,dcname=XXX,dsname=YYY-localdatastore      capacity_latest=284950528i    1481407680000000000
```
If the _with ``sys.uptime.latest``_ config is used, the metric received is dated with the current time:

### Additional info:

``sys.uptime.latest`` should be not a valid metric for a datastore, but including it modifies the query sent to the vSphere API, modifying the timestamp.

Query sent without ``sys.uptime.latest``:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
  <Body>
    <QueryPerf xmlns="urn:vim25">
      <_this type="PerformanceManager">PerfMgr</_this>      
      <querySpec>
        <entity type="Datastore">datastore-231</entity>
        <startTime>2020-06-01T11:12:00Z</startTime>
        <endTime>2020-06-01T11:27:19.474351Z</endTime>
        <maxSample>10</maxSample>
        <metricId>
          <counterId>283</counterId>
          <instance/>
        </metricId>
        <intervalId>300</intervalId>
        <format>normal</format>
      </querySpec>
    </QueryPerf>
  </Body>
</Envelope>
```

Query sent with ``sys.uptime.latest``:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/">
  <Body>
    <QueryPerf xmlns="urn:vim25">
      <_this type="PerformanceManager">PerfMgr</_this>
      <querySpec>
        <entity type="Datastore">datastore-231</entity>
        <startTime>2020-06-01T11:07:40Z</startTime>
        <endTime>2020-06-01T11:22:43.702509Z</endTime>
        <maxSample>10</maxSample>
        <metricId>
          <counterId>155</counterId>
          <instance/>
        </metricId>
        <metricId>
          <counterId>283</counterId>
          <instance/>
        </metricId>
        <intervalId>300</intervalId>
        <format>normal</format>
      </querySpec>
    </QueryPerf>
  </Body>
</Envelope>
```
A new ``counterId`` has been added.

---

Response for the query sent without ``sys.uptime.latest``:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <QueryPerfResponse xmlns="urn:vim25">
      <returnval xsi:type="PerfEntityMetric">
        <entity type="Datastore">datastore-231</entity>
        <sampleInfo>
          <timestamp>2016-12-12T15:21:26.775999Z</timestamp>
          <interval>1800</interval>
        </sampleInfo>
        <value xsi:type="PerfMetricIntSeries">
          <id>
            <counterId>283</counterId>
            <instance/>
          </id>
          <value>2147221504</value>
        </value>
      </returnval>
    </QueryPerfResponse>
  </soapenv:Body>
</soapenv:Envelope>
```
Timestamp is from 2016

Response for the query sent with ``sys.uptime.latest``:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <soapenv:Body>
    <QueryPerfResponse xmlns="urn:vim25">
      <returnval xsi:type="PerfEntityMetric">
        <entity type="Datastore">datastore-231</entity>
        <sampleInfo>
          <timestamp>2020-06-01T11:20:00Z</timestamp>
          <interval>300</interval>
        </sampleInfo>
        <value xsi:type="PerfMetricIntSeries">
          <id>
            <counterId>283</counterId>
            <instance/>
          </id>
          <value>2147221504</value>
        </value>
      </returnval>
    </QueryPerfResponse>
  </soapenv:Body>
</soapenv:Envelope>
```
Timestamp is the current date.
