### ISSUE TITLE
JTI Plugin - cannot validate certificate because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by andrewckh** [influxdata/telegraf#7614]
Hi guys, I found that cannot use the plugin because of the server name cannot be override. Hence, I would like to ask what can i do. The ssl cert is generated by openssl in the server side, how can I override the name to prevent this problem (cannot validate ssl cert)? 

Thanks!

> [inputs.jti_openconfig_telemetry] Could not initiate login check for <IP_address>:50051: 
> rpc error: code = Unavailable desc = connection error: desc = 
> "transport: authentication handshake failed: 
> x509: cannot validate certificate for <IP_address> because it doesn't contain any IP SANs"

### Relevant telegraf.conf:

```toml
[[inputs.jti_openconfig_telemetry]]
  servers = ["<IP_address>:50051"]
  username = "admin"
  password = "admin"
  client_id = "telegraf"

  sample_frequency = "1000ms"

  sensors = [
   "/interfaces/",
   "collection /components/ /lldp",
  ]

  enable_tls = true
   tls_ca = "/etc/telegraf/certs/CA.crt"
   tls_cert = "/etc/telegraf/certs/client.crt"
   tls_key = "/etc/telegraf/certs/client.key"
   insecure_skip_verify = false

  retry_delay = "1000ms"
  str_as_tags = false

```

### Steps to reproduce:

1. ...
2. ...

### Actual behavior:

How can I override the server_name to prevent this problem for TLS validation?
