### ISSUE TITLE
Support additional metadata on memcached input

### ISSUE THREAD

**Issue by ddreier** [influxdata/telegraf#7621]
### Proposal:
Allow for additional metadata to be supplied along with the memcached host:port pairs.

### Current behavior:
Configuring the memcached input looks like this
```
[[inputs.memcached]]
  servers = ["localhost:11211", "localhost:11212", "localhost:11213"]
```

### Desired behavior:
Maybe it would look something like this?
```
[[inputs.memcached]]
  [memcached-1]
    address = "localhost:11211"
    key1 = "value1"
    key2 = "value2"
  [memcached-2]
    address = "localhost:11212"
    key1 = "value1"
    key2 = "value2"
```

### Use case: 
We run containerized memcached instances for various jobs in our HashiCorp Nomad clusters and collect metrics using Telegraf & Prometheus. There ends up being 10-20 small memcached containers per node, and the only way we have to differentiate them in the metrics is with the IP:Port pair. It would be very useful for us to have additional metadata per monitored memcached instance like the Nomad Job name and Allocation ID.

I'm happy to take a stab at implementing something, and would like some feedback on the best path forward.

Thanks!

**Comment by danielnelson** [comment]
You can add additional tags to any input plugin with the `tags` subtable, you will need to use multiple plugins to give them each their own tags.  Not sure if you need it, but it is also common to set tags like this with via environment variables.
```toml
[[inputs.memcached]]
  servers = ["localhost:11211"]
  [inputs.memcached.tags]
    key1 = "value1"
    key2 = "value2"

[[inputs.memcached]]
  servers = ["localhost:11212"]
  [inputs.memcached.tags]
    key1 = "value1"
    key2 = "value2"
    key3 = "${ALLOCTATION_ID}"
```
