### ISSUE TITLE
Redis input EOF error

### ISSUE THREAD

**Issue by PingLord** [influxdata/telegraf#7626]
### Relevant telegraf.conf:

```toml
[global_tags]
   service = "fservice"
   system = "redis_ipservice"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "redis.ipservice"
  omit_hostname = false
[[outputs.influxdb]]
   urls = ["http://10.13.13.130:8086"]
   database = "justadb"
   retention_policy = ""
   username = "influx"
   password = "password"
[[inputs.redis]]
    servers = ["tcp://10.13.13.193:6379"]
    password = "redispassword"

```

### System info:
Telegraf version : telegraf-1.14.3-1
Os : Centos 7.8.2003 
Kernel : 3.10.0-1127.el7.x86_64

### Steps to reproduce:

1. I've spinned up a centos 7 vm with a redis server installed from repos
2. I have installed telegraf from influxdb repo.
3. Started the service

### Expected behavior:

The expected behavior is receiving data to influxdb.

### Actual behavior:

The actual behavior is that the service is running but the redis plugin is in an error state.Checking telegraf logs i see the following :

`E! [inputs.redis] Error in plugin: EOF`

What is odd is that is working using the --test parameter :

`# sudo -H -u telegraf -s
bash-4.2$ cd $HOME
bash-4.2$ telegraf --config telegraf.conf --test
2020-06-03T17:28:12Z I! Starting Telegraf 1.14.3
redis_cmdstat,command=get,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=1757i,usec=6880i,usec_per_call=3.92 1591205292000000000
redis_cmdstat,command=incr,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=742i,usec=4552i,usec_per_call=6.13 1591205292000000000
redis_cmdstat,command=expire,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=564i,usec=1834i,usec_per_call=3.25 1591205292000000000
redis_cmdstat,command=keys,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=42i,usec=3991i,usec_per_call=95.02 1591205292000000000
redis_cmdstat,command=auth,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=615i,usec=2301i,usec_per_call=3.74 1591205292000000000
redis_cmdstat,command=flushall,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=1i,usec=10421i,usec_per_call=10421 1591205292000000000
redis_cmdstat,command=info,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=68i,usec=5661i,usec_per_call=83.25 1591205292000000000
redis_cmdstat,command=ttl,host=redis.ipservice,port=6379,replication_role=master,server=10.13.13.193,service=fservice,system=redis_ipservice calls=540i,usec=1395i,usec_per_call=2.58 1591205292000000000
`
Is there anything im doing wrong ? I tried also without authentication and same error.
