### ISSUE TITLE
SFlow Plugin does not support sampleType COUNTERSSAMPLE

### ISSUE THREAD

**Issue by mcolburn-jn** [influxdata/telegraf#7627]
### Relevant telegraf.conf:

```toml
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"


# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""

  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "sflowdata"

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout", "/tmp/metrics.out"]
  data_format = "influx"


###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################
[[inputs.sflow]]
  service_address = "udp://:6343"
  #read_buffer_size = "64KiB"
```

### System info:

CentOS Linux release 7.8.2003 (Core)
Telegraf 1.14.3 (git: HEAD 1b35d6c2)

### Steps to reproduce:

1. Configure Telegraf with Sflow input plugin
2. Start Service
3. No data seen by telegraf but packet captures and sflowtool do see it

### Expected behavior:

Expect to see sflow data in telegraf then exported to influxdb
### Actual behavior:
Telegraf not reporting any data being received

Telegraf starts normally and lists the sflow input plugin and listening
### Additional info:

[root@centos7-Center aio_sflow]# tcpdump -r sflowdump.pcap
reading from file sflowdump.pcap, link-type EN10MB (Ethernet)
12:32:22.589488 IP 172.30.37.178.63506 > 172.30.36.24.sflow: sFlowv5, IPv4 agent 172.30.37.178, agent-id 0, length 268
12:32:42.473693 IP 172.30.37.178.63506 > 172.30.36.24.sflow: sFlowv5, IPv4 agent 172.30.37.178, agent-id 0, length 268
12:33:02.606606 IP 172.30.37.178.63506 > 172.30.36.24.sflow: sFlowv5, IPv4 agent 172.30.37.178, agent-id 0, length 268

Sample output from sflowtool
[root@centos7-Center aio_sflow]# /usr/local/bin/sflowtool -p 6343
startDatagram =================================
datagramSourceIP 172.30.37.178
datagramSize 268
unixSecondsUTC 1591208882
localtime 2020-06-03T12:28:02-0600
datagramVersion 5
agentSubId 0
agent 172.30.37.178
packetSequenceNo 21667
sysUpTime 433649792
samplesInPacket 1
startSample ----------------------
sampleType_tag 0:2
sampleType COUNTERSSAMPLE
sampleSequenceNo 21668
sourceId 0:532
counterBlock_tag 0:1
ifIndex 532
networkType 6
ifSpeed 10000000000
ifDirection 1
ifStatus 3
ifInOctets 0
ifInUcastPkts 0
ifInMulticastPkts 0
ifInBroadcastPkts 0
ifInDiscards 0
ifInErrors 0
ifInUnknownProtos 0
ifOutOctets 51596772
ifOutUcastPkts 416103
ifOutMulticastPkts 0
ifOutBroadcastPkts 0
ifOutDiscards 0
ifOutErrors 0
ifPromiscuousMode 0
counterBlock_tag 0:2
dot3StatsAlignmentErrors 0
dot3StatsFCSErrors 0
dot3StatsSingleCollisionFrames 0
dot3StatsMultipleCollisionFrames 0
dot3StatsSQETestErrors 0
dot3StatsDeferredTransmissions 0
dot3StatsLateCollisions 0
dot3StatsExcessiveCollisions 0
dot3StatsInternalMacTransmitErrors 0
dot3StatsCarrierSenseErrors 0
dot3StatsFrameTooLongs 0
dot3StatsInternalMacReceiveErrors 0
dot3StatsSymbolErrors 0
counterBlock_tag 0:7
actorSystemID 00e567edac10
partnerSystemID 000000000000
attachedAggID 550
actorAdminPortState 0
actorOperPortState 71
partnerAdminPortState 0
partnerOperPortState 70
LACPDUsRx 0
markerPDUsRx 0
markerResponsePDUsRx 0
unknownRx 0
illegalRx 0
LACPDUsTx 416764
markerPDUsTx 0
markerResponsePDUsTx 0
endSample   ----------------------
endDatagram   =================================
startDatagram =================================
datagramSourceIP 172.30.37.178
datagramSize 268
unixSecondsUTC 1591208902
localtime 2020-06-03T12:28:22-0600
datagramVersion 5
agentSubId 0
agent 172.30.37.178
packetSequenceNo 21668
sysUpTime 433669728
samplesInPacket 1
startSample ----------------------
sampleType_tag 0:2
sampleType COUNTERSSAMPLE
sampleSequenceNo 21669
sourceId 0:532
counterBlock_tag 0:1
ifIndex 532
networkType 6
ifSpeed 10000000000
ifDirection 1
ifStatus 3
ifInOctets 0
ifInUcastPkts 0
ifInMulticastPkts 0
ifInBroadcastPkts 0
ifInDiscards 0
ifInErrors 0
ifInUnknownProtos 0
ifOutOctets 51599128
ifOutUcastPkts 416122
ifOutMulticastPkts 0
ifOutBroadcastPkts 0
ifOutDiscards 0
ifOutErrors 0
ifPromiscuousMode 0
counterBlock_tag 0:2
dot3StatsAlignmentErrors 0
dot3StatsFCSErrors 0
dot3StatsSingleCollisionFrames 0
dot3StatsMultipleCollisionFrames 0
dot3StatsSQETestErrors 0
dot3StatsDeferredTransmissions 0
dot3StatsLateCollisions 0
dot3StatsExcessiveCollisions 0
dot3StatsInternalMacTransmitErrors 0
dot3StatsCarrierSenseErrors 0
dot3StatsFrameTooLongs 0
dot3StatsInternalMacReceiveErrors 0
dot3StatsSymbolErrors 0
counterBlock_tag 0:7
actorSystemID 00e567edac10
partnerSystemID 000000000000
attachedAggID 550
actorAdminPortState 0
actorOperPortState 71
partnerAdminPortState 0
partnerOperPortState 70
LACPDUsRx 0
markerPDUsRx 0
markerResponsePDUsRx 0
unknownRx 0
illegalRx 0
LACPDUsTx 416793
markerPDUsTx 0
markerResponsePDUsTx 0
endSample   ----------------------
endDatagram   =================================
startDatagram =================================
datagramSourceIP 172.30.37.178
datagramSize 268
unixSecondsUTC 1591208922
localtime 2020-06-03T12:28:42-0600
datagramVersion 5
agentSubId 0
agent 172.30.37.178
packetSequenceNo 21669
sysUpTime 433689838
samplesInPacket 1
startSample ----------------------
sampleType_tag 0:2
sampleType COUNTERSSAMPLE
sampleSequenceNo 21670
sourceId 0:532
counterBlock_tag 0:1
ifIndex 532
networkType 6
ifSpeed 10000000000
ifDirection 1
ifStatus 3
ifInOctets 0
ifInUcastPkts 0
ifInMulticastPkts 0
ifInBroadcastPkts 0
ifInDiscards 0
ifInErrors 0
ifInUnknownProtos 0
ifOutOctets 51601608
ifOutUcastPkts 416142
ifOutMulticastPkts 0
ifOutBroadcastPkts 0
ifOutDiscards 0
ifOutErrors 0
ifPromiscuousMode 0
counterBlock_tag 0:2
dot3StatsAlignmentErrors 0
dot3StatsFCSErrors 0
dot3StatsSingleCollisionFrames 0
dot3StatsMultipleCollisionFrames 0
dot3StatsSQETestErrors 0
dot3StatsDeferredTransmissions 0
dot3StatsLateCollisions 0
dot3StatsExcessiveCollisions 0
dot3StatsInternalMacTransmitErrors 0
dot3StatsCarrierSenseErrors 0
dot3StatsFrameTooLongs 0
dot3StatsInternalMacReceiveErrors 0
dot3StatsSymbolErrors 0
counterBlock_tag 0:7
actorSystemID 00e567edac10
partnerSystemID 000000000000
attachedAggID 550
actorAdminPortState 0
actorOperPortState 71
partnerAdminPortState 0
partnerOperPortState 70
LACPDUsRx 0
markerPDUsRx 0
markerResponsePDUsRx 0
unknownRx 0
illegalRx 0
LACPDUsTx 416822
markerPDUsTx 0
markerResponsePDUsTx 0
endSample   ----------------------
endDatagram   =================================
startDatagram =================================
datagramSourceIP 172.30.37.178
datagramSize 268
unixSecondsUTC 1591208942
localtime 2020-06-03T12:29:02-0600
datagramVersion 5
agentSubId 0
agent 172.30.37.178
packetSequenceNo 21670
sysUpTime 433709776
samplesInPacket 1
startSample ----------------------
sampleType_tag 0:2
sampleType COUNTERSSAMPLE
sampleSequenceNo 21671
sourceId 0:532
counterBlock_tag 0:1
ifIndex 532
networkType 6
ifSpeed 10000000000
ifDirection 1
ifStatus 3
ifInOctets 0
ifInUcastPkts 0
ifInMulticastPkts 0
ifInBroadcastPkts 0
ifInDiscards 0
ifInErrors 0
ifInUnknownProtos 0
ifOutOctets 51603964
ifOutUcastPkts 416161
ifOutMulticastPkts 0
ifOutBroadcastPkts 0
ifOutDiscards 0
ifOutErrors 0
ifPromiscuousMode 0
counterBlock_tag 0:2
dot3StatsAlignmentErrors 0
dot3StatsFCSErrors 0
dot3StatsSingleCollisionFrames 0
dot3StatsMultipleCollisionFrames 0
dot3StatsSQETestErrors 0
dot3StatsDeferredTransmissions 0
dot3StatsLateCollisions 0
dot3StatsExcessiveCollisions 0
dot3StatsInternalMacTransmitErrors 0
dot3StatsCarrierSenseErrors 0
dot3StatsFrameTooLongs 0
dot3StatsInternalMacReceiveErrors 0
dot3StatsSymbolErrors 0
counterBlock_tag 0:7
actorSystemID 00e567edac10
partnerSystemID 000000000000
attachedAggID 550
actorAdminPortState 0
actorOperPortState 71
partnerAdminPortState 0
partnerOperPortState 70
LACPDUsRx 0
markerPDUsRx 0
markerResponsePDUsRx 0
unknownRx 0
illegalRx 0
LACPDUsTx 416822
markerPDUsTx 0
markerResponsePDUsTx 0
endSample   ----------------------
endDatagram   =================================
