### ISSUE TITLE
Memory leak in redis input plugin?

### ISSUE THREAD

**Issue by m4ce** [influxdata/telegraf#7637]
### Relevant telegraf.conf:

```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  debug = false
  quiet = true
  logfile = ""
  omit_hostname = false

[[inputs.redis]]
  servers = ["localhost:6379"]

[[inputs.disk]]
  mount_points = ["/var/lib/redis"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "overlay2"]

[[outputs.socket_writer]]
  address = "udp://influxdb:8094"
  data_format = "influx"
```

### System info:

Telegraf: 1.14.0
OS: CentOS 7, running under Docker

### Steps to reproduce:

Leave telegraf running and collecting metrics over time results in memory steadily increasing. It clearly shows a memory leak.

### Expected behavior:

Memory remains stable.

### Actual behavior:

Memory keeps increasing until OOM.

### Additional info:

![image](https://user-images.githubusercontent.com/1254063/83848660-1b6d1f00-a706-11ea-8058-e5a7d5dc28d0.png)

---

I wonder if the go-redis library the plugin uses is too old and suffers from memory leaks?
