### ISSUE TITLE
prometheus_client doesn't collect string value metrics

### ISSUE THREAD

**Issue by guoqiao** [influxdata/telegraf#7667]
### Relevant telegraf.conf:

```toml
[[outputs.prometheus_client]]
  listen = ":9103"
  metric_version = 2
  string_as_label = false

[[inputs.exec]]
commands = [
    "echo hello"
]
name_override = "echo_str"
data_format = "value"
data_type = "string"

[[inputs.exec]]
commands = [
    "echo 9999"
]
name_override = "echo_int"
data_format = "value"
data_type = "integer"
```

### System info:

Ubuntu 20.04 LTS
Telegraf 1.14.3 (git: HEAD 1b35d6c2)

### Steps to reproduce:

1. edit telegraf.conf as above
2. sudo service telegraf restart
3. test:
```
telegraf  --debug --input-filter exec --output-filter prometheus_client --test
> echo_str,host=t480 value="hello" 1591953166000000000
> echo_int,host=t480 value=9999i 1591953166000000000
```
here I can see both str and int metrics are working.
4. check prometheus_client output via url:
```
curl http://localhost:9103/metrics | grep echo
# HELP echo_int_value Telegraf collected metric
# TYPE echo_int_value untyped
echo_int_value{host="t480"} 9999
```
### Expected behavior:

In step 4, I should be able to see both int and str metrics.

### Actual behavior:

only the int metric is showing, str metric is gone.
It seems prometheus_client output will ignore string value metrics.
### Additional info:

Either string_as_label = false or ture, no difference.
