### ISSUE TITLE
Add option to create virtual registers in modbus input plugin

### ISSUE THREAD

**Issue by krishnacy** [influxdata/telegraf#7672]
## Feature Request

Add option to create virtual registers in modbus input plugin.

### Proposal:
Able to perform arithmetic/math/formula implementations and assign them to a  virtual register in the modbus input plugin. Ex: create a virtual register "energy"  - calculate energy ((power)*60))  from a field device register power(W). or calculate power from voltage & current.

### Current behavior:
no option for creating virtual registers

### Desired behavior:
Provide a filed called virtual registers (like holding registers, input registers) are something similar to that. so user can implement formulas/ perform calculations. 
### Use case: 
All virtual registers along with field registers can be stream as data flow into influxdb and influxdb can act as a historian.

**Comment by danielnelson** [comment]
We have a new Starlark processor in development that will allow for this: https://github.com/influxdata/telegraf/issues/7194

Starlark is a programming language that has a syntax similar to Python.  For example you could compute the power and add it as a field like:
```toml
[[processors.starlark]]
  namepass = ["mymeasurement"]
  source = '''
def apply(metric):
    I = metric.fields['current']
    V = metric.fields['voltage']
    metric.fields['power'] = I * V
    return metric
'''
```

I expect this processor will be in the [nightly builds](https://github.com/influxdata/telegraf#nightly-builds) in the next few days, and it should let you do a lot of custom computations on the input side.  Let's merge this issue with #7194.
