### ISSUE TITLE
Elasticsearch plugin stackdriver output issues

### ISSUE THREAD

**Issue by dpogorzelski** [influxdata/telegraf#7682]
### Relevant telegraf.conf:

```toml
[[inputs.elasticsearch]]
  cluster_health = true
  cluster_stats_only_from_master = true
  indices_include = []
  cluster_health_level = "cluster"
  cluster_stats = false
  node_stats = []

```

### System info:

Elastic 7.7
Telegraf: 1.14.4
Debian buster

### Expected behavior:

1. When setting node_stats = [] metrics like elasticsearch_* should not be sent
2. Any metric exported to stackdriver should have it's name URL formatted

### Actual behavior:

The above points 1,2 are not satisfied currently

### Additional info:

2020-06-15T08:41:35Z E! [agent] Error writing to outputs.stackdriver: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written: Field timeSeries[163].metric.type had an invalid value of "custom.googleapis.com/telegraf/elasticsearch_jvm/buffer_pools_mapped - 'non-volatile memory'_used_in_bytes": The metric type must be a URL-formatted string with a domain and non-empty path.: timeSeries[163]
