### ISSUE TITLE
systemd_unit Error in plugin: exec: "systemctl": executable file not found in $PATH

### ISSUE THREAD

**Issue by jbjuin** [influxdata/telegraf#7689]
### Relevant telegraf.conf:
```toml
[[inputs.systemd_units]]
  ## Set timeout for systemctl execution
  timeout = "10s"
  #
  ## Filter for a specific unit type, default is "service", other possible
  ## values are "socket", "target", "device", "mount", "automount", "swap",
  ## "timer", "path", "slice" and "scope ":
  unittype = "service"

```

### System info:
Telegraf version: 1.14.4
Ubuntu 18.04.3 LTS server

### Docker

docker-compose.yml

```yaml
version: '3'
services:
  telegraf:
    image: telegraf:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./telegraf.conf:/etc/telegraf/telegraf.conf"
```

### Steps to reproduce:

1. run `docker-compose up` with the previous docker-compose file on a ubuntu 18.04 server box

### Expected behavior:

Collect systemd service units state.

### Actual behavior:

Error message in telegraf docker logs: 

```
telegraf_1  | 2020-06-16T08:58:00Z E! [inputs.systemd_units] Error in plugin: exec: "systemctl": executable file not found in $PATH
```

### Additional info:

Any idea on that ?
