### ISSUE TITLE
The processors are no more initialized

### ISSUE THREAD

**Issue by essobedo** [influxdata/telegraf#7692]
While testing https://github.com/influxdata/telegraf/pull/7596 from the nightly build, I realized that the different processors that I use where no more initialized. After a deeper investigation, it seems to be regression due to [this commit](https://github.com/influxdata/telegraf/commit/741ea839d2cd014d91c18412bd5f6d2d3e25f4ec#diff-873f97b281f6488add08e5e7d8fd8868) which adds a wrapper on top of a `Processor` known as `StreamingProcessor` so when it tests if the processor is of type `Initializer`, it actually tests the wrapper instead of the wrapped processor such that the `Init` method is never called.

### Relevant telegraf.conf:

```toml
[[processors.converter]]
  order = 10
  [processors.converter.fields]
    string = ["result_code"]
```

### System info:

Nightly build
