### ISSUE TITLE
Support modifying the field key with data_format=value

### ISSUE THREAD

**Issue by danielnelson** [influxdata/telegraf#7702]
### Proposal:

Add a new option `value_field = "whatever"` that will set the field key used by the parser

### Current behavior:

Parser always uses `value` as the field key.

### Desired behavior:

Parse should allow user to provide an appropriately descriptive field key.

### Use case: 

We have experienced the same behavior with exec input plugin and _data format_:

```toml
[[inputs.exec]]
  commands = ["/bin/bash -c \"curl -s http://127.0.0.1:8080/tunnelcount | grep -Eo '[0-9]+'\""]
  data_format = "value"
  name_override = "tunnels_total"

# OUTPUTS

[[outputs.prometheus_client]]
  listen = ":9126"
  expiration_interval = "120s"
  collectors_exclude = ["gocollector", "process"]
  metric_version = 2
```
```bash
# It shows tunnels_total as metric name
telegraf --test --input-filter exec
```
However, the metric name in the endpoint is **tunnels_total_value**

Thank you

_Originally posted by @AntonioAlfrz in https://github.com/influxdata/telegraf/issues/7171#issuecomment-645520921_
