### ISSUE TITLE
Prometheus input to Influx Exporter not working with metric_version = 2

### ISSUE THREAD

**Issue by SoniCoder** [influxdata/telegraf#7711]
### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
  urls = ["http://host.docker.internal:8086"]
  database = "scraped_metrics"
  skip_database_creation = false

[[inputs.prometheus]]
  urls = ["http://host.docker.internal:8181/metrics"]
  metric_version = 2

```

### System info:

Telegraf 1.14.4 (git: HEAD c6fff6d8)
Insider Docker Container pulled from https://hub.docker.com/_/telegraf

### Steps to reproduce:

1. Expose these metrics on localhost:8181/metrics
```
# TYPE mnesia_transaction_duration_us histogram
# HELP mnesia_transaction_duration_us Mnesia txn execution time
mnesia_transaction_duration_us_bucket{le="20"} 129
mnesia_transaction_duration_us_bucket{le="40"} 4026
mnesia_transaction_duration_us_bucket{le="80"} 6682
mnesia_transaction_duration_us_bucket{le="160"} 7687
mnesia_transaction_duration_us_bucket{le="320"} 7977
mnesia_transaction_duration_us_bucket{le="640"} 8043
mnesia_transaction_duration_us_bucket{le="1280"} 8048
mnesia_transaction_duration_us_bucket{le="2560"} 8050
mnesia_transaction_duration_us_bucket{le="5120"} 8051
mnesia_transaction_duration_us_bucket{le="10240"} 8053
mnesia_transaction_duration_us_bucket{le="20480"} 8053
mnesia_transaction_duration_us_bucket{le="40960"} 8057
mnesia_transaction_duration_us_bucket{le="81920"} 8057
mnesia_transaction_duration_us_bucket{le="163840"} 8058
mnesia_transaction_duration_us_bucket{le="327680"} 8058
mnesia_transaction_duration_us_bucket{le="655360"} 8058
mnesia_transaction_duration_us_bucket{le="1310720"} 8058
mnesia_transaction_duration_us_bucket{le="2621440"} 8058
mnesia_transaction_duration_us_bucket{le="5242880"} 8058
mnesia_transaction_duration_us_bucket{le="+Inf"} 8058
mnesia_transaction_duration_us_count 8058
mnesia_transaction_duration_us_sum 769500
```
2. With given telegraf config run telegraf and influx on localhost.

### Expected behavior:

These metrics should be visible in influx database - scraped metrics

### Actual behavior:

With metric_version = 1, the metrics are being sent correctly but i desire the output of metric_version = 2 where the labels don't end up showing as columns in influx and stay as series and no output gets send if i use metric_version = 2

Thanks
