### ISSUE TITLE
tagdrop and fieldpass not working as expected with aggregator

### ISSUE THREAD

**Issue by vgudla** [influxdata/telegraf#7734]
### Relevant telegraf.conf:

```toml
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})


# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""  
  
  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  [outputs.influxdb.tagdrop]
    protocol = ["influx"]
  fielddrop = [
    "*_count",
    "*_min",
    "*_max",
    "*_mean",
    "*_s2",
    "*_stdev",
    "*_sum",
  ]
  ## The full HTTP or UDP URL for your InfluxDB instance.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  # urls = ["unix:///var/run/influxdb.sock"]
  # urls = ["udp://127.0.0.1:8089"]
  # urls = ["http://127.0.0.1:8086"]


# # Send telegraf metrics to file(s)
[[outputs.file]]
#   ## Files to write to, "stdout" is a specially handled file.
   files = ["stdout", "/tmp/metrics.out"]

#   ## Data format to output.
#   ## Each data format has its own unique set of configuration options, read
#   ## more about them here:
#   ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md
   data_format = "influx"
   [outputs.file.tagdrop]
     protocol = ["influx"]
   fieldpass = [
     "*_count",
     "*_min",
     "*_max",
     "*_mean",
     "*_s2",
     "*_stdev",
     "*_sum",
   ]


###############################################################################
#                            AGGREGATOR PLUGINS                               #
###############################################################################


# # Keep the aggregate basicstats of each metric passing through.
[[aggregators.basicstats]]
#   ## The period on which to flush & clear the aggregator.
   period = "20s"
#
#   ## If true, the original metric will be dropped by the
#   ## aggregator and will not get sent to the output plugins.
   drop_original = false
#
#   ## Configures which basic stats to push as fields
#   # stats = ["count", "min", "max", "mean", "stdev", "s2", "sum"]
   stats = ["count", "min", "sum", "max"]


###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

[[inputs.socket_listener]]
#   ## URL to listen on
    service_address = "tcp://:8094"
```

### Steps to reproduce:

1. Start telegraf with the above config
2. Send metrics to the socket listener as follows
```
$ nc localhost 8094
cpu_load_test,host=server01,region=us-west value=10 1593025931000000000
cpu_load_test,host=server01,region=us-west value=10 1593025953000000000
cpu_load_test,host=server01,region=us-west value=10 1593025960000000000
cpu_load_test,host=server01,region=us-west value=10 1593025965000000000
cpu_load_test,host=server01,region=us-west value=10 1593025987000000000
```

### Expected behavior:

Expected the following output in the file where the raw datapoints would get dropped because of the fieldpass filter in the outputs plugins. 
```
cpu_load_test,host=server01,region=us-west value_max=10,value_sum=10,value_count=1,value_min=10 1593025960000000000
cpu_load_test,host=server01,region=us-west value_count=2,value_min=10,value_max=10,value_sum=20 1593025980000000000
cpu_load_test,host=server01,region=us-west value_count=1,value_min=10,value_max=10,value_sum=10 1593026000000000000
```
### Actual behavior:

Noticed the following output in the file. The raw points also are emitted to the file output along with the aggregated points.
Note that when I remove the tagdrop filter, then this works correctly and the unaggregated points are dropped from the output
```
cpu_load_test,host=server01,region=us-west value=10 1593025931000000000
cpu_load_test,host=server01,region=us-west value_max=10,value_sum=10,value_count=1,value_min=10 1593025960000000000
cpu_load_test,host=server01,region=us-west value=10 1593025953000000000
cpu_load_test,host=server01,region=us-west value=10 1593025960000000000
cpu_load_test,host=server01,region=us-west value_count=2,value_min=10,value_max=10,value_sum=20 1593025980000000000
cpu_load_test,host=server01,region=us-west value=10 1593025965000000000
cpu_load_test,host=server01,region=us-west value=10 1593025987000000000
cpu_load_test,host=server01,region=us-west value_count=1,value_min=10,value_max=10,value_sum=10 1593026000000000000
```
