### ISSUE TITLE
net_response giving two timeseries on same metrics

### ISSUE THREAD

**Issue by Lawrence-Pet** [influxdata/telegraf#7757]
I'll apologize for my english in advance, thanks for trying to help! 

I've had an issue regarding multiple time series from telegraf to prometheus on the same metric whilst using the `net_response` plugin. 

```TOML
[[inputs.net_response]]

name_override = "net_TCP_test_connect"

protocol = "tcp"
address = "server:port"
## Set timeout
 timeout = "1s"
## Set read timeout (only used if expecting a response)
# read_timeout = "1s"
```

When i look at the metrics on my endpoint, every once in a while, I get a timeout from the TCP-request and the magic happens with two results at the same time: 
```
net_TCP_test_connect_response_time{host="hostserver",port="port",protocol="tcp",result="success",result_type="success",server="server"} 0.0034664
# HELP net_TCP_test_connect_result_code Telegraf collected metric
# TYPE net_TCP_test_connect_result_code untyped
net_TCP_test_connect_result_code{host="hostserver",port="port",protocol="tcp",result="success",result_type="success",server="server"} 0
net_TCP_test_connect_result_code{host="hostserver",port="port",protocol="tcp",result="timeout",result_type="timeout",server="server"} 1
```
I reckon this is not what is supposed to happen? 
Have i configured the plugin wrong? 

Thanks in advance

EDIT:
Its the two bottom responses giving `result="success"` and `result="timeout"` at the same time on the same stream.
