### ISSUE TITLE
Expanding existing `infiniband` input plugin to capture hardware counters

### ISSUE THREAD

**Issue by kerriwait** [influxdata/telegraf#7766]
### Proposal:
Extend the functionality of the existing `infiniband` input plugin to capture hardware counters. Mellanox, the hardware vendor, has already written the function in the upstream module, `rdmamap.GetRdmaSysfsHwStats(dev, portInt)`, so it's a matter of extending the `infiniband` plugin to call this function in addition to the existing one. 

More information on the hardware counters can be found here: https://community.mellanox.com/s/article/understanding-mlx5-linux-counters-and-status-parameters

We currently monitor these counters using `[[inputs.multifile]]`, but with up to 4 devices per host, and 20 counters per device, that's an extra ~80 config entries for us to manage. An example of this config is: 

```toml
[[inputs.multifile]]
  name_override="infiniband"
  base_dir="/sys/class/infiniband"

  [inputs.multifile.tags]
    port = "1"
    device = "mlx5_1"
    type = "hw_counters"

  [[inputs.multifile.file]]
    file = "mlx5_1/ports/1/hw_counters/duplicate_request"
    conversion = "int"
```

This change would reduce that long config to a handful of lines. 

### Current behavior:
The existing `infiniband` plugin captures one set of counters 

Example 
- `/sys/class/infiniband/mlx5_0/ports/1/counters/`

Relevant line: 
- https://github.com/influxdata/telegraf/blob/master/plugins/inputs/infiniband/infiniband_linux.go#L30 

Function in upstream Mellanox lib: 
- `rdmamap.GetRdmaSysfsStats(dev, portInt)`

### Desired behavior:
The `infiniband` plugin should capture two sets of counters 

Example
- `/sys/class/infiniband/mlx5_0/ports/1/counters/` 
- *and* `/sys/class/infiniband/mlx5_0/ports/1/hw_counters/`

Relevant lines: 
- https://github.com/Mellanox/rdmamap/blob/master/rdma_stats.go#L82
- https://github.com/Mellanox/rdmamap/blob/master/rdma_stats.go#L92

Functions in upstream Mellanox lib: 
- `rdmamap.GetRdmaSysfsStats(dev, portInt)`
- `rdmamap.GetRdmaSysfsHwStats(dev, portInt)`

### Use case: 
This minor change will be very beneficial for sites with Infiniband networking. 

We utilise telegraf for monitoring Lustre storage systems in our High Performance Computing (HPC) facility. I need to capture stats on the hardware counters to provide us with more granular debug information when troubleshooting complex networking issues. 

#### Post-script

I've had a quick go at this, but I'm new to go-lang and the structure of telegraf plugins, so I'm fairly certain this is not the correct approach. I'm happy to collaborate with a more experienced contributor to implement this properly. I think adding a conditional to the config file to allow sites to select which kind of counters to capture would be the best approach here. 

My working branch can be seen here:

https://github.com/influxdata/telegraf/compare/master...kerriwait:patch-infiniband
