### ISSUE TITLE
Json input data format issue: unable to extract string values (same with example in documentation)

### ISSUE THREAD

**Issue by anthosz** [influxdata/telegraf#7777]
Hello,

### Relevant telegraf.conf:

```toml
[[inputs.file]]
  files = ["/tmp/a"]
  data_format = "json"
  tag_keys = ["first"]
  json_string_fields = ["last"]
  json_query = ["obj.friends"]
```
/tmp/a available on https://docs.influxdata.com/telegraf/v1.14/data_formats/input/json/:
```json
{
    "obj": {
        "name": {"first": "Tom", "last": "Anderson"},
        "age":37,
        "children": ["Sara","Alex","Jack"],
        "fav.movie": "Deer Hunter",
        "friends": [
            {"first": "Dale", "last": "Murphy", "age": 44},
            {"first": "Roger", "last": "Craig", "age": 68},
            {"first": "Jane", "last": "Murphy", "age": 47}
        ]
    }
}
```

### System info:
RHEL 7 with telegraf 1.14.3

### Steps to reproduce:
1.Follow the procedure on https://docs.influxdata.com/telegraf/v1.14/data_formats/input/json/ (last step query with json_query

### Expected behavior:
Expected output:
file,first=Dale last="Murphy",age=44
file,first=Roger last="Craig",age=68
file,first=Jane last="Murphy",age=47

### Actual behavior:
file,host=XXXX obj_age=37,obj_friends_0_age=44,obj_friends_1_age=68,obj_friends_2_age=47 1593708403000000000

### Additional info:
I don't understand why the first name is ignored and last name converted to auto-incremental (int) value
