### ISSUE TITLE
IPMI Plugin: add support for Windows (IPMIUtil and IPMItool.exe Cygwin) + Bad Command with IPMIUtil

### ISSUE THREAD

**Issue by VegethB** [influxdata/telegraf#7798]
### Relevant telegraf.conf:

```toml
[[inputs.ipmi_sensor]]
  path = "C:\\Program Files\\Sourceforge\\ipmiutil\\ipmiutil.exe" # This is the default install location of ipmitool
  servers = ["USER:PASSWORD@lan(192.168.1.6)"]
  interval = "30s"
  timeout = "20s"
  metric_version = 2 # Usually 1 or 2
```
Obviously I changed the password and username of that command with the right ones.

### System info:

Windows Server 2019 Stable Latest, Telegraf for windows latest stable (2020-09-07), IPMI = iLo2 HP ProLiant DL380 G6 ; IPMI v2.

### Steps to reproduce:

1. Install IPMIUtil (version for windows of IPMITool, tested it works)
2. Config Telegraf to use IPMI and start from CMD to view console output.

### Expected behavior:

Execution of the task using the commands for "IPMIUtil.exe" since it is the only free and similar official alternative to IPMITools for Windows.

### Actual behavior:

![image](https://user-images.githubusercontent.com/17975351/87079554-81c5ef80-c226-11ea-843b-c7aaa7a87610.png)
Rightly use the command for linux IPMITool Instead of giving the possibility to use a custom command through an overide option that can be enabled.

### Additional info:
I spent 2 days building IPMITool for Windows via Cygwin. The output .exe version seems to work but only from an external pc (not the pc itself where IPMI resides) for this reason I ask to add the compatibility with IPMIUtil which works even if run by the host itself:
IPMITool.exe on host = 
![image](https://user-images.githubusercontent.com/17975351/87081255-4d076780-c229-11ea-9a35-8d3b52a1ab94.png) (I want to re-specify that this error occurs only if IPMITool.exe is run on the same machine where IPMI / iLo2 resides)

IPMIUtil.exe on host = 
![image](https://user-images.githubusercontent.com/17975351/87081450-b25b5880-c229-11ea-91e1-fa9e3945cf7c.png) It is not the command I want to use but it is an example. The end result is to get all the statistics (such as the current consumed by each device or fan status or hdd states etc.)

http://ipmiutil.sourceforge.net/man.htm
