### ISSUE TITLE
dns timeout in HTTP Response Plugin is not counted as DNS error

### ISSUE THREAD

**Issue by x70b1** [influxdata/telegraf#7800]
### Relevant telegraf.conf:
```toml

[[inputs.http_response]]
  urls = [
    "https://foobar.com"
  ]

  [inputs.http_response.tags]
    influxdb_database = "Availability"
```

### System info:

I use the latest stable release.

### Steps to reproduce:

1. Set an ip in `/etc/resolv.conf` that gives you a timeout or don't answer the request.

### Expected behavior:

I would expect an error code `5`, because this would show me that there is something wrong with dns. 
At the moment I get an result code `4`. But the description `timeout` would mean that the http server is not reachable. 

For me its just a bit confusing. If it is worth to think about this then use this issue. Otherwise just close it. :sunglasses:
