### ISSUE TITLE
Unsupported protocol scheme

### ISSUE THREAD

**Issue by ahoffer** [influxdata/telegraf#7829]
### Relevant telegraf.conf:

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = "syslog_test"
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "telegraf"


###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################

[[inputs.neptune_apex]]
  ## The Neptune Apex plugin reads the publicly available status.xml data from a local Apex.
  ## Measurements will be logged under "apex".

  ## The base URL of the local Apex(es). If you specify more than one server, they will
  ## be differentiated by the "source" tag.
  servers = [
    "192.168.0.209",
   # "http://apex.local",
  ]

  ## The response_timeout specifies how long to wait for a reply from the Apex.
  #response_timeout = "5s"
```

### System info:
See "Docker" section

### Docker
```yaml
version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - /projects/tig-tutorial/influxdb:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "6514:6514/udp"
    links:
      - influxdb
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
      - influxdb
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - /projects/tig-tutorial/grafana_data:/var/lib/grafana

```

### Steps to reproduce:

1.  docker-compose up

### Expected behavior:

No errors in Telegraf log.

### Actual behavior:

This log message keeps repeating every 10 seconds.

```
telegraf    | 2020-07-13T14:43:50Z E! [inputs.neptune_apex] Error in plugin: http GET failed: Get 192.168.0.209/cgi-bin/status.xml: unsupported protocol scheme ""
```

#### Apex Controller

`192.168.0.209` is the IP address of my Apex controller. 

#### wget
I can shell into the telegraf container:

`docker exec -it telegraf bash`

and I can get the status.xml file from the command line:

```
tmp# wget 192.168.0.209/cgi-bin/status.xml
--2020-07-13 15:53:26--  http://192.168.0.209/cgi-bin/status.xml
Connecting to 192.168.0.209:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/xml]
Saving to: 'status.xml'

status.xml   [ <=>   ]   3.11K  --.-KB/s    in 0.009s  

2020-07-13 15:53:26 (332 KB/s) - 'status.xml' saved [3187]
```

#### About Me

I have programming experience, but I have no experience with telegraf (or any part of the TIG stack)
