### ISSUE TITLE
Telegraf tail plugin does not parse json files  when following parameter is used: data_format=json  

### ISSUE THREAD

**Issue by davidgarciaMontreal** [influxdata/telegraf#7831]
### Relevant telegraf.conf:

```toml
[[inputs.tail]]
  files = ["input_tail.json"]
  data_format = "json"
  json_string_fields = ["key1", "key2", "key3"]
  json_name_key = "key1"
  from_beginning = true
```

### System info:

 uname -a
Linux node 3.10.0-957.46.1.el7.x86_64 #1 SMP Wed Jan 15 08:14:48 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

2020-07-13T22:35:10Z I! Starting Telegraf 1.14.5

![image](https://user-images.githubusercontent.com/10030411/87360227-a7f5d300-c537-11ea-97dd-9c3753ab7c20.png)

### Steps to reproduce:

1. use json file
input_tail.json 
```json
[{"key1":"value1","key2":"value2","key3":"value3avalue3b"},
{"key1":"value1","key2":"value2","key3":"value3avalue3b"}
]
```
2. run: telegraf --debug -config telegraf.conf -input-filter tail -test

### Expected behavior:

I should expect to see the following ouput, this is an example provided by the file input plugin:
```bash
2020-07-13T22:45:31Z I! Starting Telegraf 1.14.5
> value1,host=mtl-mgm01x key1="value1",key2="value2",key3="value3avalue3b" 1594680332000000000
> value1,host=mtl-mgm01x key1="value1",key2="value2",key3="value3avalue3b" 1594680332000000000
```

### Actual behavior:

No ouput in STDOUT.

**Comment by danielnelson** [comment]
When using `--test` with event-driven input such as the tail input you will want to specify an amount of time to wait in seconds by adding `--test-wait 5`.

However, this data cannot be parsed by the `json` data format (this would require a custom streaming JSON parser to be written), instead you should receive this error:
```
E! [inputs.tail] Malformed log line in "test.json": ["[{\"key1\":\"value1\",\"key2\":\"value2\",\"key3\":\"value3avalue3b\"},"]: unexpected end of JSON input
```

The parser will work with newline delimited objects::
```
{"key1":"value1","key2":"value2","key3":"value3avalue3b"}
{"key1":"value1","key2":"value2","key3":"value3avalue3b"}
```

**Comment by davidgarciaMontreal** [comment]
@danielnelson , I understand your comment. However, why would the json file work fine with the input file plugin? Try it. 
Are you saying that not the same parser is being used? it does not make sense.

```toml
[[inputs.file]]
  files = ["input_tail.json"]
  data_format = "json"
  json_string_fields = ["key1", "key2", "key3"]
  json_name_key = "key1"
  from_beginning = true
```
