### ISSUE TITLE
Inputs.win_perf_counters reports values from terminated processes

### ISSUE THREAD

**Issue by Lawrence-Pet** [influxdata/telegraf#7833]
Hi guys!
Been having an issue with telegraf reporting "frozen" values on processes that are terminated. I have in my metrics four processes running. Telegraf is reporting the CPU usage of each process in as expected. If i start up two more processes this works fine as well and updates nicely in my telegraf metrics. However after terminating said two processes they don't stop beeing reported in the metrics. They keep their last value and telegraf keeps reporting this. If Telegraf is restarted the extra metrics for the terminated processes are gone. 

### Relevant telegraf.conf:

```toml
[[inputs.win_perf_counters]]
  ## Settings:
  # PrintValid = false # Print All matching performance counters
  PreVistaSupport=false
  UseWildcardsExpansion=true

  [[inputs.win_perf_counters.object]]
    ObjectName = "Process"
    #Instances = ["chrome", "chrome#1", "chrome#2"]
    Instances = ["Test*"]
    Counters = [
      "% Processor Time"
    ]
    Measurement = "win_proc"
```

### System info:

Windows Server 2016
Telegraf 1.14.2

### Expected behavior:
```
win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts",objectname="Process"} 0.17734798789024353

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#1",objectname="Process"} 0.17734798789024353

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#2",objectname="Process"} 0.17734798789024353

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#3",objectname="Process"} 0.17734798789024353

```
Expect the metrics for terminated processes `#4` and `#5` do disappear for metrics and be reported as NULL values in my prometheus database.

### Actual behavior:

```
win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts",objectname="Process"} 0.17734798789024353

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#1",objectname="Process"} 0.17734798789024353

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#2",objectname="Process"} 0.17734798789024353

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#3",objectname="Process"} 0.17734798789024353

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#4",objectname="Process"} 6.96364720182376482

win_proc_Percent_Processor_Time{host="server",instance="Test.ServiceHosts#5",objectname="Process"} 3.25479878902543365

```
Processes `#4` and `#5` keeps being reported as last obtained value until Telegraf is restarted.
