### ISSUE TITLE
json parsing only getting first key of hashes

### ISSUE THREAD

**Issue by kallisti5** [influxdata/telegraf#7849]
### Relevant telegraf.conf:

```toml
[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  client_id = "telegraf-tnn-temp"
  topics = [
    "external/ttn/terarocket-temp-sensors/devices/tx-XXX-woods/up",
    "external/ttn/terarocket-temp-sensors/devices/tx-XXX-wellhouse/up",
  ]
  qos = 0
  username = "XXX"
  password = "XXX"
  data_format = "json"
  json_query = "payload_fields"
```

```
external/ttn/terarocket-temp-sensors/devices/tx-XXX-wellhouse/up {"app_id":"terarocket-temp-sensors","dev_id":"tx-XXX-wellhouse","hardware_serial":"XXXX","port":2,"counter":5922,"payload_raw":"zAEOIAF6AX//f/8=","payload_fields":{"BatV":3.073,"Hum_SHT":"37.8","TempC_DS":"327.67","TempC_SHT":"36.16"},"metadata":{"time":"2020-07-16T23:44:05.909063943Z","frequency":904.1,"modulation":"LORA","data_rate":"SF7BW125","airtime":61696000,"coding_rate":"4/5","gateways":[{"gtw_id":"eui-XXX","timestamp":923877299,"time":"2020-07-16T23:44:05.934Z","channel":1,"rssi":-85,"snr":9.2,"rf_chain":0}],"latitude":1.1,"longitude":-1.1,"location_source":"registry"}}
```

### System info:

1.12.2

### Expected behavior:

These values to show up in influxdb:
```{"BatV":3.073,"Hum_SHT":"37.8","TempC_DS":"327.67","TempC_SHT":"36.16"}```

### Actual behavior:

Only BatV shows up as a field in influxdb.

InfluxDB:
```
select * from mqtt_consumer where topic = 'external/ttn/terarocket-temp-sensors/devices/tx-XXX-wellhouse/up' LIMIT 1;
name: mqtt_consumer
time                BatV  host                   topic                                                             value
----                ----  ----                   -----                                                             -----
1594931046094279732 3.073 iot.dal1.terarocket.io external/ttn/terarocket-temp-sensors/devices/tx-XXX-wellhouse/up 
```
