### ISSUE TITLE
Input execd - "restart_delay" config is ignored

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#7858]
In the execd input plugin, the configuration parameter _restart_delay_ is not used, and a fixed value of 10 seconds is used.

see row below:
https://github.com/influxdata/telegraf/blob/ef262b137275e63103ef83770c9bcf7388f0eeb7/plugins/inputs/execd/execd.go#L159

**Comment by ssoroka** [comment]
This is just the default for the plugin, and should be set from config after creation. Missing toml tags might be problematic. Are you seeing any problems changing the default?

**Comment by Trovalo** [comment]
I've tried with several values of _restart_delay_ (by default set to 10s), but the value gets ignored and the executable restarts after 10s.
I had a look in the code, and personally I didn't find any reference to the value defined in the telegraf configuration (but I'm not so good at GO yet) 

A sample conf section
```toml
[[inputs.execd]]

  ## use bat file
  command = ['C:\Users\gluisotto\Desktop\test_Telegraf\StartPrintrandom.bat']

  signal = "none"
  restart_delay = "25s"
  data_format = "influx"
```
In case of error, this is what I get in the log:
```
2020-07-20T14:52:21Z I! Process [C:\Users\gluisotto\Desktop\test_Telegraf\StartPrintrandom.bat] terminated: %!s(<nil>)
2020-07-20T14:52:21Z I! Restarting in 10s...
```
