### ISSUE TITLE
Tailing files stopped working since v1.15

### ISSUE THREAD

**Issue by Tenzer** [influxdata/telegraf#7880]
I've upgraded from Telegraf v1.14 to v1.15.1 in our systems today and found that it broke one of our use cases.

We are tailing some log-like files from a service, the service outputs lines in InfluxDB format which is then read by Telegraf and passed on to our metrics system. I made a minimal example of this:

`telegraf.conf`
```toml
[[inputs.tail]]
  files = ["clock.log"]
  data_format = "influx"

[[processors.printer]]

[[outputs.discard]]
```

I've then run this loop in bash in order to write to `clock.log`:
```bash
while :; do
    echo "clock now=$(date +%s)"
    sleep 1
done >> clock.log
```

Using that example I was able to use Git bisect which pointed at this stopping working when #7792 was merged.

I've tried to set `character_encoding` in the config file to both an empty string and "utf-8" but it doesn't seem to make any difference, so I think the problem might more deeply rooted.
