### ISSUE TITLE
Inconsistant units for SQL Server server_memory

### ISSUE THREAD

**Issue by Cova** [influxdata/telegraf#7888]
### Relevant telegraf.conf:
```toml
[[inputs.sqlserver]]
  servers = [
    "Server=pshrdbdev3.b1b30c58f8d7.database.windows.net;Port=1433;User Id=telegraf;Password=<redacted>;app name=telegraf;log=1;",
    "Server=pshrdb.<redacted>;Port=1433;User Id=telegraf;Password=<redacted>;app name=telegraf;log=1;",
  ]
```

### System info:

telegraf:1.14 docker image running in an Azure AKS cluster.

### Steps to reproduce:

Query multiple SQL Servers, including both cloud-based (first server above is EngnieEdition 8 - Azure SQL Managed Instance) and on-prem (second above is SQL Enterprise x64).
### Expected behavior:

Pick a unit, stick with it.

### Actual behavior:

I cannot build a single dashboard that accurately shows the total memory allocated to both instance types, as the Managed Instance reports in Megabytes, while the SQL Enterprise reports in Kilobytes

### Additional info:

The units are obvious from the SQL queries used in the input plugin.  I would expect the plugin to convert as required to always give a consistant output regardless of what kind of SQL is being queried.

https://github.com/influxdata/telegraf/blob/af1e8ac63c5ed83b7d2a7c3e89a276f4711da7fe/plugins/inputs/sqlserver/sqlserver.go#L513

https://github.com/influxdata/telegraf/blob/af1e8ac63c5ed83b7d2a7c3e89a276f4711da7fe/plugins/inputs/sqlserver/sqlserver.go#L543

https://github.com/influxdata/telegraf/blob/af1e8ac63c5ed83b7d2a7c3e89a276f4711da7fe/plugins/inputs/sqlserver/sqlserver.go#L582
