### ISSUE TITLE
Empty variable on tags using environement variable send the defined variable instead of not sending the tag

### ISSUE THREAD

**Issue by Tonic8** [influxdata/telegraf#7903]
### Relevant telegraf.conf:

```toml
[global_tags]
    Application="Test"
    ClassID = "${classid}"
    Country = "${country}"
    Datacenter = "Jupiter"
    EmptyTag = ""
```

### System info:

Telegraf 1.15.1
Windows 10

### Steps to reproduce:

1. setup any tag with an environment variable
2. do NOT set the environment variable
3. start Telegraf
4. it's sending the data with tag     ClassID = "${classid}", instead of not using it/sending it
example line using the telegraf.conf at the beginning of the message

`ctx_broker,Application=Test,ClassID=PROD,Country=${country},Datacenter=Jupiter,host=machine1 networkLatency=26`

### Expected behavior:

if Tag is not set, it should not send it, on telegraf.conf globatags i tested an empty tag, and the tag is not sent.

### Actual behavior:

 but if the tag is configured to use an environment variable, it will send if the environement varaible configuration
tag defined Country = "${country}"
tag sent      Country=${country}

### Additional info:

with an heterogenous environement, is to avoid the multiplication of telegraf.conf when setting the tags...
maybe is by design, but if you set an empty tag is not sent.

many thanks for the wonderfull work done, i love telegraf!
