### ISSUE TITLE
Telegraf unable to start without existing log file

### ISSUE THREAD

**Issue by jmcarless** [influxdata/telegraf#7905]
### Relevant telegraf.conf:
```toml
[agent]
flush_interval = "10s"
flush_jitter = "5s"
interval = "10s"
metric_buffer_limit = 20000
round_interval = true
```

### System info:
Telegraf version 1.15.1, Amazon Linux 2018.03

### Steps to reproduce:

1. Install telegraf version 1.15.1
2. `/var/log/telegraf` directory exists, but has no files
3. Start telegraf

### Expected behavior:

Telegraf starts, and writes logs to `/var/log/telegraf/telegraf.log`

### Actual behavior:

```
sudo service telegraf start
Starting the process telegraf [ OK ]
sh: /var/log/telegraf/telegraf.log: Permission denied
```
Telegraf does not start

### Additional info:

When rolling back our version to 14.5.1, telgraf starts correctly and logs to `/var/log/telegraf/telegraf.log`.
Alternatively, if I manually create a blank log file named `/var/log/telegraf/telegraf.log` and chown it to telegraf, then version 1.15.1 will start correctly.

This unexpectedly broke metrics reporting for us today on new hosts.
