### ISSUE TITLE
Issue with Docker log plugin

### ISSUE THREAD

**Issue by karkandcoypp** [influxdata/telegraf#7924]
Hello everyone!

I have issue with telegraf plugin https://github.com/influxdata/telegraf/tree/master/plugins/inputs/docker_log.
After restartnig docker Service container (in swarm cluster) logs do not arrive in InfluxDB.
I see logs in Grafana that docker service Stopped, but don't see the service Started.

```toml
[global_tags]
environment="swarm"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "${HOSTNAME_TELEGRAF}" 
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["{{ influxdbUrl }}"]
  database = "{{ influxdbName }}"
  retention_policy = ""
  write_consistency = "any"
  timeout = "5s"
  username = "{{ influxdb_prod_login }}"
  password = "{{ influxdb_prod_password }}"
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "aufs", "squashfs"]
  mount_points = ["/"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_names = []
  timeout = "5s"
  perdevice = true
  total = false
  docker_label_include = []
  docker_label_exclude = []
[[inputs.net]]
[[inputs.docker_log]]
  endpoint = "unix:///var/run/docker.sock"
  source_tag = false
```

Parameter timeout = 1s in [[inputs.docker_log]] don't help.
