### ISSUE TITLE
vsphere input - [inputs.vsphere] Unable to find metric name for id %d. Skipping!411

### ISSUE THREAD

**Issue by jstiops** [influxdata/telegraf#7940]
### Relevant telegraf.conf:

```toml
[[inputs.vsphere]]
   vcenters = [ "https://hostname/sdk" ]
   username = ""
   password = ""
     
  interval = "60s"
  insecure_skip_verify = true
  force_discover_on_init = true

  # Exclude all historical metrics
  datastore_metric_exclude = ["*"]
  cluster_metric_exclude = ["*"]
  datacenter_metric_exclude = ["*"]


  #historical stats
 [[inputs.vsphere]]
   vcenters = [ "https://hostname/sdk" ]
   username = ""
   password = ""
   
  interval = "300s"
  insecure_skip_verify = true
  force_discover_on_init = true
  object_discovery_interval = "600s"
  host_metric_exclude = ["*"] # Exclude realtime metrics
  vm_metric_exclude = ["*"] # Exclude realtime metrics

  use_int_samples = true

```

### System info:

using Telegraf v1.15.2 on a Windows 2012 R2 x64 OS connecting to a vCenter 6.7 u3 (latest patches, 6.7.0.44000).
vcenter contains a single cluster with 3 hosts on ESXi 6.7 EP 09 (build 13644319). 

### Problem:

telegraf started to produce these errors in the telegraf.log upon every interval of the realtime stats collection. I have no idea why this started. I did some troubleshooting and checked my grafana setup and saw the graphs stopped displaying data in graphs that filter on clustername. There was no clustername in my influxdb measurement anymore. When i stopped filtering on clustername, the graph showed data. It seems the clustername stopped being send to output influxdb as a tag at some point.

Other stats seem to still get pushed out to influxdb.

```toml
2020-08-05T07:28:00Z I! [inputs.vsphere] Unable to find metric name for id %d. Skipping!411
2020-08-05T07:28:00Z I! [inputs.vsphere] Unable to find metric name for id %d. Skipping!411
2020-08-05T07:28:00Z I! [inputs.vsphere] Unable to find metric name for id %d. Skipping!411
2020-08-05T07:28:00Z I! [inputs.vsphere] Unable to find metric name for id %d. Skipping!411
2020-08-05T07:28:00Z I! [inputs.vsphere] Unable to find metric name for id %d. Skipping!411

```
