### ISSUE TITLE
Azure Monitor - Alerts on top of disk input plugin not available for some metrics

### ISSUE THREAD

**Issue by jangelfdez** [influxdata/telegraf#7947]
### Relevant telegraf.conf:

```toml

###############################################################################
#                            OUTPUT PLUGINS                                                                                                             #
###############################################################################

# Send aggregate metrics to Azure Monitor
[[outputs.azure_monitor]]
  ## Timeout for HTTP writes.
  # timeout = "20s"

  ## Set the namespace prefix, defaults to "Telegraf/<input-name>".
  # namespace_prefix = "Telegraf/"

  ## Azure Monitor doesn't have a string value type, so convert string
  ## fields to dimensions (a.k.a. tags) if enabled. Azure Monitor allows
  ## a maximum of 10 dimensions so Telegraf will only send the first 10
  ## alphanumeric dimensions.
  # strings_as_dimensions = false

  ## Both region and resource_id must be set or be available via the
  ## Instance Metadata service on Azure Virtual Machines.
  #
  ## Azure Region to publish metrics against.
  ##   ex: region = "southcentralus"
  # region = ""
  #
  ## The Azure Resource ID against which metric will be logged, e.g.
  ##   ex: resource_id = "/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Compute/virtualMachines/<vm_name>"
  # resource_id = ""

###############################################################################
#                            INPUT PLUGINS                                                                                                                 #
###############################################################################

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]

  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]


```
### System info:
Linux test 5.3.0-1034-azure#3518.04.1-Ubuntu SMP Mon Jul 13 12:54:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
telegraf_1.8.0~rc1-1_amd64.deb

### Steps to reproduce:

1. Configure telegraf to export disk metrics to Azure Monitor
2. Check the "Metrics" section inside the virtual machine and review that all of them are available
![image](https://user-images.githubusercontent.com/992009/89524234-80b3be00-d7e4-11ea-9ee5-4871e46d98b9.png)

3. Try to create an alert on the metric and only some of them shows as an option
![image](https://user-images.githubusercontent.com/992009/89524329-a8a32180-d7e4-11ea-8509-69aaef2b0a13.png)

### Expected behavior:

I would expect that *Free*, *Total*, *used*, etc. would be available to generate a new alert. Something similar to what **mem** or **cpu** plugins allow.

### Actual behavior:

Those metrics are missing

### Additional info:

N/A
