### ISSUE TITLE
inputs.tail is not releasing file descriptor when file is deleted

### ISSUE THREAD

**Issue by davidgarciaMontreal** [influxdata/telegraf#7959]
### Relevant telegraf.conf:

```toml
[[inputs.tail]]
  ## files to tail.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   "/var/log/**.log"  -> recursively find all .log files in /var/log
  ##   "/var/log/*/*.log" -> find all .log files with a parent dir in /var/log
  ##   "/var/log/apache.log" -> just tail the apache log file
  ##
  ## See https://github.com/gobwas/glob for more examples
  ##
  files = ["/tmp/metrics/*.out"]
##   ## Read file from beginning.
   from_beginning = true
```

### System info:
centos7 telegraf 1.15.2 

```bash
[vagrant@localhost telegraf]$ ./telegraf version
Telegraf 1.15.2 (git: HEAD cd037b49)
```
### Steps to reproduce:

1. use configuration as provided
2. ./telegraf -config telegraf.conf
3.  run following command:
```bash 
mkdir -p /tmp/metrics &&  echo 'example,tag1=a,tag2=b i=42i,j=43i,k=44i'  >> /tmp/metrics/logs_00.out
```
4. wait 60 seconds
5. remove file:
```bash
rm -rf /tmp/metrics/logs_00.out
```
6. check file descriptor is not released:
```bash
[vagrant@localhost telegraf]$ lsof | grep metrics | grep logs_00
telegraf  18104              vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18105        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18106        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18107        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18108        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18109        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18110        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18112        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18113        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18114        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)
telegraf  18104 18115        vagrant    8r      REG                8,1        40  12436180 /tmp/metrics/logs_00.out (deleted)

```

### Expected behavior:

It should release all deleted file descriptors. 

### Actual behavior:
It doesn't release the file descriptors.
### Additional info:
This is affecting functionality as when too many files are created and deleted telegraf stops working as it cannot open more files due to running out of file descriptors.
