### ISSUE TITLE
internal_write errors never incremented or logged

### ISSUE THREAD

**Issue by yangkev** [influxdata/telegraf#7964]
### Relevant telegraf.conf:

`bug.conf`:
```toml
[global_tags]


# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"

  ## Log at debug level.
  debug = true
  ## Log only error level messages.
  quiet = false

# Collect statistics about itself
[[inputs.internal]]
  ## If true, collect telegraf memory stats.
  collect_memstats = false

[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout"]

```

### System info:

Code: https://github.com/influxdata/telegraf/blob/a6c8f5be13e17e6a62fd2b2b274879cdc1bf76cc/models/running_output.go#L70-L74
SHA: a6c8f5be13e17e6a62fd2b2b274879cdc1bf76cc

### Steps to reproduce:

To reproduce reliably:
1. Modify https://github.com/influxdata/telegraf/blob/a6c8f5be13e17e6a62fd2b2b274879cdc1bf76cc/plugins/outputs/file/file.go#L124-L127 to always return `error` (use the patch below)
2. `./telegraf --config bug.conf --debug`

### Expected behavior:

When an output experiences a write error, then the `internal_write.errors` metric should be incremented.
```
internal_write,host=kyang-mbp151,output=file,version=unknown metrics_added=0i,metrics_written=0i,metrics_dropped=0i,buffer_size=0i,buffer_limit=10000i,metrics_filtered=0i,write_time_ns=0i,errors=1 1597091220000000000
```

### Actual behavior:

I see that the `internal_write.errors` metric is still 0 after going through a few write cycles
```
...
internal_write,host=kyang-mbp151,output=file,version=unknown metrics_added=0i,metrics_written=0i,metrics_dropped=0i,buffer_size=0i,buffer_limit=10000i,metrics_filtered=0i,write_time_ns=0i,errors=0i 1597091220000000000
...
```
### Additional info:

To deliberately cause the `file` `output` `Write()` to error, `git apply` this patch:
```
From e6e036e8ee1b911c548f38ccbf659ae59fe72c2a Mon Sep 17 00:00:00 2001
From: Kevin Yang <16491459+yangkev@users.noreply.github.com>
Date: Mon, 10 Aug 2020 17:01:33 -0400
Subject: [PATCH] error patch

---
 plugins/outputs/file/file.go | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/plugins/outputs/file/file.go b/plugins/outputs/file/file.go
index 3798f107..9d7ec09a 100644
--- a/plugins/outputs/file/file.go
+++ b/plugins/outputs/file/file.go
@@ -128,6 +128,9 @@ func (f *File) Write(metrics []telegraf.Metric) error {
 		}
 	}
 
+	if writeErr == nil {
+		return fmt.Errorf("deliberate write error")
+	}
 	return writeErr
 }
 
-- 
2.20.1 (Apple Git-117)

```
