### ISSUE TITLE
Better way to retrieve snmp setting for ifName plugin

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#8010]
## Feature Request

Opening a feature request kicks off a discussion.
As discussed in https://github.com/influxdata/telegraf/pull/7763#issuecomment-676801651

### Proposal:

Make it possible some way to retrieve the community string (and other snmp config) directly from the config set for the `snmp` or `sflow` input.

### Current behavior:

Community string (and other snmp config) needs to be configured in `ifName` plugin as well

### Desired behavior:

Let `ifName` plugin figure out from which plugin the metric comes and use the config from that plugin if possible.

### Use case: 

Usually each device (or group of devices) has its own specific community string and that would make a huge config even more huge.

**Comment by Hipska** [comment]
Correct, I think it could be possible if a metric could have a reference to the input plugin where it originated from somehow. What do you think?

**Comment by Hipska** [comment]
Easier to implement would be the community string could come from a tag.

**Comment by Hipska** [comment]
@powersj What if I added an option to `inputs.snmp` which adds the required client config parameters as tags? On its turn, the `processors.ifname` can read from the tags?

**Comment by powersj** [comment]
@Hipska,

If we have the knowledge of what needs to get done in the `snmp` input plugin, why not add this as a feature of the `snmp` plugin?

Thanks

**Comment by Hipska** [comment]
@srebhan is proposing to have a list/table of client parameters in the plugin config instead of putting the info in tags..

**Comment by Hipska** [comment]
@powersj @srebhan, can you please give a descision here, so the PR can be on time for 1.29?

**Comment by powersj** [comment]
@Hipska,

@srebhan and I have been talking about this today and we need to reset our understanding. We both understanding that there is friction between how to efficiently share configuration data between the SNMP plugin and when you do lookups.

What we both do not fully understand is why we could not do this in the SNMP plugin itself? Does this really need to be a new processor?

Thanks

**Comment by Hipska** [comment]
Yeah, sometimes you need another processor first to split the index if it is a combined one. 

The ifname was originally created to work with the sflow input. It can also be useful with the snmp_trap plugin.

**Comment by powersj** [comment]
> sometimes you need another processor first to split the index if it is a combined one

Can you give us a short example? Would go a long way to help us understand the situation better. Thanks

**Comment by Hipska** [comment]
See for example [TIMETRA-SAP-MIB::sapBaseInfoEntry](https://oidref.com/1.3.6.1.4.1.6527.3.1.2.4.3.2.1) where the index is a combination of 3 fields. 2 of them are available to gather from the table, but `svcId` isn't and I need that one to get the `TIMETRA-SERV-MIB::svcName` with snmp_lookup, so this processor comes in between:
```toml
# Parse TIMETRA-SAP-MIB::sapBaseStatsEntry index
[[processors.starlark]]
  alias = "sapBaseStatsEntry_index"
  order = 1
  namepass = ["sap"]

  ## Source of the Starlark script.
  source = '''
def apply(metric):

	index = metric.tags.pop("index", "0.0.0").split(".")

	metric.tags["svcId"] = index[0]
	metric.tags["sapPortId"] = index[1]
	metric.tags["sapEncapValue"] = index[2]

	return metric
'''

  ## Only need to run when the tag exists
  [processors.starlark.tagpass]
    index = ["*"]
```

And as said before, you can't do lookups when the functionality is embedded into `inputs.snmp` and the info comes from `inputs.snmp_trap` or `inputs.sflow` or others..

There is already some table merging functionality included in the snmp input, but that only works for one:one relations, not one:many or many:many relations.
