### ISSUE TITLE
ifName plugin changes tag into a field

### ISSUE THREAD

**Issue by Hipska** [influxdata/telegraf#8012]
It appears that `processors.ifname` plugin changes the interface index tag into a field.

### Relevant telegraf.conf:

```toml
# Lookup interface name for sff_lane table
[[processors.ifname]]
  namepass = ["sff_lane"]

  ## Name of tag holding the interface number
  tag = "ifIndex"

  ## Name of output tag where service name will be added
  # dest = "ifName"

  ## Name of tag of the SNMP agent to request the interface name from
  agent = "agent_host"

  ## Timeout for each request.
  timeout = "5s"

  ## SNMP version; can be 1, 2, or 3.
  version = 2

  ## SNMP community string.
  community = "xxxxx"

  ## Number of retries to attempt.
  retries = 3

  ## The GETBULK max-repetitions parameter.
  max_repetitions = 10
```

### System info:

Telegraf 1.15.2 (git: HEAD cd037b49)

### Expected behavior:

```
sff_lane,LaneIndex=0,agent_host=x.x.x.x,host=dama,hostname=example,ifName=xe-3/0/6,ifIndex=602,index=602.0 in_laser_power=0 1597922445000000000
```

### Actual behavior:

```
sff_lane,LaneIndex=0,agent_host=x.x.x.x,host=dama,hostname=example,ifName=xe-3/0/6,index=602.0 ifIndex=602i,in_laser_power=0 1597922445000000000
```

### Additional info:

Output when processors.ifname is not enabled:
```
sff_lane,LaneIndex=0,agent_host=x.x.x.x,host=dama,hostname=example,ifIndex=602,index=602.0 in_laser_power=0 1597922414000000000
```
