### ISSUE TITLE
OpenTSDB output returns EOF error with HTTP client

### ISSUE THREAD

**Issue by agaudreault-jive** [influxdata/telegraf#8034]
## Description

We are having multiple errors when using the HTTP client to write to OpenTSDB. The error is happening at inconsistent time, but almost every minutes. We also get a warning on the flush interval that might be related but that is happening a lot less often. I found several articles online to not use the Default Go HTTP client for production. I think the problem might be that the connection is being closed at some point and we are trying to read the response.

https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi

```
W! [agent] ["outputs.opentsdb"] did not complete within its flush interval
E! [agent] Error writing to outputs.opentsdb: Error when sending metrics: Post http://opentsdb.example.com:4242/api/put: EOF
```

### Relevant telegraf.conf:

```toml
[[outputs.opentsdb]]
  ## DNS name of the OpenTSDB server
  ## Using "opentsdb.example.com" or "tcp://opentsdb.example.com" will use the
  ## telnet API. "http://opentsdb.example.com" will use the Http API.
  host = "http://opentsdb.example.com"

  ## Port of the OpenTSDB server
  port = 4242

  ## Number of data points to send to OpenTSDB in Http requests.
  ## Not used with telnet API.
  http_batch_size = 50

  ## URI Path for Http requests to OpenTSDB.
  ## Used in cases where OpenTSDB is located behind a reverse proxy.
  http_path = "/api/put"

  ## Debug true - Prints OpenTSDB communication
  debug = false

  ## Separator separates measurement name from field
  separator = "."
```

### System info:

telegraf:1.13.4

### Expected behavior:

No error returned in logs or message should be more relevant.

### Actual behavior:

Error is in logs and I think data loss is occurring.

### Additional information

I will look into why/if our OpenTSDB instance is closing connection. But I think the error message should be a bit clearer.
