### ISSUE TITLE
MongoDB state, repl_state metrics show wrong info for non replica-set

### ISSUE THREAD

**Issue by 0zeroxzero0** [influxdata/telegraf#8035]
### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
  urls = ["http://10.10.10.11:8086"]
  database = "telegraf"
[[inputs.mongodb]]
  servers = ["mongodb://root:root@10.10.10.10:27017/admin?&authSource=admin"]
```

### System info:

Telegraf 1.15.2
Linux CentOS 7.4.1708 
Mongodb 3.6.2

### Steps to reproduce:

1. Run non-replica mongodb process. (without --replicaset)
2. Collect mongodb metrics using telegraf 1.15.2.
3. Query collected metric data in influxdb.
4. It shows state, repl_state metrics as Secondary Node.

### Expected behavior:

It must show non-replica or single node.

### Actual behavior:

It shows state, repl_state metrics as Secondary Node.
