### ISSUE TITLE
Is it possible add a Prometheus scrape job config in the input Plugin

### ISSUE THREAD

**Issue by KesavanKing** [influxdata/telegraf#8042]
## Feature Request

We need a feature in Prometheus input plugin which allows to 
add prometheus scrape configs as part of [configuration](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/prometheus#configuration).

Opening a feature request kicks off a discussion.

### Proposal:

Similar approach like in Prometheus 

```
- job_name: 'envoy-stats'
  metrics_path: /stats/prometheus
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: keep
    regex: '.*-envoy-prom'
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:15090
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
```

### Current behavior:

Only able to read the metadata from annotations or via static endpoints

### Use case: 

We have multiple containers  in a pod exposing metrics. One pod exposes on port 9090 and other is an 15090. So by the current approach of annotations we can only scrape only one metrics endpoint. Example: [Istio versions > 1.5](https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/https://istio.io/latest/docs/tasks/observability/metrics/customize-metrics/) there is no mixer. So each envoy proxy emit metrics on sidecar level
