### ISSUE TITLE
parse error with grok custom timestamp.

### ISSUE THREAD

**Issue by butson** [influxdata/telegraf#8045]
### Relevant telegraf.conf:

```toml
[[inputs.tail]]
  ## File names or a pattern to tail.
  ## These accept standard unix glob matching rules, but with the addition of
  ## ** as a "super asterisk". ie:
  ##   "/var/log/**.log"  -> recursively find all .log files in /var/log
  ##   "/var/log/*/*.log" -> find all .log files with a parent dir in /var/log
  ##   "/var/log/apache.log" -> just tail the apache log file
  ##
  ## See https://github.com/gobwas/glob for more examples
  ##
  files = ["/opt/nuodocker/logs/nuoadmin_sqlconn.log"]
  from_beginning = true
  data_format = "grok"
  grok_patterns= ['%{TIMESTAMP_ISO8601:timestamp:ts-"1999-12-31T12:59:59.999+0400"} %{GREEDYDATA:message:tag}']
  #  grok_patterns= ['%{TIMESTAMP_ISO8601:timestamp:tag} %{GREEDYDATA:message}']
```

### System info:

telegraf --version
Telegraf 1.14.5

### Steps to reproduce:

1. start telegraf with input plugin and tail file with input line:
```
2020-08-24T15:32:58.535+0000 Loading database CIP_LX_VM_NUO balancer:
```
2. output to file

### Expected behavior:

Expect that I would see timestamp field as time of metric with message.   Instead I get an error in parsing the field.

### Actual behavior:

```
2020-08-27T16:28:33Z E! Error parsing 2020-08-24T15:32:58.535+0000 to time layout [1999-12-31T12:59:59.999+0400]: parsing time "2020-08-24T15:32:58.535+0000": month out of range
```

### Additional info:

Changing the custom string slight gives a different error.

```
2020-08-27T16:29:20Z E! Error parsing 2020-08-24T15:32:58.535+0000 to time layout [2020-12-31T12:59:59.999+0400]: parsing time "2020-08-24T15:32:58.535+0000" as "2020-12-31T12:59:59.999+0400": cannot parse "-08-24T15:32:58.535+0000" as "0-"
```
