### ISSUE TITLE
The regex processor does not correctly process capture groups

### ISSUE THREAD

**Issue by neben** [influxdata/telegraf#8046]
### Relevant telegraf.conf:

```toml
[[processors.regex]]
  [[processors.regex.tags]]
    key = "topic"
    pattern = '^Sensor_?(\d+)'
    replacement = "${1}"

[[processors.printer]]
```

### System info:

Telegraf version 1.15.2
Docker 19.03.12 on Debian 

### Steps to reproduce:

1. Process data with tag `topic="Sensor22_humi"`

### Expected behavior:

The topic tag should have the value "22", as the capture group should only capture digits. This is also the result of this [Go regex tester](https://regoio.herokuapp.com).

### Actual behavior:

The topic tag has the value "22_humi".
