### ISSUE TITLE
can't add tagpass before source field in starlark processor

### ISSUE THREAD

**Issue by neben** [influxdata/telegraf#8050]
### Relevant telegraf.conf:

```toml
[[processors.starlark]]
  [processors.starlark.tagpass]
    topic = ["foo"]
  source = '''
def apply(metric):
    return metric
  '''
```

### System info:

Telegraf version 1.15.2
Docker 19.03.12

### Steps to reproduce:

1. start telegraf

### Expected behavior:

Telegraf starts without errors.

### Actual behavior:

Telegraf stops, because the starlark processor does not find the source field:
```
[telegraf] Error running agent: could not initialize processor starlark: one of source or script must be set
```

### Additional info:
Setting the tagpass filter **after** the source entry **does** work.
