### ISSUE TITLE
input postgresql plugin doesn't work with PostgreSQL 12

### ISSUE THREAD

**Issue by hedgss** [influxdata/telegraf#8066]
### Relevant telegraf.conf:

```toml
# Global tags can be specified here in key="value" format.
[global_tags]

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "${MONITORING_INTERVAL}"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = ${TELEGRAF_METRIC_BATCH_SIZE}

  ## Maximum number of unwritten metrics per output.
  metric_buffer_limit = ${TELEGRAF_METRIC_BUFFER_LIMIT}

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "${MONITORING_INTERVAL}"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# # Configuration for the Prometheus client to spawn
 [[outputs.prometheus_client]]
   ## Address to listen on
   listen = ":${TELEGRAF_PROMETHEUS_METRICS_PORT}"

   ## Use HTTP Basic Authentication.
   # basic_username = "Foo"
   # basic_password = "Bar"

   ## If set, the IP Ranges which are allowed to access metrics.
   ##   ex: ip_range = ["192.168.0.0/24", "192.168.1.0/30"]
   # ip_range = []

   ## Path to publish the metrics on.
   path = "${TELEGRAF_PROMETHEUS_METRICS_ENDPOINT}"

   ## Expiration interval for each metric. 0 == no expiration
   expiration_interval = "20s"

   ## Collectors to enable, valid entries are "gocollector" and "process".
   ## If unset, both are enabled.
   # collectors_exclude = ["gocollector", "process"]

   ## Send string metrics as Prometheus labels.
   ## Unless set to false all string metrics will be sent as labels.
   # string_as_label = true

   ## If set, enable TLS with the given certificate.
   # tls_cert = "/etc/ssl/telegraf.crt"
   # tls_key = "/etc/ssl/telegraf.key"

   ## Set one or more allowed client CA certificate file names to
   ## enable mutually authenticated TLS connections
   # tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]

   ## Export metric collection time.
   export_timestamp = false

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################
# Read formatted metrics from one or more HTTP endpoints
[[inputs.http]]
  ## One or more URLs from which to read formatted metrics
  urls = [
    "http://localhost:${BG_MON_PORT}/"
  ]

  ## HTTP method
  # method = "GET"

  ## Optional HTTP headers
  # headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP entity-body to send with POST/PUT requests.
  # body = ""

  ## HTTP Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "identity"

  ## Optional HTTP Basic Auth Credentials
  # username = "username"
  # password = "pa$$word"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Amount of time allowed to complete the HTTP request
 # timeout = "5s"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "json"
  json_string_fields = ["postgresql_role"]
  name_override = "bg_mon"

# Read formatted metrics from one or more HTTP endpoints
[[inputs.http]]
  ## One or more URLs from which to read formatted metrics
  urls = [
    "http://localhost:9000/api/v1/monitoring/node/status"
  ]

  ## HTTP method
  # method = "GET"

  ## Optional HTTP headers
  # headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP entity-body to send with POST/PUT requests.
  # body = ""

  ## HTTP Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "identity"

  ## Optional HTTP Basic Auth Credentials
  # username = "username"
  # password = "pa$$word"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## Amount of time allowed to complete the HTTP request
 # timeout = "5s"

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "json"
  name_override = "spilo_sidecar_service"

# Read metrics about disk usage by mount point
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  mount_points = ["/home/postgres/pgdata"]

  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]


# Get the number of processes and group them by status
[[inputs.processes]]
  # no configuration

###############################################################################
#                            SERVICE INPUT PLUGINS                            #
###############################################################################

# # Read metrics from one or many postgresql servers
[[inputs.postgresql]]
   ## specify address via a url matching:
   ##   postgres://[pqgotest[:password]]@localhost[/dbname]\
   ##       ?sslmode=[disable|verify-ca|verify-full]
   ## or a simple string:
   ##   host=localhost user=pqotest password=... sslmode=... dbname=app_production
   ##
   ## All connection parameters are optional.
   ##
   ## Without the dbname parameter, the driver will default to a database
   ## with the same name as the user. This dbname is just for instantiating a
   ## connection with the server and doesn't restrict the databases we are trying
   ## to grab metrics for.
   ##
   #address = "host=localhost user=postgres sslmode=disable"
   address = "host=localhost user=postgres dbname=postgres sslmode=disable"
   ## A custom name for the database that will be used as the "server" tag in the
   ## measurement output. If not specified, a default one generated from
   ## the connection address is used.
   # outputaddress = "db01"

   ## connection configuration.
   ## maxlifetime - specify the maximum lifetime of a connection.
   ## default is forever (0s)
   max_lifetime = "0s"

   ## A  list of databases to explicitly ignore.  If not specified, metrics for all
   ## databases are gathered.  Do NOT use with the 'databases' option.
   # ignored_databases = ["postgres", "template0", "template1"]

   ## A list of databases to pull metrics about. If not specified, metrics for all
   ## databases are gathered.  Do NOT use with the 'ignored_databases' option.
   # databases = ["app_production", "testing"]
```
All environment variables are defined:
```properties
    TELEGRAF_METRIC_BATCH_SIZE=1000
    TELEGRAF_METRIC_BUFFER_LIMIT=60000
    TELEGRAF_PROMETHEUS_METRICS_PORT=8080
    TELEGRAF_PROMETHEUS_METRICS_ENDPOINT="/metrics"
```
### System info:

Telegraf: 1.13.3
OS: Debian GNU/Linux 10 (buster)
PostgreSQL: 12

### Docker

I am using telegraf in kubernetes.
One pod has 2 containers.
1st one is postgres node
2nd is sidecar.

All connections in localhost allowed in (pg_hba.conf)

### Steps to reproduce:

1. Start Postgres in one docker container
2. Start telegraf with provided configuration in the 2nd docker container. The 2nd docker container must have access without password to the 1st one.

or you can use a simpler way to reproduce it.
1. You need to have a Postgresql.
2. You need to have a host where you can start telegraf. Telegraf must have access to the PostgreSQL without password.

### Expected behavior:

Telegraf should be able to get access and collect metrics from PostgreSQL 12

### Actual behavior:

```bash
2020-09-01T13:25:36Z I! [outputs.prometheus_client] Listening on http://[::]:8080/metrics
panic: interface conversion: interface {} is nil, not string

goroutine 71 [running]:
github.com/influxdata/telegraf/plugins/inputs/postgresql.(*Postgresql).accRow(0xc000578100, 0x2c31d60, 0xc0005ae100, 0x2c9ef00, 0xc00026c4a0, 0xc0005b8000, 0x15, 0x15, 0xc0005ae100, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/postgresql/postgresql.go:158 +0x7bb
github.com/influxdata/telegraf/plugins/inputs/postgresql.(*Postgresql).Gather(0xc000578100, 0x2c9ef00, 0xc00026c4a0, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/postgresql/postgresql.go:100 +0x1cf
github.com/influxdata/telegraf/internal/models.(*RunningInput).Gather(0xc000150640, 0x2c9ef00, 0xc00026c4a0, 0x2c83e00, 0xc000064440)
        /go/src/github.com/influxdata/telegraf/internal/models/running_input.go:110 +0x6d
github.com/influxdata/telegraf/agent.(*Agent).gatherOnce.func1(0xc000167020, 0xc000150640, 0x2c9ef00, 0xc00026c4a0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:332 +0x3f
created by github.com/influxdata/telegraf/agent.(*Agent).gatherOnce
        /go/src/github.com/influxdata/telegraf/agent/agent.go:331 +0xf5
^C
[1]+  Exit 2                  /base/apps/telegraf/telegraf --config /app/configs/telegraf.conf
```
