### ISSUE TITLE
Using docker_log plugin causes docker daemon to crash

### ISSUE THREAD

**Issue by w4tsn** [influxdata/telegraf#8072]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 1000000
  collection_jitter = "5s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = "s"

[[outputs.influxdb]]
  timeout = "5s"

[[inputs.docker_log]]
  endpoint = "tcp://dockersocket:2375"
  source_tag = true
  [inputs.docker_log.tags]
    retention_policy = "logs"
```

### System info:

Telegraf: 1.15.2 Container
Host: CentOS 7 3.10.0-1127.18.2.el7.x86_64
Docker: 1.13.1
Docker Log-Driver: journald

### Docker + journald

```yaml
version: "2"
services:
  telegraf:
    image: docker.io/library/telegraf:1.15
    restart: always
    mem_limit: 1024mb
    memswap_limit: 1536mb
    read_only: true
    security_opt:
      - label:disable
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
      - /var/srv/telegraf/conf:/etc/telegraf/:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
    networks:
      telegraf:
  dockersocket:
    image: quay.io/sheogorath/docker-socket-proxy:1.9
    mem_limit: 16mb
    memswap_limit: 32mb
    security_opt:
      - "label:disable"
    read_only: true
    tmpfs:
      - /run/:size=32K
    environment:
      - "CONTAINERS=1"
      - "INFO=1"
      - "NETWORKS=1"
      - "IMAGES=1"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      telegraf:
    restart: always
networks:
  telegraf:
```

I'm using a journald vacuum size of 12 GB. The tests were done with a journal size of 128M and 12G.

The test system runs 40 Containers, from databases, over backend services to frontends. Consuming 3 - 4 CPUs, 25 GB of RAM, several GB of Disk and most importantly generates around 10 GB logs per 24h.

A second, significantly smaller test system only runs 5 containers with a similar journald configuration than the first server.

### Steps to reproduce:

1. Run telegraf in the afformentioned setup(s)

### Expected behavior:

Telegraf (docker_log plugin) collects the latest logs and writes them to influxdb.

### Actual behavior:

The docker daemon starts to consume all resources before it crashes. System load rises by a magnitude of 20.

### Additional info:

- This might be a quite "special" setup because of the older version of docker and centos.
- I've commented out the docker_log plugin to verify that this is caused by the usage of this plugin.
- In general, using telegraf increases system load by a factor of 1 or 2.
- Reducing the size of the present journald logs (`journalctl --vacuum-size=128M`) helps increasing the time to crash and also causes a lower increase of system load; magnitude of 10, instead of around 20
- I'm observing `[inputs.docker_log] Error in plugin: unexpected EOF` in the logs
- Starting the telegraf container with the plugin enabled almost immediately rises the system load eventually crashing the docker daemon
- The process dockerd-current allocates over 400G of VIRT memory according to htop
