### ISSUE TITLE
SIGSEGV caused by processors

### ISSUE THREAD

**Issue by mjf** [influxdata/telegraf#8089]
### Relevant telegraf.conf:
```toml
[agent]
  hostname = "test.example.com"
[[outputs.influxdb_v2]]
  bucket = "test"
  organization = "Test Organization"
  token = "REDACTED"
  urls = ["https://test.example.com:9999"]
[[inputs.http_listener_v2]]
    name_override = "test"
    service_address = "test.example.com:8001"
    methods = [ "GET" ]
    path = "/test"
    data_source = "query"
    data_format = "form_urlencoded"
    form_urlencoded_tag_keys = ["chan", "unit", "name", "id", "val", "min", "max"]
    # fielddrop = ["val_1"]
[[processors.regex]]
    order = 1
    namepass = ["test"]
    [[processors.regex.tags]]
      key = "val"
      pattern = "^(%20)+"
      replacement = ""
    [[processors.regex.tags]]
      key = "min"
      pattern = "^(%20)+"
      replacement = ""
    [[processors.regex.tags]]
      key = "max"
      pattern = "^(%20)+"
      replacement = ""
[[processors.converter]]
    order = 2
    namepass = ["test"]
    [processors.converter.tags]
      float = ["val", "min", "max"]
```

### System info:
``Telegraf 1.15.2 (git: HEAD cd037b49)``

### Docker

No *Docker*...

### Steps to reproduce:
With the provided configuration *Telegraf* crashes on the following ``GET`` request:

```shell
$ curl 'http://test.example.com:8001/test?chan=01&name=measurement%20test&stat=0&val=%20%20%201.234&unit=Pa&max=0&min=0&mode=0&id=test'
```

1. start *Telegraf* with configuration similar to the provided sample configuration
2. submit the provided sample ``GET`` request

### Expected behavior:

*Telegraf* operates as expected and does not crash with ``SIGSEGV``.

### Actual behavior:
*Telegraf* crashes with ``SIGSEGV``:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1f92c58]

goroutine 23 [running]:
github.com/influxdata/telegraf/plugins/processors/converter.(*Converter).convertTags(0xc000029f80, 0x2f59ae0, 0xc0004b2000)
        /go/src/github.com/influxdata/telegraf/plugins/processors/converter/converter.go:217 +0x358
github.com/influxdata/telegraf/plugins/processors/converter.(*Converter).Apply(0xc000029f80, 0xc000060c90, 0x1, 0x1, 0xc00006de40, 0xc00006ded8, 0x7e03ba)
        /go/src/github.com/influxdata/telegraf/plugins/processors/converter/converter.go:85 +0x7a
github.com/influxdata/telegraf/plugins/processors.(*streamingProcessor).Add(0xc00042d4c0, 0x2f59ae0, 0xc0004b2000, 0x2f4aa80, 0xc00000e820, 0x1, 0xc000000101)
        /go/src/github.com/influxdata/telegraf/plugins/processors/streamingprocessor.go:35 +0x81
github.com/influxdata/telegraf/models.(*RunningProcessor).Add(0xc00055c150, 0x2f59ae0, 0xc0004b2000, 0x2f4aa80, 0xc00000e820, 0x2, 0x1)
        /go/src/github.com/influxdata/telegraf/models/running_processor.go:95 +0x106
github.com/influxdata/telegraf/agent.(*Agent).runProcessors.func1(0xc0004fa000, 0xc00000e620)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:559 +0x156
created by github.com/influxdata/telegraf/agent.(*Agent).runProcessors
        /go/src/github.com/influxdata/telegraf/agent/agent.go:554 +0x90
```

### Additional info:
I found the bug while trying to workaround issues described in #8064.
