### ISSUE TITLE
Send metrics to specific outputs

### ISSUE THREAD

**Issue by s1m0** [influxdata/telegraf#809]
It would be very useful to be able to output exec inputs to different Influxdb databases with differing retention policies and precisions. e.g.
```
[[inputs.exec]]
  command = "/usr/local/bin/my5minutescript.sh"
  interval = "5m"  
  data_format = "influx"
  influx_db = "database1"
  influx_retention = "default"
  influx_precision = "s"

[[inputs.exec]]
  command = "/usr/local/bin/my5secondcript.sh"
  interval = "5s"
  data_format = "influx"
  influx_db = "database2"
  influx_retention = "5days"
  influx_precision = "ns"
```

**Comment by titilambert** [comment]
And what about to be able to select which input send data to which outputs ?

```
[[inputs.exec]]
  command = "/usr/local/bin/my5minutescript.sh"
  interval = "5m"  
  data_format = "influx"
  # if outputs is empty, then send to all outputs
  outputs = ["influxdb1"]

[[inputs.exec]]
  command = "/usr/local/bin/my5secondcript.sh"
  interval = "5s"
  data_format = "influx"
  # if outputs is empty, then send to all outputs
  outputs = ["influxdb2"]

[[outputs.influxdb]]
  name = "influxdb1"
   urls = ["http://localhost:8086"]
  database = "telegraf"
  retention_policy = "default"
  precision = "s"

[[outputs.influxdb]]
  name = "influxdb2"
   urls = ["http://localhost:8086"]
  database = "telegraf2"
  retention_policy = "5days"
  precision = "ns"
```

**Comment by s1m0** [comment]
That approach would hopefully be applicable to all types of inputs and outputs. It would be a breaking change but well worth the disruption to make telegraf a lot more flexible, allowing you to 'wire-up' inputs to outputs, rather like Node-Red does visually.

**Comment by sparrc** [comment]
Sending inputs to specific outputs sounds like a useful feature, but there is a way of doing this already using measurement name filtering:

```toml
[[inputs.exec]]
  command = "/usr/local/bin/my5minutescript.sh"
  interval = "5m"  
  data_format = "influx"
  name_suffix = "_default"

[[inputs.exec]]
  command = "/usr/local/bin/my5secondcript.sh"
  interval = "5s"
  data_format = "influx"
  name_suffix = "_5days"

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "telegraf"
  retention_policy = "default"
  precision = "s"
  namepass = ["*_default"]

[[outputs.influxdb]]
  urls = ["http://localhost:8086"]
  database = "telegraf2"
  retention_policy = "5days"
  precision = "ns"
  namepass = ["*_5days"]
```
