### ISSUE TITLE
telegraf not getting metrics from containers with a short lifetime

### ISSUE THREAD

**Issue by rdxmb** [influxdata/telegraf#8122]
### Relevant telegraf.conf:

```toml
[agent]
  logfile = ""
  interval = "1m"
  round_interval = true
  debug = false
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  quiet = true
  omit_hostname = false
# ------------ snip ------
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  timeout = "10s"
  total = true
# ------------ snip ------
```

### System info:
telegraf  1.15.3, running in docker

### Docker

```
# docker --version
Docker version 18.06.3-ce, build d7080c1
# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Steps to reproduce:

1. Start a container with a short lifetime like 20s. In my case, this is controlled by a k8-(cron)job and runs an incremental backup.
2. Try to get metrics with the telegraf `inputs.docker`-Plugin

### Expected behavior:

Telegraf gathers all the metrics it can gather from the mounted docker-socket (like `docker ps -a`)

### Actual behavior:

Telegraf only sometimes collect the metrics of the containers with a short lifetime. My job is running hourly, I have no metrics for that containers for about one week. Today, there was one timestamp of one container with that metrics. Therefore I cannot get the exit-code of the containers with the short lifetime.

### Additional info:

* I have containers gathered by the same telegraf running some days ago. (09/11 and 09/12). Before and after that, I do not have any metrics of those containers.
* Running the scripts with additional `sleep 1m` seems to be a workround in some cases. `sleep 5m` seems to be even better.

If you need additional debug information, please let me know.
