### ISSUE TITLE
ClickHouse error "Poco::Exception. Code: 1000" when ClickHouse telegraf plugin is enabled

### ISSUE THREAD

**Issue by farafarafara** [influxdata/telegraf#8136]
### Relevant telegraf.conf:

```toml
[global_tags]
  region = "$region"
  role = "$role"
  host = "$hostname"
  env  = "$env"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = true
  logfile = ""
  hostname = ""
  omit_hostname = true
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.net]]
[[inputs.netstat]]
[[inputs.kernel_vmstat]]
[[inputs.linux_sysctl_fs]]
[[inputs.procstat]]
  pattern = "carbon-clickhouse"
  prefix = "pgrep_serviceprocess"
[[inputs.procstat]]
  pattern = "graphite-clickhouse"
  prefix = "pgrep_serviceprocess"
[[inputs.net_response]]
  protocol = "tcp"
  address = "localhost:2003"
[[inputs.net_response]]
  protocol = "tcp"
  address = "localhost:9090"
[[inputs.clickhouse]]
  username = "username"
  password = "password"
  servers = ["http://127.0.0.1:8123"]
  auto_discovery = false

[[outputs.graphite]]
  servers = ["$graphite_relay:2003"]
  prefix = "nodes."
  template = "env.region.role.host.tags.measurement.field"
  timeout = 2
```

### System info:

/etc/os-release contents:
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

Telegraf 1.15.2 (git: HEAD cd037b49)
ClickHouse server version 20.5.4.40.

### Steps to reproduce:

1. On a node with ClickHouse db install telegraf plugin. Check /var/log/clickhouse-server/clickhouse-server.err.log and verify that there're no errors.
2. Add ClickHouse input plugin section to telegraf config. Note: in our case we have a ClickHouse cluster with 3 nodes, however, I don't expect this to make a difference.
```toml
[[inputs.clickhouse]]
  username = "username"
  password = "password"
  servers = ["http://127.0.0.1:8123"]
  auto_discovery = false

```
3. Restart telegraf service.

### Expected behavior:

No clickhouse-server errors after telegraf service is started.

### Actual behavior:

In /var/log/clickhouse-server/clickhouse-server.err.log we can see following errors every X seconds (where X = agent interval, in our case it is 10s):

```
2020.09.11 13:39:10.008042 [ 15679 ] {} <Error> ServerErrorHandler: Poco::Exception. Code: 1000, e.code() = 104, e.displayText() = Connection reset by peer, Stack trace (when copying this message, always include the lines below):

0. Poco::IOException::IOException(int) @ 0xcc3877b in /usr/bin/clickhouse
1. Poco::Net::ConnectionResetException::ConnectionResetException(int) @ 0xcb55549 in /usr/bin/clickhouse
2. ? @ 0x5930a6a in /usr/bin/clickhouse
3. Poco::Net::SocketImpl::receiveBytes(void*, int, int) @ 0xcb6ac50 in /usr/bin/clickhouse
4. Poco::Net::HTTPSession::receive(char*, int) @ 0xcb48be4 in /usr/bin/clickhouse
5. Poco::Net::HTTPSession::get() @ 0xcb48c4b in /usr/bin/clickhouse
6. Poco::Net::HTTPHeaderStreamBuf::readFromDevice(char*, long) @ 0xcb431b2 in /usr/bin/clickhouse
7. Poco::BasicBufferedStreamBuf<char, std::__1::char_traits<char>, Poco::Net::HTTPBufferAllocator>::underflow() @ 0xcb43098 in /usr/bin/clickhouse
8. std::__1::basic_streambuf<char, std::__1::char_traits<char> >::uflow() @ 0xd87193a in /usr/bin/clickhouse
9. std::__1::basic_istream<char, std::__1::char_traits<char> >::get() @ 0xd878166 in /usr/bin/clickhouse
10. Poco::Net::HTTPRequest::read(std::__1::basic_istream<char, std::__1::char_traits<char> >&) @ 0xcb458a3 in /usr/bin/clickhouse
11. Poco::Net::HTTPServerRequestImpl::HTTPServerRequestImpl(Poco::Net::HTTPServerResponseImpl&, Poco::Net::HTTPServerSession&, Poco::Net::HTTPServerParams*) @ 0xcb4814e in /usr/bin/clickhouse
12. Poco::Net::HTTPServerConnection::run() @ 0xcb72ad4 in /usr/bin/clickhouse
13. Poco::Net::TCPServerConnection::start() @ 0xcb6f517 in /usr/bin/clickhouse
14. Poco::Net::TCPServerDispatcher::run() @ 0xcb6f90b in /usr/bin/clickhouse
15. Poco::PooledThread::run() @ 0xcca652e in /usr/bin/clickhouse
16. Poco::ThreadImpl::runnableEntry(void*) @ 0xcca3229 in /usr/bin/clickhouse
17. start_thread @ 0x7e65 in /usr/lib64/libpthread-2.17.so
18. __clone @ 0xfe88d in /usr/lib64/libc-2.17.so
 (version 20.5.4.40)
```

### Additional info:

I was not able to find relevant issues, the most close ones are https://github.com/ClickHouse/ClickHouse/issues/3636 and https://github.com/ClickHouse/ClickHouse/issues/2577. However, they're not applicable to our case, we have HTTP checks set up and when we remove ClickHouse plugin from telegraf config and restart the service, errors disappear.
