### ISSUE TITLE
Telegraf cannot send data to InfluxDb on PFSense. "dial tcp 192.168.2.21:8086: connect: permission denied"

### ISSUE THREAD

**Issue by douglasg14b** [influxdata/telegraf#8146]
### Relevant telegraf.conf:

```toml
# This file is automatically generated by pfSense #
[agent]
	interval = "10s"
	round_interval = true

  ## Log at debug level.
  debug = true

  ## Log only error level messages.
  quiet = false

[[inputs.exec]]
    commands = ["sh /root/scripts/sys_temp.sh"]
    timeout = "5s"
    data_format = "json"
    name_suffix = "_cpu_temp"

[[inputs.cpu]]
	percpu = true
	totalcpu = true
	fielddrop = ["time_*"]

[[inputs.disk]]
	ignore_fs = ["tmpfs", "devtmpfs"]

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.net]]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.unbound]]
	binary = "/usr/local/sbin/unbound-control"
	server = "127.0.0.1:953"
	#thread_as_tag = false
	#use_sudo = true
[[outputs.influxdb]]
	urls = ["https://[snip]:8086"]
	database = "pfsense"
	username = "pfsense"
	password = "[snip]"
	insecure_skip_verify = true

```

### System info:

**Telegraf:** v1.13.4
**System:** PFSense 2.4.4-RELEASE-p3 (FreeBSD 11.2-RELEASE-p10)

### Steps to reproduce:

1. Run telegraf on pfsense
2. Look at a logs and see that it cannot send data to influx
3. ??? More info with some help diagnosing

### Expected behavior:

It sends data to influx

### Actual behavior:

It fails to send data to influx, seemingly due to the `connect` call being denied?

### Additional info:

* **This started a week ago, and was previously working. Which is... strange. It's been working since 2018**
  * This started on telegraf v1.6, I upgraded to v1.13 in an attempt to resolve
  * The only changes made where creating a LAGG for 2 ports for LAN
     * I have tried reverting to a normal interface for LAN and the issue persists.
* All other devices can send to the InfluxDB instance just fine
* No actual connections are made to 192.168.2.21, this *seems* to be a local permissions issue? 

```
2020-09-17T22:49:20Z E! [outputs.influxdb] When writing to [https://[snip]:8086]: Post https://[snip]:8086/write?db=pfsense: dial tcp 192.168.2.21:8086: connect: permission denied
2020-09-17T22:49:20Z E! [agent] Error writing to outputs.influxdb: could not write any address
2020-09-17T22:49:30Z E! [outputs.influxdb] When writing to [https://[snip]:8086]: Post https://[snip]:8086/write?db=pfsense: dial tcp 192.168.2.21:8086: connect: permission denied
2020-09-17T22:49:30Z E! [agent] Error writing to outputs.influxdb: could not write any address

```
