### ISSUE TITLE
WebIdentityProvider for AWS authentification

### ISSUE THREAD

**Issue by cjaber** [influxdata/telegraf#8193]
On a AWS EKS environment it's considered as a good practice to have fine grained access policy through https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html. This is implemented through assuming a IAM role and a web_identity_provider. The application uses the provided token by reading a token file mounted into the pod by EKS.

This authentication mode doesn't seem to be taken into account currently in telegraf (according to the code https://github.com/influxdata/telegraf/blob/master/config/aws/credentials.go#L50). Can you confim this? If yes is there any plans to implement it ?

Thanks in advance

### Relevant telegraf.conf:

```toml
# Configuration for AWS CloudWatch output.
[[outputs.cloudwatch]]
  ## Amazon REGION
  region = "eu-west-1"

  ## Amazon Credentials
  ## Credentials are loaded in the following order
  ## 1) Assumed credentials via STS if role_arn is specified
  ## 2) explicit credentials from 'access_key' and 'secret_key'
  ## 3) shared profile from 'profile'
  ## 4) environment variables
  ## 5) shared credentials file
  ## 6) EC2 Instance Profile
  #access_key = ""
  #secret_key = ""
  #token = ""
  role_arn = "$AWS_ROLE_ARN"
  #profile = ""
  #shared_credential_file = ""

  ## Endpoint to make request against, the correct endpoint is automatically
  ## determined and this option should only be set if you wish to override the
  ## default.
  ##   ex: endpoint_url = "http://localhost:8000"
  # endpoint_url = ""

  ## Namespace for the CloudWatch MetricDatums
  namespace = "InfluxData/Telegraf"

  ## If you have a large amount of metrics, you should consider to send statistic
  ## values instead of raw metrics which could not only improve performance but
  ## also save AWS API cost. If enable this flag, this plugin would parse the required
  ## CloudWatch statistic fields (count, min, max, and sum) and send them to CloudWatch.
  ## You could use basicstats aggregator to calculate those fields. If not all statistic
  ## fields are available, all fields would still be sent as raw metrics.
  # write_statistics = false

  ## Enable high resolution metrics of 1 second (if not enabled, standard resolution are of 60 seconds precision)
  # high_resolution_metrics = false
```

### System info:

Telegraf 1.15
AWS EKS optimized AMI AL2_x86_64 1.16.8-20200507
