### ISSUE TITLE
telegraf kafka consumer not reading all the data from a topic

### ISSUE THREAD

**Issue by sgreszcz** [influxdata/telegraf#8207]
### Relevant telegraf.conf:

```toml
# Telegraf Configuration
#
# Telegraf is entirely plugin driven. All metrics are gathered from the
# declared inputs, and sent to the declared outputs.
#
# Plugins must be declared in here to be active.
# To deactivate a plugin, comment out the name and any variables.
#
# Use 'telegraf -config telegraf.conf -test' to see what metrics a config
# file would generate.
#
# Environment variables can be used anywhere in this config file, simply surround
# them with ${}. For strings the variable must be within quotes (ie, "${STR_VAR}"),
# for numbers and booleans they should be plain (ie, ${INT_VAR}, ${BOOL_VAR})

# Global tags can be specified here in key="value" format.
[global_tags]
  # dc = "us-east-1" # will tag all metrics with dc=us-east-1
  # rack = "1a"
  ## Environment variables can be used as tags, and throughout the config file
  # user = "$USER"

# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "500ms"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  debug = {{ telegraf_debug_on }}
  ## Log only error level messages.
  # quiet = false

  ## Log target controls the destination for logs and can be one of "file",
  ## "stderr" or, on Windows, "eventlog".  When set to "file", the output file
  ## is determined by the "logfile" setting.
  # logtarget = "file"

  ## Name of the file to be logged to when using the "file" logtarget.  If set to
  ## the empty string then logs are written to stderr.
  # logfile = ""

  ## The logfile will be rotated after the time interval specified.  When set
  ## to 0 no time based rotation is performed.  Logs are rotated only when
  ## written to, if there is no log activity rotation may be delayed.
  # logfile_rotation_interval = "0d"

  ## The logfile will be rotated when it becomes larger than the specified
  ## size.  When set to 0 no size based rotation is performed.
  # logfile_rotation_max_size = "0MB"

  ## Maximum number of rotated archives to keep, any older logs are deleted.
  ## If set to -1, no archives are removed.
  # logfile_rotation_max_archives = 5

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false


[[inputs.kafka_consumer]]
  ## Kafka brokers.
  brokers = [{{ sa_kafka_brokers }}]

  ## Topics to consume.
  topics = [{{ kafka_topics_ucv }}]

  ## When set this tag will be added to all metrics with the topic as the value.
  # topic_tag = ""

  ## Optional Client id
  # client_id = "Telegraf"

  ## Set the minimal supported Kafka version.  Setting this enables the use of new
  ## Kafka features and APIs.  Must be 0.10.2.0 or greater.
  ##   ex: version = "1.1.0"
  # version = ""

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

  ## SASL authentication credentials.  These settings should typically be used
  ## with TLS encryption enabled using the "enable_tls" option.
  # sasl_username = "kafka"
  # sasl_password = "secret"

  ## SASL protocol version.  When connecting to Azure EventHub set to 0.
  # sasl_version = 1

  ## Name of the consumer group.
  # consumer_group = "telegraf_metrics_consumers"

  ## Initial offset position; one of "oldest" or "newest".
  # offset = "oldest"

  ## Consumer group partition assignment strategy; one of "range", "roundrobin" or "sticky".
  # balance_strategy = "range"

  ## Maximum length of a message to consume, in bytes (default 0/unlimited);
  ## larger messages are dropped
  max_message_len = 1000000

  ## Maximum messages to read from the broker that have not been written by an
  ## output.  For best throughput set based on the number of metrics within
  ## each message and the size of the output's metric_batch_size.
  ##
  ## For example, if each message from the queue contains 10 metrics and the
  ## output metric_batch_size is 1000, setting this to 100 will ensure that a
  ## full batch is collected and the write is triggered immediately without
  ## waiting until the next flush_interval.
  max_undelivered_messages = 10000

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"

# Configuration for sending metrics to InfluxDB 2.0
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://{{ influxdb_server }}:9999"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to.
  organization = "{{ influxdb_organisation }}"

  ## Destination bucket to write into.
  bucket = "{{ influxdb_bucket }}"

  ## The value of this tag will be used to determine the bucket.  If this
  ## tag is not set the 'bucket' option is used as the default.
  # bucket_tag = ""

  ## If true, the bucket tag will not be added to the metric.
  # exclude_bucket_tag = false

  ## Timeout for HTTP messages.
  # timeout = "5s"

  ## Additional HTTP headers
  # http_headers = {"X-Special-Header" = "Special-Value"}

  ## HTTP Proxy override, if unset values the standard proxy environment
  ## variables are consulted to determine which proxy, if any, should be used.
  # http_proxy = "http://corporate.proxy:3128"

  ## HTTP User-Agent
  # user_agent = "telegraf"

  ## Content-Encoding for write request body, can be set to "gzip" to
  ## compress body or "identity" to apply no encoding.
  # content_encoding = "gzip"

  ## Enable or disable uint support for writing uints influxdb 2.0.
  # influx_uint_support = false

  ## Optional TLS Config for use on HTTP connections.
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

```

### System info:

Telegraf 1.14.4 (vanilla from InfluxDB in docker)

### Steps to reproduce:

1. Writing influx line protocol to kafka using custom code in this format:
```
mra_count,host=vce-aer-201 value=284i 1601497655000000000
mra_count,host=vce-aer-202 value=279i 1601497656000000000
mra_count,host=vce-aer-201 value=284i 1601497716000000000
mra_count,host=vce-aer-202 value=281i 1601497716000000000
```
so far I have this many lines:
```
cat influx.txt | wc -l
54
```
2. I can see the data across my 9 partitions in kafka:
<img width="1125" alt="Screenshot 2020-09-30 at 21 54 39" src="https://user-images.githubusercontent.com/22910494/94738889-ff058a00-0367-11eb-9990-09423f935c51.png">

3. But for some reason Telegraf is not loading each of the lines of data off of the kafka topics and into influx DB (for example at the same time there are only 30 metrics in influxDB.

<img width="1339" alt="Screenshot 2020-09-30 at 21 57 06" src="https://user-images.githubusercontent.com/22910494/94739271-a2ef3580-0368-11eb-8bc5-5a595437c47b.png">

### Expected behavior:

I would expect to see all the data that I'm sending through kafka:
```
cat influx.txt  | grep 201
mra_count,host=vce-aer-201 value=284i 1601497655000000000
mra_count,host=vce-aer-201 value=284i 1601497716000000000
mra_count,host=vce-aer-201 value=285i 1601497776000000000
mra_count,host=vce-aer-201 value=282i 1601497836000000000
mra_count,host=vce-aer-201 value=277i 1601497896000000000
mra_count,host=vce-aer-201 value=276i 1601497956000000000
mra_count,host=vce-aer-201 value=272i 1601498016000000000
mra_count,host=vce-aer-201 value=271i 1601498076000000000
mra_count,host=vce-aer-201 value=274i 1601498136000000000
mra_count,host=vce-aer-201 value=271i 1601498196000000000
mra_count,host=vce-aer-201 value=271i 1601498256000000000
mra_count,host=vce-aer-201 value=270i 1601498316000000000
mra_count,host=vce-aer-201 value=270i 1601498376000000000
mra_count,host=vce-aer-201 value=271i 1601498436000000000
mra_count,host=vce-aer-201 value=269i 1601498496000000000
mra_count,host=vce-aer-201 value=265i 1601498556000000000
mra_count,host=vce-aer-201 value=266i 1601498616000000000
mra_count,host=vce-aer-201 value=269i 1601498676000000000
mra_count,host=vce-aer-201 value=271i 1601498736000000000
mra_count,host=vce-aer-201 value=267i 1601498796000000000
mra_count,host=vce-aer-201 value=266i 1601498856000000000
mra_count,host=vce-aer-201 value=268i 1601498917000000000
mra_count,host=vce-aer-201 value=267i 1601498977000000000
mra_count,host=vce-aer-201 value=265i 1601499037000000000
mra_count,host=vce-aer-201 value=266i 1601499097000000000
mra_count,host=vce-aer-201 value=267i 1601499157000000000
mra_count,host=vce-aer-201 value=263i 1601499217000000000
mra_count,host=vce-aer-201 value=272i 1601499277000000000
mra_count,host=vce-aer-201 value=269i 1601499337000000000
mra_count,host=vce-aer-201 value=270i 1601499397000000000
mra_count,host=vce-aer-201 value=270i 1601499457000000000
mra_count,host=vce-aer-201 value=263i 1601499517000000000
mra_count,host=vce-aer-201 value=258i 1601499577000000000
mra_count,host=vce-aer-201 value=262i 1601499637000000000
mra_count,host=vce-aer-201 value=265i 1601499697000000000
mra_count,host=vce-aer-201 value=265i 1601499757000000000
```

### Actual behavior:

I don't see all of the data (some is missing - this is the csv export from influxdb looking at all the data for vce-aer-201 over a 2h period):
```
#group,false,false,true,true,false,false,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string
#default,_result,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,host
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:28:36Z,284,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:29:36Z,285,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:30:36Z,282,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:35:36Z,274,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:37:36Z,271,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:39:36Z,270,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:40:36Z,271,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:42:36Z,265,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:48:37Z,268,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:50:37Z,265,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:51:37Z,266,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:54:37Z,272,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:56:37Z,270,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:57:37Z,270,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:58:37Z,263,value,mra_count,vce-aer-201
,,0,2020-09-28T21:03:50.040788656Z,2020-09-30T21:03:50.040788656Z,2020-09-30T20:59:37Z,258,value,mra_count,vce-aer-201
```

**Comment by sgreszcz** [comment]
I think that this might have to do with the telegraf kafka consumer group not reading properly across all the topics that are partitioned.  In this case, I am reading from three topics using telegraf, and each topic has 9 partitions, but I see this in the telegraf logs:
```
2020-09-30T20:46:37Z D! [sarama] client/metadata fetching metadata for [ucv-video-metrics ucv-voice-metrics-cube-snmp ucv-video-metrics-xapi] from broker chain-prd-16:9092
2020-09-30T20:46:37Z D! [sarama] client/coordinator requesting coordinator for consumergroup telegraf_metrics_consumers from chain-prd-16:9092
2020-09-30T20:46:37Z D! [sarama] client/coordinator coordinator for consumergroup telegraf_metrics_consumers is #2 (chain-prd-17:9092)
2020-09-30T20:46:37Z D! [sarama] Connected to broker at chain-prd-17:9092 (registered as #2)
2020-09-30T20:46:38Z D! [sarama] client/coordinator requesting coordinator for consumergroup telegraf_metrics_consumers from chain-prd-16:9092
2020-09-30T20:46:38Z D! [sarama] client/coordinator coordinator for consumergroup telegraf_metrics_consumers is #2 (chain-prd-17:9092)
2020-09-30T20:46:38Z D! [sarama] client/metadata fetching metadata for [ucv-video-metrics ucv-voice-metrics-cube-snmp ucv-video-metrics-xapi] from broker chain-prd-16:9092
2020-09-30T20:46:38Z D! [sarama] client/metadata fetching metadata for [ucv-video-metrics ucv-voice-metrics-cube-snmp ucv-video-metrics-xapi] from broker chain-prd-16:9092
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics/4
2020-09-30T20:46:38Z D! [sarama] Connected to broker at chain-prd-16:9092 (registered as #1)
2020-09-30T20:46:38Z D! [sarama] Connected to broker at chain-prd-18:9092 (registered as #3)
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics/1
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-voice-metrics-cube-snmp/8
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-voice-metrics-cube-snmp/5
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics-xapi/4
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics-xapi/1
2020-09-30T20:46:38Z D! [sarama] consumer/broker/3 added subscription to ucv-video-metrics/2
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics/0
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-voice-metrics-cube-snmp/7
2020-09-30T20:46:38Z D! [sarama] consumer/broker/3 added subscription to ucv-voice-metrics-cube-snmp/6
2020-09-30T20:46:38Z D! [sarama] consumer/broker/3 added subscription to ucv-video-metrics-xapi/2
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics-xapi/0
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics-xapi/3
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics/3
```

In this case you can see that it is only reading from some of the partitions...  It should read from each topic which also happen to be distributed across 9 partitions on 3 brokers.

The topic that is missing data in influxDB seems to only subscribe to 5 partitions:
```
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics-xapi/0
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics-xapi/1
2020-09-30T20:46:38Z D! [sarama] consumer/broker/3 added subscription to ucv-video-metrics-xapi/2
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics-xapi/3
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics-xapi/4
```

but is missing the other 4?

**Comment by sgreszcz** [comment]
Yes, I think that this is definitely a bug on the kafka consumer input, I looked through the messages that were sent, and the ones that were read by telegraf and were written to influxDB were only in partitions 0, 1, 2, 3, and 4 (where there was no data in that partition).

Data sent to kafka
```
mra_count,host=vce-aer-201 count=381i,timestamp=1601569605000000000 1601569605000000000
mra_count,host=vce-aer-202 count=425i,timestamp=1601569606000000000 1601569606000000000
mra_count,host=vce-aer-201 count=382i,timestamp=1601569665000000000 1601569665000000000
mra_count,host=vce-aer-202 count=425i,timestamp=1601569665000000000 1601569665000000000
mra_count,host=vce-aer-201 count=384i,timestamp=1601569725000000000 1601569725000000000
mra_count,host=vce-aer-202 count=430i,timestamp=1601569725000000000 1601569725000000000
mra_count,host=vce-aer-201 count=386i,timestamp=1601569785000000000 1601569785000000000
mra_count,host=vce-aer-202 count=433i,timestamp=1601569785000000000 1601569785000000000
mra_count,host=vce-aer-201 count=388i,timestamp=1601569845000000000 1601569845000000000
mra_count,host=vce-aer-202 count=435i,timestamp=1601569845000000000 1601569845000000000
mra_count,host=vce-aer-201 count=389i,timestamp=1601569905000000000 1601569905000000000
mra_count,host=vce-aer-202 count=433i,timestamp=1601569905000000000 1601569905000000000
mra_count,host=vce-aer-201 count=388i,timestamp=1601569965000000000 1601569965000000000
mra_count,host=vce-aer-202 count=432i,timestamp=1601569965000000000 1601569965000000000
mra_count,host=vce-aer-201 count=394i,timestamp=1601570025000000000 1601570025000000000
mra_count,host=vce-aer-202 count=434i,timestamp=1601570026000000000 1601570026000000000
mra_count,host=vce-aer-201 count=387i,timestamp=1601570085000000000 1601570085000000000
mra_count,host=vce-aer-202 count=434i,timestamp=1601570086000000000 1601570086000000000
mra_count,host=vce-aer-201 count=386i,timestamp=1601570145000000000 1601570145000000000
mra_count,host=vce-aer-202 count=441i,timestamp=1601570146000000000 1601570146000000000
mra_count,host=vce-aer-201 count=386i,timestamp=1601570205000000000 1601570205000000000
mra_count,host=vce-aer-202 count=438i,timestamp=1601570206000000000 1601570206000000000
mra_count,host=vce-aer-201 count=383i,timestamp=1601570265000000000 1601570265000000000
mra_count,host=vce-aer-202 count=432i,timestamp=1601570266000000000 1601570266000000000
mra_count,host=vce-aer-201 count=381i,timestamp=1601570325000000000 1601570325000000000
mra_count,host=vce-aer-202 count=433i,timestamp=1601570326000000000 1601570326000000000
```
Reading from kafka with kafkacat:
```
kafkacat -b chain-prd-16:9092 -t ucv-video-metrics-xapi -C -f '%s \tPartition: %p\tOffset: %o\n'
mra_count,host=vce-aer-201 count=381i,timestamp=1601569605000000000 1601569605000000000 	Partition: 0	Offset: 0
mra_count,host=vce-aer-201 count=388i,timestamp=1601569845000000000 1601569845000000000 	Partition: 0	Offset: 1
mra_count,host=vce-aer-202 count=432i,timestamp=1601570266000000000 1601570266000000000 	Partition: 0	Offset: 2
mra_count,host=vce-aer-201 count=382i,timestamp=1601569665000000000 1601569665000000000 	Partition: 1	Offset: 0
mra_count,host=vce-aer-202 count=435i,timestamp=1601569845000000000 1601569845000000000 	Partition: 1	Offset: 1
mra_count,host=vce-aer-202 count=425i,timestamp=1601569665000000000 1601569665000000000 	Partition: 2	Offset: 0
mra_count,host=vce-aer-202 count=438i,timestamp=1601570206000000000 1601570206000000000 	Partition: 2	Offset: 1
mra_count,host=vce-aer-201 count=381i,timestamp=1601570325000000000 1601570325000000000 	Partition: 2	Offset: 2
mra_count,host=vce-aer-202 count=430i,timestamp=1601569725000000000 1601569725000000000 	Partition: 3	Offset: 0
mra_count,host=vce-aer-202 count=432i,timestamp=1601569965000000000 1601569965000000000 	Partition: 3	Offset: 1
mra_count,host=vce-aer-201 count=394i,timestamp=1601570025000000000 1601570025000000000 	Partition: 3	Offset: 2
mra_count,host=vce-aer-201 count=386i,timestamp=1601569785000000000 1601569785000000000 	Partition: 5	Offset: 0
mra_count,host=vce-aer-202 count=433i,timestamp=1601569785000000000 1601569785000000000 	Partition: 5	Offset: 1
mra_count,host=vce-aer-202 count=433i,timestamp=1601569905000000000 1601569905000000000 	Partition: 5	Offset: 2
mra_count,host=vce-aer-201 count=388i,timestamp=1601569965000000000 1601569965000000000 	Partition: 5	Offset: 3
mra_count,host=vce-aer-202 count=434i,timestamp=1601570086000000000 1601570086000000000 	Partition: 5	Offset: 4
mra_count,host=vce-aer-201 count=383i,timestamp=1601570265000000000 1601570265000000000 	Partition: 5	Offset: 5
mra_count,host=vce-aer-202 count=433i,timestamp=1601570326000000000 1601570326000000000 	Partition: 5	Offset: 6
mra_count,host=vce-aer-201 count=389i,timestamp=1601569905000000000 1601569905000000000 	Partition: 6	Offset: 0
mra_count,host=vce-aer-202 count=434i,timestamp=1601570026000000000 1601570026000000000 	Partition: 6	Offset: 1
mra_count,host=vce-aer-201 count=387i,timestamp=1601570085000000000 1601570085000000000 	Partition: 6	Offset: 2
mra_count,host=vce-aer-201 count=386i,timestamp=1601570145000000000 1601570145000000000 	Partition: 6	Offset: 3
mra_count,host=vce-aer-202 count=425i,timestamp=1601569606000000000 1601569606000000000 	Partition: 7	Offset: 0
mra_count,host=vce-aer-201 count=386i,timestamp=1601570205000000000 1601570205000000000 	Partition: 7	Offset: 1
mra_count,host=vce-aer-201 count=384i,timestamp=1601569725000000000 1601569725000000000 	Partition: 8	Offset: 0
mra_count,host=vce-aer-202 count=441i,timestamp=1601570146000000000 1601570146000000000 	Partition: 8	Offset: 1
```
Data exported from InfluxDB (notice that the data from partitions 5-8 (partition 4 had no data) is missing.  This matches the telegraf logs (above) that show the telegraf consumer group only reading from topic "ucv-video-metrics-xapi" from partitions 0-4!
```
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics-xapi/4
2020-09-30T20:46:38Z D! [sarama] consumer/broker/2 added subscription to ucv-video-metrics-xapi/1
2020-09-30T20:46:38Z D! [sarama] consumer/broker/3 added subscription to ucv-video-metrics-xapi/2
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics-xapi/0
2020-09-30T20:46:38Z D! [sarama] consumer/broker/1 added subscription to ucv-video-metrics-xapi/3
```

```
_measurement | host | timestamp | Kafka partition | Message offset
mra_count | vce-aer-201 | 1601569605000000000 | 0 | 0
mra_count | vce-aer-201 | 1601569665000000000 | 1 | 0
mra_count | vce-aer-201 | 1601569845000000000 | 0 | 1
mra_count | vce-aer-201 | 1601570025000000000 | 3 | 2
mra_count | vce-aer-201 | 1601570325000000000 | 2 | 2
mra_count | vce-aer-202 | 1601569665000000000 | 2 | 0
mra_count | vce-aer-202 | 1601569725000000000 | 3 | 0
mra_count | vce-aer-202 | 1601569845000000000 | 1 | 1
mra_count | vce-aer-202 | 1601569965000000000 | 3 | 3
mra_count | vce-aer-202 | 1601570206000000000 | 2 | 1
mra_count | vce-aer-202 | 1601570266000000000 | 0 | 2
```

**Comment by sgreszcz** [comment]
OK, I tried to do further testing using a single-broker kafka instance from https://docs.lenses.io/4.0/tools/box/get-started/ but I was unable to reproduce the problem as telegraf properly read from all 9 kafka partitions:
```
telegraf    | 2020-10-02T11:11:19Z D! [sarama] consumer/broker/101 added subscription to testtopic/0
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/1
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/5
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/2
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/3
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/6
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/8
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/4
telegraf    | 2020-10-02T11:11:20Z D! [sarama] consumer/broker/101 added subscription to testtopic/7
telegraf    | 2020-10-02T11:11:37Z D! [sarama] client/metadata fetching metadata for [testtopic] from broker localhost:9092
telegraf    | 2020-10-02T11:11:38Z D! [outputs.influxdb_v2] Wrote batch of 26 metrics in 15.442474ms
```

This leads me to the conclusion that telegraf is having problems with:
a) reading from multiple partitions spread over multiple broker on a three-broker kafka cluster
b) pulling for multiple topics in the same telegraf instance

I'm guessing it is "b" and I'll work on testing this by running three separate instances of telegraf, one for each topic.

Here is how I tested for the record:
1) register for a test kafka docker instance from https://docs.lenses.io/4.0/tools/box/get-started/
2) follow the procedure to start the lenses kafka container and through the web GUI make a new topic called "testtopic" with 9 partitions
3) start up another influxdb container using the documentation here: https://docs.influxdata.com/influxdb/v2.0/get-started/#download-and-run-influxdb-v2-0
4) use the InfluxDB GUI and create a new organization and bucket called "test".  Retrieve the security token for the "test" user.  Take that token and write it to a local file:
```
cat token
export INFLUX_TOKEN="-KphtA3pmqD0tTMShbOmuzN-NYUw2sfRejPYEX_LoVzbbO9ZA5bLOunVQmHYscGwtYjWRiCEbohjBuot9bP12A=="
```
5) source the env variable:
```
. ./token
```
6) write the influx line protocol data to kafka using the kafkacat app (I installed with homebrew on my mac) to read from a file:
```
kafkacat -b localhost:9092 -t testtopic -T -P -l ./influx.txt
```
7) check to see if the data is in the kafka topic via the lenses.io GUI
8) create a local telegraf.conf file
```
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "500ms"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## Maximum number of unwritten metrics per output.  Increasing this value
  ## allows for longer periods of output downtime without dropping metrics at the
  ## cost of higher maximum memory usage.
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Log at debug level.
  debug = true

[[inputs.kafka_consumer]]
  ## Kafka brokers.
  brokers = ["localhost:9092"]

  ## Topics to consume.
  topics = ["testtopic"]

  ## Maximum length of a message to consume, in bytes (default 0/unlimited);
  ## larger messages are dropped
  max_message_len = 1000000

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "influx"

# Configuration for sending metrics to InfluxDB 2.0
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ##   ex: urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]
  urls = ["http://localhost:8086"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to.
  organization = "test"

  ## Destination bucket to write into.
  bucket = "test"
```
9) run telegraf to consume from the testtopic using this docker-compose.yaml:
```
version: '2'
services:
  telegraf:
    image: telegraf:1.15.3
    container_name: telegraf
    restart: on-failure
    environment:
      - INFLUX_TOKEN
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    network_mode: host
```
10) check the telegraf logs (docker logs -f telegraf) and in influxDB to see if all the raw data made it.  In my case it did with this test, so I need to go back and try to see what is different against our production setup.
<img width="1603" alt="Screenshot 2020-10-02 at 12 38 04" src="https://user-images.githubusercontent.com/22910494/94919266-25ccd900-04ac-11eb-8532-8b99df4f05a1.png">
