### ISSUE TITLE
Receiving Transport error with GNMI Input plugin when using telegraf 1.15+  

### ISSUE THREAD

**Issue by TechDawg** [influxdata/telegraf#8208]
### Relevant telegraf.conf:

```toml
[[inputs.gnmi]]
  addresses = ["***.***.***.***:57400"]
  username = "****"
  password = "****"
  encoding = "json"
  redial = "10s"
  enable_tls = true
  tls_ca = "/certs/CAcert_l1.pem"
  tls_cert = "/certs/cert_l1.pem"
  tls_key = "/certs/servkey_l1.pem"
[[inputs.gnmi.subscription]]
    name = "Ethernet Statistics"
    origin = "NokiaState"
    path = "/state/port[port-id=6/1/1]/ethernet/statistics/"
    subscription_mode = "sample"
    sample_interval = "10s"
```

### System info:
OS: Ubuntu 18.04.5 LTS
Telegraf version: 1.15.0 + 

### Steps to reproduce:

1. Install/upgrade telegraf version 1.15.0 + from version 1.14.5

2. Configure gnmi input plugin with the configuration that is working with the previous telegraf versions.

### Expected behavior:

The device should return a stream of requested data at specified sample intervals. 

### Actual behavior:
Instead of the client authenticating and the device returning data, I am receiving an error shown below. 

When I downgrade telegraf back to versions 1.14.0-1.14.5, the subscription is established successfully.. 

### Additional info:
`2020-10-01T13:23:42Z I! [agent] Hang on, flushing any cached metrics before shutdown
2020-10-01T13:23:42Z I! Loaded inputs: gnmi snmp
2020-10-01T13:23:42Z I! Loaded aggregators: 
2020-10-01T13:23:42Z I! Loaded processors: converter printer
2020-10-01T13:23:42Z I! Loaded outputs: influxdb_v2 kafka
2020-10-01T13:23:42Z I! Tags enabled: host=dv-telegraf
2020-10-01T13:23:42Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"dv-telegraf", Flush Interval:10s
2020-10-01T13:23:42Z E! [inputs.cisco_telemetry_gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
2020-10-01T13:23:52Z E! [inputs.cisco_telemetry_gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
2020-10-01T13:24:02Z E! [inputs.cisco_telemetry_gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
2020-10-01T13:24:12Z E! [inputs.cisco_telemetry_gnmi] Error in plugin: failed to setup subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
2020-10-01T13:24:43Z I! [agent] Hang on, flushing any cached metrics before shutdown`
