### ISSUE TITLE
SQLServer plugin shows wrong latency values

### ISSUE THREAD

**Issue by iatalay** [influxdata/telegraf#8227]
### Relevant telegraf.conf:

```toml
[[inputs.sqlserver]]
  servers = ["Server=localhost;Port=1433;User Id=usrtelegraf;Password=xxxxxxx;app name=telegraf;log=1;",]
  query_version = 2
```

### System info:

Windows Server 2016

### Steps to reproduce:

1. Configure telegraf to monitor sqlserver using inputs.sqlserver
2. Start telegraf servis
3. Go to grafana and add new graph
4. Add follwing query to see Read latency metrics

SELECT non_negative_derivative(mean("read_latency_ms"), 1s) FROM "sqlserver_database_io" WHERE ("sql_instance" =~ /^$Instance$/ AND "file_type" = 'DATA' AND "database_name" !~ /^(msdb|model|master)/) AND $timeFilter GROUP BY time($__interval), "database_name"

### Expected behavior

SQL server shows us avg latency around 3 ms.

![sql-query](https://user-images.githubusercontent.com/2380953/95179365-33929f00-07c9-11eb-96c4-611dc780b254.jpg)
![expected-behavior](https://user-images.githubusercontent.com/2380953/95179371-34c3cc00-07c9-11eb-93e9-afb23788bb86.jpeg)

### Actual behavior:

We see latecy values around 100 ms

![actual-behavior](https://user-images.githubusercontent.com/2380953/95179376-355c6280-07c9-11eb-8ace-b279ee354ac9.jpg)

### Additional info:

Telegraf Version:
Telegraf 1.13.4 (git: HEAD ffabd6b5)
