### ISSUE TITLE
mongodb plugin logs error when polling arbiter

### ISSUE THREAD

**Issue by chadshowalter** [influxdata/telegraf#8230]
### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]

[[inputs.mongodb]]

  servers = [
    "mongodb://primary:27017", "mongodb://secondary:27018", "mongodb://arbiter:27019"
  ]
  gather_perdb_stats = true
```

### System info:

docker image from docker hub: telegraf-alpine:1.15.3
mongodb image from docker hub: mongo:4.0

### Docker
I reproduced the problem by running the following set of containers.  
```
version: '2'
services:
  primary:
    image: "mongo:4.0"
    ports:
      - 27017:27017
    restart: "always"
    command: --replSet myReplSet --enableMajorityReadConcern=false
  secondary:
    image: "mongo:4.0"
    ports:
      - 27018:27018
    restart: "always"
    command: --replSet myReplSet --port 27018 --enableMajorityReadConcern=false
  arbiter:
    image: "mongo:4.0"
    ports:
      - 27019:27019
    restart: "always"
    command: --replSet myReplSet --port 27019 --enableMajorityReadConcern=false
  telegraf:
    image: "telegraf:1.15.3-alpine"
    restart: "always"
    hostname: "local"
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: "influxdb:1.8.3-alpine"
    restart: "always"
    ports:
      - 8086:8086
    hostname: "local"
```

### Steps to reproduce:

1. Run 3 member repl set (primary, secondary, arbiter) where each member is an instance of the mongo:4.0 docker image, e.g., the docker compose file shown above will work. 
2. After the initial launch, set up the repl set by connecting a mongo client to the primary node and running the following command:
```
rs.initiate(
{
          "_id": "myReplSet",
          version: 1,
          "members": [
          {"_id": 0, "host": "primary:27017", "priority": 1 },
          {"_id": 1, "host": "secondary:27018", "priority": 0},
          {"_id": 2, "host": "arbiter:27019", "arbiterOnly": true }
          ]}
)
```

### Expected behavior:

Normal logging; no errors.

### Actual behavior:

The telegraf container logs the following at regular intervals:
```
telegraf_1   | 2020-10-06T20:44:39Z E! [inputs.mongodb] Unable to get oplog stats: not found
```

### Additional info:

If I remove the arbiter from telegraf config, the error logs stop. By code inspection, it appears that the error is logged by code that expects either the oplog.rs or oplog.$main collections to exist in the local database in each of the repl set members.  In the case of the arbiter, neither of these collections exists.

My telegraf.conf file:
[telegraf.conf.zip](https://github.com/influxdata/telegraf/files/5342538/telegraf.conf.zip)

**Comment by akrantz01** [comment]
This appears to be fixed in the latest version of telegraf. The release can be found [here](https://github.com/influxdata/telegraf/releases/latest), and it is also available on [Docker Hub](https://hub.docker.com/_/telegraf).

**Comment by chadshowalter** [comment]
This issue is still there with the latest telegraf and mongo.  Consider this set of containers:


```
version: '2'
services:
  primary:
    image: "mongo:6.0.3"
    ports:
      - 27017:27017
    restart: "always"
    command: --replSet myReplSet
  secondary:
    image: "mongo:6.0.3"
    ports:
      - 27018:27018
    restart: "always"
    command: --replSet myReplSet --port 27018
  arbiter:
    image: "mongo:6.0.3"
    ports:
      - 27019:27019
    restart: "always"
    command: --replSet myReplSet --port 27019
  telegraf:
    image: "telegraf:1.25.0-alpine"
    restart: "always"
    hostname: "local"
    environment:
      INFLUX_URL: http://influx:8086
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: "influxdb:1.8.10-alpine"
    restart: "always"
    ports:
      - 8086:8086
    hostname: "local"
```


Note also that we now need to include /?connect=direct on the mongodb urls in the config, e.g. 
```
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]

[[inputs.mongodb]]

  servers = [
    "mongodb://primary:27017/?connect=direct", "mongodb://secondary:27018/?connect=direct", "mongodb://arbiter:27019/?connect=direct"
  ]
  gather_perdb_stats = true
```
Here is the logging that I see repeated when running with this set of containers above:
```
telegraf_1   | 2022-12-28T17:30:50Z D! [inputs.mongodb] Previous collection has not completed; scheduled collection skipped
telegraf_1   | 2022-12-28T17:30:50Z W! [inputs.mongodb] Collection took longer than expected; not complete after interval of 10s
telegraf_1   | 2022-12-28T17:31:00Z E! [inputs.mongodb] Unable to get oplog stats: mongo: no documents in result
telegraf_1   | 2022-12-28T17:31:01Z D! [inputs.mongodb] Unable to gather cluster status: (NotPrimaryOrSecondary) node is not in primary or recovering state
```

Can we re-open this ticket?  Otherwise, I can create another.  Let me know what you would prefer.
