### ISSUE TITLE
inputs.kinesis_consumer - Ingestion stops after changing number of shards

### ISSUE THREAD

**Issue by madamak** [influxdata/telegraf#8253]
### Relevant telegraf.conf:
```toml
[global_tags]
[agent]
  interval = "1s"
  round_interval = false
  metric_batch_size = 5000
  metric_buffer_limit = 1000000
  collection_jitter = "0s"
  flush_interval = "5s"

  flush_jitter = "1s"
  precision = "s"
  debug = true
  quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.influxdb]]
  urls = ["http://10.124.65.79:8086"]
  flush_interval = "10s"
  flush_jitter = "5s"
  database = "telegraf"
  skip_database_creation = true
  timeout = "5s"

[[inputs.kinesis_consumer]]
  region = "eu-west-1"
  # endpoint_url = ""
  streamname = "mystreamname"
  # shard_iterator_type = "TRIM_HORIZON"
  max_undelivered_messages = 100
  ## Data format to consume.
  data_format = "influx"
  [inputs.kinesis_consumer.checkpoint_dynamodb]
	app_name = "telegraf-1"
	table_name = "pocrealtime-telegraf"
```

### System info:
OS - Ubuntu
Telegraf - v1.15.3 - On an EC2 instance
InfluxDB - v1.8 - On another EC2 instance

### Steps to reproduce:
1. Start Kinesis agent
2. Ingestion running fine
3. Change number of shards in the source Kinesis Input

### Expected behavior:
Ingestion of records from Kinesis should continue.

### Actual behavior:
Agent stops getting metrics. There is nothing in the Telegraf agent logs from the input.kinesis_consumer, but in AWS CloudWatch we can see that there are no GetRecords operation on our stream.

### Additional info:
We have tried:
- Restarting the Telegraf service. 
- Rebooting the instance machine. 
- Erasing all entries in the DynamoDB checkpoint base.
- Reverting back to 5 shards
In every case what happens is that ingestion starts for a few moments then stops.
We know for sure that our Kinesis data stream is full of records to ingest.

Example logs attached.
[telegraf.log](https://github.com/influxdata/telegraf/files/5356063/telegraf.log)
