### ISSUE TITLE
[azure_monitor] Cannot use empty string as the nampspace prefix

### ISSUE THREAD

**Issue by ethanshea-ms** [influxdata/telegraf#8256]
### Relevant telegraf.conf:

```toml
[[outputs.azure_monitor]]
  namespace_prefix = ""

# For debugging
[[outputs.file]]
  data_format = "influx"
  files = ["stdout"]
```

### System info:

Telegraf 1.15.3

### Steps to reproduce:

1. Run telegraf with the above configuration

### Expected behavior:

Metrics are emitted to azure monitor in the AZM namespace which matches the field name.

### Actual behavior:

Metrics are emitted to azure monitor in the AZM namespace `telegraf/{fieldName}`.

### Additional info:

[This](https://github.com/influxdata/telegraf/blob/a8810b2b7ae93000105b20842cb7ffb5cf94d6f8/plugins/outputs/azure_monitor/azure_monitor.go#L158-L160) seems to be the suspect part of the code. Can it be compared to `nil` instead of the empty string?

As a side note, the [regex](https://github.com/influxdata/telegraf/tree/master/plugins/processors/regex) processor may be a better solution to add namespace prefixes.

~ATTN: @ danielnelson~
