### ISSUE TITLE
Telegraf Panic and won't restart

### ISSUE THREAD

**Issue by robanderson** [influxdata/telegraf#8258]
### Relevant telegraf.conf:

```toml
[[outputs.influxdb_v2]]

  urls = ["https://us-west-2-1.aws.cloud2.influxdata.com"]

  ## Token for authentication.
  token = "my token here, not included for security"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "robanderson@me.com"

  ## Destination bucket to write into.
  bucket = "15thValley"


[[inputs.mqtt_consumer]]
  servers = ["tcp://127.0.0.1:1883"]
  qos = 0
  topics = ["InfluxDB/Sensors/#"]
  data_format = "value"
  data_type = "float"
#  data_format = "influx"
  max_undelivered_messages = 1000
```

### System info:

telegraf-1.15.3                     telegraf-1.15.3_linux_armhf.tar.gz

running Telegraf on Linksys WRT32x Router

Hostname	15Valley-P2
Model	Linksys WRT32X
Architecture	ARMv7 Processor rev 1 (v7l)
Firmware Version	OpenWrt 19.07.4 r11208-ce6496d796 / LuCI openwrt-19.07 branch git-20.247.75781-0d0ab01
Kernel Version	4.14.195

### Steps to reproduce:

Was working fine then over night it stopped working and telegraf no longer restarts

### Actual behavior:

root@15Valley-P2:~# telegraf -version
runtime: g1: frame.sp=0x499ffcc top=0x499ffe4
	stack=[0x4980000-0x49a0000] n=3 max=2147483647
fatal error: traceback did not unwind completely

runtime stack:
runtime.throw(0x1f165c7, 0x23)
	/usr/local/go/src/runtime/panic.go:1116 +0x5c
runtime.gentraceback(0x5e1ac, 0x499ff9c, 0x0, 0x44000e0, 0x0, 0x0, 0x7fffffff, 0xbee97d7c, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/traceback.go:559 +0x14f0
runtime.addOneOpenDeferFrame.func1()
	/usr/local/go/src/runtime/panic.go:721 +0x8c
runtime.systemstack(0x76dc8)
	/usr/local/go/src/runtime/asm_arm.s:347 +0x84
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1041

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm.s:294 +0x4 fp=0x499ff20 sp=0x499ff1c pc=0x76ed0
runtime.addOneOpenDeferFrame(0x44000e0, 0x5e1ac, 0x499ff9c)
	/usr/local/go/src/runtime/panic.go:720 +0x60 fp=0x499ff3c sp=0x499ff20 pc=0x44e10
panic(0x1b63280, 0x375a708)
	/usr/local/go/src/runtime/panic.go:929 +0xa4 fp=0x499ff9c sp=0x499ff3c pc=0x453f4
runtime.panicmem(...)
	/usr/local/go/src/runtime/panic.go:212
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:695 +0x31c fp=0x499ffb4 sp=0x499ff9c pc=0x5e1ac
runtime.doInit(0x1)
	/usr/local/go/src/runtime/proc.go:5412 +0x58 fp=0x499ffcc sp=0x499ffb8 pc=0x55974
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:857 +0x4 fp=0x499ffcc sp=0x499ffcc pc=0x78c48

goroutine 5 [select]:
go.opencensus.io/stats/view.(*worker).start(0x45a3740)
	/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0xb0
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x48
