### ISSUE TITLE
inputs.opcua: schema improvements and fix static tag additions

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#8270]
Current defects with existing inputs.opcua plugin

#### Broken Static tag additions
The current plugin config accepts them (standard Telegraf). In this plugin code the measurement is only given tags from the data acquired from OPC-UA. `[opcua.tags]` is broken and does not alert
 - Expected: 
`[opcua.tags]`need to be able to add static tags and Telegraf needs to error on incorrect configuration

#### Schema improvements
The config for a Node in the configuration takes a ’name’ but this is used as the value of the “name” field in the code and the name of the field that contains the value received from OPC-UA in the code. 

- Current schema: 
`[tag {name="x”}, field{x=<value>}]`
- Expected: 
Default to a field named `value` with an optional `name_override` config to change it to something else.

**Comment by sjwang90** [comment]
Current Config:
```toml
[[outputs.influxdb]]
    urls = ["http://xxxxx:8086"]
    database = "telegraf"
    timeout = "0s"
    username = "influx"
    password = "*****"
    retention_policy = ""
[outputs.influxdb.tagpass]
        source = ["telegraf"]

[[inputs.mem]]
[inputs.mem.tags]
    source = "telegraf"
[[inputs.net]]
[inputs.net.tags]
    source = "telegraf"
[[inputs.system]]
[inputs.system.tags]
    source = "telegraf"

[[inputs.opcua_client]]
name = "hostname1"
endpoint = "opc.tcp://xxxxx:12345"
timeout = 60
time_interval = "10s"
security_policy = "None"
security_mode = "None"
nodes = [
                {name="2001_A01", namespace="2", identifier_type="s", identifier="B123_U_XX01.ABCD.A01", data_type="float", description="hostname1 node 01 abcd 2001"},
		{name="2001_A02", namespace="2", identifier_type="s", identifier="B123_U_XX01.ABCD.A02", data_type="float", description="hostname1 node 02 abcd 2001"},
		{name="2001_A03", namespace="2", identifier_type="s", identifier="B123_U_XX01.ABCD.A03", data_type="float", description="hostname1 node 03 abcd 2001"},
....
		]

[[inputs.opcua_client]]
name = "hostname2"
endpoint = "opc.tcp://xxxxx:56789"
timeout = 60
time_interval = "10s"
security_policy = "None"
security_mode = "None"
nodes = [
                {name="2001_AB01", namespace="2", identifier_type="s", identifier="B123_U_XX01.AVG.AB01", data_type="float", description="hostname2 01 abcd 2001"},
		{name="2001_AB02", namespace="2", identifier_type="s", identifier="B123_U_XX01.AVG.AB02", data_type="float", description="hostname2 02 abcd 2001"},
		{name="2001_AB03", namespace="2", identifier_type="s", identifier="B123_U_XX01.AVG.AB03", data_type="float", description="hostname2 03 abcd 2001"},
....
]
```

Desired config:
Include static tag addition to route metrics to one database versus another. 
```toml
[inputs.opcua.tags]
    source = "telegraf"
```
