### ISSUE TITLE
input exec windows cmd command and double quotes not rendered 

### ISSUE THREAD

**Issue by vincent-gou** [influxdata/telegraf#8294]
### Relevant telegraf.conf:

```toml
  [[inputs.exec]]
  commands = ['''cmd /c "@echo off & for /f %F in (c:/temp/talend_version.log) do echo tag="tag_value" talend_component="%F"" ''']
  name_override = "talend_plugin_version_display"
  data_format = "influx"
```

### System info:
Telegraf versionbelow running on Windows 2016
![image](https://user-images.githubusercontent.com/46958513/96646742-e49e4b00-132c-11eb-8e24-371c9871a7af.png)

### Docker

Not running through Docker.

### Steps to reproduce:

1. Run following command in Windows command prompt as administrator or local user
```
cmd /c "@echo off & for /f %F in (c:/temp/talend_version.log) do echo tag=tag_value talend_component="%F""
```
Content of c:/temp/talend_version.log
```
a00preparefilefrompgitoxnet_5_92 
a00preparefileretourxnet_1_28 
b00transfertreferentieltoxnet_0_12 
b00transfertretourpgi_1_11 
c00deployfilefrompgitoxnet_2_60 
c00deployfileretourxnet_1_39 
c00deployfileretourxnet_1_40 
e00remoteexectomcat_0_10 
e01remoteexecjoomla_1_10 
```
Command output display correctly double-quote:
![image](https://user-images.githubusercontent.com/46958513/96647247-99d10300-132d-11eb-89a6-9efd0fa062e0.png)

2. While running through telegraf field error since double quotes are not correctly rendered:
```
2020-10-20T21:40:58Z E! [inputs.exec] Error in plugin: metric parse error: expected field at 1:32: "tag=tag_value talend_component=a00preparefilefrompgitoxnet_5_92"
```
![image](https://user-images.githubusercontent.com/46958513/96647388-d270dc80-132d-11eb-9f7a-30e05fadda78.png)

### Expected behavior:

Should render double quotes in influx data_format to be correctly inserted in Influxdb.

### Actual behavior:

metric parse error...

### Additional info:

With data_format = "value" no erreors but i can't insert it in Influxdb.
![image](https://user-images.githubusercontent.com/46958513/96647628-51661500-132e-11eb-9800-328465376c1f.png)

Thanks.

Vincent
