### ISSUE TITLE
Wireguard Plugin - "Error in plugin: error enumerating Wireguard devices: operation not permitted"

### ISSUE THREAD

**Issue by victorbrca** [influxdata/telegraf#8302]
### Relevant telegraf.conf:

**Config 1**
```toml
# # Collect Wireguard server interface and peer statistics
[[inputs.wireguard]]
#   ## Optional list of Wireguard device/interface names to query.
#   ## If omitted, all Wireguard interfaces are queried.
  #devices = ["wg0-server"]
```

**Config 2**
```toml
# # Collect Wireguard server interface and peer statistics
[[inputs.wireguard]]
#   ## Optional list of Wireguard device/interface names to query.
#   ## If omitted, all Wireguard interfaces are queried.
  devices = ["wg0-server"]
```

**Config 3**
```toml
# # Collect Wireguard server interface and peer statistics
[[inputs.wireguard]]
#   ## Optional list of Wireguard device/interface names to query.
#   ## If omitted, all Wireguard interfaces are queried.
  devices = ["wg0"]
```

### System info:

```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core
```
```
$ rpm -qa | grep telegraf
telegraf-1.15.3-1.x86_64
```

```
$ wg | grep interface
interface: wg0-server
```

### Steps to reproduce:

1. Configure wireguard server
2. Configure the wireguard collector in telegraf
3. Restart the service

### Expected behavior:

Wireguard data to be populated in the database.

### Actual behavior:

**Config 1:**
```
Oct 22 13:52:10 centos telegraf[4985]: 2020-10-22T17:52:10Z E! [inputs.wireguard] Error in plugin: error enumerating Wireguard devices: operation not permitted
```

**Config 2:**
```
Oct 22 13:52:50 centos telegraf[5810]: 2020-10-22T17:52:50Z W! [inputs.wireguard] No Wireguard device found with name wg0-server
```

**Config 3:**
```
Oct 22 13:53:40 centos telegraf[5936]: 2020-10-22T17:53:40Z W! [inputs.wireguard] No Wireguard device found with name wg0
```
