### ISSUE TITLE
inputs.procstat causes cpu spikes - 16.x does not fix the procstat issue.

### ISSUE THREAD

**Issue by Kedesai** [influxdata/telegraf#8339]
### Relevant telegraf.conf:

```toml
# # Monitor process cpu and memory usage
 [[inputs.procstat]]
#   ## PID file to monitor process
#   pid_file = "/var/run/nginx.pid"
#   ## executable name (ie, pgrep <exe>)
#   # exe = "nginx"
#   ## pattern as argument for pgrep (ie, pgrep -f <pattern>)
     pattern = ".*"
#   ## user as argument for pgrep (ie, pgrep -u <user>)
#   # user = "nginx"
#   ## Systemd unit name
#   # systemd_unit = "nginx.service"
#   ## CGroup name or path
#   # cgroup = "systemd/system.slice/nginx.service"
#
#   ## Windows service name
#   # win_service = ""
#
#   ## override for process_name
#   ## This is optional; default is sourced from /proc/<pid>/status
#   # process_name = "bar"
#
#   ## Field name prefix
#   # prefix = ""
#
#   ## When true add the full cmdline as a tag.
#   # cmdline_tag = false
#
#   ## Add PID as a tag instead of a field; useful to differentiate between
#   ## processes whose tags are otherwise the same.  Can create a large number
#   ## of series, use judiciously.
#   # pid_tag = false
#
#   ## Method to use when finding process IDs.  Can be one of 'pgrep', or
#   ## 'native'.  The pgrep finder calls the pgrep executable in the PATH while
#   ## the native finder performs the search directly in a manor dependent on the
#   ## platform.  Default is 'pgrep'
#   # pid_finder = "pgrep"
 [inputs.procstat.tags]
     tag = "procstat"

```

### System info:

 RHEL 7.316.x downloaded 10/29/2020.

### Steps to reproduce:

1. ...enable procstat plugin on a  telegraf 1.16.x released version
2. ... 

### Expected behavior:

cpu keeps spiking to 35 % every few seconds. Once this plugin is stopped the spikes go away.

### Additional info:

![image](https://user-images.githubusercontent.com/15807296/97629364-9c012480-19f3-11eb-8346-2b314726741e.png)
