### ISSUE TITLE
cgroups input ignores machine-qemu\x2d1\x2dvmname.scope directory

### ISSUE THREAD

**Issue by slynn1324** [influxdata/telegraf#8340]
### Relevant telegraf.conf:

```toml
# # Read specific statistics per cgroup
[[inputs.cgroup]]
#   ## Directories in which to look for files, globs are supported.
#   ## Consider restricting paths to the set of cgroups you really
#   ## want to monitor if you have a large number of cgroups, to avoid
#   ## any cardinality issues.
#   # paths = [
#   #   "/cgroup/memory",
#   #   "/cgroup/memory/child1",
#   #   "/cgroup/memory/child2/*",
#   # ]
    paths = [
        "/rootfs/sys/fs/cgroup/cpu/lxc.payload.*",
        "/rootfs/sys/fs/cgroup/cpu/machine.slice/machine-qemu*"
    ]
#    files = ["memory.*usage*", "memory.limit_in_bytes"]
#   ## cgroup stat fields, as file names, globs are supported.
#   ## these file names are appended to each path from above.
#   # files = ["memory.*usage*", "memory.limit_in_bytes"]
    files = ["cpuacct.usage"]
```

### System info:

Telegraf 1.16.0 in Docker (with appropriate rootfs mapped)
Ubuntu 20.04.1 

### Steps to reproduce:

1. ...  Run a VM with KVM+Libvirt
2. ... The above configuration will NOT pick up the cpuacct.usage statistic for /sys/fs/cgroup/cpu/machine.slice/machine-qemu*.  

### Expected behavior:

cgroup stats are read as normal

### Actual behavior:

Directory is ignored.  Additional directories are picked up as normal.

### Additional info:

I'm assuming this is due to the odd directory names that libvirt creates for each vm, but my Go skills are sparse to determine where the error might be in the cgroup plugin.  

As a work-around, I was able to create symlinks to a different directory ( e.g., /libvirt_cgroup/cpu/nginx -> '../../sys/fs/cgroup/cpu/machine.slice/machine-qemu\x2d1\x2dnginx.scope/'), and update the configuration to point to the new directory of symlinks - and it works correctly -- further enforcing that something with the '\x2' in the directory name is a likely culprit.
