### ISSUE TITLE
problem with regexp and converter string to float conversion

### ISSUE THREAD

**Issue by mikkoss** [influxdata/telegraf#8355]
### Relevant telegraf.conf:

```toml

[[processors.regex]]
 [[processors.regex.fields]]
    key = "DataReductionRatio"
    pattern = "^([0-9]+(?:\\.[0-9]+)?):(\\d)"
    replacement = "${1}"
    result_key = "DataReductionRatio-float"

 [[processors.regex.fields]]
    key = "DeduplicationRatio"
    pattern = "^([0-9]+(?:\\.[0-9]+)?):(\\d)"
    replacement = "${1}"
    result_key = "DeduplicationRatio-float"

 [[processors.regex.fields]]
    key = "CompressionRatio"
    pattern = "^([0-9]+(?:\\.[0-9]+)?):(\\d)"
    replacement = "${1}"
    result_key = "CompressionRatio-float"

[[processors.converter]]
 [processors.converter.fields]
  float = ["DataReductionRatio-float", "DeduplicationRatio-float", "CompressionRatio-float"]


```

### System info:
telegraf-1.14.5-1 and later tested
Rhel 8 OS 

### Steps to reproduce:

hi,

I have an odd problem with regexp and converter in telegraf. I am getting an string reply from SNMP which I want to convert to float in a new result_key.

Data the snmp get's is for example:
DataReductionRatio: 1.935:1

which I want to save to a new field: DataReductionRatio-float
I have following regexp and converter configured in main telegraf.conf and then snmp collectors are in their own files in conf.d directory.

### Expected behavior:

First string is cut with regexp to remove the ":1" part of the reply, then it's converted from string to float and saved to new result_key in influxdb.

### Actual behavior:

This works now and then randomly when I restart thre telegraf agent, but now and then I do get errors:

[outputs.influxdb] When writing to [http://127.0.0.1:8086]: received error partial write: field type conflict: input field "DataReductionRatio-float" on measurement "hw_storagepool" is type string, already exists as type float dropped=1; discarding points

Is there some order that have to be specified to have this work every time? or is this a bug? 

### Additional info:

Attached picture of grafana graph.
<img width="1091" alt="screenshot" src="https://user-images.githubusercontent.com/65343082/97976538-7d27d700-1dd3-11eb-9aad-9116a870943e.png">
