### ISSUE TITLE
After updating config.go, settings for parsers and measurement names are not taken

### ISSUE THREAD

**Issue by M0rdecay** [influxdata/telegraf#8362]
### Relevant telegraf.conf:
```toml
[[inputs.file]]
  files = [ "data.xml" ]
  name_override = "measurement_1"
  data_format = "value"
  data_type = "string"
```

### Expected behavior:
The telegraf will work with this configuration

### Actual behavior:
`2020-11-04T10:19:56Z E! [telegraf] Error running agent: Error loading config file some_data.conf: plugin inputs.file: line 1: configuration specified the fields ["name_override" "data_type"], but they weren't used`

### Additional info:
I ran into this while testing after updating my branch after merging this PR - https://github.com/influxdata/telegraf/pull/7583.
Parameters for the parser are now marked as unused.

After that, I builded telegraf from the master branch, after which I encountered the error described above.

@ssoroka, take a look, please. The situation is reproduced on the `master` build.
