### ISSUE TITLE
Error - configuration specified the fields ["__something__"], but they weren't used

### ISSUE THREAD

**Issue by Trovalo** [influxdata/telegraf#8417]
### Relevant telegraf.conf:
```toml
# Collect statistics about itself
[[inputs.internal]]
  ## If true, collect telegraf memory stats.
  # collect_memstats = true
  [inputs.internal.tags]
    telegraf_instance = "Telegraf Gateway"
```

Here is the error  I get
```
2020-11-16T15:53:50Z E! [telegraf] Error running agent: Error loading config file configuration\gateway\telegraf.d\input_internal.conf: plugin inputs.internal: line 3: configuration specified the fields ["tags"], but they weren't used
```

### System info:
- Windows Server
- Equivalent to Telegraf Nightly (I usually make my own build)

### Steps to reproduce:

- Specify some additional static tags in an input plugin using the `[inputs._inputname_.tags]`
In my case I've just used the internal plugin, but I think the issue present itself on any plugin.

### Expected behavior:
The configuration is valid and everything runs

### Actual behavior:
an error happens
