### ISSUE TITLE
RAM usage grows when installing Telegraf without any configuration

### ISSUE THREAD

**Issue by mcassaniti** [influxdata/telegraf#8427]
When the Telegraf agent is installed on Linux and is not configured (because someone forgot to configure it) the RAM usage continues to increase. This may take days to become an apparent issue.

### Relevant telegraf.conf:

```toml
# Default Debian/Ubuntu Linux configuration with comments stripped

[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
```

### System info:

<u>Version:</u> 1.15.3
<u>OS:</u> Ubuntu Linux 18.04.5 LTS
<u>Configuration:</u> Not modified from initial installation

### Steps to reproduce:

1. Install Telegraf and start service without changing configuration. Why? because you forgot to configure the Telegraf agent.
2. Leave the agent running well after the default buffer fills.

### Expected behavior:

RAM usage stays relatively constant.

### Actual behavior:

The RAM usage slowly grows. It may take several days to become an apparent issue. For example, on a machine with 4GB of RAM it may take 2 weeks to consume 20% of RAM.
