### ISSUE TITLE
Proxmox: "search domain is not set"

### ISSUE THREAD

**Issue by stenehall** [influxdata/telegraf#8437]
### Relevant telegraf.conf:

```toml
[[inputs.proxmox]]
  base_url = "https://...:8006/api2/json"
  api_token = "telegraf@pam!telegraf=..."
  insecure_skip_verify = true
```

### System info:
Telegraf 1.16.2 tested on docker and on OSX
Proxmox 6.2-15

### Steps to reproduce:

1. Empty `telegraf.conf` file except for above 
2. Run `telegraf --config telegraf.conf --input-filter proxmox --test`

### Expected behavior:

I would assume this to not return an error

### Actual behavior:

outputs:
```
2020-11-19T14:24:38Z I! Starting Telegraf 1.16.2
2020-11-19T14:24:38Z E! [inputs.proxmox] Error in plugin: search domain is not set
2020-11-19T14:24:38Z E! [telegraf] Error running agent: input plugins recorded 1 errors
```

### Additional info:

Trying to access the proxmox api directly give me 

```{"data":{"search":"local","dns2":"1.1.1.1","dns1":"8.8.8.8"}}```

and checking it using `pvesh get /nodes/<node>/dns` gives me the same values.

I'm not actually sure if this is me completely missing something in the setup or not but could confirm the behaviour with one other person. Looking at the [struct](https://github.com/influxdata/telegraf/blob/fb463bcc179857aa3dfd00288d1e9c2b4ef51f86/plugins/inputs/proxmox/structs.go#L67) it seems to suggest that everything should work.
