### ISSUE TITLE
Telegraf tail not working after "cannot allocate memory" error

### ISSUE THREAD

**Issue by naveenabt** [influxdata/telegraf#8448]
### Relevant telegraf.conf:

```toml
[agent]
    interval = "10s"
    round_interval = true
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    collection_jitter = "0s"
    flush_interval = "10s"
    flush_jitter = "0s"
    precision = ""
    debug = false
    quiet = true
    logtarget = "file"
    logfile = "/var/log/telegraf/telegraf.log"
    hostname = ""
    omit_hostname = false
    logfile_rotation_interval = "1d"
    logfile_rotation_max_archives = 7
```

### System info:
Telegraf version: 1.13
operating system: Amazon Linux

### Docker

Running Telegraf in docker

### Steps to reproduce:

1. ... Log more data to log file using concurrent request
2. ... Once memory full, getting below error.

E! [inputs.tail] Tailing \"app_logs.log\": Error reading app_logs.log: read app_logs.log: cannot allocate memory"

### Expected behavior:

Once memory available, it should tail the data from log file

### Actual behavior:

Currently it is not sending metrics after memory issue

### Additional info:

Telegraf Error:

E! [inputs.tail] Tailing \"app_logs.log\": Error reading app_logs.log: read app_logs.log: cannot allocate memory"
