### ISSUE TITLE
Multiple tail input instances with inotify not working as expected

### ISSUE THREAD

**Issue by leopoldsedev** [influxdata/telegraf#8449]
### Relevant telegraf.conf:

```toml
[[outputs.file]]
  files = ["stdout"]
  data_format = "influx"

[[inputs.tail]]
  name_override = "tail1"

  files = ["/config/telegraf/test.log"]
  from_beginning = false
  watch_method = "inotify"

  data_format = "value"
  data_type = "string"

[[inputs.tail]]
  name_override = "tail2"

  files = ["/config/telegraf/test.log"]
  from_beginning = false
  watch_method = "inotify"

  data_format = "value"
  data_type = "string"
```

### System info:

```
$ telegraf --version
Telegraf 1.16.2 (git: release-1.16 962082f6)
$ cat /etc/issue
Ubuntu 20.04.1 LTS
$ uname -ris
Linux 5.4.0-53-generic x86_64
```

### Steps to reproduce:

Run
```
$ telegraf --config test.conf
```
and then in another terminal
```
$ echo "line 1" >> /config/telegraf/test.log
$ echo "line 2" >> /config/telegraf/test.log
$ echo "line 3" >> /config/telegraf/test.log
```

### Expected behavior:

In the terminal where telegraf is running, something like
```
[after first echo]
tail1,host=server,path=/config/telegraf/test.log value="line 1" 1606042136271573374
tail2,host=server,path=/config/telegraf/test.log value="line 1" 1606042136271573364
[after second echo]
tail1,host=server,path=/config/telegraf/test.log value="line 2" 1606042142526207498
tail2,host=server,path=/config/telegraf/test.log value="line 2" 1606042142526220753
[after third echo]
tail1,host=server,path=/config/telegraf/test.log value="line 3" 1606042152533259345
tail2,host=server,path=/config/telegraf/test.log value="line 3" 1606042152533300898
```

### Actual behavior:

```
[after first echo]
tail1,host=server,path=/config/telegraf/test.log value="line 1" 1606042481061620892
[after second echo]
tail2,host=server,path=/config/telegraf/test.log value="line 1" 1606042532796022014
tail2,host=server,path=/config/telegraf/test.log value="line 2" 1606042532796048376
[after third echo]
tail1,host=server,path=/config/telegraf/test.log value="line 2" 1606042545797547384
tail1,host=server,path=/config/telegraf/test.log value="line 3" 1606042545797574024
```

### Additional info:
It seems like the inotify event only arrives at one tail plugin instance (either tail1 or tail2) for every file append.
It seems to be random which tail instance receives the first append, and for subsequent appends it seems to alternate between the instances.
Using `poll` for both instances yields the expected behavior.
