### ISSUE TITLE
http_response plugin have issues when urls list contains IPv4 and IPv6 addresses

### ISSUE THREAD

**Issue by zak-pawel** [influxdata/telegraf#8451]
Issue is present only when `interface` is set to proper value in `telegraf.conf`

### Relevant telegraf.conf for Windows:
```toml
[[inputs.http_response]]
  ## List of urls to query.
  urls = ["http://127.0.0.1:15000/hello", "http://[::1]:15000/hello"]

  ## Interface to use when dialing an address
  interface = "Loopback Pseudo-Interface 1"
```

### Relevant telegraf.conf for Linux:
```toml
[[inputs.http_response]]
  ## List of urls to query.
  urls = ["http://127.0.0.1:15000/hello", "http://[::1]:15000/hello"]

  ## Interface to use when dialing an address
  interface = "lo"
```

### System info:
1. Telegraf 1.16.2 (but probably there is problem since `interface` was added to plugin here: https://github.com/influxdata/telegraf/pull/6006 - so from Telegraf 1.12.0)
2. Windows 10 Pro and Ubuntu 18

### Steps to reproduce:
1. Start web server which listens on the TCP6 and TCP4 networks. For example:
```
	http.HandleFunc("/hello", func(writer http.ResponseWriter, request *http.Request) {
		fmt.Fprintf(writer, "hello\n")
	})
	http.ListenAndServe(":15000", nil)
```
2. Verify that web server responds successfully for `http://127.0.0.1:15000/hello` and `http://[::1]:15000/hello` (using web browser or `curl`)
3. Run Telegraf in Windows with given config (be sure that proper name of loopback interface is used).
4. Run Telegraf in Linux with given config (be sure that proper name of loopback interface is used).

### Expected behavior:
1. Web server starts successfully.
2. Web server responds successfully for `http://127.0.0.1:15000/hello` and `http://[::1]:15000/hello`.
3. Telegraf for Windows successfully monitors both URLs.
3. Telegraf for Linux successfully monitors both URLs.

### Actual behavior:
1. Web server starts successfully.
2. Web server responds successfully for `http://127.0.0.1:15000/hello` and `http://[::1]:15000/hello`.
3. Telegraf for Windows successfully monitors only `http://[::1]:15000/hello` URL:
```
http_response,host=win10,method=GET,result=connection_failed,server=http://127.0.0.1:15000/hello result_type="connection_failed",result_code=3i 1606058770000000000
http_response,host=win10,method=GET,result=success,server=http://[::1]:15000/hello,status_code=200 content_length=6i,result_type="success",result_code=0i,response_time=0.0020097,http_response_code=200i 1606058770000000000
```
4. Telegraf for Linux successfully monitors only `http://127.0.0.1:15000/hello` URL:
```
http_response,host=ubuntu,method=GET,result=success,server=http://127.0.0.1:15000/hello,status_code=200 result_code=0i,response_time=0.02016597,http_response_code=200i,content_length=6i,result_type="success" 1606058900000000000
http_response,host=ubuntu,method=GET,result=connection_failed,server=http://[::1]:15000/hello result_type="connection_failed",result_code=3i 1606058900000000000
```
### Additional info:
**Why Telegraf for Windows fails for IPv4 URL `http://127.0.0.1:15000/hello` and Telegraf for Linux fails for IPv6 URL `http://[::1]:15000/hello`?**
It is because in this line https://github.com/influxdata/telegraf/blob/b39c1974a23507a1892979c4401d135778a52fad/plugins/inputs/http_response/http_response.go#L209 plugin chooses first available address for given interface. In my case it is IPv6 for Windows and IPv4 for Linux.

**Would it work if any address ordering solution is provided (so the same address would be chosen 
independently from OS type)?**
No, they would just fail for the same address type. Other address type would still not work. It is because HTTP Client with chosen address is configured per plugin and not per provided URL.
