### ISSUE TITLE
[inputs.docker] No memory stats for docker containers

### ISSUE THREAD

**Issue by giejay** [influxdata/telegraf#8453]
### Relevant telegraf.conf:

```toml
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.net]]
  interfaces = ["eth*"]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.docker]]
endpoint = "unix:///var/run/docker.sock"
gather_services = false
```

### System info:

Telegraf: telegraf:1.16.2
Raspberry Pi 4 with latest Raspbian

### Docker
```
  telegraf:
    image: telegraf:1.16.2
    restart: always
    network_mode: host
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: localhost
    volumes:
      - /home/pi/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro
      - media:/rootfs/media:ro
```
### Steps to reproduce:

I have telegraf running on 2 Raspberry Pi's and 1 Odroid with Ubuntu. On 1 Raspberry and the Odroid, I can see the memory stats in grafana under the key docker_container_mem_usage.

Unfortunately, on my Raspberry Pi 4, the memory is always 0 for all the containers: 
```
{build_version="",com_docker_compose_config_hash="1f84fe33ddadb7d2d440f806bbaa4d754af17959e6648856317ec9ad74d3809a",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="automation",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/home/pi/automation",com_docker_compose_service="zigbee2mqtt",com_docker_compose_version="1.27.4",container_id="afee0b847b6be12ae6116301cccd925bcb031f192fc5f1953f9951217ab23b6a",container_image="koenkk/zigbee2mqtt",container_name="automation_zigbee2mqtt_1",container_status="running",container_version="1.15.0",engine_host="master-pi",host="master-pi",maintainer="",org_label_schema_build_date="",org_label_schema_description="",org_label_schema_docker_dockerfile="",org_label_schema_license="",org_label_schema_name="",org_label_schema_url="",org_label_schema_vcs_ref="",org_label_schema_vcs_type="",org_label_schema_vcs_url="",org_label_schema_vendor="",org_label_schema_version="",server_version="19.03.13"} 0
``` 

Everything else is available (like cpu):

```
docker_memory_total{engine_host="master-pi",host="master-pi",server_version="19.03.13"} 4.013207552e+09

docker_container_cpu_usage_in_usermode{build_version="",com_docker_compose_config_hash="1f84fe33ddadb7d2d440f806bbaa4d754af17959e6648856317ec9ad74d3809a",com_docker_compose_container_number="1",com_docker_compose_oneoff="False",com_docker_compose_project="automation",com_docker_compose_project_config_files="docker-compose.yml",com_docker_compose_project_working_dir="/home/pi/automation",com_docker_compose_service="zigbee2mqtt",com_docker_compose_version="1.27.4",container_id="afee0b847b6be12ae6116301cccd925bcb031f192fc5f1953f9951217ab23b6a",container_image="koenkk/zigbee2mqtt",container_name="automation_zigbee2mqtt_1",container_status="running",container_version="1.15.0",cpu="cpu-total",engine_host="master-pi",host="master-pi",maintainer="",org_label_schema_build_date="",org_label_schema_description="",org_label_schema_docker_dockerfile="",org_label_schema_license="",org_label_schema_name="",org_label_schema_url="",org_label_schema_vcs_ref="",org_label_schema_vcs_type="",org_label_schema_vcs_url="",org_label_schema_vendor="",org_label_schema_version="",server_version="19.03.13"} 5.579e+10
```

I tried rebooting, pulling the latest telegraf image but no luck.. anyone got a pointer?
