### ISSUE TITLE
inputs.opcua missing support for arrays

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [influxdata/telegraf#8475]
### Relevant telegraf.conf:

```toml
[[inputs.opcua]]
   name = "codesys"
   endpoint = "opc.tcp://192.168.2.247:4840"
   connect_timeout = "10s"
   request_timeout = "5s"
   interval = "1s"
   security_policy = "None"
   security_mode = "None"
   auth_method = "Anonymous"
   nodes = [
     {name="joints", namespace="4", identifier_type="s", identifier="|var|CODESYS.Joints", data_type="float", description="Joint values"},
   ]
```

### System info:

Ubuntu 20.04, Telegraf 1.16.2 (git: release-1.16 962082f6), InfluxDB v1.8.3 (git: 1.8 563e6c3d1a7a2790763c6289501095dbec19244e)

### Steps to reproduce:

1. Define an array value in OPCUA like in the picture
![image](https://user-images.githubusercontent.com/34926125/100354912-26d43f80-2ff1-11eb-96ca-e75dbb6cbc39.png)
2. import it into telegraf with above configuration

### Expected behavior:

Arrays should be imported as separated fields, just like it happens in mqtt consumer when an array is fed to the plugin in json format.

### Actual behavior:

Array values are not imported, as shown in picture
![image](https://user-images.githubusercontent.com/34926125/100355187-99ddb600-2ff1-11eb-846f-b9845efa3002.png)

### Additional info:

As an example, this json
```
{
	"data_epoch": 1606398721.25,
	"J": {
		"1": 0.8607293824546176,
		"2": 4.381520765315148,
		"3": 0.8909938918704291,
		"4": 3.6710059274584418,
		"5": 4.801455750458236,
		"6": 5.99702671486787,
		"7": 6.237032901194868
	}
}
```
is correctly translated into multiple fields by the mqtt consumer with this configuration
```
[[inputs.mqtt_consumer]]
  servers = ["tcp://1.2.3.4:4321"]
  connection_timeout = "15s"
  topics = [
    "some/#",
  ]
  tag_keys = [
    "sometagA",
    "sometagB"
  ]
  tagexclude = [
    "host",
    "topic"
  ]
  persistent_session = true
  client_id = "someid"

  data_format = "json"
  json_name_key = "measurement"
  json_time_key = "data_epoch"
  json_time_format = "unix"
```
see picture below
![image](https://user-images.githubusercontent.com/34926125/100359187-81709a00-2ff7-11eb-9d1f-cb8b2be0b0b7.png)

Thanks!
