### ISSUE TITLE
processors.enum.mapping - redunant configuration leads to default value overriding all actual values

### ISSUE THREAD

**Issue by cun-dp** [influxdata/telegraf#8487]
We have multiple instances of the same configuration snippet for the enum-processor-plugin.
All these instances contain a default value. 

If there is a default value for the same field in any but the last configuration file (alphabetical order), then all the actual values are overriden by the default value.

This behavior appeared with v1.15.0, the previous 1.14.xx versions were working as expected.

### Relevant telegraf.conf:

**A.config**
```toml
    [[processors.enum]]
        [[processors.enum.mapping]]
            field = "status"          
	    default = 10 			
            [processors.enum.mapping.value_mappings]
	    Healthy = 1
            Unhealthy = 2
```

**B.config**
```toml
    [[processors.enum]]
        [[processors.enum.mapping]]
            field = "status"          
	    default = 10 			
            [processors.enum.mapping.value_mappings]
	    Healthy = 1
            Unhealthy = 2
```

**Output plugin**: outputs.prometheus_client

### System info:

**OS**: Windows Server 2016
**Telegraf amd64**: affected versions that were tested: 1.15.0, 1.16.2 
**Telegraf amd64**: unaffected versions that were tested: 1.14.2 to 1.14.5

### Docker

Docker is not used here.

### Steps to reproduce:

1. have a "status" field in a metric machting the A/B Config files
2. use both the "A.config" and the "B.config" config files in your config path
3. Inspect your metric: all values are now "10", instead of 1 or 2

Example for 1-3:
```
Test_status{tenant="XX"} 10
Test_status{tenant="YY"} 10
```

4. remove the "default" value from B.config
5. Inspect your metric: all values are still "10", instead of 1 or 2

Example for 4-5:
```
Test_status{tenant="XX"} 10
Test_status{tenant="YY"} 10
```

6. add the "default" value back to B.config
7. remove the "default" value from A.config
8. Inspect your metric: all values are now 1 or 2, as expected. Unknown enum values are mapped to default 10, as expected.

Example for 6-8:
```
Test_status{tenant="XX"} 1
Test_status{tenant="YY"} 2
```

9. there are no errors or anything related in the logs, except the indication that the processor hat been loaded

### Expected behavior:
 The default value is only used for enums that are not in the value_mappings list, irregardless of multiple default values or other redundant configuration.

### Actual behavior:
The default value, if placed in any but the last redundant config, overrides ALL actual values, even if the enums are in the value_mappings list.

### Additional info:

Using different default values for A.config and B.Config shows the the default value from A.config is used to override the acutal value.
