### ISSUE TITLE
Input data format: value

### ISSUE THREAD

**Issue by sparrc** [influxdata/telegraf#849]
we should be able to parse simple values as a data format, with the ability to specify string, integer, float or boolean, like this:

```toml
[[inputs.exec]]
  commands = ["uname -r"]
  data_format = "value"
  data_type = "string"
  name_override = "kernel_version"
```

which would output:

```
kernel_version,[tags]  value="15.3.0"  1457975011144006845
```

see #235
