### ISSUE TITLE
Docker + docker-compose input may not fully index to elastic

### ISSUE THREAD

**Issue by bmagistro** [influxdata/telegraf#8492]
Using an instance of telegraf to monitor the host and docker and another instance (containerized on a different host) to send to elastic I am seeing logs indicating an indexing failure.  I have been able to narrow this down to the docker input, if that input is disabled the messages stop.

### Relevant telegraf.conf:
source instance
additional host metric inputs are not included as not applicable
```toml
# # Read metrics about docker containers
[[inputs.docker]]
  ## Docker Endpoint
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  container_names = []
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  perdevice = true
  ## Whether to report for each container total blkio and network stats or not
  total = false

# Generic socket writer capable of handling multiple socket types.
[[outputs.socket_writer]]
  address = "tcp://target.aggregator:8094"
  keep_alive_period = "5m"
```

aggregator instance
```toml
[[inputs.socket_listener]]
  ## URL to listen on
  service_address = "tcp://:8094"

[[outputs.elasticsearch]]
  urls = [ "http://elasticsearch:9200" ] # required.
  timeout = "5s"
  enable_sniffer = false
  health_check_interval = "10s"

  ## Index Config
  index_name = "telegraf-%Y.%m" # required.

  ## Template Config
  manage_template = true
  template_name = "telegraf"
  overwrite_template = false
  force_document_id = false
```

### System info:
the source is a vanilla centos 7 + telegraf 1.16 + docker ce 19
the aggregator is the same with the instance of telegraf (+elk) run in containers 

### Docker
while docker is being used, I don't believe anything here is relevant

### Steps to reproduce:
1. install/start telegraf
2. have docker installed + containers running
3. monitor logs on aggregator

### Expected behavior:
No errors indexing

### Actual behavior:
On the aggregator the log lines are observed
```
2020-12-01T03:24:46Z E! Elasticsearch indexing failure, id: 118, error: Can't merge a non object mapping [tag.com.docker.compose.project] with an object mapping [tag.com.docker.compose.project], caused by: %!s(<nil>), %!s(<nil>)
2020-12-01T03:24:46Z E! Elasticsearch indexing failure, id: 119, error: Can't merge a non object mapping [tag.com.docker.compose.project] with an object mapping [tag.com.docker.compose.project], caused by: %!s(<nil>), %!s(<nil>)
2020-12-01T03:24:46Z E! [agent] Error writing to outputs.elasticsearch: W! Elasticsearch failed to index 120 metrics
```

### Additional info:
I had a file output also running while this was occurring, below is what I believe is a relevant line.  Based on the line, the error makes sense.  I am not sure I "need" the compose tags so can strip them out but that does not seem like it should be the final answer.
```
{"fields":{"container_id":"d8ce31e4163d76a77418f22204830465a197e2942cf73d17ebb165cccf23f158","exitcode":0,"oomkilled":false,"pid":9225,"started_at":1606759524570504319,"uptime_ns":6466572720},"name":"docker_container_status","tags":{"com.docker.compose.config-hash":"4e1180e273c54f6d6c96320c9eea079dace8025c79e8616e4bcf9a4d94e6b286","com.docker.compose.container-number":"1","com.docker.compose.oneoff":"False","com.docker.compose.project":"data","com.docker.compose.project.config_files":"docker-compose.yml","com.docker.compose.project.working_dir":"/data","com.docker.compose.service":"logstash","com.docker.compose.version":"1.27.4","container_image":"logstash","container_name":"logstash","container_status":"running","container_version":"7.7.0","engine_host":"machinename","host":"machinename","license":"Elastic License","org.label-schema.build-date":"20200504","org.label-schema.license":"GPLv2","org.label-schema.name":"logstash","org.label-schema.schema-version":"1.0","org.label-schema.url":"https://www.elastic.co/products/logstash","org.label-schema.vcs-url":"https://github.com/elastic/logstash","org.label-schema.vendor":"Elastic","org.label-schema.version":"7.7.0","org.opencontainers.image.created":"2020-05-04 00:00:00+01:00","org.opencontainers.image.licenses":"GPL-2.0-only","org.opencontainers.image.title":"CentOS Base Image","org.opencontainers.image.vendor":"CentOS","server_version":"19.03.12"},"timestamp":1606759531}
```

Work around to filter the compose tags
```
docker_label_exclude = [ "com.docker.compose*" ]
```
