### ISSUE TITLE
inputs.ping native sends wrong number of pings

### ISSUE THREAD

**Issue by bjoe2k4** [influxdata/telegraf#8501]
### Relevant telegraf.conf:

```toml
[global_tags]
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = true
  logtarget = "file"
  logfile = "/var/log/telegraf/telegraf.log"
  logfile_rotation_interval = "1d"
  hostname = ""
  omit_hostname = false
[[outputs.prometheus_client]]
  listen = ":9283"
  metric_version = 2
[[inputs.ping]]
urls = ["vodafone.de" ]
count = 5
method = "native"
ping_interval = 0.2
timeout = 4.0
```

### System info:
RaspberryOS with a 4GB Raspi4
Linux raspi-pihole2 5.4.72-v7l+ #1356 SMP Thu Oct 22 13:57:51 BST 2020 armv7l GNU/Linux
Telegraf 1.16.2 (git: release-1.16 962082f6) (offical release)

### Steps to reproduce:

1. Set above config & start telegraf + prometheus
2. Wait for a day

### Expected behavior:
telegraf sends and receives exactly 5 packets every 10s when there is no packetloss.

### Actual behavior:
telegraf sometimes seems to send more packages than it is supposed to (6 instead of 5)

![telegraf](https://user-images.githubusercontent.com/1668390/100935603-987c2400-34f0-11eb-9155-5909ffd9b657.png)

The question is if the 6th packet is actually sent or if it is just a reporting bug. A 100% correlation with a packetloss of 16.66% rather points to a bug.
