### ISSUE TITLE
win_perf_counters cannot collect "DHCP Server" counters.

### ISSUE THREAD

**Issue by hyberdk** [influxdata/telegraf#8515]
### Relevant telegraf.conf:

```toml

# Global tags can be specified here in key="value" format.
[global_tags]


# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true

  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################


[[outputs.influxdb]]
  urls = ["http://django-dev.vestas.net:8086"]
  database = "telegraf"

###############################################################################
#                                  INPUTS                                     #
###############################################################################

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    # DHCP Server
    ObjectName = "DHCP Server"
    Counters = [
      "Acks/sec"
      ]
    Measurement = "win_dhcp"
```

### System info:

Windows 2012 server.
Telegraf 1.16.3 (git: HEAD c7f21728)

### Steps to reproduce:

run: "telegraf.exe --console --debug --config telegraf.conf --test"

I tried to limit the number of counters to a minimum..

### Expected behavior:

to print the Acks/sec.

### Actual behavior:

2020-12-04T13:49:17Z I! Starting Telegraf 1.16.3
2020-12-04T13:49:17Z D! [agent] Initializing plugins
2020-12-04T13:49:17Z D! [agent] Starting service inputs
2020-12-04T13:49:17Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2020-12-04T13:49:17Z D! [agent] Stopping service inputs
2020-12-04T13:49:17Z D! [agent] Input channel closed
2020-12-04T13:49:17Z D! [agent] Stopped Successfully
2020-12-04T13:49:17Z E! [telegraf] Error running agent: input plugins recorded 1 errors

### Additional info:

```
PS C:\Users\eslau-adm> TypePerf -q | Select-String -Pattern DHCP

\DHCP Server v6\Declines/sec
\DHCP Server v6\Releases/sec
\DHCP Server v6\Acks/sec
\DHCP Server v6\Informs/sec
\DHCP Server v6\Rebinds/sec
\DHCP Server v6\Confirms/sec
\DHCP Server v6\Renews/sec
\DHCP Server v6\Requests/sec
\DHCP Server v6\Advertises/sec
\DHCP Server v6\Solicits/sec
\DHCP Server v6\Active Queue Length
\DHCP Server v6\Milliseconds per packet (Avg).
\DHCP Server v6\Packets Expired/sec
\DHCP Server v6\Duplicates Dropped/sec
\DHCP Server v6\Packets Received/sec
\DHCP Server\Failover: BndUpd Dropped.
\DHCP Server\Failover: Transitions to RECOVER state.
\DHCP Server\Failover: Transitions to PARTNER-DOWN state.
\DHCP Server\Failover: Transitions to COMMUNICATION-INTERRUPTED state.
\DHCP Server\Failover: BndUpd pending in outbound queue.
\DHCP Server\Failover: BndAck received/sec.
\DHCP Server\Failover: BndAck sent/sec.
\DHCP Server\Failover: BndUpd received/sec.
\DHCP Server\Failover: BndUpd sent/sec.
\DHCP Server\Denied due to nonmatch.
\DHCP Server\Denied due to match.
\DHCP Server\Offer Queue Length
\DHCP Server\Releases/sec
\DHCP Server\Declines/sec
\DHCP Server\Nacks/sec
\DHCP Server\Acks/sec
\DHCP Server\Informs/sec
\DHCP Server\Requests/sec
\DHCP Server\Offers/sec
\DHCP Server\Discovers/sec
\DHCP Server\Conflict Check Queue Length
\DHCP Server\Active Queue Length
\DHCP Server\Milliseconds per packet (Avg).
\DHCP Server\Packets Expired/sec
\DHCP Server\Duplicates Dropped/sec
\DHCP Server\Packets Received/sec
```
