### ISSUE TITLE
processor.date creates duplicate values

### ISSUE THREAD

**Issue by sAws** [influxdata/telegraf#8533]
### Relevant telegraf.conf:

```toml
[global_tags]
map_data_type = "log"
map_agent_type = "telegraf-app-local"
map_agent_alias = "app-local"
map_agent_source = "file"

[agent]
interval = "10s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
debug = false
quiet = false
hostname = "app.local"
omit_hostname = false

[[inputs.tail]]
files = ["/opt/app/logs/trace.log"]
from_beginning = false
pipe = false
watch_method = "inotify"
data_format = "grok"
grok_patterns = ["%{WORD:trace_id}%{SPACE}\\|%{SPACE}%{TIMESTAMP_ISO8601:timestamp_hub}%{SPACE}\\|%{SPACE}%{LOGLEVEL:level}%{SPACE}\\|%{SPACE}%{GREEDYDATA:msg:string}"]

[[outputs.kafka]]
brokers = ["kafka.local:9092"]
topic = "telegraf-hub"
routing_tag = "host"
routing_key = "random"
compression_codec = 1
data_format = "json"
max_retry = 3

[[processors.date]]
field_key = "created"
date_format = "unix_ms"
timezone = "UTC"
```

### System info:

```bash
$ telegraf --version
Telegraf 1.16.0 (git: HEAD c2a53d0f)
```

### Docker

none

### Steps to reproduce:

1. Configured and start agent
2. Writing to a log file
3. Show logs in kibana

### Expected behavior:

Unique value for field

### Actual behavior:

Non unique value for field

### Additional info:

<img width="1145" alt="Снимок экрана 2020-12-09 в 18 11 15" src="https://user-images.githubusercontent.com/10175884/101647690-150b8700-3a4a-11eb-9a81-67db012933a4.png">
