### ISSUE TITLE
snmp_trap plugin get error message like" Error resolving OID: exit status 2"

### ISSUE THREAD

**Issue by xiaopeng163** [influxdata/telegraf#8535]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "180s"
  flush_interval = "60s"
  debug = true
# Publish all metrics to /metrics for Prometheus to scrape
[[outputs.prometheus_client]]
  ## Address to listen on.
  listen = ":9126"
  metric_version = 2
  path = "/metrics"
  string_as_label = true
  export_timestamp = true

[[inputs.snmp_trap]]
  service_address = "udp://:162"

  version = "3"
  sec_name = "xxxxxx"
  sec_level = "authPriv"
  auth_protocol = "SHA"
  auth_password = "xxxxxxx"
  priv_protocol = "AES"
  priv_password = "xxxxxxxx"

#Add DNS Key/Value pair to metric
[[processors.reverse_dns]]
  order = 1
  [[processors.reverse_dns.lookup]]
    tag = "source"
    dest = "dns"
```

### Docker

docker image version is 1.15.3

### Steps to reproduce:

1.  start teleraf
2.  Cisco routers send snmp traps to telegraf

### Actual behavior:

Get error logging message like

```
2020-11-24T06:04:55Z E! [inputs.snmp_trap] Error resolving OID: exit status 2
```
