### ISSUE TITLE
Odd behavior of http_response plugin

### ISSUE THREAD

**Issue by sanel** [influxdata/telegraf#8560]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  # debug = false
  # quiet = false
  hostname = ""
  omit_hostname = false

[[outputs.riemann]]
   url = "tcp://localhost:5555"
   ttl = 10.0
   separator = "/"
   measurement_as_attribute = false
   string_as_state = false
   tags = ["telegraf"]

[[inputs.dns_query]]
  servers = ["server1", "server2"]
  domains = ["domain1", "domain2", "domain3"]
  record_type = "A"
  timeout = 5

[[inputs.http_response]]
  urls = [
  "http://site1"
  "https://site2",
  ...
  "https://site11"
  ]

  method = "GET"
  follow_redirects = true
  response_timeout = "5s"
```

### System info:

OS: Ubuntu 16.04.7 LTS x86_64, Telegraf: 1.16.3 (git: HEAD c7f21728).

### Steps to reproduce:

1. Telegraf, Riemann, InfluxDB.
2. Add multiple sites to monitor, like in configuration. More than 10.

### Expected behavior:

Measurements from all sites should be sent from telegraf around every 10 seconds.

### Actual behavior:

For some sites, measurements are received every 10 seconds, for some randomly, every N minutes or not at all.

### Additional info:

A few days ago, I set `http_response` plugin to monitor a number of sites, alongside `dns_query` as the only two input plugins used and `riemann` as the only output plugin. Riemann will then route events to InfluxDB. `dns_query` runs for about a month without any problems.

`http_response` is currently monitoring 11 sites, but metrics are not received for all sites - for some, telegraf will correctly send metrics every 10 seconds; for some, it will not send at all and for some will send it in the irregular interval.

Also, to confirm discrepancy, here are the queries for some of those sites:

```
# for this site, all measurements are received and recorded
> SELECT count(value) FROM "http_response/response_time" WHERE  "server" = 'https://site1';
name: http_response/response_time
time count
---- -----
0    3223

# for these, only partial
> SELECT count(value) FROM "http_response/response_time" WHERE  "server" = 'https://site2'
name: http_response/response_time
time count
---- -----
0    99

> SELECT count(value) FROM "http_response/response_time" WHERE  "server" = 'https://site3';
name: http_response/response_time
time count
---- -----
0    51

> SELECT count(value) FROM "http_response/response_time" WHERE  "server" = 'https://site4';
name: http_response/response_time
time count
---- -----
0    25
```

If I'm not mistaken, if measurements for all sites are correctly sent, the count should be around 3223, like for the site1.
