### ISSUE TITLE
Docker plugin + InfluxDB 2.0: type mismatch

### ISSUE THREAD

**Issue by Jamesits** [influxdata/telegraf#8570]
### Relevant telegraf.conf:
```toml
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = true
  source_tag = true
  timeout = "5s"
  perdevice = true
  total = true
```

### System info:

* CentOS 7.9
* Telegraf 1.16.1 (git: HEAD 292e285a)
* Docker version 20.10.0, build 7287ab3

### Docker

N/A

### Steps to reproduce:

1. Enable Telegraf Docker plugin and a InfluxDB v2 output plugin
2. Wait a while for the `docker_swarm` series to be created
3. Enable Docker Swarm mode on the host

### Expected behavior:

Telegraf should be able to write new data to influxdb.

### Actual behavior:

```
E! [agent] Error writing to outputs.influxdb_v2: 500 Internal Server Error: internal error: unexpected error writing points to database: partial write: field type conflict: input field "tasks_desired" on measurement "docker_swarm" is type integer, already exists as type unsigned dropped=7
```

### Additional info:

N/A
