### ISSUE TITLE
postgresql plugin has to retry connection in case of failure

### ISSUE THREAD

**Issue by igomura** [influxdata/telegraf#8586]
### Relevant telegraf.conf:
```toml
[[inputs.postgresql]]
address = "postgres://telegraf:here_is_my_password@localhost:5432/postgres"
databases = ["mydb"]
tagexclude = ["server", "db"]
```

### System info:

telegraf-1.15.3-1.x86_64
CentOS Linux release 7.8.2003 (Core)
kernel 3.10.0-1160.6.1.el7.x86_64

### Steps to reproduce:

1. shut down postgres server
2. start telegraf
3. start postgres server few seconds later

### Expected behavior:

plugin reconnects to the database as soon as it becomes available

### Actual behavior:

plugin throws an error and never reconnects to the server
I had to restart telegraf in order to make it work

### Additional info:

2020-12-17T02:02:50Z E! [inputs.postgresql] Error in plugin: FATAL: the database system is starting up (SQLSTATE 57P03)
