### ISSUE TITLE
outputs.influxdb broken with Telegraf v1.17.0/InfluxDB 1.8.2

### ISSUE THREAD

**Issue by LloydW93** [influxdata/telegraf#8612]
### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
urls = [ "https://influxdb.example.com" ]
database = "vocicast"
timeout = "10s"
username = "admin"
password = "admin"
retention_policy = ""
tls_cert = "/path/to/client.pem"
tls_key = "/path/to/client.key"
skip_database_creation = true
```

### System info:

Telegraf v1.17.0 (and v1.16.0 and newer), RHEL 7.

### Steps to reproduce:

1. On a RHEL 7 environment, install the latest telegraf (v1.17.0)
2. Elsewhere, install InfluxDB 1.8.2, with an mTLS reverse proxy in front

Create an outputs.influxdb configuration as per the example above.

### Expected behavior:

System metrics data is written to InfluxDB.

### Actual behavior:

InfluxDB responds with a HTTP 400, e.g.:
```
HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: 9c7a25e3-446c-11eb-b86f-0afdf16e9fa3
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse '.............r.8..{..B..k........8.ru....Hr..w.+.....$.(.W...p.KV.......7...>...~}~{..?...?........~{.......7.=?..~.?..P!..$..}y}~.....>......... ..v..............1%.....w..._...8..`...><?................$.a...|1 h....?....{}.z...r............X....../...........4R...).><?>..?..?.....Bb........._.;.P.A...-.......I>..0	..)...	c......_.....r.......ww..0...........vw.bb).O.z............ ................r.........7>.D.q....{.v....x..( "...........M...m...Qb.#.......1.........6a.;4.=...]B!.SC...Z......w.0r.@l$q........ow...1': invalid field format unable to parse '.o.=.}.2....A..a#....~....." EP.9.....].vn....?..<.....%.ibH.e.......w!.......}...jR.....o...a...,...'.........._X..u..c.......(\y..S......[........|......m..p..........O..^......)....;..r._.uK.".._........../..}..!......./..?....z.t....../.y.......uw..m.t....d.......c........rX.)E.....K5J........./......._...../.%..H.Cr...."Y.;....T..x...n...<UO.SB......./.7ck.!..Q...Y?!.......B.....k	DlX...M..D....cow.fa.!Hh1..U. ."4.\.../....C.........
X-Influxdb-Version: 1.8.1
X-Request-Id: 9c7a25e3-446c-11eb-b86f-0afdf16e9fa3
```

### Additional info:
I haven't tested this configuration without the mTLS proxy, though I would assume that would have been covered now if this was not the problem.

The issue is not present in Telegraf v1.15.2 or Telegraf v1.15.4.
The issue is present in Telegraf v.1.16.0.
