### ISSUE TITLE
gNMI metric path has leading character truncated

### ISSUE THREAD

**Issue by mousedownmike** [influxdata/telegraf#8653]
### Relevant telegraf.conf:

```toml

```

### System info:

Here is a sample subscription. 

```toml
  [[inputs.gnmi.subscription]]
   name = "interface-1-counters"
   origin = "Monta"
   path = "/oc-if:interfaces/oc-if:interface[name=1]/oc-if:state/oc-if:counters/"
   subscription_mode = "sample"
   sample_interval = "10s"
```
### Steps to reproduce:

Have a device that sends a gNMI Update that is processed by Telegraf to look like:
```go
	u := &gnmi.SubscribeResponse_Update{
		Update: &gnmi.Notification{
			Timestamp: time.Now().UnixNano(),
			Prefix: &gnmi.Path{
				Origin: "Monta",
				Elem: []*gnmi.PathElem{
					{Name: "oc-if:interfaces"}, 
					{Name: "oc-if:interface"}, 
					{Name: "oc-if:state"}, 
					{Name: "oc-if:counters"},
				},
			},
			Update: []*gnmi.Update{
				{
					Path: &gnmi.Path{Origin: "Monta", Elem: []*gnmi.PathElem{{Name: "in-1024-to-1518-octet-pkts"}}},
					Val:  &gnmi.TypedValue{Value: &gnmi.TypedValue_UintVal{UintVal: uint64(324504)}},
				}}}}
```

### Expected behavior:

The Metric key should  be:

`Monta:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersMonta:/in_1024_to_1518_octet_pkts`

### Actual behavior:

When the Metric is added the key ends up being:
`onta:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersMonta:/in_1024_to_1518_octet_pkts`

Observe the missing `M` from the beginning of the key.

### Additional info:

This appears to be occurring in the `// Group metrics` section of `gnmi.go`.  

```go
		// Group metrics
		for k, v := range fields {
			key := k
			if len(aliasPath) < len(key) {
				// This may not be an exact prefix, due to naming style
				// conversion on the key.
				key = key[len(aliasPath)+1:]
			} else {
```

Removing the `+1` puts the `M` back in `Monta`.  

I'll post a PR with a unit test that illustrates this...
