### ISSUE TITLE
govc and influx inconsistent: telegraf metric no update

### ISSUE THREAD

**Issue by kkruzich** [influxdata/telegraf#8681]
#### vsphere.historical.conf:
```toml
[[inputs.vsphere]]
  vcenters = [ "https://v.happyplace.com/sdk" ]
  username = "${VSPHERE_USERNAME}"
  password = "${VSPHERE_PASSWORD}"
  interval = "420s"
  vm_metric_exclude = [ "*" ]
  host_metric_exclude = [ "*" ]
  datastore_metric_exclude = [ "*" ]
  datacenter_metric_exclude = [ "*" ]
   cluster_metric_include = [ "*" ]
  collect_concurrency = 5
  force_discover_on_init = true
  timeout = "240s"
  insecure_skip_verify = true
```

#### vsphere.realtime.conf:
```toml
[[inputs.vsphere]]
  vcenters = [ "https://v.happyplace.com/sdk" ]
  username = "${VSPHERE_USERNAME}"
  password = "${VSPHERE_PASSWORD}"
  interval = "180s"
  vm_metric_exclude = [ "*" ]
  datastore_metric_exclude = [ "*" ]
  cluster_metric_exclude = [ "*" ]
  datacenter_metric_exclude = [ "*" ]
   host_metric_include = [ "*" ]
  collect_concurrency = 7
  discover_concurrency = 7
  force_discover_on_init = true
  timeout = "240s"
  insecure_skip_verify = true
```

#### telegraf.conf:
```toml

[global_tags]
  ecsam_name = "${INSTANCE_NAME}"
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 5000
  metric_buffer_limit = 90000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  logfile = "/var/log/telegraf/telegraf.log"
  hostname = ""
  omit_hostname = false
[[outputs.influxdb]]
  urls = ["${INFLUXDBSSL}"]
  timeout = "10s"
  username = "${TELEGRAF_USER}"
  password = "${TELEGRAF_PASS}"
  insecure_skip_verify = true
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]

```

### System info:

telegraf-1.17.0-1.x86_64
Amazon Linux 2
Linux - 4.14.192-147.314.amzn2.x86_64 #1 SMP Mon Aug 17 06:07:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**InfluxDB is separate server**
influxdb-1.8.1-1.x86_64
Amazon Linux 2
Linux - 4.14.192-147.314.amzn2.x86_64 #1 SMP Mon Aug 17 06:07:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce:

1. view metric with govc
2. view metric as InfluxDB query

### Expected behavior:

I expect the metrics collected by telegraf / vsphere plugin to reflect the same or closely similar to that collected by govc:

```
# date
Tue Jan 12 22:07:36 UTC 2021
# govc metric.sample /foobar/host/CL100 cpu.usage.average
CL100 -  cpu.usage.average    78.12,78.00  %
```

### Actual behavior:

telegraf is writing to InfluxDB and I can see this metric hasn't updated for a very long time:

```
> SELECT LAST("usage_average") FROM vsphere_cluster_cpu WHERE clustername = 'CL100'
 name: vsphere_cluster_cpu
 time                last
 ----                ----
 1598624400000000000 58.55

```
https://www.epochconverter.com/
August 28, 2020
