### ISSUE TITLE
Restrict permissions on the telegraf config file

### ISSUE THREAD

**Issue by sajoupa** [influxdata/telegraf#8685]
### Relevant telegraf.conf:

(just a random example)
```toml
[[inputs.postgresql_extensible]]
  address = "dbname=telegraf-postgresql host=10.1.1.2 password=<plain text password> port=5432 user=telegraf-postgresql"
```

### System info:

```
Telegraf 1.17.0 (git: HEAD 3f7a54c9)
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```

### Steps to reproduce:

```
$ wget https://dl.influxdata.com/telegraf/releases/telegraf_1.17.0-1_amd64.deb
$ sudo dpkg -i telegraf_1.17.0-1_amd64.deb
```

### Expected behavior:

Files owned by `root:telegraf`, not world-readable:
```
$ ls -la /etc/telegraf/telegraf.conf
-rw-r----- 1 root telegraf 278943 Jan 13 09:24 /etc/telegraf/telegraf.conf
```
### Actual behavior:

Files world-readable, owned by `root:root`:
```
$ ls -la /etc/telegraf/telegraf.conf
-rw-r--r-- 1 root root 278943 Jan 13 09:24 /etc/telegraf/telegraf.conf
```
### Additional info:

There's https://github.com/influxdata/telegraf/issues/3124 to move secrets out of the config files, which would address the same concern.
But it's been open for 2+ years and some ambitious but complex solutions are considered.
Changing the default file permissions would, in my opinion, address the issue without much complexity.
