### ISSUE TITLE
gNMI metric Origin truncated in path

### ISSUE THREAD

**Issue by mousedownmike** [influxdata/telegraf#8694]
### Relevant telegraf.conf:

```toml
[agent]
debug = false
    [[inputs.gnmi]]
    addresses =["10.120.1.1:6702"]
    [[inputs.gnmi.subscription]]
    name = "device_one"
    origin = "Monta"
    path = "/oc-if:interfaces/oc-if:interface[name=1]/oc-if:state/oc-if:counters"
    subscription_mode = "sample"
    sample_interval = "10s"
    [[inputs.gnmi]]
    addresses =["10.120.1.2:6702"]
    [[inputs.gnmi.subscription]]
    name = "device_two"
    origin = "Monta"
    path = "/oc-if:interfaces/oc-if:interface[name=1]/oc-if:state/oc-if:counters"
    subscription_mode = "sample"
    sample_interval = "10s"
[[outputs.prometheus_client]]
metric_version = 2
listen = ":9011"
```

### System info:

This was built from the `master` branch to make use of the fix from PR #8653.  Prior to that fix the subscription `name` value was being ignored.  I assume this was because the configured `origin` value of `Monta` did not match the truncated value of `onta`.

### Steps to reproduce:

1. Configure gNMI inputs as defined above.
2. Review the output in the metrics page.

### Expected behavior:

I'm not entirely sure how the logic works for the conversion of the metric's gNMI path to the name that is output.  However if the origin is supposed to be included in the output, it should not be truncated.  Given the above configuration, I would expect one of the following outputs:

**With Origin** (as it seems to want to do)
```
device_one_Monta:_out_pkts{host="deepthought",Monta__name="\"1\"",name="1",path="Monta:/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters",source="10.120.1.1"} 502239
...
device_two_Monta:_out_pkts{host="deepthought",Monta__name="\"1\"",name="1",path="Monta:/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters",source="10.120.1.2"} 0
```
**Without the Origin** (which seems ok, if we're explicitly setting a name)
```
device_one:_out_pkts{host="deepthought",_name="\"1\"",name="1",path="Monta:/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters",source="10.120.1.1"} 502239
...
device_two:_out_pkts{host="deepthought",_name="\"1\"",name="1",path="Monta:/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters",source="10.120.1.2"} 0
```

### Actual behavior:

The Origin element of the path gets truncated to `onta` much like it did before #8653 was fixed. This has metrics with the following output:
```
device_one_onta:_out_pkts{host="deepthought",onta__name="\"1\"",name="1",path="Monta:/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters",source="10.120.1.1"} 502239
...
device_two_onta:_out_pkts{host="deepthought",onta__name="\"1\"",name="1",path="Monta:/oc-if:interfaces/oc-if:interface/oc-if:state/oc-if:counters",source="10.120.1.2"} 0
```

### Additional info:

This appears to be happening in `gnmi.go` where the value of `key` is reset to `key[len(aliasPath)+1:]`

```go
		for k, v := range fields {
			key := k
			if len(aliasPath) < len(key) && len(aliasPath) != 0 {
				// This may not be an exact prefix, due to naming style
				// conversion on the key.
				key = key[len(aliasPath)+1:]
			}
```

The original value of `key` is `Monta:/oc_if:interfaces/oc_if:interface/oc_if:state/oc_if:countersMonta:/out_pkts`.  Once processed through the code above, it becomes `onta:/out_pkts`.
