### ISSUE TITLE
Support namespacing plugins

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#8696]
## Feature Request

namespace plugins so that you can easily control the flow of metrics through Telegraf without depending on a rather verbose namepass setup.

eg 

```toml
# -------------- namespace 1
[inputs.cpu]
  namespace = "foo"
[processors.starlark]
  namespace = "foo"
[outputs.file]
  namespace = "foo"
# -------------- namespace 2
[inputs.cpu]
  namespace = "foo2"
[processors.rename]
  namespace = "foo2"
[outputs.file]
  namespace = "foo2"
# --------------
```
