### ISSUE TITLE
TLS stopped working when upgrading to v1.17

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#8698]
### Relevant telegraf.conf:

```toml
[[inputs.jti_openconfig_telemetry]]
  servers = ["router1.mgt.net:50051", "router2.mgt.net:50051"]
    sensors = ["interfaces /junos/system/linecard/interface/","ifaceDesc /interfaces/interface/state/description/","lsps /junos/services/label-switched-path/usage/","cpu /junos/system/linecard/cpu/memory/","npu /junos/system/linecard/npu/memory/"] 
  sample_frequency = "60000ms"
  username = "$routerUser"
  password = "$routerPass"
  client_id = "$containerName"
  enable_tls = true
  tls_ca = "/etc/telegraf/router_ca.pem"
  insecure_skip_verify = false
  str_as_tags = false
```

### System info:

Telegraf v1.17.0
### Steps to reproduce:

1. ...
2. ...
