### ISSUE TITLE
TLS stopped working with Telegraf v1.15 and newer.

### ISSUE THREAD

**Issue by mohsin106** [influxdata/telegraf#8699]
### Relevant telegraf.conf:

```toml
[global_tags]
[agent]
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "5s"
  flush_interval = "1m"
  flush_jitter = "5s"
  debug = true
  quiet = false
  hostname = "test1"
  omit_hostname = false

[[inputs.jti_openconfig_telemetry]]
  servers = ["router1.mgt.net:50051", "router2.mgt.net:50051"]
    sensors = ["interfaces /junos/system/linecard/interface/","ifaceDesc /interfaces/interface/state/description/","lsps /junos/services/label-switched-path/usage/","cpu /junos/system/linecard/cpu/memory/","npu /junos/system/linecard/npu/memory/"] 
  sample_frequency = "60000ms"
  username = "$routerUser"
  password = "$routerPass"
  client_id = "$containerName"
  enable_tls = true
  tls_ca = "/etc/telegraf/router_ca.pem"
  insecure_skip_verify = false
  str_as_tags = false

[[outputs.file]]
  files = ["stdout"]
```

### System info:

Telegraf v1.17.0
MacOS 11.0.1

### Steps to reproduce:

1. Brew install Telegraf 1.17
2. Run Telegraf using the above config

### Expected behavior:

Telegraf should be able to connect to the routers and start streaming the telemetry data.
### Actual behavior:

Get this error:
[inputs.jti_openconfig_telemetry] Could not initiate login check for nep6bbrj03.mgt.cox.net:50051: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: EOF"
### Additional info:
Downgrade to version 1.14 or older and TLS works.
