### ISSUE TITLE
Docker plugin only reports container defined healthchecks, not docker-compose defined healthchecks

### ISSUE THREAD

**Issue by zacps** [influxdata/telegraf#8743]
### Relevant telegraf.conf:

```toml
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  perdevice = true
  total = false
```

### System info:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
---
Package: telegraf
Version: 1.17.0-1
---
Package: docker
Version: 1.5-2
---
Package: docker-compose
Version: 1.21.0-3
```

### Docker

```yml
...
   calibre:
      image: linuxserver/calibre-web
      environment:
        - DOCKER_MODS=linuxserver/calibre-web:calibre
     healthcheck:
         test: ["CMD", "curl", "localhost:8083"]
         interval: 2m
         timeout: 5s
         retries: 3
         start_period: 40s
...
```

### Steps to reproduce:

1. Start a container using a compose file with a healthcheck defined where the container itself does not have a healthcheck defined
2. Check reported metrics

### Expected behavior:

The container with the compose healthcheck is reported

### Actual behavior:

The container with the compose healthcheck is not reported

### Additional info:

`ctop` (1.0.0-2) does report the healthcheck from compose correctly, so it must be possible to obtain.

**Comment by akrantz01** [comment]
I can't seem to reproduce this locally. My only suggestion would be to try updating everything just in case.

Below are the files I used to attempt to reproduce your issue:
<details><summary>docker-compose.yml</summary>
<p>

```yaml
# docker-compose.yml
version: "3"

services:
  integrated:
    container_name: telegraf-8743_integrated
    image: telegraf-8743:integrated
    build:
      context: .
      target: with-healthcheck

  none:
    container_name: telegraf-8743_none
    image: telegraf-8743:external
    build:
      context: .
      target: base

  compose:
    container_name: telegraf-8743_compose
    image: telegraf-8743:external
    build:
      context: .
      target: base
    healthcheck:
      test: curl -f http://localhost:8000/ || exit 1
      interval: 10s
      timeout: 3s
```
</p>
</details>

<details><summary>telegraf.conf</summary>
<p>

```toml
# telegraf.conf
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  perdevice = true
  total = false
  container_name_include = ["telegraf-8743_*"]

[[outputs.file]]
```
</p>
</details>

<details><summary>Dockerfile</summary>
<p>

```Dockerfile
# Dockerfile
FROM python:3-slim as base

RUN apt-get update && apt-get upgrade -y && apt-get install -y curl

HEALTHCHECK NONE

ENTRYPOINT ["python3", "-m", "http.server"]


FROM base as with-healthcheck

HEALTHCHECK --interval=10s --timeout=3s \
  CMD curl -f http://localhost:8000/ || exit 1
```
</p>
</details>
