### ISSUE TITLE
SQLServer plugin: Invalid columns with SQLServerAvailabilityReplicaStates on SQL 2014 and earlier

### ISSUE THREAD

**Issue by simonwhybrow-cbre** [influxdata/telegraf#8750]
Columns 'seeding_mode_desc' and 'secondary_lag_seconds' are only available on SQL 2016 and later.
The plugin generates an error on SQL 2014 and earlier when the SQLServerAvailabilityReplicaStates input script is selected. Could a check for version be included to determine which columns to return.

### Relevant telegraf.conf:

```toml
# Read metrics from Microsoft SQL Server
[[inputs.sqlserver]]
  servers = ["Server=xxxxxxxxx;Port=1433"]

  database_type = "SQLServer"
```

### System info:

All Windows versions
SQL 2014 and earlier 
Telegraf version 1.17.0

### Expected behavior:

No error returned regarding invalid column names
### Actual behavior:

2021-01-26T16:21:39Z I! Starting Telegraf 1.17.0
2021-01-26T16:21:39Z I! [inputs.sqlserver] Config: database_type: SQLServer , query_version:0 , azuredb: false
2021-01-26T16:21:39Z E! [inputs.sqlserver] Error in plugin: Script SQLServerAvailabilityReplicaStates failed: mssql: Invalid column name 'seeding_mode_desc'.
2021-01-26T16:21:39Z E! [inputs.sqlserver] Error in plugin: Script SQLServerDatabaseReplicaStates failed: mssql: Invalid column name 'secondary_lag_seconds'.
2021-01-26T16:21:41Z E! [telegraf] Error running agent: input plugins recorded 2 errors
