### ISSUE TITLE
Telegraf on Windows fails with "File not found"

### ISSUE THREAD

**Issue by alexdrl** [influxdata/telegraf#8756]
### Relevant telegraf.conf:

```toml
# Parse a complete file each interval
[[inputs.tail]]
  ## Files to parse each interval.  Accept standard unix glob matching rules,
  ## as well as ** to match recursive files and directories.
  files = ['C:/Users/alexD/Desktop/TempMT4-jose-3010/MQL4/Files/*.csv'
         ,'C:/Users/alexD/Desktop/TempMT4-jose-3615/MQL4/Files/*.csv'
     ,'C:/Users/alexD/Desktop/TempMT4-alexdrl-real-1k/MQL4/Files/*.csv'

]

  from_beginning = true

  watch_method = "poll"

  ## Whether file is a named pipe
  pipe = false

  ## Data format to consume.
  ## Each data format has its own unique set of configuration options, read
  ## more about them here:
  ##   https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
  data_format = "csv"

  ## Indicates how many rows to treat as a header. By default, the parser assumes
  ## there is no header and will parse the first row as data. If set to anything more
  ## than 1, column names will be concatenated with the name listed in the next header row.
  ## If `csv_column_names` is specified, the column names in header will be overridden.
  csv_header_row_count = 0

  ## For assigning custom names to columns
  ## If this is specified, all columns should have a name
  ## Unnamed columns will be ignored by the parser.
  ## If `csv_header_row_count` is set to 0, this config must be used
  csv_column_names = [ "timestamp", "acc_name", "acc_number", "acc_balance", "acc_margin", "acc_margin_level", "acc_equity", "acc_profit", "acc_free_margin", "acc_currency", "acc_num_orders"]

  ## For assigning explicit data types to columns.
  ## Supported types: "int", "float", "bool", "string".
  ## Specify types in order by column (e.g. `["string", "int", "float"]`)
  ## If this is not specified, type conversion will be done on the types above.
  csv_column_types = [ "string", "string", "string", "float", "float", "float", "float", "float", "float", "string", "int" ]

  ## Indicates the number of rows to skip before looking for header information.
  csv_skip_rows = 0

  ## Indicates the number of columns to skip before looking for data to parse.
  ## These columns will be skipped in the header as well.
  csv_skip_columns = 0

  ## The separator between csv fields
  ## By default, the parser assumes a comma (",")
  csv_delimiter = ";"

  ## The character reserved for marking a row as a comment row
  ## Commented rows are skipped and not parsed
  csv_comment = ""

  ## If set to true, the parser will remove leading whitespace from fields
  ## By default, this is false
  csv_trim_space = false

  ## Columns listed here will be added as tags. Any other columns
  ## will be added as fields.
  csv_tag_columns = [ "acc_name", "acc_number" ]

  ## The column to extract the name of the metric from. Will not be
  ## included as field in metric.
  csv_measurement_column = ""

  ## The column to extract time information for the metric
  ## `csv_timestamp_format` must be specified if this is used.
  ## Will not be included as field in metric.
  csv_timestamp_column = "timestamp"

  ## The format of time data extracted from `csv_timestamp_column`
  ## this must be specified if `csv_timestamp_column` is specified
  csv_timestamp_format = "2006.01.02 15:04:05"

  ## The timezone of time data extracted from `csv_timestamp_column`
  ## in case of there is no timezone information.
  ## It follows the  IANA Time Zone database.
  csv_timezone = "Europe/Sofia"
```

### System info:

Telegraf binary on Windows 10.

Telegraf 1.15+

### Steps to reproduce:

Setting up some .tail input on Windows, having this error:

2021-01-27T10:42:25Z E! [inputs.tail] Malformed log line in "C:\\Users\\alexD\\Desktop\\TempMT4-alexdrl-real-1k\\MQL4\\Files\\2500375652021127321.csv": ["2021.01.27 03:21:55;Alejandro;250037565;1534.82;46;3313.04347826087;1524;-10.82;1478;EUR;6;0\r"]: El sistema no puede encontrar la ruta especificada.
2021-01-27T10:42:26Z E! [inputs.tail] Malformed log line in "C:\\Users\\alexD\\Desktop\\TempMT4-jose-3010\\MQL4\\Files\\2500330102021127322.csv": ["2021.01.27 03:23:14;;250033010;7343.44;88.54591260543322;8181.247204803776;7244.16;-99.27999999999999;7155.614087394567;EUR;27;0\r"]: El sistema no puede encontrar la ruta especificada.

Basically the error: "The system cannot find the specified file.", but in the log I see the file and the content on that...

### Expected behavior:

CSV read correctly.

### Actual behavior:

2021-01-27T10:42:25Z E! [inputs.tail] Malformed log line in "C:\\Users\\alexD\\Desktop\\TempMT4-alexdrl-real-1k\\MQL4\\Files\\Del Rincon Lopez Alejandro2500375652021127321.csv": ["2021.01.27 03:21:55;Del Rincon Lopez Alejandro;250037565;1534.82;46;3313.04347826087;1524;-10.82;1478;EUR;6;0\r"]: El sistema no puede encontrar la ruta especificada.
2021-01-27T10:42:26Z E! [inputs.tail] Malformed log line in "C:\\Users\\alexD\\Desktop\\TempMT4-jose-3010\\MQL4\\Files\\Qablaoui Fath Zakaria2500330102021127322.csv": ["2021.01.27 03:23:14;Qablaoui Fath Zakaria;250033010;7343.44;88.54591260543322;8181.247204803776;7244.16;-99.27999999999999;7155.614087394567;EUR;27;0\r"]: El sistema no puede encontrar la ruta especificada.

Basically the error: "The system cannot find the specified file.", but in the log I see the file and the content on that...

### Additional info:

Tried some versions back and version 1.14 of telegraf finds the contents and parses ok, but I don't have csv_timezone, so rolling back does not work.
