### ISSUE TITLE
Native Mode - interface not working / showing in Tcpdump

### ISSUE THREAD

**Issue by cinntech** [influxdata/telegraf#8767]
### Relevant telegraf.conf:

```toml
[[inputs.ping]]
        #hostname = "wan_xplornet2"
        method = "native"
        urls = ["8.8.8.8"]
        count = 4
        ping_interval = 1.0
       #interface = "eth1"
[inputs.ping.tags]
interface = "eth1"

[[inputs.ping]]
        #hostname = "wan_xplornet1"
        method = "native"
        urls = ["8.8.4.4"]
        count = 4
        ping_interval = 1.0
        # interface = "eth0"
[inputs.ping.tags]
interface = "eth0"

```

### System info:

Telegraf 1.17.1 (git: HEAD 8907e61a)
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
Hyper-V VM with 3 nics
X-Influxdb-Version: 1.8.3

### Steps to reproduce:

1. ... sudo tcpdump -nni eth1 icmp shows no output. 
2.   sudo tcpdump -nni eth0  icmp shows all output
3. ... ping -I eth1 8.8.8.8 works as intended 

### Expected behavior:
See traffic on tcpdump -nni eth1 icmp  and tcpdump -nni eth0  icmp 

### Actual behavior:
See all traffic on tcpdump -nni eth0  icmp 

All traffic is going out the default interface and not taking the -I variable (interface = foo)

### Additional info:
> ping,host=c-nms,interface=eth1,url=8.8.8.8 average_response_ms=55.011149,maximum_response_ms=55.011149,minimum_response_ms=55.011149,packets_received=1i,packets_transmitted=1i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0,ttl=115i 1611812299000000000
> ping,host=c-nms,interface=eth0,url=8.8.4.4 average_response_ms=55.135049,maximum_response_ms=55.135049,minimum_response_ms=55.135049,packets_received=1i,packets_transmitted=1i,percent_packet_loss=0,result_code=0i,standard_deviation_ms=0,ttl=115i 1611812299000000000

root@c-nms:/etc/netplan# cat 50-cloud-init.yaml
network:
    version: 2
    renderer: networkd
    ethernets:
        eth0:
            dhcp4: true
            dhcp4-overrides:
                    route-metric: 100
        eth1:
            dhcp4: true
            dhcp4-overrides:
                    route-metric: 200
        eth2:
            dhcp4: true
            dhcp4-overrides:
                    route-metric: 300

If change to exec mode I get a panic:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b2542a]

goroutine 33 [running]:
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).pingToURL(0xc000050460, 0xc000442ee1, 0x7, 0x34ae180, 0xc00021a1c0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping_notwindows.go:22 +0x18a
github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather.func1(0xc000050460, 0x34ae180, 0xc00021a1c0, 0xc000442ee1, 0x7)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:138 +0x9b
created by github.com/influxdata/telegraf/plugins/inputs/ping.(*Ping).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/ping/ping.go:131 +0xd2
