### ISSUE TITLE
SNMP Trap - Panic Invalid Memory or Nil Pointer Reference

### ISSUE THREAD

**Issue by DustyArmstrong** [influxdata/telegraf#8774]
### Relevant telegraf.conf:

```
[[inputs.snmp_trap]]
service_address = "udp://:162"
timeout = "5s"
sec_name = "myuser"
auth_protocol = "SHA"
auth_password = "myauth"
sec_level = "authNoPriv"
priv_protocol = ""
priv_password = ""
version = "3"
```

### System info:

1.7.2 (Docker Container)

### Docker

```

version: '2'
services:
        influxdb:
                image: influxdb:latest
                container_name: influxdb
                restart: unless-stopped
                ports:
                       - '8086:8086'
                volumes:
                       - ./influxdb-storage:/var/lib/influxdb
                environment:
                       - INFLUXDB_DB=db0
                       - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
                       - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
        telegraf:
                image: telegraf:latest
                container_name: telegraf
                restart: unless-stopped
                ports:
                       - '162:162/udp'
                volumes:
                      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
volumes:
       influxdb-storage:

```

### Steps to reproduce:

1. Docker container running as above.
2. Run ```telegraf --test```.
3. Send a trap to the address of Telegraf.

Alternatively:

1. Run ```telegraf --test```.
2. Wait for the failure to occur. 

### Expected behavior:

SNMP trap to be received and processed to Influxdb.

### Actual behavior:

No traps are received. I have verified via `tcpdump` on port 162 that traps are being received to the container itself, both on v2 and v3. The output of `docker logs telegraf` appears to suggest that the input plugin has been loaded and listening on port 162. I have been testing from a QNAP device to trigger an SNMP trap. Using `telegraf --test` and triggering the trap results in the following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e5249d]

goroutine 10 [running]:
github.com/soniah/gosnmp.(*TrapListener).Close(0xc000181d10)
        /go/pkg/mod/github.com/soniah/gosnmp@v1.25.0/trap.go:131 +0x3d
github.com/influxdata/telegraf/plugins/inputs/snmp_trap.(*SnmpTrap).Stop(0xc00027c380)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp_trap/snmp_trap.go:251 +0x36
github.com/influxdata/telegraf/agent.stopServiceInputs(0xc00011c300, 0xa, 0x10)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:445 +0x82
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs(0xc000116248, 0x3490f80, 0xc0005a2780, 0x0, 0xc0000e5ce0, 0x0, 0xc000551fb8)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:434 +0x1b7
github.com/influxdata/telegraf/agent.(*Agent).test.func4(0xc000388994, 0xc000116248, 0x3490f80, 0xc0005a2780, 0x0, 0xc0000e5ce0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:977 +0x8b
created by github.com/influxdata/telegraf/agent.(*Agent).test
        /go/src/github.com/influxdata/telegraf/agent/agent.go:975 +0x352
```

### Additional info:

I am aware that my dockerfile does not make considerations for external mibs etc. I have set this up manually at present (I will do it properly in future). I have had some community assistance already but this seems to be a bug.
