### ISSUE TITLE
proxmox plugin - [inputs.proxmox] Error in plugin: search domain is not set

### ISSUE THREAD

**Issue by er-pratyush** [influxdata/telegraf#8776]
### Relevant telegraf.conf:

```toml
# Configuration for telegraf agent
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false
[[outputs.influxdb_v2]]
  urls = ["http://192.x.x.x:8086"]
  token = "xxxx=="
  organization = "xxx"
  bucket = "proxmox"
[[inputs.proxmox]]
  ## API connection configuration. The API token was introduced in Proxmox v6.2. Required permissions for user and token: PVEAuditor role on /.
  base_url = "https://192.x.x.x:8006/api2/json"
  api_token = "infTele1@pve!monitor=xxx-xxx-xxx-xxx-xxx"
  ## Node name, defaults to OS hostname
  node_name = "pve"

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  insecure_skip_verify = true

  # HTTP response timeout (default: 5s)
  response_timeout = "5s"
```

### System info:

telegraf -version
Telegraf 1.17.2 (git: HEAD 74011e22)

pve version
proxmox-ve: 6.3-1 (running kernel: 5.4.78-2-pve)
pve-manager: 6.3-3 (running version: 6.3-3/eee5f901)
pve-kernel-5.4: 6.3-3
pve-kernel-helper: 6.3-3
pve-kernel-5.4.78-2-pve: 5.4.78-2
pve-kernel-5.4.73-1-pve: 5.4.73-1

telegraf host : ubuntu 20.04-1 container on proxmox
### Docker
no Docker

### Steps to reproduce:

running telegraf throws error "search domain is not set"

### Expected behavior:

should not throw error

### Actual behavior:

2021-01-30T01:18:45Z I! Starting Telegraf 1.17.2
2021-01-30T01:18:45Z I! Using config file: /etc/telegraf/telegraf.conf
2021-01-30T01:18:45Z I! Loaded inputs: proxmox
2021-01-30T01:18:45Z I! Loaded aggregators: 
2021-01-30T01:18:45Z I! Loaded processors: 
2021-01-30T01:18:45Z I! Loaded outputs: influxdb_v2
2021-01-30T01:18:45Z I! Tags enabled: host=influx
2021-01-30T01:18:45Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"influx", Flush Interval:10s
2021-01-30T01:18:45Z D! [agent] Initializing plugins
2021-01-30T01:18:45Z D! [agent] Connecting outputs
2021-01-30T01:18:45Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2021-01-30T01:18:45Z D! [agent] Successfully connected to outputs.influxdb_v2
2021-01-30T01:18:45Z D! [agent] Starting service inputs
2021-01-30T01:18:50Z E! [inputs.proxmox] Error in plugin: search domain is not set
2021-01-30T01:18:55Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2021-01-30T01:19:00Z E! [inputs.proxmox] Error in plugin: search domain is not set
2021-01-30T01:19:05Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics

### Additional info:

telegraf/plugins/inputs/proxmox/proxmox.go line 96 checks for nodeDns.Data.Searchdomain == ""

{"data":{"dns1":"192.x.x.x","search":"xxxxx.xx"}}
