### ISSUE TITLE
GNMI plugin missing measurement name when when writing to influxdb

### ISSUE THREAD

**Issue by jrametta** [influxdata/telegraf#8783]
Hi, I was not seeing GNMI metric data being sent to influxdb, so I instead enabled the file output plugin with data_format="influx".  I am seeing similar error to #6391                                                             
                                                                                                                                                                                                                                    
```                                                                                                                                                                                                                                 
telegraf_1    | 2021-02-02T07:01:10Z D! [inputs.gnmi] Connection to gNMI device 10.196.21.52:50051 established                                                                                                                      
telegraf_1    | 2021-02-02T07:01:20Z D! [outputs.file] Could not serialize metric: invalid name                                                                                                                                     
telegraf_1    | 2021-02-02T07:01:20Z D! [outputs.file] Wrote batch of 1 metrics in 166.729µs                                                                                                                                        
telegraf_1    | 2021-02-02T07:01:20Z D! [outputs.file] Buffer fullness: 0 / 10000000 metrics                                                                                                                                        
```                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                    
### Relevant telegraf.conf:                                                                                                                                                                                                         
<!-- Place config in the toml code section. -->                                                                                                                                                                                     
```toml                                                                                                                                                                                                                             
  [[inputs.gnmi.subscription]]                                                                                                                                                                                                      
    origin = "device"                                                                                                                                                                                                               
    path = "/System/procsys-items/sysload-items"                                                                                                                                                                                    
    subscription_mode = "sample"                                                                                                                                                                                                    
    sample_interval = "10s"                                                                                                                                                                                                         
```                                                                                                                                                                                                                                 
If I set file output plugin to json, I can see name is empty in the output ("name":"")                                                                                                                                              
                                                                                                                                                                                                                                    
```                                                                                                                                                                                                                                 
telegraf_1    | 2021-02-02T07:03:53Z D! [inputs.gnmi] Connection to gNMI device 10.196.21.52:50051 established¬¬                                                                                                                    
telegraf_1    | {"fields":{"device:/System/procsys_items_sysload-items_loadAverage15m":"0.5","device:/System/procsys_items_sysload-items_loadAverage1m":"0.14","device:/System/procsys_items_sysload-items_loadAverage5m":"0.38","device:/System/procsys_items_sysload-items_loadAverage5sec":"9.0","device:/System/procsys_items_sysload-items_name":"sysload","device:/System/procsys_items_sysload-items_runProc":1,"device:/System/procsys_items_sysload-items_totalProc":359},"name":"","tags":{"host":"telemetry2.lab","path":"","source":"10.196.21.52"},"timestamp":1612249437}                                                                                                                     
```                                                                                                                                                                                                                                 
Per the other defect mentioned, if I configure `name_override`, then the measurement successfully written and given the configured name.                                                                                            
                                                                                                                                                                                                                                    
### System info:                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    
- Telegraf 1.17.1 (git: HEAD 8907e61a)                                                                                                                                                                                              
- cisco Nexus9000 93180YC-EX                                                                                                                                                                                                        
- NXOS: version 9.3(5)                                                                                                                                                                                                              
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    
<!-- If your bug involves third party dependencies or services, it can be very helpful to provide a Dockerfile or docker-compose.yml that reproduces the environment you're testing against -->                                     
                                                                                                                                                                                                                                    
### Steps to reproduce:                                                                                                                                                                                                             
                                                                                                                                                                                                                                    
<!-- Describe the steps to reproduce the bug. -->                                                                                                                                                                                   
                                                                                                                                                                                                                                    
1. configure GNMI plugin with subscription to Cisco                                                                                                                                                                                 
2. start telegraf                                                                                                                                                                                                                   
                                                                                                                                                                                                                                    
### Expected behavior:                                                                                                                                                                                                              
                                                                                                                                                                                                                                    
Influxdb measurement is successfully written without error                                                                                                                                                                          
                                                                                                                                                                                                                                    
### Actual behavior:                                                                                                                                                                                                                
                                                                                                                                                                                                                                    
Receive "Could not serialize metric: invalid name"  error msg                                                                                                                                                                       
                                                                                                                                                                                                                                    
This error seems to occur for any path given, not just the one mentioned.
