### ISSUE TITLE
Issue with Minecraft Plugin (Telegraf) 

### ISSUE THREAD

**Issue by InTheFlipside** [influxdata/telegraf#8806]
### Relevant telegraf.conf:

```toml
[[inputs.minecraft]]  # server address for minecraft
server = "45.140.x.x" # port for RCON
port = "25592"   # password RCON for mincraft server
password = "MyGoodPassword"  
```

### System info:

OS : Debian 10 (VM)

### Steps to reproduce:

1. Set up 1.16.4 Minecraft server (Internet) 
2. Enable RCON 
3. Set up Telegraf plugin on another network
4. Check if RCON works

### Expected behavior:

We should have a "Minecraft" table on Grafana to monitor the Minecraft server

### Actual behavior:

No minecraft measurements are sent.

### Additional info:

First of all, i'm sorry if my english is not perfect, i'm doing my best to be clear. 

I'm using OuiHeberg.com to rent the Minecraft. The issue is not from RCON since I can login on a HypeRCON (Android App), 
I can also see Telegraf on my console : 
  [19:16:50] [RCON Listener #1/INFO]: Thread RCON Client /178.32.x.x started
