### ISSUE TITLE
OPC UA input plugin erroneous bad data (code 0xC0)

### ISSUE THREAD

**Issue by zeldalegends** [influxdata/telegraf#8826]
### Relevant telegraf.conf:

```toml
[[outputs.influxdb]]
  urls = ["http://127.0.0.1:8086"]
  database = "telegraf"
[[inputs.opcua]]
  name = "OPC Expert Simulation Server"
  endpoint = "opc.tcp://127.0.0.1:57895/simulation"
  connect_timeout = "10s"
  request_timeout = "5s"
  security_policy = "None"
  security_mode = "None"
  nodes = [
    {name="Ramp", namespace="3", identifier_type="s", identifier="Instrument01", data_type="double", description=""},
    {name="Sine", namespace="3", identifier_type="s", identifier="Instrument02", data_type="double", description=""},
  ]
```

### System info:

Telegraf 1.17.0 (git: HEAD 3f7a54c9)
Windows 10 Pro 19042.746
### Docker

No docker, win-binary version

### Steps to reproduce:

1. Install OPC Expert (https://opcexpert.com/)
2. Enable Simulation Server in Options
3. Add Calculations to Instrumentation01 and Instrumentation02 as Ramp and Sine

### Expected behavior:

The OPC Expert Simulation Server prompts a ramp and a sinusoid with quality code 0xC0. According to the following link, 0xC0 is considered as "Good" quality:
https://www.opcsupport.com/s/article/What-are-the-OPC-Quality-Codes
The values of the ramp and the sinusoid should be correctly processed by the input plugin and passed to the influxdb output plugin and stored into the db. Actually it is done using external Node,js OPC UA libraries, as an example.

### Actual behavior:

The input plugin discards the values, apparently misinterpreting the 0xC0 code as "not OK":
2021-02-06T16:34:20Z E! [inputs.opcua] Error in plugin: Get Data Failed: Status not OK: 0xC0
So, the output plugin is never called and the influxdb not updated.
