### ISSUE TITLE
Telegraf CloudWatch Logs output plugin

### ISSUE THREAD

**Issue by kpvenugo** [influxdata/telegraf#8856]
## Feature Request
Telegraf CloudWatch **Logs** output plugin

We do have OP plugin for cloudWatch Metrics, but I feel that we are missing on advantages of cloudWatch without logs integration. I am wondering if this request was considered earlier. 

Also for somebody looking to push raw logs or the syslog metrics onto cloudWatch wouldn't require a different agent if this is added to Telegraf.

I understand that metrics and logs are different data concepts(periodic v/s event driven nature) but it doesn't sound illlogical to convert a log to metrics like it is done by syslog input plugins I believe. Please do let me know if there is any limitation with this.

Advance Thanks
-KP

**Comment by avoidik** [comment]
https://github.com/influxdata/telegraf/pull/8639

**Comment by avoidik** [comment]
hello @i-prudnikov much appreciated for the feature you're added, would you please suggest how to interconnect something like `[[inputs.logparser]]` and `[[outputs.cloudwatch_logs]]`? specifically `log_stream`, `log_data_metric_name`, and `log_data_source` attributes

```toml
[[inputs.logparser]]
    files = ["/var/log/auth.log"]
    from_beginning = false
    watch_method = "inotify"
    [inputs.logparser.grok]
      patterns = ['''%{SYSLOGTIMESTAMP:system.auth.timestamp} %{DATA:system.auth.hostname} sshd(?:\[%{POSINT:system.auth.pid}\])?: %{DATA:system.auth.ssh.event} user %{DATA:system.auth.user} from %{IPORHOST:system.auth.ip}''']
      measurement = "auth_log"

[[outputs.cloudwatch_logs]]
    region = "eu-west-1"
    log_group = "auth-log"
    log_stream = ""
    log_data_metric_name = ""
    log_data_source  = ""
```
