### ISSUE TITLE
Officially support aggregator Starlark scripts

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#8869]
## Feature Request

support calling push() in Starlark scripts so that Starlark processor scripts can fully implement all the features that aggregators would need.

### Proposal:

allow running starlark as an aggregator. this would probably mean supporting something like this:
```toml
[[aggregators.starlark]]
  period = "30s"
  delay = "5m"
  grace = "5m" 
  drop_original = true
  source = '''
state = {}

def apply(metric): # or should this be named add() like the aggregators?
    last = state["last"]
    if last != None:
        metric.fields["value"] = last.fields["value'] + metric.fields["value"]
    state["last"] = deepcopy(metric) # do I need to copy it if I'm not returning it?
    return None

def push(): # called when we push this group of metrics down the line
    last = state["last"]
    state["last"] = None
    return last
'''
```

(see [Aggregator Plugins](https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#aggregator-plugins) for details on aggregator settings)

### Current behavior:

There is no call to push, and as such it's not possible to guarantee the aggregate record will be written out in the right aggregation window. This can be problematic for infrequently collected metrics.

### Desired behavior:

support writing aggregators in Starlark.

### Use case: 

People have asked for this, and will continue to build it in processors if we don't add it, though not ideal.
