### ISSUE TITLE
[azure_monitor] Cannot write NaN-valued metrics

### ISSUE THREAD

**Issue by ethanshea-ms** [influxdata/telegraf#8928]
### Relevant telegraf.conf:

Metrics are being ingested from a Prometheus endpoint:

```toml
[[inputs.prometheus]]
  metric_version = 2
  urls = ["http://edgeAgent:9600/metrics"]

[[outputs.azure_monitor]]
  region = "westus"
  resource_id = "/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/myResourceGroup/providers/Microsoft.Devices/IotHubs/myIotHub"
```

One of these metrics contains a `NaN`.

```
edgeAgent_command_latency_seconds{edge_device="myEdgeDevice",instance_number="00000000-0000-0000-0000-000000000001",iothub="myIotHub",ms_telemetry="True",quantile="0.1",url="http://edgeAgent:9600/metrics"} NaN
```

`NaN` seems to be permissible according to prometheus, which [allows](https://prometheus.io/docs/concepts/data_model/) values to contain a `float64` value.

### System info:

Telegraf: 1.17.3
OS: Ubuntu 18.04

### Steps to reproduce:

1. Create a telegraf.toml with an azure monitor output.
2. Ingest a NaN-valued metric

### Expected behavior:

Ideally, NaN is correctly serialized to JSON and uploaded to Azure Monitor. Otherwise, the problematic metric is skipped and a warning is emitted.

### Actual behavior:

The following error is emitted and no metrics are uploaded.

```
2021-03-01T18:36:11Z E! [agent] Error writing to outputs.azure_monitor: json: unsupported value: NaN
```
