### ISSUE TITLE
http input support dynamic body

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#8952]
### Proposal

Is it possible to dynamically change request body in http input for each input cycle

### Current behavior

I need to read data from a HTTP endpoint with time window in request body
Currently the request body can only be hard-coded in the config file

```toml
# Read formatted metrics from one or more HTTP endpoints
[[inputs.http]]
  ## One or more URLs from which to read formatted metrics
  urls = [
    "http://127.0.0.1:8808/metrics"
  ]

  ## HTTP method
  method = "POST"

  ## HTTP entity-body to send with POST/PUT requests.
  body = '''{
    "startTime": "2021/03/08 09:00:00",
    "endTime": "2021/03/08 09:10:00"
  }'''
```

### Desired behavior:

Is it possible to dynamically change the body, says in this cycle the body is like below

```toml
  body = '''{
    "startTime": "2021/03/08 09:00:00",
    "endTime": "2021/03/08 09:10:00"
  }'''
``` 

With `agent.interval` set to `10s`.
In the next cycle, the body is dynamically changed to 

```toml
  body = '''{
    "startTime": "2021/03/08 09:00:10",
    "endTime": "2021/03/08 09:10:10"
  }'''
```

### Use case

This sliding time window feature is crucial to sync monitoring data from cloud providers like Tencent Cloud, because it requires time window parameter in the request body.
