### ISSUE TITLE
Can't use starlark with constants

### ISSUE THREAD

**Issue by luanhdeandrade** [influxdata/telegraf#8957]
Hello Everybody. I just can't use the starlark plugin. I am doing just like the docs. Is there something broken?

### Relevant telegraf.conf:

```toml
[[processors.starlark]]
   script = "/opt/pgpool_cloudwatch.star"

   ## The constants of the Starlark script.
   [processors.starlark.constants]
       somecustomnum = 10
       somecustomstr = "mycustomfield"
```

### System info:

Telegraf version: 1.17.3 (docker)

### Docker

Not relevant

### Steps to reproduce:

1. Use the starlark processor with constants (configuration above) with any input
2. Run telegraf: 
  ```telegraf --debug --test --config /path/to/telegraf.conf```

### Expected behavior:

Starlark script be executed

### Actual behavior:

Error message: 

```2021-03-08T22:12:38Z E! [telegraf] Error running agent: Error loading config file /root/telegraf.conf: plugin processors.starlark: line 21: configuration specified the fields ["constants"], but they weren't used```
