### ISSUE TITLE
DNS Query plugin providing false/unreliable statistics

### ISSUE THREAD

**Issue by vargasvic** [influxdata/telegraf#8983]
Hello guys,

When using **dns_query input plugin** with multiple DNS servers and multiple urls, statistics don't seem reliable. Query time is very high, and compared with other DNS query tools on the same machine at the same time, query time results are very different. 
Telegraf plugin statistics show very high times.

### Relevant telegraf.conf:
```toml
[[inputs.dns_query]]
   servers = ["1.1.1.1", "8.8.8.8"]
   domains = ["www.google.com",
     "www.amazon.com",
     "www.pichincha.com",
     "www.youtube.com"
   ]
   record_type = "A"
   port = 53
   timeout = 5
```
Thank you for your help!
