### ISSUE TITLE
[[outputs.influxdb]] drops metric_type clobbering counter metrics

### ISSUE THREAD

**Issue by jeff-minard-ck** [influxdata/telegraf#8999]
I have an ecosystem in which there is Application A, two telegrafs and NewRelic. I want counter metrics from AppA to be picked up by TelegrafA, sent through TelegrafB, and eventually show up in New Relic.

AppA has a prometheus style `/metrics` endpoint with a `Counter` value reported out of it. I setup TelegrafA instance configured as such:

```toml
[[inputs.prometheus]]
  metric_version = 2
  urls = [
    "http://my-coolthing.dns.name:8888/metrics",
  ]
[[outputs.influxdb]]
  urls = [
    "http://upstream-telegraf:2201"
  ]
```

TelegrafA scrapes the metrics fine and forwards them to our "central" telegraf service, TelegrafB. TelegrafB is setup (cribbed, of course) something like:

```toml
[[inputs.influxdb_listener]]
  service_address = ":2201"

[[outputs.newrelic]]
  insights_key = "super-secret-key-here"
```

When the counter value gets to New Relic, it is **incorrectly** recorded as a gauge.

My theory, is that when the data is transferred between the two telegrafs _in line protocol format_, it loses the metadata which identifies the value as a counter. If I run a single telegraf with the configuration:

```toml
[[inputs.prometheus]]
  metric_version = 2
  urls = [
    "http://my-coolthing.dns.name:8888/metrics",
  ]
[[outputs.newrelic]]
  insights_key = "super-secret-key-here"
```

The counter DOES make it to NewRelic as the proper type.

### Proposal:

Can the `[[outputs.influxdb]]` plugin output some kind of value that informs the receiving `[[inputs.influxdb_listener]]` of the metric type?

### Current behavior:

Counters lose metric type and show up as gauges.

### Desired behavior:

Counters remain counters

### Use case: 

We wish to have a hub/spoke type model of telegraf deployments, when it comes to scraping prom end points, but would like to aggregate through a central collector.
