### ISSUE TITLE
Modbus: Name Prefix stacks up

### ISSUE THREAD

**Issue by orbweaver** [influxdata/telegraf#9022]
I'm connecting to a device and collecting discrete inputs, input registers and holding registers.  I specify a name_prefix in order to do some processing, i.e. pass to a script and also to influxdb.  But, when the data arrives, some of the name field gets multiples of the name_prefix "egx150warehouse_" added to the beginning.  
the json output to my script, as well as the name in influxdb will look like these examples...

one copy of holding registers, with the value:
"name" : "egx150warehouse_modbus"

two copies of input register data, with the value:
"name" : "egx150warehouse_egx150warehouse_modbus"

three copies of the discrete output data, with the value:
"name" : "egx150warehouse_egx150warehouse_egx150warehouse_modbus"

### Relevant telegraf.conf:

```toml
[[inputs.modbus]]
 name = "gateway-egx"
 slave_id = 1
 controller = "tcp://192.168.1.24:502"
 interval = "60s"
 timeout = "10s"
 name_prefix = "egx150warehouse_"

discrete_inputs = [
{ name = "High Space Temperature", address = [35]},
{ name = "Low Space Temperature", address = [39]},
{ name = "Supply Fan Failure", address = [48]},
]

holding_registers = [
{ name = "Setpoint_Fahrenheit", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [8,9]},
{ name = "System Space Temp_Fahrenheit", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [122,123]},
]

input_registers = [
{ name = "Supply Air Temp_Fahrenheit", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [108,109]},
{ name = "Cooling Output_Percent", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [20,21]},
{ name = "Return Air Temp_Fahrenheit", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [64,65]},
{ name = "Space Relative Humidity_Percent", byte_order = "CDAB", data_type = "FLOAT32-IEEE", scale=1.0, address = [102,103]},
{ name = "Fan Run", byte_order = "AB", data_type = "INT16" , scale=1.0, address = [174]},
]

[[processors.regex]]
  namepass = ["egx150warehouse_*"]
  [[processors.regex.tags]]
    key = "name"
    pattern = "^(.*)$"
    replacement = "${1}"
    result_key = "datasource"

[[processors.override]]
      namepass = ["egx150warehouse_*"]
  [processors.override.tags]
     usescale = "1"

[[outputs.exec]]
  command = ["/bin/telegraf2customDB.pl"]
  data_format = "json"
  json_timestamp_units = "1s"
  flush_interval = "60s"
  timeout = "30s"
  namepass = ["egx150warehouse_*"]

[[outputs.influxdb]]
  flush_interval = "60s"
  timeout = "30s"
  namepass = ["egx150warehouse_*"]

```

### System info:
running telegraf 1.17.2 on CentOS 8

I'll probably break up the register groups into different files, each with their own prefix and namepass, to see how that works.
