### ISSUE TITLE
Docker input panics with "slice bounds out of range"

### ISSUE THREAD

**Issue by aleho** [influxdata/telegraf#9029]
Using `inputs.docker` fails with the following panic:

```
panic: runtime error: slice bounds out of range [:4] with capacity 0
goroutine 86 [running]:
github.com/influxdata/telegraf/plugins/inputs/docker.parseContainerStats(0xc000f0f200, 0x42dc618, 0xc00007c3a0, 0xc000d06000, 0xc0005663c0, 0x40, 0xc0000b47c0, 0x3, 0x4, 0xc0
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:742 +0x256a
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainerInspect(0xc0005898c0, 0xc0005663c0, 0x40, 0xc00027a680, 0x1, 0x4, 0xc00055c060, 0x26, 0xc00067e0
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:630 +0x29c
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).gatherContainer(0xc0005898c0, 0xc0005663c0, 0x40, 0xc00027a680, 0x1, 0x4, 0xc00055c060, 0x26, 0xc00067e000, 0x4
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:557 +0x919
github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather.func1(0xc000476d90, 0xc0005898c0, 0x42dc618, 0xc00007c3a0, 0xc0005663c0, 0x40, 0xc00027a680, 0x1, 0x4, 0
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:281 +0xbd
created by github.com/influxdata/telegraf/plugins/inputs/docker.(*Docker).Gather
        /go/src/github.com/influxdata/telegraf/plugins/inputs/docker/docker.go:279 +0x3f8
```

### Relevant telegraf.conf:
```toml
[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"

  container_names = [
    "some",
    "containers"
  ]

  gather_services = false
  source_tag = false
  container_name_include = []
  container_name_exclude = []
  timeout = "5s"
  perdevice = true
  total = false
  docker_label_include = []
  docker_label_exclude = []
```

### System info:

Debian Buster
Telegraf 1.18.0
Docker CE 20.10.5

```
$ id telegraf
uid=996(telegraf) gid=995(telegraf) groups=995(telegraf),997(docker)
```
