### ISSUE TITLE
Graylog output plugin: Add TCP option

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9034]
### Proposal:
Add a TCP option to [Graylog (Gelf) Output Plugin](https://github.com/influxdata/telegraf/tree/master/plugins/outputs/graylog). 

### Current behavior:
Plugin only supports (compressed) UDP

```toml
[[outputs.graylog]]
  ## UDP endpoint for your graylog instances.
  servers = ["127.0.0.1:12201"]
```

### Desired behavior:
Support for [GELF TCP](https://docs.graylog.org/en/4.0/pages/gelf.html#gelf-via-tcp) option in addition to UDP. 

### Use case: 
Want to use Telegraf to collect log files and send log messages to other systems which does not support UDP gelf. Currently cannot do this and have to use other agents.

Benefits to GELF TCP such as bigger payload, encryption possible, more reliable, could be parsed with standard json receiver etc.
