### ISSUE TITLE
[inputs.ping] ping failed: failed to run pinger: socket: permission denied

### ISSUE THREAD

**Issue by pmalek-sumo** [influxdata/telegraf#9068]
Ping input plugin fails when using `method = "native"` in telegraf `1.18.0`. Switching to `1.17.3` or changing the method to `"exec"` makes the error go away.

### Relevant telegraf.conf:

```toml
[agent]
  interval = "5s"
  flush_interval = "10s"
  logtarget = "stderr"

[[inputs.ping]]
  urls = ["1.1.1.1"]
  method = "native"
```

### Docker

It also fails in docker with the same config:

```
docker run --rm --name telegraftest -v $(pwd)/conf/:/etc/telegraf/ telegraf:1.18.0 telegraf --config /etc/telegraf/telegraf.conf
```

### Steps to reproduce:

Described above

### Expected behavior:

No error.

### Actual behavior:

2021-03-29T18:38:04Z I! Starting Telegraf 1.18.0
2021-03-29T18:38:04Z I! Loaded inputs: ping
2021-03-29T18:38:04Z I! Loaded aggregators:
2021-03-29T18:38:04Z I! Loaded processors:
2021-03-29T18:38:04Z I! Loaded outputs: sumologic
2021-03-29T18:38:04Z I! Tags enabled: host=pc
2021-03-29T18:38:04Z I! [agent] Config: Interval:5s, Quiet:false, Hostname:"pc", Flush Interval:10s
2021-03-29T18:38:05Z E! [inputs.ping] ping failed: failed to run pinger: socket: permission denied

### Additional info:

Run on Ubuntu/Linux box with kernel 5.4.0-70 kernel
