### ISSUE TITLE
Telegraf throws: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Zysiu** [influxdata/telegraf#9111]
I am running Telegraf v.1.18.1 on Azure App Service using Docker Compose. I created a Docker Image with telegraf.conf copied inside.

### Relevant telegraf.conf:

```toml
[agent]
  interval = "20s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "20s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false
  debug = true


[[outputs.azure_monitor]]
  region = "${TELEGRAF_AZ_MONITOR_REGION}"
  resource_id = "${TELEGRAF_AZ_MONITOR_RESOURCE_ID}"
  namespace_prefix = "app-${HOSTNAME}-"

[[inputs.prometheus]]
  urls = ["${TELEGRAF_PROMETHEUS_ENDPOINT}"]
  metric_version = 2
```

### Relevant Dockerfile:

```dockerfile
FROM telegraf:1.18.1

COPY telegraf.conf /etc/telegraf/telegraf.conf

CMD ["telegraf"]
```

### Relevant docker-compose.yml:

```yaml
version: '3.3'
services:
  app:
    image: jfrog/app
    ports:
      - "80:80"
    hostname: app
  telegraf:
    image: jfrog/telegraf
    hostname: telegraf
    links:
      - app
    environment:
      - "TELEGRAF_AZ_MONITOR_RESOURCE_ID=/subscriptions/*****/resourceGroups/*****/providers/Microsoft.Web/sites/*****"
      - "TELEGRAF_AZ_MONITOR_REGION=northeurope"
      - "TELEGRAF_PROMETHEUS_ENDPOINT=http://app/metrics"
      - "AZURE_TENANT_ID=*****"
      - "AZURE_CLIENT_ID=*****"
      - "AZURE_CLIENT_SECRET=*****"
```

### System info:

Telegraf v.1.18.1 running inside Docker Container on Azure App Service

### Steps to reproduce:

Create Docker Image with provided Dockerfile and upload it to repository.
Deploy on Azure App Service using Docker-Compose.

### Expected behavior:

Telegraf running and sending metrics to Azure Monitor

### Actual behavior:

Telegraf starts and fails when trying to send metrics to Azure Monitor.
Log from App Service container:
```
Starting Telegraf 1.18.1
Using config file: /etc/telegraf/telegraf.conf
Loaded inputs: prometheus
Loaded aggregators:
Loaded processors:
Loaded outputs: azure_monitor
Tags enabled: host=2e3539037f7f
[agent] Config: Interval:20s, Quiet:false, Hostname:"2e3539037f7f", Flush Interval:20s
[agent] Initializing plugins
[agent] Connecting outputs
[agent] Attempting connection to [outputs.azure_monitor]
[outputs.azure_monitor] Writing to Azure Monitor URL: https://northeurope.monitoring.azure.com/subscriptions/*****/resourceGroups/*****/providers/Microsoft.Web/sites/*****/metrics
[agent] Successfully connected to outputs.azure_monitor
[agent] Starting service inputs
[outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics
[outputs.azure_monitor] Buffer fullness: 0 / 10000 metrics

- Container for ***** site ***** is unhealthy, Stopping site.
- Stopping site ***** because it is not healthy.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x11c7057]
goroutine 142 [running]:
github.com/Azure/go-autorest/autorest/adal.(*ServicePrincipalToken).refreshInternal(0xc0001c0a80, 0x42c1228, 0xc00005a068, 0x3b6e930, 0x1d, 0x0, 0x0)
	/go/pkg/mod/github.com/!azure/go-autorest/autorest/adal@v0.8.1/token.go:912 +0x717
github.com/Azure/go-autorest/autorest/adal.(*ServicePrincipalToken).EnsureFreshWithContext(0xc0001c0a80, 0x42c1228, 0xc00005a068, 0x0, 0x0)
	/go/pkg/mod/github.com/!azure/go-autorest/autorest/adal@v0.8.1/token.go:778 +0x1b4
github.com/Azure/go-autorest/autorest.(*BearerAuthorizer).WithAuthorization.func1.1(0xc00057df00, 0x1, 0x424d980, 0xc000878de0)
	/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.3/authorization.go:122 +0x103
github.com/Azure/go-autorest/autorest.PreparerFunc.Prepare(0xc000878de0, 0xc00057df00, 0x1, 0x424d980, 0xc000878de0)
	/go/pkg/mod/github.com/!azure/go-autorest/autorest@v0.9.3/preparer.go:76 +0x30
github.com/influxdata/telegraf/plugins/outputs/azure_monitor.(*AzureMonitor).send(0xc000475ad0, 0xc000894000, 0x1d2e, 0x2000, 0x0, 0x0)
	/go/src/github.com/influxdata/telegraf/plugins/outputs/azure_monitor/azure_monitor.go:348 +0x399
github.com/influxdata/telegraf/plugins/outputs/azure_monitor.(*AzureMonitor).Write(0xc000475ad0, 0xc000436000, 0x26, 0x26, 0xc000436000, 0xc000087ee0)
	/go/src/github.com/influxdata/telegraf/plugins/outputs/azure_monitor/azure_monitor.go:325 +0x5fa
github.com/influxdata/telegraf/models.(*RunningOutput).write(0xc0000fcb00, 0xc000436000, 0x26, 0x26, 0x26, 0xc000845d01)
	/go/src/github.com/influxdata/telegraf/models/running_output.go:246 +0x99
github.com/influxdata/telegraf/models.(*RunningOutput).Write(0xc0000fcb00, 0x87a5000, 0x10a000)
	/go/src/github.com/influxdata/telegraf/models/running_output.go:203 +0x1f8
github.com/influxdata/telegraf/agent.(*Agent).flushOnce.func1(0xc000850060, 0xc000859350)
	/go/src/github.com/influxdata/telegraf/agent/agent.go:853 +0x27
created by github.com/influxdata/telegraf/agent.(*Agent).flushOnce
	/go/src/github.com/influxdata/telegraf/agent/agent.go:852 +0x7a
````

### Additional info:
When I tried running that docker-compose.yml file on Centos 8 using ```docker-compose up -d``` everything was fine and Telegraf was sending metrics to Azure Monitor.
