### ISSUE TITLE
Interval 24 hours runs at 00:00 Zulu

### ISSUE THREAD

**Issue by ms-ai** [influxdata/telegraf#9142]
### Relevant telegraf.conf:

```toml
[agent]
  ## Default data collection interval for all inputs
  interval = "24h"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

```

### System info:

Windows 10, telegraf 1.9.0

### Steps to reproduce:

1. Configure agent collection with 24 h interval
2. Start at some random time, let's say 9 pm

### Expected behavior:

The data would be collected the next day at 9 pm

### Actual behavior:

The data are collected at 5 pm local time = 00:00 Zulu

### Additional info:

Due to CPU resources on data acquisition computers, the telegraf collector needs to run after 6 pm, daily.
