### ISSUE TITLE
Prometheus Remote Write

### ISSUE THREAD

**Issue by jessingrass** [influxdata/telegraf#9165]
Related PRs

https://github.com/influxdata/telegraf/issues/8682

https://github.com/influxdata/telegraf/pull/8966

https://github.com/influxdata/telegraf/pull/8967

https://github.com/influxdata/telegraf/pull/9074

**Comment by prab2014** [comment]
is this done??Can we connect prometheus to influxdb via remote write? kindly share the documents for the same.

**Comment by helenosheaa** [comment]
Hi @prab2014, you can test out this functionality at the moment from one of our nightly builds [here](https://github.com/influxdata/telegraf#nightly-builds).

It should be released into Telegraf 1.19.0 which is coming soon.

You'll use the `[[inputs.http_listener_v2]] `and then set the `data_format = "prometheusremotewrite"`. Check out the parser [here](https://github.com/influxdata/telegraf/tree/master/plugins/parsers/prometheusremotewrite).

There will hopefully be a new blog post on the new parser soon also.

If you have any questions in the meantime just ping me here!

**Comment by prab2014** [comment]
THANKS FOR THE reply @helenosheaa . i do have few questions.
1) is this approach suited for the production environment(nightly builds)?
2) what changes we need to do at prometheus side to enable the remote write to influxdb2.0. Right now am using prometheus and influxdb 1.8.x .Both are connecting well as per the steps mentioned in the below url. Made changes at prometheus side by adding remote_write section in the yml file.

https://docs.influxdata.com/influxdb/v1.8/supported_protocols/prometheus/

Now, i want to migrate to influxdb 2.0 because of new ui, query language and its rich feature. What changes has to be done at the prometheus side to connect to influxdb2.0 via telegraf. Did not find any concrete document for the same. 

3) Telegraf - what would be the input for the remote write?



4) Telegraf - what would be the output plugin for remote write.

Here my understanding for output would be :   [[outputs.influxdb_v2]] .
if not these then http_url - and points to influxdb?

It would be great if can share sample prometheus config and telegraf config for the remote write feature for influxdb2.0.

Regards,
Prabhat Ranjan.

**Comment by helenosheaa** [comment]
Hi Prabhat,

1. Testing it out on staging might be better and once it's released into the next Telegraf version then it would be ready for a production environment (in my opinion). 

2. Whatever is in your prometheus yml file for remote_write would need to be the same as what you put into the `[[inputs.http_listener_v2]]` for service_address and path.

3. The input would be [[inputs.http_listener_v2]], the input would be your remote_write url.

4. The output would be [[[outputs.influxdb_v2]].

It's worth mentioning that Telegraf has a different schema for Prometheus metrics than InfluxDB 1.x. If you would like to keep it consistent with what you had previously you would also add starlark to the config which is demonstrated in the config below.

What a metric would look like without starlark:
`prometheus_remote_write,instance=localhost:9090,job=prometheus scrape_samples_scraped=390 1622840468859000000
`

What a metric would look like with starlark:
`scrape_samples_scraped,instance=localhost:9090,job=prometheus value=390 1622843903859000000`

Basic sample prometheus config, add any jobs you want and update the remote_write url.

```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  # - job_name: node
  #   static_configs:
  #   - targets: ['localhost:9100']

remote_write:
  - url: "http://localhost:1234/receive"
```

Telegraf config: change the service address and path to your remote write url. And then update the influxdb info. You can also take away the starlark script / change it based on your needs.

```
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ## urls exp: http://127.0.0.1:9999
  urls = ["https://your-cloud2-url.com"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "your-org@your-org.com"

  ## Destination bucket to write into.
  bucket = "your-bucket-name"

[[processors.starlark]]
  ## The Starlark source can be set as a string in this configuration file, or
  ## by referencing a file containing the script.  Only one source or script
  ## should be set at once.

  ## Source of the Starlark script.
  source = '''
def apply(metric):
   if metric.name == "prometheus_remote_write":
        for k, v in metric.fields.items():
            metric.name = k
            metric.fields["value"] = v
            metric.fields.pop(k)
   return metric
'''

[[inputs.http_listener_v2]]
  ## Address and port to host HTTP listener on
  service_address = ":1234"

  ## Path to listen to.
  path = "/receive"

  ## Data format to consume.
  data_format = "prometheusremotewrite"
```

Hopefully that helps you get started to try it out. Any more questions just let me know.
