### ISSUE TITLE
[MQTT Consumer] Unable to remove topic tag without causing issues with processors

### ISSUE THREAD

**Issue by abhi1693** [influxdata/telegraf#9180]
### Relevant telegraf.conf:

```toml
[agent]
  collection_jitter = "3s"
  debug = true
  flush_interval = "5s"
  flush_jitter = "5s"
  hostname = "telegraf.xxx.com"
  interval = "10s"
  logfile = ""
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true
  precision = "ms"
  quiet = false
  round_interval = true
[[processors.regex]]
  order = 1
  [[processors.regex.tags]]
    key = "topic"
    pattern = "(.*)/.*/.*/.*"
    replacement = "${1}"
    result_key = "product"
[[processors.regex]]
  order = 2
  [[processors.regex.tags]]
    key = "topic"
    pattern = ".*/(.*)/.*/.*"
    replacement = "${1}"
    result_key = "profile"
[[processors.regex]]
  order = 3
  [[processors.regex.tags]]
    key = "topic"
    pattern = ".*/.*/(.*)/.*"
    replacement = "${1}"
    result_key = "mac"

	
[[processors.printer]]


[[outputs.influxdb_v2]]
  bucket = "things"
  organization = "test"
  token = "xxx"
  urls = [
    "https://tsdb.xxx.com"
  ]
  
[[inputs.mqtt_consumer]]
  client_id = "erp-telegraf2"
  connection_timeout = "30s"
  data_format = "json"
  insecure_skip_verify = false
  name_override = "streams"
  json_strict = true
  json_query = "data"
  tag_keys = [
    "s"
  ]
  json_time_key = "t"
  json_time_format = "unix"
  max_undelivered_messages = 1000
  password = "metricsmetricsmetricsmetrics"
  persistent_session = false
  qos = 0
  servers = [
    "ssl://mqtt.xxx.com:8883"
  ]
  tls_ca = "/etc/telegraf/certs/ca.crt"
  tls_cert = "/etc/telegraf/certs/tls.crt"
  tls_key = "/etc/telegraf/certs/tls.key"
  topics = [
    "+/+/+/streams"
  ]
  topic_tag = ""
  username = "erp-telegraf2"  

[[inputs.internal]]
  collect_memstats = false
```

### System info:

Version: Telegraf 1.18.0
OS: Alpine

### Steps to reproduce:

I'm not sure at the moment if this is a bug or something amiss in the configuration

### Expected behavior:

I want to process the topic to extract the relevant tags but not save the topic itself.

### Actual behavior:

As per the documentation, I have added `topic_tag=""`, but this makes the `processors` skip. I have tried to use `tagexclude`, which also makes the `processor` not do anything.

### Additional info:

```
streams,s=feed2,topic=controller/thing1/b814ea5cd45a/streams v=1 1619205880000000000
```
