### ISSUE TITLE
Storing openweathermap forecast with correct timestamp

### ISSUE THREAD

**Issue by frimdo** [influxdata/telegraf#9239]
### Relevant telegraf.conf:

```toml
[[inputs.openweathermap]]
  app_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  city_id = ["5391959"]
  fetch = ["forecast"]
  interval = "10m"
```

### Expected behavior:
Forecast values should be stored with timestamp that corresponds to their predicted time.

### Actual behavior:
Forecast values are stored with timestamp corresponding to the time when they were collected.

### Additional info:
I think, that the problem could be solved by a simple patch. Although I am not a go programmer, I think that changing line **296** of `telegraf/plugins/inputs/openweathermap/openweathermap.go` to 
```go 
		acc.AddFields("weather", fields, tags, tm.Add(time.Hour * ((i+1)*3)) )
```
should solve the issue.

**Comment by sjwang90** [comment]
the openweathermap plugin is pretty low on the internal Influx's team's priority. If anyone from the community wants to pick this please open a PR and we'll review!

**Comment by powersj** [comment]
Hi,

I put up #12167, however now that I have my openweather API key active I was able to test it live. I ran with the default behavior at 8:05am local time and got the following values for the first 5 results of the forecast:

```toml
[[inputs.openweathermap]]
  app_id = "mykey"
  city_id = ["5586437"]
  fetch = ["forecast"]
```

```
1667844000000000000	11am local
1667854800000000000	2pm local
1667865600000000000	5pm local
1667876400000000000	8pm local
1667887200000000000     11pm local
```

This would indicate that timestamps are already 3 hours in the future. The assumption that the timestamps are stored with the time they were forecasted at, not the prediction time, does not seem to apply. 

Could someone confirm this or show me how to reproduce an example that shows something different?
