### ISSUE TITLE
Starlark gives error key not in fields

### ISSUE THREAD

**Issue by xxwassyxx** [influxdata/telegraf#9252]
### Relevant telegraf.conf:

```toml
# Uptime
[[inputs.snmp.field]]
  name = "uptime"
  oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"

# Interfaces
[[inputs.snmp.table]]
  name = "interface"
  inherit_tags = [ "hostname" ]
  oid = "IF-MIB::ifTable"

  # Down interfaces and every "unrouted" l2 interface that is created with every L3 SVI or subif - not wanted or needed
  [inputs.snmp.tagdrop]
    interfaceName = ["VLAN-*"]
    ifOperStatus = ["2"]

  [[inputs.snmp.table.field]]
    name = "interfaceName"
    oid = "IF-MIB::ifName"
    is_tag = true

  [[inputs.snmp.table.field]]
    name = "interfaceAlias"
    oid = "IF-MIB::ifAlias"
    is_tag = true

  # Append the high-capacity (64-bit) counters for interface transfer instead of collecting everything twice
  [[inputs.snmp.table.field]]
    name = "ifHCInOctets"
    oid = "IF-MIB::ifHCInOctets"
    is_tag = false

  [[inputs.snmp.table.field]]
    name = "ifHCOutOctets"
    oid = "IF-MIB::ifHCOutOctets"
    is_tag = false

# CPU
[[inputs.snmp.field]]
  name = "cpu"
  oid = ".1.3.6.1.2.1.25.3.3.1.2"

# Memory
[[inputs.snmp.field]]
  name = "memory_total"
  oid = ".1.3.6.1.4.1.2021.4.5.0"

[[inputs.snmp.field]]
  name = "memory_free"
  oid = ".1.3.6.1.4.1.2021.4.11.0"

[[processors.starlark]]
## so this is taking cpu idle. And doing math, minus 100 to get usage and sending that to influxdb
  source = '''
def apply(metric):
    free = metric.fields['memory_free']
    total = metric.fields['memory_total']
    metric.fields['memory_used'] = total - free
    return metric
'''


```

### System info:

OS: CentOS Linux release 7.9.2009 (Core)
telegraf: telegraf-1.15.2-1.x86_64

1. create telegraf config
2. run telegraf with options of --debug --test

### Expected behavior:

no errors

### Actual behavior:

2021-05-10T19:35:36Z E! [processors.starlark]   processor.starlark:2:22: in apply
2021-05-10T19:35:36Z E! [processors.starlark] Error: key "memory_free" not in Fields
2021-05-10T19:35:36Z E! [processors.starlark] Error in plugin: key "memory_free" not in Fields

### Additional info:

Even tho i get this error I do however get the desired result. 
```
device memory_free=7571556i,memory_total=8316224i,memory_used=744668i,uptime=1566405i 1620675337000000000
```
It feels like instead of matching to the field I specified, its trying to apply this field key to every field and therefore produces alot of errors until the match. I followed the instructions and have researched this as best I could. As far as I can tell this should only match against the fields I mention not all. Unless im just missing something.

https://www.influxdata.com/blog/how-use-starlark-telegraf/
https://github.com/influxdata/telegraf/blob/master/plugins/processors/starlark/testdata/ratio.star
