### ISSUE TITLE
inputs.tail  data loss

### ISSUE THREAD

**Issue by shengzhou1216** [influxdata/telegraf#9262]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  hostname = "test0"
  omit_hostname = false
[[inputs.tail]]
  files = ["/chialogs/*.out"]
  data_format="value"
  data_type="integer"
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "influxdb"
  bucket = "chia"
  timeout = "5s"
```

#### system info
```
Linux sheng-MS-7C71 5.8.0-52-generic #59~20.04.1-Ubuntu SMP Fri Apr 30 16:10:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
#### telegraf
```
Telegraf 1.18.2 (git: HEAD e58cb456) (Docker)
```
#### influxdb
```
Influx CLI 2.0.6 (git: 4db98b4c9a) build_date: 2021-04-29T16:48:12Z (Docker)
```

#### docker-compose.yaml
```yaml
version: "3"
services:
    influxdb:
        image: influxdb:2.0.6
        container_name: influxdb
        restart: always
        environment: 
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
            - DOCKER_INFLUXDB_INIT_ORG=influxdb
            - DOCKER_INFLUXDB_INIT_BUCKET=chia
            - DOCKER_INFLUXDB_INIT_RETENTION=4w
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=sometoken
        ports:
            - 8086:8086
        networks:
            - monitoring
        volumes:
            - ./influxdb:/var/lib/influxdb2
            - ./config.yml:/etc/influxdb2/config.yml

    telegraf:
        image: telegraf
        container_name: telegraf
        environment: 
            - INFLUX_TOKEN=sometoken
        restart: always
        networks:
            - monitoring
        depends_on: 
            - influxdb
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
            - ./chialogs:/chialogs
            - ./groks:/groks

    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            - monitoring

networks:
    monitoring:
```
#### config.yml(influxdb)
```yaml
assets-path: ""
bolt-path: /var/lib/influxdb2/influxd.bolt
e2e-testing: false
engine-path: /var/lib/influxdb2/engine
feature-flags: {}
http-bind-address: :8086
http-idle-timeout: 3m0s
http-read-header-timeout: 10s
http-read-timeout: 0s
http-write-timeout: 0s
influxql-max-select-buckets: 0
influxql-max-select-point: 0
influxql-max-select-series: 0
key-name: ""
log-level: info
metrics-disabled: false
nats-max-payload-bytes: 1048576
nats-port: 4222
no-tasks: false
pprof-disabled: false
query-concurrency: 1024
query-initial-memory-bytes: 0
query-max-memory-bytes: 0
query-memory-bytes: 9223372036854775807
query-queue-size: 1024
reporting-disabled: false
secret-store: bolt
session-length: 60
session-renew-disabled: false
storage-cache-max-memory-size: 1073741824
storage-cache-snapshot-memory-size: 26214400
storage-cache-snapshot-write-cold-duration: 10m0s
storage-compact-full-write-cold-duration: 4h0m0s
storage-compact-throughput-burst: 50331648
storage-max-concurrent-compactions: 0
storage-max-index-log-file-size: 1048576
storage-retention-check-interval: 30m0s
storage-series-file-max-concurrent-snapshot-compactions: 0
storage-series-id-set-cache-size: 0
storage-shard-precreator-advance-period: 30m0s
storage-shard-precreator-check-interval: 10m0s
storage-tsm-use-madv-willneed: false
storage-validate-keys: false
storage-wal-fsync-delay: 0s
store: bolt
testing-always-allow-setup: false
tls-cert: ""
tls-key: ""
tls-min-version: "1.2"
tls-strict-ciphers: false
tracing-type: ""
vault-addr: ""
vault-cacert: ""
vault-capath: ""
vault-client-cert: ""
vault-client-key: ""
vault-client-timeout: 0s
vault-max-retries: 0
vault-skip-verify: false
vault-tls-server-name: ""
vault-token: ""
```

### Steps to reproduce:

1. Keep writing data (`echo 2222 >> 1.out`) to file (e.g. /chialogs/1.out)
2. Watch data in Influxdb data explorer (http://localhost:8086)

### Expected behavior:
All data should be stored in the influxdb.

### Actual behavior:
Only some of the data is stored in the influxdb.
