### ISSUE TITLE
inputs.snmp_trap panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BenCastricum** [influxdata/telegraf#9287]
### Relevant telegraf.conf:

```toml
[[inputs.snmp_trap]]
#   ## Transport, local address, and port to listen on.  Transport must
#   ## be "udp://".  Omit local address to listen on all interfaces.
#   ##   example: "udp://127.0.0.1:1234"
#   ##
#   ## Special permissions may be required to listen on a port less than
#   ## 1024.  See README.md for details
#   ##
#   # service_address = "udp://:162"
#   ## Timeout running snmptranslate command
#   # timeout = "5s"
service_address = "udp://:6162"
```

### System info:

Telegraf 1.18.2 (git: HEAD a6143722)

Running inside docker container telegraf:latest ("Created": "2021-05-13T01:53:56.89930314Z")

### Docker

version : "3"

services:
  telegraf:
    image: telegraf
    hostname: TelegrafHost
    user: 201:201
    command: --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
    ports:
      - 6514:6514/udp
      - 162:6162/udp
    volumes:
      - /home/docker/etc/telegraf:/etc/telegraf:ro
      - /proc:/host/proc:ro
      - /home/docker/.snmp/mibs:/usr/share/snmp/mibs:ro
    networks:
       influxdatanet:

### Steps to reproduce:

1. configure telegraf to use inputs.snmp_trap plugin
2. run telegraf with the --test option with same config as the already running instance

### Expected behavior:

An error message that telegraf cannot bind to the snmp_trap port because it's already in use.

### Actual behavior:

Telegraf panics

### Additional info:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1e9505d]

goroutine 27 [running]:
github.com/soniah/gosnmp.(*TrapListener).Close(0xc00049ae60)
        /go/pkg/mod/github.com/soniah/gosnmp@v1.25.0/trap.go:131 +0x3d
github.com/influxdata/telegraf/plugins/inputs/snmp_trap.(*SnmpTrap).Stop(0xc00037c0e0)
        /go/src/github.com/influxdata/telegraf/plugins/inputs/snmp_trap/snmp_trap.go:251 +0x36
github.com/influxdata/telegraf/agent.stopServiceInputs(0xc000c65680, 0x8, 0x8)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:445 +0x82
github.com/influxdata/telegraf/agent.(*Agent).testRunInputs(0xc0001140f0, 0x42c17f0, 0xc000311980, 0x0, 0xc00002b0c0, 0x0, 0x0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:434 +0x1b7
github.com/influxdata/telegraf/agent.(*Agent).test.func4(0xc000af91f0, 0xc0001140f0, 0x42c17f0, 0xc000311980, 0x0, 0xc00002b0c0)
        /go/src/github.com/influxdata/telegraf/agent/agent.go:983 +0x8b
created by github.com/influxdata/telegraf/agent.(*Agent).test
        /go/src/github.com/influxdata/telegraf/agent/agent.go:981 +0x352
