### ISSUE TITLE
Sflow invalid version Error even though sflow is valid

### ISSUE THREAD

**Issue by chaichairiko** [influxdata/telegraf#9309]
### Relevant telegraf.conf:
```toml
[agent]
  ## Override default hostname, if empty use os.Hostname()
  hostname = "${TELEGRAF_HOSTNAME}"
# Output Configuration for telegraf agent
[[outputs.influxdb_v2]]
  ## Point to your influxdb container
 urls = ["${INFLUXDB_URL}"]
 ## Token for authentication; created with the influxdb_cli service.
 token = "o9EE2FYJPTCp3NJBjrveUgC18h0xJ8btNRA8N-G6uA8KvKM6aD5kizyyKWn6PpfI4JgQiSB-HY0tqbNAa2Gwkg=="
 ## Organization is the name of the organization you wish to write to; created with the influxdb_cli service.
 organization = "insidepacket"
 ## Destination bucket to write into; created with the influxdb_cli service.
 bucket = "monitor"

 # Read metrics about memory usage
[[inputs.mem]]
  # no configuration
[[inputs.cpu]]
  ## Whether to report per-cpu stats or not
  percpu = true
  ## Whether to report total system cpu stats or not
  totalcpu = true
  ## If true, collect raw CPU time metrics.
  collect_cpu_time = false
  ## If true, compute and report the sum of all non-idle CPU states.
  report_active = true
[[inputs.disk]]
  ## By default stats will be gathered for all mount points.
  ## Set mount_points will restrict the stats to only the specified mount points.
  # mount_points = ["/"]

  ## Ignore mount points by filesystem type.
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.docker_log]]
  ## Docker Endpoint
  ##   To use TCP, set endpoint = "tcp://[ip]:[port]"
  ##   To use environment variables (ie, docker-machine), set endpoint = "ENV"
  # endpoint = "unix:///var/run/docker.sock"

  ## When true, container logs are read from the beginning; otherwise
  ## reading begins at the end of the log.
  # from_beginning = false

  ## Timeout for Docker API calls.
  # timeout = "5s"

  ## Containers to include and exclude. Globs accepted.
  ## Note that an empty array for both will include all containers
  # container_name_include = []
  # container_name_exclude = []

  ## Container states to include and exclude. Globs accepted.
  ## When empty only containers in the "running" state will be captured.
  # container_state_include = []
  # container_state_exclude = []

  ## docker labels to include and exclude as tags.  Globs accepted.
  ## Note that an empty array for both will include all labels as tags
  # docker_label_include = []
  # docker_label_exclude = []

  ## Set the source tag for the metrics to the container ID hostname, eg first 12 chars
  source_tag = false

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"
  ## Use TLS but skip chain & host verification
  # insecure_skip_verify = false

[[inputs.temp]]
  # no configuration
[[inputs.sflow]]
  service_address = "udp://:6343"
[[outputs.health]]
  ## Address and port to listen on.
  ##   ex: service_address = "http://localhost:8080"
  ##       service_address = "unix:///var/run/telegraf-health.sock"
  service_address = "${TELEGRAF_URL}"

  ## The maximum duration for reading the entire request.
  # read_timeout = "5s"
  ## The maximum duration for writing the entire response.
  # write_timeout = "5s"

  ## Username and password to accept for HTTP basic authentication.
  # basic_username = "user1"
  # basic_password = "secret"

  ## Allowed CA certificates for client certificates.
  # tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]

  ## TLS server certificate and private key.
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"

  ## One or more check sub-tables should be defined, it is also recommended to
  ## use metric filtering to limit the metrics that flow into this output.
  ##
  ## When using the default buffer sizes, this example will fail when the
  ## metric buffer is half full.
  ##
  ## namepass = ["internal_write"]
  tagpass = { output = ["influxdb"] }
  ##
   [[outputs.health.compares]]
     field = "buffer_size"
     lt = 5000.0
  ##
   [[outputs.health.contains]]
     field = "buffer_size"
```

### System info:

Telegraf version 1.18.2

### Steps to reproduce:

1. I ran an sflow generator - solarwind netflow generator
2. Saw empty data in Chronoraf

### Actual behavior:

getting an error for each flow:
2021-05-27T16:03:40Z E! [inputs.sflow] Error in plugin: unable to parse incoming packet: Version 0 not supported, only version 5

### Additional info:

Data was seen correctly on slfow-RT and sflow tool.

sflow-tool log (sample):
startDatagram =================================
datagramSourceIP 192.168.10.218
datagramSize 868
unixSecondsUTC 1622128849
localtime 2021-05-27T15:20:49+0000
datagramVersion 5
agentSubId 0
agent 127.0.0.1
packetSequenceNo 635549
sysUpTime 1622128847
samplesInPacket 4
startSample ----------------------
sampleType_tag 0:3
sampleType FLOWSAMPLE
sampleSequenceNo 1
sourceId 2:1
meanSkipCount 1000
samplePool 198000
dropEvents 15
inputPort 7
outputPort 8
flowBlock_tag 0:3
flowSampleType IPV4
sampledPacketSize 3000
IPSize 3000
srcIP 192.168.1.32
dstIP 192.168.1.139
IPProtocol 6
IPTOS 0
TCPSrcPort 49650
TCPDstPort 443
TCPFlags 0
flowBlock_tag 0:3
flowSampleType IPV4
sampledPacketSize 3000
IPSize 3000
srcIP 192.168.1.32
dstIP 192.168.1.139
IPProtocol 6
IPTOS 0
TCPSrcPort 49650
TCPDstPort 443
TCPFlags 0
flowBlock_tag 0:3
flowSampleType IPV4
sampledPacketSize 3000
IPSize 3000
srcIP 192.168.1.32
dstIP 192.168.1.139
IPProtocol 6
IPTOS 0
TCPSrcPort 49650
TCPDstPort 443
TCPFlags 0
flowBlock_tag 0:3
flowSampleType IPV4
sampledPacketSize 3000
IPSize 3000
srcIP 192.168.1.32
dstIP 192.168.1.139
IPProtocol 6
IPTOS 0
TCPSrcPort 49650
TCPDstPort 443
TCPFlags 0
endSample   ----------------------
startSample ----------------------
sampleType_tag 0:4
sampleType COUNTERSSAMPLE
sampleSequenceNo 2
sourceId 2:1
counterBlock_tag 0:1
ifIndex 1
networkType 1
ifSpeed 631
ifDirection 1
ifStatus 1
ifInOctets 0
ifInUcastPkts 6
ifInMulticastPkts 5
ifInBroadcastPkts 3
ifInDiscards 4
ifInErrors 7
ifInUnknownProtos 2
ifOutOctets 1
ifOutUcastPkts 9
ifOutMulticastPkts 3
ifOutBroadcastPkts 2
ifOutDiscards 6
ifOutErrors 9
ifPromiscuousMode 1
counterBlock_tag 0:1
ifIndex 2
networkType 1
ifSpeed 904
ifDirection 1
ifStatus 1
ifInOctets 5
ifInUcastPkts 3
ifInMulticastPkts 7
ifInBroadcastPkts 1
ifInDiscards 6
ifInErrors 5
ifInUnknownProtos 7
ifOutOctets 7
ifOutUcastPkts 0
ifOutMulticastPkts 0
ifOutBroadcastPkts 7
ifOutDiscards 0
ifOutErrors 3
ifPromiscuousMode 1
counterBlock_tag 0:1
ifIndex 3
networkType 1
ifSpeed 168
ifDirection 1
ifStatus 1
ifInOctets 5
ifInUcastPkts 6
ifInMulticastPkts 2
ifInBroadcastPkts 6
ifInDiscards 6
ifInErrors 1
ifInUnknownProtos 1
ifOutOctets 5
ifOutUcastPkts 7
ifOutMulticastPkts 8
ifOutBroadcastPkts 9
ifOutDiscards 0
ifOutErrors 9
ifPromiscuousMode 1
counterBlock_tag 0:1
ifIndex 4
networkType 1
ifSpeed 548
ifDirection 1
ifStatus 1
ifInOctets 0
ifInUcastPkts 3
ifInMulticastPkts 5
ifInBroadcastPkts 6
ifInDiscards 8
ifInErrors 0
ifInUnknownProtos 6
ifOutOctets 4
ifOutUcastPkts 0
ifOutMulticastPkts 6
ifOutBroadcastPkts 3
ifOutDiscards 9
ifOutErrors 0
ifPromiscuousMode 1
endSample   ----------------------
startSample ----------------------
sampleType_tag 0:3
sampleType FLOWSAMPLE
sampleSequenceNo 3
sourceId 2:1
meanSkipCount 1000
samplePool 198000
dropEvents 10
inputPort 2
outputPort 6
flowBlock_tag 0:3
flowSampleType IPV4
sampledPacketSize 3000
IPSize 3000
srcIP 192.168.1.176
dstIP 192.168.1.189
IPProtocol 6
IPTOS 0
TCPSrcPort 49650
TCPDstPort 443
TCPFlags 0
endSample   ----------------------
startSample ----------------------
sampleType_tag 0:4
sampleType COUNTERSSAMPLE
sampleSequenceNo 4
sourceId 2:1
counterBlock_tag 0:1
ifIndex 1
networkType 1
ifSpeed 475
ifDirection 1
ifStatus 1
ifInOctets 2
ifInUcastPkts 6
ifInMulticastPkts 2
ifInBroadcastPkts 6
ifInDiscards 0
ifInErrors 0
ifInUnknownProtos 4
ifOutOctets 0
ifOutUcastPkts 1
ifOutMulticastPkts 6
ifOutBroadcastPkts 5
ifOutDiscards 6
ifOutErrors 8
ifPromiscuousMode 1
endSample   ----------------------
endDatagram   =================================
