### ISSUE TITLE
inputs.test plugin

### ISSUE THREAD

**Issue by ssoroka** [influxdata/telegraf#9316]
## Feature Request

support an input plugin of the following type:
```toml
[[inputs.test]]
  metrics = [
    'weather,state=ny temperature=81.3'
  ]
```

### Proposal:

support the above

### Current behavior:

possible through creating a file and using inputs.file or inputs.tail

### Desired behavior:

above

### Use case: 

Very useful for debugging and creating demos of processor/aggregator behavior. Allows self-contained config files that demo a specific configuration behavior

In the future this could potentially be paired with a special output that expects that a specific metric shows up; could be an interesting way to write documentation-focused tests.
