### ISSUE TITLE
inputs.tail watch_method poll bug

### ISSUE THREAD

**Issue by suconghou** [influxdata/telegraf#9320]
```toml
[agent]
    interval = 3
    flush_interval = 5
    metric_batch_size = 200
    metric_buffer_limit = 800
    collection_jitter = "5s"
    flush_jitter = "5s"
    round_interval = true
[[inputs.tail]]
    from_beginning = false
    watch_method = "poll"
    max_undelivered_lines = 3000
    files = ["/mnt/share/log/nginx/access.log"]
    name_override = "nginx_access_log"
    grok_patterns = ["^%{CUSTOM_LOG}$"]
    data_format = "grok"
    grok_custom_patterns = '''
        CUSTOM_LOG %{COMBINED_LOG_FORMAT} %{QS:xforwardedfor} %{IPORHOST:httphost} %{NUMBER:request_length:int} %{NUMBER:bytes_sent:int} (?:%{URIHOST:upstream_addr}|-) (?:%{NUMBER:upstream_status:int}|-) %{NUMBER:request_time:float} (?:%{NUMBER:upstream_response_time:float}|-) (?:%{NUMBER:upstream_connect_time:float}|-) (?:%{NUMBER:upstream_header_time:float}|-)
        '''


[[outputs.influxdb_v2]] 
    urls = ["http://10.105.37.x:1086"] 
    organization = "xx" 
    bucket = "xx" 
    token = "xx" 
 

```

Telegraf 1.18.3 (git: HEAD 6a94f65a)

 /usr/local/bin/telegraf --config /etc/telegraf.conf --debug

conf works well on local disk with `watch_method = inotify`

but got error sometimes on nfs with `watch_method=poll`

a lot of nginx access log `Grok no match `

```
 Grok no match found for: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00
```
