### ISSUE TITLE
shim plugin does not run multiple inputs in the plugin’s config - it only runs the first

### ISSUE THREAD

**Issue by ashishkaransingh** [influxdata/telegraf#9325]
### Relevant telegraf.conf:

```toml
custom_plugin.conf (https://github.com/influxdata/telegraf/tree/master/plugins/common/shim)
[[inputs.custom_mssql_1]]
  servers = ["Server = 10.111.00.000;Port=1433;Database=Database_1;app name=telegraf;log=1;"]
  queries = ["sql_query_from_plugin_1"]

[[inputs.custom_mssql_1]]
  servers = ["Server = 10.111.00.000;Port=1433;Database=Database_2;app name=telegraf;log=1;"]
  queries = ["sql_query_from_plugin_2"]

[[inputs.custom_mssql_1]]
  servers = ["Server = 10.111.00.000;Port=1433;Database=Database_3;app name=telegraf;log=1;"]
  queries = ["sql_query_from_plugin_3"]

Telegraf.exe.conf

[[inputs.execd]]
  command = ["C:\\Users\\*****\\go\\src\\sql-server\\custom_mssql_.exe", "--config", "C:\\Users\\*****\\go\\src\\sql-server\\custom_mssql.conf"]
  signal = "STDIN"
```

### System info:

```
Telegraf  v1.18.2
go-mssqldb v0.10.0
go 1.15
```

### Steps to reproduce:

1. running locally with telegraf.exe --config telegraf.conf --test
2. multiple inputs in the plugin’s config (custom_plugin.conf) but it only runs the first i.e ```["sql_query_from_plugin_1"]```

### Expected behavior:

All the inputs containing sql queries  under custom_plugin.conf should run
```
["sql_query_from_plugin_1"], ["sql_query_from_plugin_2"], ["sql_query_from_plugin_3"]
```
### Actual behavior:

Only the following runs, rest two are skipped
```[[inputs.custom_mssql_1]]
  servers = ["Server = 10.111.00.000;Port=1433;Database=Database_1;app name=telegraf;log=1;"]
  queries = ["sql_query_from_plugin_1"]
```
### Additional info:
- Each input is for a separate sql database
- It is very important for us because there are multiple DBs on a server for different products and we should be able to run these queries for different databases.
- It works fine if I compile the plugin in Telegraf itself, but not as a separate app

- Is this because main agent has for loop, and that the shim doesn’t 
Example:
https://github.com/influxdata/telegraf/blob/2e7b232073650883b016b7bf2ab585a75862f6b2/agent/agent.go#L188
                for _, input := range a.Config.Inputs {
