### ISSUE TITLE
Issues with SQLSErver Plugin

### ISSUE THREAD

**Issue by ThePeltonian** [influxdata/telegraf#9347]
### Relevant telegraf.conf:

```toml
<[[inputs.sqlserver]]
  servers = [
   
    "Server=localhost;Port=1433;Integrated Security=SSPI;app name=telegraf;log=1",
  ]
 
  ## Queries enabled by default for database_type = "SQLServer" are - 
  ## SQLServerPerformanceCounters, SQLServerWaitStatsCategorized, SQLServerDatabaseIO, SQLServerProperties, SQLServerMemoryClerks, 
  ## SQLServerSchedulers, SQLServerRequests, SQLServerVolumeSpace, SQLServerCpu

  database_type = "SQLServer"

  include_query = []

  ## SQLServerAvailabilityReplicaStates and SQLServerDatabaseReplicaStates are optional queries and hence excluded here as default
  exclude_query = ["SQLServerAvailabilityReplicaStates", "SQLServerDatabaseReplicaStates"]
   ## Optional parameter, setting this to two will use a new version
  ## of the collection queries that break compatibility with the original
  ## dashboards. 
  #query_version = 2
  ## If you are using AzureDB, setting this to True will gather resource utilization metrics
  # azuredb = False
  ## If you would like to exclude some of the metrics queries, list them here
  # exclude_query = [ 'PerformanceCounters','WaitStatsCatagorized' ]
#[[inputs.win_perf_counters.object]]
  # Processor usage, alternative to native, reports on a per core.
 # ObjectName = "Processor"
 # Instances = ["*"]
 # Counters = ["% Idle Time", "% Interrupt Time", "% Privileged Time", "% User Time", "% Processor Time"]
 # Measurement = "sql_cpu"
  #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).
#[[inputs.win_perf_counters.object]]
#  ObjectName = "LogicalDisk"
#  Instances = ["*"]
#  Counters = ["% Free Space","Free Megabytes","Avg. Disk Read Queue Length","Avg. Disk Write Queue Length","Avg. Disk sec/Read","Avg. Disk sec/Write"]
#  Measurement = "sql_disk"
#[[inputs.win_perf_counters.object]]
#   ObjectName = "SQLServer:Query Store"
#   Instances = ["*"]
#   Counters = ["Query Store CPU Usage", "Query Store logical reads", "Query Store logical writes", "Query Store physical reads"]
#   Measurement = "sql_qs" 
```

### System info:

Telegraf Version = 1.18.2 / 1.18.3
Operating System Win 2008 R2
Microsoft SQL Server 2008 R2 (SP3) - 10.50.6220.0 (X64) 
	Mar 19 2015 12:32:14 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor)

### Steps to reproduce:

1. Install telegraf service 
2. Execute telegraf service

### Expected behavior:

Telegraf pushes data to InfluxDB

### Actual behavior:

Partial Data pushed with error of:

D:\Program Files\telegraf>telegraf.exe --config "D:\program files\telegraf\telegraf.conf" --once --debug
2021-06-09T13:24:20Z I! Starting Telegraf 1.18.3
2021-06-09T13:24:20Z D! [agent] Initializing plugins
2021-06-09T13:24:20Z D! [agent] Connecting outputs
2021-06-09T13:24:20Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2021-06-09T13:24:20Z D! [agent] Successfully connected to outputs.influxdb_v2
2021-06-09T13:24:20Z D! [agent] Starting service inputs
2021-06-09T13:24:20Z I! [inputs.sqlserver] Config: database_type: SQLServer , query_version:0 , azuredb: false
2021-06-09T13:24:20Z I! [inputs.sqlserver] Config: Effective Queries: []string{"SQLServerSchedulers", "SQLServerRequests", SQLServerVolumeSpace", "SQLServerCpu", "SQLServerWaitStatsCategorized", "SQLServerDatabaseIO", "SQLServerProperties"
, "SQLServerMemoryClerks", "SQLServerPerformanceCounters"}
2021-06-09T13:24:20Z I! gopsutil: unexpected processor queue length counter error, please file an issue on github: err
2021-06-09T13:24:20Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2021-06-09T13:24:20Z D! [agent] Stopping service inputs
2021-06-09T13:24:20Z D! [agent] Input channel closed
2021-06-09T13:24:20Z D! [agent] Processor channel closed
2021-06-09T13:24:20Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-06-09T13:24:20Z D! [outputs.influxdb_v2] Wrote batch of 349 metrics in 29.0016ms
2021-06-09T13:24:20Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2021-06-09T13:24:20Z I! [agent] Stopping running outputs
2021-06-09T13:24:20Z D! [agent] Stopped Successfully
2021-06-09T13:24:20Z E! [telegraf] Error running agent: input plugins recorded 1 errors

### Additional info:

The same config and telegraf version works fine on other servers that are Win2012+ and pull back all data.
I have tried using the query version 2 also within the config and this also does not supply all data to InfluxDB

D:\Program Files\telegraf>telegraf.exe --config "D:\program files\telegraf\telegraf.conf" --once --debug
2021-06-09T13:11:19Z I! Starting Telegraf 1.18.3
2021-06-09T13:11:19Z D! [agent] Initializing plugins
2021-06-09T13:11:19Z D! [agent] Connecting outputs
2021-06-09T13:11:19Z D! [agent] Attempting connection to [outputs.influxdb_v2]
2021-06-09T13:11:19Z D! [agent] Successfully connected to outputs.influxdb_v2
2021-06-09T13:11:19Z D! [agent] Starting service inputs
2021-06-09T13:11:19Z I! [inputs.sqlserver] Config: database_type:  , query_version:2 , azuredb: false
2021-06-09T13:11:19Z W! DEPRECATION NOTICE: query_version=2 is being deprecated in favor of database_type.
2021-06-09T13:11:19Z I! [inputs.sqlserver] Config: Effective Queries: []string{"Schedulers", "SqlRequests", "VolumeSpace", "PerformanceCounters", "WaitStatsCategorized", "DatabaseIO", "ServerProperties", "MemoryClerk", "Cpu"}
2021-06-09T13:11:19Z D! [inputs.win_eventlog] Subscription handle id:1
2021-06-09T13:11:19Z I! Incorrect syntax near ' '.
2021-06-09T13:11:19Z I! Incorrect syntax near ' '.
2021-06-09T13:11:19Z E! [inputs.sqlserver] Error in plugin: Script Cpu failed: mssql: Incorrect syntax near ' '.
2021-06-09T13:11:19Z I! gopsutil: unexpected processor queue length counter error, please file an issue on github: err
2021-06-09T13:11:19Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2021-06-09T13:11:19Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2021-06-09T13:11:19Z E! [inputs.win_perf_counters] Error in plugin: No data to return.
2021-06-09T13:11:20Z D! [agent] Stopping service inputs
2021-06-09T13:11:20Z D! [agent] Input channel closed
2021-06-09T13:11:20Z D! [agent] Processor channel closed
2021-06-09T13:11:20Z I! [agent] Hang on, flushing any cached metrics before shutdown
2021-06-09T13:11:20Z D! [outputs.influxdb_v2] Wrote batch of 367 metrics in 35.002ms
2021-06-09T13:11:20Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2021-06-09T13:11:20Z I! [agent] Stopping running outputs
2021-06-09T13:11:20Z D! [agent] Stopped Successfully
2021-06-09T13:11:20Z E! [telegraf] Error running agent: input plugins recorded 4 errors
