### ISSUE TITLE
SQL Server input no longer functions correctly with Windows Integrated authentication

### ISSUE THREAD

**Issue by cerilewis** [influxdata/telegraf#9362]
### Relevant telegraf.conf:

```toml
# Read metrics from Microsoft SQL Server
[[inputs.sqlserver]]
  ## Specify instances to monitor with a list of connection strings.
  ## All connection parameters are optional.
  ## By default, the host is localhost, listening on default port, TCP 1433.
  ##   for Windows, the user is the currently running AD user (SSO).
  ##   See https://github.com/denisenkom/go-mssqldb for detailed connection
  ##   parameters.

  servers = [
    "Server=localhost;app name=telegraf;log=1;"
  ]

  database_type = "SQLServer"
```

### System info:
telegraf 1.19.0-rc0 running on Windows OS

### Steps to reproduce:

1. Add SQL Server input configuration intended to use Windows Integrated authentication (i.e. no user id/password fields) and database_type of `SQLServer`
2. Run telegraf binary with above configuration

### Expected behavior:
Telegraf agent should connect to SQL Server instance using Windows Integrated authentication using the user identity of the running process.

### Actual behavior:
Telegraf incorrectly determines that it should connection using Azure Active Directory (AAD) authentication but `SQLServer` database type was specified and therefore throws error
`[inputs.sqlserver] Error in plugin: database connection failed : AAD auth is not supported for SQL VM i.e. DatabaseType=SQLServer`
