### ISSUE TITLE
MQTT json format

### ISSUE THREAD

**Issue by alexmc1510** [influxdata/telegraf#9376]
Hello, I am desperated trying to ingest data from MQTT into InfluxDB. I have followed all documents and I have looked for some forums without success. Would someone be so kind as to provide me any idea how to ingest data that I receive from MQTT in the following format?
```
{
  "timestamp": 1623786169180,
  "values": [
    {
      "id": "GET_S19_GATEHOST.VGF120B.VGF120_D435.Variables_HMI.Host_IdPart",
      "v": 630,
      "q": true,
      "t": 1623785875134
    },
    {
      "id": "GET_S19_GATEHOST.VGF120B.VGF120_D435.Variables_HMI.Host_MSN",
      "v": "MSN0573_CG10563",
      "q": true,
      "t": 1623784689919
    }
  ]
}
```
I would appreciate so much your help.

Thanks in advance.

Regards

**Comment by srebhan** [comment]
Hey @alexmc1510, 

with 
```toml
  data_format = "json"
  json_query = "values"

  json_string_fields= ["v", "q"]
  tag_keys = ["id"]
  json_time_key = "t"
  json_time_format = "unix_ms"
```

I do get 
```
file,host=Hugin,id=GET_S19_GATEHOST.VGF120B.VGF120_D435.Variables_HMI.Host_IdPart v=630,q=true 1623785875000000000
file,host=Hugin,id=GET_S19_GATEHOST.VGF120B.VGF120_D435.Variables_HMI.Host_MSN v="MSN0573_CG10563",q=true 1623784690000000000
```

You have to postprocess `q` and maybe also `v` but that's nothing too hard using the [starlark processor](https://github.com/influxdata/telegraf/tree/master/plugins/processors/starlark)...
