### ISSUE TITLE
AWS plugin - Prometheus output does not return billing metrics

### ISSUE THREAD

**Issue by flaker** [influxdata/telegraf#9391]
### Relevant telegraf.conf:

```toml
[agent]
debug = true
quiet = false
logfile = ""
hostname = ""
omit_hostname = true

[[outputs.prometheus_client]]
metric_version = 2
collectors_exclude = ["gocollector", "process"]

# AWS Billing metrics
[[inputs.cloudwatch]]
region = "us-east-1"
period = "360m"
delay = "5m"
interval = "1m"
namespace = "AWS/Billing"
ratelimit = 50

  ## Pull total billing costs across all services (don't specify ServiceName as a dimension)
  [[inputs.cloudwatch.metrics]]
    names = ["EstimatedCharges"]
```

### System info:

./telegraf --version
Telegraf unknown (git: master 28fbdd8f)

(also tested on image telegraf:1.16.1)

### Steps to reproduce:

1. Execute telegraf in an environment that has working credentials to connect to AWS and retrieve metrics.
2. ...

### Expected behavior:

Opening a browser and pointing to http://localhost:9273/metrics should return a number of metrics related to AWS billing. The same metrics and numbers retrieved ruing `--test` should be available.

### Actual behavior:

Billing metrics are never shown.

### Additional info:

 - Running ` ./telegraf --config ~/dev/test_telegraf/telegraf.conf --test` returns values for the requested metrics.
 - The influxdb output plugin does emit the metrics. I can successfully query them via Grafana.
 - I have tried adding some other input, like `[[inputs.system]]` and that shows up in the Prometheus output as some gauges.
 - Billing metrics are pushed every 6 hours by Cloudwatch, hence the 360 minutes.
