### ISSUE TITLE
json_v2: tags required to be listed as included_keys

### ISSUE THREAD

**Issue by igomura** [influxdata/telegraf#9394]
### Relevant telegraf.conf:

```toml
[[inputs.file]]
  files = ["/tmp/ctrl.json"]
  data_format = "json_v2"
  [[inputs.file.json_v2]]
    measurement_name = "storcli_controller"
    [[inputs.file.json_v2.tag]]
    path = "Controllers.#.Command Status.Controller"
    rename = "Controller"
    [[inputs.file.json_v2.object]]
    path = "Controllers.#.Response Data"
    disable_prepend_keys = true
    included_keys = [
      "Drive_Groups",
      "Virtual_Drives"
    ]
    tags = [
      "Product_Name",
      "Serial_Number"
    ]
```

### System info:

Telegraf: telegraf-1.19.0-0.1.x86_64
OS: Linux localhost 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce:

1. Create json_v2 input
2. add "included_keys" option
3. add "tags" option

### Expected behavior:

metrics, if found, should be tagged by tags from the list

### Actual behavior:

Metrics are not tagged

### Additional info:

In order to work all tags should be added to the "included_keys" list as below
```toml
    included_keys = [
      "Drive_Groups",
      "Virtual_Drives",
      "Product_Name",
      "Serial_Number"
    ]
    tags = [
      "Product_Name",
      "Serial_Number"
    ]
```
This is kind of obvious action and could be done by default.
