### ISSUE TITLE
outputs.cloudwatch gets stuck when receiving data older than 2 weeks

### ISSUE THREAD

**Issue by japsu** [influxdata/telegraf#9402]
Consider a scenario where there are clients that stay offline for a long time and then send their metrics when they come back online.

If such metrics are more than 2 weeks old, `outputs.cloudwatch` will get stuck due to AWS Cloudwatch API error. Even though there are less than 2 weeks old messages in the queue, they will not get through.

In our case, input is Kinesis, so the old messages will be dropped after 24h, after which normal operation will resume, but we'd rather have the >2w messages dropped and <2w messages through as soon as possible.

### Relevant telegraf.conf:

```toml
[[inputs.kinesis_consumer]]
  region = "..."
  streamname = "..."
  data_format = "json"
[[outputs.cloudwatch]]
  region = "..."
  namespace = "..."
```

### System info:

`telegraf:1.17-alpine`

### Steps to reproduce:

1. Have an input consisting of messages both >2w and <2w old
2. Output to CloudWatch

### Expected behavior:

Metrics older than 2 weeks dropped, metrics less than 2 weeks old processed normally

### Actual behavior:

Processing gets stuck until metrics older than 2 weeks expire from input queue

### Additional info:

Error in logs:
```
2021-06-21T09:45:52Z E! CloudWatch: Unable to write to CloudWatch : InvalidParameterValue: The parameter MetricData.member.19.Timestamp must specify a time within the past two weeks.
```
