### ISSUE TITLE
prometheus input plugin: mistaken delete

### ISSUE THREAD

**Issue by wujianhanshu** [influxdata/telegraf#9408]
### Relevant telegraf.conf:

```toml

[[inputs.prometheus]]
      metric_version = 1
      pod_scrape_scope = "node"
      monitor_kubernetes_pods = true
      insecure_skip_verify = true
      pod_scrape_interval = 1
      bearer_token = "/run/secrets/kubernetes.io/serviceaccount/token"

```

### Mistaken info:

Telegraf:  v1.8.3-v1.19.0

https://github.com/influxdata/telegraf/pull/8937/files#diff-dcebbfefbef8e986af6172ea7f96ab8b6d0b62aac383a7fa3f7bc1df5d06f2e0

func (p *Prometheus) cAdvisor(ctx context.Context) error {
        ...
        client.SetHeaders(req.Header) // mistaken delete
        ...
}
