### ISSUE TITLE
Telegraf 1.9.0 doesn't support Health Output Plugin anymore

### ISSUE THREAD

**Issue by donfirst** [influxdata/telegraf#9410]
### Relevant telegraf.conf:

```toml
# Configuration for telegraf agent
[agent]
  ## Default data collection interval for all inputs
  interval = "10s"
  ## Rounds collection interval to 'interval'
  ## ie, if interval="10s" then always collect on :00, :10, :20, etc.
  round_interval = true

  ## Telegraf will send metrics to outputs in batches of at most
  ## metric_batch_size metrics.
  ## This controls the size of writes that Telegraf sends to output plugins.
  metric_batch_size = 1000

  ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
  ## output, and will flush this buffer on a successful write. Oldest metrics
  ## are dropped first when this buffer fills.
  ## This buffer only fills when writes fail to output plugin(s).
  metric_buffer_limit = 10000

  ## Collection jitter is used to jitter the collection by a random amount.
  ## Each plugin will sleep for a random time within jitter before collecting.
  ## This can be used to avoid many plugins querying things like sysfs at the
  ## same time, which can have a measurable effect on the system.
  collection_jitter = "0s"

  ## Default flushing interval for all outputs. Maximum flush_interval will be
  ## flush_interval + flush_jitter
  flush_interval = "10s"
  ## Jitter the flush interval by a random amount. This is primarily to avoid
  ## large write spikes for users running a large number of telegraf instances.
  ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
  flush_jitter = "0s"

  ## By default or when set to "0s", precision will be set to the same
  ## timestamp order as the collection interval, with the maximum being 1s.
  ##   ie, when interval = "10s", precision will be "1s"
  ##       when interval = "250ms", precision will be "1ms"
  ## Precision will NOT be used for service inputs. It is up to each individual
  ## service input to set the timestamp at the appropriate precision.
  ## Valid time units are "ns", "us" (or "µs"), "ms", "s".
  precision = ""

  ## Logging configuration:
  ## Run telegraf with debug log messages.
  debug = false
  ## Run telegraf in quiet mode (error log messages only).
  quiet = false
  ## Specify the log file name. The empty string means to log to stderr.
  logfile = ""

  ## Override default hostname, if empty use os.Hostname()
  hostname = ""
  ## If set to true, do no set the "host" tag in the telegraf agent.
  omit_hostname = false
[[outputs.influxdb_v2]]
  ## The URLs of the InfluxDB cluster nodes.
  ##
  ## Multiple URLs can be specified for a single cluster, only ONE of the
  ## urls will be written to each interval.
  ## urls exp: http://127.0.0.1:8086
  #urls = ["http://eu-west-2-influxdb2.vibrantmedia.com:8086"]
  urls = ["http://changeme:8086"]

  ## Token for authentication.
  token = "$INFLUX_TOKEN"

  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "test"

  ## Destination bucket to write into.
  bucket = "bucket_change"
[[outputs.health]]
 service_address = "tcp://:8025"
[[inputs.statsd]]
 #   ## Protocol, must be "tcp", "udp", "udp4" or "udp6" (default=udp)
     protocol = "udp"
 #
 #   ## MaxTCPConnection - applicable when protocol is set to tcp (default=250)
 #   max_tcp_connections = 250
 #
 #   ## Enable TCP keep alive probes (default=false)
 #   tcp_keep_alive = true
 #
 #   ## Specifies the keep-alive period for an active network connection.
 #   ## Only applies to TCP sockets and will be ignored if tcp_keep_alive is fal$
 #   ## Defaults to the OS configuration.=
 #   tcp_keep_alive_period = "2h"
 #
 #   ## Address and port to host listener on
    service_address = ":8127"

    ## Parses tags in the datadog statsd format
    ## http://docs.datadoghq.com/guides/dogstatsd/
    ## deprecated in 1.10; use datadog_extensions option instead
    parse_data_dog_tags = true


```

### Steps to reproduce:

1. docker pull telegraf
2. docker images ( grab image  ID)
3. docker run -it IMAGE_ID /bin/bash
4. edit /etc/telegraf/telegraf.conf
5. Add secttion
[[outputs.health]]
 service_address = "tcp://:8025"
6. run telegraf

### Expected behavior:

 Telegraf should run without any  error ( the config is valid  for  1.18.3)

### Actual behavior:

root@249eaac04b94:/etc# telegraf
2021-06-22T14:07:36Z I! Starting Telegraf 1.9.0
2021-06-22T14:07:36Z I! Using config file: /etc/telegraf/telegraf.conf
2021-06-22T14:07:36Z E! [telegraf] Error running agent: Error parsing /etc/telegraf/telegraf.conf, Undefined but requested output: health

**Comment by popey** [comment]
Thanks for filing this issue. Did you maybe download the wrong (older) version of telegraf?
I note you're mentioning telegraf 1.9.0, when the latest release is telegraf 1.*19*.0.
I grabbed 1.19.0 and it works as expected with the snippet you suggested.

```toml
[[outputs.health]]
  service_address = "tcp://:8025"
```

```
$ usr/bin/telegraf  --config etc/telegraf/telegraf.conf 
2021-06-23T11:17:45Z I! Starting Telegraf 1.19.0
2021-06-23T11:17:45Z I! Loaded inputs: cpu
2021-06-23T11:17:45Z I! Loaded aggregators: 
2021-06-23T11:17:45Z I! Loaded processors: 
2021-06-23T11:17:45Z I! Loaded outputs: file health
2021-06-23T11:17:45Z I! Tags enabled: host=ac
2021-06-23T11:17:45Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ac", Flush Interval:10s
2021-06-23T11:17:45Z I! [outputs.health] Listening on http://[::]:8025
```

```
$ lynx --dump http://localhost:8025
OK

```

For completeness I downloaded telegraf 1.9.0 and it fails as you identified, as expected. as 1.9.0 dates from November 2018, and the health output plugin landed in [May 2019](https://github.com/influxdata/telegraf/pull/5882).

```
2021-06-23T11:20:24Z I! Starting Telegraf 1.9.0
2021-06-23T11:20:24Z E! [telegraf] Error running agent: Error parsing etc/telegraf/telegraf.conf, Undefined but requested output: health

```
