### ISSUE TITLE
elasticsearch output doesn't work with opensearch

### ISSUE THREAD

**Issue by tiny6996** [influxdata/telegraf#9414]
### Relevant telegraf.conf:

```toml
[[outputs.elasticsearch]]
  urls = ["https://10.0.0.195:9200"]
  timeout = "5s"
  health_check_interval = "10s"
  username = "admin"
  password = "admin"
  index_name = "telegraf-%Y.%m.%d"
  manage_template = true
  template_name = "telegraf"
  overwrite_template = false
  insecure_skip_verify = true
```

### System info:

os: Ubuntu 20.04
telegraf version: 1.19
opensearch version: 1.0.0-rc1

### Steps to reproduce:

1. start telegraf with output config listed
2.  follow logs with journalctl

### Expected behavior:

no logs and documents appearing in elasticserch
### Actual behavior:
outputs 2021-06-23T05:11:31Z E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'Elasticsearch version not supported: 1.0.0-rc1' to the console
