### ISSUE TITLE
Telegraf 1.19.0 isn't working with couchbase in 6.0.5 build 3340

### ISSUE THREAD

**Issue by Levarix** [influxdata/telegraf#9416]
### Relevant telegraf.conf:

```toml
### MANAGED BY dj-wasabi.telegraf ANSIBLE ROLE ###

[global_tags]
    customer = "<text>"
    product = "<text>"
    environment = "<text>"


# Configuration for telegraf agent
[agent]
    interval = "10s"
    debug = false
    hostname = "<text>"
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "0s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    logfile = ""
    omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.prometheus_client]]
    metric_version = 2
    ip_range = ["<text>"]
    collectors_exclude = ["gocollector", "process"]

###############################################################################
#                                  INPUTS                                     #
###############################################################################

[[inputs.cpu]]
    percpu = true
    totalcpu = true
[[inputs.disk]]
    ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
[[inputs.diskio]]
[[inputs.mem]]
[[inputs.net]]
[[inputs.system]]
[[inputs.netstat]]
[[inputs.processes]]
[[inputs.kernel]]
[[inputs.internal]]
[[inputs.linux_sysctl_fs]]


###############################################################################
#                                  PROCESSORS                                    #
###############################################################################
```
### Relevant couchbase.conf:
```toml
[[inputs.couchbase]]
    servers = ["http://<username>:<password>@localhost:8091"]
```

### System info:

Tested in Docker image and directly Ubuntu host
### Docker
Image: https://hub.docker.com/layers/bitnami/telegraf/1.19.0/images/sha256-50dfbfb37faed8894ca60cea120f1b819b2d31dc3515debfea2b849fc7f109d0?context=explore

### Ubuntu
Version: Ubuntu 18.04.5 LTS

### Steps to reproduce:

1. Just run telegraf 1.19.0 with couchbase plugin

### Expected behavior:

Gathering metrics

### Actual behavior:

```
[agent] Config: Interval:10s, Quiet:false, Hostname:"<hostname>", Flush Interval:10s
panic: runtime error: index out of range [59] with length 0

goroutine 43 [running]:
github.com/influxdata/telegraf/plugins/inputs/couchbase.(*Couchbase).gatherDetailedBucketStats(0xc00031d4c0, 0xc000b16401, 0x3a, 0xc000af3838, 0x7, 0xc000d0ef00, 0x17, 0x0)
	/bitnami/blacksmith-sandox/telegraf-1.19.0/src/github.com/influxdata/telegraf/plugins/inputs/couchbase/couchbase.go:164 +0xca1e
github.com/influxdata/telegraf/plugins/inputs/couchbase.(*Couchbase).gatherServer(0xc00031d4c0, 0x5648b58, 0xc000148e00, 0xc000b16401, 0x3a, 0xc000adfd68, 0xc000a391e0, 0x0)
	/bitnami/blacksmith-sandox/telegraf-1.19.0/src/github.com/influxdata/telegraf/plugins/inputs/couchbase/couchbase.go:111 +0xa2d
github.com/influxdata/telegraf/plugins/inputs/couchbase.(*Couchbase).Gather.func1(0xc000cf8060, 0x5648b58, 0xc000148e00, 0xc00031d4c0, 0xc000b16401, 0x3a)
	/bitnami/blacksmith-sandox/telegraf-1.19.0/src/github.com/influxdata/telegraf/plugins/inputs/couchbase/couchbase.go:64 +0x91
created by github.com/influxdata/telegraf/plugins/inputs/couchbase.(*Couchbase).Gather
	/bitnami/blacksmith-sandox/telegraf-1.19.0/src/github.com/influxdata/telegraf/plugins/inputs/couchbase/couchbase.go:62 +0x10d
```

**Comment by popey** [comment]
Thanks for the issue report. I installed couchbase-server 6.6.2-9600-1 (the latest as per their [documentation](https://docs.couchbase.com/server/current/install/ubuntu-debian-install.html) on both Ubuntu 20.04 LTS and 18.04 LTS and used your simple config snippet:

```toml
[[inputs.couchbase]]
    servers = ["http://admin:foo@10.55.242.238:8091", "http://admin:foo@10.55.242.204:8091"]
```

It seems to work fine here with telegraf 1.19.0, I'm unable to reproduce this. 

```bash
$ ./usr/bin/telegraf --debug --config etc/telegraf/telegraf.conf 
2021-06-23T10:15:52Z I! Starting Telegraf 1.19.0
2021-06-23T10:15:52Z I! Loaded inputs: couchbase cpu
2021-06-23T10:15:52Z I! Loaded aggregators: 
2021-06-23T10:15:52Z I! Loaded processors: 
2021-06-23T10:15:52Z I! Loaded outputs: file
2021-06-23T10:15:52Z I! Tags enabled: host=ac
2021-06-23T10:15:52Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"ac", Flush Interval:10s
2021-06-23T10:15:52Z D! [agent] Initializing plugins
2021-06-23T10:15:52Z D! [agent] Connecting outputs
2021-06-23T10:15:52Z D! [agent] Attempting connection to [outputs.file]
2021-06-23T10:15:52Z D! [agent] Successfully connected to outputs.file
2021-06-23T10:15:52Z D! [agent] Starting service inputs
couchbase_node,cluster=http://10.55.242.238:8091,host=ac,hostname=10.55.242.238:8091 memory_free=15566405632,memory_total=16488493056 1624443360000000000
couchbase_node,cluster=http://10.55.242.204:8091,host=ac,hostname=10.55.242.204:8091 memory_free=15632822272,memory_total=16488493056 1624443360000000000
2021-06-23T10:16:02Z D! [outputs.file] Wrote batch of 2 metrics in 214.815µs
2021-06-23T10:16:02Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics

```
Does it happy for you on a newer couchbase-server, or is it limited to 6.0.5?
