### ISSUE TITLE
Expand set of allowed symbols in graphite tagged

### ISSUE THREAD

**Issue by VorobevPavel-dev** [influxdata/telegraf#9421]
## Feature request

Adding new symbols is needed. Now in Telegraf there is a little problem with using ```graphite_tag_support```: symbols (for example '/') are replaced with '-'.

### Proposal:
Allow user to choose: replace '/' or any similar symbols with '-' or not via some sort of config field 

##### telegraf.conf
```toml
[agent]
  round_interval = true
  metric_batch_size = 500
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "2s"
  flush_jitter = "0s"
  precision = ""
  debug = true
  quiet = false
  logfile = "/var/log/telegraf/telegraf.log"
  # logfile_rotation_interval = "0d"
  logfile_rotation_max_size = "1MB"
  logfile_rotation_max_archives = 1
  hostname = "test-host"
  omit_hostname = false

[[inputs.file]]
        files = ["/home/user/input.txt"]
        data_format = "graphite"
        graphite_tag_support = true

[[outputs.file]]
        files = ["/home/user/output.txt"]
        data_format = "graphite"
        graphite_tag_support = true
```

##### input.txt
```
metrics_name_1;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_2;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_3;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_4;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_5;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_6;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_7;url=test:8080/metrics;tag1=test 10 1624358641
```

##### output.txt
```
metrics_name_1;host=test-host;tag1=test;url=test:8080-metrics 10 1624358641
metrics_name_2;host=test-host;tag1=test;url=test:8080-metrics 10 1624358641
metrics_name_3;host=test-host;tag1=test;url=test:8080-metrics 10 1624358641
metrics_name_4;host=test-host;tag1=test;url=test:8080-metrics 10 1624358641
metrics_name_5;host=test-host;tag1=test;url=test:8080-metrics 10 1624358641
metrics_name_6;host=test-host;tag1=test;url=test:8080-metrics 10 1624358641
metrics_name_7;host=test-host;tag1=test;url=test:8080-metrics 10 1624358641
```

However influx format does support such symbols:

```
# Telegraf output if i replace format with "influx" and delete "graphite_tag_support"
metrics_name_1,host=test-host,tag1=test,url=test:8080/metrics value=10 1624358641000000000
metrics_name_2,host=test-host,tag1=test,url=test:8080/metrics value=10 1624358641000000000
metrics_name_3,host=test-host,tag1=test,url=test:8080/metrics value=10 1624358641000000000
metrics_name_4,host=test-host,tag1=test,url=test:8080/metrics value=10 1624358641000000000
metrics_name_5,host=test-host,tag1=test,url=test:8080/metrics value=10 1624358641000000000
metrics_name_6,host=test-host,tag1=test,url=test:8080/metrics value=10 1624358641000000000
metrics_name_7,host=test-host,tag1=test,url=test:8080/metrics value=10 1624358641000000000
```

That behavior indicates that symbols are replaced when metric is about to be sent, not when gathered
##### telegraf.conf (```agent``` and ```global tags``` blocks are the same as before)
```toml
[[inputs.file]]
        files = ["/home/user/input.txt"]
        data_format = "graphite"
        graphite_tag_support = true

[[outputs.file]]
        files = ["/home/user/output.txt"]
        data_format = "graphite"
        graphite_tag_support = true
       allow_replacing_graphite_symbols = false
```

##### input.txt
```
metrics_name_1;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_2;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_3;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_4;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_5;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_6;url=test:8080/metrics;tag1=test 10 1624358641
metrics_name_7;url=test:8080/metrics;tag1=test 10 1624358641
````

##### output.txt
```
metrics_name_1;host=test-host;tag1=test;url=test:8080/metrics 10 1624358641
metrics_name_2;host=test-host;tag1=test;url=test:8080/metrics 10 1624358641
metrics_name_3;host=test-host;tag1=test;url=test:8080/metrics 10 1624358641
metrics_name_4;host=test-host;tag1=test;url=test:8080/metrics 10 1624358641
metrics_name_5;host=test-host;tag1=test;url=test:8080/metrics 10 1624358641
metrics_name_6;host=test-host;tag1=test;url=test:8080/metrics 10 1624358641
metrics_name_7;host=test-host;tag1=test;url=test:8080/metrics 10 1624358641
```

### Use case: 
For example, in [grafana](https://grafana.com/) it is inconvenient to navigate by different urls in set of metrics where all slashes are replaced with '-', a lot of database management systems will work without any reconfiguration. Moreover, it is complies with the standard of Graphite and tag usage in it.
