### ISSUE TITLE
error parsing http array, line 24: field corresponding to `insecure_skip_verify' in http.HTTP cannot be set through TOML

### ISSUE THREAD

**Issue by chvnch** [influxdata/telegraf#9459]
### Relevant telegraf.conf:

```toml
[[outputs.http]]
  url = "https://splunk.com:8088/services/collector"
  insecure_skip_verify = false
  data_format = "splunkmetric"
  splunkmetric_hec_routing = true
  timeout = "30s"

```

### System info:

1.19
### Steps to reproduce:

1. ...
2. ...
