### ISSUE TITLE
rabbitmq plugin 1.19.1 api/federation-links failure

### ISSUE THREAD

**Issue by pabigot** [influxdata/telegraf#9489]
### Relevant telegraf.conf:

```toml
# Reads metrics from RabbitMQ servers via the Management Plugin
[[inputs.rabbitmq]]
  queues = ["collate", "influxdb.write", "wsn.asrpdu", "wsn.signal"]
  exchanges = ["amq.topic", "influxdb", "openweather", "tasmota", "wsn"]
  queue_name_exclude = ["amq.gen-*", "mqtt-subscription-DVES_*"]
```

### System info:

```
central20[7]$ uname -a
Linux central20 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
central20[8]$ dpkg -l | grep telegraf
ii  telegraf                             1.19.1-1                                    amd64        Plugin-driven server agent for reporting metrics into InfluxDB.
central20[9]$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
### Steps to reproduce:

Update from telegraph 1.19.0 to 1.19.1

### Expected behavior:

Removal of unmarshal errors due to incorporation of #9443

### Actual behavior:

While #9443 fixed part of the problem, https://github.com/influxdata/telegraf/issues/9383#issuecomment-869687723 notes that `/api/federation-links` in at least some installations does not exist, a problem that was masked by the unmarshal bug.  My installation is now repeatedly complaining:

```
Jul 11 02:59:40 central20 telegraf[1353]: 2021-07-11T02:59:40Z E! [inputs.rabbitmq] Error in plugin: getting "/api/federation-links" failed: 404 Not Found
Jul 11 02:59:50 central20 telegraf[1353]: 2021-07-11T02:59:50Z E! [inputs.rabbitmq] Error in plugin: getting "/api/federation-links" failed: 404 Not Found
```
