### ISSUE TITLE
Monitor multiple postgres instances

### ISSUE THREAD

**Issue by jwmarshall** [influxdata/telegraf#949]
The postgres plugin says its capable of monitoring multiple servers/instances but I cant figure out how to provide these to the plugin. The redis plugin takes and array of server connection strings, but from what I can tell the postgres plugin only accepts one 'address' connection string.

**Comment by sparrc** [comment]
you can specify multiple instances of all plugins, so just do it like this:

```toml
[[inputs.postgres]]
  address = ....
  ...

[[inputs.postgres]]
  address = ...
  ...
```
