### ISSUE TITLE
Pdns_recursor plugin fails collection with I/O timeout

### ISSUE THREAD

**Issue by levithanius** [influxdata/telegraf#9494]
### Relevant telegraf.conf:
```toml
[[inputs.powerdns_recursor]]
  unix_sockets = ["/var/run/pdns/pdns_recursor.controlsocket"]
  socket_dir = "/var/run/pdns/"
  socket_mode = "0666"
```

### System info:
OS: Debian 10 buster
Telegraf: 1.19.0-1
pdns-recursor: 4.5.2-1pdns.buster

### Steps to reproduce:

Everything has been set up according to the manuals, no data is been sent to the InfluxDB.

(Same procdure as stated here: https://community.influxdata.com/t/pdns-recursor-plugin-fails-collection-with-i-o-timeout/19759)

Trying ```sudo -u telegraf rec_control get-all``` works, but when started normally in daemon mode, we get i/o timeouts.

### Actual behavior:

Jul 12 17:29:35 pdns-rec02 telegraf[80265]: 2021-07-12T15:29:35Z E! [inputs.powerdns_recursor] Error in plugin: read unixgram /var/run/pdns/pdns_recursor_telegraf2809338431652061292->/var/run/pdns/pdns_recursor.controlsocket: i/o timeout

### Additional info:

As mentioned in the influxdata link above, maybe this has something to do with the inserted newline?
```
Received rec_control command 'get-all
' from control socket
```
