### ISSUE TITLE
prometheus  output   metric_version=2 query result null

### ISSUE THREAD

**Issue by CarlosEssun** [influxdata/telegraf#9500]
### Relevant telegraf.conf:

```toml
[[inputs.http_listener_v2]]
  ## Address and port to host HTTP listener on
  service_address = ":9980" 
  ## Path to listen to.
  path = "/api/v1/write"

  ## HTTP methods to accept.
  methods = ["POST", "PUT"] 
  data_format = "prometheusremotewrite"

[[outputs.prometheus_client]]
  ## Address to listen on
  listen = ":9273"
  path = "/metrics"
  metric_version = 2 
 export_timestamp = true
```

### System info:

```bash 
[root@master telegraf]# uname -a
Linux master 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@master telegraf]# telegraf  --version
Telegraf 1.19.0 (git: HEAD ed412d7f)
```

### Steps to reproduce:

1. http post is submitted using application/x-protobuf; using the default metric_version configuration, the prefix of the original metric name is prefixed with prometheus_remote_write, followed by the original metric name, such as:
source:test_name{xxx:"xxxx"} ==>dest: prometheus_remote_write_test_name
2. The corresponding text content of the prometheus server /metric list is as follows:
```bash
# HELP prometheus_remote_write_qaz Telegraf collected metric
# TYPE prometheus_remote_write_qaz untyped
prometheus_remote_write_qaz{host="master",ssl_cipher="some_value"} 400
The type here becomes untyped, why is there no clear type (counter or other)
```
3. When export_timestamp = true is enabled, the record can be found in the /metric list, but the result of the query is null
### Actual behavior:
```bash
[root@master prometheus]# ./prometheus --version
prometheus, version 2.28.1 (branch: HEAD, revision: b0944590a1c9a6b35dc5a696869f75f422b107a1)
  build user:       root@2915dd495090
  build date:       20210701-15:20:10
  go version:       go1.16.5
  platform:         linux/amd64
```

```bash
1. I want to keep the original metric format and the timestamp to be the same as the http post.
```
### Additional info:

/metric list 
![image](https://user-images.githubusercontent.com/15261765/125565087-9bfc26d5-1538-4c7a-a911-7acf2616ee83.png)
query result 
![image](https://user-images.githubusercontent.com/15261765/125565119-fbb128fa-9103-4ca5-80a3-e3a343dd1869.png)
