### ISSUE TITLE
inputs.redis password containing % keeps reporting error

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#9507]
When the password field in configuration contains a % The process will keep reporting plugin error on every gather.

```
E! [inputs.redis] Error in plugin: EOF
```

**Comment by akrantz01** [comment]
I wasn't able to reproduce this on Telegraf 1.19.1 or 1.18.3. What version are you using and what does your `telegraf.conf` look like?

<br>
<p>Here's the files I was testing with:</p>
<details><summary><code>docker-compose.yml</code></summary>

```yaml
version: "3"

services:
  password:
    image: redis:6-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.73.0.2

networks:
  default:
    ipam:
      config:
        - subnet: 172.73.0.0/16
```
</details>

<details><summary><code>telegraf.conf</code></summary>

```toml
[[inputs.redis]]
  servers = ["tcp://172.73.0.2:6379"]
  password = "testingpassword%"

[[outputs.file]]
```
</details>

<details><summary><code>redis.conf</code></summary>

```
bind 0.0.0.0
protected-mode no
port 6379
always-show-logo no
requirepass testingpassword%

# All other options are the default
```
</details>
