### ISSUE TITLE
Incorrect data aggregation

### ISSUE THREAD

**Issue by KenStlqptq** [influxdata/telegraf#9511]
### Relevant telegraf.conf:

```toml
[[inputs.influxdb_v2_listener]]
  service_address = ":8086"
  token = ""
  tagexclude = ["host"]

[[aggregators.basicstats]]
  period = "2s"
  drop_original = false
  stats = ["count", "sum"]

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = ""
  organization = "stress-platform"
  bucket = "ken_test"
```

### System info:
telegraf 1.19.1    MacOS

As you can see the only plugin I use is [[aggregators.basicstats]]. It consumes all incoming data, summarizes their values and writes all data to InfluxDb. But total sum of aggregated data is much less than total sum of non-aggregated values. And I can't understand why does it hapen?
