### ISSUE TITLE
Error writing to outputs.sql: ERROR: type “double” does not exist (SQLSTATE 42704)

### ISSUE THREAD

**Issue by waqaskhan137** [influxdata/telegraf#9562]
Please redirect question about Telegraf usage to the InfluxData Community
site: https://community.influxdata.com/t/error-writing-to-outputs-sql-error-type-double-does-not-exist-sqlstate-42704/20979

### Relevant telegraf.conf:

```toml
# PUT TELEGRAF CONFIG HERE
[global_tags]

# Configuration for telegraf agent
[agent]
    interval = "60s"
    debug = true
    hostname = ""
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "5s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    omit_hostname = false
###############################################################################
#                                  OUTPUTS                                    #
###############################################################################
[[outputs.sql]]
  driver = "pgx"
  data_source_name = "postgres://postgres:postgres@10.32.22.179:5438/postgres"
```

### System info:

Telegraf version 1.19.2
Operating System : CentOS 7 

### Docker

```
telegraf:
    container_name: nms-telegraf
    image: telegraf:latest
    ports:
      - "162:162/udp"
    volumes:
      - /usr/share/snmp/mibs/:/usr/share/snmp/mibs/
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=P@ssword1
      - POSTGRES_HOST=10.32.22.179:5438
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SSLMODE=disable
      - POSTGRES_DBNAME=postgres
      - INFLUXDB_URL=http://influxdb:8086
      - AGENT_URL=udp://docker-host:1061
    depends_on:
      - influxdb_cli
    restart: always
    logging:
      options:
        max-file: "10"
        max-size: "50m"
```
### Steps to reproduce:

1. Use the output.sql plugin 
2. Fetch some snmp.input which includes double 

### Expected behavior:

It should write the metrics normally

### Actual behavior:

it throws an error about double data type not being in Postgres. 

### Additional info:

it seems the data type isn't handled properly in the output plugin. Although there is a conversion method mentioned in the [readme of the plugin](https://github.com/influxdata/telegraf/tree/release-1.19/plugins/outputs/sql) but there isn't any clear instructions for using it to eliminate the mentioned issue. 

```
  ## Metric type to SQL type conversion
  #[outputs.sql.convert]
  #  integer              = "INT"
  #  real                 = "DOUBLE"
  #  text                 = "TEXT"
  #  timestamp            = "TIMESTAMP"
  #  defaultvalue         = "TEXT"
  #  unsigned             = "UNSIGNED"
```

**Comment by bvilnis** [comment]
I came across this issue as well and had the same line of thought as you (using the type conversion).

I have my type conversion set as follows:
```
  [outputs.sql.convert]
    integer            = "BIGINT"
    real                 = "REAL"
    text                 = "TEXT"
    timestamp      = "TIMESTAMP"
    defaultvalue   = "TEXT"
    unsigned        = "BIGINT"
```

Which appears to have fixed the initial problem of:

`Error writing to outputs.sql: ERROR: type “double” does not exist (SQLSTATE 42704)`

but now produces:

`Error writing to outputs.sql: 358503060759561 is greater than maximum value for Int4`.

It would appear the type conversion is not mapping correctly as `BIGINT` should be converting the value to Int8, not Int4.

Any ideas @srebhan @reimda?

**Comment by thyseus** [comment]
I would like to add my issue here instead of creating a new one. I get the message:

```
2021-08-02T09:44:50Z E! [agent] Error writing to outputs.sql: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''kernel'("timestamp" TIMESTAMP,"host" TEXT,"context_switches" INT,"boot_time"...' at line 1
```

when connecting the `[outputs.sql]` plugin to a mariadb 10.3.29-0+deb10u1 instance.

**Comment by srebhan** [comment]
@waqaskhan137 please check the solution of @bvilnis 
```toml
  [outputs.sql.convert]
    integer = "BIGINT"
    real = "REAL"
    text = "TEXT"
    timestamp = "TIMESTAMP"
    defaultvalue = "TEXT"
    unsigned = "BIGINT"
```
and set `real = "REAL"`.
