### ISSUE TITLE
If snmp custom agent is restarted have to restart telegraf too

### ISSUE THREAD

**Issue by waqaskhan137** [influxdata/telegraf#9563]
InfluxData Community
site: https://community.influxdata.com/t/if-snmp-custom-agent-is-restarted-have-to-restart-telegraf-too/20761

### Relevant telegraf.conf:

```toml
# PUT TELEGRAF CONFIG HERE
[global_tags]

# Configuration for telegraf agent
[agent]
    interval = "60s"
    debug = true
    hostname = ""
    round_interval = true
    flush_interval = "10s"
    flush_jitter = "5s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    omit_hostname = false

[[outputs.influxdb_v2]]	
  ## Point to your influxdb container
 urls = ["${INFLUXDB_URL}"]
  ## Token for authentication.
  token = "mytoken"
  ## Organization is the name of the organization you wish to write to; must exist.
  organization = "afiniti"
  ## Destination bucket to write into.
  bucket = "Monitoring"

[[inputs.snmp]]
  agents = ["${AGENT_URL}"]
  interval = "60s"
  timeout = "5s"
  version = 3
  retries = 3
  sec_name = "user"
  auth_protocol = "SHA"
  auth_password = "secret"
  sec_level = "authPriv"
  priv_protocol = "AES"
  priv_password = "secret"

[[inputs.snmp.table]]
name = "linuxPerf"
oid = "OVERSIGHT-MIB::linuxPerf"

[[inputs.snmp.table]]
name ="archivalIOLoad"
oid ="OVERSIGHT-MIB::archivalIOLoad"
```

### System info:

Telegraf : 1.19.2 
OS : CentOS 7 

### Docker

```
telegraf:
    container_name: nms-telegraf
    image: docker.afiniti.com/telegraf-pg:1.0
    ports:
      - "162:162/udp"
    volumes:
      - /usr/share/snmp/mibs/:/usr/share/snmp/mibs/
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - INFLUXDB_DB=monitoring
      - INFLUXDB_ADMIN_USER=user
      - INFLUXDB_ADMIN_PASSWORD=Password
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_SSLMODE=disable 
      - POSTGRES_DBNAME=postgres
      - INFLUXDB_URL=http://influxdb:8086
      - AGENT_URL=udp://docker-host:1061
    depends_on:
      - influxdb_cli
    restart: always
    logging:
      options:
        max-file: "10"
        max-size: "50m"
```
### Steps to reproduce:

1. Restart the custom agent 
2. Telegraf won't be able to get any data from the custom agent using snmp.input plugin. 

### Expected behavior:

it should write metrics normally event after agent is restarted. 

### Actual behavior:

snmp.input plugin throws the following error. 

```
2021-07-30T14:47:05Z D! [outputs.influxdb_v2] Wrote batch of 15 metrics in 7.418528ms
2021-07-30T14:47:05Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
```
Here agent has been restarted and now we start getting timeouts for requests. 
```
2021-07-30T14:48:40Z E! [inputs.snmp] Error in plugin: agent udp://docker-host:1061: performing get on field productionMySQLPort: request timeout (after 3 retries)
2021-07-30T14:48:47Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics
2021-07-30T14:49:00Z W! [inputs.snmp] Collection took longer than expected; not complete after interval of 1m0s
2021-07-30T14:49:00Z D! [inputs.snmp] Previous collection has not completed; scheduled collection skipped

```
