### ISSUE TITLE
Prometheus metrics titles are capitalized 

### ISSUE THREAD

**Issue by dewnull** [influxdata/telegraf#9568]
### Relevant telegraf.conf:

```toml
[[outputs.prometheus_client]]
  collectors_exclude = [
    "gocollector",
    "process"
  ]
  expiration_interval = "60s"
  listen = ":9273"
  metric_version = 2
  path = "/metrics"
  string_as_label = false
```

### System info:

 using helm chart to deploy Telegraf  https://github.com/influxdata/helm-charts/tree/master/charts/telegraf
### Docker
1.19-alpine and 1.19.2-alpine

### Steps to reproduce:

1.  deploy telegraf 

### Expected behavior:

influxdb_query_executor_queries_active
### Actual behavior:
influxdb_query**E**xecutor_queriesActive

### Additional info:
The prometheus_client metrics are have mixed 🐪camel case and 🐍snake case.
