### ISSUE TITLE
Aggregation and starlark results in no output

### ISSUE THREAD

**Issue by tsujp** [influxdata/telegraf#9592]
It appears that using an aggregator with a starlark processor is indeed calling starlark twice as expected, but I don't see my expected aggregation. I cannot work out why this is. Is this a bug?

### Relevant telegraf.conf:

```toml
[agent]
  debug = true
  quiet = false
  interval = "2s"
  round_interval = true
  collection_jitter = "0s"
  flush_interval = "60s" # Do not set below `interval`.
  flush_jitter = "0s"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  precision = ""
  hostname = ""
  omit_hostname = true

# metrics sent here look like: http_listener_v2 health=5
# where `5` is any number
[[inputs.http_listener_v2]]
  service_address = ":6066"
  methods = ["POST"]
  data_source = "body"
  data_format = "json"

  path = "/metrics"

[[processors.starlark]]
  fieldpass = ["height"]
  source = '''
def apply(metric):
  v = metric.fields.get('height) * 10
  metric.fields['height'] = v * 10
  return metric
'''

[[aggregators.basicstats]]
  period = "60s"
  fieldpass = ["height"]
  grace = "1s"
  drop_original = false
  stats = ["diff"]
```

### System info:

Telegraf 1.19.2-1 (git: release-1.14-geneva 0366f9d2)
Ubuntu 20.04

### Expected behavior:

Given input:

```
http_listener_v2 height=5641 1628162160512897109
http_listener_v2 height=5642 1628162165512468553
http_listener_v2 height=5643 1628162170512735867
http_listener_v2 height=5644 1628162175511493874
http_listener_v2 height=5645 1628162180511945925
http_listener_v2 height=5646 1628162185511711719
http_listener_v2 height=5647 1628162190010513625
http_listener_v2 height=5648 1628162195510946111
http_listener_v2 height=5649 1628162200510761044
http_listener_v2 height=5650 1628162205511840938
http_listener_v2 height=5651 1628162210510445631
http_listener_v2 height=5652 1628162215010422597
```

Expected output:

```
http_listener_v2 height=564100 1628162160512897109
http_listener_v2 height=564200 1628162165512468553
http_listener_v2 height=564300 1628162170512735867
http_listener_v2 height=564400 1628162175511493874
http_listener_v2 height=564500 1628162180511945925
http_listener_v2 height=564600 1628162185511711719
http_listener_v2 height=564700 1628162190010513625
http_listener_v2 height=564800 1628162195510946111
http_listener_v2 height=564900 1628162200510761044
http_listener_v2 height=565000 1628162205511840938
http_listener_v2 height=565100 1628162210510445631
http_listener_v2 height=565200 1628162215010422597
http_listener_v2 height_diff=11 1628162215010422597    <--- notice we expected to have the aggregation _diff
```

### Actual behavior:

Given input:

```
same as above
```

Observed output:

```
http_listener_v2 height=564100 1628162160512897109
http_listener_v2 height=564200 1628162165512468553
http_listener_v2 height=564300 1628162170512735867
http_listener_v2 height=564400 1628162175511493874
http_listener_v2 height=564500 1628162180511945925
http_listener_v2 height=564600 1628162185511711719
http_listener_v2 height=564700 1628162190010513625
http_listener_v2 height=564800 1628162195510946111
http_listener_v2 height=564900 1628162200510761044
http_listener_v2 height=565000 1628162205511840938
http_listener_v2 height=565100 1628162210510445631
http_listener_v2 height=565200 1628162215010422597   <--- lack of any aggregation diff
```

### Additional info:

None.
