### ISSUE TITLE
JSON parser reports additional metric when field and object subtable used together

### ISSUE THREAD

**Issue by sjwang90** [influxdata/telegraf#9594]
When you use a `.field` + `.object` with your JSON parser, it an includes an extra line of the whatever `.field` or `.tag` subtables are also configured with the object. 

### Relevant telegraf.conf:

```toml
[[inputs.http]]
  urls = [
    "https://api.openweathermap.org/data/2.5/weather?q=london&appid=dd0be88fd6d6fa1097a785db9de880b3&units=metric"
  ]
  tagexclude = ["url", "host"]
  data_format = "json_v2"
  [[inputs.http.json_v2]]
      measurement_name = "openweather"
      [[inputs.http.json_v2.field]]
          path = "weather.#.main"
          rename = "summary"
      [[inputs.http.json_v2.field]]
          path = "weather.#.description"
      [[inputs.http.json_v2.object]]
            path = "@this"
            included_keys = ["coord_lat", "coord_lon", "main_temp", "wind_speed"] # List of JSON keys (for a nested key, prepend the parent keys with underscores) that should be only included in result
            tags = ["id", "name"] # List of JSON keys (for a nested key, prepend the parent keys with underscores) to be a tag instead of a field

[[outputs.file]]
    files = ["stdout"]
```

### System info:

Telegraf 1.19.2

### Expected behavior:

Output:
```
openweather,id=2.643743e+06,name=London coord_lat=51.5085,coord_lon=-0.1257,description="light rain",main_temp=16.88,summary="Rain",wind_speed=5.14 1628186541000000000
```

### Actual behavior:
Output
```
openweather description="light rain",summary="Rain" 1628186541000000000
openweather,id=2.643743e+06,name=London coord_lat=51.5085,coord_lon=-0.1257,description="light rain",main_temp=16.88,summary="Rain",wind_speed=5.14 1628186541000000000
```
