### ISSUE TITLE
inputs.snmp get the data of discontinuity

### ISSUE THREAD

**Issue by meimz** [influxdata/telegraf#9607]
192.168.1.35 is not noline, To get the data of 192.168.1.34 discontinuity

snmp timeout = 5s 

telegraf config example

```toml
[[inputs.snmp]]
  interval = "5s"
  agents = ["192.168.1.34","192.168.1.35"]
  version = 2
  community = "public"
  [[inputs.snmp.table]]
    oid = ".1.3.6.1.2.1.25.2.3"
    name = "hrStorageTable"
  [[inputs.snmp.table]]
    oid = ".1.3.6.1.2.1.25.3.3"
    name = "hrProcessorTable"
    index_as_tag = true
```
