### ISSUE TITLE
Error getting VM curent VM status - Proxmox error

### ISSUE THREAD

**Issue by abrondijk** [influxdata/telegraf#9611]
### Relevant telegraf.conf:
```toml
# Provides metrics from Proxmox nodes (Proxmox Virtual Environment > 6.2).
[[inputs.proxmox]]
  ## API connection configuration. The API token was introduced in Proxmox v6.2. Required permissions for user and token: PVEAuditor role on /.
  base_url = "https://localhost:8006/api2/json"
  api_token = "<api_token>"
  ## Node name, defaults to OS hostname
  #node_name = ""

  ## Optional TLS Config
  # tls_ca = "/etc/telegraf/ca.pem"
  # tls_cert = "/etc/telegraf/cert.pem"
  # tls_key = "/etc/telegraf/key.pem"

  ## Use TLS but skip chain & host verification
  insecure_skip_verify = true
  # HTTP response timeout (default: 5s)
  response_timeout = "5s"
```

### System info:

PVE 7.0-11 based on debian 11
Telegraf version 1.19.2, installed according to [this ](https://docs.influxdata.com/telegraf/v1.19/introduction/installation/) guide.

### Steps to reproduce:

1. Start the telegraf service

### Expected behavior:

I expect telegraf to behave normally and to not spam errors in syslog.

### Actual behavior:

The following error on every poll:
```
Aug 11 12:51:05 Raptor telegraf[625244]: 2021-08-11T10:51:05Z E! [inputs.proxmox] Error getting VM curent VM status: json: cannot unmarshal number into Go struct field VMStat.data.vmid of type string
Aug 11 12:51:05 Raptor telegraf[625244]: 2021-08-11T10:51:05Z E! [inputs.proxmox] Error getting VM stats: %vjson: cannot unmarshal number into Go struct field VMStat.data.vmid of type string
```
Besides the fact that current is spelled with only 1 R, I expect the data from proxmox to be gathered and sent to my output plugins.

### Additional info:

I can confirm that the api token I use is correct, because if I change it, I get a completely different error.
