### ISSUE TITLE
HTTP Response Input: Support extraction of response body and export to environment variables

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#9672]
### Current behavior: Extract and export not supported. Two inputs can not work in coalition.

The `first` input do a login request which will response with a `sessionId` that needs to be used in the body `second` input.

```toml
# This input will response with body: {"sessionId":"session-id-last-for-a-period-of-time"}
[[inputs.http_response]]
  urls = ["http://localhost/api/v1/login"]

# This input requires sessionId obtained from first input but now can only be hardcoded.
[[inputs.http_response]]
  urls = ["http://localhost/api/v1/home"]
  body = '''
  {'sessionId':'hardcoded-sessionId'}
  '''
```

### Desired behavior: Extract and export supported. Two inputs can share variables via environment variables.

```toml
# This input will extract sessionId from response body and export it as environment variable: SESSIONID
[[inputs.http_response]]
  urls = ["http://localhost/api/v1/login"]
[inputs.http_response.response_set_env]
  SESSIONID = "sessionId"

# This input will use environment variable SESSIONID that was exported by first input
[[inputs.http_response]]
  urls = ["http://localhost/api/v1/home"]
  body = '''
  {'sessionId':'${SESSIONID}'}
  '''
```

### Use case: 

Per above inputs' comment. When two or more HTTP requests are dependent on each other (e.g. requires a sessionId), they can share the dependent value via environment variables.

This feature is really powerful as it enables a fully covered web app HTTP check. Also, the exported environment variables can be used by other part of the config file(wherever supports `${}` reference).
