### ISSUE TITLE
windows events sent to loki with spaces in the field name

### ISSUE THREAD

**Issue by tiny6996** [influxdata/telegraf#9691]
### Relevant telegraf.conf:

```toml
[[ outputs.loki]]
  domain = "$loki_url"
  username = "$loki_user"
  password = "$loki_password"
  namepass = ["tail*","systemd_units","exec*","win_services","win_eventlog"]

[[inputs.win_eventlog]]
  event_fields = ["Message","UserName","TimeCreated","Level","ProcessID","ThreatID","Version"]
  separator = "_"
  xpath_query = '''<QueryList>
  <Query Id="0" Path="Microsoft-Windows-Windows Defender/Operational">
    <Select Path="Microsoft-Windows-Windows Defender/Operational">*</Select>
    <Select Path="Microsoft-Windows-Windows Defender/WHC">*</Select>
  </Query>
</QueryList>'''
```

### System info:

windows server 2022 and Windows 10

### Steps to reproduce:

1. add pasted to config to c:\program files\telegraf\telegraf.d\defender.conf
2. restart telegraf
3. download eicar files from https://www.eicar.org/?page_id=3950 on the machine with telegraf
4. try to view logs in grafana's  explore area with the query ```{EventID="1117"} |  logfmt ```

### Expected behavior:

all fields are parsed with logfmt correctly 

### Actual behavior:

keys contain spaces so loki is not able to parse the field names correctly 

![image](https://user-images.githubusercontent.com/13280132/131267337-194997ee-8dc3-4dae-8684-d28575b1c0f9.png)

### Additional info:
example output from grafana. I have asked question if there is work around on the grafana forums, and I am also able to parse this correctly from my influxdb2 instance.
```
Data_Type ID="2" Data_Product Name="Microsoft Defender Antivirus" Data_Product Version="4.18.2107.4" Data_Origin Name="Internet" Data_Category ID="42" Data_State="2" Data_Pre Execution Status="0" Data_Security intelligence Version="AV: 1.347.660.0, AS: 1.347.660.0, NIS: 1.347.660.0" Data_Threat ID="2147538637" Data_Severity ID="5" Data_Severity Name="Severe" Data_Post Clean Status="0" Message="Microsoft Defender Antivirus has taken action to protect this machine from malware or other potentially unwanted software." Data_Detection Time="2021-08-29T22:20:05.221Z" Data_Error Description="The program could not find the malware and other potentially unwanted software on this device." Data_Category Name="Virus" Data_FWLink="https://go.microsoft.com/fwlink/?linkid=37020&name=Virus:VBS/Gascript.gen&threatid=2147538637&enterprise=0" Data_Process Name="Unknown" Data_Action Name="Clean" Data_Error Code="0x80508023" Version="0" UserName="NT AUTHORITY\SYSTEM" Data_Detection ID="{874FED35-2455-4FA9-B480-09EF81494973}" Data_Engine Version="AM: 1.1.18400.5, NIS: 1.1.18400.5" Data_Source ID="4" Data_Source Name="Downloads and attachments" Data_Remediation User="NT AUTHORITY\SYSTEM" Data_Additional Actions String="No additional actions required" Data_Threat Name="Virus:VBS/Gascript.gen" Data_Detection User="RENIER\Administrator" Data_Origin ID="4" Data_Execution ID="0" Data_Execution Name="Unknown" Data_Type Name="Generic" Data_Additional Actions ID="0" TimeCreated="2021-08-29T22:20:23.3470689Z" Data_Status Code="2" Data_Path="containerfile:_C:\Users\Administrator\Downloads\camila.zip; file:_C:\Users\Administrator\Downloads\camila.zip->VBS.Camila.vbs; webfile:_C:\Users\Administrator\Downloads\camila.zip|https://raw.githubusercontent.com/brandoski99/GEDZAC-E-zines-Sources-Malwares/master/camila.zip|pid:132,ProcessStart:132747492040801694; webfile:_C:\Users\Administrator\Downloads\camila.zip|https://raw.githubusercontent.com/brandoski99/GEDZAC-E-zines-Sources-Malwares/master/camila.zip|pid:5876,ProcessStart:132747492068761772" Data_Action ID="1" 
```
