### ISSUE TITLE
MQTT Consumer subscription topic changes are not honoured if persistent_session is true until the session is invalidated 

### ISSUE THREAD

**Issue by DavidAntliff** [influxdata/telegraf#9703]
Using `persistent_session = true` for MQTT Consumer prevents subscription topic changes from taking effect, even after the telegraf container is recreated. _Even if the broker and telegraf are restarted, the topic changes are not honoured until telegraf & the broker collectively fail to reinstantiate the session._

MQTT supports persistent sessions where previous subscriptions are restored when the client reconnects. This is expected behaviour. What is not expected by me is that telegraf does not subscribe to any newly defined topics, or unsubscribe from any removed topics, making an assumption that the list of topics in the config has not changed. In most cases this is true, but when trying to configure telegraf this can be a source of confusion.

This may be intended behaviour but if it is, it's extremely obtuse and took a long time to figure out cause/effect. If it's intentional I suggest better documentation around `persistent_session = true` and topic changes, as well as documentation of the proper way to invalidate a session and have the topics reprocessed. At the very least, a recommendation to set `persistent_session` to false while making config changes is advised.

Otherwise this could be the source of major confusion for end users. Looking through old issues I see evidence of users' having trouble with getting MQTT Consumer to work and I wonder how many of those were due to this issue (and it mysteriously resolving itself once mosquitto or telegraf threw away the session).

### Relevant telegraf.conf:

```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_buffer_limit = 10000
  flush_buffer_when_full = true
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  debug = false
  quiet = false
  hostname = "docker-telegraf"

[[outputs.influxdb]]
  urls = ["udp://network-multitool:8089"]

# Using a UDP output to view the plugin's output
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  qos = 0
  topics = ["telemetry/float/#"]
  persistent_session = true
#  persistent_session = false
  client_id = "telegraf-consumer-float"
  data_format = "value"
  data_type = "float"
```

### System info:

Arch linux 20210831, docker 20.10.8, telegraf 1.19.3, mosquitto 2.0.11.

### Docker

```yaml
version: "3.5"

networks:
  default:
    name: mqtt

services:
  network-multitool:
    image: praqma/network-multitool:extra
    links:
     - telegraf

  # Define a Telegraf service
  telegraf:
    image: telegraf:1.19
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"

  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.8.9
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_UDP_ENABLED: "true"
    ports:
      - "8086:8086"
      - "8089:8089/udp"

  # Define a Chronograf service
  chronograf:
    image: chronograf:1.9.0
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor

  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.6.1
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"

  # Define a mosquitto MQTT broker service
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:2.0.11
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/:/mosquitto/config/:ro
      - ./mosquitto/log/:/mosquitto/log/
      - ./mosquitto/data/:/mosquitto/data/
```

### Steps to reproduce:

With `persistent_session = true`:

1. `docker-compose up -d`
2. `docker-compose exec network-multitool /bin/bash`
3. In this container: `socat udp-recvfrom:8089,reuseaddr,fork -`
4. `mosquitto_pub -h localhost -t telemetry/float/test0 -m 53` - you should see line protocol appear on socat's stdout: `mqtt_consumer,host=docker-telegraf,topic=telemetry/float/test0 value=53 1630455966575178022`
5. Edit `telegraf.conf` and change the topic to `topics = ["telemetry2/float/#"]` - note the change from "telemetry" to "telemetry2".
6. Restart telegraf: `docker-compose restart telegraf`
7. `mosquitto_pub -h localhost -t telemetry/float/test0 -m 53` - no output on socat's stdout (expected)
8. `mosquitto_pub -h localhost -t telemetry2/float/test0 -m 53` - *no output on socat's stdout (unexpected!)*
9. Bring down the whole stack: `docker-compose down` and restart it `docker-compose up -d`
10. `mosquitto_pub -h localhost -t telemetry/float/test0 -m 53` - no output on socat's stdout (expected)
11. `mosquitto_pub -h localhost -t telemetry2/float/test0 -m 53` - *still no output on socat's stdout (unexpected!)*
12. Restart mosquitto: `docker-compose restart mosquitto` and look at telegraf's log: `docker-compose logs -f telegraf`
13. Wait for telegraf to reconnect to mosquitto:

```
telegraf_1           | 2021-09-01T00:37:20Z I! [inputs.mqtt_consumer] Connected [tcp://mosquitto:1883]
telegraf_1           | 2021-09-01T00:37:11Z E! [inputs.mqtt_consumer] Error in plugin: connection lost: EOF
```
14. `mosquitto_pub -h localhost -t telemetry/float/test0 -m 53` - no output on socat's stdout (expected)
15. `mosquitto_pub -h localhost -t telemetry2/float/test0 -m 53` - *observe output on socat's stdout (expected)*

If `persistent_session = false`, then the expected behaviour below is what occurs (expected).

Note: there may be a race involved between mosquitto and telegraf so that sometimes a down/up cycle does result in a clearing of the session. I've seen this happen on a different computer.

### Expected behavior:

1. `docker-compose up -d`
2. `docker-compose exec network-multitool /bin/bash`
3. In this container: `socat udp-recvfrom:8089,reuseaddr,fork -`
4. `mosquitto_pub -h localhost -t telemetry/float/test0 -m 53` - you should see line protocol appear on socat's stdout: `mqtt_consumer,host=docker-telegraf,topic=telemetry/float/test0 value=53 1630455966575178022`
5. Edit `telegraf.conf` and change the topic to `topics = ["telemetry2/float/#"]` - note the change from "telemetry" to "telemetry2".
6. Restart telegraf: `docker-compose restart telegraf`
7. `mosquitto_pub -h localhost -t telemetry/float/test0 -m 53` - no output on socat's stdout (expected)
8. `mosquitto_pub -h localhost -t telemetry2/float/test0 -m 53` - *observe output on socat's stdout (expected)*

### Actual behavior:

If `persistent_session = true` is set in the config, then the UDP line-protocol output on socat's stdout does not appear until mosquitto is restarted *while telegraf is running*.  I suspect this "connection lost" condition causes telegraf to finally discard the persistent session and pick up the changes to the topics.
