### ISSUE TITLE
Prometheus Input: Support filtered metrics gathering.

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#9711]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:

`All metrics` will be gathered from the urls.

```toml
# Read metrics from one or many prometheus clients
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://localhost:9100/metrics"]
```

### Desired behavior:

Only `metric_a` and `metric_b` will be gathered from the urls.

```toml
# Read metrics from one or many prometheus clients
[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://localhost:9100/metrics"]
  metric_filter = ["metric_a", "metric_b"]
```

### Use case: 

This adds flexibility for pulling metrics from various exporters as one can selectively gather metrics by their needs.
