### ISSUE TITLE
Suricata Plugin not sending Logs

### ISSUE THREAD

**Issue by estebanramos** [influxdata/telegraf#9730]
Hello, I've configured my Suricata and Telegraf as the guide says but I'm not getting any info on my outputs (Prometheus, File). This is my configuration. It's seems like Suricata it's not connecting to Telegraf socket.

```
  - eve-log:
      enabled: yes
      filetype: unix_stream
      filename: /tmp/suricata-stats.sock
      types:
        - stats:
           threads: yes
        #- alert:
        #   tagged-packets: yes
```

```
# # Suricata stats plugin
 [[inputs.suricata]]
#   ## Data sink for Suricata stats log
#   # This is expected to be a filename of a
#   # unix socket to be created for listening.
   source = "/tmp/suricata-stats.sock"
#
#   # Delimiter for flattening field keys, e.g. subitem "alert" of "detect"
#   # becomes "detect_alert" when delimiter is "_".
   #delimiter = "_"
   #alert = true
```

And the socket created looks like this.

`srwxr-xr-x  1 telegraf telegraf    0 Sep  7 12:36 suricata-stats.sock`
