### ISSUE TITLE
postgresql_extensible wrong timestamp

### ISSUE THREAD

**Issue by phemmer** [influxdata/telegraf#9737]
### Relevant telegraf.conf:

```toml
[[inputs.postgresql_extensible]]
[[inputs.postgresql_extensible.query]]
sqlquery = "select * from foo"
```

### System info:

ba1484c

### Steps to reproduce:

1. Create a table (`foo`) with many values
2. Run the above config

### Expected behavior:

All emitted metrics for each monitoring interval should have the same timestamp.

### Actual behavior:

Each metric has a different timestamp.

### Additional info:

After digging through the code, the problem is that the timestamp is being added at the time the plugin iterates over the response row. This is wrong as PostgreSQL executes queries such that all results are from a single point in time. Thus all results should have the same timestamp, that of when the query was executed, not when the row was handled.
