### ISSUE TITLE
telegraf forwarding empty metrics

### ISSUE THREAD

**Issue by johnseekins** [influxdata/telegraf#9738]
### Relevant telegraf.conf:

```toml
[global_tags]
  dc = "1"

[agent]
  hostname = ""
  omit_hostname = false
  interval = "60s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 100000
  collection_jitter = "10s"
  flush_interval = "10s"
  flush_jitter = "5s"
  precision = ""
  logfile = "/var/log/telegraf/telegraf.log"
  debug = false
  quiet = false

[[inputs.prometheus]]
  ## An array of urls to scrape metrics from.
  urls = ["http://localhost:3000/metrics"]
  metric_version = 2
  name_override = "grafana"
  tagexclude = ["url"]
  [inputs.prometheus.tags]
    metrictype = "applicationlevel"

[[outputs.kafka]]
  brokers = ["<broker list>"]
  compression_codec = 1
  data_format = "json"
  required_acks = 1
  routing_tag = "host"
  tagexclude = ["metrictype"]
  topic = "metrics"
  [outputs.kafka.tagpass]
    metrictype = ["applicationlevel"]
```

### System info:

telegraf 1.17.2 and 1.19.3
Ubuntu 20.04

### Steps to reproduce:

Collecting prometheus-style data from a Grafana instance, I consistently get some empty values collected and forwarded to Kafka. While they don't hurt anything, it seems like they _should_ be dropped.

For example, this metric was dropped on the other side of Kafka:
```
{"fields":{},"tags":{"dc":"1","handler":"/","host":"grafana","method":"get","quantile":"0.99","statuscode":"200"},"name":"grafana_","timestamp":1631129284}
```
You can see there are no actual fields attached to the metric.

### Expected behavior:

Empty metrics aren't forwarded to systems and are instead dropped or filtered in telegraf. Or even not collected in the first place.

### Additional info:

This also occurs in data from Benthos (https://benthos.dev/) and occasionally with statsd data.

In the case of Grafana, it seems to be histogram stats that have a `NaN` value. I would assume something similar is happening in other places, where a system is initially submitting a `NaN` and telegraf is (reasonably) not keeping that field, but not actually dropping the entire metric.
