### ISSUE TITLE
[mongodb] Cannot get metrics from arbiter - failed to gather data: NotMasterOrSecondary  (oplog stats)

### ISSUE THREAD

**Issue by alx75** [influxdata/telegraf#9742]
### Relevant telegraf.conf:

```toml
[[inputs.mongodb]]
  servers = ["mongodb://localhost:27017/?connect=direct"]
  gather_perdb_stats = true
```

### System info:

OS : 4.9.0-16-amd64 #1 SMP Debian 4.9.272-2 (2021-07-19) x86_64 GNU/Linux
Telegraf version : Telegraf 1.19.3 (git: HEAD a799489f)

### Steps to reproduce:

start telegraf 

### Expected behavior:

Telegraf must gather metrics from mongo

### Actual behavior:

Telegraf fails to get metrics from mongo

### Additional info:

Logs:
E! [inputs.mongodb] Unable to get oplog stats: mongo: no documents in result
E! [inputs.mongodb] failed to gather data: "(NotMasterOrSecondary) node is not in primary or recovering state"
