### ISSUE TITLE
HTTP Response Input: Add multiple entries in response_string_match

### ISSUE THREAD

**Issue by KEVISONG** [influxdata/telegraf#9746]
## Feature Request

Opening a feature request kicks off a discussion.

### Current behavior:

Only `ONE` string is supported in `response_string_match`

```toml
[[inputs.http_response]]
  urls = ["http://awesome-app/api/v1/ping"]
  method = "GET"
  response_string_match = "\"code\":0"
```

### Desired behavior:

Support multiple entries in `response_string_match`, where either one match will be considered success.

```toml
[[inputs.http_response]]
  urls = ["http://awesome-app/api/v1/ping"]
  method = "GET"
  response_string_match = ["\"code\":0", "\"code\":1"]
```

### Use case: 

This is useful when the exact same HTTP API call that results in two different response, where both response are considered normal. 

A real example is when a HTTP API have QPS limit for the same origin IP. The API returns `"code":0` if success while `"code":1` for QPS limited call. Both responses indicate a successful API call and the server is healthy.
