### ISSUE TITLE
inputs.exec first start is delayed until interval is reached

### ISSUE THREAD

**Issue by vainkop** [influxdata/telegraf#9759]
### Relevant telegraf.conf:

```toml
    [[inputs.exec]]
      commands = ["/write.sh"]
      interval = "3600s"
      timeout = "3600s"
      data_format = "influx"
```

### System info:

**Telegraf v1.19.3** running on **EKS 1.21**

### Steps to reproduce:

1. start telegraf with inteval big enough to notice idle behavior f.e. `interval = "3600s"`
2. change `interval = "60s"` & recreate pod. Notice that exec plugin started exactly after 60s of pod start.

### Expected behavior:

I expect the exec plugin to start immediately but repeat at the interval which is configured with `interval = `
