### ISSUE TITLE
Mountpoints of machine mismatch to mountpoints seen by Telegraf in the container

### ISSUE THREAD

**Issue by mazzy89** [influxdata/telegraf#9792]
### Relevant telegraf.conf:

```toml
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = "$HOSTNAME"
  omit_hostname = false

[[inputs.diskio]]

[[inputs.kernel]]

[[inputs.mem]]

[[inputs.net]]
  interfaces = ["eth0"]

[[inputs.processes]]

[[inputs.swap]]

[[inputs.system]]

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.file]]
  files = ["/sys/class/thermal/thermal_zone0/temp"]
  name_override = "cpu_temperature"
  data_format = "value"
  data_type = "integer"

[[outputs.influxdb]]
  urls = ["http://192.168.10.93:8086"]
  database = "k3s"
  username = "k3s"
  password = "k3s"
```

### System info:

```
root@telegraf-telegraf-ds-lsqzb:/# telegraf --version
Telegraf 1.19.3 (git: HEAD a799489f)
```

Running on a RPI 4

### Docker

Running the upstream Telegraf-ds Helm chart on a k8s cluster https://github.com/influxdata/helm-charts/tree/master/charts/telegraf-ds

### Steps to reproduce:

1. ...
2. ...

### Expected behavior:

I would expect that the mountpoint `/dev/root /` would be visible in Telegraf.

### Actual behavior:

This is what I see from the pod (container) running  Telegraf

```
root@telegraf-telegraf-ds-lsqzb:/# telegraf --input-filter=disk --test

2021-09-22T11:11:39Z I! Starting Telegraf 1.19.3
2021-09-22T11:11:39Z I! Using config file: /etc/telegraf/telegraf.conf
> disk,cluster=hzk8s.k3s.home,device=mmcblk0p2,fstype=ext4,host=worker03.hzk8s.k3s.home,mode=rw,path=/etc/hosts free=117067415552i,inodes_free=7237587i,inodes_total=7273296i,inodes_used=35709i,total=125897183232i,used=3694718976i,used_percent=3.059501217364901 1632309099000000000
> disk,cluster=hzk8s.k3s.home,device=mmcblk0p2,fstype=ext4,host=worker03.hzk8s.k3s.home,mode=rw,path=/etc/resolv.conf free=117067415552i,inodes_free=7237587i,inodes_total=7273296i,inodes_used=35709i,total=125897183232i,used=3694718976i,used_percent=3.059501217364901 1632309099000000000
> disk,cluster=hzk8s.k3s.home,device=mmcblk0p2,fstype=ext4,host=worker03.hzk8s.k3s.home,mode=ro,path=/etc/telegraf free=117067415552i,inodes_free=7237587i,inodes_total=7273296i,inodes_used=35709i,total=125897183232i,used=3694718976i,used_percent=3.059501217364901 1632309099000000000
> disk,cluster=hzk8s.k3s.home,device=mmcblk0p2,fstype=ext4,host=worker03.hzk8s.k3s.home,mode=rw,path=/dev/termination-log free=117067415552i,inodes_free=7237587i,inodes_total=7273296i,inodes_used=35709i,total=125897183232i,used=3694718976i,used_percent=3.059501217364901 1632309099000000000
> disk,cluster=hzk8s.k3s.home,device=mmcblk0p2,fstype=ext4,host=worker03.hzk8s.k3s.home,mode=rw,path=/etc/hostname free=117067415552i,inodes_free=7237587i,inodes_total=7273296i,inodes_used=35709i,total=125897183232i,used=3694718976i,used_percent=3.059501217364901 1632309099000000000
```

### Additional info:

Running `df -h` in the machine

```
worker01 [~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root       118G  7.4G  106G   7% /
/dev/loop0       46M   46M     0 100% /usr
none            3.8G  1.8M  3.8G   1% /etc
tmpfs           777M   11M  766M   2% /run
tmpfs           777M     0  777M   0% /tmp
dev              10M     0   10M   0% /dev
shm             3.8G     0  3.8G   0% /dev/shm
cgroup_root      10M     0   10M   0% /sys/fs/cgroup
shm              64M     0   64M   0% /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/e9af9d5e52635643fd501847aa61d0fe2ad0b5db1e882d962b7a939032de4a77/shm
shm              64M     0   64M   0% /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/0774840a8491b400fa8e3a8cd666ebd9998a5add8375aeeaaa3dc2316c0b510b/shm
shm              64M     0   64M   0% /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/c1b2263885f0417f8b02547882dae09a39115e712532c03efc381fdc6fcfc61b/shm
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/c1b2263885f0417f8b02547882dae09a39115e712532c03efc381fdc6fcfc61b/rootfs
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/0774840a8491b400fa8e3a8cd666ebd9998a5add8375aeeaaa3dc2316c0b510b/rootfs
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/e9af9d5e52635643fd501847aa61d0fe2ad0b5db1e882d962b7a939032de4a77/rootfs
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/0fb2db380d550fba34a2594bbc4e8d78a8f1bc16f3019414c584e129256d4b66/rootfs
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/f373a26928fda350297892461d40334cc06c983fc6de98f6733dbd0e1d3403b0/rootfs
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/08a634d5c06fa5b8b9c22ee9cf70a183091a42a051ff1c5a7f74a5fd6000db48/rootfs
shm              64M     0   64M   0% /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/62cbec9a3e9cf58367d6f8210ce950a9207c108940de010a0d1f346ca1b0c57d/shm
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/62cbec9a3e9cf58367d6f8210ce950a9207c108940de010a0d1f346ca1b0c57d/rootfs
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/b746bc2dc4a2175a6564f486e7b93b2943bfca8f9c843d28c98ecd8f5edeab91/rootfs
shm              64M     0   64M   0% /run/k3s/containerd/io.containerd.grpc.v1.cri/sandboxes/d23d8a289a312f37e559ddbf0b8f51927c747f9a9ec070bbf3a662f2832000ae/shm
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/d23d8a289a312f37e559ddbf0b8f51927c747f9a9ec070bbf3a662f2832000ae/rootfs
overlay         118G  7.4G  106G   7% /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/dfc5446792f59c8d4eacd5c3c632842a2cf9b6d88276f57c06888935d111caaf/rootfs
```

The pod has mounted the following (from the upstream Helm chart)

```
    Environment:
      HOSTIP:      (v1:status.hostIP)
      HOSTNAME:    (v1:spec.nodeName)
      HOSTIP:      (v1:status.hostIP)
      HOST_PROC:  /rootfs/proc
      HOST_SYS:   /rootfs/sys
    Mounts:
      /etc/telegraf from config (rw)
      /rootfs/proc from procro (ro)
      /rootfs/sys from sysro (ro)
      /var/run/docker.sock from docker-socket (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from telegraf-telegraf-ds-token-9sjvq (ro)
      /var/run/utmp from varrunutmpro (ro)
```
