### ISSUE TITLE
Buffer never decreases with high volume inputs

### ISSUE THREAD

**Issue by powersj** [influxdata/telegraf#9799]
### Overview

In scenarios where inputs fill the batch size before the flush interval is hit batches are continuously ready for writing. Due to changes in [this PR](https://github.com/influxdata/telegraf/commit/a6d2c4f254dbe9f7353961d892f8b91d907423ea) when a batch is written the ticker is also reset. As such the `ticker.Elapsed()` event is starved from ever triggering. The result is that a full write is never called, only a batch write.

### Data generation
I used [this shell script](https://paste.ubuntu.com/p/XsycvnqTDB/) to generate 1000 metrics at a time via the `exec` input below.

### Relevant telegraf.conf:

```toml
[agent]
  precision = "1ns"
  interval = "1s"
  flush_interval = "10s"
  metric_batch_size = 1500
  metric_buffer_limit = 50000
  round_interval = true
  debug = true
  quiet = false
  omit_hostname = true

[[inputs.exec]]
  commands = [
    "bash /home/$USER/echo_metrics.sh",
  ]
  data_format = "influx"

[[outputs.influxdb_v2]]
  urls = ["http://192.168.2.11:8086"]
  token = "<redacted>"
  organization = "local-testing"
  bucket = "lab"
```

### System info:

This affects Telegraf versions v1.18.0-rc1 and newer.

### Steps to reproduce:

1. Setup InfluxDB as output
2. Copy exec script to generate metrics
3. Copy config.toml configuration file
4. `./telegraf --config config.toml`
5. After letting run for 5-10 seconds, kill the connection to InfluxDB via `sudo systemctl stop influxdb; sleep 1; sudo systemctl start influxdb`
6. Observe the buffer fullness increase to ~10,000-15,000
7. Once InfluxDB is back up, observe if the buffer value ever decreases

### Expected behavior:

The `ticker.Elapsed()` event triggers periodically to allow for the writing of all data, including buffered data.

### Actual behavior:

The `ticker.Elapsed()` event never triggers and the Telegraf buffer never decreases.

### Additional info:

[Example of the issue](https://paste.ubuntu.com/p/r4NWRXCDDg/) with some additional [logging](https://paste.ubuntu.com/p/F6xB3yq6fx/) shows the batch ready event getting fired constantly. Notice that the ticker elapsed event never shows up.

Using [this patch](https://paste.ubuntu.com/p/vq2SwWnWzX/) to remove the ticker reset during a batch ready call, results in [this output](https://paste.ubuntu.com/p/jBBhhQfCtZ/). This shows the ticker elapsed event getting triggered periodically as expected, and the buffer going down after a loss of connectivity.
