### ISSUE TITLE
AWS EC2 Processor busts the DescribeTags request limit

### ISSUE THREAD

**Issue by Richard-Payne** [influxdata/telegraf#9839]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "10s"
  flush_interval = "10s"

[[inputs.net]]
  interfaces = ["eth0,docker0,lo"]
[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs"]
[[inputs.diskio]]
[[inputs.kernel]]
[[inputs.mem]]
[[inputs.processes]]
[[inputs.swap]]
[[inputs.system]]
[[inputs.netstat]]

[[processors.aws_ec2]]
    imds_tags = [
      "instanceId",
      "privateIp"
    ]
    ec2_tags = [
      "Name",
      "EnvironmentName",
      "service_type"
    ]
```

### System info:

Telegraf v1.18
Amazon Linux 2

### Steps to reproduce:

Deploy the above Telegraf config to a few different Linux hosts and leave to run.

### Expected behavior:

Telegraf caches the tag lookups to avoid flooding the AWS api.

### Actual behavior:

Telegraf floods the AWS api resulting in metric gathering stopping with the following error being repeated over and over in the log:

2021-09-29T14:45:20Z E! [processors.aws_ec2] Error during EC2 DescribeTags: operation error EC2: DescribeTags, retry quota exceeded, 4 available, 5 requested
