### ISSUE TITLE
input.cisco_telemetry_mdt: It will miss part of the content when monitoring sr policy information

### ISSUE THREAD

**Issue by xinmos** [influxdata/telegraf#9840]
### Relevant telegraf.conf:

```toml
[[outputs.file]]
  ## Files to write to, "stdout" is a specially handled file.
  files = ["stdout", "/tmp/metrics.out"]
  use_batch_format = true
  rotation_interval = "7d"
  rotation_max_archives = 5
  data_format = "json"
  json_timestamp_units = "1ms"

[[inputs.cisco_telemetry_mdt]]
  transport = "tcp"
  service_address = ":5432"
```
### XR config:
```toml
telemetry model-driven  
 destination-group DGroup1  
   address family ipv4 172.30.8.4 port 5432  
   encoding self-describing-gpb  
   protocol tcp
  !
 !
 sensor-group SGroup1
  sensor-path Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy
 !  
 subscription Sub1  
  sensor-group-id SGroup1 sample-interval 30000  
  destination-id DGroup1   
```

### System info:

Telegraf version:1.19.3

### Steps to reproduce:

when i get the data:
    "candidate_path/segment_list/hop/local_address/af_name": "ipv4",
    "candidate_path/segment_list/hop/local_address/ipv4": "1.1.1.3",
     "candidate_path/segment_list/hop/remote_address/af_name": "ipv4",
     "candidate_path/segment_list/hop/remote_address/ipv4": "1.1.1.4",

we know the segment_list/hop not just have one piece of data, it should be a list or object, and not a sample string. but telegraf just gave me the last one. The same things happen in the "event_buffer/event_message".

### Expected behavior:

Make expandable data items like "segment_list" appear as dict or list instead of string
