### ISSUE TITLE
Internet Speed Monitor Input Plugin - fetching server list failed: unable to retrieve server list

### ISSUE THREAD

**Issue by phantomski77** [influxdata/telegraf#9852]
### Relevant telegraf.conf:

```toml
# Monitors internet speed in the network
[[inputs.internet_speed]]
  ## Sets if runs file download test
  ## Default: false
  enable_file_download = false
  interval = "30m"
```

### System info:

**System:** Raspberry Pi 4 Model B Rev 1.4 8GB
**OS/Kernel:** Ubuntu 21.04 (Linux 5.11.0-1019-raspi) arm64 arch
**Version:** TELEGRAF_VERSION 1.20.0 from hub.docker.com tag `telegraf:1.20.0`
### Docker
Docker CE 20.10.8
Separate Overlay network for InfluxDB 2.0.8 and Telegraf 1.20.0.
All other plugins and Telegraf container able to communicate with the internet.

### Steps to reproduce:

1. Add plugin in `telegraf.conf` as per code above
2. Restart `telegraf` container.
3. Wait for interval to execute the plugin
4. No data stored in InfluxDB and error message produced

### Expected behavior:

Internet Speed measured by plugin and stored in InfluxDB database.
### Actual behavior:
**Telegraf container log:**
```
2021-10-03T18:00:00Z E! [inputs.internet_speed] Error in plugin: fetching server list failed: unable to retrieve server list
```
The same error is produced on every interval attempt.

### Additional info:
When I've used the plugin without `interval` parameter (so defaulting to agent's 10s) or with shorter duration (5m) during initial experiments, it was working fine for about half an hour. Then it suddenly stopped working without any other configuration changes. Other plugins are still working fine collecting other local system, local network and internet based metrics. Restarting telegraf container, InfluxDB container or the whole system doesn't improve the situation, which now lasts for about 24 hours.
