### ISSUE TITLE
typeperf "\Process(*)\% Processor time" differs from win_perf_counters

### ISSUE THREAD

**Issue by rbucchi** [influxdata/telegraf#9882]
### Relevant telegraf.conf:

```toml
[agent]
  interval = "30s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = false


###############################################################################
#                            OUTPUT PLUGINS                                   #
###############################################################################

# Configuration for sending metrics to InfluxDB
[[outputs.influxdb]]
  urls = ["https://192.168.41.241:8086"]
  database = "telegraf"
  skip_database_creation = true
  retention_policy = "six_weeks"
  insecure_skip_verify = true

###############################################################################
#                            INPUT PLUGINS                                    #
###############################################################################
# Windows Performance Counters plugin.
# These are the recommended method of monitoring system metrics on windows,
# as the regular system plugins (inputs.cpu, inputs.mem, etc.) rely on WMI,
# which utilize more system resources.
#
# See more configuration examples at:
#   https://github.com/influxdata/telegraf/tree/master/plugins/inputs/win_perf_counters

[[inputs.win_perf_counters]]
  [[inputs.win_perf_counters.object]]
    # Processor usage, alternative to native, reports on a per core.
    ObjectName = "Processor"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Interrupt Time",
      "% Privileged Time",
      "% User Time",
      "% Processor Time",
      "% DPC Time",
    ]
    Measurement = "win_cpu"
    # Set to true to include _Total instance when querying for all (*).
    IncludeTotal=true

  [[inputs.win_perf_counters.object]]
    # Disk times and queues
    ObjectName = "LogicalDisk"
    Instances = ["*"]
    Counters = [
      "% Idle Time",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
      "% Free Space",
      "Current Disk Queue Length",
      "Free Megabytes",
    ]
    Measurement = "win_disk"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    ObjectName = "PhysicalDisk"
    Instances = ["*"]
    Counters = [
      "Disk Read Bytes/sec",
      "Disk Write Bytes/sec",
      "Current Disk Queue Length",
      "Disk Reads/sec",
      "Disk Writes/sec",
      "% Disk Time",
      "% Disk Read Time",
      "% Disk Write Time",
    ]
    Measurement = "win_diskio"

  [[inputs.win_perf_counters.object]]
    ObjectName = "Network Interface"
    Instances = ["*"]
    Counters = [
      "Bytes Received/sec",
      "Bytes Sent/sec",
      "Packets Received/sec",
      "Packets Sent/sec",
      "Packets Received Discarded",
      "Packets Outbound Discarded",
      "Packets Received Errors",
      "Packets Outbound Errors",
    ]
    Measurement = "win_net"

  [[inputs.win_perf_counters.object]]
    ObjectName = "System"
    Counters = [
      "Context Switches/sec",
      "System Calls/sec",
      "Processor Queue Length",
      "System Up Time",
	  "Processes",
    ]
    Instances = ["------"]
    Measurement = "win_system"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    # Example query where the Instance portion must be removed to get data back,
    # such as from the Memory object.
    ObjectName = "Memory"
    Counters = [
      "Available Bytes",
      "Cache Faults/sec",
      "Demand Zero Faults/sec",
      "Page Faults/sec",
      "Pages/sec",
      "Transition Faults/sec",
      "Pool Nonpaged Bytes",
      "Pool Paged Bytes",
      "Standby Cache Reserve Bytes",
      "Standby Cache Normal Priority Bytes",
      "Standby Cache Core Bytes",
    ]
    # Use 6 x - to remove the Instance bit from the query.
    Instances = ["------"]
    Measurement = "win_mem"
    # Set to true to include _Total instance when querying for all (*).
    #IncludeTotal=false

  [[inputs.win_perf_counters.object]]
    # Example query where the Instance portion must be removed to get data back,
    # such as from the Paging File object.
    ObjectName = "Paging File"
    Counters = [
      "% Usage",
    ]
    Instances = ["_Total"]
    Measurement = "win_swap"


  [[inputs.win_perf_counters.object]]
    # Process metrics
    ObjectName = "Process"
    Counters = [
      "% Processor Time",
	  "% User Time",
	  "Elapsed Time",
      "Handle Count",
      "Private Bytes",
      "Thread Count",
      "Virtual Bytes",
      "Working Set"
      ]
    Instances = ["*"]
    Measurement = "win_proc"
    IncludeTotal=true #Set to true to include _Total instance when querying for all (*).

  [[inputs.win_perf_counters.object]]
    # HTTP Service request queues in the Kernel before being handed over to User Mode.
    ObjectName = "HTTP Service Request Queues"
    Instances = ["*"]
    Counters = ["CurrentQueueSize","RejectedRequests"]
    Measurement = "win_http_queues"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).

  [[inputs.win_perf_counters.object]]
    # IIS, ASP.NET Applications
    ObjectName = "ASP.NET Applications"
    Counters = ["Cache Total Entries","Cache Total Hit Ratio","Cache Total Turnover Rate","Output Cache Entries","Output Cache Hits","Output Cache Hit Ratio","Output Cache Turnover Rate","Compilations Total","Errors Total/Sec","Pipeline Instance Count","Requests Executing","Requests in Application Queue","Requests/Sec"]
    Instances = ["*"]
    Measurement = "win_aspnet_app"
    IncludeTotal=true #Set to true to include _Total instance when querying for all (*).

  [[inputs.win_perf_counters.object]]
    # IIS, ASP.NET
    ObjectName = "ASP.NET"
    Counters = ["Application Restarts","Request Wait Time","Requests Current","Requests Queued","Requests Rejected"]
    Instances = ["*"]
    Measurement = "win_aspnet"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).

  [[inputs.win_perf_counters.object]]
    # IIS, Web Service
    ObjectName = "Web Service"
    Counters = ["Get Requests/sec","Post Requests/sec","Connection Attempts/sec","Current Connections","ISAPI Extension Requests/sec"]
    Instances = ["*"]
    Measurement = "win_websvc"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).

  [[inputs.win_perf_counters.object]]
    # Web Service Cache / IIS
    ObjectName = "Web Service Cache"
    Counters = ["URI Cache Hits %","Kernel: URI Cache Hits %","File Cache Hits %"]
    Instances = ["*"]
    Measurement = "win_websvc_cache"
    #IncludeTotal=false #Set to true to include _Total instance when querying for all (*).
# Windows system plugins using WMI (disabled by default, using
# win_perf_counters over WMI is recommended)

```

### System info:

Monitoring machine: 

monitor@moritoring:~$ influxd version
InfluxDB v1.8.4 (git: 1.8 bc8ec4384eed25436d31045f974bf39f3310fa3c)
monitor@moritoring:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Monitored machine(s):
PS C:\Windows\system32> cmd ?
Microsoft Windows [Versione 6.3.9600]
(c) 2013 Microsoft Corporation. Tutti i diritti riservati.
Windows Server 2012 R2

C:\Program Files\Telegraf>telegraf.exe version
Telegraf 1.20.0 (git: HEAD f489cff3)

### Steps to reproduce:

1. Collecting win_perf_counters ObjectName = Process, % Processor Time only for some specific process instances, collect data which seems to be false and repeated over time

example:

on monitored machine (timezone CEST, GMT+2. VM in Italian)
```powershell
PS C:\Windows\system32> typeperf "\Processo(sqlceip)\% Tempo processo"
...
"10/07/2021 07:20:38.494","0.000000"
"10/07/2021 07:20:39.516","0.000000"
"10/07/2021 07:20:40.547","0.000000"
"10/07/2021 07:20:41.553","0.000000"
"10/07/2021 07:20:42.568","0.000000"
"10/07/2021 07:20:43.576","0.000000"
"10/07/2021 07:20:44.582","0.000000"
"10/07/2021 07:20:45.593","0.000000"
"10/07/2021 07:20:46.710","0.000000"
"10/07/2021 07:20:47.712","0.000000"
"10/07/2021 07:20:48.731","0.000000"
"10/07/2021 07:20:49.740","0.000000"
"10/07/2021 07:20:50.753","0.000000"
"10/07/2021 07:20:51.759","0.000000"
"10/07/2021 07:20:52.762","0.000000"
"10/07/2021 07:20:53.771","0.000000"
"10/07/2021 07:20:54.781","0.000000"
"10/07/2021 07:20:55.792","0.000000"
"10/07/2021 07:20:56.797","0.000000"
"10/07/2021 07:20:57.803","0.000000"
"10/07/2021 07:20:58.805","0.000000"
"10/07/2021 07:20:59.808","0.000000"
"10/07/2021 07:21:00.821","0.000000"
"10/07/2021 07:21:01.831","0.000000"
"10/07/2021 07:21:02.837","0.000000"
"10/07/2021 07:21:03.845","0.000000"
"10/07/2021 07:21:04.874","0.000000"
"10/07/2021 07:21:05.885","0.000000"
"10/07/2021 07:21:06.897","0.000000"
"10/07/2021 07:21:07.907","0.000000"
"10/07/2021 07:21:08.913","0.000000"
"10/07/2021 07:21:09.923","0.000000"
"10/07/2021 07:21:10.928","0.000000"
"10/07/2021 07:21:11.934","0.000000"
"10/07/2021 07:21:12.937","0.000000"
"10/07/2021 07:21:13.944","0.000000"
"10/07/2021 07:21:14.946","0.000000"
"10/07/2021 07:21:15.961","0.000000"
"10/07/2021 07:21:16.967","0.000000"
"10/07/2021 07:21:17.982","0.000000"
"10/07/2021 07:21:18.987","0.000000"
"10/07/2021 07:21:19.998","0.000000"
"10/07/2021 07:21:21.006","0.000000"
"10/07/2021 07:21:22.016","0.000000"
"10/07/2021 07:21:23.044","0.000000"
"10/07/2021 07:21:24.050","0.000000"
"10/07/2021 07:21:25.136","0.000000"
"10/07/2021 07:21:26.159","0.000000"
"10/07/2021 07:21:27.169","0.000000"
"10/07/2021 07:21:28.176","0.000000"
"10/07/2021 07:21:29.179","0.000000"
"10/07/2021 07:21:30.180","0.000000"
"10/07/2021 07:21:31.194","0.000000"
"10/07/2021 07:21:32.198","0.000000"
"10/07/2021 07:21:33.206","0.000000"
"10/07/2021 07:21:34.212","0.000000"
"10/07/2021 07:21:35.220","0.000000"
"10/07/2021 07:21:36.234","0.000000"
"10/07/2021 07:21:37.234","0.000000"
"10/07/2021 07:21:38.238","0.000000"
"10/07/2021 07:21:39.242","0.000000"
"10/07/2021 07:21:40.254","0.000000"
"10/07/2021 07:21:41.261","0.000000"
"10/07/2021 07:21:42.275","0.000000"
"10/07/2021 07:21:43.287","0.000000"
"10/07/2021 07:21:44.300","0.000000"
"10/07/2021 07:21:45.311","0.000000"
"10/07/2021 07:21:46.325","0.000000"
"10/07/2021 07:21:47.339","0.000000"
"10/07/2021 07:21:48.344","0.000000"
"10/07/2021 07:21:49.359","0.000000"
"10/07/2021 07:21:50.368","0.000000"
"10/07/2021 07:21:51.383","0.000000"
"10/07/2021 07:21:52.386","0.000000"
"10/07/2021 07:21:53.387","0.000000"
"10/07/2021 07:21:54.399","0.000000"
"10/07/2021 07:21:55.410","0.000000"
"10/07/2021 07:21:56.419","0.000000"
"10/07/2021 07:21:57.420","0.000000"
"10/07/2021 07:21:58.423","0.000000"
"10/07/2021 07:21:59.429","0.000000"
...
"10/07/2021 07:44:52.069","0.000000"
"10/07/2021 07:44:53.079","0.000000"
"10/07/2021 07:44:54.084","0.000000"
"10/07/2021 07:44:55.087","0.000000"
"10/07/2021 07:44:56.095","0.000000"
"10/07/2021 07:44:57.110","0.000000"
"10/07/2021 07:44:58.117","0.000000"
"10/07/2021 07:44:59.128","0.000000"
"10/07/2021 07:45:00.133","0.000000"
"10/07/2021 07:45:01.134","0.000000"
"10/07/2021 07:45:02.147","0.000000"
"10/07/2021 07:45:03.148","0.000000"
"10/07/2021 07:45:04.154","0.000000"
"10/07/2021 07:45:05.164","0.000000"
"10/07/2021 07:45:06.178","0.000000"
"10/07/2021 07:45:07.190","0.000000"
"10/07/2021 07:45:08.196","0.000000"
"10/07/2021 07:45:09.200","0.000000"
"10/07/2021 07:45:10.211","0.000000"
"10/07/2021 07:45:11.221","0.000000"
"10/07/2021 07:45:12.226","0.000000"
"10/07/2021 07:45:13.236","0.000000"
"10/07/2021 07:45:14.242","0.000000"
"10/07/2021 07:45:15.245","0.000000"
"10/07/2021 07:45:16.256","0.000000"
"10/07/2021 07:45:17.268","0.000000"
"10/07/2021 07:45:18.277","0.000000"
"10/07/2021 07:45:19.289","0.000000"
"10/07/2021 07:45:20.301","0.000000"
"10/07/2021 07:45:21.315","0.000000"
"10/07/2021 07:45:22.320","0.000000"
"10/07/2021 07:45:23.327","0.000000"
"10/07/2021 07:45:24.334","0.000000"
"10/07/2021 07:45:25.337","0.000000"
"10/07/2021 07:45:26.342","0.000000"
"10/07/2021 07:45:27.357","0.000000"
"10/07/2021 07:45:28.365","0.000000"
"10/07/2021 07:45:29.373","0.000000"
"10/07/2021 07:45:30.378","0.000000"
"10/07/2021 07:45:31.386","0.000000"
"10/07/2021 07:45:32.399","0.000000"
"10/07/2021 07:45:33.415","0.000000"
"10/07/2021 07:45:34.420","0.000000"
"10/07/2021 07:45:35.435","0.000000"
"10/07/2021 07:45:36.440","0.000000"
"10/07/2021 07:45:37.447","0.000000"
"10/07/2021 07:45:38.452","0.000000"
"10/07/2021 07:45:39.466","0.000000"
"10/07/2021 07:45:40.476","0.000000"
"10/07/2021 07:45:41.476","0.000000"
"10/07/2021 07:45:42.491","0.000000"
"10/07/2021 07:45:43.496","0.000000"
"10/07/2021 07:45:44.508","0.000000"
"10/07/2021 07:45:45.511","0.000000"
"10/07/2021 07:45:46.521","0.000000"
"10/07/2021 07:45:47.536","0.000000"
"10/07/2021 07:45:48.540","0.000000"
"10/07/2021 07:45:49.551","0.000000"
"10/07/2021 07:45:50.559","0.000000"
"10/07/2021 07:45:51.569","0.000000"
"10/07/2021 07:45:52.574","0.000000"
"10/07/2021 07:45:53.581","0.000000"
"10/07/2021 07:45:54.594","0.000000"
"10/07/2021 07:45:55.595","0.000000"
"10/07/2021 07:45:56.601","0.000000"
"10/07/2021 07:45:57.676","0.000000"
"10/07/2021 07:45:58.682","0.000000"
"10/07/2021 07:45:59.688","0.000000"
"10/07/2021 07:46:00.688","0.000000"
"10/07/2021 07:46:01.692","0.000000"
"10/07/2021 07:46:02.705","0.000000"
"10/07/2021 07:46:03.712","0.000000"
"10/07/2021 07:46:04.717","0.000000"
"10/07/2021 07:46:05.727","0.000000"
"10/07/2021 07:46:06.727","0.000000"
"10/07/2021 07:46:07.741","0.000000"
"10/07/2021 07:46:08.751","0.000000"
"10/07/2021 07:46:09.752","0.000000"
"10/07/2021 07:46:10.761","0.000000"
"10/07/2021 07:46:11.765","0.000000"
"10/07/2021 07:46:12.773","0.000000"
"10/07/2021 07:46:13.785","0.000000"
"10/07/2021 07:46:14.785","0.000000"
"10/07/2021 07:46:15.791","0.000000"
"10/07/2021 07:46:16.793","0.000000"
"10/07/2021 07:46:17.797","0.000000"
"10/07/2021 07:46:18.801","0.000000"
"10/07/2021 07:46:19.803","0.000000"
"10/07/2021 07:46:20.809","0.000000"
"10/07/2021 07:46:21.814","0.000000"
"10/07/2021 07:46:22.829","0.000000"
"10/07/2021 07:46:23.837","0.000000"
"10/07/2021 07:46:24.842","0.000000"
"10/07/2021 07:46:25.857","0.000000"
"10/07/2021 07:46:26.868","0.000000"
"10/07/2021 07:46:27.869","0.000000"
"10/07/2021 07:46:28.871","0.000000"
"10/07/2021 07:46:29.883","0.000000"
"10/07/2021 07:46:30.886","0.000000"
"10/07/2021 07:46:31.898","0.000000"
"10/07/2021 07:46:32.905","0.000000"
"10/07/2021 07:46:33.911","0.000000"
"10/07/2021 07:46:34.914","0.000000"
"10/07/2021 07:46:35.928","0.000000"
"10/07/2021 07:46:36.937","0.000000"
"10/07/2021 07:46:37.951","0.000000"
"10/07/2021 07:46:38.957","0.000000"
"10/07/2021 07:46:39.966","0.000000"
"10/07/2021 07:46:40.972","0.000000"
"10/07/2021 07:46:41.978","0.000000"
"10/07/2021 07:46:42.993","0.000000"
"10/07/2021 07:46:44.001","0.000000"
"10/07/2021 07:46:45.011","0.000000"
"10/07/2021 07:46:46.019","0.000000"
"10/07/2021 07:46:47.024","0.000000"
"10/07/2021 07:46:48.039","0.000000"
"10/07/2021 07:46:49.043","0.000000"
"10/07/2021 07:46:50.058","0.000000"
"10/07/2021 07:46:51.069","0.000000"
"10/07/2021 07:46:52.079","0.000000"
"10/07/2021 07:46:53.087","0.000000"
"10/07/2021 07:46:54.091","0.000000"
"10/07/2021 07:46:55.104","0.000000"
"10/07/2021 07:46:56.109","0.000000"
"10/07/2021 07:46:57.115","0.000000"
"10/07/2021 07:46:58.121","0.000000"
"10/07/2021 07:46:59.133","0.000000"
"10/07/2021 07:47:00.134","0.000000"
```

while on Monitoring machine (time in UTC)

```
> select time, Percent_Processor_Time, instance from win_proc where instance = 'sqlceip' AND host = 'SACMIDB1' AND time > '2021-10-07T05:20:00Z' AND time <= '2021-10-07T07:30:00Z'                                        name: win_proc
time                 Percent_Processor_Time instance
----                 ---------------------- --------
2021-10-07T05:20:30Z 574.0712280273438      sqlceip
2021-10-07T05:21:01Z 0                      sqlceip
2021-10-07T05:21:30Z 600.301025390625       sqlceip
2021-10-07T05:22:00Z 574.47802734375        sqlceip
2021-10-07T05:22:31Z 0                      sqlceip
2021-10-07T05:23:00Z 600.17138671875        sqlceip
2021-10-07T05:23:30Z 574.6160888671875      sqlceip
2021-10-07T05:24:01Z 0                      sqlceip
2021-10-07T05:24:30Z 600.80712890625        sqlceip
2021-10-07T05:25:00Z 574.4966430664062      sqlceip
2021-10-07T05:25:31Z 0                      sqlceip
2021-10-07T05:26:00Z 601.8507690429688      sqlceip
2021-10-07T05:26:30Z 574.0886840820312      sqlceip
2021-10-07T05:27:01Z 0                      sqlceip
2021-10-07T05:27:30Z 601.477783203125       sqlceip
2021-10-07T05:28:00Z 574.1615600585938      sqlceip
2021-10-07T05:28:31Z 0                      sqlceip
2021-10-07T05:29:00Z 600.8656005859375      sqlceip
2021-10-07T05:29:30Z 574.3079833984375      sqlceip
2021-10-07T05:30:01Z 0                      sqlceip
2021-10-07T05:30:30Z 600.4652709960938      sqlceip
2021-10-07T05:31:00Z 574.3005981445312      sqlceip
2021-10-07T05:31:31Z 0                      sqlceip
2021-10-07T05:32:00Z 600.1180419921875      sqlceip
2021-10-07T05:32:30Z 574.2723388671875      sqlceip
2021-10-07T05:33:01Z 0                      sqlceip
2021-10-07T05:33:30Z 601.1929931640625      sqlceip
2021-10-07T05:34:00Z 574.247802734375       sqlceip
2021-10-07T05:34:31Z 0                      sqlceip
2021-10-07T05:35:00Z 600.0116577148438      sqlceip
2021-10-07T05:35:30Z 574.385498046875       sqlceip
2021-10-07T05:36:01Z 0                      sqlceip
2021-10-07T05:36:30Z 602.0765991210938      sqlceip
2021-10-07T05:37:00Z 574.4107666015625      sqlceip
2021-10-07T05:38:00Z 601.3425903320312      sqlceip
2021-10-07T05:38:30Z 574.1731567382812      sqlceip
2021-10-07T05:39:01Z 0                      sqlceip
2021-10-07T05:39:30Z 602.6521606445312      sqlceip
2021-10-07T05:40:00Z 574.8468017578125      sqlceip
2021-10-07T05:40:31Z 0                      sqlceip
2021-10-07T05:41:00Z 601.8409423828125      sqlceip
2021-10-07T05:41:30Z 574.1224365234375      sqlceip
2021-10-07T05:42:01Z 0                      sqlceip
2021-10-07T05:42:30Z 601.3575439453125      sqlceip
2021-10-07T05:43:31Z 0                      sqlceip
2021-10-07T05:44:00Z 600.588623046875       sqlceip
2021-10-07T05:44:30Z 574.266357421875       sqlceip
2021-10-07T05:45:01Z 0                      sqlceip
2021-10-07T05:45:30Z 602.1854248046875      sqlceip
2021-10-07T05:46:00Z 574.4557495117188      sqlceip
2021-10-07T05:46:31Z 0                      sqlceip
```

That's a portion of 'false' data, because I collected over night `sqlceip` % process time which stay always in the same pattern (typeperf collect 0 after I disabled it, while telegraf keep collect around 600% (the VM have 6 CPU, so should be around 100%).

Same behaviour with `telegraf` instance or `WMIPrvSE`.

### Expected behavior:

typeperf "\Processo(*)\% Tempo processore" to be the same in influxdb instance

### Actual behavior:

typeperf "\Processo(*)\% Tempo processore" collect 0, while in influxdb db values are different.

### Additional info:

Processor Time (Tempo processore in italian) from windows performance monitor it seems to be calculated for each logical processor (and multithreading, but documentation is rare and spare) https://social.technet.microsoft.com/wiki/contents/articles/12984.understanding-processor-processor-time-and-process-processor-time.aspx

could be related to https://github.com/influxdata/telegraf/issues/4453
