### ISSUE TITLE
rabbitmq plugin field type conflict after version upgrade

### ISSUE THREAD

**Issue by dschuldt** [influxdata/telegraf#9930]
Hello,

first, thank you all for telegraf development and your support!

After upgrading the official docker image to the latest version, we experience issues with the rabbitmq plugin. Please have a look at the actual behaviour below. 

Has the field type changed? How can we fix this error?

Thank you in advance!

### Relevant telegraf.conf:
```toml
[[inputs.rabbitmq]]
      url = "http://rabbitmq_endpoint:15672"
      header_timeout = "5s"
      client_timeout = "5s"
      username = "username"
      password = "password"
      metric_exclude = ["federation"]
```

### System info:

telegraf:1.20.2-alpine Image from Docker Hub
InfluxDB 1.9.5

### Steps to reproduce:

1. Update Telegraf from 1.18 to 1.20.2

### Expected behavior:
RabbitMQ Metrics are still delivered successfully to Influx

### Actual behavior:

2021-10-14T08:50:20Z E! [outputs.influxdb] When writing to [http://influx_endpoint:8086]: received error write failed: error code 1: write shard 45313: partial write: field type conflict: input field "io_read_avg_time" on measurement "rabbitmq_node" is type float, already exists as type integer dropped=2; discarding points
