### ISSUE TITLE
internet_speed input plugin not collecting/reporting latency

### ISSUE THREAD

**Issue by donmahallem** [influxdata/telegraf#9931]
### Relevant telegraf.conf:

```toml

[global_tags]

[agent]
  interval = "60s"
  round_interval = true

  metric_batch_size = 1000

  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "60s"
  flush_jitter = "30s"
  precision = ""
  debug = true
  omit_hostname = false
[[inputs.internet_speed]]
  interval = "60s"
  ## servers to query
[[outputs.file]]
  files = ["stdout"]

```

### System info:

Telegraf 1.20

Tested on Windows 10 and current Raspbian
### Docker
```yaml

version: '3.1'
services:
  telegraf:
    container_name: telegraf
    image: telegraf:1.20
    volumes:
      - ./telegraf_pi_speedtest.conf:/etc/telegraf/telegraf.conf:ro
      - telegraf_test:/telegraf
volumes:
  telegraf_test:

```
### Steps to reproduce:

1. Run telegraf with the provided config above

### Expected behavior:

Should report latency as described in the [plugins readme](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internet_speed)
### Actual behavior:

Only reports upload and download speed. No latency

### Additional info:
A sample from my logs. No errors reported

```text
telegraf  | 2021-10-14T16:03:00Z D! [inputs.internet_speed] Starting Speed Test
telegraf  | 2021-10-14T16:03:00Z D! [inputs.internet_speed] Running Ping...
telegraf  | 2021-10-14T16:03:01Z D! [inputs.internet_speed] Running Download...
telegraf  | 2021-10-14T16:03:07Z D! [inputs.internet_speed] Running Upload...
telegraf  | 2021-10-14T16:03:33Z D! [inputs.internet_speed] Test finished.
telegraf  | internet_speed,host=any upload=1.7020006070397913,download=54.815106717946776 1634227340000000000
telegraf  | 2021-10-14T16:03:19Z D! [outputs.file] Wrote batch of 1 metrics in 47.1µs
telegraf  | 2021-10-14T16:03:19Z D! [outputs.file] Buffer fullness: 0 / 10000 metrics
```
