### ISSUE TITLE
http plugin doesn't collect all json objects

### ISSUE THREAD

**Issue by Levarix** [influxdata/telegraf#9935]
### Relevant telegraf.conf:
```toml
[global_tags]
    customer = "<customer>"
    product = "<product>"
    environment = "<env>"


# Configuration for telegraf agent
[agent]
    interval = "30s"
    debug = false
    hostname = "<hostname>"
    round_interval = true
    flush_interval = "30s"
    flush_jitter = "0s"
    collection_jitter = "0s"
    metric_batch_size = 1000
    metric_buffer_limit = 10000
    quiet = false
    logfile = ""
    omit_hostname = false

###############################################################################
#                                  OUTPUTS                                    #
###############################################################################

[[outputs.file]]
  files = ["stdout"]

###############################################################################
#                                  INPUTS                                     #
###############################################################################

###############################################################################
#                                  PROCESSORS                                    #
###############################################################################
```

### Relevant telegraf.d/json.conf:

```toml
[[inputs.http]]
  urls = ["<url>"]
  timeout = "30"
  method = "POST"
  data_format = "json"
  body = "{'PackageId': <packageId>, 'UserName': '<email>', 'Password': '<password>'}"
  headers = {"Content-Type" = "application/json"}
```

### Requested JSON
```json
{
  "Header": {
    "HttpStatusCode": 200
  },
  "Body": {
    "Consumers": [
      "\"connection_name\": \"<ip>:<port> -> <ip>:<port>\" - ConsumerTag : <tag>"
    ],
    "NumberMessagesInQueue": 0,
    "MessagesPerSecond": 1.4,
    "IsDistributionOn": true
  }
}
```
Metric:
```
http,customer=<customer>,environment=<env>,host=<host>,product=<product>,url=<url> Body_NumberMessagesInQueue=1,Body_MessagesPerSecond=0.2,Header_HttpStatusCode=200 1634285130000000000
```
### System info:
The problem exists on telegraf run directly on a host and into a docker container
Telegraf version: 1.20.2
Ubuntu 20.04
Docker: 20.10.8

### Docker

```docker run --network=host -v $PWD/telegraf:/etc/telegraf:ro bitnami/telegraf:1.20.2 --config-directory /etc/telegraf```

### Steps to reproduce:

1. Just run telegraf with http plugin

### Expected behavior:

Consumers list and IsDistributionOn available into metric to monitor if any consumer is connected

### Actual behavior:

Consumers list and IsDistributionOn don't available into metric
