### ISSUE TITLE
proxmox plugin - [inputs.proxmox] Error getting VM curent VM status: json: cannot unmarshal number into Go struct field VMStat.data.vmid of type string

### ISSUE THREAD

**Issue by jrhbcn** [influxdata/telegraf#9938]
Trying to run the proxmox plugin in a proxmox 7.0-13 node results in the following error:

```
[inputs.proxmox] Error getting VM curent VM status: json: cannot unmarshal number into Go struct field VMStat.data.vmid of type string
[inputs.proxmox] Error getting VM stats: %vjson: cannot unmarshal number into Go struct field VMStat.data.vmid of type string
```

### Relevant telegraf.conf:
```toml
[[inputs.proxmox]]
  base_url = "https://192.168.*.*:8006/api2/json"
  api_token = "telegraf@pam!monitoring=****"
  node_name = "pve"
  insecure_skip_verify = true
  response_timeout = "5s"
```

### System info:

Telegraf is running inside a docker container (works perfectly for docker plugin). Currently using the following docker-compose file:
```
telegraf:  
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
```

### Steps to reproduce:

Using the above config on a proxmox 7.0-13 node throws the above error.

### Expected behavior:

promox monitor info is read by telegraf and send to influxdb.

### Actual behavior:

Throws error above.

### Additional info:

proxmox seems to be setup correctly as the following command returns a valid json:

```
curl -k -H 'Authorization: PVEAPIToken=telegraf@pam!monitoring=*****' https://192.168.*.*:8006/api2/json/nodes/pve
```
