### ISSUE TITLE
Snmp - Support for custom tags

### ISSUE THREAD

**Issue by wgrcunha** [influxdata/telegraf#997]
Hello,

Currently we use the same telegraf instance to monitor "n" snmp devices, will be good if we can set custom tags per host, something like this:

[[inputs.snmp.host]]
     address = "ip:161"
     tag_foo = "bar"

Is possible to implement it?

Thanks!

**Comment by joelsdc** [comment]
+1 on this. It would be very useful.

**Comment by sparrc** [comment]
this is now available in 1.0 RC 1 with the new SNMP plugin, please see here to download the latest version: https://github.com/influxdata/telegraf#linux-deb-and-rpm-packages, and [the changelog](https://github.com/influxdata/telegraf/blob/master/CHANGELOG.md) for details on the new SNMP plugin.

**Comment by osiris123d** [comment]
Are you sure you can do Custom Tags with the SNMP input model now like what wgrcunha shows above as an example?  I don't see any documentation of it.

**Comment by danielnelson** [comment]
@osiris123d It looks like this issue probably shouldn't have been closed, as you can't set static tags on a per agent basis.  What you can do now, and I think this is what most people needed, is something like in this example where you can apply a snmp field as a tag:
```toml
[[inputs.snmp]]
  agents = [ "127.0.0.1:161" ]
  version = 2
  community = "public"

  [[inputs.snmp.field]]
    oid = "TEST::hostname"
    is_tag = true

  [[inputs.snmp.table]]
    oid = "TEST::testTable"
    inherit_tags = "hostname"
```

If you are really after static tags, keep an eye on #3773 which should give you what you are looking for.
